async function heartbeat(){if(!token||!context?.source?.public_id||!liveClientSessionId)return;const room=liveRoomParams();try{const j=await api('/api/extension.php?action=presence',{method:'POST',body:JSON.stringify({source:context.source.public_id,mode:$('#presence').value,client_session_id:liveClientSessionId,...room})});renderPresence(j.data);return j.data;}catch(e){return null;}}
function renderPresence(d){$('#liveStats').textContent=`${d.total||0} people here now · ${d.following_visible||0} you follow`;$('#presenceCount').textContent=(d.total||0)+' here';const named=(d.visible||[]).map(p=>`<span class="person">${esc(p.is_self?'You':p.display_name)}${p.following?' · following':''}</span>`);const cloaked=(d.cloaked||[]).map(p=>`<span class="person cloaked">${esc(p.is_self?'You · cloaked':p.alias||'Cloaked participant')}</span>`);$('#livePeople').innerHTML=[...named,...cloaked].join('');}
async function loadLiveRooms(){if(!token)return;try{const j=await api('/api/extension.php?action=live_rooms');const teams=j.data.teams||[],projects=j.data.projects||[];let html='<option value="public">Public · this source</option>';if(teams.length)html+='<optgroup label="Teams">'+teams.map(t=>`<option value="team:${esc(t.public_id)}">Team · ${esc(t.name)}</option>`).join('')+'</optgroup>';if(projects.length)html+='<optgroup label="Research">'+projects.map(p=>`<option value="project:${esc(p.public_id)}">Research · ${esc(p.title)}${p.can_post?'':' · read only'}</option>`).join('')+'</optgroup>';$('#liveRoom').innerHTML=html;const values=[...$('#liveRoom').options].map(o=>o.value);$('#liveRoom').value=values.includes(liveRoomSelection)?liveRoomSelection:'public';liveRoomSelection=$('#liveRoom').value;await chrome.storage.local.set({liveRoomSelection});}catch(e){$('#liveStats').textContent=e.message||'Unable to load Live rooms';}}
function liveRoomParams(){const v=$('#liveRoom')?.value||liveRoomSelection||'public';if(v.startsWith('team:'))return{room_type:'team',room_id:v.slice(5)};if(v.startsWith('project:'))return{room_type:'project',room_id:v.slice(8)};return{room_type:'public',room_id:null};}
function liveCurrentKey(){const r=liveRoomParams();return [context?.source?.public_id||'',r.room_type,r.room_id||''].join('|');}
function resetLiveState(){liveMessageCursor=0;liveEventCursor=0;liveMessageCache=new Map();liveEventCache=new Map();liveReplyTo=null;livePollCount=0;renderLiveReply();renderLiveMessages();renderLiveEvents();}
function renderLiveReply(){const el=$('#liveReplyTarget');if(!el)return;if(!liveReplyTo){el.hidden=true;el.textContent='';$('#cancelLiveReply').hidden=true;return;}el.hidden=false;el.textContent='Replying to '+(liveReplyTo.label||'message');$('#cancelLiveReply').hidden=false;}
function renderLiveMessages(){const box=$('#liveMessages');if(!box)return;const rows=[...liveMessageCache.values()];rows.sort((a,b)=>Number(b.pinned)-Number(a.pinned)||String(a.created_at).localeCompare(String(b.created_at)));box.innerHTML=rows.length?rows.map(m=>{const who=m.author?.display_name||(m.is_self?'You · cloaked':m.cloak_alias||'Cloaked participant');const reply=m.parent_public_id?'<div class="liveReplyLine">↳ reply</div>':'';const pin=m.pinned?'<span class="livePin">Pinned</span>':'';const body=m.deleted?'<em>Message removed</em>':esc(m.body||'');const actions=m.deleted?'':`<div class="liveMessageActions"><button data-live-action="reply" data-message="${esc(m.public_id)}" data-label="${esc(who)}">Reply</button><button data-live-action="like" data-message="${esc(m.public_id)}">${m.viewer_liked?'♥':'♡'} ${m.like_count||0}</button>${m.can_pin?`<button data-live-action="pin" data-message="${esc(m.public_id)}">${m.pinned?'Unpin':'Pin'}</button>`:''}${m.can_delete?`<button data-live-action="delete" data-message="${esc(m.public_id)}">Delete</button>`:''}<button data-live-action="report" data-message="${esc(m.public_id)}">Report</button>${m.source_timestamp_seconds!==null?`<button data-live-action="seek" data-time="${Number(m.source_timestamp_seconds)}">Jump</button>`:''}</div>`;return `<div class="message ${m.pinned?'pinned':''}" data-message-id="${esc(m.public_id)}">${reply}<div class="messageHead"><strong>${esc(who)}</strong> ${pin}${m.source_timestamp_seconds!==null?' · '+fmtTime(m.source_timestamp_seconds):''}<span> · ${esc(m.created_at)}</span></div><div>${body}</div>${actions}</div>`;}).join(''):'<div class="hint">No messages yet.</div>';box.scrollTop=box.scrollHeight;}
function renderLiveEvents(){const box=$('#liveEvents');if(!box)return;const rows=[...liveEventCache.values()];box.innerHTML=rows.length?rows.slice(-20).map(e=>`<button type="button" class="liveEvent" data-live-event-type="${esc(e.object_type)}" data-live-event-id="${esc(e.object_public_id||'')}"><strong>${esc(e.label)}</strong><span>${esc(e.created_at)}</span></button>`).join(''):'<div class="hint">Live activity will appear here.</div>';}
async function loadLive(reset=false){if(!token||!context?.source?.public_id){$('#liveMessages').innerHTML='<div class="hint">Connect your account to join Live.</div>';return;}const key=liveCurrentKey();if(key!==liveRoomKey){liveRoomKey=key;reset=true;}if(reset)resetLiveState();const room=liveRoomParams();try{await heartbeat();const qs=new URLSearchParams({source:context.source.public_id,room_type:room.room_type,after_message:String(reset?0:liveMessageCursor),after_event:String(reset?0:liveEventCursor)});if(room.room_id)qs.set('room_id',room.room_id);const j=await api('/api/extension.php?action=live&'+qs);const d=j.data;renderPresence(d.presence||{});for(const m of d.messages||[])liveMessageCache.set(m.public_id,m);for(const e of d.events||[])liveEventCache.set(e.public_id,e);liveMessageCursor=Math.max(liveMessageCursor,Number(d.message_cursor||0));liveEventCursor=Math.max(liveEventCursor,Number(d.event_cursor||0));livePollFailures=0;livePollCount++;$('#liveConnection').textContent=d.room?.can_post===false?'Connected · read only':'Connected';$('#sendLive').disabled=d.room?.can_post===false;renderLiveMessages();renderLiveEvents();if(livePollCount%20===0&&!reset)return loadLive(true);}catch(e){livePollFailures++;$('#liveConnection').textContent='Reconnecting…';if(livePollFailures===1)$('#liveMessages').insertAdjacentHTML('beforeend','<div class="hint">Live connection interrupted. Retrying automatically.</div>');throw e;}}
function scheduleLivePoll(delay=2500){clearTimeout(liveTimer);const active=document.querySelector('nav button.active')?.dataset.tab==='live';if(!active)return;liveTimer=setTimeout(async()=>{try{await loadLive(false);}catch{}const next=Math.min(15000,2500*Math.max(1,livePollFailures));scheduleLivePoll(next);},delay);}
async function startLive(){await loadLiveRooms();liveRoomKey='';try{await loadLive(true);}catch{}scheduleLivePoll(2500);}
function stopLivePoll(){clearTimeout(liveTimer);liveTimer=null;}
async function sendLive(){if(!token){await connect();if(!token)return;}const body=$('#liveBody').value.trim();if(!body||!context?.source?.public_id)return;page=await readPage();const room=liveRoomParams(),parent=liveReplyTo?.id||null,roomKey=liveCurrentKey();if(!pendingLiveSend||pendingLiveSend.body!==body||pendingLiveSend.roomKey!==roomKey||pendingLiveSend.parent!==parent)pendingLiveSend={id:crypto.randomUUID(),body,roomKey,parent};try{await api('/api/extension.php?action=live_message',{method:'POST',body:JSON.stringify({source:context.source.public_id,body,timestamp:page?.mediaType?page.currentTime:null,reveal_identity:$('#liveReveal')?.checked||false,client_message_id:pendingLiveSend.id,client_session_id:liveClientSessionId,parent_message_id:parent,...room})});pendingLiveSend=null;$('#liveBody').value='';if($('#liveReveal'))$('#liveReveal').checked=false;liveReplyTo=null;renderLiveReply();await loadLive(false);}catch(e){alert(e.message);}}
async function liveMessageAction(e){const b=e.target.closest('[data-live-action]');if(!b)return;const action=b.dataset.liveAction,id=b.dataset.message,room=liveRoomParams();try{if(action==='reply'){liveReplyTo={id,label:b.dataset.label||'message'};renderLiveReply();$('#liveBody').focus();return;}if(action==='seek'){const tab=await activeTab();if(tab?.id)await chrome.tabs.sendMessage(tab.id,{type:'annotated:seek',time:Number(b.dataset.time)});return;}if(action==='report'){await reportObject('live_message',id);return;}if(action==='delete'&&!confirm('Remove this Live message?'))return;const apiAction=action==='like'?'live_react':action==='pin'?'live_message_pin':action==='delete'?'live_message_delete':null;if(!apiAction)return;await api('/api/extension.php?action='+apiAction,{method:'POST',body:JSON.stringify({source:context.source.public_id,message_id:id,reaction:'like',...room})});await loadLive(true);}catch(err){alert(err.message);}}
function liveEventAction(e){const b=e.target.closest('[data-live-event-id]');if(!b||!b.dataset.liveEventId)return;if(b.dataset.liveEventType==='annotation')chrome.tabs.create({url:API_BASE+'/annotation.php?id='+encodeURIComponent(b.dataset.liveEventId)});else if(b.dataset.liveEventType==='source')chrome.tabs.create({url:API_BASE+'/source.php?id='+encodeURIComponent(b.dataset.liveEventId)});}
async function changeLiveRoom(){liveRoomSelection=$('#liveRoom').value||'public';await chrome.storage.local.set({liveRoomSelection});liveRoomKey='';pendingLiveSend=null;try{await loadLive(true);}catch{}scheduleLivePoll(2500);}
function cancelLiveReply(){liveReplyTo=null;renderLiveReply();}
async function switchTab(btn){$$('nav button').forEach(x=>x.classList.toggle('active',x===btn));$$('main>section').forEach(s=>s.hidden=s.id!==btn.dataset.tab);if(btn.dataset.tab==='following')loadFollowing();if(btn.dataset.tab==='live')startLive();else stopLivePoll();if(btn.dataset.tab==='research')loadProjects();}
async function loadProjects(){if(!token){$('#researchProjects').innerHTML='<div class="hint">Connect your account to use Research.</div>';return [];}try{const j=await api('/api/extension.php?action=research_projects');const ps=j.data.projects||[];$('#researchProjects').innerHTML=ps.length?ps.map(p=>`<button type="button" class="projectCard workspaceProjectCard" data-workspace-project="${esc(p.public_id)}"><strong>${esc(p.title)}</strong></button>`).join(''):'<div class="hint">No projects yet. Create one on the Annotated website.</div>';return ps;}catch{return [];}}
async function openResearch(annotationId){pendingResearchAnnotation=annotationId;const ps=await loadProjects();if(!ps.length)return;$('#projectSelect').innerHTML=ps.map(p=>`<option value="${esc(p.public_id)}">${esc(p.title)}</option>`).join('');const state=await phase34WorkspaceRead();if(ps.some(p=>String(p.public_id)===state.research_public_id))$('#projectSelect').value=state.research_public_id;$('#researchDialog').showModal();}
async function confirmResearch(){if(!pendingResearchAnnotation)return;const annotationId=pendingResearchAnnotation,projectId=$('#projectSelect').value;try{await api('/api/extension.php?action=research_add',{method:'POST',body:JSON.stringify({project_id:projectId,annotation_id:annotationId})});await phase34WorkspaceCommit({research_public_id:projectId,object_type:'annotation',object_public_id:annotationId,surface:'research'});pendingResearchAnnotation=null;alert('Added to Research.');}catch(e){alert(e.message);}}
function notificationHref(n){return n.url||'';}
function notificationLabel(n){const label=String(n.notification_type||'notification').replaceAll('_',' ');return label.charAt(0).toUpperCase()+label.slice(1);}
async function loadNotifications(){
  if(!token){$('#notificationCount').textContent='';return;}
  try{
    const j=await api('/api/extension.php?action=notifications'),ns=j.data.notifications||[],unread=Number(j.data.unread_count||0);
    $('#notificationCount').textContent=unread?String(unread):'';
    $('#notificationList').innerHTML=ns.length?ns.map(n=>{
      const href=notificationHref(n),count=Number(n.group_count||1);
      const scope=n.context?.source_public_id?'source':(n.context?.conversation_public_id?'conversation':'');
      const scopeId=n.context?.source_public_id||n.context?.conversation_public_id||'';
      let actions='';const proactive=n.object_type==='cognitive_alert'&&n.context?.observation_key;const observationKey=proactive?String(n.context.observation_key):'';
      if(href)actions+='<button type="button" data-notification-action="open" data-notification-href="'+esc(href)+'">Open</button>';
      if(proactive&&n.context?.has_agent_action)actions+='<button type="button" data-notification-action="agent" data-observation-key="'+esc(observationKey)+'">Ask Agent</button>';
      if(proactive){actions+='<button type="button" data-notification-action="snooze" data-observation-key="'+esc(observationKey)+'">Snooze 1 day</button>';actions+='<button type="button" data-notification-action="resolve" data-observation-key="'+esc(observationKey)+'">Resolve</button>';}
      if(!n.read_at)actions+='<button type="button" data-notification-action="read">Mark read</button>';
      actions+='<button type="button" data-notification-action="archive">Archive</button>';
      if(scope)actions+='<button type="button" data-notification-action="mute" data-scope-type="'+esc(scope)+'" data-scope-id="'+esc(scopeId)+'" data-category="'+esc(n.category||'all')+'">Mute</button>';
      const why=proactive&&n.context?.why?'<div class="notificationWhy"><strong>Why this matters</strong><span>'+esc(n.context.why)+'</span></div>':'';
      return '<div class="notification '+(n.read_at?'':'unread')+'" data-id="'+esc(n.public_id)+'"><div class="notificationHead"><strong>'+esc(notificationLabel(n))+'</strong>'+(count>1?'<span class="badge">'+count+'</span>':'')+'</div><div>'+esc(n.body||'')+'</div>'+why+'<div class="hint">'+esc(n.created_at)+'</div><div class="notificationActions">'+actions+'</div></div>';
    }).join(''):'<div class="hint">No notifications yet.</div>';
  }catch(e){$('#notificationList').innerHTML='<div class="hint">Unable to load notifications.</div>';}
}
async function markNotification(e){
  const row=e.target.closest('.notification'),btn=e.target.closest('[data-notification-action]');if(!row||!btn)return;
  const id=row.dataset.id,action=btn.dataset.notificationAction;
  try{
    if(action==='open'){if(!row.classList.contains('read'))await api('/api/extension.php?action=notification_read',{method:'POST',body:JSON.stringify({notification_id:id})});chrome.tabs.create({url:API_BASE+btn.dataset.notificationHref});return;}
    if(action==='agent'){if(!row.classList.contains('read'))await api('/api/extension.php?action=notification_read',{method:'POST',body:JSON.stringify({notification_id:id})});chrome.tabs.create({url:API_BASE+'/home.php?proactive_agent='+encodeURIComponent(btn.dataset.observationKey||'')});return;}
    if(action==='snooze')await api('/api/extension.php?action=notification_snooze',{method:'POST',body:JSON.stringify({observation_key:btn.dataset.observationKey||'',hours:24})});
    if(action==='resolve')await api('/api/extension.php?action=notification_resolve',{method:'POST',body:JSON.stringify({observation_key:btn.dataset.observationKey||''})});
    if(action==='read')await api('/api/extension.php?action=notification_read',{method:'POST',body:JSON.stringify({notification_id:id})});
    if(action==='archive')await api('/api/extension.php?action=notification_archive',{method:'POST',body:JSON.stringify({notification_id:id})});
    if(action==='mute'){if(!confirm('Mute similar notifications from this scope?'))return;await api('/api/extension.php?action=notification_mute',{method:'POST',body:JSON.stringify({scope_type:btn.dataset.scopeType,scope_id:btn.dataset.scopeId,category:btn.dataset.category||'all',muted:true})});}
    await loadNotifications();
  }catch(err){alert(err.message);}
}
async function markAllNotificationsRead(){try{await api('/api/extension.php?action=notification_read_all',{method:'POST',body:'{}'});await loadNotifications();}catch(e){alert(e.message);}}
async function reportObject(objectType,objectId){
  if(!token){await connect();if(!token)return;}
  const reason=prompt('Report reason (spam, harassment, impersonation, misleading_context, privacy, illegal_content, other):','other');if(reason===null)return;
  const description=prompt('Optional details:','')||'';
  try{const j=await api('/api/extension.php?action=report',{method:'POST',body:JSON.stringify({object_type:objectType,object_id:objectId,reason:reason.trim()||'other',description})});alert(j.data.created?'Report submitted for review.':'You already have an open report for this item and reason.');}catch(e){alert(e.message);}
}
async function cardAction(e){const b=e.target.closest('button[data-action]');if(!b)return;const card=b.closest('.annotationCard'),id=card?.dataset.id;try{if(b.dataset.action==='follow'){if(!token){await connect();if(!token)return;}const j=await api('/api/extension.php?action=follow',{method:'POST',body:JSON.stringify({user_id:b.dataset.user})});b.textContent=j.data.following?'Following':'Follow';}else if(b.dataset.action==='save'){if(!token){await connect();if(!token)return;}const j=await api('/api/extension.php?action=save',{method:'POST',body:JSON.stringify({annotation_id:id})});b.textContent=j.data.saved?'Saved':'Save';}else if(b.dataset.action==='comment'){if(!token){await connect();if(!token)return;}const body=prompt('Comment on this annotation:');if(body){await api('/api/extension.php?action=comment',{method:'POST',body:JSON.stringify({annotation_id:id,body})});await loadThisPage();}}else if(b.dataset.action==='research')await openResearch(id);else if(b.dataset.action==='open')phase34WorkspaceOpen('/annotation.php?id='+encodeURIComponent(id),{object_type:'annotation',object_public_id:id,surface:'annotation'});else if(b.dataset.action==='source')phase34WorkspaceOpen('/source.php?id='+encodeURIComponent(b.dataset.source),{object_type:'source',object_public_id:b.dataset.source,surface:'source'});else if(b.dataset.action==='seek'){const tab=await activeTab();if(tab?.id)await chrome.tabs.sendMessage(tab.id,{type:'annotated:seek',time:Number(b.dataset.time)});}}catch(err){alert(err.message);}}
