async function captureVisible(rect=null){const tab=await activeTab();const full=await chrome.tabs.captureVisibleTab(tab.windowId,{format:'jpeg',quality:80});if(!rect||!page?.viewport)return {context:full,target:full};const img=new Image();await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;img.src=full});const sx=img.width/page.viewport.width,sy=img.height/page.viewport.height;const x=Math.max(0,Math.round(rect.x*sx)),y=Math.max(0,Math.round(rect.y*sy)),w=Math.max(1,Math.min(img.width-x,Math.round(rect.width*sx))),h=Math.max(1,Math.min(img.height-y,Math.round(rect.height*sy)));const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,x,y,w,h,0,0,w,h);return {context:full,target:c.toDataURL('image/jpeg',.9)};}
function blobToDataUrl(blob){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result));r.onerror=rej;r.readAsDataURL(blob);});}
async function startAudio(){if(mediaRecorder?.state==='recording')return;try{audioStream=await navigator.mediaDevices.getUserMedia({audio:true});const chunks=[];mediaRecorder=new MediaRecorder(audioStream,{mimeType:MediaRecorder.isTypeSupported('audio/webm;codecs=opus')?'audio/webm;codecs=opus':'audio/webm'});mediaRecorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};mediaRecorder.onstop=async()=>{audioBlob=new Blob(chunks,{type:mediaRecorder.mimeType||'audio/webm'});audioDataUrl=await blobToDataUrl(audioBlob);$('#audioPreview').src=URL.createObjectURL(audioBlob);$('#audioPreview').hidden=false;$('#clearAudio').hidden=false;$('#audioStatus').textContent='Audio ready · transcript will be queued after publish.';audioStream?.getTracks().forEach(t=>t.stop());};mediaRecorder.start();$('#recordAudio').disabled=true;$('#stopAudio').disabled=false;$('#audioStatus').textContent='● Recording audio commentary…';}catch(e){alert('Microphone access failed: '+(e.message||e));}}
function stopAudio(){if(mediaRecorder?.state==='recording')mediaRecorder.stop();$('#recordAudio').disabled=false;$('#stopAudio').disabled=true;}
function clearAudio(){if(mediaRecorder?.state==='recording')mediaRecorder.stop();audioStream?.getTracks().forEach(t=>t.stop());audioBlob=null;audioDataUrl='';$('#audioPreview').removeAttribute('src');$('#audioPreview').hidden=true;$('#clearAudio').hidden=true;$('#audioStatus').textContent='Audio commentary will be transcribed after publishing.';}
async function publish(){if(!token){await connect();if(!token)return;}page=await readPage(true);if(!page)return;let type='text',rect=page.selectionRect,start=null,end=null;if(captureMode==='region'){type='image_region';rect=regionRect||page.regionRect;if(!rect){await startRegion();return;}}if(captureMode==='media'){if(!page.mediaType)return;type=page.mediaType==='video'?'video_clip':'audio_clip';start=Number($('#clipStart').value);end=Number($('#clipEnd').value);if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start||end-start>90){alert('Choose a clip between 0 and 90 seconds.');return;}rect=null;}$('#publish').disabled=true;try{const shots=await captureVisible(rect);const j=await api('/api/extension.php?action=publish',{method:'POST',body:JSON.stringify({url:page.url,title:page.title,page_text:page.pageText,selected_text:captureMode==='text'?page.selectedText:'',selector:page.selector,commentary:$('#commentary').value.trim(),audio_commentary:audioDataUrl,capture_type:type,media_type:page.mediaType,start_seconds:start,end_seconds:end,visibility:$('#visibility').value,screenshot_context:shots.context,screenshot_target:shots.target})});$('#commentary').value='';regionRect=null;$('#regionPreview').hidden=true;clearAudio();const notes=[];if(j.data.media_queued)notes.push('media queued');if(j.data.transcription_queued)notes.push('audio transcription queued');alert(notes.length?'Published · '+notes.join(' · '):'Published');await loadPage();await loadNotifications();}catch(e){alert(e.message||'Unable to publish');}finally{$('#publish').disabled=false;}}
async function startRegion(){const tab=await activeTab();if(tab?.id)await chrome.tabs.sendMessage(tab.id,{type:'annotated:start-region'});}
function updateClipDuration(){const s=Number($('#clipStart').value),e=Number($('#clipEnd').value),d=e-s;$('#clipDuration').textContent=Number.isFinite(d)&&d>0?`${d.toFixed(1)} / 90 seconds${d>90?' — too long':''}`:'';}
async function setClip(which){page=await readPage();if(!Number.isFinite(Number(page?.currentTime)))return;$('#clip'+(which==='start'?'Start':'End')).value=Number(page.currentTime).toFixed(1);updateClipDuration();}
