async function heartbeat(){if(!token||!context?.source?.public_id)return;try{const j=await api('/api/extension.php?action=presence',{method:'POST',body:JSON.stringify({source:context.source.public_id,mode:$('#presence').value})});renderPresence(j.data);}catch{}}
function renderPresence(d){$('#liveStats').textContent=`${d.total||0} people here now · ${d.following_visible||0} you follow`;$('#presenceCount').textContent=(d.total||0)+' here';$('#livePeople').innerHTML=(d.visible||[]).map(p=>`<span class="person">${esc(p.display_name)}${p.following?' · following':''}</span>`).join('');}
async function loadLiveTeams(){if(!token)return;try{const j=await api('/api/extension.php?action=live_teams');const current=$('#liveRoom').value;$('#liveRoom').innerHTML='<option value="public">Public</option>'+j.data.teams.map(t=>`<option value="team:${esc(t.public_id)}">Team · ${esc(t.name)}</option>`).join('');if([...$('#liveRoom').options].some(o=>o.value===current))$('#liveRoom').value=current;}catch{}}
function liveRoomParams(){const v=$('#liveRoom').value||'public';return v.startsWith('team:')?{room_type:'team',team_id:v.slice(5)}:{room_type:'public',team_id:null};}
async function loadLive(){if(!token||!context?.source?.public_id){$('#liveMessages').innerHTML='<div class="hint">Connect your account to join Live.</div>';return;}await heartbeat();const room=liveRoomParams();try{const qs=new URLSearchParams({source:context.source.public_id,room_type:room.room_type});if(room.team_id)qs.set('team_id',room.team_id);const j=await api('/api/extension.php?action=live&'+qs);$('#liveMessages').innerHTML=j.data.messages.map(m=>`<div class="message"><div class="messageHead"><strong>${esc(m.display_name)}</strong>${m.source_timestamp_seconds!==null?' · '+fmtTime(m.source_timestamp_seconds):''}</div><div>${esc(m.body)}</div></div>`).join('')||'<div class="hint">No messages yet.</div>';$('#liveMessages').scrollTop=$('#liveMessages').scrollHeight;}catch(e){$('#liveMessages').innerHTML='<div class="hint">'+esc(e.message)+'</div>';}}
async function sendLive(reveal=false){if(!token){await connect();if(!token)return;}const body=$('#liveBody').value.trim();if(!body||!context?.source?.public_id)return;page=await readPage();const room=liveRoomParams();try{await api('/api/extension.php?action=live_message',{method:'POST',body:JSON.stringify({source:context.source.public_id,body,timestamp:page?.mediaType?page.currentTime:null,reveal_identity:reveal,...room})});$('#liveBody').value='';await loadLive();}catch(e){if(e.code==='IDENTITY_DISCLOSURE_REQUIRED'){if(confirm('You are cloaked/private in Live. Posting publicly will reveal your identity for this message only. Continue?'))return sendLive(true);}alert(e.message);}}
async function loadProjects(){if(!token){$('#researchProjects').innerHTML='<div class="hint">Connect your account to use Research.</div>';return [];}try{const j=await api('/api/extension.php?action=research_projects');const ps=j.data.projects||[];$('#researchProjects').innerHTML=ps.length?ps.map(p=>`<div class="projectCard"><strong>${esc(p.title)}</strong></div>`).join(''):'<div class="hint">No projects yet. Create one on the Annotated website.</div>';return ps;}catch{return [];}}
async function openResearch(annotationId){pendingResearchAnnotation=annotationId;const ps=await loadProjects();if(!ps.length)return;$('#projectSelect').innerHTML=ps.map(p=>`<option value="${esc(p.public_id)}">${esc(p.title)}</option>`).join('');$('#researchDialog').showModal();}
async function confirmResearch(){if(!pendingResearchAnnotation)return;try{await api('/api/extension.php?action=research_add',{method:'POST',body:JSON.stringify({project_id:$('#projectSelect').value,annotation_id:pendingResearchAnnotation})});pendingResearchAnnotation=null;alert('Added to Research.');}catch(e){alert(e.message);}}
function notificationHref(n){if(!n.object_public_id)return '';if(n.object_type==='annotation')return '/annotation.php?id='+encodeURIComponent(n.object_public_id)+'#discussion';if(n.object_type==='source')return '/source.php?id='+encodeURIComponent(n.object_public_id);if(n.object_type==='research_report')return '/research-report.php?id='+encodeURIComponent(n.object_public_id);return '';}
async function loadNotifications(){if(!token){$('#notificationCount').textContent='';return;}try{const j=await api('/api/extension.php?action=notifications');const ns=j.data.notifications||[],unread=ns.filter(n=>!n.read_at).length;$('#notificationCount').textContent=unread?String(unread):'';$('#notificationList').innerHTML=ns.length?ns.map(n=>{const href=notificationHref(n);return `<div class="notification ${n.read_at?'':'unread'}" data-id="${n.id}"><strong>${esc(n.notification_type.replaceAll('_',' '))}</strong><div>${esc(n.body||'')}</div><div class="hint">${esc(n.created_at)}</div>${href?`<button type="button" data-notification-href="${esc(href)}">Open</button>`:''}</div>`;}).join(''):'<div class="hint">No notifications yet.</div>';}catch{}}
async function markNotification(e){const row=e.target.closest('.notification');if(!row)return;try{if(!row.classList.contains('read')){await api('/api/extension.php?action=notification_read',{method:'POST',body:JSON.stringify({id:Number(row.dataset.id)})});row.classList.remove('unread');}const open=e.target.closest('[data-notification-href]');if(open)chrome.tabs.create({url:API_BASE+open.dataset.notificationHref});else await loadNotifications();}catch{}}
async function cardAction(e){const b=e.target.closest('button[data-action]');if(!b)return;const card=b.closest('.annotationCard'),id=card?.dataset.id;try{if(b.dataset.action==='follow'){if(!token){await connect();if(!token)return;}const j=await api('/api/extension.php?action=follow',{method:'POST',body:JSON.stringify({user_id:b.dataset.user})});b.textContent=j.data.following?'Following':'Follow';}else if(b.dataset.action==='save'){if(!token){await connect();if(!token)return;}const j=await api('/api/extension.php?action=save',{method:'POST',body:JSON.stringify({annotation_id:id})});b.textContent=j.data.saved?'Saved':'Save';}else if(b.dataset.action==='comment'){if(!token){await connect();if(!token)return;}const body=prompt('Comment on this annotation:');if(body){await api('/api/extension.php?action=comment',{method:'POST',body:JSON.stringify({annotation_id:id,body})});await loadThisPage();}}else if(b.dataset.action==='research')await openResearch(id);else if(b.dataset.action==='open')chrome.tabs.create({url:API_BASE+'/annotation.php?id='+encodeURIComponent(id)});else if(b.dataset.action==='source')chrome.tabs.create({url:API_BASE+'/source.php?id='+encodeURIComponent(b.dataset.source)});else if(b.dataset.action==='seek'){const tab=await activeTab();if(tab?.id)await chrome.tabs.sendMessage(tab.id,{type:'annotated:seek',time:Number(b.dataset.time)});}}catch(err){alert(err.message);}}
async function switchTab(btn){$$('nav button').forEach(x=>x.classList.toggle('active',x===btn));$$('main>section').forEach(s=>s.hidden=s.id!==btn.dataset.tab);if(btn.dataset.tab==='following')loadFollowing();if(btn.dataset.tab==='live'){loadLiveTeams();loadLive();clearInterval(liveTimer);liveTimer=setInterval(loadLive,4000);}else{clearInterval(liveTimer);liveTimer=null;}if(btn.dataset.tab==='research')loadProjects();}
