let API_BASE='http://localhost',token='',page=null,context=null,captureMode='text',regionRect=null,regionTargetData='',pendingResearchAnnotation=null,liveTimer=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function settings(){const s=await chrome.storage.sync.get({apiBase:'http://localhost'});API_BASE=(s.apiBase||'http://localhost').replace(/\/$/,'');const a=await chrome.storage.local.get({annotatedToken:''});token=a.annotatedToken||'';}
async function api(path,opts={}){const headers={'Content-Type':'application/json',...(opts.headers||{})};if(token)headers.Authorization='Bearer '+token;const r=await fetch(API_BASE+path,{...opts,headers});let j={};try{j=await r.json()}catch{}if(!r.ok||j.ok===false){const e=new Error(j.error?.message||j.error?.code||('HTTP '+r.status));e.code=j.error?.code||'HTTP_'+r.status;e.status=r.status;throw e;}return j;}
async function connect(){const redirect=chrome.identity.getRedirectURL('annotated');const state=crypto.randomUUID();const url=API_BASE+'/extension-authorize.php?'+new URLSearchParams({redirect_uri:redirect,state});try{const response=await chrome.identity.launchWebAuthFlow({url,interactive:true});if(!response)return;const u=new URL(response);if(u.searchParams.get('state')!==state)throw new Error('Invalid authorization state.');const code=u.searchParams.get('code');const j=await api('/api/extension-token.php',{method:'POST',body:JSON.stringify({code,redirect_uri:redirect,device_name:'Chrome sidebar'})});token=j.data.token;await chrome.storage.local.set({annotatedToken:token});await loadMe();await loadPage();}catch(e){$('#status').textContent=e.message||'Connection failed';}}
async function loadMe(){if(!token){$('#status').textContent='Not connected';$('#connect').hidden=false;return false;}try{const j=await api('/api/extension.php?action=me');$('#status').textContent='@'+j.data.user.username;$('#connect').textContent='Reconnect';$('#presence').value=j.data.user.live_presence_mode||'cloaked';return true;}catch{token='';await chrome.storage.local.remove('annotatedToken');$('#status').textContent='Connect account';$('#connect').hidden=false;return false;}}
async function activeTab(){const [tab]=await chrome.tabs.query({active:true,currentWindow:true});return tab;}
async function readPage(){const tab=await activeTab();if(!tab?.id)return null;return await chrome.tabs.sendMessage(tab.id,{type:'annotated:get-page'}).catch(()=>({url:tab.url,title:tab.title,selectedText:'',pageText:'',viewport:null,mediaType:null}));}
async function loadPage(){page=await readPage();if(!page)return;$('#title').textContent=page.title||'Current page';try{$('#domain').textContent=new URL(page.url).hostname}catch{}$('#selection').textContent=page.selectedText|| (captureMode==='region'?'Choose a region on the page.':'Highlight text on the page to capture it.');$('#mediaMode').hidden=!page.mediaType;$('#mediaControls').hidden=!(captureMode==='media'&&page.mediaType);if(page.mediaType)updateClipDuration();try{const j=await api('/api/extension.php?action=page_context',{method:'POST',body:JSON.stringify({url:page.url,title:page.title,page_text:page.pageText,media_type:page.mediaType})});context=j.data;$('#count').textContent=(context.annotation_count||0)+' annotations';$('#presenceCount').textContent=(context.presence_count||0)+' here';$('#presence').value=context.presence_mode||$('#presence').value;await loadThisPage();if(token)heartbeat();}catch(e){$('#count').textContent='Backend unavailable';$('#presenceCount').textContent='';} }
function fmtTime(v){v=Number(v);if(!Number.isFinite(v))return '';const m=Math.floor(v/60),s=Math.floor(v%60);return m+':'+String(s).padStart(2,'0');}
function annotationCard(a){const follow=Number(a.is_following)?'Following':'Follow';const saved=Number(a.is_saved)?'Saved':'Save';const sourceBadge=a.source_status==='edited'?'<span class="badge">Edited</span>':'';const shot=a.screenshot_target_path?`<img src="${esc(API_BASE+a.screenshot_target_path)}" alt="Captured source snapshot">`:'';const time=a.start_seconds!==null&&a.start_seconds!==undefined?`<div class="hint">Clip ${fmtTime(a.start_seconds)} → ${fmtTime(a.end_seconds)}</div>`:'';return `<article class="annotationCard" data-id="${esc(a.public_id)}"><div class="author"><strong>${esc(a.display_name)}</strong><span>@${esc(a.username)}</span>${sourceBadge}<button data-action="follow" data-user="${esc(a.author_public_id)}">${follow}</button></div><h4>${esc(a.source_title||'Annotated source')}</h4>${a.text_commentary?`<p>${esc(a.text_commentary)}</p>`:''}${a.selected_text?`<div class="excerpt">${esc(a.selected_text.slice(0,500))}</div>`:''}${shot}${time}<div class="cardActions"><button data-action="comment">Comment · ${Number(a.comment_count||0)}</button><button data-action="save">${saved}</button><button data-action="research">Research</button><button data-action="open">Open</button>${a.start_seconds!==null&&a.start_seconds!==undefined?'<button data-action="seek" data-time="'+Number(a.start_seconds)+'">Jump</button>':''}</div></article>`;}
async function loadThisPage(){if(!context?.source?.public_id){$('#feed').innerHTML='<div class="hint">No public annotations yet. Be the first.</div>';return;}try{const j=await api('/api/extension.php?action=feed_page&source='+encodeURIComponent(context.source.public_id));$('#feed').innerHTML=j.data.annotations.length?j.data.annotations.map(annotationCard).join(''):'<div class="hint">No public annotations yet. Be the first.</div>';}catch(e){$('#feed').innerHTML='<div class="hint">Unable to load annotations.</div>';}}
async function loadFollowing(){if(!token){$('#followingFeed').innerHTML='<div class="hint">Connect your account to see Following.</div>';return;}try{const j=await api('/api/extension.php?action=feed_following');$('#followingFeed').innerHTML=j.data.annotations.length?j.data.annotations.map(annotationCard).join(''):'<div class="hint">Follow researchers from This Page to build this feed.</div>';}catch(e){$('#followingFeed').innerHTML='<div class="hint">Unable to load Following.</div>';}}
async function captureVisible(rect=null){const tab=await activeTab();const full=await chrome.tabs.captureVisibleTab(tab.windowId,{format:'jpeg',quality:80});if(!rect||!page?.viewport)return {context:full,target:full};const img=new Image();await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;img.src=full});const sx=img.width/page.viewport.width,sy=img.height/page.viewport.height;const x=Math.max(0,Math.round(rect.x*sx)),y=Math.max(0,Math.round(rect.y*sy)),w=Math.max(1,Math.min(img.width-x,Math.round(rect.width*sx))),h=Math.max(1,Math.min(img.height-y,Math.round(rect.height*sy)));const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,x,y,w,h,0,0,w,h);return {context:full,target:c.toDataURL('image/png')};}
async function publish(){if(!token){await connect();if(!token)return;}page=await readPage();if(!page)return;let type='text',rect=page.selectionRect,start=null,end=null;if(captureMode==='region'){type='image_region';rect=regionRect||page.regionRect;if(!rect){await startRegion();return;}}if(captureMode==='media'){if(!page.mediaType)return;type=page.mediaType==='video'?'video_clip':'audio_clip';start=Number($('#clipStart').value);end=Number($('#clipEnd').value);if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start||end-start>90){alert('Choose a clip between 0 and 90 seconds.');return;}rect=null;}$('#publish').disabled=true;try{const shots=await captureVisible(rect);const j=await api('/api/extension.php?action=publish',{method:'POST',body:JSON.stringify({url:page.url,title:page.title,page_text:page.pageText,selected_text:captureMode==='text'?page.selectedText:'',selector:page.selector,commentary:$('#commentary').value.trim(),capture_type:type,media_type:page.mediaType,start_seconds:start,end_seconds:end,visibility:$('#visibility').value,screenshot_context:shots.context,screenshot_target:shots.target})});$('#commentary').value='';regionRect=null;regionTargetData='';$('#regionPreview').hidden=true;alert(j.data.media_queued?'Published. Media is queued for processing.':'Published');await loadPage();}catch(e){alert(e.message||'Unable to publish');}finally{$('#publish').disabled=false;}}
async function startRegion(){const tab=await activeTab();if(tab?.id)await chrome.tabs.sendMessage(tab.id,{type:'annotated:start-region'});}
function updateClipDuration(){const s=Number($('#clipStart').value),e=Number($('#clipEnd').value);const d=e-s;$('#clipDuration').textContent=Number.isFinite(d)&&d>0?`${d.toFixed(1)} / 90 seconds${d>90?' — too long':''}`:'';}
async function setClip(which){page=await readPage();if(!Number.isFinite(Number(page?.currentTime)))return;$('#clip'+(which==='start'?'Start':'End')).value=Number(page.currentTime).toFixed(1);updateClipDuration();}
async function heartbeat(){if(!token||!context?.source?.public_id)return;try{const j=await api('/api/extension.php?action=presence',{method:'POST',body:JSON.stringify({source:context.source.public_id,mode:$('#presence').value})});renderPresence(j.data);}catch{} }
function renderPresence(d){$('#liveStats').textContent=`${d.total||0} people here now · ${d.following_visible||0} you follow`;$('#presenceCount').textContent=(d.total||0)+' here';$('#livePeople').innerHTML=(d.visible||[]).map(p=>`<span class="person">${esc(p.display_name)}${p.following?' · following':''}</span>`).join('');}
async function loadLive(){if(!token||!context?.source?.public_id){$('#liveMessages').innerHTML='<div class="hint">Connect your account to join Live.</div>';return;}await heartbeat();try{const j=await api('/api/extension.php?action=live&source='+encodeURIComponent(context.source.public_id));$('#liveMessages').innerHTML=j.data.messages.map(m=>`<div class="message"><div class="messageHead"><strong>${esc(m.display_name)}</strong>${m.source_timestamp_seconds!==null?' · '+fmtTime(m.source_timestamp_seconds):''}</div><div>${esc(m.body)}</div></div>`).join('')||'<div class="hint">No messages yet.</div>';$('#liveMessages').scrollTop=$('#liveMessages').scrollHeight;}catch{} }
async function sendLive(reveal=false){if(!token){await connect();if(!token)return;}const body=$('#liveBody').value.trim();if(!body||!context?.source?.public_id)return;page=await readPage();try{await api('/api/extension.php?action=live_message',{method:'POST',body:JSON.stringify({source:context.source.public_id,body,timestamp:page?.mediaType?page.currentTime:null,reveal_identity:reveal})});$('#liveBody').value='';await loadLive();}catch(e){if(e.code==='IDENTITY_DISCLOSURE_REQUIRED'){if(confirm('You are cloaked/private in Live. Posting publicly will reveal your identity for this message only. Continue?'))return sendLive(true);}alert(e.message);}}
async function loadProjects(){if(!token){$('#researchProjects').innerHTML='<div class="hint">Connect your account to use Research.</div>';return [];}try{const j=await api('/api/extension.php?action=research_projects');const ps=j.data.projects||[];$('#researchProjects').innerHTML=ps.length?ps.map(p=>`<div class="projectCard"><strong>${esc(p.title)}</strong></div>`).join(''):'<div class="hint">No projects yet. Create one on the Annotated website.</div>';return ps;}catch{return [];}}
async function openResearch(annotationId){pendingResearchAnnotation=annotationId;const ps=await loadProjects();if(!ps.length)return;$('#projectSelect').innerHTML=ps.map(p=>`<option value="${esc(p.public_id)}">${esc(p.title)}</option>`).join('');$('#researchDialog').showModal();}
async function confirmResearch(){if(!pendingResearchAnnotation)return;try{await api('/api/extension.php?action=research_add',{method:'POST',body:JSON.stringify({project_id:$('#projectSelect').value,annotation_id:pendingResearchAnnotation})});pendingResearchAnnotation=null;alert('Added to Research.');}catch(e){alert(e.message);}}
async function cardAction(e){const b=e.target.closest('button[data-action]');if(!b)return;const card=b.closest('.annotationCard'),id=card?.dataset.id;try{if(b.dataset.action==='follow'){if(!token){await connect();if(!token)return;}const j=await api('/api/extension.php?action=follow',{method:'POST',body:JSON.stringify({user_id:b.dataset.user})});b.textContent=j.data.following?'Following':'Follow';}if(b.dataset.action==='save'){if(!token){await connect();if(!token)return;}const j=await api('/api/extension.php?action=save',{method:'POST',body:JSON.stringify({annotation_id:id})});b.textContent=j.data.saved?'Saved':'Save';}if(b.dataset.action==='comment'){if(!token){await connect();if(!token)return;}const body=prompt('Comment on this annotation:');if(body){await api('/api/extension.php?action=comment',{method:'POST',body:JSON.stringify({annotation_id:id,body})});await loadThisPage();}}if(b.dataset.action==='research')await openResearch(id);if(b.dataset.action==='open')chrome.tabs.create({url:API_BASE+'/annotation.php?id='+encodeURIComponent(id)});if(b.dataset.action==='seek'){const tab=await activeTab();if(tab?.id)await chrome.tabs.sendMessage(tab.id,{type:'annotated:seek',time:Number(b.dataset.time)});}}catch(err){alert(err.message);}}
async function switchTab(btn){$$('nav button').forEach(x=>x.classList.toggle('active',x===btn));$$('main>section').forEach(s=>s.hidden=s.id!==btn.dataset.tab);if(btn.dataset.tab==='following')loadFollowing();if(btn.dataset.tab==='live'){loadLive();clearInterval(liveTimer);liveTimer=setInterval(loadLive,4000);}else{clearInterval(liveTimer);liveTimer=null;}if(btn.dataset.tab==='research')loadProjects();}
$('#connect').onclick=connect;$('#refresh').onclick=loadPage;$('#publish').onclick=publish;$('#setStart').onclick=()=>setClip('start');$('#setEnd').onclick=()=>setClip('end');$('#clipStart').oninput=updateClipDuration;$('#clipEnd').oninput=updateClipDuration;$('#sendLive').onclick=()=>sendLive(false);$('#refreshFollowing').onclick=loadFollowing;$('#presence').onchange=heartbeat;$('#feed').addEventListener('click',cardAction);$('#followingFeed').addEventListener('click',cardAction);$('#confirmResearch').addEventListener('click',e=>{e.preventDefault();confirmResearch();$('#researchDialog').close();});$$('nav button').forEach(b=>b.onclick=()=>switchTab(b));$$('.modes button').forEach(b=>b.onclick=async()=>{captureMode=b.dataset.mode;$$('.modes button').forEach(x=>x.classList.toggle('active',x===b));$('#mediaControls').hidden=!(captureMode==='media'&&page?.mediaType);if(captureMode==='region')await startRegion();});
chrome.runtime.onMessage.addListener(async m=>{if(m?.type==='annotated:tab-changed')loadPage();if(m?.type==='annotated:region-selected'){regionRect=m.rect;captureMode='region';$$('.modes button').forEach(x=>x.classList.toggle('active',x.dataset.mode==='region'));page=await readPage();try{const shots=await captureVisible(regionRect);regionTargetData=shots.target;$('#regionPreview').innerHTML='<img src="'+shots.target+'" alt="Selected region">';$('#regionPreview').hidden=false;$('#selection').textContent='Selected screen region ready to annotate.';}catch{}}});
(async()=>{await settings();await loadMe();await loadPage();setInterval(()=>{if(!document.hidden&&token&&context?.source?.public_id)heartbeat();},30000);})();
