let API_BASE='http://localhost',token='',page=null,context=null,captureMode='text',regionRect=null,pendingResearchAnnotation=null,liveTimer=null;
let audioBlob=null,audioDataUrl='',mediaRecorder=null,audioStream=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function settings(){const s=await chrome.storage.sync.get({apiBase:'http://localhost'});API_BASE=(s.apiBase||'http://localhost').replace(/\/$/,'');const a=await chrome.storage.local.get({annotatedToken:''});token=a.annotatedToken||'';}
async function api(path,opts={}){const headers={'Content-Type':'application/json',...(opts.headers||{})};if(token)headers.Authorization='Bearer '+token;const r=await fetch(API_BASE+path,{...opts,headers});let j={};try{j=await r.json()}catch{}if(!r.ok||j.ok===false){const e=new Error(j.error?.message||j.error?.code||('HTTP '+r.status));e.code=j.error?.code||'HTTP_'+r.status;e.status=r.status;throw e;}return j;}
async function connect(){const redirect=chrome.identity.getRedirectURL('annotated');const state=crypto.randomUUID();const url=API_BASE+'/extension-authorize.php?'+new URLSearchParams({redirect_uri:redirect,state});try{const response=await chrome.identity.launchWebAuthFlow({url,interactive:true});if(!response)return;const u=new URL(response);if(u.searchParams.get('state')!==state)throw new Error('Invalid authorization state.');const code=u.searchParams.get('code');const j=await api('/api/extension-token.php',{method:'POST',body:JSON.stringify({code,redirect_uri:redirect,device_name:'Chrome sidebar'})});token=j.data.token;await chrome.storage.local.set({annotatedToken:token});await loadMe();await loadPage();await loadNotifications();}catch(e){$('#status').textContent=e.message||'Connection failed';}}
async function loadMe(){if(!token){$('#status').textContent='Not connected';return false;}try{const j=await api('/api/extension.php?action=me');$('#status').textContent='@'+j.data.user.username;$('#connect').textContent='Reconnect';$('#presence').value=j.data.user.live_presence_mode||'cloaked';return true;}catch{token='';await chrome.storage.local.remove('annotatedToken');$('#status').textContent='Connect account';return false;}}
async function activeTab(){const [tab]=await chrome.tabs.query({active:true,currentWindow:true});return tab;}
async function readPage(){const tab=await activeTab();if(!tab?.id)return null;return await chrome.tabs.sendMessage(tab.id,{type:'annotated:get-page'}).catch(()=>({url:tab.url,title:tab.title,selectedText:'',pageText:'',viewport:null,mediaType:null}));}
async function loadPage(){page=await readPage();if(!page)return;$('#title').textContent=page.title||'Current page';try{$('#domain').textContent=new URL(page.url).hostname}catch{}$('#selection').textContent=page.selectedText||(captureMode==='region'?'Choose a region on the page.':'Highlight text on the page to capture it.');$('#mediaMode').hidden=!page.mediaType;$('#mediaControls').hidden=!(captureMode==='media'&&page.mediaType);if(page.mediaType)updateClipDuration();try{const j=await api('/api/extension.php?action=page_context',{method:'POST',body:JSON.stringify({url:page.url,title:page.title,page_text:page.pageText,media_type:page.mediaType})});context=j.data;$('#count').textContent=(context.annotation_count||0)+' annotations';$('#presenceCount').textContent=(context.presence_count||0)+' here';$('#presence').value=context.presence_mode||$('#presence').value;await loadThisPage();if(token){heartbeat();loadLiveTeams();}}catch{$('#count').textContent='Backend unavailable';$('#presenceCount').textContent='';}}
function fmtTime(v){v=Number(v);if(!Number.isFinite(v))return '';const m=Math.floor(v/60),s=Math.floor(v%60);return m+':'+String(s).padStart(2,'0');}
function annotationCard(a){const follow=Number(a.is_following)?'Following':'Follow',saved=Number(a.is_saved)?'Saved':'Save';const badge=a.source_status==='edited'?'<span class="badge">Edited</span>':a.source_status==='updated'?'<span class="badge">Updated</span>':'';const shot=a.screenshot_target_path?`<img src="${esc(API_BASE+a.screenshot_target_path)}" alt="Captured source snapshot">`:'';const time=a.start_seconds!==null&&a.start_seconds!==undefined?`<div class="hint">Clip ${fmtTime(a.start_seconds)} → ${fmtTime(a.end_seconds)}</div>`:'';const audio=a.audio_commentary_path?`<audio controls src="${esc(API_BASE+a.audio_commentary_path)}"></audio>`:'';const transcript=a.transcript_status==='ready'&&a.transcript_text?`<details class="transcript"><summary>Transcript</summary>${esc(a.transcript_text.slice(0,1200))}</details>`:a.audio_commentary_path?`<div class="hint">Transcript: ${esc(a.transcript_status||'queued')}</div>`:'';return `<article class="annotationCard" data-id="${esc(a.public_id)}"><div class="author"><strong>${esc(a.display_name)}</strong><span>@${esc(a.username)}</span>${badge}<button data-action="follow" data-user="${esc(a.author_public_id)}">${follow}</button></div><h4>${esc(a.source_title||'Annotated source')}</h4>${a.text_commentary?`<p>${esc(a.text_commentary)}</p>`:''}${a.selected_text?`<div class="excerpt">${esc(a.selected_text.slice(0,500))}</div>`:''}${shot}${audio}${transcript}${time}<div class="cardActions"><button data-action="comment">Comment · ${Number(a.comment_count||0)}</button><button data-action="save">${saved}</button><button data-action="research">Research</button><button data-action="source" data-source="${esc(a.source_public_id)}">Source</button><button data-action="open">Open</button>${a.start_seconds!==null&&a.start_seconds!==undefined?'<button data-action="seek" data-time="'+Number(a.start_seconds)+'">Jump</button>':''}</div></article>`;}
async function loadThisPage(){if(!context?.source?.public_id){$('#feed').innerHTML='<div class="hint">No Annotated source record yet.</div>';return;}try{const j=await api('/api/extension.php?action=feed_page&source='+encodeURIComponent(context.source.public_id));$('#feed').innerHTML=j.data.annotations.length?j.data.annotations.map(annotationCard).join(''):'<div class="hint">No public annotations yet. Be the first.</div>';}catch{$('#feed').innerHTML='<div class="hint">Unable to load annotations.</div>';}}
async function loadFollowing(){if(!token){$('#followingFeed').innerHTML='<div class="hint">Connect your account to see Following.</div>';return;}try{const j=await api('/api/extension.php?action=feed_following');$('#followingFeed').innerHTML=j.data.annotations.length?j.data.annotations.map(annotationCard).join(''):'<div class="hint">Follow researchers from This Page to build this feed.</div>';}catch{$('#followingFeed').innerHTML='<div class="hint">Unable to load Following.</div>';}}
