<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';
if(PHP_SAPI!=='cli')header('Cache-Control: no-store, private');
$user=require_user($pdo);if(!account_membership_ready($pdo)){http_response_code(503);exit('Account membership requires the latest database upgrade.');}
$accountId=trim((string)($_GET['account']??$_POST['account']??''));$accounts=account_membership_accounts_for_user($pdo,$user,false);if(!$accounts){http_response_code(404);exit('No commercial account membership found.');}
$account=account_membership_account_for_user($pdo,$user,$accountId!==''?$accountId:null,false);$role=account_membership_actor_role($pdo,$user,(int)$account['id']);$canManage=in_array($role,['owner','admin','site_admin'],true);$isOwner=in_array($role,['owner','site_admin'],true);$success='';$error='';$inviteUrl='';
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();try{
    $action=(string)($_POST['action']??'');$reason=(string)($_POST['reason']??'');
    if($action==='invite'){
        if(!$canManage)throw new RuntimeException('Account owner or account admin access is required.');
        $invite=account_membership_create_invitation($pdo,$config,$user,(string)$account['public_id'],(string)($_POST['email']??''),(string)($_POST['account_role']??'member'),!empty($_POST['reserve_seat']),(int)($_POST['expires_days']??7),$reason);
        $inviteUrl=(string)($invite['invite_url']??'');$success=$invite['delivery_status']==='sent'?'Invitation created and email accepted by the configured mail transport.':'Invitation created. Copy the secure invitation link below.';
    }elseif($action==='resend'){
        $invite=account_membership_resend_invitation($pdo,$config,$user,(string)($_POST['invitation_id']??''),(int)($_POST['expires_days']??7),$reason);$inviteUrl=(string)($invite['invite_url']??'');$success=$invite['delivery_status']==='sent'?'Invitation token rotated and email resent.':'Invitation token rotated. Copy the new secure invitation link below.';
    }elseif($action==='revoke'){account_membership_revoke_invitation($pdo,$user,(string)($_POST['invitation_id']??''),$reason);$success='Invitation revoked.';}
    elseif($action==='member_role'){account_membership_update_role($pdo,$user,(string)$account['public_id'],(int)($_POST['user_id']??0),(string)($_POST['account_role']??'member'),$reason);$success='Member role updated.';}
    elseif($action==='remove_member'){account_membership_remove_member($pdo,$user,(string)$account['public_id'],(int)($_POST['user_id']??0),$reason);$success='Member removed from this commercial account.';}
    elseif($action==='transfer_owner'){account_membership_transfer_owner($pdo,$user,(string)$account['public_id'],(int)($_POST['user_id']??0),$reason);$success='Account ownership transferred.';}
    else throw new RuntimeException('Unknown account membership action.');
}catch(Throwable $e){$error=$e->getMessage();}
$account=account_membership_account_for_user($pdo,$user,(string)$account['public_id'],false);$role=account_membership_actor_role($pdo,$user,(int)$account['id']);$canManage=in_array($role,['owner','admin','site_admin'],true);$isOwner=in_array($role,['owner','site_admin'],true);}
$members=account_admin_members($pdo,(int)$account['id']);$seats=account_membership_seat_summary($pdo,(int)$account['id']);$invitations=$canManage?account_membership_invitations($pdo,(int)$account['id'],false,100):[];$events=$canManage?account_membership_events($pdo,(int)$account['id'],80):[];
$mail=account_membership_mail_settings($config);$billingUrl='/billing.php?account='.rawurlencode((string)$account['public_id']);
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Account Members · Annotated</title><link rel="stylesheet" href="/assets/css/app.css"></head><body>
<main class="panel accountMembershipPage"><div class="pageTitle"><span class="eyebrow">COMMERCIAL ACCOUNT</span><h1>Members & seats</h1><p>Manage commercial account membership without changing Research Teams or research permissions.</p></div>
<?php if(count($accounts)>1):?><nav class="billingAccountSwitcher" aria-label="Commercial accounts"><?php foreach($accounts as $a):?><a class="<?=$a['public_id']===$account['public_id']?'active':''?>" href="/account-members.php?account=<?=h(rawurlencode((string)$a['public_id']))?>"><strong><?=h((string)$a['name'])?></strong><small><?=h((string)$a['account_role'])?> · <?=h((string)$a['package_name'])?></small></a><?php endforeach?></nav><?php endif?>
<?php if($success):?><div class="success"><?=h($success)?></div><?php endif?><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?>
<?php if($inviteUrl):?><section class="card accountInviteLinkCard"><span class="eyebrow">INVITATION LINK</span><h2>Secure invitation link</h2><p>This is the only time the current invitation token is displayed. Resending rotates the token and invalidates this link.</p><input value="<?=h($inviteUrl)?>" readonly onclick="this.select()" aria-label="Invitation link"></section><?php endif?>
<section class="accountSeatGrid"><article class="card"><span class="meta">Account</span><strong><?=h((string)$account['name'])?></strong><small><?=h((string)$role)?> access</small></article><article class="card"><span class="meta">Package</span><strong><?=h((string)$account['package_name'])?></strong><small><?=h((string)$account['subscription_status'])?></small></article><article class="card"><span class="meta">Occupied members</span><strong><?=h((string)$seats['member_count'])?></strong><small>accepted account members</small></article><article class="card"><span class="meta">Pending reserved</span><strong><?=h((string)$seats['pending_reserved'])?></strong><small>pending invitations reserving seats</small></article><article class="card"><span class="meta">Seat usage</span><strong><?=h((string)$seats['used_seats'])?> / <?=h((string)$seats['member_limit'])?></strong><small><?=h((string)$seats['available_seats'])?> available</small></article></section>
<?php if($seats['over_capacity']||$seats['over_reserved']):?><div class="error"><strong>Account is over capacity.</strong> Existing members are preserved, but new invitations/acceptances may be blocked until seats are removed or the package/entitlement is increased. <?php if($canManage):?><a href="<?=h($billingUrl)?>">Review billing/package options</a>.<?php endif?></div><?php endif?>
<?php if($account['status']!=='active'):?><div class="error"><strong><?=h(ucfirst((string)$account['status']))?> account.</strong> New invitations and invitation acceptance are unavailable until this commercial account is active.</div><?php endif?>
<?php if($canManage):?><section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">INVITE</span><h2>Invite an account member</h2></div><span class="badge"><?=h((string)$seats['available_seats'])?> seats available</span></div><form method="post" class="accountInviteForm"><?=csrf_field()?><input type="hidden" name="account" value="<?=h((string)$account['public_id'])?>"><input type="hidden" name="action" value="invite"><label>Email<input type="email" name="email" required placeholder="person@example.com"></label><label>Role<select name="account_role"><option value="member">Member</option><option value="admin">Account admin</option></select></label><label>Expires<select name="expires_days"><option value="3">3 days</option><option value="7" selected>7 days</option><option value="14">14 days</option><option value="30">30 days</option></select></label><label class="accountSeatCheckbox"><input type="checkbox" name="reserve_seat" value="1" checked> Reserve a seat while pending</label><label>Reason<input name="reason" maxlength="500" value="Invite account member." required></label><button <?=$account['status']!=='active'||$seats['full']?'disabled':''?>>Create invitation</button></form><p class="meta"><?=$mail['enabled']?'Invitation email delivery is enabled. A secure copyable link is also returned after creation.':'Email delivery is disabled in config. Invitations still work through secure copyable links.'?></p></section><?php endif?>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">MEMBERS</span><h2>Account members</h2></div><span class="badge"><?=h((string)$seats['member_count'])?> occupied</span></div><div class="tableWrap"><table><thead><tr><th>User</th><th>Role</th><th>Joined</th><?php if($canManage):?><th>Administration</th><?php endif?></tr></thead><tbody><?php foreach($members as $m):?><tr><td><strong><?=h((string)$m['display_name'])?></strong><div class="meta">@<?=h((string)$m['username'])?> · <?=h((string)$m['email'])?></div></td><td><?=h((string)$m['account_role'])?></td><td><?=h((string)$m['joined_at'])?></td><?php if($canManage):?><td><?php if($m['account_role']==='owner'):?><span class="meta">Owner protected.</span><?php else:?><form method="post" class="adminMemberActionForm"><?=csrf_field()?><input type="hidden" name="account" value="<?=h((string)$account['public_id'])?>"><input type="hidden" name="action" value="member_role"><input type="hidden" name="user_id" value="<?=h((string)$m['user_id'])?>"><select name="account_role"><option value="member" <?=$m['account_role']==='member'?'selected':''?>>Member</option><option value="admin" <?=$m['account_role']==='admin'?'selected':''?>>Account admin</option></select><input name="reason" required value="Update account member role."><button>Update</button></form><form method="post" class="adminMemberActionForm"><?=csrf_field()?><input type="hidden" name="account" value="<?=h((string)$account['public_id'])?>"><input type="hidden" name="action" value="remove_member"><input type="hidden" name="user_id" value="<?=h((string)$m['user_id'])?>"><input name="reason" required value="Remove account member."><button class="button secondary">Remove</button></form><?php if($isOwner&&$account['account_type']!=='personal'):?><form method="post" class="adminMemberActionForm"><?=csrf_field()?><input type="hidden" name="account" value="<?=h((string)$account['public_id'])?>"><input type="hidden" name="action" value="transfer_owner"><input type="hidden" name="user_id" value="<?=h((string)$m['user_id'])?>"><input name="reason" required value="Transfer account ownership."><button class="button secondary">Make owner</button></form><?php endif?><?php endif?></td><?php endif?></tr><?php endforeach?></tbody></table></div></section>
<?php if($canManage):?><section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">INVITATIONS</span><h2>Invitation lifecycle</h2></div></div><div class="tableWrap"><table><thead><tr><th>Email</th><th>Role</th><th>Status</th><th>Seat</th><th>Expires</th><th>Delivery</th><th>Actions</th></tr></thead><tbody><?php foreach($invitations as $i):?><tr><td><?=h((string)$i['invited_email'])?></td><td><?=h((string)$i['account_role'])?></td><td><?=h((string)$i['status'])?></td><td><?=((int)$i['reserves_seat'])?'Reserved':'At acceptance'?></td><td><?=h((string)$i['expires_at'])?></td><td><?=h((string)$i['delivery_status'])?><?php if($i['last_delivery_error']):?><div class="meta"><?=h((string)$i['last_delivery_error'])?></div><?php endif?></td><td><?php if($i['status']==='pending'):?><form method="post" class="inlineActions"><?=csrf_field()?><input type="hidden" name="account" value="<?=h((string)$account['public_id'])?>"><input type="hidden" name="action" value="resend"><input type="hidden" name="invitation_id" value="<?=h((string)$i['public_id'])?>"><input type="hidden" name="expires_days" value="7"><input type="hidden" name="reason" value="Resend account invitation."><button class="button secondary">Resend / new link</button></form><form method="post" class="inlineActions"><?=csrf_field()?><input type="hidden" name="account" value="<?=h((string)$account['public_id'])?>"><input type="hidden" name="action" value="revoke"><input type="hidden" name="invitation_id" value="<?=h((string)$i['public_id'])?>"><input type="hidden" name="reason" value="Revoke account invitation."><button class="button secondary">Revoke</button></form><?php else:?><span class="meta">Complete</span><?php endif?></td></tr><?php endforeach?><?php if(!$invitations):?><tr><td colspan="7" class="empty">No invitations yet.</td></tr><?php endif?></tbody></table></div></section>
<section class="card"><span class="eyebrow">MEMBERSHIP AUDIT</span><h2>Membership history</h2><?php foreach($events as $e):?><div class="historyItem"><strong><?=h(ucwords(str_replace('_',' ',(string)$e['event_type'])))?></strong><div class="meta"><?=h((string)$e['created_at'])?> · <?=h((string)($e['actor_username']?:'System'))?><?php if($e['subject_username']):?> · @<?=h((string)$e['subject_username'])?><?php elseif($e['invited_email']):?> · <?=h((string)$e['invited_email'])?><?php endif?></div><p><?=h((string)$e['reason'])?></p></div><?php endforeach?><?php if(!$events):?><p class="empty">No V1.50 membership events yet.</p><?php endif?></section><?php endif?>
</main></body></html>