<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';
require_once __DIR__.'/app/unified-activity.php';
$u=require_user($pdo);header('Cache-Control: private, no-store');header('Vary: Cookie');
$items=unified_activity_collect($pdo,$u,100);
function activity_icon(string $surface): string {return match($surface){'annotation'=>'✎','team'=>'◌','research'=>'▣','agent'=>'✦','publish'=>'↗',default=>'•'};}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Activity · Annotated</title><meta name="robots" content="noindex,nofollow"><link rel="stylesheet" href="/assets/css/app.css"></head><body data-workspace-user="<?=h((string)$u['public_id'])?>" data-workspace-surface="activity">
<header class="topbar"><a class="brand" href="/home.php">Annotated</a><nav><a href="/home.php">Home</a><a href="/action-center.php">Actions</a><a href="/activity.php">Activity</a><a href="/research.php">Research</a><a href="/teams.php">Teams</a><a href="/settings.php">Settings</a></nav></header>
<main class="panel unifiedActivityPage"><div class="pageTitle"><span class="eyebrow">WORKSPACE ACTIVITY</span><h1>What happened across Annotated</h1><p>One permission-checked timeline derived from your Annotations, Teams, Research, Agent actions, and publications. Activity disappears if you lose access to the underlying object.</p></div>
<?php if(!$items):?><div class="card empty">No workspace activity yet.</div><?php endif?>
<div class="unifiedActivityList"><?php foreach($items as $item):?><article class="card unifiedActivityItem"><div class="unifiedActivityIcon" aria-hidden="true"><?=h(activity_icon((string)$item['surface']))?></div><div class="unifiedActivityMain"><div class="unifiedActivityHead"><div><span class="badge"><?=h(ucfirst((string)$item['surface']))?></span><strong><?=h((string)$item['title'])?></strong></div><time><?=h((string)$item['created_at'])?></time></div><?php if($item['body']!==''):?><p><?=h((string)$item['body'])?></p><?php endif?><?php if(!empty($item['meta'])):?><div class="cognitiveCardMeta"><?php foreach($item['meta'] as $k=>$v):if($v===null||$v==='')continue;?><span><small><?=h(ucfirst(str_replace('_',' ',(string)$k)))?></small><?=h((string)$v)?></span><?php endforeach?></div><?php endif?><div class="inlineActions"><?php if($item['href']!==''):?><a class="button secondary" data-activity-open-context href="<?=h((string)$item['href'])?>" data-context="<?=h(json_encode((array)($item['context']??[]),JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE))?>" data-object-type="<?=h((string)($item['object']['type']??''))?>" data-object-id="<?=h((string)($item['object']['public_id']??''))?>">Open</a><?php endif?><?php if(!empty($item['context'])&&(user_is_pro($pdo,$u)||($u['role']??'')==='admin')):?><button type="button" class="button secondary" data-activity-agent data-prompt="<?=h('Review this workspace activity and explain what changed, why it matters, and the most useful next step. Do not change anything without confirmation.')?>" data-context="<?=h(json_encode($item['context'],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE))?>">Ask Agent</button><?php endif?></div></div></article><?php endforeach?></div>
</main><script src="/assets/js/activity.js?v=36.0"></script><script src="/assets/js/workspace-state.js?v=36.0"></script></body></html>
