<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';require_once __DIR__.'/app/public-discovery.php';require_once __DIR__.'/app/annotation-ui.php';
$viewer=current_user($pdo);$id=(string)($_GET['id']??'');if($viewer){header('Cache-Control: private, no-store');header('Vary: Cookie');}$a=public_discovery_annotation($pdo,$id,$viewer);if(!$a){http_response_code(404);exit('Annotation not found.');}
$comments=public_discovery_comments($pdo,$a,$viewer);$relatedRows=search_related_annotations($pdo,$a['public_id'],$viewer,6);$relatedAnnotations=[];foreach($relatedRows as $row){$full=public_discovery_annotation($pdo,(string)($row['public_id']??''),$viewer);if($full)$relatedAnnotations[]=$full;}$isPublic=$a['visibility']==='public';$pageTitle=trim((string)($a['text_commentary']?:$a['selected_text']?:$a['source_title']?:'Annotation'));
$metaTitle=mb_substr($pageTitle,0,90);$desc=public_discovery_meta_description((string)($a['text_commentary']?:$a['selected_text']?:('Annotation on '.$a['source_title'])));
$canonical=public_discovery_absolute_url($config,'/annotation.php?id='.rawurlencode($a['public_id']));
$showDiscussion=(string)($_GET['comments']??'')==='1';
$extraActions=[];
if($viewer&&(int)$viewer['id']!==(int)$a['user_id'])$extraActions[]='<button type="button" id="followAuthor" data-user="'.h($a['author_public_id']).'">'.($a['is_following']?'Following':'Follow author').'</button>';
if($viewer)$extraActions[]='<button type="button" id="followSource" data-source="'.h($a['source_public_id']).'">'.($a['source_following']?'Following source':'Follow source').'</button>';
if($viewer&&((int)$viewer['id']===(int)$a['user_id']||($viewer['role']??'')==='admin'))$extraActions[]='<button type="button" data-intelligence-refresh data-id="'.h($a['public_id']).'">Refresh intelligence</button>';
$extraActionsHtml=implode('',$extraActions);
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=h($metaTitle)?> · Annotated</title><meta name="description" content="<?=h($desc)?>"><?php if(!$isPublic):?><meta name="robots" content="noindex,nofollow"><?php endif?><link rel="canonical" href="<?=h($canonical)?>">
<?php if($isPublic):?><meta property="og:type" content="article"><meta property="og:title" content="<?=h($metaTitle)?> · Annotated"><meta property="og:description" content="<?=h($desc)?>"><meta property="og:url" content="<?=h($canonical)?>"><?php if($a['screenshot_url']):?><meta property="og:image" content="<?=h(public_discovery_absolute_url($config,$a['screenshot_url']))?>"><?php endif?><?php endif?><link rel="stylesheet" href="/assets/css/app.css"></head><body<?php if($viewer):?> data-workspace-user="<?=h((string)$viewer['public_id'])?>" data-workspace-surface="annotation" data-workspace-object-type="annotation" data-workspace-object="<?=h((string)$a['public_id'])?>"<?php endif?>>
<main class="layout annotationLayout"><section>
<?=annotation_ui_card($a,$viewer,['show_open'=>false,'comments_href'=>'#discussion','extra_actions_html'=>$extraActionsHtml])?>
<section id="discussion" class="annotationDiscussion" <?=$showDiscussion?'':'hidden'?>>
  <div class="sectionHeadWeb"><div><span class="eyebrow">DISCUSSION</span><h2><?=count($comments)?> comments</h2></div></div>
  <div id="discussionList"><?php if(!$comments):?><div class="card empty">No comments yet.</div><?php endif?><?php foreach($comments as $c):?><article class="commentWebCard <?=$c['parent_comment_id']?'reply':''?>" data-comment-id="<?=h($c['id'])?>"><a class="commentAuthorIdentity" href="<?=h(profile_path((string)$c['username']))?>"><?=app_shell_avatar(['display_name'=>$c['display_name'],'profile_image_url'=>$c['profile_image_url']??null],'avatarSm')?><span><strong><?=h($c['display_name'])?></strong><small>@<?=h($c['username'])?> · <?=h($c['created_at'])?></small></span></a><p><?=nl2br(h($c['body']))?></p><?php if($viewer):?><button class="textButton replyButton" type="button" data-id="<?=h($c['id'])?>" data-author="<?=h($c['display_name'])?>">Reply</button><?php endif?><?php if(!empty($c['public_id'])):?><a class="textButton" href="/report.php?type=comment&id=<?=h($c['public_id'])?>">Report</a><?php endif?></article><?php endforeach?></div>
  <?php if($viewer):?><form id="commentForm" class="card stack"><div id="replyTarget" class="meta" hidden></div><textarea id="commentBody" maxlength="5000" placeholder="Add to the discussion" required></textarea><div class="inlineActions"><button type="button" class="button secondary" id="cancelReply" hidden>Cancel reply</button><button>Post comment</button></div></form><?php else:?><div class="card"><a href="/login.php">Log in</a> to join the discussion.</div><?php endif?>
</section>
<div class="sectionHeadWeb"><div><span class="eyebrow">RELATED</span><h2>Related annotations</h2></div><a href="/search.php?q=<?=urlencode(mb_substr((string)($a['selected_text']?:$a['text_commentary']?:$a['source_title']),0,120))?>">Find more</a></div><div class="relatedAnnotations"><?php foreach($relatedAnnotations as $r):?><?=annotation_ui_card($r,$viewer)?><?php endforeach?><?php if(!$relatedAnnotations):?><div class="card">Related annotations will appear as this source and its entities accumulate more research.</div><?php endif?></div>
</section>
<aside><div class="card"><h3>About this annotation</h3><p class="meta">Annotation type</p><p><?=h(annotation_type_label($a))?></p><p class="meta">Visibility</p><p><?=h(ucfirst($a['visibility']))?></p><p class="meta">Published</p><p><?=h((string)$a['published_at'])?></p></div><div class="card"><h3>Why provenance matters</h3><p>Annotated keeps this annotation tied to the exact captured source version even if the live page changes later.</p></div></aside></main>
<script>
document.querySelector('a[href="#discussion"]')?.addEventListener('click',e=>{e.preventDefault();const d=document.querySelector('#discussion');if(d){d.hidden=false;d.scrollIntoView({behavior:'smooth',block:'start'});}});
</script>
<?php if($viewer):?><script>
const csrf=<?=json_encode(csrf_token())?>,annotationId=<?=json_encode($a['public_id'])?>;let replyParent=null;
async function mutate(action,payload){const r=await fetch('/api/extension.php?action='+encodeURIComponent(action),{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok||j.ok===false)throw new Error(j.error?.message||j.error?.code||'Request failed');return j.data;}
document.querySelector('#followAuthor')?.addEventListener('click',async e=>{try{const d=await mutate('follow',{user_id:e.currentTarget.dataset.user});e.currentTarget.textContent=d.following?'Following':'Follow author';}catch(x){alert(x.message)}});
document.querySelector('#followSource')?.addEventListener('click',async e=>{try{const d=await mutate('watch_source',{source:e.currentTarget.dataset.source});e.currentTarget.textContent=d.following?'Following source':'Follow source';}catch(x){alert(x.message)}});
document.querySelectorAll('.replyButton').forEach(b=>b.addEventListener('click',()=>{replyParent=b.dataset.id;const t=document.querySelector('#replyTarget');t.textContent='Replying to '+b.dataset.author;t.hidden=false;document.querySelector('#cancelReply').hidden=false;document.querySelector('#commentBody').focus();}));
document.querySelector('#cancelReply')?.addEventListener('click',e=>{replyParent=null;e.currentTarget.hidden=true;document.querySelector('#replyTarget').hidden=true;});
document.querySelector('#commentForm')?.addEventListener('submit',async e=>{e.preventDefault();const body=document.querySelector('#commentBody').value.trim();if(!body)return;try{await mutate('comment',{annotation_id:annotationId,body,parent_comment_id:replyParent});location.reload();}catch(x){alert(x.message)}});
document.querySelector('#editTranscript')?.addEventListener('click',async()=>{const current=<?=json_encode($a['transcript_edited']?:$a['transcript_raw']?:'')?>;const text=prompt('Correct the transcript:',current);if(text===null)return;try{await mutate('transcript_edit',{annotation_id:annotationId,text});location.reload();}catch(x){alert(x.message)}});
</script><?php endif?><?=annotation_ui_scripts($viewer)?><?php if($viewer):?><script src="/assets/js/workspace-state.js?v=34.0"></script><?php endif?></body></html>