<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';require_once __DIR__.'/app/public-discovery.php';
$viewer=current_user($pdo);$id=(string)($_GET['id']??'');$a=public_discovery_annotation($pdo,$id,$viewer);if(!$a){http_response_code(404);exit('Annotation not found.');}
$comments=public_discovery_comments($pdo,$a,$viewer);$isPublic=$a['visibility']==='public';$pageTitle=trim((string)($a['text_commentary']?:$a['selected_text']?:$a['source_title']?:'Annotation'));
$metaTitle=mb_substr($pageTitle,0,90);$desc=public_discovery_meta_description((string)($a['text_commentary']?:$a['selected_text']?:('Annotation on '.$a['source_title'])));
$canonical=public_discovery_absolute_url($config,'/annotation.php?id='.rawurlencode($a['public_id']));
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=h($metaTitle)?> · Annotated</title><meta name="description" content="<?=h($desc)?>"><?php if(!$isPublic):?><meta name="robots" content="noindex,nofollow"><?php endif?><link rel="canonical" href="<?=h($canonical)?>">
<?php if($isPublic):?><meta property="og:type" content="article"><meta property="og:title" content="<?=h($metaTitle)?> · Annotated"><meta property="og:description" content="<?=h($desc)?>"><meta property="og:url" content="<?=h($canonical)?>"><?php if($a['screenshot_url']):?><meta property="og:image" content="<?=h(public_discovery_absolute_url($config,$a['screenshot_url']))?>"><?php endif?><?php endif?><link rel="stylesheet" href="/assets/css/app.css"></head><body>
<header class="topbar"><a class="brand" href="/">Annotated</a><nav><a href="/explore.php">Explore</a><a href="/search.php">Search</a><a href="/source.php?id=<?=h($a['source_public_id'])?>">Source</a><?php if($viewer):?><a href="/research.php">Research</a><a href="/saved.php">Saved</a><?php else:?><a href="/login.php">Log in</a><?php endif?></nav></header>
<main class="layout annotationLayout"><section><div class="pageTitle"><div class="annotationIdentity"><a class="profileMini" href="/profile.php?u=<?=h($a['username'])?>"><span class="avatarSm"><?=h(mb_strtoupper(mb_substr($a['display_name'],0,1)))?></span><span><strong><?=h($a['display_name'])?></strong><small>@<?=h($a['username'])?></small></span></a><span class="meta"><?=h((string)$a['published_at'])?></span></div>
<div class="inlineActions"><?php if($a['visibility']!=='public'):?><span class="badge"><?=h(ucfirst($a['visibility']))?><?php if($a['team_name']):?> · <?=h($a['team_name'])?><?php endif?></span><?php endif?><?php if($a['source_changed']):?><span class="badge warn">Captured v<?=h((string)$a['capture_version_number'])?> · current v<?=h((string)$a['current_version_number'])?></span><?php endif?></div>
<h1><?=h($pageTitle)?></h1><?php if($a['text_commentary']&&$a['selected_text']):?><blockquote><?=h($a['selected_text'])?></blockquote><?php endif?></div>
<?php if($a['screenshot_url']):?><figure><img class="snapshot annotationSnapshot" src="<?=h($a['screenshot_url'])?>" alt="Preserved screenshot of annotated content"><figcaption class="meta">Preserved at capture time · Source version <?=h((string)$a['capture_version_number'])?></figcaption></figure><?php endif?>
<?php if($a['media_url']):?><?php if($a['capture_type']==='video_clip'):?><video class="webMedia" controls src="<?=h($a['media_url'])?>"></video><?php else:?><audio class="wideAudio" controls src="<?=h($a['media_url'])?>"></audio><?php endif?><?php elseif(in_array($a['capture_type'],['video_clip','audio_clip'],true)):?><div class="card"><strong>Captured clip <?=h((string)$a['start_seconds'])?> → <?=h((string)$a['end_seconds'])?></strong><p class="meta">Media derivative: <?=h((string)($a['media_status']?:'queued'))?></p></div><?php endif?>
<?php if(in_array($a['capture_type'],['video_clip','audio_clip'],true)):?><div class="card provenanceCard"><span class="eyebrow">MEDIA PROVENANCE</span><h3><?=h((string)($a['media_title']?:$a['source_title']?:'Captured media'))?></h3><p class="meta"><?=h(strtoupper((string)($a['media_provider']?:'web')))?><?php if($a['media_author']):?> · <?=h($a['media_author'])?><?php endif?><?php if($a['provider_media_id']):?> · provider ID <?=h($a['provider_media_id'])?><?php endif?></p><p>Source timestamp <?=h((string)$a['start_seconds'])?> → <?=h((string)$a['end_seconds'])?><?php if($a['source_media_duration_seconds']):?> · source duration <?=h((string)$a['source_media_duration_seconds'])?>s<?php endif?></p></div><?php endif?>
<?php if($a['audio_url']):?><div class="card"><h2>Audio commentary</h2><audio class="wideAudio" controls src="<?=h($a['audio_url'])?>"></audio><details open><summary>Transcript · <?=h((string)($a['transcript_status']?:'queued'))?></summary><?php $transcript=$a['transcript_edited']?:$a['transcript_raw'];if($transcript):?><p><?=nl2br(h($transcript))?></p><?php else:?><p class="meta">Transcription is <?=h((string)($a['transcript_status']?:'queued'))?>.</p><?php endif?></details><?php if($viewer&&((int)$viewer['id']===(int)$a['user_id']||$viewer['role']==='admin')):?><button class="button secondary" id="editTranscript">Edit transcript</button><?php endif?></div><?php endif?>
<div class="card sourceContextCard"><span class="eyebrow">SOURCE CONTEXT</span><h2><?=h((string)($a['source_title']?:$a['canonical_url']))?></h2><p class="sourceUrl"><?=h($a['canonical_url'])?></p><div class="sourceStats"><span>Captured <strong>v<?=h((string)$a['capture_version_number'])?></strong></span><?php if($a['current_version_number']):?><span>Current <strong>v<?=h((string)$a['current_version_number'])?></strong></span><?php endif?><span>Status <strong><?=h(ucfirst((string)$a['source_status']))?></strong></span></div><div class="inlineActions"><a href="/source.php?id=<?=h($a['source_public_id'])?>">Annotated source page</a><?php if($a['context_url']):?><a href="<?=h($a['context_url'])?>" target="_blank" rel="noopener">Open original context ↗</a><?php endif?><?php if($a['source_changed']):?><a href="/source.php?id=<?=h($a['source_public_id'])?>">Review source history</a><?php endif?></div></div>
<div class="inlineActions actionRail"><button type="button" class="button secondary" id="copyLink">Copy link</button><?php if($viewer):?><button type="button" class="button secondary" id="save"><?=$a['is_saved']?'Saved':'Save'?></button><?php if((int)$viewer['id']!==(int)$a['user_id']):?><button type="button" class="button secondary" id="followAuthor" data-user="<?=h($a['author_public_id'])?>"><?=$a['is_following']?'Following':'Follow author'?></button><?php endif?><button type="button" class="button secondary" id="followSource" data-source="<?=h($a['source_public_id'])?>"><?=$a['source_following']?'Following source':'Follow source'?></button><button type="button" class="button secondary" id="addResearch">Add to Research</button><?php endif?><?php if($isPublic):?><a class="button secondary" href="/file-a-claim.php?id=<?=h($a['public_id'])?>">File a claim</a><a class="button secondary" href="/report.php?id=<?=h($a['public_id'])?>">Report</a><?php endif?></div>
<hr><div class="sectionHeadWeb"><div><span class="eyebrow">DISCUSSION</span><h2><?=count($comments)?> comments</h2></div></div><div id="discussion"><?php if(!$comments):?><div class="card empty">No comments yet.</div><?php endif?><?php foreach($comments as $c):?><article class="commentWebCard <?=$c['parent_comment_id']?'reply':''?>" data-comment-id="<?=h($c['id'])?>"><div class="meta"><strong><?=h($c['display_name'])?></strong> @<?=h($c['username'])?> · <?=h($c['created_at'])?></div><p><?=nl2br(h($c['body']))?></p><?php if($viewer):?><button class="textButton replyButton" type="button" data-id="<?=h($c['id'])?>" data-author="<?=h($c['display_name'])?>">Reply</button><?php endif?></article><?php endforeach?></div>
<?php if($viewer):?><form id="commentForm" class="card stack"><div id="replyTarget" class="meta" hidden></div><textarea id="commentBody" maxlength="5000" placeholder="Add to the discussion" required></textarea><div class="inlineActions"><button type="button" class="button secondary" id="cancelReply" hidden>Cancel reply</button><button>Post comment</button></div></form><?php else:?><div class="card"><a href="/login.php">Log in</a> to join the discussion.</div><?php endif?></section>
<aside><div class="card"><h3>About this annotation</h3><p class="meta">Capture type</p><p><?=h(str_replace('_',' ',ucwords($a['capture_type'],'_')))?></p><p class="meta">Visibility</p><p><?=h(ucfirst($a['visibility']))?></p><p class="meta">Published</p><p><?=h((string)$a['published_at'])?></p></div><div class="card"><h3>Why provenance matters</h3><p>Annotated keeps this annotation tied to the exact captured source version even if the live page changes later.</p></div></aside></main>
<dialog id="researchDialog"><form method="dialog" class="stack"><h3>Add to Research</h3><select id="projectSelect"></select><div class="inlineActions"><button value="cancel" class="button secondary">Cancel</button><button type="button" id="confirmResearch">Add</button></div></form></dialog>
<script>document.querySelector('#copyLink')?.addEventListener('click',async e=>{await navigator.clipboard.writeText(location.href);e.currentTarget.textContent='Copied';});</script>
<?php if($viewer):?><script>
const csrf=<?=json_encode(csrf_token())?>,annotationId=<?=json_encode($a['public_id'])?>;let replyParent=null;
async function mutate(action,payload){const r=await fetch('/api/extension.php?action='+encodeURIComponent(action),{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok||j.ok===false)throw new Error(j.error?.message||j.error?.code||'Request failed');return j.data;}
document.querySelector('#save')?.addEventListener('click',async e=>{try{const d=await mutate('save',{annotation_id:annotationId});e.currentTarget.textContent=d.saved?'Saved':'Save';}catch(x){alert(x.message)}});
document.querySelector('#followAuthor')?.addEventListener('click',async e=>{try{const d=await mutate('follow',{user_id:e.currentTarget.dataset.user});e.currentTarget.textContent=d.following?'Following':'Follow author';}catch(x){alert(x.message)}});
document.querySelector('#followSource')?.addEventListener('click',async e=>{try{const d=await mutate('watch_source',{source:e.currentTarget.dataset.source});e.currentTarget.textContent=d.following?'Following source':'Follow source';}catch(x){alert(x.message)}});
document.querySelectorAll('.replyButton').forEach(b=>b.addEventListener('click',()=>{replyParent=b.dataset.id;const t=document.querySelector('#replyTarget');t.textContent='Replying to '+b.dataset.author;t.hidden=false;document.querySelector('#cancelReply').hidden=false;document.querySelector('#commentBody').focus();}));
document.querySelector('#cancelReply')?.addEventListener('click',e=>{replyParent=null;e.currentTarget.hidden=true;document.querySelector('#replyTarget').hidden=true;});
document.querySelector('#commentForm')?.addEventListener('submit',async e=>{e.preventDefault();const body=document.querySelector('#commentBody').value.trim();if(!body)return;try{await mutate('comment',{annotation_id:annotationId,body,parent_comment_id:replyParent});location.reload();}catch(x){alert(x.message)}});
document.querySelector('#addResearch')?.addEventListener('click',async()=>{try{const r=await fetch('/api/extension.php?action=research_projects');const j=await r.json();if(!j.ok)throw new Error('Unable to load Research projects');const ps=j.data.projects||[];if(!ps.length){alert('No writable Research projects yet.');return;}document.querySelector('#projectSelect').innerHTML=ps.map(p=>'<option value="'+String(p.public_id).replaceAll('"','&quot;')+'">'+String(p.title).replaceAll('<','&lt;')+'</option>').join('');document.querySelector('#researchDialog').showModal();}catch(x){alert(x.message)}});
document.querySelector('#confirmResearch')?.addEventListener('click',async()=>{try{await mutate('research_add',{project_id:document.querySelector('#projectSelect').value,annotation_id:annotationId});document.querySelector('#researchDialog').close();document.querySelector('#addResearch').textContent='Added to Research';}catch(x){alert(x.message)}});
document.querySelector('#editTranscript')?.addEventListener('click',async()=>{const current=<?=json_encode($a['transcript_edited']?:$a['transcript_raw']?:'')?>;const text=prompt('Correct the transcript:',current);if(text===null)return;try{await mutate('transcript_edit',{annotation_id:annotationId,text});location.reload();}catch(x){alert(x.message)}});
</script><?php endif?></body></html>