<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';
$user=require_user($pdo);$error='';$notice='';
if(!subscriptions_ready($pdo)){http_response_code(503);exit('Billing requires the latest database upgrade.');}
$accountId=trim((string)($_GET['account']??$_POST['account']??''));$account=stripe_billing_account_for_user($pdo,$user,$accountId!==''?$accountId:null);$accounts=stripe_billing_user_accounts($pdo,$user);
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();try{
    $op=(string)($_POST['op']??'');
    if($op==='checkout'){$session=stripe_billing_create_checkout_for_account($pdo,$config,$user,$account,(string)($_POST['package_id']??''));header('Location: '.(string)$session['url'],true,303);exit;}
    if($op==='portal'){$session=stripe_billing_create_portal_for_account($pdo,$config,$user,$account);header('Location: '.(string)$session['url'],true,303);exit;}
    if($op==='cancellation_feedback'){if(!billing_operations_ready($pdo))throw new RuntimeException('Cancellation feedback requires the latest database upgrade.');billing_operations_record_cancellation_feedback($pdo,$user,(int)$account['id'],'customer',(string)($_POST['reason_code']??'other'),(string)($_POST['feedback_text']??''),!empty($_POST['win_back_eligible']));$notice='Thanks — your cancellation feedback was recorded. This does not change your Stripe subscription.';}
    else throw new RuntimeException('Unknown billing action.');
}catch(Throwable $e){$error=$e->getMessage();}}
if(($_GET['checkout']??'')==='success')$notice='Checkout completed. Stripe is synchronizing this subscription; this page will reflect the webhook-confirmed state.';
elseif(($_GET['checkout']??'')==='cancelled')$notice='Checkout was cancelled. This Annotated account was not changed.';
$configured=stripe_billing_configured($pdo,$config);$summary=stripe_billing_ready($pdo)?stripe_billing_account_summary($pdo,(int)$account['id']):['customer'=>null,'subscription'=>null,'invoices'=>[],'events'=>[],'mode'=>'test'];$subscription=$summary['subscription'];$usage=ai_usage_ready($pdo)?ai_usage_account_summary($pdo,(int)$account['id']):null;$cancellationFeedback=billing_operations_ready($pdo)?billing_operations_feedback($pdo,(int)$account['id'],10):[];
$packages=[];if(stripe_billing_ready($pdo)){foreach(stripe_billing_package_rows($pdo) as $p){if($p['status']==='active'&&(int)$p['is_public']===1)$packages[]=$p;}}
$accountQuery='?account='.rawurlencode((string)$account['public_id']);
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Billing · Annotated</title><link rel="stylesheet" href="/assets/css/app.css"></head><body>
<main class="panel billingSelfServicePage"><div class="pageTitle"><span class="eyebrow">ACCOUNT BILLING</span><h1>Subscription & billing</h1><p>Stripe securely handles payment methods and recurring charges. Annotated controls packages, membership, AI allowance, and access.</p></div>
<?php if(count($accounts)>1):?><nav class="billingAccountSwitcher" aria-label="Billing accounts"><?php foreach($accounts as $a):?><a class="<?=$a['public_id']===$account['public_id']?'active':''?>" href="/billing.php?account=<?=h(rawurlencode((string)$a['public_id']))?>"><strong><?=h((string)$a['name'])?></strong><small><?=h((string)$a['account_type'])?> · <?=h((string)$a['account_role'])?></small></a><?php endforeach?></nav><?php endif?>
<?php if($notice):?><div class="success"><?=h($notice)?></div><?php endif?><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?>
<?php $displayPrice=$summary['subscription_price']??null;$displayAmount=$displayPrice?(int)$displayPrice['unit_amount_cents']:(int)$account['monthly_price_cents'];$displayCurrency=$displayPrice?strtoupper((string)$displayPrice['currency']):'USD';?>
<section class="billingSummaryGrid"><article class="card"><span class="meta">Billing account</span><strong><?=h((string)$account['name'])?></strong><small><?=h((string)$account['account_type'])?> account</small></article><article class="card"><span class="meta">Current package</span><strong><?=h((string)$account['package_name'])?></strong><small><?=h((string)$account['subscription_status'])?> · <?=h((string)($account['billing_source']??'manual'))?></small></article><article class="card"><span class="meta">Monthly price</span><strong><?=h($displayCurrency)?> <?=h(number_format($displayAmount/100,2))?></strong><small><?=$displayPrice?'Current Stripe Price':'Annotated package price'?></small></article><article class="card"><span class="meta">AI tokens</span><strong><?=$usage?($usage['remaining_tokens']===null?'Uncapped':h(number_format((int)$usage['remaining_tokens'])).' remaining'):'—'?></strong><small><?=$usage?h(number_format((int)$usage['used_tokens'])).' used this period':'Usage unavailable'?></small></article><article class="card"><span class="meta">Billing period</span><strong><?=h((string)$account['period_start'])?></strong><small>through <?=h((string)$account['period_end'])?></small></article></section>
<?php if($account['subscription_status']==='past_due'):?><div class="error"><strong>Payment needs attention.</strong> This account is in a billing grace state. Use Stripe billing management to update the payment method or resolve the invoice.</div><?php endif?>
<?php if($subscription):?><section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">STRIPE SUBSCRIPTION</span><h2>Manage recurring billing</h2></div></div><div class="billingSubscriptionFacts"><div><span>Status</span><strong><?=h((string)$subscription['status'])?></strong></div><div><span>Renews / period ends</span><strong><?=h((string)($subscription['current_period_end']?:'—'))?></strong></div><div><span>Cancel at period end</span><strong><?=((int)$subscription['cancel_at_period_end'])?'Yes':'No'?></strong></div></div><?php if($configured):?><form method="post"><?=csrf_field()?><input type="hidden" name="account" value="<?=h((string)$account['public_id'])?>"><input type="hidden" name="op" value="portal"><button>Manage billing in Stripe</button></form><?php endif?></section><?php endif?>
<?php if($subscription&&billing_operations_ready($pdo)):?><section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">CANCELLATION FEEDBACK</span><h2>Help us understand cancellation decisions</h2></div></div><p>This records feedback only. Use Stripe billing management above to actually change or cancel the subscription.</p><form method="post" class="billingFeedbackForm"><?=csrf_field()?><input type="hidden" name="account" value="<?=h((string)$account['public_id'])?>"><input type="hidden" name="op" value="cancellation_feedback"><label>Reason<select name="reason_code"><option value="price">Price</option><option value="missing_features">Missing features</option><option value="not_using">Not using enough</option><option value="temporary">Temporary pause/need</option><option value="support">Support experience</option><option value="competitor">Using another product</option><option value="business_closed">Business closed</option><option value="other">Other</option></select></label><label>Details<textarea name="feedback_text" rows="3" maxlength="2000"></textarea></label><label><input type="checkbox" name="win_back_eligible" value="1" checked> Okay to consider for a future win-back offer</label><button class="button secondary">Save feedback</button></form><?php if($cancellationFeedback):?><p class="meta">Latest feedback: <?=h((string)$cancellationFeedback[0]['reason_code'])?> · <?=h((string)$cancellationFeedback[0]['created_at'])?></p><?php endif?></section><?php endif?>
<?php if(!$subscription):?><section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">PLANS</span><h2>Choose a paid package</h2></div></div><?php if(!$configured):?><p class="empty">Online billing is not available yet. This account remains under its existing package state.</p><?php else:?><div class="billingPlanGrid"><?php foreach($packages as $p):if((int)$p['monthly_price_cents']<=0)continue;$map=$p['stripe_price']??null;?><article class="billingPlanCard"><h3><?=h((string)$p['name'])?></h3><div class="billingPlanPrice">$<?=h(number_format(((int)$p['monthly_price_cents'])/100,2))?><small>/ month</small></div><p><?=h((string)($p['description']??''))?></p><div class="meta"><?=h(number_format((int)($p['monthly_ai_token_allowance']??0)))?> AI tokens · <?=h((string)$p['member_limit'])?> member<?=((int)$p['member_limit']===1?'':'s')?></div><?php if($map):?><form method="post"><?=csrf_field()?><input type="hidden" name="account" value="<?=h((string)$account['public_id'])?>"><input type="hidden" name="op" value="checkout"><input type="hidden" name="package_id" value="<?=h((string)$p['public_id'])?>"><button><?=((int)$account['package_id']===(int)$p['id'])?'Start paid billing':'Choose '.h((string)$p['name'])?></button></form><?php else:?><span class="meta">Online purchase not configured for this package.</span><?php endif?></article><?php endforeach?></div><?php endif?></section><?php endif?>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">INVOICES</span><h2>Billing history</h2></div><?php if($summary['customer']&&$configured):?><form method="post"><?=csrf_field()?><input type="hidden" name="account" value="<?=h((string)$account['public_id'])?>"><input type="hidden" name="op" value="portal"><button class="button secondary">Payment methods & invoices</button></form><?php endif?></div><div class="tableWrap"><table><thead><tr><th>Invoice</th><th>Status</th><th>Amount</th><th>Paid</th><th>Date</th><th></th></tr></thead><tbody><?php foreach($summary['invoices'] as $i):$hosted=(string)($i['hosted_invoice_url']??'');?><tr><td><?=h((string)($i['invoice_number']?:$i['stripe_invoice_id']))?></td><td><?=h((string)$i['status'])?></td><td><?=h(strtoupper((string)$i['currency']))?> <?=h(number_format(((int)$i['amount_due_cents'])/100,2))?></td><td><?=h(number_format(((int)$i['amount_paid_cents'])/100,2))?></td><td><?=h((string)$i['created_at'])?></td><td><?php if(str_starts_with($hosted,'https://')):?><a href="<?=h($hosted)?>" target="_blank" rel="noopener noreferrer">View</a><?php endif?></td></tr><?php endforeach?><?php if(!$summary['invoices']):?><tr><td colspan="6" class="empty">No Stripe invoices yet.</td></tr><?php endif?></tbody></table></div></section>
</main></body></html>