<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';$viewer=current_user($pdo);header('Cache-Control: private, no-store');header('Vary: Cookie');header('Referrer-Policy: no-referrer');
$id=(string)($_GET['id']??$_POST['id']??'');$incomingToken=(string)($_GET['token']??'');
if($incomingToken!==''&&$_SERVER['REQUEST_METHOD']==='GET'){$probe=rights_claim_access($pdo,$id,$viewer,$incomingToken);if($probe){$_SESSION['claim_tracking_tokens'][$id]=$incomingToken;header('Location: /claim-status.php?id='.rawurlencode($id),true,303);exit;}}
$token=(string)($_SESSION['claim_tracking_tokens'][$id]??'');$claim=rights_claim_access($pdo,$id,$viewer,$token?:null);if(!$claim){http_response_code(404);exit('Claim not found.');}
$error='';$success='';
if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['action']??'')==='appeal'){require_csrf();try{rights_claim_appeal($pdo,$claim,$viewer,(string)($_POST['note']??''));$success='Appeal submitted for human review.';$claim=rights_claim_access($pdo,$id,$viewer,$token?:null)?:$claim;}catch(Throwable $e){$error=$e->getMessage();}}
$events=rights_claim_events($pdo,(int)$claim['id']);$canAppeal=in_array($claim['status'],['resolved','rejected','restricted'],true);
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Claim status · Annotated</title><meta name="robots" content="noindex,nofollow"><link rel="stylesheet" href="/assets/css/app.css"></head><body><main class="panel narrow"><span class="eyebrow">CLAIM STATUS</span><h1><?=h(ucwords(str_replace('_',' ',(string)$claim['status'])))?></h1><p class="meta">Claim <?=h($claim['public_id'])?> · <?=h($claim['claim_type'])?> · submitted <?=h($claim['created_at'])?></p>
<?php if($success):?><div class="success"><?=h($success)?></div><?php endif?><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?>
<div class="card"><p><?=nl2br(h((string)$claim['description']))?></p><p><a href="/annotation.php?id=<?=h($claim['annotation_public_id'])?>">Open annotation</a> · <a href="<?=h($claim['canonical_url'])?>" target="_blank" rel="noopener">Original source ↗</a></p><?php if($claim['decision_summary']):?><p><strong>Decision:</strong> <?=nl2br(h((string)$claim['decision_summary']))?></p><?php endif?><?php if($claim['moderator_note']):?><p class="meta"><?=nl2br(h((string)$claim['moderator_note']))?></p><?php endif?></div>
<h2>Case history</h2><?php foreach($events as $e):?><div class="historyItem"><strong><?=h(ucwords(str_replace('_',' ',(string)$e['event_type'])))?></strong><?php if($e['status']):?> · <?=h(str_replace('_',' ',(string)$e['status']))?><?php endif?><div class="meta"><?=h($e['created_at'])?></div><?php if($e['note']):?><p><?=nl2br(h((string)$e['note']))?></p><?php endif?></div><?php endforeach?>
<?php if($canAppeal):?><div class="card"><h2>Appeal this decision</h2><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="appeal"><input type="hidden" name="id" value="<?=h($id)?>"><label>Why should this case be reviewed again?<textarea name="note" rows="5" maxlength="5000" required></textarea></label><button>Submit appeal</button></form></div><?php endif?></main></body></html>