<?php
declare(strict_types=1);require __DIR__.'/app/bootstrap.php';$u=require_user($pdo);header('Cache-Control: private, no-store');header('Vary: Cookie');$error='';$success='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 require_csrf();$action=(string)($_POST['action']??'');
 if($action==='disconnect'){$provider=(string)($_POST['provider']??'');if(!in_array($provider,['google','x'],true))$error='Invalid provider.';else{$q=$pdo->prepare('SELECT COUNT(*) FROM user_identities WHERE user_id=?');$q->execute([$u['id']]);$identityCount=(int)$q->fetchColumn();$q=$pdo->prepare('SELECT password_hash FROM users WHERE id=?');$q->execute([$u['id']]);$hasPassword=(bool)$q->fetchColumn();if(!$hasPassword&&$identityCount<=1)$error='Add a native password or another login method before disconnecting your last provider.';else{$q=$pdo->prepare('DELETE FROM user_identities WHERE user_id=? AND provider=?');$q->execute([$u['id'],$provider]);$success=$q->rowCount()?'Account disconnected.':'That provider was not connected.';}}}
 if($action==='revoke_session'){$id=(int)($_POST['session_id']??0);$q=$pdo->prepare('UPDATE extension_sessions SET revoked_at=NOW() WHERE id=? AND user_id=? AND revoked_at IS NULL');$q->execute([$id,$u['id']]);$success='Extension session revoked.';}
 if($action==='revoke_all'){$pdo->prepare('UPDATE extension_sessions SET revoked_at=NOW() WHERE user_id=? AND revoked_at IS NULL')->execute([$u['id']]);$success='All extension sessions revoked.';}
 if($action==='revoke_web'){$pdo->prepare('UPDATE users SET sessions_revoked_before=NOW() WHERE id=?')->execute([$u['id']]);$_SESSION['auth_time']=time();session_regenerate_id(true);$success='Older browser sessions were signed out. This session remains active.';}
 if($action==='revoke_everywhere'){$pdo->beginTransaction();try{$pdo->prepare('UPDATE extension_sessions SET revoked_at=NOW() WHERE user_id=? AND revoked_at IS NULL')->execute([$u['id']]);$pdo->prepare('UPDATE users SET sessions_revoked_before=NOW() WHERE id=?')->execute([$u['id']]);$pdo->commit();$_SESSION['auth_time']=time();session_regenerate_id(true);$success='Other browser sessions and all extension sessions were revoked.';}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error='Unable to revoke all sessions.';}}
}
$q=$pdo->prepare('SELECT provider,provider_email,created_at FROM user_identities WHERE user_id=? ORDER BY provider');$q->execute([$u['id']]);$identities=$q->fetchAll();$byProvider=[];foreach($identities as $i)$byProvider[$i['provider']]=$i;
try{$q=$pdo->prepare('SELECT id,device_name,client_version,created_at,last_used_at,expires_at,revoked_at FROM extension_sessions WHERE user_id=? ORDER BY created_at DESC LIMIT 50');$q->execute([$u['id']]);$sessions=$q->fetchAll();}catch(PDOException $e){$q=$pdo->prepare('SELECT id,device_name,NULL client_version,created_at,last_used_at,expires_at,revoked_at FROM extension_sessions WHERE user_id=? ORDER BY created_at DESC LIMIT 50');$q->execute([$u['id']]);$sessions=$q->fetchAll();}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Connected accounts · Annotated</title><meta name="robots" content="noindex,nofollow"><link rel="stylesheet" href="/assets/css/app.css"></head><body><header class="topbar"><a class="brand" href="/">Annotated</a><nav><a href="/onboarding.php">Onboarding</a><a href="/settings.php">Settings</a><a href="/logout.php">Sign out</a></nav></header><main class="panel article"><div class="pageTitle"><div class="eyebrow">SECURITY</div><h1>Connected accounts</h1><p>Review login methods and revoke website or Chrome sessions without exposing credentials.</p></div>
<?php if($error):?><div class="error"><?=h($error)?></div><?php endif?><?php if($success):?><div class="success"><?=h($success)?></div><?php endif?>
<div class="accountGrid"><?php foreach(['google'=>'Google','x'=>'X'] as $key=>$label):?><div class="card"><h3><?=h($label)?></h3><?php if(isset($byProvider[$key])):?><p class="meta">Connected <?=h($byProvider[$key]['created_at'])?><?php if($byProvider[$key]['provider_email']):?> · <?=h($byProvider[$key]['provider_email'])?><?php endif?></p><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="disconnect"><input type="hidden" name="provider" value="<?=h($key)?>"><button class="button secondary">Disconnect</button></form><?php else:?><p class="meta">Not connected.</p><a class="button secondary" href="/link-account.php?provider=<?=h($key)?>">Connect <?=h($label)?></a><?php endif?></div><?php endforeach?></div>
<h2>Browser sessions</h2><div class="card"><p>Use these controls if you signed in on another browser or device that should no longer have access.</p><div class="inlineActions"><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="revoke_web"><button class="button secondary">Sign out other browser sessions</button></form><form method="post" onsubmit="return confirm('Revoke all other browser sessions and every Chrome extension session?')"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="revoke_everywhere"><button class="button secondary">Sign out everywhere else</button></form></div></div>
<h2>Chrome extension sessions</h2><?php if(!$sessions):?><div class="card">No extension sessions yet.</div><?php endif?><?php foreach($sessions as $s):?><div class="card sessionRow"><div><strong><?=h($s['device_name']?:'Chrome extension')?></strong><div class="meta">Created <?=h($s['created_at'])?> · Last used <?=h($s['last_used_at']?:'never')?><?php if($s['client_version']):?> · v<?=h($s['client_version'])?><?php endif?><?php if($s['expires_at']):?> · expires <?=h($s['expires_at'])?><?php endif?><?=$s['revoked_at']?' · Revoked '.$s['revoked_at']:''?></div></div><?php if(!$s['revoked_at']):?><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="revoke_session"><input type="hidden" name="session_id" value="<?=h((string)$s['id'])?>"><button class="button secondary">Revoke</button></form><?php endif?></div><?php endforeach?><?php if($sessions):?><form method="post" class="inlineActions"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="revoke_all"><button class="button secondary">Revoke all extension sessions</button></form><?php endif?></main></body></html>