<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';require_once __DIR__.'/app/public-discovery.php';require_once __DIR__.'/app/annotation-ui.php';$viewer=current_user($pdo);$d=public_discovery_explore($pdo,$viewer);$intel=search_explore_intelligence($pdo,$viewer);
$hydrateAnnotations=function(array $rows)use($pdo,$viewer):array{$out=[];foreach($rows as $row){$full=public_discovery_annotation($pdo,(string)($row['public_id']??''),$viewer);if($full)$out[]=$full;}return $out;};
$d['annotations']=$hydrateAnnotations($d['annotations']);$d['media']=$hydrateAnnotations($d['media']);$intel['recommendations']=$hydrateAnnotations($intel['recommendations']??[]);
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Explore · Annotated</title><meta name="description" content="Explore public annotations, active sources, media captures, discussions, and published Research on Annotated."><link rel="canonical" href="<?=h(public_discovery_absolute_url($config,'/explore.php'))?>"><meta property="og:title" content="Explore Annotated"><meta property="og:description" content="See what people are annotating, discussing, and researching around the web."><link rel="stylesheet" href="/assets/css/app.css"></head><body>
<header class="topbar"><a class="brand" href="/">Annotated</a><nav><?php if($viewer):?><a href="/home.php">Home</a><?php endif?><a href="/explore.php">Explore</a><a href="/search.php">Search</a><?php if($viewer):?><a href="/research.php">Research</a><a href="/saved.php">Saved</a><a href="/notifications.php">Notifications</a><?php else:?><a href="/login.php">Log in</a><a href="/register.php">Sign up</a><?php endif?></nav></header>
<main class="discoveryShell"><section class="discoveryHero"><span class="eyebrow">EXPLORE</span><h1>Research the web in context.</h1><p>Follow the original source, preserved evidence, public discussion, and published research without separating commentary from what it refers to.</p><form action="/search.php" method="get" class="searchBar exploreSearch"><input name="q" placeholder="Search sources, annotations, people, claims, entities, reports"><button>Search</button></form></section>
<section><div class="sectionHeadWeb"><div><span class="eyebrow">TRENDING · 7 DAYS</span><h2>Sources gaining attention</h2></div><a href="/search.php?sort=discussed&q=source">Open Search</a></div><div class="sourceGrid discoveryGrid"><?php foreach($intel['trending'] as $s):?><a class="card sourceCard" href="/source.php?id=<?=h($s['public_id'])?>"><div class="meta"><?=h($s['domain'])?> · <?=h((string)$s['contributor_count'])?> contributors</div><h3><?=h($s['title']?:$s['domain'])?></h3><div class="metricRow"><span><strong><?=h((string)$s['annotation_count'])?></strong> annotations</span><span><strong><?=h((string)$s['comment_count'])?></strong> comments</span></div></a><?php endforeach?><?php if(!$intel['trending']):?><div class="card">Trending sources will appear as public activity accumulates.</div><?php endif?></div></section>
<section><div class="sectionHeadWeb"><div><span class="eyebrow">TOPICS & ENTITIES · 30 DAYS</span><h2>Growing research threads</h2></div></div><div class="topicCloud"><?php foreach($intel['topics'] as $t):?><a href="/entity.php?id=<?=h($t['public_id'])?>"><span><?=h($t['canonical_name'])?></span><small><?=h($t['entity_type'])?> · <?=h((string)$t['mention_count'])?></small></a><?php endforeach?><?php if(!$intel['topics']):?><div class="card">Public topics appear as published Research reports contribute confirmed entities.</div><?php endif?></div></section>
<?php if($viewer):?><section><div class="sectionHeadWeb"><div><span class="eyebrow">BECAUSE YOU FOLLOW</span><h2>Recommended annotations</h2></div></div><div class="sourceGrid discoveryGrid"><?php foreach($intel['recommendations'] as $a):?><?=annotation_ui_card($a,$viewer)?><?php endforeach?><?php if(!$intel['recommendations']):?><div class="card">Follow people or sources to personalize discovery.</div><?php endif?></div></section><?php endif?>
<section><div class="sectionHeadWeb"><div><span class="eyebrow">RECENTLY ACTIVE</span><h2>Sources</h2></div></div><div class="sourceGrid discoveryGrid"><?php foreach($d['sources'] as $s):?><a class="card sourceCard" href="/source.php?id=<?=h($s['public_id'])?>"><div class="meta"><?=h($s['domain'])?><?php if($s['status']!=='current'):?> · <span class="badge warn"><?=h(ucfirst($s['status']))?></span><?php endif?></div><h3><?=h($s['title']?:$s['canonical_url'])?></h3><div class="metricRow"><span><strong><?=h((string)$s['annotation_count'])?></strong> annotations</span><span><strong><?=h((string)$s['contributor_count'])?></strong> contributors</span><span><strong><?=h((string)$s['comment_count'])?></strong> comments</span></div></a><?php endforeach?></div></section>
<section class="splitDiscovery"><div><div class="sectionHeadWeb"><div><span class="eyebrow">LATEST</span><h2>Annotations</h2></div></div><?php if(!$d['annotations']):?><div class="card">No public annotations yet.</div><?php endif?><?php foreach($d['annotations'] as $a):?><?=annotation_ui_card($a,$viewer)?><?php endforeach?></div>
<aside><div class="sectionHeadWeb"><div><span class="eyebrow">MOST DISCUSSED</span><h2>Conversation</h2></div></div><?php if(!$d['discussed']):?><div class="card"><p class="meta">Discussion will appear here as public comments accumulate.</p></div><?php endif?><?php foreach($d['discussed'] as $s):?><a class="card sourceCard compactCard" href="/source.php?id=<?=h($s['public_id'])?>"><div class="meta"><?=h($s['domain'])?></div><h3><?=h($s['title']?:'Source')?></h3><p><?=h((string)$s['comment_count'])?> comments across <?=h((string)$s['annotation_count'])?> annotations</p></a><?php endforeach?></aside></section>
<section><div class="sectionHeadWeb"><div><span class="eyebrow">RICH CAPTURE</span><h2>Media & visual annotations</h2></div></div><div class="sourceGrid discoveryGrid"><?php foreach($d['media'] as $a):?><?=annotation_ui_card($a,$viewer)?><?php endforeach?></div></section>
<section><div class="sectionHeadWeb"><div><span class="eyebrow">PUBLISHED RESEARCH</span><h2>Reports</h2></div><a href="/search.php?q=research">Search Research</a></div><div class="sourceGrid discoveryGrid"><?php if(!$d['reports']):?><div class="card">No public Research reports yet.</div><?php endif?><?php foreach($d['reports'] as $r):?><a class="card sourceCard" href="/research-report.php?id=<?=h($r['public_id'])?>"><div class="meta">Version <?=h((string)$r['version_number'])?> · <?=h($r['display_name'])?> · <?=h((string)$r['published_at'])?></div><h3><?=h($r['title'])?></h3><?php if($r['summary']):?><p><?=h(public_discovery_meta_description($r['summary'],260))?></p><?php endif?></a><?php endforeach?></div></section>
</main><?=annotation_ui_scripts($viewer)?></body></html>