<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';require_once __DIR__.'/app/ai.php';
$u=current_user($pdo);$id=(string)($_GET['id']??$_POST['id']??'');$q=$pdo->prepare("SELECT a.public_id,s.canonical_url FROM annotations a JOIN sources s ON s.id=a.source_id WHERE a.public_id=? AND a.visibility='public' AND a.status='published'");$q->execute([$id]);$a=$q->fetch();if(!$a){http_response_code(404);exit('Annotation not found.');}
$done=false;$error='';$claimPublic='';$trackingToken='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    require_csrf();$email=trim((string)($_POST['email']??''));$name=trim((string)($_POST['name']??''));$desc=trim((string)($_POST['description']??''));$type=(string)($_POST['claim_type']??'other');
    $limit=rate_limit_page_message($pdo,'rights-claim-ip',rate_limit_ip_subject(),3,3600)?:rate_limit_page_message($pdo,'rights-claim-email',rate_limit_subject($email),3,86400);
    if($limit)$error=$limit;else try{$created=rights_claim_create($pdo,$u,$id,$name,$email,$type,$desc);$claimPublic=$created['public_id'];$trackingToken=$created['tracking_token'];try{$model=ai_setting_model_id($pdo,'moderation');if($model)ai_queue_job($pdo,$u['id']??null,'moderation_rights_triage',$model,'rights_claim',$claimPublic,[],2);}catch(Throwable $e){}$done=true;}catch(Throwable $e){$error=$e->getMessage();}
}
$defaultName=$u['display_name']??'';$defaultEmail=$u['email']??'';
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>File a claim · Annotated</title><meta name="robots" content="noindex,nofollow"><link rel="stylesheet" href="/assets/css/app.css"></head><body><main class="panel narrow"><span class="eyebrow">RIGHTS & ATTRIBUTION</span><h1>File a claim</h1><p>This workflow is for ownership, copyright, attribution, privacy, impersonation, or inaccurate-context concerns tied to a public annotation. Claims are reviewed by a human moderator.</p>
<?php if($done):?><div class="success">Your claim has been submitted for review.</div><div class="card"><h3>Track your claim</h3><p>Save this tracking link. The secret token is shown only once.</p><p><a href="/claim-status.php?id=<?=h($claimPublic)?>&token=<?=h($trackingToken)?>">Open claim status</a></p><code><?=h($trackingToken)?></code></div>
<?php else:?><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="id" value="<?=h($id)?>"><label>Name<input name="name" value="<?=h((string)$defaultName)?>" required></label><label>Email<input type="email" name="email" value="<?=h((string)$defaultEmail)?>" required></label><label>Claim type<select name="claim_type"><option value="copyright">Copyright / fair-use concern</option><option value="ownership">Ownership</option><option value="incorrect_attribution">Incorrect attribution</option><option value="inaccurate_context">Inaccurate context</option><option value="privacy">Privacy</option><option value="impersonation">Impersonation</option><option value="other">Other legal or rights concern</option></select></label><label>Description<textarea name="description" rows="7" maxlength="8000" required></textarea></label><button>Submit claim</button></form><?php endif?></main></body></html>