<?php
declare(strict_types=1);require __DIR__.'/app/bootstrap.php';
if(users_exist($pdo)){http_response_code(404);exit('First-admin setup is closed.');}
$bootstrap=(string)($config['app']['bootstrap_key']??'');if(strlen($bootstrap)<24){http_response_code(503);exit('First-admin setup is disabled until app.bootstrap_key is configured with a strong random secret.');}
$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
 require_csrf();$submitted=(string)($_POST['bootstrap_key']??'');if(!hash_equals($bootstrap,$submitted))$errors[]='Invalid bootstrap key.';
 $email=strtolower(trim((string)($_POST['email']??'')));$username=trim((string)($_POST['username']??''));$name=trim((string)($_POST['display_name']??''));$password=(string)($_POST['password']??'');
 if(!filter_var($email,FILTER_VALIDATE_EMAIL))$errors[]='Enter a valid email.';if(!preg_match('/^[A-Za-z0-9_]{3,30}$/',$username))$errors[]='Username must be 3–30 letters, numbers, or underscores.';if(strlen($password)<12)$errors[]='Password must be at least 12 characters.';if($name==='')$errors[]='Display name is required.';
 if(!$errors){$got=(int)$pdo->query("SELECT GET_LOCK('annotated_first_admin',5)")->fetchColumn();if($got!==1)throw new RuntimeException('First-admin setup is busy. Retry.');try{if(users_exist($pdo)){http_response_code(409);exit('First admin was already created.');}$q=$pdo->prepare('INSERT INTO users(public_id,username,display_name,email,password_hash,role) VALUES(?,?,?,?,?,"admin")');$q->execute([ulid_like(),$username,$name,$email,password_hash($password,PASSWORD_DEFAULT)]);session_regenerate_id(true);$_SESSION['user_id']=(int)$pdo->lastInsertId();$_SESSION['rotated_at']=time();$_SESSION['last_activity']=time();$_SESSION['auth_time']=time();header('Location: /upgrade.php');exit;}finally{$pdo->query("SELECT RELEASE_LOCK('annotated_first_admin')");}}
}
?><!doctype html><html><head><meta charset="utf-8"><title>Create First Admin · Annotated</title><link rel="stylesheet" href="/assets/css/app.css"></head><body><main class="panel narrow"><h1>Create First Admin</h1><p>This one-time screen requires the private bootstrap key from <code>config.php</code> and closes permanently after the first account is created.</p><?php foreach($errors as $e):?><div class="error"><?=h($e)?></div><?php endforeach?><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><label>Bootstrap key<input type="password" name="bootstrap_key" required autocomplete="off"></label><label>Display name<input name="display_name" required></label><label>Username<input name="username" required></label><label>Email<input type="email" name="email" required></label><label>Password<input type="password" name="password" minlength="12" required></label><button>Create administrator</button></form></main></body></html>
