<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';
$u=require_user($pdo);header('Cache-Control: private, no-store');header('Vary: Cookie');

$q=$pdo->prepare("SELECT a.public_id,a.text_commentary,a.audio_commentary_path,a.published_at,u2.username,u2.display_name,u2.profile_image_url,s.public_id source_public_id,s.title,s.canonical_url,s.status source_status,c.selected_text,c.screenshot_target_path,at.status transcript_status,COALESCE(at.edited_text,at.raw_text) transcript_text FROM annotations a JOIN users u2 ON u2.id=a.user_id JOIN follows f ON f.followed_user_id=a.user_id AND f.follower_user_id=? JOIN sources s ON s.id=a.source_id JOIN captures c ON c.id=a.capture_id LEFT JOIN annotation_transcripts at ON at.annotation_id=a.id WHERE a.visibility='public' AND a.status='published' AND NOT EXISTS(SELECT 1 FROM blocks b WHERE (b.blocker_user_id=? AND b.blocked_user_id=a.user_id) OR (b.blocker_user_id=a.user_id AND b.blocked_user_id=?)) ORDER BY a.published_at DESC LIMIT 50");
$q->execute([$u['id'],$u['id'],$u['id']]);$feed=$q->fetchAll();

$q=$pdo->prepare("SELECT u.username,u.display_name,u.profile_image_url,u.bio,(SELECT COUNT(*) FROM annotations a WHERE a.user_id=u.id AND a.visibility='public' AND a.status='published') annotation_count FROM users u LEFT JOIN user_preferences p ON p.user_id=u.id WHERE u.id<>? AND u.status='active' AND COALESCE(p.profile_visibility,'public')='public' AND COALESCE(p.search_visibility,1)=1 AND NOT EXISTS(SELECT 1 FROM follows f WHERE f.follower_user_id=? AND f.followed_user_id=u.id) AND NOT EXISTS(SELECT 1 FROM blocks b WHERE (b.blocker_user_id=? AND b.blocked_user_id=u.id) OR (b.blocker_user_id=u.id AND b.blocked_user_id=?)) ORDER BY annotation_count DESC,u.created_at DESC LIMIT 5");
$q->execute([$u['id'],$u['id'],$u['id'],$u['id']]);$people=$q->fetchAll();

$q=$pdo->prepare("SELECT t.public_id,t.name,tm.role,(SELECT COUNT(*) FROM team_members x WHERE x.team_id=t.id) member_count FROM teams t JOIN team_members tm ON tm.team_id=t.id WHERE tm.user_id=? ORDER BY t.name LIMIT 5");
$q->execute([$u['id']]);$teams=$q->fetchAll();

$q=$pdo->prepare('SELECT (SELECT COUNT(*) FROM follows WHERE followed_user_id=?) followers,(SELECT COUNT(*) FROM follows WHERE follower_user_id=?) following_count,(SELECT COUNT(*) FROM annotations WHERE user_id=? AND status="published") annotation_count');
$q->execute([$u['id'],$u['id'],$u['id']]);$stats=$q->fetch()?:['followers'=>0,'following_count'=>0,'annotation_count'=>0];
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Home · Annotated</title><meta name="robots" content="noindex,nofollow"><link rel="stylesheet" href="/assets/css/app.css"></head><body>
<main class="layout"><section>
<div class="pageTitle"><span class="eyebrow">FOLLOWING</span><h1>Your Annotated feed</h1><p>What people you follow are annotating, discussing, and researching across the live web.</p></div>
<?php if(!$feed):?><div class="card empty"><h2>Your Following feed is ready.</h2><p>Follow researchers from Explore or the people suggestions here. Captures published by people you follow will appear in this feed.</p><div class="inlineActions"><a class="button" href="/explore.php">Discover people & sources</a><a class="button secondary" href="/chrome-extension.php">Get the Chrome extension</a></div></div><?php endif?>
<?php foreach($feed as $a):?><article class="card annotationWebCard">
<div class="annotationIdentity"><a class="profileMini" href="/profile.php?u=<?=h($a['username'])?>"><?=app_shell_avatar($a,'avatarSm')?><span><strong><?=h($a['display_name'])?></strong><small>@<?=h($a['username'])?> · <?=h($a['published_at'])?></small></span></a><?php if($a['source_status']==='edited'):?><span class="badge warn">Edited source</span><?php endif?></div>
<h2><a href="/source.php?id=<?=h($a['source_public_id'])?>"><?=h($a['title']?:$a['canonical_url'])?></a></h2>
<?php if($a['text_commentary']):?><p class="commentary"><?=nl2br(h($a['text_commentary']))?></p><?php endif?><?php if($a['selected_text']):?><blockquote><?=h($a['selected_text'])?></blockquote><?php endif?>
<?php if($a['screenshot_target_path']):?><img class="snapshot" src="<?=h(evidence_url($a['public_id'],'target'))?>" alt="Preserved annotation snapshot"><?php endif?>
<?php if($a['audio_commentary_path']):?><audio class="wideAudio" controls src="<?=h(evidence_url($a['public_id'],'audio'))?>"></audio><details><summary>Transcript · <?=h($a['transcript_status']?:'queued')?></summary><?php if($a['transcript_text']):?><p><?=nl2br(h($a['transcript_text']))?></p><?php else:?><p class="meta">Transcription is still processing.</p><?php endif?></details><?php endif?>
<div class="inlineActions"><a href="/annotation.php?id=<?=h($a['public_id'])?>">Open annotation</a><a href="<?=h($a['canonical_url'])?>" target="_blank" rel="noopener">Original source ↗</a></div>
</article><?php endforeach?>
</section><aside>
<div class="card"><div class="profileMini"><?=app_shell_avatar($u,'avatarImageLg')?><span><strong><?=h($u['display_name'])?></strong><small>@<?=h($u['username'])?></small></span></div><div class="profileStats"><span><strong><?=h((string)$stats['followers'])?></strong> followers</span><span><strong><?=h((string)$stats['following_count'])?></strong> following</span><span><strong><?=h((string)$stats['annotation_count'])?></strong> annotations</span></div><a href="/profile.php?u=<?=h($u['username'])?>">View your profile</a></div>
<div class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">PEOPLE</span><h3>Discover researchers</h3></div></div><?php foreach($people as $p):?><a class="profileMini" style="margin:12px 0" href="/profile.php?u=<?=h($p['username'])?>"><?=app_shell_avatar($p,'avatarSm')?><span><strong><?=h($p['display_name'])?></strong><small>@<?=h($p['username'])?> · <?=h((string)$p['annotation_count'])?> annotations</small></span></a><?php endforeach?><?php if(!$people):?><p class="meta">No new profile suggestions right now.</p><?php endif?><a href="/explore.php">Explore Annotated</a></div>
<div class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">TEAMS</span><h3>Your teams</h3></div></div><?php foreach($teams as $t):?><a class="savedSearchRow" href="/team.php?id=<?=h($t['public_id'])?>"><strong><?=h($t['name'])?></strong><small><?=h(ucfirst($t['role']))?> · <?=h((string)$t['member_count'])?> members</small></a><?php endforeach?><?php if(!$teams):?><p class="meta">Create a team for private collaboration and shared Research.</p><?php endif?><a href="/teams.php">Open Teams</a></div>
<div class="card"><span class="eyebrow">BROWSER SIDEBAR</span><h3>Annotate while you browse</h3><p class="meta">The Chrome extension connects this social website to the live page you are researching.</p><a class="button" href="/chrome-extension.php">Download Chrome Extension</a></div>
</aside></main></body></html>