<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';require_once __DIR__.'/app/live.php';
$u=require_user($pdo);$sourcePublic=(string)($_GET['id']??$_POST['source']??'');$source=source_access($pdo,$sourcePublic,$u);if(!$source){http_response_code(404);exit('Source not found.');}
function web_live_room(PDO $pdo,array $u,string $sourcePublic): ?array {return live_room_scope($pdo,$u,$sourcePublic,(string)($_REQUEST['room_type']??'public'),isset($_REQUEST['room_id'])?(string)$_REQUEST['room_id']:null,false);}
if(isset($_GET['ajax'])){
    header('Content-Type: application/json; charset=utf-8');$room=web_live_room($pdo,$u,$sourcePublic);if(!$room)json_response(['ok'=>false,'error'=>['code'=>'ROOM_FORBIDDEN']],403);
    $messages=live_message_rows($pdo,$u,$room,max(0,(int)($_GET['after_message']??0)),100);$events=live_event_rows($pdo,$u,$room,max(0,(int)($_GET['after_event']??0)),60);$presence=live_presence_rows($pdo,$u,$room,(string)$u['live_presence_mode']);
    json_response(['ok'=>true,'data'=>['messages'=>$messages['messages'],'message_cursor'=>$messages['cursor'],'events'=>$events['events'],'event_cursor'=>$events['cursor'],'presence'=>$presence,'room'=>['type'=>$room['room_type'],'id'=>$room['room_public_id'],'name'=>$room['room_name'],'can_post'=>$room['can_post'],'can_moderate'=>$room['can_moderate']]]]);
}
if($_SERVER['REQUEST_METHOD']==='POST'){
    require_csrf();$action=(string)($_POST['action']??'');$room=web_live_room($pdo,$u,$sourcePublic);if(!$room)json_response(['ok'=>false,'error'=>['code'=>'ROOM_FORBIDDEN']],403);
    try{
        if($action==='presence'){$data=live_presence_touch($pdo,$u,$room,(string)($_POST['client_session_id']??''),(string)($_POST['mode']??'cloaked'));json_response(['ok'=>true,'data'=>$data]);}
        if($action==='message'){$write=live_room_scope($pdo,$u,$sourcePublic,$room['room_type'],$room['room_public_id'],true);if(!$write)json_response(['ok'=>false,'error'=>['code'=>'ROOM_FORBIDDEN']],403);$created=live_message_create($pdo,$u,$write,(string)($_POST['body']??''),null,(string)($_POST['client_message_id']??''),(string)($_POST['client_session_id']??''),!empty($_POST['reveal_identity']),isset($_POST['parent_message_id'])?(string)$_POST['parent_message_id']:null);json_response(['ok'=>true,'data'=>$created],$created['created']?201:200);}
        if($action==='react'){$active=live_message_react($pdo,$u,$room,(string)($_POST['message_id']??''));json_response(['ok'=>true,'data'=>['active'=>$active]]);}
        if($action==='pin'){$pinned=live_message_pin($pdo,$u,$room,(string)($_POST['message_id']??''));json_response(['ok'=>true,'data'=>['pinned'=>$pinned]]);}
        if($action==='delete'){$ok=live_message_delete($pdo,$u,$room,(string)($_POST['message_id']??''));if(!$ok)json_response(['ok'=>false,'error'=>['code'=>'MESSAGE_NOT_FOUND']],404);json_response(['ok'=>true,'data'=>['deleted'=>true]]);}
    }catch(InvalidArgumentException $e){json_response(['ok'=>false,'error'=>['code'=>'INVALID_LIVE_REQUEST','message'=>$e->getMessage()]],422);}catch(RuntimeException $e){json_response(['ok'=>false,'error'=>['code'=>'LIVE_FORBIDDEN','message'=>$e->getMessage()]],403);}
    json_response(['ok'=>false,'error'=>['code'=>'UNKNOWN_ACTION']],404);
}
$rooms=live_rooms_for_user($pdo,$u);$title=(string)($source['title']?:$source['canonical_url']);header('Cache-Control: private, no-store');header('Vary: Cookie');
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Live · <?=h($title)?> · Annotated</title><meta name="robots" content="noindex,nofollow"><link rel="stylesheet" href="/assets/css/app.css"></head><body>
<header class="topbar"><a class="brand" href="/">Annotated</a><nav><a href="/source.php?id=<?=h($source['public_id'])?>">Source</a><a href="/explore.php">Explore</a><a href="/research.php">Research</a><a href="/notifications.php">Notifications</a></nav></header>
<main class="liveWebShell"><section><div class="pageTitle"><span class="eyebrow">LIVE ROOM</span><h1><?=h($title)?></h1><p class="sourceUrl"><?=h($source['canonical_url'])?></p></div>
<div class="liveWebToolbar card"><label>Room<select id="room"><option value="public">Public · this source</option><?php if($rooms['teams']):?><optgroup label="Teams"><?php foreach($rooms['teams'] as $t):?><option value="team:<?=h($t['public_id'])?>">Team · <?=h($t['name'])?></option><?php endforeach?></optgroup><?php endif?><?php if($rooms['projects']):?><optgroup label="Research"><?php foreach($rooms['projects'] as $p):?><option value="project:<?=h($p['public_id'])?>">Research · <?=h($p['title'])?><?=$p['can_post']?'':' · read only'?></option><?php endforeach?></optgroup><?php endif?></select></label>
<label>Presence<select id="presence"><option value="visible">Visible</option><option value="team_only">Team only</option><option value="cloaked">Cloaked</option><option value="off">Off</option></select></label><div><strong id="connection">Connecting…</strong><div id="stats" class="meta"></div></div></div>
<div id="people" class="liveWebPeople"></div><div id="events" class="liveWebEvents"></div><div id="messages" class="card liveWebMessages"></div>
<form id="composer" class="card stack"><div id="reply" class="meta" hidden></div><textarea id="body" maxlength="3000" placeholder="Message this Live room" required></textarea><label class="checkRow"><input type="checkbox" id="reveal"> Reveal my identity for this message</label><p class="meta">Cloaked messages never include your profile identity in Live client payloads. Team-only identity is disclosed only to shared-team viewers.</p><div class="inlineActions"><button type="button" id="cancelReply" class="button secondary" hidden>Cancel reply</button><button id="send">Send</button></div></form></section>
<aside><div class="card"><h3>Live context</h3><p>Public, Team, and Research rooms share the same server authorization model used by the Chrome sidebar.</p><p class="meta">Live automatically reconnects and deduplicates retried sends.</p></div><div class="card"><h3>Cloak Mode</h3><p class="meta">Cloaked presence and messages expose only a room pseudonym. Moderation permissions do not reveal the underlying profile to other participants.</p></div></aside></main>
<script>
const csrf=<?=json_encode(csrf_token())?>,source=<?=json_encode($source['public_id'])?>,defaultPresence=<?=json_encode($u['live_presence_mode'])?>;
let client=localStorage.getItem('annotated_live_client')||crypto.randomUUID(),roomSelection=localStorage.getItem('annotated_live_room')||'public',messageCursor=0,eventCursor=0,messages=new Map(),events=new Map(),replyTo=null,pollTimer=null,failures=0,pending=null;localStorage.setItem('annotated_live_client',client);
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function params(){const v=$('#room').value||'public';if(v.startsWith('team:'))return{room_type:'team',room_id:v.slice(5)};if(v.startsWith('project:'))return{room_type:'project',room_id:v.slice(8)};return{room_type:'public',room_id:''};}
async function post(action,data={}){const r=params(),body=new URLSearchParams({csrf,action,source,room_type:r.room_type,room_id:r.room_id,client_session_id:client,...data});const res=await fetch('/live.php?id='+encodeURIComponent(source),{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const j=await res.json();if(!res.ok||j.ok===false)throw new Error(j.error?.message||j.error?.code||'Live request failed');return j.data;}
function presence(d){$('#stats').textContent=(d.total||0)+' here · '+(d.following_visible||0)+' you follow';$('#people').innerHTML=[...(d.visible||[]).map(p=>'<span class="livePerson">'+esc(p.display_name)+'</span>'),...(d.cloaked||[]).map(p=>'<span class="livePerson cloaked">'+esc(p.is_self?'You · cloaked':p.alias)+'</span>')].join('');}
function render(){const rows=[...messages.values()].sort((a,b)=>Number(b.pinned)-Number(a.pinned)||String(a.created_at).localeCompare(String(b.created_at)));$('#messages').innerHTML=rows.length?rows.map(m=>{const who=m.author?.display_name||(m.is_self?'You · cloaked':m.cloak_alias||'Cloaked participant'),actions=m.deleted?'':`<div class="inlineActions"><button data-action="reply" data-id="${esc(m.public_id)}" data-who="${esc(who)}">Reply</button><button data-action="react" data-id="${esc(m.public_id)}">${m.viewer_liked?'♥':'♡'} ${m.like_count||0}</button>${m.can_pin?`<button data-action="pin" data-id="${esc(m.public_id)}">${m.pinned?'Unpin':'Pin'}</button>`:''}${m.can_delete?`<button data-action="delete" data-id="${esc(m.public_id)}">Delete</button>`:''}</div>`;return `<article class="liveWebMessage ${m.pinned?'pinned':''}"><div class="meta"><strong>${esc(who)}</strong>${m.pinned?' · PINNED':''} · ${esc(m.created_at)}</div><p>${m.deleted?'<em>Message removed</em>':esc(m.body||'')}</p>${actions}</article>`;}).join(''):'<div class="empty">No messages yet.</div>';
$('#events').innerHTML=[...events.values()].slice(-20).map(e=>`<a class="liveWebEvent" href="${e.object_type==='annotation'?'/annotation.php?id=':'/source.php?id='}${encodeURIComponent(e.object_public_id||'')}"><strong>${esc(e.label)}</strong><span>${esc(e.created_at)}</span></a>`).join('');}
async function heartbeat(){try{presence(await post('presence',{mode:$('#presence').value}));}catch{}}
async function poll(reset=false){if(reset){messageCursor=0;eventCursor=0;messages.clear();events.clear();}const r=params(),qs=new URLSearchParams({id:source,ajax:'1',room_type:r.room_type,room_id:r.room_id,after_message:String(messageCursor),after_event:String(eventCursor)});try{await heartbeat();const res=await fetch('/live.php?'+qs),j=await res.json();if(!res.ok||!j.ok)throw new Error(j.error?.message||'Live unavailable');for(const m of j.data.messages||[])messages.set(m.public_id,m);for(const e of j.data.events||[])events.set(e.public_id,e);messageCursor=Math.max(messageCursor,Number(j.data.message_cursor||0));eventCursor=Math.max(eventCursor,Number(j.data.event_cursor||0));presence(j.data.presence||{});$('#connection').textContent=j.data.room?.can_post===false?'Connected · read only':'Connected';$('#send').disabled=j.data.room?.can_post===false;failures=0;render();}catch(e){failures++;$('#connection').textContent='Reconnecting…';}clearTimeout(pollTimer);pollTimer=setTimeout(()=>poll(false),Math.min(15000,2500*Math.max(1,failures)));}
$('#room').value=[...$('#room').options].some(o=>o.value===roomSelection)?roomSelection:'public';$('#presence').value=defaultPresence||'cloaked';$('#room').onchange=()=>{roomSelection=$('#room').value;localStorage.setItem('annotated_live_room',roomSelection);pending=null;replyTo=null;poll(true)};$('#presence').onchange=heartbeat;
$('#composer').onsubmit=async e=>{e.preventDefault();const text=$('#body').value.trim(),r=params(),key=$('#room').value+'|'+(replyTo?.id||'');if(!text)return;if(!pending||pending.text!==text||pending.key!==key)pending={id:crypto.randomUUID(),text,key};try{await post('message',{body:text,client_message_id:pending.id,parent_message_id:replyTo?.id||'',reveal_identity:$('#reveal').checked?'1':''});pending=null;replyTo=null;$('#body').value='';$('#reveal').checked=false;$('#reply').hidden=true;$('#cancelReply').hidden=true;await poll(false);}catch(err){alert(err.message)}};
$('#messages').onclick=async e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,id=b.dataset.id;if(a==='reply'){replyTo={id,who:b.dataset.who};$('#reply').textContent='Replying to '+replyTo.who;$('#reply').hidden=false;$('#cancelReply').hidden=false;$('#body').focus();return;}if(a==='delete'&&!confirm('Remove this Live message?'))return;try{await post(a,{message_id:id});await poll(true);}catch(err){alert(err.message)}};
$('#cancelReply').onclick=()=>{replyTo=null;$('#reply').hidden=true;$('#cancelReply').hidden=true};poll(true);
</script></body></html>