<?php
declare(strict_types=1);
$GLOBALS['annotated_shell_disabled']=true;
require __DIR__.'/app/bootstrap.php';
require_once __DIR__.'/app/public-discovery.php';
require_once __DIR__.'/app/profile-network.php';

$viewer=current_user($pdo);if($viewer){header('Cache-Control: private, no-store');header('Vary: Cookie');}
$q=trim((string)($_GET['q']??''));$people=profile_network_discover_people($pdo,$viewer,$q,60);$suggested=$viewer&&$q===''?profile_network_suggested_people($pdo,$viewer,12):[];
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>People · Annotated</title><meta name="description" content="Discover public Annotated researchers, creators, and their published Research."><link rel="stylesheet" href="/assets/css/app.css?v=profile-300"></head>
<body class="profileStandaloneBody"><main class="profileStandalonePage peopleDiscoveryPage">
<header class="peopleDiscoveryHero"><a href="/explore.php" class="profileBackLink">← Explore</a><span class="profileSectionEyebrow">PEOPLE & RESEARCH</span><h1>Discover people worth following.</h1><p>Find public researchers and creators through the Sources, topics, and published Research they actually share.</p><form method="get" class="peopleDiscoverySearch"><input type="search" name="q" value="<?=h($q)?>" placeholder="Search people or public Research"><button>Search</button></form></header>
<?php if($suggested):?><section class="peopleDiscoverySection"><header class="profileContentHeader"><div><span class="profileSectionEyebrow">FOR YOU</span><h2>Suggested people</h2></div><span class="profileActivityCount">Explainable recommendations</span></header><div class="profilePeopleDiscoveryGrid"><?php foreach($suggested as $person):?>
<a class="profileDiscoveryCard" href="<?=h(profile_path((string)$person['username']))?>"><div class="profileDiscoveryIdentity"><?php if($person['profile_image_url']):?><img src="<?=h((string)$person['profile_image_url'])?>" alt=""><?php else:?><span><?=h(mb_strtoupper(mb_substr((string)$person['display_name'],0,1)))?></span><?php endif?><div><strong><?=h((string)$person['display_name'])?></strong><small>@<?=h((string)$person['username'])?></small></div></div><?php if(!empty($person['recommendation_reasons'])):?><p class="profileDiscoveryReason"><?=h(implode(' · ',$person['recommendation_reasons']))?></p><?php endif?><div class="profileDiscoveryMetrics"><span><?=h((string)$person['report_count'])?> Research</span><span><?=h((string)$person['annotation_count'])?> annotations</span></div></a>
<?php endforeach?></div></section><?php endif?>
<section class="peopleDiscoverySection"><header class="profileContentHeader"><div><span class="profileSectionEyebrow"><?=$q!==''?'SEARCH RESULTS':'PUBLIC NETWORK'?></span><h2><?=$q!==''?'People matching “'.h($q).'”':'Research-oriented profiles'?></h2></div><span class="profileActivityCount"><?=h((string)count($people))?> shown</span></header>
<div class="profilePeopleDiscoveryGrid"><?php if(!$people):?><div class="profileEmptyState"><div class="profileEmptyIcon">○</div><h3>No public profiles found</h3><p>Try a different name, topic, or Research phrase.</p></div><?php endif?><?php foreach($people as $person):?>
<a class="profileDiscoveryCard" href="<?=h(profile_path((string)$person['username']))?>"><div class="profileDiscoveryIdentity"><?php if($person['profile_image_url']):?><img src="<?=h((string)$person['profile_image_url'])?>" alt=""><?php else:?><span><?=h(mb_strtoupper(mb_substr((string)$person['display_name'],0,1)))?></span><?php endif?><div><strong><?=h((string)$person['display_name'])?></strong><small>@<?=h((string)$person['username'])?></small></div></div><?php if($person['bio']):?><p><?=h(public_discovery_meta_description((string)$person['bio'],170))?></p><?php endif?><?php if(!empty($person['topics'])):?><div class="profileDiscoveryTopics"><?php foreach(array_slice($person['topics'],0,4) as $topic):?><span><?=h((string)$topic['canonical_name'])?></span><?php endforeach?></div><?php endif?><div class="profileDiscoveryMetrics"><span><?=h((string)$person['report_count'])?> Research</span><span><?=h((string)$person['annotation_count'])?> annotations</span><span><?=h((string)$person['follower_count'])?> followers</span></div></a>
<?php endforeach?></div></section>
<footer class="profileStandaloneFooter"><a href="<?=$viewer?'/home.php':'/'?>">Annotated</a><a href="/explore.php">Explore</a><a href="/search.php">Search</a></footer>
</main></body></html>