<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';require_once __DIR__.'/app/public-discovery.php';require_once __DIR__.'/app/annotation-ui.php';
$viewer=current_user($pdo);$username=trim((string)($_GET['u']??''));if($viewer){header('Cache-Control: private, no-store');header('Vary: Cookie');}$p=$username!==''?public_discovery_profile($pdo,$username,$viewer):null;if(!$p){http_response_code(404);exit('Profile not found.');}
$owner=$viewer&&(int)$viewer['id']===(int)$p['id'];$isPublic=$p['profile_visibility']==='public';$desc=public_discovery_meta_description((string)($p['bio']?:$p['display_name'].' on Annotated'));
$canonical=public_discovery_absolute_url($config,'/profile.php?u='.rawurlencode($p['username']));
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=h($p['display_name'])?> · Annotated</title><meta name="description" content="<?=h($desc)?>"><?php if(!$isPublic):?><meta name="robots" content="noindex,nofollow"><?php endif?><link rel="canonical" href="<?=h($canonical)?>"><?php if($isPublic):?><meta property="og:type" content="profile"><meta property="og:title" content="<?=h($p['display_name'])?> · Annotated"><meta property="og:description" content="<?=h($desc)?>"><meta property="og:url" content="<?=h($canonical)?>"><?php endif?><link rel="stylesheet" href="/assets/css/app.css"></head><body>
<header class="topbar"><a class="brand" href="/">Annotated</a><nav><?php if($viewer):?><a href="/home.php">Home</a><?php endif?><a href="/explore.php">Explore</a><a href="/search.php">Search</a><?php if($viewer):?><a href="/research.php">Research</a><a href="/saved.php">Saved</a><?php else:?><a href="/login.php">Log in</a><?php endif?></nav></header>
<main class="panel profilePage"><section class="profileHead"><div><?php if($p['profile_image_url']):?><img class="avatarImageLg" src="<?=h($p['profile_image_url'])?>" alt="<?=h($p['display_name'])?>"><?php else:?><div class="avatarLg"><?=h(mb_strtoupper(mb_substr($p['display_name'],0,1)))?></div><?php endif?></div><div><div class="meta">@<?=h($p['username'])?></div><h1><?=h($p['display_name'])?></h1><?php if($p['bio']):?><p class="commentary"><?=nl2br(h($p['bio']))?></p><?php endif?><?php if($p['website_url']):?><p><a href="<?=h($p['website_url'])?>" rel="nofollow noopener" target="_blank"><?=h($p['website_url'])?></a></p><?php endif?><div class="profileStats"><span><strong><?=$p['annotation_count']?></strong> annotations</span><span><strong><?=$p['source_count']?></strong> sources</span><span><strong><?=$p['followers']?></strong> followers</span><span><strong><?=$p['following_count']?></strong> following</span></div><div class="inlineActions"><?php if($viewer&&!$owner):?><button id="follow" class="button secondary"><?=$p['following']?'Following':'Follow'?></button><?php elseif($owner):?><a class="button secondary" href="/settings.php">Edit profile</a><?php endif?><button class="button secondary" type="button" id="copyProfile">Copy profile link</button><?php if(!$owner&&$isPublic):?><a class="button secondary" href="/report.php?type=user&id=<?=h($p['public_id'])?>">Report profile</a><?php endif?></div></div></section>
<div class="profileColumns"><section><div class="sectionHeadWeb"><div><span class="eyebrow">PUBLIC ACTIVITY</span><h2>Annotations</h2></div><span class="meta"><?=count($p['annotations'])?> shown</span></div><?php if(!$p['annotations']):?><div class="card">No public annotations yet.</div><?php endif?><?php foreach($p['annotations'] as $a):?><?=annotation_ui_card($a,$viewer,['show_author'=>false])?><?php endforeach?></section>
<aside><div class="sectionHeadWeb"><div><span class="eyebrow">PUBLISHED RESEARCH</span><h2>Reports</h2></div></div><?php if(!$p['reports']):?><div class="card"><p class="meta">No public Research reports yet.</p></div><?php endif?><?php foreach($p['reports'] as $r):?><a class="card sourceCard" href="/research-report.php?id=<?=h($r['public_id'])?>"><div class="meta">Version <?=h((string)$r['version_number'])?> · <?=h((string)$r['published_at'])?></div><h3><?=h($r['title'])?></h3><?php if($r['summary']):?><p><?=h(public_discovery_meta_description($r['summary'],220))?></p><?php endif?></a><?php endforeach?><div class="card privacyNote"><h3>Public profile scope</h3><p class="meta">Only public annotations and explicitly public Research reports appear here. Private saves, followed sources, Team activity, and private Research remain private.</p></div></aside></div></main>
<script>document.querySelector('#copyProfile')?.addEventListener('click',async e=>{await navigator.clipboard.writeText(location.href);e.currentTarget.textContent='Copied';});</script>
<?php if($viewer&&!$owner):?><script>const csrf=<?=json_encode(csrf_token())?>;document.querySelector('#follow')?.addEventListener('click',async e=>{const r=await fetch('/api/extension.php?action=follow',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({user_id:<?=json_encode($p['public_id'])?>})});const j=await r.json();if(j.ok)e.currentTarget.textContent=j.data.following?'Following':'Follow';});</script><?php endif?><?=annotation_ui_scripts($viewer)?></body></html>