<?php
declare(strict_types=1); require __DIR__.'/app/bootstrap.php';
if(!users_exist($pdo)){ header('Location: /first-admin.php'); exit; }
$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
 require_csrf(); $email=strtolower(trim($_POST['email']??''));$username=trim($_POST['username']??'');$name=trim($_POST['display_name']??'');$password=$_POST['password']??'';
 $limit=rate_limit_page_message($pdo,'register-ip',rate_limit_ip_subject(),6,3600)?:rate_limit_page_message($pdo,'register-email',rate_limit_subject($email),3,3600);if($limit)$errors[]=$limit;
 if(!filter_var($email,FILTER_VALIDATE_EMAIL))$errors[]='Enter a valid email.'; if(!preg_match('/^[A-Za-z0-9_]{3,30}$/',$username))$errors[]='Invalid username.'; if(mb_strlen($name)>100)$errors[]='Display name is too long.'; if(strlen($password)<12)$errors[]='Password must be at least 12 characters.';
 if(!$errors){try{$s=$pdo->prepare('INSERT INTO users(public_id,username,display_name,email,password_hash) VALUES(?,?,?,?,?)');$s->execute([ulid_like(),$username,$name?:$username,$email,password_hash($password,PASSWORD_DEFAULT)]);$uid=(int)$pdo->lastInsertId();onboarding_ensure($pdo,$uid);session_regenerate_id(true);$_SESSION['user_id']=$uid;$_SESSION['rotated_at']=time();$_SESSION['last_activity']=time();$_SESSION['auth_time']=time();header('Location:/onboarding.php');exit;}catch(PDOException $e){$errors[]='Email or username is already registered.';}}
}
?><!doctype html><html><head><meta charset="utf-8"><title>Sign up · Annotated</title><link rel="stylesheet" href="/assets/css/app.css"></head><body><main class="panel narrow"><h1>Create your Annotated account</h1><?php foreach($errors as $e):?><div class="error"><?=h($e)?></div><?php endforeach?><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><label>Display name<input name="display_name" required></label><label>Username<input name="username" required></label><label>Email<input type="email" name="email" required></label><label>Password<input type="password" name="password" minlength="12" required></label><button>Create account</button></form><div class="oauth"><a class="button secondary" href="/oauth/google.php">Continue with Google</a><a class="button secondary" href="/oauth/x.php">Continue with X</a></div><p>Already have an account? <a href="/login.php">Log in</a></p></main></body></html>
