<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';require_once __DIR__.'/app/research-knowledge.php';require_once __DIR__.'/app/research-intelligence.php';require_once __DIR__.'/app/research-entities.php';require_once __DIR__.'/app/ai.php';require_once __DIR__.'/app/ai-access.php';
$u=require_user($pdo);$id=(string)($_GET['id']??$_POST['id']??'');$project=project_access($pdo,(int)$u['id'],$id);if(!$project){http_response_code(404);exit('Research project not found.');}$canWrite=project_can_write($project);$snapshot=research_project_brief_snapshot($pdo,(int)$project['id']);$success='';$error='';
$lines=function(array $rows,string $key): string {$out=[];foreach($rows as $r)$out[]='- '.trim((string)($r[$key]??''));return implode("\n",array_filter($out));};
$deterministic=function(array $s)use($lines): array {$c=$s['counts'];$summary="This project currently contains {$c['sources']} sources, {$c['annotations']} annotations, {$c['claims']} claims and {$c['findings']} active findings. {$c['supported']} claims are marked supported, {$c['disputed']} are disputed or contradicted, and {$c['unverified']} remain unverified. There are {$c['open_tasks']} open research tasks and {$c['recent_source_changes']} monitored source changes in the last 30 days.";$key=[];foreach($s['claims'] as $r)if(in_array($r['status'],['supported','resolved'],true)&&((int)$r['evidence_count'])>0)$key[]='- ['.$r['public_id'].'] '.$r['statement'].' ('.$r['status'].', '.$r['evidence_count'].' evidence links)';$conf=[];foreach($s['conflicts'] as $r)$conf[]='- ['.$r['source_id'].'] contradicts ['.$r['target_id'].']';$gaps=[];foreach($s['gaps'] as $r)$gaps[]='- ['.$r['public_id'].'] '.$r['statement'].' (no attached evidence)';$next=[];foreach($s['tasks'] as $r)$next[]='- '.$r['title'].' ('.$r['task_type'].', '.$r['status'].')';return ['summary'=>$summary,'key_evidence'=>implode("\n",$key),'conflicts'=>implode("\n",$conf),'gaps'=>implode("\n",$gaps),'next_steps'=>implode("\n",$next)];};
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();$op=(string)($_POST['op']??'');try{
    if(!$canWrite)throw new RuntimeException('You have view-only access to this project.');$baseBrief=$deterministic($snapshot);$generatedBy='deterministic';$aiRun=null;$summary=$baseBrief['summary'];
    if($op==='generate_ai'){
        if(!user_is_pro($pdo,$u))throw new RuntimeException('AI Research Briefs are available to Pro users.');$isAdmin=($u['role']??'')==='admin';$quota=rate_limit_consume($pdo,$isAdmin?'ai-admin':'ai-pro','user:'.(string)$u['id'],$isAdmin?240:40,3600);if(!$quota['allowed'])throw new RuntimeException('AI request limit reached. Try again later.');
        $model=ai_setting_model_id($pdo,'research',true);if(!$model)$model=ai_setting_model_id($pdo,'pro',true);if(!$model)throw new RuntimeException('No Pro research model is configured.');ai_interactive_model_record($pdo,$u,$model);$raw=ai_research_context($pdo,(int)$project['id']);$knowledge=research_knowledge_ai_context($pdo,(int)$project['id']);$intel=research_intelligence_ai_context($pdo,(int)$project['id']);$entities=research_entity_graph_ai_context($pdo,(int)$project['id']);
        $system='You are Annotated Research Brief. Use only supplied project context. Distinguish captured evidence from human-authored Claims, Findings, Claim relationships, Entities, and Entity relationships. Treat Claim status as a human research state, not proof. Treat Entity status=suggested as unconfirmed extraction, not fact. Cite exact IDs such as [SOURCE id], [ANNOTATION id], [CLAIM id], [FINDING id], [CLAIM-RELATION id], [ENTITY id], and [ENTITY-RELATION id]. Produce a concise briefing with these headings: Executive Summary, Key Evidence, Important Entities, Conflicts, Evidence Gaps, Recent Changes, Next Research Steps. Never invent evidence or citations.';$prompt="Project: {$project['title']}\n\nSOURCE/ANNOTATION CONTEXT:\n{$raw['text']}\n\nKNOWLEDGE CONTEXT:\n{$knowledge['text']}\n\nCLAIM GRAPH/SNAPSHOT CONTEXT:\n{$intel['text']}\n\nENTITY KNOWLEDGE GRAPH:\n{$entities['text']}";$r=ai_run($pdo,$config,$u,$isAdmin?'admin':'pro','research_brief',$model,$system,$prompt,array_merge($raw['refs'],$knowledge['refs'],$intel['refs'],$entities['refs']),'research_project',$project['public_id']);$summary=$r['text'];$generatedBy='ai';$aiRun=$r['public_id'];
    }elseif($op!=='save_snapshot')throw new RuntimeException('Unknown brief action.');
    $pdo->beginTransaction();$pdo->prepare("UPDATE research_briefs SET status='archived' WHERE project_id=? AND status='current'")->execute([$project['id']]);$public=ulid_like();$pdo->prepare('INSERT INTO research_briefs(public_id,project_id,created_by_user_id,generated_by,status,summary,key_evidence,conflicts,gaps,next_steps,snapshot_json,ai_run_public_id) VALUES(?,?,?,?,\'current\',?,?,?,?,?,?,?)')->execute([$public,$project['id'],$u['id'],$generatedBy,$summary,$baseBrief['key_evidence']?:null,$baseBrief['conflicts']?:null,$baseBrief['gaps']?:null,$baseBrief['next_steps']?:null,json_encode($snapshot,JSON_UNESCAPED_SLASHES),$aiRun]);$pdo->commit();$success=$generatedBy==='ai'?'AI Research Brief generated and saved.':'Research snapshot saved as the current Brief.';
}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error=$e->getMessage();}}
$q=$pdo->prepare('SELECT rb.*,u2.display_name FROM research_briefs rb JOIN users u2 ON u2.id=rb.created_by_user_id WHERE rb.project_id=? ORDER BY rb.created_at DESC LIMIT 10');$q->execute([$project['id']]);$briefs=$q->fetchAll();$current=$briefs[0]??null;$preview=$deterministic($snapshot);
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Research Brief · <?=h($project['title'])?> · Annotated</title><link rel="stylesheet" href="/assets/css/app.css"></head><body><header class="topbar"><a class="brand" href="/home.php">Annotated</a><nav><a href="/research-knowledge.php?id=<?=h($project['public_id'])?>">Knowledge</a><a href="/research-graph.php?id=<?=h($project['public_id'])?>">Claim Graph</a><a href="/research-entities.php?id=<?=h($project['public_id'])?>">Entities</a><a href="/research-timeline.php?id=<?=h($project['public_id'])?>">Timeline</a><a href="/research.php">Research</a></nav></header><main class="layout"><section><div class="pageTitle"><span class="eyebrow">RESEARCH BRIEF · <?=h(strtoupper($project['access_role']))?></span><h1><?=h($project['title'])?></h1><p>A point-in-time briefing built from the project's Sources, Annotations, Claims, Claim relationships, Findings, Entity Graph, tasks and monitored source changes.</p></div><?php if($success):?><div class="success"><?=h($success)?></div><?php endif?><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?>
<div class="card"><div class="meta">LIVE PROJECT SNAPSHOT</div><p><?=h($preview['summary'])?></p></div>
<?php if($current):?><h2>Current saved Brief</h2><article class="card"><div class="meta"><?=h(strtoupper($current['generated_by']))?> · <?=h($current['created_at'])?> · <?=h($current['display_name'])?></div><p><?=nl2br(h($current['summary']))?></p><?php foreach(['key_evidence'=>'Key Evidence','conflicts'=>'Conflicts','gaps'=>'Evidence Gaps','next_steps'=>'Next Research Steps'] as $field=>$label):?><?php if($current[$field]):?><h3><?=h($label)?></h3><p><?=nl2br(h($current[$field]))?></p><?php endif?><?php endforeach?></article><?php endif?>
<?php if(count($briefs)>1):?><h2>Brief history</h2><?php foreach(array_slice($briefs,1) as $b):?><details class="card"><summary><?=h(strtoupper($b['generated_by']))?> · <?=h($b['created_at'])?> · <?=h($b['display_name'])?></summary><p><?=nl2br(h($b['summary']))?></p></details><?php endforeach?><?php endif?></section><aside><?php if($canWrite):?><div class="card"><h3>Save current snapshot</h3><p class="meta">Creates a durable Brief without AI and archives the previous current Brief.</p><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="id" value="<?=h($project['public_id'])?>"><input type="hidden" name="op" value="save_snapshot"><button>Save Research Brief</button></form></div><?php endif?><?php if($canWrite&&user_is_pro($pdo,$u)):?><div class="card"><h3>Generate Pro Brief</h3><p class="meta">Synthesizes project evidence, Claim Graph and Entity Graph while preserving exact Annotated citations.</p><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="id" value="<?=h($project['public_id'])?>"><input type="hidden" name="op" value="generate_ai"><button>Generate AI Brief</button></form></div><?php endif?><div class="card"><h3>Snapshot</h3><p class="meta"><?=h((string)$snapshot['counts']['claims'])?> Claims · <?=h((string)$snapshot['counts']['findings'])?> Findings · <?=h((string)$snapshot['counts']['relations'])?> Claim relationships · <?=h((string)$snapshot['counts']['open_tasks'])?> open tasks · <?=h((string)$snapshot['counts']['recent_source_changes'])?> source changes / 30 days</p></div></aside></main></body></html>
