<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';require_once __DIR__.'/app/research-knowledge.php';require_once __DIR__.'/app/research-intelligence.php';require_once __DIR__.'/app/research-workspace.php';
$u=require_user($pdo);$id=(string)($_GET['id']??$_POST['id']??'');$project=project_access($pdo,(int)$u['id'],$id);if(!$project){http_response_code(404);exit('Research project not found.');}$canWrite=project_can_write($project);$success='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();$op=(string)($_POST['op']??'');try{
    if(!$canWrite)throw new RuntimeException('You have view-only access to this project.');
    if($op==='add_relation'){
        $source=research_project_claim_target($pdo,(int)$project['id'],trim((string)($_POST['source_claim']??'')));$target=research_project_claim_target($pdo,(int)$project['id'],trim((string)($_POST['target_claim']??'')));
        if(!$source||!$target)throw new RuntimeException('Both Claims must belong to this Research project.');if((int)$source['id']===(int)$target['id'])throw new RuntimeException('A Claim cannot relate to itself.');
        $type=(string)($_POST['relation_type']??'supports');if(!in_array($type,['supports','contradicts','depends_on','refines','duplicates','context'],true))throw new RuntimeException('Invalid Claim relationship.');
        $pdo->prepare('INSERT INTO claim_relations(public_id,project_id,source_claim_id,target_claim_id,added_by_user_id,relation_type,note) VALUES(?,?,?,?,?,?,?)')->execute([ulid_like(),$project['id'],$source['id'],$target['id'],$u['id'],$type,trim((string)($_POST['note']??''))?:null]);$success='Claim relationship added.';
    }
    if($op==='remove_relation'){$pdo->prepare('DELETE FROM claim_relations WHERE public_id=? AND project_id=?')->execute([(string)($_POST['relation']??''),$project['id']]);$success='Claim relationship removed.';}
    if($success!==''&&research_workspace_ready($pdo))research_workspace_queue($pdo,(int)$project['id'],3);
}catch(Throwable $e){$error=$e->getMessage();}}
$rows=research_project_graph_rows($pdo,(int)$project['id']);$q=$pdo->prepare('SELECT public_id,statement,status FROM research_claims WHERE project_id=? ORDER BY updated_at DESC');$q->execute([$project['id']]);$claims=$q->fetchAll();$counts=[];foreach($rows as $r)$counts[$r['relation_type']]=($counts[$r['relation_type']]??0)+1;
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Claim Graph · <?=h($project['title'])?> · Annotated</title><link rel="stylesheet" href="/assets/css/app.css"></head><body><header class="topbar"><a class="brand" href="/home.php">Annotated</a><nav><a href="/research-knowledge.php?id=<?=h($project['public_id'])?>">Knowledge</a><a href="/research-brief.php?id=<?=h($project['public_id'])?>">Brief</a><a href="/research-timeline.php?id=<?=h($project['public_id'])?>">Timeline</a><a href="/research.php">Research</a></nav></header><main class="layout"><section><div class="pageTitle"><span class="eyebrow">CLAIM GRAPH · <?=h(strtoupper($project['access_role']))?></span><h1><?=h($project['title'])?></h1><p>Connect Claims explicitly so support, contradiction, dependency, refinement and contextual relationships are reviewable instead of hidden inside prose.</p></div><?php if($success):?><div class="success"><?=h($success)?></div><?php endif?><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?>
<div class="card"><div class="meta">GRAPH SUMMARY</div><p><?=count($claims)?> Claims · <?=count($rows)?> relationships<?php foreach($counts as $type=>$n):?> · <?=h((string)$n)?> <?=h(str_replace('_',' ',$type))?><?php endforeach?></p></div>
<h2>Relationships</h2><?php if(!$rows):?><div class="card empty">No Claim relationships yet.</div><?php endif?><?php foreach($rows as $r):?><article class="card"><div class="meta"><?=h(strtoupper(str_replace('_',' ',$r['relation_type'])))?> · <?=h($r['created_at'])?></div><p><a href="/research-claim.php?id=<?=h($r['source_public_id'])?>"><?=h($r['source_statement'])?></a></p><p><strong>→ <?=h(str_replace('_',' ',$r['relation_type']))?> →</strong></p><p><a href="/research-claim.php?id=<?=h($r['target_public_id'])?>"><?=h($r['target_statement'])?></a></p><?php if($r['note']):?><p><?=nl2br(h($r['note']))?></p><?php endif?><?php if($canWrite):?><form method="post" class="inlineForm"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="id" value="<?=h($project['public_id'])?>"><input type="hidden" name="op" value="remove_relation"><input type="hidden" name="relation" value="<?=h($r['public_id'])?>"><button>Remove</button></form><?php endif?></article><?php endforeach?></section><aside><?php if($canWrite):?><div class="card"><h3>Connect Claims</h3><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="id" value="<?=h($project['public_id'])?>"><input type="hidden" name="op" value="add_relation"><label>Source Claim<select name="source_claim" required><option value="">Choose Claim</option><?php foreach($claims as $c):?><option value="<?=h($c['public_id'])?>"><?=h(mb_substr((string)$c['statement'],0,90))?> · <?=h($c['status'])?></option><?php endforeach?></select></label><label>Relationship<select name="relation_type"><option value="supports">Supports</option><option value="contradicts">Contradicts</option><option value="depends_on">Depends on</option><option value="refines">Refines</option><option value="duplicates">Duplicates</option><option value="context">Context</option></select></label><label>Target Claim<select name="target_claim" required><option value="">Choose Claim</option><?php foreach($claims as $c):?><option value="<?=h($c['public_id'])?>"><?=h(mb_substr((string)$c['statement'],0,90))?> · <?=h($c['status'])?></option><?php endforeach?></select></label><label>Note<textarea name="note" rows="3"></textarea></label><button>Add relationship</button></form></div><?php endif?><div class="card"><h3>Direction matters</h3><p class="meta">“A supports B” is different from “B supports A.” Contradiction and dependency are also stored directionally so research reasoning stays explicit.</p></div></aside></main></body></html>
