<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';$viewer=current_user($pdo);$ready=living_research_ready($pdo);$slug=living_research_topic_slug((string)($_GET['topic']??''));$topics=$ready?living_research_public_topics($pdo,120):[];$reports=$ready&&$slug!==''?living_research_public_topic_reports($pdo,$slug,80):[];$selectedLabel='';foreach($topics as $t)if((string)$t['topic_slug']===$slug){$selectedLabel=(string)$t['topic_label'];break;}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=h($selectedLabel!==''?$selectedLabel.' Research':'Research Topics')?> · Annotated</title><meta name="description" content="<?=h($selectedLabel!==''?'Published Living Research about '.$selectedLabel.'.':'Browse public Living Research by publisher-assigned topic.')?>"><link rel="stylesheet" href="/assets/css/app.css"></head><body>
<header class="topbar"><a class="brand" href="/">Annotated</a><nav><?php if($viewer):?><a href="/research-publications.php">Living Research</a><a href="/research.php">Research</a><?php endif?><a href="/explore.php">Explore</a></nav></header>
<main class="topicResearchLayout"><section>
<div class="pageTitle"><span class="eyebrow">LIVING RESEARCH · PUBLIC TOPICS</span><h1><?=h($selectedLabel!==''?$selectedLabel:'Research Topics')?></h1><p><?=h($selectedLabel!==''?'Public immutable Research reports currently tagged with this publisher-assigned topic.':'Browse public Research reports by explicit publisher-assigned topics. Topics organize discovery; they do not imply endorsement, correctness, or consensus.')?></p></div>
<?php if(!$ready):?><div class="card empty"><h2>Living Research is not available yet.</h2><p>The site needs the Phase 24 database upgrade.</p></div>
<?php elseif($slug===''):?>
<div class="topicCloud"><?php if(!$topics):?><div class="card empty">No public report topics have been published yet.</div><?php endif?><?php foreach($topics as $t):?><a class="card topicCard" href="/research-topic.php?topic=<?=h((string)$t['topic_slug'])?>"><strong><?=h((string)$t['topic_label'])?></strong><span><?=h((string)$t['report_count'])?> report<?=((int)$t['report_count']===1?'':'s')?></span><small>Latest publication <?=h((string)$t['last_published_at'])?></small></a><?php endforeach?></div>
<?php else:?>
<?php if(!$reports):?><div class="card empty"><h2>No current public reports for this topic.</h2><p>The topic may have been removed, renamed, or its reports may no longer be public.</p><a href="/research-topic.php">Browse all topics</a></div><?php endif?>
<div class="livingReportGrid"><?php foreach($reports as $r):?><article class="card livingHubCard"><div class="livingReportBadges"><span class="badge">v<?=h((string)$r['version_number'])?></span><span class="badge"><?=h((string)$r['topic_label'])?></span></div><h2><a href="/research-report.php?id=<?=h((string)$r['public_id'])?>"><?=h((string)$r['title'])?></a></h2><?php if(!empty($r['summary'])):?><p><?=h(mb_substr((string)$r['summary'],0,520))?></p><?php endif?><p class="meta">Published <?=h((string)$r['published_at'])?> · <?=h((string)$r['display_name'])?><?php if(!empty($r['username'])):?> · <a href="/<?=h((string)$r['username'])?>">@<?=h((string)$r['username'])?></a><?php endif?></p></article><?php endforeach?></div>
<?php endif?></section>
<aside><div class="card stickyLivingRail"><h3>Topic boundary</h3><p class="meta">Topics are assigned by the report publisher and are used only for discovery. They do not change report evidence, Claims, Findings, or visibility.</p><?php if($slug!==''):?><a href="/research-topic.php">All topics</a><?php endif?></div></aside>
</main></body></html>