<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';
$u=require_user($pdo);header('Cache-Control: private, no-store');header('Vary: Cookie');
if(!research_intelligence_portfolio_operations_ready($pdo)){header('Location: /upgrade.php?from=research-intelligence-command-center');exit;}
$center=research_intelligence_organization_command_center($pdo,$u);$s=$center['summary'];
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Intelligence Command Center · Annotated</title><meta name="robots" content="noindex,nofollow"><link rel="stylesheet" href="/assets/css/app.css?v=61.0"></head><body data-workspace-user="<?=h((string)$u['public_id'])?>" data-workspace-surface="research-intelligence-command-center">
<main class="intelligenceCommandCenter">
<section class="researchLibraryToolbar"><nav class="researchLibraryTabs researchPrimaryActions"><a href="/research.php">Research Agents</a><a href="/research-programs.php">Programs</a><a href="/research-portfolio.php">Project Portfolio</a><a href="/research-intelligence-portfolios.php">Intelligence Portfolios</a><a class="active" href="/research-intelligence-command-center.php">Command Center</a><a href="/research-publications.php">Publishing</a><a href="/research-reviews.php">Review Center</a></nav></section>
<header class="intelligenceCommandHero"><div><span class="eyebrow">PHASE 61 · ORGANIZATION COMMAND CENTER</span><h1>Executive Intelligence</h1><p>One permission-checked view across Portfolio attention, material changes, follow-through, opportunities, cross-Portfolio themes, and briefings awaiting human review.</p></div><small>Generated <?=h((string)$center['generated_at'])?></small></header>
<section class="intelligencePortfolioStats"><div><strong><?=h((string)$s['portfolios'])?></strong><span>Portfolios</span></div><div><strong><?=h((string)$s['programs'])?></strong><span>Programs</span></div><div><strong><?=h((string)count($center['needs_attention']))?></strong><span>Need attention</span></div><div><strong><?=h((string)count($center['new_since_last_briefing']))?></strong><span>Changed</span></div><div><strong><?=h((string)count($center['decisions_awaiting_follow_through']))?></strong><span>Follow-through</span></div><div><strong><?=h((string)count($center['briefings_awaiting_review']))?></strong><span>Briefings in review</span></div></section>
<section class="intelligenceCommandGrid">
<section class="card"><span class="eyebrow">NEEDS ATTENTION</span><h2>Portfolio attention</h2><?php if(!$center['needs_attention']):?><p class="empty">No current Portfolio attention signals.</p><?php endif?><?php foreach($center['needs_attention'] as $x):?><article class="commandCenterRow"><div><strong><?=h((string)$x['title'])?></strong><small><?=h((string)$x['risks'])?> risks · <?=h((string)$x['tensions'])?> tensions<?=!empty($x['briefing_due'])?' · briefing due':''?></small></div><a href="/research-intelligence-portfolios.php?portfolio=<?=rawurlencode((string)$x['portfolio_id'])?>">Open</a></article><?php endforeach?></section>
<section class="card"><span class="eyebrow">NEW SINCE LAST BRIEFING</span><h2>Material movement</h2><?php if(!$center['new_since_last_briefing']):?><p class="empty">No newly material Portfolio cycle changes.</p><?php endif?><?php foreach($center['new_since_last_briefing'] as $x):?><article class="commandCenterRow"><div><strong><?=h((string)$x['title'])?></strong><small><?=h((string)($x['cycle']['detail']??'Material Portfolio change recorded.'))?></small></div><a href="/research-intelligence-portfolios.php?portfolio=<?=rawurlencode((string)$x['portfolio_id'])?>">Review</a></article><?php endforeach?></section>
<section class="card"><span class="eyebrow">DECISIONS AWAITING FOLLOW-THROUGH</span><h2>Commitments</h2><?php if(!$center['decisions_awaiting_follow_through']):?><p class="empty">No open executive follow-through tasks.</p><?php endif?><?php foreach($center['decisions_awaiting_follow_through'] as $x):?><article class="commandCenterRow"><div><strong><?=h((string)$x['title'])?></strong><small><?=h((string)$x['portfolio_title'])?> · <?=h((string)$x['task_status'])?><?=!empty($x['due_at'])?' · due '.h((string)$x['due_at']):''?></small></div><a href="/research-tasks.php?task=<?=rawurlencode((string)$x['task_public_id'])?>">Open task</a></article><?php endforeach?></section>
<section class="card"><span class="eyebrow">EMERGING OPPORTUNITIES</span><h2>Positive movement</h2><?php if(!$center['emerging_opportunities']):?><p class="empty">No current deterministic opportunity signals.</p><?php endif?><?php foreach($center['emerging_opportunities'] as $x):?><article class="commandCenterRow"><div><strong><?=h((string)$x['portfolio_title'])?></strong><small><?=h((string)($x['summary']??''))?></small></div><a href="/research-intelligence-portfolios.php?portfolio=<?=rawurlencode((string)$x['portfolio_id'])?>">Open</a></article><?php endforeach?></section>
<section class="card"><span class="eyebrow">CROSS-PORTFOLIO THEMES</span><h2>Shared organizational signals</h2><?php if(!$center['cross_portfolio_themes']):?><p class="empty">No reference currently spans multiple accessible Portfolios.</p><?php endif?><?php foreach($center['cross_portfolio_themes'] as $x):?><article class="commandTheme"><strong><?=h((string)$x['key'])?></strong><span><?=h((string)$x['portfolio_count'])?> Portfolios</span><small><?=h(implode(' · ',array_values($x['portfolios'])))?></small></article><?php endforeach?></section>
<section class="card"><span class="eyebrow">BRIEFINGS AWAITING REVIEW</span><h2>Human governance</h2><?php if(!$center['briefings_awaiting_review']):?><p class="empty">No Executive Briefings currently waiting in Phase 59 review.</p><?php endif?><?php foreach($center['briefings_awaiting_review'] as $x):?><article class="commandCenterRow"><div><strong><?=h((string)$x['title'])?></strong><small><?=h((string)$x['portfolio_title'])?> · <?=h((string)($x['publication_status']??$x['status']))?></small></div><?php if(!empty($x['publication_public_id'])):?><a href="/research-publications.php?workflow=<?=rawurlencode((string)$x['publication_public_id'])?>">Review</a><?php else:?><a href="/research-intelligence-portfolios.php?portfolio=<?=rawurlencode((string)$x['portfolio_id'])?>">Open</a><?php endif?></article><?php endforeach?></section>
</section>
</main></body></html>