<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';
$u=require_user($pdo);header('Cache-Control: private, no-store');header('Vary: Cookie');
if(!research_intelligence_portfolios_ready($pdo)){header('Location: /upgrade.php?from=research-intelligence-portfolios');exit;}
$error='';$success='';$portfolioId=trim((string)($_GET['portfolio']??$_POST['portfolio_id']??''));
if($_SERVER['REQUEST_METHOD']==='POST'){
    require_csrf();$op=(string)($_POST['op']??'');
    try{
        if($op==='create'){
            $p=research_intelligence_portfolio_create($pdo,$u,[
              'title'=>(string)($_POST['title']??''),'objective'=>(string)($_POST['objective']??''),'team_id'=>(string)($_POST['team_id']??''),
              'briefing_cadence'=>(string)($_POST['briefing_cadence']??'manual'),'timezone_name'=>(string)($_POST['timezone_name']??($u['timezone_name']??'UTC')),
              'briefing_time_local'=>(string)($_POST['briefing_time_local']??'09:00'),'briefing_weekday'=>(int)($_POST['briefing_weekday']??1),'briefing_day_of_month'=>(int)($_POST['briefing_day_of_month']??1)
            ]);header('Location: /research-intelligence-portfolios.php?portfolio='.rawurlencode((string)$p['public_id']).'&created=1');exit;
        }
        if($portfolioId==='')throw new InvalidArgumentException('Choose a Portfolio first.');
        if($op==='add_program'){research_intelligence_portfolio_add_program($pdo,$u,$portfolioId,(string)($_POST['program_id']??''),(string)($_POST['member_role']??'supporting'));$success='Program added to Portfolio.';}
        elseif($op==='remove_program'){research_intelligence_portfolio_remove_program($pdo,$u,$portfolioId,(string)($_POST['program_id']??''));$success='Program removed from Portfolio.';}
        elseif($op==='snapshot'){research_intelligence_portfolio_snapshot($pdo,$u,$portfolioId,(int)($_POST['window_days']??30),'manual');$success='Frozen Portfolio snapshot created.';}
        elseif($op==='briefing'){$b=research_intelligence_portfolio_create_briefing($pdo,$u,$portfolioId,['title'=>(string)($_POST['title']??''),'window_days'=>(int)($_POST['window_days']??30)]);$success='Executive Briefing created as a normal Research Doc.';}
        elseif($op==='prepare_publication'){$w=research_intelligence_portfolio_prepare_publication($pdo,$u,(string)($_POST['briefing_id']??''),['required_approvals'=>(int)($_POST['required_approvals']??1)]);header('Location: /research-publications.php?workflow='.rawurlencode((string)$w['public_id']));exit;}
        elseif($op==='archive'){$p=research_intelligence_portfolio_access($pdo,$u,$portfolioId);if(!$p||!research_intelligence_portfolio_can_write($p))throw new RuntimeException('Portfolio is unavailable.');$pdo->prepare("UPDATE research_intelligence_portfolios SET status='archived',updated_at=NOW() WHERE id=?")->execute([(int)$p['id']]);research_intelligence_portfolio_event($pdo,(int)$p['id'],'archived','user',(int)$u['id']);header('Location: /research-intelligence-portfolios.php');exit;}
    }catch(Throwable $e){$error=$e->getMessage();}
}
$dashboard=research_intelligence_portfolio_dashboard($pdo,$u);$portfolios=$dashboard['portfolios'];$selected=$portfolioId!==''?research_intelligence_portfolio_detail($pdo,$u,$portfolioId):null;
if(!$selected&&$portfolios){$portfolioId=(string)$portfolios[0]['public_id'];$selected=research_intelligence_portfolio_detail($pdo,$u,$portfolioId);}
$teams=[];try{$q=$pdo->prepare("SELECT t.public_id,t.name,tm.role FROM teams t JOIN team_members tm ON tm.team_id=t.id WHERE tm.user_id=? AND tm.role IN ('owner','admin','researcher') ORDER BY t.name");$q->execute([(int)$u['id']]);$teams=$q->fetchAll()?:[];}catch(Throwable $e){}
$csrf=csrf_token();$summary=$dashboard['summary'];
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Intelligence Portfolios · Annotated</title><meta name="robots" content="noindex,nofollow"><link rel="stylesheet" href="/assets/css/app.css?v=60.0"></head>
<body data-workspace-user="<?=h((string)$u['public_id'])?>" data-workspace-surface="research-intelligence-portfolios">
<main class="intelligencePortfolioCanvas">
<section class="researchLibraryToolbar"><nav class="researchLibraryTabs researchPrimaryActions"><a href="/research.php">Research Agents</a><a href="/research-programs.php">Programs</a><a href="/research-portfolio.php">Project Portfolio</a><a class="active" href="/research-intelligence-portfolios.php">Intelligence Portfolios</a><a href="/research-publications.php">Publishing</a><a href="/research-reviews.php">Review Center</a></nav></section>
<header class="intelligencePortfolioHero"><div><span class="eyebrow">PHASE 60 · ORGANIZATION INTELLIGENCE</span><h1>Research Intelligence Portfolios</h1><p>Roll multiple Research Programs into explainable cross-program trends, risks, opportunities, tensions, immutable snapshots, and executive briefings without creating a second Research or publishing system.</p></div></header>
<?php if($success):?><div class="success"><?=h($success)?></div><?php endif?><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?>
<section class="intelligencePortfolioStats">
<div><strong><?=h((string)$summary['portfolios'])?></strong><span>Portfolios</span></div><div><strong><?=h((string)$summary['programs'])?></strong><span>Programs</span></div><div><strong><?=h((string)$summary['briefings'])?></strong><span>Briefings</span></div><div><strong><?=h((string)$summary['risk_signals'])?></strong><span>Risk signals</span></div><div><strong><?=h((string)$summary['opportunity_signals'])?></strong><span>Opportunity signals</span></div><div><strong><?=h((string)$summary['cross_program_tensions'])?></strong><span>Cross-program tensions</span></div>
</section>
<section class="intelligencePortfolioGrid">
<aside class="card intelligencePortfolioCreate"><span class="eyebrow">NEW PORTFOLIO</span><h2>Group Research Programs</h2><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="op" value="create"><label>Portfolio title<input name="title" required maxlength="255" placeholder="Market Intelligence"></label><label>Objective<textarea name="objective" required rows="5" maxlength="16000" placeholder="What should leadership continuously understand across these Programs?"></textarea></label><label>Scope<select name="team_id"><option value="">Personal</option><?php foreach($teams as $team):?><option value="<?=h((string)$team['public_id'])?>"><?=h((string)$team['name'])?></option><?php endforeach?></select></label><label>Briefing cadence<select name="briefing_cadence"><option value="manual">Manual</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option></select></label><input type="hidden" name="timezone_name" value="<?=h((string)($u['timezone_name']??'UTC'))?>"><button>Create Portfolio</button></form><p class="meta">Portfolios aggregate existing Program state. They do not create another worker, scheduler, Claim store, task system, or document system.</p></aside>
<section class="intelligencePortfolioList">
<header><div><span class="eyebrow">PORTFOLIOS</span><h2>Organization intelligence</h2></div><small>Generated <?=h((string)$dashboard['generated_at'])?></small></header>
<?php if(!$portfolios):?><div class="card empty"><h3>No Intelligence Portfolios yet.</h3><p>Create one and add existing Research Programs.</p></div><?php endif?>
<?php foreach($portfolios as $p):$a=$p['aggregate']['summary']??[];$sel=$selected&&$selected['public_id']===$p['public_id'];?>
<article class="card intelligencePortfolioCard <?=$sel?'is-selected':''?>"><a href="/research-intelligence-portfolios.php?portfolio=<?=rawurlencode((string)$p['public_id'])?>"><div><span><?=!empty($p['team_name'])?h((string)$p['team_name']):'PERSONAL'?></span><h3><?=h((string)$p['title'])?></h3></div><strong><?=h((string)$p['program_count'])?> Programs</strong></a><p><?=h(mb_substr((string)$p['objective'],0,260))?></p><div class="intelligencePortfolioMeta"><span><?=h((string)($a['material_changes']??0))?> changes</span><span><?=h((string)($a['high_changes']??0))?> high</span><span><?=!empty($p['briefing_due'])?'Briefing due':'Briefing current'?></span></div></article>
<?php endforeach?>
</section></section>
<?php if($selected):$a=$selected['aggregate'];$canWrite=research_intelligence_portfolio_can_write($selected);?>
<section class="card intelligencePortfolioDetail">
<header class="intelligencePortfolioDetailHeader"><div><span class="eyebrow">PROGRAM PORTFOLIO</span><h2><?=h((string)$selected['title'])?></h2><p><?=h((string)$selected['objective'])?></p></div><div class="intelligencePortfolioDetailMeta"><span><?=!empty($selected['team_name'])?h((string)$selected['team_name']):'Personal scope'?></span><span><?=h((string)$selected['access_role'])?></span></div></header>
<section class="intelligencePortfolioOverview"><div><strong><?=h((string)$a['summary']['programs'])?></strong><span>Programs</span></div><div><strong><?=h((string)$a['summary']['material_changes'])?></strong><span>Material changes</span></div><div><strong><?=h((string)$a['summary']['high_changes'])?></strong><span>High changes</span></div><div><strong><?=h((string)$a['summary']['failed_runs_30d'])?></strong><span>Failed runs · 30d</span></div><div><strong><?=h((string)$a['summary']['stale_sources'])?></strong><span>Stale evidence</span></div></section>
<div class="intelligencePortfolioColumns">
<section><header><span class="eyebrow">PROGRAMS</span><h3>Portfolio members</h3></header><?php if(!$selected['programs']):?><div class="empty">No Programs added yet.</div><?php endif?><?php foreach($selected['programs'] as $program):?><article class="intelligenceProgramRow"><div><strong><?=h((string)$program['title'])?></strong><small><?=h((string)$program['project_title'])?> · <?=h((string)$program['member_role'])?> · <?=h((string)$program['status'])?></small></div><a href="/research-programs.php?agent=<?=rawurlencode((string)$program['agent_public_id'])?>&program=<?=rawurlencode((string)$program['public_id'])?>">Open</a><?php if($canWrite):?><form method="post"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="portfolio_id" value="<?=h((string)$selected['public_id'])?>"><input type="hidden" name="op" value="remove_program"><input type="hidden" name="program_id" value="<?=h((string)$program['public_id'])?>"><button class="linkButton">Remove</button></form><?php endif?></article><?php endforeach?>
<?php if($canWrite&&!empty($selected['available_programs'])):?><form method="post" class="intelligencePortfolioAddProgram"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="portfolio_id" value="<?=h((string)$selected['public_id'])?>"><input type="hidden" name="op" value="add_program"><label>Add Program<select name="program_id"><?php foreach($selected['available_programs'] as $program):?><option value="<?=h((string)$program['public_id'])?>"><?=h((string)$program['title'])?> · <?=h((string)$program['project_title'])?></option><?php endforeach?></select></label><label>Role<select name="member_role"><option value="primary">Primary</option><option value="supporting" selected>Supporting</option><option value="watch">Watch</option></select></label><button>Add</button></form><?php endif?></section>
<section><header><span class="eyebrow">CROSS-PROGRAM INTELLIGENCE</span><h3>Risks & opportunities</h3></header><div class="intelligenceSignalGroup"><h4>Risks</h4><?php if(!$a['risks']):?><p class="meta">No deterministic risk deltas in this window.</p><?php endif?><?php foreach(array_slice($a['risks'],0,8) as $r):?><div class="intelligenceSignal is-risk"><strong><?=h((string)$r['program_title'])?></strong><span><?=h((string)$r['summary'])?></span></div><?php endforeach?></div><div class="intelligenceSignalGroup"><h4>Opportunities / positive movement</h4><?php if(!$a['opportunities']):?><p class="meta">No positive deterministic deltas in this window.</p><?php endif?><?php foreach(array_slice($a['opportunities'],0,8) as $r):?><div class="intelligenceSignal is-opportunity"><strong><?=h((string)$r['program_title'])?></strong><span><?=h((string)$r['summary'])?></span></div><?php endforeach?></div></section>
</div>
<section class="intelligencePortfolioTensions"><header><span class="eyebrow">SHARED REFERENCES</span><h3>Cross-program trends & tensions</h3></header><?php if(!$a['cross_program']):?><div class="empty">No shared cross-program reference signals in the current window.</div><?php endif?><div class="intelligenceTensionGrid"><?php foreach($a['cross_program'] as $x):?><article class="<?=$x['kind']==='cross_program_tension'?'is-tension':''?>"><strong><?=h(ucwords(str_replace('_',' ',(string)$x['kind'])))?></strong><span><?=h((string)$x['key'])?></span><small><?=h((string)$x['program_count'])?> Programs</small></article><?php endforeach?></div></section>
<section class="intelligencePortfolioInference"><header><div><span class="eyebrow">AGENT INTERPRETATION</span><h3>Explicit inference layer</h3></div><p>These are interpretations, not deterministic portfolio facts. Each inference retains explicit provenance references and optional confidence.</p></header><?php if(!$selected['inferences']):?><div class="empty">No Agent inferences have been attached to this Portfolio.</div><?php endif?><?php foreach($selected['inferences'] as $i):?><article><div><span class="badge"><?=h(strtoupper((string)$i['category']))?></span><span class="badge"><?=h(strtoupper((string)$i['severity']))?></span><?php if($i['confidence']!==null):?><span class="badge"><?=h((string)round((float)$i['confidence']*100))?>% confidence</span><?php endif?></div><h4><?=h((string)$i['title'])?></h4><p><?=h((string)$i['body'])?></p><small><?=h((string)count((array)($i['provenance']['refs']??[])))?> provenance ref(s)</small></article><?php endforeach?></section>
<section class="intelligencePortfolioActions"><?php if($canWrite):?><form method="post"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="portfolio_id" value="<?=h((string)$selected['public_id'])?>"><input type="hidden" name="op" value="snapshot"><label>Snapshot window<input type="number" name="window_days" min="1" max="365" value="30"></label><button>Create frozen snapshot</button></form><form method="post"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="portfolio_id" value="<?=h((string)$selected['public_id'])?>"><input type="hidden" name="op" value="briefing"><input type="hidden" name="window_days" value="30"><label>Briefing title<input name="title" maxlength="240" placeholder="Optional custom title"></label><button>Create Executive Briefing</button></form><?php endif?></section>
<section class="intelligenceBriefings"><header><span class="eyebrow">EXECUTIVE BRIEFINGS</span><h3>Living briefing documents</h3></header><?php if(!$selected['briefings']):?><div class="empty">No briefings yet.</div><?php endif?><?php foreach($selected['briefings'] as $b):?><article><div><strong><?=h((string)$b['title'])?></strong><small><?=h((string)$b['created_at'])?> · <?=h((string)$b['status'])?></small></div><div><a href="/home.php<?=!empty($b['conversation_public_id'])?'?agent='.rawurlencode((string)$b['conversation_public_id']).'&doc='.rawurlencode((string)$b['document_public_id']):''?>">Open Research Doc</a><?php if(!empty($b['publication_public_id'])):?><a href="/research-publications.php?workflow=<?=rawurlencode((string)$b['publication_public_id'])?>">Open publication workflow</a><?php elseif($canWrite):?><form method="post"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="portfolio_id" value="<?=h((string)$selected['public_id'])?>"><input type="hidden" name="op" value="prepare_publication"><input type="hidden" name="briefing_id" value="<?=h((string)$b['public_id'])?>"><input type="hidden" name="required_approvals" value="1"><button class="linkButton">Send to Phase 59 review</button></form><?php endif?></div></article><?php endforeach?></section>
</section><?php endif?>
</main></body></html>