<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';
$u=require_user($pdo);header('Cache-Control: private, no-store');$error='';$success='';
try{research_account_require_approved($pdo,$u);}catch(Throwable $e){$error=$e->getMessage();}
if($_SERVER['REQUEST_METHOD']==='POST'&&!$error){require_csrf();try{sponsored_research_knowledge_item_revoke_rights($pdo,$u,(string)($_POST['item_id']??''),(string)($_POST['reason']??''));$success='Future use revoked. Historical releases and audit lineage were preserved.';}catch(Throwable $e){$error=$e->getMessage();}}
$items=$error?[]:sponsored_research_knowledge_items_for_contributor($pdo,$u,250);
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sponsored Knowledge Rights · Annotated</title><link rel="stylesheet" href="/assets/css/app.css"></head><body><main class="panel" style="max-width:1100px;margin:32px auto"><div class="pageTitle"><span class="eyebrow">SPONSORED RESEARCH</span><h1>Knowledge Rights</h1><p>Review Sponsored Research Knowledge items attributed to you. Revocation blocks future use while preserving historical release evidence and provenance.</p></div>
<?php if($error):?><div class="error"><?=h($error)?></div><?php endif?><?php if($success):?><div class="success"><?=h($success)?></div><?php endif?>
<section class="card"><?php if(!$items):?><p>No promoted Sponsored Research Knowledge items.</p><?php else:?><?php foreach($items as $i):?><article style="margin-bottom:20px"><strong><?=h((string)$i['title'])?></strong><div class="meta"><?=h((string)$i['campaign_title'])?> · <?=h((string)$i['knowledge_base_name'])?> · <?=h((string)$i['state'])?> · future use <?=$i['future_use_allowed']?'allowed':'blocked'?></div><p><?=h(mb_substr((string)$i['body'],0,320))?></p><?php if((string)$i['state']==='active'&&(int)$i['future_use_allowed']===1):?><form method="post" class="stack"><?=csrf_field()?><input type="hidden" name="item_id" value="<?=h((string)$i['public_id'])?>"><label>Reason for future-use revocation<textarea name="reason" rows="3" required></textarea></label><button>Revoke future use</button></form><?php endif?></article><?php endforeach?><?php endif?></section></main></body></html>