<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';
$u=require_user($pdo);header('Cache-Control: private, no-store');$error='';$success='';
$projectPublic=(string)($_GET['project']??$_POST['project_id']??'');$sp=sponsored_research_project_get($pdo,$projectPublic);if(!$sp){http_response_code(404);exit('Sponsored Research project not found.');}
$canManage=false;$contributor=null;
try{sponsored_research_project_require_manage($pdo,$u,$projectPublic);$canManage=true;}catch(Throwable $e){}
$q=$pdo->prepare('SELECT * FROM sponsored_research_project_contributors WHERE sponsored_project_id=? AND user_id=? LIMIT 1');$q->execute([(int)$sp['id'],(int)$u['id']]);$contributor=$q->fetch()?:null;
if(!$canManage&&!$contributor){http_response_code(403);exit('Project access required.');}
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();try{
 $op=(string)($_POST['op']??'');
 if($op==='accept_invite'){sponsored_research_project_accept($pdo,$u,$projectPublic);$success='Project invitation accepted.';}
 elseif($op==='invite'){if(!$canManage)throw new RuntimeException('Project manager access required.');sponsored_research_project_invite($pdo,$u,$projectPublic,(string)($_POST['username']??''),(string)($_POST['role']??'researcher'));$success='Contributor invited.';}
 elseif($op==='remove'){if(!$canManage)throw new RuntimeException('Project manager access required.');sponsored_research_project_remove_contributor($pdo,$u,$projectPublic,(int)($_POST['user_id']??0));$success='Contributor removed.';}
 elseif($op==='task_create'){if(!$canManage)throw new RuntimeException('Project manager access required.');$task=sponsored_research_project_task($pdo,$u,$projectPublic,['title'=>(string)($_POST['title']??''),'description'=>(string)($_POST['description']??''),'task_type'=>(string)($_POST['task_type']??'general'),'priority'=>(string)($_POST['priority']??'medium'),'due_at'=>(string)($_POST['due_at']??'')]);$success='Research task created.';}
 elseif($op==='assign'){if(!$canManage)throw new RuntimeException('Project manager access required.');sponsored_research_project_task_assign($pdo,$u,$projectPublic,(string)($_POST['task_id']??''),(int)($_POST['contributor_user_id']??0),(string)($_POST['assignment_role']??'contributor'));$success='Task assigned.';}
 elseif($op==='assignment_status'){sponsored_research_project_assignment_update($pdo,$u,(string)($_POST['assignment_id']??''),(string)($_POST['status']??''));$success='Task assignment updated.';}
 elseif($op==='submit_ref'){sponsored_research_project_submit_ref($pdo,$u,(string)($_POST['assignment_id']??''),(string)($_POST['ref_type']??''),(string)($_POST['ref_public_id']??''),(string)($_POST['note']??''));$success='Research deliverable attached to the task.';}
}catch(Throwable $e){$error=$e->getMessage();}}
$sp=sponsored_research_project_get($pdo,$projectPublic);$contributors=sponsored_research_project_contributors($pdo,$projectPublic);$tasks=sponsored_research_project_tasks($pdo,$projectPublic);$assignments=sponsored_research_project_assignments($pdo,$projectPublic,$canManage?null:(int)$u['id']);$events=sponsored_research_project_events($pdo,$projectPublic,60);
$q=$pdo->prepare("SELECT r.public_id,r.assignment_id,r.ref_type,r.ref_public_id,r.note,r.submitted_at,u.display_name FROM sponsored_research_task_deliverable_refs r JOIN sponsored_research_task_assignments a ON a.id=r.assignment_id JOIN users u ON u.id=r.contributor_user_id WHERE a.sponsored_project_id=? ORDER BY r.id DESC LIMIT 100");$q->execute([(int)$sp['id']]);$deliverables=$q->fetchAll()?:[];
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=h((string)$sp['campaign_title'])?> · Sponsored Project · Annotated</title><link rel="stylesheet" href="/assets/css/app.css"></head><body>
<main class="panel" style="max-width:1200px;margin:32px auto">
<div class="pageTitle"><span class="eyebrow">SPONSORED RESEARCH PROJECT</span><h1><?=h((string)$sp['research_project_title'])?></h1><p><?=nl2br(h((string)$sp['campaign_brief']))?></p><div class="inlineActions"><a class="button secondary" href="/research-project.php?id=<?=rawurlencode((string)$sp['research_project_public_id'])?>">Open canonical Research Project</a><?php if($sp['research_agent_public_id']):?><a class="button secondary" href="/research-agent-research.php?agent=<?=rawurlencode((string)$sp['research_agent_public_id'])?>">Open Research Agent</a><?php endif?></div></div>
<?php if($error):?><div class="error"><?=h($error)?></div><?php endif?><?php if($success):?><div class="success"><?=h($success)?></div><?php endif?>
<?php if(!$canManage&&$contributor&&$contributor['status']==='invited'):?><section class="card"><h2>Project invitation</h2><p>You were invited as <?=h((string)$contributor['role'])?>. Accepting adds you to the project Team so the normal Research Project, Tasks, Sources, and Agent surfaces use the same access rules.</p><form method="post"><?=csrf_field()?><input type="hidden" name="project_id" value="<?=h($projectPublic)?>"><input type="hidden" name="op" value="accept_invite"><button>Accept project invitation</button></form></section><?php endif?>

<div class="researchHomeStats"><div><strong><?=count(array_filter($contributors,fn($x)=>$x['status']==='active'))?></strong><span>Active contributors</span></div><div><strong><?=count($tasks)?></strong><span>Tasks</span></div><div><strong><?=count(array_filter($assignments,fn($x)=>$x['status']==='submitted'))?></strong><span>Submitted assignments</span></div><div><strong><?=count($deliverables)?></strong><span>Deliverable refs</span></div></div>

<section class="card"><h2>Contributors</h2><?php if($canManage):?><form method="post" class="stack"><?=csrf_field()?><input type="hidden" name="project_id" value="<?=h($projectPublic)?>"><input type="hidden" name="op" value="invite"><label>Approved Research Account username<input name="username" required></label><label>Project role<select name="role"><option value="researcher">Researcher</option><option value="lead">Lead</option><option value="reviewer">Reviewer</option><option value="observer">Observer</option></select></label><button>Invite contributor</button></form><?php endif?>
<table><thead><tr><th>Contributor</th><th>Role</th><th>Status</th><?php if($canManage):?><th></th><?php endif?></tr></thead><tbody><?php foreach($contributors as $c):?><tr><td><?=h((string)$c['display_name'])?><div class="meta">@<?=h((string)$c['username'])?></div></td><td><?=h(ucfirst((string)$c['role']))?></td><td><?=h(ucfirst((string)$c['status']))?></td><?php if($canManage):?><td><?php if($c['status']==='active'):?><form method="post"><?=csrf_field()?><input type="hidden" name="project_id" value="<?=h($projectPublic)?>"><input type="hidden" name="op" value="remove"><input type="hidden" name="user_id" value="<?=h((string)$c['user_id'])?>"><button class="button secondary">Remove</button></form><?php endif?></td><?php endif?></tr><?php endforeach?></tbody></table></section>

<section class="card"><h2>Research tasks</h2><?php if($canManage):?><form method="post" class="stack"><?=csrf_field()?><input type="hidden" name="project_id" value="<?=h($projectPublic)?>"><input type="hidden" name="op" value="task_create"><label>Task title<input name="title" required></label><label>Instructions<textarea name="description" rows="4"></textarea></label><div class="researchAgentEditSplit"><label>Type<select name="task_type"><?php foreach(research_task_types() as $k=>$label):?><option value="<?=h($k)?>"><?=h($label)?></option><?php endforeach?></select></label><label>Priority<select name="priority"><?php foreach(research_task_priorities() as $k=>$label):?><option value="<?=h($k)?>"><?=h($label)?></option><?php endforeach?></select></label><label>Due<input type="datetime-local" name="due_at"></label></div><button>Create task</button></form><?php endif?>
<?php foreach($tasks as $t):?><article class="card"><strong><?=h((string)$t['title'])?></strong><div class="meta"><?=h((string)$t['priority'])?> · <?=h((string)$t['status'])?><?php if($t['due_at']):?> · due <?=h((string)$t['due_at'])?><?php endif?> · <?=h((string)$t['assignment_count'])?> assignments</div><?php if($t['description']):?><p><?=nl2br(h((string)$t['description']))?></p><?php endif?>
<?php if($canManage):?><form method="post" class="inlineForm"><?=csrf_field()?><input type="hidden" name="project_id" value="<?=h($projectPublic)?>"><input type="hidden" name="op" value="assign"><input type="hidden" name="task_id" value="<?=h((string)$t['public_id'])?>"><select name="contributor_user_id" required><option value="">Assign contributor</option><?php foreach($contributors as $pc):if($pc['status']!=='active')continue;?><option value="<?=h((string)$pc['user_id'])?>"><?=h((string)$pc['display_name'])?></option><?php endforeach?></select><select name="assignment_role"><option value="contributor">Contributor</option><option value="owner">Owner</option><option value="reviewer">Reviewer</option></select><button>Assign</button></form><?php endif?></article><?php endforeach?></section>

<section class="card"><h2><?= $canManage?'Assignments':'My assignments' ?></h2><?php if(!$assignments):?><p>No assignments yet.</p><?php endif?><?php foreach($assignments as $a):?><article class="card"><strong><?=h((string)$a['task_title'])?></strong><div class="meta"><?=h((string)$a['display_name'])?> · <?=h((string)$a['assignment_role'])?> · <?=h((string)$a['status'])?></div>
<?php if((int)$a['contributor_user_id']===(int)$u['id']):?><form method="post" class="inlineForm"><?=csrf_field()?><input type="hidden" name="project_id" value="<?=h($projectPublic)?>"><input type="hidden" name="op" value="assignment_status"><input type="hidden" name="assignment_id" value="<?=h((string)$a['public_id'])?>"><?php if($a['status']==='assigned'):?><button name="status" value="accepted">Accept task</button><?php endif?><?php if(in_array($a['status'],['accepted','assigned'],true)):?><button name="status" value="in_progress">Start</button><?php endif?></form>
<form method="post" class="stack"><?=csrf_field()?><input type="hidden" name="project_id" value="<?=h($projectPublic)?>"><input type="hidden" name="op" value="submit_ref"><input type="hidden" name="assignment_id" value="<?=h((string)$a['public_id'])?>"><label>Deliverable type<select name="ref_type"><option value="annotation">Annotation</option><option value="source">Source</option><option value="claim">Claim</option><option value="finding">Finding</option><option value="report_version">Report version</option><option value="mission">Mission</option><option value="dataset">Dataset</option><option value="document">Document</option></select></label><label>Public ID<input name="ref_public_id" required></label><label>Note<input name="note"></label><button>Submit deliverable</button></form><?php endif?>
<?php if($canManage&&$a['status']==='submitted'):?><form method="post"><?=csrf_field()?><input type="hidden" name="project_id" value="<?=h($projectPublic)?>"><input type="hidden" name="op" value="assignment_status"><input type="hidden" name="assignment_id" value="<?=h((string)$a['public_id'])?>"><button name="status" value="completed">Approve complete</button></form><?php endif?></article><?php endforeach?></section>

<section class="card"><h2>Deliverables</h2><?php if(!$deliverables):?><p>No task deliverables submitted yet.</p><?php endif?><?php foreach($deliverables as $d):?><div class="meta"><?=h((string)$d['submitted_at'])?> · <?=h((string)$d['display_name'])?> · <?=h((string)$d['ref_type'])?>: <?=h((string)$d['ref_public_id'])?><?php if($d['note']):?> · <?=h((string)$d['note'])?><?php endif?></div><?php endforeach?></section>

<section class="card"><h2>Project activity</h2><?php foreach($events as $e):?><div class="meta"><?=h((string)$e['created_at'])?> · <?=h(ucwords(str_replace('_',' ',(string)$e['event_type'])))?><?php if($e['actor_name']):?> · <?=h((string)$e['actor_name'])?><?php endif?></div><?php endforeach?></section>
</main></body></html>