<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';$u=require_user($pdo);header('Cache-Control: private, no-store');header('Vary: Cookie');
$error='';$success='';$ready=research_reviews_ready($pdo);
if($_SERVER['REQUEST_METHOD']==='POST'){
    require_csrf();$op=(string)($_POST['op']??'');
    try{
        if(!$ready)throw new RuntimeException('Run the Phase 21 database upgrade first.');
        if($op==='create'){$reviewers=array_values(array_filter(array_map('intval',(array)($_POST['reviewer_ids']??[]))));$r=research_review_create($pdo,$u,(string)($_POST['subject_type']??''),(string)($_POST['subject_id']??''),$reviewers,(string)($_POST['due_at']??''),(string)($_POST['instructions']??''));header('Location: /research-reviews.php?id='.rawurlencode((string)$r['public_id']).'&created=1');exit;}
        if($op==='respond'){research_review_respond($pdo,$u,(string)($_POST['review_id']??''),(string)($_POST['decision']??''),(string)($_POST['comment']??''));$success='Review response recorded.';}
        if($op==='comment'){research_review_comment($pdo,$u,(string)($_POST['review_id']??''),(string)($_POST['body']??''));$success='Comment added.';}
        if($op==='complete'){research_review_complete($pdo,$u,(string)($_POST['review_id']??''));$success='Review completed and frozen.';}
        if($op==='cancel'){research_review_cancel($pdo,$u,(string)($_POST['review_id']??''));$success='Review cancelled.';}
        if($op==='restart'){$r=research_review_restart($pdo,$u,(string)($_POST['review_id']??''),(string)($_POST['due_at']??''));header('Location: /research-reviews.php?id='.rawurlencode((string)$r['public_id']).'&restarted=1');exit;}
        if($op==='thread_create'){research_publication_thread_create($pdo,$u,(string)($_POST['workflow_id']??''),['title'=>(string)($_POST['title']??''),'body'=>(string)($_POST['body']??''),'anchor_type'=>(string)($_POST['anchor_type']??'general'),'anchor_public_id'=>(string)($_POST['anchor_public_id']??''),'locator'=>['label'=>(string)($_POST['locator_label']??'')]]);$success='Review thread added.';}
        if($op==='thread_reply'){research_publication_thread_message($pdo,$u,(string)($_POST['thread_id']??''),(string)($_POST['body']??''));$success='Thread reply added.';}
        if($op==='thread_resolve'||$op==='thread_reopen'){research_publication_thread_resolve($pdo,$u,(string)($_POST['thread_id']??''),$op==='thread_resolve');$success=$op==='thread_resolve'?'Thread resolved.':'Thread reopened.';}
    }catch(Throwable $e){$error=$e->getMessage();}
}
$reviewId=trim((string)($_GET['id']??''));$newType=trim((string)($_GET['type']??''));$newId=trim((string)($_GET['subject']??$_GET['object']??''));
$review=$ready&&$reviewId!==''?research_review_access($pdo,$u,$reviewId):null;
if($review){$aggregate=research_review_aggregate($pdo,$review);$comments=research_review_comments($pdo,$review,250);$canManage=research_review_can_manage($u,$review);$assigned=research_review_is_assigned($pdo,$u,$review);$publicationWorkflow=research_publications_ready($pdo)?research_publication_workflow_for_review($pdo,$u,(string)$review['public_id']):null;}
$subject=$ready&&$newType!==''&&$newId!==''?research_review_subject($pdo,$u,$newType,$newId):null;$eligible=$subject?research_review_eligible_reviewers($pdo,$u,(string)$subject['project_public_id']):[];
$all=$ready&&!$review&&!$subject?research_review_list($pdo,$u,'all',200):[];$scope=(string)($_GET['scope']??'assigned');
if($all){$all=array_values(array_filter($all,function($r)use($scope,$u){$a=$r['aggregate'];if($scope==='assigned')return !empty($r['assigned_to_viewer'])&&$r['status']==='open';if($scope==='requested')return (int)$r['requested_by_user_id']===(int)$u['id']&&$r['status']==='open';if($scope==='changes')return $r['status']==='open'&&in_array($a['consensus'],['changes_requested','unresolved_objection'],true);if($scope==='awaiting')return $r['status']==='open'&&$a['counts']['pending']>0;if($scope==='completed')return $r['status']==='completed';return true;}));}
$labels=research_review_decisions();
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Review Center · Annotated</title><meta name="robots" content="noindex,nofollow"><link rel="stylesheet" href="/assets/css/app.css?v=59.0"></head><body>
<header class="topbar"><a class="brand" href="/home.php">Annotated</a><nav><a href="/home.php">Home</a><a href="/research.php">Research</a><a href="/research-outcomes.php">Decision Memory</a><a href="/settings.php">Settings</a></nav></header>
<main class="reviewCenterLayout"><section>
<div class="pageTitle"><span class="eyebrow">COLLABORATIVE RESEARCH REVIEW</span><h1>Review Center</h1><p>Structured human review for Research documents, Claims, Findings, immutable Report versions, and bounded Agent proposals. Publication reviews can add anchored evidence threads; the Agent may summarize but never casts a vote or approves publication.</p></div>
<?php if(isset($_GET['created'])):?><div class="success">Review requested.</div><?php endif?><?php if(isset($_GET['restarted'])):?><div class="success">Updated review started from the current Research state.</div><?php endif?><?php if($success):?><div class="success"><?=h($success)?></div><?php endif?><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?>
<?php if(!$ready):?><div class="card empty"><h2>Collaborative Review needs migration 028.</h2><?php if(($u['role']??'')==='admin'):?><a class="button" href="/upgrade.php">Run database upgrade</a><?php endif?></div>
<?php elseif($subject):?>
<div class="card reviewRequestCard"><span class="badge"><?=h(ucwords(str_replace('_',' ',$subject['type'])))?></span><h2>Request review</h2><h3><?=h((string)$subject['title'])?></h3><p class="meta"><?=h((string)$subject['project_title'])?> · <?=h((string)$subject['version_label'])?></p><p><?=h(mb_substr((string)$subject['summary'],0,800))?></p>
<form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="op" value="create"><input type="hidden" name="subject_type" value="<?=h((string)$subject['type'])?>"><input type="hidden" name="subject_id" value="<?=h((string)$subject['public_id'])?>">
<fieldset><legend>Reviewers</legend><?php $count=0;foreach($eligible as $person):if((int)$person['id']===(int)$u['id'])continue;$count++;?><label class="reviewerChoice"><input type="checkbox" name="reviewer_ids[]" value="<?=h((string)$person['id'])?>"><span><?=h((string)($person['display_name']?:$person['username']))?></span></label><?php endforeach?><?php if($count===0):?><p class="meta">No other active project collaborators are currently available to review this object.</p><?php endif?></fieldset>
<label>Deadline <input type="datetime-local" name="due_at"></label><label>Review instructions<textarea name="instructions" rows="5" maxlength="8000" placeholder="What should reviewers pay special attention to?"></textarea></label><div class="inlineActions"><button <?=$count===0?'disabled':''?>>Request review</button><a class="button secondary" href="<?=h((string)$subject['url'])?>">Back to Research object</a></div></form></div>
<?php elseif($review):?>
<?php $consensus=(string)$aggregate['consensus'];$completion=$review['completion_json']?json_decode((string)$review['completion_json'],true):null;?>
<div class="card reviewDetail <?=$review['is_stale']?'reviewStale':''?>">
<div class="reviewHeader"><div><div class="reviewBadges"><span class="badge"><?=h(ucwords(str_replace('_',' ',$review['subject_type'])))?></span><span class="badge"><?=h(ucwords(str_replace('_',' ',$review['status'])))?></span><span class="badge"><?=h(ucwords(str_replace('_',' ',$consensus)))?></span></div><h2><?=h((string)$review['title'])?></h2><p class="meta"><?=h((string)$review['project_title'])?> · requested by <?=h((string)($review['requester_name']?:$review['requester_username']))?> · <?=h((string)$review['subject_version_label'])?></p></div><div class="inlineActions"><a class="button secondary" href="<?=h((string)($review['subject']['url']??'/research.php'))?>">Open subject</a><a class="button secondary" href="/home.php?review_agent=<?=h((string)$review['public_id'])?>">Ask Agent</a></div></div>
<?php if($review['is_stale']):?><div class="error"><strong>Review based on earlier Research.</strong> <?=h((string)$review['stale_reason'])?></div><?php endif?>
<?php if(!empty($review['instructions'])):?><div class="reviewInstructions"><strong>Review instructions</strong><p><?=nl2br(h((string)$review['instructions']))?></p></div><?php endif?>
<div class="reviewMetrics"><span><strong><?=h((string)$aggregate['assigned'])?></strong> assigned</span><span><strong><?=h((string)$aggregate['counts']['approve'])?></strong> approve</span><span><strong><?=h((string)$aggregate['counts']['request_changes'])?></strong> changes</span><span><strong><?=h((string)$aggregate['counts']['disagree'])?></strong> disagree</span><span><strong><?=h((string)$aggregate['counts']['abstain'])?></strong> abstain</span><span><strong><?=h((string)$aggregate['counts']['pending'])?></strong> pending</span></div>
<?php if(!empty($review['due_at'])):?><p class="meta <?=strtotime((string)$review['due_at'])<time()&&$review['status']==='open'?'reviewOverdue':''?>">Deadline: <?=h((string)$review['due_at'])?></p><?php endif?>
</div>
<section class="reviewResponses"><div class="sectionHeadWeb"><div><span class="eyebrow">REVIEWERS</span><h2>Responses</h2></div></div>
<?php foreach($aggregate['assignments'] as $a):?><article class="card reviewResponse"><div><strong><?=h((string)($a['display_name']?:$a['username']))?></strong> <span class="badge"><?=h(ucwords((string)($a['reviewer_role']??'reviewer')))?> · <?=!empty($a['is_required'])?'required':'optional'?></span><?php if($a['decision']):?> <span class="badge"><?=h((string)($labels[$a['decision']]??$a['decision']))?></span><?php else:?><span class="badge">Pending</span><?php endif?></div><?php if(!empty($a['response_comment'])):?><p><?=nl2br(h((string)$a['response_comment']))?></p><?php endif?><p class="meta"><?=h((string)($a['response_created_at']?:'Awaiting response'))?></p></article><?php endforeach?>
</section>
<?php if($assigned&&$review['status']==='open'&&!$review['is_stale']):?><section class="card reviewRespond"><h3>Your response</h3><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="op" value="respond"><input type="hidden" name="review_id" value="<?=h((string)$review['public_id'])?>"><label>Decision<select name="decision"><?php foreach($labels as $key=>$label):?><option value="<?=h($key)?>"><?=h($label)?></option><?php endforeach?></select></label><label>Comment<textarea name="comment" rows="5" maxlength="12000" placeholder="Required for Request changes or Disagree."></textarea></label><button>Record response</button></form></section><?php endif?>
<?php if(!empty($publicationWorkflow)):?><section class="reviewPublicationThreads"><div class="sectionHeadWeb"><div><span class="eyebrow">PUBLICATION REVIEW</span><h2>Anchored evidence threads</h2></div><a href="/research-publications.php?workflow=<?=h((string)$publicationWorkflow['public_id'])?>">Open publishing workflow</a></div>
<?php if(!$publicationWorkflow['threads']):?><div class="card empty">No anchored publication review threads.</div><?php endif?>
<?php foreach($publicationWorkflow['threads'] as $thread):?><article class="card publicationThread is-<?=h((string)$thread['status'])?>"><header><div><span class="badge"><?=h(str_replace('_',' ',(string)$thread['anchor_type']))?></span><?php if($thread['anchor_public_id']):?><code><?=h((string)$thread['anchor_public_id'])?></code><?php endif?></div><strong><?=h(ucfirst((string)$thread['status']))?></strong></header><?php if($thread['title']):?><h3><?=h((string)$thread['title'])?></h3><?php endif?><?php foreach($thread['messages'] as $m):?><div class="publicationThreadMessage"><strong><?=h((string)($m['display_name']?:$m['username']))?></strong><p><?=nl2br(h((string)$m['body']))?></p><small><?=h((string)$m['created_at'])?></small></div><?php endforeach?><?php if($thread['status']==='open'):?><form method="post" class="inlineForm"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="op" value="thread_reply"><input type="hidden" name="thread_id" value="<?=h((string)$thread['public_id'])?>"><input name="body" maxlength="12000" required placeholder="Reply"><button>Reply</button></form><form method="post" class="inlineForm"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="op" value="thread_resolve"><input type="hidden" name="thread_id" value="<?=h((string)$thread['public_id'])?>"><button>Resolve</button></form><?php elseif($canManage):?><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="op" value="thread_reopen"><input type="hidden" name="thread_id" value="<?=h((string)$thread['public_id'])?>"><button>Reopen</button></form><?php endif?></article><?php endforeach?>
<?php if($review['status']==='open'):?><details class="card publicationNewThread"><summary>+ Add anchored thread</summary><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="op" value="thread_create"><input type="hidden" name="workflow_id" value="<?=h((string)$publicationWorkflow['public_id'])?>"><div class="publicationFormSplit"><label>Anchor<select name="anchor_type"><option value="general">General</option><option value="document_section">Document section</option><option value="claim">Claim</option><option value="source">Source</option><option value="citation">Citation</option><option value="task">Task</option><option value="program_delta">Program delta</option></select></label><label>Object ID<input name="anchor_public_id"></label></div><label>Location / section<input name="locator_label"></label><label>Title<input name="title" maxlength="255"></label><label>Comment<textarea name="body" rows="4" maxlength="12000" required></textarea></label><button>Add thread</button></form></details><?php endif?></section><?php endif?>
<section class="reviewDiscussion"><div class="sectionHeadWeb"><div><span class="eyebrow">DISCUSSION</span><h2>Review comments</h2></div></div><?php if(!$comments):?><div class="card empty">No review comments yet.</div><?php endif?><?php foreach($comments as $cm):?><article class="card"><strong><?=h((string)($cm['display_name']?:$cm['username']))?></strong><p><?=nl2br(h((string)$cm['body']))?></p><p class="meta"><?=h((string)$cm['created_at'])?></p></article><?php endforeach?><?php if($review['status']==='open'):?><form method="post" class="card stack"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="op" value="comment"><input type="hidden" name="review_id" value="<?=h((string)$review['public_id'])?>"><label>Add comment<textarea name="body" rows="4" maxlength="12000" required></textarea></label><button>Add comment</button></form><?php endif?></section>
<?php if($canManage):?><section class="card reviewGovernance"><h3>Governance</h3><?php if($review['status']==='open'&&!$review['is_stale']):?><p class="meta">Completing freezes the current reviewer decision set. Pending reviewers remain recorded as pending; Annotated does not turn a majority into an automatic verdict.</p><form method="post" class="inlineForm"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="op" value="complete"><input type="hidden" name="review_id" value="<?=h((string)$review['public_id'])?>"><button>Complete review</button></form><?php endif?><?php if($review['status']==='open'):?><form method="post" class="inlineForm" onsubmit="return confirm('Cancel this review? Existing responses remain in the audit history.')"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="op" value="cancel"><input type="hidden" name="review_id" value="<?=h((string)$review['public_id'])?>"><button class="button secondary">Cancel</button></form><?php endif?><?php if($review['is_stale']):?><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="op" value="restart"><input type="hidden" name="review_id" value="<?=h((string)$review['public_id'])?>"><label>New deadline <input type="datetime-local" name="due_at"></label><button>Start updated review</button></form><?php endif?><?php if($review['status']==='completed'&&$completion):?><details><summary>Frozen completion record</summary><pre><?=h(json_encode($completion,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE))?></pre></details><?php endif?></section><?php endif?>
<?php else:?>
<nav class="reviewTabs"><?php foreach(['assigned'=>'Assigned to Me','requested'=>'Requested by Me','changes'=>'Needs Changes','awaiting'=>'Awaiting Others','completed'=>'Completed'] as $key=>$label):?><a class="<?=$scope===$key?'active':''?>" href="/research-reviews.php?scope=<?=h($key)?>"><?=h($label)?></a><?php endforeach?></nav>
<?php if(!$all):?><div class="card empty"><h2>No reviews in this view.</h2><p>Open a Claim, Finding, or Research Report version to request a structured review.</p></div><?php endif?>
<div class="reviewList"><?php foreach($all as $r):$a=$r['aggregate'];?><article class="card reviewListCard <?=$r['is_stale']?'reviewStale':''?>"><div class="reviewHeader"><div><div class="reviewBadges"><span class="badge"><?=h(ucwords(str_replace('_',' ',$r['subject_type'])))?></span><span class="badge"><?=h(ucwords(str_replace('_',' ',$a['consensus'])))?></span><?php if($r['overdue']):?><span class="badge">Overdue</span><?php endif?><?php if($r['is_stale']):?><span class="badge">Earlier version</span><?php endif?></div><h2><a href="/research-reviews.php?id=<?=h((string)$r['public_id'])?>"><?=h((string)$r['title'])?></a></h2><p class="meta"><?=h((string)$r['project_title'])?> · <?=h((string)$r['subject_version_label'])?></p></div><span class="meta"><?=h((string)$r['created_at'])?></span></div><div class="reviewMetrics compact"><span><?=h((string)$a['counts']['approve'])?> approve</span><span><?=h((string)$a['counts']['request_changes'])?> changes</span><span><?=h((string)$a['counts']['disagree'])?> disagree</span><span><?=h((string)$a['counts']['pending'])?> pending</span></div></article><?php endforeach?></div>
<?php endif?>
</section>
<aside><div class="card stickyReviewRail"><h3>Review principles</h3><p class="meta">Reviews are pinned to exact Research state. Reviewer responses and comments are append-only. Completed reviews freeze the actual decision set. The Agent may summarize but cannot approve, disagree, abstain, request changes, or complete a review.</p><div class="inlineActions"><a href="/research.php">Research</a><a href="/research-automations.php">Automations</a><a href="/research-outcomes.php">Decision Memory</a></div></div></aside>
</main></body></html>