<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';
$u=require_user($pdo);header('Cache-Control: private, no-store');header('Vary: Cookie');
$ready=living_research_ready($pdo);$phase59=research_publications_ready($pdo);$error='';$success='';
$workflowId=trim((string)($_GET['workflow']??''));$documentId=trim((string)($_GET['doc']??''));

if($_SERVER['REQUEST_METHOD']==='POST'){
    require_csrf();$op=(string)($_POST['op']??'');
    try{
        if(!$phase59)throw new RuntimeException('Run the latest database upgrade first.');
        if($op==='create_workflow'){
            $topics=(string)($_POST['topics']??'');$workflow=research_publication_workflow_create($pdo,$u,(string)($_POST['document_id']??''),[
              'title'=>(string)($_POST['title']??''),'summary'=>(string)($_POST['summary']??''),'visibility'=>(string)($_POST['visibility']??'private'),
              'topics'=>$topics,'required_approvals'=>(int)($_POST['required_approvals']??1),'owner_approval'=>isset($_POST['owner_approval']),
              'review_complete'=>true,'no_unresolved_threads'=>true,'no_failed_task_gates'=>true,'no_high_contradictions'=>true,
              'fresh_evidence_days'=>(int)($_POST['fresh_evidence_days']??30),'notify_team'=>isset($_POST['notify_team']),'notify_subscribers'=>isset($_POST['notify_subscribers'])
            ]);header('Location: /research-publications.php?workflow='.rawurlencode((string)$workflow['public_id']).'&created=1');exit;
        }
        if($op==='update_workflow'){
            $workflowId=(string)($_POST['workflow_id']??'');research_publication_workflow_update($pdo,$u,$workflowId,[
              'title'=>(string)($_POST['title']??''),'summary'=>(string)($_POST['summary']??''),'visibility'=>(string)($_POST['visibility']??'private'),'topics'=>(string)($_POST['topics']??''),
              'required_approvals'=>(int)($_POST['required_approvals']??1),'owner_approval'=>isset($_POST['owner_approval']),'review_complete'=>true,
              'no_unresolved_threads'=>true,'no_failed_task_gates'=>true,'no_high_contradictions'=>true,'fresh_evidence_days'=>(int)($_POST['fresh_evidence_days']??30),
              'notify_team'=>isset($_POST['notify_team']),'notify_subscribers'=>isset($_POST['notify_subscribers'])
            ]);$success='Publication workflow updated.';
        }
        if($op==='request_review'){
            $workflowId=(string)($_POST['workflow_id']??'');$w=research_publication_workflow_access($pdo,$u,$workflowId);if(!$w)throw new RuntimeException('Publication workflow not found.');
            $eligible=research_review_eligible_reviewers($pdo,$u,(string)$w['project_public_id']);$reviewers=[];
            foreach($eligible as $person){$uid=(int)$person['id'];if($uid===(int)$u['id'])continue;$choice=(string)($_POST['assignment_'.$uid]??'none');if($choice==='none')continue;$parts=explode('_',$choice,2);$required=$parts[0]==='required';$role=($parts[1]??'reviewer')==='approver'?'approver':'reviewer';$reviewers[]=['user_id'=>$uid,'role'=>$role,'required'=>$required];}
            research_publication_request_review($pdo,$u,$workflowId,$reviewers,(string)($_POST['due_at']??''),(string)($_POST['instructions']??''));$success='Publication review requested.';
        }
        if($op==='restart_review'){$workflowId=(string)($_POST['workflow_id']??'');research_publication_restart_review($pdo,$u,$workflowId,(string)($_POST['due_at']??''));$success='New review round started from the current document revision.';}
        if($op==='owner_approve'){$workflowId=(string)($_POST['workflow_id']??'');research_publication_owner_approve($pdo,$u,$workflowId);$success='Owner approval recorded.';}
        if($op==='publish'){$workflowId=(string)($_POST['workflow_id']??'');$result=research_publication_publish($pdo,$u,$workflowId);$success='Published immutable report version '.(int)$result['version_number'].'.';}
        if($op==='archive'){$workflowId=(string)($_POST['workflow_id']??'');research_publication_archive($pdo,$u,$workflowId);$success='Publication workflow archived.';}
        if($op==='thread_create'){$workflowId=(string)($_POST['workflow_id']??'');research_publication_thread_create($pdo,$u,$workflowId,['title'=>(string)($_POST['title']??''),'body'=>(string)($_POST['body']??''),'anchor_type'=>(string)($_POST['anchor_type']??'general'),'anchor_public_id'=>(string)($_POST['anchor_public_id']??''),'locator'=>['label'=>(string)($_POST['locator_label']??'')]]);$success='Review thread added.';}
        if($op==='thread_reply'){$workflowId=(string)($_POST['workflow_id']??'');research_publication_thread_message($pdo,$u,(string)($_POST['thread_id']??''),(string)($_POST['body']??''));$success='Reply added.';}
        if($op==='thread_resolve'||$op==='thread_reopen'){$workflowId=(string)($_POST['workflow_id']??'');research_publication_thread_resolve($pdo,$u,(string)($_POST['thread_id']??''),$op==='thread_resolve');$success=$op==='thread_resolve'?'Thread resolved.':'Thread reopened.';}
    }catch(Throwable $e){$error=$e->getMessage();}
}

$workflow=$phase59&&$workflowId!==''?research_publication_workflow_detail($pdo,$u,$workflowId):null;
if($workflow)research_publication_evaluate($pdo,$u,(string)$workflow['public_id']);
$workflow=$workflow?research_publication_workflow_detail($pdo,$u,(string)$workflow['public_id']):null;
$eligible=$workflow?research_review_eligible_reviewers($pdo,$u,(string)$workflow['project_public_id']):[];
$summary=$phase59?research_publication_summary($pdo,$u):['counts'=>[],'overdue'=>0,'total'=>0];
$scope=(string)($_GET['scope']??'all');$workflows=$phase59&&!$workflow?research_publication_list($pdo,$u,$scope,250):[];
$subscriptions=$ready&&!$workflow?living_research_subscribed_reports($pdo,$u,100):[];$managed=$ready&&!$workflow?living_research_managed_reports($pdo,$u,100):[];
$document=$phase59&&$documentId!==''&&!$workflow?research_agent_workspace_object($pdo,$u,$documentId,false):null;
$docProject=$document?project_access($pdo,(int)$u['id'],(string)$document['project_public_id']):null;
$canCreate=$document&&$document['object_type']==='document'&&$docProject&&project_can_write($docProject);
$statuses=research_publication_statuses();$csrf=csrf_token();
?><!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Research Publishing · Annotated</title><meta name="robots" content="noindex,nofollow"><link rel="stylesheet" href="/assets/css/app.css?v=59.0"></head>
<body>
<header class="topbar"><a class="brand" href="/home.php">Annotated</a><nav><a href="/research.php">Research</a><a href="/research-reviews.php">Review Center</a><a href="/research-publications.php">Publishing</a></nav></header>
<main class="publicationCenter">
<section class="publicationCenterMain">
<div class="pageTitle"><span class="eyebrow">PHASE 59 · REVIEW, APPROVAL & PUBLISHING</span><h1>Research Publishing</h1><p>Move living Research documents through assigned review, evidence-aware discussion, explicit approval gates, immutable publication snapshots, and controlled distribution.</p></div>
<?php if(isset($_GET['created'])):?><div class="success">Publication workflow created.</div><?php endif?><?php if($success):?><div class="success"><?=h($success)?></div><?php endif?><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?>
<?php if(!$phase59):?><div class="card empty"><h2>Collaborative Publishing needs migration 057.</h2><?php if(($u['role']??'')==='admin'):?><a class="button" href="/upgrade.php">Run database upgrade</a><?php endif?></div>
<?php elseif($document&&$canCreate):?>
<section class="card publicationCreate"><span class="eyebrow">NEW PUBLICATION WORKFLOW</span><h2><?=h((string)$document['title'])?></h2><p class="meta"><?=h((string)$document['project_title'])?> · document revision <?=h((string)$document['revision_number'])?></p>
<form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="op" value="create_workflow"><input type="hidden" name="document_id" value="<?=h((string)$document['public_id'])?>">
<label>Publication title<input name="title" value="<?=h((string)$document['title'])?>" required></label><label>Executive summary<textarea name="summary" rows="5"><?=h((string)($document['document_summary']??''))?></textarea></label>
<div class="publicationFormSplit"><label>Visibility<select name="visibility"><option value="private">Private</option><?php if($docProject['team_id']):?><option value="team" selected>Team</option><?php endif?><option value="public">Public</option></select></label><label>Required approvals<input type="number" name="required_approvals" min="1" max="20" value="1"></label></div>
<label>Topics<input name="topics" maxlength="600" placeholder="competitors, market intelligence, weekly report"></label>
<div class="publicationFormSplit"><label>Evidence freshness (days)<input type="number" name="fresh_evidence_days" min="0" max="3650" value="30"></label><label class="publicationCheck"><input type="checkbox" name="owner_approval" checked> Require project owner approval</label></div>
<label class="publicationCheck"><input type="checkbox" name="notify_subscribers" checked> Notify existing report subscribers after publication</label><?php if($docProject['team_id']):?><label class="publicationCheck"><input type="checkbox" name="notify_team"> Notify active Team members after publication</label><?php endif?>
<button>Create review workflow</button></form></section>
<?php elseif($workflow):?>
<?php $canManage=research_publication_can_manage($u,$workflow);$isOwner=($u['role']??'')==='admin'||(int)$workflow['owner_user_id']===(int)$u['id'];?>
<section class="publicationWorkflow card is-<?=h((string)$workflow['status'])?>">
<header class="publicationWorkflowHeader"><div><div class="reviewBadges"><span class="badge"><?=h(strtoupper((string)$workflow['status']))?></span><span class="badge">DOC REV <?=h((string)$workflow['document_revision_number'])?></span><span class="badge"><?=h(strtoupper((string)$workflow['visibility']))?></span></div><h2><?=h((string)$workflow['title'])?></h2><p><?=h((string)($workflow['summary']??''))?></p><p class="meta"><?=h((string)$workflow['project_title'])?> · <?=h((string)$workflow['document_title'])?></p></div><div class="inlineActions"><a class="button secondary" href="/home.php<?=!empty($workflow['agent_public_id'])?'?agent='.rawurlencode((string)$workflow['conversation_public_id']??'').'&doc='.rawurlencode((string)$workflow['document_public_id']):'?doc='.rawurlencode((string)$workflow['document_public_id'])?>">Open document</a><?php if(!empty($workflow['review_public_id'])):?><a class="button secondary" href="/research-reviews.php?id=<?=h((string)$workflow['review_public_id'])?>">Open review</a><?php endif?></div></header>
</section>

<section class="publicationGateGrid">
<?php foreach($workflow['gates'] as $gate):?><article class="card publicationGate is-<?=h((string)$gate['status'])?>"><strong><?=h(ucwords(str_replace('_',' ',(string)$gate['gate_type'])))?></strong><span><?=h(strtoupper((string)$gate['status']))?></span><p><?=h((string)($gate['detail']??'Not evaluated'))?></p></article><?php endforeach?>
</section>

<?php if($workflow['status']==='changes_requested'&&$canManage):?><div class="card publicationActionCard"><h3>Start the next review round</h3><p>The document or review state changed. Restarting pins the current document revision and preserves every prior review round.</p><form method="post" class="inlineForm"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="op" value="restart_review"><input type="hidden" name="workflow_id" value="<?=h((string)$workflow['public_id'])?>"><label>New deadline <input type="datetime-local" name="due_at"></label><button>Restart review</button></form></div><?php endif?>

<?php if($workflow['status']==='draft'&&$canManage):?><section class="card publicationReviewRequest"><h3>Assign review</h3><p class="meta">The workflow creator cannot review their own request. Required/optional assignments remain visible in the existing Review Center.</p><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="op" value="request_review"><input type="hidden" name="workflow_id" value="<?=h((string)$workflow['public_id'])?>">
<div class="publicationReviewerGrid"><?php $reviewerCount=0;foreach($eligible as $person):if((int)$person['id']===(int)$u['id'])continue;$reviewerCount++;?><label><span><?=h((string)($person['display_name']?:$person['username']))?></span><select name="assignment_<?=h((string)$person['id'])?>"><option value="none">Not assigned</option><option value="required_reviewer">Required reviewer</option><option value="optional_reviewer">Optional reviewer</option><option value="required_approver">Required approver</option><option value="optional_approver">Optional approver</option></select></label><?php endforeach?></div>
<?php if(!$reviewerCount):?><p class="error">No other active project collaborator is available to review this document.</p><?php endif?><label>Deadline<input type="datetime-local" name="due_at"></label><label>Instructions<textarea name="instructions" rows="4" maxlength="8000"></textarea></label><button <?=$reviewerCount?'':'disabled'?>>Request review</button></form></section><?php endif?>

<?php if(!empty($workflow['review'])):?>
<section class="card publicationReviewState"><div class="sectionHeadWeb"><div><span class="eyebrow">CURRENT REVIEW · ROUND <?=h((string)$workflow['current_round'])?></span><h3><?=h((string)$workflow['review']['title'])?></h3></div><span class="badge"><?=h(str_replace('_',' ',(string)($workflow['review_aggregate']['consensus']??'')))?></span></div>
<div class="publicationReviewerGrid"><?php foreach($workflow['review_aggregate']['assignments'] as $a):?><div class="publicationReviewer"><strong><?=h((string)($a['display_name']?:$a['username']))?></strong><span><?=h(ucwords((string)($a['reviewer_role']??'reviewer')))?> · <?=!empty($a['is_required'])?'required':'optional'?></span><small><?=h((string)($a['decision']?:'pending'))?></small></div><?php endforeach?></div></section>
<?php endif?>

<section class="publicationThreads"><div class="sectionHeadWeb"><div><span class="eyebrow">EVIDENCE-AWARE DISCUSSION</span><h2>Review threads</h2></div><span class="badge"><?=h((string)count($workflow['threads']))?></span></div>
<?php if(!$workflow['threads']):?><div class="card empty">No anchored review threads yet.</div><?php endif?>
<?php foreach($workflow['threads'] as $thread):?><article class="card publicationThread is-<?=h((string)$thread['status'])?>"><header><div><span class="badge"><?=h(str_replace('_',' ',(string)$thread['anchor_type']))?></span><?php if($thread['anchor_public_id']):?><code><?=h((string)$thread['anchor_public_id'])?></code><?php endif?></div><strong><?=h(ucfirst((string)$thread['status']))?></strong></header><?php if($thread['title']):?><h3><?=h((string)$thread['title'])?></h3><?php endif?><?php foreach($thread['messages'] as $m):?><div class="publicationThreadMessage"><strong><?=h((string)($m['display_name']?:$m['username']))?></strong><p><?=nl2br(h((string)$m['body']))?></p><small><?=h((string)$m['created_at'])?></small></div><?php endforeach?>
<?php if($thread['status']==='open'):?><form method="post" class="inlineForm"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="op" value="thread_reply"><input type="hidden" name="workflow_id" value="<?=h((string)$workflow['public_id'])?>"><input type="hidden" name="thread_id" value="<?=h((string)$thread['public_id'])?>"><input name="body" required maxlength="12000" placeholder="Reply"><button>Reply</button></form><form method="post" class="inlineForm"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="op" value="thread_resolve"><input type="hidden" name="workflow_id" value="<?=h((string)$workflow['public_id'])?>"><input type="hidden" name="thread_id" value="<?=h((string)$thread['public_id'])?>"><button>Resolve thread</button></form><?php elseif($canManage):?><form method="post"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="op" value="thread_reopen"><input type="hidden" name="workflow_id" value="<?=h((string)$workflow['public_id'])?>"><input type="hidden" name="thread_id" value="<?=h((string)$thread['public_id'])?>"><button>Reopen thread</button></form><?php endif?></article><?php endforeach?>
<?php if(!empty($workflow['review'])&&$workflow['review']['status']==='open'):?><details class="card publicationNewThread"><summary>+ Add anchored thread</summary><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="op" value="thread_create"><input type="hidden" name="workflow_id" value="<?=h((string)$workflow['public_id'])?>"><div class="publicationFormSplit"><label>Anchor<select name="anchor_type"><option value="general">General</option><option value="document_section">Document section</option><option value="claim">Claim</option><option value="source">Source</option><option value="citation">Citation</option><option value="task">Task</option><option value="program_delta">Program delta</option></select></label><label>Object ID<input name="anchor_public_id" placeholder="Optional for general/document section"></label></div><label>Location / section<input name="locator_label" placeholder="e.g. Executive summary, paragraph 3"></label><label>Thread title<input name="title" maxlength="255"></label><label>Comment<textarea name="body" rows="4" required maxlength="12000"></textarea></label><button>Add review thread</button></form></details><?php endif?>
</section>

<?php if($isOwner&&!empty($workflow['review'])&&$workflow['status']!=='published'&&$workflow['status']!=='archived'):?><section class="card publicationActionCard"><h3>Owner approval</h3><p>Owner approval is separate from reviewer votes and cannot be supplied by the Agent.</p><?php if($workflow['owner_approved_at']):?><p class="success">Approved <?=h((string)$workflow['owner_approved_at'])?>.</p><?php else:?><form method="post"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="op" value="owner_approve"><input type="hidden" name="workflow_id" value="<?=h((string)$workflow['public_id'])?>"><button>Record owner approval</button></form><?php endif?></section><?php endif?>

<?php if($workflow['status']==='approved'&&$isOwner):?><section class="card publicationReady"><span class="eyebrow">READY TO PUBLISH</span><h2>All approval gates passed.</h2><p>Publishing freezes document revision <?=h((string)$workflow['document_revision_number'])?>, its approval record, and the current Research evidence snapshot into the existing immutable report-version history.</p><form method="post"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="op" value="publish"><input type="hidden" name="workflow_id" value="<?=h((string)$workflow['public_id'])?>"><button>Publish immutable version</button></form></section><?php endif?>

<?php if($workflow['status']==='published'):?><section class="card publicationPublished"><span class="eyebrow">PUBLISHED</span><h2>Immutable publication snapshot</h2><p>Published <?=h((string)$workflow['published_at'])?>. The living document can continue changing; this published version will not.</p><?php if($workflow['published_report_id']):?><a class="button" href="/research-report.php?id=<?=h((string)($workflow['published_report_id']))?>">Open published report</a><?php endif?><h3>Distribution history</h3><?php if(!$workflow['distribution_events']):?><p class="meta">No explicit distribution events.</p><?php endif?><?php foreach($workflow['distribution_events'] as $event):?><p class="meta"><?=h(strtoupper((string)$event['status']))?> · <?=h((string)$event['target_type'])?> · <?=h((string)($event['display_name']?:$event['team_name']?:'subscribers'))?><?=!empty($event['detail'])?' · '.h((string)$event['detail']):''?></p><?php endforeach?></section><?php endif?>

<?php if($canManage&&!in_array($workflow['status'],['published','archived'],true)):?><details class="card publicationWorkflowSettings"><summary>Workflow settings</summary><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="op" value="update_workflow"><input type="hidden" name="workflow_id" value="<?=h((string)$workflow['public_id'])?>"><label>Title<input name="title" value="<?=h((string)$workflow['title'])?>" required></label><label>Summary<textarea name="summary" rows="5"><?=h((string)($workflow['summary']??''))?></textarea></label><div class="publicationFormSplit"><label>Visibility<select name="visibility"><option value="private" <?=$workflow['visibility']==='private'?'selected':''?>>Private</option><?php if($workflow['team_id']):?><option value="team" <?=$workflow['visibility']==='team'?'selected':''?>>Team</option><?php endif?><option value="public" <?=$workflow['visibility']==='public'?'selected':''?>>Public</option></select></label><label>Required approvals<input type="number" name="required_approvals" min="1" max="20" value="<?=h((string)$workflow['policy']['required_approvals'])?>"></label></div><label>Topics<input name="topics" value="<?=h(implode(', ',(array)$workflow['topics']))?>"></label><div class="publicationFormSplit"><label>Evidence freshness (days)<input type="number" name="fresh_evidence_days" min="0" max="3650" value="<?=h((string)$workflow['policy']['fresh_evidence_days'])?>"></label><label class="publicationCheck"><input type="checkbox" name="owner_approval" <?=!empty($workflow['policy']['owner_approval'])?'checked':''?>> Require owner approval</label></div><label class="publicationCheck"><input type="checkbox" name="notify_subscribers" checked> Notify report subscribers</label><?php if($workflow['team_id']):?><label class="publicationCheck"><input type="checkbox" name="notify_team" <?=count(array_filter($workflow['distribution_targets'],fn($t)=>$t['target_type']==='team'))?'checked':''?>> Notify Team members</label><?php endif?><button>Save settings</button></form><form method="post" class="publicationArchiveForm"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="op" value="archive"><input type="hidden" name="workflow_id" value="<?=h((string)$workflow['public_id'])?>"><button>Archive workflow</button></form></details><?php endif?>

<?php else:?>
<section class="publicationStats"><?php foreach(['draft','in_review','changes_requested','approved','published','archived'] as $st):?><a href="/research-publications.php?scope=<?=h($st)?>"><strong><?=h((string)($summary['counts'][$st]??0))?></strong><span><?=h($statuses[$st])?></span></a><?php endforeach?></section>
<nav class="researchLibraryTabs publicationStatusTabs"><a class="<?=$scope==='all'?'active':''?>" href="/research-publications.php">All</a><?php foreach($statuses as $st=>$label):?><a class="<?=$scope===$st?'active':''?>" href="/research-publications.php?scope=<?=h($st)?>"><?=h($label)?></a><?php endforeach?></nav>
<section class="publicationWorkflowList"><div class="sectionHeadWeb"><div><span class="eyebrow">WORKFLOWS</span><h2>Review & publication pipeline</h2></div><span class="badge"><?=h((string)count($workflows))?></span></div><?php if(!$workflows):?><div class="card empty">No publication workflows in this view. Open a Research document and choose Review &amp; publish.</div><?php endif?><?php foreach($workflows as $w):?><article class="card publicationWorkflowCard is-<?=h((string)$w['status'])?>"><a href="/research-publications.php?workflow=<?=h((string)$w['public_id'])?>"><div><span><?=h(strtoupper((string)$w['status']))?> · DOC REV <?=h((string)$w['document_revision_number'])?></span><h3><?=h((string)$w['title'])?></h3><p><?=h((string)$w['project_title'])?> · <?=h((string)$w['document_title'])?></p></div><strong>Open →</strong></a></article><?php endforeach?></section>

<?php if($ready):?><section class="livingHubSection"><div class="sectionHeadWeb"><div><span class="eyebrow">PUBLISHED RESEARCH</span><h2>Reports you manage</h2></div><span class="badge"><?=h((string)count($managed))?></span></div><div class="livingReportGrid"><?php foreach($managed as $r):?><article class="card livingHubCard"><div class="livingReportBadges"><span class="badge">v<?=h((string)$r['version_number'])?></span><span class="badge"><?=h(strtoupper((string)$r['visibility']))?></span></div><h3><a href="/research-report.php?id=<?=h((string)$r['public_id'])?>"><?=h((string)$r['title'])?></a></h3><p class="meta"><?=h((string)$r['subscriber_count'])?> follower<?=((int)$r['subscriber_count']===1?'':'s')?> · published <?=h((string)$r['published_at'])?></p></article><?php endforeach?></div></section>
<section class="livingHubSection"><div class="sectionHeadWeb"><div><span class="eyebrow">FOLLOWING</span><h2>Reports you follow</h2></div><span class="badge"><?=h((string)count($subscriptions))?></span></div><div class="livingReportGrid"><?php foreach($subscriptions as $r):?><article class="card livingHubCard"><h3><a href="/research-report.php?id=<?=h((string)$r['public_id'])?>"><?=h((string)$r['title'])?></a></h3><p class="meta">v<?=h((string)$r['version_number'])?> · <?=h((string)$r['published_at'])?></p></article><?php endforeach?></div></section><?php endif?>
<?php endif?>
<?php endif?>
</section>
<aside class="publicationCenterRail"><?php if($workflow):?><div class="card"><h3>Review rounds</h3><?php if(!$workflow['rounds']):?><p class="meta">No review rounds yet.</p><?php endif?><?php foreach($workflow['rounds'] as $round):?><p><a href="/research-reviews.php?id=<?=h((string)$round['review_public_id'])?>">Round <?=h((string)$round['round_number'])?></a><br><span class="meta">Document rev <?=h((string)$round['document_revision_number'])?> · <?=h((string)$round['created_at'])?></span></p><?php endforeach?></div><?php else:?><div class="card"><h3>Publishing rules</h3><p class="meta">Reviewer votes never publish content by themselves. The workflow must satisfy every configured gate, remain pinned to the reviewed document revision, and an authorized publisher must explicitly publish it.</p><p><a href="/research-reviews.php">Open Review Center</a></p></div><?php endif?></aside>
</main></body></html>