<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';$u=require_user($pdo);$id=trim((string)($_GET['pack']??''));$pack=research_evidence_pack_access($pdo,$u,$id);if(!$pack){http_response_code(404);exit('Evidence Pack not found.');}$compare=research_evidence_pack_compare($pack);$m=$pack['manifest'];
function ep_count(mixed $v): int{return is_array($v)?count($v):($v===null?0:1);}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Evidence Pack · Annotated</title><meta name="robots" content="noindex,nofollow"><link rel="stylesheet" href="/assets/css/app.css"></head><body>
<header class="topbar"><a class="brand" href="/home.php">Annotated</a><nav><a href="/research-evidence-packs.php?id=<?=h((string)$pack['project_public_id'])?>">Evidence Packs</a><a href="/research-project.php?id=<?=h((string)$pack['project_public_id'])?>">Project</a><a href="/research.php">Research</a></nav></header>
<main class="evidencePackLayout"><section><div class="pageTitle"><span class="eyebrow">IMMUTABLE EVIDENCE PACK · REPLAY</span><h1><?=h((string)$pack['project_title'])?></h1><p><?=h(strtoupper(str_replace('_',' ',(string)$pack['scope_type'])))?> <?=h((string)$pack['scope_public_id'])?> · created <?=h((string)$pack['created_at'])?> by <?=h((string)($pack['creator_name']?:$pack['creator_username']))?></p></div>
<div class="<?=$pack['stored_hash_valid']?'success':'error'?>"><strong>Manifest SHA-256 <?=$pack['stored_hash_valid']?'verified':'does not verify'?>.</strong><br><code><?=h((string)$pack['manifest_hash'])?></code></div>
<div class="<?=$compare['matches']?'success':'card evidencePackDrift'?>"><strong><?=$compare['matches']?'This pack matches current Research.':'Current Research differs from this frozen pack.'?></strong><?php if(!$compare['matches']):?><p>Changed sections: <?=h($compare['changed_sections']?implode(', ',$compare['changed_sections']):'none')?>. Added: <?=h($compare['added_sections']?implode(', ',$compare['added_sections']):'none')?>. Removed: <?=h($compare['removed_sections']?implode(', ',$compare['removed_sections']):'none')?>.</p><?php endif?></div>
<section class="evidencePackReplay"><h2>Frozen state</h2><div class="evidencePackSummary"><?php foreach($m as $k=>$v):?><?php if(in_array($k,['schema','scope','project'],true))continue;?><div class="card"><strong><?=h((string)ep_count($v))?></strong><span><?=h(ucwords(str_replace('_',' ',$k)))?></span></div><?php endforeach?></div>
<?php if(!empty($m['claims'])):?><h2>Claims at pack creation</h2><?php foreach($m['claims'] as $c):?><article class="card"><div class="meta">CLAIM <?=h((string)$c['id'])?> · <?=h(strtoupper((string)$c['status']))?></div><h3><?=h((string)$c['statement'])?></h3><p class="meta"><?=h((string)count($c['evidence']??[]))?> evidence links frozen</p></article><?php endforeach?><?php endif?>
<?php if(!empty($m['finding'])):?><article class="card"><div class="meta">FINDING <?=h((string)$m['finding']['id'])?></div><h2><?=h((string)$m['finding']['title'])?></h2><p><?=nl2br(h((string)$m['finding']['summary']))?></p></article><?php endif?>
<?php if(!empty($m['report_version'])):?><article class="card"><div class="meta">REPORT VERSION <?=h((string)$m['report_version']['version_number'])?></div><h2><?=h((string)$m['report_version']['title'])?></h2><p class="meta">Snapshot hash <?=$m['snapshot_hash_valid']?'verified':'mismatch'?> · <?=h((string)$m['report_version']['stored_snapshot_hash'])?></p></article><?php endif?>
<details class="card"><summary>Canonical manifest</summary><pre class="evidencePackJson"><?=h(json_encode($m,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?:'')?></pre></details>
</section></section><aside class="stickyEvidencePackRail"><div class="card"><h3>Replay boundary</h3><p class="meta">This view reconstructs what Annotated froze at pack creation. It does not silently replace frozen values with current Research.</p></div><div class="card"><h3>Export</h3><a class="button secondary" href="/research-evidence-pack-export.php?pack=<?=h((string)$pack['public_id'])?>">Download JSON manifest</a></div></aside></main></body></html>
