<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';require_once __DIR__.'/app/research-reports.php';
$u=require_user($pdo);$id=(string)($_GET['id']??$_POST['id']??'');$project=project_access($pdo,(int)$u['id'],$id);if(!$project){http_response_code(404);exit('Research project not found.');}$canPublish=research_report_can_publish($project);$success='';$error='';
$q=$pdo->prepare('SELECT * FROM research_reports WHERE project_id=? LIMIT 1');$q->execute([$project['id']]);$report=$q->fetch()?:null;
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();$op=(string)($_POST['op']??'');try{
    if(!$canPublish)throw new RuntimeException('Only a project owner or administrator can publish or unpublish reports.');
    if($op==='publish'){$title=trim((string)($_POST['title']??''));$summary=trim((string)($_POST['summary']??''));$visibility=(string)($_POST['visibility']??'private');$topics=(string)($_POST['topics']??'');if($title==='')throw new RuntimeException('Report title is required.');$result=research_report_publish($pdo,$project,$u,$visibility,$title,$summary?:null,$topics);$success='Published report version '.$result['version_number'].'.'.($result['subscriber_notifications']>0?' Sent '.(int)$result['subscriber_notifications'].' subscriber update notification(s).':'');$q=$pdo->prepare('SELECT * FROM research_reports WHERE project_id=? LIMIT 1');$q->execute([$project['id']]);$report=$q->fetch()?:null;}
    elseif($op==='unpublish'){if(!$report)throw new RuntimeException('No report exists yet.');$pdo->prepare("UPDATE research_reports SET status='unpublished',updated_at=NOW() WHERE id=?")->execute([$report['id']]);$report['status']='unpublished';$success='Report unpublished. Existing immutable versions are retained but no longer viewable through the report URL.';}
    else throw new RuntimeException('Unknown publishing action.');
}catch(Throwable $e){$error=$e->getMessage();}}
$versions=[];$topics=[];$subscriberCount=0;$staleness=null;$currentAccess=null;$workingCitations=research_network_ready($pdo)?research_network_project_references($pdo,$u,$project['public_id']):[];
if($report){$q=$pdo->prepare('SELECT rv.public_id,rv.version_number,rv.visibility,rv.title,rv.summary,rv.snapshot_hash,rv.created_at,u.display_name FROM research_report_versions rv JOIN users u ON u.id=rv.published_by_user_id WHERE rv.report_id=? ORDER BY rv.version_number DESC');$q->execute([$report['id']]);$versions=$q->fetchAll();if(living_research_ready($pdo)){$topics=living_research_topics($pdo,(int)$report['id']);$subscriberCount=living_research_subscriber_count($pdo,(int)$report['id']);}
    if($report['status']==='published'){$currentAccess=research_report_access($pdo,(string)$report['public_id'],$u);if($currentAccess&&living_research_ready($pdo))$staleness=living_research_staleness($pdo,$u,$currentAccess);}
}
$titleDefault=$report['title']??$project['title'];$summaryDefault=$report['summary']??$project['description'];$visibilityDefault=$report['visibility']??($project['team_id']?'team':'private');$topicDefault=implode(', ',array_column($topics,'topic_label'));$currentVersion=$versions?(int)$versions[0]['version_number']:0;
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Publish Research · <?=h($project['title'])?> · Annotated</title><link rel="stylesheet" href="/assets/css/app.css"></head><body>
<header class="topbar"><a class="brand" href="/home.php">Annotated</a><nav><a href="/research-project.php?id=<?=h($project['public_id'])?>">Project</a><a href="/research-publications.php">Living Research</a><a href="/research-knowledge.php?id=<?=h($project['public_id'])?>">Knowledge</a><a href="/research.php">Research</a></nav></header>
<main class="layout"><section><div class="pageTitle"><span class="eyebrow">RESEARCH PUBLISHING · <?=h(strtoupper($project['access_role']))?></span><h1><?=h($project['title'])?></h1><p>Create immutable report versions from the current Research project. Internal notes, tasks and AI run data are never included in publication snapshots.</p></div>
<?php if($success):?><div class="success"><?=h($success)?></div><?php endif?><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?>
<?php if($report):?><div class="card publicationCurrent"><div class="meta">CURRENT REPORT · <?=h(strtoupper($report['status']))?> · <?=h(strtoupper($report['visibility']))?></div><h2><?=h($report['title'])?></h2><?php if($report['summary']):?><p><?=nl2br(h($report['summary']))?></p><?php endif?>
<div class="publicationStats"><span><strong><?=h((string)$currentVersion)?></strong> current version</span><span><strong><?=h((string)$subscriberCount)?></strong> subscribers</span><span><strong><?=h((string)count($topics))?></strong> topics</span></div>
<?php if($topics):?><div class="publicationTopics"><?php foreach($topics as $topic):?><a class="badge" href="/research-topic.php?topic=<?=h((string)$topic['topic_slug'])?>"><?=h((string)$topic['topic_label'])?></a><?php endforeach?></div><?php endif?>
<?php if($staleness):?><div class="error publicationStale"><strong>Published report may need an update.</strong> <?=h((string)$staleness['reason'])?> Source: <?=h((string)$staleness['source_title'])?> changed <?=h((string)$staleness['created_at'])?>. <a href="/research-impact.php?event=<?=h((string)$staleness['event_id'])?>&project=<?=h($project['public_id'])?>">Review downstream impact</a>. The current published version remains immutable until you deliberately publish a new version.</div><?php endif?>
<?php if($report['status']==='published'):?><p><a href="/research-report.php?id=<?=h($report['public_id'])?>" target="_blank">Open report ↗</a> · <a href="/research-report-export.php?id=<?=h($report['public_id'])?>&format=json">JSON export</a> · <a href="/research-report-export.php?id=<?=h($report['public_id'])?>&format=html">HTML export</a><?php if($currentVersion>1):?> · <a href="/research-report-diff.php?id=<?=h($report['public_id'])?>&from=<?=h((string)($currentVersion-1))?>&to=<?=h((string)$currentVersion)?>">Latest changes</a><?php endif?></p><?php endif?></div><?php endif?>
<h2>Version history</h2><?php if(!$versions):?><div class="card empty">No report versions yet.</div><?php endif?>
<?php foreach($versions as $index=>$v):$vn=(int)$v['version_number'];?><article class="card"><div class="meta">VERSION <?=h((string)$vn)?> · <?=h(strtoupper($v['visibility']))?> · <?=h($v['created_at'])?> · <?=h($v['display_name'])?></div><h3><?=h($v['title'])?></h3><p class="meta">Snapshot SHA-256: <?=h($v['snapshot_hash'])?></p><?php if($report&&$report['status']==='published'):?><p><a href="/research-report.php?id=<?=h($report['public_id'])?>&v=<?=h((string)$vn)?>">View version</a> · <a href="/research-report-export.php?id=<?=h($report['public_id'])?>&v=<?=h((string)$vn)?>&format=json">JSON</a> · <a href="/research-report-export.php?id=<?=h($report['public_id'])?>&v=<?=h((string)$vn)?>&format=html">HTML</a><?php if($vn>1):?> · <a href="/research-report-diff.php?id=<?=h($report['public_id'])?>&from=<?=h((string)($vn-1))?>&to=<?=h((string)$vn)?>">Compare with v<?=h((string)($vn-1))?></a><?php endif?><?php if($vn<$currentVersion):?> · <a href="/research-report-diff.php?id=<?=h($report['public_id'])?>&from=<?=h((string)$vn)?>&to=<?=h((string)$currentVersion)?>">Compare with current</a><?php endif?></p><?php endif?></article><?php endforeach?>
</section>
<aside><?php if($canPublish):?><div class="card"><h3><?=$report?'Publish new version':'Publish report'?></h3><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="id" value="<?=h($project['public_id'])?>"><input type="hidden" name="op" value="publish"><label>Report title<input name="title" value="<?=h($titleDefault)?>" required></label><label>Executive summary<textarea name="summary" rows="6"><?=h($summaryDefault)?></textarea></label><label>Topics<input name="topics" value="<?=h($topicDefault)?>" maxlength="600" placeholder="e.g. broadband, Phoenix, municipal networks"></label><small>Up to 8 publisher-assigned topics. Public reports appear in public topic collections.</small><label>Visibility<select name="visibility"><option value="private" <?=$visibilityDefault==='private'?'selected':''?>>Private</option><?php if($project['team_id']):?><option value="team" <?=$visibilityDefault==='team'?'selected':''?>>Team</option><?php endif?><option value="public" <?=$visibilityDefault==='public'?'selected':''?>>Public</option></select></label><button>Publish immutable version</button></form><p class="meta">Publishing creates a new immutable snapshot. Existing subscribers are notified only after the version commits successfully.</p><p class="meta">Public snapshots downgrade non-public Annotation references to their pinned Source Version instead of exposing private commentary.</p></div>
<?php if($report&&$report['status']==='published'):?><div class="card"><h3>Unpublish</h3><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="id" value="<?=h($project['public_id'])?>"><input type="hidden" name="op" value="unpublish"><button>Unpublish report</button></form><p class="meta">Versions remain immutable for audit/history but the report URL and exports become inaccessible.</p></div><?php endif?>
<?php else:?><div class="card"><h3>Publishing authority</h3><p class="meta">Only the project owner or a Team administrator can publish or unpublish Research reports.</p></div><?php endif?>
<div class="card"><h3>Report citations</h3><p class="meta"><?=h((string)count($workingCitations))?> working report citation<?=count($workingCitations)===1?'':'s'?>. The published snapshot includes only citations compatible with the selected report visibility.</p><a href="/research-citations.php?id=<?=h($project['public_id'])?>">Manage citations</a></div><div class="card"><h3>Publishing boundary</h3><p class="meta">Published snapshots include Sources, version-pinned evidence, Claims, final Findings, Claim Graph, confirmed Entities, Entity Graph and a safe Research timeline. Notes, tasks, AI prompts/runs and unreviewed AI entities stay internal.</p></div></aside></main></body></html>
