<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';$u=require_user($pdo);$id=(string)($_GET['id']??'');$receipt=provenance_receipt_access($pdo,$u,$id);if(!$receipt){http_response_code(404);exit('Audit receipt not found.');}$m=$receipt['manifest'];$edges=provenance_manifest_edges($m);
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Audit Receipt · Annotated</title><meta name="robots" content="noindex,nofollow"><link rel="stylesheet" href="/assets/css/app.css"></head><body>
<header class="topbar"><a class="brand" href="/home.php">Annotated</a><nav><a href="/research-provenance.php?id=<?=h((string)$receipt['project_public_id'])?>">Current provenance</a><a href="/research-project.php?id=<?=h((string)$receipt['project_public_id'])?>">Project</a></nav></header>
<main class="auditReceiptLayout"><section><div class="pageTitle"><span class="eyebrow">IMMUTABLE AUDIT RECEIPT</span><h1><?=h((string)$receipt['project_title'])?></h1><p>Created <?=h((string)$receipt['created_at'])?>. This receipt stores the exact permission-scoped provenance manifest captured at that time.</p></div>
<div class="card provenanceIntegrity <?=$receipt['stored_hash_valid']?'provenanceValid':'provenanceInvalid'?>"><span class="eyebrow">RECEIPT SHA-256</span><h2><?=h((string)$receipt['manifest_hash'])?></h2><p><strong><?=$receipt['stored_hash_valid']?'Stored receipt hash verifies.':'RECEIPT HASH MISMATCH.'?></strong></p><p><?=$receipt['current_matches_receipt']?'The current project provenance still matches this receipt.':'The project provenance has changed since this receipt was created.'?></p><?php if(!$receipt['current_matches_receipt']):?><p class="meta">Current manifest SHA-256: <?=h((string)$receipt['current_manifest_hash'])?></p><?php endif?></div>
<div class="provenanceSummary"><div class="card"><strong><?=h((string)count($m['source_versions']??[]))?></strong><span>Source Versions</span></div><div class="card"><strong><?=h((string)count($m['claims']??[]))?></strong><span>Claims</span></div><div class="card"><strong><?=h((string)count($m['findings']??[]))?></strong><span>Findings</span></div><div class="card"><strong><?=h((string)count($m['report_versions']??[]))?></strong><span>Report Versions</span></div><div class="card"><strong><?=h((string)count($m['reviews']??[]))?></strong><span>Reviews</span></div><div class="card"><strong><?=h((string)count($edges))?></strong><span>Lineage edges</span></div></div>
<h2>Frozen lineage</h2><div class="provenanceEdgeList"><?php foreach(array_slice($edges,0,250) as $edge):?><div class="card provenanceEdge"><code><?=h((string)$edge['from'])?></code><strong><?=h(str_replace('_',' ',(string)$edge['type']))?></strong><code><?=h((string)$edge['to'])?></code></div><?php endforeach?></div>
</section><aside><div class="card stickyProvenanceRail"><h3>Export receipt</h3><p class="meta">The JSON export contains the stored manifest, receipt metadata, and recorded receipt hash.</p><a class="button" href="/research-audit-export.php?id=<?=h((string)$receipt['public_id'])?>">Download JSON</a></div><div class="card"><h3>Receipt boundary</h3><p class="meta">A valid receipt proves the stored manifest has not changed since capture. It does not claim the underlying Research conclusion is correct.</p></div></aside></main></body></html>