<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';$u=require_user($pdo);header('Cache-Control: private, no-store');header('Vary: Cookie');
$error='';$success='';$ready=change_impact_ready($pdo);
$eventId=(int)($_GET['event']??$_POST['event_id']??0);$projectFilter=trim((string)($_GET['project']??$_POST['project_id']??''));
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();try{
    if(!$ready)throw new RuntimeException('Run the Phase 22 database upgrade first.');
    if(($_POST['op']??'')==='decide'){change_impact_set_decision($pdo,$u,$eventId,(string)($_POST['object_type']??''),(string)($_POST['object_public_id']??''),(string)($_POST['decision']??''),(string)($_POST['note']??''),(string)($_POST['snoozed_until']??''));$success='Impact review decision saved.';}
}catch(Throwable $e){$error=$e->getMessage();}}
$view=$ready&&$eventId>0?change_impact_event_view($pdo,$u,$eventId):null;if($eventId>0&&!$view&&$ready){http_response_code(404);$error='Source change impact not found or unavailable.';}
if($view&&$projectFilter!=='')$view['projects']=array_values(array_filter($view['projects'],fn($p)=>(string)$p['project']['public_id']===$projectFilter));
$portfolio=[];if($ready&&$eventId===0){$q=$pdo->prepare("SELECT DISTINCT rp.public_id,rp.title FROM research_projects rp LEFT JOIN team_members tm ON tm.team_id=rp.team_id AND tm.user_id=? WHERE rp.owner_user_id=? OR tm.user_id=? ORDER BY rp.updated_at DESC LIMIT 30");$q->execute([$u['id'],$u['id'],$u['id']]);foreach($q->fetchAll() as $p){if($projectFilter!==''&&(string)$p['public_id']!==$projectFilter)continue;$s=change_impact_project_summary($pdo,$u,(string)$p['public_id'],8);if($s['events']>0)$portfolio[]=['project'=>$p,'summary'=>$s];}}
$labels=change_impact_decisions();
function impact_page_url(string $type,array $row): string {
    return match($type){
      'annotation'=>'/annotation.php?id='.rawurlencode((string)$row['public_id']),
      'claim'=>'/research-claim.php?id='.rawurlencode((string)$row['public_id']),
      'finding'=>'/research-finding.php?id='.rawurlencode((string)$row['public_id']),
      'report_version'=>'/research-report.php?id='.rawurlencode((string)$row['report_public_id']).'&v='.(int)$row['version_number'],
      'research_review'=>'/research-reviews.php?id='.rawurlencode((string)$row['public_id']),
      'cross_research_link'=>'/cross-research.php',
      default=>'#'
    };
}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Change Impact · Annotated</title><meta name="robots" content="noindex,nofollow"><link rel="stylesheet" href="/assets/css/app.css"></head><body>
<header class="topbar"><a class="brand" href="/home.php">Annotated</a><nav><a href="/home.php">Home</a><a href="/research.php">Research</a><a href="/research-reviews.php">Reviews</a><a href="/research-outcomes.php">Decision Memory</a><a href="/settings.php">Settings</a></nav></header>
<main class="impactCenterLayout"><section>
<div class="pageTitle"><span class="eyebrow">PHASE 22 · CHANGE IMPACT & STALENESS</span><h1>Change Impact</h1><p>Trace a Source change through the exact Research that depended on earlier evidence. “Potentially stale” means review is warranted—not that a Claim, Finding, or Report is automatically wrong.</p></div>
<?php if($success):?><div class="success"><?=h($success)?></div><?php endif?><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?>
<?php if(!$ready):?><div class="card empty"><h2>Change Impact requires migration 029.</h2><?php if(($u['role']??'')==='admin'):?><a class="button" href="/upgrade.php">Run database upgrade</a><?php endif?></div>
<?php elseif(!$view):?>
<div class="impactPortfolio"><?php if(!$portfolio):?><div class="card empty"><h2>No recent downstream Source impacts.</h2><p>When a monitored Source changes, Annotated will show the exact Research dependencies here.</p></div><?php endif?>
<?php foreach($portfolio as $entry):$p=$entry['project'];$s=$entry['summary'];?><article class="card impactProjectSummary"><div class="impactProjectHeader"><div><span class="eyebrow">RESEARCH PROJECT</span><h2><?=h((string)$p['title'])?></h2></div><a href="/research-project.php?id=<?=h((string)$p['public_id'])?>">Open project</a></div><div class="impactMetrics"><span><strong><?=h((string)$s['unresolved'])?></strong> unresolved</span><span><strong><?=h((string)$s['affected_claims'])?></strong> Claims</span><span><strong><?=h((string)$s['affected_findings'])?></strong> Findings</span><span><strong><?=h((string)$s['affected_reports'])?></strong> Report versions</span></div><?php foreach(array_slice($s['items'],0,5) as $i):?><a class="impactEventLink" href="/research-impact.php?event=<?=h((string)$i['event_id'])?>&project=<?=h((string)$p['public_id'])?>"><span><strong><?=h((string)$i['source_title'])?></strong><small><?=h((string)$i['created_at'])?> · <?=h((string)$i['unresolved_count'])?> unresolved</small></span><span class="badge"><?=h(strtoupper((string)$i['severity']))?></span></a><?php endforeach?></article><?php endforeach?></div>
<?php else:$e=$view['event'];?>
<div class="card impactSourceHeader"><div><span class="eyebrow">SOURCE CHANGE EVENT <?=h((string)$e['id'])?></span><h2><?=h((string)($e['source_title']?:$e['domain']))?></h2><p class="meta"><?=h((string)$e['source_public_id'])?> · v<?=h((string)($e['previous_version_number']??'?'))?> → v<?=h((string)$e['new_version_number'])?> · <?=h((string)$e['created_at'])?></p></div><div class="inlineActions"><a class="button secondary" href="/source.php?id=<?=h((string)$e['source_public_id'])?>#change-<?=h((string)$e['id'])?>">Open Source</a><?php if(!empty($e['previous_version_id'])):?><a class="button secondary" href="/source-compare.php?id=<?=h((string)$e['source_public_id'])?>&from=<?=h((string)$e['previous_version_id'])?>&to=<?=h((string)$e['new_version_id'])?>">Compare versions</a><?php endif?></div><?php if(!empty($e['diff_summary'])):?><p><?=h((string)$e['diff_summary'])?></p><?php endif?><div class="impactMetrics"><span><strong><?=h((string)$view['total_projects'])?></strong> projects</span><span><strong><?=h((string)$view['total_unresolved'])?></strong> unresolved items</span><span><strong><?=h((string)$e['affected_annotation_count'])?></strong> changed annotations</span></div></div>
<?php foreach($view['projects'] as $impact):$p=$impact['project'];$state=$impact['project_review_state'];?>
<section class="impactProjectBlock" id="project-<?=h((string)$p['public_id'])?>"><div class="card impactProjectHeader"><div><span class="eyebrow"><?=h(strtoupper((string)$impact['severity']))?> IMPACT</span><h2><?=h((string)$p['title'])?></h2><p><?=h((string)$impact['unresolved_count'])?> downstream item(s) still need human review.</p></div><div class="inlineActions"><a class="button secondary" href="/research-project.php?id=<?=h((string)$p['public_id'])?>">Open Research</a><a class="button secondary" href="/home.php?impact_agent=<?=h((string)$e['id'])?>&project=<?=h((string)$p['public_id'])?>">Ask Agent</a></div></div>
<div class="impactMetrics"><span><?=h((string)$impact['counts']['annotations'])?> annotations</span><span><?=h((string)$impact['counts']['claims'])?> Claims</span><span><?=h((string)$impact['counts']['findings'])?> Findings</span><span><?=h((string)$impact['counts']['reports'])?> reports</span><span><?=h((string)$impact['counts']['reviews'])?> prior reviews</span><span><?=h((string)$impact['counts']['cross_research_links'])?> cross-project links</span></div>
<form method="post" class="card impactDecisionForm"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="op" value="decide"><input type="hidden" name="event_id" value="<?=h((string)$e['id'])?>"><input type="hidden" name="project_id" value="<?=h((string)$p['public_id'])?>"><input type="hidden" name="object_type" value="project"><input type="hidden" name="object_public_id" value="<?=h((string)$p['public_id'])?>"><strong>Project-level review</strong><label>Decision<select name="decision"><?php foreach($labels as $key=>$label):?><option value="<?=h($key)?>" <?=($state['decision']??'')===$key?'selected':''?>><?=h($label)?></option><?php endforeach?></select></label><label>Note<input name="note" maxlength="8000" value="<?=h((string)($state['note']??''))?>" placeholder="Why is this still current, needs work, or resolved?"></label><label>Snooze until<input type="datetime-local" name="snoozed_until"></label><button>Save project review</button></form>
<?php
$buckets=[
 ['annotation','Affected annotations',$impact['annotations']],
 ['claim','Claims using earlier Source Versions',$impact['claims']],
 ['finding','Findings depending on affected Claims',$impact['findings']],
 ['report_version','Published Report Versions',$impact['reports']],
 ['research_review','Prior collaborative reviews',$impact['reviews']],
 ['cross_research_link','Accepted Cross-Research links',$impact['cross_research_links']]
];
foreach($buckets as [$type,$heading,$rows]):if(!$rows)continue;?>
<div class="sectionHeadWeb"><div><span class="eyebrow"><?=h(strtoupper(str_replace('_',' ',$type)))?></span><h3><?=h($heading)?></h3></div><span class="meta"><?=count($rows)?> affected</span></div>
<div class="impactObjectList"><?php foreach($rows as $row):$rs=$row['review_state']??null;$label=$type==='claim'?($row['statement']??$row['public_id']):($row['title']??$row['public_id']);?>
<article class="card impactObject <?=$row['needs_review']?'impactNeedsReview':'impactReviewed'?>"><div class="impactObjectHeader"><div><div class="impactBadges"><span class="badge"><?=h($row['needs_review']?'Needs review':'Reviewed')?></span><?php if(!empty($row['severity'])):?><span class="badge"><?=h(strtoupper((string)$row['severity']))?></span><?php endif?><?php if(!empty($rs['decision'])):?><span class="badge"><?=h((string)($labels[$rs['decision']]??$rs['decision']))?></span><?php endif?></div><h4><?=h(mb_substr((string)$label,0,300))?></h4></div><a href="<?=h(impact_page_url($type,$row))?>">Open</a></div>
<?php if($type==='annotation'):?><p class="meta"><?=h(str_replace('_',' ',(string)$row['impact_type']))?></p><?php if(!empty($row['previous_excerpt'])):?><blockquote><?=h(mb_substr((string)$row['previous_excerpt'],0,500))?></blockquote><?php endif?>
<?php elseif($type==='claim'):?><p class="meta">Current Claim status: <?=h((string)$row['status'])?></p><?php foreach($row['evidence'] as $ev):?><p class="meta"><?=h(strtoupper((string)$ev['relationship']))?> evidence captured at Source v<?=h((string)$ev['captured_version'])?>; Source is now v<?=h((string)$ev['current_version'])?>.</p><?php endforeach?>
<?php elseif($type==='finding'):?><p class="meta">Depends on affected Claim(s): <?=h(implode(', ',$row['claim_ids']))?></p>
<?php elseif($type==='report_version'):?><p class="meta">Immutable Report v<?=h((string)$row['version_number'])?><?=$row['is_current']?' · CURRENT PUBLISHED VERSION':' · historical version'?></p><?php foreach($row['reasons'] as $reason):?><p class="meta"><?=h((string)$reason)?></p><?php endforeach?>
<?php elseif($type==='research_review'):?><p class="meta"><?=h(ucfirst((string)$row['status']))?> review of <?=h(str_replace('_',' ',(string)$row['subject_type']))?> · requested <?=h((string)$row['created_at'])?></p>
<?php elseif($type==='cross_research_link'):?><p class="meta"><?=h((string)$row['source_project_title'])?> ↔ <?=h((string)$row['target_project_title'])?> · <?=h(str_replace('_',' ',(string)$row['relation_type']))?></p><?php endif?>
<form method="post" class="impactDecisionForm compact"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="op" value="decide"><input type="hidden" name="event_id" value="<?=h((string)$e['id'])?>"><input type="hidden" name="project_id" value="<?=h((string)$p['public_id'])?>"><input type="hidden" name="object_type" value="<?=h($type)?>"><input type="hidden" name="object_public_id" value="<?=h((string)$row['public_id'])?>"><select name="decision"><?php foreach($labels as $key=>$decisionLabel):?><option value="<?=h($key)?>" <?=($rs['decision']??'')===$key?'selected':''?>><?=h($decisionLabel)?></option><?php endforeach?></select><input name="note" maxlength="8000" value="<?=h((string)($rs['note']??''))?>" placeholder="Review note"><button>Save</button></form>
</article><?php endforeach?></div>
<?php endforeach?></section><?php endforeach?>
<?php endif?>
</section><aside><div class="card stickyImpactRail"><h3>How to read impact</h3><p class="meta"><strong>Needs review</strong> means an earlier evidence dependency changed. It does not mean the downstream Research is false.</p><p class="meta">Use <strong>Reviewed — still current</strong> when the change does not alter the conclusion, <strong>Needs update</strong> when follow-up work is required, and <strong>Resolved</strong> after that work is complete.</p><div class="inlineActions"><a href="/research.php">Research</a><a href="/research-reviews.php">Review Center</a><a href="/research-automations.php">Automations</a></div></div></aside>
</main></body></html>