<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';$u=require_user($pdo);$id=(string)($_GET['id']??$_POST['id']??'');$project=project_access($pdo,(int)$u['id'],$id);if(!$project){http_response_code(404);exit('Research project not found.');}
$success='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();try{if(($_POST['op']??'')==='receipt'){$r=provenance_receipt_create($pdo,$u,$project['public_id']);$success='Audit receipt created: '.$r['public_id'];}else throw new RuntimeException('Unknown provenance action.');}catch(Throwable $e){$error=$e->getMessage();}}
$manifest=provenance_ready($pdo)?provenance_project_manifest($pdo,$u,$project['public_id']):[];$integrity=$manifest?provenance_project_integrity($manifest):['report_snapshots'=>['total'=>0,'valid'=>0,'invalid'=>0],'manifest_hash'=>''];$edges=$manifest?provenance_manifest_edges($manifest):[];$receipts=provenance_ready($pdo)?provenance_receipts($pdo,$u,$project['public_id'],40):[];
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Research Provenance · Annotated</title><meta name="robots" content="noindex,nofollow"><link rel="stylesheet" href="/assets/css/app.css"></head><body>
<header class="topbar"><a class="brand" href="/home.php">Annotated</a><nav><a href="/research-project.php?id=<?=h($project['public_id'])?>">Project</a><a href="/research-network.php">Network</a><a href="/research.php">Research</a></nav></header>
<main class="provenanceLayout"><section><div class="pageTitle"><span class="eyebrow">PHASE 26 · RESEARCH PROVENANCE</span><h1><?=h($project['title'])?></h1><p>Trace the exact lineage from Source Versions through Annotations, Claim evidence, Findings, Reports, Citations, Reviews, and your Decision Memory. Recorded hashes are shown as recorded; only hashes Annotated can deterministically recompute are marked verified.</p></div>
<?php if($success):?><div class="success"><?=h($success)?></div><?php endif?><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?>
<?php if(!provenance_ready($pdo)):?><div class="card empty"><h2>Research Provenance needs migration 033.</h2><?php if(($u['role']??'')==='admin'):?><a class="button" href="/upgrade.php">Run database upgrade</a><?php endif?></div><?php else:?>
<div class="provenanceSummary"><div class="card"><strong><?=h((string)count($manifest['source_versions']))?></strong><span>Source Versions</span></div><div class="card"><strong><?=h((string)count($manifest['annotations']))?></strong><span>Annotations</span></div><div class="card"><strong><?=h((string)count($manifest['claims']))?></strong><span>Claims</span></div><div class="card"><strong><?=h((string)count($manifest['findings']))?></strong><span>Findings</span></div><div class="card"><strong><?=h((string)count($manifest['report_versions']))?></strong><span>Report Versions</span></div><div class="card"><strong><?=h((string)count($edges))?></strong><span>Lineage edges</span></div></div>
<div class="card provenanceIntegrity <?=$integrity['report_snapshots']['invalid']?'provenanceInvalid':'provenanceValid'?>"><span class="eyebrow">CURRENT MANIFEST</span><h2>SHA-256 <?=h($integrity['manifest_hash'])?></h2><p><?=h((string)$integrity['report_snapshots']['valid'])?> report snapshot hash<?=((int)$integrity['report_snapshots']['valid']===1?'':'es')?> verified · <?=h((string)$integrity['report_snapshots']['invalid'])?> mismatch<?=((int)$integrity['report_snapshots']['invalid']===1?'':'es')?>.</p><?php if($integrity['report_snapshots']['invalid']):?><strong>Integrity attention required: stored immutable report snapshot content does not match its recorded hash.</strong><?php endif?></div>

<section class="provenanceSection"><div class="sectionHeadWeb"><div><span class="eyebrow">SOURCE LINEAGE</span><h2>Source Versions</h2></div></div><?php if(!$manifest['source_versions']):?><div class="card empty">No Source Version lineage yet.</div><?php endif?><div class="provenanceGrid"><?php foreach($manifest['source_versions'] as $s):?><article class="card"><div class="meta"><?=h((string)$s['source_id'])?> · VERSION <?=h((string)$s['version_number'])?></div><h3><?=h((string)($s['source_title']?:$s['url']))?></h3><p class="meta">Roles: <?=h(implode(', ',$s['roles']))?></p><p class="meta">Recorded content hash: <?=h((string)($s['recorded_content_hash']?:'not recorded'))?></p><a href="/source.php?id=<?=h((string)$s['source_id'])?>">Open Source</a></article><?php endforeach?></div></section>

<section class="provenanceSection"><div class="sectionHeadWeb"><div><span class="eyebrow">EVIDENCE</span><h2>Claims & Evidence</h2></div></div><?php if(!$manifest['claims']):?><div class="card empty">No Claim lineage yet.</div><?php endif?><?php foreach($manifest['claims'] as $c):?><article class="card provenanceClaim"><div class="meta"><?=h(strtoupper((string)$c['type']))?> · <?=h(strtoupper((string)$c['status']))?> · <?=h((string)$c['id'])?></div><h3><?=h((string)$c['statement'])?></h3><?php foreach($c['evidence'] as $e):?><p class="meta"><?=h(strtoupper((string)$e['relationship']))?> · <?=h((string)$e['source_id'])?> v<?=h((string)$e['source_version'])?><?php if($e['annotation_id']):?> · Annotation <?=h((string)$e['annotation_id'])?><?php endif?></p><?php endforeach?><a href="/research-claim.php?id=<?=h((string)$c['id'])?>">Open Claim</a></article><?php endforeach?></section>

<section class="provenanceSection"><div class="sectionHeadWeb"><div><span class="eyebrow">SYNTHESIS</span><h2>Findings</h2></div></div><?php foreach($manifest['findings'] as $f):?><article class="card"><div class="meta"><?=h(strtoupper((string)$f['status']))?> · <?=h((string)$f['id'])?></div><h3><?=h((string)$f['title'])?></h3><p><?=h(mb_substr((string)$f['summary'],0,700))?></p><p class="meta">Claim links: <?=h((string)count($f['claims']))?></p><a href="/research-finding.php?id=<?=h((string)$f['id'])?>">Open Finding</a></article><?php endforeach?></section>

<section class="provenanceSection"><div class="sectionHeadWeb"><div><span class="eyebrow">PUBLICATION</span><h2>Report Versions</h2></div></div><?php foreach($manifest['report_versions'] as $r):?><article class="card provenanceReport <?=$r['snapshot_hash_valid']?'provenanceValid':'provenanceInvalid'?>"><div class="provenanceBadges"><span class="badge">v<?=h((string)$r['version_number'])?></span><span class="badge"><?=h(strtoupper((string)$r['visibility']))?></span><span class="badge"><?=$r['snapshot_hash_valid']?'Hash verified':'HASH MISMATCH'?></span><?php if($r['is_current']):?><span class="badge">Current</span><?php endif?></div><h3><?=h((string)$r['title'])?></h3><p class="meta">Stored: <?=h((string)$r['stored_snapshot_hash'])?><br>Computed: <?=h((string)$r['computed_snapshot_hash'])?></p><p class="meta"><?=h((string)count($r['citations']))?> outgoing report citation<?=count($r['citations'])===1?'':'s'?></p><div class="inlineActions"><a href="/research-report.php?id=<?=h((string)$r['report_id'])?>&v=<?=h((string)$r['version_number'])?>">Open version</a><a href="/research-report-network.php?id=<?=h((string)$r['report_id'])?>&v=<?=h((string)$r['version_number'])?>">Citation network</a></div></article><?php endforeach?></section>

<section class="provenanceSection"><div class="sectionHeadWeb"><div><span class="eyebrow">GOVERNANCE</span><h2>Reviews & Decisions</h2></div></div><div class="provenanceGrid"><div class="card"><h3><?=h((string)count($manifest['reviews']))?> collaborative reviews</h3><?php foreach(array_slice($manifest['reviews'],0,8) as $r):?><p><a href="/research-reviews.php?id=<?=h((string)$r['id'])?>"><?=h((string)$r['title'])?></a><br><span class="meta"><?=h((string)$r['subject_type'])?> · <?=h((string)$r['status'])?> · <?=h((string)count($r['responses']))?> response(s)</span></p><?php endforeach?></div><div class="card"><h3><?=h((string)count($manifest['decision_memory']))?> Decision Memory events</h3><p class="meta">Only your permission-scoped Decision Memory is included in your live provenance manifest and audit receipts.</p><a href="/research-outcomes.php?project=<?=h($project['public_id'])?>">Open Decision Memory</a></div></div></section>

<section class="provenanceSection"><div class="sectionHeadWeb"><div><span class="eyebrow">LINEAGE GRAPH</span><h2>Deterministic edges</h2></div></div><div class="provenanceEdgeList"><?php foreach(array_slice($edges,0,250) as $edge):?><div class="card provenanceEdge"><code><?=h((string)$edge['from'])?></code><strong><?=h(str_replace('_',' ',(string)$edge['type']))?></strong><code><?=h((string)$edge['to'])?></code></div><?php endforeach?></div><?php if(count($edges)>250):?><p class="meta">Showing the first 250 deterministic edges of <?=h((string)count($edges))?>.</p><?php endif?></section>
<?php endif?></section>
<aside><div class="card stickyProvenanceRail"><h3>Create audit receipt</h3><p class="meta">Freezes your current permission-scoped provenance manifest into an immutable JSON receipt with its own SHA-256.</p><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="id" value="<?=h($project['public_id'])?>"><input type="hidden" name="op" value="receipt"><button>Create audit receipt</button></form></div>
<div class="card"><h3>Your audit receipts</h3><?php if(!$receipts):?><p class="meta">No receipts yet.</p><?php endif?><?php foreach($receipts as $r):?><p><a href="/research-audit-receipt.php?id=<?=h((string)$r['public_id'])?>"><?=h((string)$r['created_at'])?></a><br><span class="meta"><?=$r['stored_hash_valid']?'Receipt hash valid':'HASH MISMATCH'?> · <?=$r['current_matches_receipt']?'Current state matches':'Project changed since receipt'?></span></p><?php endforeach?></div>
<div class="card"><h3>Verification boundary</h3><p class="meta">Report snapshot hashes and receipt hashes are recomputed here. Source content hashes are shown as recorded because the exact original hashing input may not be retained independently of the stored Source Version.</p></div></aside></main></body></html>