<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';$u=require_user($pdo);header('Cache-Control: private, no-store');header('Vary: Cookie');
$projects=[];$updates=0;$refsTotal=0;$q=$pdo->prepare("SELECT DISTINCT rp.public_id,rp.title FROM research_projects rp LEFT JOIN team_members tm ON tm.team_id=rp.team_id AND tm.user_id=? WHERE rp.status='active' AND (rp.owner_user_id=? OR tm.user_id=?) ORDER BY rp.updated_at DESC LIMIT 60");$q->execute([$u['id'],$u['id'],$u['id']]);
foreach($q->fetchAll() as $p){$refs=research_network_ready($pdo)?research_network_project_references($pdo,$u,(string)$p['public_id']):[];$count=count($refs);$newer=count(array_filter($refs,fn($r)=>!empty($r['available'])&&!empty($r['has_update'])));$refsTotal+=$count;$updates+=$newer;if($count>0||$newer>0)$projects[]=['project'=>$p,'references'=>$refs,'count'=>$count,'updates'=>$newer];}
$managed=living_research_ready($pdo)?living_research_managed_reports($pdo,$u,80):[];$managedRows=[];$incomingTotal=0;foreach($managed as $r){$n=research_network_ready($pdo)?research_network_report_network($pdo,$u,$r,(int)$r['version_number']):['counts'=>['references'=>0,'cited_by'=>0,'updates'=>0]];$incomingTotal+=(int)($n['counts']['cited_by']??0);$managedRows[]=['report'=>$r,'network'=>$n];}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Research Network · Annotated</title><meta name="robots" content="noindex,nofollow"><link rel="stylesheet" href="/assets/css/app.css"></head><body>
<header class="topbar"><a class="brand" href="/home.php">Annotated</a><nav><a href="/research-portfolio.php">Portfolio</a><a href="/research-publications.php">Living Research</a><a href="/research.php">Research</a></nav></header>
<main class="researchNetworkHub"><section><div class="pageTitle"><span class="eyebrow">PHASE 25 · RESEARCH NETWORK</span><h1>Research Network</h1><p>Manage explicit, version-pinned citations between Annotated Research reports. New report versions are surfaced for review without automatically changing any citation.</p></div>
<?php if(!research_network_ready($pdo)):?><div class="card empty"><h2>Research Network needs migration 032.</h2><?php if(($u['role']??'')==='admin'):?><a class="button" href="/upgrade.php">Run database upgrade</a><?php endif?></div><?php else:?>
<div class="citationNetworkSummary"><div class="card"><strong><?=h((string)$refsTotal)?></strong><span>Working citations</span></div><div class="card"><strong><?=h((string)$updates)?></strong><span>Newer cited versions available</span></div><div class="card"><strong><?=h((string)$incomingTotal)?></strong><span>Accessible citations to reports you manage</span></div><div class="card"><strong><?=h((string)count($managedRows))?></strong><span>Managed publications</span></div></div>
<section><div class="sectionHeadWeb"><div><span class="eyebrow">WORKING RESEARCH</span><h2>Project citation updates</h2></div></div><?php if(!$projects):?><div class="card empty">No active project currently references another Annotated Research report.</div><?php endif?>
<div class="citationHubList"><?php foreach($projects as $row):?><article class="card citationHubCard <?=$row['updates']?'citationUpdateAvailable':''?>"><div><span class="eyebrow">RESEARCH PROJECT</span><h3><?=h((string)$row['project']['title'])?></h3><p class="meta"><?=h((string)$row['count'])?> pinned report reference<?= $row['count']===1?'':'s' ?> · <?=h((string)$row['updates'])?> newer version<?= $row['updates']===1?'':'s' ?> available</p></div><div class="inlineActions"><a href="/research-citations.php?id=<?=h((string)$row['project']['public_id'])?>">Open citations</a><a href="/home.php?portfolio_agent=1&project=<?=h((string)$row['project']['public_id'])?>">Ask Agent</a></div></article><?php endforeach?></div></section>
<section><div class="sectionHeadWeb"><div><span class="eyebrow">PUBLISHED NETWORK</span><h2>Reports you manage</h2></div></div><?php if(!$managedRows):?><div class="card empty">No currently published report is managed by you.</div><?php endif?>
<div class="citationHubList"><?php foreach($managedRows as $row):$r=$row['report'];$n=$row['network'];?><article class="card citationHubCard"><div><span class="eyebrow">REPORT v<?=h((string)$r['version_number'])?></span><h3><a href="/research-report.php?id=<?=h((string)$r['public_id'])?>"><?=h((string)$r['title'])?></a></h3><p class="meta"><?=h((string)$n['counts']['references'])?> references · <?=h((string)$n['counts']['cited_by'])?> cited-by edges · <?=h((string)$n['counts']['updates'])?> cited report updates</p></div><a href="/research-report-network.php?id=<?=h((string)$r['public_id'])?>&v=<?=h((string)$r['version_number'])?>">Open network</a></article><?php endforeach?></div></section>
<?php endif?></section>
<aside><div class="card stickyCitationRail"><h3>Network boundary</h3><p class="meta">Only explicit citations become network edges. Similarity and Cross-Research suggestions remain separate until a user pins a report version into a project.</p><p class="meta">Published citation edges are immutable because they belong to immutable report versions.</p></div></aside>
</main></body></html>