<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';
$u=require_user($pdo);header('Cache-Control: private, no-store');header('Vary: Cookie');
if(!research_intelligence_portfolios_ready($pdo)){header('Location: /upgrade.php?from=research-intelligence-portfolios');exit;}
$error='';$success='';$portfolioId=trim((string)($_GET['portfolio']??$_POST['portfolio_id']??''));
if($_SERVER['REQUEST_METHOD']==='POST'){
    require_csrf();$op=(string)($_POST['op']??'');
    try{
        if($op==='create'){
            $p=research_intelligence_portfolio_create($pdo,$u,[
              'title'=>(string)($_POST['title']??''),'objective'=>(string)($_POST['objective']??''),'team_id'=>(string)($_POST['team_id']??''),
              'briefing_cadence'=>(string)($_POST['briefing_cadence']??'manual'),'timezone_name'=>(string)($_POST['timezone_name']??($u['timezone_name']??'UTC')),
              'briefing_time_local'=>(string)($_POST['briefing_time_local']??'09:00'),'briefing_weekday'=>(int)($_POST['briefing_weekday']??1),'briefing_day_of_month'=>(int)($_POST['briefing_day_of_month']??1),'briefing_policy'=>(string)($_POST['briefing_policy']??'material_only'),'materiality_threshold'=>(string)($_POST['materiality_threshold']??'important')
            ]);header('Location: /research-intelligence-portfolios.php?portfolio='.rawurlencode((string)$p['public_id']).'&created=1');exit;
        }
        if($portfolioId==='')throw new InvalidArgumentException('Choose a Portfolio first.');
        if($op==='add_program'){research_intelligence_portfolio_add_program($pdo,$u,$portfolioId,(string)($_POST['program_id']??''),(string)($_POST['member_role']??'supporting'));$success='Program added to Portfolio.';}
        elseif($op==='remove_program'){research_intelligence_portfolio_remove_program($pdo,$u,$portfolioId,(string)($_POST['program_id']??''));$success='Program removed from Portfolio.';}
        elseif($op==='snapshot'){research_intelligence_portfolio_snapshot($pdo,$u,$portfolioId,(int)($_POST['window_days']??30),'manual');$success='Frozen Portfolio snapshot created.';}
        elseif($op==='briefing'){$b=research_intelligence_portfolio_create_briefing($pdo,$u,$portfolioId,['title'=>(string)($_POST['title']??''),'window_days'=>(int)($_POST['window_days']??30)]);$success='Executive Briefing created as a normal Research Doc.';}
        elseif($op==='prepare_publication'){$w=research_intelligence_portfolio_prepare_publication($pdo,$u,(string)($_POST['briefing_id']??''),['required_approvals'=>(int)($_POST['required_approvals']??1)]);header('Location: /research-publications.php?workflow='.rawurlencode((string)$w['public_id']));exit;}
        elseif($op==='operations_update'){research_intelligence_portfolio_update($pdo,$u,$portfolioId,['briefing_cadence'=>(string)($_POST['briefing_cadence']??'manual'),'briefing_policy'=>(string)($_POST['briefing_policy']??'material_only'),'materiality_threshold'=>(string)($_POST['materiality_threshold']??'important'),'timezone_name'=>(string)($_POST['timezone_name']??($u['timezone_name']??'UTC')),'briefing_time_local'=>(string)($_POST['briefing_time_local']??'09:00'),'briefing_weekday'=>(int)($_POST['briefing_weekday']??1),'briefing_day_of_month'=>(int)($_POST['briefing_day_of_month']??1)]);$success='Portfolio intelligence schedule updated.';}
        elseif($op==='subscription_set'){research_intelligence_portfolio_subscription_set($pdo,$u,$portfolioId,['status'=>(string)($_POST['status']??'active'),'cadence'=>(string)($_POST['cadence']??'inherit'),'delivery_preference'=>(string)($_POST['delivery_preference']??'both')]);$success='Executive briefing subscription updated.';}
        elseif($op==='decision'){$result=research_intelligence_portfolio_create_native_decision($pdo,$u,$portfolioId,[
          'idempotency_key'=>(string)($_POST['idempotency_key']??''),'title'=>(string)($_POST['title']??''),'statement'=>(string)($_POST['statement']??''),
          'rationale'=>(string)($_POST['rationale']??''),'decision_type'=>(string)($_POST['decision_type']??'decision'),'confidence'=>(string)($_POST['confidence']??''),
          'insight_id'=>(string)($_POST['insight_id']??''),'briefing_id'=>(string)($_POST['briefing_id']??'')
        ]);$success='Draft Decision created in the native Decision Ledger: '.(string)($result['decision']['title']??'Decision').'.';}
        elseif($op==='feedback'){research_intelligence_portfolio_feedback_set($pdo,$u,$portfolioId,['feedback_type'=>(string)($_POST['feedback_type']??'useful'),'insight_id'=>(string)($_POST['insight_id']??''),'briefing_id'=>(string)($_POST['briefing_id']??''),'note'=>(string)($_POST['note']??'')]);$success='Portfolio feedback recorded.';}
        elseif($op==='pattern_refresh'){$memory=research_intelligence_portfolio_pattern_refresh($pdo,$u,$portfolioId,'manual');$success='Cross-Decision Pattern Memory refreshed: '.(string)($memory['summary']['active_patterns']??0).' active pattern(s).';}
        elseif($op==='strategic_edge_create'){[$st,$sid]=array_pad(explode(':',(string)($_POST['source_node']??''),2),2,'');[$tt,$tid]=array_pad(explode(':',(string)($_POST['target_node']??''),2),2,'');$edge=research_intelligence_strategic_edge_upsert($pdo,$u,$portfolioId,['source_type'=>$st,'source_public_id'=>$sid,'target_type'=>$tt,'target_public_id'=>$tid,'relation_type'=>(string)($_POST['relation_type']??''),'rationale'=>(string)($_POST['rationale']??''),'confidence'=>(string)($_POST['confidence']??''),'materiality'=>(string)($_POST['materiality']??'medium')]);$success='Strategic relationship recorded: '.research_intelligence_strategic_relation_types()[(string)$edge['relation_type']].'.';}
        elseif($op==='strategic_edge_refresh'){$edge=research_intelligence_strategic_edge_refresh($pdo,$u,(string)($_POST['edge_id']??''));$success='Strategic relationship state snapshots refreshed.';}
        elseif($op==='strategic_edge_remove'){research_intelligence_strategic_edge_remove($pdo,$u,(string)($_POST['edge_id']??''),(string)($_POST['reason']??''));$success='Strategic relationship removed with an audited reason.';}
        elseif($op==='strategic_review_configure'){$reviewers=[];foreach((array)($_POST['reviewer_ids']??[]) as $rid){$rid=trim((string)$rid);if($rid!=='')$reviewers[]=['user_id'=>$rid,'role'=>'reviewer','required'=>true];}research_intelligence_strategic_review_configure($pdo,$u,$portfolioId,['status'=>(string)($_POST['review_status']??'paused'),'cadence'=>(string)($_POST['review_cadence']??'monthly'),'due_offset_hours'=>(int)($_POST['review_due_offset_hours']??72),'reviewers'=>$reviewers]);$success='Recurring Strategic Review settings updated.';}
        elseif($op==='strategic_review_create'){$sr=research_intelligence_strategic_review_create($pdo,$u,$portfolioId,['trigger_type'=>'manual','idempotency_key'=>(string)($_POST['idempotency_key']??ulid_like())]);if(!empty($sr['collaborative_review_public_id'])){header('Location: /research-reviews.php?id='.rawurlencode((string)$sr['collaborative_review_public_id']));exit;}$success='Strategic Review packet created.';}
        elseif($op==='strategic_briefing_create'){$sb=research_intelligence_strategic_briefing_create($pdo,$u,$portfolioId,['idempotency_key'=>(string)($_POST['idempotency_key']??ulid_like()),'strategic_review_id'=>(string)($_POST['strategic_review_id']??''),'title'=>(string)($_POST['title']??''),'window_days'=>(int)($_POST['window_days']??30)]);if(!empty($sb['team_review_public_id'])){header('Location: /research-reviews.php?id='.rawurlencode((string)$sb['team_review_public_id']));exit;}$success='Executive Strategic Briefing created.';}
        elseif($op==='acknowledge'){research_intelligence_portfolio_acknowledge($pdo,$u,(string)($_POST['briefing_id']??''));$success='Executive Briefing acknowledged.';}
        elseif($op==='archive'){$p=research_intelligence_portfolio_access($pdo,$u,$portfolioId);if(!$p||!research_intelligence_portfolio_can_write($p))throw new RuntimeException('Portfolio is unavailable.');$pdo->prepare("UPDATE research_intelligence_portfolios SET status='archived',updated_at=NOW() WHERE id=?")->execute([(int)$p['id']]);research_intelligence_portfolio_event($pdo,(int)$p['id'],'archived','user',(int)$u['id']);header('Location: /research-intelligence-portfolios.php');exit;}
    }catch(Throwable $e){$error=$e->getMessage();}
}
$dashboard=research_intelligence_portfolio_dashboard($pdo,$u);$portfolios=$dashboard['portfolios'];$selected=$portfolioId!==''?research_intelligence_portfolio_detail($pdo,$u,$portfolioId):null;
if(!$selected&&$portfolios){$portfolioId=(string)$portfolios[0]['public_id'];$selected=research_intelligence_portfolio_detail($pdo,$u,$portfolioId);}
$teams=[];try{$q=$pdo->prepare("SELECT t.public_id,t.name,tm.role FROM teams t JOIN team_members tm ON tm.team_id=t.id WHERE tm.user_id=? AND tm.role IN ('owner','admin','researcher') ORDER BY t.name");$q->execute([(int)$u['id']]);$teams=$q->fetchAll()?:[];}catch(Throwable $e){}
$csrf=csrf_token();$summary=$dashboard['summary'];
$portfolioView=research_portfolios_view((string)($_GET['view']??'overview'));
$center=research_intelligence_portfolio_operations_ready($pdo)?research_intelligence_organization_command_center($pdo,$u):['summary'=>[],'generated_at'=>date('Y-m-d H:i:s')];
$overviewSections=research_portfolios_attention_sections($center);
$overviewAttentionCount=research_portfolios_attention_count($overviewSections);
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Intelligence Portfolios · Annotated</title><meta name="robots" content="noindex,nofollow"><link rel="stylesheet" href="/assets/css/app.css?v=61.0"></head>
<body data-workspace-user="<?=h((string)$u['public_id'])?>" data-workspace-surface="research-intelligence-portfolios">
<main class="intelligencePortfolioCanvas">
<section class="researchLibraryToolbar"><nav class="researchLibraryTabs researchPrimaryActions"><a href="/research.php">Research Agents</a><a class="active" href="/research-intelligence-portfolios.php">Portfolios</a></nav></section>
<header class="intelligencePortfolioHero"><div><span class="eyebrow">PHASE 74 · PORTFOLIOS &amp; GLOBAL ATTENTION</span><h1>Portfolios</h1><p>One organization-level home for Phase 60/73 Portfolio intelligence, strategic attention, review, Decision follow-through, Pattern Memory, dependencies, and Executive Briefings.</p></div></header>
<nav class="portfolioUnifiedTabs" aria-label="Portfolio views"><a class="<?=$portfolioView==='overview'?'active':''?>" href="<?=h(research_portfolios_href('overview'))?>">Overview</a><a class="<?=$portfolioView==='portfolios'?'active':''?>" href="<?=h(research_portfolios_href('portfolios',$portfolioId))?>">Portfolios</a></nav>
<?php if($success):?><div class="success"><?=h($success)?></div><?php endif?><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?>
<?php if($portfolioView==='overview'):$cs=(array)($center['summary']??[]);$xs=(array)($center['execution_summary']??[]);$ps=(array)($center['pattern_summary']??[]);$gs=(array)($center['strategic_graph_summary']??[]);$rs=(array)($center['strategic_review_summary']??[]);$bs=(array)($center['strategic_briefing_summary']??[]);$os=(array)($center['organizational_cognition_summary']??[]);?>
<section class="intelligencePortfolioStats portfolioOverviewStats">
<div><strong><?=h((string)($cs['portfolios']??$summary['portfolios']??0))?></strong><span>Portfolios</span></div>
<div><strong><?=h((string)$overviewAttentionCount)?></strong><span>Needs attention</span></div>
<div><strong><?=h((string)($xs['native_decisions']??0))?></strong><span>Decisions</span></div>
<div><strong><?=h((string)($xs['action_plans']??0))?></strong><span>Action plans</span></div>
<div><strong><?=h((string)($ps['active_patterns']??0))?></strong><span>Learning patterns</span></div>
<div><strong><?=h((string)($gs['conflicts']??0))?></strong><span>Strategic conflicts</span></div>
<div><strong><?=h((string)($rs['open']??0))?></strong><span>Open reviews</span></div>
<div><strong><?=h((string)($bs['publication_ready']??0))?></strong><span>Briefs ready</span></div>
<div><strong><?=h((string)($os['signals']??0))?></strong><span>Cognition signals</span></div>
</section>
<section class="portfolioAttentionIntro card"><div><span class="eyebrow">GLOBAL ATTENTION</span><h2>What needs review now</h2><p>Existing organization intelligence is grouped here instead of living in a separate Command Center. Every item deep-links to its authoritative Portfolio, Review, Action Plan, Task, or Phase 59 publication workflow.</p></div><small>Generated <?=h((string)($center['generated_at']??date('Y-m-d H:i:s')))?></small></section>
<section class="portfolioAttentionGrid">
<?php foreach($overviewSections as $section):?>
<article class="card portfolioAttentionCard" data-attention-key="<?=h((string)$section['key'])?>"><header><div><span class="eyebrow"><?=h((string)$section['eyebrow'])?></span><h2><?=h((string)$section['title'])?></h2></div><strong><?=h((string)$section['count'])?></strong></header>
<?php if(empty($section['items'])):?><p class="empty">Nothing currently needs attention in this area.</p><?php endif?>
<?php foreach(array_slice((array)$section['items'],0,24) as $item):?><div class="portfolioAttentionRow"><div><strong><?=h((string)$item['label'])?></strong><?php if((string)$item['meta']!==''):?><small><?=h((string)$item['meta'])?></small><?php endif?></div><a href="<?=h((string)$item['href'])?>">Open</a></div><?php endforeach?>
</article>
<?php endforeach?>
</section>
<section class="portfolioOverviewDirectory"><header><div><span class="eyebrow">PORTFOLIO DIRECTORY</span><h2>Organization intelligence</h2></div><a class="button" href="<?=h(research_portfolios_href('portfolios'))?>">Manage Portfolios</a></header><div class="portfolioOverviewCards">
<?php if(!$portfolios):?><div class="card empty"><h3>No Portfolios yet.</h3><p>Create one from the Portfolios view and add existing Research Programs.</p></div><?php endif?>
<?php foreach($portfolios as $p):$pa=$p['aggregate']['summary']??[];?><article class="card intelligencePortfolioCard"><a href="<?=h(research_portfolios_href('portfolios',(string)$p['public_id']))?>"><div><span><?=!empty($p['team_name'])?h((string)$p['team_name']):'PERSONAL'?></span><h3><?=h((string)$p['title'])?></h3></div><strong><?=h((string)$p['program_count'])?> Programs</strong></a><p><?=h(mb_substr((string)$p['objective'],0,260))?></p><div class="intelligencePortfolioMeta"><span><?=h((string)($pa['material_changes']??0))?> changes</span><span><?=h((string)($pa['high_changes']??0))?> high</span><span><?=!empty($p['briefing_due'])?'Briefing due':'Briefing current'?></span></div></article><?php endforeach?>
</div></section>
<?php else:?>
<section class="intelligencePortfolioStats">
<div><strong><?=h((string)$summary['portfolios'])?></strong><span>Portfolios</span></div><div><strong><?=h((string)$summary['programs'])?></strong><span>Programs</span></div><div><strong><?=h((string)$summary['briefings'])?></strong><span>Briefings</span></div><div><strong><?=h((string)$summary['risk_signals'])?></strong><span>Risk signals</span></div><div><strong><?=h((string)$summary['opportunity_signals'])?></strong><span>Opportunity signals</span></div><div><strong><?=h((string)$summary['cross_program_tensions'])?></strong><span>Cross-program tensions</span></div>
</section>
<section class="intelligencePortfolioGrid">
<aside class="card intelligencePortfolioCreate"><span class="eyebrow">NEW PORTFOLIO</span><h2>Group Research Programs</h2><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="op" value="create"><label>Portfolio title<input name="title" required maxlength="255" placeholder="Market Intelligence"></label><label>Objective<textarea name="objective" required rows="5" maxlength="16000" placeholder="What should leadership continuously understand across these Programs?"></textarea></label><label>Scope<select name="team_id"><option value="">Personal</option><?php foreach($teams as $team):?><option value="<?=h((string)$team['public_id'])?>"><?=h((string)$team['name'])?></option><?php endforeach?></select></label><label>Briefing cadence<select name="briefing_cadence"><option value="manual">Manual</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option></select></label><label>Draft policy<select name="briefing_policy"><option value="material_only">Only when materially changed</option><option value="always">Every scheduled cycle</option></select></label><label>Materiality<select name="materiality_threshold"><option value="important">Important + high</option><option value="high">High only</option><option value="any">Any tracked change</option></select></label><input type="hidden" name="timezone_name" value="<?=h((string)($u['timezone_name']??'UTC'))?>"<button>Create Portfolio</button></form><p class="meta">Portfolios aggregate existing Program state. They do not create another worker, scheduler, Claim store, task system, or document system.</p></aside>
<section class="intelligencePortfolioList">
<header><div><span class="eyebrow">PORTFOLIOS</span><h2>Organization intelligence</h2></div><small>Generated <?=h((string)$dashboard['generated_at'])?></small></header>
<?php if(!$portfolios):?><div class="card empty"><h3>No Intelligence Portfolios yet.</h3><p>Create one and add existing Research Programs.</p></div><?php endif?>
<?php foreach($portfolios as $p):$a=$p['aggregate']['summary']??[];$sel=$selected&&$selected['public_id']===$p['public_id'];?>
<article class="card intelligencePortfolioCard <?=$sel?'is-selected':''?>"><a href="/research-intelligence-portfolios.php?portfolio=<?=rawurlencode((string)$p['public_id'])?>"><div><span><?=!empty($p['team_name'])?h((string)$p['team_name']):'PERSONAL'?></span><h3><?=h((string)$p['title'])?></h3></div><strong><?=h((string)$p['program_count'])?> Programs</strong></a><p><?=h(mb_substr((string)$p['objective'],0,260))?></p><div class="intelligencePortfolioMeta"><span><?=h((string)($a['material_changes']??0))?> changes</span><span><?=h((string)($a['high_changes']??0))?> high</span><span><?=!empty($p['briefing_due'])?'Briefing due':'Briefing current'?></span></div></article>
<?php endforeach?>
</section></section>
<?php if($selected):$a=$selected['aggregate'];$canWrite=research_intelligence_portfolio_can_write($selected);$portfolioAttentionSections=research_portfolios_attention_sections($center,(string)$selected['public_id']);$portfolioAttentionCount=research_portfolios_attention_count($portfolioAttentionSections);?>
<section class="card intelligencePortfolioDetail">
<header class="intelligencePortfolioDetailHeader"><div><span class="eyebrow">PROGRAM PORTFOLIO</span><h2><?=h((string)$selected['title'])?></h2><p><?=h((string)$selected['objective'])?></p></div><div class="intelligencePortfolioDetailMeta"><span><?=!empty($selected['team_name'])?h((string)$selected['team_name']):'Personal scope'?></span><span><?=h((string)$selected['access_role'])?></span></div></header>
<section class="portfolioContextAttention"><header><div><span class="eyebrow">CONTEXTUAL ATTENTION</span><h3>Needs attention in this Portfolio</h3></div><strong><?=h((string)$portfolioAttentionCount)?></strong></header>
<?php if($portfolioAttentionCount===0):?><p class="empty">No current review, execution, briefing, dependency, or intelligence signal requires attention.</p><?php else:?><div class="portfolioContextAttentionGrid">
<?php foreach($portfolioAttentionSections as $section):if(empty($section['items']))continue;?><section><h4><?=h((string)$section['title'])?></h4><?php foreach(array_slice((array)$section['items'],0,6) as $item):?><div class="portfolioAttentionRow"><div><strong><?=h((string)$item['label'])?></strong><?php if((string)$item['meta']!==''):?><small><?=h((string)$item['meta'])?></small><?php endif?></div><a href="<?=h((string)$item['href'])?>">Open</a></div><?php endforeach?></section><?php endforeach?>
</div><?php endif?></section>
<section class="intelligencePortfolioOverview"><div><strong><?=h((string)$a['summary']['programs'])?></strong><span>Programs</span></div><div><strong><?=h((string)$a['summary']['material_changes'])?></strong><span>Material changes</span></div><div><strong><?=h((string)$a['summary']['high_changes'])?></strong><span>High changes</span></div><div><strong><?=h((string)$a['summary']['failed_runs_30d'])?></strong><span>Failed runs · 30d</span></div><div><strong><?=h((string)$a['summary']['stale_sources'])?></strong><span>Stale evidence</span></div></section>
<?php $ops=$selected['operations']??['ready'=>false];$subscription=$ops['subscription']??null;?>
<?php if(!empty($ops['ready'])):?><section class="intelligenceOperationsPanel"><div class="intelligenceOperationsGrid">
<div class="card"><span class="eyebrow">61A · SCHEDULED INTELLIGENCE</span><h3>Portfolio cycle</h3><p class="meta">Next cycle: <?=h((string)($selected['next_cycle_at']??'Manual only'))?><br>Last cycle: <?=h((string)($selected['last_cycle_at']??'Not run'))?></p><?php if($canWrite):?><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="portfolio_id" value="<?=h((string)$selected['public_id'])?>"><input type="hidden" name="op" value="operations_update"><label>Cadence<select name="briefing_cadence"><?php foreach(['manual'=>'Manual','weekly'=>'Weekly','monthly'=>'Monthly','quarterly'=>'Quarterly'] as $v=>$label):?><option value="<?=h($v)?>" <?=$selected['briefing_cadence']===$v?'selected':''?>><?=h($label)?></option><?php endforeach?></select></label><label>Draft policy<select name="briefing_policy"><option value="material_only" <?=($selected['briefing_policy']??'material_only')==='material_only'?'selected':''?>>Only when materially changed</option><option value="always" <?=($selected['briefing_policy']??'')==='always'?'selected':''?>>Every scheduled cycle</option></select></label><label>Materiality<select name="materiality_threshold"><option value="important" <?=($selected['materiality_threshold']??'important')==='important'?'selected':''?>>Important + high</option><option value="high" <?=($selected['materiality_threshold']??'')==='high'?'selected':''?>>High only</option><option value="any" <?=($selected['materiality_threshold']??'')==='any'?'selected':''?>>Any change</option></select></label><input type="hidden" name="timezone_name" value="<?=h((string)($selected['timezone_name']??'UTC'))?>"><input type="hidden" name="briefing_time_local" value="<?=h((string)($selected['briefing_time_local']??'09:00'))?>"><input type="hidden" name="briefing_weekday" value="<?=h((string)($selected['briefing_weekday']??1))?>"><input type="hidden" name="briefing_day_of_month" value="<?=h((string)($selected['briefing_day_of_month']??1))?>"><button>Update cycle</button></form><?php endif?></div>
<div class="card"><span class="eyebrow">61C · EXECUTIVE SUBSCRIPTION</span><h3>My briefing delivery</h3><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="portfolio_id" value="<?=h((string)$selected['public_id'])?>"><input type="hidden" name="op" value="subscription_set"><label>Status<select name="status"><option value="active" <?=($subscription['status']??'active')==='active'?'selected':''?>>Active</option><option value="paused" <?=($subscription['status']??'')==='paused'?'selected':''?>>Paused</option></select></label><label>Cadence<select name="cadence"><?php foreach(['inherit'=>'Portfolio cadence','every_briefing'=>'Every briefing','weekly'=>'At most weekly','monthly'=>'At most monthly','quarterly'=>'At most quarterly'] as $v=>$label):?><option value="<?=h($v)?>" <?=($subscription['cadence']??'inherit')===$v?'selected':''?>><?=h($label)?></option><?php endforeach?></select></label><label>Delivery<select name="delivery_preference"><?php foreach(['both'=>'Draft + published','draft_ready'=>'Draft ready','published_only'=>'Published only'] as $v=>$label):?><option value="<?=h($v)?>" <?=($subscription['delivery_preference']??'both')===$v?'selected':''?>><?=h($label)?></option><?php endforeach?></select></label><button>Save subscription</button></form></div>
<div class="card intelligenceCycleHistory"><span class="eyebrow">CYCLE HISTORY</span><h3>Recent runs</h3><?php if(empty($ops['cycles'])):?><p class="meta">No scheduled Portfolio cycles yet.</p><?php else:?><?php foreach(array_slice($ops['cycles'],0,6) as $cycle):?><div><strong><?=h(strtoupper((string)$cycle['status']))?></strong><span><?=h((string)$cycle['scheduled_for'])?></span><small><?=h((string)($cycle['detail']??''))?></small></div><?php endforeach?><?php endif?></div>
</div></section><?php endif?>
<div class="intelligencePortfolioColumns">
<section><header><span class="eyebrow">PROGRAMS</span><h3>Portfolio members</h3></header><?php if(!$selected['programs']):?><div class="empty">No Programs added yet.</div><?php endif?><?php foreach($selected['programs'] as $program):?><article class="intelligenceProgramRow"><div><strong><?=h((string)$program['title'])?></strong><small><?=h((string)$program['project_title'])?> · <?=h((string)$program['member_role'])?> · <?=h((string)$program['status'])?></small></div><a href="/research-programs.php?agent=<?=rawurlencode((string)$program['agent_public_id'])?>&program=<?=rawurlencode((string)$program['public_id'])?>">Open</a><?php if($canWrite):?><form method="post"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="portfolio_id" value="<?=h((string)$selected['public_id'])?>"><input type="hidden" name="op" value="remove_program"><input type="hidden" name="program_id" value="<?=h((string)$program['public_id'])?>"><button class="linkButton">Remove</button></form><?php endif?></article><?php endforeach?>
<?php if($canWrite&&!empty($selected['available_programs'])):?><form method="post" class="intelligencePortfolioAddProgram"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="portfolio_id" value="<?=h((string)$selected['public_id'])?>"><input type="hidden" name="op" value="add_program"><label>Add Program<select name="program_id"><?php foreach($selected['available_programs'] as $program):?><option value="<?=h((string)$program['public_id'])?>"><?=h((string)$program['title'])?> · <?=h((string)$program['project_title'])?></option><?php endforeach?></select></label><label>Role<select name="member_role"><option value="primary">Primary</option><option value="supporting" selected>Supporting</option><option value="watch">Watch</option></select></label><button>Add</button></form><?php endif?></section>
<section><header><span class="eyebrow">CROSS-PROGRAM INTELLIGENCE</span><h3>Risks & opportunities</h3></header><div class="intelligenceSignalGroup"><h4>Risks</h4><?php if(!$a['risks']):?><p class="meta">No deterministic risk deltas in this window.</p><?php endif?><?php foreach(array_slice($a['risks'],0,8) as $r):?><div class="intelligenceSignal is-risk"><strong><?=h((string)$r['program_title'])?></strong><span><?=h((string)$r['summary'])?></span></div><?php endforeach?></div><div class="intelligenceSignalGroup"><h4>Opportunities / positive movement</h4><?php if(!$a['opportunities']):?><p class="meta">No positive deterministic deltas in this window.</p><?php endif?><?php foreach(array_slice($a['opportunities'],0,8) as $r):?><div class="intelligenceSignal is-opportunity"><strong><?=h((string)$r['program_title'])?></strong><span><?=h((string)$r['summary'])?></span></div><?php endforeach?></div></section>
</div>
<section class="intelligencePortfolioTensions"><header><span class="eyebrow">SHARED REFERENCES</span><h3>Cross-program trends & tensions</h3></header><?php if(!$a['cross_program']):?><div class="empty">No shared cross-program reference signals in the current window.</div><?php endif?><div class="intelligenceTensionGrid"><?php foreach($a['cross_program'] as $x):?><article class="<?=$x['kind']==='cross_program_tension'?'is-tension':''?>"><strong><?=h(ucwords(str_replace('_',' ',(string)$x['kind'])))?></strong><span><?=h((string)$x['key'])?></span><small><?=h((string)$x['program_count'])?> Programs</small></article><?php endforeach?></div></section>
<section class="intelligencePortfolioInference"><header><div><span class="eyebrow">AGENT INTERPRETATION</span><h3>Explicit inference layer</h3></div><p>These are interpretations, not deterministic portfolio facts. Each inference retains explicit provenance references and optional confidence.</p></header><?php if(!$selected['inferences']):?><div class="empty">No Agent inferences have been attached to this Portfolio.</div><?php endif?><?php foreach($selected['inferences'] as $i):?><article><div><span class="badge"><?=h(strtoupper((string)$i['category']))?></span><span class="badge"><?=h(strtoupper((string)$i['severity']))?></span><?php if($i['confidence']!==null):?><span class="badge"><?=h((string)round((float)$i['confidence']*100))?>% confidence</span><?php endif?></div><h4><?=h((string)$i['title'])?></h4><p><?=h((string)$i['body'])?></p><small><?=h((string)count((array)($i['provenance']['refs']??[])))?> provenance ref(s)</small></article><?php endforeach?></section>
<?php if(!empty($ops['ready'])):?><section class="intelligenceExecutiveFollowThrough"><div class="intelligencePortfolioColumns">
<section><span class="eyebrow">61D · DECISIONS & FOLLOW-THROUGH · PHASE 73 NATIVE DECISION HANDOFF</span><h3>Create a Decision from Portfolio intelligence</h3><?php if($canWrite):?><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="portfolio_id" value="<?=h((string)$selected['public_id'])?>"><input type="hidden" name="op" value="decision"><input type="hidden" name="idempotency_key" value="<?=h(ulid_like())?>"><label>Decision title<input name="title" required maxlength="255"></label><label>Decision type<select name="decision_type"><?php foreach(research_decision_types() as $v=>$label):?><option value="<?=h($v)?>"><?=h($label)?></option><?php endforeach?></select></label><label>Link insight<select name="insight_id"><option value="">No specific insight</option><?php foreach($selected['inferences'] as $i):?><option value="<?=h((string)$i['public_id'])?>"><?=h((string)$i['title'])?></option><?php endforeach?></select></label><label>Link briefing<select name="briefing_id"><option value="">No specific briefing</option><?php foreach($selected['briefings'] as $b):?><option value="<?=h((string)$b['public_id'])?>"><?=h((string)$b['title'])?></option><?php endforeach?></select></label><label>Decision statement<textarea name="statement" rows="4" required maxlength="64000"></textarea></label><label>Rationale<textarea name="rationale" rows="4" maxlength="64000"></textarea></label><label>Confidence <input type="number" name="confidence" min="0" max="1" step="0.01" placeholder="Optional 0–1"></label><button>Create Draft Decision</button></form><p class="meta">This creates a real Phase 71 Decision on the Portfolio anchor Research Agent. It does not create a Task or Action Plan automatically. After the Decision is explicitly accepted, use the normal Action Plan handoff for execution.</p><?php endif?></section>
<section><span class="eyebrow">61E · EXPLICIT LEARNING</span><h3>Human feedback</h3><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="portfolio_id" value="<?=h((string)$selected['public_id'])?>"><input type="hidden" name="op" value="feedback"><label>Feedback<select name="feedback_type"><option value="useful">Useful</option><option value="irrelevant">Irrelevant</option><option value="resolved">Resolved</option><option value="escalated">Escalated</option><option value="acted_on">Acted on</option></select></label><label>Insight<select name="insight_id"><option value="">Portfolio-level feedback</option><?php foreach($selected['inferences'] as $i):?><option value="<?=h((string)$i['public_id'])?>"><?=h((string)$i['title'])?></option><?php endforeach?></select></label><label>Note<textarea name="note" rows="4" maxlength="2000"></textarea></label><button>Record feedback</button></form><p class="meta">Feedback is inspectable context. It never silently rewrites Claims, Findings, evidence, or Agent conclusions.</p></section>
</div><section class="intelligenceDecisionList"><h3>Portfolio Decisions</h3><?php if(empty($ops['decisions'])):?><p class="meta">No Portfolio decisions recorded yet.</p><?php else:?><?php foreach(array_slice($ops['decisions'],0,12) as $d):?><article><div><strong><?=h((string)$d['title'])?></strong><small><?php if(($d['record_kind']??'')==='native'):?><?=h(strtoupper((string)$d['decision_type']))?> · <?=h(strtoupper((string)$d['status']))?> · <?=h((string)$d['occurred_at'])?><?php else:?>LEGACY PHASE 61 · <?=h(strtoupper((string)$d['decision_type']))?> · <?=h((string)$d['occurred_at'])?><?php endif?></small></div><div><?php if(!empty($d['decision_public_id'])):?><a href="/research-decisions.php?decision=<?=rawurlencode((string)$d['decision_public_id'])?>">Open Decision</a><?php elseif(!empty($d['task_public_id'])):?><span class="badge"><?=h((string)$d['task_status'])?></span><a href="/research-tasks.php?task=<?=rawurlencode((string)$d['task_public_id'])?>">Open legacy follow-up</a><?php else:?><span class="meta">Historical Portfolio record</span><?php endif?></div></article><?php endforeach?><?php endif?></section>
<?php $dx=$ops['decision_execution']??['ready'=>false,'summary'=>[],'decisions'=>[]];?>
<?php if(!empty($dx['ready'])):$ds=$dx['summary'];?><section class="intelligenceDecisionExecutionRollup"><header><span class="eyebrow">PHASE 73 · DECISION & EXECUTION ROLLUP</span><h3>Strategic execution state</h3><p>Live read-only rollup from native Decisions, Phase 72 Action Plans, variances, Team Reviews, and Outcome Memory.</p></header>
<section class="intelligencePortfolioOverview"><div><strong><?=h((string)($ds['native_decisions']??0))?></strong><span>Native decisions</span></div><div><strong><?=h((string)($ds['action_plans']??0))?></strong><span>Action plans</span></div><div><strong><?=h((string)($ds['active_action_plans']??0))?></strong><span>Active</span></div><div><strong><?=h((string)($ds['material_open_variances']??0))?></strong><span>Material variances</span></div><div><strong><?=h((string)($ds['open_reviews']??0))?></strong><span>Open reviews</span></div><div><strong><?=h((string)($ds['completed_without_outcome']??0))?></strong><span>Awaiting outcome</span></div></section>
<div class="intelligenceDecisionList"><?php if(empty($dx['decisions'])):?><p class="meta">No native Portfolio Decisions yet.</p><?php else:?><?php foreach(array_slice($dx['decisions'],0,20) as $decision):?><article><div><strong><?=h((string)$decision['title'])?></strong><small><?=h(strtoupper((string)$decision['status']))?> · <?=h((string)count((array)$decision['action_plans']))?> Action Plan(s) · <?=h((string)($decision['reviews']['open']??0))?> open Decision review(s)</small><?php foreach((array)$decision['action_plans'] as $plan):?><small><?=h((string)$plan['title'])?> · <?=h(strtoupper((string)$plan['status']))?> · <?=h((string)($plan['variance']['material_open']??0))?> material variance(s) · <?=h((string)($plan['reviews']['open']??0))?> open review(s) · <?=$plan['outcome_recorded']?'Outcome recorded':'No outcome yet'?></small><?php endforeach?></div><div><a href="/research-decisions.php?decision=<?=rawurlencode((string)$decision['public_id'])?>">Open Decision</a><?php foreach(array_slice((array)$decision['action_plans'],0,2) as $plan):?><a href="/research-action-plans.php?action_plan=<?=rawurlencode((string)$plan['public_id'])?>">Open Plan</a><?php endforeach?></div></article><?php endforeach?><?php endif?></div>
<?php if(!empty($ds['legacy_records'])):?><p class="meta"><?=h((string)$ds['legacy_records'])?> historical Phase 61 Portfolio decision record(s) are preserved separately and are not counted as native execution state.</p><?php endif?></section><?php endif?>
<?php $pm=$ops['pattern_memory']??['ready'=>false,'summary'=>[],'patterns'=>[],'latest_run'=>null];?>
<?php if(!empty($pm['ready'])):$ps=$pm['summary'];?><section class="intelligenceDecisionPatternMemory"><header><div><span class="eyebrow">PHASE 73 · CROSS-DECISION PATTERN MEMORY</span><h3>Organizational learning patterns</h3><p>Deterministic memory from facts repeated across two or more native Portfolio Decisions. No fuzzy similarity, no automatic Decision changes.</p></div><?php if($canWrite):?><form method="post"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="portfolio_id" value="<?=h((string)$selected['public_id'])?>"><input type="hidden" name="op" value="pattern_refresh"><button>Refresh Pattern Memory</button></form><?php endif?></header>
<section class="intelligencePortfolioOverview"><div><strong><?=h((string)($ps['active_patterns']??0))?></strong><span>Active patterns</span></div><div><strong><?=h((string)($ps['repeated_assumptions']??0))?></strong><span>Repeated assumptions</span></div><div><strong><?=h((string)($ps['repeated_plan_risks']??0))?></strong><span>Repeated risks</span></div><div><strong><?=h((string)($ps['recurring_variance_types']??0))?></strong><span>Variance patterns</span></div><div><strong><?=h((string)($ps['recurring_outcome_assessments']??0))?></strong><span>Outcome patterns</span></div><div><strong><?=h((string)($ps['repeated_lessons']??0))?></strong><span>Repeated lessons</span></div></section>
<?php if(empty($pm['patterns'])):?><p class="meta">No cross-Decision pattern has met the deterministic two-Decision threshold yet. Refresh after more Decisions accumulate comparable evidence.</p><?php else:?><div class="intelligenceDecisionList"><?php foreach(array_slice((array)$pm['patterns'],0,30) as $pattern):?><article><div><strong><?=h((string)$pattern['label'])?></strong><small><?=h(strtoupper(str_replace('_',' ',(string)$pattern['pattern_type'])))?> · <?=h((string)$pattern['decision_count'])?> Decisions · <?=h((string)$pattern['evidence_count'])?> evidence member(s)</small><small><?=h((string)$pattern['summary'])?></small><small>First seen <?=h((string)$pattern['first_seen_at'])?> · last seen <?=h((string)$pattern['last_seen_at'])?></small></div><div><?php foreach(array_slice((array)$pattern['members'],0,4) as $member):?><?php if(($member['member_type']??'')==='decision'):?><a href="/research-decisions.php?decision=<?=rawurlencode((string)$member['member_public_id'])?>">Decision</a><?php elseif(($member['member_type']??'')==='action_plan'):?><a href="/research-action-plans.php?action_plan=<?=rawurlencode((string)$member['member_public_id'])?>">Plan</a><?php endif?><?php endforeach?></div></article><?php endforeach?></div><?php endif?>
<?php if(!empty($pm['latest_run'])):?><p class="meta">Latest memory run <?=h((string)$pm['latest_run']['created_at'])?> · <?=h(strtoupper((string)$pm['latest_run']['triggered_by']))?> · state <?=h(substr((string)$pm['latest_run']['state_hash'],0,12))?>…</p><?php endif?></section><?php endif?>
<?php $sg=$ops['strategic_graph']??['ready'=>false,'summary'=>[],'edges'=>[],'nodes'=>[],'attention'=>[]];?>
<?php if(!empty($sg['ready'])):$gs=$sg['summary'];$sourceGraphNodes=array_values(array_filter((array)$sg['nodes'],fn($n)=>!empty($n['in_portfolio'])));$allGraphNodes=research_intelligence_strategic_available_nodes($pdo,$u,500);?><section class="intelligenceStrategicGraph"><header><div><span class="eyebrow">PHASE 73 · STRATEGIC DEPENDENCY & CONFLICT GRAPH</span><h3>Decision and Action Plan relationships</h3><p>Explicit, audited relationships. Stale means an endpoint changed after the relationship was recorded; it never changes Decision or Plan state automatically.</p></div></header>
<section class="intelligencePortfolioOverview"><div><strong><?=h((string)($gs['active_edges']??0))?></strong><span>Relationships</span></div><div><strong><?=h((string)($gs['dependencies']??0))?></strong><span>Dependencies</span></div><div><strong><?=h((string)($gs['conflicts']??0))?></strong><span>Conflicts</span></div><div><strong><?=h((string)($gs['blocks']??0))?></strong><span>Blocks</span></div><div><strong><?=h((string)($gs['stale_edges']??0))?></strong><span>Stale</span></div><div><strong><?=h((string)($gs['cross_portfolio_edges']??0))?></strong><span>Cross-Portfolio</span></div></section>
<?php if($canWrite&&$sourceGraphNodes&&$allGraphNodes):?><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="portfolio_id" value="<?=h((string)$selected['public_id'])?>"><input type="hidden" name="op" value="strategic_edge_create"><label>Source<select name="source_node" required><?php foreach($sourceGraphNodes as $node):?><option value="<?=h((string)$node['type'].':'.(string)$node['public_id'])?>"><?=h(strtoupper(str_replace('_',' ',(string)$node['type'])).' · '.(string)$node['title'])?></option><?php endforeach?></select></label><label>Relationship<select name="relation_type"><?php foreach(research_intelligence_strategic_relation_types() as $key=>$label):?><option value="<?=h($key)?>"><?=h($label)?></option><?php endforeach?></select></label><label>Target<select name="target_node" required><?php foreach($allGraphNodes as $node):?><option value="<?=h((string)$node['type'].':'.(string)$node['public_id'])?>"><?=h(strtoupper(str_replace('_',' ',(string)$node['type'])).' · '.(string)$node['title'].' · '.implode(', ',(array)$node['portfolio_ids']))?></option><?php endforeach?></select></label><label>Rationale<textarea name="rationale" rows="3" maxlength="12000" required></textarea></label><label>Materiality<select name="materiality"><option value="low">Low</option><option value="medium" selected>Medium</option><option value="high">High</option><option value="critical">Critical</option></select></label><label>Confidence <input type="number" name="confidence" min="0" max="1" step="0.01" placeholder="Optional 0–1"></label><button>Record relationship</button></form><?php endif?>
<?php if(empty($sg['edges'])):?><p class="meta">No strategic relationships recorded for this Portfolio yet.</p><?php else:?><div class="intelligenceDecisionList"><?php foreach($sg['edges'] as $edge):?><article><div><strong><?=h((string)$edge['source']['title'])?> → <?=h((string)$edge['target']['title'])?></strong><small><?=h(strtoupper(str_replace('_',' ',(string)$edge['relation_type'])))?> · <?=h(strtoupper((string)($edge['materiality']??'medium')))?><?=$edge['cross_portfolio']?' · CROSS-PORTFOLIO':''?><?=$edge['stale']?' · STALE':''?></small><small><?=h((string)$edge['rationale'])?></small></div><div><?php if($edge['source_type']==='decision'):?><a href="/research-decisions.php?decision=<?=rawurlencode((string)$edge['source_public_id'])?>">Source</a><?php else:?><a href="/research-action-plans.php?action_plan=<?=rawurlencode((string)$edge['source_public_id'])?>">Source</a><?php endif?><?php if($edge['target_type']==='decision'):?><a href="/research-decisions.php?decision=<?=rawurlencode((string)$edge['target_public_id'])?>">Target</a><?php else:?><a href="/research-action-plans.php?action_plan=<?=rawurlencode((string)$edge['target_public_id'])?>">Target</a><?php endif?><?php if($canWrite):?><?php if($edge['stale']):?><form method="post"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="portfolio_id" value="<?=h((string)$selected['public_id'])?>"><input type="hidden" name="op" value="strategic_edge_refresh"><input type="hidden" name="edge_id" value="<?=h((string)$edge['public_id'])?>"><button class="linkButton">Acknowledge current state</button></form><?php endif?><form method="post"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="portfolio_id" value="<?=h((string)$selected['public_id'])?>"><input type="hidden" name="op" value="strategic_edge_remove"><input type="hidden" name="edge_id" value="<?=h((string)$edge['public_id'])?>"><input name="reason" maxlength="12000" required placeholder="Removal reason"><button class="linkButton">Remove relationship</button></form><?php endif?></div></article><?php endforeach?></div><?php endif?></section><?php endif?>
<?php $sr=$ops['strategic_reviews']??['ready'=>false,'settings'=>[],'summary'=>[],'reviews'=>[]];?>
<?php if(!empty($sr['ready'])):$ss=$sr['settings'];$srs=$sr['summary'];$reviewCandidates=$canWrite?research_intelligence_strategic_review_candidate_reviewers($pdo,$u,$selected):[];$configuredReviewers=array_map(fn($x)=>(string)($x['user_id']??''),(array)($ss['reviewers']??[]));?>
<section class="intelligenceStrategicReviews">
<header><div><span class="eyebrow">PHASE 73 · RECURRING STRATEGIC REVIEW</span><h3>Frozen strategic review packets</h3><p>Each packet freezes Decision/execution state, Pattern Memory, Strategic Graph attention, and Portfolio signals, then sends that immutable packet through the existing Collaborative Review engine. Recurrence is evaluated only when the existing Portfolio cycle runs.</p></div><a href="/research-reviews.php">Open Review Center</a></header>
<section class="intelligencePortfolioOverview"><div><strong><?=h((string)($srs['total']??0))?></strong><span>Review packets</span></div><div><strong><?=h((string)($srs['open']??0))?></strong><span>Open</span></div><div><strong><?=h((string)($srs['completed']??0))?></strong><span>Completed</span></div><div><strong><?=h((string)($srs['overdue']??0))?></strong><span>Overdue</span></div><div><strong><?=h((string)($srs['unresolved_objections']??0))?></strong><span>Objections</span></div><div><strong><?=h((string)($srs['current_drift']??0))?></strong><span>Current drift</span></div></section>
<?php if($canWrite):?><div class="intelligencePortfolioColumns"><section><h4>Recurring review settings</h4><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="portfolio_id" value="<?=h((string)$selected['public_id'])?>"><input type="hidden" name="op" value="strategic_review_configure"><label>Status<select name="review_status"><option value="paused" <?=($ss['status']??'paused')==='paused'?'selected':''?>>Paused</option><option value="active" <?=($ss['status']??'')==='active'?'selected':''?>>Active</option></select></label><label>Cadence<select name="review_cadence"><?php foreach(research_intelligence_strategic_review_cadences() as $key=>$label):?><option value="<?=h($key)?>" <?=($ss['cadence']??'monthly')===$key?'selected':''?>><?=h($label)?></option><?php endforeach?></select></label><label>Review deadline after packet<input type="number" name="review_due_offset_hours" min="1" max="720" value="<?=h((string)($ss['due_offset_hours']??72))?>"> hours</label><fieldset><legend>Reviewers</legend><?php if(!$reviewCandidates):?><p class="meta">No other current collaborator is available in the Portfolio anchor Research project. Add a Team collaborator before activating recurring review.</p><?php endif?><?php foreach($reviewCandidates as $candidate):?><label><input type="checkbox" name="reviewer_ids[]" value="<?=h((string)$candidate['public_id'])?>" <?=in_array((string)$candidate['public_id'],$configuredReviewers,true)?'checked':''?>> <?=h((string)($candidate['display_name']?:$candidate['username']))?></label><?php endforeach?></fieldset><button>Save Strategic Review settings</button></form><p class="meta">This does not create another scheduler. Weekly/monthly/quarterly review cadence is checked only when the Portfolio's existing scheduled cycle runs.</p></section>
<section><h4>Manual Strategic Review</h4><?php if(!empty($ss['reviewers'])):?><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="portfolio_id" value="<?=h((string)$selected['public_id'])?>"><input type="hidden" name="op" value="strategic_review_create"><input type="hidden" name="idempotency_key" value="<?=h(ulid_like())?>"><p class="meta">Create an immutable packet now and send it to the configured reviewers through Collaborative Review.</p><button>Create Strategic Review now</button></form><?php else:?><p class="meta">Configure at least one reviewer before creating a Strategic Review packet.</p><?php endif?></section></div><?php endif?>
<div class="intelligenceDecisionList"><?php if(empty($sr['reviews'])):?><p class="meta">No Strategic Review packets yet.</p><?php else:?><?php foreach((array)$sr['reviews'] as $reviewPacket):$cr=$reviewPacket['review']??null;$agg=$reviewPacket['review_aggregate']??[];$focus=(array)($reviewPacket['packet']['state']['review_focus']??[]);?><article><div><strong><?=h((string)$reviewPacket['created_at'])?> · <?=h(strtoupper((string)$reviewPacket['trigger_type']))?></strong><small><?=h((string)count($focus))?> focus item(s) · <?=$reviewPacket['material_changed']?'material state changed':'same strategic state hash'?><?php if($cr):?> · <?=h(strtoupper((string)$cr['status']))?> · <?=h(str_replace('_',' ',(string)($agg['consensus']??'pending')))?><?php endif?></small><?php foreach(array_slice($focus,0,3) as $f):?><small><?=h(strtoupper((string)$f['severity']))?> · <?=h((string)$f['summary'])?></small><?php endforeach?></div><div><?php if($cr):?><a href="/research-reviews.php?id=<?=rawurlencode((string)$cr['public_id'])?>">Open review</a><?php endif?></div></article><?php endforeach?><?php endif?></div>
</section><?php endif?>
<?php $sb=$ops['strategic_briefings']??['ready'=>false,'summary'=>[],'briefings'=>[]];?>
<?php if(!empty($sb['ready'])):$sbs=$sb['summary'];?>
<section class="intelligenceStrategicBriefings">
<header><div><span class="eyebrow">PHASE 73 · EXECUTIVE STRATEGIC BRIEFINGS &amp; TEAM REVIEW</span><h3>Team-reviewed leadership briefings</h3><p>Strategic Briefings are normal Executive Briefing Research Docs rendered from a frozen Phase 73 strategic packet. The existing Collaborative Review engine governs Team Review, and Phase 59 remains the publication workflow.</p></div><a href="/research-reviews.php">Open Review Center</a></header>
<section class="intelligencePortfolioOverview"><div><strong><?=h((string)($sbs['total']??0))?></strong><span>Strategic briefings</span></div><div><strong><?=h((string)($sbs['open_review']??0))?></strong><span>Open Team Review</span></div><div><strong><?=h((string)($sbs['approved']??0))?></strong><span>Approved</span></div><div><strong><?=h((string)($sbs['overdue']??0))?></strong><span>Overdue</span></div><div><strong><?=h((string)($sbs['publication_ready']??0))?></strong><span>Publication ready</span></div><div><strong><?=h((string)($sbs['current_drift']??0))?></strong><span>Current drift</span></div></section>
<?php if($canWrite):?><section class="intelligencePortfolioActions"><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="portfolio_id" value="<?=h((string)$selected['public_id'])?>"><input type="hidden" name="op" value="strategic_briefing_create"><input type="hidden" name="idempotency_key" value="<?=h(ulid_like())?>"><input type="hidden" name="window_days" value="30"><label>Strategic source<select name="strategic_review_id"><option value="">Current strategic state</option><?php foreach((array)($sr['reviews']??[]) as $sourcePacket):?><option value="<?=h((string)$sourcePacket['public_id'])?>">Strategic Review · <?=h((string)$sourcePacket['created_at'])?> · <?=h(str_replace('_',' ',(string)($sourcePacket['review_aggregate']['consensus']??'awaiting_reviewers')))?></option><?php endforeach?></select></label><label>Briefing title<input name="title" maxlength="240" placeholder="Optional custom title"></label><p class="meta">Configured Strategic Review collaborators become the Team Reviewers. Publication is blocked until that document review is completed, current, and unanimously approved.</p><button>Create Executive Strategic Briefing</button></form></section><?php endif?>
<div class="intelligenceDecisionList"><?php if(empty($sb['briefings'])):?><p class="meta">No Executive Strategic Briefings yet.</p><?php else:?><?php foreach((array)$sb['briefings'] as $brief):$tr=$brief['team_review']??null;$ta=$brief['team_review_aggregate']??[];?><article><div><strong><?=h((string)$brief['title'])?></strong><small><?=h((string)$brief['created_at'])?><?php if($tr):?> · <?=h(strtoupper((string)$tr['status']))?> · <?=h(str_replace('_',' ',(string)($ta['consensus']??'awaiting_reviewers')))?><?php endif?><?=$brief['current_drift']?' · CURRENT STRATEGIC DRIFT':''?><?=$brief['publication_ready']?' · PUBLICATION READY':''?></small><small>Frozen strategic packet <?=h(substr((string)$brief['packet_hash'],0,12))?>…</small></div><div><a href="/home.php?doc=<?=rawurlencode((string)$brief['document_public_id'])?>">Open Research Doc</a><?php if($tr):?><a href="/research-reviews.php?id=<?=rawurlencode((string)$tr['public_id'])?>">Open Team Review</a><?php endif?><?php if(!empty($brief['publication_public_id'])):?><a href="/research-publications.php?workflow=<?=rawurlencode((string)$brief['publication_public_id'])?>">Open publication</a><?php endif?></div></article><?php endforeach?><?php endif?></div>
</section><?php endif?>
<?php $oc=$ops['organizational_cognition']??['ready'=>false,'summary'=>[],'signals'=>[],'analogues'=>[],'state_hash'=>''];?>
<?php if(!empty($oc['ready'])):$ocs=$oc['summary'];?>
<section class="intelligenceOrganizationalCognition">
<header><div><span class="eyebrow">PHASE 73 · ORGANIZATIONAL AGENT COGNITION &amp; GOVERNED FOLLOW-THROUGH</span><h3>Strategic organizational memory</h3><p>Deterministic reasoning across native Decisions, Action Plan execution, Outcome Memory, exact Pattern Memory, Strategic Graph relationships, Strategic Reviews, and Executive Strategic Briefings. The Agent can explain and propose follow-through; every write still requires the existing explicit confirmation and lifecycle gates.</p></div><a href="/home.php">Open Agent Chat</a></header>
<section class="intelligencePortfolioOverview"><div><strong><?=h((string)($ocs['signals']??0))?></strong><span>Cognition signals</span></div><div><strong><?=h((string)($ocs['critical']??0))?></strong><span>Critical</span></div><div><strong><?=h((string)($ocs['high']??0))?></strong><span>High</span></div><div><strong><?=h((string)($ocs['decision_reconsideration']??0))?></strong><span>Decision review</span></div><div><strong><?=h((string)($ocs['execution_follow_through']??0))?></strong><span>Execution follow-through</span></div><div><strong><?=h((string)($ocs['analogues']??0))?></strong><span>Decision analogues</span></div></section>
<p class="meta">Strategic state hash: <code><?=h((string)$oc['state_hash'])?></code>. Agent proposals generated from this state are rejected as stale if the underlying Portfolio changes before confirmation.</p>
<div class="intelligencePortfolioColumns">
<section><header><span class="eyebrow">GOVERNED REASONING</span><h4>Signals requiring judgment</h4></header><?php if(empty($oc['signals'])):?><p class="meta">No current organizational cognition signals require follow-through.</p><?php else:?><?php foreach(array_slice((array)$oc['signals'],0,20) as $signal):?><article class="intelligenceDecisionRow"><div><strong><?=h(strtoupper((string)$signal['severity']))?> · <?=h((string)$signal['title'])?></strong><small><?=h(str_replace('_',' ',(string)$signal['kind']))?> · <?=h((string)$signal['summary'])?></small><small><?=h((string)count((array)$signal['provenance']))?> provenance reference(s) · proposed path <?=h(str_replace('research.','',(string)($signal['recommended_capability']??'none')))?></small></div><div><?php if(($signal['object_type']??'')==='decision'):?><a href="/research-decisions.php?decision=<?=rawurlencode((string)$signal['object_id'])?>">Open Decision</a><?php elseif(($signal['object_type']??'')==='action_plan'):?><a href="/research-action-plans.php?action_plan=<?=rawurlencode((string)$signal['object_id'])?>">Open Action Plan</a><?php endif?></div></article><?php endforeach?><?php endif?></section>
<section><header><span class="eyebrow">EXACT DECISION ANALOGUES</span><h4>What happened in similar recorded situations</h4></header><p class="meta">These analogues come only from exact durable Pattern Memory shared across at least two native Decisions. No fuzzy matching or LLM-created membership.</p><?php if(empty($oc['analogues'])):?><p class="meta">No exact cross-Decision analogue currently meets the threshold.</p><?php else:?><?php foreach(array_slice((array)$oc['analogues'],0,16) as $analogue):?><article class="intelligenceDecisionRow"><div><strong><?=h((string)$analogue['label'])?></strong><small><?=h((string)$analogue['summary'])?></small><small><?=h((string)$analogue['decision_count'])?> Decisions · <?=h((string)$analogue['evidence_count'])?> evidence member(s)</small><?php foreach(array_slice((array)$analogue['decisions'],0,5) as $ad):?><small><?=h((string)$ad['title'])?> · <?=h(strtoupper((string)$ad['status']))?></small><?php endforeach?></div></article><?php endforeach?><?php endif?></section>
</div>
</section><?php endif?>
</section><?php endif?>
<section class="intelligencePortfolioActions"><?php if($canWrite):?><form method="post"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="portfolio_id" value="<?=h((string)$selected['public_id'])?>"><input type="hidden" name="op" value="snapshot"><label>Snapshot window<input type="number" name="window_days" min="1" max="365" value="30"></label><button>Create frozen snapshot</button></form><form method="post"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="portfolio_id" value="<?=h((string)$selected['public_id'])?>"><input type="hidden" name="op" value="briefing"><input type="hidden" name="window_days" value="30"><label>Briefing title<input name="title" maxlength="240" placeholder="Optional custom title"></label><button>Create Executive Briefing</button></form><?php endif?></section>
<section class="intelligenceBriefings"><header><span class="eyebrow">EXECUTIVE BRIEFINGS</span><h3>Living briefing documents</h3></header><?php if(!$selected['briefings']):?><div class="empty">No briefings yet.</div><?php endif?><?php foreach($selected['briefings'] as $b):?><article id="briefing-<?=h((string)$b['public_id'])?>"><div><strong><?=h((string)$b['title'])?></strong><small><?=h((string)$b['created_at'])?> · <?=h((string)$b['status'])?></small></div><div><a href="/home.php<?=!empty($b['conversation_public_id'])?'?agent='.rawurlencode((string)$b['conversation_public_id']).'&doc='.rawurlencode((string)$b['document_public_id']):''?>">Open Research Doc</a><?php if(!empty($b['publication_public_id'])):?><a href="/research-publications.php?workflow=<?=rawurlencode((string)$b['publication_public_id'])?>">Open publication workflow</a><?php elseif($canWrite):?><form method="post"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="portfolio_id" value="<?=h((string)$selected['public_id'])?>"><input type="hidden" name="op" value="prepare_publication"><input type="hidden" name="briefing_id" value="<?=h((string)$b['public_id'])?>"><input type="hidden" name="required_approvals" value="1"><button class="linkButton">Send to Phase 59 review</button></form><?php endif?><form method="post"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="portfolio_id" value="<?=h((string)$selected['public_id'])?>"><input type="hidden" name="op" value="acknowledge"><input type="hidden" name="briefing_id" value="<?=h((string)$b['public_id'])?>"><button class="linkButton">Acknowledge</button></form></div></article><?php endforeach?></section>
</section><?php endif?>
<?php endif?>
</main></body></html>