<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';$u=require_user($pdo);header('Cache-Control: private, no-store');$q=$pdo->prepare("SELECT DISTINCT rp.public_id,rp.title,rp.updated_at FROM research_projects rp LEFT JOIN team_members tm ON tm.team_id=rp.team_id AND tm.user_id=? WHERE rp.status='active' AND (rp.owner_user_id=? OR tm.user_id=?) ORDER BY rp.updated_at DESC LIMIT 80");$q->execute([$u['id'],$u['id'],$u['id']]);$projects=[];
foreach($q->fetchAll() as $p){$integrity=provenance_ready($pdo)?provenance_project_report_integrity($pdo,$u,(string)$p['public_id']):['total'=>0,'valid'=>0,'invalid'=>0];$receipts=provenance_ready($pdo)?provenance_receipts($pdo,$u,(string)$p['public_id'],10):[];$projects[]=['project'=>$p,'integrity'=>$integrity,'receipts'=>$receipts];}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Audit Ledger · Annotated</title><meta name="robots" content="noindex,nofollow"><link rel="stylesheet" href="/assets/css/app.css"></head><body>
<header class="topbar"><a class="brand" href="/home.php">Annotated</a><nav><a href="/research-portfolio.php">Portfolio</a><a href="/research-network.php">Network</a><a href="/research.php">Research</a></nav></header>
<main class="auditHubLayout"><section><div class="pageTitle"><span class="eyebrow">PHASE 26 · AUDIT LEDGER</span><h1>Research Audit Ledger</h1><p>Open deterministic project provenance, verify immutable report snapshot hashes, and create or revisit your audit receipts. No project receives a trust score.</p></div>
<?php if(!provenance_ready($pdo)):?><div class="card empty">Run migration 033 to enable the Audit Ledger.</div><?php endif?>
<div class="auditProjectList"><?php foreach($projects as $row):$p=$row['project'];$i=$row['integrity'];?><article class="card auditProjectCard <?=$i['invalid']?'provenanceInvalid':''?>"><div><span class="eyebrow">RESEARCH PROJECT</span><h2><?=h((string)$p['title'])?></h2><p class="meta"><?=h((string)$i['valid'])?> verified report snapshot<?=((int)$i['valid']===1?'':'s')?> · <?=h((string)$i['invalid'])?> mismatch<?=((int)$i['invalid']===1?'':'es')?> · <?=h((string)count($row['receipts']))?> recent receipt<?=count($row['receipts'])===1?'':'s'?></p></div><div class="inlineActions"><a href="/research-provenance.php?id=<?=h((string)$p['public_id'])?>">Open provenance</a><a href="/research-project.php?id=<?=h((string)$p['public_id'])?>">Project</a></div></article><?php endforeach?></div>
</section><aside><div class="card stickyProvenanceRail"><h3>Audit semantics</h3><p class="meta">Verified means a stored immutable snapshot or audit receipt matches its recomputed SHA-256. It is an integrity statement, not a judgment about whether a conclusion is true.</p></div></aside></main></body></html>