<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';$u=require_user($pdo);$id=trim((string)($_GET['id']??$_POST['id']??''));$project=$id!==''?project_access($pdo,(int)$u['id'],$id):null;$success='';$error='';
if($id!==''&&!$project){http_response_code(404);exit('Research project not found.');}
if($_SERVER['REQUEST_METHOD']==='POST'&&$project){require_csrf();try{$pack=research_evidence_pack_create($pdo,$u,$project['public_id'],(string)($_POST['scope_type']??'project'),trim((string)($_POST['scope_id']??'')));header('Location:/research-evidence-pack.php?pack='.rawurlencode((string)$pack['public_id']));exit;}catch(Throwable $e){$error=$e->getMessage();}}
if($project){$packs=research_evidence_pack_list($pdo,$u,$project['public_id'],120,false);$canWrite=in_array((string)($project['access_role']??''),['owner','admin','researcher'],true);}
else{$q=$pdo->prepare("SELECT DISTINCT rp.public_id,rp.title,rp.updated_at FROM research_projects rp LEFT JOIN team_members tm ON tm.team_id=rp.team_id AND tm.user_id=? WHERE rp.owner_user_id=? OR tm.user_id=? ORDER BY rp.updated_at DESC LIMIT 80");$q->execute([$u['id'],$u['id'],$u['id']]);$projects=$q->fetchAll();}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Evidence Packs · Annotated</title><meta name="robots" content="noindex,nofollow"><link rel="stylesheet" href="/assets/css/app.css"></head><body>
<header class="topbar"><a class="brand" href="/home.php">Annotated</a><nav><?php if($project):?><a href="/research-project.php?id=<?=h($project['public_id'])?>">Project</a><a href="/research-verification.php?id=<?=h($project['public_id'])?>">Verification</a><a href="/research-provenance.php?id=<?=h($project['public_id'])?>">Provenance</a><?php endif?><a href="/research.php">Research</a></nav></header>
<?php if(!$project):?><main class="evidencePackHub"><section><div class="pageTitle"><span class="eyebrow">PHASE 28 · REPRODUCIBILITY</span><h1>Evidence Packs</h1><p>Freeze the exact permission-scoped evidence, verification and provenance state behind Research so another project member can replay what was known at that point in time.</p></div><div class="evidencePackList"><?php foreach($projects as $p):?><article class="card evidencePackProject"><div><div class="meta">UPDATED <?=h((string)$p['updated_at'])?></div><h2><?=h((string)$p['title'])?></h2></div><a class="button" href="/research-evidence-packs.php?id=<?=h((string)$p['public_id'])?>">Open packs</a></article><?php endforeach?></div></section><aside class="stickyEvidencePackRail"><div class="card"><h3>Immutable, not authoritative</h3><p class="meta">A pack is a frozen replay record. Current Research remains authoritative and may legitimately move on after the pack was created.</p></div></aside></main>
<?php else:?><main class="evidencePackLayout"><section><div class="pageTitle"><span class="eyebrow">PHASE 28 · EVIDENCE PACKS</span><h1><?=h((string)$project['title'])?></h1><p>Create a frozen reproducibility package for the Project, a Claim, Finding, or immutable Report Version. Each pack receives a canonical SHA-256 manifest and never changes after creation.</p></div><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?>
<div class="evidencePackList"><?php foreach($packs as $p):?><article class="card evidencePackCard"><div><div class="meta"><?=h(strtoupper(str_replace('_',' ',(string)$p['scope_type'])))?> · <?=h((string)$p['scope_public_id'])?> · <?=h((string)$p['created_at'])?></div><h2><a href="/research-evidence-pack.php?pack=<?=h((string)$p['public_id'])?>">Evidence Pack <?=h((string)$p['public_id'])?></a></h2><p class="meta">SHA-256 <?=h((string)$p['manifest_hash'])?></p><div class="inlineActions"><span class="badge"><?=$p['stored_hash_valid']?'Manifest verified':'Hash mismatch'?></span><span class="badge">Open to compare current Research</span></div></div><a class="button secondary" href="/research-evidence-pack.php?pack=<?=h((string)$p['public_id'])?>">Replay / compare</a></article><?php endforeach?><?php if(!$packs):?><div class="card empty">No Evidence Packs yet.</div><?php endif?></div></section>
<aside class="stickyEvidencePackRail"><?php if($canWrite):?><div class="card"><h3>Create Evidence Pack</h3><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="id" value="<?=h((string)$project['public_id'])?>"><label>Scope<select name="scope_type"><option value="project">Whole project</option><option value="claim">Claim</option><option value="finding">Finding</option><option value="report_version">Report version</option></select></label><label>Scope ID<input name="scope_id" placeholder="Leave blank for project"></label><button>Create immutable pack</button></form></div><?php endif?><div class="card"><h3>What gets frozen?</h3><p class="meta">Exact Source Versions, Annotations, Claims, Findings, report snapshots/citations, verification events and provenance relevant to the selected scope. No live page text is fetched during replay.</p></div></aside></main><?php endif?></body></html>
