<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';$viewer=current_user($pdo);$id=(string)($_GET['id']??'');$report=research_report_access($pdo,$id,$viewer);if(!$report){http_response_code(404);exit('Research report not found.');}
$versions=living_research_version_rows($pdo,$report);$current=(int)$report['version_number'];$from=(int)($_GET['from']??max(1,$current-1));$to=(int)($_GET['to']??$current);$error='';$diff=null;
try{if($current<2)throw new RuntimeException('This report has only one published version.');$diff=living_research_version_diff($pdo,$report,$viewer,$from,$to);}catch(Throwable $e){$error=$e->getMessage();}
function living_diff_label(string $section,array $item): string {
 return match($section){'sources'=>(string)($item['title']??$item['url']??$item['id']),'claims'=>(string)($item['statement']??$item['id']),'findings'=>(string)($item['title']??$item['id']),'entities'=>(string)($item['name']??$item['id']),default=>(string)($item['id']??'Item')};
}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Report Version Diff · Annotated</title><meta name="robots" content="noindex,nofollow"><link rel="stylesheet" href="/assets/css/app.css"></head><body>
<header class="topbar"><a class="brand" href="/">Annotated</a><nav><a href="/research-report.php?id=<?=h($report['public_id'])?>">Current report</a><?php if($viewer):?><a href="/research-publications.php">Living Research</a><?php endif?></nav></header>
<main class="livingDiffLayout"><section><div class="pageTitle"><span class="eyebrow">LIVING RESEARCH · VERSION DIFF</span><h1><?=h((string)$report['title'])?></h1><p>Compare immutable publication snapshots. This view describes what changed between versions; it does not rewrite either version.</p></div>
<form method="get" class="card livingDiffControls"><input type="hidden" name="id" value="<?=h($report['public_id'])?>"><label>From<select name="from"><?php foreach(array_reverse($versions) as $v):?><option value="<?=h((string)$v['version_number'])?>" <?=$from===(int)$v['version_number']?'selected':''?>>Version <?=h((string)$v['version_number'])?></option><?php endforeach?></select></label><label>To<select name="to"><?php foreach(array_reverse($versions) as $v):?><option value="<?=h((string)$v['version_number'])?>" <?=$to===(int)$v['version_number']?'selected':''?>>Version <?=h((string)$v['version_number'])?></option><?php endforeach?></select></label><button>Compare</button></form>
<?php if($error):?><div class="error"><?=h($error)?></div><?php elseif($diff):?>
<div class="livingDiffSummary"><div class="card"><strong><?=h((string)$diff['totals']['added'])?></strong><span>Added</span></div><div class="card"><strong><?=h((string)$diff['totals']['removed'])?></strong><span>Removed</span></div><div class="card"><strong><?=h((string)$diff['totals']['changed'])?></strong><span>Changed</span></div><div class="card"><strong>v<?=h((string)$from)?> → v<?=h((string)$to)?></strong><span>Immutable snapshots</span></div></div>
<?php foreach($diff['sections'] as $section=>$data):?><section class="livingDiffSection"><div class="sectionHeadWeb"><div><span class="eyebrow"><?=h(strtoupper($section))?></span><h2><?=h(ucfirst($section))?></h2></div><span class="meta"><?=h((string)array_sum($data['counts']))?> change(s)</span></div>
<?php if(array_sum($data['counts'])===0):?><div class="card empty">No <?=h($section)?> changes between these versions.</div><?php endif?>
<?php foreach($data['added'] as $item):?><article class="card livingDiffItem"><span class="badge">Added</span><h3><?=h(mb_substr(living_diff_label($section,$item),0,400))?></h3><p class="meta"><?=h((string)($item['id']??''))?></p></article><?php endforeach?>
<?php foreach($data['removed'] as $item):?><article class="card livingDiffItem"><span class="badge">Removed</span><h3><?=h(mb_substr(living_diff_label($section,$item),0,400))?></h3><p class="meta"><?=h((string)($item['id']??''))?></p></article><?php endforeach?>
<?php foreach($data['changed'] as $item):?><article class="card livingDiffItem"><span class="badge">Changed</span><h3><?=h(mb_substr(living_diff_label($section,$item['after']),0,400))?></h3><p>Changed fields: <?=h(implode(', ',$item['fields']))?></p><p class="meta"><?=h((string)$item['id'])?></p></article><?php endforeach?>
</section><?php endforeach?>
<?php endif?></section>
<aside><div class="card stickyLivingRail"><h3>Version integrity</h3><p class="meta">Version <?=h((string)$from)?> and version <?=h((string)$to)?> remain immutable. The diff is derived from their stored snapshots each time you open this page.</p><?php if($diff):?><p><a href="/research-report.php?id=<?=h($report['public_id'])?>&v=<?=h((string)$from)?>">Open v<?=h((string)$from)?></a><br><a href="/research-report.php?id=<?=h($report['public_id'])?>&v=<?=h((string)$to)?>">Open v<?=h((string)$to)?></a></p><?php endif?></div></aside>
</main></body></html>