<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';$u=require_user($pdo);header('Cache-Control: private, no-store');header('Vary: Cookie');$ready=living_research_ready($pdo);$subscriptions=$ready?living_research_subscribed_reports($pdo,$u,100):[];$managed=$ready?living_research_managed_reports($pdo,$u,100):[];$topics=$ready?living_research_public_topics($pdo,40):[];
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Living Research · Annotated</title><meta name="robots" content="noindex,nofollow"><link rel="stylesheet" href="/assets/css/app.css"></head><body>
<header class="topbar"><a class="brand" href="/home.php">Annotated</a><nav><a href="/research-portfolio.php">Portfolio</a><a href="/research.php">Research</a><a href="/research-topic.php">Public Topics</a></nav></header>
<main class="livingHubLayout"><section><div class="pageTitle"><span class="eyebrow">PHASE 24 · LIVING RESEARCH</span><h1>Living Research</h1><p>Follow published Research, see when an immutable new version appears, compare what changed, and manage publications that may need a deliberate update after upstream evidence changes.</p></div>
<?php if(!$ready):?><div class="card empty"><h2>Living Research needs migration 031.</h2><?php if(($u['role']??'')==='admin'):?><a class="button" href="/upgrade.php">Run database upgrade</a><?php endif?></div><?php else:?>
<section class="livingHubSection"><div class="sectionHeadWeb"><div><span class="eyebrow">FOLLOWING</span><h2>Reports you follow</h2></div><span class="badge"><?=h((string)count($subscriptions))?></span></div>
<?php if(!$subscriptions):?><div class="card empty">You are not following any Research reports yet. Open an accessible report and choose <strong>Follow updates</strong>.</div><?php endif?>
<div class="livingReportGrid"><?php foreach($subscriptions as $r):$rs=$r['read_status'];?><article class="card livingHubCard"><div class="livingReportBadges"><?php if($rs['updated_since_read']):?><span class="badge">Updated since you read</span><?php endif?><span class="badge">v<?=h((string)$r['version_number'])?></span><span class="badge"><?=h(strtoupper((string)$r['visibility']))?></span></div><h3><a href="/research-report.php?id=<?=h((string)$r['public_id'])?>"><?=h((string)$r['title'])?></a></h3><?php if(!empty($r['summary'])):?><p><?=h(mb_substr((string)$r['summary'],0,400))?></p><?php endif?><div class="publicationTopics"><?php foreach($r['topics'] as $t):?><a class="badge" href="/research-topic.php?topic=<?=h((string)$t['topic_slug'])?>"><?=h((string)$t['topic_label'])?></a><?php endforeach?></div><?php if($rs['updated_since_read']&&$rs['last_read_version']):?><p><a href="/research-report-diff.php?id=<?=h((string)$r['public_id'])?>&from=<?=h((string)$rs['last_read_version'])?>&to=<?=h((string)$r['version_number'])?>">See what changed since v<?=h((string)$rs['last_read_version'])?></a></p><?php endif?><p class="meta">Published <?=h((string)$r['published_at'])?></p></article><?php endforeach?></div></section>
<section class="livingHubSection"><div class="sectionHeadWeb"><div><span class="eyebrow">PUBLISHER</span><h2>Reports you manage</h2></div><span class="badge"><?=h((string)count($managed))?></span></div>
<?php if(!$managed):?><div class="card empty">No currently published reports are managed by you.</div><?php endif?>
<div class="livingReportGrid"><?php foreach($managed as $r):?><article class="card livingHubCard <?=$r['staleness']?'livingHubStale':''?>"><div class="livingReportBadges"><span class="badge">v<?=h((string)$r['version_number'])?></span><span class="badge"><?=h(strtoupper((string)$r['visibility']))?></span><?php if($r['staleness']):?><span class="badge">Review recommended</span><?php endif?></div><h3><a href="/research-report.php?id=<?=h((string)$r['public_id'])?>"><?=h((string)$r['title'])?></a></h3><p class="meta"><?=h((string)$r['subscriber_count'])?> follower<?=((int)$r['subscriber_count']===1?'':'s')?> · published <?=h((string)$r['published_at'])?></p><div class="publicationTopics"><?php foreach($r['topics'] as $t):?><a class="badge" href="/research-topic.php?topic=<?=h((string)$t['topic_slug'])?>"><?=h((string)$t['topic_label'])?></a><?php endforeach?></div><?php if($r['staleness']):?><p><strong>Upstream evidence changed after publication.</strong> <?=h((string)$r['staleness']['source_title'])?> changed <?=h((string)$r['staleness']['created_at'])?>.</p><a href="/research-impact.php?event=<?=h((string)$r['staleness']['event_id'])?>&project=<?=h((string)$r['project_public_id'])?>">Review impact</a> · <?php endif?><a href="/research-publish.php?id=<?=h((string)$r['project_public_id'])?>">Manage publication</a></article><?php endforeach?></div></section>
<?php endif?></section>
<aside><div class="card stickyLivingRail"><h3>Public topics</h3><?php if(!$topics):?><p class="meta">No public report topics yet.</p><?php endif?><?php foreach(array_slice($topics,0,18) as $t):?><p><a href="/research-topic.php?topic=<?=h((string)$t['topic_slug'])?>"><?=h((string)$t['topic_label'])?></a><br><span class="meta"><?=h((string)$t['report_count'])?> public report<?=((int)$t['report_count']===1?'':'s')?></span></p><?php endforeach?><a href="/research-topic.php">Browse all topics</a></div></aside></main></body></html>