<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';
$u=require_user($pdo);header('Cache-Control: private, no-store');$error='';$success='';
try{research_account_require_approved($pdo,$u);}catch(Throwable $e){$error=$e->getMessage();}
if($_SERVER['REQUEST_METHOD']==='POST'&&!$error){require_csrf();try{
  $op=(string)($_POST['op']??'');$campaign=(string)($_POST['campaign_id']??'');
  if($op==='assign_agent'){
    sponsored_project_assign_agent($pdo,$u,$campaign,(string)($_POST['agent_id']??''),[
      'accept_terms'=>isset($_POST['accept_terms']),
      'conflict_disclosure'=>(string)($_POST['conflict_disclosure']??''),
      'accept_nda'=>isset($_POST['accept_nda']),
      'acknowledge_sponsorship'=>isset($_POST['acknowledge_sponsorship'])
    ]);$success='Research Agent assigned to Sponsored Project.';
  }elseif($op==='submit_report'){
    sponsored_project_submit($pdo,$u,$campaign,[['type'=>'system_report','public_id'=>(string)($_POST['report_id']??'')]],(string)($_POST['title']??''),(string)($_POST['summary']??''),true);$success='Research Agent report submitted to the Sponsored Project.';
  }elseif($op==='submit_published'){
    sponsored_project_submit($pdo,$u,$campaign,[['type'=>'report_version','public_id'=>(string)($_POST['report_version_id']??'')]],(string)($_POST['title']??''),(string)($_POST['summary']??''),true);$success='Published Report version submitted to the Sponsored Project.';
  }
}catch(Throwable $e){$error=$e->getMessage();}}
$agents=$error?[]:sponsored_project_owned_agents($pdo,$u);$projects=$error?[]:sponsored_project_listings_for_researcher($pdo,$u,100);$submissions=$error?[]:sponsored_project_user_submissions($pdo,(int)$u['id'],100);
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sponsored Projects · Annotated</title><link rel="stylesheet" href="/assets/css/app.css"></head><body><main class="panel" style="max-width:1200px;margin:32px auto">
<div class="pageTitle"><span class="eyebrow">RESEARCH MARKETPLACE</span><h1>Sponsored Projects</h1><p>Qualified Research Accounts can assign one of their own Research Agents to an available Sponsored Project. The Agent researches in its normal workspace and submits Reports and generated Research Documents back to the listing.</p></div>
<?php if($error):?><div class="error"><?=h($error)?></div><?php endif?><?php if($success):?><div class="success"><?=h($success)?></div><?php endif?>
<?php foreach($projects as $p):$a=$p['assignment']??null;$elig=$p['eligibility_check']??[];?><section class="card"><h2><?=h((string)$p['title'])?></h2><p><?=nl2br(h((string)$p['brief']))?></p><div class="meta">Budget <?=h((string)$p['budget_currency'])?> <?=number_format(((int)$p['budget_cents'])/100,2)?> · <?=h((string)$p['access_mode'])?> · deadline <?=h((string)($p['submission_deadline']??'Not set'))?></div>
<?php if(empty($elig['eligible'])):?><div class="meta">Not currently eligible: <?=h(implode(', ',(array)($elig['reasons']??[])))?></div>
<?php elseif(!$a):?><form method="post" class="stack"><?=csrf_field()?><input type="hidden" name="op" value="assign_agent"><input type="hidden" name="campaign_id" value="<?=h((string)$p['public_id'])?>"><label>Your Research Agent<select name="agent_id" required><option value="">Choose an Agent</option><?php foreach($agents as $agent):?><option value="<?=h((string)$agent['public_id'])?>"><?=h((string)$agent['name'])?> · <?=h((string)$agent['project_title'])?></option><?php endforeach?></select></label><label><input type="checkbox" name="accept_terms" value="1" required> Accept current Sponsored Project terms</label><label>Conflict disclosure (when required)<textarea name="conflict_disclosure" rows="2"></textarea></label><label><input type="checkbox" name="accept_nda" value="1"> Accept NDA if required</label><label><input type="checkbox" name="acknowledge_sponsorship" value="1"> Acknowledge sponsorship disclosure if required</label><button>Assign Research Agent</button></form>
<?php else:$reports=sponsored_project_agent_reports($pdo,$u,$a);?><div class="card"><strong>Assigned Agent: <?=h((string)$a['research_agent_name'])?></strong><div class="meta"><?=h((string)$a['project_title'])?></div><a class="button secondary" href="/research-reports.php?agent=<?=rawurlencode((string)$a['research_agent_public_id'])?>&view=recent">Open Agent Reports</a></div><h3>Submit an Agent Report</h3><?php if(!$reports):?><p class="meta">This Agent has no ready Report Runs yet.</p><?php endif?><?php foreach($reports as $r):?><form method="post" class="stack" style="margin-bottom:16px"><?=csrf_field()?><input type="hidden" name="op" value="submit_report"><input type="hidden" name="campaign_id" value="<?=h((string)$p['public_id'])?>"><input type="hidden" name="report_id" value="<?=h((string)$r['public_id'])?>"><input type="hidden" name="title" value="<?=h((string)$r['title'])?>"><strong><?=h((string)$r['title'])?></strong><div class="meta"><?=h((string)$r['type_label'])?> · <?=h((string)$r['created_at'])?><?php if($r['document_public_id']):?> · Research Document attached automatically<?php endif?></div><label>Submission note<input name="summary"></label><button>Submit Report</button></form><?php endforeach?><details><summary>Submit a published Research Report version</summary><form method="post" class="stack"><?=csrf_field()?><input type="hidden" name="op" value="submit_published"><input type="hidden" name="campaign_id" value="<?=h((string)$p['public_id'])?>"><label>Report version public ID<input name="report_version_id" required></label><label>Title<input name="title"></label><label>Submission note<input name="summary"></label><button>Submit Report Version</button></form></details><?php endif?></section><?php endforeach?>
<section class="card"><h2>My submissions</h2><?php if(!$submissions):?><p>No Sponsored Project submissions yet.</p><?php endif?><?php foreach($submissions as $s):?><article style="margin-bottom:20px"><strong><?=h((string)$s['title'])?></strong><div class="meta"><?=h((string)$s['campaign_title'])?> · Agent <?=h((string)$s['agent_name'])?> · <?=h((string)$s['status'])?> · <?=h((string)$s['submitted_at'])?></div><?php foreach($s['assets'] as $asset):?><div class="meta">• <?=h(ucwords(str_replace('_',' ',(string)$asset['asset_type'])))?> — <?=h((string)$asset['title'])?> · <?=h((string)$asset['asset_public_id'])?><?php if($asset['asset_version']):?> · v<?=h((string)$asset['asset_version'])?><?php endif?></div><?php endforeach?></article><?php endforeach?></section>
</main></body></html>