<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';$viewer=current_user($pdo);$id=(string)($_GET['id']??'');$report=research_report_access($pdo,$id,$viewer);if(!$report){http_response_code(404);exit('Research report not found.');}$version=(int)($_GET['v']??$report['version_number']);$row=research_report_version_access($pdo,$report,$version,$viewer);if(!$row){http_response_code(404);exit('Report version not found.');}$snapshot=json_decode((string)$row['snapshot_json'],true);if(!is_array($snapshot)){http_response_code(500);exit('Invalid report snapshot.');}$computed=hash('sha256',(string)$row['snapshot_json']);$valid=hash_equals((string)$row['snapshot_hash'],$computed);$network=research_network_ready($pdo)?research_network_report_network($pdo,$viewer,$report,$version):['counts'=>['references'=>0,'cited_by'=>0,'updates'=>0]];
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Report Provenance · Annotated</title><meta name="robots" content="<?=($report['visibility']==='public'?'index,follow':'noindex,nofollow')?>"><link rel="stylesheet" href="/assets/css/app.css"></head><body>
<header class="topbar"><a class="brand" href="/">Annotated</a><nav><a href="/research-report.php?id=<?=h($report['public_id'])?>&v=<?=h((string)$version)?>">Report</a><a href="/research-report-network.php?id=<?=h($report['public_id'])?>&v=<?=h((string)$version)?>">Citation Network</a></nav></header>
<main class="reportProvenanceLayout"><section><div class="pageTitle"><span class="eyebrow">REPORT PROVENANCE · IMMUTABLE VERSION <?=h((string)$version)?></span><h1><?=h((string)$row['title'])?></h1><p>Verify the stored immutable report snapshot and inspect the provenance identifiers published inside it. This page does not expose private Research state beyond this accessible report version.</p></div>
<div class="card provenanceIntegrity <?=$valid?'provenanceValid':'provenanceInvalid'?>"><span class="eyebrow">SNAPSHOT SHA-256</span><h2><?=h((string)$row['snapshot_hash'])?></h2><p><strong><?=$valid?'Snapshot hash verifies.':'SNAPSHOT HASH MISMATCH.'?></strong></p><p class="meta">Computed SHA-256: <?=h($computed)?></p></div>
<div class="provenanceSummary"><div class="card"><strong><?=h((string)count($snapshot['sources']??[]))?></strong><span>Sources</span></div><div class="card"><strong><?=h((string)count($snapshot['claims']??[]))?></strong><span>Claims</span></div><div class="card"><strong><?=h((string)count($snapshot['findings']??[]))?></strong><span>Findings</span></div><div class="card"><strong><?=h((string)count($snapshot['entities']??[]))?></strong><span>Entities</span></div><div class="card"><strong><?=h((string)($network['counts']['references']??0))?></strong><span>Report citations</span></div><div class="card"><strong><?=h((string)($network['counts']['cited_by']??0))?></strong><span>Cited by</span></div></div>
<h2>Published Source provenance</h2><?php if(empty($snapshot['sources'])):?><div class="card empty">No Sources published in this version.</div><?php endif?><?php foreach(($snapshot['sources']??[]) as $s):?><article class="card"><div class="meta"><?=h((string)$s['id'])?> · SOURCE VERSION <?=h((string)($s['version']??'?'))?></div><h3><?=h((string)($s['title']?:$s['url']))?></h3><p class="meta">Recorded content hash: <?=h((string)($s['content_hash']??'not recorded'))?></p><a href="/source.php?id=<?=h((string)$s['id'])?>">Open Source</a></article><?php endforeach?>
<h2>Published Research identifiers</h2><div class="provenanceGrid"><div class="card"><h3>Claims</h3><?php foreach(($snapshot['claims']??[]) as $c):?><p><code><?=h((string)$c['id'])?></code><br><span class="meta"><?=h(strtoupper((string)$c['status']))?> · <?=h(mb_substr((string)$c['statement'],0,180))?></span></p><?php endforeach?></div><div class="card"><h3>Findings</h3><?php foreach(($snapshot['findings']??[]) as $f):?><p><code><?=h((string)$f['id'])?></code><br><span class="meta"><?=h((string)$f['title'])?></span></p><?php endforeach?></div></div>
</section><aside><div class="card stickyProvenanceRail"><h3>Verification boundary</h3><p class="meta">Annotated recomputes this report snapshot hash from the exact stored JSON. Source content hashes are displayed as recorded values and are not represented here as independently recomputed.</p><a href="/research-report-network.php?id=<?=h($report['public_id'])?>&v=<?=h((string)$version)?>">Open citation network</a></div></aside></main></body></html>