<?php
declare(strict_types=1);require __DIR__.'/app/bootstrap.php';require_once __DIR__.'/app/public-discovery.php';require_once __DIR__.'/app/annotation-ui.php';require_once __DIR__.'/app/ai.php';require_once __DIR__.'/app/ai-access.php';require_once __DIR__.'/app/research-workspace.php';$u=require_user($pdo);$id=(string)($_GET['id']??$_POST['id']??'');$project=project_access($pdo,(int)$u['id'],$id);if(!$project){http_response_code(404);exit('Research project not found.');}$canWrite=project_can_write($project);$success='';$error='';$aiAnswer='';
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();$op=(string)($_POST['op']??'');try{
 if(!$canWrite)throw new RuntimeException('You have view-only access to this project.');
 if($op==='add_source'){$url=trim((string)($_POST['url']??''));if(!filter_var($url,FILTER_VALIDATE_URL))throw new RuntimeException('Enter a valid source URL.');$s=ensure_source($pdo,$url,trim((string)($_POST['title']??''))?:null);$pdo->prepare('INSERT IGNORE INTO project_sources(project_id,source_id,added_by_user_id) VALUES(?,?,?)')->execute([$project['id'],$s['id'],$u['id']]);$pdo->prepare("INSERT INTO source_monitor_jobs(source_id,priority,status) SELECT ?,3,'queued' WHERE NOT EXISTS(SELECT 1 FROM source_monitor_jobs WHERE source_id=? AND status IN ('queued','processing'))")->execute([$s['id'],$s['id']]);$success='Source added and queued for integrity capture.';}
 if($op==='note'){$body=trim((string)($_POST['body']??''));if($body==='')throw new RuntimeException('Note cannot be empty.');$pdo->prepare('INSERT INTO research_notes(public_id,project_id,user_id,body) VALUES(?,?,?,?)')->execute([ulid_like(),$project['id'],$u['id'],$body]);$success='Research note added.';}
 if($op==='task'){$title=trim((string)($_POST['title']??''));if($title==='')throw new RuntimeException('Task title is required.');$type=in_array($_POST['task_type']??'general',['general','find_source','verify_claim','review_source_change'],true)?$_POST['task_type']:'general';$pdo->prepare('INSERT INTO research_tasks(public_id,project_id,created_by_user_id,title,description,task_type) VALUES(?,?,?,?,?,?)')->execute([ulid_like(),$project['id'],$u['id'],$title,trim((string)($_POST['description']??''))?:null,$type]);$success='Research task added.';}
 if($op==='task_status'){$task=(string)($_POST['task']??'');$status=in_array($_POST['status']??'open',['open','in_progress','done','archived'],true)?$_POST['status']:'open';$pdo->prepare('UPDATE research_tasks SET status=? WHERE public_id=? AND project_id=?')->execute([$status,$task,$project['id']]);$success='Task updated.';}
 if($op==='ask_ai'){
   if(!user_is_pro($pdo,$u))throw new RuntimeException('Ask Annotated is available to Pro users.');$isAdmin=($u['role']??'')==='admin';$quota=rate_limit_consume($pdo,$isAdmin?'ai-admin':'ai-pro','user:'.(string)$u['id'],$isAdmin?240:40,3600);if(!$quota['allowed'])throw new RuntimeException('AI request limit reached. Try again in about '.max(1,(int)ceil($quota['retry_after']/60)).' minute(s).');$question=trim((string)($_POST['question']??''));if($question==='')throw new RuntimeException('Ask a research question.');$model=ai_setting_model_id($pdo,'research',true);if(!$model)$model=ai_setting_model_id($pdo,'pro',true);if(!$model)throw new RuntimeException('No Pro research model is configured.');ai_interactive_model_record($pdo,$u,$model);$ctx=ai_research_context($pdo,(int)$project['id']);$system='You are Ask Annotated, a provenance-first research assistant. Use only the supplied project context. Separate source evidence from inference. Cite exact IDs like [SOURCE id] and [ANNOTATION id]. If the context cannot answer the question, say what evidence is missing. Never invent citations.';$prompt="Project: {$project['title']}\nQuestion: {$question}\n\nPROJECT CONTEXT:\n".$ctx['text'];$r=ai_run($pdo,$config,$u,$isAdmin?'admin':'pro','research_question',$model,$system,$prompt,array_merge($ctx['refs'],[['type'=>'question','text'=>$question]]),'research_project',$project['public_id']);$aiAnswer=$r['text'];
 }
 if(in_array($op,['add_source','note','task','task_status'],true)&&$success!==''&&research_workspace_ready($pdo))research_workspace_queue($pdo,(int)$project['id'],3);
}catch(Throwable $e){$error=$e->getMessage();}}
$q=$pdo->prepare('SELECT s.public_id,s.title,s.canonical_url,s.domain,s.status,s.last_checked_at,ps.created_at FROM project_sources ps JOIN sources s ON s.id=ps.source_id WHERE ps.project_id=? ORDER BY ps.created_at DESC');$q->execute([$project['id']]);$sources=$q->fetchAll();$q=$pdo->prepare("SELECT a.public_id FROM project_annotations pa JOIN annotations a ON a.id=pa.annotation_id WHERE pa.project_id=? ORDER BY pa.created_at DESC");$q->execute([$project['id']]);$annotations=[];foreach($q->fetchAll(PDO::FETCH_COLUMN) as $aid){$row=public_discovery_annotation($pdo,(string)$aid,$u);if($row)$annotations[]=$row;}$q=$pdo->prepare('SELECT rn.*,u2.display_name FROM research_notes rn JOIN users u2 ON u2.id=rn.user_id WHERE rn.project_id=? ORDER BY rn.created_at DESC');$q->execute([$project['id']]);$notes=$q->fetchAll();$q=$pdo->prepare('SELECT * FROM research_tasks WHERE project_id=? ORDER BY FIELD(status,\'open\',\'in_progress\',\'done\',\'archived\'),created_at DESC');$q->execute([$project['id']]);$tasks=$q->fetchAll();$q=$pdo->prepare("SELECT output_text,created_at FROM ai_runs WHERE scope_type='research_project' AND scope_public_id=? AND status='completed' ORDER BY created_at DESC LIMIT 5");$q->execute([$project['public_id']]);$aiRuns=$q->fetchAll();
$workspaceReady=research_workspace_ready($pdo);$workspaceAiAvailable=$workspaceReady&&research_workspace_ai_model_configured($pdo);$workspaceSnapshot=$workspaceReady?research_workspace_deterministic_snapshot($pdo,(int)$project['id']):null;$workspaceRecord=$workspaceReady?research_workspace_record($pdo,(int)$project['id']):null;
if($workspaceAiAvailable&&$canWrite){$currentHash=research_workspace_input_hash($pdo,(int)$project['id']);if(!$workspaceRecord||($workspaceRecord['status']??'')!=='ready'||!hash_equals((string)($workspaceRecord['input_hash']??''),$currentHash)){research_workspace_queue($pdo,(int)$project['id'],4);$workspaceRecord=research_workspace_record($pdo,(int)$project['id']);}}
$workspaceCounts=$workspaceSnapshot['counts']??['sources'=>count($sources),'annotations'=>count($annotations),'claims'=>0,'findings'=>0,'open_tasks'=>count($tasks),'recent_source_changes'=>0];
$workspaceGaps=$workspaceSnapshot['gaps']??[];$workspaceConflicts=$workspaceSnapshot['conflicts']??[];$workspaceRisks=$workspaceSnapshot['source_risks']??[];$workspaceActions=($workspaceRecord&&($workspaceRecord['status']??'')==='ready'&&!empty($workspaceRecord['next_actions']))?$workspaceRecord['next_actions']:($workspaceSnapshot['next_actions']??[]);
$workspaceHighlights=($workspaceRecord&&($workspaceRecord['status']??'')==='ready')?($workspaceRecord['highlights']??[]):[];$workspaceEntities=$workspaceSnapshot['entities']??[];$workspaceLinks=$workspaceSnapshot['annotation_links']??[];$workspaceActivity=$workspaceSnapshot['recent_activity']??[];
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=h($project['title'])?> · Research · Annotated</title><link rel="stylesheet" href="/assets/css/app.css"></head><body class="researchWorkspacePage"><header class="topbar"><a class="brand" href="/home.php">Annotated</a><nav><a href="/research.php">Research</a><a href="/research-knowledge.php?id=<?=h($project['public_id'])?>">Knowledge</a><a href="/research-graph.php?id=<?=h($project['public_id'])?>">Graph</a><a href="/research-entities.php?id=<?=h($project['public_id'])?>">Entities</a><a href="/research-timeline.php?id=<?=h($project['public_id'])?>">Timeline</a><a href="/research-publish.php?id=<?=h($project['public_id'])?>">Publish</a></nav></header><main class="layout researchWorkspaceLayout"><section class="researchWorkspaceMain"><div class="pageTitle researchWorkspaceTitle"><span class="eyebrow">RESEARCH PROJECT · <?=h(strtoupper($project['access_role']))?></span><h1><?=h($project['title'])?></h1><p><?=nl2br(h($project['description']))?></p></div><?php if($success):?><div class="success"><?=h($success)?></div><?php endif?><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?>

<section class="researchNow" data-research-now data-project="<?=h($project['public_id'])?>">
  <header class="researchNowHeader"><div><span class="eyebrow">NOW</span><h2>Research intelligence</h2></div><div class="researchNowStatus"><span class="researchWorkspaceStatus status-<?=h((string)($workspaceRecord['status']??($workspaceReady?($workspaceAiAvailable?'pending':'deterministic'):'unavailable')))?>"><?=h(ucfirst((string)($workspaceRecord['status']??($workspaceReady?($workspaceAiAvailable?'pending':'deterministic'):'upgrade required'))))?></span><?php if($canWrite&&$workspaceAiAvailable):?><button type="button" class="button secondary" data-workspace-refresh>Refresh intelligence</button><?php endif?></div></header>
  <div class="researchNowStats">
    <a href="#sources"><strong><?=h((string)($workspaceCounts['sources']??0))?></strong><span>Sources</span></a>
    <a href="#annotations"><strong><?=h((string)($workspaceCounts['annotations']??0))?></strong><span>Annotations</span></a>
    <a href="/research-knowledge.php?id=<?=h($project['public_id'])?>"><strong><?=h((string)($workspaceCounts['claims']??0))?></strong><span>Claims</span></a>
    <a href="/research-knowledge.php?id=<?=h($project['public_id'])?>"><strong><?=h((string)($workspaceCounts['findings']??0))?></strong><span>Findings</span></a>
    <a href="#tasks"><strong><?=h((string)($workspaceCounts['open_tasks']??0))?></strong><span>Open tasks</span></a>
  </div>
  <div class="researchNowSummary">
    <?php if($workspaceRecord&&($workspaceRecord['status']??'')==='ready'):?><p><?=nl2br(h((string)$workspaceRecord['summary']))?></p><small>AI-assisted live synthesis · <?=h(number_format((float)($workspaceRecord['confidence']??0)*100,0))?>% analysis confidence · verify against project evidence.</small>
    <?php elseif($workspaceReady):?><p>This project currently contains <?=h((string)($workspaceCounts['claims']??0))?> claims, <?=h((string)($workspaceCounts['findings']??0))?> findings, and <?=h((string)($workspaceCounts['recent_source_changes']??0))?> recent source changes. The deterministic workspace below is current<?= $workspaceAiAvailable?' while the AI synthesis is '.h((string)($workspaceRecord['status']??'pending')):'; no Research/default AI model is configured, so no background model job is being queued' ?>.</p>
    <?php else:?><p>Research Workspace Intelligence requires the Phase 14 database upgrade.</p><?php endif?>
  </div>
  <?php if(user_is_pro($pdo,$u)||($u['role']??'')==='admin'):?><div class="researchAgentQuickActions" aria-label="Agent research actions">
    <button type="button" data-research-agent-prompt="Summarize the strongest supported evidence and findings in this Research project. Distinguish evidence from inference.">Summarize</button>
    <button type="button" data-research-agent-prompt="Investigate the highest-priority research gaps in this project. Tell me what evidence is missing and what should be checked next.">Investigate gaps</button>
    <button type="button" data-research-agent-prompt="Compare the conflicting or disputed claims in this project and explain what evidence would resolve them.">Compare conflicts</button>
    <?php if($canWrite):?><button type="button" data-research-agent-prompt="Review the current Research gaps and propose the most useful follow-up tasks. Do not execute anything without my confirmation.">Propose tasks</button>
    <button type="button" data-research-agent-prompt="Review the strongest supported Claims and propose a draft Finding if the evidence is sufficient. Do not create it without my confirmation.">Draft finding</button><?php endif?>
  </div><?php endif?>
  <?php if($workspaceHighlights):?><div class="researchNowHighlights"><?php foreach(array_slice($workspaceHighlights,0,4) as $item):?><article><span><?=h(ucfirst((string)($item['priority']??'medium')))?></span><strong><?=h((string)$item['title'])?></strong><p><?=h((string)$item['detail'])?></p></article><?php endforeach?></div><?php endif?>
</section>

<div class="researchWorkspaceGrid">
<section class="researchWorkspaceAttention"><div class="sectionHeadWeb"><div><span class="eyebrow">NEEDS ATTENTION</span><h2>Gaps, conflicts & source risks</h2></div></div>
<?php $attention=array_merge(array_slice($workspaceRisks,0,4),array_slice($workspaceConflicts,0,4),array_slice($workspaceGaps,0,4));?>
<?php if(!$attention):?><div class="card empty">No high-priority evidence gaps, conflicts, or changed-source risks are currently detected.</div><?php endif?>
<?php foreach($attention as $item):?><article class="researchAttentionItem">
  <span class="researchAttentionType"><?=h(isset($item['source_public_id'])?'Source risk':ucfirst(str_replace('_',' ',(string)($item['type']??'Attention'))))?></span>
  <strong><?=h((string)($item['title']??($item['source_title']??$item['domain']??'Research attention item')))?></strong>
  <p><?=h((string)($item['detail']??$item['latest_diff']??''))?></p>
  <?php if(!empty($item['claim_id'])):?><a href="/research-claim.php?id=<?=h((string)$item['claim_id'])?>">Open claim</a><?php elseif(!empty($item['source_public_id'])):?><a href="/source.php?id=<?=h((string)$item['source_public_id'])?>">Open source</a><?php endif?>
</article><?php endforeach?>
</section>
<section class="researchWorkspaceActions"><div class="sectionHeadWeb"><div><span class="eyebrow">NEXT ACTIONS</span><h2>What to investigate next</h2></div></div>
<?php if(!$workspaceActions):?><div class="card empty">Add claims, evidence, or tasks and Annotated will surface next research actions here.</div><?php endif?>
<?php foreach(array_slice($workspaceActions,0,8) as $item):?><article class="researchActionItem"><span class="priority-<?=h((string)($item['priority']??'medium'))?>"><?=h(ucfirst((string)($item['priority']??'medium')))?></span><strong><?=h((string)$item['title'])?></strong><p><?=h((string)($item['detail']??$item['reason']??''))?></p><button type="button" class="textButton" data-research-agent-prompt="<?=h((string)$item['title'].': '.(string)($item['detail']??$item['reason']??''))?>">Ask Agent</button></article><?php endforeach?>
</section>
</div>

<?php if($workspaceLinks||$workspaceEntities):?><section class="researchWorkspaceConnections"><div class="sectionHeadWeb"><div><span class="eyebrow">CONNECTIONS</span><h2>Evidence relationships & entities</h2></div></div>
<div class="researchConnectionsGrid"><?php if($workspaceLinks):?><div><h3>Annotation relationships</h3><?php foreach(array_slice($workspaceLinks,0,8) as $link):?><a class="researchConnectionRow" href="/annotation.php?id=<?=h((string)$link['source_annotation_id'])?>"><span><?=h(ucfirst((string)$link['relation_type']))?></span><strong><?=h((string)($link['source_title']?:'Annotation'))?> ↔ <?=h((string)($link['target_title']?:'Annotation'))?></strong><small><?=h(number_format((float)$link['confidence']*100,0))?>% analysis confidence</small></a><?php endforeach?></div><?php endif?>
<?php if($workspaceEntities):?><div><h3>Top entities</h3><?php foreach(array_slice($workspaceEntities,0,10) as $entity):?><a class="researchConnectionRow" href="/research-entity.php?id=<?=h((string)$entity['public_id'])?>"><span><?=h((string)$entity['entity_type'])?></span><strong><?=h((string)$entity['canonical_name'])?></strong><small><?=h((string)$entity['mention_count'])?> mentions</small></a><?php endforeach?></div><?php endif?></div></section><?php endif?>

<?php if($workspaceActivity):?><details class="researchActivityPanel"><summary><span><small>PROJECT ACTIVITY</small><strong>Recent changes</strong></span><span>⌄</span></summary><div class="researchActivityList"><?php foreach(array_slice($workspaceActivity,0,12) as $event):?><div><span><?=h(ucfirst(str_replace('_',' ',(string)$event['type'])))?></span><strong><?=h((string)$event['title'])?></strong><p><?=h((string)$event['body'])?></p><small><?=h((string)$event['occurred_at'])?></small><?php if(!empty($event['href'])):?><a href="<?=h((string)$event['href'])?>">Open</a><?php endif?></div><?php endforeach?></div></details><?php endif?>

<section id="sources" class="researchEvidenceSection"><div class="sectionHeadWeb"><div><span class="eyebrow">EVIDENCE</span><h2>Sources</h2></div></div><?php if(!$sources):?><div class="card empty">No sources yet.</div><?php endif?><?php foreach($sources as $s):?><article class="card"><div class="meta"><?=h($s['domain'])?> · <?=h($s['status'])?> · checked <?=h($s['last_checked_at']?:'pending')?></div><h3><a href="/source.php?id=<?=h($s['public_id'])?>"><?=h($s['title']?:$s['canonical_url'])?></a></h3><a href="<?=h($s['canonical_url'])?>" target="_blank" rel="noopener">Original source ↗</a></article><?php endforeach?><div id="annotations" class="sectionHeadWeb"><div><span class="eyebrow">EVIDENCE</span><h2>Annotations</h2></div></div><?php foreach($annotations as $a):?><?=annotation_ui_card($a,$u)?><?php endforeach?><div id="notes" class="sectionHeadWeb"><div><span class="eyebrow">WORKSPACE</span><h2>Notes</h2></div></div><?php foreach($notes as $n):?><article class="card"><div class="meta"><?=h($n['display_name'])?> · <?=h($n['created_at'])?></div><p><?=nl2br(h($n['body']))?></p></article><?php endforeach?><div id="tasks" class="sectionHeadWeb"><div><span class="eyebrow">WORKSPACE</span><h2>Tasks</h2></div></div><?php foreach($tasks as $t):?><article class="card"><div class="meta"><?=h($t['task_type'])?> · <?=h($t['status'])?></div><h3><?=h($t['title'])?></h3><p><?=nl2br(h($t['description']))?></p><?php if($canWrite):?><form method="post" class="inlineForm"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="id" value="<?=h($project['public_id'])?>"><input type="hidden" name="op" value="task_status"><input type="hidden" name="task" value="<?=h($t['public_id'])?>"><select name="status"><?php foreach(['open','in_progress','done','archived'] as $st):?><option <?=$t['status']===$st?'selected':''?>><?=$st?></option><?php endforeach?></select><button>Update</button></form><?php endif?></article><?php endforeach?><?php if($aiRuns):?><h2>Recent AI research</h2><?php foreach($aiRuns as $r):?><details class="card"><summary><?=h($r['created_at'])?></summary><p><?=nl2br(h($r['output_text']))?></p></details><?php endforeach?><?php endif?></section><aside class="researchWorkspaceRail">
<div class="card researchWorkspaceNav"><span class="eyebrow">PROJECT</span><h3>Research tools</h3><a href="/research-knowledge.php?id=<?=h($project['public_id'])?>">Claims & Findings</a><a href="/research-graph.php?id=<?=h($project['public_id'])?>">Claim Graph</a><a href="/research-entities.php?id=<?=h($project['public_id'])?>">Entities</a><a href="/research-timeline.php?id=<?=h($project['public_id'])?>">Timeline</a><a href="/research-brief.php?id=<?=h($project['public_id'])?>">Research Brief</a><a href="/research-publish.php?id=<?=h($project['public_id'])?>">Publish Report</a></div>
<?php if($canWrite):?><details class="card researchQuickAdd" open><summary>Add to research</summary><div class="researchQuickAddBody"><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="id" value="<?=h($project['public_id'])?>"><input type="hidden" name="op" value="add_source"><label>Source URL<input type="url" name="url" required></label><button>Add source</button></form><hr><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="id" value="<?=h($project['public_id'])?>"><input type="hidden" name="op" value="note"><textarea name="body" rows="3" required placeholder="Research note"></textarea><button>Add note</button></form><hr><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="id" value="<?=h($project['public_id'])?>"><input type="hidden" name="op" value="task"><input name="title" required placeholder="Research task"><select name="task_type"><option value="general">General</option><option value="find_source">Find source</option><option value="verify_claim">Verify claim</option><option value="review_source_change">Review source change</option></select><button>Add task</button></form></div></details><?php endif?>
</aside></main>
<?php if(user_is_pro($pdo,$u)||($u['role']??'')==='admin'):?>
<section class="researchAgentPanel" data-research-agent-panel data-project="<?=h($project['public_id'])?>" data-csrf="<?=h(csrf_token())?>" hidden><header><div><span class="eyebrow">PROJECT AGENT</span><strong><?=h($project['title'])?></strong></div><div><button type="button" data-research-agent-new title="New chat">＋</button><button type="button" data-research-agent-close aria-label="Close Agent panel">×</button></div></header><div class="researchAgentMessages" data-research-agent-messages role="log" aria-live="polite"></div></section>
<form class="researchAgentDock" data-research-agent-composer><button type="button" data-research-agent-context aria-label="Project context">◎</button><textarea rows="1" maxlength="12000" placeholder="Ask Annotated about this research project…" aria-label="Ask Annotated"></textarea><button type="submit" aria-label="Send to Agent">↑</button></form>
<script src="/assets/js/research-agent.js?v=15.0"></script>
<?php endif?>
<script src="/assets/js/research-workspace.js?v=15.0"></script>
<?=annotation_ui_scripts($u)?></body></html>