<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';
$u=require_user($pdo);header('Cache-Control: private, no-store');header('Vary: Cookie');
if(!research_intelligence_portfolio_operations_ready($pdo)){header('Location: /upgrade.php?from=research-intelligence-command-center');exit;}
$center=research_intelligence_organization_command_center($pdo,$u);$s=$center['summary'];$xs=$center['execution_summary']??[];$ps=$center['pattern_summary']??[];$gs=$center['strategic_graph_summary']??[];
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Intelligence Command Center · Annotated</title><meta name="robots" content="noindex,nofollow"><link rel="stylesheet" href="/assets/css/app.css?v=61.0"></head><body data-workspace-user="<?=h((string)$u['public_id'])?>" data-workspace-surface="research-intelligence-command-center">
<main class="intelligenceCommandCenter">
<section class="researchLibraryToolbar"><nav class="researchLibraryTabs researchPrimaryActions"><a href="/research.php">Research Agents</a><a href="/research-programs.php">Programs</a><a href="/research-portfolio.php">Project Portfolio</a><a href="/research-intelligence-portfolios.php">Intelligence Portfolios</a><a class="active" href="/research-intelligence-command-center.php">Command Center</a><a href="/research-publications.php">Publishing</a><a href="/research-decisions.php">Decisions</a><a href="/research-action-plans.php">Action Plans</a><a href="/research-reviews.php">Review Center</a></nav></section>
<header class="intelligenceCommandHero"><div><span class="eyebrow">PHASE 61 · ORGANIZATION COMMAND CENTER · PHASE 73 · PORTFOLIO DECISION & EXECUTION</span><h1>Executive Intelligence</h1><p>One permission-checked view across Portfolio intelligence, native Decisions, Action Plan execution, cross-Decision Pattern Memory, explicit dependency/conflict relationships, Team Reviews, Outcome Memory, and Executive Briefings.</p></div><small>Generated <?=h((string)$center['generated_at'])?></small></header>
<section class="intelligencePortfolioStats"><div><strong><?=h((string)$s['portfolios'])?></strong><span>Portfolios</span></div><div><strong><?=h((string)($xs['native_decisions']??0))?></strong><span>Native decisions</span></div><div><strong><?=h((string)($xs['action_plans']??0))?></strong><span>Action plans</span></div><div><strong><?=h((string)($ps['active_patterns']??0))?></strong><span>Learning patterns</span></div><div><strong><?=h((string)($gs['conflicts']??0))?></strong><span>Strategic conflicts</span></div><div><strong><?=h((string)($gs['stale_edges']??0))?></strong><span>Stale relationships</span></div></section>
<section class="intelligenceCommandGrid">
<section class="card"><span class="eyebrow">STRATEGIC DEPENDENCY & CONFLICT GRAPH</span><h2>Relationship attention</h2><?php if(empty($center['strategic_graph_attention'])):?><p class="empty">No conflicts, blocks, or stale strategic relationships require review.</p><?php endif?><?php foreach((array)$center['strategic_graph_attention'] as $x):?><article class="commandCenterRow"><div><strong><?=h((string)$x['source_title'])?> → <?=h((string)$x['target_title'])?></strong><small><?=h((string)$x['portfolio_title'])?> · <?=h(strtoupper(str_replace('_',' ',(string)$x['relation_type'])))?> · <?=h(strtoupper((string)($x['materiality']??'medium')))?><?=$x['cross_portfolio']?' · CROSS-PORTFOLIO':''?><?=$x['stale']?' · STALE':''?></small><small><?=h(implode(' · ',array_map(fn($v)=>str_replace('_',' ',(string)$v),(array)($x['reasons']??[]))))?></small></div><a href="/research-intelligence-portfolios.php?portfolio=<?=rawurlencode((string)$x['portfolio_id'])?>">Review graph</a></article><?php endforeach?></section>
<section class="card"><span class="eyebrow">CROSS-DECISION LEARNING</span><h2>Pattern Memory</h2><?php if(empty($center['learning_patterns'])):?><p class="empty">No deterministic cross-Decision patterns have reached the two-Decision threshold.</p><?php endif?><?php foreach((array)$center['learning_patterns'] as $x):?><article class="commandCenterRow"><div><strong><?=h((string)$x['label'])?></strong><small><?=h((string)$x['portfolio_title'])?> · <?=h(strtoupper(str_replace('_',' ',(string)$x['pattern_type'])))?> · <?=h((string)$x['decision_count'])?> Decisions · <?=h((string)$x['evidence_count'])?> evidence member(s)</small></div><a href="/research-intelligence-portfolios.php?portfolio=<?=rawurlencode((string)$x['portfolio_id'])?>">Open Portfolio</a></article><?php endforeach?></section>
<section class="card"><span class="eyebrow">DECISION & EXECUTION ATTENTION</span><h2>Strategic follow-through</h2><?php if(empty($center['decision_execution_attention'])):?><p class="empty">No native Decision execution currently needs attention.</p><?php endif?><?php foreach((array)$center['decision_execution_attention'] as $x):?><article class="commandCenterRow"><div><strong><?=h((string)$x['action_plan_title'])?></strong><small><?=h((string)$x['portfolio_title'])?> · <?=h((string)$x['decision_title'])?> · <?=h(strtoupper((string)$x['action_plan_status']))?> · <?=h(implode(' · ',array_map(fn($v)=>str_replace('_',' ',(string)$v),(array)$x['reasons'])))?></small></div><a href="/research-action-plans.php?action_plan=<?=rawurlencode((string)$x['action_plan_public_id'])?>">Open plan</a></article><?php endforeach?></section>
<section class="card"><span class="eyebrow">NEEDS ATTENTION</span><h2>Portfolio attention</h2><?php if(!$center['needs_attention']):?><p class="empty">No current Portfolio attention signals.</p><?php endif?><?php foreach($center['needs_attention'] as $x):?><article class="commandCenterRow"><div><strong><?=h((string)$x['title'])?></strong><small><?=h((string)$x['risks'])?> risks · <?=h((string)$x['tensions'])?> tensions<?=!empty($x['briefing_due'])?' · briefing due':''?></small></div><a href="/research-intelligence-portfolios.php?portfolio=<?=rawurlencode((string)$x['portfolio_id'])?>">Open</a></article><?php endforeach?></section>
<section class="card"><span class="eyebrow">NEW SINCE LAST BRIEFING</span><h2>Material movement</h2><?php if(!$center['new_since_last_briefing']):?><p class="empty">No newly material Portfolio cycle changes.</p><?php endif?><?php foreach($center['new_since_last_briefing'] as $x):?><article class="commandCenterRow"><div><strong><?=h((string)$x['title'])?></strong><small><?=h((string)($x['cycle']['detail']??'Material Portfolio change recorded.'))?></small></div><a href="/research-intelligence-portfolios.php?portfolio=<?=rawurlencode((string)$x['portfolio_id'])?>">Review</a></article><?php endforeach?></section>
<section class="card"><span class="eyebrow">DECISIONS AWAITING FOLLOW-THROUGH · LEGACY PHASE 61</span><h2>Historical task commitments</h2><?php if(!$center['decisions_awaiting_follow_through']):?><p class="empty">No open executive follow-through tasks.</p><?php endif?><?php foreach($center['decisions_awaiting_follow_through'] as $x):?><article class="commandCenterRow"><div><strong><?=h((string)$x['title'])?></strong><small><?=h((string)$x['portfolio_title'])?> · <?=h((string)$x['task_status'])?><?=!empty($x['due_at'])?' · due '.h((string)$x['due_at']):''?></small></div><a href="/research-tasks.php?task=<?=rawurlencode((string)$x['task_public_id'])?>">Open task</a></article><?php endforeach?></section>
<section class="card"><span class="eyebrow">EMERGING OPPORTUNITIES</span><h2>Positive movement</h2><?php if(!$center['emerging_opportunities']):?><p class="empty">No current deterministic opportunity signals.</p><?php endif?><?php foreach($center['emerging_opportunities'] as $x):?><article class="commandCenterRow"><div><strong><?=h((string)$x['portfolio_title'])?></strong><small><?=h((string)($x['summary']??''))?></small></div><a href="/research-intelligence-portfolios.php?portfolio=<?=rawurlencode((string)$x['portfolio_id'])?>">Open</a></article><?php endforeach?></section>
<section class="card"><span class="eyebrow">CROSS-PORTFOLIO THEMES</span><h2>Shared organizational signals</h2><?php if(!$center['cross_portfolio_themes']):?><p class="empty">No reference currently spans multiple accessible Portfolios.</p><?php endif?><?php foreach($center['cross_portfolio_themes'] as $x):?><article class="commandTheme"><strong><?=h((string)$x['key'])?></strong><span><?=h((string)$x['portfolio_count'])?> Portfolios</span><small><?=h(implode(' · ',array_values($x['portfolios'])))?></small></article><?php endforeach?></section>
<section class="card"><span class="eyebrow">BRIEFINGS AWAITING REVIEW</span><h2>Human governance</h2><?php if(!$center['briefings_awaiting_review']):?><p class="empty">No Executive Briefings currently waiting in Phase 59 review.</p><?php endif?><?php foreach($center['briefings_awaiting_review'] as $x):?><article class="commandCenterRow"><div><strong><?=h((string)$x['title'])?></strong><small><?=h((string)$x['portfolio_title'])?> · <?=h((string)($x['publication_status']??$x['status']))?></small></div><?php if(!empty($x['publication_public_id'])):?><a href="/research-publications.php?workflow=<?=rawurlencode((string)$x['publication_public_id'])?>">Review</a><?php else:?><a href="/research-intelligence-portfolios.php?portfolio=<?=rawurlencode((string)$x['portfolio_id'])?>">Open</a><?php endif?></article><?php endforeach?></section>
</section>
</main></body></html>