<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';require_once __DIR__.'/app/research-reports.php';require_once __DIR__.'/app/public-discovery.php';
$viewer=current_user($pdo);$id=(string)($_GET['id']??$_POST['id']??'');$report=research_report_access($pdo,$id,$viewer);if(!$report){http_response_code(404);exit('Research report not found.');}
$message='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){if(!$viewer){http_response_code(401);exit('Sign in to follow Research reports.');}require_csrf();try{$op=(string)($_POST['op']??'');if($op==='subscribe'){living_research_set_subscription($pdo,$viewer,$report,true,true);$message='Following this Research report.';}elseif($op==='unsubscribe'){living_research_set_subscription($pdo,$viewer,$report,false);$message='Stopped following this Research report.';}else throw new RuntimeException('Unknown report action.');}catch(Throwable $e){$error=$e->getMessage();}}
$version=(int)($_GET['v']??$report['version_number']);$row=$version===(int)$report['version_number']?$report:research_report_version_access($pdo,$report,$version,$viewer);if(!$row){http_response_code(404);exit('Report version not found.');}$snapshot=json_decode((string)$row['snapshot_json'],true);if(!is_array($snapshot)){http_response_code(500);exit('Report snapshot is invalid.');}
$reviewVersion=$viewer?research_report_version($pdo,$report,$version):null;$reviewProject=$viewer?project_access($pdo,(int)$viewer['id'],(string)$report['project_public_id']):null;$canRequestReview=$reviewProject&&project_can_write($reviewProject)&&!empty($reviewVersion['public_id']);
$subscription=$viewer&&living_research_ready($pdo)?living_research_subscription($pdo,$viewer,$report):['subscribed'=>false];$readStatus=$viewer&&living_research_ready($pdo)?living_research_read_status($pdo,$viewer,$report):['updated_since_read'=>false,'first_read'=>true,'last_read_version'=>null];$subscriberCount=living_research_ready($pdo)?living_research_subscriber_count($pdo,(int)$report['id']):0;$topics=living_research_ready($pdo)?living_research_topics($pdo,(int)$report['id']):[];$versions=living_research_version_rows($pdo,$report);$staleness=$viewer&&living_research_ready($pdo)?living_research_staleness($pdo,$viewer,$report):null;
$currentVersion=(int)$report['version_number'];$viewVersionId=$version===$currentVersion?(int)$report['current_version_id']:(int)($row['id']??0);if($viewer&&living_research_ready($pdo)&&$viewVersionId>0)living_research_mark_read($pdo,$viewer,$report,$viewVersionId);
if($viewer){header('Cache-Control: private, no-store');header('Vary: Cookie');}
$reportTitle=(string)($snapshot['project']['title']??$report['title']);$reportDesc=public_discovery_meta_description((string)($snapshot['project']['summary']??$report['summary']??('Published Research report: '.$reportTitle)));$reportCanonical=public_discovery_absolute_url($config,'/research-report.php?id='.rawurlencode($report['public_id']).($version===$currentVersion?'':'&v='.$version));$reportPublic=$report['visibility']==='public';
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=h($reportTitle)?> · Research Report · Annotated</title><meta name="description" content="<?=h($reportDesc)?>"><?php if(!$reportPublic):?><meta name="robots" content="noindex,nofollow"><?php endif?><link rel="canonical" href="<?=h($reportCanonical)?>"><?php if($reportPublic):?><meta property="og:type" content="article"><meta property="og:title" content="<?=h($reportTitle)?> · Research Report · Annotated"><meta property="og:description" content="<?=h($reportDesc)?>"><meta property="og:url" content="<?=h($reportCanonical)?>"><?php endif?><link rel="stylesheet" href="/assets/css/app.css"></head><body>
<header class="topbar"><a class="brand" href="/">Annotated</a><nav><?php if($viewer):?><a href="/research-publications.php">Living Research</a><a href="/research.php">Research</a><?php endif?><a href="/research-report-export.php?id=<?=h($report['public_id'])?>&v=<?=h((string)$version)?>&format=json">JSON</a><a href="/research-report-export.php?id=<?=h($report['public_id'])?>&v=<?=h((string)$version)?>&format=html">HTML</a></nav></header>
<main class="layout livingReportLayout"><section>
<?php if($message):?><div class="success"><?=h($message)?></div><?php endif?><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?>
<div class="pageTitle livingReportTitle"><div class="livingReportBadges"><span class="eyebrow">RESEARCH REPORT · VERSION <?=h((string)$version)?> · <?=h(strtoupper($report['visibility']))?></span><?php if($version<$currentVersion):?><span class="badge">Historical version</span><?php endif?><?php if($readStatus['updated_since_read']):?><span class="badge">Updated since you read</span><?php endif?></div><h1><?=h($reportTitle)?></h1><?php if(!empty($snapshot['project']['summary'])):?><p><?=nl2br(h((string)$snapshot['project']['summary']))?></p><?php elseif(!empty($snapshot['project']['description'])):?><p><?=nl2br(h((string)$snapshot['project']['description']))?></p><?php endif?><p class="meta">Immutable snapshot · SHA-256 <?=h((string)($row['snapshot_hash']??$report['snapshot_hash']))?> · published <?=h((string)($row['created_at']??$report['version_created_at']))?></p>
<?php if($topics):?><div class="publicationTopics"><?php foreach($topics as $topic):?><a class="badge" href="/research-topic.php?topic=<?=h((string)$topic['topic_slug'])?>"><?=h((string)$topic['topic_label'])?></a><?php endforeach?></div><?php endif?>
<div class="inlineActions livingReportActions">
<?php if($viewer):?><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="id" value="<?=h($report['public_id'])?>"><input type="hidden" name="op" value="<?=$subscription['subscribed']?'unsubscribe':'subscribe'?>"><button class="button <?=$subscription['subscribed']?'secondary':''?>"><?=$subscription['subscribed']?'Following':'Follow updates'?></button></form><?php endif?>
<?php if($canRequestReview):?><a class="button secondary" href="/research-reviews.php?type=report_version&subject=<?=h((string)$reviewVersion['public_id'])?>">Request Review</a><?php endif?>
<?php if($currentVersion>1):?><a class="button secondary" href="/research-report-diff.php?id=<?=h($report['public_id'])?>&from=<?=h((string)max(1,$version-1))?>&to=<?=h((string)$version)?>">Compare versions</a><?php endif?><a class="button secondary" href="/research-report-network.php?id=<?=h($report['public_id'])?>&v=<?=h((string)$version)?>">Research Network</a>
<button type="button" class="button secondary" data-copy-report-url data-url="<?=h($reportCanonical)?>">Copy link</button><span class="meta"><?=h((string)$subscriberCount)?> follower<?= $subscriberCount===1?'':'s' ?></span></div></div>
<?php if($readStatus['updated_since_read']&&!empty($readStatus['last_read_version'])):?><div class="card livingUpdateNotice"><strong>This report has changed since you last read it.</strong><p>You last read version <?=h((string)$readStatus['last_read_version'])?>. The current publication is version <?=h((string)$currentVersion)?>.</p><a href="/research-report-diff.php?id=<?=h($report['public_id'])?>&from=<?=h((string)$readStatus['last_read_version'])?>&to=<?=h((string)$currentVersion)?>">See what changed</a></div><?php endif?>
<?php if($version<$currentVersion):?><div class="card livingHistoricalNotice"><strong>You are viewing immutable version <?=h((string)$version)?>.</strong><p>Version <?=h((string)$currentVersion)?> is the current published version.</p><a href="/research-report.php?id=<?=h($report['public_id'])?>">Open current version</a> · <a href="/research-report-diff.php?id=<?=h($report['public_id'])?>&from=<?=h((string)$version)?>&to=<?=h((string)$currentVersion)?>">Compare with current</a></div><?php endif?>
<?php if($staleness):?><div class="error livingStaleNotice"><strong>Publisher review recommended.</strong> <?=h((string)$staleness['reason'])?> <a href="/research-impact.php?event=<?=h((string)$staleness['event_id'])?>&project=<?=h((string)$report['project_public_id'])?>">Review impact</a>. This warning is visible because you have access to the underlying Research project; public readers still see the immutable published version until a new version is deliberately published.</div><?php endif?>

<h2>Findings</h2><?php if(empty($snapshot['findings'])):?><div class="card empty">No published Findings in this version.</div><?php endif?><?php foreach(($snapshot['findings']??[]) as $fnd):?><article class="card" id="finding-<?=h((string)$fnd['id'])?>"><div class="meta"><?=h(strtoupper((string)$fnd['status']))?> · FINDING <?=h((string)$fnd['id'])?></div><h3><?=h((string)$fnd['title'])?></h3><p><?=nl2br(h((string)$fnd['summary']))?></p><?php if(!empty($fnd['claims'])):?><p class="meta">Claims: <?php foreach($fnd['claims'] as $cl):?><?=h((string)$cl['public_id'])?> (<?=h((string)$cl['relationship'])?>) <?php endforeach?></p><?php endif?></article><?php endforeach?>

<h2>Claims & Evidence</h2><?php if(empty($snapshot['claims'])):?><div class="card empty">No published Claims in this version.</div><?php endif?><?php foreach(($snapshot['claims']??[]) as $cl):?><article class="card" id="claim-<?=h((string)$cl['id'])?>"><div class="meta"><?=h(strtoupper((string)$cl['type']))?> · <?=h(strtoupper((string)$cl['status']))?> · CLAIM <?=h((string)$cl['id'])?></div><h3><?=h((string)$cl['statement'])?></h3><?php if(!empty($cl['resolution_note'])):?><p><?=nl2br(h((string)$cl['resolution_note']))?></p><?php endif?><?php foreach(($cl['evidence']??[]) as $ev):?><div class="card"><div class="meta"><?=h(strtoupper((string)$ev['relationship']))?> EVIDENCE<?=isset($ev['source_version'])?' · SOURCE VERSION '.h((string)$ev['source_version']):''?></div><?php if(!empty($ev['source_id'])):?><a href="/source.php?id=<?=h((string)$ev['source_id'])?>">Source <?=h((string)$ev['source_id'])?></a><?php endif?><?php if(!empty($ev['annotation_id'])):?> · <a href="/annotation.php?id=<?=h((string)$ev['annotation_id'])?>">Annotation <?=h((string)$ev['annotation_id'])?></a><?php endif?></div><?php endforeach?></article><?php endforeach?>

<h2>Entities</h2><?php if(empty($snapshot['entities'])):?><div class="card empty">No published Entities in this version.</div><?php endif?><?php foreach(($snapshot['entities']??[]) as $ent):?><article class="card" id="entity-<?=h((string)$ent['id'])?>"><div class="meta"><?=h(strtoupper((string)$ent['type']))?> · <?=h(strtoupper((string)$ent['status']))?> · ENTITY <?=h((string)$ent['id'])?></div><h3><?=h((string)$ent['name'])?></h3><?php if(!empty($ent['description'])):?><p><?=nl2br(h((string)$ent['description']))?></p><?php endif?><p class="meta"><?=count($ent['mentions']??[])?> provenance references</p></article><?php endforeach?>

<?php if(!empty($snapshot['claim_relations'])):?><h2>Claim Graph</h2><?php foreach($snapshot['claim_relations'] as $rel):?><article class="card"><p><strong><?=h((string)$rel['source_claim_id'])?></strong> <?=h(str_replace('_',' ',(string)$rel['relation_type']))?> <strong><?=h((string)$rel['target_claim_id'])?></strong></p></article><?php endforeach?><?php endif?>
<?php if(!empty($snapshot['entity_relations'])):?><h2>Entity Graph</h2><?php foreach($snapshot['entity_relations'] as $rel):?><article class="card"><p><strong><?=h((string)$rel['source_entity_id'])?></strong> <?=h(str_replace('_',' ',(string)$rel['relation_type']))?> <strong><?=h((string)$rel['target_entity_id'])?></strong></p></article><?php endforeach?><?php endif?>
<?php if(!empty($snapshot['report_citations'])):?><h2>Referenced Research</h2><?php foreach($snapshot['report_citations'] as $citation):?><article class="card citationEdge"><div class="meta"><?=h(strtoupper((string)$citation['relation']))?> · PINNED REPORT VERSION <?=h((string)$citation['version_number'])?></div><h3><a href="/research-report.php?id=<?=h((string)$citation['report_id'])?>&v=<?=h((string)$citation['version_number'])?>"><?=h((string)$citation['title'])?></a></h3><p class="meta">Immutable SHA-256 <?=h((string)$citation['snapshot_hash'])?><?php if(!empty($citation['publisher'])):?> · <?=h((string)$citation['publisher'])?><?php endif?></p><?php if(!empty($citation['note'])):?><p><?=nl2br(h((string)$citation['note']))?></p><?php endif?></article><?php endforeach?><?php endif?>
<h2>Research Timeline</h2><?php foreach(($snapshot['timeline']??[]) as $t):?><article class="card"><div class="meta"><?=h(strtoupper(str_replace('_',' ',(string)$t['type'])))?> · <?=h((string)($t['at']??'unknown date'))?></div><p><?=h((string)$t['label'])?></p><?php if(!empty($t['detail'])):?><p class="meta"><?=nl2br(h((string)$t['detail']))?></p><?php endif?></article><?php endforeach?>
</section><aside>
<div class="card"><h3>Citations</h3><ol class="livingCitationList"><?php foreach(($snapshot['sources']??[]) as $s):?><li><a href="<?=h((string)$s['url'])?>" target="_blank" rel="noopener"><?=h((string)($s['title']?:$s['domain']))?></a><br><span class="meta">Source Version <?=h((string)($s['version']??'?'))?> · <?=h((string)($s['captured_at']??'capture pending'))?></span></li><?php endforeach?></ol></div>
<div class="card"><h3>Version history</h3><?php foreach($versions as $v):?><p><a href="/research-report.php?id=<?=h($report['public_id'])?>&v=<?=h((string)$v['version_number'])?>">Version <?=h((string)$v['version_number'])?></a><?php if((int)$v['version_number']===$currentVersion):?> <span class="badge">Current</span><?php endif?><br><span class="meta"><?=h((string)$v['created_at'])?></span></p><?php endforeach?></div>
<div class="card"><h3>Version integrity</h3><p class="meta">This page renders one immutable publication snapshot. New Research never rewrites this version; it creates another version with its own SHA-256 hash.</p></div>
</aside></main>
<script>document.querySelectorAll('[data-copy-report-url]').forEach(btn=>btn.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(btn.dataset.url||location.href);const old=btn.textContent;btn.textContent='Copied';setTimeout(()=>btn.textContent=old,1400);}catch(e){}}));</script>
</body></html>
