<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';require_once __DIR__.'/app/public-discovery.php';$viewer=current_user($pdo);$term=trim((string)($_GET['q']??''));$results=public_discovery_search($pdo,$term);
$total=array_sum(array_map('count',$results));
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=h($term!==''?'Search “'.$term.'”':'Search')?> · Annotated</title><meta name="robots" content="noindex,follow"><link rel="stylesheet" href="/assets/css/app.css"></head><body><header class="topbar"><a class="brand" href="/">Annotated</a><nav><?php if($viewer):?><a href="/home.php">Home</a><?php endif?><a href="/explore.php">Explore</a><?php if($viewer):?><a href="/research.php">Research</a><a href="/saved.php">Saved</a><?php else:?><a href="/login.php">Log in</a><?php endif?></nav></header>
<main class="discoveryShell searchPage"><div class="pageTitle"><span class="eyebrow">DISCOVERY</span><h1>Search Annotated</h1><p>Search public sources, annotations, transcripts, people, published Research reports, and the claims/entities inside those immutable report snapshots.</p></div><form method="get" class="searchBar"><input name="q" value="<?=h($term)?>" placeholder="Search the public research graph" autofocus><button>Search</button></form>
<?php if($term!==''&&mb_strlen($term)<2):?><div class="error">Enter at least 2 characters.</div><?php elseif(mb_strlen($term)>=2):?><p class="meta"><?=h((string)$total)?> results across <?=count(array_filter($results,fn($v)=>count($v)>0))?> categories</p><div class="searchResultsGrid">
<section><h2>Sources <span class="meta"><?=count($results['sources'])?></span></h2><?php if(!$results['sources']):?><div class="card">No sources found.</div><?php endif?><?php foreach($results['sources'] as $s):?><a class="card sourceCard" href="/source.php?id=<?=h($s['public_id'])?>"><div class="meta"><?=h($s['domain'])?> · <?=h($s['status'])?> · <?=h((string)$s['annotation_count'])?> annotations</div><h3><?=h($s['title']?:$s['canonical_url'])?></h3></a><?php endforeach?></section>
<section><h2>Annotations & transcripts <span class="meta"><?=count($results['annotations'])?></span></h2><?php if(!$results['annotations']):?><div class="card">No annotations found.</div><?php endif?><?php foreach($results['annotations'] as $a):?><article class="card"><div class="meta"><a href="/profile.php?u=<?=h($a['username'])?>"><?=h($a['display_name'])?></a> · <a href="/source.php?id=<?=h($a['source_public_id'])?>"><?=h($a['source_title']?:'Source')?></a></div><?php if($a['text_commentary']):?><p><?=nl2br(h(public_discovery_meta_description($a['text_commentary'],500)))?></p><?php endif?><?php if($a['selected_text']):?><blockquote><?=h(mb_substr($a['selected_text'],0,500))?></blockquote><?php endif?><?php if($a['transcript_text']):?><details><summary>Transcript match</summary><p><?=nl2br(h(mb_substr($a['transcript_text'],0,900)))?></p></details><?php endif?><a href="/annotation.php?id=<?=h($a['public_id'])?>">Open annotation</a></article><?php endforeach?></section>
<section><h2>People <span class="meta"><?=count($results['people'])?></span></h2><?php if(!$results['people']):?><div class="card">No people found.</div><?php endif?><?php foreach($results['people'] as $p):?><a class="card sourceCard" href="/profile.php?u=<?=h($p['username'])?>"><strong><?=h($p['display_name'])?></strong><div class="meta">@<?=h($p['username'])?></div><?php if($p['bio']):?><p><?=h(public_discovery_meta_description($p['bio'],240))?></p><?php endif?></a><?php endforeach?></section>
<section><h2>Research reports <span class="meta"><?=count($results['reports'])?></span></h2><?php if(!$results['reports']):?><div class="card">No public Research reports found.</div><?php endif?><?php foreach($results['reports'] as $r):?><a class="card sourceCard" href="/research-report.php?id=<?=h($r['public_id'])?>"><div class="meta">Version <?=h((string)$r['version_number'])?> · <?=h($r['display_name'])?> · <?=h((string)$r['published_at'])?></div><h3><?=h($r['title'])?></h3><?php if($r['summary']):?><p><?=h(public_discovery_meta_description($r['summary'],260))?></p><?php endif?><?php foreach($r['matches'] as $match):?><div class="searchMatch"><?=h($match)?></div><?php endforeach?></a><?php endforeach?></section>
</div><?php endif?></main></body></html>