<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';require_once __DIR__.'/app/public-discovery.php';
$viewer=current_user($pdo);if($viewer){header('Cache-Control: private, no-store');header('Vary: Cookie');}
$error='';$success='';$savedLoaded=null;
if($viewer&&isset($_GET['saved'])){$savedLoaded=search_saved_access($pdo,$viewer,(string)$_GET['saved']);if($savedLoaded){$_GET['q']=$savedLoaded['query_text'];$savedFilters=json_decode((string)$savedLoaded['filters_json'],true)?:[];foreach($savedFilters as $k=>$v)if(!isset($_GET[$k]))$_GET[$k]=$v;}}
$term=search_normalize_query((string)($_GET['q']??$_POST['q']??''));$filters=search_filters_from_input($_GET+$_POST);
$roomData=$viewer?live_rooms_for_user($pdo,$viewer):['teams'=>[],'projects'=>[]];$writeProjects=[];if($viewer){foreach($roomData['projects'] as $p)if(!empty($p['can_post']))$writeProjects[]=$p;}
if($_SERVER['REQUEST_METHOD']==='POST'&&$viewer){require_csrf();$action=(string)($_POST['action']??'');try{
    if($action==='save_search'){$scope=(string)($_POST['save_scope']??'private');$visibility='private';$scopeId=null;if(str_starts_with($scope,'team:')){$visibility='team';$scopeId=substr($scope,5);}elseif(str_starts_with($scope,'project:')){$visibility='project';$scopeId=substr($scope,8);}$saved=search_saved_create($pdo,$viewer,(string)($_POST['title']??''),$term,$filters,$visibility,$scopeId,!empty($_POST['alerts_enabled']));$success='Search saved.';$savedLoaded=search_saved_access($pdo,$viewer,$saved['public_id']);}
    elseif($action==='delete_saved'){if(!search_saved_delete($pdo,$viewer,(string)($_POST['saved_id']??'')))throw new RuntimeException('Only the saved-search owner can delete it.');$success='Saved search deleted.';}
    elseif($action==='toggle_alert'){if(!search_saved_alert_toggle($pdo,$viewer,(string)($_POST['saved_id']??''),!empty($_POST['enabled'])))throw new RuntimeException('Only the saved-search owner can change alerts.');$success='Saved-search alerts updated.';}
    elseif($action==='add_research'){$project=project_access($pdo,(int)$viewer['id'],(string)($_POST['project_id']??''));if(!$project||!project_can_write($project))throw new RuntimeException('Research write access required.');$kind=(string)($_POST['result_type']??'');$id=(string)($_POST['result_id']??'');if($kind==='annotation'){$a=annotation_access($pdo,$id,$viewer);if(!$a)throw new RuntimeException('Annotation not available.');$pdo->prepare('INSERT IGNORE INTO project_annotations(project_id,annotation_id,added_by_user_id) VALUES(?,?,?)')->execute([$project['id'],$a['id'],$viewer['id']]);}elseif($kind==='source'){$s=source_access($pdo,$id,$viewer);if(!$s)throw new RuntimeException('Source not available.');$pdo->prepare('INSERT IGNORE INTO project_sources(project_id,source_id,added_by_user_id) VALUES(?,?,?)')->execute([$project['id'],$s['id'],$viewer['id']]);}else throw new RuntimeException('This result type cannot be added directly.');$success='Added to Research.';}
}catch(Throwable $e){$error=$e->getMessage();}}
$results=search_unified($pdo,$term,$viewer,$filters);$total=(int)$results['meta']['total'];$savedSearches=$viewer?search_saved_list($pdo,$viewer):[];$recent=$viewer?search_recent($pdo,$viewer,8):[];
$typeLabels=['all'=>'All','sources'=>'Sources','annotations'=>'Annotations','people'=>'People','reports'=>'Reports','entities'=>'Entities','projects'=>'Projects','research'=>'Research objects'];
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=h($term!==''?'Search “'.$term.'”':'Search')?> · Annotated</title><meta name="robots" content="noindex,follow"><link rel="stylesheet" href="/assets/css/app.css"></head><body>
<header class="topbar"><a class="brand" href="/">Annotated</a><nav><?php if($viewer):?><a href="/home.php">Home</a><?php endif?><a href="/explore.php">Explore</a><?php if($viewer):?><a href="/research.php">Research</a><a href="/saved.php">Saved</a><a href="/notifications.php">Notifications</a><?php else:?><a href="/login.php">Log in</a><?php endif?></nav></header>
<main class="searchWorkspace"><section class="searchMain"><div class="pageTitle"><span class="eyebrow">PHASE 10 · DISCOVERY</span><h1>Search Annotated</h1><p>Search sources, annotations, commentary, transcripts, people, public entities, accessible Research, Findings and Claims. Permissions are checked against the relational source of truth before results are returned.</p></div>
<?php if($success):?><div class="success"><?=h($success)?></div><?php endif?><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?>
<form method="get" class="searchControl card"><div class="searchBar"><input name="q" value="<?=h($term)?>" placeholder="Search the research graph" autofocus><button>Search</button></div><div class="searchFilters">
<label>Type<select name="type"><?php foreach($typeLabels as $key=>$label):?><option value="<?=h($key)?>" <?=$filters['type']===$key?'selected':''?>><?=h($label)?></option><?php endforeach?></select></label>
<label>Sort<select name="sort"><option value="relevance" <?=$filters['sort']==='relevance'?'selected':''?>>Relevance</option><option value="newest" <?=$filters['sort']==='newest'?'selected':''?>>Newest</option><option value="discussed" <?=$filters['sort']==='discussed'?'selected':''?>>Most discussed</option></select></label>
<label>Domain<input name="domain" value="<?=h($filters['domain'])?>" placeholder="example.com"></label><label>Author<input name="author" value="<?=h($filters['author'])?>" placeholder="@username"></label>
<label>Media<select name="media"><option value="">Any</option><?php foreach(['text'=>'Text','screenshot'=>'Screenshot','video_clip'=>'Video','audio_clip'=>'Audio','audio_commentary'=>'Audio commentary'] as $k=>$v):?><option value="<?=h($k)?>" <?=$filters['media']===$k?'selected':''?>><?=h($v)?></option><?php endforeach?></select></label>
<label>Integrity<select name="integrity"><option value="">Any</option><?php foreach(['source_unchanged'=>'Source unchanged','source_updated'=>'Source updated','passage_changed'=>'Passage changed','passage_missing'=>'Passage missing','source_unavailable'=>'Source unavailable','source_restored'=>'Source restored'] as $k=>$v):?><option value="<?=h($k)?>" <?=$filters['integrity']===$k?'selected':''?>><?=h($v)?></option><?php endforeach?></select></label>
<label>From<input type="date" name="date_from" value="<?=h($filters['date_from'])?>"></label><label>To<input type="date" name="date_to" value="<?=h($filters['date_to'])?>"></label>
<?php if($viewer):?><label>Team<select name="team"><option value="">Any accessible Team</option><?php foreach($roomData['teams'] as $t):?><option value="<?=h($t['public_id'])?>" <?=$filters['team']===$t['public_id']?'selected':''?>><?=h($t['name'])?></option><?php endforeach?></select></label><label>Research project<select name="project"><option value="">Any accessible project</option><?php foreach($roomData['projects'] as $p):?><option value="<?=h($p['public_id'])?>" <?=$filters['project']===$p['public_id']?'selected':''?>><?=h($p['title'])?></option><?php endforeach?></select></label><?php endif?>
</div></form>
<?php if($term!==''&&mb_strlen($term)<2):?><div class="error">Enter at least 2 characters.</div><?php elseif(mb_strlen($term)>=2):?><div class="searchSummary"><strong><?=h((string)$total)?> results</strong><span class="meta">Current filters are applied before permission-safe results are returned.</span></div>
<div class="searchTypeTabs"><?php foreach($typeLabels as $key=>$label):$qs=$_GET;$qs['type']=$key;?><a class="<?=$filters['type']===$key?'active':''?>" href="/search.php?<?=h(http_build_query($qs))?>"><?=h($label)?></a><?php endforeach?></div>
<div class="searchResultsGrid phase10Results">
<?php if($filters['type']==='all'||$filters['type']==='sources'):?><section><h2>Sources <span class="meta"><?=count($results['sources'])?></span></h2><?php foreach($results['sources'] as $s):?><article class="card sourceCard"><div class="meta"><?=h($s['domain'])?> · <?=h($s['status'])?> · <?=h((string)$s['annotation_count'])?> accessible annotations</div><h3><a href="/source.php?id=<?=h($s['public_id'])?>"><?=h($s['title']?:$s['canonical_url'])?></a></h3><?php if($viewer&&$writeProjects):?><form method="post" class="searchAddResearch"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="add_research"><input type="hidden" name="q" value="<?=h($term)?>"><input type="hidden" name="result_type" value="source"><input type="hidden" name="result_id" value="<?=h($s['public_id'])?>"><select name="project_id"><?php foreach($writeProjects as $p):?><option value="<?=h($p['public_id'])?>"><?=h($p['title'])?></option><?php endforeach?></select><button class="button secondary">Add to Research</button></form><?php endif?></article><?php endforeach?><?php if(!$results['sources']):?><div class="card">No accessible sources found.</div><?php endif?></section><?php endif?>
<?php if($filters['type']==='all'||$filters['type']==='annotations'):?><section><h2>Annotations <span class="meta"><?=count($results['annotations'])?></span></h2><?php foreach($results['annotations'] as $a):?><article class="card"><div class="meta"><a href="/profile.php?u=<?=h($a['username'])?>"><?=h($a['display_name'])?></a> · <a href="/source.php?id=<?=h($a['source_public_id'])?>"><?=h($a['source_title']?:$a['domain'])?></a> · <span class="badge <?=in_array($a['integrity']['impact_type'],['passage_changed','passage_missing','source_unavailable'],true)?'warn':''?>"><?=h($a['integrity']['label'])?></span></div><?php if($a['text_commentary']):?><p><?=nl2br(h(public_discovery_meta_description($a['text_commentary'],520)))?></p><?php endif?><?php if($a['selected_text']):?><blockquote><?=h(mb_substr($a['selected_text'],0,500))?></blockquote><?php endif?><?php if($a['transcript_text']):?><details><summary>Transcript match</summary><p><?=nl2br(h(mb_substr($a['transcript_text'],0,900)))?></p></details><?php endif?><div class="inlineActions"><a href="/annotation.php?id=<?=h($a['public_id'])?>">Open annotation</a><?php if($viewer&&$writeProjects):?><form method="post" class="searchAddResearch"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="add_research"><input type="hidden" name="q" value="<?=h($term)?>"><input type="hidden" name="result_type" value="annotation"><input type="hidden" name="result_id" value="<?=h($a['public_id'])?>"><select name="project_id"><?php foreach($writeProjects as $p):?><option value="<?=h($p['public_id'])?>"><?=h($p['title'])?></option><?php endforeach?></select><button class="button secondary">Add to Research</button></form><?php endif?></div></article><?php endforeach?><?php if(!$results['annotations']):?><div class="card">No accessible annotations found.</div><?php endif?></section><?php endif?>
<?php if($filters['type']==='all'||$filters['type']==='people'):?><section><h2>People <span class="meta"><?=count($results['people'])?></span></h2><?php foreach($results['people'] as $p):?><a class="card sourceCard" href="/profile.php?u=<?=h($p['username'])?>"><strong><?=h($p['display_name'])?></strong><div class="meta">@<?=h($p['username'])?></div><?php if($p['bio']):?><p><?=h(public_discovery_meta_description($p['bio'],240))?></p><?php endif?></a><?php endforeach?><?php if(!$results['people']):?><div class="card">No public profiles found.</div><?php endif?></section><?php endif?>
<?php if($filters['type']==='all'||$filters['type']==='reports'):?><section><h2>Research reports <span class="meta"><?=count($results['reports'])?></span></h2><?php foreach($results['reports'] as $r):?><article class="card sourceCard"><div class="meta"><?=h(ucfirst($r['visibility']))?> · version <?=h((string)$r['version_number'])?> · <?=h($r['display_name'])?></div><h3><a href="/research-report.php?id=<?=h($r['public_id'])?>"><?=h($r['title'])?></a></h3><?php if($r['summary']):?><p><?=h(public_discovery_meta_description($r['summary'],260))?></p><?php endif?><?php foreach($r['matches'] as $m):?><a class="searchMatch" href="/research-report.php?id=<?=h($r['public_id'])?>#<?=h($m['anchor'])?>"><?=h($m['label'])?></a><?php endforeach?></article><?php endforeach?><?php if(!$results['reports']):?><div class="card">No accessible reports found.</div><?php endif?></section><?php endif?>
<?php if($filters['type']==='all'||$filters['type']==='entities'):?><section><h2>Entities & topics <span class="meta"><?=count($results['entities'])?></span></h2><?php foreach($results['entities'] as $e):?><a class="card sourceCard" href="<?=$e['scope']==='public'?'/entity.php?id='.h($e['public_id']):'/research-entity.php?id='.h($e['public_id'])?>"><div class="meta"><?=h($e['entity_type'])?> · <?=h($e['scope'])?> · <?=h((string)$e['mention_count'])?> mentions</div><h3><?=h($e['canonical_name'])?></h3><?php if($e['description']):?><p><?=h(public_discovery_meta_description($e['description'],240))?></p><?php endif?></a><?php endforeach?><?php if(!$results['entities']):?><div class="card">No entities found.</div><?php endif?></section><?php endif?>
<?php if($viewer&&($filters['type']==='all'||$filters['type']==='projects')):?><section><h2>Research projects <span class="meta"><?=count($results['projects'])?></span></h2><?php foreach($results['projects'] as $p):?><a class="card sourceCard" href="/research-project.php?id=<?=h($p['public_id'])?>"><div class="meta"><?=h($p['access_role'])?></div><h3><?=h($p['title'])?></h3><?php if($p['description']):?><p><?=h(public_discovery_meta_description($p['description'],240))?></p><?php endif?></a><?php endforeach?><?php if(!$results['projects']):?><div class="card">No accessible projects found.</div><?php endif?></section><?php endif?>
<?php if($viewer&&($filters['type']==='all'||$filters['type']==='research')):?><section><h2>Findings & claims <span class="meta"><?=count($results['research'])?></span></h2><?php foreach($results['research'] as $r):?><a class="card sourceCard" href="<?=$r['object_type']==='claim'?'/research-claim.php?id=':'/research-finding.php?id='?><?=h($r['public_id'])?>"><div class="meta"><?=h($r['project_title'])?> · <?=h($r['object_type'])?></div><h3><?=h($r['title'])?></h3><?php if($r['snippet']):?><p><?=h(public_discovery_meta_description($r['snippet'],280))?></p><?php endif?></a><?php endforeach?><?php if(!$results['research']):?><div class="card">No matching Research objects found.</div><?php endif?></section><?php endif?>
</div><?php endif?></section>
<?php if($viewer):?><aside class="searchSidebar"><div class="card"><h3>Save this search</h3><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="save_search"><input type="hidden" name="q" value="<?=h($term)?>"><?php foreach($filters as $k=>$v):?><input type="hidden" name="<?=h($k)?>" value="<?=h((string)$v)?>"><?php endforeach?><label>Name<input name="title" value="<?=h($term)?>" required></label><label>Sharing<select name="save_scope"><option value="private">Private</option><?php foreach($roomData['teams'] as $t):?><option value="team:<?=h($t['public_id'])?>">Team · <?=h($t['name'])?></option><?php endforeach?><?php foreach($roomData['projects'] as $p):?><option value="project:<?=h($p['public_id'])?>">Research · <?=h($p['title'])?></option><?php endforeach?></select></label><label><input type="checkbox" name="alerts_enabled" value="1"> Alert me to new matches</label><button <?=mb_strlen($term)<2?'disabled':''?>>Save search</button></form></div>
<div class="card"><h3>Saved searches</h3><?php if(!$savedSearches):?><p class="meta">No saved searches yet.</p><?php endif?><?php foreach(array_slice($savedSearches,0,12) as $s):?><div class="savedSearchRow"><a href="/search.php?saved=<?=h($s['public_id'])?>"><strong><?=h($s['title'])?></strong><small><?=h($s['query_text'])?> · <?=h($s['visibility'])?></small></a><?php if($savedLoaded&&$savedLoaded['public_id']===$s['public_id']&&(int)$savedLoaded['owner_user_id']===(int)$viewer['id']):?><div class="inlineActions"><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="toggle_alert"><input type="hidden" name="saved_id" value="<?=h($s['public_id'])?>"><input type="hidden" name="enabled" value="<?=$s['alerts_enabled']?'0':'1'?>"><button class="button secondary"><?=$s['alerts_enabled']?'Disable alerts':'Enable alerts'?></button></form><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="delete_saved"><input type="hidden" name="saved_id" value="<?=h($s['public_id'])?>"><button class="button secondary">Delete</button></form></div><?php endif?></div><?php endforeach?></div>
<div class="card"><h3>Recent searches</h3><?php foreach($recent as $r):?><a class="recentSearch" href="/search.php?q=<?=urlencode($r['query_text'])?>&<?=h(search_filter_query_string($r['filters']))?>"><?=h($r['query_text'])?><small><?=h($r['last_used_at'])?></small></a><?php endforeach?></div></aside><?php endif?></main></body></html>