<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';require_once __DIR__.'/app/public-discovery.php';require_once __DIR__.'/app/annotation-ui.php';
$viewer=current_user($pdo);$id=(string)($_GET['id']??'');if($viewer){header('Cache-Control: private, no-store');header('Vary: Cookie');}$source=public_discovery_source($pdo,$id,$viewer);if(!$source){http_response_code(404);exit('Source not found.');}$relatedSources=search_related_sources($pdo,$source['public_id'],$viewer,8);
$isPublic=(int)$source['public_annotation_count']>0;$title=(string)($source['title']?:$source['canonical_url']);
$desc=public_discovery_meta_description('Annotations, preserved source versions, discussion, and provenance for '.$title.' on Annotated.');
$canonical=public_discovery_absolute_url($config,'/source.php?id='.rawurlencode($source['public_id']));
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=h($title)?> · Annotated</title>
<meta name="description" content="<?=h($desc)?>"><?php if(!$isPublic):?><meta name="robots" content="noindex,nofollow"><?php endif?><link rel="canonical" href="<?=h($canonical)?>">
<?php if($isPublic):?><meta property="og:type" content="article"><meta property="og:title" content="<?=h($title)?> · Annotated"><meta property="og:description" content="<?=h($desc)?>"><meta property="og:url" content="<?=h($canonical)?>"><?php endif?>
<link rel="stylesheet" href="/assets/css/app.css"></head><body<?php if($viewer):?> data-workspace-user="<?=h((string)$viewer['public_id'])?>" data-workspace-surface="source" data-workspace-object-type="source" data-workspace-object="<?=h((string)$source['public_id'])?>"<?php endif?>><header class="topbar"><a class="brand" href="/">Annotated</a><nav><?php if($viewer):?><a href="/home.php">Home</a><?php endif?><a href="/explore.php">Explore</a><a href="/search.php">Search</a><?php if($viewer):?><a href="/research.php">Research</a><a href="/saved.php">Saved</a><?php else:?><a href="/login.php">Log in</a><?php endif?></nav></header>
<main class="layout"><section><div class="sourceHero"><div class="meta"><?=h($source['domain'])?> · <?=h(ucfirst($source['source_type']))?><?php if($source['current_version_number']):?> · current v<?=h((string)$source['current_version_number'])?><?php endif?></div><h1><?=h($title)?></h1><p class="sourceUrl"><?=h($source['canonical_url'])?></p>
<div class="sourceStats"><span><strong><?=h((string)$source['public_annotation_count'])?></strong> public annotations</span><span><strong><?=h((string)$source['public_contributor_count'])?></strong> contributors</span><span><strong><?=h((string)$source['follower_count'])?></strong> followers</span></div>
<div class="inlineActions"><a class="button secondary" href="<?=h($source['canonical_url'])?>" target="_blank" rel="noopener">Open original ↗</a><a class="button secondary" href="/search.php?q=annotation&source=<?=h($source['public_id'])?>">Search within source</a><button class="button secondary" type="button" id="copyLink">Copy source link</button><?php if($viewer):?><a class="button secondary" href="/live.php?id=<?=h($source['public_id'])?>">Open Live</a><button class="button secondary" id="watch" data-source="<?=h($source['public_id'])?>"><?=$source['followed']?'Following source':'Follow source'?></button><button class="button secondary" type="button" id="muteSource" data-source="<?=h($source['public_id'])?>">Mute source alerts</button><?php endif?><?php if($isPublic):?><a class="button secondary" href="/report.php?type=source&id=<?=h($source['public_id'])?>">Report source</a><?php endif?></div>
<?php if($source['status']==='edited'):?><div class="integrityAlert"><strong>Source changed after earlier captures</strong><p>Annotated has preserved prior versions so the original annotation context can still be reviewed.</p></div><?php elseif($source['status']!=='current'):?><div class="integrityAlert mild"><strong>Source status: <?=h(ucfirst($source['status']))?></strong><p>Compare preserved versions to see what changed.</p></div><?php endif?></div>
<div class="sectionHeadWeb"><div><span class="eyebrow">THIS SOURCE</span><h2>Annotations</h2></div><span class="meta"><?=count($source['annotations'])?> accessible</span></div>
<?php if(!$source['annotations']):?><div class="card empty">No annotations you can access on this source yet.</div><?php endif?>
<?php foreach($source['annotations'] as $a):?><?=annotation_ui_card($a,$viewer,['show_source'=>false])?><?php endforeach?></section>
<aside><div class="card"><h3>Source history</h3><p class="meta">Each captured version is immutable. Later edits to the live page do not replace earlier evidence.</p><?php foreach($source['versions'] as $i=>$v):?><div class="historyItem"><strong>Version <?=h((string)$v['version_number'])?></strong><div class="meta"><?=h($v['captured_at'])?></div><div><?php if($v['screenshot_path']):?><a href="<?=h(source_evidence_url($source['public_id'],(int)$v['id']))?>" target="_blank" rel="noopener">Snapshot</a><?php endif?><?php if(isset($source['versions'][$i+1])):?> · <a href="/source-compare.php?id=<?=h($source['public_id'])?>&from=<?=h((string)$source['versions'][$i+1]['id'])?>&to=<?=h((string)$v['id'])?>">Compare</a><?php endif?></div></div><?php endforeach?></div>
<?php if($source['events']):?><div class="card"><h3>Recent changes</h3><?php foreach(array_slice($source['events'],0,8) as $e):?><div class="historyItem" id="change-<?=h((string)$e['id'])?>"><span class="badge <?=in_array($e['impact_type'],['passage_changed','passage_missing','source_unavailable'],true)?'warn':''?>"><?=h($e['label'])?></span><div class="meta">v<?=h((string)$e['previous_number'])?> → v<?=h((string)$e['new_number'])?></div><?php if($e['diff_summary']):?><p class="meta"><?=h($e['diff_summary'])?></p><?php endif?><a href="/source-compare.php?id=<?=h($source['public_id'])?>&from=<?=h((string)$e['previous_version_id'])?>&to=<?=h((string)$e['new_version_id'])?>">Compare versions</a><?php if($viewer):?> · <a href="/research-impact.php?event=<?=h((string)$e['id'])?>">Review downstream impact</a><?php endif?></div><?php endforeach?></div><?php endif?>
<div class="card"><h3>Related sources</h3><?php if(!$relatedSources):?><p class="meta">Related sources appear when contributors annotate multiple public or accessible sources.</p><?php endif?><?php foreach($relatedSources as $r):?><a class="relatedSource" href="/source.php?id=<?=h($r['public_id'])?>"><strong><?=h($r['title']?:$r['domain'])?></strong><small><?=h($r['domain'])?> · <?=h((string)$r['shared_contributors'])?> shared contributors</small></a><?php endforeach?></div></aside></main>
<script>document.querySelector('#copyLink')?.addEventListener('click',async e=>{await navigator.clipboard.writeText(location.href);e.currentTarget.textContent='Copied';});</script>
<?php if($viewer):?><script>const csrf=<?=json_encode(csrf_token())?>;document.querySelector('#watch')?.addEventListener('click',async e=>{const r=await fetch('/api/extension.php?action=watch_source',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({source:e.currentTarget.dataset.source})});const j=await r.json();if(j.ok)e.currentTarget.textContent=j.data.following?'Following source':'Follow source';});document.querySelector('#muteSource')?.addEventListener('click',async e=>{if(!confirm('Mute source-change notifications for this source?'))return;const r=await fetch('/api/extension.php?action=notification_mute',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({scope_type:'source',scope_id:e.currentTarget.dataset.source,category:'sources',muted:true})});const j=await r.json();if(j.ok)e.currentTarget.textContent='Source alerts muted';});</script><?php endif?><?=annotation_ui_scripts($viewer)?><?php if($viewer):?><script src="/assets/js/workspace-state.js?v=34.0"></script><?php endif?></body></html>