<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';
$u=require_user($pdo);header('Cache-Control: private, no-store');$error='';$success='';
if(!sponsored_research_campaigns_ready($pdo)){http_response_code(503);exit('Sponsored Research campaigns require the latest database upgrade.');}
try{$sponsor=sponsor_account_require_approved($pdo,$u);}catch(Throwable $e){$sponsor=null;$error=$e->getMessage();}
$accounts=$sponsor?account_membership_accounts_for_user($pdo,$u,true):[];$agents=$sponsor&&function_exists('research_agent_list')?research_agent_list($pdo,$u,100):[];
if($_SERVER['REQUEST_METHOD']==='POST'&&$sponsor){
 require_csrf();
 try{
  $op=(string)($_POST['op']??'create');
  if($op==='create'){
   $c=sponsored_research_campaign_create($pdo,$u,[
    'account_id'=>(string)($_POST['account_id']??''),'research_agent_id'=>(string)($_POST['research_agent_id']??''),
    'title'=>(string)($_POST['title']??''),'brief'=>(string)($_POST['brief']??''),'objective'=>(string)($_POST['objective']??''),
    'questions'=>(string)($_POST['questions']??''),'access_mode'=>(string)($_POST['access_mode']??'private'),
    'budget_currency'=>(string)($_POST['budget_currency']??'USD'),'budget'=>(string)($_POST['budget_amount']??'0'),
    'max_participants'=>(int)($_POST['max_participants']??0),'starts_at'=>(string)($_POST['starts_at']??''),'submission_deadline'=>(string)($_POST['submission_deadline']??''),'review_deadline'=>(string)($_POST['review_deadline']??''),
    'eligibility'=>['min_verification'=>(string)($_POST['minimum_verification']??'basic'),'specialties'=>(string)($_POST['required_specialties']??''),'languages'=>(string)($_POST['required_languages']??''),'min_completed_campaigns'=>(int)($_POST['min_completed_campaigns']??0)],
    'disclosures'=>['sponsorship_disclosure_required'=>isset($_POST['sponsorship_disclosure_required']),'conflict_disclosure_required'=>isset($_POST['conflict_disclosure_required']),'nda_required'=>isset($_POST['nda_required']),'ai_assistance_policy'=>(string)($_POST['ai_assistance_policy']??'allowed_with_disclosure'),'training_use_request'=>(string)($_POST['training_use_request']??'none')]
   ]);$success='Sponsored Research campaign created.';$_GET['campaign']=$c['public_id'];
  }elseif($op==='update'){
   sponsored_research_campaign_update($pdo,$u,(string)$_POST['campaign_id'],[
    'research_agent_id'=>(string)($_POST['research_agent_id']??''),'title'=>(string)($_POST['title']??''),'brief'=>(string)($_POST['brief']??''),'objective'=>(string)($_POST['objective']??''),'questions'=>(string)($_POST['questions']??''),
    'access_mode'=>(string)($_POST['access_mode']??'private'),'budget_currency'=>(string)($_POST['budget_currency']??'USD'),'budget'=>(string)($_POST['budget_amount']??'0'),'max_participants'=>(int)($_POST['max_participants']??0),
    'starts_at'=>(string)($_POST['starts_at']??''),'submission_deadline'=>(string)($_POST['submission_deadline']??''),'review_deadline'=>(string)($_POST['review_deadline']??''),
    'eligibility'=>['min_verification'=>(string)($_POST['minimum_verification']??'basic'),'specialties'=>(string)($_POST['required_specialties']??''),'languages'=>(string)($_POST['required_languages']??''),'min_completed_campaigns'=>(int)($_POST['min_completed_campaigns']??0)],
    'disclosures'=>['sponsorship_disclosure_required'=>isset($_POST['sponsorship_disclosure_required']),'conflict_disclosure_required'=>isset($_POST['conflict_disclosure_required']),'nda_required'=>isset($_POST['nda_required']),'ai_assistance_policy'=>(string)($_POST['ai_assistance_policy']??'allowed_with_disclosure'),'training_use_request'=>(string)($_POST['training_use_request']??'none')],
    'reason'=>(string)($_POST['reason']??'Campaign brief updated.')
   ]);$success='Campaign updated.';$_GET['campaign']=(string)$_POST['campaign_id'];
  }elseif($op==='status'){sponsored_research_campaign_set_status($pdo,$u,(string)$_POST['campaign_id'],(string)$_POST['status']);$success='Campaign status updated.';$_GET['campaign']=(string)$_POST['campaign_id'];}
  elseif($op==='terms'){sponsored_research_campaign_terms_publish($pdo,$u,(string)$_POST['campaign_id'],(string)($_POST['terms_text']??''),(string)($_POST['reason']??'Campaign participation terms updated.'));$success='Participation terms published.';$_GET['campaign']=(string)$_POST['campaign_id'];}
  elseif($op==='invite'){sponsored_research_campaign_invite($pdo,$u,(string)$_POST['campaign_id'],(string)($_POST['researcher']??''),(string)($_POST['expires_at']??''));$success='Researcher invited.';$_GET['campaign']=(string)$_POST['campaign_id'];}
  elseif($op==='review_open'){
    $case=sponsored_research_review_open($pdo,$u,(string)$_POST['submission_id'],['criteria'=>(string)($_POST['criteria']??''),'blind_review'=>isset($_POST['blind_review'])]);
    $success='Review case opened.';$_GET['campaign']=(string)$_POST['campaign_id'];$_GET['review']=(string)$case['public_id'];
  }
  elseif($op==='review_assign'){
    sponsored_research_review_assign($pdo,$u,(string)$_POST['review_id'],(string)($_POST['reviewer']??''),(string)($_POST['reviewer_role']??'independent'));
    $success='Reviewer assigned.';$_GET['campaign']=(string)$_POST['campaign_id'];$_GET['review']=(string)$_POST['review_id'];
  }
  elseif($op==='review_decide'){
    sponsored_research_review_decide($pdo,$u,(string)$_POST['review_id'],(string)($_POST['decision']??''),(string)($_POST['decision_note']??''));
    $success='Final review decision recorded.';$_GET['campaign']=(string)$_POST['campaign_id'];$_GET['review']=(string)$_POST['review_id'];
  }
 }catch(Throwable $e){$error=$e->getMessage();}
}
$campaigns=$sponsor?sponsored_research_campaign_list($pdo,$u,100):[];$selected=null;$versions=[];$events=[];$participants=[];$currentTerms=null;$submissions=[];$reviewCases=[];$selectedReview=null;$reviewResponses=[];
if($sponsor&&!empty($_GET['campaign'])){try{$selected=sponsored_research_campaign_require_manage($pdo,$u,(string)$_GET['campaign']);$versions=sponsored_research_campaign_versions($pdo,$u,(string)$_GET['campaign']);$events=sponsored_research_campaign_events($pdo,$u,(string)$_GET['campaign']);$participants=sponsored_research_campaign_participants($pdo,$u,(string)$_GET['campaign']);$currentTerms=sponsored_research_campaign_terms_latest($pdo,(int)$selected['id']);$submissions=sponsored_research_campaign_submissions($pdo,$u,(string)$_GET['campaign']);$reviewCases=sponsored_research_review_cases_for_campaign($pdo,$u,(string)$_GET['campaign']);if(!empty($_GET['review'])){$selectedReview=sponsored_research_review_case_get($pdo,(string)$_GET['review']);if($selectedReview)$reviewResponses=sponsored_research_review_responses($pdo,(int)$selectedReview['id']);}}catch(Throwable $e){$error=$e->getMessage();}}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sponsored Research · Annotated</title><link rel="stylesheet" href="/assets/css/app.css"></head><body>
<main class="panel" style="max-width:1200px;margin:32px auto"><div class="pageTitle"><span class="eyebrow">PHASE 80 · SPONSORED RESEARCH</span><h1>Sponsored Research Campaigns</h1><p>Create governed research briefs that reuse existing Accounts, Research Agents, Missions, billing, and provenance systems.</p></div>
<?php if($error):?><div class="error"><?=h($error)?></div><?php endif?><?php if($success):?><div class="success"><?=h($success)?></div><?php endif?>
<?php if($sponsor&&$accounts):?>
<section class="card"><h2>New campaign</h2><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="op" value="create">
<label>Commercial account<select name="account_id" required><?php foreach($accounts as $a):?><option value="<?=h((string)$a['public_id'])?>"><?=h((string)$a['name'])?></option><?php endforeach?></select></label>
<label>Research Agent<select name="research_agent_id"><option value="">No Agent yet</option><?php foreach($agents as $a):?><option value="<?=h((string)$a['public_id'])?>"><?=h((string)$a['name'])?></option><?php endforeach?></select></label>
<label>Campaign title<input name="title" maxlength="255" required></label><label>Research brief<textarea name="brief" rows="5" required></textarea></label><label>Objective<textarea name="objective" rows="4" required></textarea></label><label>Research questions<textarea name="questions" rows="6" required placeholder="One question per line"></textarea></label>
<div class="researchAgentEditSplit"><label>Access<select name="access_mode"><option value="private">Private</option><option value="invite_only">Invite only</option><option value="public">Public</option></select></label><label>Currency<input name="budget_currency" value="USD" maxlength="3"></label><label>Budget<input type="number" name="budget_amount" min="0" step="0.01" value="0"></label><label>Max participants<input type="number" name="max_participants" min="1"></label></div>
<div class="researchAgentEditSplit"><label>Starts<input type="datetime-local" name="starts_at"></label><label>Submission deadline<input type="datetime-local" name="submission_deadline"></label><label>Review deadline<input type="datetime-local" name="review_deadline"></label><label>Minimum verification<select name="minimum_verification"><option value="basic">Any approved Research Account</option><option value="identity">Identity</option><option value="qualification">Qualification</option><option value="organization">Organization</option><option value="payout">Payout ready</option></select></label></div>
<label>Required specialties<input name="required_specialties" placeholder="Energy, software, market research"></label><label>Required languages<input name="required_languages" placeholder="English, Spanish"></label><label>Minimum completed campaigns<input type="number" min="0" name="min_completed_campaigns" value="0"></label>
<label><input type="checkbox" name="sponsorship_disclosure_required" value="1" checked> Require sponsorship disclosure</label><label><input type="checkbox" name="conflict_disclosure_required" value="1" checked> Require conflict-of-interest disclosure</label><label><input type="checkbox" name="nda_required" value="1"> Require NDA</label>
<label>AI assistance policy<select name="ai_assistance_policy"><option value="allowed_with_disclosure">Allowed with disclosure</option><option value="unrestricted">Unrestricted</option><option value="restricted">Restricted</option><option value="prohibited">Prohibited</option></select></label>
<label>Training/evaluation use<select name="training_use_request"><option value="none">No training-use request</option><option value="optional_separate_consent">May request separate consent later</option></select></label><p class="meta">Campaign participation never grants training rights. Training/evaluation use requires separate explicit consent.</p><button>Create campaign</button></form></section>
<?php endif?>
<section class="card"><h2>Your sponsored campaigns</h2><?php if(!$campaigns):?><p>No sponsored campaigns yet.</p><?php else:?><table><thead><tr><th>Campaign</th><th>Status</th><th>Access</th><th>Budget</th></tr></thead><tbody><?php foreach($campaigns as $c):?><tr><td><a href="/sponsored-research.php?campaign=<?=rawurlencode((string)$c['public_id'])?>"><strong><?=h((string)$c['title'])?></strong></a><div class="meta"><?=h((string)$c['account_name'])?><?php if($c['research_agent_name']):?> · <?=h((string)$c['research_agent_name'])?><?php endif?></div></td><td><?=h((string)$c['status'])?></td><td><?=h((string)$c['access_mode'])?></td><td><?=h((string)$c['budget_currency'])?> <?=number_format(((int)$c['budget_cents'])/100,2)?></td></tr><?php endforeach?></tbody></table><?php endif?></section>
<?php if($selected):?><section class="card"><span class="eyebrow">CAMPAIGN DETAIL</span><h2><?=h((string)$selected['title'])?></h2><p class="meta">Revision <?=h((string)$selected['current_revision'])?> · Config <?=h(substr((string)$selected['config_hash'],0,12))?>… · <?=h(ucwords(str_replace('_',' ',(string)$selected['status'])))?></p>
<form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="op" value="update"><input type="hidden" name="campaign_id" value="<?=h((string)$selected['public_id'])?>">
<label>Research Agent<select name="research_agent_id"><option value="">No Agent yet</option><?php foreach($agents as $a):?><option value="<?=h((string)$a['public_id'])?>" <?=($selected['research_agent_public_id']??'')===$a['public_id']?'selected':''?>><?=h((string)$a['name'])?></option><?php endforeach?></select></label>
<label>Title<input name="title" maxlength="255" required value="<?=h((string)$selected['title'])?>"></label><label>Objective<textarea name="objective" rows="4" required><?=h((string)$selected['objective'])?></textarea></label><label>Brief<textarea name="brief" rows="6" required><?=h((string)$selected['brief'])?></textarea></label><label>Questions<textarea name="questions" rows="6" required><?=h(implode("\n",array_map(fn($q)=>(string)$q['question'],$selected['questions'])))?></textarea></label>
<div class="researchAgentEditSplit"><label>Access<select name="access_mode"><?php foreach(sponsored_research_campaign_access_modes() as $k=>$label):?><option value="<?=h($k)?>" <?=$selected['access_mode']===$k?'selected':''?>><?=h($label)?></option><?php endforeach?></select></label><label>Budget<input name="budget_amount" inputmode="decimal" value="<?=h(number_format(((int)$selected['budget_cents'])/100,2,'.',''))?>"></label><label>Currency<input name="budget_currency" maxlength="3" value="<?=h((string)$selected['budget_currency'])?>"></label><label>Max participants<input type="number" min="1" name="max_participants" value="<?=h((string)($selected['max_participants']??''))?>"></label></div>
<div class="researchAgentEditSplit"><label>Starts<input type="datetime-local" name="starts_at" value="<?=!empty($selected['starts_at'])?h(date('Y-m-d\TH:i',strtotime((string)$selected['starts_at']))):''?>"></label><label>Submission deadline<input type="datetime-local" name="submission_deadline" value="<?=!empty($selected['submission_deadline'])?h(date('Y-m-d\TH:i',strtotime((string)$selected['submission_deadline']))):''?>"></label><label>Review deadline<input type="datetime-local" name="review_deadline" value="<?=!empty($selected['review_deadline'])?h(date('Y-m-d\TH:i',strtotime((string)$selected['review_deadline']))):''?>"></label></div>
<label>Minimum verification<select name="minimum_verification"><?php foreach(['basic','identity','qualification','organization','payout'] as $v):?><option value="<?=h($v)?>" <?=($selected['eligibility']['min_verification']??'basic')===$v?'selected':''?>><?=h(ucfirst($v))?></option><?php endforeach?></select></label><label>Required specialties<input name="required_specialties" value="<?=h(implode(', ',(array)($selected['eligibility']['specialties']??[])))?>"></label><label>Required languages<input name="required_languages" value="<?=h(implode(', ',(array)($selected['eligibility']['languages']??[])))?>"></label><label>Minimum completed campaigns<input type="number" min="0" name="min_completed_campaigns" value="<?=h((string)($selected['eligibility']['min_completed_campaigns']??0))?>"></label>
<label><input type="checkbox" name="sponsorship_disclosure_required" value="1" <?=!empty($selected['disclosures']['sponsorship_disclosure_required'])?'checked':''?>> Require sponsorship disclosure</label><label><input type="checkbox" name="conflict_disclosure_required" value="1" <?=!empty($selected['disclosures']['conflict_disclosure_required'])?'checked':''?>> Require conflict disclosure</label><label><input type="checkbox" name="nda_required" value="1" <?=!empty($selected['disclosures']['nda_required'])?'checked':''?>> Require NDA</label>
<label>AI assistance policy<select name="ai_assistance_policy"><?php foreach(['allowed_with_disclosure','unrestricted','restricted','prohibited'] as $v):?><option value="<?=h($v)?>" <?=($selected['disclosures']['ai_assistance_policy']??'allowed_with_disclosure')===$v?'selected':''?>><?=h(ucwords(str_replace('_',' ',$v)))?></option><?php endforeach?></select></label><label>Training/evaluation use<select name="training_use_request"><option value="none" <?=($selected['disclosures']['training_use_request']??'none')==='none'?'selected':''?>>No training-use request</option><option value="optional_separate_consent" <?=($selected['disclosures']['training_use_request']??'')==='optional_separate_consent'?'selected':''?>>May request separate consent later</option></select></label>
<label>Change reason<input name="reason" maxlength="1000" placeholder="Why is the campaign brief changing?"></label><button>Save new revision</button></form>
<h3>Status</h3><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="op" value="status"><input type="hidden" name="campaign_id" value="<?=h((string)$selected['public_id'])?>"><select name="status"><?php foreach(sponsored_research_campaign_statuses() as $k=>$label):?><option value="<?=h($k)?>" <?=$selected['status']===$k?'selected':''?>><?=h($label)?></option><?php endforeach?></select><button>Update status</button></form>
<h3>Participation terms</h3>
<form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="op" value="terms"><input type="hidden" name="campaign_id" value="<?=h((string)$selected['public_id'])?>">
<label>Campaign-specific terms<textarea name="terms_text" rows="6" required><?=h((string)($currentTerms['terms_text']??''))?></textarea></label>
<label>Change reason<input name="reason" maxlength="1000" placeholder="Why are the participation terms changing?"></label>
<p class="meta">Terms are versioned against the current campaign revision. Training/evaluation permission is not granted here.</p><button>Publish participation terms</button></form>
<?php if($currentTerms):?><p class="meta">Current terms v<?=h((string)$currentTerms['version_number'])?> · campaign revision <?=h((string)$currentTerms['campaign_revision'])?> · <?=h(substr((string)$currentTerms['terms_hash'],0,12))?>…</p><?php endif?>
<h3>Invite researcher</h3>
<form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="op" value="invite"><input type="hidden" name="campaign_id" value="<?=h((string)$selected['public_id'])?>">
<label>Username or email<input name="researcher" required></label><label>Invite expires<input type="datetime-local" name="expires_at"></label><button>Send invite</button></form>
<h3>Research submissions</h3><?php if(!$submissions):?><p class="meta">No submissions yet.</p><?php else:?><table><thead><tr><th>Researcher</th><th>Submission</th><th>Status</th><th>Revision</th><th>Review</th></tr></thead><tbody><?php foreach($submissions as $s):?><tr><td><?=h((string)$s['display_name'])?><div class="meta">@<?=h((string)$s['username'])?></div></td><td><strong><?=h((string)$s['title'])?></strong><div class="meta"><?=h(mb_substr((string)$s['summary'],0,140))?></div></td><td><?=h((string)$s['status'])?></td><td><?=h((string)$s['current_revision'])?><?php if($s['latest_snapshot_hash']):?> · <?=h(substr((string)$s['latest_snapshot_hash'],0,10))?>…<?php endif?></td><td><?php if((string)$s['status']==='submitted'):?><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="op" value="review_open"><input type="hidden" name="campaign_id" value="<?=h((string)$selected['public_id'])?>"><input type="hidden" name="submission_id" value="<?=h((string)$s['public_id'])?>"><label><input type="checkbox" name="blind_review" value="1" checked> Blind</label><textarea name="criteria" rows="3" placeholder="Evidence strength&#10;Completeness&#10;Methodology&#10;Originality&#10;Adherence to brief"></textarea><button>Open review</button></form><?php else:?>—<?php endif?></td></tr><?php endforeach?></tbody></table><?php endif?>
<h3>Review cases</h3><?php if(!$reviewCases):?><p class="meta">No review cases yet.</p><?php else:?><table><thead><tr><th>Submission</th><th>Researcher</th><th>Status</th><th>Revision</th></tr></thead><tbody><?php foreach($reviewCases as $rc):?><tr><td><a href="/sponsored-research.php?campaign=<?=rawurlencode((string)$selected['public_id'])?>&review=<?=rawurlencode((string)$rc['public_id'])?>"><?=h((string)$rc['submission_title'])?></a></td><td><?=h((string)$rc['researcher_display_name'])?></td><td><?=h((string)$rc['status'])?></td><td><?=h((string)$rc['revision_number'])?></td></tr><?php endforeach?></tbody></table><?php endif?>
<?php if($selectedReview):?><div class="card"><h3>Selected review</h3><p><?=h((string)$selectedReview['submission_title'])?> · revision <?=h((string)$selectedReview['revision_number'])?> · <?=!empty($selectedReview['blind_review'])?'blind':'named'?></p>
<form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="op" value="review_assign"><input type="hidden" name="campaign_id" value="<?=h((string)$selected['public_id'])?>"><input type="hidden" name="review_id" value="<?=h((string)$selectedReview['public_id'])?>"><label>Reviewer username<input name="reviewer" required></label><label>Role<select name="reviewer_role"><option value="independent">Independent</option><option value="subject_matter">Subject matter</option><option value="sponsor">Sponsor</option></select></label><button>Assign reviewer</button></form>
<?php if($reviewResponses):?><h4>Reviewer responses</h4><?php foreach($reviewResponses as $rr):?><div class="meta"><?=h((string)$rr['display_name'])?> · <?=h((string)$rr['reviewer_role'])?> · <?=h((string)$rr['recommendation'])?> · <?=h((string)$rr['created_at'])?></div><?php endforeach?><?php endif?>
<?php if(!in_array((string)$selectedReview['status'],['accepted','rejected','resolved'],true)):?><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="op" value="review_decide"><input type="hidden" name="campaign_id" value="<?=h((string)$selected['public_id'])?>"><input type="hidden" name="review_id" value="<?=h((string)$selectedReview['public_id'])?>"><label>Final decision<select name="decision"><option value="accepted">Accept</option><option value="revision_requested">Request revision</option><option value="rejected">Reject</option></select></label><label>Decision note<textarea name="decision_note" rows="4"></textarea></label><button>Record final decision</button></form><?php endif?></div><?php endif?>
<h3>Participants</h3>
<?php if(!$participants):?><p class="meta">No participants yet.</p><?php else:?><table><thead><tr><th>Researcher</th><th>Status</th><th>Verification</th><th>Terms</th></tr></thead><tbody><?php foreach($participants as $p):?><tr><td><?=h((string)$p['display_name'])?><div class="meta">@<?=h((string)$p['username'])?></div></td><td><?=h((string)$p['status'])?></td><td><?=h((string)$p['verification_level'])?></td><td>v<?=h((string)$p['terms_version'])?></td></tr><?php endforeach?></tbody></table><?php endif?>
<h3>Version history</h3><?php foreach($versions as $v):?><div class="meta">Revision <?=h((string)$v['revision_number'])?> · <?=h((string)$v['created_at'])?> · <?=h(substr((string)$v['config_hash'],0,12))?>…<?php if($v['change_reason']):?> · <?=h((string)$v['change_reason'])?><?php endif?></div><?php endforeach?>
<h3>Campaign event ledger</h3><?php foreach(array_slice($events,0,30) as $e):?><div class="meta"><?=h((string)$e['created_at'])?> · <?=h(ucwords(str_replace('_',' ',(string)$e['event_type'])))?><?php if($e['actor_display_name']):?> · <?=h((string)$e['actor_display_name'])?><?php endif?></div><?php endforeach?></section><?php endif?>
</main></body></html>