<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';
$u=require_user($pdo);header('Cache-Control: private, no-store');$error='';$success='';
$campaignId=(string)($_GET['campaign']??$_POST['campaign_id']??'');if($campaignId==='')exit('Campaign required.');
$campaign=sponsored_research_campaign_require_manage($pdo,$u,$campaignId);$kb=sponsored_research_knowledge_base_for_campaign($pdo,$u,$campaignId);
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();try{
 $op=(string)($_POST['op']??'');
 if($op==='create'){$kb=sponsored_research_knowledge_base_create($pdo,$u,$campaignId,['name'=>(string)($_POST['name']??''),'description'=>(string)($_POST['description']??'')]);$success='Knowledge Base created.';}
 elseif($op==='promote'){$kb??=sponsored_research_knowledge_base_create($pdo,$u,$campaignId,[]);sponsored_research_knowledge_promote($pdo,$u,(string)$kb['public_id'],(string)$_POST['asset_id'],trim((string)($_POST['supersedes_id']??''))?:null);$success='Accepted research promoted into governed Knowledge.';}
 elseif($op==='release'){sponsored_research_knowledge_release_create($pdo,$u,(string)$kb['public_id'],(string)($_POST['note']??''));$success='Immutable Knowledge Base release created.';}
 elseif($op==='withdraw'){sponsored_research_knowledge_item_withdraw($pdo,$u,(string)$_POST['item_id'],(string)($_POST['reason']??''));$success='Knowledge item withdrawn from future use.';}
}catch(Throwable $e){$error=$e->getMessage();}}
$kb=$kb?:sponsored_research_knowledge_base_for_campaign($pdo,$u,$campaignId);$assets=sponsored_research_knowledge_promotable_assets($pdo,$u,$campaignId);$items=$kb?sponsored_research_knowledge_items($pdo,(string)$kb['public_id'],true):[];$releases=$kb?sponsored_research_knowledge_releases($pdo,(string)$kb['public_id']):[];
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sponsored Knowledge · Annotated</title><link rel="stylesheet" href="/assets/css/app.css"></head><body><main class="panel" style="max-width:1200px;margin:32px auto"><div class="pageTitle"><span class="eyebrow">PHASE 80 · KNOWLEDGE</span><h1><?=h((string)$campaign['title'])?></h1><p>Accepted research is promoted explicitly. Releases are immutable; corrections and rights changes create new future-use state without rewriting history.</p></div>
<?php if($error):?><div class="error"><?=h($error)?></div><?php endif?><?php if($success):?><div class="success"><?=h($success)?></div><?php endif?>
<?php if(!$kb):?><section class="card"><h2>Create Knowledge Base</h2><form method="post" class="stack"><?=csrf_field()?><input type="hidden" name="op" value="create"><input type="hidden" name="campaign_id" value="<?=h($campaignId)?>"><label>Name<input name="name" value="<?=h((string)$campaign['title'])?> Knowledge Base" required></label><label>Description<textarea name="description" rows="4"></textarea></label><button>Create Knowledge Base</button></form></section>
<?php else:?><section class="card"><h2><?=h((string)$kb['name'])?></h2><div class="meta">Status <?=h((string)$kb['status'])?> · current release <?=h((string)$kb['current_release_number'])?></div></section>
<section class="card"><h2>Promote accepted research</h2><?php foreach($assets as $a):?><form method="post" class="stack" style="margin-bottom:16px"><?=csrf_field()?><input type="hidden" name="op" value="promote"><input type="hidden" name="campaign_id" value="<?=h($campaignId)?>"><input type="hidden" name="asset_id" value="<?=h((string)$a['public_id'])?>"><strong><?=h((string)$a['asset_type'])?> · <?=h((string)$a['submission_title'])?></strong><div class="meta"><?=h((string)$a['contributor_name'])?> · revision <?=h((string)$a['revision_number'])?> · <?=h((string)$a['asset_public_id'])?></div><label>Corrects existing item public ID (optional)<input name="supersedes_id"></label><button>Promote to Knowledge</button></form><?php endforeach?><?php if(!$assets):?><p>No accepted promotable assets.</p><?php endif?></section>
<section class="card"><h2>Knowledge items</h2><?php foreach($items as $i):?><article><strong><?=h((string)$i['title'])?></strong><div class="meta"><?=h((string)$i['state'])?> · future use <?=$i['future_use_allowed']?'allowed':'blocked'?> · <?=h((string)$i['public_id'])?></div><p><?=h(mb_substr((string)$i['body'],0,300))?></p><?php if($i['state']==='active'):?><form method="post"><?=csrf_field()?><input type="hidden" name="op" value="withdraw"><input type="hidden" name="campaign_id" value="<?=h($campaignId)?>"><input type="hidden" name="item_id" value="<?=h((string)$i['public_id'])?>"><input name="reason" required placeholder="Withdrawal reason"><button>Withdraw from future use</button></form><?php endif?></article><?php endforeach?></section>
<section class="card"><h2>Create immutable release</h2><form method="post" class="stack"><?=csrf_field()?><input type="hidden" name="op" value="release"><input type="hidden" name="campaign_id" value="<?=h($campaignId)?>"><label>Release note<input name="note"></label><button>Create release</button></form><h3>Release history</h3><?php foreach($releases as $r):$st=sponsored_research_knowledge_release_current_use_status($pdo,(string)$r['public_id']);?><div class="meta">v<?=h((string)$r['release_number'])?> · <?=h(substr((string)$r['manifest_hash'],0,12))?>… · <?=$st['usable']?'usable':'blocked: '.h((string)$st['reason'])?></div><?php endforeach?></section><?php endif?>
</main></body></html>