<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';$u=require_user($pdo);header('Cache-Control: private, no-store');header('Vary: Cookie');
$connection=vp3_connector_connection($pdo,(int)$u['id']);$error='';$success='';$artifacts=[];$agents=research_agent_list($pdo,$u,50);$imports=vp3_connector_imports_for_user($pdo,$u);$importMap=[];foreach($imports as $row)$importMap[(string)$row['agent_public_id'].'|'.(string)$row['remote_artifact_id']]=$row;
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();try{$agent=(string)($_POST['agent_id']??'');$remote=(string)($_POST['artifact_id']??'');$parts=[];if(!empty($_POST['import_transcript']))$parts[]='transcript';if(!empty($_POST['import_summary']))$parts[]='summary';$row=vp3_connector_import($pdo,$config,$u,$agent,$remote,$parts);$success='VP3 material added to the Research Agent with source provenance.';$imports=vp3_connector_imports_for_user($pdo,$u);$importMap=[];foreach($imports as $r)$importMap[(string)$r['agent_public_id'].'|'.(string)$r['remote_artifact_id']]=$r;}catch(Throwable $e){$error=$e->getMessage();}}
if($connection)try{$artifacts=vp3_connector_artifacts($pdo,$config,$u);foreach($artifacts as &$a){foreach($imports as $imp)if((string)$imp['remote_artifact_id']===(string)$a['id']&&!hash_equals((string)$imp['remote_version_hash'],(string)$a['version_hash'])){$a['update_available']=true;break;}}unset($a);}catch(Throwable $e){$error=$error?:$e->getMessage();}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>VP3 Library · Annotated</title><meta name="robots" content="noindex,nofollow"><link rel="stylesheet" href="/assets/css/app.css?v=63.0"></head><body data-workspace-user="<?=h((string)$u['public_id'])?>" data-workspace-surface="vp3-library">
<main class="researchLibraryCanvas"><section class="researchLibraryToolbar"><nav class="researchLibraryTabs researchPrimaryActions"><a href="/research.php">Research Agents</a><a class="active" href="/vp3-library.php">VP3 Library</a><a href="/research-monitoring.php">Monitoring</a><a href="/research-tasks.php">Tasks</a><a href="/research-programs.php">Programs</a><a href="/research-intelligence-portfolios.php">Intelligence Portfolios</a></nav></section>
<header class="vp3LibraryHero"><div><span class="eyebrow">VP3 CONNECTION</span><h1>VP3 Library</h1><p>Bring VP3 meeting transcripts and AI summaries into a Research Agent as versioned Annotated evidence. VP3 remains the source system; Annotated preserves the imported snapshot and provenance for validation and deeper research.</p></div><a class="button secondary" href="/settings.php#vp3">Connection settings</a></header>
<?php if(isset($_GET['connected'])):?><div class="success">VP3 account connected.</div><?php endif?><?php if($success):?><div class="success"><?=h($success)?></div><?php endif?><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?>
<?php if(!$connection):?><section class="card vp3LibraryDisconnected"><h2>Connect your VP3 account</h2><p>Authorize Annotated to read the VP3 meeting transcripts and AI summaries you can access.</p><a class="button" href="/vp3/connect.php?mode=connect">Connect VP3 Account</a></section><?php else:?>
<section class="vp3LibraryStatus card"><div><strong><?=h((string)($connection['vp3_display_name']?:'VP3 account'))?></strong><span><?=h((string)$connection['vp3_email'])?></span></div><span class="badge">Connected</span></section>
<section class="vp3LibraryGrid"><?php if(!$artifacts):?><div class="card empty"><h3>No VP3 meeting artifacts available.</h3><p>Completed VP3 meetings with transcripts will appear here.</p></div><?php endif?><?php foreach($artifacts as $a):?>
<article class="card vp3ArtifactCard"><header><div><span class="eyebrow">VP3 MEETING</span><h2><?=h((string)$a['title'])?></h2></div><?php if(!empty($a['update_available'])):?><span class="badge">Update available</span><?php endif?></header><p class="meta"><?=h((string)$a['start_at_utc'])?> · <?=h(ucfirst((string)$a['status']))?> · <?=h((string)$a['segment_count'])?> transcript segments</p><div class="vp3ArtifactAvailability"><span class="<?=!empty($a['transcript_available'])?'is-ready':''?>">Transcript <?=!empty($a['transcript_available'])?'ready':'not ready'?></span><span class="<?=!empty($a['summary_available'])?'is-ready':''?>">AI summary <?=!empty($a['summary_available'])?'ready':'not available'?></span></div>
<form method="post" class="vp3ArtifactImport"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="artifact_id" value="<?=h((string)$a['id'])?>"><label>Research Agent<select name="agent_id" required><?php foreach($agents as $agent):?><option value="<?=h((string)$agent['public_id'])?>"><?=h((string)$agent['name'])?><?=!empty($agent['team_name'])?' · '.h((string)$agent['team_name']):''?></option><?php endforeach?></select></label><div class="vp3ImportChecks"><label><input type="checkbox" name="import_transcript" value="1" <?=!empty($a['transcript_available'])?'checked':'disabled'?>> Transcript</label><label><input type="checkbox" name="import_summary" value="1" <?=!empty($a['summary_available'])?'checked':'disabled'?>> AI summary</label></div><button <?=!$agents||empty($a['transcript_available'])&&empty($a['summary_available'])?'disabled':''?>><?=!empty($a['update_available'])?'Update Research snapshot':'Add to Research Agent'?></button></form></article><?php endforeach?></section>
<?php if($imports):?><section class="card vp3ImportHistory"><span class="eyebrow">IMPORTED RESEARCH</span><h2>VP3 provenance</h2><?php foreach(array_slice($imports,0,30) as $imp):?><div><span><strong><?=h((string)$imp['title'])?></strong><small><?=h((string)$imp['agent_name'])?> · <?=h(implode(' + ',(array)$imp['parts']))?> · imported <?=h((string)$imp['imported_at'])?></small></span><a href="/research-project.php?id=<?=rawurlencode((string)$imp['project_public_id'])?>">Open Agent files</a></div><?php endforeach?></section><?php endif?>
<?php endif?></main></body></html>