<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=(string)getenv('DB_DSN');$dbUser=(string)getenv('DB_USER');$dbPass=(string)getenv('DB_PASS');if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
foreach(['installer','functions','concurrency','subscriptions','account-admin','account-membership','stripe-billing','billing-operations','ai-usage','ai-overage-billing','commercial-promotions','commercial-billing','admin-operations'] as $lib)require_once $root.'/app/'.$lib.'.php';
function av20(bool $ok,string $m): void {if(!$ok)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}
$run='av20'.substr(bin2hex(random_bytes(5)),0,10);$pub=fn(string $p)=>$p.'-'.$run.'-'.substr(bin2hex(random_bytes(3)),0,6);
$makeUser=function(string $name,string $role='user')use($pdo,$run,$pub): array{$username=substr(strtolower($name).'_'.$run,0,48);$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,status,role,plan_tier,live_presence_mode) VALUES(?,?,?,?, 'active',?,'free','cloaked')")->execute([$pub('u'),$username,$name,$username.'@example.test',$role]);$id=(int)$pdo->lastInsertId();$q=$pdo->prepare('SELECT * FROM users WHERE id=?');$q->execute([$id]);return $q->fetch();};
av20(admin_ops_ready($pdo),'Migration 073 operations schema is ready.');
$admin=$makeUser('OpsAdmin','admin');$user=$makeUser('OpsUser');
$profile=admin_ops_operator_profile($pdo,$admin);av20($profile['role_key']==='super_admin'&&admin_ops_has_capability($profile,'admin.billing.sync'),'New site administrators inherit V2.0 super-admin capability groundwork without weakening existing role authorization.');
$package=subscription_package_create($pdo,$admin,['name'=>'Ops Package','slug'=>'ops-'.$run,'legacy_plan_tier'=>'pro','monthly_price'=>'25.00','monthly_ai_token_allowance'=>'1000','member_limit'=>'2','trial_days'=>'0','sort_order'=>'999','is_public'=>'1','status'=>'active']);
$account=subscription_ensure_user_account($pdo,(int)$user['id'],(int)$admin['id']);$account=subscription_assign_user_package($pdo,$admin,(int)$user['id'],(string)$package['public_id'],'V2.0 operations test.');
$account=account_admin_update_lifecycle($pdo,$admin,(string)$account['public_id'],['name'=>$account['name'],'status'=>'suspended','subscription_status'=>$account['subscription_status'],'reason'=>'Exercise V2.0 Needs Attention.']);
$scan=admin_ops_refresh_alerts($pdo);av20((int)$scan['observed']>=1,'Operations scan materializes current authoritative source conditions.');
$q=$pdo->prepare("SELECT * FROM admin_operations_alerts WHERE account_id=? AND source_type='account_suspended' ORDER BY id DESC LIMIT 1");$q->execute([(int)$account['id']]);$alert=$q->fetch();av20($alert&&$alert['status']==='open','Suspended account becomes a durable open Needs Attention item.');
$assigned=admin_ops_alert_update($pdo,$admin,(string)$alert['public_id'],'assign',['user_id'=>(int)$admin['id'],'reason'=>'Assign V2.0 test alert.']);av20((int)$assigned['assigned_user_id']===(int)$admin['id'],'Operational alert supports durable Admin ownership.');
$snoozed=admin_ops_alert_update($pdo,$admin,(string)$alert['public_id'],'snooze',['hours'=>4,'reason'=>'Pause while account state is investigated.']);av20($snoozed['status']==='snoozed'&&!empty($snoozed['snoozed_until']),'Operational alert supports reasoned snooze state.');
$resolved=admin_ops_alert_update($pdo,$admin,(string)$alert['public_id'],'resolve',['reason'=>'Temporarily marked resolved for persistence test.']);av20($resolved['status']==='resolved','Operational alert supports explicit reasoned resolution.');
admin_ops_refresh_alerts($pdo);$q->execute([(int)$account['id']]);$reopened=$q->fetch();av20($reopened['status']==='open','A still-active source condition reopens a manually resolved alert instead of hiding the issue.');
$account=account_admin_update_lifecycle($pdo,$admin,(string)$account['public_id'],['name'=>$account['name'],'status'=>'active','subscription_status'=>$account['subscription_status'],'reason'=>'Resolve V2.0 source condition.']);admin_ops_refresh_alerts($pdo);$q->execute([(int)$account['id']]);$auto=$q->fetch();av20($auto['status']==='resolved'&&str_contains((string)$auto['resolution_note'],'source condition'),'Alert auto-resolves after the authoritative source condition disappears.');
$view=admin_ops_saved_view_save($pdo,$admin,'Danger queue',['severity'=>'danger','assigned'=>'me'],true);av20($view['name']==='Danger queue'&&(int)$view['is_default']===1,'Command Center filters can be persisted as a default saved view.');
$search=admin_ops_global_search($pdo,(string)$account['public_id'],20);av20((bool)array_filter($search,fn($r)=>$r['type']==='Account'&&$r['identifier']===$account['public_id']),'Global operations search resolves canonical account identifiers.');
$preview=admin_ops_action_preview($pdo,$admin,'reconcile_ai_overage',(string)$account['public_id'],'Validate governed preview and execution.');av20($preview['record']['status']==='previewed'&&$preview['preview']['risk_level']==='elevated','Governed action creates a durable preview before execution.');
$executed=admin_ops_action_execute($pdo,[],$admin,(string)$preview['record']['public_id']);av20($executed['status']==='executed'&&!empty($executed['correlation_id']),'Governed action claims, executes and records one correlated result.');
$timeline=admin_ops_account_timeline($pdo,(int)$account['id'],200);$sources=array_column($timeline,'source');av20(in_array('account',$sources,true)&&in_array('admin_action',$sources,true),'Account 360 timeline merges existing account events with V2.0 governed actions.');
$ops360=admin_ops_account_360($pdo,(int)$account['id']);av20(isset($ops360['stripe'],$ops360['billing_profile'],$ops360['benefits'],$ops360['overage'],$ops360['timeline']),'Account 360 aggregates commercial systems without replacing their source ledgers.');
$q=$pdo->prepare("SELECT COUNT(*) FROM admin_action_records WHERE actor_user_id=? AND action_type LIKE 'alert_%'");$q->execute([(int)$admin['id']]);av20((int)$q->fetchColumn()>=3,'Alert ownership/snooze/resolution changes are themselves recorded in the governed Admin action ledger.');
echo "Admin V2.0 unified operations command center database journey passed.\n";
