<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=(string)getenv('DB_DSN');$dbUser=(string)getenv('DB_USER');$dbPass=(string)getenv('DB_PASS');if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
foreach(['installer','functions','subscriptions','account-admin','stripe-billing','ai-usage'] as $lib)require_once $root.'/app/'.$lib.'.php';
function av140(bool $ok,string $m):void{if(!$ok)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}
function av140throws(callable $fn,string $m):void{try{$fn();}catch(Throwable $e){echo "PASS: $m\n";return;}throw new RuntimeException('FAIL: '.$m);}
function av140signed(array $event,string $secret):array{$payload=json_encode($event,JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);$t=time();$sig='t='.$t.',v1='.hash_hmac('sha256',$t.'.'.$payload,$secret);return [$payload,$sig];}
av140(stripe_billing_ready($pdo),'Migration 065 Stripe billing schema is ready.');
$run='av140'.substr(bin2hex(random_bytes(5)),0,10);$seq=0;$pub=function(string $p)use($run,&$seq):string{$seq++;return $p.'-'.$run.'-'.$seq;};
$mk=function(string $name,string $role='user')use($pdo,$run,$pub):array{$u=strtolower($name).'_'.$run;$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,status,role,plan_tier,live_presence_mode) VALUES(?,?,?,?, 'active',?,'free','cloaked')")->execute([$pub('u'),$u,$name,$u.'@example.test',$role]);$id=(int)$pdo->lastInsertId();$q=$pdo->prepare('SELECT * FROM users WHERE id=?');$q->execute([$id]);return $q->fetch();};
$admin=$mk('StripeAdmin','admin');$user=$mk('StripeUser');$other=$mk('StripeOther');
$teamBefore=(int)$pdo->query('SELECT COUNT(*) FROM teams')->fetchColumn();$account=subscription_ensure_user_account($pdo,(int)$user['id'],(int)$admin['id']);$otherAccount=subscription_ensure_user_account($pdo,(int)$other['id'],(int)$admin['id']);
$secret='whsec_'.$run;stripe_billing_save_settings($pdo,['app'=>['encryption_key'=>'v140-test-encryption-key-abcdefghijklmnopqrstuvwxyz']],$admin,['mode'=>'test','publishable_key'=>'pk_test_'.$run,'secret_key'=>'sk_test_'.$run,'webhook_secret'=>$secret,'checkout_success_path'=>'/billing.php?checkout=success','checkout_cancel_path'=>'/billing.php?checkout=cancelled','portal_return_path'=>'/billing.php']);
$settings=stripe_billing_settings($pdo);av140($settings['mode']==='test'&&!empty($settings['secret_key_ciphertext'])&&!empty($settings['webhook_secret_ciphertext']),'Stripe settings encrypt secret and webhook keys.');
$basic=subscription_package($pdo,'basic-user');$team=subscription_package($pdo,'team-builder');if(!$basic||!$team)throw new RuntimeException('Seeded paid packages are required.');
$org=account_admin_create($pdo,$admin,['name'=>'Stripe Org '.$run,'account_type'=>'organization','owner'=>$user['username'],'package_id'=>$team['public_id'],'reason'=>'V1.40 organization billing authorization fixture.']);account_admin_add_member($pdo,$admin,(string)$org['public_id'],$other['username'],'member','Ordinary member must not receive billing authority.');
$billingAccounts=stripe_billing_user_accounts($pdo,$user);av140(count($billingAccounts)>=2,'Account owner can see personal and organization billing accounts.');$resolvedOrg=stripe_billing_account_for_user($pdo,$user,(string)$org['public_id']);av140((int)$resolvedOrg['id']===(int)$org['id'],'Organization owner can open organization billing workspace.');av140throws(fn()=>stripe_billing_account_for_user($pdo,$other,(string)$org['public_id']),'Ordinary organization member cannot administer billing.');
$priceId='price_'.$run;$productId='prod_'.$run;$pdo->prepare("INSERT INTO stripe_package_prices(public_id,package_id,mode,stripe_product_id,stripe_price_id,currency,unit_amount_cents,billing_interval,active,created_by_user_id) VALUES(?,?, 'test',?,?, 'usd',2999,'month',1,?)")->execute([$pub('spp'),(int)$basic['id'],$productId,$priceId,(int)$admin['id']]);
$customerId='cus_'.$run;stripe_billing_link_customer($pdo,(int)$account['id'],'test',$customerId,$user['email'],$account['name'],['fixture'=>'v140']);
av140throws(fn()=>stripe_billing_link_customer($pdo,(int)$otherAccount['id'],'test',$customerId,$other['email'],$otherAccount['name'],[]),'A Stripe Customer cannot be linked to two Annotated accounts in the same mode.');
$stripeSameIdLive=stripe_billing_link_customer($pdo,(int)$otherAccount['id'],'live',$customerId,$other['email'],$otherAccount['name'],['fixture'=>'v140-live']);av140((int)$stripeSameIdLive['account_id']===(int)$otherAccount['id']&&$stripeSameIdLive['mode']==='live','Test and live Stripe modes can safely reuse the same provider object ID.');
$now=time();$subId='sub_'.$run;$subEvent=['id'=>'evt_sub_'.$run,'type'=>'customer.subscription.created','created'=>$now,'livemode'=>false,'data'=>['object'=>['id'=>$subId,'customer'=>$customerId,'status'=>'active','cancel_at_period_end'=>false,'current_period_start'=>$now,'current_period_end'=>$now+2592000,'metadata'=>['annotated_account_id'=>$account['public_id'],'annotated_package_id'=>$basic['public_id']],'items'=>['data'=>[['price'=>['id'=>$priceId]]]]]]];
[$payload,$sig]=av140signed($subEvent,$secret);av140throws(fn()=>stripe_billing_process_webhook($pdo,['app'=>['encryption_key'=>'v140-test-encryption-key-abcdefghijklmnopqrstuvwxyz']],$payload,'t='.time().',v1=deadbeef'),'Invalid Stripe webhook signature is rejected before synchronization.');$result=stripe_billing_process_webhook($pdo,['app'=>['encryption_key'=>'v140-test-encryption-key-abcdefghijklmnopqrstuvwxyz']],$payload,$sig);av140(!empty($result['ok'])&&empty($result['duplicate']),'Signed subscription webhook is processed.');
$account=subscription_user_account($pdo,(int)$user['id'],false);av140($account&&$account['package_slug']==='basic-user'&&$account['billing_source']==='stripe'&&$account['subscription_status']==='active','Stripe subscription makes mapped package and billing source authoritative.');
av140(user_plan($pdo,$user)==='pro','Stripe-paid package synchronizes legacy Pro compatibility.');
$duplicate=stripe_billing_process_webhook($pdo,['app'=>['encryption_key'=>'v140-test-encryption-key-abcdefghijklmnopqrstuvwxyz']],$payload,$sig);av140(!empty($duplicate['duplicate']),'Webhook event replay is idempotently ignored.');
$liveClaim=stripe_billing_claim_webhook($pdo,$subEvent['id'],'live','fixture.live','obj_'.$run,hash('sha256','live-'.$run));av140(!empty($liveClaim['claimed']),'Identical Stripe event IDs remain isolated between test and live mode.');stripe_billing_finish_webhook($pdo,'live',$subEvent['id'],'ignored');
stripe_billing_event($pdo,(int)$account['id'],'stripe','retry_fixture_a','Retry fixture.','evt_audit_'.$run);stripe_billing_event($pdo,(int)$account['id'],'stripe','retry_fixture_b','Retry fixture.','evt_audit_'.$run);stripe_billing_event($pdo,(int)$account['id'],'stripe','retry_fixture_a','Retry fixture.','evt_audit_'.$run);$q=$pdo->prepare("SELECT COUNT(*) FROM account_billing_events WHERE account_id=? AND stripe_event_id=?");$q->execute([(int)$account['id'],'evt_audit_'.$run]);av140((int)$q->fetchColumn()===2,'Billing audit permits multiple event types while suppressing retry duplicates.');
$tampered=$subEvent;$tampered['data']['object']['status']='past_due';[$tamperedPayload,$tamperedSig]=av140signed($tampered,$secret);av140throws(fn()=>stripe_billing_process_webhook($pdo,['app'=>['encryption_key'=>'v140-test-encryption-key-abcdefghijklmnopqrstuvwxyz']],$tamperedPayload,$tamperedSig),'Existing Stripe event ID cannot be replayed with a different payload hash.');
$q=$pdo->prepare('SELECT COUNT(*) FROM stripe_webhook_events WHERE stripe_event_id=?');$q->execute([$subEvent['id']]);av140((int)$q->fetchColumn()===1,'Webhook ledger stores one row per Stripe event ID.');
av140throws(fn()=>subscription_assign_user_package($pdo,$admin,(int)$user['id'],(string)$team['public_id'],'Manual drift attempt.'),'Stripe-managed account rejects legacy Admin user package reassignment.');
av140throws(fn()=>account_admin_change_package($pdo,$admin,(string)$account['public_id'],(string)$team['public_id'],'Manual drift attempt.'),'Stripe-managed account rejects Account Admin package reassignment.');
av140throws(fn()=>account_admin_update_lifecycle($pdo,$admin,(string)$account['public_id'],['name'=>$account['name'],'status'=>'active','subscription_status'=>'paused','reason'=>'Manual Stripe state drift attempt.']),'Stripe-managed subscription status cannot be manually rewritten.');
$account=account_admin_update_lifecycle($pdo,$admin,(string)$account['public_id'],['name'=>$account['name'],'status'=>'suspended','subscription_status'=>'active','reason'=>'Product suspension remains local authority.']);av140($account['status']==='suspended'&&user_plan($pdo,$user)==='free','Annotated can suspend product access without mutating Stripe subscription state.');
$account=account_admin_update_lifecycle($pdo,$admin,(string)$account['public_id'],['name'=>$account['name'],'status'=>'active','subscription_status'=>'active','reason'=>'Restore product access.']);av140($account['status']==='active'&&user_plan($pdo,$user)==='pro','Restoring account access preserves Stripe-paid Pro state.');
$invoiceId='in_'.$run;$failed=['id'=>'evt_fail_'.$run,'type'=>'invoice.payment_failed','created'=>$now+10,'livemode'=>false,'data'=>['object'=>['id'=>$invoiceId,'customer'=>$customerId,'subscription'=>$subId,'status'=>'open','currency'=>'usd','amount_due'=>2999,'amount_paid'=>0,'amount_remaining'=>2999,'number'=>'INV-'.$run,'lines'=>['data'=>[['period'=>['start'=>$now,'end'=>$now+2592000]]]],'status_transitions'=>[]]]];[$p2,$s2]=av140signed($failed,$secret);stripe_billing_process_webhook($pdo,['app'=>['encryption_key'=>'v140-test-encryption-key-abcdefghijklmnopqrstuvwxyz']],$p2,$s2);$account=subscription_user_account($pdo,(int)$user['id'],false);av140($account&&$account['subscription_status']==='past_due','invoice.payment_failed moves Stripe account into past_due grace state.');av140(user_plan($pdo,$user)==='pro','past_due remains in access grace and does not immediately remove Pro.');
$paid=['id'=>'evt_paid_'.$run,'type'=>'invoice.paid','created'=>$now+20,'livemode'=>false,'data'=>['object'=>['id'=>$invoiceId,'customer'=>$customerId,'subscription'=>$subId,'status'=>'paid','currency'=>'usd','amount_due'=>2999,'amount_paid'=>2999,'amount_remaining'=>0,'number'=>'INV-'.$run,'hosted_invoice_url'=>'https://invoice.stripe.test/'.$run,'invoice_pdf'=>'https://invoice.stripe.test/'.$run.'.pdf','lines'=>['data'=>[['period'=>['start'=>$now,'end'=>$now+2592000]]]],'status_transitions'=>['paid_at'=>$now+60]]]];[$p3,$s3]=av140signed($paid,$secret);stripe_billing_process_webhook($pdo,['app'=>['encryption_key'=>'v140-test-encryption-key-abcdefghijklmnopqrstuvwxyz']],$p3,$s3);$account=subscription_user_account($pdo,(int)$user['id'],false);av140($account&&$account['subscription_status']==='active','invoice.paid restores active Stripe subscription state.');
$refund=['id'=>'evt_refund_'.$run,'type'=>'charge.refunded','created'=>$now+30,'livemode'=>false,'data'=>['object'=>['id'=>'ch_'.$run,'customer'=>$customerId]]];[$p4,$s4]=av140signed($refund,$secret);stripe_billing_process_webhook($pdo,['app'=>['encryption_key'=>'v140-test-encryption-key-abcdefghijklmnopqrstuvwxyz']],$p4,$s4);$q=$pdo->prepare("SELECT COUNT(*) FROM account_billing_events WHERE account_id=? AND event_type='charge_refunded'");$q->execute([(int)$account['id']]);av140((int)$q->fetchColumn()===1,'Refund webhook is preserved in account billing audit.');
$deleted=$subEvent;$deleted['id']='evt_cancel_'.$run;$deleted['type']='customer.subscription.deleted';$deleted['created']=$now+120;$deleted['data']['object']['status']='canceled';$deleted['data']['object']['canceled_at']=$now+120;$deleted['data']['object']['ended_at']=$now+120;[$p5,$s5]=av140signed($deleted,$secret);stripe_billing_process_webhook($pdo,['app'=>['encryption_key'=>'v140-test-encryption-key-abcdefghijklmnopqrstuvwxyz']],$p5,$s5);$account=subscription_user_account($pdo,(int)$user['id'],false);av140($account&&$account['subscription_status']==='canceled','Deleted Stripe subscription cancels local subscription state.');av140(user_plan($pdo,$user)==='free','Canceled Stripe subscription removes legacy Pro access without deleting package history.');
$stale=$subEvent;$stale['id']='evt_stale_'.$run;$stale['type']='customer.subscription.updated';$stale['created']=$now+60;$stale['data']['object']['status']='active';[$sp,$ss]=av140signed($stale,$secret);stripe_billing_process_webhook($pdo,['app'=>['encryption_key'=>'v140-test-encryption-key-abcdefghijklmnopqrstuvwxyz']],$sp,$ss);$account=subscription_user_account($pdo,(int)$user['id'],false);av140($account&&$account['subscription_status']==='canceled','Out-of-order older Stripe event cannot roll a newer canceled subscription backward.');
$q=$pdo->prepare('SELECT COUNT(*) FROM stripe_invoices WHERE account_id=? AND stripe_invoice_id=?');$q->execute([(int)$account['id'],$invoiceId]);av140((int)$q->fetchColumn()===1,'Invoice ledger upserts one durable invoice record across payment state changes.');
$orgCustomer='cus_org_'.$run;stripe_billing_link_customer($pdo,(int)$org['id'],'test',$orgCustomer,$user['email'],$org['name'],['fixture'=>'org']);
$orgEvent=['id'=>'evt_org_'.$run,'type'=>'customer.subscription.created','created'=>$now+200,'livemode'=>false,'data'=>['object'=>['id'=>'sub_org_'.$run,'customer'=>$orgCustomer,'status'=>'active','cancel_at_period_end'=>false,'current_period_start'=>$now,'current_period_end'=>$now+2592000,'metadata'=>['annotated_account_id'=>$org['public_id'],'annotated_package_id'=>$basic['public_id']],'items'=>['data'=>[['price'=>['id'=>$priceId]]]]]]];[$op,$os]=av140signed($orgEvent,$secret);stripe_billing_process_webhook($pdo,['app'=>['encryption_key'=>'v140-test-encryption-key-abcdefghijklmnopqrstuvwxyz']],$op,$os);$orgAfter=account_admin_get($pdo,(int)$org['id']);av140($orgAfter&&$orgAfter['package_slug']==='basic-user','Stripe package change remains authoritative even when it lowers the package member limit.');$over=stripe_billing_over_capacity_account_ids($pdo);av140(in_array((int)$org['id'],$over,true),'Over-capacity Stripe-synced account is flagged for Admin attention instead of rejecting the webhook.');
av140((int)$pdo->query('SELECT COUNT(*) FROM teams')->fetchColumn()===$teamBefore,'Stripe billing never creates or changes Research Teams.');
echo "Admin V1.40 Stripe billing database journey passed.\n";