<?php
declare(strict_types=1);
$root=dirname(__DIR__);$fail=[];
$need=function(string $file,string $needle,string $message)use(&$fail,$root){$p=$root.'/'.$file;if(!is_file($p)){$fail[]='Missing '.$file;return;}if(!str_contains((string)file_get_contents($p),$needle))$fail[]=$message;};
$m='database/migrations/20260924_076_admin_financial_reporting_reconciliation.sql';
foreach(['admin_finance_reconciliation_exceptions','admin_finance_reconciliation_events','admin_finance_period_closes','admin_finance_exports','admin.finance.view','admin.finance.manage','admin.finance.export'] as $n)$need($m,$n,'Migration 076 missing '.$n);
foreach(['function admin_finance_ready','function admin_finance_metrics','function admin_finance_receivables','function admin_finance_scan','function admin_finance_exception_update','function admin_finance_period_close','function admin_finance_account_ledger','function admin_finance_export','function admin_finance_agent_context'] as $n)$need('app/admin-finance.php',$n,'Admin V2.30 finance runtime missing '.$n);
$need('app/admin-finance.php',"in_array(\$v[0],['=','+','-','@'],true)",'Finance CSV export must neutralize spreadsheet formula injection.');
$need('app/admin-finance.php','subtotal_cents=0 AND amount_due_cents<>0','Finance reporting must preserve invoice value for pre-V1.90 rows awaiting enrichment.');
$need('app/admin-access.php',"'admin.finance.view'",'Finance view capability must be registered.');
$need('app/admin-access.php',"'admin.finance.manage'",'Finance manage capability must be registered.');
$need('app/admin-access.php',"'admin.finance.export'",'Finance export capability must be registered.');
$need('app/admin-access.php',"'/admin/financial-reporting.php'=>['admin.finance.view','admin.finance.manage']", 'Financial Reporting route must separate view and mutation authority.');
$need('app/admin-access.php',"'/admin/financial-export.php'=>['admin.finance.export','admin.finance.export']", 'Finance export endpoint must require explicit export capability.');
$need('app/admin-ui.php',"'financial_reporting'=>['label'=>'Financial Reporting'",'Shared Admin navigation must expose Financial Reporting.');
$need('app/admin-ui.php','Admin V2.30','Shared Admin shell must identify V2.30.');
foreach(['ADMIN V2.30 · FINANCIAL REPORTING & RECONCILIATION','Finance workspace','RECONCILIATION','RECEIVABLE AGING','PERIOD CLOSE','CLOSE LEDGER','ACCOUNT FINANCIAL LEDGER','AUDITED EXPORTS'] as $n)$need('admin/financial-reporting.php',$n,'Financial Reporting workspace missing '.$n);
$need('admin/financial-export.php',"Content-Type: text/csv",'Finance export endpoint must return CSV content.');
$need('admin/index.php','Finance exceptions','Command Center must surface finance exceptions.');
$need('admin/index.php','FINANCIAL REPORTING','Command Center must link Finance workspace.');
$need('admin/account.php','ADMIN V2.30 · FINANCE','Account 360 must surface financial summary.');
$need('admin/support.php',"new_title",'Support creation must accept Finance prefill handoff.');
$need('app/agent-chat.php','admin_finance_agent_context','Admin Agent must receive read-only V2.30 finance context.');
$need('app/agent-chat.php','Admin V2.30 finance context is read-only','Agent prompt must deny finance mutation claims.');
$need('assets/css/app.css','.adminSidebar~main.panel{','Admin shell must explicitly override the generic panel container.');
$need('assets/css/app.css','background:#f7f7f5;','Admin content canvas must use the page background.');
$need('assets/css/app.css','border:0;','Admin outer content canvas must remove the generic panel border.');
$need('assets/css/app.css','margin:0 0 0 268px;','Admin main workspace must consume the right-side width from the fixed sidebar.');
$need('tests/ci/run-full-regression.sh','tests/admin-v2-30-financial-reporting-db.php','Full regression must execute V2.30 finance database journey.');
$need('.github/workflows/full-regression.yml','admin-v2-30-upgrade-from-075.php','Phase gate must rehearse migration 076 from 075.');
$need('.github/workflows/package-two-zips.yml','20260924_076_admin_financial_reporting_reconciliation.sql','Production package must include migration 076.');
$need('tests/ci/package-smoke.sh','admin-v2-30-financial-reporting.md','Release smoke must require V2.30 files.');
if($fail){foreach($fail as $f)fwrite(STDERR,"FAIL: $f\n");exit(1);}echo "Admin V2.30 Financial Reporting static contract passed.\n";
