<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=(string)getenv('DB_DSN');$dbUser=(string)getenv('DB_USER');$dbPass=(string)getenv('DB_PASS');if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
foreach(['installer','functions','concurrency','subscriptions','account-admin','account-membership','stripe-billing','billing-operations','ai-usage','ai-overage-billing','commercial-promotions','commercial-billing','admin-operations','admin-access','admin-support','admin-finance'] as $lib)require_once $root.'/app/'.$lib.'.php';
function av230(bool $ok,string $m): void {if(!$ok)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}
$run='av230'.substr(bin2hex(random_bytes(5)),0,10);$pub=fn(string $p)=>$p.'-'.$run.'-'.substr(bin2hex(random_bytes(3)),0,6);
$makeUser=function(string $name,string $role='user')use($pdo,$run,$pub): array{$username=substr(strtolower($name).'_'.$run,0,48);$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,status,role,plan_tier,live_presence_mode) VALUES(?,?,?,?, 'active',?,'free','cloaked')")->execute([$pub('u'),$username,$name,$username.'@example.test',$role]);$id=(int)$pdo->lastInsertId();$q=$pdo->prepare('SELECT * FROM users WHERE id=?');$q->execute([$id]);return $q->fetch();};
av230(admin_finance_ready($pdo),'Migration 076 finance schema is ready.');
$super=$makeUser('FinanceOwner','admin');$billing=$makeUser('FinanceOperator','admin');$auditor=$makeUser('FinanceAuditor','admin');$accountViewer=$makeUser('AccountOnlyFinanceTest','admin');$customer=$makeUser('FinanceCustomer');
admin_access_profile($pdo,$super);$billingRole=admin_access_role($pdo,'billing_admin');$auditorRole=admin_access_role($pdo,'read_only_auditor');if(!$billingRole||!$auditorRole)throw new RuntimeException('Seeded Admin roles missing.');
admin_access_assign_operator($pdo,$super,(int)$billing['id'],(string)$billingRole['public_id'],'active','Delegate V2.30 finance operations.');admin_access_assign_operator($pdo,$super,(int)$auditor['id'],(string)$auditorRole['public_id'],'active','Delegate V2.30 finance audit visibility.');$accountRole=admin_access_role_save($pdo,$super,['name'=>'Finance account viewer '.$run,'role_key'=>'finance_account_view_'.$run,'description'=>'Negative finance isolation role.','capabilities'=>['admin.operations.view','admin.accounts.view'],'status'=>'active','reason'=>'Create V2.30 isolation role.']);admin_access_assign_operator($pdo,$super,(int)$accountViewer['id'],(string)$accountRole['public_id'],'active','Exercise account access without finance access.');
av230(admin_access_has_capability($pdo,$billing,'admin.finance.manage')&&admin_access_has_capability($pdo,$billing,'admin.finance.export'),'Billing Admin receives finance management and export authority.');
av230(admin_access_has_capability($pdo,$auditor,'admin.finance.view')&&!admin_access_has_capability($pdo,$auditor,'admin.finance.manage')&&!admin_access_has_capability($pdo,$auditor,'admin.finance.export'),'Read-only Auditor sees Finance but cannot mutate or export.');
av230(!admin_access_has_capability($pdo,$accountViewer,'admin.finance.view'),'Account-only delegated Admin remains isolated from finance evidence.');
av230(admin_access_route_requirement('/admin/financial-reporting.php','GET')==='admin.finance.view'&&admin_access_route_requirement('/admin/financial-reporting.php','POST')==='admin.finance.manage'&&admin_access_route_requirement('/admin/financial-export.php','GET')==='admin.finance.export','Finance routes enforce view, manage and export capabilities.');
$package=subscription_package_create($pdo,$super,['name'=>'Finance Package '.$run,'slug'=>'finance-'.$run,'legacy_plan_tier'=>'pro','monthly_price'=>'25.00','monthly_ai_token_allowance'=>'1000','member_limit'=>'3','trial_days'=>'0','sort_order'=>'999','is_public'=>'1','status'=>'active']);
$account=subscription_ensure_user_account($pdo,(int)$customer['id'],(int)$super['id']);$account=subscription_assign_user_package($pdo,$super,(int)$customer['id'],(string)$package['public_id'],'V2.30 finance test package.');$mode=admin_finance_mode($pdo);$today=gmdate('Y-m-d');$yesterday=gmdate('Y-m-d',time()-86400);$periodStart=gmdate('Y-m-01');$periodEnd=gmdate('Y-m-t');$baseline=admin_finance_metrics($pdo,$yesterday,$today);
$invoice1='in_'.$run.'_paid';$invoice2='in_'.$run.'_overdue';
$pdo->prepare("INSERT INTO stripe_invoices(public_id,account_id,mode,stripe_invoice_id,stripe_customer_id,status,currency,amount_due_cents,amount_paid_cents,amount_remaining_cents,subtotal_cents,discount_amount_cents,tax_amount_cents,total_cents,invoice_number,period_start,period_end,due_at,paid_at,finalized_at) VALUES(?,?,?,?,?,'paid','usd',9900,9900,0,10000,1000,900,9900,?,?,?,NOW(),NOW(),NOW())")->execute([$pub('inv'),(int)$account['id'],$mode,$invoice1,'cus_'.$run,'FIN-PAID-'.$run,$periodStart.' 00:00:00',$periodEnd.' 23:59:59']);
$pdo->prepare("INSERT INTO stripe_invoices(public_id,account_id,mode,stripe_invoice_id,stripe_customer_id,status,currency,amount_due_cents,amount_paid_cents,amount_remaining_cents,subtotal_cents,discount_amount_cents,tax_amount_cents,total_cents,invoice_number,period_start,period_end,due_at,finalized_at) VALUES(?,?,?,?,?,'open','usd',5000,0,5000,5000,0,0,5000,?,?,?,DATE_SUB(UTC_TIMESTAMP(),INTERVAL 10 DAY),NOW())")->execute([$pub('inv'),(int)$account['id'],$mode,$invoice2,'cus_'.$run,'FIN-DUE-'.$run,$periodStart.' 00:00:00',$periodEnd.' 23:59:59']);
$snapshot=json_encode(['total'=>9900,'tax'=>900],JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);$pdo->prepare("INSERT INTO commercial_invoice_evidence(public_id,account_id,stripe_mode,stripe_invoice_id,invoice_number,currency,financial_snapshot_sha256,financial_snapshot_json,finalized_at,drift_detected,drift_details_json) VALUES(?,?,?,?,?,'usd',?,?,NOW(),1,?)")->execute([$pub('evid'),(int)$account['id'],$mode,$invoice1,'FIN-PAID-'.$run,hash('sha256',$snapshot),$snapshot,json_encode(['observed_sha256'=>str_repeat('a',64)],JSON_THROW_ON_ERROR)]);
$insertCredit=$pdo->prepare("INSERT INTO commercial_credit_adjustments(public_id,account_id,stripe_mode,actor_user_id,adjustment_type,amount_cents,currency,reason,idempotency_key,stripe_customer_id,status,last_error,applied_at) VALUES(?,?,?,?,?,?,'usd',?,?,?,?,?,?)");
$creditApplied=$pub('cr');$insertCredit->execute([$creditApplied,(int)$account['id'],$mode,(int)$billing['id'],'credit',-500,'Test credit','idem-'.$creditApplied,'cus_'.$run,'applied',null,gmdate('Y-m-d H:i:s')]);
$debitApplied=$pub('db');$insertCredit->execute([$debitApplied,(int)$account['id'],$mode,(int)$billing['id'],'debit',200,'Test debit','idem-'.$debitApplied,'cus_'.$run,'applied',null,gmdate('Y-m-d H:i:s')]);
$creditFailed=$pub('cf');$insertCredit->execute([$creditFailed,(int)$account['id'],$mode,(int)$billing['id'],'credit',-700,'Failed credit','idem-'.$creditFailed,'cus_'.$run,'failed','Synthetic Stripe failure',null]);
$metrics=admin_finance_metrics($pdo,$yesterday,$today);av230(
    ((int)$metrics['gross_cents']-(int)$baseline['gross_cents'])===15000&&
    ((int)$metrics['discount_cents']-(int)$baseline['discount_cents'])===1000&&
    ((int)$metrics['tax_cents']-(int)$baseline['tax_cents'])===900&&
    ((int)$metrics['invoiced_cents']-(int)$baseline['invoiced_cents'])===14900&&
    ((int)$metrics['collected_cents']-(int)$baseline['collected_cents'])===9900&&
    ((int)$metrics['outstanding_cents']-(int)$baseline['outstanding_cents'])===5000&&
    ((int)$metrics['credit_issued_cents']-(int)$baseline['credit_issued_cents'])===500&&
    ((int)$metrics['debit_issued_cents']-(int)$baseline['debit_issued_cents'])===200&&
    ((int)$metrics['net_collection_position_cents']-(int)$baseline['net_collection_position_cents'])===9600,
    'Finance metrics add the expected invoice, collection, receivable, tax, discount and credit/debit deltas without assuming an empty regression database.'
);
$aging=admin_finance_receivable_aging($pdo);av230((int)$aging['total']>=5000&&(int)$aging['1_30']>=5000,'Receivable aging places overdue balance in the correct aging bucket.');
$scan=admin_finance_scan($pdo,$billing);av230((int)$scan['active_count']>=3,'Finance reconciliation scan materializes active source exceptions.');
$rows=admin_finance_exceptions($pdo,$billing,[],100);$types=array_column($rows,'exception_type');av230(in_array('invoice_financial_drift',$types,true)&&in_array('overdue_receivable',$types,true)&&in_array('credit_adjustment_failed',$types,true),'Reconciliation detects invoice drift, overdue receivable and failed credit evidence.');
$driftRows=array_values(array_filter($rows,fn($r)=>$r['exception_type']==='invoice_financial_drift'&&$r['source_public_id']===$invoice1));av230(count($driftRows)===1,'Reconciliation exposes the synthetic invoice drift by its authoritative Stripe invoice identifier.');$drift=$driftRows[0];admin_finance_exception_update($pdo,$billing,(string)$drift['public_id'],'acknowledge',['reason'=>'Finance operator is investigating.']);$ack=admin_finance_exception($pdo,(string)$drift['public_id']);av230($ack['status']==='acknowledged'&&(int)$ack['assigned_user_id']===(int)$billing['id'],'Finance exception can be acknowledged and self-assigned with audit evidence.');
admin_finance_exception_update($pdo,$billing,(string)$drift['public_id'],'resolve',['reason'=>'Reviewed against current source evidence.']);$scanAgain=admin_finance_scan($pdo,$billing);$reopened=admin_finance_exception($pdo,(string)$drift['public_id']);av230($reopened['status']==='open','Persistent source condition reopens a previously resolved reconciliation exception.');
$pdo->prepare("UPDATE commercial_invoice_evidence SET drift_detected=0,drift_details_json=NULL WHERE stripe_mode=? AND stripe_invoice_id=?")->execute([$mode,$invoice1]);$cleared=admin_finance_scan($pdo,$billing);$resolved=admin_finance_exception($pdo,(string)$drift['public_id']);av230($resolved['status']==='resolved'&&(int)$cleared['auto_resolved']>=1,'Cleared source condition auto-resolves the reconciliation exception without deleting history.');
$closeBlocked=false;try{admin_finance_period_close($pdo,$billing,$yesterday,$today,'This close should be blocked by a critical failed credit.');}catch(Throwable $e){$closeBlocked=str_contains($e->getMessage(),'critical finance reconciliation');}av230($closeBlocked,'Period close is blocked while unresolved critical reconciliation exceptions remain.');
$criticalRows=admin_finance_exceptions($pdo,$billing,['severity'=>'critical'],100);foreach($criticalRows as $criticalRow)if(in_array($criticalRow['status'],['open','acknowledged'],true))admin_finance_exception_update($pdo,$billing,(string)$criticalRow['public_id'],'ignore',['reason'=>'Synthetic critical condition acknowledged for close-gate test.']);
$close=admin_finance_period_close($pdo,$billing,$yesterday,$today,'V2.30 test period close after reconciliation.');av230(strlen((string)$close['metrics_sha256'])===64&&$close['period_start']===$yesterday&&$close['period_end']===$today,'Period close stores an immutable SHA-256 fingerprint over finance snapshot evidence.');$close2=admin_finance_period_close($pdo,$billing,$yesterday,$today,'Repeat close should return immutable record.');av230((int)$close2['id']===(int)$close['id']&&(string)$close2['metrics_sha256']===(string)$close['metrics_sha256'],'Closing the same mode/date range is idempotent and does not rewrite the snapshot.');
$ledger=admin_finance_account_ledger($pdo,(int)$account['id'],100);av230(count($ledger)>=5,'Account financial ledger merges invoices, credits/debits and commercial evidence streams.');
$export=admin_finance_export($pdo,$billing,'ledger',['from'=>$yesterday,'to'=>$today,'account'=>$account['public_id']]);av230((int)$export['row_count']>=5&&strlen((string)$export['sha256'])===64&&str_contains((string)$export['content'],$invoice1)&&str_contains((string)$export['content'],$invoice2)&&str_contains((string)$export['content'],$creditApplied),'Audited account-scoped finance export contains invoice and adjustment ledger evidence and records a SHA-256.');
$q=$pdo->prepare("SELECT COUNT(*) FROM admin_finance_exports WHERE public_id=? AND requested_by_user_id=?");$q->execute([$export['public_id'],(int)$billing['id']]);av230((int)$q->fetchColumn()===1,'Finance export request is durably audited.');
$csv=admin_finance_csv([['name'=>'=SUM(1,1)','amount'=>'100']]);av230(str_contains($csv,"'=SUM(1,1)"),'Finance CSV neutralizes spreadsheet formula injection.');
$blocked=false;try{admin_finance_scan($pdo,$auditor);}catch(Throwable $e){$blocked=true;}av230($blocked,'Read-only Auditor cannot run finance reconciliation.');
$ctx=admin_finance_agent_context($pdo,$billing);av230(str_contains($ctx,'ADMIN V2.30 FINANCE')&&str_contains($ctx,'READ ONLY'),'Admin Agent finance context is explicit and read-only.');
$q=$pdo->prepare("SELECT COUNT(*) FROM admin_security_audit_events WHERE event_type LIKE 'finance_%'");$q->execute();av230((int)$q->fetchColumn()>=4,'Reconciliation, period close and export actions produce durable V2.10 security audit evidence.');
echo "Admin V2.30 Financial Reporting database journey passed.\n";
