<?php
declare(strict_types=1);
$root=dirname(__DIR__);$fail=[];
$need=function(string $file,string $needle,string $message)use(&$fail,$root){$p=$root.'/'.$file;if(!is_file($p)){$fail[]='Missing '.$file;return;}if(!str_contains((string)file_get_contents($p),$needle))$fail[]=$message;};
$m='database/migrations/20260924_075_admin_support_operations.sql';
foreach(['admin_support_cases','admin_support_case_events','admin_support_case_links','admin_support_saved_views','sla_due_at','duplicate_of_case_id','escalation_team','admin.support.view','admin.support.manage'] as $n)$need($m,$n,'Migration 075 missing '.$n);
foreach(['function admin_support_ready','function admin_support_create','function admin_support_duplicate_candidates','function admin_support_cases','function admin_support_update','function admin_support_case_timeline','function admin_support_customer_360','function admin_support_metrics','function admin_support_workload','function admin_support_saved_view_save','function admin_support_agent_context'] as $n)$need('app/admin-support.php',$n,'Admin V2.20 support runtime missing '.$n);
$need('app/admin-support.php','support_mention','Support internal @mentions must use the existing notification system.');
$need('app/admin-support.php','support_assigned','Support assignments must notify the assigned operator.');
$need('app/admin-support.php','support_escalated','Support escalations must notify authorized delegated domain operators.');
$need('app/admin-support.php',"'team'",'Support queue filters must support escalation-team routing.');
$need('app/admin-support.php',"'customer_communication'",'Support communications must be durably distinguished from internal notes.');
$need('app/admin-support.php',"'case_reopened'",'Support cases must preserve reopen history.');
$need('app/admin-support.php','duplicate_candidates','Support case creation must detect likely duplicates.');
$need('app/admin-access.php',"'admin.support.view'",'V2.10 capability registry must expose Support view permission.');
$need('app/admin-access.php',"'admin.support.manage'",'V2.10 capability registry must expose Support manage permission.');
$need('app/admin-access.php',"'/admin/support.php'=>['admin.support.view','admin.support.manage']", 'Support route must separate read and mutation authority.');
$need('app/admin-ui.php',"'support'=>['label'=>'Support Operations'",'Shared Admin navigation must expose Support Operations.');
$need('app/admin-ui.php','Admin V2.20','Shared Admin shell must identify V2.20.');
foreach(['ADMIN V2.20 · SUPPORT OPERATIONS','Support inbox & customer service workspace','SUPPORT INBOX','NEW CASE','CATEGORY VOLUME','WORKLOAD'] as $n)$need('admin/support.php',$n,'Support Inbox missing '.$n);
foreach(['ADMIN V2.20 · SUPPORT CASE','CASE CONTROL','INTERNAL COLLABORATION','CUSTOMER COMMUNICATION LOG','DUPLICATE DETECTION','CUSTOMER 360','CASE + ACCOUNT TIMELINE'] as $n)$need('admin/support-case.php',$n,'Support Case workspace missing '.$n);
$need('admin/account.php','ADMIN V2.20 · SUPPORT','Account 360 must surface Support history for authorized operators.');
$need('admin/index.php','Open support cases','Command Center must surface support metrics.');
$need('admin/index.php','SUPPORT OPERATIONS','Command Center must link Support Operations.');
$need('app/admin-operations.php','Support case','Global Admin search must support cases for authorized operators.');
$need('app/admin-operations.php',"admin.support.view",'Account 360 support evidence must be viewer-scoped.');
$need('app/notifications.php',"'support_case'",'Notifications must authorize and deep-link Support cases.');
$need('app/agent-chat.php','admin_support_agent_context','Admin Agent must receive read-only V2.20 support context.');
$need('app/agent-chat.php','Admin V2.20 support context is read-only','Agent system prompt must deny support case mutation claims.');
$need('tests/ci/run-full-regression.sh','tests/admin-v2-20-support-operations-db.php','Full regression must execute V2.20 support database journey.');
$need('.github/workflows/full-regression.yml','admin-v2-20-upgrade-from-074.php','Phase gate must rehearse migration 075 from 074.');
$need('.github/workflows/package-two-zips.yml','20260924_075_admin_support_operations.sql','Production package must include migration 075.');
$need('tests/ci/package-smoke.sh','admin-v2-20-support-operations.md','Release smoke must require V2.20 files.');
if($fail){foreach($fail as $f)fwrite(STDERR,"FAIL: $f\n");exit(1);}echo "Admin V2.20 Support Operations static contract passed.\n";
