<?php
declare(strict_types=1);
$root=dirname(__DIR__);$fail=[];
$need=function(string $file,string $needle,string $message)use(&$fail,$root){$p=$root.'/'.$file;if(!is_file($p)){$fail[]='Missing '.$file;return;}if(!str_contains((string)file_get_contents($p),$needle))$fail[]=$message;};
$m='database/migrations/20260924_072_tax_invoices_commercial_billing_hardening.sql';
foreach(['subtotal_cents','tax_amount_cents','commercial_billing_settings','account_billing_profiles','commercial_tax_id_snapshots','commercial_invoice_evidence','commercial_billing_audit_events'] as $n)$need($m,$n,'Migration 072 missing '.$n);
foreach(['function commercial_billing_save_settings','function commercial_billing_profile_save','function commercial_billing_checkout_policy_hash','function commercial_billing_checkout_params','function commercial_billing_prepare_draft_invoice','function commercial_billing_sync_subscription_policy','function commercial_billing_handle_invoice','function commercial_billing_reconcile_invoice','function commercial_billing_tax_summary','function commercial_billing_agent_context'] as $n)$need('app/commercial-billing.php',$n,'V1.90 runtime missing '.$n);
$need('app/commercial-billing.php',"['automatic_tax']=['enabled'=>'true']", 'Checkout tax policy must support Stripe automatic tax.');
$need('app/commercial-billing.php',"['tax_id_collection']=['enabled'=>'true']", 'Checkout tax policy must support Stripe tax-ID collection.');
$need('app/commercial-billing.php',"'value_last4'",'Tax ID snapshots must avoid storing full tax-ID values.');
$need('app/commercial-billing.php','drift_detected','Finalized invoice evidence must detect financial snapshot drift.');
$need('app/stripe-billing.php','annotated_billing_policy_hash','Checkout reuse must be bound to the V1.90 billing policy fingerprint.');
$need('app/stripe-billing.php','commercial_billing_checkout_params','Checkout must apply V1.90 billing and tax policy.');
$need('app/stripe-billing.php',"\$eventType==='invoice.created'",'Stripe webhook flow must prepare draft invoices.');
$need('app/stripe-billing.php','commercial_billing_handle_invoice','Stripe invoice webhooks must record V1.90 invoice evidence.');
$need('billing.php','BILLING PROFILE','Customer billing must expose governed billing profile fields.');
$need('billing.php','discount_amount_cents','Customer invoice history must separate discounts.');
$need('billing.php','tax_amount_cents','Customer invoice history must expose tax.');
$need('admin/tax-invoices.php','Tax, invoices & commercial billing hardening','Admin V1.90 tax and invoice workspace is required.');
$need('app/admin-ui.php',"'tax_invoices'=>",'Admin navigation must expose Tax & Invoices.');
$need('admin/billing.php','invoice.created/finalized','Stripe Admin must recommend invoice.created for draft invoice defaults.');
$need('admin/billing-analytics.php','TAX & INVOICE EVIDENCE · 30D','Billing analytics must expose V1.90 tax and invoice integrity metrics.');
$need('app/agent-chat.php','commercial_billing_agent_context','Admin Agent must receive read-only tax and invoice intelligence.');
$need('app/agent-chat.php','Tax and invoice context is read-only','Admin Agent must not gain autonomous tax or invoice mutation authority.');
$need('tests/ci/run-full-regression.sh','tests/admin-v1-90-tax-invoices-commercial-billing-db.php','Full regression must execute V1.90 database journey.');
$need('.github/workflows/full-regression.yml','admin-v1-90-upgrade-from-071.php','Phase gate must rehearse migration 072 from 071.');
$need('.github/workflows/package-two-zips.yml','20260924_072_tax_invoices_commercial_billing_hardening.sql','Production package must include migration 072.');
$need('tests/ci/package-smoke.sh','admin-v1-90-tax-invoices-commercial-billing.md','Release smoke must require V1.90 files.');
if($fail){foreach($fail as $f)fwrite(STDERR,"FAIL: $f\n");exit(1);}echo "Admin V1.90 tax, invoices & commercial billing hardening static contract passed.\n";
