<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=(string)getenv('DB_DSN');$dbUser=(string)getenv('DB_USER');$dbPass=(string)getenv('DB_PASS');if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
foreach(['installer','functions','subscriptions','account-admin','account-membership','stripe-billing','billing-operations'] as $lib)require_once $root.'/app/'.$lib.'.php';
function av160(bool $ok,string $m):void{if(!$ok)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}
function av160throws(callable $fn,string $contains,string $m):void{try{$fn();}catch(Throwable $e){if($contains!==''&&!str_contains($e->getMessage(),$contains))throw new RuntimeException('FAIL: '.$m.' (unexpected: '.$e->getMessage().')');echo "PASS: $m\n";return;}throw new RuntimeException('FAIL: '.$m);}
av160(billing_operations_ready($pdo),'Migration 069 billing operations schema is ready.');
$defaults=billing_operations_settings($pdo);av160((int)$defaults['suspend_after_grace']===0,'Automatic dunning suspension is disabled by default.');$snapshotDates=[gmdate('Y-m-d',time()-86400),gmdate('Y-m-d'),gmdate('Y-m-d',time()+86400),gmdate('Y-m-d',time()+2*86400),gmdate('Y-m-d',time()+3*86400),gmdate('Y-m-d',time()+4*86400),gmdate('Y-m-d',time()+5*86400)];$marks=implode(',',array_fill(0,count($snapshotDates),'?'));$pdo->prepare("DELETE FROM billing_account_snapshots WHERE stripe_mode='test' AND snapshot_date IN ($marks)")->execute($snapshotDates);$pdo->prepare("DELETE FROM billing_daily_snapshots WHERE stripe_mode='test' AND snapshot_date IN ($marks)")->execute($snapshotDates);
$run='av160'.substr(bin2hex(random_bytes(5)),0,10);$seq=0;$pub=function(string $p)use($run,&$seq):string{$seq++;return $p.'-'.$run.'-'.$seq;};
$mk=function(string $name,string $role='user')use($pdo,$run,$pub):array{$u=strtolower($name).'_'.$run;$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,status,role,plan_tier,live_presence_mode) VALUES(?,?,?,?, 'active',?,'free','cloaked')")->execute([$pub('u'),$u,$name,$u.'@example.test',$role]);$id=(int)$pdo->lastInsertId();$q=$pdo->prepare('SELECT * FROM users WHERE id=?');$q->execute([$id]);return $q->fetch();};
$admin=$mk('BillingAdmin','admin');$owner=$mk('BillingOwner');$teamBefore=(int)$pdo->query('SELECT COUNT(*) FROM teams')->fetchColumn();
$packagePublic=$pub('pkg');$packageSlug='billing-'.$run;$pdo->prepare("INSERT INTO subscription_packages(public_id,slug,name,description,status,is_public,legacy_plan_tier,billing_interval,monthly_price_cents,monthly_ai_token_allowance,member_limit,trial_days,feature_json,sort_order) VALUES(?,?,?,'V1.60 paid fixture','active',1,'pro','monthly',5000,100000,5,0,'{}',500)")
  ->execute([$packagePublic,$packageSlug,'Billing V1.60 '.$run]);$packageId=(int)$pdo->lastInsertId();$mrrBefore=(int)billing_operations_current_metrics($pdo,'test')['mrr_cents'];
$account=account_admin_create($pdo,$admin,['name'=>'Billing Ops '.$run,'account_type'=>'organization','owner'=>$owner['username'],'package_id'=>$packagePublic,'reason'=>'Create V1.60 billing fixture.']);av160((int)$account['package_id']===$packageId,'Paid V1.60 account fixture created.');
$q=$pdo->prepare("SELECT COUNT(*) FROM subscription_package_events WHERE account_id=? AND event_type='account_created' AND new_package_id=?");$q->execute([(int)$account['id'],$packageId]);av160((int)$q->fetchColumn()===1,'Admin-created account emits canonical package event for revenue movement.');
$liveOwner=$mk('BillingLiveOwner');$liveAccount=account_admin_create($pdo,$admin,['name'=>'Billing Live Only '.$run,'account_type'=>'organization','owner'=>$liveOwner['username'],'package_id'=>$packagePublic,'reason'=>'Create live-only mode isolation fixture.']);$liveCustomer='cus_live_'.$run;stripe_billing_link_customer($pdo,(int)$liveAccount['id'],'live',$liveCustomer,$liveOwner['email'],$liveAccount['name'],['fixture'=>'v160-live']);$pdo->prepare("UPDATE accounts SET billing_source='stripe',subscription_status='active' WHERE id=?")->execute([(int)$liveAccount['id']]);$pdo->prepare("INSERT INTO stripe_subscriptions(public_id,account_id,mode,stripe_subscription_id,stripe_customer_id,status,current_period_start,current_period_end) VALUES(?,?,'live',?,?,'active',NOW(),DATE_ADD(NOW(),INTERVAL 1 MONTH))")->execute([$pub('ss'),(int)$liveAccount['id'],'sub_live_'.$run,$liveCustomer]);
$stripeOwner=$mk('BillingStripeOwner');$stripeAccount=account_admin_create($pdo,$admin,['name'=>'Billing Stripe Price '.$run,'account_type'=>'organization','owner'=>$stripeOwner['username'],'package_id'=>$packagePublic,'reason'=>'Create actual Stripe price fixture.']);$stripeCustomer='cus_test_'.$run;$stripePrice='price_'.$run;stripe_billing_link_customer($pdo,(int)$stripeAccount['id'],'test',$stripeCustomer,$stripeOwner['email'],$stripeAccount['name'],['fixture'=>'v160-test-price']);$pdo->prepare("INSERT INTO stripe_package_prices(public_id,package_id,mode,stripe_product_id,stripe_price_id,currency,unit_amount_cents,billing_interval,active,created_by_user_id) VALUES(?,?,'test',?,?,'usd',4200,'month',1,?)")->execute([$pub('spp'),$packageId,'prod_'.$run,$stripePrice,(int)$admin['id']]);$pdo->prepare("UPDATE accounts SET billing_source='stripe',subscription_status='active' WHERE id=?")->execute([(int)$stripeAccount['id']]);$pdo->prepare("INSERT INTO stripe_subscriptions(public_id,account_id,mode,stripe_subscription_id,stripe_customer_id,stripe_price_id,status,current_period_start,current_period_end) VALUES(?,?,'test',?,?,?,'active',NOW(),DATE_ADD(NOW(),INTERVAL 1 MONTH))")->execute([$pub('ss'),(int)$stripeAccount['id'],'sub_test_'.$run,$stripeCustomer,$stripePrice]);
$pdo->exec("UPDATE stripe_billing_settings SET mode='test' WHERE id=1");$customer='cus_'.$run;stripe_billing_link_customer($pdo,(int)$account['id'],'test',$customer,$owner['email'],$account['name'],['fixture'=>'v160']);
billing_operations_save_settings($pdo,$admin,['dunning_grace_days'=>0,'trial_reminder_days'=>3,'restore_after_payment'=>1]);
$invoice='in_'.$run;$base=time()-180;$obj=['id'=>$invoice,'customer'=>$customer,'subscription'=>'sub_'.$run,'amount_due'=>5000,'amount_remaining'=>5000];
billing_operations_handle_invoice_event($pdo,$obj,'invoice.payment_failed','test','evt_fail_1_'.$run,gmdate('Y-m-d H:i:s',$base));
$case=billing_operations_case($pdo,'test',$invoice);av160($case&&$case['status']==='open'&&(int)$case['failure_count']===1,'First payment failure opens one dunning case.');
$grace=(string)$case['grace_until'];billing_operations_handle_invoice_event($pdo,$obj,'invoice.payment_failed','test','evt_fail_2_'.$run,gmdate('Y-m-d H:i:s',$base+30));$case=billing_operations_case($pdo,'test',$invoice);av160((int)$case['failure_count']===2&&(string)$case['grace_until']===$grace,'Repeated failed-payment event increments failure count without silently extending grace.');
billing_operations_handle_invoice_event($pdo,$obj,'invoice.payment_failed','test','evt_stale_'.$run,gmdate('Y-m-d H:i:s',$base-60));$case=billing_operations_case($pdo,'test',$invoice);av160((int)$case['failure_count']===2&&$case['last_event_id']==='evt_fail_2_'.$run,'Older failed-payment event cannot overwrite newer dunning state.');
$pdo->prepare("UPDATE billing_dunning_cases SET grace_until=DATE_SUB(NOW(),INTERVAL 1 MINUTE),next_review_at=DATE_SUB(NOW(),INTERVAL 1 MINUTE) WHERE id=?")->execute([(int)$case['id']]);$review=billing_operations_process_due_dunning($pdo,$admin);$case=billing_operations_case($pdo,'test',$invoice);$account=account_admin_get($pdo,(int)$account['id']);av160($case['status']==='grace'&&$account['status']==='active'&&$review['grace']>=1,'Expired grace preserves account access while automatic suspension policy is disabled.');
billing_operations_save_settings($pdo,$admin,['dunning_grace_days'=>0,'trial_reminder_days'=>3,'suspend_after_grace'=>1,'restore_after_payment'=>1]);$pdo->prepare("UPDATE billing_dunning_cases SET grace_until=DATE_SUB(NOW(),INTERVAL 1 MINUTE),next_review_at=DATE_SUB(NOW(),INTERVAL 1 MINUTE) WHERE id=?")->execute([(int)$case['id']]);billing_operations_process_due_dunning($pdo,$admin);$case=billing_operations_case($pdo,'test',$invoice);$account=account_admin_get($pdo,(int)$account['id']);av160($case['status']==='suspended'&&(int)$case['suspended_by_dunning']===1&&$account['status']==='suspended','Configured dunning policy can suspend account access and marks suspension ownership.');
$paid=$obj;$paid['amount_remaining']=0;$paid['amount_paid']=5000;billing_operations_handle_invoice_event($pdo,$paid,'invoice.paid','test','evt_paid_'.$run,gmdate('Y-m-d H:i:s',$base+120));$case=billing_operations_case($pdo,'test',$invoice);$account=account_admin_get($pdo,(int)$account['id']);av160($case['status']==='recovered'&&$account['status']==='active','Payment recovery restores an account only when V1.60 still owns the suspension.');

$invoice2='in_manual_'.$run;$obj2=['id'=>$invoice2,'customer'=>$customer,'subscription'=>'sub_'.$run,'amount_due'=>5000,'amount_remaining'=>5000];billing_operations_handle_invoice_event($pdo,$obj2,'invoice.payment_failed','test','evt_mfail_'.$run,gmdate('Y-m-d H:i:s'));$case2=billing_operations_case($pdo,'test',$invoice2);$pdo->prepare("UPDATE billing_dunning_cases SET grace_until=DATE_SUB(NOW(),INTERVAL 1 MINUTE),next_review_at=DATE_SUB(NOW(),INTERVAL 1 MINUTE) WHERE id=?")->execute([(int)$case2['id']]);billing_operations_process_due_dunning($pdo,$admin);$account=account_admin_get($pdo,(int)$account['id']);av160($account['status']==='suspended','Second dunning case reaches configured suspension.');
$account=account_admin_update_lifecycle($pdo,$admin,(string)$account['public_id'],['name'=>$account['name'].' Manual Hold','status'=>'suspended','subscription_status'=>$account['subscription_status'],'reason'=>'Manual security suspension after dunning.']);$paid2=$obj2;$paid2['amount_remaining']=0;$paid2['amount_paid']=5000;billing_operations_handle_invoice_event($pdo,$paid2,'invoice.paid','test','evt_mpaid_'.$run,gmdate('Y-m-d H:i:s',time()+60));$account=account_admin_get($pdo,(int)$account['id']);av160($account['status']==='suspended','Payment recovery never undoes a later explicit lifecycle decision.');
$account=account_admin_update_lifecycle($pdo,$admin,(string)$account['public_id'],['name'=>$account['name'],'status'=>'active','subscription_status'=>$account['subscription_status'],'reason'=>'Restore fixture after manual override test.']);

$invoice3='in_grace_'.$run;$obj3=['id'=>$invoice3,'customer'=>$customer,'subscription'=>'sub_'.$run,'amount_due'=>5000,'amount_remaining'=>5000];billing_operations_handle_invoice_event($pdo,$obj3,'invoice.payment_failed','test','evt_gfail_'.$run,gmdate('Y-m-d H:i:s'));$case3=billing_operations_case($pdo,'test',$invoice3);$pdo->prepare("UPDATE billing_dunning_cases SET grace_until=DATE_SUB(NOW(),INTERVAL 1 MINUTE),next_review_at=DATE_SUB(NOW(),INTERVAL 1 MINUTE) WHERE id=?")->execute([(int)$case3['id']]);billing_operations_process_due_dunning($pdo,$admin);$case3=billing_operations_case($pdo,'test',$invoice3);$account=account_admin_get($pdo,(int)$account['id']);av160($case3['status']==='suspended'&&$account['status']==='suspended','Third case proves dunning-owned suspension before grace override.');$case3=billing_operations_grant_grace($pdo,$admin,(string)$case3['public_id'],5,'Grant temporary grace for fixture.');$account=account_admin_get($pdo,(int)$account['id']);av160($case3['status']==='grace'&&(int)$case3['suspended_by_dunning']===0&&$account['status']==='active','Explicit Admin grace restores a dunning-owned suspension and clears ownership.');

$note=billing_operations_add_note($pdo,$admin,(int)$account['id'],'general','V1.60 internal billing note.');av160($note['body']==='V1.60 internal billing note.','Internal billing note is append-only persisted.');$feedback=billing_operations_record_cancellation_feedback($pdo,$owner,(int)$account['id'],'customer','price','Fixture cancellation feedback.',true);av160($feedback['reason_code']==='price'&&(int)$feedback['win_back_eligible']===1,'Customer cancellation feedback and win-back eligibility persist separately from subscription mutation.');
stripe_billing_record_customer_event($pdo,[],['mode'=>'test'],['id'=>'re_'.$run,'customer'=>$customer,'amount_refunded'=>1000,'currency'=>'usd'],'charge.refunded','evt_refund_'.$run);stripe_billing_record_customer_event($pdo,[],['mode'=>'test'],['id'=>'dp_'.$run,'customer'=>$customer,'amount'=>2500,'currency'=>'usd'],'charge.dispute.created','evt_dispute_'.$run);
$metrics=billing_operations_current_metrics($pdo,'test');av160((int)$metrics['mrr_cents']===$mrrBefore+9200,'Test-mode MRR excludes Live-only Stripe accounts and adds the actual mapped Stripe Price instead of the Annotated list price.');
$baselineDate=gmdate('Y-m-d',time()-86400);$baseline=billing_operations_snapshot_day($pdo,$baselineDate,'test');av160((int)$baseline['mrr_cents']===$mrrBefore+9200&&(int)$baseline['new_mrr_cents']===0,'First snapshot establishes a revenue baseline without fabricating historical new MRR.');
$newOwner=$mk('BillingNewOwner');$newAccount=account_admin_create($pdo,$admin,['name'=>'Billing New '.$run,'account_type'=>'organization','owner'=>$newOwner['username'],'package_id'=>$packagePublic,'reason'=>'Create post-baseline MRR fixture.']);
$snap=billing_operations_snapshot_day($pdo,null,'test');av160((int)$snap['mrr_cents']===$mrrBefore+14200&&(int)$snap['arr_cents']===(($mrrBefore+14200)*12),'Daily snapshot captures mode-isolated recurring revenue using actual Stripe price.');av160((int)$snap['new_mrr_cents']===5000,'Daily movement compares durable account snapshots and recognizes only post-baseline new MRR.');av160((int)$snap['refunded_amount_cents']>=1000&&(int)$snap['disputed_amount_cents']>=2500,'Daily snapshot captures refund and dispute amounts from Stripe audit.');
billing_operations_snapshot_day($pdo,null,'test');$q=$pdo->prepare('SELECT COUNT(*) FROM billing_daily_snapshots WHERE stripe_mode=? AND snapshot_date=?');$q->execute(['test',gmdate('Y-m-d')]);av160((int)$q->fetchColumn()===1,'Re-running a daily snapshot upserts instead of duplicating the day.');$q=$pdo->prepare('SELECT COUNT(*) FROM billing_account_snapshots WHERE stripe_mode=? AND snapshot_date=? AND account_id=?');$q->execute(['test',gmdate('Y-m-d'),(int)$account['id']]);av160((int)$q->fetchColumn()===1,'Daily snapshot persists one account-level billing state row.');$q->execute(['test',gmdate('Y-m-d'),(int)$liveAccount['id']]);av160((int)$q->fetchColumn()===0,'Test-mode account snapshots exclude Live-only Stripe accounts.');$q->execute(['test',gmdate('Y-m-d'),(int)$stripeAccount['id']]);av160((int)$q->fetchColumn()===1,'Test-mode account snapshots include the Test Stripe account.');$q=$pdo->prepare('SELECT monthly_price_cents FROM billing_account_snapshots WHERE stripe_mode=? AND snapshot_date=? AND account_id=?');$q->execute(['test',gmdate('Y-m-d'),(int)$stripeAccount['id']]);av160((int)$q->fetchColumn()===4200,'Stripe account snapshot stores the actual mapped recurring Price, not the package list price.');
$packageRows=billing_operations_revenue_by_package($pdo);$packageRow=null;foreach($packageRows as $p)if($p['package_public_id']===$packagePublic)$packageRow=$p;av160($packageRow&&(int)$packageRow['mrr_cents']===14200,'Revenue-by-package uses actual Stripe recurring price and mode isolation.');
$pdo->prepare('UPDATE subscription_packages SET monthly_price_cents=6000 WHERE id=?')->execute([$packageId]);$expSnap=billing_operations_snapshot_day($pdo,gmdate('Y-m-d',time()+86400),'test');av160((int)$expSnap['expansion_mrr_cents']===2000,'Snapshot delta classifies manual-account price growth as expansion MRR while Stripe price remains unchanged.');
$pdo->prepare('UPDATE subscription_packages SET monthly_price_cents=4000 WHERE id=?')->execute([$packageId]);$contractSnap=billing_operations_snapshot_day($pdo,gmdate('Y-m-d',time()+2*86400),'test');av160((int)$contractSnap['contraction_mrr_cents']===4000,'Snapshot delta classifies recurring-price decreases as contraction MRR.');
$pdo->prepare("UPDATE accounts SET subscription_status='canceled' WHERE id=?")->execute([(int)$newAccount['id']]);$churnSnap=billing_operations_snapshot_day($pdo,gmdate('Y-m-d',time()+3*86400),'test');av160((int)$churnSnap['churned_mrr_cents']===4000,'Snapshot delta classifies a paid account becoming non-recurring as churned MRR.');
$pdo->prepare("UPDATE accounts SET subscription_status='past_due' WHERE id=?")->execute([(int)$account['id']]);billing_operations_snapshot_day($pdo,gmdate('Y-m-d',time()+4*86400),'test');$pdo->prepare("UPDATE accounts SET subscription_status='active' WHERE id=?")->execute([(int)$account['id']]);$recoverySnap=billing_operations_snapshot_day($pdo,gmdate('Y-m-d',time()+5*86400),'test');av160((int)$recoverySnap['recovered_mrr_cents']===4000,'Snapshot delta classifies past-due to active recurring revenue as recovered MRR.');

$trialSub='sub_trial_'.$run;$trialEnd=gmdate('Y-m-d H:i:s',time()+2*86400);$pdo->prepare("INSERT INTO stripe_subscriptions(public_id,account_id,mode,stripe_subscription_id,stripe_customer_id,status,current_period_start,current_period_end,trial_end) VALUES(?,?, 'test',?,?, 'trialing',NOW(),DATE_ADD(NOW(),INTERVAL 1 MONTH),?)")->execute([$pub('ss'),(int)$account['id'],$trialSub,$customer,$trialEnd]);$trials=billing_operations_trial_accounts($pdo);$found=false;foreach($trials as $t)if($t['stripe_subscription_id']===$trialSub)$found=true;av160($found,'Trial ending inside configured reminder window appears in billing alerts.');
$alerts=billing_operations_alerts($pdo,100);$hasDispute=false;$hasDunning=false;foreach($alerts as $a){if($a['type']==='dispute')$hasDispute=true;if($a['type']==='dunning')$hasDunning=true;}av160($hasDispute&&$hasDunning,'Billing alerts surface unresolved disputes and open dunning cases.');
$timeline=billing_operations_account_timeline($pdo,(int)$account['id'],200);$sources=array_column($timeline,'source');av160(in_array('note',$sources,true)&&in_array('dunning',$sources,true)&&in_array('cancellation',$sources,true),'Account billing timeline merges notes, dunning and cancellation intelligence.');
$adminContext=billing_operations_agent_context($pdo,$admin);$userContext=billing_operations_agent_context($pdo,$owner);av160(str_contains($adminContext,'ADMIN BILLING OPERATIONS')&&str_contains($adminContext,'MRR $')&&$userContext==='','Only Admin Agent Chat receives global revenue and dunning context.');
av160((int)$pdo->query('SELECT COUNT(*) FROM teams')->fetchColumn()===$teamBefore,'Billing operations never create or modify Research Teams.');
echo "Admin V1.60 billing analytics, revenue operations & dunning database journey passed.\n";