<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=(string)getenv('DB_DSN');$dbUser=(string)getenv('DB_USER');$dbPass=(string)getenv('DB_PASS');if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
foreach(['installer','functions','concurrency','subscriptions','account-admin','account-membership','stripe-billing','billing-operations','ai-usage','ai-overage-billing','commercial-promotions'] as $lib)require_once $root.'/app/'.$lib.'.php';
function cp80(bool $ok,string $m): void {if(!$ok)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}
function cp80throws(callable $fn,string $m): void {try{$fn();}catch(Throwable $e){echo "PASS: $m\n";return;}throw new RuntimeException('FAIL: '.$m);}
cp80(commercial_promotions_ready($pdo),'Migration 071 commercial promotion schema is ready.');
$run='cp80'.substr(bin2hex(random_bytes(5)),0,10);$pub=fn(string $p)=>$p.'-'.$run.'-'.substr(bin2hex(random_bytes(3)),0,6);
$makeUser=function(string $name,string $role='user')use($pdo,$run,$pub): array{$username=substr(strtolower($name).'_'.$run,0,48);$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,status,role,plan_tier,live_presence_mode) VALUES(?,?,?,?, 'active',?,'free','cloaked')")->execute([$pub('u'),$username,$name,$username.'@example.test',$role]);$id=(int)$pdo->lastInsertId();$q=$pdo->prepare('SELECT * FROM users WHERE id=?');$q->execute([$id]);return $q->fetch();};
$admin=$makeUser('PromoAdmin','admin');$user=$makeUser('PromoUser');
$package=subscription_package_create($pdo,$admin,['name'=>'Promo Package','slug'=>'promo-'.$run,'legacy_plan_tier'=>'pro','monthly_price'=>'25.00','monthly_ai_token_allowance'=>'1000','member_limit'=>'2','trial_days'=>'0','sort_order'=>'999','is_public'=>'1','status'=>'active']);
$account=subscription_ensure_user_account($pdo,(int)$user['id'],(int)$admin['id']);$account=subscription_assign_user_package($pdo,$admin,(int)$user['id'],(string)$package['public_id'],'V1.80 promotion test.');
$promo=commercial_promotion_create($pdo,$admin,['name'=>'Welcome 25','code'=>'welcome-25','status'=>'active','discount_type'=>'percent','percent_off'=>'25','duration'=>'once','customer_scope'=>'all','package_ids'=>[(string)$package['public_id']],'starts_at'=>gmdate('Y-m-d H:i:s',time()-3600),'ends_at'=>gmdate('Y-m-d H:i:s',time()+86400),'max_redemptions'=>'2','per_account_limit'=>'1']);
cp80($promo['code']==='WELCOME-25'&&(int)$promo['percent_basis_points']===2500,'Promotion code and percentage are normalized into canonical local policy.');
commercial_promotion_validate_checkout($pdo,$promo,$account,$package,'test');echo "PASS: Eligible new checkout passes local promotion policy.\n";
$hash=commercial_promotion_definition_hash($promo);$pdo->prepare("INSERT INTO commercial_promotion_stripe_mappings(promotion_id,stripe_mode,definition_hash,stripe_coupon_id,stripe_promotion_code_id,status,synced_at) VALUES(?, 'test', ?, ?, ?, 'synced', NOW())")->execute([(int)$promo['id'],$hash,'coupon_'.$run,'promo_'.$run]);
$map=commercial_promotion_mapping($pdo,(int)$promo['id'],'test');$attempt=$pub('attempt');$reserved=commercial_promotion_reserve_attempt($pdo,$promo,$account,$package,$user,'test',$attempt,$map);cp80($reserved['status']==='pending','Promotion redemption is reserved before checkout completion.');
commercial_promotion_bind_session($pdo,'test',$attempt,'cs_'.$run);commercial_promotion_apply_checkout($pdo,['id'=>'cs_'.$run,'subscription'=>'sub_'.$run,'metadata'=>['annotated_promotion_id'=>$promo['public_id'],'annotated_account_id'=>$account['public_id'],'annotated_package_id'=>$package['public_id']],'client_reference_id'=>$account['public_id']],'test');
$q=$pdo->prepare('SELECT * FROM commercial_promotion_redemptions WHERE id=?');$q->execute([(int)$reserved['id']]);$applied=$q->fetch();cp80($applied['status']==='applied'&&$applied['stripe_subscription_id']==='sub_'.$run,'Checkout completion idempotently promotes reservation to applied redemption.');
cp80throws(fn()=>commercial_promotion_reserve_attempt($pdo,$promo,$account,$package,$user,'test',$pub('attempt2'),$map),'Per-account redemption limit blocks a second checkout reservation.');
$pdo->prepare("INSERT INTO stripe_customers(public_id,account_id,mode,stripe_customer_id) VALUES(?,?, 'test',?)")->execute([$pub('cus'),(int)$account['id'],'cus_'.$run]);
$pdo->prepare("INSERT INTO stripe_subscriptions(public_id,account_id,mode,stripe_subscription_id,stripe_customer_id,status,current_period_start,current_period_end) VALUES(?,?, 'test',?,?, 'active',NOW(),DATE_ADD(NOW(),INTERVAL 1 MONTH))")->execute([$pub('sub'),(int)$account['id'],'sub_'.$run,'cus_'.$run]);
$pdo->prepare("INSERT INTO stripe_invoices(public_id,account_id,mode,stripe_invoice_id,stripe_subscription_id,stripe_customer_id,status,currency,amount_due_cents,amount_paid_cents,amount_remaining_cents) VALUES(?,?, 'test',?,?,?,'paid','usd',1875,1875,0)")->execute([$pub('inv'),(int)$account['id'],'in_'.$run,'sub_'.$run,'cus_'.$run]);
$invoice=['id'=>'in_'.$run,'subscription'=>'sub_'.$run,'subtotal'=>2500,'total'=>1875,'total_discount_amounts'=>[['amount'=>625]],'created'=>time()];
commercial_promotion_handle_invoice($pdo,$invoice,'test');commercial_promotion_handle_invoice($pdo,$invoice,'test');
$q=$pdo->prepare('SELECT COUNT(*) c,MAX(discount_amount_cents) d FROM commercial_discount_events WHERE stripe_mode=? AND stripe_invoice_id=?');$q->execute(['test','in_'.$run]);$event=$q->fetch();cp80((int)$event['c']===1&&(int)$event['d']===625,'Invoice discount evidence is idempotent and records Stripe actual discount.');
$q=$pdo->prepare('SELECT amount_discounted_cents FROM commercial_promotion_redemptions WHERE id=?');$q->execute([(int)$reserved['id']]);cp80((int)$q->fetchColumn()===625,'Applied redemption accumulates reconciled invoice discount amount.');
$newOnly=commercial_promotion_create($pdo,$admin,['name'=>'New Only','code'=>'NEW-'.$run,'status'=>'active','discount_type'=>'fixed_amount','amount_off_dollars'=>'5.00','duration'=>'once','customer_scope'=>'new_customers','per_account_limit'=>'1']);
cp80throws(fn()=>commercial_promotion_validate_checkout($pdo,$newOnly,$account,$package,'test'),'New-customer promotion rejects an account with paid invoice history.');
$pdo->prepare("INSERT INTO commercial_credit_adjustments(public_id,account_id,stripe_mode,actor_user_id,adjustment_type,amount_cents,currency,reason,idempotency_key,stripe_customer_id,status,applied_at) VALUES(?,?, 'test',?,'credit',-500,'usd','Support credit',?,?,'applied',NOW()),(?,?, 'test',?,'debit',100,'usd','Correction',?,?,'applied',NOW())")
 ->execute([$pub('credit'),(int)$account['id'],(int)$admin['id'],$pub('idem'),'cus_'.$run,$pub('debit'),(int)$account['id'],(int)$admin['id'],$pub('idem2'),'cus_'.$run]);
$benefits=commercial_account_benefits_summary($pdo,(int)$account['id']);cp80((int)$benefits['credit_net_cents']===-400&&(int)$benefits['discount_total_cents']===625,'Account benefits keep monetary credits separate from promotion discounts.');
$summary=commercial_revenue_adjustment_summary($pdo,30);cp80((int)$summary['discount_cents']>=625&&(int)$summary['credit_issued_cents']>=500&&(int)$summary['debit_issued_cents']>=100,'Commercial analytics separately report discounts, credits and debits.');
commercial_promotion_update($pdo,$admin,(string)$promo['public_id'],['name'=>$promo['name'],'code'=>$promo['code'],'status'=>'archived','discount_type'=>'percent','percent_off'=>'25','duration'=>'once','customer_scope'=>'all','per_account_limit'=>'1','package_ids'=>[(string)$package['public_id']]]);$archived=commercial_promotion($pdo,(string)$promo['public_id']);cp80throws(fn()=>commercial_promotion_validate_checkout($pdo,$archived,$account,$package,'live'),'Archived promotion cannot be redeemed in another Stripe mode.');
echo "Admin V1.80 coupons, promotions & credits database journey passed.\n";
