<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=(string)getenv('DB_DSN');$dbUser=(string)getenv('DB_USER');$dbPass=(string)getenv('DB_PASS');if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
foreach(['installer','functions','concurrency','subscriptions','account-admin','account-membership','stripe-billing','billing-operations','ai-usage','ai-overage-billing','commercial-promotions','commercial-billing','admin-operations','admin-access','admin-support','admin-finance','admin-customer-success','admin-security-compliance'] as $lib)require_once $root.'/app/'.$lib.'.php';
function av250(bool $ok,string $m): void {if(!$ok)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}
$run='av250'.substr(bin2hex(random_bytes(5)),0,10);$pub=fn(string $p)=>$p.'-'.$run.'-'.substr(bin2hex(random_bytes(3)),0,6);
$makeUser=function(string $name,string $role='user')use($pdo,$run,$pub): array{$username=substr(strtolower($name).'_'.$run,0,48);$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,status,role,plan_tier,live_presence_mode) VALUES(?,?,?,?, 'active',?,'free','cloaked')")->execute([$pub('u'),$username,$name,$username.'@example.test',$role]);$id=(int)$pdo->lastInsertId();$q=$pdo->prepare('SELECT * FROM users WHERE id=?');$q->execute([$id]);return $q->fetch();};
av250(admin_security_ready($pdo),'Migration 078 security/compliance schema is ready.');
$super=$makeUser('SecurityOwner','admin');$security=$makeUser('SecurityOperator','admin');$customer=$makeUser('SecurityCustomer');
admin_access_profile($pdo,$super);$role=admin_access_role($pdo,'security_compliance_admin');av250((bool)$role,'Bounded Security & Compliance Admin role is seeded.');
admin_access_assign_operator($pdo,$super,(int)$security['id'],(string)$role['public_id'],'active','Delegate V2.50 security and compliance operations.');
av250(admin_access_has_capability($pdo,$security,'admin.security.manage')&&admin_access_has_capability($pdo,$security,'admin.privacy.manage'),'Security operator can manage V2.50 workflows.');
av250(!admin_access_has_capability($pdo,$security,'admin.support.view')&&!admin_access_has_capability($pdo,$security,'admin.finance.view'),'Security role does not inherit Support or Finance source-domain access.');
$account=subscription_ensure_user_account($pdo,(int)$customer['id'],(int)$super['id']);av250(!empty($account['id']),'Test commercial account is available.');
admin_security_audit_record($pdo,$super,['account_id'=>(int)$account['id'],'subject_type'=>'support_case','subject_public_id'=>$pub('case'),'event_type'=>'support_sensitive_test','source_domain'=>'support','sensitivity'=>'high','before'=>['customer_secret'=>'before'],'after'=>['customer_secret'=>'after'],'metadata'=>['internal'=>'restricted'],'reason'=>'Sensitive support-domain audit test.']);
$redacted=admin_security_events($pdo,$security,['event_type'=>'support_sensitive_test'],20);$rr=$redacted[0]??null;av250((bool)$rr&&!$rr['source_allowed']&&$rr['before_json']===null&&$rr['after_json']===null&&$rr['subject_public_id']===null,'Security-wide visibility redacts Support payload and subject identifiers without Support permission.');
$visible=admin_security_events($pdo,$super,['event_type'=>'support_sensitive_test'],20);av250(!empty($visible[0]['source_allowed'])&&!empty($visible[0]['after_json_decoded']['customer_secret']),'Super Admin can inspect authorized source-domain evidence.');
account_admin_event($pdo,(int)$account['id'],(int)$super['id'],null,'v250_account_test',null,['status'=>'observed'],'Exercise normalized account audit.');$normalized=admin_security_events($pdo,$security,['event_type'=>'v250_account_test'],50);av250((bool)$normalized&&$normalized[0]['source_domain']==='accounts'&&$normalized[0]['source_allowed'],'Existing authoritative Account audit is normalized without copying it.');
$case=admin_security_case_create($pdo,$security,['title'=>'V2.50 case '.$run,'severity'=>'high','account_id'=>(int)$account['id'],'description'=>'Investigate a bounded test signal.','reason'=>'Open V2.50 test case.']);av250($case['status']==='open','Authorized security operator can open a governed case.');
$case=admin_security_case_update($pdo,$security,(string)$case['public_id'],['status'=>'resolved','severity'=>'high','resolution_note'=>'Verified and closed.','reason'=>'Resolve V2.50 test case.']);av250($case['status']==='resolved'&&!empty($case['resolved_at']),'Security case lifecycle records explicit resolution.');
$privacy=admin_privacy_create($pdo,$security,['request_type'=>'access','subject_user_id'=>(int)$customer['id'],'account_id'=>(int)$account['id'],'assigned_user_id'=>(int)$security['id'],'request_reference'=>'REQ-'.$run,'request_note'=>'Customer data-access request.','reason'=>'Create V2.50 privacy request.']);av250($privacy['status']==='open','Privacy request is created with explicit governed state.');
$privacy=admin_privacy_update($pdo,$security,(string)$privacy['public_id'],['status'=>'completed','completion_note'=>'Evidence delivered through approved channel.','evidence_json'=>'{"delivery":"verified"}','reason'=>'Complete V2.50 privacy request.']);av250($privacy['status']==='completed'&&!empty($privacy['completed_at']),'Privacy request completion is explicit and durable.');
$export=admin_security_export($pdo,$security,['account'=>(string)$account['public_id']],'json');av250($export['row_count']>0&&strlen($export['sha256'])===64&&hash_equals($export['sha256'],hash('sha256',$export['content'])),'Permission-scoped audit export is hashed and reproducible.');
$q=$pdo->prepare("SELECT COUNT(*) FROM admin_audit_exports WHERE public_id=? AND requested_by_user_id=?");$q->execute([$export['public_id'],(int)$security['id']]);av250((int)$q->fetchColumn()===1,'Audit export request is durably recorded.');
$q=$pdo->prepare("SELECT COUNT(*) FROM admin_security_audit_events WHERE actor_user_id=? AND event_type IN ('security_case_created','security_case_updated','privacy_request_created','privacy_request_updated','audit_export_created')");$q->execute([(int)$security['id']]);av250((int)$q->fetchColumn()>=5,'V2.50 case, privacy and export operations write append-only security evidence.');
$ctx=admin_security_agent_context($pdo,$security);av250(str_contains($ctx,'READ ONLY')&&str_contains($ctx,'open security cases'),'Admin Agent receives bounded read-only V2.50 context.');
echo "Admin V2.50 Security, Compliance & Administrative Audit Center database journey passed.\n";
