<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=(string)getenv('DB_DSN');$dbUser=(string)getenv('DB_USER');$dbPass=(string)getenv('DB_PASS');if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
foreach(['installer','functions','subscriptions','account-admin','account-membership','stripe-billing'] as $lib)require_once $root.'/app/'.$lib.'.php';
function av150(bool $ok,string $m):void{if(!$ok)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}
function av150throws(callable $fn,string $contains,string $m):void{try{$fn();}catch(Throwable $e){if($contains!==''&&!str_contains($e->getMessage(),$contains))throw new RuntimeException('FAIL: '.$m.' (unexpected: '.$e->getMessage().')');echo "PASS: $m\n";return;}throw new RuntimeException('FAIL: '.$m);}
function av150token(array $invite):string{$url=(string)($invite['invite_url']??'');$q=[];parse_str((string)parse_url($url,PHP_URL_QUERY),$q);return (string)($q['token']??'');}
av150(account_membership_ready($pdo),'Migration 068 membership schema is ready.');
$run='av150'.substr(bin2hex(random_bytes(5)),0,10);$seq=0;$pub=function(string $p)use($run,&$seq):string{$seq++;return $p.'-'.$run.'-'.$seq;};
$mk=function(string $name,string $role='user')use($pdo,$run,$pub):array{$u=strtolower($name).'_'.$run;$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,status,role,plan_tier,live_presence_mode) VALUES(?,?,?,?, 'active',?,'free','cloaked')")->execute([$pub('u'),$u,$name,$u.'@example.test',$role]);$id=(int)$pdo->lastInsertId();$q=$pdo->prepare('SELECT * FROM users WHERE id=?');$q->execute([$id]);return $q->fetch();};
$config=['app'=>['base_url'=>'https://annotated.example.test','name'=>'Annotated'],'mail'=>['enabled'=>false]];
$admin=$mk('SeatAdmin','admin');$owner=$mk('SeatOwner');$memberA=$mk('SeatMemberA');$memberB=$mk('SeatMemberB');$outsider=$mk('SeatOutsider');$owner2=$mk('SeatOwner2');$owner3=$mk('SeatOwner3');
$teamBefore=(int)$pdo->query('SELECT COUNT(*) FROM teams')->fetchColumn();$team=subscription_package($pdo,'team-builder');$basic=subscription_package($pdo,'basic-user');if(!$team||!$basic)throw new RuntimeException('Seeded packages missing.');
$org=account_admin_create($pdo,$admin,['name'=>'V150 Org '.$run,'account_type'=>'organization','owner'=>$owner['username'],'package_id'=>$team['public_id'],'reason'=>'Create V1.50 fixture.']);
account_admin_set_override($pdo,$admin,(string)$org['public_id'],'member_limit',2,null,'Two-seat V1.50 fixture.');
$inviteA=account_membership_create_invitation($pdo,$config,$owner,(string)$org['public_id'],$memberA['email'],'member',true,7,'Invite member A.');$tokenA=av150token($inviteA);av150((bool)preg_match('/^[a-f0-9]{64}$/',$tokenA),'Invitation returns a 256-bit hex token only through the generated link.');
$q=$pdo->prepare('SELECT token_hash FROM account_invitations WHERE public_id=?');$q->execute([$inviteA['public_id']]);$stored=(string)$q->fetchColumn();av150($stored===hash('sha256',$tokenA)&&$stored!==$tokenA,'Database stores only the invitation token hash.');
$seat=account_membership_seat_summary($pdo,(int)$org['id']);av150($seat['member_count']===1&&$seat['pending_reserved']===1&&$seat['used_seats']===2&&$seat['full'],'Pending reserved invitation consumes the final package seat.');
av150throws(fn()=>account_membership_create_invitation($pdo,$config,$owner,(string)$org['public_id'],$memberB['email'],'member',true,7,'Too many reserved seats.'),'no available seats','A second reserved invitation cannot overbook the account.');
$inviteB=account_membership_create_invitation($pdo,$config,$owner,(string)$org['public_id'],$memberB['email'],'member',false,7,'Non-reserving invitation.');$tokenB=av150token($inviteB);av150($tokenB!=='','A non-reserving invitation can wait for a future seat without consuming capacity.');
av150throws(fn()=>account_membership_accept_invitation($pdo,$memberB,$tokenA),'email address this invitation was sent to','Forwarded invitation cannot be claimed by a different email.');
av150throws(fn()=>account_membership_accept_invitation($pdo,$memberB,$tokenB),'no longer has an available seat','Non-reserving invitation rechecks capacity at acceptance.');
$resultA=account_membership_accept_invitation($pdo,$memberA,$tokenA);av150(!empty($resultA['joined'])&&$resultA['role']==='member','Invited existing user joins the commercial account with the invited role.');
av150throws(fn()=>account_membership_create_invitation($pdo,$config,$memberA,(string)$org['public_id'],$outsider['email'],'member',false,7,'Unauthorized invite.'),'owner or account admin','Ordinary account member cannot invite other members.');
account_membership_remove_member($pdo,$owner,(string)$org['public_id'],(int)$memberA['id'],'Free a seat for member B.');$resultB=account_membership_accept_invitation($pdo,$memberB,$tokenB);av150(!empty($resultB['joined']),'Waiting non-reserving invitation can be accepted once a seat becomes available.');
account_membership_update_role($pdo,$owner,(string)$org['public_id'],(int)$memberB['id'],'admin','Promote B to account admin.');$roles=array_column(account_admin_members($pdo,(int)$org['id']),'account_role','user_id');av150(($roles[$memberB['id']]??'')==='admin','Owner can promote an account member to account admin.');
$org=account_membership_transfer_owner($pdo,$owner,(string)$org['public_id'],(int)$memberB['id'],'Transfer V1.50 organization ownership.');av150((int)$org['owner_user_id']===(int)$memberB['id'],'Organization ownership transfer remains governed and explicit.');
account_admin_set_override($pdo,$admin,(string)$org['public_id'],'member_limit',3,null,'Allow a pending invite after ownership transfer.');
$inviteRotate=account_membership_create_invitation($pdo,$config,$memberB,(string)$org['public_id'],$memberA['email'],'member',true,7,'Rotation fixture.');$oldToken=av150token($inviteRotate);$rotated=account_membership_resend_invitation($pdo,$config,$memberB,(string)$inviteRotate['public_id'],7,'Rotate invite token.');$newToken=av150token($rotated);av150($newToken!==''&&!hash_equals($oldToken,$newToken),'Resend rotates the invitation secret.');av150(account_membership_invitation_by_token($pdo,$oldToken)===null&&account_membership_invitation_by_token($pdo,$newToken)!==null,'Old invitation token becomes invalid immediately after resend.');
$org=account_admin_update_lifecycle($pdo,$admin,(string)$org['public_id'],['name'=>$org['name'],'status'=>'suspended','subscription_status'=>$org['subscription_status'],'reason'=>'Suspend V1.50 fixture.']);av150throws(fn()=>account_membership_accept_invitation($pdo,$memberA,$newToken),'not currently accepting members','Suspended account cannot accept an invitation.');av150throws(fn()=>account_membership_create_invitation($pdo,$config,$memberB,(string)$org['public_id'],$outsider['email'],'member',false,7,'Suspended invite attempt.'),'Only active accounts','Suspended account cannot create invitations.');
$org=account_admin_update_lifecycle($pdo,$admin,(string)$org['public_id'],['name'=>$org['name'],'status'=>'active','subscription_status'=>$org['subscription_status'],'reason'=>'Reactivate V1.50 fixture.']);
$context=account_membership_agent_context($pdo,$memberB);av150(str_contains($context,'COMMERCIAL ACCOUNT MEMBERSHIP')&&str_contains($context,(string)$org['name'])&&str_contains($context,'seats'),'Agent receives read-only commercial account and seat context.');
$org=account_admin_update_lifecycle($pdo,$admin,(string)$org['public_id'],['name'=>$org['name'],'status'=>'closed','subscription_status'=>'canceled','reason'=>'Close V1.50 fixture.']);$closedInvite=account_membership_invitation_by_public($pdo,(string)$inviteRotate['public_id']);av150($closedInvite&&$closedInvite['status']==='revoked','Closing an account revokes outstanding invitations.');

$org2=account_admin_create($pdo,$admin,['name'=>'V150 Direct '.$run,'account_type'=>'organization','owner'=>$owner2['username'],'package_id'=>$team['public_id'],'reason'=>'Direct-add seat fixture.']);account_admin_set_override($pdo,$admin,(string)$org2['public_id'],'member_limit',2,null,'Two-seat direct-add fixture.');
$pending2=account_membership_create_invitation($pdo,$config,$owner2,(string)$org2['public_id'],$memberA['email'],'member',true,7,'Reserve direct-add seat.');av150throws(fn()=>account_admin_add_member($pdo,$admin,(string)$org2['public_id'],$outsider['username'],'member','Attempt Admin bypass.'),'effective member limit','Site Admin direct-add cannot bypass pending reserved seats.');
account_admin_add_member($pdo,$admin,(string)$org2['public_id'],$memberA['username'],'member','Consume matching invitation seat.');$pending2After=account_membership_invitation_by_public($pdo,(string)$pending2['public_id']);av150($pending2After&&$pending2After['status']==='accepted','Direct Admin add consumes a matching pending invitation instead of double-counting its reserved seat.');

$org3=account_admin_create($pdo,$admin,['name'=>'V150 Package '.$run,'account_type'=>'organization','owner'=>$owner3['username'],'package_id'=>$team['public_id'],'reason'=>'Package seat fixture.']);$pending3=account_membership_create_invitation($pdo,$config,$owner3,(string)$org3['public_id'],$outsider['email'],'member',true,7,'Reserved seat blocks downgrade.');
av150throws(fn()=>account_admin_change_package($pdo,$admin,(string)$org3['public_id'],(string)$basic['public_id'],'Too-small package.'),'reserved invitations','Package downgrade cannot ignore a reserved invitation seat.');
av150throws(fn()=>account_admin_set_override($pdo,$admin,(string)$org3['public_id'],'member_limit',1,null,'Too-small override.'),'reserved invitations','Member-limit override cannot undercut members plus reserved invitations.');
$pdo->prepare("UPDATE account_invitations SET expires_at=DATE_SUB(NOW(),INTERVAL 1 MINUTE) WHERE id=?")->execute([(int)$pending3['id']]);account_membership_expire_pending($pdo,(int)$org3['id']);$expired=account_membership_invitation_by_public($pdo,(string)$pending3['public_id']);av150($expired&&$expired['status']==='expired','Expired invitation is durably transitioned out of pending state.');$q=$pdo->prepare("SELECT COUNT(*) FROM account_membership_events WHERE invitation_id=? AND event_type='invitation_expired'");$q->execute([(int)$pending3['id']]);av150((int)$q->fetchColumn()===1,'Invitation expiry is append-only audited exactly once.');
av150((int)$pdo->query('SELECT COUNT(*) FROM teams')->fetchColumn()===$teamBefore,'Commercial account invitations and seats never create or change Research Teams.');
echo "Admin V1.50 account invitations, membership & seats database journey passed.\n";