<?php
declare(strict_types=1);
$root=dirname(__DIR__);$fail=[];
$need=function(string $file,string $needle,string $message)use(&$fail,$root){$p=$root.'/'.$file;if(!is_file($p)){$fail[]='Missing '.$file;return;}if(!str_contains((string)file_get_contents($p),$needle))$fail[]=$message;};
$m='database/migrations/20260924_077_admin_customer_success_health.sql';
foreach(['admin_customer_success_assignments','admin_customer_health_snapshots','admin_customer_success_plans','admin_customer_success_milestones','admin_customer_success_followups','admin_customer_success_events','customer_success_admin','admin.customer_success.view','admin.customer_success.manage'] as $n)$need($m,$n,'Migration 077 missing '.$n);
foreach(['function admin_customer_success_ready','function admin_customer_success_calculate_health','function admin_customer_success_snapshot','function admin_customer_success_refresh','function admin_customer_success_portfolio','function admin_customer_success_assign','function admin_customer_success_followup_create','function admin_customer_success_plan_create','function admin_customer_success_milestone_create','function admin_customer_success_agent_context'] as $n)$need('app/admin-customer-success.php',$n,'Admin V2.40 Customer Success runtime missing '.$n);
$need('app/admin-customer-success.php',"'impact'=>",'Health reasons must retain explicit contribution values.');
$need('app/admin-customer-success.php',"'fingerprint'=>",'Health snapshots must use deterministic evidence fingerprints.');
$need('app/admin-customer-success.php',"'support_sla_risk'",'Support SLA risk must participate in explainable account health.');
$need('app/admin-customer-success.php',"'critical_finance'",'Critical finance reconciliation must participate in explainable account health.');
$need('app/admin-customer-success.php',"'seat_expansion'",'Member-capacity expansion opportunity must be explicit.');
$need('app/admin-customer-success.php',"'ai_capacity_expansion'",'AI capacity expansion opportunity must be explicit.');
$need('app/admin-access.php',"'admin.customer_success.view'",'Customer Success view capability must be registered.');
$need('app/admin-access.php',"'admin.customer_success.manage'",'Customer Success manage capability must be registered.');
$need('app/admin-access.php',"'/admin/customer-success.php'=>['admin.customer_success.view','admin.customer_success.manage']", 'Customer Success route must separate read and mutation authority.');
$need('app/admin-ui.php',"'customer_success'=>['label'=>'Customer Success'",'Shared Admin navigation must expose Customer Success.');
$need('app/admin-ui.php','Admin V2.40','Shared Admin shell must identify V2.40.');
foreach(['ADMIN V2.40 · CUSTOMER SUCCESS, ACCOUNT HEALTH & RETENTION','Account health portfolio','Refresh health evidence','PORTFOLIO OWNERSHIP'] as $n)$need('admin/customer-success.php',$n,'Customer Success portfolio missing '.$n);
foreach(['ADMIN V2.40 · ACCOUNT SUCCESS 360','WHY THIS HEALTH STATE','ONBOARDING & ADOPTION','SUCCESS PLANS','HEALTH HISTORY','CUSTOMER SUCCESS AUDIT'] as $n)$need('admin/customer-success-account.php',$n,'Account Success 360 missing '.$n);
$need('admin/index.php','At-risk accounts','Command Center must surface Customer Success health.');
$need('admin/index.php','CUSTOMER SUCCESS','Command Center must link Customer Success workspace.');
$need('admin/account.php','ADMIN V2.40 · CUSTOMER SUCCESS','Account 360 must surface Customer Success health.');
$need('admin/support-case.php','Customer Success','Support case must hand off into Customer Success.');
$need('admin/financial-reporting.php','Customer Success','Finance exception must hand off into Customer Success.');
$need('app/notifications.php',"'customer_success_account'",'Customer Success assignments/follow-ups must use permission-checked notification deep links.');
$need('app/agent-chat.php','admin_customer_success_agent_context','Admin Agent must receive V2.40 Customer Success context.');
$need('app/agent-chat.php','Admin V2.40 Customer Success context is read-only','Agent prompt must deny Customer Success mutation claims.');
$need('assets/css/app.css','/* Admin V2.40 — Customer Success + Admin UI consistency */','Admin-wide V2.40 consistency layer must exist.');
foreach(['.adminSidebar~main.panel>.pageTitle','.adminContentSplit','.adminFormGrid','.adminInlineForm','.customerSuccessMetrics','.customerOnboardingGrid'] as $n)$need('assets/css/app.css',$n,'Admin V2.40 UI consistency CSS missing '.$n);
$web=(string)file_get_contents($root.'/assets/css/app.css');$ext=(string)file_get_contents($root.'/extension/landing-app.css');if($web!==$ext)$fail[]='Extension landing base CSS must match the website base CSS after the V2.40 Admin consistency pass.';
$need('tests/ci/run-full-regression.sh','tests/admin-v2-40-customer-success-db.php','Full regression must execute V2.40 Customer Success database journey.');
$need('.github/workflows/full-regression.yml','admin-v2-40-upgrade-from-076.php','Phase gate must rehearse migration 077 from 076.');
$need('.github/workflows/package-two-zips.yml','20260924_077_admin_customer_success_health.sql','Production package must include migration 077.');
$need('tests/ci/package-smoke.sh','admin-v2-40-customer-success.md','Release smoke must require V2.40 files.');
if($fail){foreach($fail as $f)fwrite(STDERR,"FAIL: $f\n");exit(1);}echo "Admin V2.40 Customer Success and Admin UI consistency static contract passed.\n";
