<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=(string)getenv('DB_DSN');$dbUser=(string)getenv('DB_USER');$dbPass=(string)getenv('DB_PASS');if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
foreach(['installer','functions','subscriptions','ai-usage'] as $lib)require_once $root.'/app/'.$lib.'.php';
function auv1(bool $ok,string $m): void {if(!$ok)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}
function auv1throws(callable $fn,string $m): void {try{$fn();}catch(Throwable $e){echo "PASS: $m\n";return;}throw new RuntimeException('FAIL: '.$m);}
auv1(ai_usage_ready($pdo),'Migration 063 AI usage schema is ready.');
$run='auv1'.substr(bin2hex(random_bytes(5)),0,10);$pub=fn(string $p)=>$p.'-'.$run.'-'.substr(bin2hex(random_bytes(3)),0,6);
$makeUser=function(string $name,string $role='user')use($pdo,$run,$pub): array{$username=substr(strtolower($name).'_'.$run,0,48);$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,status,role,plan_tier,live_presence_mode) VALUES(?,?,?,?, 'active',?,'free','cloaked')")->execute([$pub('u'),$username,$name,$username.'@example.test',$role]);$id=(int)$pdo->lastInsertId();$q=$pdo->prepare('SELECT * FROM users WHERE id=?');$q->execute([$id]);return $q->fetch();};
$admin=$makeUser('UsageAdmin','admin');$user=$makeUser('UsageUser');
$package=subscription_package_create($pdo,$admin,['name'=>'Metered Test','slug'=>'metered-'.$run,'legacy_plan_tier'=>'pro','monthly_price'=>'1.00','monthly_ai_token_allowance'=>'100','member_limit'=>'1','trial_days'=>'0','sort_order'=>'999']);
$account=subscription_ensure_user_account($pdo,(int)$user['id'],(int)$admin['id']);$account=subscription_assign_user_package($pdo,$admin,(int)$user['id'],(string)$package['public_id'],'Metering test package.');
$pdo->prepare("INSERT INTO ai_providers(public_id,label,provider_type,enabled) VALUES(?,?, 'openai_compatible',1)")->execute([$pub('prov'),'Usage Test Provider']);$provider=(int)$pdo->lastInsertId();
$pdo->prepare("INSERT INTO ai_models(public_id,provider_id,model_name,display_name,enabled,admin_enabled,pro_enabled,max_output_tokens,input_cost_per_million_usd,output_cost_per_million_usd) VALUES(?,?,?,?,1,1,1,2048,2.0,4.0)")->execute([$pub('model'),$provider,'usage-test-model-'.$run,'Usage Test Model']);$model=(int)$pdo->lastInsertId();
$record=function(array $who,string $initiated,string $task,int $in,int $out)use($pdo,$model,$pub): array{$pdo->prepare("INSERT INTO ai_runs(public_id,user_id,initiated_by,task_type,model_id,prompt_version,status,input_tokens,output_tokens,completed_at) VALUES(?,?,?,?,?,'v1','completed',?,?,NOW())")->execute([$pub('run'),(int)$who['id'],$initiated,$task,$model,$in,$out]);$id=(int)$pdo->lastInsertId();$event=ai_usage_record_completed_run($pdo,$id,$who,$initiated,['input_tokens'=>$in,'output_tokens'=>$out,'text'=>'done'],'system','prompt');return [$id,$event];};
[$id1,$event1]=$record($user,'pro','agent_chat',50,30);auv1((int)$event1['total_tokens']===80&&(int)$event1['chargeable']===1,'User-requested run writes 80 chargeable tokens.');
$summary=ai_usage_summary_for_user($pdo,(int)$user['id']);auv1($summary!==null&&(int)$summary['used_tokens']===80&&(int)$summary['remaining_tokens']===20,'Account summary consumes the package allowance.');
ai_usage_assert_can_run($pdo,$user,'pro','agent_chat');echo "PASS: Account can run while tokens remain.\n";
[$id2,$event2]=$record($user,'pro','research_task_execution',15,10);$summary=ai_usage_summary_for_user($pdo,(int)$user['id']);auv1((int)$summary['used_tokens']===105&&(int)$summary['overage_tokens']===5&&(int)$summary['remaining_tokens']===0,'Final request may cross the allowance and subsequent usage is exhausted.');
auv1throws(fn()=>ai_usage_assert_can_run($pdo,$user,'pro','agent_chat'),'Exhausted account is blocked before another provider request.');
$adjusted=ai_usage_admin_adjust($pdo,$admin,(string)$account['public_id'],50,'Support credit for metering test.');auv1((int)$adjusted['adjustment_tokens']===50&&(int)$adjusted['remaining_tokens']===45,'Admin credit expands only the current period allowance.');
ai_usage_assert_can_run($pdo,$user,'pro','agent_chat');echo "PASS: Admin credit restores account AI availability.\n";
[$adminRun,$adminEvent]=$record($admin,'admin','admin_model_test',40,20);auv1((int)$adminEvent['chargeable']===0&&$adminEvent['usage_class']==='admin','Administrator usage is observed but not charged to a customer allowance.');
$before=ai_usage_summary_for_user($pdo,(int)$user['id']);$pdo->prepare("INSERT INTO ai_runs(public_id,user_id,initiated_by,task_type,model_id,prompt_version,status,input_tokens,output_tokens,completed_at) VALUES(?,?,?,?,?,'v1','completed',?,?,NOW())")->execute([$pub('run'),(int)$user['id'],'pro','deployment_shadow',$model,70,30]);$shadowId=(int)$pdo->lastInsertId();$shadow=ai_usage_record_completed_run($pdo,$shadowId,$user,'pro',['input_tokens'=>70,'output_tokens'=>30,'text'=>'shadow'],'system','prompt');$after=ai_usage_summary_for_user($pdo,(int)$user['id']);auv1((int)$shadow['chargeable']===0&&$shadow['usage_class']==='system'&&(int)$before['used_tokens']===(int)$after['used_tokens'],'Deployment shadow usage is system-observed and never charged.');
$pdo->prepare("INSERT INTO ai_runs(public_id,user_id,initiated_by,task_type,model_id,prompt_version,status,completed_at) VALUES(?,?,?,?,?,'v1','completed',NOW())")->execute([$pub('run'),(int)$user['id'],'pro','agent_chat',$model]);$estimatedId=(int)$pdo->lastInsertId();$estimated=ai_usage_record_completed_run($pdo,$estimatedId,$user,'pro',['input_tokens'=>null,'output_tokens'=>null,'text'=>'A provider response without usage metadata.'],'system prompt','user prompt');auv1($estimated['token_source']==='estimated'&&(int)$estimated['total_tokens']>0,'Missing provider token metadata falls back to deterministic token estimates.');
$q=$pdo->prepare('SELECT COUNT(*) FROM ai_usage_events WHERE ai_run_id=?');$q->execute([$id1]);$count=(int)$q->fetchColumn();ai_usage_record_completed_run($pdo,$id1,$user,'pro',['input_tokens'=>50,'output_tokens'=>30,'text'=>'done'],'system','prompt');$q->execute([$id1]);auv1((int)$q->fetchColumn()===$count,'Usage recording is idempotent per AI run.');
echo "Admin AI Usage V1.10 database journey passed.\n";
