<?php
declare(strict_types=1);
$root=dirname(__DIR__);$fail=[];
$need=function(string $file,string $needle,string $message)use(&$fail,$root){$p=$root.'/'.$file;if(!is_file($p)){$fail[]='Missing '.$file;return;}if(!str_contains((string)file_get_contents($p),$needle))$fail[]=$message;};
foreach(['billing_operations_settings','billing_daily_snapshots','billing_account_snapshots','billing_dunning_cases','billing_dunning_events','billing_notes','billing_cancellation_feedback','suspend_after_grace TINYINT(1) NOT NULL DEFAULT 0','suspended_by_dunning','suspended_at'] as $n)$need('database/migrations/20260924_069_billing_analytics_dunning.sql',$n,'Migration 069 missing billing-operations contract: '.$n);
foreach(['function billing_operations_current_metrics','function billing_operations_snapshot_day','function billing_operations_handle_stripe_event','function billing_operations_process_due_dunning','function billing_operations_grant_grace','function billing_operations_extend_trial','function billing_operations_resync_account','function billing_operations_alerts','function billing_operations_account_timeline','function billing_operations_agent_context'] as $n)$need('app/billing-operations.php',$n,'Billing operations runtime missing '.$n);
$need('app/billing-operations.php','FOR UPDATE','Dunning review/grace paths must row-lock mutable cases.');
$need('app/billing-operations.php',"reason<>'Billing dunning grace expired.'",'Payment recovery must respect later lifecycle decisions.');
$need('app/billing-operations.php',"'suspend_after_grace'",'Automatic suspension must remain a configurable policy.');
$need('app/billing-operations.php',"'restore_after_payment'",'Payment recovery restoration must remain configurable.');
$need('app/billing-operations.php','invoice.voided','Voided Stripe invoices must reconcile open dunning.');
$need('app/billing-operations.php','function billing_operations_close_subscription_dunning','Ended Stripe subscriptions must close related open dunning.');
$need('app/billing-operations.php','function billing_operations_close_account_dunning','Explicit account closure must close stale open dunning.');
$need('app/account-admin.php','billing_operations_close_account_dunning','Account lifecycle closure must reconcile V1.60 dunning state.');
$need('app/billing-operations.php','dunning_closed_nonbillable','Dunning worker must not suspend canceled or paused subscriptions.');
$need('app/billing-operations.php','function billing_operations_recurring_rows','Recurring revenue must have one mode-aware account pricing source.');
$need('app/billing-operations.php','stripe_price_cents','Stripe-managed revenue must use mapped Stripe Price amounts.');
$need('app/billing-operations.php','MAX(snapshot_date)','MRR movement must compare durable account snapshots rather than current package prices.');
$need('app/billing-operations.php',"reason<>'Billing dunning grace expired.'",'Admin grace and payment recovery must respect later lifecycle decisions.');
if(str_contains((string)file_get_contents($root.'/app/billing-operations.php'),'try{billing_operations_snapshot_day($pdo,null,$mode);}catch(Throwable $ignored){}'))$fail[]='Stripe webhook hot path must not rebuild full daily/account snapshots.';
$need('app/stripe-billing.php','billing_operations_handle_stripe_event','Stripe webhook processing must feed V1.60 operations after provider synchronization.');
$need('app/stripe-billing.php',"'amount_cents'=>\$amount",'Refund/dispute audit must persist provider amount for revenue snapshots.');
$need('app/bootstrap.php',"/billing-operations.php'",'Billing operations runtime must load from bootstrap.');
$need('app/account-admin.php',"'admin_account_create'",'Admin-created accounts must emit canonical package events for MRR movement.');
$need('admin/billing-analytics.php','Billing analytics, revenue operations & dunning','Admin V1.60 dashboard is required.');
$need('admin/billing-analytics.php','Review due dunning','Admin must expose explicit dunning review.');
$need('admin/billing-analytics.php','Extend','Admin must expose explicit Stripe trial extension.');
$need('app/admin-ui.php',"'billing_analytics'=>",'Admin navigation must expose Billing Analytics.');
$need('app/admin-ui.php','Open billing dunning cases','Admin dashboard must surface dunning attention.');
$need('admin/account.php','Account billing timeline','Account detail must expose combined billing operations history.');
$need('billing.php','cancellation_feedback','Self-service billing must capture cancellation feedback separately from Stripe mutation.');
$need('billing.php','This records feedback only.','Cancellation feedback UX must not imply it changes Stripe.');
$need('app/agent-chat.php','billing_operations_agent_context','Admin Agent Chat must receive read-only billing analytics context.');
$need('app/agent-chat.php','Admin billing analytics context is read-only','Agent must not acquire autonomous financial mutation authority.');
$need('bin/billing-operations.php','billing_operations_process_due_dunning','Daily billing worker must review dunning.');
$need('bin/billing-operations.php','billing_operations_snapshot_day','Daily billing worker must persist snapshots.');
$need('tests/ci/run-full-regression.sh','tests/admin-v1-60-billing-analytics-db.php','Full regression must execute V1.60 billing operations journey.');
$need('.github/workflows/full-regression.yml','admin-v1-60-upgrade-from-068.php','Phase gate must rehearse migration 069 from 068.');
$need('.github/workflows/package-two-zips.yml','20260924_069_billing_analytics_dunning.sql','Production package must include migration 069.');
$css=(string)file_get_contents($root.'/assets/css/app.css');$ext=(string)file_get_contents($root.'/extension/landing-app.css');if(!hash_equals(hash('sha256',$css),hash('sha256',$ext)))$fail[]='Website and extension shared CSS must remain byte-identical.';
if($fail){foreach($fail as $f)fwrite(STDERR,"FAIL: $f\n");exit(1);}echo "Admin V1.60 billing analytics, revenue operations & dunning static contract passed.\n";