<?php
declare(strict_types=1);
$root=dirname(__DIR__);$fail=[];
$need=function(string $file,string $needle,string $message)use(&$fail,$root){$p=$root.'/'.$file;if(!is_file($p)){$fail[]='Missing '.$file;return;}if(!str_contains((string)file_get_contents($p),$needle))$fail[]=$message;};
foreach(['account_invitations','account_membership_events','token_hash','reserves_seat','actor_ip_hash','actor_user_agent_hash'] as $n)$need('database/migrations/20260924_068_account_invitations_membership_seats.sql',$n,'Migration 068 missing '.$n);
$migration=(string)file_get_contents($root.'/database/migrations/20260924_068_account_invitations_membership_seats.sql');if(preg_match('/\btoken\s+VARCHAR/i',$migration))$fail[]='Invitation plaintext tokens must never be persisted.';
foreach(['function account_membership_create_invitation','function account_membership_accept_invitation','function account_membership_resend_invitation','function account_membership_revoke_invitation','function account_membership_seat_summary','function account_membership_transfer_owner','function account_membership_agent_context'] as $n)$need('app/account-membership.php',$n,'Membership runtime missing '.$n);
$need('app/account-membership.php',"hash('sha256',\$token)",'Invitation tokens must be stored as SHA-256 hashes.');
$need('app/account-membership.php','commercial_account_with_lock','Membership mutations must serialize on the commercial account.');
$need('app/account-membership.php',"'account-invite-create'",'Invitation creation must be rate limited.');
$need('app/account-membership.php','FOR UPDATE','Invitation expiry must row-lock pending records before transition.');
$need('app/account-membership.php',"account['status']!=='active'",'Inactive accounts must not accept/send membership invitations.');
$need('app/account-membership.php','str_replace(["\r","\n"]','Invitation mail headers must sanitize account-controlled text.');
$need('account-invite.php','require_csrf()','Invitation acceptance/decline must be CSRF protected.');
$need('account-invite.php',"header('Location: /account-invite.php',true,303)",'Invitation token landing must immediately redirect to a clean URL.');
$need('account-invite.php','Cache-Control: no-store','Invitation token pages must not be cached.');
$need('account-invite.php','account_membership_clear_pending_session','Invalid token landing must clear stale pending invitation session state.');
$need('account-invite.php','Commercial account membership is separate from Research Teams','Invitation UX must preserve Research Team separation.');
$need('register.php','account_membership_pending_session_invite','Registration must preserve invitation email binding.');
$need('register.php',"Use the email address this account invitation was sent to.",'Registration must reject a different invited email.');
$need('login.php','pending account invitation','Login must preserve invitation intent.');
$need('account-members.php','Members & seats','Self-service commercial membership workspace is required.');
$need('account-members.php','Reserve a seat while pending','Self-service must expose pending-seat reservation behavior.');
$need('admin/account.php','INVITATIONS & SEATS','Admin account detail must expose invitation/seat administration.');
$need('app/account-admin.php','reserved invitations','Privileged account/package/member-limit operations must honor reserved seats.');
$need('app/stripe-billing.php','account_membership_pending_reserved_count','Stripe package preflight must honor reserved invitations.');
$need('app/agent-chat.php','account_membership_agent_context','Agent Chat must receive read-only commercial membership context.');
$need('app/agent-chat.php','cannot add, remove, invite, or transfer account members','Agent must not gain autonomous membership authority.');
$need('app/shell.php','/account-members.php','User menu must expose account member administration.');
$need('tests/ci/run-full-regression.sh','tests/admin-v1-50-account-membership-db.php','Full regression must execute V1.50 membership journey.');
$need('.github/workflows/full-regression.yml','admin-v1-50-upgrade-from-067.php','Phase gate must rehearse migration 068 from 067.');
$need('.github/workflows/package-two-zips.yml','20260924_068_account_invitations_membership_seats.sql','Production package must include migration 068.');
$css=(string)file_get_contents($root.'/assets/css/app.css');$ext=(string)file_get_contents($root.'/extension/landing-app.css');if(!hash_equals(hash('sha256',$css),hash('sha256',$ext)))$fail[]='Website and extension shared CSS must remain byte-identical.';
if($fail){foreach($fail as $f)fwrite(STDERR,"FAIL: $f\n");exit(1);}echo "Admin V1.50 account invitations, membership & seats static contract passed.\n";