<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=(string)getenv('DB_DSN');$dbUser=(string)getenv('DB_USER');$dbPass=(string)getenv('DB_PASS');if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
foreach(['installer','functions','concurrency','subscriptions','account-admin','account-membership','stripe-billing','ai-usage','ai-overage-billing'] as $lib)require_once $root.'/app/'.$lib.'.php';
function ov70(bool $ok,string $m): void {if(!$ok)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}
function ov70throws(callable $fn,string $m): void {try{$fn();}catch(Throwable $e){echo "PASS: $m\n";return;}throw new RuntimeException('FAIL: '.$m);}
ov70(ai_overage_ready($pdo),'Migration 070 AI overage schema is ready.');
$run='ov70'.substr(bin2hex(random_bytes(5)),0,10);$pub=fn(string $p)=>$p.'-'.$run.'-'.substr(bin2hex(random_bytes(3)),0,6);
$makeUser=function(string $name,string $role='user')use($pdo,$run,$pub): array{$username=substr(strtolower($name).'_'.$run,0,48);$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,status,role,plan_tier,live_presence_mode) VALUES(?,?,?,?, 'active',?,'free','cloaked')")->execute([$pub('u'),$username,$name,$username.'@example.test',$role]);$id=(int)$pdo->lastInsertId();$q=$pdo->prepare('SELECT * FROM users WHERE id=?');$q->execute([$id]);return $q->fetch();};
$admin=$makeUser('OverageAdmin','admin');$user=$makeUser('OverageUser');
$package=subscription_package_create($pdo,$admin,['name'=>'Overage Test','slug'=>'overage-'.$run,'legacy_plan_tier'=>'pro','monthly_price'=>'25.00','monthly_ai_token_allowance'=>'100','member_limit'=>'2','trial_days'=>'0','sort_order'=>'999']);
ai_overage_admin_update_package($pdo,$admin,(string)$package['public_id'],['ai_overage_policy'=>'allow_overage','ai_overage_input_dollars_per_million'=>'10.00','ai_overage_output_dollars_per_million'=>'20.00','ai_overage_default_cap_dollars'=>'5.00']);
$account=subscription_ensure_user_account($pdo,(int)$user['id'],(int)$admin['id']);$account=subscription_assign_user_package($pdo,$admin,(int)$user['id'],(string)$package['public_id'],'V1.70 overage test.');
$pdo->prepare("UPDATE accounts SET billing_source='stripe',subscription_status='active' WHERE id=?")->execute([(int)$account['id']]);
$pdo->prepare("INSERT INTO stripe_customers(public_id,account_id,mode,stripe_customer_id) VALUES(?,?, 'test',?)")->execute([$pub('cus'),(int)$account['id'],'cus_'.$run]);
$pdo->prepare("INSERT INTO stripe_subscriptions(public_id,account_id,mode,stripe_subscription_id,stripe_customer_id,status,current_period_start,current_period_end) VALUES(?,?, 'test',?,?, 'active',NOW(),DATE_ADD(NOW(),INTERVAL 1 MONTH))")->execute([$pub('sub'),(int)$account['id'],'sub_'.$run,'cus_'.$run]);
$summary=ai_overage_account_summary($pdo,(int)$account['id']);ov70(!$summary['policy']['enabled'],'Customer overage is off by default.');
ov70throws(fn()=>ai_overage_assert_account_can_run($pdo,(int)$account['id']),'Overage cannot continue without explicit opt-in.');
$enabled=ai_overage_customer_save($pdo,$user,(int)$account['id'],true,500);ov70($enabled['policy']['enabled']&&(int)$enabled['policy']['monthly_cap_cents']===500,'Account owner can explicitly enable overage with a monthly cap.');
$pdo->prepare("INSERT INTO ai_providers(public_id,label,provider_type,enabled) VALUES(?,?, 'openai_compatible',1)")->execute([$pub('prov'),'Overage Provider']);$provider=(int)$pdo->lastInsertId();
$pdo->prepare("INSERT INTO ai_models(public_id,provider_id,model_name,display_name,enabled,admin_enabled,pro_enabled,max_output_tokens,input_cost_per_million_usd,output_cost_per_million_usd) VALUES(?,?,?,?,1,1,1,2048,1.0,2.0)")->execute([$pub('model'),$provider,'overage-model-'.$run,'Overage Model']);$model=(int)$pdo->lastInsertId();
$insertUsage=function(int $input,int $output)use($pdo,$account,$user,$provider,$model,$pub): int{$pdo->prepare("INSERT INTO ai_usage_events(public_id,account_id,user_id,provider_id,model_id,initiated_by,usage_class,chargeable,task_type,token_source,input_tokens,output_tokens,total_tokens,period_start,period_end,metadata_json) VALUES(?,?,?,?,?,'pro','account',1,'agent_chat','provider',?,?,?,?,?,?)")->execute([$pub('usage'),(int)$account['id'],(int)$user['id'],$provider,$model,$input,$output,$input+$output,$account['period_start'],$account['period_end'],'{}']);return (int)$pdo->lastInsertId();};
$first=$insertUsage(50,30);$l1=ai_overage_record_usage_event($pdo,$first);ov70((int)$l1['overage_tokens']===0&&(int)$l1['amount_micros']===0,'Included usage does not create an overage charge.');
$second=$insertUsage(30,20);$l2=ai_overage_record_usage_event($pdo,$second);ov70((int)$l2['overage_tokens']===30&&(int)$l2['overage_input_tokens']===10&&(int)$l2['overage_output_tokens']===20,'Crossing the allowance attributes input/output overage exactly.');
ov70((int)$l2['amount_micros']===500,'Overage pricing preserves sub-cent micro-dollar precision.');
$again=ai_overage_record_usage_event($pdo,$second);ov70((int)$again['id']===(int)$l2['id'],'Overage ledger is idempotent per AI usage event.');
$q=$pdo->prepare('SELECT COUNT(*) FROM ai_overage_threshold_events WHERE account_id=? AND threshold_type=? AND threshold_percent=100');$q->execute([(int)$account['id'],'allowance']);ov70((int)$q->fetchColumn()===1,'Allowance threshold crossing is deduplicated per period.');
ai_overage_assert_projected_request($pdo,(int)$account['id'],1000,1000,0);echo "PASS: Projected request under configured dollar cap is permitted.\n";
$pdo->prepare('UPDATE ai_overage_account_settings SET monthly_cap_cents=1 WHERE account_id=?')->execute([(int)$account['id']]);ov70throws(fn()=>ai_overage_assert_projected_request($pdo,(int)$account['id'],1000000,1000000,0),'Projected request exceeding the account cap is blocked before provider execution.');
$pdo->prepare("UPDATE stripe_billing_settings SET mode='live' WHERE id=1")->execute();$live=ai_overage_account_summary($pdo,(int)$account['id']);ov70((int)$live['accrued_micros']===0,'Test and Live overage ledgers are isolated by Stripe mode.');$pdo->prepare("UPDATE stripe_billing_settings SET mode='test' WHERE id=1")->execute();
$pdo->prepare('UPDATE subscription_packages SET monthly_ai_token_allowance=200 WHERE id=?')->execute([(int)$package['id']]);$usage=ai_usage_account_summary($pdo,(int)$account['id']);ov70($usage['effective_allowance']!==null&&(int)$usage['effective_allowance']>=100&&(int)$usage['effective_allowance']<=200,'Mid-period allowance change is prorated instead of fully resetting usage.');
echo "Admin V1.70 AI overage billing database journey passed.\n";
