<?php
declare(strict_types=1);
$root=dirname(__DIR__);$fail=[];
$need=function(string $file,string $needle,string $message)use($root,&$fail){$s=(string)file_get_contents($root.'/'.$file);if(!str_contains($s,$needle))$fail[]=$message;};
$avoid=function(string $file,string $needle,string $message)use($root,&$fail){$s=(string)file_get_contents($root.'/'.$file);if(str_contains($s,$needle))$fail[]=$message;};

foreach(['app/shell.php','chrome-extension.php','team.php','teams.php'] as $file)if(!is_file($root.'/'.$file))$fail[]="Missing product shell file: $file";
$need('app/bootstrap.php',"/shell.php",'Bootstrap must load the universal application shell.');
$need('app/functions.php','app_shell_activate($pdo,$user)','Authenticated identity must activate the shared shell.');
$need('app/functions.php','profile_image_url','Current user identity must expose the profile image.');
$need('app/shell.php','/teams.php','Teams must be first-class universal navigation.');
$need('app/shell.php','/chrome-extension.php','Universal shell must expose Chrome extension download/install.');
$need('app/shell.php','appUserMenu','Universal header must include the profile/avatar dropdown.');
$need('app/shell.php','app_shell_header_notification','Universal header must render the notification center control.');
$need('app/shell.php','app_shell_unread_count','Header notification badge must use the live unread notification count.');
$need('app/shell.php','appHeaderNotificationBadge','Unread notifications must render as a header badge.');
$need('app/shell.php','appHeaderNotificationDropdown','Header bell must expose a notification dropdown.');
$need('app/shell.php','app_shell_notification_preview','Header dropdown must use permission-filtered notification rows.');
$need('app/shell.php','View all notifications','Header dropdown must link to the full notification center.');
$need('assets/css/app.css','/* Header notification dropdown + notification page rhythm */','Notification dropdown and page spacing layer must exist.');
$need('assets/css/app.css','.appShellContent>.notificationCenter{','Notifications page must have dedicated shell spacing.');
$need('assets/css/app.css','/* Annotated shell sharp UI pass */','Shared shell must include the sharp visual refinement layer.');
$need('assets/css/app.css','.appHeaderNotificationBadge{','Header notification badge must have dedicated centered styling.');
$need('assets/css/app.css','/* Shared header stacking integrity */','Shared header must own a stacking context above sticky page controls.');
$need('assets/css/app.css','z-index:400','Shared header must render above Home sticky controls and menus.');
$need('assets/css/app.css','isolation:isolate','Shared header stacking context must be isolated.');
$need('assets/css/app.css','box-shadow:inset 2px 0 0 #111','Active sidebar navigation must use the sharper inset indicator.');
$need('app/shell.php','appShellFooter','Every authenticated product page must inherit the shared footer.');
$need('app/shell.php','$isAdmin','Admin navigation must be role-gated.');
$need('app/shell.php','app_shell_admin_nav','Admin pages must use the dedicated permission-aware admin navigation.');
$avoid('app/shell.php',"app_shell_link('/ai.php','Ask Annotated'",'User sidebar must not include Ask Annotated.');
$avoid('app/shell.php',"app_shell_link('/search.php','Search'",'User sidebar must not include Search; global search belongs in the header.');
$avoid('app/shell.php',"'SOCIAL RESEARCH'",'User sidebar must not render the Social Research section title.');
$avoid('app/shell.php',"app_shell_link('/notifications.php','Notifications'",'User sidebar must not include Notifications; the shared header owns notifications.');
$avoid('app/shell.php',"app_shell_link('/data-attribution.php','Data & Attribution'",'User sidebar must not include Data & Attribution.');
$need('app/shell.php','<a href="/data-attribution.php">Data & Attribution</a>','Data & Attribution must live in the user dropdown.');
$need('app/shell.php','research_agent_list','Sidebar Research Agents must come from the explicit Research Agent registry.');
$need('app/shell.php','research_agent_ensure_default','Sidebar must provision the user\'s one default Research Agent when needed.');
$need('app/research-agents.php','is_default','Research Agent runtime must explicitly identify the default Agent.');
$need('app/research-agents.php','function research_agent_ensure_default','Research Agent runtime must provide idempotent default provisioning.');
$need('app/shell.php','appShellSectionTitle">Research Agents','User sidebar must expose a Research Agents section.');
$need('app/shell.php','data-research-agent-add','Research Agents section must expose a + create button.');
$need('app/shell.php','New Research Agent','Sidebar + control must open the New Research Agent modal.');
$need('assets/js/research-agent-shell.js','/api/research-agents.php?action=create','New Research Agent modal must create an explicit Research Agent through the API.');
$avoid('profile.php',"$GLOBALS['annotated_shell_mode']='header_only'",'Signed-in Profile must use the full Annotated shell.');
$need('profile.php',"if(!$viewer):?><header class=\"topbar\"", 'Profile legacy header must be restricted to logged-out public visitors.');
$need('assets/css/app.css','/* Profile shell repair */','Profile must have a dedicated shell layout repair.');
$avoid('annotation.php','<header class="topbar">','Annotation detail pages must not render a second legacy header inside the shared app shell.');
$need('app/shell.php','/home.php?agent=','Research Agent sidebar items must deep-link to existing Agent chats.');
$need('app/shell.php','app_shell_research_project_rows','Sidebar Research Projects must come from permission-scoped project records.');
$need('app/shell.php','appShellSectionTitle">Research Projects','Accessible Research projects must appear in the sidebar.');
$need('app/shell.php','/research-project.php?id=','Research Project sidebar items must deep-link to existing project workspaces.');
$need('assets/css/app.css','/* Sidebar Research Projects */','Research Projects must have compact sidebar styling.');
$need('assets/css/app.css','/* Sidebar Research Agents */','Research Agents list must have dedicated compact sidebar styling.');
$avoid('app/shell.php','<strong>Chrome Extension</strong>','User sidebar footer must not include the Chrome Extension download button.');
$avoid('app/shell.php','Open Admin','User sidebar footer must not include an Open Admin button.');
$need('assets/css/app.css','line-height:calc(1.2em - 3px)','Sidebar navigation line height must be reduced by 3px.');
$need('teams.php','/team.php?id=','Teams list must open real team workspaces.');
$need('team.php','team_members','Team workspace must expose permission-scoped membership.');
$need('team.php','profile_image_url','Team members must display social identity/profile images.');
$need('home.php','Discover researchers','Home must expose social discovery.');
$need('home.php','Your teams','Home must expose team membership.');
$need('settings.php','profile_image_url','Settings must let users control their profile picture.');
$need('chrome-extension.php','Annotated-Chrome-Extension.zip','Extension page must offer the packaged Chrome download.');
$need('.github/workflows/package-two-zips.yml','package-website/downloads/Annotated-Chrome-Extension.zip','Website package must embed the Chrome extension ZIP.');
$need('live.php','if($sourcePublic','Live navigation must have a directory rather than require a source ID.');
$need('ai.php','catch(PDOException $e)','Ask Annotated must tolerate pre-upgrade project ordering during migration recovery.');

if($fail){foreach($fail as $f)fwrite(STDERR,"FAIL: $f\n");exit(1);}
echo "Universal app shell and social product contracts passed.\n";
