<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=(string)getenv('DB_DSN');$dbUser=(string)getenv('DB_USER');$dbPass=(string)getenv('DB_PASS');if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
$pdo2=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
foreach(['installer','functions','subscriptions','account-admin','stripe-billing','ai-usage'] as $lib)require_once $root.'/app/'.$lib.'.php';
function cah(bool $ok,string $message):void{if(!$ok)throw new RuntimeException('FAIL: '.$message);echo "PASS: $message\n";}
function cahThrows(callable $fn,string $contains,string $message):void{try{$fn();}catch(Throwable $e){if($contains!==''&&!str_contains($e->getMessage(),$contains))throw new RuntimeException('FAIL: '.$message.' (unexpected error: '.$e->getMessage().')');echo "PASS: $message\n";return;}throw new RuntimeException('FAIL: '.$message);}
function cahSigned(array $event,string $secret):array{$payload=json_encode($event,JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);$t=time();return [$payload,'t='.$t.',v1='.hash_hmac('sha256',$t.'.'.$payload,$secret)];}
cah(stripe_billing_ready($pdo),'Migration 066 Stripe hardening schema is ready.');
$run='audit'.substr(bin2hex(random_bytes(6)),0,12);$seq=0;$pub=function(string $p)use($run,&$seq):string{return $p.'-'.$run.'-'.(++$seq);};
$mk=function(string $name,string $role='user')use($pdo,$run,$pub):array{$u=strtolower($name).'_'.$run;$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,status,role,plan_tier,live_presence_mode) VALUES(?,?,?,?, 'active',?,'free','cloaked')")->execute([$pub('u'),$u,$name,$u.'@example.test',$role]);$id=(int)$pdo->lastInsertId();$q=$pdo->prepare('SELECT * FROM users WHERE id=?');$q->execute([$id]);return $q->fetch();};
$admin=$mk('AuditAdmin','admin');$user=$mk('AuditUser');$member=$mk('AuditMember');$teamBefore=(int)$pdo->query('SELECT COUNT(*) FROM teams')->fetchColumn();
$account=subscription_ensure_user_account($pdo,(int)$user['id'],(int)$admin['id']);$team=subscription_package($pdo,'team-builder');$basic=subscription_package($pdo,'basic-user');if(!$team||!$basic)throw new RuntimeException('Seeded packages unavailable.');
subscription_assign_user_package($pdo,$admin,(int)$user['id'],(string)$team['public_id'],'Audit account lock fixture.');
$account=subscription_user_account($pdo,(int)$user['id'],false);$lock=app_advisory_lock($pdo,'commercial-account',(int)$account['id'],0);
try{cahThrows(fn()=>account_admin_add_member($pdo2,$admin,(string)$account['public_id'],$member['username'],'member','Lock contention fixture.'),'already in progress','Concurrent member mutation is rejected while the account serialization lock is held.');}finally{app_advisory_unlock($pdo,$lock);}
$members=account_admin_add_member($pdo,$admin,(string)$account['public_id'],$member['username'],'member','Lock released fixture.');cah(count($members)===2,'Member mutation succeeds after the serialization lock is released.');

$secret='whsec_'.$run;stripe_billing_save_settings($pdo,['app'=>['encryption_key'=>'audit-encryption-key-abcdefghijklmnopqrstuvwxyz']],$admin,['mode'=>'test','publishable_key'=>'pk_test_'.$run,'secret_key'=>'sk_test_'.$run,'webhook_secret'=>$secret,'checkout_success_path'=>'/billing.php?checkout=success','checkout_cancel_path'=>'/billing.php?checkout=cancelled','portal_return_path'=>'/billing.php']);
$price='price_'.$run;$pdo->prepare("INSERT INTO stripe_package_prices(public_id,package_id,mode,stripe_product_id,stripe_price_id,currency,unit_amount_cents,billing_interval,active,created_by_user_id) VALUES(?,?, 'test',?,?, 'usd',2999,'month',1,?)")->execute([$pub('price'),(int)$basic['id'],'prod_'.$run,$price,(int)$admin['id']]);
$customer='cus_'.$run;stripe_billing_link_customer($pdo,(int)$account['id'],'test',$customer,$user['email'],$account['name'],['fixture'=>'audit']);
$now=time();$sub='sub_'.$run;$subEvent=['id'=>'evt_sub_'.$run,'type'=>'customer.subscription.created','created'=>$now,'livemode'=>false,'data'=>['object'=>['id'=>$sub,'customer'=>$customer,'status'=>'active','current_period_start'=>$now,'current_period_end'=>$now+2592000,'metadata'=>['annotated_account_id'=>$account['public_id']],'items'=>['data'=>[['price'=>['id'=>$price]]]]]]];[$p,$s]=cahSigned($subEvent,$secret);stripe_billing_process_webhook($pdo,['app'=>['encryption_key'=>'audit-encryption-key-abcdefghijklmnopqrstuvwxyz']],$p,$s);
$newer=['id'=>'evt_paid_new_'.$run,'type'=>'invoice.paid','created'=>$now+40,'livemode'=>false,'data'=>['object'=>['id'=>'in_new_'.$run,'customer'=>$customer,'subscription'=>$sub,'status'=>'paid','currency'=>'usd','amount_due'=>2999,'amount_paid'=>2999,'amount_remaining'=>0,'lines'=>['data'=>[['period'=>['start'=>$now,'end'=>$now+2592000]]]],'status_transitions'=>['paid_at'=>$now+40]]]];[$p,$s]=cahSigned($newer,$secret);stripe_billing_process_webhook($pdo,['app'=>['encryption_key'=>'audit-encryption-key-abcdefghijklmnopqrstuvwxyz']],$p,$s);
$older=['id'=>'evt_failed_old_'.$run,'type'=>'invoice.payment_failed','created'=>$now+20,'livemode'=>false,'data'=>['object'=>['id'=>'in_old_'.$run,'customer'=>$customer,'subscription'=>$sub,'status'=>'open','currency'=>'usd','amount_due'=>2999,'amount_paid'=>0,'amount_remaining'=>2999,'lines'=>['data'=>[['period'=>['start'=>$now,'end'=>$now+2592000]]]],'status_transitions'=>[]]]];[$p,$s]=cahSigned($older,$secret);stripe_billing_process_webhook($pdo,['app'=>['encryption_key'=>'audit-encryption-key-abcdefghijklmnopqrstuvwxyz']],$p,$s);
$account=subscription_user_account($pdo,(int)$user['id'],false);cah($account&&$account['subscription_status']==='active','Older failed invoice with a different invoice ID cannot regress a newer paid account state.');
$q=$pdo->prepare("SELECT COUNT(*) FROM stripe_invoices WHERE account_id=? AND stripe_invoice_id IN (?,?)");$q->execute([(int)$account['id'],'in_new_'.$run,'in_old_'.$run]);cah((int)$q->fetchColumn()===2,'Stale cross-invoice event is still preserved in the durable invoice ledger.');
$q=$pdo->prepare("SELECT COUNT(*) FROM account_billing_events WHERE account_id=? AND event_type='invoice_stale_account_state_ignored'");$q->execute([(int)$account['id']]);cah((int)$q->fetchColumn()===1,'Cross-object stale account state is explicitly audited.');
$q=$pdo->prepare("SELECT last_event_id FROM stripe_account_state_watermarks WHERE account_id=? AND mode='test'");$q->execute([(int)$account['id']]);cah((string)$q->fetchColumn()==='evt_paid_new_'.$run,'Account state watermark remains pinned to the newer Stripe event.');

$checkoutExpired='cs_expired_'.$run;$pdo->prepare("INSERT INTO stripe_checkout_sessions(public_id,account_id,package_id,created_by_user_id,mode,stripe_customer_id,stripe_price_id,stripe_checkout_session_id,checkout_url,request_json,status,expires_at) VALUES(?,?,?,?, 'test',?,?,?,?,?,'open',DATE_ADD(NOW(),INTERVAL 1 HOUR))")
  ->execute([$pub('checkout'),(int)$account['id'],(int)$basic['id'],(int)$user['id'],$customer,$price,$checkoutExpired,'https://checkout.stripe.com/c/pay/'.$run,json_encode(['mode'=>'subscription'],JSON_UNESCAPED_SLASHES)]);
$pending=stripe_billing_checkout_pending($pdo,(int)$account['id'],'test');cah($pending&&$pending['stripe_checkout_session_id']===$checkoutExpired,'Pending Stripe Checkout ledger exposes the one reusable account session.');
$expired=['id'=>'evt_checkout_expired_'.$run,'type'=>'checkout.session.expired','created'=>$now+50,'livemode'=>false,'data'=>['object'=>['id'=>$checkoutExpired]]];[$p,$s]=cahSigned($expired,$secret);stripe_billing_process_webhook($pdo,['app'=>['encryption_key'=>'audit-encryption-key-abcdefghijklmnopqrstuvwxyz']],$p,$s);$q=$pdo->prepare('SELECT status FROM stripe_checkout_sessions WHERE stripe_checkout_session_id=?');$q->execute([$checkoutExpired]);cah($q->fetchColumn()==='expired','checkout.session.expired closes the reusable local Checkout attempt.');
$checkoutComplete='cs_complete_'.$run;$pdo->prepare("INSERT INTO stripe_checkout_sessions(public_id,account_id,package_id,created_by_user_id,mode,stripe_customer_id,stripe_price_id,stripe_checkout_session_id,checkout_url,request_json,status,expires_at) VALUES(?,?,?,?, 'test',?,?,?,?,?,'open',DATE_ADD(NOW(),INTERVAL 1 HOUR))")
  ->execute([$pub('checkout'),(int)$account['id'],(int)$basic['id'],(int)$user['id'],$customer,$price,$checkoutComplete,'https://checkout.stripe.com/c/pay/'.$run.'2',json_encode(['mode'=>'subscription'],JSON_UNESCAPED_SLASHES)]);
$completed=['id'=>'evt_checkout_complete_'.$run,'type'=>'checkout.session.completed','created'=>$now+60,'livemode'=>false,'data'=>['object'=>['id'=>$checkoutComplete,'customer'=>$customer,'client_reference_id'=>$account['public_id'],'metadata'=>['annotated_account_id'=>$account['public_id']]]]];[$p,$s]=cahSigned($completed,$secret);stripe_billing_process_webhook($pdo,['app'=>['encryption_key'=>'audit-encryption-key-abcdefghijklmnopqrstuvwxyz']],$p,$s);$q=$pdo->prepare('SELECT status FROM stripe_checkout_sessions WHERE stripe_checkout_session_id=?');$q->execute([$checkoutComplete]);cah($q->fetchColumn()==='completed','checkout.session.completed closes the local Checkout attempt idempotently.');

account_admin_set_override($pdo,$admin,(string)$account['public_id'],'monthly_ai_token_allowance',450,null,'Audit concurrent quota reservation.');
$pdo->prepare("INSERT INTO ai_providers(public_id,label,provider_type,enabled) VALUES(?,?,'openai_compatible',1)")->execute([$pub('prov'),'Audit quota provider']);$providerId=(int)$pdo->lastInsertId();
$pdo->prepare("INSERT INTO ai_models(public_id,provider_id,model_name,display_name,enabled,admin_enabled,pro_enabled,max_output_tokens) VALUES(?,?,?,?,1,1,1,256)")->execute([$pub('model'),$providerId,'audit-quota-'.$run,'Audit quota model']);$modelId=(int)$pdo->lastInsertId();
$makeRun=function()use($pdo,$pub,$user,$modelId):int{$pdo->prepare("INSERT INTO ai_runs(public_id,user_id,initiated_by,task_type,model_id,prompt_version,status) VALUES(?,?, 'pro','agent_chat',?,'v1','processing')")->execute([$pub('run'),(int)$user['id'],$modelId]);return (int)$pdo->lastInsertId();};
$run1=$makeRun();$reservation1=ai_usage_reserve_run($pdo,$run1,$user,'pro','agent_chat','','',256);cah($reservation1&&$reservation1['status']==='reserved'&&(int)$reservation1['reserved_tokens']>0,'First chargeable AI run reserves worst-case quota before provider execution.');
$summary=ai_usage_account_summary($pdo,(int)$account['id']);cah((int)$summary['reserved_tokens']===(int)$reservation1['reserved_tokens']&&(int)$summary['remaining_tokens']<450,'Outstanding AI reservation immediately reduces available account tokens.');
$run2=$makeRun();cahThrows(fn()=>ai_usage_reserve_run($pdo,$run2,$user,'pro','agent_chat','','',256),'enough remaining AI tokens','Second run cannot reserve the same remaining quota concurrently.');
ai_usage_release_run($pdo,$run1,'provider_failed');$pdo->prepare("UPDATE ai_runs SET status='failed',completed_at=NOW() WHERE id=?")->execute([$run1]);$summary=ai_usage_account_summary($pdo,(int)$account['id']);cah((int)$summary['reserved_tokens']===0&&(int)$summary['remaining_tokens']===450,'Failed provider execution releases its unused reservation.');
$reservation2=ai_usage_reserve_run($pdo,$run2,$user,'pro','agent_chat','','',256);cah($reservation2&&$reservation2['status']==='reserved','Released quota becomes reservable by a subsequent AI run.');
$pdo->prepare("UPDATE ai_runs SET status='completed',input_tokens=10,output_tokens=20,completed_at=NOW() WHERE id=?")->execute([$run2]);$usage=ai_usage_record_completed_run($pdo,$run2,$user,'pro',['input_tokens'=>10,'output_tokens'=>20,'text'=>'done'],'','');cah($usage&&(int)$usage['total_tokens']===30,'Completed AI run writes immutable provider usage.');
$q=$pdo->prepare('SELECT status,actual_tokens FROM ai_usage_reservations WHERE ai_run_id=?');$q->execute([$run2]);$settled=$q->fetch();cah($settled&&$settled['status']==='settled'&&(int)$settled['actual_tokens']===30,'Completed AI usage atomically settles its reservation to actual tokens.');
$summary=ai_usage_account_summary($pdo,(int)$account['id']);cah((int)$summary['used_tokens']===30&&(int)$summary['reserved_tokens']===0&&(int)$summary['remaining_tokens']===420,'Settled reservation stops blocking quota and actual usage becomes authoritative.');

$pdo->prepare("UPDATE accounts SET period_start='2020-01-01',period_end='2020-02-01',billing_source='stripe' WHERE id=?")->execute([(int)$account['id']]);$refreshed=ai_usage_account_by_id($pdo,(int)$account['id']);cah($refreshed&&$refreshed['period_start']==='2020-01-01'&&$refreshed['period_end']==='2020-02-01','AI usage never locally rolls a Stripe-owned billing period.');$q=$pdo->prepare('SELECT period_start,period_end FROM accounts WHERE id=?');$q->execute([(int)$account['id']]);$dates=$q->fetch();cah($dates&&$dates['period_start']==='2020-01-01'&&$dates['period_end']==='2020-02-01','Stripe-owned period remains unchanged in persistent account state.');
cah((int)$pdo->query('SELECT COUNT(*) FROM teams')->fetchColumn()===$teamBefore,'Audit hardening preserves commercial account and Research Team separation.');
echo "Code audit hardening database journey passed.\n";
