<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=(string)getenv('DB_DSN');$dbUser=(string)getenv('DB_USER');$dbPass=(string)getenv('DB_PASS');if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
$pdo2=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
foreach(['installer','functions','subscriptions','account-admin','stripe-billing','ai-usage'] as $lib)require_once $root.'/app/'.$lib.'.php';
function cah(bool $ok,string $message):void{if(!$ok)throw new RuntimeException('FAIL: '.$message);echo "PASS: $message\n";}
function cahThrows(callable $fn,string $contains,string $message):void{try{$fn();}catch(Throwable $e){if($contains!==''&&!str_contains($e->getMessage(),$contains))throw new RuntimeException('FAIL: '.$message.' (unexpected error: '.$e->getMessage().')');echo "PASS: $message\n";return;}throw new RuntimeException('FAIL: '.$message);}
function cahSigned(array $event,string $secret):array{$payload=json_encode($event,JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);$t=time();return [$payload,'t='.$t.',v1='.hash_hmac('sha256',$t.'.'.$payload,$secret)];}
cah(stripe_billing_ready($pdo),'Migration 066 Stripe hardening schema is ready.');
$run='audit'.substr(bin2hex(random_bytes(6)),0,12);$seq=0;$pub=function(string $p)use($run,&$seq):string{return $p.'-'.$run.'-'.(++$seq);};
$mk=function(string $name,string $role='user')use($pdo,$run,$pub):array{$u=strtolower($name).'_'.$run;$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,status,role,plan_tier,live_presence_mode) VALUES(?,?,?,?, 'active',?,'free','cloaked')")->execute([$pub('u'),$u,$name,$u.'@example.test',$role]);$id=(int)$pdo->lastInsertId();$q=$pdo->prepare('SELECT * FROM users WHERE id=?');$q->execute([$id]);return $q->fetch();};
$admin=$mk('AuditAdmin','admin');$user=$mk('AuditUser');$member=$mk('AuditMember');$teamBefore=(int)$pdo->query('SELECT COUNT(*) FROM teams')->fetchColumn();
$account=subscription_ensure_user_account($pdo,(int)$user['id'],(int)$admin['id']);$team=subscription_package($pdo,'team-builder');$basic=subscription_package($pdo,'basic-user');if(!$team||!$basic)throw new RuntimeException('Seeded packages unavailable.');
subscription_assign_user_package($pdo,$admin,(int)$user['id'],(string)$team['public_id'],'Audit account lock fixture.');
$account=subscription_user_account($pdo,(int)$user['id'],false);$lock=app_advisory_lock($pdo,'commercial-account',(int)$account['id'],0);
try{cahThrows(fn()=>account_admin_add_member($pdo2,$admin,(string)$account['public_id'],$member['username'],'member','Lock contention fixture.'),'already in progress','Concurrent member mutation is rejected while the account serialization lock is held.');}finally{app_advisory_unlock($pdo,$lock);}
$members=account_admin_add_member($pdo,$admin,(string)$account['public_id'],$member['username'],'member','Lock released fixture.');cah(count($members)===2,'Member mutation succeeds after the serialization lock is released.');

$secret='whsec_'.$run;stripe_billing_save_settings($pdo,['app'=>['encryption_key'=>'audit-encryption-key-abcdefghijklmnopqrstuvwxyz']],$admin,['mode'=>'test','publishable_key'=>'pk_test_'.$run,'secret_key'=>'sk_test_'.$run,'webhook_secret'=>$secret,'checkout_success_path'=>'/billing.php?checkout=success','checkout_cancel_path'=>'/billing.php?checkout=cancelled','portal_return_path'=>'/billing.php']);
$price='price_'.$run;$pdo->prepare("INSERT INTO stripe_package_prices(public_id,package_id,mode,stripe_product_id,stripe_price_id,currency,unit_amount_cents,billing_interval,active,created_by_user_id) VALUES(?,?, 'test',?,?, 'usd',2999,'month',1,?)")->execute([$pub('price'),(int)$basic['id'],'prod_'.$run,$price,(int)$admin['id']]);
$customer='cus_'.$run;stripe_billing_link_customer($pdo,(int)$account['id'],'test',$customer,$user['email'],$account['name'],['fixture'=>'audit']);
$now=time();$sub='sub_'.$run;$subEvent=['id'=>'evt_sub_'.$run,'type'=>'customer.subscription.created','created'=>$now,'livemode'=>false,'data'=>['object'=>['id'=>$sub,'customer'=>$customer,'status'=>'active','current_period_start'=>$now,'current_period_end'=>$now+2592000,'metadata'=>['annotated_account_id'=>$account['public_id']],'items'=>['data'=>[['price'=>['id'=>$price]]]]]]];[$p,$s]=cahSigned($subEvent,$secret);stripe_billing_process_webhook($pdo,['app'=>['encryption_key'=>'audit-encryption-key-abcdefghijklmnopqrstuvwxyz']],$p,$s);
$newer=['id'=>'evt_paid_new_'.$run,'type'=>'invoice.paid','created'=>$now+40,'livemode'=>false,'data'=>['object'=>['id'=>'in_new_'.$run,'customer'=>$customer,'subscription'=>$sub,'status'=>'paid','currency'=>'usd','amount_due'=>2999,'amount_paid'=>2999,'amount_remaining'=>0,'lines'=>['data'=>[['period'=>['start'=>$now,'end'=>$now+2592000]]]],'status_transitions'=>['paid_at'=>$now+40]]]];[$p,$s]=cahSigned($newer,$secret);stripe_billing_process_webhook($pdo,['app'=>['encryption_key'=>'audit-encryption-key-abcdefghijklmnopqrstuvwxyz']],$p,$s);
$older=['id'=>'evt_failed_old_'.$run,'type'=>'invoice.payment_failed','created'=>$now+20,'livemode'=>false,'data'=>['object'=>['id'=>'in_old_'.$run,'customer'=>$customer,'subscription'=>$sub,'status'=>'open','currency'=>'usd','amount_due'=>2999,'amount_paid'=>0,'amount_remaining'=>2999,'lines'=>['data'=>[['period'=>['start'=>$now,'end'=>$now+2592000]]]],'status_transitions'=>[]]]];[$p,$s]=cahSigned($older,$secret);stripe_billing_process_webhook($pdo,['app'=>['encryption_key'=>'audit-encryption-key-abcdefghijklmnopqrstuvwxyz']],$p,$s);
$account=subscription_user_account($pdo,(int)$user['id'],false);cah($account&&$account['subscription_status']==='active','Older failed invoice with a different invoice ID cannot regress a newer paid account state.');
$q=$pdo->prepare("SELECT COUNT(*) FROM stripe_invoices WHERE account_id=? AND stripe_invoice_id IN (?,?)");$q->execute([(int)$account['id'],'in_new_'.$run,'in_old_'.$run]);cah((int)$q->fetchColumn()===2,'Stale cross-invoice event is still preserved in the durable invoice ledger.');
$q=$pdo->prepare("SELECT COUNT(*) FROM account_billing_events WHERE account_id=? AND event_type='invoice_stale_account_state_ignored'");$q->execute([(int)$account['id']]);cah((int)$q->fetchColumn()===1,'Cross-object stale account state is explicitly audited.');
$q=$pdo->prepare("SELECT last_event_id FROM stripe_account_state_watermarks WHERE account_id=? AND mode='test'");$q->execute([(int)$account['id']]);cah((string)$q->fetchColumn()==='evt_paid_new_'.$run,'Account state watermark remains pinned to the newer Stripe event.');

$pdo->prepare("UPDATE accounts SET period_start='2020-01-01',period_end='2020-02-01',billing_source='stripe' WHERE id=?")->execute([(int)$account['id']]);$refreshed=ai_usage_account_by_id($pdo,(int)$account['id']);cah($refreshed&&$refreshed['period_start']==='2020-01-01'&&$refreshed['period_end']==='2020-02-01','AI usage never locally rolls a Stripe-owned billing period.');$q=$pdo->prepare('SELECT period_start,period_end FROM accounts WHERE id=?');$q->execute([(int)$account['id']]);$dates=$q->fetch();cah($dates&&$dates['period_start']==='2020-01-01'&&$dates['period_end']==='2020-02-01','Stripe-owned period remains unchanged in persistent account state.');
cah((int)$pdo->query('SELECT COUNT(*) FROM teams')->fetchColumn()===$teamBefore,'Audit hardening preserves commercial account and Research Team separation.');
echo "Code audit hardening database journey passed.\n";
