<?php
declare(strict_types=1);

$root=dirname(__DIR__);$dsn=(string)(getenv('DB_DSN')?:'mysql:host=127.0.0.1;port=3306;dbname=annotated_test;charset=utf8mb4');$dbUser=(string)(getenv('DB_USER')?:'root');$dbPass=(string)(getenv('DB_PASS')?:'root');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);$pdo2=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
require_once $root.'/app/migrations.php';
function ok(bool $condition,string $message): void {if(!$condition)throw new RuntimeException('FAIL: '.$message);echo "PASS: $message\n";}
function throws(callable $fn,string $message): Throwable {try{$fn();}catch(Throwable $e){echo "PASS: $message\n";return $e;}throw new RuntimeException('FAIL: '.$message);}
function scalar(PDO $pdo,string $sql,array $params=[]): mixed {$q=$pdo->prepare($sql);$q->execute($params);return $q->fetchColumn();}

foreach(migration_split_sql((string)file_get_contents($root.'/database/schema.sql'),$root.'/database') as $sql)$pdo->exec($sql);
$applied=migration_apply_pending($pdo,$root.'/database/migrations',5);ok(count($applied)===7,'all seven ordered migrations apply through the production migration runner');ok((int)scalar($pdo,'SELECT COUNT(*) FROM schema_migrations')===7,'migration ledger records all migrations');ok((int)scalar($pdo,"SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='ai_jobs' AND COLUMN_NAME='claim_token'")===1,'worker lease columns exist');ok((int)scalar($pdo,"SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='rate_limit_buckets'")===1,'rate-limit table exists');

require_once $root.'/app/storage.php';require_once $root.'/app/functions.php';require_once $root.'/app/rate-limit.php';require_once $root.'/app/access.php';require_once $root.'/app/concurrency.php';require_once $root.'/app/jobs.php';require_once $root.'/app/oauth.php';require_once $root.'/app/ai.php';
$config=['app'=>['encryption_key'=>'integration-test-encryption-key-32-chars-minimum'],'storage'=>['private_root'=>sys_get_temp_dir().'/annotated-ci-private-'.getmypid()],'oauth'=>[]];
$createUser=function(string $username,string $email,string $role='user',string $plan='free')use($pdo): array{$q=$pdo->prepare('INSERT INTO users(public_id,username,display_name,email,email_verified_at,password_hash,role,plan_tier) VALUES(?,?,?,?,NOW(),?,?,?)');$hash=password_hash('correct horse battery staple',PASSWORD_DEFAULT);$q->execute([ulid_like(),$username,ucfirst($username),$email,$hash,$role,$plan]);$id=(int)$pdo->lastInsertId();$q=$pdo->prepare('SELECT * FROM users WHERE id=?');$q->execute([$id]);return $q->fetch();};
$admin=$createUser('admin','admin@example.test','admin');$owner=$createUser('owner','owner@example.test');$viewer=$createUser('viewer','viewer@example.test');$researcher=$createUser('researcher','researcher@example.test');$outsider=$createUser('outsider','outsider@example.test');$pro=$createUser('pro','pro@example.test','user','pro');
ok(password_verify('correct horse battery staple',(string)$owner['password_hash']),'native password hashes authenticate correctly');ok(user_plan($pdo,$pro)==='pro'&&user_plan($pdo,$outsider)==='free'&&user_plan($pdo,$admin)==='admin','Free, Pro, and Admin plan boundaries resolve correctly');

$pdo->prepare("INSERT INTO user_identities(user_id,provider,provider_user_id,provider_email) VALUES(?,'google','google-owner','owner@example.test')")->execute([$owner['id']]);throws(fn()=>oauth_finish_login($pdo,'google','google-owner','outsider@example.test','Outsider','outsider',true,(int)$outsider['id']),'OAuth account-link collision fails closed');

$validToken=bin2hex(random_bytes(32));$expiredToken=bin2hex(random_bytes(32));$pdo->prepare("INSERT INTO extension_sessions(user_id,token_hash,device_name,expires_at) VALUES(?,?, 'CI',DATE_ADD(NOW(),INTERVAL 1 HOUR))")->execute([$owner['id'],hash('sha256',$validToken)]);$pdo->prepare("INSERT INTO extension_sessions(user_id,token_hash,device_name,expires_at) VALUES(?,?, 'CI expired',DATE_SUB(NOW(),INTERVAL 1 HOUR))")->execute([$owner['id'],hash('sha256',$expiredToken)]);$_SESSION=[];$_SERVER['HTTP_AUTHORIZATION']='Bearer '.$validToken;ok((int)(current_user($pdo)['id']??0)===(int)$owner['id'],'valid extension bearer session authenticates');$_SERVER['HTTP_AUTHORIZATION']='Bearer '.$expiredToken;ok(current_user($pdo)===null,'expired extension bearer session is rejected');unset($_SERVER['HTTP_AUTHORIZATION']);

$canonical='https://example.test/article';$pdo->prepare("INSERT INTO sources(public_id,source_type,canonical_url,canonical_url_hash,domain,title) VALUES(?,'article',?,?,'example.test','Example')")->execute([$sourcePublic=ulid_like(),$canonical,hash('sha256',$canonical)]);$sourceId=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO source_versions(source_id,version_number,final_url,title,extracted_text,content_hash) VALUES(?,1,?,?,?,?)')->execute([$sourceId,$canonical,'Example','evidence text',hash('sha256','evidence text')]);$versionId=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE sources SET current_version_id=? WHERE id=?')->execute([$versionId,$sourceId]);
$makeAnnotation=function(array $user,string $visibility,?int $teamId=null)use($pdo,$sourceId,$versionId): array{$pdo->prepare("INSERT INTO captures(public_id,source_id,source_version_id,user_id,capture_type,selected_text) VALUES(?,?,?,?,'text','evidence text')")->execute([ulid_like(),$sourceId,$versionId,$user['id']]);$capture=(int)$pdo->lastInsertId();$public=ulid_like();$pdo->prepare("INSERT INTO annotations(public_id,user_id,source_id,source_version_id,capture_id,text_commentary,visibility,team_id,status) VALUES(?,?,?,?,?,'note',?,?,'published')")->execute([$public,$user['id'],$sourceId,$versionId,$capture,$visibility,$teamId]);$q=$pdo->prepare('SELECT * FROM annotations WHERE id=?');$q->execute([(int)$pdo->lastInsertId()]);return $q->fetch();};
$publicAnnotation=$makeAnnotation($owner,'public');$privateAnnotation=$makeAnnotation($owner,'private');$pdo->prepare('INSERT INTO teams(public_id,owner_user_id,name) VALUES(?,?,?)')->execute([$teamPublic=ulid_like(),$owner['id'],'CI Team']);$teamId=(int)$pdo->lastInsertId();foreach([[$owner,'owner'],[$viewer,'viewer'],[$researcher,'researcher']] as [$tu,$role])$pdo->prepare('INSERT INTO team_members(team_id,user_id,role) VALUES(?,?,?)')->execute([$teamId,$tu['id'],$role]);$teamAnnotation=$makeAnnotation($owner,'team',$teamId);
ok(annotation_access($pdo,$publicAnnotation['public_id'],null)!==null,'public annotation is visible anonymously');ok(annotation_access($pdo,$privateAnnotation['public_id'],null)===null&&annotation_access($pdo,$privateAnnotation['public_id'],$outsider)===null,'private annotation is hidden from anonymous and unrelated users');ok(annotation_access($pdo,$privateAnnotation['public_id'],$owner)!==null,'private annotation remains visible to its owner');ok(annotation_access($pdo,$teamAnnotation['public_id'],$viewer)!==null&&annotation_access($pdo,$teamAnnotation['public_id'],$outsider)===null,'team annotation is limited to team members');

$privateCanonical='https://private.example.test/note';$pdo->prepare("INSERT INTO sources(public_id,source_type,canonical_url,canonical_url_hash,domain,title) VALUES(?,'article',?,?,'private.example.test','Private Example')")->execute([$privateSourcePublic=ulid_like(),$privateCanonical,hash('sha256',$privateCanonical)]);$privateSourceId=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO source_versions(source_id,version_number,final_url,title,extracted_text,content_hash) VALUES(?,1,?,?,?,?)')->execute([$privateSourceId,$privateCanonical,'Private Example','private evidence',hash('sha256','private evidence')]);$privateVersion=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE sources SET current_version_id=? WHERE id=?')->execute([$privateVersion,$privateSourceId]);$pdo->prepare("INSERT INTO captures(public_id,source_id,source_version_id,user_id,capture_type,selected_text) VALUES(?,?,?,?,'text','private evidence')")->execute([ulid_like(),$privateSourceId,$privateVersion,$owner['id']]);$privateCapture=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO annotations(public_id,user_id,source_id,source_version_id,capture_id,text_commentary,visibility,status) VALUES(?,?,?,?,?,'private note','private','published')")->execute([ulid_like(),$owner['id'],$privateSourceId,$privateVersion,$privateCapture]);ok(source_access($pdo,$privateSourcePublic,null)===null&&source_access($pdo,$privateSourcePublic,$outsider)===null,'private-only Source is not publicly discoverable');ok(source_access($pdo,$privateSourcePublic,$owner)!==null,'private-only Source remains visible to its authorized owner');ok(users_share_team($pdo,(int)$owner['id'],(int)$viewer['id'])&&!users_share_team($pdo,(int)$owner['id'],(int)$outsider['id']),'Team Only presence is database-scoped');

$pdo->prepare('INSERT INTO research_projects(public_id,owner_user_id,team_id,title) VALUES(?,?,?,?)')->execute([$projectPublic=ulid_like(),$owner['id'],$teamId,'CI Project']);$ownerProject=project_access($pdo,(int)$owner['id'],$projectPublic);$viewerProject=project_access($pdo,(int)$viewer['id'],$projectPublic);$researchProject=project_access($pdo,(int)$researcher['id'],$projectPublic);ok(project_can_write($ownerProject)&&!project_can_write($viewerProject)&&project_can_write($researchProject),'research viewer is read-only while owner/researcher may write');

$stored=private_storage_write($config,'secret evidence bytes','ci','txt');ok(str_starts_with($stored,'private://'),'new evidence uses private:// references');$abs=storage_path_to_absolute($config,$stored);ok($abs!==null&&is_file($abs),'private evidence resolves inside configured private storage');ok(storage_path_to_absolute($config,'private://../escape')===null,'private evidence path traversal is rejected');

$subject='email:person@example.test';$a=rate_limit_consume($pdo,'ci-limit',$subject,2,3600);$b=rate_limit_consume($pdo,'ci-limit',$subject,2,3600);$c=rate_limit_consume($pdo,'ci-limit',$subject,2,3600);ok($a['allowed']&&$b['allowed']&&!$c['allowed'],'server-side rate limiter enforces threshold atomically');$bucket=(string)scalar($pdo,"SELECT bucket_hash FROM rate_limit_buckets ORDER BY updated_at DESC LIMIT 1");ok($bucket!==''&&!str_contains($bucket,'person@example.test'),'rate-limit storage contains only hashed subject material');

$captureId=(int)$publicAnnotation['capture_id'];$pdo->prepare("INSERT INTO media_derivatives(capture_id,media_type,duration_seconds,processing_status) VALUES(?,'audio',10,'queued')")->execute([$captureId]);$derivativeId=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO media_jobs(derivative_id,source_url,start_seconds,end_seconds) VALUES(?,?,0,10)')->execute([$derivativeId,$canonical]);$select="SELECT * FROM media_jobs WHERE status='queued' AND available_at<=NOW() ORDER BY id LIMIT 1";$claim1=job_claim($pdo,'media_jobs',$select,[],60);ok($claim1!==null,'first worker atomically claims a queued job');$claim2=job_claim($pdo2,'media_jobs',$select,[],60);ok($claim2===null,'second worker cannot claim an active lease');$pdo->prepare('UPDATE media_jobs SET lease_expires_at=DATE_SUB(NOW(),INTERVAL 1 SECOND) WHERE id=?')->execute([$claim1['id']]);$claim3=job_claim($pdo2,'media_jobs',$select,[],60);ok($claim3!==null&&$claim3['claim_token']!==$claim1['claim_token'],'expired worker lease is reclaimed with a new token');throws(fn()=>job_claim_complete($pdo,'media_jobs',(int)$claim1['id'],(string)$claim1['claim_token']),'stale worker cannot complete a reclaimed job');job_claim_complete($pdo2,'media_jobs',(int)$claim3['id'],(string)$claim3['claim_token']);

$pdo->beginTransaction();lock_source_row($pdo,$sourceId);$pdo2->exec('SET innodb_lock_wait_timeout=1');$pdo2->beginTransaction();throws(fn()=>lock_source_row($pdo2,$sourceId),'concurrent Source Version writer blocks on canonical Source row');if($pdo2->inTransaction())$pdo2->rollBack();$pdo->commit();$pdo2->beginTransaction();lock_source_row($pdo2,$sourceId);ok(next_source_version_number($pdo2,$sourceId)===2,'next Source Version number is allocated under the canonical row lock');$pdo2->rollBack();

$tmp=sys_get_temp_dir().'/annotated-migration-ci-'.bin2hex(random_bytes(4));mkdir($tmp,0770,true);$version='20990101_001_ci_retry';$file=$tmp.'/'.$version.'.sql';file_put_contents($file,"CREATE TABLE IF NOT EXISTS ci_partial(id INT PRIMARY KEY);\nSELECT * FROM ci_environment_dependency;\n");throws(fn()=>migration_apply_pending($pdo,$tmp,2),'migration failure is surfaced and recorded');ok((string)scalar($pdo,'SELECT status FROM schema_migration_runs WHERE version=?',[$version])==='failed','failed migration attempt is persisted');$pdo->exec('CREATE TABLE ci_environment_dependency(id INT PRIMARY KEY)');$retry=migration_apply_pending($pdo,$tmp,2);ok(in_array($version,$retry,true),'same immutable migration succeeds after environment repair');ok((string)scalar($pdo,'SELECT status FROM schema_migration_runs WHERE version=?',[$version])==='applied','migration retry becomes applied without changing checksum');
$empty=sys_get_temp_dir().'/annotated-migration-empty-'.bin2hex(random_bytes(4));mkdir($empty,0770,true);ok((int)$pdo2->query("SELECT GET_LOCK('annotated_schema_upgrade',0)")->fetchColumn()===1,'second connection can hold schema-upgrade advisory lock');throws(fn()=>migration_apply_pending($pdo,$empty,1),'concurrent schema upgrade runner is rejected');$pdo2->query("SELECT RELEASE_LOCK('annotated_schema_upgrade')");

@unlink($file);@rmdir($tmp);@rmdir($empty);if($abs)@unlink($abs);echo "MariaDB integration/security suite passed.\n";
