<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=getenv('DB_DSN')?:'';$dbUser=getenv('DB_USER')?:'root';$dbPass=getenv('DB_PASS')?:'';if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
foreach(['installer','storage','jobs','concurrency','functions','shell','access','notifications','rate-limit','ai','ai-access','source-integrity','annotation-intelligence','research-workspace','research-knowledge','research-intelligence','research-reports','conversations','agent-actions','agent-chat','cognitive-feed','research-entities','proactive-intelligence','research-automation','cross-research','research-outcomes','research-reviews','change-impact','research-portfolio','living-research','research-network','research-provenance'] as $lib)require_once $root.'/app/'.$lib.'.php';
function p26(bool $ok,string $m): void {if(!$ok)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}
$run='p26'.substr(bin2hex(random_bytes(6)),0,10);$pub=fn(string $p)=>$p.'-'.$run.'-'.substr(bin2hex(random_bytes(3)),0,6);
$makeUser=function(string $name)use($pdo,$run,$pub): array{$username=substr(strtolower($name).'_'.$run,0,48);$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,email_verified_at,status,role,plan_tier,live_presence_mode) VALUES(?,?,?,?,NOW(),'active','user','pro','cloaked')")->execute([$pub('u'),$username,$name,$username.'@example.test']);$id=(int)$pdo->lastInsertId();$pdo->prepare('INSERT IGNORE INTO user_preferences(user_id) VALUES(?)')->execute([$id]);$q=$pdo->prepare('SELECT * FROM users WHERE id=?');$q->execute([$id]);return $q->fetch();};
$owner=$makeUser('ProvenanceOwner');$member=$makeUser('ProvenanceMember');$outsider=$makeUser('ProvenanceOutsider');p26(provenance_ready($pdo),'Phase 26 schema is available');

$targetProject=$pub('target-project');$pdo->prepare("INSERT INTO research_projects(public_id,owner_user_id,title,description,status) VALUES(?,?,?,?,'active')")->execute([$targetProject,$owner['id'],'Public Citation Target','Target publication for provenance citation']);$tp=project_access($pdo,$owner['id'],$targetProject);$targetPublished=research_report_publish($pdo,$tp,$owner,'public','Public Target Report','Public target for provenance chain.','Provenance');$targetReport=research_report_access($pdo,(string)$targetPublished['public_id'],$owner);

$teamPublic=$pub('team');$pdo->prepare('INSERT INTO teams(public_id,owner_user_id,name) VALUES(?,?,?)')->execute([$teamPublic,$owner['id'],'Provenance Team']);$teamId=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO team_members(team_id,user_id,role) VALUES(?,?,'owner'),(?,?,'researcher')")->execute([$teamId,$owner['id'],$teamId,$member['id']]);
$projectPublic=$pub('project');$pdo->prepare("INSERT INTO research_projects(public_id,owner_user_id,team_id,title,description,status) VALUES(?,?,?,?,?,'active')")->execute([$projectPublic,$owner['id'],$teamId,'Provenance Research','Full lineage fixture']);$projectId=(int)$pdo->lastInsertId();$project=project_access($pdo,$owner['id'],$projectPublic);

$url='https://example.com/'.$run.'/source';$sourcePublic=$pub('source');$pdo->prepare("INSERT INTO sources(public_id,source_type,canonical_url,canonical_url_hash,domain,title,status,monitoring_enabled,moderation_status) VALUES(?,'article',?,?,?,'Provenance Source','current',1,'visible')")->execute([$sourcePublic,$url,hash('sha256',$url),'example.com']);$sourceId=(int)$pdo->lastInsertId();
$text='Exact source evidence for provenance.';$contentHash=hash('sha256',$text);$pdo->prepare("INSERT INTO source_versions(source_id,version_number,final_url,title,extracted_text,content_hash,target_content_hash,captured_at) VALUES(?,1,?,'Provenance Source',?,?,?,NOW())")->execute([$sourceId,$url,$text,$contentHash,hash('sha256','target-'.$run)]);$sv1=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE sources SET current_version_id=? WHERE id=?')->execute([$sv1,$sourceId]);$pdo->prepare('INSERT INTO project_sources(project_id,source_id,added_by_user_id) VALUES(?,?,?)')->execute([$projectId,$sourceId,$owner['id']]);

$capturePublic=$pub('capture');$pdo->prepare("INSERT INTO captures(public_id,source_id,source_version_id,user_id,capture_type,selected_text) VALUES(?,?,?,?,'text',?)")->execute([$capturePublic,$sourceId,$sv1,$owner['id'],$text]);$captureId=(int)$pdo->lastInsertId();
$annotationPublic=$pub('annotation');$pdo->prepare("INSERT INTO annotations(public_id,user_id,source_id,source_version_id,capture_id,text_commentary,visibility,status) VALUES(?,?,?,?,?,'Owner commentary','team','published')")->execute([$annotationPublic,$owner['id'],$sourceId,$sv1,$captureId]);$annotationId=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO project_annotations(project_id,annotation_id,added_by_user_id) VALUES(?,?,?)')->execute([$projectId,$annotationId,$owner['id']]);

$claimPublic=$pub('claim');$pdo->prepare("INSERT INTO research_claims(public_id,project_id,created_by_user_id,statement,claim_type,status) VALUES(?,?,?,'The provenance evidence supports this Claim.','factual','supported')")->execute([$claimPublic,$projectId,$owner['id']]);$claimId=(int)$pdo->lastInsertId();$evidencePublic=$pub('evidence');$pdo->prepare("INSERT INTO claim_evidence(public_id,claim_id,added_by_user_id,evidence_type,annotation_id,source_version_id,relationship,note) VALUES(?,?,?,'annotation',?,?,'primary','Pinned evidence note')")->execute([$evidencePublic,$claimId,$owner['id'],$annotationId,$sv1]);
$findingPublic=$pub('finding');$pdo->prepare("INSERT INTO research_findings(public_id,project_id,created_by_user_id,title,summary,status) VALUES(?,?,?,'Provenance Finding','Finding synthesized from the provenance Claim.','final')")->execute([$findingPublic,$projectId,$owner['id']]);$findingId=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO finding_claims(finding_id,claim_id,added_by_user_id,relationship,position) VALUES(?,?,?,'primary',0)")->execute([$findingId,$claimId,$owner['id']]);

$ref=research_network_reference_upsert($pdo,$owner,$projectPublic,(string)$targetReport['public_id'],1,'background','External published Research reference.');p26(($ref['target']['version_number']??0)===1,'working citation is version-pinned before publication');
$review=research_review_create($pdo,$owner,'claim',$claimPublic,[$member['id']],null,'Check the evidence lineage.');research_review_respond($pdo,$member,(string)$review['public_id'],'approve','Lineage is clear for this Claim.');
$outcomePublic=$pub('outcome');$dedupe=hash('sha256','p26-outcome-'.$run);$pdo->prepare("INSERT INTO research_outcome_events(public_id,user_id,project_id,event_type,decision_type,source_type,source_public_id,object_type,object_public_id,title,summary,dedupe_key,is_manual,occurred_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,NOW())")->execute([$outcomePublic,$owner['id'],$projectId,'manual_decision','accepted','claim',$claimPublic,'claim',$claimPublic,'Accepted Claim','Owner Decision Memory provenance event.',$dedupe,1]);

$published=research_report_publish($pdo,$project,$owner,'team','Provenance Team Report','Immutable report for provenance.','Provenance, Audit');$report=research_report_access($pdo,(string)$published['public_id'],$owner);p26($report!==null&&(int)$report['version_number']===1,'project publishes immutable report version for provenance');
$manifest=provenance_project_manifest($pdo,$owner,$projectPublic);p26(count($manifest['source_versions'])===1&&count($manifest['annotations'])===1&&count($manifest['claims'])===1&&count($manifest['findings'])===1,'manifest includes Source Version → Annotation → Claim → Finding lineage');
p26(count($manifest['report_versions'])===1&&count($manifest['report_versions'][0]['citations'])===1,'manifest includes report version and outgoing version-pinned citation');
p26(count($manifest['reviews'])===1&&count($manifest['reviews'][0]['responses'])===1,'manifest includes collaborative review and response provenance');
p26(count($manifest['decision_memory'])===1&&$manifest['decision_memory'][0]['public_id']===$outcomePublic,'manifest includes only current viewer Decision Memory provenance');
p26($manifest['source_versions'][0]['recorded_content_hash']===$contentHash&&!array_key_exists('computed_content_hash',$manifest['source_versions'][0]),'Source hash is represented as recorded rather than overclaimed as independently verified');

$edges=provenance_manifest_edges($manifest);$edgeTypes=array_values(array_unique(array_column($edges,'type')));foreach(['captured_as','evidence','annotation_evidence','synthesized_into','cites','reviewed_as','decision_memory'] as $type)p26(in_array($type,$edgeTypes,true),'lineage graph includes '.$type.' edge');
$integrity=provenance_project_integrity($manifest);p26($integrity['report_snapshots']['total']===1&&$integrity['report_snapshots']['valid']===1&&$integrity['report_snapshots']['invalid']===0,'report snapshot hash deterministically verifies');
$directIntegrity=provenance_project_report_integrity($pdo,$owner,$projectPublic);p26($directIntegrity['valid']===1&&$directIntegrity['invalid']===0,'lightweight report integrity path matches full manifest result');

$receipt=provenance_receipt_create($pdo,$owner,$projectPublic);p26(!empty($receipt['public_id'])&&$receipt['stored_hash_valid']&&$receipt['current_matches_receipt'],'owner can create valid immutable audit receipt matching current provenance');
p26(hash_equals((string)$receipt['manifest_hash'],provenance_hash($receipt['manifest'])),'receipt hash equals deterministic canonical manifest hash');
p26(provenance_receipt_access($pdo,$member,(string)$receipt['public_id'])===null,'audit receipt is creator-scoped even for a current project collaborator');

$memberManifest=provenance_project_manifest($pdo,$member,$projectPublic);p26(count($memberManifest['decision_memory'])===0,'another collaborator does not inherit owner Decision Memory into provenance');
$memberReceipt=provenance_receipt_create($pdo,$member,$projectPublic);p26($memberReceipt['stored_hash_valid'],'collaborator can create own permission-scoped receipt while access exists');

$privateProject=$pub('private-project');$pdo->prepare("INSERT INTO research_projects(public_id,owner_user_id,team_id,title,description,status) VALUES(?,?,?,?,?,'active')")->execute([$privateProject,$owner['id'],$teamId,'Private Publication Project','Project is shared but its report is owner/admin private.']);$privateAccess=project_access($pdo,$owner['id'],$privateProject);$privatePublished=research_report_publish($pdo,$privateAccess,$owner,'private','Private Audit Report','Private report must not leak through project provenance.','Audit');
$ownerPrivateManifest=provenance_project_manifest($pdo,$owner,$privateProject);p26(count($ownerPrivateManifest['report_versions'])===1,'project owner provenance includes owner-accessible private report version');
$memberPrivateManifest=provenance_project_manifest($pdo,$member,$privateProject);p26(count($memberPrivateManifest['report_versions'])===0,'project researcher provenance does not reveal private report version');
$memberPrivateIntegrity=provenance_project_report_integrity($pdo,$member,$privateProject);p26($memberPrivateIntegrity['total']===0&&$memberPrivateIntegrity['invalid']===0,'lightweight integrity feed does not leak private report existence or integrity state');

$pdo->prepare("UPDATE research_claims SET statement='The provenance evidence supports this revised Claim.' WHERE public_id=?")->execute([$claimPublic]);$receiptAfter=provenance_receipt_access($pdo,$owner,(string)$receipt['public_id']);p26($receiptAfter['stored_hash_valid']&&!$receiptAfter['current_matches_receipt'],'later Research change causes current-state drift without rewriting receipt');
p26(hash_equals((string)$receiptAfter['manifest_hash'],(string)$receipt['manifest_hash']),'receipt manifest hash remains immutable after project drift');

$rv=research_report_version($pdo,$report,1);$originalJson=(string)$rv['snapshot_json'];$tampered=json_encode(['tampered'=>true,'original_hash'=>$rv['snapshot_hash']],JSON_UNESCAPED_SLASHES);$pdo->prepare('UPDATE research_report_versions SET snapshot_json=? WHERE id=?')->execute([$tampered,$rv['id']]);
$bad=provenance_project_report_integrity($pdo,$owner,$projectPublic);p26($bad['invalid']===1&&$bad['valid']===0,'provenance detects stored report snapshot/hash mismatch');
$items=[];provenance_cognitive_observations($pdo,$owner,$items,20);$alerts=array_values(array_filter($items,fn($i)=>($i['type']??'')==='provenance_integrity'));p26(count($alerts)>=1&&($alerts[0]['priority']??'')==='high','report integrity mismatch surfaces as high-priority Cognitive Feed observation');
$pdo->prepare('UPDATE research_report_versions SET snapshot_json=? WHERE id=?')->execute([$originalJson,$rv['id']]);$restored=provenance_project_report_integrity($pdo,$owner,$projectPublic);p26($restored['valid']===1&&$restored['invalid']===0,'restoring immutable snapshot content restores deterministic hash verification');

$publicTarget=research_report_access($pdo,(string)$targetPublished['public_id'],$outsider);p26($publicTarget!==null,'public report remains publicly accessible independently of private project provenance');
$pdo->prepare('DELETE FROM team_members WHERE team_id=? AND user_id=?')->execute([$teamId,$member['id']]);$blocked=false;try{provenance_project_manifest($pdo,$member,$projectPublic);}catch(RuntimeException $e){$blocked=true;}p26($blocked,'Team revocation immediately blocks live project provenance');p26(provenance_receipt_access($pdo,$member,(string)$memberReceipt['public_id'])===null,'Team revocation also blocks previously created private project receipt');

$runtime=file_get_contents($root.'/app/research-provenance.php');p26(!str_contains($runtime,'trust_score')&&!str_contains($runtime,'ai_run(')&&!str_contains($runtime,'UPDATE research_audit_receipts')&&!str_contains($runtime,'agent_action_confirm_execute('),'provenance runtime has no trust score, AI ranker, mutable receipt path, or direct Agent execution');
echo "Phase 26 Research Provenance & Audit Ledger MariaDB suite passed.\n";
