<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=(string)getenv('DB_DSN');$dbUser=(string)getenv('DB_USER');$dbPass=(string)getenv('DB_PASS');if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
require_once $root.'/app/installer.php';require_once $root.'/app/functions.php';require_once $root.'/app/data-attribution.php';require_once $root.'/app/data-datasets.php';require_once $root.'/app/ai.php';require_once $root.'/app/data-evaluations.php';require_once $root.'/app/data-model-registry.php';
function p40(bool $v,string $m): void {if(!$v)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}
p40(data_model_registry_ready($pdo),'Phase 40 Model Registry schema is available');

$run='p40'.substr(bin2hex(random_bytes(7)),0,12);$pub=fn(string $p)=>$p.'-'.$run.'-'.substr(bin2hex(random_bytes(4)),0,8);
$makeUser=function(string $name,string $role='user')use($pdo,$run,$pub): array{$username=substr(strtolower($name).'_'.$run,0,48);$public=$pub('u');$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,password_hash,status,role) VALUES(?,?,?,?,?,'active',?)")->execute([$public,$username,$name,$username.'@example.test',password_hash('model-registry-test',PASSWORD_DEFAULT),$role]);return ['id'=>(int)$pdo->lastInsertId(),'public_id'=>$public,'username'=>$username,'display_name'=>$name,'role'=>$role];};
$admin=$makeUser('ModelAdmin','admin');$contributor=$makeUser('Contributor');$outsider=$makeUser('Outsider');

$sourcePublic=$pub('source');$url='https://'.$run.'.example.test/model-eval';$pdo->prepare("INSERT INTO sources(public_id,source_type,canonical_url,canonical_url_hash,domain,title,status) VALUES(?,'article',?,?,?,?, 'current')")->execute([$sourcePublic,$url,hash('sha256',$url),$run.'.example.test','Model evidence']);$sourceId=(int)$pdo->lastInsertId();
$sourceText='External source text '.$run;$pdo->prepare('INSERT INTO source_versions(source_id,version_number,final_url,title,extracted_text,content_hash,target_content_hash) VALUES(?,1,?,?,?,?,?)')->execute([$sourceId,$url,'Model evidence',$sourceText,hash('sha256',$sourceText),hash('sha256','target '.$run)]);$versionId=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE sources SET current_version_id=? WHERE id=?')->execute([$versionId,$sourceId]);
$pdo->prepare("INSERT INTO captures(public_id,source_id,source_version_id,user_id,capture_type,selected_text) VALUES(?,?,?,?, 'text',?)")->execute([$pub('cap'),$sourceId,$versionId,$contributor['id'],'captured source '.$run]);$captureId=(int)$pdo->lastInsertId();
$annotationPublic=$pub('ann');$comment='Phoenix renewable expansion remains active and funded '.$run;$pdo->prepare("INSERT INTO annotations(public_id,user_id,source_id,source_version_id,capture_id,text_commentary,visibility,status) VALUES(?,?,?,?,?,?,'public','published')")->execute([$annotationPublic,$contributor['id'],$sourceId,$versionId,$captureId,$comment]);data_attribution_capture_object($pdo,(int)$contributor['id'],'annotation',$annotationPublic);
data_contributor_preferences_update($pdo,$contributor,['allow_shared_retrieval'=>1,'allow_evaluation'=>1,'allow_training'=>0,'allow_commercial_training'=>0,'attribution_required'=>1]);data_corpus_refresh_object($pdo,'annotation',$annotationPublic);
$dataset=data_dataset_create($pdo,$admin,['name'=>'Model Governance Evaluation '.$run,'purpose'=>'evaluation','corpus_types'=>'annotation_commentary','max_items'=>10000]);$dataset=data_dataset_freeze($pdo,$admin,$dataset['public_id']);$items=data_dataset_items($pdo,$dataset['public_id'],500,0);$ownItems=array_values(array_filter($items,fn($item)=>$item['source_object_type']==='annotation'&&$item['source_object_public_id']===$annotationPublic));p40(count($ownItems)===1,'model governance fixture locates its own frozen evaluation item inside the shared governed corpus');$expectedItemId=(int)$ownItems[0]['id'];

$providerPublic=$pub('provider');$pdo->prepare("INSERT INTO ai_providers(public_id,label,provider_type,api_base_url,api_key_ciphertext,enabled) VALUES(?,?,'openai_compatible','http://127.0.0.1:9',NULL,1)")->execute([$providerPublic,'Phase40 Provider']);$providerId=(int)$pdo->lastInsertId();
$makeModel=function(string $name)use($pdo,$providerId,$pub): array{$public=$pub('model');$pdo->prepare("INSERT INTO ai_models(public_id,provider_id,model_name,display_name,enabled,admin_enabled,pro_enabled,max_output_tokens) VALUES(?,?,?,?,1,1,0,2048)")->execute([$public,$providerId,strtolower(str_replace(' ','-',$name)),$name]);return ['id'=>(int)$pdo->lastInsertId(),'public_id'=>$public];};
$modelA=$makeModel('Candidate A');$modelB=$makeModel('Candidate B');
$pdo->prepare('UPDATE ai_settings SET admin_default_model_id=? WHERE id=1')->execute([$modelA['id']]);$routeBefore=(int)$pdo->query('SELECT admin_default_model_id FROM ai_settings WHERE id=1')->fetchColumn();

$completeRun=function(array $queued)use($pdo): array {
    $suite=data_evaluation_suite_get($pdo,(string)$queued['suite_public_id']);if(!$suite)throw new RuntimeException('Fixture suite missing.');$cases=data_evaluation_cases($pdo,(int)$suite['id']);$rows=data_evaluation_dataset_rows($pdo,(int)$queued['dataset_id']);
    foreach($cases as $case){$ranked=data_evaluation_rank_rows($rows,(string)$case['query_text'],(int)$suite['top_k']);$expectedRank=null;foreach($ranked['all'] as $hit)if((int)$hit['dataset_item_id']===(int)$case['expected_dataset_item_id']){$expectedRank=(int)$hit['rank'];break;}$response='The project remains active [['.$case['expected_corpus_public_id'].']].';$metrics=['expected_rank'=>$expectedRank??0,'expected_score'=>(float)($ranked['top'][0]['score']??0),'hit_at_1'=>$expectedRank===1?1:0,'hit_at_3'=>$expectedRank!==null&&$expectedRank<=3?1:0,'hit_at_5'=>$expectedRank!==null&&$expectedRank<=5?1:0,'mrr'=>$expectedRank?1/$expectedRank:0.0,'top_score'=>(float)($ranked['top'][0]['score']??0),'expected_citation'=>1,'grounded_token_ratio'=>0.90,'reference_token_f1'=>0.80,'input_tokens'=>120,'output_tokens'=>24,'latency_ms'=>12.5];data_evaluation_result_insert($pdo,(int)$queued['id'],$case,$ranked,$response,$metrics,true,[(string)$case['expected_corpus_public_id']]);}
    $summary=data_evaluation_summary($pdo,(int)$queued['id'],'model');$summaryJson=data_attribution_encode($summary);$summaryHash=hash('sha256',$summaryJson);$q=$pdo->prepare('SELECT result_hash FROM data_evaluation_results WHERE run_id=? ORDER BY case_id');$q->execute([$queued['id']]);$resultHashes=$q->fetchAll(PDO::FETCH_COLUMN);$runHash=data_attribution_hash(['run_public_id'=>$queued['public_id'],'dataset_manifest_hash'=>$queued['dataset_manifest_hash'],'suite_config_hash'=>$queued['suite_config_hash'],'cases_hash'=>$queued['cases_hash'],'model_snapshot'=>json_decode((string)($queued['model_snapshot_json']??''),true),'result_hashes'=>$resultHashes,'summary_hash'=>$summaryHash]);$pdo->prepare("UPDATE data_evaluation_runs SET status='completed',result_summary_json=?,result_summary_hash=?,run_hash=?,started_at=COALESCE(started_at,NOW()),completed_at=NOW() WHERE id=?")->execute([$summaryJson,$summaryHash,$runHash,$queued['id']]);return data_evaluation_run_get($pdo,(string)$queued['public_id']);
};
$makeBenchmark=function(array $model,string $name)use($pdo,$admin,$dataset,$expectedItemId,$completeRun): array {
    $suite=data_evaluation_suite_create($pdo,$admin,['dataset_id'=>$dataset['id'],'name'=>$name,'benchmark_type'=>'model','top_k'=>3,'model_id'=>$model['id'],'prompt_template'=>'Use only supplied benchmark context and cite [[ITEM]].']);
    data_evaluation_case_add($pdo,$admin,$suite['public_id'],['label'=>'Shared governance benchmark','query_text'=>'Phoenix renewable expansion active funded','expected_dataset_item_id'=>$expectedItemId,'reference_answer'=>'The Phoenix renewable expansion remains active and funded.','weight'=>1,'tags'=>'phoenix,renewable']);
    $suite=data_evaluation_suite_activate($pdo,$admin,$suite['public_id']);
    $baseline=$completeRun(data_evaluation_run_queue($pdo,$admin,$suite['public_id']));data_evaluation_set_baseline($pdo,$admin,$suite['public_id'],$baseline['public_id']);
    $current=$completeRun(data_evaluation_run_queue($pdo,$admin,$suite['public_id']));$results=data_evaluation_results($pdo,(int)$current['id']);data_evaluation_review_save($pdo,$admin,(int)$results[0]['id'],['decision'=>'pass','relevance_score'=>5,'groundedness_score'=>5,'accuracy_score'=>5,'note'=>'Phase 40 human review']);
    return ['suite'=>data_evaluation_suite_get($pdo,$suite['public_id']),'baseline'=>$baseline,'current'=>data_evaluation_run_get($pdo,$current['public_id'])];
};
$benchA=$makeBenchmark($modelA,'Governance Benchmark A '.$run);$benchB=$makeBenchmark($modelB,'Governance Benchmark B '.$run);
p40(data_evaluation_run_integrity($pdo,$benchA['current'])['ok']&&data_evaluation_run_integrity($pdo,$benchB['current'])['ok'],'both model candidates have integrity-valid Phase 39 runs');

$registry=data_model_registry_create($pdo,$admin,['name'=>'Annotated Governed Model '.$run,'description'=>'Phase 40 registry fixture']);p40(!empty($registry['public_id']),'logical model registry is created');
$policyA=['version_label'=>'v1','origin'=>'external_hosted','ai_model_id'=>$modelA['id'],'architecture'=>'hosted transformer','intended_use'=>'Research answer generation','license_code'=>'provider-terms','context_window'=>128000,'required_model_runs'=>1,'required_human_reviews'=>1,'minimum_human_pass_rate'=>1,'require_integrity'=>1,'require_no_regression'=>1,'max_regressed_metrics'=>0,'required_suite_public_ids'=>$benchA['suite']['public_id']];
$v1=data_model_version_create($pdo,$admin,$registry['public_id'],$policyA);p40($v1['status']==='experimental'&&data_model_version_integrity($v1)['ok'],'registered model version starts experimental with valid identity hash');
$hashBefore=$v1['version_hash'];$v1=data_model_version_update_experimental($pdo,$admin,$v1['public_id'],array_merge($policyA,['architecture'=>'hosted transformer v2']));p40($v1['version_hash']!==$hashBefore&&data_model_version_integrity($v1)['ok'],'experimental edits refresh the model version identity hash');
$v1=data_model_transition($pdo,$admin,$v1['public_id'],'candidate','Ready for evidence');p40($v1['status']==='candidate','experimental version moves explicitly to candidate');
$immutable=false;try{data_model_version_update_experimental($pdo,$admin,$v1['public_id'],['architecture'=>'mutated']);}catch(RuntimeException $e){$immutable=str_contains($e->getMessage(),'immutable');}p40($immutable,'candidate metadata and gate policy are immutable');

$premature=false;try{data_model_transition($pdo,$admin,$v1['public_id'],'approved','Too early');}catch(RuntimeException $e){$premature=str_contains($e->getMessage(),'gates');}p40($premature,'candidate cannot be approved before release gates are satisfied');
$mismatch=false;try{data_model_link_evaluation($pdo,$admin,$v1['public_id'],$benchB['current']['public_id']);}catch(RuntimeException $e){$mismatch=str_contains($e->getMessage(),'does not match');}p40($mismatch,'evaluation evidence must match the registered runtime model');
data_model_link_evaluation($pdo,$admin,$v1['public_id'],$benchA['current']['public_id'],'Candidate A evidence');$v1=data_model_version_get($pdo,$v1['public_id']);$gate1=data_model_gate_evaluate($pdo,$v1);p40($gate1['pass']&&$gate1['evidence']['regression_comparisons']===1&&$gate1['evidence']['human_reviews']===1,'linked integrity-valid evidence satisfies model release gates including regression and human review');
$v1=data_model_transition($pdo,$admin,$v1['public_id'],'approved','Human approval after review');p40($v1['status']==='approved','candidate moves to approved only through explicit gated transition');
$linkFrozen=false;try{data_model_unlink_evaluation($pdo,$admin,$v1['public_id'],$benchA['current']['public_id']);}catch(RuntimeException $e){$linkFrozen=str_contains($e->getMessage(),'immutable');}p40($linkFrozen,'approved model evidence links become immutable');
$approvalReceipts=data_model_receipts($pdo,(int)$v1['id']);p40(count($approvalReceipts)>=2&&!empty($approvalReceipts[0]['integrity']['ok']),'model lifecycle transitions create integrity-valid promotion receipts');
$v1=data_model_transition($pdo,$admin,$v1['public_id'],'active','Activate governed version');$registry=data_model_registry_get($pdo,$registry['public_id']);p40($v1['status']==='active'&&(int)$registry['active_version_id']===(int)$v1['id'],'approved model can become the governed active version');
p40((int)$pdo->query('SELECT admin_default_model_id FROM ai_settings WHERE id=1')->fetchColumn()===$routeBefore,'governed activation does not silently rewrite AI task routing');

$policyB=$policyA;$policyB['version_label']='v2';$policyB['ai_model_id']=$modelB['id'];$policyB['required_suite_public_ids']=$benchB['suite']['public_id'];$policyB['architecture']='second hosted transformer';
$v2=data_model_version_create($pdo,$admin,$registry['public_id'],$policyB);$v2=data_model_transition($pdo,$admin,$v2['public_id'],'candidate','Second candidate');data_model_link_evaluation($pdo,$admin,$v2['public_id'],$benchB['current']['public_id'],'Candidate B evidence');p40(data_model_gate_evaluate($pdo,data_model_version_get($pdo,$v2['public_id']))['pass'],'second candidate independently satisfies equivalent release gates');
$v2=data_model_transition($pdo,$admin,$v2['public_id'],'approved','Approve second candidate');$comparison=data_model_comparison($pdo,[$v1['public_id'],$v2['public_id']]);p40(count($comparison['common_benchmarks'])===1,'different runtime models compare only through an equivalent frozen benchmark definition');
$cmp=$comparison['common_benchmarks'][0];p40(count($cmp['versions'])===2&&!empty($cmp['benchmark_fingerprint'])&&$cmp['dataset_manifest_hash']===$dataset['manifest_hash'],'comparison preserves common dataset and benchmark fingerprint without selecting a winner');
$v2=data_model_transition($pdo,$admin,$v2['public_id'],'active','Activate second governed version');$v1=data_model_version_get($pdo,$v1['public_id']);$registry=data_model_registry_get($pdo,$registry['public_id']);p40($v1['status']==='deprecated'&&$v2['status']==='active'&&(int)$registry['active_version_id']===(int)$v2['id'],'activating a new version deprecates the previous governed active version');
p40((int)$pdo->query('SELECT admin_default_model_id FROM ai_settings WHERE id=1')->fetchColumn()===$routeBefore,'superseding governed active version still does not alter task routing');

$never=data_model_version_create($pdo,$admin,$registry['public_id'],array_merge($policyA,['version_label'=>'never-active']));$never=data_model_transition($pdo,$admin,$never['public_id'],'candidate','Candidate only');data_model_link_evaluation($pdo,$admin,$never['public_id'],$benchA['current']['public_id']);$never=data_model_transition($pdo,$admin,$never['public_id'],'approved','Approved but never active');
$badRollback=false;try{data_model_rollback($pdo,$admin,$registry['public_id'],$never['public_id'],'Should fail');}catch(RuntimeException $e){$badRollback=str_contains($e->getMessage(),'previously been active');}p40($badRollback,'rollback cannot target an approved version that was never active');
$v1=data_model_rollback($pdo,$admin,$registry['public_id'],$v1['public_id'],'Restore prior known version');$v2=data_model_version_get($pdo,$v2['public_id']);$registry=data_model_registry_get($pdo,$registry['public_id']);p40($v1['status']==='active'&&$v2['status']==='deprecated'&&(int)$registry['active_version_id']===(int)$v1['id'],'explicit rollback reactivates a previously active integrity-valid version and deprecates the current one');
p40((int)$pdo->query('SELECT admin_default_model_id FROM ai_settings WHERE id=1')->fetchColumn()===$routeBefore,'rollback also leaves AI routing independently controlled');

$neverReceipts=data_model_receipts($pdo,(int)$never['id']);$approval=array_values(array_filter($neverReceipts,fn($r)=>$r['to_status']==='approved'))[0]??null;p40($approval&&$approval['integrity']['ok'],'approval receipt integrity validates before tampering');
$pdo->prepare('UPDATE data_model_promotion_receipts SET note=? WHERE id=?')->execute(['tampered decision note '.$run,$approval['id']]);$neverReceipts=data_model_receipts($pdo,(int)$never['id']);$approvalAfter=array_values(array_filter($neverReceipts,fn($r)=>$r['to_status']==='approved'))[0]??null;p40($approvalAfter&&!$approvalAfter['integrity']['ok'],'direct promotion-receipt note tampering is detected');
$activationBlocked=false;try{data_model_transition($pdo,$admin,$never['public_id'],'active','Must fail');}catch(RuntimeException $e){$activationBlocked=str_contains($e->getMessage(),'approval receipt failed integrity');}p40($activationBlocked,'corrupted approval receipt blocks activation');

$tampered=data_model_version_create($pdo,$admin,$registry['public_id'],array_merge($policyA,['version_label'=>'tampered-version']));$tampered=data_model_transition($pdo,$admin,$tampered['public_id'],'candidate','Candidate before direct tamper');data_model_link_evaluation($pdo,$admin,$tampered['public_id'],$benchA['current']['public_id']);$pdo->prepare('UPDATE data_model_versions SET architecture=? WHERE id=?')->execute(['direct database mutation',$tampered['id']]);$tampered=data_model_version_get($pdo,$tampered['public_id']);$tamperGate=data_model_gate_evaluate($pdo,$tampered);p40(!$tamperGate['pass']&&!$tamperGate['checks']['version_integrity']['pass'],'direct candidate metadata tampering invalidates the model version identity hash');
$tamperApproval=false;try{data_model_transition($pdo,$admin,$tampered['public_id'],'approved','Must fail');}catch(RuntimeException $e){$tamperApproval=str_contains($e->getMessage(),'gates');}p40($tamperApproval,'tampered model version cannot pass approval gates');

$v2=data_model_transition($pdo,$admin,$v2['public_id'],'retired','Retire superseded version');p40($v2['status']==='retired','deprecated model version can be explicitly retired');
$jobsBefore=(int)$pdo->query('SELECT COUNT(*) FROM ai_jobs')->fetchColumn();$summary=data_model_summary($pdo);$jobsAfter=(int)$pdo->query('SELECT COUNT(*) FROM ai_jobs')->fetchColumn();p40($jobsBefore===$jobsAfter,'Model Registry governance creates no training or generic AI jobs');
p40($summary['registries']>=1&&$summary['versions']>=4&&$summary['active']>=1&&$summary['receipts']>=1,'Model Registry summary reflects governed lifecycle state');

$nonAdmin=false;try{data_model_registry_create($pdo,$outsider,['name'=>'Unauthorized Registry']);}catch(RuntimeException $e){$nonAdmin=str_contains($e->getMessage(),'Administrator');}p40($nonAdmin,'Model Registry lifecycle operations are administrator-only');

$events=data_model_events($pdo,(int)$registry['id']);$types=array_column($events,'event_type');foreach(['registry_created','version_created','evaluation_linked','status_transition','superseded_by_activation','rollback_activated'] as $needed)p40(in_array($needed,$types,true),'audit history includes '.$needed);

echo "Phase 40 Model Registry & Candidate Lifecycle MariaDB suite passed.\n";
