<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=getenv('DB_DSN')?:'';$dbUser=getenv('DB_USER')?:'root';$dbPass=getenv('DB_PASS')?:'';if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
foreach(['installer','storage','jobs','concurrency','functions','shell','access','notifications','rate-limit','ai','ai-access','source-integrity','annotation-intelligence','research-workspace','research-knowledge','research-intelligence','research-reports','conversations','agent-actions','agent-chat','cognitive-feed','research-entities','proactive-intelligence','research-automation','cross-research','research-outcomes','research-reviews','change-impact','research-portfolio','living-research','research-network','research-provenance','research-verification','research-evidence-packs','research-workflow'] as $lib)require_once $root.'/app/'.$lib.'.php';
function p30(bool $ok,string $m): void {if(!$ok)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}
$run='p30'.substr(bin2hex(random_bytes(6)),0,10);$pub=fn(string $p)=>$p.'-'.$run.'-'.substr(bin2hex(random_bytes(3)),0,6);
$makeUser=function(string $name)use($pdo,$run,$pub): array{$username=substr(strtolower($name).'_'.$run,0,48);$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,email_verified_at,status,role,plan_tier,live_presence_mode) VALUES(?,?,?,?,NOW(),'active','user','pro','cloaked')")->execute([$pub('u'),$username,$name,$username.'@example.test']);$id=(int)$pdo->lastInsertId();$pdo->prepare('INSERT IGNORE INTO user_preferences(user_id) VALUES(?)')->execute([$id]);$q=$pdo->prepare('SELECT * FROM users WHERE id=?');$q->execute([$id]);return $q->fetch();};
$owner=$makeUser('CompletionOwner');$member=$makeUser('CompletionMember');$outsider=$makeUser('CompletionOutsider');
$teamPublic=$pub('team');$pdo->prepare('INSERT INTO teams(public_id,owner_user_id,name) VALUES(?,?,?)')->execute([$teamPublic,$owner['id'],'Completion Team']);$teamId=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO team_members(team_id,user_id,role) VALUES(?,?,'owner'),(?,?,'researcher')")->execute([$teamId,$owner['id'],$teamId,$member['id']]);
$projectPublic=$pub('project');$pdo->prepare("INSERT INTO research_projects(public_id,owner_user_id,team_id,title,description,status) VALUES(?,?,?,?,?,'active')")->execute([$projectPublic,$owner['id'],$teamId,'Completion Research','Final hardening fixture']);$projectId=(int)$pdo->lastInsertId();$project=project_access($pdo,$owner['id'],$projectPublic);

$makeSource=function(string $domain,string $label)use($pdo,$owner,$projectId,$run,$pub): array{$url='https://'.$domain.'/'.$run.'/'.$label;$sp=$pub('source');$pdo->prepare("INSERT INTO sources(public_id,source_type,canonical_url,canonical_url_hash,domain,title,status,monitoring_enabled,moderation_status) VALUES(?,'article',?,?,?,?,'current',1,'visible')")->execute([$sp,$url,hash('sha256',$url),$domain,$label]);$sid=(int)$pdo->lastInsertId();$text='Completion evidence '.$label;$pdo->prepare("INSERT INTO source_versions(source_id,version_number,final_url,title,extracted_text,content_hash,target_content_hash,captured_at) VALUES(?,1,?,?,?,?,?,NOW())")->execute([$sid,$url,$label,$text,hash('sha256',$text),hash('sha256','target-'.$label.$run)]);$sv=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE sources SET current_version_id=? WHERE id=?')->execute([$sv,$sid]);$pdo->prepare('INSERT INTO project_sources(project_id,source_id,added_by_user_id) VALUES(?,?,?)')->execute([$projectId,$sid,$owner['id']]);return ['public_id'=>$sp,'id'=>$sid,'version_id'=>$sv];};
$a=$makeSource('completion-a.example','A');$b=$makeSource('completion-b.example','B');
$claimPublic=$pub('claim');$pdo->prepare("INSERT INTO research_claims(public_id,project_id,created_by_user_id,statement,claim_type,status) VALUES(?,?,?,'Completion Claim','factual','supported')")->execute([$claimPublic,$projectId,$owner['id']]);$claimId=(int)$pdo->lastInsertId();
foreach([$a,$b] as $i=>$src)$pdo->prepare("INSERT INTO claim_evidence(public_id,claim_id,added_by_user_id,evidence_type,source_version_id,relationship,note) VALUES(?,?,?,'source_version',?,?,?)")->execute([$pub('ev'),$claimId,$owner['id'],$src['version_id'],$i===0?'primary':'supports','Completion evidence']);
research_verification_record($pdo,$owner,'claim',$claimPublic,'reviewed_current','Verified before synthesis.');
$findingPublic=$pub('finding');$pdo->prepare("INSERT INTO research_findings(public_id,project_id,created_by_user_id,title,summary,status) VALUES(?,?,?,'Completion Finding','Current reviewed synthesis.','final')")->execute([$findingPublic,$projectId,$owner['id']]);$findingId=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO finding_claims(finding_id,claim_id,added_by_user_id,relationship,position) VALUES(?,?,?,'primary',0)")->execute([$findingId,$claimId,$owner['id']]);

$pdo->prepare("INSERT INTO research_reviews(public_id,project_id,requested_by_user_id,subject_type,subject_public_id,subject_hash,title,status,completed_at,completion_json) VALUES(?,?,?,'agent_action',?,?,'Irrelevant Agent action review','completed',NOW(),'{}')")->execute([$pub('review-agent'),$projectId,$owner['id'],$pub('agent-action'),hash('sha256','agent-review-'.$run)]);
$w=research_workflow_state($pdo,$owner,$projectPublic);p30($w['next']['stage']==='review'&&$w['counts']['current_completed_reviews']===0,'completed Agent-action review cannot satisfy human Research review stage');

$review=research_review_create($pdo,$owner,'finding',$findingPublic,[$member['id']],null,'Final Finding review.');research_review_respond($pdo,$member,(string)$review['public_id'],'approve','Evidence and synthesis reviewed.');research_review_complete($pdo,$owner,(string)$review['public_id']);
$w=research_workflow_state($pdo,$owner,$projectPublic);p30($w['next']['stage']==='publish'&&$w['counts']['current_completed_reviews']===1,'current completed Finding review unlocks Publish');

$pdo->prepare("UPDATE research_findings SET summary='Finding changed after completed review.' WHERE id=?")->execute([$findingId]);$w=research_workflow_state($pdo,$owner,$projectPublic);p30($w['next']['stage']==='review'&&$w['counts']['current_completed_reviews']===0,'changed Finding invalidates old completed review for workflow progression');
$review2=research_review_create($pdo,$owner,'finding',$findingPublic,[$member['id']],null,'Updated Finding review.');research_review_respond($pdo,$member,(string)$review2['public_id'],'approve','Updated Finding reviewed.');research_review_complete($pdo,$owner,(string)$review2['public_id']);
$w=research_workflow_state($pdo,$owner,$projectPublic);p30($w['next']['stage']==='publish','new current review restores Publish readiness');

$published=research_report_publish($pdo,$project,$owner,'public','Completion Public Report','Public immutable report.','Completion');$report=research_report_access($pdo,(string)$published['public_id'],$owner);$rv=research_report_version($pdo,$report,1);p30($rv!==null&&hash_equals((string)$rv['snapshot_hash'],hash('sha256',(string)$rv['snapshot_json'])),'published Report snapshot hash verifies');
p30(research_report_access($pdo,(string)$published['public_id'],$outsider)!==null,'public Report remains accessible without private project access');
p30(project_access($pdo,(int)$outsider['id'],$projectPublic)===null&&research_verification_subject($pdo,$outsider,'claim',$claimPublic)===null,'public Report does not grant outsider access to private Research/verification state');

$pack=research_evidence_pack_create($pdo,$owner,$projectPublic,'project',$projectPublic);$receipt=provenance_receipt_create($pdo,$owner,$projectPublic);p30($pack['stored_hash_valid']&&$pack['current_matches_pack']&&$receipt['stored_hash_valid'],'final Research can create verified Evidence Pack and audit receipt');
$packHash=(string)$pack['manifest_hash'];$receiptHash=(string)$receipt['manifest_hash'];
$pdo->prepare("UPDATE research_projects SET description='Description changed after frozen records.' WHERE id=?")->execute([$projectId]);
$packAfter=research_evidence_pack_access($pdo,$owner,(string)$pack['public_id']);$receiptAfter=provenance_receipt_access($pdo,$owner,(string)$receipt['public_id']);p30($packAfter['stored_hash_valid']&&!$packAfter['current_matches_pack']&&hash_equals($packHash,(string)$packAfter['manifest_hash']),'Evidence Pack remains immutable and reports current-state drift');
p30($receiptAfter['stored_hash_valid']&&!$receiptAfter['current_matches_receipt']&&hash_equals($receiptHash,(string)$receiptAfter['manifest_hash']),'audit receipt remains immutable and reports current-state drift');
$w=research_workflow_state($pdo,$owner,$projectPublic);p30($w['next']['stage']==='monitor'&&$w['drifted_packs']>=1,'published workflow routes reproducibility drift into Monitor');

$secretProject=$pub('secret-project');$pdo->prepare("INSERT INTO research_projects(public_id,owner_user_id,title,description,status) VALUES(?,?,?,'Private unrelated project','active')")->execute([$secretProject,$owner['id'],'Secret Research']);$secretProjectId=(int)$pdo->lastInsertId();$secretToken='SECRET-CROSS-PROJECT-'.$run;$pdo->prepare("INSERT INTO research_claims(public_id,project_id,created_by_user_id,statement,claim_type,status) VALUES(?,?,?,?,'factual','unverified')")->execute([$pub('secret-claim'),$secretProjectId,$owner['id'],$secretToken]);
$agent=agent_chat_context_item($pdo,$owner,'research',$projectPublic);p30($agent!==null&&mb_strlen((string)$agent['text'])<=30000,'Research Agent context remains bounded to the 30k context contract');p30(!str_contains((string)$agent['text'],$secretToken),'Research Agent context does not leak unrelated project content');
p30(str_contains((string)$agent['text'],'[UNIFIED RESEARCH WORKFLOW]')&&str_contains((string)$agent['text'],'[RESEARCH EVIDENCE VERIFICATION]')&&str_contains((string)$agent['text'],'[RESEARCH PROVENANCE]'),'Agent receives workflow, verification and provenance boundaries together');

p30(research_evidence_pack_access($pdo,$member,(string)$pack['public_id'])!==null,'current Team member can replay frozen project Evidence Pack');
$memberManifest=provenance_project_manifest($pdo,$member,$projectPublic);$ownerManifest=provenance_project_manifest($pdo,$owner,$projectPublic);p30(isset($memberManifest['evidence_packs'])&&isset($ownerManifest['evidence_packs']),'provenance exposes pack lineage only inside authorized project scope');
$pdo->prepare('DELETE FROM team_members WHERE team_id=? AND user_id=?')->execute([$teamId,$member['id']]);p30(research_evidence_pack_access($pdo,$member,(string)$pack['public_id'])===null&&project_access($pdo,(int)$member['id'],$projectPublic)===null,'Team revocation removes Research and historical pack access');

$packRuntime=file_get_contents($root.'/app/research-evidence-packs.php');$provRuntime=file_get_contents($root.'/app/research-provenance.php');p30(!str_contains($packRuntime,'UPDATE research_evidence_packs')&&!str_contains($packRuntime,'DELETE FROM research_evidence_packs')&&!str_contains($provRuntime,'UPDATE research_audit_receipts'),'frozen Evidence Packs and audit receipts expose no mutable runtime path');
$workflowRuntime=file_get_contents($root.'/app/research-workflow.php');p30(!str_contains($workflowRuntime,'ai_run(')&&!str_contains($workflowRuntime,'INSERT INTO')&&!str_contains($workflowRuntime,'UPDATE ')&&!str_contains($workflowRuntime,'DELETE FROM'),'final unified workflow remains deterministic and read-only');
echo "Phase 30 Research Completion & Release Hardening MariaDB suite passed.\n";
