<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=(string)getenv('DB_DSN');$dbUser=(string)getenv('DB_USER');$dbPass=(string)getenv('DB_PASS');if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
foreach(['installer','storage','jobs','concurrency','functions','shell','access','notifications','rate-limit','ai','ai-access','source-integrity','annotation-intelligence','research-workspace','research-knowledge','research-intelligence','research-reports','conversations','cognitive-feed','research-automation','research-agent-workspace','research-agents','research-retrieval','research-autonomy','research-monitoring','research-tasks','research-programs','cross-research','research-outcomes','research-reviews','change-impact','research-portfolio','living-research','research-publishing','research-intelligence-portfolios','research-intelligence-operations'] as $lib)require_once $root.'/app/'.$lib.'.php';
function p62s(bool $ok,string $m): void {if(!$ok)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}
$run='p62s'.substr(bin2hex(random_bytes(5)),0,8);$pubSeq=0;$pub=function(string $p)use($run,&$pubSeq): string {$pubSeq++;return $p.'-'.$run.'-'.str_pad((string)$pubSeq,6,'0',STR_PAD_LEFT);};
$username='soak_'.$run;$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,email_verified_at,status,role,plan_tier,live_presence_mode) VALUES(?,?,?, ?,NOW(),'active','user','pro','cloaked')")->execute([$pub('u'),$username,'Phase 62 Soak Owner',$username.'@example.test']);$uid=(int)$pdo->lastInsertId();$pdo->prepare('INSERT IGNORE INTO user_preferences(user_id) VALUES(?)')->execute([$uid]);$q=$pdo->prepare('SELECT * FROM users WHERE id=?');$q->execute([$uid]);$owner=$q->fetch();
$teamPublic=$pub('team');$pdo->prepare('INSERT INTO teams(public_id,owner_user_id,name) VALUES(?,?,?)')->execute([$teamPublic,$uid,'Phase 62 Seeded Organization']);$teamId=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO team_members(team_id,user_id,role) VALUES(?,?,'owner')")->execute([$teamId,$uid]);

$agents=[];$programs=[];$projects=[];
for($i=0;$i<6;$i++){$agent=research_agent_create($pdo,$owner,['name'=>'Soak Agent '.($i+1),'description'=>'Phase 62 seeded organization Agent.','cadence'=>'manual','timezone_name'=>'UTC','team_id'=>$teamPublic]);$project=research_agent_workspace_project($pdo,$owner,(string)$agent['public_id']);$program=research_program_create($pdo,$owner,['agent_id'=>$agent['public_id'],'title'=>'Soak Program '.($i+1),'objective'=>'Exercise bounded V1.1 organization intelligence at scale.','cadence'=>'manual','priority'=>$i<2?'high':'medium','tasks'=>[['title'=>'Seeded observation','task_type'=>'general']]]);$agents[]=$agent;$projects[]=$project;$programs[]=$program;}
p62s(count($agents)===6&&count($programs)===6,'62E seeded organization creates multiple real Research Agents and Programs.');

$sourceStmt=$pdo->prepare("INSERT INTO sources(public_id,source_type,canonical_url,canonical_url_hash,domain,title,status,monitoring_enabled,moderation_status) VALUES(?,'article',?,?,?,?,'current',1,'visible')");
$versionStmt=$pdo->prepare("INSERT INTO source_versions(source_id,version_number,final_url,title,extracted_text,content_hash,captured_at) VALUES(?,1,?,?,?,?,NOW())");
$claimStmt=$pdo->prepare("INSERT INTO research_claims(public_id,project_id,created_by_user_id,statement,claim_type,status) VALUES(?,?,?,?,'factual','supported')");
$linkSource=$pdo->prepare('INSERT IGNORE INTO project_sources(project_id,source_id,added_by_user_id) VALUES(?,?,?)');
for($i=0;$i<300;$i++){$project=$projects[$i%6];$url='https://seed'.$i.'.example.test/'.$run;$sp=$pub('s');$title='Seed Source '.$i;$sourceStmt->execute([$sp,$url,hash('sha256',$url),'seed'.($i%40).'.example.test',$title]);$sid=(int)$pdo->lastInsertId();$body='Seeded evidence record '.$i.' for '.$run;$versionStmt->execute([$sid,$url,$title,$body,hash('sha256',$body)]);$vid=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE sources SET current_version_id=? WHERE id=?')->execute([$vid,$sid]);$linkSource->execute([(int)$project['id'],$sid,$uid]);}
for($i=0;$i<600;$i++){$project=$projects[$i%6];$claimStmt->execute([$pub('c'),(int)$project['id'],$uid,'Seeded supported Claim '.$i.' '.$run]);}
$q=$pdo->query("SELECT COUNT(*) FROM sources WHERE title LIKE 'Seed Source %'");$sourceCount=(int)$q->fetchColumn();$q=$pdo->query("SELECT COUNT(*) FROM research_claims WHERE statement LIKE 'Seeded supported Claim %'");$claimCount=(int)$q->fetchColumn();p62s($sourceCount>=300&&$claimCount>=600,'62E seeded organization contains hundreds of evidence and Claim records.');

$runs=[];$deltaStmt=$pdo->prepare("INSERT INTO research_program_deltas(public_id,run_id,program_id,project_id,delta_type,importance,ref_type,ref_public_id,fingerprint,summary) VALUES(?,?,?,?,?,?,?,?,?,?)");
for($i=0;$i<6;$i++){$rp=research_program_enqueue($pdo,$programs[$i],$uid,'manual');$q=$pdo->prepare('SELECT id FROM research_program_runs WHERE public_id=?');$q->execute([$rp]);$rid=(int)$q->fetchColumn();$runs[$i]=$rid;for($j=0;$j<80;$j++){$type=$j%5===0?'claim_contradicted':($j%3===0?'source_restored':'claim_strengthened');$importance=$j%7===0?'high':'important';$ref='shared-'.$run.'-'.($j%35);$summary='Seeded delta '.$i.'-'.$j;$deltaStmt->execute([ulid_like(),$rid,(int)$programs[$i]['id'],(int)$programs[$i]['project_id'],$type,$importance,'claim',$ref,hash('sha256',$rid.'|'.$type.'|'.$ref.'|'.$j),$summary]);}}
p62s((int)$pdo->query("SELECT COUNT(*) FROM research_program_deltas WHERE summary LIKE 'Seeded delta %'")->fetchColumn()>=480,'62E seeded Programs carry hundreds of material intelligence deltas.');

$portfolios=[];
for($i=0;$i<3;$i++){$p=research_intelligence_portfolio_create($pdo,$owner,['title'=>'Soak Portfolio '.($i+1),'objective'=>'Bounded executive intelligence scale fixture.','team_id'=>$teamPublic,'briefing_cadence'=>'weekly','briefing_policy'=>'material_only','materiality_threshold'=>'important','timezone_name'=>'UTC','briefing_time_local'=>'09:00','briefing_weekday'=>1]);research_intelligence_portfolio_add_program($pdo,$owner,(string)$p['public_id'],(string)$programs[$i*2]['public_id'],'primary');research_intelligence_portfolio_add_program($pdo,$owner,(string)$p['public_id'],(string)$programs[$i*2+1]['public_id'],'supporting');$portfolios[]=research_intelligence_portfolio_access($pdo,$owner,(string)$p['public_id']);}
foreach($portfolios as $p){$agg=research_intelligence_portfolio_aggregate($pdo,$owner,$p,30);p62s((int)$agg['summary']['programs']===2&&count($agg['risks'])<=30&&count($agg['opportunities'])<=30&&count($agg['cross_program'])<=30,'62E Portfolio aggregation stays bounded under hundreds of deltas: '.$p['title']);$pdo->prepare('UPDATE research_intelligence_portfolios SET next_cycle_at=DATE_SUB(NOW(),INTERVAL 3 MINUTE) WHERE id=?')->execute([(int)$p['id']]);}
$first=research_intelligence_portfolio_process_due($pdo,10);p62s($first['completed']===3&&$first['briefings']===3,'62E one existing automation invocation processes all due seeded Portfolios without another worker.');
foreach($portfolios as $p)$pdo->prepare('UPDATE research_intelligence_portfolios SET next_cycle_at=DATE_SUB(NOW(),INTERVAL 1 MINUTE) WHERE id=?')->execute([(int)$p['id']]);$second=research_intelligence_portfolio_process_due($pdo,10);p62s($second['skipped']===3&&$second['briefings']===0,'62E repeated unchanged Portfolio cycles are idempotently suppressed by material hashes.');

$center=research_intelligence_organization_command_center($pdo,$owner);p62s(($center['summary']['portfolios']??0)>=3&&count($center['needs_attention'])<=120&&count($center['emerging_opportunities'])<=30&&count($center['cross_portfolio_themes'])<=30,'62E organization command center remains bounded at seeded organization scale.');
$q=$pdo->query("SELECT COUNT(*) FROM research_intelligence_portfolio_cycles WHERE portfolio_id IN (SELECT id FROM research_intelligence_portfolios WHERE owner_user_id=".$uid.")");p62s((int)$q->fetchColumn()===6,'62E cycle ledger preserves exactly one receipt per forced scheduled cycle.');

echo "Phase 62 seeded-organization soak passed with 6 Agents, 6 Programs, 300+ Sources, 600+ Claims, 480+ deltas, 3 Portfolios, and repeated bounded cycles.\n";
