<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=getenv('DB_DSN')?:'';$dbUser=getenv('DB_USER')?:'root';$dbPass=getenv('DB_PASS')?:'';if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
foreach(['installer','storage','jobs','concurrency','functions','shell','access','notifications','rate-limit','ai','ai-access','source-integrity','annotation-intelligence','research-workspace','research-knowledge','research-intelligence','research-reports','conversations','agent-actions','agent-chat','cognitive-feed','research-entities','proactive-intelligence','research-automation','cross-research','research-outcomes','research-reviews','change-impact'] as $lib)require_once $root.'/app/'.$lib.'.php';
function p22(bool $ok,string $m): void {if(!$ok)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}
$run='p22'.substr(bin2hex(random_bytes(6)),0,10);$pub=fn(string $p)=>$p.'-'.$run.'-'.substr(bin2hex(random_bytes(3)),0,6);
$makeUser=function(string $name)use($pdo,$run,$pub): array{$username=substr(strtolower($name).'_'.$run,0,48);$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,email_verified_at,status,role,plan_tier,live_presence_mode) VALUES(?,?,?,?,NOW(),'active','user','pro','cloaked')")->execute([$pub('u'),$username,$name,$username.'@example.test']);$id=(int)$pdo->lastInsertId();$pdo->prepare('INSERT IGNORE INTO user_preferences(user_id) VALUES(?)')->execute([$id]);$q=$pdo->prepare('SELECT * FROM users WHERE id=?');$q->execute([$id]);return $q->fetch();};
$owner=$makeUser('ImpactOwner');$collab=$makeUser('ImpactCollaborator');$outsider=$makeUser('ImpactOutsider');p22(change_impact_ready($pdo),'Phase 22 schema is available');

$teamPublic=$pub('team');$pdo->prepare('INSERT INTO teams(public_id,owner_user_id,name) VALUES(?,?,?)')->execute([$teamPublic,$owner['id'],'Impact Team']);$teamId=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO team_members(team_id,user_id,role) VALUES(?,?,'owner'),(?,?,'researcher')")->execute([$teamId,$owner['id'],$teamId,$collab['id']]);
$projectPublic=$pub('project');$pdo->prepare("INSERT INTO research_projects(public_id,owner_user_id,team_id,title,description,status) VALUES(?,?,?,?,?,'active')")->execute([$projectPublic,$owner['id'],$teamId,'Impact Research','Downstream impact fixture']);$projectId=(int)$pdo->lastInsertId();
$otherProject=$pub('other-project');$pdo->prepare("INSERT INTO research_projects(public_id,owner_user_id,title,description,status) VALUES(?,?,?,?,'active')")->execute([$otherProject,$owner['id'],'Related Research','Cross-project fixture']);$otherProjectId=(int)$pdo->lastInsertId();

$url='https://example.com/'.$run.'/changing-source';$sourcePublic=$pub('source');$pdo->prepare("INSERT INTO sources(public_id,source_type,canonical_url,canonical_url_hash,domain,title,status,monitoring_enabled,moderation_status) VALUES(?,'article',?,?,?,'Changing Evidence Source','edited',1,'visible')")->execute([$sourcePublic,$url,hash('sha256',$url),'example.com']);$sourceId=(int)$pdo->lastInsertId();
$pdo->prepare("INSERT INTO source_versions(source_id,version_number,final_url,title,extracted_text,content_hash,captured_at) VALUES(?,1,?,'Changing Evidence Source','The original study reported a twenty percent reduction.',?,DATE_SUB(NOW(),INTERVAL 2 HOUR))")->execute([$sourceId,$url,hash('sha256','p22-v1-'.$run)]);$v1=(int)$pdo->lastInsertId();
$pdo->prepare("INSERT INTO source_versions(source_id,version_number,final_url,title,extracted_text,content_hash,captured_at) VALUES(?,2,?,'Changing Evidence Source','The revised study reports a ten percent reduction after correction.',?,NOW())")->execute([$sourceId,$url,hash('sha256','p22-v2-'.$run)]);$v2=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE sources SET current_version_id=? WHERE id=?')->execute([$v2,$sourceId]);$pdo->prepare('INSERT INTO project_sources(project_id,source_id,added_by_user_id) VALUES(?,?,?)')->execute([$projectId,$sourceId,$owner['id']]);

$capturePublic=$pub('capture');$pdo->prepare("INSERT INTO captures(public_id,source_id,source_version_id,user_id,capture_type,selected_text) VALUES(?,?,?,?,'text','The original study reported a twenty percent reduction.')")->execute([$capturePublic,$sourceId,$v1,$owner['id']]);$captureId=(int)$pdo->lastInsertId();
$annotationPublic=$pub('annotation');$pdo->prepare("INSERT INTO annotations(public_id,user_id,source_id,source_version_id,capture_id,text_commentary,visibility,status) VALUES(?,?,?,?,?,'Evidence captured before correction.','public','published')")->execute([$annotationPublic,$owner['id'],$sourceId,$v1,$captureId]);$annotationId=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO project_annotations(project_id,annotation_id,added_by_user_id) VALUES(?,?,?)')->execute([$projectId,$annotationId,$owner['id']]);

$claimPublic=$pub('claim');$pdo->prepare("INSERT INTO research_claims(public_id,project_id,created_by_user_id,statement,claim_type,status) VALUES(?,?,?,'The intervention reduced costs by twenty percent.','factual','supported')")->execute([$claimPublic,$projectId,$owner['id']]);$claimId=(int)$pdo->lastInsertId();$evidencePublic=$pub('evidence');$pdo->prepare("INSERT INTO claim_evidence(public_id,claim_id,added_by_user_id,evidence_type,annotation_id,source_version_id,relationship,note) VALUES(?,?,?,'annotation',?,?,'primary','Primary evidence from v1.')")->execute([$evidencePublic,$claimId,$owner['id'],$annotationId,$v1]);
$findingPublic=$pub('finding');$pdo->prepare("INSERT INTO research_findings(public_id,project_id,created_by_user_id,title,summary,status,created_at,updated_at) VALUES(?,?,?,'Cost reduction finding','The current synthesis relies on the twenty percent figure.','final',DATE_SUB(NOW(),INTERVAL 90 MINUTE),DATE_SUB(NOW(),INTERVAL 90 MINUTE))")->execute([$findingPublic,$projectId,$owner['id']]);$findingId=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO finding_claims(finding_id,claim_id,added_by_user_id,relationship,position) VALUES(?,?,?,'primary',0)")->execute([$findingId,$claimId,$owner['id']]);

$reportPublic=$pub('report');$reportVersionPublic=$pub('report-v1');$snapshot=json_encode(['schema'=>'annotated-research-report-v1','project'=>['title'=>'Impact Research'],'sources'=>[['id'=>$sourcePublic,'version'=>1]],'claims'=>[['id'=>$claimPublic]],'findings'=>[['id'=>$findingPublic]]],JSON_UNESCAPED_SLASHES);$snapshotHash=hash('sha256',$snapshot);
$pdo->prepare("INSERT INTO research_reports(public_id,project_id,created_by_user_id,title,summary,visibility,status,published_at,created_at,updated_at) VALUES(?,?,?,?,?,'team','published',DATE_SUB(NOW(),INTERVAL 70 MINUTE),DATE_SUB(NOW(),INTERVAL 70 MINUTE),DATE_SUB(NOW(),INTERVAL 70 MINUTE))")->execute([$reportPublic,$projectId,$owner['id'],'Impact Report','Published before correction']);$reportId=(int)$pdo->lastInsertId();
$pdo->prepare("INSERT INTO research_report_versions(public_id,report_id,version_number,published_by_user_id,visibility,title,summary,snapshot_json,snapshot_hash,created_at) VALUES(?,?,1,?,'team','Impact Report','Published before correction',?,?,DATE_SUB(NOW(),INTERVAL 70 MINUTE))")->execute([$reportVersionPublic,$reportId,$owner['id'],$snapshot,$snapshotHash]);$reportVersionId=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE research_reports SET current_version_id=? WHERE id=?')->execute([$reportVersionId,$reportId]);

$review=research_review_create($pdo,$owner,'claim',$claimPublic,[$collab['id']],null,'Review the evidence supporting this claim.');$pdo->prepare('UPDATE research_reviews SET created_at=DATE_SUB(NOW(),INTERVAL 60 MINUTE),updated_at=DATE_SUB(NOW(),INTERVAL 60 MINUTE) WHERE id=?')->execute([$review['id']]);research_review_respond($pdo,$collab,(string)$review['public_id'],'approve','The v1 evidence supported the claim at review time.');$pdo->prepare('UPDATE research_review_responses SET created_at=DATE_SUB(NOW(),INTERVAL 55 MINUTE) WHERE review_id=?')->execute([$review['id']]);$pdo->prepare('UPDATE research_review_assignments SET responded_at=DATE_SUB(NOW(),INTERVAL 55 MINUTE) WHERE review_id=?')->execute([$review['id']]);

$otherClaim=$pub('other-claim');$pdo->prepare("INSERT INTO research_claims(public_id,project_id,created_by_user_id,statement,claim_type,status) VALUES(?,?,?,'A related project reuses this conclusion.','interpretation','unverified')")->execute([$otherClaim,$otherProjectId,$owner['id']]);
$linkPublic=$pub('cross-link');$pdo->prepare("INSERT INTO cross_research_links(public_id,user_id,source_project_id,target_project_id,object_type,source_object_public_id,target_object_public_id,relation_type,rationale) VALUES(?,?,?,?, 'claim',?,?,'depends_on','Related Research depends on the affected claim.')")->execute([$linkPublic,$owner['id'],$projectId,$otherProjectId,$claimPublic,$otherClaim]);

$pdo->prepare("INSERT INTO source_change_events(source_id,previous_version_id,new_version_id,change_type,impact_type,target_changed,affected_annotation_count,diff_summary,created_at) VALUES(?,?,?,'edited','passage_changed',1,1,'The reported reduction changed from twenty percent to ten percent.',NOW())")->execute([$sourceId,$v1,$v2]);$eventId=(int)$pdo->lastInsertId();
$pdo->prepare("INSERT INTO source_annotation_impacts(source_change_event_id,annotation_id,impact_type,previous_excerpt,current_excerpt) VALUES(?,?,'passage_changed','The original study reported a twenty percent reduction.','The revised study reports a ten percent reduction after correction.')")->execute([$eventId,$annotationId]);

$view=change_impact_event_view($pdo,$owner,$eventId);p22($view!==null&&$view['total_projects']===1,'source change resolves to the accessible affected Research project without unrelated project noise');$impact=$view['projects'][0]??null;p22($impact!==null,'project impact is available');
p22($impact['counts']['annotations']===1&&$impact['counts']['claims']===1&&$impact['counts']['findings']===1,'impact chain reaches Annotation → Claim → Finding');
p22($impact['counts']['reports']===1&&$impact['reports'][0]['is_current']===true,'current immutable published Report version is identified as potentially stale');
p22($impact['counts']['reviews']===1,'prior collaborative review of affected Claim is identified downstream');
p22($impact['counts']['cross_research_links']===1,'accepted Cross-Research dependency is identified downstream');
p22($impact['claims'][0]['evidence'][0]['captured_version']===1&&$impact['claims'][0]['evidence'][0]['current_version']===2,'Claim impact explains exact earlier Source Version versus current version');
p22($impact['unresolved_count']>=6&&$impact['severity']==='high','material source correction consolidates into a high-impact project event');

$reviewAfter=research_review_access($pdo,$owner,(string)$review['public_id']);p22($reviewAfter['is_stale']===true&&str_contains((string)$reviewAfter['stale_reason'],'Upstream source evidence changed'),'Phase 21 review becomes stale when upstream evidence changes after review request');

$context=agent_chat_context_item($pdo,$owner,'research',$projectPublic);p22($context!==null&&str_contains((string)$context['text'],'[CHANGE IMPACT / STALENESS]'),'primary Agent receives permission-checked change-impact context');
$handoff=change_impact_agent_handoff($pdo,$owner,$eventId,$projectPublic);p22($handoff!==null&&str_contains((string)$handoff['prompt'],'potentially stale')&&str_contains((string)$handoff['prompt'],'Do not change Claim/Finding status'),'Agent handoff explains impact without automatic Research mutation');

$feed=cognitive_feed_compose($pdo,$owner,null,8,120);$cards=array_values(array_filter(proactive_feed_items($feed),fn($i)=>($i['type']??'')==='change_impact'));p22(count($cards)>=1,'unresolved source impact surfaces as one consolidated Cognitive Feed observation');
$watch=proactive_watch_upsert($pdo,$owner,'project',$projectPublic,null,'all');proactive_preferences_set($pdo,$owner,'mentions',true);proactive_intelligence_sync($pdo,$owner,$feed);$q=$pdo->prepare("SELECT context_json FROM notifications WHERE user_id=? AND notification_type='research_proactive' ORDER BY id DESC LIMIT 100");$q->execute([$owner['id']]);$impactNotice=false;foreach($q->fetchAll(PDO::FETCH_COLUMN) as $json){$j=json_decode((string)$json,true)?:[];if(($j['observation_type']??'')==='change_impact'){$impactNotice=true;break;}}p22($impactNotice,'Stage 17 project watch can deliver consolidated change-impact alert');

$decision=change_impact_set_decision($pdo,$owner,$eventId,'claim',$claimPublic,'needs_update','Recalculate the conclusion from corrected Source v2.');p22(($decision['decision']??'')==='needs_update','user can explicitly mark an impacted Claim as needing update');
$q=$pdo->prepare("SELECT COUNT(*) FROM research_outcome_events WHERE user_id=? AND source_type='source_change_event' AND source_public_id=?");$q->execute([$owner['id'],(string)$eventId]);p22((int)$q->fetchColumn()>=1,'impact review decision is preserved in Decision Memory');
$resolvedProject=change_impact_set_decision($pdo,$owner,$eventId,'project',$projectPublic,'reviewed_current','Reviewed all downstream dependencies; current conclusions remain intentionally published pending a new report version.');p22(($resolvedProject['decision']??'')==='reviewed_current','project-level human review can explicitly resolve consolidated impact');
$viewResolved=change_impact_event_view($pdo,$owner,$eventId);p22(($viewResolved['projects'][0]['unresolved_count']??-1)===0,'project-level reviewed-current decision resolves consolidated alert without deleting dependency audit rows');
$feedResolved=cognitive_feed_compose($pdo,$owner,null,8,120);$cardsResolved=array_values(array_filter(proactive_feed_items($feedResolved),fn($i)=>($i['type']??'')==='change_impact'&&($i['meta']['event_id']??0)===$eventId));p22(count($cardsResolved)===0,'resolved project impact leaves Cognitive Feed');

$auto=research_automation_create($pdo,$owner,['title'=>'Weekly Change Impact Review','project_id'=>$projectPublic,'workflow_type'=>'impact_review','trigger_type'=>'schedule','cadence'=>'manual','timezone_name'=>'UTC']);$aiBefore=(int)$pdo->query('SELECT COUNT(*) FROM ai_jobs')->fetchColumn();$result=research_automation_execute($pdo,[],['automation_id'=>$auto['id'],'user_id'=>$owner['id'],'trigger_type'=>'manual']);$aiAfter=(int)$pdo->query('SELECT COUNT(*) FROM ai_jobs')->fetchColumn();p22($result['status']==='completed'&&$result['ai_run']===null&&$result['proposals']===0&&str_contains($result['output'],'Change impact review'),'Change Impact Review automation is deterministic and read-only');p22($aiBefore===$aiAfter,'Change Impact Review automation creates no AI job');

$collabView=change_impact_event_view($pdo,$collab,$eventId);p22($collabView!==null&&count($collabView['projects'])===1,'Team collaborator can inspect impact while project access exists');$pdo->prepare('DELETE FROM team_members WHERE team_id=? AND user_id=?')->execute([$teamId,$collab['id']]);$revoked=change_impact_event_view($pdo,$collab,$eventId);p22($revoked!==null&&count($revoked['projects'])===0,'revoked Team member sees no downstream Research impact even when Source itself remains visible');$outsiderView=change_impact_event_view($pdo,$outsider,$eventId);p22($outsiderView!==null&&count($outsiderView['projects'])===0,'outsider receives no Research dependency leakage from a visible Source change');

$runtime=file_get_contents($root.'/app/change-impact.php');p22(!str_contains($runtime,'ai_run(')&&!str_contains($runtime,'agent_action_confirm_execute(')&&!str_contains($runtime,'UPDATE research_claims SET status')&&!str_contains($runtime,'UPDATE research_findings SET status'),'Change Impact runtime contains no AI ranker or automatic Claim/Finding mutation');
echo "Phase 22 Change Impact & Staleness Intelligence MariaDB suite passed.\n";
