<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=getenv('DB_DSN')?:'';$dbUser=getenv('DB_USER')?:'root';$dbPass=getenv('DB_PASS')?:'';if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
foreach(['installer','storage','jobs','concurrency','functions','shell','access','notifications','rate-limit','ai','ai-access','source-integrity','annotation-intelligence','research-workspace','research-knowledge','research-intelligence','research-reports','conversations','agent-actions','agent-chat','cognitive-feed','research-entities','proactive-intelligence','research-automation','cross-research','research-outcomes','research-reviews'] as $lib)require_once $root.'/app/'.$lib.'.php';
function p21(bool $ok,string $m): void {if(!$ok)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}
$run='p21'.substr(bin2hex(random_bytes(6)),0,10);$pub=fn(string $p)=>$p.'-'.$run.'-'.substr(bin2hex(random_bytes(3)),0,6);
$makeUser=function(string $name)use($pdo,$run,$pub): array{$username=substr(strtolower($name).'_'.$run,0,48);$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,email_verified_at,status,role,plan_tier,live_presence_mode) VALUES(?,?,?,?,NOW(),'active','user','pro','cloaked')")->execute([$pub('u'),$username,$name,$username.'@example.test']);$id=(int)$pdo->lastInsertId();$pdo->prepare('INSERT IGNORE INTO user_preferences(user_id) VALUES(?)')->execute([$id]);$q=$pdo->prepare('SELECT * FROM users WHERE id=?');$q->execute([$id]);return $q->fetch();};
$owner=$makeUser('ReviewOwner');$r1=$makeUser('ReviewerOne');$r2=$makeUser('ReviewerTwo');$outsider=$makeUser('ReviewOutsider');p21(research_reviews_ready($pdo),'Phase 21 schema is available');

$teamPublic=$pub('team');$pdo->prepare('INSERT INTO teams(public_id,owner_user_id,name) VALUES(?,?,?)')->execute([$teamPublic,$owner['id'],'Review Team']);$teamId=(int)$pdo->lastInsertId();
$pdo->prepare("INSERT INTO team_members(team_id,user_id,role) VALUES(?,?,'owner'),(?,?,'researcher'),(?,?,'researcher')")->execute([$teamId,$owner['id'],$teamId,$r1['id'],$teamId,$r2['id']]);
$projectPublic=$pub('project');$pdo->prepare("INSERT INTO research_projects(public_id,owner_user_id,team_id,title,description,status) VALUES(?,?,?,?,?,'active')")->execute([$projectPublic,$owner['id'],$teamId,'Governed Research','Collaborative review fixture']);$projectId=(int)$pdo->lastInsertId();

$claimPublic=$pub('claim');$pdo->prepare("INSERT INTO research_claims(public_id,project_id,created_by_user_id,statement,claim_type,status) VALUES(?,?,?,'The reviewed evidence supports the current claim.','factual','supported')")->execute([$claimPublic,$projectId,$owner['id']]);
$findingPublic=$pub('finding');$pdo->prepare("INSERT INTO research_findings(public_id,project_id,created_by_user_id,title,summary,status) VALUES(?,?,?,'Governed Finding','Initial finding summary.','draft')")->execute([$findingPublic,$projectId,$owner['id']]);

$review=research_review_create($pdo,$owner,'claim',$claimPublic,[$r1['id'],$r2['id']],date('Y-m-d H:i:s',time()+86400),'Check the exact evidence and note any unresolved objections.');p21(!empty($review['public_id']),'project owner can request Claim review from current collaborators');
$agg=research_review_aggregate($pdo,$review);p21($agg['assigned']===2&&$agg['counts']['pending']===2,'review starts with two pending reviewer assignments');
$q=$pdo->prepare("SELECT COUNT(*) FROM notifications WHERE user_id IN (?,?) AND notification_type='research_review_requested' AND object_public_id=?");$q->execute([$r1['id'],$r2['id'],$review['public_id']]);p21((int)$q->fetchColumn()===2,'review request uses existing notification center for each reviewer');

$blocked=false;try{research_review_respond($pdo,$outsider,(string)$review['public_id'],'approve','');}catch(RuntimeException $e){$blocked=true;}p21($blocked,'unassigned outsider cannot respond to a review');
research_review_respond($pdo,$r1,(string)$review['public_id'],'approve','Evidence is adequate for this version.');
research_review_respond($pdo,$r1,(string)$review['public_id'],'disagree','One source needs independent verification.');
$q=$pdo->prepare('SELECT COUNT(*) FROM research_review_responses WHERE review_id=? AND reviewer_user_id=?');$q->execute([$review['id'],$r1['id']]);p21((int)$q->fetchColumn()===2,'review responses are append-only rather than overwritten');
research_review_respond($pdo,$r2,(string)$review['public_id'],'approve','I approve this exact Claim state.');
$review=research_review_access($pdo,$owner,(string)$review['public_id']);$agg=research_review_aggregate($pdo,$review);p21($agg['consensus']==='unresolved_objection'&&$agg['counts']['approve']===1&&$agg['counts']['disagree']===1,'latest reviewer responses produce unresolved objection without majority verdict');

research_review_comment($pdo,$r2,(string)$review['public_id'],'The objection should remain visible in the completion record.');p21(count(research_review_comments($pdo,$review,20))===1,'review discussion comment is append-only and attached to exact review');
$completed=research_review_complete($pdo,$owner,(string)$review['public_id']);$frozen=json_decode((string)$completed['completion_json'],true)?:[];p21($completed['status']==='completed'&&($frozen['consensus']??'')==='unresolved_objection','requester can complete review while preserving unresolved objection instead of inventing consensus');
$late=false;try{research_review_respond($pdo,$r2,(string)$review['public_id'],'approve','late');}catch(RuntimeException $e){$late=true;}p21($late,'completed review rejects later responses and remains immutable');

$q=$pdo->prepare("SELECT COUNT(*) FROM research_outcome_events WHERE user_id=? AND source_type='research_review' AND source_public_id=? AND decision_type='completed'");$q->execute([$owner['id'],$review['public_id']]);p21((int)$q->fetchColumn()===1,'completed governance decision is recorded in Decision Memory');
$q=$pdo->prepare("SELECT COUNT(*) FROM research_outcome_events WHERE user_id=? AND source_type='research_review' AND source_public_id=? AND decision_type='disagree'");$q->execute([$r1['id'],$review['public_id']]);p21((int)$q->fetchColumn()===1,'individual reviewer response is recorded in that reviewer Decision Memory');

$pdo->prepare("UPDATE research_claims SET statement='The reviewed evidence supports the revised claim after additional analysis.' WHERE public_id=?")->execute([$claimPublic]);$afterChange=research_review_access($pdo,$owner,(string)$review['public_id']);p21($afterChange['is_stale']===true,'completed Claim review is visibly based on earlier Research after Claim changes');$frozenAgain=json_decode((string)$afterChange['completion_json'],true)?:[];p21(($frozenAgain['subject_hash']??'')===($frozen['subject_hash']??''),'later Claim changes do not rewrite frozen completion record');

$findingReview=research_review_create($pdo,$owner,'finding',$findingPublic,[$r1['id'],$r2['id']],null,'Review the Finding synthesis.');research_review_respond($pdo,$r1,(string)$findingReview['public_id'],'approve','Current draft is coherent.');
$pdo->prepare("UPDATE research_findings SET summary='Materially changed finding summary.' WHERE public_id=?")->execute([$findingPublic]);$staleFinding=research_review_access($pdo,$owner,(string)$findingReview['public_id']);p21($staleFinding['is_stale']===true,'open Finding review becomes stale after material Finding change');
$staleResponseBlocked=false;try{research_review_respond($pdo,$r2,(string)$findingReview['public_id'],'approve','');}catch(RuntimeException $e){$staleResponseBlocked=true;}p21($staleResponseBlocked,'stale review blocks new reviewer responses');
$staleCompleteBlocked=false;try{research_review_complete($pdo,$owner,(string)$findingReview['public_id']);}catch(RuntimeException $e){$staleCompleteBlocked=true;}p21($staleCompleteBlocked,'stale review cannot be completed as if current');
$restartedFinding=research_review_restart($pdo,$owner,(string)$findingReview['public_id'],null);p21($restartedFinding['subject_hash']!==$findingReview['subject_hash']&&$restartedFinding['status']==='open','restart pins a new Finding review to current Research state');

$reportPublic=$pub('report');$v1Public=$pub('report-v1');$v2Public=$pub('report-v2');
$pdo->prepare("INSERT INTO research_reports(public_id,project_id,created_by_user_id,title,summary,visibility,status,published_at) VALUES(?,?,?,?,?,'team','published',NOW())")->execute([$reportPublic,$projectId,$owner['id'],'Governed Report','Versioned review fixture']);$reportId=(int)$pdo->lastInsertId();
$snap1=json_encode(['schema'=>'test','project'=>['title'=>'Governed Report'],'claims'=>[]]);$hash1=hash('sha256',$snap1);$pdo->prepare("INSERT INTO research_report_versions(public_id,report_id,version_number,published_by_user_id,visibility,title,summary,snapshot_json,snapshot_hash) VALUES(?,?,1,?,'team','Governed Report','V1',?,?)")->execute([$v1Public,$reportId,$owner['id'],$snap1,$hash1]);$v1Id=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE research_reports SET current_version_id=? WHERE id=?')->execute([$v1Id,$reportId]);
$reportReview=research_review_create($pdo,$owner,'report_version',$v1Public,[$r1['id']],null,'Approve the immutable report version.');
research_review_respond($pdo,$r1,(string)$reportReview['public_id'],'approve','Version 1 is approved.');
$snap2=json_encode(['schema'=>'test','project'=>['title'=>'Governed Report v2'],'claims'=>[]]);$hash2=hash('sha256',$snap2);$pdo->prepare("INSERT INTO research_report_versions(public_id,report_id,version_number,published_by_user_id,visibility,title,summary,snapshot_json,snapshot_hash) VALUES(?,?,2,?,'team','Governed Report','V2',?,?)")->execute([$v2Public,$reportId,$owner['id'],$snap2,$hash2]);$v2Id=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE research_reports SET current_version_id=? WHERE id=?')->execute([$v2Id,$reportId]);
$oldVersion=research_review_access($pdo,$owner,(string)$reportReview['public_id']);p21($oldVersion['is_stale']===true&&str_contains((string)$oldVersion['stale_reason'],'newer report version'),'Report review remains pinned to V1 and is marked earlier-version after V2 publishes');
$reportRestart=research_review_restart($pdo,$owner,(string)$reportReview['public_id'],null);p21($reportRestart['subject_public_id']===$v2Public&&str_contains((string)$reportRestart['subject_version_label'],'2'),'restarting stale Report review targets current immutable Report version');

$conversation=agent_chat_create($pdo,$owner,'Governed Agent Proposal');$um=conversation_message_create($pdo,$owner,(string)$conversation['public_id'],'Prepare a bounded proposal.',null,'p21-'.$run);$am=agent_chat_insert_agent_message($pdo,$conversation,'Proposal ready.',(int)$um['id']);
$proposalPublic=$pub('proposal');$args=json_encode(['title'=>'Verify the disputed evidence']);$pdo->prepare("INSERT INTO agent_action_proposals(public_id,conversation_id,assistant_message_id,proposed_by_user_id,project_id,capability_key,status,arguments_json,provenance_json,project_state_hash,dedupe_key,expires_at) VALUES(?,?,?,?,?,'research.create_task','pending',?,'{}',?,?,DATE_ADD(NOW(),INTERVAL 1 HOUR))")->execute([$proposalPublic,$conversation['id'],$am['id'],$owner['id'],$projectId,$args,hash('sha256','p21-state-'.$run),hash('sha256','p21-proposal-'.$run)]);
$proposalReview=research_review_create($pdo,$owner,'agent_action',$proposalPublic,[$r1['id']],null,'Review the proposed write before I confirm it.');p21(str_contains((string)$proposalReview['subject']['url'],(string)$conversation['public_id']),'Agent proposal review links to the public Agent conversation');
$pdo->prepare("UPDATE agent_action_proposals SET status='executed',executed_at=NOW() WHERE public_id=?")->execute([$proposalPublic]);p21(research_review_access($pdo,$owner,(string)$proposalReview['public_id'])['is_stale']===true,'Agent proposal review becomes stale when proposal state changes');

$openReview=research_review_create($pdo,$owner,'claim',$claimPublic,[$r1['id']],date('Y-m-d H:i:s',time()+7200),'Fresh deadline fixture.');$pdo->prepare('UPDATE research_reviews SET due_at=DATE_SUB(NOW(),INTERVAL 1 HOUR) WHERE id=?')->execute([$openReview['id']]);
$feedR1=cognitive_feed_compose($pdo,$r1,null,8,100);$reviewCards=array_values(array_filter(proactive_feed_items($feedR1),fn($i)=>($i['type']??'')==='review_overdue'));p21(count($reviewCards)>=1,'overdue assigned review surfaces in Cognitive Feed');
$watch=proactive_watch_upsert($pdo,$r1,'project',$projectPublic,null,'all');proactive_preferences_set($pdo,$r1,'mentions',true);proactive_intelligence_sync($pdo,$r1,$feedR1);
$q=$pdo->prepare("SELECT context_json FROM notifications WHERE user_id=? AND notification_type='research_proactive' ORDER BY id DESC LIMIT 50");$q->execute([$r1['id']]);$reviewNotice=false;foreach($q->fetchAll(PDO::FETCH_COLUMN) as $json){$j=json_decode((string)$json,true)?:[];if(($j['observation_type']??'')==='review_overdue'){$reviewNotice=true;break;}}p21($reviewNotice,'Stage 17 proactive intelligence can deliver overdue review observation');

$agentContext=agent_chat_context_item($pdo,$owner,'research',$projectPublic);p21($agentContext!==null&&str_contains((string)$agentContext['text'],'[COLLABORATIVE RESEARCH REVIEW]'),'primary Agent receives permission-checked collaborative review context');
$handoff=research_review_agent_handoff($pdo,$owner,(string)$openReview['public_id']);p21($handoff!==null&&str_contains((string)$handoff['prompt'],'without voting')&&str_contains((string)$handoff['prompt'],'Do not approve'),'Review Agent handoff explicitly forbids Agent voting or review decisions');

$auto=research_automation_create($pdo,$owner,['title'=>'Weekly Review Digest','project_id'=>$projectPublic,'workflow_type'=>'review_digest','trigger_type'=>'schedule','cadence'=>'manual','timezone_name'=>'UTC']);$aiBefore=(int)$pdo->query('SELECT COUNT(*) FROM ai_jobs')->fetchColumn();$result=research_automation_execute($pdo,[],['automation_id'=>$auto['id'],'user_id'=>$owner['id'],'trigger_type'=>'manual']);$aiAfter=(int)$pdo->query('SELECT COUNT(*) FROM ai_jobs')->fetchColumn();p21($result['status']==='completed'&&$result['ai_run']===null&&$result['proposals']===0&&str_contains($result['output'],'Collaborative review digest'),'Review Digest automation is deterministic and read-only');p21($aiBefore===$aiAfter,'Review Digest creates no AI job');

$revokedReview=research_review_create($pdo,$owner,'finding',$findingPublic,[$r2['id']],null,'Revocation boundary fixture.');$q=$pdo->prepare("SELECT * FROM notifications WHERE user_id=? AND object_type='research_review' AND object_public_id=? ORDER BY id DESC LIMIT 1");$q->execute([$r2['id'],$revokedReview['public_id']]);$reviewNotification=$q->fetch();p21((bool)$reviewNotification,'review notification exists before access revocation');
$pdo->prepare('DELETE FROM team_members WHERE team_id=? AND user_id=?')->execute([$teamId,$r2['id']]);p21(research_review_access($pdo,$r2,(string)$revokedReview['public_id'])===null,'revoked Team member immediately loses review access');p21(!notification_object_access($pdo,$r2,$reviewNotification),'stored review notification is hidden after Team access revocation');p21(count(research_review_list($pdo,$r2,'all',100))===0,'revoked Team member gets no Review Center leakage');
p21(count(research_review_list($pdo,$outsider,'all',100))===0,'outsider receives no review identity leakage');

$runtime=file_get_contents($root.'/app/research-reviews.php');p21(!str_contains($runtime,'ai_run(')&&!str_contains($runtime,'agent_action_confirm_execute(')&&!str_contains($runtime,'agent_action_execute_capability('),'review governance runtime has no Agent vote, AI execution, or Research write execution path');
echo "Phase 21 Collaborative Research Review & Governance MariaDB suite passed.\n";
