<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=getenv('DB_DSN')?:'';$dbUser=getenv('DB_USER')?:'root';$dbPass=getenv('DB_PASS')?:'';if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
foreach(['installer','storage','jobs','concurrency','functions','shell','access','notifications','rate-limit','ai','ai-access','source-integrity','annotation-intelligence','research-workspace','conversations','agent-actions','agent-chat','cognitive-feed','research-entities','proactive-intelligence','research-automation','cross-research'] as $lib)require_once $root.'/app/'.$lib.'.php';
function p19(bool $ok,string $message): void {if(!$ok)throw new RuntimeException('FAIL: '.$message);echo "PASS: $message\n";}
$run='p19'.substr(bin2hex(random_bytes(6)),0,10);$pub=fn(string $p)=>$p.'-'.$run.'-'.substr(bin2hex(random_bytes(3)),0,6);
$makeUser=function(string $name,string $plan='pro')use($pdo,$run,$pub): array{$username=substr(strtolower($name).'_'.$run,0,48);$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,email_verified_at,status,role,plan_tier,live_presence_mode) VALUES(?,?,?,?,NOW(),'active','user',?,'cloaked')")->execute([$pub('u'),$username,$name,$username.'@example.test',$plan]);$id=(int)$pdo->lastInsertId();$pdo->prepare('INSERT IGNORE INTO user_preferences(user_id) VALUES(?)')->execute([$id]);$q=$pdo->prepare('SELECT * FROM users WHERE id=?');$q->execute([$id]);return $q->fetch();};
$owner=$makeUser('CrossOwner');$collab=$makeUser('CrossCollaborator');$outsider=$makeUser('CrossOutsider');p19(cross_research_ready($pdo),'Phase 19 schema is available');

$teamPublic=$pub('team');$pdo->prepare('INSERT INTO teams(public_id,owner_user_id,name) VALUES(?,?,?)')->execute([$teamPublic,$owner['id'],'Cross Research Team']);$teamId=(int)$pdo->lastInsertId();
$pdo->prepare("INSERT INTO team_members(team_id,user_id,role) VALUES(?,?,'owner'),(?,?,'researcher')")->execute([$teamId,$owner['id'],$teamId,$collab['id']]);

$projectA=$pub('project-a');$projectB=$pub('project-b');$pdo->prepare("INSERT INTO research_projects(public_id,owner_user_id,team_id,title,description,status) VALUES(?,?,?,?,?,'active'),(?,?,?,?,?,'active')")->execute([$projectA,$owner['id'],$teamId,'Phoenix Broadband Costs','Cost and adoption evidence',$projectB,$owner['id'],$teamId,'Municipal Network Outcomes','Outcome and verification evidence']);
$q=$pdo->prepare('SELECT id,public_id FROM research_projects WHERE public_id IN (?,?)');$q->execute([$projectA,$projectB]);$projectIds=[];foreach($q->fetchAll() as $r)$projectIds[$r['public_id']]=(int)$r['id'];$projectAId=$projectIds[$projectA];$projectBId=$projectIds[$projectB];

$url='https://example.com/'.$run.'/broadband-study';$sourcePublic=$pub('source');$pdo->prepare("INSERT INTO sources(public_id,source_type,canonical_url,canonical_url_hash,domain,title,status,monitoring_enabled,moderation_status) VALUES(?,'article',?,?,?,'Broadband Cost Study','current',1,'visible')")->execute([$sourcePublic,$url,hash('sha256',$url),'example.com']);$sourceId=(int)$pdo->lastInsertId();
$pdo->prepare("INSERT INTO source_versions(source_id,version_number,final_url,title,extracted_text,content_hash) VALUES(?,1,?,'Broadband Cost Study','Municipal broadband reduced household internet costs by twenty percent across Phoenix neighborhoods.',?)")->execute([$sourceId,$url,hash('sha256','p19-v1-'.$run)]);$versionId=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE sources SET current_version_id=? WHERE id=?')->execute([$versionId,$sourceId]);
$pdo->prepare('INSERT INTO project_sources(project_id,source_id,added_by_user_id) VALUES(?,?,?),(?,?,?)')->execute([$projectAId,$sourceId,$owner['id'],$projectBId,$sourceId,$owner['id']]);

$capturePublic=$pub('capture');$pdo->prepare("INSERT INTO captures(public_id,source_id,source_version_id,user_id,capture_type,selected_text) VALUES(?,?,?,?,'text',?)")->execute([$capturePublic,$sourceId,$versionId,$owner['id'],'Municipal broadband reduced household internet costs by twenty percent.']);$captureId=(int)$pdo->lastInsertId();
$annotationShared=$pub('annotation-shared');$pdo->prepare("INSERT INTO annotations(public_id,user_id,source_id,source_version_id,capture_id,text_commentary,visibility,status) VALUES(?,?,?,?,?,?,'public','published')")->execute([$annotationShared,$owner['id'],$sourceId,$versionId,$captureId,'Exact cost reduction evidence used by both projects.']);$annotationSharedId=(int)$pdo->lastInsertId();
$pdo->prepare('INSERT INTO project_annotations(project_id,annotation_id,added_by_user_id) VALUES(?,?,?),(?,?,?)')->execute([$projectAId,$annotationSharedId,$owner['id'],$projectBId,$annotationSharedId,$owner['id']]);

$capture2=$pub('capture2');$pdo->prepare("INSERT INTO captures(public_id,source_id,source_version_id,user_id,capture_type,selected_text) VALUES(?,?,?,?,'text',?)")->execute([$capture2,$sourceId,$versionId,$owner['id'],'Neighborhood adoption increased after the municipal network launch.']);$capture2Id=(int)$pdo->lastInsertId();
$annotationReuse=$pub('annotation-reuse');$pdo->prepare("INSERT INTO annotations(public_id,user_id,source_id,source_version_id,capture_id,text_commentary,visibility,status) VALUES(?,?,?,?,?,?,'public','published')")->execute([$annotationReuse,$owner['id'],$sourceId,$versionId,$capture2Id,'Adoption evidence available only in the first project.']);$annotationReuseId=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO project_annotations(project_id,annotation_id,added_by_user_id) VALUES(?,?,?)')->execute([$projectAId,$annotationReuseId,$owner['id']]);

$entityA=$pub('entity-a');$entityB=$pub('entity-b');$pdo->prepare("INSERT INTO research_entities(public_id,project_id,created_by_user_id,entity_type,canonical_name,normalized_name,status,source_type) VALUES(?,?,?,'organization','Phoenix Municipal Broadband','phoenix municipal broadband','confirmed','manual'),(?,?,?,'organization','Phoenix Municipal Broadband','phoenix municipal broadband','confirmed','manual')")->execute([$entityA,$projectAId,$owner['id'],$entityB,$projectBId,$owner['id']]);

$claimA=$pub('claim-a');$claimB=$pub('claim-b');$statement='The municipal broadband program reduced household internet costs by twenty percent across Phoenix neighborhoods.';
$pdo->prepare("INSERT INTO research_claims(public_id,project_id,created_by_user_id,statement,claim_type,status) VALUES(?,?,?,?,'factual','supported'),(?,?,?,?,'factual','contradicted')")->execute([$claimA,$projectAId,$owner['id'],$statement,$claimB,$projectBId,$owner['id'],$statement]);$claimAId=(int)$pdo->query("SELECT id FROM research_claims WHERE public_id=".$pdo->quote($claimA))->fetchColumn();$claimBId=(int)$pdo->query("SELECT id FROM research_claims WHERE public_id=".$pdo->quote($claimB))->fetchColumn();
$pdo->prepare("INSERT INTO claim_evidence(public_id,claim_id,added_by_user_id,evidence_type,source_version_id,relationship,note) VALUES(?,?,?,'source_version',?,'supports','Project A interprets the evidence as support.'),(?,?,?,'source_version',?,'contradicts','Project B currently classifies the same version as contradictory.')")->execute([$pub('evidence-a'),$claimAId,$owner['id'],$versionId,$pub('evidence-b'),$claimBId,$owner['id'],$versionId]);

$jobsBefore=(int)$pdo->query('SELECT COUNT(*) FROM ai_jobs')->fetchColumn();$suggestions=cross_research_suggestions($pdo,$owner,null,200,false);$jobsAfter=(int)$pdo->query('SELECT COUNT(*) FROM ai_jobs')->fetchColumn();p19($jobsBefore===$jobsAfter,'Cross-Research discovery creates no AI ranking jobs');
$types=array_column($suggestions,'type');foreach(['shared_source','shared_annotation','same_entity','claim_status_difference','evidence_label_conflict','evidence_reuse','related_projects'] as $expected)p19(in_array($expected,$types,true),'deterministic discovery includes '.$expected);
$conflict=array_values(array_filter($suggestions,fn($s)=>$s['type']==='evidence_label_conflict'))[0]??null;p19($conflict!==null&&$conflict['priority']==='high'&&$conflict['score']>=95,'opposite labels on identical Source Version surface as high-priority evidence conflict');
$claimDifference=array_values(array_filter($suggestions,fn($s)=>$s['type']==='claim_status_difference'))[0]??null;p19($claimDifference!==null&&str_contains(implode(' ',$claimDifference['reasons']),'does not by itself mean'),'Claim status difference is explicitly not misrepresented as semantic contradiction');

$ownerEntity=array_values(array_filter($suggestions,fn($s)=>$s['type']==='same_entity'))[0]??null;p19($ownerEntity!==null,'same normalized Entity suggestion is available for decision testing');
p19(cross_research_reject($pdo,$owner,(string)$ownerEntity['key']),'owner can dismiss a Cross-Research suggestion');$ownerAfterReject=cross_research_suggestions($pdo,$owner,null,200,false);p19(!in_array((string)$ownerEntity['key'],array_column($ownerAfterReject,'key'),true),'rejected suggestion is hidden for that user');
$collabSuggestions=cross_research_suggestions($pdo,$collab,null,200,false);p19(in_array((string)$ownerEntity['key'],array_column($collabSuggestions,'key'),true),'Cross-Research decisions are user-scoped and do not hide collaborator suggestions');

$sharedSource=array_values(array_filter($suggestions,fn($s)=>$s['type']==='shared_source'))[0]??null;$link=cross_research_accept($pdo,$owner,(string)$sharedSource['key'],'shared_source');p19(($link['relation_type']??'')==='shared_source','accepted suggestion persists as an explicit Cross-Research link');p19(count(cross_research_links($pdo,$owner,null,50))>=1,'owner can list accepted Cross-Research links');p19(count(cross_research_links($pdo,$collab,null,50))===0,'accepted Cross-Research links are user-scoped');
$badProjectRelation=false;try{cross_research_create_project_link($pdo,$owner,$projectA,$projectB,'same_entity','invalid project-only relation');}catch(InvalidArgumentException $e){$badProjectRelation=true;}p19($badProjectRelation,'manual project links reject object-specific relationship types');
$manualLink=cross_research_create_project_link($pdo,$owner,$projectA,$projectB,'follow_up','The outcomes project follows the cost study.');p19(($manualLink['relation_type']??'')==='follow_up','explicit project relationship can be created without merging projects');

$threads=cross_research_entity_threads($pdo,$owner,null,20);p19(count($threads)>=1&&$threads[0]['project_count']>=2,'Entity thread consolidates exact normalized identity across accessible projects');
$ctx=cross_research_context($pdo,$owner,$projectA,20);p19(str_contains((string)$ctx['text'],'[CROSS-RESEARCH INTELLIGENCE]'),'project Agent context includes Cross-Research intelligence');
$agentContext=agent_chat_context_item($pdo,$owner,'research',$projectA);p19($agentContext!==null&&str_contains((string)$agentContext['text'],'[CROSS-RESEARCH INTELLIGENCE]'),'primary Agent Chat receives permission-checked Cross-Research project context');
$handoff=cross_research_agent_handoff($pdo,$owner,(string)$conflict['key']);p19($handoff!==null&&count($handoff['context'])>=2&&str_contains($handoff['prompt'],'Do not merge'),'Cross-Research Ask Agent handoff is rebuilt from current accessible suggestion');

$feed=cognitive_feed_compose($pdo,$owner,null,8,80);$feedItems=proactive_feed_items($feed);$crossFeed=array_values(array_filter($feedItems,fn($i)=>in_array(($i['type']??''),['cross_project_conflict','cross_research_found','cross_research_opportunity'],true)));p19(count($crossFeed)>=1,'Cognitive Feed surfaces Cross-Research observations');
$watch=proactive_watch_upsert($pdo,$owner,'project',$projectA,null,'all');proactive_preferences_set($pdo,$owner,'mentions',true);$sync=proactive_intelligence_sync($pdo,$owner,$feed);$q=$pdo->prepare("SELECT context_json FROM notifications WHERE user_id=? AND notification_type='research_proactive' ORDER BY id DESC LIMIT 50");$q->execute([$owner['id']]);$crossNotification=false;foreach($q->fetchAll(PDO::FETCH_COLUMN) as $json){$j=json_decode((string)$json,true)?:[];if(in_array(($j['observation_type']??''),['cross_project_conflict','cross_research_found','cross_research_opportunity'],true)){$crossNotification=true;break;}}p19($crossNotification,'existing Stage 17 project watch can deliver Cross-Research observations');

$automation=research_automation_create($pdo,$owner,['title'=>'Weekly Related Research Review','project_id'=>$projectA,'workflow_type'=>'cross_research_review','trigger_type'=>'schedule','cadence'=>'weekly','timezone_name'=>'America/Phoenix','run_time_local'=>'09:00','weekday'=>1]);p19(($automation['workflow_type']??'')==='cross_research_review','Stage 18 supports Cross-Research Review automation');
$result=research_automation_execute($pdo,[],['automation_id'=>$automation['id'],'user_id'=>$owner['id'],'trigger_type'=>'manual']);p19($result['status']==='completed'&&$result['ai_run']===null&&$result['proposals']===0&&str_contains($result['output'],'Cross-Research review'),'Cross-Research automation is deterministic, read-only, and uses no AI run or Research proposal');

$pdo->prepare("UPDATE sources SET moderation_status='restricted' WHERE id=?")->execute([$sourceId]);$restricted=cross_research_suggestions($pdo,$owner,null,200,false);$restrictedTypes=array_column($restricted,'type');p19(!in_array('shared_source',$restrictedTypes,true)&&!in_array('shared_annotation',$restrictedTypes,true)&&!in_array('evidence_label_conflict',$restrictedTypes,true)&&!in_array('evidence_reuse',$restrictedTypes,true),'restricted Source suppresses source/annotation/evidence Cross-Research signals for non-admin users');
p19(cross_research_link_access($pdo,$owner,(string)$link['public_id'])===null,'accepted object link is hidden if its Source later becomes restricted');
$pdo->prepare("UPDATE sources SET moderation_status='visible' WHERE id=?")->execute([$sourceId]);

$pdo->prepare('DELETE FROM team_members WHERE team_id=? AND user_id=?')->execute([$teamId,$collab['id']]);p19(count(cross_research_suggestions($pdo,$collab,null,200,false))===0,'revoked Team membership immediately removes cross-project suggestion access');p19(count(cross_research_links($pdo,$collab,null,50))===0,'revoked Team membership exposes no accepted Cross-Research link data');
$outsiderJson=json_encode(cross_research_suggestions($pdo,$outsider,null,200,false),JSON_UNESCAPED_SLASHES);p19(!str_contains($outsiderJson,$projectA)&&!str_contains($outsiderJson,$projectB)&&!str_contains($outsiderJson,$sourcePublic),'outsider receives no project, Source, Claim, Entity, or evidence identity leakage');

$runtime=file_get_contents($root.'/app/cross-research.php');p19(!str_contains($runtime,'agent_action_confirm_execute(')&&!str_contains($runtime,'agent_action_execute_capability('),'Cross-Research runtime has no direct Research execution path');
echo "Phase 19 Cross-Research Intelligence MariaDB suite passed.\n";
