<?php
declare(strict_types=1);
$root=dirname(__DIR__);$fail=[];
$read=function(string $p)use($root,&$fail): string{$f=$root.'/'.$p;if(!is_file($f)){$fail[]='Missing '.$p;return '';}return (string)file_get_contents($f);};
$need=function(string $p,string $n,string $m)use($read,&$fail): void{$c=$read($p);if($c!==''&&!str_contains($c,$n))$fail[]=$m;};
$avoid=function(string $p,string $n,string $m)use($read,&$fail): void{$c=$read($p);if($c!==''&&str_contains($c,$n))$fail[]=$m;};

$need('app/bootstrap.php',"'/unified-activity.php'","Bootstrap must load the canonical unified activity runtime.");
$need('app/bootstrap.php',"'/universal-object-detail.php'","Bootstrap must load the universal object detail adapter.");
$need('app/shell.php','data-notification-drawer-open','Header notification control must open the slideout.');
$need('app/shell.php','data-notification-drawer','Shell must render a notification/activity slideout.');
$need('app/shell.php','data-notification-tab="notifications"','Slideout must include Notifications tab.');
$need('app/shell.php','data-notification-tab="activity"','Slideout must include Activity tab.');
$need('app/shell.php','app_shell_object_detail_drawer','Shell must render the universal object drawer.');
$need('app/shell.php','data-object-tab="overview"','Object drawer must include Overview.');
$need('app/shell.php','data-object-tab="activity"','Object drawer must include Activity.');
$need('app/shell.php','data-object-tab="files"','Object drawer must include Files.');
$need('app/shell.php','data-object-tab="people"','Object drawer must include People.');
$need('app/shell.php','data-object-tab="links"','Object drawer must include Links.');
$need('app/shell.php','data-object-tab="agent"','Object drawer must include Agent.');
$need('app/shell.php','/assets/js/shell-drawers.js?v=74.5','Shell must load Section 5 drawer behavior.');
$need('app/shell.php','/assets/css/shell-drawers.css?v=74.6','Shell must load Section 5 drawer styling.');
$avoid('app/shell.php','appHeaderNotificationDropdown','Legacy notification dropdown markup must be removed.');
$need('assets/js/shell-drawers.js','/api/activity.php?limit=60','Activity tab must reuse the canonical activity API.');
$need('assets/js/shell-drawers.js','/api/object-detail.php?type=','Object drawer must use the permission-aware detail API.');
$need('assets/js/shell-drawers.js',"searchParams.set('drawer_type'","Object drawer must preserve deep-link state.");
$need('assets/js/shell-drawers.js','data-object-detail-type','Search/notification/activity results must be routable to the drawer.');
$need('assets/js/shell-drawers.js','document.body.appendChild(node)','Drawers and backdrops must portal outside the sticky header stacking context.');
$need('assets/css/shell-drawers.css','position:fixed','Slideouts must be fixed viewport surfaces.');
$need('assets/css/shell-drawers.css','height:100dvh','Slideouts must own the visible viewport.');
$need('assets/css/shell-drawers.css','overflow-x:clip!important','Authenticated shell must suppress document-level horizontal overflow from off-canvas drawers.');
$need('assets/css/shell-drawers.css','max-width:100vw','Drawers must never exceed the viewport width.');
$need('assets/css/shell-drawers.css','transform:translate3d(100%,0,0)','Closed drawers must translate fully off-canvas without adding layout width.');
$need('assets/css/shell-drawers.css','box-sizing:border-box','Drawer borders must remain inside the viewport width calculation.');
$need('assets/css/shell-drawers.css','@media(max-width:640px)','Drawers must have a mobile layout.');
$need('app/universal-object-detail.php','research_object_access($pdo,$viewer,$type,$publicId)','Object detail must revalidate canonical access.');
$need('app/universal-object-detail.php','research_object_descriptor','Object detail must use canonical descriptors.');
$need('app/universal-object-detail.php','unified_activity_collect','Object detail Activity must reuse canonical unified activity.');
$need('app/universal-object-detail.php','research_object_links','Object detail Links must reuse the Section 3 link ledger.');
$need('app/universal-object-detail.php','research_workspace_objects','Object detail Files must reuse canonical workspace objects.');
$need('api/object-detail.php','require_api_user($pdo)','Object detail API must require authentication.');
$need('api/object-detail.php',"rate_limit_api_or_429(\$pdo,'universal-object-detail'","Object detail API must be rate limited.");
$avoid('app/universal-object-detail.php','CREATE TABLE','Object detail must not create a second persistence layer.');
$avoid('app/universal-object-detail.php','INSERT INTO','Object detail must remain presentation/read-only except canonical recent-touch.');
if($fail){fwrite(STDERR,implode("\n",array_unique($fail))."\n");exit(1);}echo "Phase 74 Section 5 universal object + notification/activity drawer contract passed.\n";
