<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=(string)getenv('DB_DSN');$dbUser=(string)getenv('DB_USER');$dbPass=(string)getenv('DB_PASS');if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
require_once $root.'/app/installer.php';require_once $root.'/app/functions.php';require_once $root.'/app/data-attribution.php';require_once $root.'/app/data-datasets.php';require_once $root.'/app/ai.php';require_once $root.'/app/data-evaluations.php';require_once $root.'/app/data-model-registry.php';require_once $root.'/app/data-training.php';
function p41(bool $v,string $m): void {if(!$v)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}
p41(data_training_ready($pdo),'Phase 41 Training Registry schema is available');

$run='p41'.substr(bin2hex(random_bytes(7)),0,12);$pub=fn(string $p)=>$p.'-'.$run.'-'.substr(bin2hex(random_bytes(4)),0,8);
$makeUser=function(string $name,string $role='user')use($pdo,$run,$pub): array{$username=substr(strtolower($name).'_'.$run,0,48);$public=$pub('u');$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,password_hash,status,role) VALUES(?,?,?,?,?,'active',?)")->execute([$public,$username,$name,$username.'@example.test',password_hash('phase41-test',PASSWORD_DEFAULT),$role]);return ['id'=>(int)$pdo->lastInsertId(),'public_id'=>$public,'username'=>$username,'display_name'=>$name,'role'=>$role];};
$admin=$makeUser('TrainingAdmin','admin');$contributor=$makeUser('TrainingContributor');$outsider=$makeUser('TrainingOutsider');

$sourcePublic=$pub('source');$url='https://'.$run.'.example.test/training';$pdo->prepare("INSERT INTO sources(public_id,source_type,canonical_url,canonical_url_hash,domain,title,status) VALUES(?,'article',?,?,?,?, 'current')")->execute([$sourcePublic,$url,hash('sha256',$url),$run.'.example.test','Training source']);$sourceId=(int)$pdo->lastInsertId();
$sourceText='Training source text '.$run;$pdo->prepare('INSERT INTO source_versions(source_id,version_number,final_url,title,extracted_text,content_hash,target_content_hash) VALUES(?,1,?,?,?,?,?)')->execute([$sourceId,$url,'Training source',$sourceText,hash('sha256',$sourceText),hash('sha256','target '.$run)]);$sourceVersionId=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE sources SET current_version_id=? WHERE id=?')->execute([$sourceVersionId,$sourceId]);
$pdo->prepare("INSERT INTO captures(public_id,source_id,source_version_id,user_id,capture_type,selected_text) VALUES(?,?,?,?, 'text',?)")->execute([$pub('cap'),$sourceId,$sourceVersionId,$contributor['id'],'training passage '.$run]);$captureId=(int)$pdo->lastInsertId();
$annotationPublic=$pub('ann');$comment='Phoenix renewable project remains active '.$run;$pdo->prepare("INSERT INTO annotations(public_id,user_id,source_id,source_version_id,capture_id,text_commentary,visibility,status) VALUES(?,?,?,?,?,?,'public','published')")->execute([$annotationPublic,$contributor['id'],$sourceId,$sourceVersionId,$captureId,$comment]);
data_attribution_capture_object($pdo,(int)$contributor['id'],'annotation',$annotationPublic);
data_contributor_preferences_update($pdo,$contributor,['allow_shared_retrieval'=>1,'allow_evaluation'=>1,'allow_training'=>1,'allow_commercial_training'=>0,'attribution_required'=>0]);
data_corpus_refresh_object($pdo,'annotation',$annotationPublic);
$q=$pdo->prepare("SELECT * FROM data_corpus_items WHERE source_object_type='annotation' AND source_object_public_id=? ORDER BY id DESC LIMIT 1");$q->execute([$annotationPublic]);$corpus=$q->fetch();if(!$corpus)throw new RuntimeException('Phase 41 fixture corpus item missing.');
$corpusType='phase41_train_'.$run;$metadata=json_decode((string)($corpus['metadata_json']??''),true);if(!is_array($metadata))$metadata=[];$metadata['training_example']=['messages'=>[['role'=>'system','content'=>'Answer using verified project status.'],['role'=>'user','content'=>'What is the Phoenix renewable project status?'],['role'=>'assistant','content'=>'The Phoenix renewable project remains active.']]];
$pdo->prepare("UPDATE data_corpus_items SET corpus_type=?,metadata_json=?,training_eligible=1,commercial_training_eligible=0,attribution_required=0,eligibility_reason='phase41_fixture',invalidated_at=NULL WHERE id=?")->execute([$corpusType,data_attribution_encode($metadata),$corpus['id']]);

$dataset=data_dataset_create($pdo,$admin,['name'=>'Phase41 Training '.$run,'purpose'=>'training','corpus_types'=>$corpusType,'max_items'=>100]);$dataset=data_dataset_freeze($pdo,$admin,$dataset['public_id']);p41($dataset['purpose']==='training'&&(int)$dataset['item_count']===1,'frozen internal-training dataset contains the explicit supervised example');

$providerPublic=$pub('provider');$pdo->prepare("INSERT INTO ai_providers(public_id,label,provider_type,api_base_url,api_key_ciphertext,enabled) VALUES(?,?,'openai_compatible','http://127.0.0.1:9',NULL,1)")->execute([$providerPublic,'Phase41 Provider']);$providerId=(int)$pdo->lastInsertId();
$baseModelPublic=$pub('model');$pdo->prepare("INSERT INTO ai_models(public_id,provider_id,model_name,display_name,enabled,admin_enabled,pro_enabled,max_output_tokens) VALUES(?,?,?,'Phase41 Base Runtime',1,1,0,2048)")->execute([$baseModelPublic,$providerId,'phase41-base-'.$run]);$baseRuntimeId=(int)$pdo->lastInsertId();
$registry=data_model_registry_create($pdo,$admin,['name'=>'Phase41 Model Family '.$run,'description'=>'Training lifecycle fixture']);
$base=data_model_version_create($pdo,$admin,$registry['public_id'],['version_label'=>'base-v1','origin'=>'external_hosted','ai_model_id'=>$baseRuntimeId,'architecture'=>'fixture hosted model','intended_use'=>'Phase 41 base','required_model_runs'=>1,'required_human_reviews'=>1,'minimum_human_pass_rate'=>0.5,'require_integrity'=>1]);
$gate=['pass'=>true,'policy'=>$base['gate_policy'],'policy_hash'=>$base['gate_policy_hash'],'checks'=>['fixture'=>['pass'=>true]],'evidence'=>['fixture'=>'approved base'], 'evaluated_at'=>gmdate('c')];data_model_receipt_create($pdo,$admin,$base,'candidate','approved',null,$gate,'Phase 41 approved base fixture');$pdo->prepare("UPDATE data_model_versions SET status='approved',status_changed_at=NOW() WHERE id=?")->execute([$base['id']]);$base=data_model_version_get($pdo,$base['public_id']);$baseApproval=data_model_latest_approval_receipt($pdo,$base);
p41($base['status']==='approved'&&$baseApproval&&data_model_receipt_integrity($baseApproval,$base)['ok'],'training base has an integrity-valid Phase 40 approval receipt');

$badBase=data_model_version_create($pdo,$admin,$registry['public_id'],['version_label'=>'bad-base','origin'=>'external_hosted','ai_model_id'=>$baseRuntimeId]);$pdo->prepare("UPDATE data_model_versions SET status='approved' WHERE id=?")->execute([$badBase['id']]);
$missingReceipt=false;try{data_training_job_create($pdo,$admin,['dataset_id'=>$dataset['id'],'base_model_version_id'=>$badBase['id'],'output_registry_id'=>$registry['id'],'output_version_label'=>'should-not-create','executor_type'=>'manual','use_class'=>'internal_training']);}catch(RuntimeException $e){$missingReceipt=str_contains($e->getMessage(),'approval receipt');}p41($missingReceipt,'a forged approved status without a Phase 40 approval receipt cannot become a training base');

$routeBefore=(int)($pdo->query('SELECT admin_default_model_id FROM ai_settings WHERE id=1')->fetchColumn()?:0);$genericJobsBefore=(int)$pdo->query('SELECT COUNT(*) FROM ai_jobs')->fetchColumn();
$manual=data_training_job_create($pdo,$admin,['dataset_id'=>$dataset['id'],'base_model_version_id'=>$base['id'],'output_registry_id'=>$registry['id'],'output_version_label'=>'manual-ft-'.$run,'executor_type'=>'manual','use_class'=>'internal_training','n_epochs'=>'auto','batch_size'=>'auto','learning_rate_multiplier'=>'auto','max_attempts'=>3]);
$pre=data_training_preflight($pdo,$manual);p41($pre['pass']&&$pre['package']['valid_examples']===1&&$pre['package']['invalid_examples']===0,'manual training draft passes explicit-example preflight');
$manual=data_training_queue($pdo,$admin,$manual['public_id']);p41($manual['status']==='queued'&&!empty($manual['job_hash'])&&!empty($manual['package_hash']),'queue freezes training configuration, rights, dataset, base-model and package hashes');
p41($manual['base_approval_receipt_hash']===$baseApproval['receipt_hash'],'queued training job snapshots the exact Phase 40 approval receipt that authorized its base model');
p41(!empty($manual['runtime_snapshot_hash'])&&($manual['runtime_snapshot']['training_runtime_version']??'')==='phase41-v1','queued training job snapshots the Phase 41/app runtime identity');
p41(data_training_job_integrity($pdo,$manual)['ok'],'queued training job passes tamper-evident job integrity');
$pkg=data_training_export_package($pdo,$admin,$manual['public_id']);p41($pkg['examples']===1&&hash('sha256',$pkg['content'])===$manual['package_hash']&&str_contains($pkg['content'],'Phoenix renewable project remains active'),'exported JSONL exactly matches the queued package hash');
$processed=data_training_process_next($pdo,[]);p41($processed&&$processed['public_id']===$manual['public_id']&&$processed['status']==='prepared','manual worker prepares package without submitting it to a provider');

$artifactHash=hash('sha256','manual-artifact-'.$run);$manual=data_training_manual_complete($pdo,$admin,$manual['public_id'],['artifact_ref'=>'registry://phase41/'.$run,'artifact_hash'=>$artifactHash,'output_model_name'=>'manual-output-'.$run,'actual_cost_usd'=>'12.345678']);
$output=data_model_version_get($pdo,(string)$manual['output_model_version_public_id']);p41($manual['status']==='succeeded'&&$output&&$output['status']==='experimental'&&$output['origin']==='annotated_trained','manual completion creates only an experimental Phase 40 model version');
p41($output['artifact_hash']===$artifactHash&&!empty($manual['completion_hash']),'manual output preserves artifact and completion hashes');
p41(data_training_completion_integrity($pdo,$manual)['ok'],'manual training completion passes independent completion-integrity verification');
p41((int)($pdo->query('SELECT admin_default_model_id FROM ai_settings WHERE id=1')->fetchColumn()?:0)===$routeBefore,'manual training completion never changes production AI routing');

$manualRuntimePublic=$pub('model');$pdo->prepare("INSERT INTO ai_models(public_id,provider_id,model_name,display_name,enabled,admin_enabled,pro_enabled,max_output_tokens) VALUES(?,?,?,'Manual Trained Runtime',1,1,0,2048)")->execute([$manualRuntimePublic,$providerId,'manual-trained-'.$run]);$manualRuntimeId=(int)$pdo->lastInsertId();$oldVersionHash=$output['version_hash'];$output=data_model_version_bind_runtime($pdo,$admin,$output['public_id'],$manualRuntimeId);p41((int)$output['ai_model_id']===$manualRuntimeId&&$output['version_hash']!==$oldVersionHash&&$output['status']==='experimental','manual training output can bind a runtime model only while experimental');

$providerJob=data_training_job_create($pdo,$admin,['dataset_id'=>$dataset['id'],'base_model_version_id'=>$base['id'],'output_registry_id'=>$registry['id'],'output_version_label'=>'provider-ft-'.$run,'executor_type'=>'provider_api','use_class'=>'internal_training','external_provider_acknowledged'=>1,'cost_rate_usd_per_million_tokens'=>'8.000000']);
$providerJob=data_training_queue($pdo,$admin,$providerJob['public_id']);$providerSnapshot=$providerJob['provider_snapshot'];p41($providerJob['status']==='queued'&&($providerSnapshot['provider_public_id']??'')===$providerPublic&&($providerSnapshot['runtime_model_public_id']??'')===$baseModelPublic,'provider training queue snapshots provider and runtime model identity without secrets');
p41(!array_key_exists('api_key_ciphertext',(array)$providerSnapshot)&&!array_key_exists('api_key',(array)$providerSnapshot),'provider snapshot never contains API credentials');
$pdo->prepare("UPDATE data_training_jobs SET status='running',provider_job_id=?,provider_status='running',started_at=NOW() WHERE id=?")->execute(['ftjob-'.$run,$providerJob['id']]);$providerJob=data_training_job_get($pdo,$providerJob['public_id']);
$providerResult=['status'=>'succeeded','fine_tuned_model'=>'ft:phase41:'.$run,'result_files'=>['file-results-'.$run],'trained_tokens'=>250000];$transient=data_training_job_create($pdo,$admin,['dataset_id'=>$dataset['id'],'base_model_version_id'=>$base['id'],'output_registry_id'=>$registry['id'],'output_version_label'=>'transient-'.$run,'executor_type'=>'provider_api','use_class'=>'internal_training','external_provider_acknowledged'=>1]);$transient=data_training_queue($pdo,$admin,$transient['public_id']);$pdo->prepare("UPDATE data_training_jobs SET status='running',provider_job_id=?,provider_status='running',started_at=NOW() WHERE id=?")->execute(['transient-job-'.$run,$transient['id']]);$transient=data_training_job_get($pdo,$transient['public_id']);$preserved=data_training_handle_worker_exception($pdo,$transient,null,'running','temporary provider outage');$transient=data_training_job_get($pdo,$transient['public_id']);p41($preserved&&$transient['status']==='running'&&str_contains((string)$transient['last_error'],'temporary provider outage'),'transient provider polling errors preserve running state for a later retry');$pdo->prepare("UPDATE data_training_jobs SET status='cancelled',cancelled_at=NOW(),completed_at=NOW() WHERE id=?")->execute([$transient['id']]);

$providerDone=data_training_finalize_provider_success($pdo,[],$providerJob,$providerResult);$providerOutput=data_model_version_get($pdo,(string)$providerDone['output_model_version_public_id']);
p41($providerDone['status']==='succeeded'&&$providerOutput&&$providerOutput['status']==='experimental'&&$providerOutput['origin']==='annotated_trained','provider success registers an experimental model version without auto-promotion');
p41(data_training_completion_integrity($pdo,$providerDone)['ok'],'provider training completion passes independent completion-integrity verification');
p41((int)$providerOutput['ai_model_id']>0&&$providerDone['trained_tokens']==250000&&abs((float)$providerDone['estimated_cost_usd']-2.0)<0.000001,'provider completion records runtime model, trained tokens, and configured cost estimate');
p41((int)($pdo->query('SELECT admin_default_model_id FROM ai_settings WHERE id=1')->fetchColumn()?:0)===$routeBefore,'provider training completion never changes AI task routing');

$collision=data_training_job_create($pdo,$admin,['dataset_id'=>$dataset['id'],'base_model_version_id'=>$base['id'],'output_registry_id'=>$registry['id'],'output_version_label'=>'collision-'.$run,'executor_type'=>'provider_api','use_class'=>'internal_training','external_provider_acknowledged'=>1]);$collision=data_training_queue($pdo,$admin,$collision['public_id']);data_model_version_create($pdo,$admin,$registry['public_id'],['version_label'=>'collision-'.$run,'origin'=>'imported_artifact','architecture'=>'collision fixture','artifact_ref'=>'fixture://collision','artifact_hash'=>hash('sha256','collision-'.$run)]);$pdo->prepare("UPDATE data_training_jobs SET status='running',provider_job_id=?,provider_status='running',started_at=NOW() WHERE id=?")->execute(['collision-job-'.$run,$collision['id']]);$collision=data_training_job_get($pdo,$collision['public_id']);$collisionDone=data_training_finalize_provider_success($pdo,[],$collision,['status'=>'succeeded','fine_tuned_model'=>'ft:collision:'.$run,'result_files'=>[],'trained_tokens'=>100]);p41($collisionDone['status']==='blocked'&&$collisionDone['provider_status']==='succeeded'&&str_contains((string)$collisionDone['last_error'],'output registration failed'),'provider success with an output-registration conflict is blocked without retraining the provider job');

$noAck=data_training_job_create($pdo,$admin,['dataset_id'=>$dataset['id'],'base_model_version_id'=>$base['id'],'output_registry_id'=>$registry['id'],'output_version_label'=>'no-ack-'.$run,'executor_type'=>'provider_api','use_class'=>'internal_training']);$noAckPre=data_training_preflight($pdo,$noAck);p41(!$noAckPre['pass']&&!$noAckPre['checks']['provider_ack'],'provider API training cannot queue without explicit external/provider transfer acknowledgement');

$commercialMismatch=false;try{data_training_job_create($pdo,$admin,['dataset_id'=>$dataset['id'],'base_model_version_id'=>$base['id'],'output_registry_id'=>$registry['id'],'output_version_label'=>'commercial-mismatch-'.$run,'executor_type'=>'manual','use_class'=>'commercial_training']);}catch(RuntimeException $e){$commercialMismatch=str_contains($e->getMessage(),'commercial_training');}p41($commercialMismatch,'commercial training intent cannot use an internal-training-only frozen dataset');

$attrType='phase41_attr_'.$run;$attrText='attribution required example '.$run;$attrMeta=['training_example'=>['input'=>'Question '.$run,'output'=>'Answer '.$run]];$pdo->prepare("INSERT INTO data_corpus_items(public_id,source_object_type,source_object_public_id,source_object_version,contributor_user_id,corpus_type,normalized_text,metadata_json,content_hash,provenance_hash,shared_retrieval_eligible,evaluation_eligible,training_eligible,commercial_training_eligible,attribution_required,eligibility_reason) VALUES(?,?,?,?,?,?,?,?,?,?,0,0,1,0,1,'phase41_attr_fixture')")->execute([$pub('corpus'),'fixture',$pub('obj'),'1',$contributor['id'],$attrType,$attrText,data_attribution_encode($attrMeta),hash('sha256',$attrText),hash('sha256','prov-'.$attrText)]);
$attrDataset=data_dataset_create($pdo,$admin,['name'=>'Attribution Block '.$run,'purpose'=>'training','corpus_types'=>$attrType,'max_items'=>10]);$attrDataset=data_dataset_freeze($pdo,$admin,$attrDataset['public_id']);$attrJob=data_training_job_create($pdo,$admin,['dataset_id'=>$attrDataset['id'],'base_model_version_id'=>$base['id'],'output_registry_id'=>$registry['id'],'output_version_label'=>'attr-block-'.$run,'executor_type'=>'manual','use_class'=>'internal_training']);$attrPre=data_training_preflight($pdo,$attrJob);p41(!$attrPre['pass']&&$attrPre['package']['attribution_blocked_items']===1&&!$attrPre['checks']['attribution_compatible'],'weight training blocks frozen items that still require per-contribution attribution');

$invalidType='phase41_invalid_'.$run;$invalidText='unlabeled training text '.$run;$pdo->prepare("INSERT INTO data_corpus_items(public_id,source_object_type,source_object_public_id,source_object_version,contributor_user_id,corpus_type,normalized_text,metadata_json,content_hash,provenance_hash,shared_retrieval_eligible,evaluation_eligible,training_eligible,commercial_training_eligible,attribution_required,eligibility_reason) VALUES(?,?,?,?,?,?,?,?,?,?,0,0,1,0,0,'phase41_invalid_fixture')")->execute([$pub('corpus'),'fixture',$pub('obj'),'1',$contributor['id'],$invalidType,$invalidText,data_attribution_encode(['note'=>'no supervision']),hash('sha256',$invalidText),hash('sha256','prov-'.$invalidText)]);
$invalidDataset=data_dataset_create($pdo,$admin,['name'=>'Invalid Example '.$run,'purpose'=>'training','corpus_types'=>$invalidType,'max_items'=>10]);$invalidDataset=data_dataset_freeze($pdo,$admin,$invalidDataset['public_id']);$invalidJob=data_training_job_create($pdo,$admin,['dataset_id'=>$invalidDataset['id'],'base_model_version_id'=>$base['id'],'output_registry_id'=>$registry['id'],'output_version_label'=>'invalid-example-'.$run,'executor_type'=>'manual','use_class'=>'internal_training']);$invalidPre=data_training_preflight($pdo,$invalidJob);p41(!$invalidPre['pass']&&$invalidPre['package']['invalid_examples']===1&&!$invalidPre['checks']['examples_valid'],'ordinary corpus text is not silently converted into synthetic supervised labels');

$tamper=data_training_job_create($pdo,$admin,['dataset_id'=>$dataset['id'],'base_model_version_id'=>$base['id'],'output_registry_id'=>$registry['id'],'output_version_label'=>'tamper-'.$run,'executor_type'=>'manual','use_class'=>'internal_training']);$tamper=data_training_queue($pdo,$admin,$tamper['public_id']);$pdo->prepare("UPDATE data_training_jobs SET config_json=? WHERE id=?")->execute(['{"tampered":true}',$tamper['id']]);$tamper=data_training_job_get($pdo,$tamper['public_id']);p41(!data_training_job_integrity($pdo,$tamper)['ok'],'direct queued training-config tampering invalidates job integrity');$blocked=data_training_process_next($pdo,[]);p41($blocked&&$blocked['public_id']===$tamper['public_id']&&$blocked['status']==='blocked','worker blocks a queued job whose immutable snapshot fails integrity');

$retry=data_training_job_create($pdo,$admin,['dataset_id'=>$dataset['id'],'base_model_version_id'=>$base['id'],'output_registry_id'=>$registry['id'],'output_version_label'=>'retry-'.$run,'executor_type'=>'manual','use_class'=>'internal_training','max_attempts'=>2]);$retry=data_training_queue($pdo,$admin,$retry['public_id']);$pdo->prepare("UPDATE data_training_jobs SET status='failed',attempt_count=1,last_error='fixture failure',completed_at=NOW() WHERE id=?")->execute([$retry['id']]);$retry=data_training_retry($pdo,$admin,$retry['public_id']);p41($retry['status']==='queued'&&(int)$retry['attempt_count']===1,'failed job can be requeued without erasing prior attempt count or immutable job hash');
$pdo->prepare("UPDATE data_training_jobs SET status='failed',attempt_count=max_attempts WHERE id=?")->execute([$retry['id']]);$exhausted=false;try{data_training_retry($pdo,$admin,$retry['public_id']);}catch(RuntimeException $e){$exhausted=str_contains($e->getMessage(),'exhausted');}p41($exhausted,'retry is blocked after configured attempts are exhausted');

$cancel=data_training_job_create($pdo,$admin,['dataset_id'=>$dataset['id'],'base_model_version_id'=>$base['id'],'output_registry_id'=>$registry['id'],'output_version_label'=>'cancel-'.$run,'executor_type'=>'manual','use_class'=>'internal_training']);$cancel=data_training_queue($pdo,$admin,$cancel['public_id']);$cancel=data_training_request_cancel($pdo,$admin,$cancel['public_id']);p41($cancel['status']==='cancelled'&&!empty($cancel['cancelled_at']),'queued/prepared work can be cancelled before provider submission');

$receiptBase=data_model_version_create($pdo,$admin,$registry['public_id'],['version_label'=>'receipt-base-'.$run,'origin'=>'external_hosted','ai_model_id'=>$baseRuntimeId,'architecture'=>'receipt fixture','intended_use'=>'receipt snapshot fixture']);
$receiptGate=['pass'=>true,'policy'=>$receiptBase['gate_policy'],'policy_hash'=>$receiptBase['gate_policy_hash'],'checks'=>['fixture'=>['pass'=>true]],'evidence'=>['fixture'=>'receipt base'],'evaluated_at'=>gmdate('c')];data_model_receipt_create($pdo,$admin,$receiptBase,'candidate','approved',null,$receiptGate,'Receipt base approval');$pdo->prepare("UPDATE data_model_versions SET status='approved',status_changed_at=NOW() WHERE id=?")->execute([$receiptBase['id']]);$receiptBase=data_model_version_get($pdo,$receiptBase['public_id']);
$receiptJob=data_training_job_create($pdo,$admin,['dataset_id'=>$dataset['id'],'base_model_version_id'=>$receiptBase['id'],'output_registry_id'=>$registry['id'],'output_version_label'=>'receipt-check-'.$run,'executor_type'=>'manual','use_class'=>'internal_training']);$receiptJob=data_training_queue($pdo,$admin,$receiptJob['public_id']);$receiptApproval=data_model_latest_approval_receipt($pdo,$receiptBase);p41($receiptJob['base_approval_receipt_hash']===$receiptApproval['receipt_hash'],'job lineage binds to one specific base approval receipt');
$pdo->prepare('UPDATE data_model_promotion_receipts SET note=? WHERE id=?')->execute(['tampered base approval '.$run,$receiptApproval['id']]);$receiptJob=data_training_job_get($pdo,$receiptJob['public_id']);$receiptStatus=data_training_current_use_status($pdo,$receiptJob);p41(!$receiptStatus['usable']&&!$receiptStatus['base_approval_receipt']['ok'],'tampering the exact base approval receipt blocks later training use');
$receiptJob=data_training_request_cancel($pdo,$admin,$receiptJob['public_id']);

$rightsJob=data_training_job_create($pdo,$admin,['dataset_id'=>$dataset['id'],'base_model_version_id'=>$base['id'],'output_registry_id'=>$registry['id'],'output_version_label'=>'rights-'.$run,'executor_type'=>'manual','use_class'=>'internal_training']);$rightsJob=data_training_queue($pdo,$admin,$rightsJob['public_id']);
data_contributor_preferences_update($pdo,$contributor,['allow_shared_retrieval'=>1,'allow_evaluation'=>1,'allow_training'=>0,'allow_commercial_training'=>0,'attribution_required'=>0]);
$exportBlocked=false;try{data_training_export_package($pdo,$admin,$rightsJob['public_id']);}catch(RuntimeException $e){$exportBlocked=str_contains($e->getMessage(),'rights or integrity');}p41($exportBlocked,'later contributor training opt-out blocks export of an already queued training package');
$rightsProcessed=data_training_process_next($pdo,[]);p41($rightsProcessed&&$rightsProcessed['public_id']===$rightsJob['public_id']&&$rightsProcessed['status']==='blocked','worker blocks queued training when contributor rights change before execution');

$pdo->prepare('UPDATE data_training_jobs SET output_artifact_ref=? WHERE id=?')->execute(['tampered://artifact/'.$run,$manual['id']]);$manualTampered=data_training_job_get($pdo,$manual['public_id']);$completionTamper=data_training_completion_integrity($pdo,$manualTampered);p41(!$completionTamper['ok']&&$completionTamper['reason']==='completion_integrity_failure','direct completed-artifact tampering invalidates training completion integrity');
$genericJobsAfter=(int)$pdo->query('SELECT COUNT(*) FROM ai_jobs')->fetchColumn();p41($genericJobsAfter===$genericJobsBefore,'training registry uses its own governed job tables rather than dispatching fine-tuning through generic AI jobs');
$nonAdmin=false;try{data_training_job_create($pdo,$outsider,['dataset_id'=>$dataset['id'],'base_model_version_id'=>$base['id'],'output_registry_id'=>$registry['id'],'output_version_label'=>'unauthorized-'.$run,'executor_type'=>'manual','use_class'=>'internal_training']);}catch(RuntimeException $e){$nonAdmin=str_contains($e->getMessage(),'Administrator');}p41($nonAdmin,'Training Registry lifecycle is administrator-only');

$events=data_training_events($pdo,(int)$manual['id']);$types=array_column($events,'event_type');foreach(['job_created','job_queued','package_exported','package_prepared','manual_training_completed'] as $needed)p41(in_array($needed,$types,true),'manual training audit history includes '.$needed);
$summary=data_training_summary($pdo);p41($summary['jobs']>=8&&$summary['succeeded']>=2&&$summary['blocked']>=2,'Training Registry summary exposes controlled lifecycle state');

echo "Phase 41 Training Job Registry & Controlled Fine-Tuning MariaDB suite passed.\n";
