<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=getenv('DB_DSN')?:'';$dbUser=getenv('DB_USER')?:'root';$dbPass=getenv('DB_PASS')?:'';if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
foreach(['installer','storage','functions','shell','access','notifications','rate-limit','jobs','ai','ai-access','source-integrity','annotation-intelligence','research-workspace','conversations','agent-actions','agent-chat','cognitive-feed','research-entities','proactive-intelligence','research-automation'] as $lib)require_once $root.'/app/'.$lib.'.php';
function p18(bool $ok,string $message): void {if(!$ok)throw new RuntimeException('FAIL: '.$message);echo "PASS: $message\n";}
$run='p18'.substr(bin2hex(random_bytes(6)),0,10);$pub=fn(string $p)=>$p.'-'.$run.'-'.substr(bin2hex(random_bytes(3)),0,6);
$makeUser=function(string $name,string $plan='pro')use($pdo,$run,$pub): array{$username=substr(strtolower($name).'_'.$run,0,48);$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,email_verified_at,status,role,plan_tier,live_presence_mode) VALUES(?,?,?,?,NOW(),'active','user',?,'cloaked')")->execute([$pub('u'),$username,$name,$username.'@example.test',$plan]);$id=(int)$pdo->lastInsertId();$pdo->prepare('INSERT IGNORE INTO user_preferences(user_id) VALUES(?)')->execute([$id]);$q=$pdo->prepare('SELECT * FROM users WHERE id=?');$q->execute([$id]);return $q->fetch();};
$owner=$makeUser('AutomationOwner');$member=$makeUser('AutomationMember');p18(research_automation_ready($pdo),'Phase 18 schema is available');
$projectPublic=$pub('project');$pdo->prepare("INSERT INTO research_projects(public_id,owner_user_id,title,description,status) VALUES(?,?,?,?,'active')")->execute([$projectPublic,$owner['id'],'Automation Research','Stage 18 project']);$projectId=(int)$pdo->lastInsertId();
$url='https://example.com/'.$run.'/source';$sourcePublic=$pub('source');$pdo->prepare("INSERT INTO sources(public_id,source_type,canonical_url,canonical_url_hash,domain,title,status,monitoring_enabled,moderation_status) VALUES(?,'webpage',?,?,?,'Automation Source','current',1,'visible')")->execute([$sourcePublic,$url,hash('sha256',$url),'example.com']);$sourceId=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO project_sources(project_id,source_id,added_by_user_id) VALUES(?,?,?)')->execute([$projectId,$sourceId,$owner['id']]);

$next=research_automation_next_run('daily','America/Phoenix','09:00',null,new DateTimeImmutable('2026-09-20 16:00:00',new DateTimeZone('UTC')));p18($next==='2026-09-21 16:00:00','daily scheduling honors the configured timezone without server-local drift');
$weekly=research_automation_next_run('weekly','America/Phoenix','09:00',1,new DateTimeImmutable('2026-09-20 16:00:00',new DateTimeZone('UTC')));p18($weekly==='2026-09-21 16:00:00','weekly scheduling resolves weekday in the configured timezone');

$brief=research_automation_create($pdo,$owner,['title'=>'Daily Briefing','project_id'=>$projectPublic,'workflow_type'=>'briefing','trigger_type'=>'schedule','cadence'=>'daily','timezone_name'=>'America/Phoenix','run_time_local'=>'09:00','weekday'=>1,'prompt'=>'Brief the current Research state.']);p18($brief['workflow_type']==='briefing'&&$brief['status']==='active','read-only Agent briefing automation can be created');
$review=research_automation_create($pdo,$owner,['title'=>'Weekly Review','project_id'=>$projectPublic,'workflow_type'=>'review','trigger_type'=>'schedule','cadence'=>'weekly','timezone_name'=>'America/Phoenix','run_time_local'=>'10:00','weekday'=>1,'prompt'=>'Review evidence gaps and prepare useful proposals.']);p18($review['workflow_type']==='review','proposal-only review automation can be created');
$refresh=research_automation_create($pdo,$owner,['title'=>'Refresh Sources','project_id'=>$projectPublic,'workflow_type'=>'source_refresh','trigger_type'=>'schedule','cadence'=>'hourly','timezone_name'=>'UTC']);p18($refresh['workflow_type']==='source_refresh','source refresh automation can be created');
p18((int)$pdo->query("SELECT COUNT(*) FROM agent_action_proposals WHERE proposed_by_user_id=".(int)$owner['id'])->fetchColumn()===0,'creating or scheduling a review never executes or pre-creates Research writes');

$pdo->prepare("UPDATE research_automations SET next_run_at=DATE_SUB(NOW(),INTERVAL 1 MINUTE) WHERE id=?")->execute([$refresh['id']]);$queued=research_automation_enqueue_due($pdo,10);p18($queued>=1,'due scheduler queues an eligible automation run');$queuedAgain=research_automation_enqueue_due($pdo,10);p18($queuedAgain===0,'due scheduler advances next_run_at and avoids duplicate enqueue');
$manual=research_automation_enqueue_manual($pdo,$owner,(string)$refresh['public_id']);p18($manual!=='','manual run can be queued independently of schedule');
$claimed=research_automation_claim($pdo);p18($claimed!==null&&$claimed['status']==='queued','automation worker atomically claims a queued run with a lease');
$automation=research_automation_access($pdo,$owner,(string)$refresh['public_id']);$result=research_automation_execute($pdo,[],$claimed);p18($result['status']==='completed'&&str_contains($result['output'],'Queued'),'source refresh execution uses the existing Source Monitor without an AI call');research_automation_complete_run($pdo,$owner,$automation,$claimed,$result);
p18((int)$pdo->query("SELECT COUNT(*) FROM source_monitor_jobs WHERE source_id=".(int)$sourceId." AND status='queued'")->fetchColumn()===1,'source refresh produces one bounded source-monitor job');
$q=$pdo->prepare("SELECT COUNT(*) FROM notifications WHERE user_id=? AND notification_type='research_automation_completed'");$q->execute([$owner['id']]);p18((int)$q->fetchColumn()>=1,'completed automation uses the existing Research notification center');

$missingWatchRejected=false;try{research_automation_create($pdo,$owner,['title'=>'Invalid Watch Trigger','project_id'=>$projectPublic,'workflow_type'=>'briefing','trigger_type'=>'watch_alert','watch_id'=>'','timezone_name'=>'UTC']);}catch(InvalidArgumentException $e){$missingWatchRejected=true;}p18($missingWatchRejected,'watch-triggered automation requires an active explicit Research watch');
$watch=proactive_watch_upsert($pdo,$owner,'project',$projectPublic);$watchAuto=research_automation_create($pdo,$owner,['title'=>'Watch Review','project_id'=>$projectPublic,'workflow_type'=>'briefing','trigger_type'=>'watch_alert','watch_id'=>$watch['public_id'],'timezone_name'=>'UTC']);
$notificationPublic=$pub('notification');$context=json_encode(['watch_public_id'=>$watch['public_id'],'observation_key'=>hash('sha256','p18-watch')],JSON_UNESCAPED_SLASHES);$pdo->prepare("INSERT INTO notifications(public_id,user_id,notification_type,category,dedupe_key,group_key,object_type,object_public_id,body,context_json) VALUES(?,?,'research_proactive','research',?,?, 'cognitive_alert',?,'Watch changed',?)")->execute([$notificationPublic,$owner['id'],'p18-watch:'.$run,'p18-watch-group:'.$run,hash('sha256','p18-watch'),$context]);
p18(research_automation_enqueue_watch_alerts($pdo,20)===1,'watch-triggered workflow queues from a Stage 17 proactive alert');p18(research_automation_enqueue_watch_alerts($pdo,20)===0,'watch trigger cursor prevents duplicate runs for the same proactive alert');

p18(research_automation_set_status($pdo,$owner,(string)$refresh['public_id'],'paused'),'source-refresh automation can be paused');$pausedManualResult=research_automation_execute($pdo,[],['automation_id'=>$refresh['id'],'user_id'=>$owner['id'],'trigger_type'=>'manual']);p18($pausedManualResult['status']==='completed','explicit Run now remains valid while recurring triggers are paused');p18(research_automation_set_status($pdo,$owner,(string)$refresh['public_id'],'active'),'paused source-refresh automation can be resumed');
p18(research_automation_set_status($pdo,$owner,(string)$brief['public_id'],'paused'),'automation can be paused');$paused=research_automation_access($pdo,$owner,(string)$brief['public_id']);p18($paused['status']==='paused'&&$paused['next_run_at']===null,'pause clears the next scheduled run');p18(research_automation_set_status($pdo,$owner,(string)$brief['public_id'],'active'),'automation can be resumed');$resumed=research_automation_access($pdo,$owner,(string)$brief['public_id']);p18($resumed['status']==='active'&&!empty($resumed['next_run_at']),'resume computes a fresh next run');

$teamPublic=$pub('team');$pdo->prepare('INSERT INTO teams(public_id,owner_user_id,name) VALUES(?,?,?)')->execute([$teamPublic,$owner['id'],'Automation Team']);$teamId=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO team_members(team_id,user_id,role) VALUES(?,?,'researcher')")->execute([$teamId,$member['id']]);$teamProjectPublic=$pub('team-project');$pdo->prepare("INSERT INTO research_projects(public_id,owner_user_id,team_id,title,description,status) VALUES(?,?,?,?,?,'active')")->execute([$teamProjectPublic,$owner['id'],$teamId,'Team Automation Research','Permission test']);
$memberAuto=research_automation_create($pdo,$member,['title'=>'Member Brief','project_id'=>$teamProjectPublic,'workflow_type'=>'briefing','trigger_type'=>'schedule','cadence'=>'manual','timezone_name'=>'UTC']);p18(research_automation_access($pdo,$member,(string)$memberAuto['public_id'])!==null,'team researcher can automate an accessible project');
$pdo->prepare('DELETE FROM team_members WHERE team_id=? AND user_id=?')->execute([$teamId,$member['id']]);p18(research_automation_access($pdo,$member,(string)$memberAuto['public_id'])===null,'revoked project access immediately hides the stored automation');

$failAuto=research_automation_create($pdo,$owner,['title'=>'Failure Pause Test','project_id'=>$projectPublic,'workflow_type'=>'source_refresh','trigger_type'=>'schedule','cadence'=>'manual','timezone_name'=>'UTC']);
for($i=1;$i<=3;$i++){$runPublic=$pub('failrun');$token=bin2hex(random_bytes(16));$trigger=hash('sha256','p18-fail-'.$run.'-'.$i);$pdo->prepare("INSERT INTO research_automation_runs(public_id,automation_id,user_id,project_id,trigger_type,trigger_key,status,attempts,claim_token,lease_expires_at,started_at) VALUES(?,?,?,?, 'manual',?,'processing',3,?,DATE_ADD(NOW(),INTERVAL 10 MINUTE),NOW())")->execute([$runPublic,$failAuto['id'],$owner['id'],$projectId,$trigger,$token]);$rid=(int)$pdo->lastInsertId();research_automation_fail_run($pdo,$owner,research_automation_access($pdo,$owner,(string)$failAuto['public_id']),['id'=>$rid,'public_id'=>$runPublic,'claim_token'=>$token,'attempts'=>3],new RuntimeException('Synthetic terminal automation failure '.$i));}
$failedAuto=research_automation_access($pdo,$owner,(string)$failAuto['public_id']);p18($failedAuto['status']==='paused'&&(int)$failedAuto['failure_count']===3,'three terminal automation failures auto-pause the workflow');
$runtime=file_get_contents($root.'/app/research-automation.php');p18(!str_contains($runtime,'agent_action_confirm_execute('),'automation runtime contains no path that can auto-confirm Stage 15 proposals');p18(!str_contains($runtime,'agent_action_execute_capability('),'automation runtime contains no direct Research capability execution path');
echo "Phase 18 Research Automation MariaDB suite passed.\n";
