<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=getenv('DB_DSN')?:'';$dbUser=getenv('DB_USER')?:'root';$dbPass=getenv('DB_PASS')?:'';if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
foreach(['installer','storage','jobs','concurrency','functions','shell','access','notifications','rate-limit','ai','ai-access','source-integrity','annotation-intelligence','research-workspace','research-knowledge','research-intelligence','research-reports','conversations','agent-actions','agent-chat','cognitive-feed','research-entities','proactive-intelligence','research-automation','cross-research','research-outcomes','research-reviews','change-impact','research-portfolio','living-research','research-network','research-provenance','research-verification'] as $lib)require_once $root.'/app/'.$lib.'.php';
function p27(bool $ok,string $m): void {if(!$ok)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}
$run='p27'.substr(bin2hex(random_bytes(6)),0,10);$pub=fn(string $p)=>$p.'-'.$run.'-'.substr(bin2hex(random_bytes(3)),0,6);
$makeUser=function(string $name)use($pdo,$run,$pub): array{$username=substr(strtolower($name).'_'.$run,0,48);$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,email_verified_at,status,role,plan_tier,live_presence_mode) VALUES(?,?,?,?,NOW(),'active','user','pro','cloaked')")->execute([$pub('u'),$username,$name,$username.'@example.test']);$id=(int)$pdo->lastInsertId();$pdo->prepare('INSERT IGNORE INTO user_preferences(user_id) VALUES(?)')->execute([$id]);$q=$pdo->prepare('SELECT * FROM users WHERE id=?');$q->execute([$id]);return $q->fetch();};
$owner=$makeUser('VerificationOwner');$member=$makeUser('VerificationMember');$outsider=$makeUser('VerificationOutsider');p27(research_verification_ready($pdo),'Phase 27 schema is available');

$teamPublic=$pub('team');$pdo->prepare('INSERT INTO teams(public_id,owner_user_id,name) VALUES(?,?,?)')->execute([$teamPublic,$owner['id'],'Verification Team']);$teamId=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO team_members(team_id,user_id,role) VALUES(?,?,'owner'),(?,?,'researcher')")->execute([$teamId,$owner['id'],$teamId,$member['id']]);
$projectPublic=$pub('project');$pdo->prepare("INSERT INTO research_projects(public_id,owner_user_id,team_id,title,description,status) VALUES(?,?,?,?,?,'active')")->execute([$projectPublic,$owner['id'],$teamId,'Verification Research','Evidence-state fixture']);$projectId=(int)$pdo->lastInsertId();

$makeSource=function(string $domain,string $label)use($pdo,$owner,$projectId,$run,$pub): array{$url='https://'.$domain.'/'.$run.'/'.$label;$sourcePublic=$pub('source');$pdo->prepare("INSERT INTO sources(public_id,source_type,canonical_url,canonical_url_hash,domain,title,status,monitoring_enabled,moderation_status) VALUES(?,'article',?,?,?,?,'current',1,'visible')")->execute([$sourcePublic,$url,hash('sha256',$url),$domain,$label]);$sourceId=(int)$pdo->lastInsertId();$text='Evidence '.$label.' '.$run;$pdo->prepare("INSERT INTO source_versions(source_id,version_number,final_url,title,extracted_text,content_hash,target_content_hash,captured_at) VALUES(?,1,?,?,?,?,?,NOW())")->execute([$sourceId,$url,$label,$text,hash('sha256',$text),hash('sha256','target-'.$label)]);$versionId=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE sources SET current_version_id=? WHERE id=?')->execute([$versionId,$sourceId]);$pdo->prepare('INSERT INTO project_sources(project_id,source_id,added_by_user_id) VALUES(?,?,?)')->execute([$projectId,$sourceId,$owner['id']]);return ['id'=>$sourceId,'public_id'=>$sourcePublic,'version_id'=>$versionId,'url'=>$url,'domain'=>$domain];};
$a=$makeSource('alpha.example','Alpha Evidence');$b=$makeSource('beta.example','Beta Evidence');$c=$makeSource('gamma.example','Gamma Counterevidence');

$claimPublic=$pub('claim');$pdo->prepare("INSERT INTO research_claims(public_id,project_id,created_by_user_id,statement,claim_type,status) VALUES(?,?,?,'The evidence indicates the test proposition.','factual','supported')")->execute([$claimPublic,$projectId,$owner['id']]);$claimId=(int)$pdo->lastInsertId();
$addEvidence=function(array $s,string $rel)use($pdo,$owner,$claimId,$pub){$pdo->prepare("INSERT INTO claim_evidence(public_id,claim_id,added_by_user_id,evidence_type,source_version_id,relationship,note) VALUES(?,?,?,'source_version',?,?,?)")->execute([$pub('evidence'),$claimId,$owner['id'],$s['version_id'],$rel,'Phase 27 fixture']);};

$addEvidence($a,'primary');$claim=research_claim_access($pdo,$owner,$claimPublic);$state=research_verification_claim_state($pdo,$owner,$claim);p27($state['evidence_state']==='support_only'&&$state['corroboration']==='single_source'&&$state['freshness']==='current','single current supporting Source is represented without overclaiming corroboration');

$addEvidence($b,'supports');$state=research_verification_claim_state($pdo,$owner,$claim);p27($state['corroboration']==='independent_domains'&&$state['counts']['support_domains']===2,'support from two domains is surfaced as independent-domain corroboration');

$addEvidence($c,'contradicts');$state=research_verification_claim_state($pdo,$owner,$claim);p27($state['evidence_state']==='contested'&&$state['severity']==='high'&&$state['agent_use']==='contested_evidence','support plus contradiction becomes contested evidence and Agent caution');

$review=research_verification_record($pdo,$owner,'claim',$claimPublic,'reviewed_current','I reviewed the exact evidence state.');p27(!empty($review['public_id']),'human verification creates an append-only review event');
$state=research_verification_claim_state($pdo,$owner,$claim);p27($state['human_review']['state']==='reviewed_current','current human review is visible separately from evidence state');

$pdo->prepare("UPDATE research_claims SET statement='The evidence indicates the revised test proposition.' WHERE id=?")->execute([$claimId]);$claim=research_claim_access($pdo,$owner,$claimPublic);$state=research_verification_claim_state($pdo,$owner,$claim);p27($state['human_review']['state']==='stale'&&count($state['human_review']['stale'])===1,'editing the reviewed Claim makes the prior human review stale without rewriting it');

research_verification_record($pdo,$member,'claim',$claimPublic,'needs_review','A collaborator requests another evidence pass.');$state=research_verification_claim_state($pdo,$owner,$claim);p27($state['human_review']['state']==='needs_review'&&$state['attention'],'current collaborator review can request attention without deleting prior history');

$text2='Updated Alpha evidence '.$run;$pdo->prepare("INSERT INTO source_versions(source_id,version_number,final_url,title,extracted_text,content_hash,target_content_hash,captured_at) VALUES(?,2,?,'Alpha Evidence',?,?,?,NOW())")->execute([$a['id'],$a['url'],$text2,hash('sha256',$text2),hash('sha256','target-alpha-2')]);$a2=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE sources SET current_version_id=? WHERE id=?')->execute([$a2,$a['id']]);
$state=research_verification_claim_state($pdo,$owner,$claim);p27(in_array($state['freshness'],['mixed','stale'],true)&&in_array('evidence_version_superseded',$state['flags'],true),'superseded Source Version makes evidence freshness explicit');

$ctx=research_verification_context($pdo,$owner,$projectPublic,12);p27(str_contains($ctx['text'],'not a truth score')&&str_contains($ctx['text'],'Do not silently promote')&&str_contains($ctx['text'],$claimPublic),'Agent verification context preserves uncertainty and references the Claim');
$items=[];research_verification_cognitive_observations($pdo,$owner,$items,10);$cards=array_values(array_filter($items,fn($i)=>($i['type']??'')==='research_verification'));p27(count($cards)>=1&&($cards[0]['section']??'')==='needs_attention','Cognitive Feed surfaces evidence verification attention');

$outsiderSubject=research_verification_subject($pdo,$outsider,'claim',$claimPublic);p27($outsiderSubject===null,'outsider cannot access private Team Claim verification state');
$events=research_verification_project_events($pdo,$member,$projectPublic,50);p27(count($events)>=2,'current Team researcher can inspect project verification history');
$pdo->prepare('DELETE FROM team_members WHERE team_id=? AND user_id=?')->execute([$teamId,$member['id']]);p27(research_verification_project_events($pdo,$member,$projectPublic,50)===[],'Team revocation immediately removes verification history access');

$snapshotClaim=['id'=>$claimPublic,'evidence'=>[['relationship'=>'primary','source_id'=>$a['public_id']],['relationship'=>'supports','source_id'=>$b['public_id']],['relationship'=>'contradicts','source_id'=>$c['public_id']]]];$snapshotSources=[['id'=>$a['public_id'],'domain'=>'alpha.example'],['id'=>$b['public_id'],'domain'=>'beta.example'],['id'=>$c['public_id'],'domain'=>'gamma.example']];$publicSignal=research_verification_snapshot_claim_signal($snapshotClaim,$snapshotSources);p27($publicSignal['evidence_state']==='contested'&&$publicSignal['corroboration']==='independent_domains'&&$publicSignal['freshness']==='snapshot_pinned','public Report evidence signal is derived only from immutable snapshot data');

$runtime=file_get_contents($root.'/app/research-verification.php');p27(!str_contains($runtime,'trust_score')&&!str_contains($runtime,'ai_run(')&&!str_contains($runtime,'agent_action_confirm_execute('),'verification runtime has no opaque trust score, AI ranker, or direct Agent execution path');
echo "Phase 27 Research Trust, Review & Verification MariaDB suite passed.\n";
