<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=(string)getenv('DB_DSN');$dbUser=(string)getenv('DB_USER');$dbPass=(string)getenv('DB_PASS');if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
require_once $root.'/app/storage.php';require_once $root.'/app/functions.php';require_once $root.'/app/access.php';require_once $root.'/app/notifications.php';require_once $root.'/app/source-integrity.php';require_once $root.'/app/feed.php';require_once $root.'/app/search.php';
function p10(bool $v,string $m): void {if(!$v)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}
function p10has(array $rows,string $id): bool {return in_array($id,array_map(fn($r)=>(string)($r['public_id']??''),$rows),true);}
$run='p10'.substr(bin2hex(random_bytes(6)),0,10);$pub=fn(string $p)=>$p.'-'.$run.'-'.substr(bin2hex(random_bytes(3)),0,6);
$makeUser=function(string $name,string $role='user')use($pdo,$run,$pub): array{$username=substr(strtolower($name).'_'.$run,0,48);$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,email_verified_at,status,role,live_presence_mode) VALUES(?,?,?,?,NOW(),'active',?,'visible')")->execute([$pub('u'),$username,$name,$username.'@example.test',$role]);$id=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO user_preferences(user_id) VALUES(?)')->execute([$id]);$q=$pdo->prepare('SELECT * FROM users WHERE id=?');$q->execute([$id]);return $q->fetch();};
$owner=$makeUser('Owner');$teamUser=$makeUser('TeamUser');$projectUser=$makeUser('ProjectUser');$outsider=$makeUser('Outsider');$admin=$makeUser('Admin','admin');

$teamPublic=$pub('team');$pdo->prepare('INSERT INTO teams(public_id,owner_user_id,name) VALUES(?,?,?)')->execute([$teamPublic,$owner['id'],'Search Team']);$teamId=(int)$pdo->lastInsertId();foreach([[$owner,'owner'],[$teamUser,'viewer']] as [$u,$role])$pdo->prepare('INSERT INTO team_members(team_id,user_id,role) VALUES(?,?,?)')->execute([$teamId,$u['id'],$role]);
$projectTeamPublic=$pub('team');$pdo->prepare('INSERT INTO teams(public_id,owner_user_id,name) VALUES(?,?,?)')->execute([$projectTeamPublic,$owner['id'],'Research Team']);$projectTeamId=(int)$pdo->lastInsertId();foreach([[$owner,'owner'],[$projectUser,'researcher']] as [$u,$role])$pdo->prepare('INSERT INTO team_members(team_id,user_id,role) VALUES(?,?,?)')->execute([$projectTeamId,$u['id'],$role]);
$projectPublic=$pub('project');$pdo->prepare('INSERT INTO research_projects(public_id,owner_user_id,team_id,title,description) VALUES(?,?,?,?,?)')->execute([$projectPublic,$owner['id'],$projectTeamId,'Nebula Research','Project searching nebula evidence']);$projectId=(int)$pdo->lastInsertId();

$makeSource=function(string $slug,string $title)use($pdo,$run): array{$s=ensure_source($pdo,'https://'.$run.'.example.test/'.$slug,$title);$pdo->prepare('INSERT INTO source_versions(source_id,version_number,final_url,title,extracted_text,content_hash) VALUES(?,1,?,?,?,?)')->execute([$s['id'],$s['canonical_url'],$title,$title.' body evidence',hash('sha256',$slug)]);$v=(int)$pdo->lastInsertId();$pdo->prepare("UPDATE sources SET current_version_id=?,status='current' WHERE id=?")->execute([$v,$s['id']]);$s['version_id']=$v;return $s;};
$publicSource=$makeSource('public','Nebula Orchard Source');$privateSource=$makeSource('private','Private Delta Source');$teamSource=$makeSource('team','Team Echo Source');$projectSource=$makeSource('project','Project Foxtrot Source');$relatedSource=$makeSource('related','Nebula Related Source');

$makeAnn=function(array $source,array $user,string $visibility,string $text,?int $team=null,string $captureType='text')use($pdo,$pub): array{$cap=$pub('cap');$pdo->prepare('INSERT INTO captures(public_id,source_id,source_version_id,user_id,capture_type,selected_text) VALUES(?,?,?,?,?,?)')->execute([$cap,$source['id'],$source['version_id'],$user['id'],$captureType,$text]);$capId=(int)$pdo->lastInsertId();$id=$pub('ann');$pdo->prepare("INSERT INTO annotations(public_id,user_id,source_id,source_version_id,capture_id,text_commentary,visibility,team_id,status,published_at) VALUES(?,?,?,?,?,?,?,?, 'published',NOW())")->execute([$id,$user['id'],$source['id'],$source['version_id'],$capId,$text,$visibility,$team]);return ['id'=>(int)$pdo->lastInsertId(),'public_id'=>$id];};
$annPublic=$makeAnn($publicSource,$owner,'public','nebula orchard public evidence');
$annPrivate=$makeAnn($privateSource,$owner,'private','private delta secret evidence');
$annTeam=$makeAnn($teamSource,$owner,'team','team echo secret evidence',$teamId);
$annProject=$makeAnn($projectSource,$owner,'private','project foxtrot secret evidence');
$annRelated=$makeAnn($relatedSource,$owner,'public','nebula orchard related evidence');
$pdo->prepare('INSERT INTO project_annotations(project_id,annotation_id,added_by_user_id) VALUES(?,?,?)')->execute([$projectId,$annProject['id'],$owner['id']]);$pdo->prepare('INSERT INTO project_sources(project_id,source_id,added_by_user_id) VALUES(?,?,?)')->execute([$projectId,$projectSource['id'],$owner['id']]);

$anon=search_unified($pdo,'nebula orchard',null,[]);
p10(p10has($anon['annotations'],$annPublic['public_id'])&&p10has($anon['annotations'],$annRelated['public_id']),'anonymous search returns matching public annotations');
p10(!p10has(search_unified($pdo,'private delta secret',null,[])['annotations'],$annPrivate['public_id']),'anonymous search excludes private annotation');
p10(p10has(search_unified($pdo,'private delta secret',$owner,[])['annotations'],$annPrivate['public_id']),'owner search finds own private annotation');
p10(!p10has(search_unified($pdo,'private delta secret',$admin,[])['annotations'],$annPrivate['public_id']),'global admin search does not surface another user private annotation');
p10(p10has(search_unified($pdo,'team echo secret',$teamUser,[])['annotations'],$annTeam['public_id']),'current Team member finds Team annotation');
p10(!p10has(search_unified($pdo,'team echo secret',$outsider,[])['annotations'],$annTeam['public_id']),'outsider cannot search Team annotation');
p10(p10has(search_unified($pdo,'project foxtrot secret',$projectUser,[])['annotations'],$annProject['public_id']),'Research member finds explicitly shared private annotation');
p10(!p10has(search_unified($pdo,'project foxtrot secret',$outsider,[])['annotations'],$annProject['public_id']),'outsider cannot search Research-shared private annotation');

$pdo->prepare('INSERT INTO blocks(blocker_user_id,blocked_user_id) VALUES(?,?)')->execute([$outsider['id'],$owner['id']]);p10(!p10has(search_unified($pdo,'nebula orchard',$outsider,[])['annotations'],$annPublic['public_id']),'block relationship filters search results');$pdo->prepare('DELETE FROM blocks WHERE blocker_user_id=? AND blocked_user_id=?')->execute([$outsider['id'],$owner['id']]);

$filtered=search_unified($pdo,'nebula orchard',$owner,['source'=>$publicSource['public_id']]);p10(p10has($filtered['annotations'],$annPublic['public_id'])&&!p10has($filtered['annotations'],$annRelated['public_id']),'current-source filter scopes annotation search');
$projectFiltered=search_unified($pdo,'project foxtrot',$projectUser,['project'=>$projectPublic]);p10(p10has($projectFiltered['annotations'],$annProject['public_id']),'Research-project filter scopes search');

$pdo->prepare("UPDATE sources SET moderation_status='restricted' WHERE id=?")->execute([$publicSource['id']]);p10(!p10has(search_unified($pdo,'nebula orchard',$owner,[])['sources'],$publicSource['public_id'])&&!p10has(search_unified($pdo,'nebula orchard',$owner,[])['annotations'],$annPublic['public_id']),'restricted source and its annotation disappear from Search');$pdo->prepare("UPDATE sources SET moderation_status='visible' WHERE id=?")->execute([$publicSource['id']]);

$privateSaved=search_saved_create($pdo,$owner,'Private search','private delta secret',[],'private',null,false);p10(search_saved_access($pdo,$owner,$privateSaved['public_id'])!==null,'owner can access private saved search');p10(search_saved_access($pdo,$admin,$privateSaved['public_id'])===null,'private saved search is owner-only even for global admin');
$teamSaved=search_saved_create($pdo,$owner,'Team search','team echo secret',[],'team',$teamPublic,false);p10(search_saved_access($pdo,$teamUser,$teamSaved['public_id'])!==null,'current Team member can access Team saved search');$pdo->prepare('DELETE FROM team_members WHERE team_id=? AND user_id=?')->execute([$teamId,$teamUser['id']]);p10(search_saved_access($pdo,$teamUser,$teamSaved['public_id'])===null,'revoked Team membership immediately removes saved-search access');
$projectSaved=search_saved_create($pdo,$owner,'Project search','project foxtrot secret',['project'=>$projectPublic],'project',$projectPublic,false);p10(search_saved_access($pdo,$projectUser,$projectSaved['public_id'])!==null,'Research member can access project saved search');$pdo->prepare('DELETE FROM team_members WHERE team_id=? AND user_id=?')->execute([$projectTeamId,$projectUser['id']]);p10(search_saved_access($pdo,$projectUser,$projectSaved['public_id'])===null,'revoked Research membership immediately removes saved-search access');

$alertSaved=search_saved_create($pdo,$outsider,'Nebula alerts','alert comet unique',[],'private',null,true);$q=$pdo->prepare("SELECT COUNT(*) FROM notifications WHERE user_id=? AND notification_type='saved_search_match'");$q->execute([$outsider['id']]);$beforeAlerts=(int)$q->fetchColumn();search_saved_alert_worker($pdo,100);$q->execute([$outsider['id']]);p10((int)$q->fetchColumn()===$beforeAlerts,'enabling saved-search alerts does not notify existing matches');
$alertSource=$makeSource('alert','Alert Comet Source');$alertAnn=$makeAnn($alertSource,$owner,'public','alert comet unique newly published');search_saved_alert_worker($pdo,100);$q->execute([$outsider['id']]);$afterAlerts=(int)$q->fetchColumn();p10($afterAlerts===$beforeAlerts+1,'saved-search worker notifies one new accessible match');search_saved_alert_worker($pdo,100);$q->execute([$outsider['id']]);p10((int)$q->fetchColumn()===$afterAlerts,'saved-search alert rerun is deduplicated');

search_unified($pdo,'nebula orchard',$outsider,['sort'=>'newest']);$recent=search_recent($pdo,$outsider,10);p10(in_array('nebula orchard',array_column($recent,'query_text'),true),'signed-in search records recent query');

$reportProjectPublic=$pub('project');$pdo->prepare('INSERT INTO research_projects(public_id,owner_user_id,title,description) VALUES(?,?,?,?)')->execute([$reportProjectPublic,$owner['id'],'Public Entity Project','Entity report project']);$reportProjectId=(int)$pdo->lastInsertId();
$reportPublic=$pub('report');$pdo->prepare("INSERT INTO research_reports(public_id,project_id,created_by_user_id,title,summary,visibility,status,published_at) VALUES(?,?,?,?,?,'public','published',NOW())")->execute([$reportPublic,$reportProjectId,$owner['id'],'Orbital Citrus Report','Report about Orbital Citrus']);$reportId=(int)$pdo->lastInsertId();
$snapshot=['title'=>'Orbital Citrus Report','entities'=>[['id'=>$pub('rent'),'type'=>'topic','name'=>'Orbital Citrus','description'=>'A public discovery topic','mentions'=>[['type'=>'annotation','annotation_id'=>$annPublic['public_id'],'source_id'=>$publicSource['public_id']]]]],'claims'=>[],'findings'=>[]];
$json=json_encode($snapshot,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);$pdo->prepare("INSERT INTO research_report_versions(public_id,report_id,version_number,published_by_user_id,visibility,title,summary,snapshot_json,snapshot_hash) VALUES(?,?,1,?,'public',?,?,?,?)")->execute([$pub('rv'),$reportId,$owner['id'],'Orbital Citrus Report','Report about Orbital Citrus',$json,hash('sha256',$json)]);$rv=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE research_reports SET current_version_id=? WHERE id=?')->execute([$rv,$reportId]);
p10(search_sync_public_report_entities($pdo,$reportPublic)>=1,'public Research report indexes confirmed entity/topic data');$entityResults=search_entity_results($pdo,'Orbital Citrus',null,null,20);$entity=array_values(array_filter($entityResults,fn($e)=>($e['canonical_name']??'')==='Orbital Citrus'&&($e['scope']??'')==='public'))[0]??null;p10($entity!==null,'public entity is discoverable by name');
$entityPage=search_discovery_entity($pdo,(string)$entity['public_id'],null);p10($entityPage!==null&&count($entityPage['mentions'])>=1,'public entity page exposes only access-checked mentions');
$pdo->prepare("UPDATE research_reports SET visibility='private' WHERE id=?")->execute([$reportId]);search_remove_public_report_entities($pdo,$reportPublic);$entityPage=search_discovery_entity($pdo,(string)$entity['public_id'],null);p10($entityPage!==null&&count($entityPage['mentions'])===0,'making report non-public removes all derived public mentions');

$relatedOut=search_related_sources($pdo,$publicSource['public_id'],$outsider,20);p10(p10has($relatedOut,$relatedSource['public_id']),'related-source discovery finds accessible shared-contributor source');p10(!p10has($relatedOut,$privateSource['public_id']),'related-source discovery does not leak private-only source');
$relatedAnn=search_related_annotations($pdo,$annPublic['public_id'],$outsider,20);p10(p10has($relatedAnn,$annRelated['public_id'])&&!p10has($relatedAnn,$annPrivate['public_id']),'related annotations respect visibility');

$pdo->prepare('INSERT INTO follows(follower_user_id,followed_user_id) VALUES(?,?)')->execute([$outsider['id'],$owner['id']]);$recs=search_recommendations($pdo,$outsider,20);p10(p10has($recs,$annPublic['public_id'])&&!p10has($recs,$annPrivate['public_id']),'personalized recommendations respect search visibility');

echo "Phase 10 Search & Discovery Intelligence MariaDB suite passed.\n";
