<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=(string)getenv('DB_DSN');$dbUser=(string)getenv('DB_USER');$dbPass=(string)getenv('DB_PASS');if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
foreach(['installer','storage','jobs','concurrency','functions','subscriptions','account-admin','account-membership','shell','access','notifications','rate-limit','ai','ai-access','source-integrity','annotation-intelligence','research-workspace','research-knowledge','research-intelligence','research-reports','conversations','agent-actions','agent-chat','cognitive-feed','research-entities','proactive-intelligence','research-automation','research-agent-workspace','research-agents','research-tasks','research-programs','research-missions','research-accounts','sponsored-research-campaigns','sponsored-research-participation','data-attribution','data-datasets','sponsored-research-submissions','sponsored-research-reviews','sponsored-research-finance','sponsored-research-knowledge'] as $lib)require_once $root.'/app/'.$lib.'.php';
function p80s7(bool $ok,string $m):void{if(!$ok)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}
$run='p80s7'.substr(bin2hex(random_bytes(5)),0,10);$pub=fn(string $p)=>$p.'-'.$run.'-'.substr(bin2hex(random_bytes(3)),0,6);
$make=function(string $name,string $role='user')use($pdo,$run,$pub):array{$u=substr(strtolower($name).'_'.$run,0,48);$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,email_verified_at,status,role,plan_tier,live_presence_mode) VALUES(?,?,?,?,NOW(),'active',?,'pro','cloaked')")->execute([$pub('u'),$u,$name,$u.'@example.test',$role]);$id=(int)$pdo->lastInsertId();$pdo->prepare('INSERT IGNORE INTO user_preferences(user_id) VALUES(?)')->execute([$id]);$q=$pdo->prepare('SELECT * FROM users WHERE id=?');$q->execute([$id]);return $q->fetch();};
$admin=$make('KnowledgeAdmin','admin');$sponsor=$make('KnowledgeSponsor');$r1=$make('KnowledgeResearcherOne');$r2=$make('KnowledgeResearcherTwo');
$pkg=(int)$pdo->query("SELECT id FROM subscription_packages WHERE slug='basic-user' LIMIT 1")->fetchColumn();
$pdo->prepare("INSERT INTO accounts(public_id,account_type,name,owner_user_id,personal_user_id,package_id,subscription_status,period_start,period_end,status) VALUES(?,'personal',?,?,?,?, 'active',CURRENT_DATE,DATE_ADD(CURRENT_DATE,INTERVAL 1 MONTH),'active')")->execute([$pub('acct'),'Knowledge Sponsor Account',(int)$sponsor['id'],(int)$sponsor['id'],$pkg]);$accountId=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO account_members(account_id,user_id,account_role) VALUES(?,?,'owner')")->execute([$accountId,(int)$sponsor['id']]);$q=$pdo->prepare('SELECT public_id FROM accounts WHERE id=?');$q->execute([$accountId]);$accountPublic=(string)$q->fetchColumn();
sponsor_account_apply($pdo,$sponsor,['organization_name'=>'Knowledge Sponsor']);research_account_admin_decide($pdo,$admin,(int)$sponsor['id'],'sponsor_account','approved','Approved sponsor.','organization');
foreach([$r1,$r2] as $r){research_account_apply($pdo,$r,['specialties'=>'research','languages'=>'English']);research_account_admin_decide($pdo,$admin,(int)$r['id'],'research_account','approved','Approved researcher.','identity');}
sponsored_research_finance_settings_update($pdo,$admin,0);
$campaign=sponsored_research_campaign_create($pdo,$sponsor,['account_id'=>$accountPublic,'title'=>'Knowledge Release Campaign','brief'=>'Build governed Sponsored Research Knowledge.','objective'=>'Validate explicit promotion and immutable releases.','questions'=>['What does the evidence support?'],'access_mode'=>'public','budget'=>'1000.00','eligibility'=>['min_verification'=>'identity'],'disclosures'=>['sponsorship_disclosure_required'=>false,'conflict_disclosure_required'=>false,'nda_required'=>false],'submission_deadline'=>'2030-12-31 23:59:00']);
$campaign=sponsored_research_campaign_set_status($pdo,$sponsor,(string)$campaign['public_id'],'open');sponsored_research_campaign_terms_publish($pdo,$sponsor,(string)$campaign['public_id'],'Accepted work may be explicitly promoted into the sponsor Knowledge Base. Training rights remain separate.','Knowledge terms.');
sponsored_research_finance_record_funding($pdo,$admin,(string)$campaign['public_id'],100000,'manual_admin','kb-funding-'.$run);

$submit=function(array $researcher,string $suffix)use($pdo,$campaign,$pub,$run):array{
 sponsored_research_campaign_join($pdo,$researcher,(string)$campaign['public_id'],['accept_terms'=>true]);
 $sourcePublic=$pub('source'.$suffix);$url='https://'.$run.'.example.test/'.$suffix;$pdo->prepare("INSERT INTO sources(public_id,source_type,canonical_url,canonical_url_hash,domain,title,status) VALUES(?,'article',?,?,?,?, 'current')")->execute([$sourcePublic,$url,hash('sha256',$url),$run.'.example.test','Knowledge Source '.$suffix]);$sourceId=(int)$pdo->lastInsertId();
 $txt='Knowledge evidence '.$suffix.' '.$run;$pdo->prepare('INSERT INTO source_versions(source_id,version_number,final_url,title,extracted_text,content_hash,target_content_hash) VALUES(?,1,?,?,?,?,?)')->execute([$sourceId,$url,'Knowledge Source '.$suffix,$txt,hash('sha256',$txt),hash('sha256','target '.$suffix.$run)]);$sv=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE sources SET current_version_id=? WHERE id=?')->execute([$sv,$sourceId]);
 $pdo->prepare("INSERT INTO source_rights(source_id,rights_class,retrieval_allowed,excerpt_storage_allowed,model_context_allowed,training_allowed,commercial_training_allowed,license_code,rights_holder,review_status,reviewed_by_user_id,reviewed_at) VALUES(?,'licensed',1,1,1,0,0,'SPONSORED-KB','Publisher','reviewed',?,NOW())")->execute([$sourceId,(int)$researcher['id']]);
 $pdo->prepare("INSERT INTO captures(public_id,source_id,source_version_id,user_id,capture_type,selected_text) VALUES(?,?,?,?, 'text',?)")->execute([$pub('cap'.$suffix),$sourceId,$sv,(int)$researcher['id'],'Selected evidence '.$suffix]);$cap=(int)$pdo->lastInsertId();
 $ann=$pub('ann'.$suffix);$pdo->prepare("INSERT INTO annotations(public_id,user_id,source_id,source_version_id,capture_id,text_commentary,visibility,status) VALUES(?,?,?,?,?,?,'private','draft')")->execute([$ann,(int)$researcher['id'],$sourceId,$sv,$cap,'Knowledge analysis '.$suffix.' '.$run]);
 $draft=sponsored_research_submission_draft($pdo,$researcher,(string)$campaign['public_id'],['title'=>'Knowledge submission '.$suffix,'summary'=>'Accepted knowledge candidate '.$suffix,'methodology'=>'Source review.','limitations'=>'Test scope.']);
 $sub=sponsored_research_submission_submit($pdo,$researcher,(string)$draft['public_id'],[['type'=>'annotation','public_id'=>$ann],['type'=>'source','public_id'=>$sourcePublic]]);
 return ['submission'=>$sub,'annotation'=>$ann,'source'=>$sourcePublic];
};
$a=$submit($r1,'one');sponsored_research_compensation_reserve($pdo,$sponsor,(string)$a['submission']['public_id'],30000);$case1=sponsored_research_review_open($pdo,$sponsor,(string)$a['submission']['public_id'],[]);$case1=sponsored_research_review_decide($pdo,$sponsor,(string)$case1['public_id'],'accepted','Accepted for Knowledge.');
$b=$submit($r2,'two');sponsored_research_compensation_reserve($pdo,$sponsor,(string)$b['submission']['public_id'],30000);$case2=sponsored_research_review_open($pdo,$sponsor,(string)$b['submission']['public_id'],[]);$case2=sponsored_research_review_decide($pdo,$sponsor,(string)$case2['public_id'],'accepted','Accepted correction candidate.');

$kb=sponsored_research_knowledge_base_create($pdo,$sponsor,(string)$campaign['public_id'],['name'=>'Campaign Canonical Knowledge']);p80s7($kb['status']==='draft'&&(int)$kb['current_release_number']===0,'Knowledge Base begins as a draft with no implicit promotion.');
$assets=sponsored_research_knowledge_promotable_assets($pdo,$sponsor,(string)$campaign['public_id']);$annAsset1=null;$srcAsset1=null;$annAsset2=null;foreach($assets as $x){if($x['asset_public_id']===$a['annotation'])$annAsset1=$x;if($x['asset_public_id']===$b['annotation'])$annAsset2=$x;}
$q=$pdo->prepare("SELECT a.* FROM sponsored_research_submission_assets a JOIN sponsored_research_submission_versions sv ON sv.id=a.submission_version_id JOIN sponsored_research_submissions s ON s.id=sv.submission_id WHERE s.public_id=? AND a.asset_type='source' LIMIT 1");$q->execute([(string)$a['submission']['public_id']]);$srcAsset1=$q->fetch();
p80s7($annAsset1!==null&&$annAsset2!==null,'Only accepted submission assets are exposed for explicit Knowledge promotion.');
$blockedSource=false;try{sponsored_research_knowledge_promote($pdo,$sponsor,(string)$kb['public_id'],(string)$srcAsset1['public_id']);}catch(RuntimeException $e){$blockedSource=true;}p80s7($blockedSource,'Sources remain evidence lineage and cannot become standalone authored Knowledge items.');

$item1=sponsored_research_knowledge_promote($pdo,$sponsor,(string)$kb['public_id'],(string)$annAsset1['public_id']);p80s7($item1['state']==='active'&&(int)$item1['future_use_allowed']===1,'Sponsor explicitly promotes accepted researcher work into an active Knowledge item.');
$q=$pdo->prepare("SELECT COUNT(*) FROM data_provenance_edges WHERE from_type='sponsored_submission_asset' AND from_public_id=? AND relationship='promoted_to' AND to_type='sponsored_knowledge_item' AND to_public_id=?");$q->execute([(string)$annAsset1['public_id'],(string)$item1['public_id']]);p80s7((int)$q->fetchColumn()===1,'Knowledge promotion preserves exact submission-asset provenance.');

$release1=sponsored_research_knowledge_release_create($pdo,$sponsor,(string)$kb['public_id'],'Initial governed release.');p80s7((int)$release1['release_number']===1&&strlen((string)$release1['manifest_hash'])===64,'Release 1 freezes an immutable manifest and hash.');
$status=sponsored_research_knowledge_release_current_use_status($pdo,(string)$release1['public_id']);p80s7($status['usable']===true,'Release 1 is usable while item state and Source rights remain current.');
$manifest1=(string)$release1['manifest_json'];

$q=$pdo->prepare("UPDATE source_rights sr JOIN sources s ON s.id=sr.source_id SET sr.retrieval_allowed=0 WHERE s.public_id=?");$q->execute([$a['source']]);$status=sponsored_research_knowledge_release_current_use_status($pdo,(string)$release1['public_id']);p80s7($status['usable']===false&&in_array('source_rights_block_future_use',$status['reasons'],true),'Later Source-rights revocation blocks future use of the old release without rewriting it.');
$q=$pdo->prepare("UPDATE source_rights sr JOIN sources s ON s.id=sr.source_id SET sr.retrieval_allowed=1,license_code='SPONSORED-KB-V2' WHERE s.public_id=?");$q->execute([$a['source']]);$status=sponsored_research_knowledge_release_current_use_status($pdo,(string)$release1['public_id']);p80s7($status['usable']===false&&in_array('source_rights_changed_since_release',$status['reasons'],true),'Rights/license drift invalidates the old release until a new release captures current rights.');
$release2=sponsored_research_knowledge_release_create($pdo,$sponsor,(string)$kb['public_id'],'Rights-refreshed release.');p80s7(sponsored_research_knowledge_release_current_use_status($pdo,(string)$release2['public_id'])['usable']===true,'A new immutable release captures the current Source-rights state.');

$item2=sponsored_research_knowledge_promote($pdo,$sponsor,(string)$kb['public_id'],(string)$annAsset2['public_id'],(string)$item1['public_id']);$old=sponsored_research_knowledge_item_get($pdo,(string)$item1['public_id']);p80s7($old['state']==='corrected'&&(int)$old['future_use_allowed']===0&&$item2['state']==='active','Correction creates a replacement item and marks the prior item corrected instead of editing history.');
p80s7((string)sponsored_research_knowledge_release_get($pdo,(string)$release1['public_id'])['manifest_json']===$manifest1,'Historical release 1 manifest remains byte-for-byte unchanged after correction.');
$release3=sponsored_research_knowledge_release_create($pdo,$sponsor,(string)$kb['public_id'],'Correction release.');$r3items=sponsored_research_knowledge_release_items($pdo,(int)$release3['id']);p80s7(count($r3items)===1&&$r3items[0]['item_public_id']===$item2['public_id'],'Correction release contains only the active replacement item.');

$revoked=sponsored_research_knowledge_item_revoke_rights($pdo,$r2,(string)$item2['public_id'],'Contributor withdraws future use permission.');p80s7($revoked['state']==='rights_revoked'&&(int)$revoked['future_use_allowed']===0,'Contributor can revoke future use of their own promoted Knowledge item.');
$status3=sponsored_research_knowledge_release_current_use_status($pdo,(string)$release3['public_id']);p80s7($status3['usable']===false&&in_array('knowledge_item_no_longer_eligible',$status3['reasons'],true),'Contributor rights revocation blocks future use of release 3 while preserving the release record.');
$q=$pdo->prepare('SELECT COUNT(*) FROM sponsored_research_knowledge_releases WHERE knowledge_base_id=?');$q->execute([(int)$kb['id']]);p80s7((int)$q->fetchColumn()===3,'All historical Knowledge Base releases remain retained.');
$q=$pdo->prepare("SELECT COUNT(*) FROM sponsored_research_knowledge_events WHERE knowledge_base_id=? AND event_type IN ('knowledge_item_promoted','knowledge_item_replacement_promoted','knowledge_item_corrected','knowledge_item_rights_revoked','knowledge_release_created')");$q->execute([(int)$kb['id']]);p80s7((int)$q->fetchColumn()>=7,'Knowledge governance events preserve promotion, correction, release and revocation history.');

echo "Phase 80 Section 7 Knowledge Base Versioning & Promotion database journey passed.\n";
