<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=(string)getenv('DB_DSN');$dbUser=(string)getenv('DB_USER');$dbPass=(string)getenv('DB_PASS');if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
foreach(['installer','storage','jobs','concurrency','functions','subscriptions','account-admin','account-membership','shell','access','notifications','rate-limit','ai','ai-access','source-integrity','annotation-intelligence','research-workspace','research-knowledge','research-intelligence','research-reports','conversations','agent-actions','agent-chat','cognitive-feed','research-entities','proactive-intelligence','research-automation','research-agent-workspace','research-agents','research-tasks','research-programs','research-missions','research-accounts','sponsored-research-campaigns','sponsored-research-participation','data-attribution','data-datasets','sponsored-research-finance','sponsored-research-projects','sponsored-research-project-compensation'] as $lib)require_once $root.'/app/'.$lib.'.php';
function ok9(bool $ok,string $m):void{if(!$ok)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}
$run='p80s9'.substr(bin2hex(random_bytes(5)),0,10);$pub=fn(string $p)=>$p.'-'.$run.'-'.substr(bin2hex(random_bytes(3)),0,6);
$make=function(string $name,string $role='user')use($pdo,$run,$pub):array{$u=substr(strtolower($name).'_'.$run,0,48);$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,email_verified_at,status,role,plan_tier,live_presence_mode) VALUES(?,?,?,?,NOW(),'active',?,'pro','cloaked')")->execute([$pub('u'),$u,$name,$u.'@example.test',$role]);$id=(int)$pdo->lastInsertId();$pdo->prepare('INSERT IGNORE INTO user_preferences(user_id) VALUES(?)')->execute([$id]);$q=$pdo->prepare('SELECT * FROM users WHERE id=?');$q->execute([$id]);return $q->fetch();};
$admin=$make('SponsoredAdmin','admin');$sponsor=$make('SponsoredSponsor');$researcher=$make('SponsoredResearcher');$other=$make('OtherResearcher');
$pkg=(int)$pdo->query("SELECT id FROM subscription_packages WHERE slug='basic-user' LIMIT 1")->fetchColumn();
$pdo->prepare("INSERT INTO accounts(public_id,account_type,name,owner_user_id,personal_user_id,package_id,subscription_status,period_start,period_end,status) VALUES(?,'personal',?,?,?,?, 'active',CURRENT_DATE,DATE_ADD(CURRENT_DATE,INTERVAL 1 MONTH),'active')")->execute([$pub('acct'),'Sponsored Project Account',(int)$sponsor['id'],(int)$sponsor['id'],$pkg]);$acct=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO account_members(account_id,user_id,account_role) VALUES(?,?,'owner')")->execute([$acct,(int)$sponsor['id']]);$q=$pdo->prepare('SELECT public_id FROM accounts WHERE id=?');$q->execute([$acct]);$acctPublic=(string)$q->fetchColumn();
sponsor_account_apply($pdo,$sponsor,['organization_name'=>'Sponsored Project Sponsor']);research_account_admin_decide($pdo,$admin,(int)$sponsor['id'],'sponsor_account','approved','Approved.','organization');
foreach([$researcher,$other] as $u){research_account_apply($pdo,$u,['specialties'=>'market research','languages'=>'English']);research_account_admin_decide($pdo,$admin,(int)$u['id'],'research_account','approved','Approved.','identity');}
$campaign=sponsored_research_campaign_create($pdo,$sponsor,['account_id'=>$acctPublic,'title'=>'Agent Sponsored Project','brief'=>'Investigate the sponsored question and submit a report.','objective'=>'Test Agent assignment and submission tracking.','questions'=>['What does the evidence support?'],'access_mode'=>'public','budget'=>'100.00','researcher_compensation'=>'25.00','eligibility'=>['min_verification'=>'identity'],'disclosures'=>['sponsorship_disclosure_required'=>false,'conflict_disclosure_required'=>false,'nda_required'=>false],'submission_deadline'=>'2030-12-31 23:59:00']);
$campaign=sponsored_research_campaign_set_status($pdo,$sponsor,(string)$campaign['public_id'],'open');sponsored_research_campaign_terms_publish($pdo,$sponsor,(string)$campaign['public_id'],'Use an assigned Research Agent and submit attributable reports.','Initial terms.');

$projectPublic=$pub('proj');$convPublic=$pub('conv');$agentPublic=$pub('agent');
$pdo->prepare("INSERT INTO research_projects(public_id,owner_user_id,title,description,status) VALUES(?,?,?,?,'active')")->execute([$projectPublic,(int)$researcher['id'],'Assigned Agent Project','Sponsored project research']);$projectId=(int)$pdo->lastInsertId();
$pdo->prepare("INSERT INTO conversations(public_id,conversation_type,created_by_user_id,title) VALUES(?,'agent',?,?)")->execute([$convPublic,(int)$researcher['id'],'Assigned Research Agent']);$convId=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO conversation_members(conversation_id,user_id,member_role) VALUES(?,?,'owner')")->execute([$convId,(int)$researcher['id']]);
$pdo->prepare("INSERT INTO research_agents(public_id,owner_user_id,project_id,conversation_id,name,visibility,status,monitoring_cadence) VALUES(?,?,?,?,?,'private','active','manual')")->execute([$agentPublic,(int)$researcher['id'],$projectId,$convId,'Assigned Research Agent']);
$assignment=sponsored_project_assign_agent($pdo,$researcher,(string)$campaign['public_id'],$agentPublic,['accept_terms'=>true]);
ok9($assignment['research_agent_public_id']===$agentPublic&&$assignment['status']==='active','Qualified Research Account assigns one of its own active Research Agents.');
$foreign=false;try{sponsored_project_assign_agent($pdo,$other,(string)$campaign['public_id'],$agentPublic,['accept_terms'=>true]);}catch(RuntimeException $e){$foreign=true;}ok9($foreign,'A researcher cannot assign another user’s Research Agent.');

$project=project_access($pdo,(int)$researcher['id'],$projectPublic);$doc=research_agent_workspace_create_document($pdo,$researcher,$project,['title'=>'Agent Research Document','body'=>'Evidence-backed sponsored research document.','summary'=>'Sponsored document summary.'],true);
$report=research_report_publish($pdo,$project,$researcher,'private','Agent Sponsored Report','Sponsored report summary.');
$submission=sponsored_project_submit($pdo,$researcher,(string)$campaign['public_id'],[['type'=>'report_version','public_id'=>(string)$report['version_public_id']],['type'=>'document','public_id'=>(string)$doc['public_id']]],'Agent Sponsored Submission','Report and document bundle.',true);
ok9($submission['status']==='submitted'&&count($submission['assets'])===2,'Assigned Agent submits one bundle with an immutable Report version and Research Document.');
$types=array_column($submission['assets'],'asset_type');sort($types);ok9($types===['document','report_version'],'Submission preserves both document and report assets.');
foreach($submission['assets'] as $asset)ok9(strlen((string)$asset['snapshot_hash'])===64,'Each submitted asset has an immutable snapshot hash.');

$projects=sponsored_project_admin_projects($pdo);$found=false;foreach($projects as $p)if($p['public_id']===$campaign['public_id'])$found=(int)$p['assigned_agents']===1&&(int)$p['submissions']===1;ok9($found,'Admin project list tracks assigned Agents and submission counts.');
$subs=sponsored_project_admin_submissions($pdo,(int)$campaign['id']);ok9(count($subs)===1&&count($subs[0]['assets'])===2,'Admin project detail returns each submission with attached documents/reports.');
$updated=sponsored_project_admin_status($pdo,$admin,(string)$submission['public_id'],'under_review');ok9($updated['status']==='under_review','Admin tracks submission review state.');
$updated=sponsored_project_admin_status($pdo,$admin,(string)$submission['public_id'],'accepted');ok9($updated['status']==='accepted','Admin can accept a Sponsored Project submission.');
echo "Phase 80 Section 9 Sponsored Projects database journey passed.\n";
