<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=(string)getenv('DB_DSN');$dbUser=(string)getenv('DB_USER');$dbPass=(string)getenv('DB_PASS');if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
foreach(['installer','storage','jobs','concurrency','functions','shell','access','notifications','rate-limit','ai','ai-access','source-integrity','annotation-intelligence','research-workspace','research-knowledge','research-intelligence','research-reports','conversations','agent-actions','agent-chat','cognitive-feed','research-entities','proactive-intelligence','research-automation','research-agent-workspace','research-agents','research-retrieval','workspace-context','object-handoff','research-autonomy','research-monitoring','research-tasks','research-programs','cross-research','research-outcomes','research-decisions','research-action-plans','research-action-plan-variance','research-action-plan-cognition','research-action-plan-outcomes','research-reviews','change-impact','research-portfolio','living-research','research-publishing','research-intelligence-portfolios','research-intelligence-operations','research-missions','research-intelligence-decision-rollups','research-intelligence-pattern-memory','research-intelligence-strategic-graph','research-intelligence-strategic-reviews','research-intelligence-strategic-briefings','research-intelligence-organizational-cognition','research-portfolios-ui','research-legacy-compat'] as $lib)require_once $root.'/app/'.$lib.'.php';
function p74s7(bool $ok,string $m): void {if(!$ok)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}
$run='p74s7'.substr(bin2hex(random_bytes(5)),0,10);$pub=fn(string $p)=>$p.'-'.$run.'-'.substr(bin2hex(random_bytes(3)),0,6);
$username='compat_'.$run;$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,email_verified_at,status,role,plan_tier,live_presence_mode) VALUES(?,?,?,?,NOW(),'active','admin','pro','cloaked')")->execute([$pub('u'),$username,'Phase74 Compat',$username.'@example.test']);$uid=(int)$pdo->lastInsertId();$pdo->prepare('INSERT IGNORE INTO user_preferences(user_id) VALUES(?)')->execute([$uid]);$q=$pdo->prepare('SELECT * FROM users WHERE id=?');$q->execute([$uid]);$u=$q->fetch();
$agent=research_agent_create($pdo,$u,['name'=>'Compatibility Agent','description'=>'Section 7 fixture','cadence'=>'manual','timezone_name'=>'UTC']);
$project=(string)$agent['project_public_id'];$agentId=(string)$agent['public_id'];$conversation=(string)$agent['conversation_public_id'];

p74s7((research_legacy_agent_by_project($pdo,$u,$project)['public_id']??'')===$agentId,'Legacy Project identity resolves to its canonical Research Agent.');
p74s7(research_legacy_route_target($pdo,$u,'research-project.php',['id'=>$project])==='/home.php?agent='.rawurlencode($conversation),'Legacy Project deep link resolves to canonical Agent Chat.');
p74s7(research_legacy_route_target($pdo,$u,'research-knowledge.php',['id'=>$project])==='/research-agent-knowledge.php?agent='.rawurlencode($agentId).'&view=library','Legacy Knowledge deep link resolves to Agent Knowledge Library.');
p74s7(research_legacy_route_target($pdo,$u,'research-brief.php',['id'=>$project])==='/research-reports.php?agent='.rawurlencode($agentId).'&view=create&type=research_brief','Legacy Research Brief resolves to the Report template.');
p74s7(research_legacy_route_target($pdo,$u,'research-outcomes.php',['project'=>$project])==='/research-agent-research.php?agent='.rawurlencode($agentId).'&view=decisions','Legacy Outcome Memory resolves to Decisions.');
p74s7(research_legacy_route_target($pdo,$u,'research-automations.php',['agent'=>$agentId])==='/research-agent-research.php?agent='.rawurlencode($agentId).'&view=recurring','Generic legacy Automations resolves to Recurring.');
p74s7(research_legacy_route_target($pdo,$u,'research-automations.php',['id'=>'legacy-automation'])===null,'Object-specific Automation deep links remain available.');
p74s7(research_legacy_route_target($pdo,$u,'research-reviews.php',[])==='/research-intelligence-portfolios.php?view=overview&focus=review','Generic Review Center resolves to global attention.');
p74s7(research_legacy_route_target($pdo,$u,'research-reviews.php',['id'=>'review-1'])===null,'Object-specific Review deep links remain available.');
p74s7(research_legacy_route_target($pdo,$u,'research-portfolio.php',[])==='/research.php','Legacy Research Portfolio resolves to canonical Research home.');
p74s7(research_legacy_route_target($pdo,$u,'research-intelligence-command-center.php',[])==='/research-intelligence-portfolios.php?view=overview','Command Center resolves to Portfolio Overview.');
p74s7(research_legacy_route_target($pdo,$u,'research-project.php',['id'=>'missing-project'])===null,'Unmapped historical Project remains reachable instead of being discarded.');
p74s7(research_legacy_route_target($pdo,$u,'research-project.php',['id'=>$project,'legacy'=>'1'])===null,'Explicit compatibility escape hatch preserves advanced legacy UI.');
p74s7(!(glob($root.'/database/migrations/*_104_*.sql')?:[]),'Legacy compatibility adds no migration 104.');
echo "Phase 74 Section 7 Legacy Route & Navigation Compatibility database journey passed.\n";
