<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=(string)getenv('DB_DSN');$dbUser=(string)getenv('DB_USER');$dbPass=(string)getenv('DB_PASS');if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
require_once $root.'/app/installer.php';require_once $root.'/app/functions.php';require_once $root.'/app/data-attribution.php';require_once $root.'/app/data-datasets.php';require_once $root.'/app/ai.php';require_once $root.'/app/data-evaluations.php';require_once $root.'/app/data-model-registry.php';require_once $root.'/app/data-training.php';require_once $root.'/app/data-post-training.php';
function p42(bool $v,string $m): void {if(!$v)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}
p42(data_post_training_ready($pdo),'Phase 42 post-training readiness schema is available');

$run='p42'.substr(bin2hex(random_bytes(7)),0,12);$pub=fn(string $p)=>$p.'-'.$run.'-'.substr(bin2hex(random_bytes(4)),0,8);
$makeUser=function(string $name,string $role='user')use($pdo,$run,$pub): array{$username=substr(strtolower($name).'_'.$run,0,48);$public=$pub('u');$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,password_hash,status,role) VALUES(?,?,?,?,?,'active',?)")->execute([$public,$username,$name,$username.'@example.test',password_hash('phase42-test',PASSWORD_DEFAULT),$role]);return ['id'=>(int)$pdo->lastInsertId(),'public_id'=>$public,'username'=>$username,'display_name'=>$name,'role'=>$role];};
$admin=$makeUser('ReadinessAdmin','admin');$contributor=$makeUser('ReadinessContributor');$outsider=$makeUser('ReadinessOutsider');

$completeRun=function(array $queued,float $quality=1.0)use($pdo): array {
    $suite=data_evaluation_suite_get($pdo,(string)$queued['suite_public_id']);if(!$suite)throw new RuntimeException('Fixture suite missing.');$cases=data_evaluation_cases($pdo,(int)$suite['id']);$rows=data_evaluation_dataset_rows($pdo,(int)$queued['dataset_id']);
    foreach($cases as $case){$ranked=data_evaluation_rank_rows($rows,(string)$case['query_text'],(int)$suite['top_k']);$expectedRank=null;foreach($ranked['all'] as $hit)if((int)$hit['dataset_item_id']===(int)$case['expected_dataset_item_id']){$expectedRank=(int)$hit['rank'];break;}$q=max(0.0,min(1.0,$quality));$metrics=['expected_rank'=>$expectedRank??0,'expected_score'=>$q,'hit_at_1'=>$expectedRank===1?1:0,'hit_at_3'=>$expectedRank!==null&&$expectedRank<=3?1:0,'hit_at_5'=>$expectedRank!==null&&$expectedRank<=5?1:0,'mrr'=>$expectedRank?1/$expectedRank:0.0,'top_score'=>$q,'expected_citation'=>$q>=0.5?1:0,'grounded_token_ratio'=>$q,'reference_token_f1'=>$q,'input_tokens'=>100,'output_tokens'=>20,'latency_ms'=>20.0+(1.0-$q)*20.0];$response='The Phoenix renewable project remains active [['.$case['expected_corpus_public_id'].']].';data_evaluation_result_insert($pdo,(int)$queued['id'],$case,$ranked,$response,$metrics,$q>=0.5,[$case['expected_corpus_public_id']]);}
    $summary=data_evaluation_summary($pdo,(int)$queued['id'],'model');$summaryJson=data_attribution_encode($summary);$summaryHash=hash('sha256',$summaryJson);$q=$pdo->prepare('SELECT result_hash FROM data_evaluation_results WHERE run_id=? ORDER BY case_id');$q->execute([$queued['id']]);$hashes=$q->fetchAll(PDO::FETCH_COLUMN);$runHash=data_attribution_hash(['run_public_id'=>$queued['public_id'],'dataset_manifest_hash'=>$queued['dataset_manifest_hash'],'suite_config_hash'=>$queued['suite_config_hash'],'cases_hash'=>$queued['cases_hash'],'model_snapshot'=>json_decode((string)($queued['model_snapshot_json']??''),true),'result_hashes'=>$hashes,'summary_hash'=>$summaryHash]);$pdo->prepare("UPDATE data_evaluation_runs SET status='completed',result_summary_json=?,result_summary_hash=?,run_hash=?,started_at=COALESCE(started_at,NOW()),completed_at=NOW() WHERE id=?")->execute([$summaryJson,$summaryHash,$runHash,$queued['id']]);return data_evaluation_run_get($pdo,(string)$queued['public_id']);
};

// Frozen evaluation corpus and dataset.
$evalType='phase42_eval_'.$run;$evalText='Phoenix renewable project remains active and funded '.$run;$evalCorpusPublic=$pub('corpus');
$pdo->prepare("INSERT INTO data_corpus_items(public_id,source_object_type,source_object_public_id,source_object_version,contributor_user_id,corpus_type,normalized_text,metadata_json,content_hash,provenance_hash,shared_retrieval_eligible,evaluation_eligible,training_eligible,commercial_training_eligible,attribution_required,eligibility_reason) VALUES(?,?,?,?,?,?,?,?,?,?,1,1,0,0,0,'phase42_eval_fixture')")->execute([$evalCorpusPublic,'fixture',$pub('evalobj'),'1',$contributor['id'],$evalType,$evalText,data_attribution_encode(['kind'=>'evaluation']),hash('sha256',$evalText),hash('sha256','prov-'.$evalText)]);
$evalDataset=data_dataset_create($pdo,$admin,['name'=>'Phase42 Evaluation '.$run,'purpose'=>'evaluation','corpus_types'=>$evalType,'max_items'=>10]);$evalDataset=data_dataset_freeze($pdo,$admin,$evalDataset['public_id']);$evalItems=data_dataset_items($pdo,$evalDataset['public_id']);$evalItem=(int)$evalItems[0]['id'];p42((int)$evalDataset['item_count']===1,'fixture has one frozen evaluation item');

// Provider and runtime models.
$providerPublic=$pub('provider');$pdo->prepare("INSERT INTO ai_providers(public_id,label,provider_type,api_base_url,api_key_ciphertext,enabled) VALUES(?,?,'openai_compatible','http://127.0.0.1:9',NULL,1)")->execute([$providerPublic,'Phase42 Provider']);$providerId=(int)$pdo->lastInsertId();
$makeModel=function(string $name)use($pdo,$providerId,$pub): array{$public=$pub('model');$modelName=strtolower(str_replace(' ','-',$name)).'-'.substr($public,-6);$pdo->prepare("INSERT INTO ai_models(public_id,provider_id,model_name,display_name,enabled,admin_enabled,pro_enabled,max_output_tokens) VALUES(?,?,?,?,1,1,0,2048)")->execute([$public,$providerId,$modelName,$name]);return ['id'=>(int)$pdo->lastInsertId(),'public_id'=>$public,'model_name'=>$modelName];};
$baseRuntime=$makeModel('Phase42 Base');$candidateRuntime=$makeModel('Phase42 Candidate');
$routeBefore=(int)($pdo->query('SELECT admin_default_model_id FROM ai_settings WHERE id=1')->fetchColumn()?:0);

// Governed base model + baseline evaluation.
$registry=data_model_registry_create($pdo,$admin,['name'=>'Phase42 Model Family '.$run,'description'=>'Post-training fixture']);
$base=data_model_version_create($pdo,$admin,$registry['public_id'],['version_label'=>'base-v1','origin'=>'external_hosted','ai_model_id'=>$baseRuntime['id'],'architecture'=>'fixture base','intended_use'=>'Phase 42 baseline','required_model_runs'=>1,'required_human_reviews'=>1,'minimum_human_pass_rate'=>1,'require_integrity'=>1]);
$baselineSuite=data_evaluation_suite_create($pdo,$admin,['dataset_id'=>$evalDataset['id'],'name'=>'Phase42 Governed Baseline '.$run,'benchmark_type'=>'model','top_k'=>3,'model_id'=>$baseRuntime['id'],'prompt_template'=>'Use only supplied benchmark context and cite [[ITEM]].']);
data_evaluation_case_add($pdo,$admin,$baselineSuite['public_id'],['label'=>'Phoenix status','query_text'=>'Phoenix renewable project active funded','expected_dataset_item_id'=>$evalItem,'reference_answer'=>'The Phoenix renewable project remains active and funded.','weight'=>1,'tags'=>'phoenix,renewable']);
$baselineSuite=data_evaluation_suite_activate($pdo,$admin,$baselineSuite['public_id']);$baselineRun=$completeRun(data_evaluation_run_queue($pdo,$admin,$baselineSuite['public_id']),1.0);$baselineResults=data_evaluation_results($pdo,(int)$baselineRun['id']);data_evaluation_review_save($pdo,$admin,(int)$baselineResults[0]['id'],['decision'=>'pass','relevance_score'=>5,'groundedness_score'=>5,'accuracy_score'=>5,'note'=>'Governed baseline review']);data_evaluation_set_baseline($pdo,$admin,$baselineSuite['public_id'],$baselineRun['public_id']);data_model_link_evaluation($pdo,$admin,$base['public_id'],$baselineRun['public_id'],'Phase 42 governed baseline');$base=data_model_transition($pdo,$admin,$base['public_id'],'candidate','Baseline candidate');$base=data_model_transition($pdo,$admin,$base['public_id'],'approved','Baseline approved');
p42($base['status']==='approved'&&data_model_receipt_integrity(data_model_latest_approval_receipt($pdo,$base),$base)['ok'],'baseline model is governed and approved with valid evidence');

// Rogue baseline suite deliberately not linked to the base model.
$rogueSuite=data_evaluation_suite_create($pdo,$admin,['dataset_id'=>$evalDataset['id'],'name'=>'Phase42 Unlinked Baseline '.$run,'benchmark_type'=>'model','top_k'=>3,'model_id'=>$baseRuntime['id'],'prompt_template'=>'Use only supplied benchmark context and cite [[ITEM]].']);
data_evaluation_case_add($pdo,$admin,$rogueSuite['public_id'],['label'=>'Phoenix status','query_text'=>'Phoenix renewable project active funded','expected_dataset_item_id'=>$evalItem,'reference_answer'=>'The Phoenix renewable project remains active and funded.','weight'=>1]);
$rogueSuite=data_evaluation_suite_activate($pdo,$admin,$rogueSuite['public_id']);$rogueRun=$completeRun(data_evaluation_run_queue($pdo,$admin,$rogueSuite['public_id']),1.0);data_evaluation_set_baseline($pdo,$admin,$rogueSuite['public_id'],$rogueRun['public_id']);

// Frozen training dataset with explicit supervision.
$trainType='phase42_train_'.$run;$trainText='Training example '.$run;$trainCorpusPublic=$pub('corpus');$trainingMeta=['training_example'=>['messages'=>[['role'=>'user','content'=>'What is the Phoenix renewable project status?'],['role'=>'assistant','content'=>'The Phoenix renewable project remains active.']]]];
$pdo->prepare("INSERT INTO data_corpus_items(public_id,source_object_type,source_object_public_id,source_object_version,contributor_user_id,corpus_type,normalized_text,metadata_json,content_hash,provenance_hash,shared_retrieval_eligible,evaluation_eligible,training_eligible,commercial_training_eligible,attribution_required,eligibility_reason) VALUES(?,?,?,?,?,?,?,?,?,?,0,0,1,0,0,'phase42_training_fixture')")->execute([$trainCorpusPublic,'fixture',$pub('trainobj'),'1',$contributor['id'],$trainType,$trainText,data_attribution_encode($trainingMeta),hash('sha256',$trainText),hash('sha256','prov-'.$trainText)]);
$trainingDataset=data_dataset_create($pdo,$admin,['name'=>'Phase42 Training '.$run,'purpose'=>'training','corpus_types'=>$trainType,'max_items'=>10]);$trainingDataset=data_dataset_freeze($pdo,$admin,$trainingDataset['public_id']);

$makeTrainingOutput=function(string $label)use($pdo,$admin,$trainingDataset,$base,$registry,$candidateRuntime,$run): array {
    $job=data_training_job_create($pdo,$admin,['dataset_id'=>$trainingDataset['id'],'base_model_version_id'=>$base['id'],'output_registry_id'=>$registry['id'],'output_version_label'=>$label,'executor_type'=>'manual','use_class'=>'internal_training']);$job=data_training_queue($pdo,$admin,$job['public_id']);$pdo->prepare("UPDATE data_training_jobs SET status='prepared',prepared_at=NOW() WHERE id=?")->execute([$job['id']]);$job=data_training_manual_complete($pdo,$admin,$job['public_id'],['artifact_ref'=>'registry://phase42/'.$label,'artifact_hash'=>hash('sha256','artifact-'.$label.'-'.$run),'output_model_name'=>'output-'.$label,'runtime_model_id'=>$candidateRuntime['id'],'actual_cost_usd'=>'1.00']);return data_training_job_get($pdo,$job['public_id']);
};

// Successful output and plan.
$job1=$makeTrainingOutput('trained-good-'.$run);$out1=data_model_version_get($pdo,(string)$job1['output_model_version_public_id']);p42($job1['status']==='succeeded'&&$out1['status']==='experimental','successful Phase 41 output is experimental before readiness planning');
$rejected=false;try{data_post_training_plan_create($pdo,$admin,$job1['public_id'],[$rogueSuite['public_id']],[]);}catch(RuntimeException $e){$rejected=str_contains($e->getMessage(),'governed evidence');}p42($rejected,'unlinked Phase 39 baseline cannot be used as a post-training governed template');

$plan1=data_post_training_plan_create($pdo,$admin,$job1['public_id'],[$baselineSuite['public_id']],['required_human_reviews_per_run'=>1,'minimum_human_pass_rate'=>1,'require_no_regression'=>1,'max_regressed_metrics'=>0,'regression_tolerance'=>0.02,'require_phase40_gate'=>1]);p42($plan1['status']==='draft','successful training output creates a draft readiness plan');
$plan1=data_post_training_prepare($pdo,$admin,$plan1['public_id']);p42($plan1['status']==='evaluating'&&data_post_training_plan_integrity($pdo,$plan1)['ok'],'preparation freezes plan identity and queues equivalent candidate evaluation');
$links1=data_post_training_links($pdo,(int)$plan1['id']);p42(count($links1)===1&&!empty($links1[0]['candidate_run_public_id']),'plan maps governed baseline to a candidate suite/run');
$candidateRun1=data_evaluation_run_get($pdo,$links1[0]['candidate_run_public_id']);$candidateFp=data_model_benchmark_fingerprint($pdo,$candidateRun1);p42(hash_equals($links1[0]['benchmark_fingerprint'],$candidateFp['hash']),'cloned candidate benchmark remains fingerprint-equivalent to governed baseline');

$candidateRun1=$completeRun($candidateRun1,1.0);$plan1=data_post_training_refresh($pdo,$admin,$plan1['public_id']);p42($plan1['status']==='awaiting_review','completed candidate benchmark remains awaiting human review before readiness');
$q=$pdo->prepare('SELECT COUNT(*) FROM data_model_evaluation_links WHERE version_id=? AND evaluation_run_id=?');$q->execute([$out1['id'],$candidateRun1['id']]);p42((int)$q->fetchColumn()===1,'integrity-valid candidate run is linked into Phase 40 evidence without promotion');
$out1=data_model_version_get($pdo,$out1['public_id']);p42($out1['status']==='experimental','evidence linking does not move the output out of experimental status');

$candidateResults1=data_evaluation_results($pdo,(int)$candidateRun1['id']);data_evaluation_review_save($pdo,$admin,(int)$candidateResults1[0]['id'],['decision'=>'pass','relevance_score'=>5,'groundedness_score'=>5,'accuracy_score'=>5,'note'=>'Post-training human review']);
$receiptsBefore=(int)$pdo->query('SELECT COUNT(*) FROM data_model_promotion_receipts WHERE version_id='.(int)$out1['id'])->fetchColumn();$plan1=data_post_training_refresh($pdo,$admin,$plan1['public_id']);$packets1=data_post_training_packets($pdo,(int)$plan1['id']);p42($plan1['status']==='ready'&&count($packets1)===1,'human-reviewed non-regressed candidate produces one readiness packet');
$packet1=$packets1[0];p42(data_post_training_packet_integrity($packet1)['ok']&&($packet1['packet']['readiness_state']??'')==='ready_for_human_consideration','readiness packet is tamper-evident and explicitly human-decision only');
$out1=data_model_version_get($pdo,$out1['public_id']);$receiptsAfter=(int)$pdo->query('SELECT COUNT(*) FROM data_model_promotion_receipts WHERE version_id='.(int)$out1['id'])->fetchColumn();p42($out1['status']==='experimental'&&$receiptsBefore===$receiptsAfter,'readiness packet creation never creates a Phase 40 lifecycle receipt or promotion');
p42((int)($pdo->query('SELECT admin_default_model_id FROM ai_settings WHERE id=1')->fetchColumn()?:0)===$routeBefore,'post-training readiness never changes production AI routing');
$out1=data_model_transition($pdo,$admin,$out1['public_id'],'candidate','Human decision after Phase 42 readiness');$plan1=data_post_training_refresh($pdo,$admin,$plan1['public_id']);p42($out1['status']==='candidate'&&$plan1['status']==='ready','a later explicit human lifecycle decision does not invalidate the historical ready plan');$postDecisionPackets=data_post_training_packets($pdo,(int)$plan1['id']);p42(count($postDecisionPackets)===1,'a later human lifecycle decision does not mint a second readiness packet');

// Separate trained output proving regression policy blocks readiness.
$job2=$makeTrainingOutput('trained-regressed-'.$run);$out2=data_model_version_get($pdo,(string)$job2['output_model_version_public_id']);$plan2=data_post_training_plan_create($pdo,$admin,$job2['public_id'],[$baselineSuite['public_id']],['required_human_reviews_per_run'=>1,'minimum_human_pass_rate'=>1,'require_no_regression'=>1,'max_regressed_metrics'=>0,'regression_tolerance'=>0.02,'require_phase40_gate'=>1]);$plan2=data_post_training_prepare($pdo,$admin,$plan2['public_id']);$links2=data_post_training_links($pdo,(int)$plan2['id']);$candidateRun2=data_evaluation_run_get($pdo,$links2[0]['candidate_run_public_id']);$candidateRun2=$completeRun($candidateRun2,0.10);$candidateResults2=data_evaluation_results($pdo,(int)$candidateRun2['id']);data_evaluation_review_save($pdo,$admin,(int)$candidateResults2[0]['id'],['decision'=>'pass','relevance_score'=>5,'groundedness_score'=>5,'accuracy_score'=>5,'note'=>'Human review does not override regression policy']);$plan2=data_post_training_refresh($pdo,$admin,$plan2['public_id']);$links2=data_post_training_links($pdo,(int)$plan2['id']);p42($plan2['status']==='blocked'&&str_contains((string)$plan2['last_error'],'regression')&&($links2[0]['comparison']['regressed_metrics']??0)>0,'configured equivalent-benchmark regression blocks promotion readiness');
$out2=data_model_version_get($pdo,$out2['public_id']);p42($out2['status']==='experimental','regression-blocked output remains experimental');

// Later training eligibility change invalidates current readiness while preserving historical packet.
$pdo->prepare('UPDATE data_corpus_items SET training_eligible=0 WHERE public_id=?')->execute([$trainCorpusPublic]);$plan1=data_post_training_refresh($pdo,$admin,$plan1['public_id']);p42($plan1['status']==='blocked'&&str_contains((string)$plan1['last_error'],'lineage'),'later training eligibility invalidation blocks current readiness state');
$packetsAfterBlock=data_post_training_packets($pdo,(int)$plan1['id']);p42(count($packetsAfterBlock)===1&&data_post_training_packet_integrity($packetsAfterBlock[0])['ok'],'historical readiness packet remains auditable after later governance invalidation');

$pdo->prepare('UPDATE data_post_training_packets SET packet_json=? WHERE id=?')->execute(['{"tampered":true}',$packetsAfterBlock[0]['id']]);$tamperedPackets=data_post_training_packets($pdo,(int)$plan1['id']);p42(!data_post_training_packet_integrity($tamperedPackets[0])['ok'],'direct readiness-packet tampering is detected');

$nonAdmin=false;try{data_post_training_plan_create($pdo,$outsider,$job2['public_id'],[$baselineSuite['public_id']],[]);}catch(RuntimeException $e){$nonAdmin=str_contains($e->getMessage(),'Administrator');}p42($nonAdmin,'post-training planning is administrator-only');
$events=data_post_training_events($pdo,(int)$plan1['id']);$types=array_column($events,'event_type');foreach(['plan_created','evaluation_prepared','readiness_packet_created','status_changed'] as $needed)p42(in_array($needed,$types,true),'readiness audit history includes '.$needed);
$summary=data_post_training_summary($pdo);p42($summary['plans']>=2&&$summary['packets']>=1&&$summary['blocked']>=2,'readiness summary exposes plan and packet lifecycle state');

echo "Phase 42 Post-Training Evaluation & Promotion Readiness MariaDB suite passed.\n";
