<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=(string)getenv('DB_DSN');$dbUser=(string)getenv('DB_USER');$dbPass=(string)getenv('DB_PASS');if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
require_once $root.'/app/installer.php';require_once $root.'/app/functions.php';require_once $root.'/app/data-attribution.php';
function p37(bool $v,string $m): void {if(!$v)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}
p37(data_attribution_ready($pdo),'Phase 37 schema is available');
$run='p37'.substr(bin2hex(random_bytes(7)),0,12);$pub=fn(string $p)=>$p.'-'.$run.'-'.substr(bin2hex(random_bytes(4)),0,8);
$makeUser=function(string $name,string $role='user')use($pdo,$run,$pub): array{$username=substr(strtolower($name).'_'.$run,0,48);$public=$pub('u');$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,password_hash,status,role) VALUES(?,?,?,?,?,'active',?)")->execute([$public,$username,$name,$username.'@example.test',password_hash('data-attribution-test',PASSWORD_DEFAULT),$role]);$id=(int)$pdo->lastInsertId();return ['id'=>$id,'public_id'=>$public,'username'=>$username,'display_name'=>$name,'role'=>$role];};
$user=$makeUser('Contributor');$admin=$makeUser('GovernanceAdmin','admin');

$prefs=data_contributor_preferences($pdo,(int)$user['id']);
p37(!(bool)$prefs['allow_shared_retrieval']&&!(bool)$prefs['allow_training'],'contributor defaults are closed for shared retrieval and training');

$sourcePublic=$pub('source');$url='https://'.$run.'.example.test/article';$pdo->prepare("INSERT INTO sources(public_id,source_type,canonical_url,canonical_url_hash,domain,title,status) VALUES(?,'article',?,?,?,?, 'current')")->execute([$sourcePublic,$url,hash('sha256',$url),$run.'.example.test','Attribution source']);
$sourceId=(int)$pdo->lastInsertId();$sourceText='Publisher-owned source excerpt '.$run.' must never leak into user-authored corpus text.';
$pdo->prepare('INSERT INTO source_versions(source_id,version_number,final_url,title,extracted_text,content_hash,target_content_hash) VALUES(?,1,?,?,?,?,?)')->execute([$sourceId,$url,'Attribution source',$sourceText,hash('sha256',$sourceText),hash('sha256','selected '.$run)]);$versionId=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE sources SET current_version_id=? WHERE id=?')->execute([$versionId,$sourceId]);
$selected='selected source passage '.$run;$pdo->prepare("INSERT INTO captures(public_id,source_id,source_version_id,user_id,capture_type,selected_text) VALUES(?,?,?,?, 'text',?)")->execute([$pub('cap'),$sourceId,$versionId,$user['id'],$selected]);$captureId=(int)$pdo->lastInsertId();
$annotationPublic=$pub('ann');$comment='My original analysis '.$run;$pdo->prepare("INSERT INTO annotations(public_id,user_id,source_id,source_version_id,capture_id,text_commentary,visibility,status) VALUES(?,?,?,?,?,?,'public','published')")->execute([$annotationPublic,$user['id'],$sourceId,$versionId,$captureId,$comment]);$annotationId=(int)$pdo->lastInsertId();
data_attribution_capture_object($pdo,(int)$user['id'],'annotation',$annotationPublic);

$q=$pdo->prepare("SELECT COUNT(*) FROM data_contributions WHERE actor_user_id=? AND object_type='annotation' AND object_public_id=?");$q->execute([$user['id'],$annotationPublic]);p37((int)$q->fetchColumn()===1,'public Annotation records an append-only contribution state');
$elig=data_training_eligibility($pdo,'annotation',$annotationPublic);p37(!$elig['shared_retrieval']&&!$elig['training']&&$elig['reason']==='no_contributor_consent','public visibility alone does not make an Annotation reusable or trainable');
$q=$pdo->prepare("SELECT COUNT(*) FROM data_corpus_items WHERE source_object_type='annotation' AND source_object_public_id=? AND invalidated_at IS NULL");$q->execute([$annotationPublic]);p37((int)$q->fetchColumn()===0,'no corpus text is materialized before consent');

data_contributor_preferences_update($pdo,$user,['allow_shared_retrieval'=>1,'allow_evaluation'=>1,'allow_training'=>1,'allow_commercial_training'=>0,'attribution_required'=>1]);
$corpus=data_corpus_refresh_object($pdo,'annotation',$annotationPublic);p37($corpus['active']&&$corpus['eligibility']['training'],'explicit contributor opt-in activates eligible public Annotation corpus');
$q=$pdo->prepare("SELECT normalized_text,training_eligible,attribution_required FROM data_corpus_items WHERE source_object_type='annotation' AND source_object_public_id=? AND invalidated_at IS NULL LIMIT 1");$q->execute([$annotationPublic]);$row=$q->fetch();
p37($row&&$row['normalized_text']===$comment&&!str_contains($row['normalized_text'],$selected)&&!str_contains($row['normalized_text'],$sourceText),'Annotation corpus contains contributor commentary, not captured publisher text');
p37((int)$row['training_eligible']===1&&(int)$row['attribution_required']===1,'training eligibility preserves attribution requirement');

$pdo->prepare("UPDATE annotations SET visibility='private' WHERE public_id=?")->execute([$annotationPublic]);$private=data_corpus_refresh_object($pdo,'annotation',$annotationPublic);p37(!$private['active']&&$private['reason']==='object_not_public','private Annotation is excluded even when contributor defaults allow training');
$pdo->prepare("UPDATE annotations SET visibility='public' WHERE public_id=?")->execute([$annotationPublic]);
data_usage_grant_set($pdo,$user,'annotation',$annotationPublic,['shared_retrieval_allowed'=>0,'evaluation_allowed'=>0,'training_allowed'=>0,'commercial_training_allowed'=>0,'attribution_required'=>1]);
$deny=data_training_eligibility($pdo,'annotation',$annotationPublic);p37(!$deny['training']&&$deny['reason']==='explicit_object_grant','object-specific deny overrides permissive contributor defaults');
data_usage_grant_set($pdo,$user,'annotation',$annotationPublic,['shared_retrieval_allowed'=>1,'evaluation_allowed'=>1,'training_allowed'=>1,'commercial_training_allowed'=>0,'attribution_required'=>1]);
$allow=data_training_eligibility($pdo,'annotation',$annotationPublic);p37($allow['training']&&$allow['reason']==='explicit_object_grant','object-specific grant can explicitly restore training eligibility');

$comment2='Revised original analysis '.$run;$pdo->prepare('UPDATE annotations SET text_commentary=? WHERE public_id=?')->execute([$comment2,$annotationPublic]);data_attribution_capture_object($pdo,(int)$user['id'],'annotation',$annotationPublic);
$q=$pdo->prepare("SELECT COUNT(*) total,SUM(superseded_at IS NOT NULL) superseded FROM data_contributions WHERE actor_user_id=? AND object_type='annotation' AND object_public_id=?");$q->execute([$user['id'],$annotationPublic]);$revision=$q->fetch();p37((int)$revision['total']===2&&(int)$revision['superseded']===1,'revised contribution creates a new state while preserving superseded history');

$projectPublic=$pub('project');$pdo->prepare("INSERT INTO research_projects(public_id,owner_user_id,title,description,status) VALUES(?,?,?,'Phase 37 project','active')")->execute([$projectPublic,$user['id'],'Data attribution project']);$projectId=(int)$pdo->lastInsertId();
$claimPublic=$pub('claim');$pdo->prepare("INSERT INTO research_claims(public_id,project_id,created_by_user_id,statement,claim_type,status) VALUES(?,?,?,?,'factual','unverified')")->execute([$claimPublic,$projectId,$user['id'],'Claim '.$run]);$claimId=(int)$pdo->lastInsertId();
$evidencePublic=$pub('evidence');$pdo->prepare("INSERT INTO claim_evidence(public_id,claim_id,added_by_user_id,evidence_type,annotation_id,source_version_id,relationship,note) VALUES(?,?,?,'annotation',?,?,'supports','test')")->execute([$evidencePublic,$claimId,$user['id'],$annotationId,$versionId]);
data_attribution_capture_object($pdo,(int)$user['id'],'claim',$claimPublic);
$claimElig=data_training_eligibility($pdo,'claim',$claimPublic);p37(!$claimElig['training']&&$claimElig['reason']==='object_not_public','private Research Claim never enters shared training corpus from contributor defaults');
$q=$pdo->prepare("SELECT COUNT(*) FROM data_provenance_edges WHERE to_type='claim' AND to_public_id=? AND relationship='supports' AND revoked_at IS NULL");$q->execute([$claimPublic]);p37((int)$q->fetchColumn()>=2,'Claim lineage records both Annotation and Source evidence edges');

$findingPublic=$pub('finding');$pdo->prepare("INSERT INTO research_findings(public_id,project_id,created_by_user_id,title,summary,status) VALUES(?,?,?,?,?,'final')")->execute([$findingPublic,$projectId,$user['id'],'Finding '.$run,'Finding summary '.$run]);$findingId=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO finding_claims(finding_id,claim_id,added_by_user_id,relationship,position) VALUES(?,?,?,'primary',0)")->execute([$findingId,$claimId,$user['id']]);data_attribution_capture_object($pdo,(int)$user['id'],'finding',$findingPublic);
$q=$pdo->prepare("SELECT COUNT(*) FROM data_provenance_edges WHERE from_type='claim' AND from_public_id=? AND to_type='finding' AND to_public_id=? AND relationship='primary'");$q->execute([$claimPublic,$findingPublic]);p37((int)$q->fetchColumn()===1,'Finding lineage preserves its Claim relationship');

$snapshot=['schema'=>'phase37-test','claims'=>[['id'=>$claimPublic]],'findings'=>[['id'=>$findingPublic]]];$snapshotJson=json_encode($snapshot,JSON_UNESCAPED_SLASHES);$reportPublic=$pub('report');$pdo->prepare("INSERT INTO research_reports(public_id,project_id,created_by_user_id,title,summary,visibility,status,published_at) VALUES(?,?,?,?,?,'public','published',NOW())")->execute([$reportPublic,$projectId,$user['id'],'Report '.$run,'Report summary '.$run]);$reportId=(int)$pdo->lastInsertId();$versionPublic=$pub('reportv');$pdo->prepare("INSERT INTO research_report_versions(public_id,report_id,version_number,published_by_user_id,visibility,title,summary,snapshot_json,snapshot_hash) VALUES(?,?,1,?,'public',?,?,?,?)")->execute([$versionPublic,$reportId,$user['id'],'Report '.$run,'Report summary '.$run,$snapshotJson,hash('sha256',$snapshotJson)]);$reportVersionId=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE research_reports SET current_version_id=? WHERE id=?')->execute([$reportVersionId,$reportId]);data_attribution_capture_object($pdo,(int)$user['id'],'report_version',$versionPublic);
$q=$pdo->prepare("SELECT COUNT(*) FROM data_corpus_items WHERE source_object_type='report_version' AND source_object_public_id=? AND training_eligible=1 AND invalidated_at IS NULL");$q->execute([$versionPublic]);p37((int)$q->fetchColumn()===1,'public Report summary can enter corpus only after contributor opt-in');
$q=$pdo->prepare("SELECT COUNT(*) FROM data_provenance_edges WHERE to_type='report_version' AND to_public_id=? AND relationship='included_in'");$q->execute([$versionPublic]);p37((int)$q->fetchColumn()===2,'Report lineage records included Claim and Finding');

$verificationPublic=$pub('verify');$stateJson=json_encode(['subject'=>$claimPublic]);$pdo->prepare("INSERT INTO research_verification_events(public_id,project_id,reviewer_user_id,subject_type,subject_public_id,subject_hash,decision,evidence_state_hash,evidence_state_json,note) VALUES(?,?,?,'claim',?,?,'reviewed_current',?,?,?)")->execute([$verificationPublic,$projectId,$user['id'],$claimPublic,hash('sha256','claim-state'),hash('sha256',$stateJson),$stateJson,'Human checked evidence']);data_attribution_capture_verification($pdo,(int)$user['id'],$verificationPublic);
$q=$pdo->prepare("SELECT COUNT(*) FROM data_provenance_edges WHERE from_type='claim' AND from_public_id=? AND to_type='verification' AND to_public_id=? AND relationship='verified_by'");$q->execute([$claimPublic,$verificationPublic]);p37((int)$q->fetchColumn()===1,'human verification is attributed without converting it into a truth score');

$sourceClosed=data_training_eligibility($pdo,'source',$sourcePublic);p37(!$sourceClosed['training']&&$sourceClosed['reason']==='source_rights_not_approved','source rights default closed even for a public web Source');
data_source_rights_set($pdo,$admin,$sourcePublic,['rights_class'=>'licensed','retrieval_allowed'=>1,'excerpt_storage_allowed'=>1,'model_context_allowed'=>1,'training_allowed'=>1,'commercial_training_allowed'=>0,'license_code'=>'TEST-LICENSE','rights_holder'=>'Test Publisher']);
$sourceOpen=data_training_eligibility($pdo,'source',$sourcePublic);p37($sourceOpen['shared_retrieval']&&$sourceOpen['training'],'reviewed licensed Source may enter corpus under explicit rights');
$q=$pdo->prepare("SELECT normalized_text FROM data_corpus_items WHERE source_object_type='source' AND source_object_public_id=? AND invalidated_at IS NULL LIMIT 1");$q->execute([$sourcePublic]);p37((string)$q->fetchColumn()===$sourceText,'source corpus is separate from user-authored Annotation corpus');
data_source_rights_set($pdo,$admin,$sourcePublic,['rights_class'=>'restricted','retrieval_allowed'=>1,'excerpt_storage_allowed'=>1,'model_context_allowed'=>1,'training_allowed'=>1,'commercial_training_allowed'=>1]);
$q=$pdo->prepare("SELECT COUNT(*) FROM data_corpus_items WHERE source_object_type='source' AND source_object_public_id=? AND invalidated_at IS NULL");$q->execute([$sourcePublic]);p37((int)$q->fetchColumn()===0,'restricted source classification force-disables and invalidates source corpus');

$aiRunPublic=$pub('airun');$refs=[['type'=>'annotation','id'=>$annotationPublic],['type'=>'claim','id'=>$claimPublic],['type'=>'finding','id'=>$findingPublic],['type'=>'report_version','id'=>$versionPublic],['type'=>'source','id'=>$sourcePublic],['type'=>'question','text'=>'ignored prompt text']];
$pdo->prepare("INSERT INTO ai_runs(public_id,user_id,initiated_by,task_type,model_id,prompt_version,scope_type,scope_public_id,input_refs_json,output_text,status,completed_at) VALUES(?,?,'pro','agent_chat',NULL,'v1','research_project',?,?,?,'completed',NOW())")->execute([$aiRunPublic,$user['id'],$projectPublic,json_encode($refs), 'Attributed answer '.$run]);$aiRunId=(int)$pdo->lastInsertId();
$lineage=data_response_record($pdo,$aiRunId,$aiRunPublic,$user,'Attributed answer '.$run,$refs);p37($lineage&&$lineage['attribution_count']===5,'AI response lineage records only concrete Annotated object refs supplied to the model');
$q=$pdo->prepare('SELECT COUNT(*) FROM data_response_attributions dra JOIN data_response_lineage drl ON drl.id=dra.response_lineage_id WHERE drl.ai_run_id=? AND dra.contributor_user_id=?');$q->execute([$aiRunId,$user['id']]);p37((int)$q->fetchColumn()>=4,'response attribution resolves known human contributors');
$accessible=data_response_lineage_access($pdo,$user,$aiRunPublic);p37($accessible&&count($accessible['attributions'])===5,'response lineage is visible to the initiating user');
$outsider=$makeUser('Outsider');p37(data_response_lineage_access($pdo,$outsider,$aiRunPublic)===null,'response lineage is not exposed to another user');

$conversationPublic=$pub('conv');$pdo->prepare("INSERT INTO conversations(public_id,conversation_type,created_by_user_id,title) VALUES(?,'agent',?,'Attribution chat')")->execute([$conversationPublic,$user['id']]);$conversationId=(int)$pdo->lastInsertId();$messagePublic=$pub('msg');$pdo->prepare("INSERT INTO conversation_messages(public_id,conversation_id,user_id,sender_type,body) VALUES(?,?,NULL,'agent',?)")->execute([$messagePublic,$conversationId,'Attributed answer '.$run]);$messageId=(int)$pdo->lastInsertId();data_response_bind_message($pdo,$aiRunPublic,$messageId);$map=data_response_attribution_map($pdo,[$messageId]);p37(isset($map[$messageId])&&$map[$messageId]['attribution_count']===5,'Agent Chat message is bound to its response attribution summary');

$before=(int)$pdo->query("SELECT COUNT(*) FROM data_contributions WHERE actor_user_id=".(int)$user['id'])->fetchColumn();data_attribution_sync_user($pdo,$user,500);data_attribution_sync_user($pdo,$user,500);$after=(int)$pdo->query("SELECT COUNT(*) FROM data_contributions WHERE actor_user_id=".(int)$user['id'])->fetchColumn();p37($after===$before,'repeated ledger synchronization is idempotent for unchanged contribution states');

data_usage_grant_revoke($pdo,$user,'annotation',$annotationPublic);data_contributor_preferences_update($pdo,$user,['allow_shared_retrieval'=>0,'allow_evaluation'=>0,'allow_training'=>0,'allow_commercial_training'=>0,'attribution_required'=>1]);
$q=$pdo->prepare("SELECT COUNT(*) FROM data_corpus_items WHERE contributor_user_id=? AND invalidated_at IS NULL");$q->execute([$user['id']]);p37((int)$q->fetchColumn()===0,'revoking object grant and contributor defaults invalidates future reusable corpus');
$q=$pdo->prepare("SELECT COUNT(*) FROM data_contributions WHERE actor_user_id=?");$q->execute([$user['id']]);p37((int)$q->fetchColumn()>0,'revocation preserves the append-only attribution ledger');

$columns=$pdo->query("SELECT column_name FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='data_contributions'")->fetchAll(PDO::FETCH_COLUMN);p37(!in_array('normalized_text',$columns,true),'contribution ledger stores hashes/references rather than reusable content blobs');

echo "Phase 37 Data & Attribution Architecture v1 MariaDB suite passed.\n";
