<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=getenv('DB_DSN')?:'';$dbUser=getenv('DB_USER')?:'root';$dbPass=getenv('DB_PASS')?:'';if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
foreach(['installer','storage','jobs','concurrency','functions','shell','access','notifications','rate-limit','ai','ai-access','source-integrity','annotation-intelligence','research-workspace','research-knowledge','research-intelligence','research-reports','conversations','agent-actions','agent-chat','cognitive-feed','research-entities','proactive-intelligence','research-automation','cross-research','research-outcomes','research-reviews','change-impact','research-portfolio','living-research','research-network'] as $lib)require_once $root.'/app/'.$lib.'.php';
function p25(bool $ok,string $m): void {if(!$ok)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}
$run='p25'.substr(bin2hex(random_bytes(6)),0,10);$pub=fn(string $p)=>$p.'-'.$run.'-'.substr(bin2hex(random_bytes(3)),0,6);
$makeUser=function(string $name)use($pdo,$run,$pub): array{$username=substr(strtolower($name).'_'.$run,0,48);$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,email_verified_at,status,role,plan_tier,live_presence_mode) VALUES(?,?,?,?,NOW(),'active','user','pro','cloaked')")->execute([$pub('u'),$username,$name,$username.'@example.test']);$id=(int)$pdo->lastInsertId();$pdo->prepare('INSERT IGNORE INTO user_preferences(user_id) VALUES(?)')->execute([$id]);$q=$pdo->prepare('SELECT * FROM users WHERE id=?');$q->execute([$id]);return $q->fetch();};
$authorA=$makeUser('CitationAuthorA');$authorB=$makeUser('CitationAuthorB');$outsider=$makeUser('CitationOutsider');p25(research_network_ready($pdo),'Phase 25 schema is available');

$projectA=$pub('project-a');$pdo->prepare("INSERT INTO research_projects(public_id,owner_user_id,title,description,status) VALUES(?,?,?,?,'active')")->execute([$projectA,$authorA['id'],'Source Research A','Public cited Research']);$pa=project_access($pdo,$authorA['id'],$projectA);
$a1=research_report_publish($pdo,$pa,$authorA,'public','Source Report A','Initial public cited report.','Citation Test');$reportA=research_report_access($pdo,(string)$a1['public_id'],$authorB);p25($reportA!==null&&(int)$reportA['version_number']===1,'public cited report v1 is accessible');

$projectB=$pub('project-b');$pdo->prepare("INSERT INTO research_projects(public_id,owner_user_id,title,description,status) VALUES(?,?,?,?,'active')")->execute([$projectB,$authorB['id'],'Citing Research B','Public citing Research']);$pb=project_access($pdo,$authorB['id'],$projectB);
$ref=research_network_reference_upsert($pdo,$authorB,$projectB,(string)$reportA['public_id'],1,'supports','A v1 supports this project.');p25(($ref['target']['version_number']??0)===1,'working project pins exact cited report version 1');
$refs=research_network_project_references($pdo,$authorB,$projectB);p25(count($refs)===1&&!$refs[0]['has_update']&&$refs[0]['publishable']['public'],'public v1 citation is publishable from a public project');

$b1=research_report_publish($pdo,$pb,$authorB,'public','Citing Report B','Public report citing A v1.','Citation Test');p25(($b1['citation_count']??0)===1,'publishing B v1 indexes one immutable report citation');
$reportB=research_report_access($pdo,(string)$b1['public_id'],$authorB);$bv1=research_report_version($pdo,$reportB,1);$snapB1=json_decode((string)$bv1['snapshot_json'],true)?:[];p25(count($snapB1['report_citations']??[])===1&&($snapB1['report_citations'][0]['version_number']??0)===1,'B v1 snapshot stores exact cited report version 1');
$q=$pdo->prepare('SELECT target_version_id FROM research_report_version_citations WHERE source_version_id=?');$q->execute([$bv1['id']]);$edgeTarget=(int)$q->fetchColumn();$av1=research_report_version($pdo,$reportA,1);p25($edgeTarget===(int)$av1['id'],'immutable citation edge B v1 points to A v1');

$notices=notification_rows($pdo,$authorA,100,false);$citationNotice=null;foreach($notices as $n)if(($n['notification_type']??'')==='research_report_cited'&&($n['object_public_id']??'')===$reportB['public_id']){$citationNotice=$n;break;}p25($citationNotice!==null,'cited report author receives citation notification for accessible citing report');p25(($citationNotice['url']??'')==='/research-report.php?id='.rawurlencode((string)$reportB['public_id']).'&v=1','citation notification deep-links exact citing report version');

$a2=research_report_publish($pdo,$pa,$authorA,'public','Source Report A','Second public version.','Citation Test');p25(($a2['version_number']??0)===2,'cited report publishes version 2');
$refsAfterA2=research_network_project_references($pdo,$authorB,$projectB);p25($refsAfterA2[0]['has_update']&&$refsAfterA2[0]['target']['version_number']===1&&$refsAfterA2[0]['target']['current_version_number']===2,'working citation remains pinned to A v1 while surfacing accessible A v2');
$q=$pdo->prepare('SELECT target_version_id FROM research_report_version_citations WHERE source_version_id=?');$q->execute([$bv1['id']]);p25((int)$q->fetchColumn()===(int)$av1['id'],'publishing A v2 does not retarget already-published B v1 citation');

$feed=cognitive_feed_compose($pdo,$authorB,null,8,120);$citationCards=array_values(array_filter(proactive_feed_items($feed),fn($i)=>($i['type']??'')==='citation_update'));p25(count($citationCards)>=1,'newer cited report version surfaces in Cognitive Feed');
$ctx=agent_chat_context_item($pdo,$authorB,'research',$projectB);p25($ctx!==null&&str_contains((string)$ctx['text'],'[REPORT CITATION NETWORK]')&&str_contains((string)$ctx['text'],'newer accessible version v2'),'Research Agent context explains pinned citation and newer accessible version');

$advanced=research_network_reference_upsert($pdo,$authorB,$projectB,(string)$reportA['public_id'],2,'supports','Reviewed A v2 and deliberately advanced the pin.');p25(($advanced['target']['version_number']??0)===2,'user deliberately advances working citation to A v2');
$b2=research_report_publish($pdo,$pb,$authorB,'public','Citing Report B','Second public report version citing A v2.','Citation Test');$reportB2=research_report_access($pdo,(string)$b2['public_id'],$authorB);$bv2=research_report_version($pdo,$reportB2,2);$av2=research_report_version($pdo,research_report_access($pdo,(string)$a2['public_id'],$authorB),2);
$q=$pdo->prepare('SELECT target_version_id FROM research_report_version_citations WHERE source_version_id=?');$q->execute([$bv2['id']]);p25((int)$q->fetchColumn()===(int)$av2['id'],'B v2 immutable citation edge points to deliberately selected A v2');
$q=$pdo->prepare('SELECT target_version_id FROM research_report_version_citations WHERE source_version_id=?');$q->execute([$bv1['id']]);p25((int)$q->fetchColumn()===(int)$av1['id'],'B v1 historical citation edge remains pinned to A v1 after B v2 publishes');

$publicA=research_report_access($pdo,(string)$a2['public_id'],null);$netA1=research_network_report_network($pdo,null,$publicA,1);p25(count($netA1['cited_by'])===1&&$netA1['cited_by'][0]['source']['version_number']===1,'public network shows accessible B v1 citing A v1');
$publicB=research_report_access($pdo,(string)$b2['public_id'],null);$netB2=research_network_report_network($pdo,null,$publicB,2);p25(count($netB2['references'])===1&&$netB2['references'][0]['target']['version_number']===2,'public network shows B v2 referencing exact A v2');

$selfBlocked=false;try{research_network_reference_upsert($pdo,$authorA,$projectA,(string)$a2['public_id'],2,'context','self cite');}catch(RuntimeException $e){$selfBlocked=true;}p25($selfBlocked,'project cannot cite its own publication');

$teamPublic=$pub('team');$pdo->prepare('INSERT INTO teams(public_id,owner_user_id,name) VALUES(?,?,?)')->execute([$teamPublic,$authorA['id'],'Citation Team']);$teamId=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO team_members(team_id,user_id,role) VALUES(?,?,'owner'),(?,?,'researcher')")->execute([$teamId,$authorA['id'],$teamId,$authorB['id']]);
$teamTargetProject=$pub('team-target');$pdo->prepare("INSERT INTO research_projects(public_id,owner_user_id,team_id,title,description,status) VALUES(?,?,?,?,?,'active')")->execute([$teamTargetProject,$authorA['id'],$teamId,'Team Target Research','Team citation target']);$pt=project_access($pdo,$authorA['id'],$teamTargetProject);$teamTarget=research_report_publish($pdo,$pt,$authorA,'team','Team Target Report','Team-only target.','Team Citation');
$teamSourceProject=$pub('team-source');$pdo->prepare("INSERT INTO research_projects(public_id,owner_user_id,team_id,title,description,status) VALUES(?,?,?,?,?,'active')")->execute([$teamSourceProject,$authorB['id'],$teamId,'Team Source Research','Team citation source']);$ps=project_access($pdo,$authorB['id'],$teamSourceProject);
$teamRef=research_network_reference_upsert($pdo,$authorB,$teamSourceProject,(string)$teamTarget['public_id'],1,'background','Same-Team citation.');$teamRefs=research_network_project_references($pdo,$authorB,$teamSourceProject);p25(!$teamRefs[0]['publishable']['public']&&$teamRefs[0]['publishable']['team']&&$teamRefs[0]['publishable']['private'],'same-Team non-public citation is blocked from public publication but allowed in Team/private publication');
$teamPublicSource=research_report_publish($pdo,$ps,$authorB,'public','Team Source Report','Public version must not expose Team citation.','Team Citation');$sourcePublicReport=research_report_access($pdo,(string)$teamPublicSource['public_id'],$authorB);$sourcePublicV1=research_report_version($pdo,$sourcePublicReport,1);$snapPublic=json_decode((string)$sourcePublicV1['snapshot_json'],true)?:[];p25(count($snapPublic['report_citations']??[])===0&&($teamPublicSource['citation_count']??-1)===0,'public report snapshot filters incompatible Team-only citation');
$teamSourceV2=research_report_publish($pdo,$ps,$authorB,'team','Team Source Report','Team version may include Team citation.','Team Citation');$teamSourceReport=research_report_access($pdo,(string)$teamSourceV2['public_id'],$authorB);$teamV2=research_report_version($pdo,$teamSourceReport,2);$snapTeam=json_decode((string)$teamV2['snapshot_json'],true)?:[];p25(count($snapTeam['report_citations']??[])===1&&($teamSourceV2['citation_count']??0)===1,'Team report version includes compatible same-Team citation');

$pdo->prepare('DELETE FROM team_members WHERE team_id=? AND user_id=?')->execute([$teamId,$authorB['id']]);$afterRevoke=research_network_project_references($pdo,$authorB,$teamSourceProject);p25(count($afterRevoke)===1&&!$afterRevoke[0]['available'],'project owner retains broken dependency shell after Team target access revocation without target identity leakage');
$outsideTarget=research_network_target($pdo,$outsider,(string)$teamTarget['public_id'],1);p25($outsideTarget===null,'outsider cannot resolve Team-only citation target');

$runtime=file_get_contents($root.'/app/research-network.php');p25(!str_contains($runtime,'ai_run(')&&!str_contains($runtime,'UPDATE research_report_version_citations')&&!str_contains($runtime,'agent_action_confirm_execute('),'citation runtime has no AI ranker, mutable published-edge update path, or direct Agent execution');
echo "Phase 25 Research Network & Citation Intelligence MariaDB suite passed.\n";
