<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=(string)getenv('DB_DSN');$dbUser=(string)getenv('DB_USER');$dbPass=(string)getenv('DB_PASS');if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
foreach(['installer','storage','jobs','concurrency','functions','shell','access','notifications','rate-limit','ai','ai-access','source-integrity','annotation-intelligence','research-workspace','research-knowledge','research-intelligence','research-reports','conversations','agent-actions','agent-chat','cognitive-feed','research-entities','proactive-intelligence','research-automation','research-agent-workspace','research-agents','research-retrieval','workspace-context','object-handoff','research-autonomy','research-monitoring','research-tasks','research-programs','cross-research','research-outcomes','research-reviews','change-impact','research-portfolio','living-research','research-publishing','research-intelligence-portfolios','research-intelligence-operations'] as $lib)require_once $root.'/app/'.$lib.'.php';
function p61(bool $ok,string $m): void {if(!$ok)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}
function p61throws(callable $fn,string $m): void {try{$fn();}catch(Throwable $e){echo "PASS: $m\n";return;}throw new RuntimeException('FAIL: '.$m);}
p61(research_intelligence_portfolio_operations_ready($pdo),'61A–61F schema and reused authoritative systems are available.');

$run='p61'.substr(bin2hex(random_bytes(6)),0,10);$pub=fn(string $p)=>$p.'-'.$run.'-'.substr(bin2hex(random_bytes(3)),0,6);
$makeUser=function(string $name)use($pdo,$run,$pub): array{$username=substr(strtolower($name).'_'.$run,0,48);$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,email_verified_at,status,role,plan_tier,live_presence_mode) VALUES(?,?,?,?,NOW(),'active','user','pro','cloaked')")->execute([$pub('u'),$username,$name,$username.'@example.test']);$id=(int)$pdo->lastInsertId();$pdo->prepare('INSERT IGNORE INTO user_preferences(user_id) VALUES(?)')->execute([$id]);$q=$pdo->prepare('SELECT * FROM users WHERE id=?');$q->execute([$id]);return $q->fetch();};
$owner=$makeUser('Phase61Owner');$subscriber=$makeUser('Phase61Subscriber');$outsider=$makeUser('Phase61Outsider');
$teamPublic=$pub('team');$pdo->prepare('INSERT INTO teams(public_id,owner_user_id,name) VALUES(?,?,?)')->execute([$teamPublic,$owner['id'],'Phase 61 Team']);$teamId=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO team_members(team_id,user_id,role) VALUES(?,?,'owner'),(?,?,'researcher')")->execute([$teamId,$owner['id'],$teamId,$subscriber['id']]);

$agentA=research_agent_create($pdo,$owner,['name'=>'Phase 61 Market Agent','description'=>'Operational market Research.','cadence'=>'manual','timezone_name'=>'UTC','team_id'=>$teamPublic]);
$agentB=research_agent_create($pdo,$owner,['name'=>'Phase 61 Product Agent','description'=>'Operational product Research.','cadence'=>'manual','timezone_name'=>'UTC','team_id'=>$teamPublic]);
$programA=research_program_create($pdo,$owner,['agent_id'=>$agentA['public_id'],'title'=>'Phase 61 Market Program','objective'=>'Track market changes.','cadence'=>'manual','priority'=>'high','tasks'=>[['title'=>'Review market movement','task_type'=>'general']]]);
$programB=research_program_create($pdo,$owner,['agent_id'=>$agentB['public_id'],'title'=>'Phase 61 Product Program','objective'=>'Track product changes.','cadence'=>'manual','priority'=>'high','tasks'=>[['title'=>'Review product movement','task_type'=>'general']]]);
$portfolio=research_intelligence_portfolio_create($pdo,$owner,['title'=>'Phase 61 Executive Portfolio','objective'=>'Operationalize market and product intelligence.','team_id'=>$teamPublic,'briefing_cadence'=>'weekly','briefing_policy'=>'material_only','materiality_threshold'=>'important','timezone_name'=>'UTC','briefing_time_local'=>'09:00','briefing_weekday'=>1]);
research_intelligence_portfolio_add_program($pdo,$owner,(string)$portfolio['public_id'],(string)$programA['public_id'],'primary');$portfolio=research_intelligence_portfolio_add_program($pdo,$owner,(string)$portfolio['public_id'],(string)$programB['public_id'],'supporting');
$portfolio=research_intelligence_portfolio_access($pdo,$owner,(string)$portfolio['public_id']);p61(!empty($portfolio['next_cycle_at'])&&($portfolio['briefing_policy']??'')==='material_only','61A Portfolio creation initializes the existing automation-runner schedule and material-only policy.');

research_intelligence_portfolio_subscription_set($pdo,$subscriber,(string)$portfolio['public_id'],['status'=>'active','cadence'=>'every_briefing','delivery_preference'=>'both']);
p61((research_intelligence_portfolio_subscription($pdo,$subscriber,(string)$portfolio['public_id'])['status']??'')==='active','61C accessible Team user can subscribe to Executive Briefings.');

$runA=research_program_enqueue($pdo,$programA,(int)$owner['id'],'manual');$runB=research_program_enqueue($pdo,$programB,(int)$owner['id'],'manual');$q=$pdo->prepare('SELECT id FROM research_program_runs WHERE public_id=?');$q->execute([$runA]);$runAId=(int)$q->fetchColumn();$q->execute([$runB]);$runBId=(int)$q->fetchColumn();$shared=$pub('shared');
$insertDelta=function(int $runId,array $program,string $type,string $importance,string $summary,string $ref)use($pdo): void {$pdo->prepare("INSERT INTO research_program_deltas(public_id,run_id,program_id,project_id,delta_type,importance,ref_type,ref_public_id,fingerprint,summary) VALUES(?,?,?,?,?,?,?,?,?,?)")->execute([ulid_like(),$runId,(int)$program['id'],(int)$program['project_id'],$type,$importance,'claim',$ref,hash('sha256',$runId.'|'.$type.'|'.$ref.'|'.$summary),$summary]);};
$insertDelta($runAId,$programA,'claim_strengthened','important','Market evidence strengthened the shared signal.',$shared);$insertDelta($runBId,$programB,'claim_contradicted','high','Product evidence contradicted the shared signal.',$shared);
$pdo->prepare('UPDATE research_intelligence_portfolios SET next_cycle_at=DATE_SUB(NOW(),INTERVAL 3 MINUTE) WHERE id=?')->execute([(int)$portfolio['id']]);$first=research_intelligence_portfolio_process_due($pdo,10);
p61($first['completed']===1&&$first['briefings']===1,'61A/61B first due cycle freezes intelligence and creates one draft Executive Briefing.');
$detail=research_intelligence_portfolio_detail($pdo,$owner,(string)$portfolio['public_id']);$brief1=$detail['briefings'][0]??null;p61($brief1&&($brief1['status']??'')==='draft','61B automation creates a draft Research Doc/Briefing and never silently publishes.');
$docQ=$pdo->prepare('SELECT rwd.content_html FROM research_executive_briefings b JOIN research_workspace_documents rwd ON rwd.object_id=b.document_object_id WHERE b.id=?');$docQ->execute([(int)$brief1['id']]);$content=(string)$docQ->fetchColumn();p61(str_contains($content,'New since last briefing'),'61B briefing renders explicit prior-snapshot comparison.');
$receipts=research_intelligence_portfolio_receipts($pdo,$subscriber,(string)$brief1['public_id']);p61(count($receipts)===1&&($receipts[0]['delivery_state']??'')==='notified','61C draft-ready notification creates a durable subscriber receipt.');
$nq=$pdo->prepare("SELECT * FROM notifications WHERE user_id=? AND object_type='research_intelligence_portfolio' ORDER BY id DESC LIMIT 1");$nq->execute([(int)$subscriber['id']]);$notification=$nq->fetch();p61($notification&&notification_object_access($pdo,$subscriber,$notification)&&str_contains((string)notification_url($pdo,$subscriber,$notification),'research-intelligence-portfolios.php'),'61C Portfolio notification preserves permission-aware navigation.');
research_intelligence_portfolio_acknowledge($pdo,$subscriber,(string)$brief1['public_id']);$receipts=research_intelligence_portfolio_receipts($pdo,$subscriber,(string)$brief1['public_id']);p61(($receipts[0]['delivery_state']??'')==='acknowledged','61C subscriber acknowledgement is durable.');

$pdo->prepare('UPDATE research_intelligence_portfolios SET next_cycle_at=DATE_SUB(NOW(),INTERVAL 2 MINUTE) WHERE id=?')->execute([(int)$portfolio['id']]);$second=research_intelligence_portfolio_process_due($pdo,10);
p61($second['skipped']===1&&$second['briefings']===0,'61A material-only cycle suppresses a duplicate briefing when the material hash is unchanged.');
$insertDelta($runAId,$programA,'source_unavailable','high','A critical market source became unavailable.',$pub('risk'));
$pdo->prepare('UPDATE research_intelligence_portfolios SET next_cycle_at=DATE_SUB(NOW(),INTERVAL 1 MINUTE) WHERE id=?')->execute([(int)$portfolio['id']]);$third=research_intelligence_portfolio_process_due($pdo,10);p61($third['completed']===1&&$third['briefings']===1,'61A new high-priority evidence reopens briefing generation on the next due cycle.');

$detail=research_intelligence_portfolio_detail($pdo,$owner,(string)$portfolio['public_id']);$brief2=$detail['briefings'][0];$workflow=research_intelligence_portfolio_prepare_publication($pdo,$owner,(string)$brief2['public_id'],['required_approvals'=>1,'visibility'=>'team']);
$tq=$pdo->prepare("SELECT COUNT(*) FROM research_publication_distribution_targets WHERE workflow_id=? AND target_type='user' AND target_user_id=?");$tq->execute([(int)$workflow['id'],(int)$subscriber['id']]);p61((int)$tq->fetchColumn()===1,'61C published subscribers flow into the authoritative Phase 59 recipient targets.');

$inference=research_intelligence_portfolio_add_inference($pdo,$owner,(string)$portfolio['public_id'],['title'=>'Executive tension','body'=>'Opposing signals may require a leadership decision.','category'=>'contradiction','severity'=>'high','confidence'=>0.8,'provenance_refs'=>[['type'=>'claim','id'=>$shared]]],false);
$decision=research_intelligence_portfolio_record_decision($pdo,$owner,(string)$portfolio['public_id'],['title'=>'Investigate the divergence','summary'=>'Leadership wants a bounded follow-up before acting.','decision_type'=>'recorded','insight_id'=>$inference['public_id'],'briefing_id'=>$brief2['public_id'],'create_follow_up'=>true,'follow_up_title'=>'Verify cross-program divergence','priority'=>'high']);
p61(!empty($decision['outcome']['public_id'])&&!empty($decision['task']['public_id']),'61D executive decision is a Decision Memory event with an existing Research follow-up task.');
$linkQ=$pdo->prepare("SELECT l.*,t.task_type FROM research_intelligence_portfolio_decision_links l JOIN research_tasks t ON t.id=l.task_id WHERE l.outcome_id=?");$linkQ->execute([(int)$decision['outcome']['id']]);$link=$linkQ->fetch();p61($link&&$link['task_type']==='follow_up','61D Phase 61 stores only a bridge to the Phase 57 follow-up task.');

$project=project_access($pdo,(int)$owner['id'],(string)$programA['project_public_id']);$claimPublic=$pub('claim');$pdo->prepare("INSERT INTO research_claims(public_id,project_id,created_by_user_id,statement,claim_type,status) VALUES(?,?,?,'Phase 61 immutable Claim fixture.','factual','unverified')")->execute([$claimPublic,(int)$project['id'],(int)$owner['id']]);$before=$pdo->query("SELECT status FROM research_claims WHERE public_id=".$pdo->quote($claimPublic))->fetchColumn();
research_intelligence_portfolio_feedback_set($pdo,$owner,(string)$portfolio['public_id'],['feedback_type'=>'escalated','insight_id'=>$inference['public_id'],'note'=>'Escalated for leadership review.']);$after=$pdo->query("SELECT status FROM research_claims WHERE public_id=".$pdo->quote($claimPublic))->fetchColumn();p61($before===$after,'61E explicit human feedback never mutates Research Claim conclusions.');
$feedback=research_intelligence_portfolio_feedback_rows($pdo,$portfolio,20);p61(count($feedback)>=1&&$feedback[0]['feedback_type']==='escalated','61E human feedback remains inspectable and separate from Agent inference.');

$center=research_intelligence_organization_command_center($pdo,$owner);p61(count($center['needs_attention'])>=1&&count($center['decisions_awaiting_follow_through'])>=1&&count($center['briefings_awaiting_review'])>=1,'61F command center rolls attention, follow-through, and Phase 59 review state into one view.');
$items=[];research_intelligence_portfolio_operations_cognitive_observations($pdo,$owner,$items,20);p61(count($items)>=1,'61D/61F open executive follow-through surfaces in Now.');

p61throws(fn()=>research_intelligence_portfolio_subscription_set($pdo,$outsider,(string)$portfolio['public_id'],['status'=>'active']),'61C outsider cannot subscribe to a Portfolio they cannot access.');
$pdo->prepare('DELETE FROM team_members WHERE team_id=? AND user_id=?')->execute([$teamId,$subscriber['id']]);p61(research_intelligence_portfolio_access($pdo,$subscriber,(string)$portfolio['public_id'])===null,'61C live Team revocation immediately removes Portfolio access.');
$runtime=(string)file_get_contents($root.'/app/research-intelligence-operations.php');p61(!str_contains($runtime,'ai_run(')&&!str_contains($runtime,'agent_action_confirm_execute('),'61A–61F runtime adds no hidden AI ranker or direct Agent execution authority.');
echo "Phase 61 Portfolio Intelligence Operations & Executive Follow-Through MariaDB suite passed.\n";
