<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=(string)getenv('DB_DSN');$dbUser=(string)getenv('DB_USER');$dbPass=(string)getenv('DB_PASS');if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
foreach(['installer','storage','jobs','concurrency','functions','shell','access','notifications','rate-limit','ai','ai-access','source-integrity','annotation-intelligence','research-workspace','research-knowledge','research-intelligence','research-reports','conversations','agent-actions','agent-chat','cognitive-feed','research-entities','proactive-intelligence','research-automation','research-agent-workspace','research-agents','research-retrieval','workspace-context','object-handoff','research-autonomy','research-monitoring','research-tasks','research-programs','cross-research','research-outcomes','research-reviews','change-impact','research-portfolio','living-research','research-publishing','research-intelligence-portfolios','research-intelligence-operations','release','release-operations'] as $lib)require_once $root.'/app/'.$lib.'.php';
function p62(bool $ok,string $m): void {if(!$ok)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}
function p62throws(callable $fn,string $m): void {try{$fn();}catch(Throwable $e){echo "PASS: $m\n";return;}throw new RuntimeException('FAIL: '.$m);}

p62(ANNOTATED_RELEASE==='V1.1'&&ANNOTATED_RELEASE_VERSION==='1.1.0'&&ANNOTATED_RELEASE_PHASE===62&&ANNOTATED_RELEASE_CHANNEL==='stable','62F canonical application release identity is stable V1.1 / 1.1.0 / Phase 62.');
p62(release_latest_migration($root)==='20260923_059_portfolio_intelligence_operations_follow_through.sql','62C/62F V1.1 final release deliberately introduces no migration after 059.');

$run='p62'.substr(bin2hex(random_bytes(6)),0,10);$pub=fn(string $p)=>$p.'-'.$run.'-'.substr(bin2hex(random_bytes(3)),0,6);
$makeUser=function(string $name)use($pdo,$run,$pub): array{$username=substr(strtolower($name).'_'.$run,0,48);$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,email_verified_at,status,role,plan_tier,live_presence_mode) VALUES(?,?,?,?,NOW(),'active','user','pro','cloaked')")->execute([$pub('u'),$username,$name,$username.'@example.test']);$id=(int)$pdo->lastInsertId();$pdo->prepare('INSERT IGNORE INTO user_preferences(user_id) VALUES(?)')->execute([$id]);$q=$pdo->prepare('SELECT * FROM users WHERE id=?');$q->execute([$id]);return $q->fetch();};
$owner=$makeUser('Phase62Owner');$reviewer=$makeUser('Phase62Reviewer');$outsider=$makeUser('Phase62Outsider');
$teamPublic=$pub('team');$pdo->prepare('INSERT INTO teams(public_id,owner_user_id,name) VALUES(?,?,?)')->execute([$teamPublic,$owner['id'],'Phase 62 Release Team']);$teamId=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO team_members(team_id,user_id,role) VALUES(?,?,'owner'),(?,?,'researcher')")->execute([$teamId,$owner['id'],$teamId,$reviewer['id']]);

$agentA=research_agent_create($pdo,$owner,['name'=>'Phase 62 Primary Agent','description'=>'Final release primary Research Agent.','cadence'=>'manual','timezone_name'=>'UTC','team_id'=>$teamPublic]);
$agentB=research_agent_create($pdo,$owner,['name'=>'Phase 62 Corroboration Agent','description'=>'Final release corroborating Research Agent.','cadence'=>'manual','timezone_name'=>'UTC','team_id'=>$teamPublic]);
$projectA=research_agent_workspace_project($pdo,$owner,(string)$agentA['public_id']);$projectB=research_agent_workspace_project($pdo,$owner,(string)$agentB['public_id']);
p62($projectA&&$projectB&&(int)$projectA['team_id']===$teamId,'62B starts with real Team-scoped Research Agents and workspaces.');

$url='https://8.8.8.8/'.$run.'/final-evidence';$source=ensure_source($pdo,$url,'Phase 62 Final Evidence');$text='Fresh release evidence '.$run;
$pdo->prepare("INSERT INTO source_versions(source_id,version_number,final_url,title,extracted_text,content_hash,captured_at) VALUES(?,1,?,?,?,?,NOW())")->execute([(int)$source['id'],$url,'Phase 62 Final Evidence',$text,hash('sha256',$text)]);$sv=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE sources SET current_version_id=? WHERE id=?')->execute([$sv,(int)$source['id']]);$pdo->prepare('INSERT IGNORE INTO project_sources(project_id,source_id,added_by_user_id) VALUES(?,?,?)')->execute([(int)$projectA['id'],(int)$source['id'],(int)$owner['id']]);
$claimPublic=$pub('claim');$pdo->prepare("INSERT INTO research_claims(public_id,project_id,created_by_user_id,statement,claim_type,status) VALUES(?,?,?,'Phase 62 evidence supports the final release proposition.','factual','supported')")->execute([$claimPublic,(int)$projectA['id'],(int)$owner['id']]);$claimId=(int)$pdo->lastInsertId();
p62(research_claim_access($pdo,$owner,$claimPublic)!==null,'62B Research Agent workspace contains authoritative Source evidence and a supported Claim.');

$task=research_task_create_for_project($pdo,$owner,$projectA,['title'=>'Verify final release evidence','description'=>'Human-check the preserved evidence before publication.','task_type'=>'follow_up','priority'=>'high'],false);
$pdo->prepare("UPDATE research_tasks SET execution_summary='Evidence reviewed and ready for governed publication.',status='review' WHERE id=?")->execute([(int)$task['id']]);$task=research_task_review($pdo,$owner,(string)$task['public_id'],true);
p62(($task['status']??'')==='complete'&&!empty($task['completed_at']),'62B existing Phase 57 task completes through its normal human-review path.');

$programA=research_program_create($pdo,$owner,['agent_id'=>$agentA['public_id'],'title'=>'Final Release Primary Program','objective'=>'Track release evidence and publication continuity.','cadence'=>'manual','priority'=>'high','tasks'=>[['title'=>'Watch final evidence','task_type'=>'general']]]);
$programB=research_program_create($pdo,$owner,['agent_id'=>$agentB['public_id'],'title'=>'Final Release Corroboration Program','objective'=>'Track corroborating release intelligence.','cadence'=>'manual','priority'=>'high','tasks'=>[['title'=>'Watch corroboration','task_type'=>'general']]]);
p62($programA&&$programB,'62B existing Phase 58 Programs remain the recurring Research authority.');

$doc=research_agent_workspace_create_document($pdo,$owner,$projectA,['title'=>'V1.1 Final Research Brief','content_html'=>'<h2>Executive summary</h2><p>Governed V1.1 final release evidence.</p>','summary'=>'Phase 62 integrated release document.','document_type'=>'research_brief'],false);
$workflow=research_publication_workflow_create($pdo,$owner,(string)$doc['public_id'],['title'=>'V1.1 Final Published Brief','summary'=>'Phase 62 governed publication.','visibility'=>'team','required_approvals'=>1,'owner_approval'=>true,'review_complete'=>true,'no_unresolved_threads'=>true,'no_failed_task_gates'=>true,'no_high_contradictions'=>true,'fresh_evidence_days'=>30,'recipient_user_ids'=>[$reviewer['id']]]);
$workflow=research_publication_request_review($pdo,$owner,(string)$workflow['public_id'],[['user_id'=>$reviewer['id'],'role'=>'approver','required'=>true]],date('Y-m-d H:i:s',time()+86400),'Final V1.1 release review.');
$review=research_review_access($pdo,$reviewer,(string)$workflow['review_public_id']);research_review_respond($pdo,$reviewer,(string)$review['public_id'],'approve','Evidence and release wording verified.');research_review_complete($pdo,$owner,(string)$review['public_id']);research_publication_owner_approve($pdo,$owner,(string)$workflow['public_id']);
$evaluation=research_publication_evaluate($pdo,$owner,(string)$workflow['public_id']);p62($evaluation['pass'],'62B Phase 59 review/approval gates pass for the final Research Doc.');
$publish=research_publication_publish($pdo,$owner,(string)$workflow['public_id']);$q=$pdo->prepare('SELECT snapshot_hash,snapshot_json FROM research_report_versions WHERE id=?');$q->execute([(int)$publish['version_id']]);$frozen=$q->fetch();
p62($frozen&&hash_equals((string)$frozen['snapshot_hash'],hash('sha256',(string)$frozen['snapshot_json'])),'62B publication produces an immutable hash-verifiable report snapshot.');
$live=research_agent_workspace_object($pdo,$owner,(string)$doc['public_id'],false);research_agent_workspace_save_document($pdo,$owner,(string)$doc['public_id'],['title'=>$live['title'],'content_html'=>'<p>Living document changed after publication.</p>','summary'=>'Post-publication edit.','base_revision'=>(int)$live['revision_number']]);$q->execute([(int)$publish['version_id']]);$frozenAfter=$q->fetch();p62($frozenAfter===$frozen,'62B living document edits cannot mutate the published V1.1 snapshot.');

$portfolio=research_intelligence_portfolio_create($pdo,$owner,['title'=>'V1.1 Executive Intelligence','objective'=>'Roll final release Research Programs into executive intelligence.','team_id'=>$teamPublic,'briefing_cadence'=>'weekly','briefing_policy'=>'material_only','materiality_threshold'=>'important','timezone_name'=>'UTC','briefing_time_local'=>'09:00','briefing_weekday'=>1]);
research_intelligence_portfolio_add_program($pdo,$owner,(string)$portfolio['public_id'],(string)$programA['public_id'],'primary');research_intelligence_portfolio_add_program($pdo,$owner,(string)$portfolio['public_id'],(string)$programB['public_id'],'supporting');
research_intelligence_portfolio_subscription_set($pdo,$reviewer,(string)$portfolio['public_id'],['status'=>'active','cadence'=>'every_briefing','delivery_preference'=>'both']);
$runA=research_program_enqueue($pdo,$programA,(int)$owner['id'],'manual');$runB=research_program_enqueue($pdo,$programB,(int)$owner['id'],'manual');$q=$pdo->prepare('SELECT id FROM research_program_runs WHERE public_id=?');$q->execute([$runA]);$runAId=(int)$q->fetchColumn();$q->execute([$runB]);$runBId=(int)$q->fetchColumn();$shared=$pub('shared');
$insertDelta=function(int $runId,array $program,string $type,string $importance,string $summary,string $ref)use($pdo): void {$pdo->prepare("INSERT INTO research_program_deltas(public_id,run_id,program_id,project_id,delta_type,importance,ref_type,ref_public_id,fingerprint,summary) VALUES(?,?,?,?,?,?,?,?,?,?)")->execute([ulid_like(),$runId,(int)$program['id'],(int)$program['project_id'],$type,$importance,'claim',$ref,hash('sha256',$runId.'|'.$type.'|'.$ref.'|'.$summary),$summary]);};
$insertDelta($runAId,$programA,'claim_strengthened','important','Primary evidence strengthened.',$shared);$insertDelta($runBId,$programB,'claim_contradicted','high','Corroborating Program identified a tension.',$shared);
$pdo->prepare('UPDATE research_intelligence_portfolios SET next_cycle_at=DATE_SUB(NOW(),INTERVAL 3 MINUTE) WHERE id=?')->execute([(int)$portfolio['id']]);$cycle1=research_intelligence_portfolio_process_due($pdo,10);p62($cycle1['completed']===1&&$cycle1['briefings']===1,'62B Portfolio scheduled intelligence creates the first Executive Briefing draft.');
$detail=research_intelligence_portfolio_detail($pdo,$owner,(string)$portfolio['public_id']);$brief1=$detail['briefings'][0];p62(!empty($brief1['public_id']),'62B Executive Briefing is available through the governed Portfolio.');

$inference=research_intelligence_portfolio_add_inference($pdo,$owner,(string)$portfolio['public_id'],['title'=>'Release evidence tension','body'=>'Leadership should verify the cross-Program tension before the next decision.','category'=>'contradiction','severity'=>'watch','confidence'=>0.75,'provenance_refs'=>[['type'=>'claim','id'=>$shared]]],false);
$decision=research_intelligence_portfolio_record_decision($pdo,$owner,(string)$portfolio['public_id'],['title'=>'Resolve release evidence tension','summary'=>'Complete a bounded follow-up before the next briefing.','decision_type'=>'recorded','insight_id'=>$inference['public_id'],'briefing_id'=>$brief1['public_id'],'create_follow_up'=>true,'follow_up_title'=>'Resolve executive evidence tension','priority'=>'high']);
p62(!empty($decision['outcome']['public_id'])&&!empty($decision['task']['public_id']),'62B executive decision enters existing Decision Memory and creates an existing Research follow-up task.');
$pdo->prepare("UPDATE research_tasks SET execution_summary='Executive follow-through completed with reviewed evidence.',status='review' WHERE id=?")->execute([(int)$decision['task']['id']]);$follow=research_task_review($pdo,$owner,(string)$decision['task']['public_id'],true);p62(($follow['status']??'')==='complete','62B executive follow-through completes through the existing Research Task lifecycle.');
$q=$pdo->prepare('SELECT COUNT(*) FROM research_intelligence_portfolio_decision_links WHERE outcome_id=? AND task_id=?');$q->execute([(int)$decision['outcome']['id'],(int)$decision['task']['id']]);p62((int)$q->fetchColumn()===1,'62B Portfolio keeps a provenance link while Decision Memory and Research Tasks remain authoritative.');

$insertDelta($runAId,$programA,'source_restored','important','Follow-through restored confidence in a key source.',$pub('restored'));$pdo->prepare('UPDATE research_intelligence_portfolios SET next_cycle_at=DATE_SUB(NOW(),INTERVAL 1 MINUTE) WHERE id=?')->execute([(int)$portfolio['id']]);$cycle2=research_intelligence_portfolio_process_due($pdo,10);p62($cycle2['completed']===1&&$cycle2['briefings']===1,'62B subsequent material change creates the next Executive Briefing.');
$detail=research_intelligence_portfolio_detail($pdo,$owner,(string)$portfolio['public_id']);$brief2=$detail['briefings'][0];$q=$pdo->prepare('SELECT rwd.content_html FROM research_executive_briefings b JOIN research_workspace_documents rwd ON rwd.object_id=b.document_object_id WHERE b.public_id=?');$q->execute([(string)$brief2['public_id']]);p62(str_contains((string)$q->fetchColumn(),'New since last briefing'),'62B subsequent briefing explicitly compares against the prior frozen snapshot.');

$receipts=research_intelligence_portfolio_receipts($pdo,$reviewer,(string)$brief2['public_id']);p62(count($receipts)===1,'62B/62C subscribed collaborator receives the next briefing through current access rules.');
$center=research_intelligence_organization_command_center($pdo,$owner);p62(count($center['needs_attention'])>=1,'62D/62E Command Center resolves the integrated Portfolio lifecycle after follow-through.');
$items=[];research_intelligence_portfolio_operations_cognitive_observations($pdo,$owner,$items,20);p62(is_array($items),'62D final Now integration composes safely from executive Portfolio state.');

$pdo->prepare('DELETE FROM team_members WHERE team_id=? AND user_id=?')->execute([$teamId,$reviewer['id']]);p62(research_intelligence_portfolio_access($pdo,$reviewer,(string)$portfolio['public_id'])===null&&project_access($pdo,(int)$reviewer['id'],(string)$projectA['public_id'])===null,'62B/62D Team revocation removes Research and Portfolio access immediately.');
p62throws(fn()=>research_intelligence_portfolio_acknowledge($pdo,$reviewer,(string)$brief2['public_id']),'62D revoked collaborator cannot continue acting on an Executive Briefing.');

$tmp=sys_get_temp_dir().'/annotated-phase62-backup-'.bin2hex(random_bytes(5));mkdir($tmp,0700,true);$storage=$tmp.'/private';mkdir($storage,0700,true);file_put_contents($tmp.'/database.sql.gz','phase62-db');file_put_contents($tmp.'/private-storage.tar.gz','phase62-storage');
$config=['db'=>['dsn'=>$dsn,'user'=>$dbUser,'pass'=>$dbPass],'storage'=>['private_root'=>$storage]];$manifest=release_backup_manifest_write($tmp,$config,$root,['build_sha'=>str_repeat('a',40)]);$verified=release_backup_manifest_verify($tmp);p62($verified['ok']&&($verified['manifest']['backup_id']??'')===$manifest['backup_id'],'62C existing release backup manifest verifies as a matched database/private-storage recovery pair.');file_put_contents($tmp.'/database.sql.gz','tampered',FILE_APPEND);$tampered=release_backup_manifest_verify($tmp);p62(!$tampered['ok'],'62C backup verification detects recovery artifact tampering before restore planning.');foreach(glob($tmp.'/*')?:[] as $f){if(is_file($f))@unlink($f);}if(is_dir($storage))@rmdir($storage);@rmdir($tmp);

echo "Phase 62 V1.1 integrated release journey passed: Research Agent → Claim → Task → Program → Research Doc → Review → Publish → Portfolio → Briefing → Decision → Follow-through → next briefing.\n";
