<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=getenv('DB_DSN')?:'';$dbUser=getenv('DB_USER')?:'root';$dbPass=getenv('DB_PASS')?:'';if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
foreach(['installer','storage','jobs','concurrency','functions','shell','access','notifications','rate-limit','ai','ai-access','source-integrity','annotation-intelligence','research-workspace','research-knowledge','research-intelligence','research-reports','conversations','agent-actions','agent-chat','cognitive-feed','research-entities','proactive-intelligence','research-automation','cross-research','research-outcomes','research-reviews','change-impact','research-portfolio','living-research'] as $lib)require_once $root.'/app/'.$lib.'.php';
function p24(bool $ok,string $m): void {if(!$ok)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}
$run='p24'.substr(bin2hex(random_bytes(6)),0,10);$pub=fn(string $p)=>$p.'-'.$run.'-'.substr(bin2hex(random_bytes(3)),0,6);
$makeUser=function(string $name)use($pdo,$run,$pub): array{$username=substr(strtolower($name).'_'.$run,0,48);$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,email_verified_at,status,role,plan_tier,live_presence_mode) VALUES(?,?,?,?,NOW(),'active','user','pro','cloaked')")->execute([$pub('u'),$username,$name,$username.'@example.test']);$id=(int)$pdo->lastInsertId();$pdo->prepare('INSERT IGNORE INTO user_preferences(user_id) VALUES(?)')->execute([$id]);$q=$pdo->prepare('SELECT * FROM users WHERE id=?');$q->execute([$id]);return $q->fetch();};
$owner=$makeUser('LivingOwner');$member=$makeUser('LivingMember');$outsider=$makeUser('LivingOutsider');p24(living_research_ready($pdo),'Phase 24 schema is available');

$teamPublic=$pub('team');$pdo->prepare('INSERT INTO teams(public_id,owner_user_id,name) VALUES(?,?,?)')->execute([$teamPublic,$owner['id'],'Living Team']);$teamId=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO team_members(team_id,user_id,role) VALUES(?,?,'owner'),(?,?,'researcher')")->execute([$teamId,$owner['id'],$teamId,$member['id']]);
$projectPublic=$pub('project');$pdo->prepare("INSERT INTO research_projects(public_id,owner_user_id,team_id,title,description,status) VALUES(?,?,?,?,?,'active')")->execute([$projectPublic,$owner['id'],$teamId,'Living Team Research','Publication lifecycle fixture']);$projectId=(int)$pdo->lastInsertId();$project=project_access($pdo,$owner['id'],$projectPublic);p24($project!==null&&research_report_can_publish($project),'owner can publish the Team Research project');

$url='https://example.com/'.$run.'/living-source';$sourcePublic=$pub('source');$pdo->prepare("INSERT INTO sources(public_id,source_type,canonical_url,canonical_url_hash,domain,title,status,monitoring_enabled,moderation_status) VALUES(?,'article',?,?,?,'Living Research Source','current',1,'visible')")->execute([$sourcePublic,$url,hash('sha256',$url),'example.com']);$sourceId=(int)$pdo->lastInsertId();
$pdo->prepare("INSERT INTO source_versions(source_id,version_number,final_url,title,extracted_text,content_hash,captured_at) VALUES(?,1,?,'Living Research Source','Version one evidence.',?,DATE_SUB(NOW(),INTERVAL 2 HOUR))")->execute([$sourceId,$url,hash('sha256','p24-v1-'.$run)]);$sv1=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE sources SET current_version_id=? WHERE id=?')->execute([$sv1,$sourceId]);$pdo->prepare('INSERT INTO project_sources(project_id,source_id,added_by_user_id) VALUES(?,?,?)')->execute([$projectId,$sourceId,$owner['id']]);

$r1=research_report_publish($pdo,$project,$owner,'team','Living Team Report','Versioned team publication.','Broadband, Phoenix');p24(($r1['version_number']??0)===1,'first publish creates immutable report version 1');
$report=research_report_access($pdo,(string)$r1['public_id'],$member);p24($report!==null&&(int)$report['version_number']===1,'Team member can access published Team report');
$v1=research_report_version($pdo,$report,1);$v1Hash=(string)$v1['snapshot_hash'];$v1Json=(string)$v1['snapshot_json'];
$topics=living_research_topics($pdo,(int)$report['id']);p24(array_column($topics,'topic_slug')===['broadband','phoenix'],'publisher topics are normalized and stored explicitly');
p24(living_research_public_topics($pdo,50)===[],'Team report topics do not leak into public topic discovery');

living_research_set_subscription($pdo,$member,$report,true,true);$sub=living_research_subscription($pdo,$member,$report);p24($sub['subscribed']&&$sub['notify_updates'],'accessible Team member can explicitly follow report updates');
living_research_mark_read($pdo,$member,$report,(int)$report['current_version_id']);$rs1=living_research_read_status($pdo,$member,$report);p24($rs1['last_read_version']===1&&!$rs1['updated_since_read'],'reader state records version 1 as read');

$pdo->prepare("INSERT INTO source_versions(source_id,version_number,final_url,title,extracted_text,content_hash,captured_at) VALUES(?,2,?,'Living Research Source','Version two evidence was revised.',?,NOW())")->execute([$sourceId,$url,hash('sha256','p24-v2-'.$run)]);$sv2=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE sources SET current_version_id=?,status=\'edited\' WHERE id=?')->execute([$sv2,$sourceId]);
$r2=research_report_publish($pdo,$project,$owner,'team','Living Team Report','Versioned team publication.','Broadband, Arizona');p24(($r2['version_number']??0)===2&&($r2['subscriber_notifications']??0)===1,'publishing version 2 notifies one currently authorized subscriber after commit');
$report2=research_report_access($pdo,(string)$r2['public_id'],$member);$rs2=living_research_read_status($pdo,$member,$report2);p24($rs2['updated_since_read']&&$rs2['last_read_version']===1&&$rs2['current_version']===2,'subscriber sees report updated since version 1 was read');
$diff=living_research_version_diff($pdo,$report2,$member,1,2);p24(($diff['sections']['sources']['counts']['changed']??0)===1&&$diff['totals']['changed']>=1,'immutable version diff identifies changed Source snapshot');
$v1After=research_report_version($pdo,$report2,1);p24((string)$v1After['snapshot_hash']===$v1Hash&&(string)$v1After['snapshot_json']===$v1Json,'publishing later versions does not mutate version 1 snapshot or hash');
$newTopics=living_research_topics($pdo,(int)$report2['id']);p24(array_column($newTopics,'topic_slug')===['broadband','arizona'],'new publication updates explicit report topics without changing old report snapshots');

$notices=notification_rows($pdo,$member,100,false);$foundV2=false;foreach($notices as $n){if(($n['notification_type']??'')==='research_report_updated'&&($n['object_public_id']??'')===$report2['public_id']){$foundV2=true;p24(($n['url']??'')==='/research-report.php?id='.rawurlencode((string)$report2['public_id']).'&v=2','subscriber update notification resolves to the exact immutable published version');break;}}p24($foundV2,'subscriber receives deduplicated in-app report update notification');
living_research_mark_read($pdo,$member,$report2,(int)$report2['current_version_id']);$rsRead=living_research_read_status($pdo,$member,$report2);p24(!$rsRead['updated_since_read']&&$rsRead['last_read_version']===2,'reading current version clears updated-since-read state');
living_research_mark_read($pdo,$member,$report2,(int)$v1['id']);$rsNoRegress=living_research_read_status($pdo,$member,$report2);p24($rsNoRegress['last_read_version']===2,'opening an older immutable version does not move reader state backward');

$publicProject=$pub('public-project');$pdo->prepare("INSERT INTO research_projects(public_id,owner_user_id,title,description,status) VALUES(?,?,?,?,'active')")->execute([$publicProject,$owner['id'],'Public Living Research','Public topic fixture']);$publicProjectId=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO project_sources(project_id,source_id,added_by_user_id) VALUES(?,?,?)')->execute([$publicProjectId,$sourceId,$owner['id']]);$publicAccess=project_access($pdo,$owner['id'],$publicProject);
$pubResult=research_report_publish($pdo,$publicAccess,$owner,'public','Public Phoenix Research','Public Living Research publication.','Phoenix, Infrastructure');$publicReport=research_report_access($pdo,(string)$pubResult['public_id'],$outsider);p24($publicReport!==null,'public Living Research report is accessible to unrelated signed-in reader');
$publicTopics=living_research_public_topics($pdo,50);$publicSlugs=array_column($publicTopics,'topic_slug');p24(in_array('phoenix',$publicSlugs,true)&&in_array('infrastructure',$publicSlugs,true)&&!in_array('arizona',$publicSlugs,true),'public topic discovery includes only topics from public reports');
$phoenixReports=living_research_public_topic_reports($pdo,'phoenix',50);p24(count($phoenixReports)===1&&$phoenixReports[0]['public_id']===$publicReport['public_id'],'public topic collection returns only the matching public report');

$pdo->prepare('DELETE FROM team_members WHERE team_id=? AND user_id=?')->execute([$teamId,$member['id']]);p24(research_report_access($pdo,(string)$report2['public_id'],$member)===null,'Team revocation removes report access immediately');p24(living_research_subscribed_reports($pdo,$member,20)===[],'revoked subscriber sees no inaccessible report in Living Research hub');
$visibleAfterRevoke=notification_rows($pdo,$member,100,false);$leak=false;foreach($visibleAfterRevoke as $n)if(($n['object_public_id']??'')===$report2['public_id'])$leak=true;p24(!$leak,'stored report update notification is hidden after Team access revocation');

$pdo->prepare("INSERT INTO source_versions(source_id,version_number,final_url,title,extracted_text,content_hash,captured_at) VALUES(?,3,?,'Living Research Source','Version three evidence.',?,NOW())")->execute([$sourceId,$url,hash('sha256','p24-v3-'.$run)]);$sv3=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE sources SET current_version_id=? WHERE id=?')->execute([$sv3,$sourceId]);
$r3=research_report_publish($pdo,$project,$owner,'team','Living Team Report','Versioned team publication.','Broadband, Arizona');p24(($r3['subscriber_notifications']??-1)===0,'publisher creates no update notification for subscriber whose current access was revoked');
$reportOwner=research_report_access($pdo,(string)$r3['public_id'],$owner);$v3=research_report_version($pdo,$reportOwner,3);$pdo->prepare('UPDATE research_report_versions SET created_at=DATE_SUB(NOW(),INTERVAL 2 MINUTE) WHERE id=?')->execute([$v3['id']]);
$pdo->prepare("INSERT INTO source_versions(source_id,version_number,final_url,title,extracted_text,content_hash,captured_at) VALUES(?,4,?,'Living Research Source','Version four evidence changed after publication.',?,NOW())")->execute([$sourceId,$url,hash('sha256','p24-v4-'.$run)]);$sv4=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE sources SET current_version_id=? WHERE id=?')->execute([$sv4,$sourceId]);$pdo->prepare("INSERT INTO source_change_events(source_id,previous_version_id,new_version_id,change_type,impact_type,target_changed,affected_annotation_count,diff_summary,created_at) VALUES(?,?,?,'edited','passage_changed',1,0,'Source changed after report version 3 was published.',NOW())")->execute([$sourceId,$sv3,$sv4]);
$stale=living_research_staleness($pdo,$owner,$reportOwner);p24($stale!==null&&str_contains((string)$stale['reason'],'Upstream source evidence changed'),'publisher receives derived freshness warning when upstream evidence changes after current publication');
$q=$pdo->prepare('SELECT COUNT(*) FROM research_report_versions WHERE report_id=?');$q->execute([$reportOwner['id']]);p24((int)$q->fetchColumn()===3,'freshness warning does not silently publish a fourth report version');

$runtime=file_get_contents($root.'/app/living-research.php');p24(!str_contains($runtime,'ai_run(')&&!str_contains($runtime,'UPDATE research_report_versions SET snapshot')&&!str_contains($runtime,'agent_action_confirm_execute('),'Living Research runtime has no AI ranker, silent snapshot rewrite, or direct Agent execution path');
echo "Phase 24 Living Research Publishing & Distribution MariaDB suite passed.\n";
