<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=getenv('DB_DSN')?:'';$dbUser=getenv('DB_USER')?:'root';$dbPass=getenv('DB_PASS')?:'';if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
require_once $root.'/app/installer.php';require_once $root.'/app/storage.php';require_once $root.'/app/functions.php';require_once $root.'/app/access.php';require_once $root.'/app/notifications.php';require_once $root.'/app/rate-limit.php';require_once $root.'/app/jobs.php';require_once $root.'/app/ai.php';require_once $root.'/app/source-integrity.php';require_once $root.'/app/annotation-intelligence.php';require_once $root.'/app/research-workspace.php';require_once $root.'/app/conversations.php';require_once $root.'/app/agent-actions.php';require_once $root.'/app/agent-chat.php';require_once $root.'/app/cognitive-feed.php';require_once $root.'/app/research-entities.php';require_once $root.'/app/proactive-intelligence.php';
function p17(bool $v,string $m): void {if(!$v)throw new RuntimeException('FAIL: '.$m);echo "PASS: $m\n";}
$run='p17'.substr(bin2hex(random_bytes(6)),0,10);$pub=fn(string $p)=>$p.'-'.$run.'-'.substr(bin2hex(random_bytes(3)),0,6);
$makeUser=function(string $name)use($pdo,$run,$pub): array{$username=substr(strtolower($name).'_'.$run,0,48);$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,email_verified_at,status,role,live_presence_mode) VALUES(?,?,?,?,NOW(),'active','user','cloaked')")->execute([$pub('u'),$username,$name,$username.'@example.test']);$id=(int)$pdo->lastInsertId();$pdo->prepare('INSERT IGNORE INTO user_preferences(user_id) VALUES(?)')->execute([$id]);$q=$pdo->prepare('SELECT * FROM users WHERE id=?');$q->execute([$id]);return $q->fetch();};
$owner=$makeUser('ProactiveOwner');$outsider=$makeUser('ProactiveOutsider');p17(proactive_intelligence_ready($pdo),'Phase 17 schema is available');
$prefs=proactive_preferences_set($pdo,$owner,'important',true);p17($prefs['proactive_notification_mode']==='important'&&$prefs['proactive_briefing_enabled']===1,'proactive preferences persist');

$projectPublic=$pub('project');$pdo->prepare("INSERT INTO research_projects(public_id,owner_user_id,title,description,status) VALUES(?,?,?,?,'active')")->execute([$projectPublic,$owner['id'],'Proactive Research','Stage 17 project']);$projectId=(int)$pdo->lastInsertId();
$url='https://example.com/'.$run.'/watched';$sourcePublic=$pub('source');$pdo->prepare("INSERT INTO sources(public_id,source_type,canonical_url,canonical_url_hash,domain,title,status,monitoring_enabled,moderation_status) VALUES(?,'webpage',?,?,?,'Proactive Source','updated',1,'visible')")->execute([$sourcePublic,$url,hash('sha256',$url),'example.com']);$sourceId=(int)$pdo->lastInsertId();
$pdo->prepare("INSERT INTO source_versions(source_id,version_number,final_url,title,extracted_text,content_hash) VALUES(?,1,?,'Proactive v1','Original',?)")->execute([$sourceId,$url,hash('sha256','p17-v1')]);$v1=(int)$pdo->lastInsertId();
$pdo->prepare("INSERT INTO source_versions(source_id,version_number,final_url,title,extracted_text,content_hash) VALUES(?,2,?,'Proactive v2','Changed',?)")->execute([$sourceId,$url,hash('sha256','p17-v2')]);$v2=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE sources SET current_version_id=? WHERE id=?')->execute([$v2,$sourceId]);
$pdo->prepare('INSERT INTO project_sources(project_id,source_id,added_by_user_id) VALUES(?,?,?)')->execute([$projectId,$sourceId,$owner['id']]);$pdo->prepare('INSERT INTO source_watches(source_id,user_id) VALUES(?,?)')->execute([$sourceId,$owner['id']]);
$pdo->prepare("INSERT INTO source_change_events(source_id,previous_version_id,new_version_id,change_type,impact_type,target_changed,affected_annotation_count,diff_summary,created_at) VALUES(?,?,?,'edited','passage_changed',1,2,'A watched passage changed materially.',NOW())")->execute([$sourceId,$v1,$v2]);

$claimPublic=$pub('claim');$pdo->prepare("INSERT INTO research_claims(public_id,project_id,created_by_user_id,statement,claim_type,status) VALUES(?,?,?,'Proactive claim needs verification','factual','unverified')")->execute([$claimPublic,$projectId,$owner['id']]);
$entityPublic=$pub('entity');$pdo->prepare("INSERT INTO research_entities(public_id,project_id,canonical_name,normalized_name,entity_type,created_by_user_id) VALUES(?,?,?,?,?,?)")->execute([$entityPublic,$projectId,'Proactive Entity','proactive entity','organization',$owner['id']]);

$watchProject=proactive_watch_upsert($pdo,$owner,'project',$projectPublic);$watchClaim=proactive_watch_upsert($pdo,$owner,'claim',$claimPublic);$watchEntity=proactive_watch_upsert($pdo,$owner,'entity',$entityPublic);$watchSource=proactive_watch_upsert($pdo,$owner,'source',$sourcePublic);$watchQuestion=proactive_watch_upsert($pdo,$owner,'question',null,'watched passage changed');
p17(count(proactive_watch_list($pdo,$owner))===5,'source, project, claim, entity, and question watches persist');
$denied=false;try{proactive_watch_upsert($pdo,$outsider,'project',$projectPublic);}catch(RuntimeException $e){$denied=true;}p17($denied,'inaccessible Research objects cannot be watched');
$teamPublic=$pub('team');$pdo->prepare('INSERT INTO teams(public_id,owner_user_id,name) VALUES(?,?,?)')->execute([$teamPublic,$owner['id'],'Proactive Team']);$teamId=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO team_members(team_id,user_id,role) VALUES(?,?,'owner')")->execute([$teamId,$owner['id']]);
$teamContext=['refs'=>[['type'=>'team','public_id'=>$teamPublic]]];p17(proactive_context_access($pdo,$owner,$teamContext),'current Team member may access proactive Team context');$pdo->prepare('DELETE FROM team_members WHERE team_id=? AND user_id=?')->execute([$teamId,$owner['id']]);p17(!proactive_context_access($pdo,$owner,$teamContext),'revoked Team member loses stored proactive Team context immediately');
$synthetic=['type'=>'recent_change','priority'=>'low','score'=>30,'title'=>'Routine project change','body'=>'Low priority project activity','actions'=>[cognitive_feed_action_link('Open Research','/research-project.php?id='.rawurlencode($projectPublic))]];
$importantWatch=['status'=>'active','watch_type'=>'project','object_public_id'=>$projectPublic,'alert_level'=>'important'];$allWatch=$importantWatch;$allWatch['alert_level']='all';$matched=null;
p17(!proactive_should_alert($synthetic,$owner,['proactive_notification_mode'=>'mentions'],[$importantWatch],$matched),'important-only watch does not escalate low-priority matching state');
$matched=null;p17(proactive_should_alert($synthetic,$owner,['proactive_notification_mode'=>'mentions'],[$allWatch],$matched),'all-activity watch can surface low-priority matching state');

$jobsBefore=(int)$pdo->query('SELECT COUNT(*) FROM ai_jobs')->fetchColumn();$sync=proactive_intelligence_sync($pdo,$owner);$jobsAfter=(int)$pdo->query('SELECT COUNT(*) FROM ai_jobs')->fetchColumn();
p17($jobsBefore===$jobsAfter,'proactive evaluation creates no AI ranking jobs');p17(($sync['evaluated']??0)>0&&($sync['notified']??0)>0,'important cognitive observations create proactive notifications');
$q=$pdo->prepare("SELECT * FROM notifications WHERE user_id=? AND notification_type='research_proactive' ORDER BY id DESC LIMIT 1");$q->execute([$owner['id']]);$notification=$q->fetch();p17((bool)$notification,'proactive notification is stored in the existing notification center');
$ctx=json_decode((string)$notification['context_json'],true)?:[];p17(!empty($ctx['why'])&&!empty($ctx['observation_key']),'proactive notification carries Why this matters and observation provenance');p17(!array_key_exists('actions',$ctx),'proactive notification does not persist stale Agent prompts or action payloads');
$countBefore=(int)$pdo->query("SELECT COUNT(*) FROM notifications WHERE user_id=".(int)$owner['id']." AND notification_type='research_proactive'")->fetchColumn();proactive_intelligence_sync($pdo,$owner);$countAfter=(int)$pdo->query("SELECT COUNT(*) FROM notifications WHERE user_id=".(int)$owner['id']." AND notification_type='research_proactive'")->fetchColumn();p17($countBefore===$countAfter,'repeated evaluation deduplicates unchanged proactive alerts');

$key=(string)$ctx['observation_key'];p17(proactive_alert_snooze($pdo,$owner,$key,24),'alert can be snoozed');$q=$pdo->prepare('SELECT state FROM cognitive_alert_states WHERE user_id=? AND observation_key=?');$q->execute([$owner['id'],$key]);p17($q->fetchColumn()==='snoozed','snooze state persists per user');
$pdo->prepare('UPDATE cognitive_alert_states SET snoozed_until=DATE_SUB(NOW(),INTERVAL 1 MINUTE) WHERE user_id=? AND observation_key=?')->execute([$owner['id'],$key]);$resumed=proactive_intelligence_sync($pdo,$owner);p17(($resumed['notified']??0)>=1,'expired snooze allows the alert to surface again');
p17(proactive_alert_resolve($pdo,$owner,$key),'alert can be resolved');proactive_intelligence_sync($pdo,$owner);$q=$pdo->prepare('SELECT state FROM cognitive_alert_states WHERE user_id=? AND observation_key=?');$q->execute([$owner['id'],$key]);p17($q->fetchColumn()==='resolved','resolved unchanged state stays resolved');

$liveFeed=cognitive_feed_compose($pdo,$owner,null,8,60);$sourceObservation=null;foreach(proactive_feed_items($liveFeed) as $candidate)if(($candidate['type']??'')==='source_change'){$sourceObservation=$candidate;break;}p17($sourceObservation!==null,'current source-change observation is available for Agent handoff');$handoff=proactive_agent_handoff($pdo,$owner,(string)$sourceObservation['key']);p17($handoff!==null&&!empty($handoff['prompt'])&&!empty($handoff['context']),'proactive Ask Agent handoff is rebuilt from current permission-checked observation');
$brief=proactive_briefing($pdo,$owner,3);p17(($brief['ready']??false)&&($brief['count']??0)>=1,'Agent briefing derives from current authoritative cognitive state');
p17(proactive_watch_remove($pdo,$owner,(string)$watchQuestion['public_id']),'question watch can be removed');
$outsiderBrief=proactive_briefing($pdo,$outsider,5);p17(!str_contains(json_encode($outsiderBrief,JSON_UNESCAPED_SLASHES),$projectPublic),'briefing cannot leak inaccessible Research identity');
echo "Phase 17 Proactive Research Intelligence MariaDB suite passed.\n";
