<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=getenv('DB_DSN')?:'';$dbUser=getenv('DB_USER')?:'root';$dbPass=getenv('DB_PASS')?:'';if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
foreach(['installer','storage','jobs','concurrency','functions','shell','access','notifications','rate-limit','ai','ai-access','source-integrity','annotation-intelligence','research-workspace','conversations','agent-actions','agent-chat','cognitive-feed','research-entities','proactive-intelligence','research-automation','cross-research','research-outcomes'] as $lib)require_once $root.'/app/'.$lib.'.php';
function p20(bool $ok,string $message): void {if(!$ok)throw new RuntimeException('FAIL: '.$message);echo "PASS: $message\n";}
$run='p20'.substr(bin2hex(random_bytes(6)),0,10);$pub=fn(string $p)=>$p.'-'.$run.'-'.substr(bin2hex(random_bytes(3)),0,6);
$makeUser=function(string $name,string $plan='pro')use($pdo,$run,$pub): array{$username=substr(strtolower($name).'_'.$run,0,48);$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,email_verified_at,status,role,plan_tier,live_presence_mode) VALUES(?,?,?,?,NOW(),'active','user',?,'cloaked')")->execute([$pub('u'),$username,$name,$username.'@example.test',$plan]);$id=(int)$pdo->lastInsertId();$pdo->prepare('INSERT IGNORE INTO user_preferences(user_id) VALUES(?)')->execute([$id]);$q=$pdo->prepare('SELECT * FROM users WHERE id=?');$q->execute([$id]);return $q->fetch();};
$owner=$makeUser('OutcomeOwner');$collab=$makeUser('OutcomeCollaborator');p20(research_outcomes_ready($pdo),'Phase 20 schema is available');

$projectPublic=$pub('project');$pdo->prepare("INSERT INTO research_projects(public_id,owner_user_id,title,description,status) VALUES(?,?,?,?,'active')")->execute([$projectPublic,$owner['id'],'Outcome Research','Decision-memory test project']);$projectId=(int)$pdo->lastInsertId();
$claimPublic=$pub('claim');$pdo->prepare("INSERT INTO research_claims(public_id,project_id,created_by_user_id,statement,claim_type,status) VALUES(?,?,?,'The outcome layer should remain explicit and inspectable.','factual','supported')")->execute([$claimPublic,$projectId,$owner['id']]);

$manual=research_outcome_manual($pdo,$owner,['project_id'=>$projectPublic,'decision_type'=>'recorded','title'=>'Verify vendor statement before publication','summary'=>'The team decided to verify the claim with an independent Source.','object_type'=>'claim','object_public_id'=>$claimPublic,'note'=>'Decision made after reviewing current evidence.']);
p20(!empty($manual['public_id']),'manual Decision Memory event can be recorded');
$manualAccess=research_outcome_access($pdo,$owner,(string)$manual['public_id']);p20($manualAccess!==null&&$manualAccess['project_public_id']===$projectPublic,'manual outcome is permission-scoped to its Research project');

$feedback=research_outcome_feedback_set($pdo,$owner,(string)$manual['public_id'],'helpful','follow_up','Independent verification is still needed.');p20($feedback['usefulness']==='helpful'&&$feedback['follow_up_state']==='follow_up','explicit usefulness and follow-up feedback persist');
$summary=research_outcome_summary($pdo,$owner,$projectPublic);p20($summary['helpful']===1&&$summary['follow_up']===1,'Decision Memory summary uses explicit feedback counts');

$feed=cognitive_feed_compose($pdo,$owner,null,8,80);$items=proactive_feed_items($feed);$follow=array_values(array_filter($items,fn($i)=>($i['type']??'')==='outcome_follow_up'));p20(count($follow)>=1,'follow-up Decision Memory event resurfaces in Cognitive Feed');
$watch=proactive_watch_upsert($pdo,$owner,'project',$projectPublic,null,'all');proactive_preferences_set($pdo,$owner,'mentions',true);proactive_intelligence_sync($pdo,$owner,$feed);
$q=$pdo->prepare("SELECT context_json FROM notifications WHERE user_id=? AND notification_type='research_proactive' ORDER BY id DESC LIMIT 50");$q->execute([$owner['id']]);$outcomeNotice=false;foreach($q->fetchAll(PDO::FETCH_COLUMN) as $json){$j=json_decode((string)$json,true)?:[];if(($j['observation_type']??'')==='outcome_follow_up'){$outcomeNotice=true;break;}}p20($outcomeNotice,'existing Stage 17 project watch can deliver Decision Memory follow-up');

$conversation=agent_chat_create($pdo,$owner,'Outcome Action Test');$userMessage=conversation_message_create($pdo,$owner,(string)$conversation['public_id'],'Create a bounded test proposal.',null,'p20-user-'.$run);$assistant=agent_chat_insert_agent_message($pdo,$conversation,'Proposal ready.',(int)$userMessage['id']);
$proposalPublic=$pub('proposal');$pdo->prepare("INSERT INTO agent_action_proposals(public_id,conversation_id,assistant_message_id,proposed_by_user_id,project_id,capability_key,status,arguments_json,provenance_json,project_state_hash,dedupe_key,result_type,result_public_id,result_json,expires_at,confirmed_at,executed_at)
 VALUES(?,?,?,?,?,'create_claim','executed','{}','{}',?,?, 'claim',?, ?,DATE_ADD(NOW(),INTERVAL 1 HOUR),NOW(),NOW())")->execute([$proposalPublic,$conversation['id'],$assistant['id'],$owner['id'],$projectId,hash('sha256','state-'.$run),hash('sha256','proposal-'.$run),$claimPublic,json_encode(['type'=>'claim','public_id'=>$claimPublic])]);
$jobsBefore=(int)$pdo->query('SELECT COUNT(*) FROM ai_jobs')->fetchColumn();research_outcome_sync_agent_actions($pdo,$owner,50);$jobsAfter=(int)$pdo->query('SELECT COUNT(*) FROM ai_jobs')->fetchColumn();p20($jobsBefore===$jobsAfter,'outcome synchronization creates no AI ranking or learning jobs');
$q=$pdo->prepare("SELECT public_id FROM research_outcome_events WHERE user_id=? AND source_type='agent_action' AND source_public_id=? LIMIT 1");$q->execute([$owner['id'],$proposalPublic]);$agentOutcome=(string)$q->fetchColumn();p20($agentOutcome!=='','executed Stage 15 proposal becomes a Decision Memory event');
$agentRow=research_outcome_access($pdo,$owner,$agentOutcome);p20($agentRow!==null&&$agentRow['result_type']==='claim'&&$agentRow['result_public_id']===$claimPublic,'Agent outcome preserves result provenance');

$obsKey=hash('sha256','p20-dismiss-'.$run);cognitive_feed_dismiss($pdo,$owner,$obsKey,'research_gap');$q=$pdo->prepare("SELECT COUNT(*) FROM research_outcome_events WHERE user_id=? AND source_type='cognitive_observation' AND source_public_id=?");$q->execute([$owner['id'],$obsKey]);p20((int)$q->fetchColumn()===1,'explicit Cognitive Feed dismissal is captured as an outcome');

$automation=research_automation_create($pdo,$owner,['title'=>'Outcome Source Refresh','project_id'=>$projectPublic,'workflow_type'=>'source_refresh','trigger_type'=>'schedule','cadence'=>'manual','timezone_name'=>'UTC']);
$autoRunPublic=$pub('autorun');$pdo->prepare("INSERT INTO research_automation_runs(public_id,automation_id,user_id,project_id,trigger_type,trigger_key,status,attempts,output_text,proposal_count,completed_at) VALUES(?,?,?,?, 'manual',?,'completed',1,'Source refresh completed.',0,NOW())")->execute([$autoRunPublic,$automation['id'],$owner['id'],$projectId,hash('sha256','autorun-'.$run)]);research_outcome_sync_automations($pdo,$owner,50);
$q=$pdo->prepare("SELECT COUNT(*) FROM research_outcome_events WHERE user_id=? AND source_type='automation_run' AND source_public_id=? AND decision_type='completed'");$q->execute([$owner['id'],$autoRunPublic]);p20((int)$q->fetchColumn()===1,'completed Research Automation run becomes a Decision Memory event');

$projectB=$pub('project-b');$pdo->prepare("INSERT INTO research_projects(public_id,owner_user_id,title,description,status) VALUES(?,?,?,?,'active')")->execute([$projectB,$owner['id'],'Outcome Related Project','Cross-Research outcome fixture']);$projectBId=(int)$pdo->lastInsertId();
$url='https://example.com/'.$run.'/shared';$sourcePublic=$pub('source');$pdo->prepare("INSERT INTO sources(public_id,source_type,canonical_url,canonical_url_hash,domain,title,status,monitoring_enabled,moderation_status) VALUES(?,'article',?,?,?,'Outcome Shared Source','current',1,'visible')")->execute([$sourcePublic,$url,hash('sha256',$url),'example.com']);$sourceId=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO project_sources(project_id,source_id,added_by_user_id) VALUES(?,?,?),(?,?,?)')->execute([$projectId,$sourceId,$owner['id'],$projectBId,$sourceId,$owner['id']]);
$cross=array_values(array_filter(cross_research_suggestions($pdo,$owner,null,100,false),fn($s)=>($s['type']??'')==='shared_source'))[0]??null;p20($cross!==null,'Cross-Research fixture produces an explicit suggestion');$crossLink=cross_research_accept($pdo,$owner,(string)$cross['key'],'shared_source');$q=$pdo->prepare("SELECT COUNT(*) FROM research_outcome_events WHERE user_id=? AND source_type='cross_research_suggestion' AND source_public_id=? AND decision_type='accepted'");$q->execute([$owner['id'],$cross['key']]);p20((int)$q->fetchColumn()===1,'accepted Cross-Research relationship becomes a Decision Memory event');

$agentContext=agent_chat_context_item($pdo,$owner,'research',$projectPublic);p20($agentContext!==null&&str_contains((string)$agentContext['text'],'[DECISION MEMORY / OUTCOMES]'),'primary Agent receives permission-checked project Decision Memory');

$outcomeAuto=research_automation_create($pdo,$owner,['title'=>'Weekly Outcome Review','project_id'=>$projectPublic,'workflow_type'=>'outcome_review','trigger_type'=>'schedule','cadence'=>'weekly','timezone_name'=>'America/Phoenix','run_time_local'=>'09:00','weekday'=>1]);
$aiBefore=(int)$pdo->query('SELECT COUNT(*) FROM ai_jobs')->fetchColumn();$result=research_automation_execute($pdo,[],['automation_id'=>$outcomeAuto['id'],'user_id'=>$owner['id'],'trigger_type'=>'manual']);$aiAfter=(int)$pdo->query('SELECT COUNT(*) FROM ai_jobs')->fetchColumn();p20($result['status']==='completed'&&$result['ai_run']===null&&$result['proposals']===0&&str_contains($result['output'],'Outcome review'),'Outcome Review automation is deterministic and read-only');p20($aiBefore===$aiAfter,'Outcome Review automation creates no AI job');

$teamPublic=$pub('team');$pdo->prepare('INSERT INTO teams(public_id,owner_user_id,name) VALUES(?,?,?)')->execute([$teamPublic,$owner['id'],'Outcome Team']);$teamId=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO team_members(team_id,user_id,role) VALUES(?,?,'owner'),(?,?,'researcher')")->execute([$teamId,$owner['id'],$teamId,$collab['id']]);
$teamProject=$pub('team-project');$pdo->prepare("INSERT INTO research_projects(public_id,owner_user_id,team_id,title,description,status) VALUES(?,?,?,?,?,'active')")->execute([$teamProject,$owner['id'],$teamId,'Team Decision Memory','Revocation fixture']);$teamOutcome=research_outcome_manual($pdo,$collab,['project_id'=>$teamProject,'decision_type'=>'recorded','title'=>'Collaborator decision','summary'=>'Visible only while project access remains.']);p20(research_outcome_access($pdo,$collab,(string)$teamOutcome['public_id'])!==null,'collaborator can see own Decision Memory while project access exists');
$pdo->prepare('DELETE FROM team_members WHERE team_id=? AND user_id=?')->execute([$teamId,$collab['id']]);p20(research_outcome_access($pdo,$collab,(string)$teamOutcome['public_id'])===null,'revoked project access immediately hides stored Decision Memory context');p20(count(research_outcome_list($pdo,$collab,$teamProject,null,50))===0,'revoked project access leaks no outcome through filtered list');

$runtime=file_get_contents($root.'/app/research-outcomes.php');p20(!str_contains($runtime,'ai_run(')&&!str_contains($runtime,'agent_action_confirm_execute(')&&!str_contains($runtime,'agent_action_execute_capability('),'Decision Memory runtime has no hidden AI learner or Research execution path');
echo "Phase 20 Outcome Learning & Decision Memory MariaDB suite passed.\n";
