<?php
declare(strict_types=1);$root=dirname(__DIR__);$fail=[];
$manifest=json_decode((string)file_get_contents($root.'/extension/manifest.json'),true);if(($manifest['manifest_version']??null)!==3)$fail[]='Chrome extension must remain Manifest V3.';
$annotation=(string)file_get_contents($root.'/annotation.php');$annotationUi=(string)file_get_contents($root.'/app/annotation-ui.php');if(!str_contains($annotationUi,'File a claim'))$fail[]='Shared annotation post menu must expose File a claim.';if(!str_contains($annotationUi,'Report post'))$fail[]='Shared annotation post menu must expose Report.';
$api='';foreach(glob($root.'/api/*.php') as $f)$api.="\n".file_get_contents($f);if(!str_contains($api,'90'))$fail[]='Server/API must contain the 90-second media limit contract.';
$migrations=array_values(array_filter(glob($root.'/database/migrations/*.sql')?:[],'is_file'));sort($migrations,SORT_STRING);$seen=[];$last='';foreach($migrations as $file){$base=basename($file);if(!preg_match('/^(\d{8}_\d{3})_/', $base,$m)){$fail[]="Invalid migration filename: $base";continue;}if(isset($seen[$m[1]]))$fail[]="Duplicate migration version: {$m[1]}";$seen[$m[1]]=1;if($last!==''&&strcmp($m[1],$last)<=0)$fail[]='Migrations are not strictly ordered.';$last=$m[1];}
foreach(['20260917_003_profiles_settings_search_collections.sql','20260917_004_ai_admin_research_monitoring.sql','20260917_006_worker_leases.sql','20260917_008_research_claims_findings.sql','20260917_009_research_briefs_claim_graph.sql','20260917_010_research_entities_knowledge_graph.sql','20260917_011_research_reports.sql','20260917_012_rich_capture.sql','20260917_013_this_page_following.sql','20260917_014_live_rooms_cloak.sql','20260917_015_notifications_trust.sql','20260918_016_search_discovery.sql','20260918_017_release_hardening.sql','20260919_018_annotation_reactions.sql','20260919_019_conversation_runtime.sql','20260920_020_annotation_intelligence.sql','20260920_021_research_workspace_intelligence.sql'] as $required)if(!is_file($root.'/database/migrations/'.$required))$fail[]="Required migration missing: $required";
foreach(['app/ai.php','admin/ai.php','admin/assistant.php','admin/moderation.php','admin/source-monitor.php','worker/ai-worker.php','worker/source-monitor-worker.php','research-project.php','ai.php'] as $required)if(!is_file($root.'/'.$required))$fail[]="AI/admin/research file missing: $required";
foreach(['app/research-knowledge.php','research-knowledge.php','research-claim.php','research-finding.php','tests/research-knowledge-db.php'] as $required)if(!is_file($root.'/'.$required))$fail[]="Research knowledge file missing: $required";
foreach(['app/research-intelligence.php','research-brief.php','research-timeline.php','research-graph.php','tests/research-intelligence-db.php'] as $required)if(!is_file($root.'/'.$required))$fail[]="Research intelligence file missing: $required";
foreach(['app/research-entities.php','research-entities.php','research-entity.php','tests/research-entities-db.php'] as $required)if(!is_file($root.'/'.$required))$fail[]="Research entity graph file missing: $required";
foreach(['app/research-reports.php','research-publish.php','research-report.php','research-report-export.php','tests/research-reports-db.php'] as $required)if(!is_file($root.'/'.$required))$fail[]="Research publishing file missing: $required";
foreach(['app/rich-capture.php','api/extension-capture.php','tests/rich-capture-db.php'] as $required)if(!is_file($root.'/'.$required))$fail[]="Rich Capture file missing: $required";
foreach(['app/public-discovery.php','tests/phase7-public-discovery-db.php'] as $required)if(!is_file($root.'/'.$required))$fail[]="Phase 7 public discovery file missing: $required";
$phase7=(string)file_get_contents($root.'/app/public-discovery.php');foreach(['public_discovery_annotation','public_discovery_source','public_discovery_profile','public_discovery_explore','public_discovery_search'] as $needle)if(!str_contains($phase7,$needle))$fail[]="Phase 7 discovery helper missing: $needle";
foreach(['source.php','annotation.php','profile.php','explore.php','search.php'] as $file){$body=(string)file_get_contents($root.'/'.$file);if(!str_contains($body,'public-discovery.php'))$fail[]="Phase 7 page must use shared public discovery service: $file";}
$annotationPage=(string)file_get_contents($root.'/annotation.php');foreach(['og:title','noindex,nofollow','annotation_ui_card','annotationDiscussion'] as $needle)if(!str_contains($annotationPage,$needle))$fail[]="Phase 7 annotation page contract missing: $needle";foreach(['File a claim','Report post','data-web-annotation-action="research"'] as $needle)if(!str_contains($annotationUi,$needle))$fail[]="Shared annotation post action contract missing: $needle";
$sourcePage=(string)file_get_contents($root.'/source.php');foreach(['og:title','noindex,nofollow','Source history','Follow source','annotation_ui_card'] as $needle)if(!str_contains($sourcePage,$needle))$fail[]="Phase 7 source page contract missing: $needle";
$searchPage=(string)file_get_contents($root.'/search.php');foreach(['Research reports','searchMatch','research-report.php'] as $needle)if(!str_contains($searchPage,$needle))$fail[]="Phase 7 search contract missing: $needle";
$manifest11=json_decode((string)file_get_contents($root.'/extension/manifest.json'),true);if(($manifest11['version']??'')!=='0.14.0')$fail[]='Phase 14 extension version must be 0.14.0.';
foreach(['app/conversations.php','api/conversations.php','assets/js/team-chat.js','assets/js/chat-presence.js','chat-settings.php','tests/phase12a-conversations-db.php','app/agent-chat.php','api/agent-chat.php','assets/js/agent-chat.js','tests/phase12b-agent-chat-db.php'] as $required)if(!is_file($root.'/'.$required))$fail[]="Phase 12A conversation file missing: $required";
$phase12Migration=(string)file_get_contents($root.'/database/migrations/20260919_019_conversation_runtime.sql');foreach(['conversations','conversation_members','conversation_messages','conversation_message_attachments','conversation_events','last_read_message_id','client_message_id','chat_status_preferences','chat_presence_sessions'] as $needle)if(!str_contains($phase12Migration,$needle))$fail[]="Phase 12A migration contract missing: $needle";
$phase12=(string)file_get_contents($root.'/app/conversations.php');foreach(['conversation_runtime_ready','conversation_team_ensure','conversation_access','conversation_team_list','conversation_message_rows','conversation_message_create','conversation_mark_read','conversation_presence_ready','conversation_presence_touch','conversation_presence_rows','conversation_status_update'] as $needle)if(!str_contains($phase12,$needle))$fail[]="Phase 12A conversation helper missing: $needle";

foreach(['app/annotation-intelligence.php','api/annotation-intelligence.php','bin/queue-annotation-intelligence.php','tests/phase13-annotation-intelligence-db.php'] as $required)if(!is_file($root.'/'.$required))$fail[]="Phase 13 Annotation Intelligence file missing: $required";
$phase13Migration=(string)file_get_contents($root.'/database/migrations/20260920_020_annotation_intelligence.sql');foreach(['annotation_intelligence','annotation_relationships','annotation_intelligence_model_id','claims_json','confidence','corroborates','conflicts','generated_by'] as $needle)if(!str_contains($phase13Migration,$needle))$fail[]="Phase 13 migration contract missing: $needle";
$phase13=(string)file_get_contents($root.'/app/annotation-intelligence.php');foreach(['annotation_intelligence_queue','annotation_intelligence_apply_ai_output','annotation_intelligence_visible_relationships','annotation_intelligence_context_text','annotation_intelligence_has_analyzable_content'] as $needle)if(!str_contains($phase13,$needle))$fail[]="Phase 13 runtime helper missing: $needle";
$phase13Worker=(string)file_get_contents($root.'/worker/ai-worker.php');foreach(['annotation_intelligence','annotation_intelligence_apply_ai_output','ANNOTATION TO ANALYZE'] as $needle)if(!str_contains($phase13Worker,$needle))$fail[]="Phase 13 AI worker contract missing: $needle";
$phase13Ui=(string)file_get_contents($root.'/app/annotation-ui.php');foreach(['annotationIntelligencePanel','Derived analysis','Claims detected','Related evidence'] as $needle)if(!str_contains($phase13Ui,$needle))$fail[]="Phase 13 web intelligence UI contract missing: $needle";
$phase13Chrome=(string)file_get_contents($root.'/extension/sidepanel-feed.js');foreach(['phase13Intelligence','open-related','Claims detected','Derived analysis'] as $needle)if(!str_contains($phase13Chrome,$needle))$fail[]="Phase 13 Chrome intelligence UI contract missing: $needle";

foreach(['app/research-workspace.php','api/research-workspace.php','assets/js/research-workspace.js','assets/js/research-agent.js','bin/queue-research-workspaces.php','tests/phase14-research-workspace-db.php'] as $required)if(!is_file($root.'/'.$required))$fail[]="Phase 14 Research Workspace file missing: $required";
$phase14Migration=(string)file_get_contents($root.'/database/migrations/20260920_021_research_workspace_intelligence.sql');foreach(['research_workspace_intelligence','input_hash','highlights_json','gaps_json','conflicts_json','source_risks_json','next_actions_json','ai_run_public_id'] as $needle)if(!str_contains($phase14Migration,$needle))$fail[]="Phase 14 migration contract missing: $needle";
$phase14=(string)file_get_contents($root.'/app/research-workspace.php');foreach(['research_workspace_deterministic_snapshot','research_workspace_queue','research_workspace_apply_ai_output','research_workspace_context','research_workspace_source_risks','research_workspace_annotation_links'] as $needle)if(!str_contains($phase14,$needle))$fail[]="Phase 14 runtime helper missing: $needle";
$phase14Worker=(string)file_get_contents($root.'/worker/ai-worker.php');foreach(['research_workspace_intelligence','research_workspace_apply_ai_output','DETERMINISTIC WORKSPACE NOW'] as $needle)if(!str_contains($phase14Worker,$needle))$fail[]="Phase 14 worker contract missing: $needle";
$phase14Page=(string)file_get_contents($root.'/research-project.php');foreach(['data-research-now','NEEDS ATTENTION','NEXT ACTIONS','data-research-agent-composer','researchWorkspaceRail'] as $needle)if(!str_contains($phase14Page,$needle))$fail[]="Phase 14 Research workspace UI contract missing: $needle";


foreach(['app/live.php','live.php','tests/phase8-live-db.php'] as $required)if(!is_file($root.'/'.$required))$fail[]="Phase 8 Live file missing: $required";
$phase8Migration=(string)file_get_contents($root.'/database/migrations/20260917_014_live_rooms_cloak.sql');foreach(['live_presence_sessions',"ENUM('public','team','project')",'identity_mode','client_message_id','live_message_reactions','live_events'] as $needle)if(!str_contains($phase8Migration,$needle))$fail[]="Phase 8 migration contract missing: $needle";
$phase8=(string)file_get_contents($root.'/app/live.php');foreach(['live_room_scope','live_presence_touch','live_presence_cleanup','live_message_create','live_message_rows','live_event_rows','live_message_react'] as $needle)if(!str_contains($phase8,$needle))$fail[]="Phase 8 Live helper missing: $needle";
$liveSidebar=(string)file_get_contents($root.'/extension/sidepanel-social.js');foreach(['live_rooms','client_session_id','scheduleLivePoll','client_message_id','live_message_pin','live_react'] as $needle)if(!str_contains($liveSidebar,$needle))$fail[]="Phase 8 extension Live contract missing: $needle";
$liveHtml=(string)file_get_contents($root.'/extension/sidepanel.html');foreach(['liveEvents','liveReveal','Reveal my identity for this message'] as $needle)if(!str_contains($liveHtml,$needle))$fail[]="Phase 8 Live UI contract missing: $needle";
if(!str_contains((string)file_get_contents($root.'/source.php'),'Open Live'))$fail[]='Source page must deep-link into website Live.';
foreach(['app/notifications.php','app/source-integrity.php','app/moderation.php','api/extension-trust.php','claim-status.php','report-status.php','tests/phase9-trust-db.php'] as $required)if(!is_file($root.'/'.$required))$fail[]="Phase 9 trust file missing: $required";
$phase9Migration=(string)file_get_contents($root.'/database/migrations/20260917_015_notifications_trust.sql');foreach(['dedupe_key','notification_mutes','source_annotation_impacts','impact_type','tracking_token_hash','rights_claim_events','resolution_action','moderation_status'] as $needle)if(!str_contains($phase9Migration,$needle))$fail[]="Phase 9 migration contract missing: $needle";
$phase9Notifications=(string)file_get_contents($root.'/app/notifications.php');foreach(['notification_create','notification_rows','notification_object_access','notification_mute_set','dedupe_key','group_key'] as $needle)if(!str_contains($phase9Notifications,$needle))$fail[]="Phase 9 notification helper missing: $needle";
$phase9Integrity=(string)file_get_contents($root.'/app/source-integrity.php');foreach(['passage_changed','passage_missing','source_unavailable','source_restored','source_integrity_analyze_event','source_integrity_notify_event'] as $needle)if(!str_contains($phase9Integrity,$needle))$fail[]="Phase 9 integrity helper missing: $needle";
$phase9Moderation=(string)file_get_contents($root.'/app/moderation.php');foreach(['moderation_report_create','moderation_report_update','moderation_apply_object_action','rights_claim_create','rights_claim_access','rights_claim_appeal'] as $needle)if(!str_contains($phase9Moderation,$needle))$fail[]="Phase 9 moderation helper missing: $needle";
$phase9Chrome=(string)file_get_contents($root.'/extension/sidepanel-social.js');foreach(['notification_read_all','notification_archive','notification_mute','reportObject'] as $needle)if(!str_contains($phase9Chrome,$needle))$fail[]="Phase 9 Chrome trust contract missing: $needle";
$phase9Feed=(string)file_get_contents($root.'/extension/sidepanel-feed.js');if(substr_count($phase9Feed,'async function phase6SwitchTab(')!==1)$fail[]='Chrome feed must have exactly one Phase 6 tab dispatcher.';if(str_contains($phase9Feed,'loadLiveTeams();loadLive();'))$fail[]='Legacy Live polling entrypoint must not override the Phase 8 reconnecting Live protocol.';
foreach(['notifications.php','settings.php','admin/moderation.php','source.php','annotation.php'] as $page){$body=(string)file_get_contents($root.'/'.$page);if(!str_contains($body,'Phase 9')&&$page==='admin/moderation.php'){}}
foreach(['app/search.php','api/extension-search.php','extension/sidepanel-search.js','entity.php','admin/discovery-entities.php','worker/saved-search-worker.php','bin/rebuild-discovery-index.php','tests/phase10-search-db.php'] as $required)if(!is_file($root.'/'.$required))$fail[]="Phase 10 search file missing: $required";
$phase10Migration=(string)file_get_contents($root.'/database/migrations/20260918_016_search_discovery.sql');foreach(['saved_searches','saved_search_matches','search_recent_queries','discovery_entities','discovery_entity_aliases','discovery_entity_mentions','origin_report_public_id'] as $needle)if(!str_contains($phase10Migration,$needle))$fail[]="Phase 10 migration contract missing: $needle";
$phase10Search=(string)file_get_contents($root.'/app/search.php');foreach(['search_unified','search_annotation_access_sql','search_source_visible','search_saved_create','search_saved_access','search_saved_alert_worker','search_sync_public_report_entities','search_remove_public_report_entities','search_related_sources','search_related_annotations','search_explore_intelligence'] as $needle)if(!str_contains($phase10Search,$needle))$fail[]="Phase 10 search helper missing: $needle";
$phase10Page=(string)file_get_contents($root.'/search.php');foreach(['search_unified($pdo,$term,$viewer,$filters)','Save this search','Add to Research','Recent searches','Research reports'] as $needle)if(!str_contains($phase10Page,$needle))$fail[]="Phase 10 search page contract missing: $needle";
$phase10Explore=(string)file_get_contents($root.'/explore.php');foreach(['search_explore_intelligence','TRENDING · 7 DAYS','TOPICS & ENTITIES','BECAUSE YOU FOLLOW'] as $needle)if(!str_contains($phase10Explore,$needle))$fail[]="Phase 10 Explore contract missing: $needle";
$phase10Chrome=(string)file_get_contents($root.'/extension/sidepanel-search.js');foreach(['runSidebarSearch','search_saved','search_recent','search_add_research'] as $needle)if(!str_contains($phase10Chrome,$needle))$fail[]="Phase 10 Chrome search contract missing: $needle";
$phase10Feed=(string)file_get_contents($root.'/extension/sidepanel-feed.js');foreach(["document.querySelectorAll('nav [role=\"tab\"]').forEach","document.querySelectorAll('main>section[role=\"tabpanel\"]').forEach"] as $needle)if(!str_contains($phase10Feed,$needle))$fail[]="Chrome tab dispatcher must iterate a NodeList: $needle";if(preg_match("/(?<!\\$)\\$\\('[^']+'\\)\\.forEach/",$phase10Feed))$fail[]='Chrome tab dispatcher must not call forEach on querySelector result.';
foreach(['app/release.php','app/installer.php','install.php','onboarding.php','admin/system-health.php','bin/release-preflight.php','docs/RELEASE-V1.1-RC1.md','.github/workflows/release-rc.yml','tests/phase11-release-db.php','tests/install-db.php','tests/v1-rc-e2e-contract.php'] as $required)if(!is_file($root.'/'.$required))$fail[]="Phase 11 release file missing: $required";
$phase11Migration=(string)file_get_contents($root.'/database/migrations/20260918_017_release_hardening.sql');foreach(['user_onboarding','worker_heartbeats','sessions_revoked_before','client_version','idx_extension_session_user_active'] as $needle)if(!str_contains($phase11Migration,$needle))$fail[]="Phase 11 migration contract missing: $needle";
$phase11Release=(string)file_get_contents($root.'/app/release.php');foreach(['ANNOTATED_RELEASE','1.1.0-rc1','onboarding_status','onboarding_should_redirect','release_worker_heartbeat','release_worker_health','release_queue_health','release_environment_checks'] as $needle)if(!str_contains($phase11Release,$needle))$fail[]="Phase 11 release helper missing: $needle";
$phase11Init=(string)file_get_contents($root.'/extension/sidepanel-init.js');if(preg_match("/(?<!\\$)\\$\\('nav button'\\)\\.forEach/",$phase11Init))$fail[]='Phase 11 sidebar nav must not call forEach on querySelector.';if(preg_match("/(?<!\\$)\\$\\('\\.modes button'\\)\\.forEach/",$phase11Init))$fail[]='Phase 11 capture modes must not call forEach on querySelector.';
$phase11Html=(string)file_get_contents($root.'/extension/sidepanel.html');foreach(['role="tablist"','role="tabpanel"','aria-selected','aria-live="polite"'] as $needle)if(!str_contains($phase11Html,$needle))$fail[]="Phase 11 accessibility contract missing: $needle";
if(($manifest11['minimum_chrome_version']??'')!=='116')$fail[]='Phase 11 RC must declare Chrome 116+.';
$releaseWorkflow=(string)file_get_contents($root.'/.github/workflows/release-rc.yml');foreach(['Annotated-Website.zip','Annotated-Chrome-Extension.zip','sha256sum'] as $needle)if(!str_contains($releaseWorkflow,$needle))$fail[]="RC packaging workflow contract missing: $needle";
foreach(['media-worker.php'=>'media','transcription-worker.php'=>'transcription','source-monitor-worker.php'=>'source_monitor','ai-worker.php'=>'ai','saved-search-worker.php'=>'saved_search'] as $file=>$name){$body=(string)file_get_contents($root.'/worker/'.$file);if(!str_contains($body,"release_worker_heartbeat(\$pdo,'$name'"))$fail[]="Phase 11 worker heartbeat missing: $file";}




$reactionMigration=(string)file_get_contents($root.'/database/migrations/20260919_018_annotation_reactions.sql');foreach(['annotation_reactions',"reaction VARCHAR(32)","DEFAULT 'like'"] as $needle)if(!str_contains($reactionMigration,$needle))$fail[]="Annotation reaction migration contract missing: $needle";
$annotationUi=(string)file_get_contents($root.'/app/annotation-ui.php');foreach(['annotation_type_label','annotationSourceDetails','annotationSocialBar','like_count','comment_count'] as $needle)if(!str_contains($annotationUi,$needle))$fail[]="Unified annotation UI contract missing: $needle";
$feedUi=(string)file_get_contents($root.'/app/feed.php');foreach(['feed_toggle_annotation_like','annotation_reactions','a.user_id=$uid OR EXISTS','feed_annotation_post_type',"'image_quote'","'podcast'","'music'","'note'"] as $needle)if(!str_contains($feedUi,$needle))$fail[]="Unified annotation feed contract missing: $needle";
foreach(['app/feed.php','api/extension-feed.php','extension/sidepanel-feed.js','tests/phase6-feeds-db.php'] as $required)if(!is_file($root.'/'.$required))$fail[]="Phase 6 feed file missing: $required";
$phase6Migration=(string)file_get_contents($root.'/database/migrations/20260917_013_this_page_following.sql');foreach(['source_url_aliases','feed_reads'] as $needle)if(!str_contains($phase6Migration,$needle))$fail[]="Phase 6 migration contract missing: $needle";
$phase6Feed=(string)file_get_contents($root.'/app/feed.php');foreach(['feed_annotation_rows','feed_following_unread_count','feed_mark_read','feed_create_comment','source_watches'] as $needle)if(!str_contains($phase6Feed,$needle))$fail[]="Phase 6 feed contract missing: $needle";
$phase6Sidebar=(string)file_get_contents($root.'/extension/sidepanel-feed.js');foreach(['IntersectionObserver','Source content','feed_comments','source-follow','unread','phase6HydrateEvidence','annotation_react'] as $needle)if(!str_contains($phase6Sidebar,$needle))$fail[]="Phase 6 sidebar contract missing: $needle";

$richMigration=(string)file_get_contents($root.'/database/migrations/20260917_012_rich_capture.sql');foreach(['media_uploads','media_provider','provider_media_id','input_is_clip'] as $needle)if(!str_contains($richMigration,$needle))$fail[]="Rich Capture migration contract missing: $needle";
$rich=(string)file_get_contents($root.'/app/rich-capture.php');foreach(['rich_capture_upload_start','rich_capture_upload_append','rich_capture_upload_for_publish','rich_capture_mark_consumed','rich_capture_project_for_publish'] as $needle)if(!str_contains($rich,$needle))$fail[]="Rich Capture helper missing: $needle";
$manifestBody=(string)file_get_contents($root.'/extension/manifest.json');if(!str_contains($manifestBody,'tabCapture'))$fail[]='Rich Capture extension must request tabCapture permission.';
$captureJs=(string)file_get_contents($root.'/extension/sidepanel-capture.js');foreach(['annotated:get-tab-media-stream-id','media_upload_start','media_upload_chunk','90','media_upload_id'] as $needle)if(!str_contains($captureJs,$needle))$fail[]="Rich Capture extension contract missing: $needle";

$knowledgeMigration=(string)file_get_contents($root.'/database/migrations/20260917_008_research_claims_findings.sql');foreach(['research_claims','claim_evidence','research_findings','finding_claims','source_version_id'] as $needle)if(!str_contains($knowledgeMigration,$needle))$fail[]="Research knowledge migration contract missing: $needle";
$knowledge=(string)file_get_contents($root.'/app/research-knowledge.php');foreach(['research_claim_access','research_finding_access','research_knowledge_ai_context'] as $needle)if(!str_contains($knowledge,$needle))$fail[]="Research knowledge helper missing: $needle";
$intelligenceMigration=(string)file_get_contents($root.'/database/migrations/20260917_009_research_briefs_claim_graph.sql');foreach(['claim_relations','research_briefs','fk_claim_relation_source_project','fk_claim_relation_target_project'] as $needle)if(!str_contains($intelligenceMigration,$needle))$fail[]="Research intelligence migration contract missing: $needle";
$intelligence=(string)file_get_contents($root.'/app/research-intelligence.php');foreach(['research_project_timeline','research_project_brief_snapshot','research_project_graph_rows','research_intelligence_ai_context'] as $needle)if(!str_contains($intelligence,$needle))$fail[]="Research intelligence helper missing: $needle";
$entityMigration=(string)file_get_contents($root.'/database/migrations/20260917_010_research_entities_knowledge_graph.sql');foreach(['research_entities','research_entity_mentions','research_entity_relations','source_version_id','fk_entity_relation_source_project','fk_entity_relation_target_project'] as $needle)if(!str_contains($entityMigration,$needle))$fail[]="Research entity migration contract missing: $needle";
$entities=(string)file_get_contents($root.'/app/research-entities.php');foreach(['research_entity_access','research_entity_attach_reference','research_entity_graph_ai_context','research_apply_ai_entities'] as $needle)if(!str_contains($entities,$needle))$fail[]="Research entity helper missing: $needle";
$reportMigration=(string)file_get_contents($root.'/database/migrations/20260917_011_research_reports.sql');foreach(['research_reports','research_report_versions','snapshot_json','snapshot_hash','visibility'] as $needle)if(!str_contains($reportMigration,$needle))$fail[]="Research report migration contract missing: $needle";
$reports=(string)file_get_contents($root.'/app/research-reports.php');foreach(['research_report_can_publish','research_report_access','research_report_build_snapshot','research_report_publish','research_report_annotation_allowed'] as $needle)if(!str_contains($reports,$needle))$fail[]="Research publishing helper missing: $needle";
$reportPage=(string)file_get_contents($root.'/research-report.php');if(!str_contains($reportPage,'Immutable snapshot'))$fail[]='Research report must describe immutable snapshot semantics.';
$publishPage=(string)file_get_contents($root.'/research-publish.php');foreach(['Public snapshots downgrade non-public Annotation references','Notes, tasks, AI prompts/runs','unreviewed AI entities stay internal'] as $needle)if(!str_contains($publishPage,$needle))$fail[]="Research publishing privacy contract missing: $needle";
$ai=(string)file_get_contents($root.'/app/ai.php');foreach(['openai','anthropic','gemini','openai_compatible'] as $provider)if(!str_contains($ai,$provider))$fail[]="AI provider adapter missing: $provider";if(!str_contains($ai,'api_key_ciphertext'))$fail[]='AI provider secrets must use encrypted DB storage.';
$moderation=(string)file_get_contents($root.'/admin/moderation.php');if(!str_contains($moderation,'advisory only'))$fail[]='Moderation UI must state that AI triage is advisory only.';
$sourceWorker=(string)file_get_contents($root.'/worker/source-monitor-worker.php');if(!str_contains($sourceWorker,'fetch_public_url'))$fail[]='Source monitor must use guarded public URL fetch.';
$config=(string)file_get_contents($root.'/config.example.php');if(!str_contains($config,'encryption_key'))$fail[]='Config must expose an AI secret encryption key setting.';
if($fail){foreach($fail as $f)fwrite(STDERR,"FAIL: $f\n");exit(1);}echo "Release contracts passed (".count($migrations)." migrations).\n";
