<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=(string)getenv('DB_DSN');$dbUser=(string)getenv('DB_USER');$dbPass=(string)getenv('DB_PASS');if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
require_once $root.'/app/storage.php';require_once $root.'/app/functions.php';require_once $root.'/app/access.php';require_once $root.'/app/research-knowledge.php';
function rk_ok(bool $condition,string $message): void {if(!$condition)throw new RuntimeException($message);}
$run='rk'.substr(bin2hex(random_bytes(8)),0,12);$pub=fn(string $p)=>$p.'-'.$run.'-'.substr(bin2hex(random_bytes(4)),0,8);
$makeUser=function(string $name)use($pdo,$run,$pub): array {$public=$pub('u');$username=substr($name.'_'.$run,0,48);$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,email_verified_at,status) VALUES(?,?,?,?,NOW(),'active')")->execute([$public,$username,$name,$username.'@example.test']);return ['id'=>(int)$pdo->lastInsertId(),'public_id'=>$public,'username'=>$username,'display_name'=>$name,'role'=>'user'];};
$owner=$makeUser('knowledge_owner');$viewer=$makeUser('knowledge_viewer');$outsider=$makeUser('knowledge_outsider');
$teamPublic=$pub('team');$pdo->prepare('INSERT INTO teams(public_id,owner_user_id,name) VALUES(?,?,?)')->execute([$teamPublic,$owner['id'],'Knowledge CI']);$teamId=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO team_members(team_id,user_id,role) VALUES(?,?,'owner'),(?,?,'viewer')")->execute([$teamId,$owner['id'],$teamId,$viewer['id']]);
$projectPublic=$pub('project');$pdo->prepare('INSERT INTO research_projects(public_id,owner_user_id,team_id,title,description) VALUES(?,?,?,?,?)')->execute([$projectPublic,$owner['id'],$teamId,'Knowledge project','Claims and findings']);$projectId=(int)$pdo->lastInsertId();
$sourcePublic=$pub('source');$url='https://example.com/'.$run.'/evidence';$pdo->prepare("INSERT INTO sources(public_id,source_type,canonical_url,canonical_url_hash,domain,title,status) VALUES(?,'webpage',?,?,?,'Knowledge source','current')")->execute([$sourcePublic,$url,hash('sha256',$url),'example.com']);$sourceId=(int)$pdo->lastInsertId();
$pdo->prepare("INSERT INTO source_versions(source_id,version_number,final_url,title,extracted_text,content_hash) VALUES(?,1,?,'V1','First captured version',?)")->execute([$sourceId,$url,hash('sha256','First captured version')]);$v1=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE sources SET current_version_id=? WHERE id=?')->execute([$v1,$sourceId]);$pdo->prepare('INSERT INTO project_sources(project_id,source_id,added_by_user_id) VALUES(?,?,?)')->execute([$projectId,$sourceId,$owner['id']]);
$capturePublic=$pub('capture');$pdo->prepare("INSERT INTO captures(public_id,source_id,source_version_id,user_id,capture_type,selected_text) VALUES(?,?,?,?,'text','Exact cited passage')")->execute([$capturePublic,$sourceId,$v1,$owner['id']]);$captureId=(int)$pdo->lastInsertId();$annotationPublic=$pub('annotation');$pdo->prepare("INSERT INTO annotations(public_id,user_id,source_id,source_version_id,capture_id,text_commentary,visibility,status) VALUES(?,?,?,?,?,'Evidence commentary','private','published')")->execute([$annotationPublic,$owner['id'],$sourceId,$v1,$captureId]);$annotationId=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO project_annotations(project_id,annotation_id,added_by_user_id) VALUES(?,?,?)')->execute([$projectId,$annotationId,$owner['id']]);
$claimPublic=$pub('claim');$pdo->prepare("INSERT INTO research_claims(public_id,project_id,created_by_user_id,statement,claim_type,status) VALUES(?,?,?,'The captured evidence supports the test claim.','factual','supported')")->execute([$claimPublic,$projectId,$owner['id']]);$claimId=(int)$pdo->lastInsertId();
$ownerClaim=research_claim_access($pdo,$owner,$claimPublic);$viewerClaim=research_claim_access($pdo,$viewer,$claimPublic);$outsiderClaim=research_claim_access($pdo,$outsider,$claimPublic);rk_ok($ownerClaim!==null&&project_can_write($ownerClaim),'Owner cannot write Claim.');rk_ok($viewerClaim!==null&&!project_can_write($viewerClaim),'Viewer Claim role boundary failed.');rk_ok($outsiderClaim===null,'Claim leaked outside Research project.');
$annEvidence=research_project_annotation_evidence($pdo,$projectId,$annotationPublic);rk_ok($annEvidence!==null&&(int)$annEvidence['source_version_id']===$v1,'Project annotation did not resolve immutable Source Version evidence.');$sourceEvidence=research_project_source_evidence($pdo,$projectId,$sourcePublic);rk_ok($sourceEvidence!==null&&(int)$sourceEvidence['source_version_id']===$v1,'Project Source did not resolve current captured version.');
$evidencePublic=$pub('evidence');$pdo->prepare("INSERT INTO claim_evidence(public_id,claim_id,added_by_user_id,evidence_type,annotation_id,source_version_id,relationship,note) VALUES(?,?,?,'annotation',?,?,'supports','Pinned at attach time')")->execute([$evidencePublic,$claimId,$owner['id'],$annotationId,$v1]);
$pdo->prepare("INSERT INTO source_versions(source_id,version_number,final_url,title,extracted_text,content_hash) VALUES(?,2,?,'V2','Changed later version',?)")->execute([$sourceId,$url,hash('sha256','Changed later version')]);$v2=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE sources SET current_version_id=? WHERE id=?')->execute([$v2,$sourceId]);$rows=research_claim_evidence_rows($pdo,$claimId);rk_ok(count($rows)===1&&(int)$rows[0]['source_version_id']===$v1&&(int)$rows[0]['version_number']===1,'Claim evidence drifted when Source current version changed.');$newSourceEvidence=research_project_source_evidence($pdo,$projectId,$sourcePublic);rk_ok((int)$newSourceEvidence['source_version_id']===$v2,'New Source evidence did not resolve the newer current version.');
$findingPublic=$pub('finding');$pdo->prepare("INSERT INTO research_findings(public_id,project_id,created_by_user_id,title,summary,status) VALUES(?,?,?,'CI Finding','The Claim is backed by version-pinned evidence.','final')")->execute([$findingPublic,$projectId,$owner['id']]);$findingId=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO finding_claims(finding_id,claim_id,added_by_user_id,relationship,position) VALUES(?,?,?,'primary',0)")->execute([$findingId,$claimId,$owner['id']]);
$ownerFinding=research_finding_access($pdo,$owner,$findingPublic);$viewerFinding=research_finding_access($pdo,$viewer,$findingPublic);$outsiderFinding=research_finding_access($pdo,$outsider,$findingPublic);rk_ok($ownerFinding!==null&&project_can_write($ownerFinding),'Owner cannot write Finding.');rk_ok($viewerFinding!==null&&!project_can_write($viewerFinding),'Viewer Finding role boundary failed.');rk_ok($outsiderFinding===null,'Finding leaked outside Research project.');$findingClaims=research_finding_claim_rows($pdo,$findingId);rk_ok(count($findingClaims)===1&&$findingClaims[0]['public_id']===$claimPublic&&$findingClaims[0]['relationship']==='primary','Finding did not retain Claim relationship.');
$ctx=research_knowledge_ai_context($pdo,$projectId);rk_ok(str_contains($ctx['text'],'[CLAIM '.$claimPublic.']'),'AI knowledge context omitted Claim reference.');rk_ok(str_contains($ctx['text'],'[FINDING '.$findingPublic.']'),'AI knowledge context omitted Finding reference.');rk_ok(str_contains($ctx['text'],'source-version 1'),'AI knowledge context lost exact evidence version.');rk_ok(count(array_filter($ctx['refs'],fn($r)=>$r['type']==='claim'))===1,'Claim provenance ref missing from AI context.');rk_ok(count(array_filter($ctx['refs'],fn($r)=>$r['type']==='finding'))===1,'Finding provenance ref missing from AI context.');
$pdo->prepare('DELETE FROM annotations WHERE id=?')->execute([$annotationId]);$q=$pdo->prepare('SELECT annotation_id,source_version_id FROM claim_evidence WHERE public_id=?');$q->execute([$evidencePublic]);$surviving=$q->fetch();rk_ok($surviving!==false&&$surviving['annotation_id']===null&&(int)$surviving['source_version_id']===$v1,'Claim evidence provenance did not survive Annotation deletion.');
echo "Research knowledge MariaDB suite passed.\n";
