<?php
declare(strict_types=1);
$root=dirname(__DIR__);$fail=[];
$read=function(string $p)use($root,&$fail): string{$f=$root.'/'.$p;if(!is_file($f)){$fail[]='Missing '.$p;return '';}return (string)file_get_contents($f);};
$need=function(string $p,string $n,string $m)use($read,&$fail): void{$c=$read($p);if($c!==''&&!str_contains($c,$n))$fail[]=$m;};
$avoid=function(string $p,string $n,string $m)use($read,&$fail): void{$c=$read($p);if($c!==''&&str_contains($c,$n))$fail[]=$m;};

$m='database/migrations/20260930_106_research_agent_stories.sql';
foreach(['profile_image_url',"ENUM('private','friends','public')",'research_agent_stories','research_agent_story_states','observation_key','generation_quality','ai_run_public_id'] as $n)$need($m,$n,'Stories migration missing '.$n);
$need('app/research-agents.php','ra.profile_image_url','Research Agent list must expose profile images.');
$need('app/research-agents.php','function research_agent_update_profile','Research Agents must support canonical profile updates.');
$need('api/research-agents.php',"action==='update_profile'","Profile update API must be exposed.");
$need('app/research-agent-stories.php','function research_agent_story_sync','Stories must derive from canonical proactive intelligence.');
$need('app/research-agent-stories.php','proactive_briefing','Stories must reuse proactive research briefing output.');
$need('app/research-agent-stories.php','notification_create','Important Stories must integrate with Notifications.');
$need('app/research-agent-stories.php','ai_setting_model_id($pdo,\'research\')','Higher quality Stories must reuse the system Research LLM route.');
$need('app/research-agent-stories.php','api_key_ciphertext','LLM Stories must require an active stored provider key.');
$need('app/research-agent-stories.php','ai_queue_job','LLM Story enhancement must be queued, not block Home rendering.');
$need('worker/ai-worker.php',"task_type']==='research_agent_story'","AI worker must apply Research Agent Story enhancement.");
$need('worker/ai-worker.php',"if(\$type==='research_agent_story')","AI worker must build the bounded Story prompt.");
$need('app/unified-activity.php','research_agent_story_activity','Stories must feed the canonical Activity timeline.');
$need('app/notifications.php',"type==='research_agent_story'","Notifications must access-check and route Stories.");
$need('home.php','class="homeAgentStoriesRail"','Home must render the Agent Stories rail.');
$need('home.php','class="homeAgentStoryAvatar"','Stories must present the Agent profile image.');
$need('home.php','<strong><?=h((string)$story[\'agent_name\'])?></strong>','Stories must present the Agent name beneath the profile image.');
$avoid('home.php','RESEARCH AGENT STORIES','Stories must not render a redundant section heading.');
$avoid('home.php','What your Agents want you to know','Stories must not render explanatory heading copy.');
$avoid('home.php','System research stories','Stories must not render system-story status copy.');
$avoid('home.php','homeAgentStoryCopy','Stories must not render card-style story body copy in the feed strip.');
$avoid('home.php','<span class="eyebrow">CONTINUE RESEARCH</span>','Legacy Continue Research strip must be removed.');
$need('home.php','research_agent_story_sync','Home must sync Story presentation from proactive intelligence.');
$need('home.php','research-agent-stories.js?v=1.0','Home must load Story interactions.');
$need('assets/css/app.css','/* Research Agent Stories V1 */','Stories must have responsive Home styling.');
$need('assets/css/app.css','overflow-x:auto','Stories must horizontally scroll when the strip overflows.');
$need('assets/css/app.css','flex:0 0 76px','Stories must render as compact fixed-width story items instead of cards.');
$need('assets/css/app.css','border-radius:50%','Story profile images must be circular.');
$need('app/shell.php','appShellAgentIcon hasImage','Sidebar Agent identity must support profile images.');
$need('app/research-agent-shell-ui.php','researchAgentUnifiedAvatar','Unified Agent shell must show the Agent profile image.');
$need('research.php','data-agent-profile-edit','Research page must expose Agent profile editing.');
$avoid('app/research-agent-stories.php','cognitive_watches','Stories must not create a second proactive watch engine.');

$need('app/research-agents.php',"in_array($visibility,['private','friends','public'],true)",'Research Agent visibility must be constrained to private, friends, or public.');
$need('app/shell.php','<option value="friends">Friends only</option>','Agent creation must expose Friends only visibility.');
$need('research.php','data-agent-visibility','Research Agent profile editing must expose current visibility.');
$need('app/research-agent-stories.php',"ra.visibility='public'",'Public Agent Stories must be visible through the follow graph.');
$need('app/research-agent-stories.php',"ra.visibility='friends'",'Friends-only Agent Stories must require mutual follows.');
$need('app/research-agent-stories.php','JOIN follows ff','Story distribution must reuse the canonical follows table.');
$need('app/research-agent-stories.php','research_agent_story_notify_social','Important social Stories must integrate with Notifications.');
$need('app/research-agent-stories.php','social_rank','Social Story viewers must be distinguished from Agent workspace members.');
$need('app/research-agent-stories.php',"'/profile.php?u='",'Follower Story links must not expose private Agent conversations.');
$need('bin/proactive-intelligence.php','research_agent_story_sync','Background proactive intelligence must generate Stories without requiring Home page load.');
$need('app/profile-network.php','function profile_network_toggle_follow','Website Follow must use the canonical follow graph.');
$need('api/profile-follow.php','profile_network_toggle_follow','Profile Follow must have a normal authenticated web API.');
$need('profile.php','/api/profile-follow.php','Profile Follow button must not depend on the extension API.');
$avoid('profile.php','/api/extension.php?action=follow','Profile Follow must not route through extension bearer authentication.');

if($fail){fwrite(STDERR,implode("\n",array_unique($fail))."\n");exit(1);}echo "Research Agent Stories V1 contract passed.\n";
