<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=(string)getenv('DB_DSN');$dbUser=(string)getenv('DB_USER');$dbPass=(string)getenv('DB_PASS');if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
require_once $root.'/app/storage.php';require_once $root.'/app/functions.php';require_once $root.'/app/access.php';require_once $root.'/app/research-intelligence.php';
function ri_ok(bool $condition,string $message): void {if(!$condition)throw new RuntimeException($message);}
function ri_throws(callable $fn,string $message): void {$thrown=false;try{$fn();}catch(Throwable $e){$thrown=true;}if(!$thrown)throw new RuntimeException($message);}
$run='ri'.substr(bin2hex(random_bytes(8)),0,12);$pub=fn(string $p)=>$p.'-'.$run.'-'.substr(bin2hex(random_bytes(4)),0,8);
$makeUser=function(string $name)use($pdo,$run,$pub): array {$public=$pub('u');$username=substr($name.'_'.$run,0,48);$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,email_verified_at,status) VALUES(?,?,?,?,NOW(),'active')")->execute([$public,$username,$name,$username.'@example.test']);return ['id'=>(int)$pdo->lastInsertId(),'public_id'=>$public,'username'=>$username,'display_name'=>$name,'role'=>'user'];};
$owner=$makeUser('intel_owner');$viewer=$makeUser('intel_viewer');$outsider=$makeUser('intel_outsider');
$teamPublic=$pub('team');$pdo->prepare('INSERT INTO teams(public_id,owner_user_id,name) VALUES(?,?,?)')->execute([$teamPublic,$owner['id'],'Intelligence CI']);$teamId=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO team_members(team_id,user_id,role) VALUES(?,?,'owner'),(?,?,'viewer')")->execute([$teamId,$owner['id'],$teamId,$viewer['id']]);
$projectPublic=$pub('project');$pdo->prepare('INSERT INTO research_projects(public_id,owner_user_id,team_id,title,description) VALUES(?,?,?,?,?)')->execute([$projectPublic,$owner['id'],$teamId,'Intelligence project','Brief timeline graph']);$projectId=(int)$pdo->lastInsertId();
$project2Public=$pub('project2');$pdo->prepare('INSERT INTO research_projects(public_id,owner_user_id,title) VALUES(?,?,?)')->execute([$project2Public,$owner['id'],'Other project']);$project2Id=(int)$pdo->lastInsertId();
$claim=$pdo->prepare('INSERT INTO research_claims(public_id,project_id,created_by_user_id,statement,claim_type,status) VALUES(?,?,?, ?,\'factual\',?)');
$aPublic=$pub('claimA');$claim->execute([$aPublic,$projectId,$owner['id'],'Primary supported claim','supported']);$aId=(int)$pdo->lastInsertId();
$bPublic=$pub('claimB');$claim->execute([$bPublic,$projectId,$owner['id'],'Unverified claim missing evidence','unverified']);$bId=(int)$pdo->lastInsertId();
$cPublic=$pub('claimC');$claim->execute([$cPublic,$projectId,$owner['id'],'Contradictory claim','contradicted']);$cId=(int)$pdo->lastInsertId();
$dPublic=$pub('claimD');$claim->execute([$dPublic,$project2Id,$owner['id'],'Other project claim','unverified']);$dId=(int)$pdo->lastInsertId();
$relationPublic=$pub('relation');$pdo->prepare("INSERT INTO claim_relations(public_id,project_id,source_claim_id,target_claim_id,added_by_user_id,relation_type,note) VALUES(?,?,?,?,?,'contradicts','CI conflict')")->execute([$relationPublic,$projectId,$aId,$cId,$owner['id']]);
ri_throws(fn()=>$pdo->prepare("INSERT INTO claim_relations(public_id,project_id,source_claim_id,target_claim_id,added_by_user_id,relation_type) VALUES(?,?,?,?,?,'supports')")->execute([$pub('cross'),$projectId,$aId,$dId,$owner['id']]),'Cross-project Claim relation was accepted.');
ri_throws(fn()=>$pdo->prepare("INSERT INTO claim_relations(public_id,project_id,source_claim_id,target_claim_id,added_by_user_id,relation_type) VALUES(?,?,?,?,?,'supports')")->execute([$pub('self'),$projectId,$aId,$aId,$owner['id']]),'Self Claim relation was accepted.');
ri_ok(research_project_claim_target($pdo,$projectId,$dPublic)===null,'Project-local Claim resolver crossed project boundary.');
$graph=research_project_graph_rows($pdo,$projectId);ri_ok(count($graph)===1&&$graph[0]['public_id']===$relationPublic,'Claim Graph row missing.');$aRelations=research_claim_relation_rows($pdo,$projectId,$aId);$cRelations=research_claim_relation_rows($pdo,$projectId,$cId);ri_ok(($aRelations[0]['direction']??'')==='outgoing'&&($cRelations[0]['direction']??'')==='incoming','Claim relation direction is incorrect.');
$sourcePublic=$pub('source');$url='https://example.com/'.$run.'/timeline';$pdo->prepare("INSERT INTO sources(public_id,source_type,canonical_url,canonical_url_hash,domain,title,status) VALUES(?,'webpage',?,?,?,'Timeline source','current')")->execute([$sourcePublic,$url,hash('sha256',$url),'example.com']);$sourceId=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO source_versions(source_id,version_number,final_url,title,extracted_text,content_hash) VALUES(?,1,?,'Timeline v1','Initial timeline evidence',?)")->execute([$sourceId,$url,hash('sha256','Initial timeline evidence')]);$v1=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE sources SET current_version_id=? WHERE id=?')->execute([$v1,$sourceId]);$pdo->prepare('INSERT INTO project_sources(project_id,source_id,added_by_user_id) VALUES(?,?,?)')->execute([$projectId,$sourceId,$owner['id']]);
$pdo->prepare("INSERT INTO source_versions(source_id,version_number,final_url,title,extracted_text,content_hash) VALUES(?,2,?,'Timeline v2','Changed timeline evidence',?)")->execute([$sourceId,$url,hash('sha256','Changed timeline evidence')]);$v2=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO source_change_events(source_id,previous_version_id,new_version_id,change_type,target_changed,diff_summary) VALUES(?,?,?,'updated',0,'CI source changed')")->execute([$sourceId,$v1,$v2]);
$pdo->prepare("INSERT INTO research_tasks(public_id,project_id,created_by_user_id,title,task_type,status) VALUES(?,?,?,'Find corroborating source','find_source','open')")->execute([$pub('task'),$projectId,$owner['id']]);
$pdo->prepare("INSERT INTO research_briefs(public_id,project_id,created_by_user_id,generated_by,status,summary) VALUES(?,?,?,'deterministic','current','CI research brief')")->execute([$pub('brief'),$projectId,$owner['id']]);
$snapshot=research_project_brief_snapshot($pdo,$projectId);ri_ok($snapshot['counts']['claims']===3,'Brief snapshot Claim count is wrong.');ri_ok($snapshot['counts']['relations']===1,'Brief snapshot relation count is wrong.');ri_ok($snapshot['counts']['disputed']===1,'Brief snapshot conflict-state count is wrong.');ri_ok($snapshot['counts']['open_tasks']===1,'Brief snapshot open-task count is wrong.');ri_ok($snapshot['counts']['recent_source_changes']===1,'Brief snapshot source-change count is wrong.');ri_ok(count($snapshot['gaps'])===1&&$snapshot['gaps'][0]['public_id']===$bPublic,'Brief snapshot did not identify evidence gap.');ri_ok(count($snapshot['conflicts'])===1&&$snapshot['conflicts'][0]['source_id']===$aPublic,'Brief snapshot did not identify Claim contradiction.');
$timeline=research_project_timeline($pdo,$projectId);$types=array_values(array_unique(array_column($timeline,'type')));foreach(['source','claim','task','claim_relation','source_change','brief'] as $type)ri_ok(in_array($type,$types,true),'Timeline omitted '.$type.' event.');
$context=research_intelligence_ai_context($pdo,$projectId);ri_ok(str_contains($context['text'],'[CLAIM-RELATION '.$relationPublic.']'),'AI intelligence context omitted Claim relationship.');ri_ok(str_contains($context['text'],'[PROJECT-SNAPSHOT]'),'AI intelligence context omitted project snapshot.');
$ownerProject=project_access($pdo,$owner['id'],$projectPublic);$viewerProject=project_access($pdo,$viewer['id'],$projectPublic);$outsiderProject=project_access($pdo,$outsider['id'],$projectPublic);ri_ok($ownerProject!==null&&project_can_write($ownerProject),'Owner lost intelligence write access.');ri_ok($viewerProject!==null&&!project_can_write($viewerProject),'Viewer gained intelligence write access.');ri_ok($outsiderProject===null,'Research Intelligence project leaked to outsider.');
echo "Research intelligence MariaDB suite passed.\n";
