<?php
declare(strict_types=1);
$root=dirname(__DIR__);$dsn=(string)getenv('DB_DSN');$dbUser=(string)getenv('DB_USER');$dbPass=(string)getenv('DB_PASS');if($dsn==='')throw new RuntimeException('DB_DSN is required.');
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);require_once $root.'/app/storage.php';require_once $root.'/app/functions.php';require_once $root.'/app/access.php';require_once $root.'/app/rich-capture.php';
function rc_ok(bool $v,string $m): void {if(!$v)throw new RuntimeException($m);}function rc_throws(callable $fn,string $m): void {$ok=false;try{$fn();}catch(Throwable $e){$ok=true;}if(!$ok)throw new RuntimeException($m);}
$config=['storage'=>['private_root'=>sys_get_temp_dir().'/annotated-rich-capture-ci-'.getmypid()]];$run='rc'.substr(bin2hex(random_bytes(8)),0,12);$pub=fn(string $p)=>$p.'-'.$run.'-'.substr(bin2hex(random_bytes(4)),0,8);
$makeUser=function(string $name)use($pdo,$run,$pub): array {$public=$pub('u');$username=substr($name.'_'.$run,0,48);$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,email_verified_at,status) VALUES(?,?,?,?,NOW(),'active')")->execute([$public,$username,$name,$username.'@example.test']);return ['id'=>(int)$pdo->lastInsertId(),'public_id'=>$public,'username'=>$username,'display_name'=>$name,'role'=>'user'];};
$owner=$makeUser('capture_owner');$other=$makeUser('capture_other');
rc_ok((int)$pdo->query("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='media_uploads'")->fetchColumn()===1,'Rich Capture media_uploads table missing.');rc_ok((int)$pdo->query("SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='captures' AND COLUMN_NAME='media_provider'")->fetchColumn()===1,'Capture provenance columns missing.');rc_ok((int)$pdo->query("SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='media_jobs' AND COLUMN_NAME='input_is_clip'")->fetchColumn()===1,'Media job clip-input flag missing.');
$bytes="\x1A\x45\xDF\xA3".str_repeat('A',1000);$start=rich_capture_upload_start($pdo,$config,$owner['id'],'audio','audio/webm;codecs=opus',strlen($bytes));rc_ok(!empty($start['upload_id'])&&$start['chunk_bytes']===rich_capture_chunk_bytes(),'Upload start did not return bounded chunk contract.');$first=substr($bytes,0,200);$second=substr($bytes,200);$r1=rich_capture_upload_append($pdo,$config,$owner['id'],$start['upload_id'],0,base64_encode($first));rc_ok($r1['received_bytes']===200&&!$r1['complete'],'First chunk state incorrect.');rc_throws(fn()=>rich_capture_upload_append($pdo,$config,$owner['id'],$start['upload_id'],0,base64_encode('x')),'Out-of-order upload chunk was accepted.');$r2=rich_capture_upload_append($pdo,$config,$owner['id'],$start['upload_id'],200,base64_encode($second));rc_ok($r2['complete']&&$r2['received_bytes']===strlen($bytes),'Chunked upload did not complete exactly.');
$pdo->beginTransaction();$upload=rich_capture_upload_for_publish($pdo,$config,$owner['id'],$start['upload_id'],'audio');rc_ok(hash('sha256',$bytes)===$upload['checksum'],'Upload checksum mismatch.');rc_throws(fn()=>rich_capture_upload_for_publish($pdo,$config,$other['id'],$start['upload_id'],'audio'),'Another user accessed private media upload.');rich_capture_mark_consumed($pdo,(int)$upload['id'],(string)$upload['checksum']);$pdo->commit();$pdo->beginTransaction();rc_throws(fn()=>rich_capture_upload_for_publish($pdo,$config,$owner['id'],$start['upload_id'],'audio'),'Consumed media upload was reusable.');$pdo->rollBack();
rc_throws(fn()=>rich_capture_upload_start($pdo,$config,$owner['id'],'video','video/mp4',100),'Non-WebM media upload was accepted.');rc_throws(fn()=>rich_capture_upload_start($pdo,$config,$owner['id'],'audio','audio/webm',rich_capture_max_bytes()+1),'Oversize media upload was accepted.');$bad=rich_capture_upload_start($pdo,$config,$owner['id'],'video','video/webm',8);rc_throws(fn()=>rich_capture_upload_append($pdo,$config,$owner['id'],$bad['upload_id'],0,base64_encode('NOTWEBM!')),'Invalid WebM signature was accepted.');
$teamPublic=$pub('team');$pdo->prepare('INSERT INTO teams(public_id,owner_user_id,name) VALUES(?,?,?)')->execute([$teamPublic,$owner['id'],'Capture Team']);$teamId=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO team_members(team_id,user_id,role) VALUES(?,?,'owner')")->execute([$teamId,$owner['id']]);$projectPublic=$pub('team-project');$pdo->prepare('INSERT INTO research_projects(public_id,owner_user_id,team_id,title) VALUES(?,?,?,?)')->execute([$projectPublic,$owner['id'],$teamId,'Capture Team Research']);rc_throws(fn()=>rich_capture_project_for_publish($pdo,$owner['id'],$projectPublic,'private',null),'Private capture was allowed into Team Research.');rc_throws(fn()=>rich_capture_project_for_publish($pdo,$owner['id'],$projectPublic,'team',$teamId+999),'Mismatched Team capture was allowed into Team Research.');rc_ok(rich_capture_project_for_publish($pdo,$owner['id'],$projectPublic,'team',$teamId)!==null,'Matching Team capture cannot be added to Team Research.');$personal=$pub('personal-project');$pdo->prepare('INSERT INTO research_projects(public_id,owner_user_id,title) VALUES(?,?,?)')->execute([$personal,$owner['id'],'Personal Capture Research']);rc_ok(rich_capture_project_for_publish($pdo,$owner['id'],$personal,'private',null)!==null,'Private capture cannot be added to personal Research.');
$q=$pdo->prepare('SELECT storage_path FROM media_uploads WHERE public_id=?');$q->execute([$start['upload_id']]);$stored=(string)$q->fetchColumn();$abs=storage_path_to_absolute($config,$stored);if($abs&&is_file($abs))@unlink($abs);$q=$pdo->prepare('SELECT storage_path FROM media_uploads WHERE public_id=?');$q->execute([$bad['upload_id']]);$stored=(string)$q->fetchColumn();$abs=storage_path_to_absolute($config,$stored);if($abs&&is_file($abs))@unlink($abs);
echo "Rich Capture MariaDB suite passed.\n";
