<?php
declare(strict_types=1);
$root=dirname(__DIR__);$fail=[];
$need=function(string $file,string $needle,string $message)use(&$fail,$root){$path=$root.'/'.$file;if(!is_file($path)){$fail[]="Missing $file";return;}if(!str_contains((string)file_get_contents($path),$needle))$fail[]=$message;};
$avoid=function(string $file,string $needle,string $message)use(&$fail,$root){$path=$root.'/'.$file;if(is_file($path)&&str_contains((string)file_get_contents($path),$needle))$fail[]=$message;};

$need('register.php','onboarding_ensure($pdo,$uid)','New accounts must initialize the same onboarding state as website accounts.');
$need('register.php','post_auth_destination($pdo,$uid)','Website registration must use the shared post-auth destination flow.');
$need('app/release.php','Publish your first annotation','Onboarding milestones must guide the first annotation.');
$need('app/release.php','Follow a researcher or source','Onboarding milestones must guide social/source following.');
$need('app/release.php','Start or join Research','Onboarding milestones must guide Research setup.');
$need('onboarding.php',"\$status['steps']",'Onboarding page must render the server-derived milestone checklist.');
$need('extension/service-worker.js',"details.reason==='install'",'Extension install must trigger first-run setup.');
$need('extension/sidepanel.html','id="authLoginForm"','Chrome sidebar must expose a normal login form.');
$need('extension/sidepanel.html','id="authRegisterForm"','Chrome sidebar must expose normal account creation.');
$need('extension/sidepanel.html','id="landingPanel"','Chrome sidebar must expose a logged-out landing view.');
$need('extension/sidepanel.html','id="authAccount"','Chrome sidebar must expose a distinct signed-in account view.');
$sidebarHtml=(string)file_get_contents($root.'/extension/sidepanel.html');
if(substr_count($sidebarHtml,'Use the same account you use on the Annotated website.')!==1)$fail[]='Extension login copy must appear exactly once.';
$need('extension/sidepanel.html','id="headerCreateNew"','Sidebar header must expose the Create New shortcut.');
$need('extension/sidepanel.html','id="buildVersion"','Sidebar header must visibly expose the loaded extension version.');
$need('extension/sidepanel-init.js',"chrome.runtime.getManifest().version",'Sidebar version marker must come from the manifest actually loaded by Chrome.');
$need('extension/sidepanel-init.js',"[Annotated] Capture mode failed",'Capture mode button errors must be caught instead of surfacing as uncaught anonymous-function dashboard errors.');
$need('extension/sidepanel-capture.js','ensurePageContentScript(tab)','Region capture must ensure the page reader is present before messaging the active tab.');
$avoid('extension/sidepanel.html','id="tab-create"','Create New must not appear as a duplicate sidebar tab.');
$need('extension/sidepanel.html','id="create" class="createPanel"','Create New must remain a standalone composer opened from the header.');
$sidebarPageStart=strpos($sidebarHtml,'<section id="page"');$sidebarCreateStart=strpos($sidebarHtml,'<section id="create"');
if($sidebarPageStart===false||$sidebarCreateStart===false||$sidebarCreateStart<=$sidebarPageStart)$fail[]='Standalone Create New panel must follow the This Page panel.';
else{$pageOnly=substr($sidebarHtml,$sidebarPageStart,$sidebarCreateStart-$sidebarPageStart);if(str_contains($pageOnly,'class="capture"'))$fail[]='This Page must contain annotations only, not the annotation composer.';}
$need('extension/sidepanel.css','repeat(5,minmax(0,1fr))','All five sidebar tabs must fit on one row.');
$need('extension/sidepanel.css','white-space:nowrap','Sidebar tab labels must not wrap onto a second row.');
$need('extension/sidepanel-feed.js','async function phase6OpenCreate','Header Create New must open the standalone composer.');
$need('extension/sidepanel-capture.js',"phase6SwitchTab(pageTab)",'Publishing must return to This Page so the new annotation is visible.');
$need('extension/sidepanel-state.js','let loadPage=null,loadThisPage=null,loadFollowing=null,annotationCard=null,filterPageFeed=null;','Shared sidebar state must declare feed hooks without carrying a legacy feed implementation.');
$avoid('extension/sidepanel-state.js','async function loadPage(){','Shared sidebar state must not ship the legacy loadPage implementation.');
$avoid('extension/sidepanel-state.js','function annotationCard(','Shared sidebar state must not ship the legacy annotationCard renderer.');
$avoid('extension/sidepanel-state.js','async function loadThisPage(){','Shared sidebar state must not ship the legacy This Page feed loader.');
$avoid('extension/sidepanel-state.js','async function loadFollowing(){','Shared sidebar state must not ship the legacy Following loader.');
$need('extension/sidepanel-feed.js','loadPage=phase6LoadPage;loadThisPage=phase6LoadThisPage;loadFollowing=phase6LoadFollowing;annotationCard=phase6AnnotationCard;filterPageFeed=phase6FilterPageFeed;','The dedicated feed module must own the sidebar feed entry points.');
$need('extension/sidepanel-state.js','await enterWorkspace();','Successful extension authentication must go directly to the workspace.');
$avoid('extension/sidepanel-state.js',"authShow('chooser')",'Normal extension login must not route through an extra chooser page.');
$need('extension/sidepanel-state.js','loadLandingPage','Chrome sidebar must render the website landing page when signed out.');
$need('extension/sidepanel-state.js',"chrome.runtime.getURL('landing.html')",'The logged-out sidebar landing page must not depend on a website fetch.');
$need('extension/sidepanel-init.js',"if(!signedIn&&token)",'A preserved extension session must keep the actual workspace visible when the server check is temporarily unavailable.');
$need('extension/sidepanel-state.js','websiteSessionHandoff','Chrome sidebar must recognize a logged-in Annotated website tab.');
$need('extension/sidepanel-state.js','showAccount','Chrome sidebar must render a dedicated signed-in account view.');
$need('extension/landing.html','Research the web','Chrome sidebar must ship the Annotated public landing experience locally.');
$need('extension/sidepanel-state.js','/api/extension-account.php','Chrome sidebar must authenticate against the shared Annotated account backend.');
$need('extension/sidepanel-feed.js','phase6AnnotationType','Annotation cards must expose a derived annotation type.');
$need('extension/sidepanel-feed.js','Source content','Annotation cards must expose collapsed source content.');
$need('extension/sidepanel-feed.js','phase6HydrateEvidence','Extension annotation media must hydrate through authenticated fetches.');
$need('extension/sidepanel-feed.js',"action==='like'",'Extension annotation posts must expose real Like actions.');
$need('app/annotation-ui.php','annotation_ui_card','Website annotation views must share one post renderer.');
$need('home.php',"feed_annotation_rows(\$pdo,\$u,'following'",'Website Home must use the shared feed that includes the signed-in users own annotations.');
$need('annotation.php','annotationDiscussion','Annotation discussion must be hideable until Comments is opened.');
$need('extension/sidepanel-state.js','client_version:chrome.runtime.getManifest().version','Chrome authentication must identify the client version.');
$avoid('extension/sidepanel-state.js','extension-connect.php','Primary Chrome login must stay inside the sidebar.');
$avoid('extension/sidepanel-state.js','/api/extension-pair.php','Primary Chrome login must not use the legacy pairing flow.');
$need('extension/sidepanel-capture.js','action=publish','Capture must publish through the server API.');
$need('extension/sidepanel-feed.js','action=follow','Feed must support following.');
$need('extension/sidepanel-social.js','live_message','Live messaging must remain wired.');
$need('extension/sidepanel-search.js','action=search','Chrome Search must remain wired.');
$need('api/extension-search.php','search_add_research','Search results must remain addable to Research.');
$need('app/source-integrity.php','source_integrity_notify_event','Source-change intelligence must notify affected users.');
$need('app/notifications.php','notification_rows','Unified notifications must remain access-aware.');
$need('app/moderation.php','rights_claim_create','Rights claims must remain available.');
$need('app/moderation.php','moderation_report_create','Community reports must remain available.');
$need('admin/system-health.php','release_environment_checks','Admin must expose production readiness.');
$need('bin/release-preflight.php','release_environment_checks','CLI must expose the same production readiness service.');
$need('docs/RELEASE-V1.1-RC1.md','Restore the **database backup and private evidence backup as a matched pair**','Release runbook must document matched-data rollback.');
$need('connected-accounts.php','revoke_everywhere','Users must be able to revoke browser and extension sessions.');
$need('oauth/callback.php','$fresh=$issued>0&&$issued>=time()-600','OAuth callback state must expire.');
$need('oauth/callback.php',"unset(\$_SESSION['oauth_state']",'OAuth callback state must be consumed before provider exchange.');
$need('extension/sidepanel.html','role="tablist"','Sidebar must expose tab semantics.');
$need('extension/sidepanel-feed.js',"setAttribute('aria-selected'",'Sidebar tab state must stay accessible.');
$sidebarInit=(string)file_get_contents($root.'/extension/sidepanel-init.js');
preg_match_all("/getElementById\\('([^']+)'\\)/",$sidebarInit,$directIds);
preg_match_all("/sidebarBind(?:Click)?\\('([^']+)'/",$sidebarInit,$boundIds);
$sidebarIds=array_unique(array_merge($directIds[1]??[],$boundIds[1]??[]));
foreach($sidebarIds as $id)if(!str_contains($sidebarHtml,'id="'.$id.'"'))$fail[]='Sidebar initializer references missing element #'.$id;
$need('extension/sidepanel-init.js','function sidebarBind','Sidebar event wiring must tolerate optional/missing elements without aborting all initialization.');
$avoid('extension/sidepanel-init.js',").onclick=",'Sidebar initialization must not use brittle direct onclick chains.');
$init=(string)file_get_contents($root.'/extension/sidepanel-init.js');if(preg_match("/(?<!\\$)\\$\\('nav button'\\)\\.forEach/",$init))$fail[]='Sidebar nav wiring must not call forEach on a single selector.';if(preg_match("/(?<!\\$)\\$\\('\\.modes button'\\)\\.forEach/",$init))$fail[]='Capture mode wiring must not call forEach on a single selector.';

$avoid('home.php','YOUR FEED','Home feed must not render the redundant feed heading block.');
$avoid('home.php','data-annotation-highlight-picker','Home feed must begin with feed content, not display preference controls.');
$need('home.php','homeAgentDock','Home feed must expose the sticky Agent composer shell.');
$need('home.php','data-team-chat-rail','Home must expose Team Chat rail for users with Team memberships.');
$need('home.php','teamChatMobileToggle','Team Chat must expose a mobile drawer trigger.');
$need('assets/js/team-chat.js',"request('send'",'Team Chat client must send through the unified conversation API.');
$need('assets/js/team-chat.js',"request('read'",'Team Chat client must maintain read state.');
$need('api/conversations.php','UPGRADE_REQUIRED','Team Chat API must fail clearly when migration 019 is missing.');
$need('api/conversations.php','require_api_mutation_auth','Team Chat mutations must enforce authenticated CSRF/bearer mutation auth.');
$need('app/conversations.php','conversation_access','Conversation authorization must remain server-side.');
$need('app/conversations.php','client_message_id','Conversation sends must remain retry-idempotent.');
$need('team.php','#team-chat','Team workspace must deep-link into its Home Team Chat.');
$need('extension/manifest.json','"version": "0.13.0"','Phase 13 must bump the Chrome extension to v0.13.0.');
$need('home.php','teamChatSettingsButton','Team Chat rail must expose a footer settings icon.');
$need('home.php','data-team-chat-popout','Team Chat rail must expose an active-chat popout control.');
$need('home.php','data-team-chat-popups','Home must expose the desktop active-chat popup layer.');
$need('chat-settings.php','Chat Status','Team Chat must have a dedicated status settings page.');
$need('chat-settings.php',"'invisible'",'Chat Status settings must support Invisible mode.');
$need('assets/js/chat-presence.js',"post('heartbeat'",'Authenticated Annotated shell must maintain heartbeat-based Chat presence.');
$need('app/shell.php','chat-presence.js?v=12.0','Authenticated pages must load the shared Chat presence client.');
$need('app/shell.php','data-chat-presence-csrf','Shared Chat presence must use the authenticated shell CSRF token.');
$need('assets/js/team-chat.js','function openPopup','Team Chat client must support Facebook-style active popout chats.');
$need('assets/js/team-chat.js','POPUP_KEY','Active chat popouts must persist across Home reloads.');
$need('assets/css/app.css','.chatPresenceDot.status-online','Team Chat must visually distinguish online presence.');
$need('assets/css/app.css','.teamChatPopupLayer','Desktop active chat popouts must be styled.');
$need('settings.php','/chat-settings.php','Account Settings must link to Chat Status.');
$need('home.php','data-agent-chat-canvas','Home must expose the in-place Agent Chat canvas.');
$need('home.php','data-agent-back','Agent Chat must expose Back to Feed.');
$need('home.php','data-agent-new','Agent Chat must expose New Chat.');
$need('assets/js/agent-chat.js','annotated:agent-chat-request','Home composer must use the existing Agent Chat request event.');
$need('assets/js/agent-chat.js','annotated.feedScroll','Agent Chat must restore the exact feed scroll position.');
$need('assets/js/agent-chat.js','context_options','Agent Chat must expose permission-scoped structured context selection.');
$need('app/agent-chat.php','agent_chat_context_normalize','Agent context must be validated server-side.');
$need('app/agent-chat.php',"sender_type='agent'",'Agent replies must persist in the unified conversation runtime.');
$need('app/agent-chat.php','agent_chat_available','Agent Chat must enforce plan/model access server-side.');
$need('api/agent-chat.php','require_api_mutation_auth','Agent Chat mutations must enforce authenticated CSRF/bearer auth.');
$need('assets/css/app.css','.agentChatCanvas','Agent Chat canvas must have dedicated responsive styling.');

$need('app/annotation-intelligence.php','annotation_intelligence_queue','Phase 13 must queue Annotation Intelligence asynchronously.');
$need('app/annotation-intelligence.php','annotation_intelligence_visible_relationships','Phase 13 relationships must be filtered through current viewer access.');
$need('app/annotation-intelligence.php','annotation_intelligence_has_analyzable_content','Phase 13 must not invent text intelligence for captures without analyzable content.');
$need('app/annotation-intelligence.php','Source integrity:','Agent annotation intelligence context must include source-change state when relevant.');
$need('worker/ai-worker.php',"'annotation_intelligence'=>'annotation_intelligence'",'The shared AI worker must route Annotation Intelligence jobs.');
$need('api/extension-publish.php','annotation_intelligence_queue','Published annotations must automatically queue intelligence.');
$need('worker/transcription-worker.php','annotation_intelligence_queue','Completed transcripts must refresh annotation intelligence.');
$need('api/annotation-intelligence.php','UPGRADE_REQUIRED','Annotation Intelligence API must fail clearly before migration 020.');
$need('api/annotation-intelligence.php','require_api_mutation_auth','Manual intelligence refresh must enforce authenticated mutation authorization.');
$need('annotation.php','data-intelligence-refresh','Annotation owners/admins must have a manual intelligence refresh action.');
$need('app/annotation-ui.php','annotationIntelligencePanel','Website annotation posts must expose a collapsed Intelligence panel.');
$need('app/annotation-ui.php','AI-assisted derived analysis','Website intelligence UI must label AI output as derived analysis.');
$need('extension/sidepanel-feed.js','function phase13Intelligence','Chrome This Page and Following must render Annotation Intelligence.');
$need('extension/sidepanel-feed.js','data-action="open-related"','Chrome intelligence relationships must open the referenced annotation.');
$need('app/agent-chat.php','annotation_intelligence_context_text','Agent Chat must receive permission-filtered Annotation Intelligence context.');
$need('bin/queue-annotation-intelligence.php','annotation_intelligence_queue','Existing published annotations must have a backfill path.');




$need('assets/css/app.css','.homeFeedPage .layout>aside{position:sticky','Home feed right rail must remain sticky on desktop.');
$need('app/annotation-ui.php','Evidence-first feed rendering','Website annotation cards must render preserved screenshots as the primary visual post when available.');
$need('app/annotation-ui.php','data-annotation-transcript-toggle','Website post menus must expose Show transcript when transcript text exists.');
$need('app/annotation-ui.php',"'Media transcript'",'Website renderer must support media transcripts for video, podcast, music and audio posts.');
$need('extension/sidepanel-feed.js',"['quote','image','image_quote','annotation'].includes(postType)",'Chrome feed must render screenshots for quote and image-oriented posts.');
$need('extension/sidepanel-feed.js','data-action="toggle-transcript"','Chrome post menus must expose Show transcript.');
$need('extension/sidepanel-feed.js',"'Media transcript'",'Chrome renderer must support future media transcripts without another UI path.');
$need('app/annotation-ui.php','annotationHeaderMenu','Annotation post actions must live in the post-header overflow menu.');
$need('app/annotation-ui.php','data-annotation-expand','Long annotation notes must expose Read more / Show less behavior.');
$need('app/annotation-ui.php','data-web-annotation-action="research"','Annotation social actions must include Research.');
$need('assets/js/annotation-cards.js','annotated.highlightColor','Annotation highlight color must persist as a viewer display preference.');
$need('assets/css/app.css','--annotation-highlight','Annotation quotes must use the configurable highlight color.');
$need('app/public-discovery.php','COALESCE(at.edited_text,at.raw_text) transcript_text','Profile annotation cards must receive transcript text when available.');
$need('profile.php','profileActivity','Profile annotations must render in a single-column activity area.');
$avoid('profile.php','profileColumns','Profile page must not restore the old two-column sidebar layout.');
$avoid('profile.php','PUBLISHED RESEARCH','Profile page must not render the old Research sidebar.');
$need('.htaccess','profile.php?u=$1','Clean single-segment username routes must resolve to public profiles.');
$need('profile.php',"\$GLOBALS['annotated_shell_mode']='header_only'",'Authenticated profile pages must use the default header without the application sidebar.');
$need('profile.php','profile_path((string)$p[\'username\'])','Profile canonical URLs must use /username.');
$need('profile.php',"header('Location: '.profile_path(\$username),true,301)",'Legacy profile.php URLs must redirect permanently to /username.');
$need('app/shell.php','profile_path($username)','The account dropdown must link to the clean profile URL.');
$need('app/shell.php',"'header_only'",'The universal shell must support a header-only mode.');
$need('assets/css/app.css','.appShellHeaderOnly','Header-only profile shell styling must be present.');
$need('settings.php','enctype="multipart/form-data"','Settings profile form must support photo uploads.');
$need('settings.php','name="profile_photo"','Settings must expose a profile photo upload field.');
$need('settings.php','data-annotation-highlight-picker','Account Settings must expose the annotation highlight color preference.');
$need('settings.php','settingsSidebar','Account Settings must expose a dedicated right sidebar hook.');
$need('assets/css/app.css','.settingsSidebar{position:sticky','Account Settings right sidebar must stay sticky on desktop.');
$need('settings.php','annotation-cards.js?v=0.13.0','Account Settings highlight control must reuse the shared highlight preference runtime.');
$need('app/storage.php','function profile_image_upload','Profile photo uploads must use the validated storage helper.');
$need('app/storage.php',"'image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'",'Profile photo uploads must be restricted to safe raster image types.');
$need('app/feed.php','u.profile_image_url','Annotation feed rows must carry author profile photos.');
$need('extension/sidepanel-feed.js','function phase6AuthorAvatar','Chrome This Page and Following cards must render profile photos with an initial fallback.');
$need('extension/sidepanel-feed.js','data-action="profile"','Chrome annotation identities must open the clean user profile.');
$need('extension/sidepanel-state.js','profileImageAbsolute','Chrome account identity must support website profile photos.');
$need('annotation.php','commentAuthorIdentity','Annotation discussion identities must render profile photos.');
$need('assets/css/app.css','.annotationPost{overflow:visible}','Annotation post menus must not be clipped by the post card.');


if($fail){foreach($fail as $f)fwrite(STDERR,"FAIL: $f\n");exit(1);}echo "V1.1 RC1 end-to-end release contract passed.\n";
