<?php
declare(strict_types=1);
$root=dirname(__DIR__);$fail=[];
$need=function(string $file,string $needle,string $message)use(&$fail,$root){$path=$root.'/'.$file;if(!is_file($path)){$fail[]="Missing $file";return;}if(!str_contains((string)file_get_contents($path),$needle))$fail[]=$message;};
$avoid=function(string $file,string $needle,string $message)use(&$fail,$root){$path=$root.'/'.$file;if(is_file($path)&&str_contains((string)file_get_contents($path),$needle))$fail[]=$message;};

$need('register.php','onboarding_ensure($pdo,$uid)','New accounts must initialize the same onboarding state as website accounts.');
$need('register.php','post_auth_destination($pdo,$uid)','Website registration must use the shared post-auth destination flow.');
$need('app/release.php','Publish your first annotation','Onboarding milestones must guide the first annotation.');
$need('app/release.php','Follow a researcher or source','Onboarding milestones must guide social/source following.');
$need('app/release.php','Start or join Research','Onboarding milestones must guide Research setup.');
$need('onboarding.php',"\$status['steps']",'Onboarding page must render the server-derived milestone checklist.');
$need('extension/service-worker.js',"details.reason==='install'",'Extension install must trigger first-run setup.');
$need('extension/sidepanel.html','id="authLoginForm"','Chrome sidebar must expose a normal login form.');
$need('extension/sidepanel.html','id="authRegisterForm"','Chrome sidebar must expose normal account creation.');
$need('extension/sidepanel.html','id="landingPanel"','Chrome sidebar must expose a logged-out landing view.');
$need('extension/sidepanel.html','id="authAccount"','Chrome sidebar must expose a distinct signed-in account view.');
$sidebarHtml=(string)file_get_contents($root.'/extension/sidepanel.html');
if(substr_count($sidebarHtml,'Use the same account you use on the Annotated website.')!==1)$fail[]='Extension login copy must appear exactly once.';
$need('extension/sidepanel.html','id="headerCreateNew"','Sidebar header must expose the Create New shortcut.');
$need('extension/sidepanel.html','id="buildVersion"','Sidebar header must visibly expose the loaded extension version.');
$need('extension/sidepanel-init.js',"chrome.runtime.getManifest().version",'Sidebar version marker must come from the manifest actually loaded by Chrome.');
$need('extension/sidepanel-init.js',"[Annotated] Capture mode failed",'Capture mode button errors must be caught instead of surfacing as uncaught anonymous-function dashboard errors.');
$need('extension/sidepanel-capture.js','ensurePageContentScript(tab)','Region capture must ensure the page reader is present before messaging the active tab.');
$avoid('extension/sidepanel.html','id="tab-create"','Create New must not appear as a duplicate sidebar tab.');
$need('extension/sidepanel.html','id="create" class="createPanel"','Create New must remain a standalone composer opened from the header.');
$sidebarPageStart=strpos($sidebarHtml,'<section id="page"');$sidebarCreateStart=strpos($sidebarHtml,'<section id="create"');
if($sidebarPageStart===false||$sidebarCreateStart===false||$sidebarCreateStart<=$sidebarPageStart)$fail[]='Standalone Create New panel must follow the This Page panel.';
else{$pageOnly=substr($sidebarHtml,$sidebarPageStart,$sidebarCreateStart-$sidebarPageStart);if(str_contains($pageOnly,'class="capture"'))$fail[]='This Page must contain annotations only, not the annotation composer.';}
$need('extension/sidepanel.css','repeat(6,minmax(0,1fr))','All six sidebar tabs must fit on one row.');
$need('extension/sidepanel.css','white-space:nowrap','Sidebar tab labels must not wrap onto a second row.');
$need('extension/sidepanel-feed.js','async function phase6OpenCreate','Header Create New must open the standalone composer.');
$need('extension/sidepanel-capture.js',"phase6SwitchTab(pageTab)",'Publishing must return to This Page so the new annotation is visible.');
$need('extension/sidepanel-state.js','let loadPage=null,loadThisPage=null,loadFollowing=null,annotationCard=null,filterPageFeed=null;','Shared sidebar state must declare feed hooks without carrying a legacy feed implementation.');
$avoid('extension/sidepanel-state.js','async function loadPage(){','Shared sidebar state must not ship the legacy loadPage implementation.');
$avoid('extension/sidepanel-state.js','function annotationCard(','Shared sidebar state must not ship the legacy annotationCard renderer.');
$avoid('extension/sidepanel-state.js','async function loadThisPage(){','Shared sidebar state must not ship the legacy This Page feed loader.');
$avoid('extension/sidepanel-state.js','async function loadFollowing(){','Shared sidebar state must not ship the legacy Following loader.');
$need('extension/sidepanel-feed.js','loadPage=phase6LoadPage;loadThisPage=phase6LoadThisPage;loadFollowing=phase6LoadFollowing;annotationCard=phase6AnnotationCard;filterPageFeed=phase6FilterPageFeed;','The dedicated feed module must own the sidebar feed entry points.');
$need('extension/sidepanel-state.js','await enterWorkspace();','Successful extension authentication must go directly to the workspace.');
$avoid('extension/sidepanel-state.js',"authShow('chooser')",'Normal extension login must not route through an extra chooser page.');
$need('extension/sidepanel-state.js','loadLandingPage','Chrome sidebar must render the website landing page when signed out.');
$need('extension/sidepanel-state.js',"chrome.runtime.getURL('landing.html')",'The logged-out sidebar landing page must not depend on a website fetch.');
$need('extension/sidepanel-init.js',"if(!signedIn&&token)",'A preserved extension session must keep the actual workspace visible when the server check is temporarily unavailable.');
$need('extension/sidepanel-state.js','websiteSessionHandoff','Chrome sidebar must recognize a logged-in Annotated website tab.');
$need('extension/sidepanel-state.js','showAccount','Chrome sidebar must render a dedicated signed-in account view.');
$need('extension/landing.html','Research the web','Chrome sidebar must ship the Annotated public landing experience locally.');
$need('extension/sidepanel-state.js','/api/extension-account.php','Chrome sidebar must authenticate against the shared Annotated account backend.');
$need('extension/sidepanel-feed.js','phase6AnnotationType','Annotation cards must expose a derived annotation type.');
$need('extension/sidepanel-feed.js','Source content','Annotation cards must expose collapsed source content.');
$need('extension/sidepanel-feed.js','phase6HydrateEvidence','Extension annotation media must hydrate through authenticated fetches.');
$need('extension/sidepanel-feed.js',"action==='like'",'Extension annotation posts must expose real Like actions.');
$need('app/annotation-ui.php','annotation_ui_card','Website annotation views must share one post renderer.');
$need('home.php',"feed_annotation_rows(\$pdo,\$u,'following'",'Website Home must use the shared feed that includes the signed-in users own annotations.');
$need('annotation.php','annotationDiscussion','Annotation discussion must be hideable until Comments is opened.');
$need('extension/sidepanel-state.js','client_version:chrome.runtime.getManifest().version','Chrome authentication must identify the client version.');
$avoid('extension/sidepanel-state.js','extension-connect.php','Primary Chrome login must stay inside the sidebar.');
$avoid('extension/sidepanel-state.js','/api/extension-pair.php','Primary Chrome login must not use the legacy pairing flow.');
$need('extension/sidepanel-capture.js','action=publish','Capture must publish through the server API.');
$need('extension/sidepanel-feed.js','action=follow','Feed must support following.');
$need('extension/sidepanel-social.js','live_message','Live messaging must remain wired.');
$need('extension/sidepanel-search.js','action=search','Chrome Search must remain wired.');
$need('api/extension-search.php','search_add_research','Search results must remain addable to Research.');
$need('app/source-integrity.php','source_integrity_notify_event','Source-change intelligence must notify affected users.');
$need('app/notifications.php','notification_rows','Unified notifications must remain access-aware.');
$need('app/moderation.php','rights_claim_create','Rights claims must remain available.');
$need('app/moderation.php','moderation_report_create','Community reports must remain available.');
$need('admin/system-health.php','release_operational_audit','Admin must expose Phase 49 operational production readiness.');
$need('bin/release-preflight.php','release_operational_audit','CLI must expose the Phase 49 operational readiness service.');
$need('docs/RELEASE-V1.1-RC1.md','Restore the **database backup and private evidence backup as a matched pair**','Release runbook must document matched-data rollback.');
$need('app/release.php',"const ANNOTATED_RELEASE = 'V1.1 RC1'",'Release identity must be normalized to V1.1 RC1.');
$need('app/release.php',"const ANNOTATED_RELEASE_VERSION = '1.1.0-rc1'",'Application release version must be V1.1.0 RC1.');
$need('app/release.php',"const ANNOTATED_EXTENSION_VERSION = '0.36.0'",'Chrome RC version must share one release constant.');
$need('chrome-extension.php','ANNOTATED_EXTENSION_VERSION','Chrome download page must derive its version from the release identity.');
$need('.github/workflows/release-rc.yml',"'v1.1.0-rc*'",'Release workflow must trigger on V1.1 RC tags.');
$need('.github/workflows/release-rc.yml','!=="0.36.0"','Release workflow must validate the Phase 36 Chrome package.');
$need('install.php','installer_request_is_https()','Installer session cookies must be Secure when installation runs over HTTPS.');
$need('connected-accounts.php','revoke_everywhere','Users must be able to revoke browser and extension sessions.');
$need('oauth/callback.php','$fresh=$issued>0&&$issued>=time()-600','OAuth callback state must expire.');
$need('oauth/callback.php',"unset(\$_SESSION['oauth_state']",'OAuth callback state must be consumed before provider exchange.');
$need('extension/sidepanel.html','role="tablist"','Sidebar must expose tab semantics.');
$need('extension/sidepanel-feed.js',"setAttribute('aria-selected'",'Sidebar tab state must stay accessible.');
$sidebarInit=(string)file_get_contents($root.'/extension/sidepanel-init.js');
preg_match_all("/getElementById\\('([^']+)'\\)/",$sidebarInit,$directIds);
preg_match_all("/sidebarBind(?:Click)?\\('([^']+)'/",$sidebarInit,$boundIds);
$sidebarIds=array_unique(array_merge($directIds[1]??[],$boundIds[1]??[]));
foreach($sidebarIds as $id)if(!str_contains($sidebarHtml,'id="'.$id.'"'))$fail[]='Sidebar initializer references missing element #'.$id;
$need('extension/sidepanel-init.js','function sidebarBind','Sidebar event wiring must tolerate optional/missing elements without aborting all initialization.');
$avoid('extension/sidepanel-init.js',").onclick=",'Sidebar initialization must not use brittle direct onclick chains.');
$init=(string)file_get_contents($root.'/extension/sidepanel-init.js');if(preg_match("/(?<!\\$)\\$\\('nav button'\\)\\.forEach/",$init))$fail[]='Sidebar nav wiring must not call forEach on a single selector.';if(preg_match("/(?<!\\$)\\$\\('\\.modes button'\\)\\.forEach/",$init))$fail[]='Capture mode wiring must not call forEach on a single selector.';

$avoid('home.php','YOUR FEED','Home feed must not render the redundant feed heading block.');
$avoid('home.php','data-annotation-highlight-picker','Home feed must begin with feed content, not display preference controls.');
$need('home.php','homeAgentDock','Home feed must expose the sticky Agent composer shell.');
$need('home.php','data-team-chat-rail','Home must expose Team Chat rail for users with Team memberships.');
$need('home.php','teamChatMobileToggle','Team Chat must expose a mobile drawer trigger.');
$need('assets/js/team-chat.js',"request('send'",'Team Chat client must send through the unified conversation API.');
$need('assets/js/team-chat.js',"request('read'",'Team Chat client must maintain read state.');
$need('api/conversations.php','UPGRADE_REQUIRED','Team Chat API must fail clearly when migration 019 is missing.');
$need('api/conversations.php','require_api_mutation_auth','Team Chat mutations must enforce authenticated CSRF/bearer mutation auth.');
$need('app/conversations.php','conversation_access','Conversation authorization must remain server-side.');
$need('app/conversations.php','client_message_id','Conversation sends must remain retry-idempotent.');
$need('team.php','#team-chat','Team workspace must deep-link into its Home Team Chat.');
$need('extension/manifest.json','"version": "0.36.0"','The current Chrome extension release must be v0.36.0 for Phase 27.');
$need('home.php','teamChatSettingsButton','Team Chat rail must expose a footer settings icon.');
$need('home.php','data-team-chat-popout','Team Chat rail must expose an active-chat popout control.');
$need('home.php','data-team-chat-popups','Home must expose the desktop active-chat popup layer.');
$need('chat-settings.php','Chat Status','Team Chat must have a dedicated status settings page.');
$need('chat-settings.php',"'invisible'",'Chat Status settings must support Invisible mode.');
$need('assets/js/chat-presence.js',"post('heartbeat'",'Authenticated Annotated shell must maintain heartbeat-based Chat presence.');
$need('app/shell.php','chat-presence.js?v=12.0','Authenticated pages must load the shared Chat presence client.');
$need('app/shell.php','data-chat-presence-csrf','Shared Chat presence must use the authenticated shell CSRF token.');
$need('assets/js/team-chat.js','function openPopup','Team Chat client must support Facebook-style active popout chats.');
$need('assets/js/team-chat.js','POPUP_KEY','Active chat popouts must persist across Home reloads.');
$need('assets/css/app.css','.chatPresenceDot.status-online','Team Chat must visually distinguish online presence.');
$need('assets/css/app.css','.teamChatPopupLayer','Desktop active chat popouts must be styled.');
$need('settings.php','/chat-settings.php','Account Settings must link to Chat Status.');
$need('home.php','data-agent-chat-canvas','Home must expose the in-place Agent Chat canvas.');
$need('home.php','data-agent-back','Agent Chat must expose Back to Feed.');
$need('home.php','data-agent-new','Agent Chat must expose New Chat.');
$need('assets/js/agent-chat.js','annotated:agent-chat-request','Home composer must use the existing Agent Chat request event.');
$need('assets/js/agent-chat.js','annotated.feedScroll','Agent Chat must restore the exact feed scroll position.');
$need('assets/js/agent-chat.js','context_options','Agent Chat must expose permission-scoped structured context selection.');
$need('app/agent-chat.php','agent_chat_context_normalize','Agent context must be validated server-side.');
$need('app/agent-chat.php',"sender_type='agent'",'Agent replies must persist in the unified conversation runtime.');
$need('app/agent-chat.php','agent_chat_available','Agent Chat must enforce plan/model access server-side.');
$need('api/agent-chat.php','require_api_mutation_auth','Agent Chat mutations must enforce authenticated CSRF/bearer auth.');
$need('assets/css/app.css','.agentChatCanvas','Agent Chat canvas must have dedicated responsive styling.');

$need('app/annotation-intelligence.php','annotation_intelligence_queue','Phase 13 must queue Annotation Intelligence asynchronously.');
$need('app/annotation-intelligence.php','annotation_intelligence_visible_relationships','Phase 13 relationships must be filtered through current viewer access.');
$need('app/annotation-intelligence.php','annotation_intelligence_has_analyzable_content','Phase 13 must not invent text intelligence for captures without analyzable content.');
$need('app/annotation-intelligence.php','Source integrity:','Agent annotation intelligence context must include source-change state when relevant.');
$need('worker/ai-worker.php',"'annotation_intelligence'=>'annotation_intelligence'",'The shared AI worker must route Annotation Intelligence jobs.');
$need('api/extension-publish.php','annotation_intelligence_queue','Published annotations must automatically queue intelligence.');
$need('worker/transcription-worker.php','annotation_intelligence_queue','Completed transcripts must refresh annotation intelligence.');
$need('api/annotation-intelligence.php','UPGRADE_REQUIRED','Annotation Intelligence API must fail clearly before migration 020.');
$need('api/annotation-intelligence.php','require_api_mutation_auth','Manual intelligence refresh must enforce authenticated mutation authorization.');
$need('annotation.php','data-intelligence-refresh','Annotation owners/admins must have a manual intelligence refresh action.');
$need('app/annotation-ui.php','annotationIntelligencePanel','Website annotation posts must expose a collapsed Intelligence panel.');
$need('app/annotation-ui.php','AI-assisted derived analysis','Website intelligence UI must label AI output as derived analysis.');
$need('extension/sidepanel-feed.js','function phase13Intelligence','Chrome This Page and Following must render Annotation Intelligence.');
$need('extension/sidepanel-feed.js','data-action="open-related"','Chrome intelligence relationships must open the referenced annotation.');
$need('app/agent-chat.php','annotation_intelligence_context_text','Agent Chat must receive permission-filtered Annotation Intelligence context.');
$need('bin/queue-annotation-intelligence.php','annotation_intelligence_queue','Existing published annotations must have a backfill path.');
$need('extension/manifest.json','"version": "0.36.0"','The current Chrome extension release must be v0.36.0 for Phase 27.');
$need('app/research-workspace.php','research_workspace_deterministic_snapshot','Research Workspace must provide deterministic intelligence without AI.');
$need('app/research-workspace.php','research_workspace_queue','Research Workspace must queue hash-specific background synthesis.');
$need('app/research-workspace.php','research_workspace_apply_ai_output','Research Workspace must validate and persist derived AI synthesis.');
$need('app/research-workspace.php','research_workspace_context','Agent Chat must receive current project-level workspace intelligence.');
$need('api/research-workspace.php','UPGRADE_REQUIRED','Research Workspace API must fail clearly before migration 021.');
$need('api/research-workspace.php','project_can_write','Workspace refresh must preserve project write permissions.');
$need('research-project.php','data-research-now','Research project must start with the intelligent Now workspace.');
$need('research-project.php','NEEDS ATTENTION','Research workspace must surface gaps, conflicts and source risks.');
$need('research-project.php','NEXT ACTIONS','Research workspace must surface next research actions.');
$need('research-project.php','data-research-agent-composer','Research workspace must expose a sticky project-scoped Agent composer.');
$need('assets/js/research-agent.js',"context:[{type:'research',public_id:project}]",'Research Agent must automatically attach the current project as permission-checked context.');
$need('assets/js/research-workspace.js','research-workspace.php?action=','Research Workspace refresh must use the permission-scoped API.');
$need('worker/source-monitor-worker.php','research_workspace_queue','Monitored source changes must refresh affected Research workspaces.');
$need('api/extension-publish.php','workspace_intelligence_queued','Browser-added project evidence must refresh Research Workspace Intelligence.');
$need('app/agent-chat.php','research_workspace_context','Agent Chat Research attachments must include live workspace state.');
$need('assets/css/app.css','.researchAgentDock','Research Workspace Agent composer must have dedicated responsive styling.');

$need('app/agent-actions.php','research.create_task','Agent action registry must expose bounded task creation.');
$need('app/agent-actions.php','research.attach_annotation_evidence','Agent action registry must support provenance-safe Annotation evidence attachment.');
$need('app/agent-actions.php','research.create_finding','Agent action registry must support draft Finding creation.');
$need('app/agent-actions.php','project_state_hash','Every proposal must bind to the current Research project state.');
$need('app/agent-actions.php','agent_action_event','Agent actions must emit immutable audit events.');
$need('app/agent-actions.php',"status']==='executed'",'Agent confirmation retries must replay executed results idempotently.');
$need('app/agent-chat.php','<<ANNOTATED_ACTIONS>>','Agent Chat must separate machine-readable proposals from user-visible prose.');
$need('app/agent-chat.php','project_can_write','Read-only project viewers must not be offered write capabilities.');
$need('api/agent-chat.php',"'action_confirm'",'Agent action execution must require an explicit confirmation endpoint.');
$need('api/agent-chat.php',"'action_reject'",'Agent action proposals must support explicit rejection.');
$need('api/agent-chat.php','require_api_mutation_auth','Agent action confirmation/rejection must enforce mutation authentication.');
$need('assets/js/agent-chat.js','Confirm & execute','Home Agent canvas must render explicit confirmation cards.');
$need('assets/js/research-agent.js','Confirm & execute','Project Agent dock must render explicit confirmation cards.');
$need('research-project.php','Propose tasks','Research Now must expose contextual Agent-driven Research actions.');
$need('research-project.php','Draft finding','Research Now must expose a Finding proposal shortcut.');
$need('assets/css/app.css','.agentActionProposal','Agent action proposals must have dedicated review styling.');

$need('extension/manifest.json','"version": "0.36.0"','The current Chrome extension release must be v0.36.0 for Phase 27.');
$need('app/cognitive-feed.php','cognitive_feed_compose','Cognitive Feed must compose authoritative observations at request time.');
$need('app/cognitive-feed.php','cognitive_feed_score','Cognitive Feed ranking must use an explicit deterministic scoring function.');
$need('app/cognitive-feed.php',"'pending_agent_action'?100:98",'Pending user confirmations must retain the highest Cognitive Feed priority.');
$need('app/cognitive-feed.php','cognitive_feed_dismissed_keys','Cognitive Feed must honor user-scoped explicit dismissals.');
$need('api/cognitive-feed.php','require_api_mutation_auth','Cognitive Feed mutations must require authenticated mutation authorization.');
$need('api/cognitive-feed.php',"'dismiss'",'Cognitive Feed must expose explicit hide behavior.');
$need('api/cognitive-feed.php',"'restore'",'Cognitive Feed must support undo for hidden cards.');
$need('home.php','>Now</a>','Home must expose the cognitive Now view.');
$need('home.php','>Latest</a>','Home must preserve the chronological Latest view.');
$need('app/cognitive-feed-ui.php','data-cognitive-agent','Cognitive cards must hand permission-checked context into Agent Chat.');
$need('assets/js/cognitive-feed.js','annotated:agent-chat-request','Cognitive Feed Agent actions must reuse the primary Agent canvas.');
$need('assets/js/agent-chat.js','annotated:agent-chat-feed-restored','Returning from Agent Chat must allow the cognitive feed to refresh changed Research state.');
$need('assets/css/app.css','.cognitiveCard','Cognitive Feed cards must have dedicated responsive styling.');



$need('extension/manifest.json','"version": "0.36.0"','The current Chrome extension release must be v0.36.0 for Phase 27.');
$need('app/research-workspace.php','research_workspace_deterministic_snapshot','Research Workspace must provide deterministic intelligence without AI.');
$need('app/research-workspace.php','research_workspace_queue','Research Workspace must queue hash-specific background synthesis.');
$need('app/research-workspace.php','research_workspace_apply_ai_output','Research Workspace must validate and persist derived AI synthesis.');
$need('app/research-workspace.php','research_workspace_context','Agent Chat must receive current project-level workspace intelligence.');
$need('api/research-workspace.php','UPGRADE_REQUIRED','Research Workspace API must fail clearly before migration 021.');
$need('api/research-workspace.php','project_can_write','Workspace refresh must preserve project write permissions.');
$need('research-project.php','data-research-now','Research project must start with the intelligent Now workspace.');
$need('research-project.php','NEEDS ATTENTION','Research workspace must surface gaps, conflicts and source risks.');
$need('research-project.php','NEXT ACTIONS','Research workspace must surface next research actions.');
$need('research-project.php','data-research-agent-composer','Research workspace must expose a sticky project-scoped Agent composer.');
$need('assets/js/research-agent.js',"context:[{type:'research',public_id:project}]",'Research Agent must automatically attach the current project as permission-checked context.');
$need('assets/js/research-workspace.js','research-workspace.php?action=','Research Workspace refresh must use the permission-scoped API.');
$need('worker/source-monitor-worker.php','research_workspace_queue','Monitored source changes must refresh affected Research workspaces.');
$need('api/extension-publish.php','workspace_intelligence_queued','Browser-added project evidence must refresh Research Workspace Intelligence.');
$need('app/agent-chat.php','research_workspace_context','Agent Chat Research attachments must include live workspace state.');
$need('assets/css/app.css','.researchAgentDock','Research Workspace Agent composer must have dedicated responsive styling.');





$need('assets/css/app.css','.homeFeedPage .layout>aside{position:sticky','Home feed right rail must remain sticky on desktop.');
$need('app/annotation-ui.php','Evidence-first feed rendering','Website annotation cards must render preserved screenshots as the primary visual post when available.');
$need('app/annotation-ui.php','data-annotation-transcript-toggle','Website post menus must expose Show transcript when transcript text exists.');
$need('app/annotation-ui.php',"'Media transcript'",'Website renderer must support media transcripts for video, podcast, music and audio posts.');
$need('extension/sidepanel-feed.js',"['quote','image','image_quote','annotation'].includes(postType)",'Chrome feed must render screenshots for quote and image-oriented posts.');
$need('extension/sidepanel-feed.js','data-action="toggle-transcript"','Chrome post menus must expose Show transcript.');
$need('extension/sidepanel-feed.js',"'Media transcript'",'Chrome renderer must support future media transcripts without another UI path.');
$need('app/annotation-ui.php','annotationHeaderMenu','Annotation post actions must live in the post-header overflow menu.');
$need('app/annotation-ui.php','data-annotation-expand','Long annotation notes must expose Read more / Show less behavior.');
$need('app/annotation-ui.php','data-web-annotation-action="research"','Annotation social actions must include Research.');
$need('assets/js/annotation-cards.js','annotated.highlightColor','Annotation highlight color must persist as a viewer display preference.');
$need('assets/css/app.css','--annotation-highlight','Annotation quotes must use the configurable highlight color.');
$need('app/public-discovery.php','COALESCE(at.edited_text,at.raw_text) transcript_text','Profile annotation cards must receive transcript text when available.');
$need('profile.php','profileActivity','Profile annotations must render in a single-column activity area.');
$avoid('profile.php','profileColumns','Profile page must not restore the old two-column sidebar layout.');
$avoid('profile.php','PUBLISHED RESEARCH','Profile page must not render the old Research sidebar.');
$need('.htaccess','profile.php?u=$1','Clean single-segment username routes must resolve to public profiles.');
$need('profile.php',"\$GLOBALS['annotated_shell_mode']='header_only'",'Authenticated profile pages must use the default header without the application sidebar.');
$need('profile.php','profile_path((string)$p[\'username\'])','Profile canonical URLs must use /username.');
$need('profile.php',"header('Location: '.profile_path(\$username),true,301)",'Legacy profile.php URLs must redirect permanently to /username.');
$need('app/shell.php','profile_path($username)','The account dropdown must link to the clean profile URL.');
$need('app/shell.php',"'header_only'",'The universal shell must support a header-only mode.');
$need('assets/css/app.css','.appShellHeaderOnly','Header-only profile shell styling must be present.');
$need('settings.php','enctype="multipart/form-data"','Settings profile form must support photo uploads.');
$need('settings.php','name="profile_photo"','Settings must expose a profile photo upload field.');
$need('settings.php','data-annotation-highlight-picker','Account Settings must expose the annotation highlight color preference.');
$need('settings.php','settingsSidebar','Account Settings must expose a dedicated right sidebar hook.');
$need('app/research-workflow.php','research_workflow_current_completed_reviews','Phase 30 must ignore stale completed reviews for workflow progression.');
$need('app/research-workflow.php',"subject_type IN ('claim','finding','report_version')",'Phase 30 workflow review counts must exclude Agent-action reviews.');
$need('research-project.php','aria-current="step"','Phase 30 Research lifecycle must expose accessible current-step semantics.');
$need('docs/RESEARCH-V1-COMPLETE.md','Feature freeze','Phase 30 must declare the Research V1 feature-complete boundary.');
$need('extension/manifest.json','"version": "0.36.0"','The final Research-loop Chrome release must be v0.36.0.');
$need('app/object-handoff.php','object_handoff_resolve','Phase 31 must re-resolve shared Annotated objects through current access rules.');
$need('app/object-handoff.php','object_handoff_can_share_to_conversation','Phase 31 must prevent Team handoff permission escalation.');
$need('app/conversations.php','object_handoff_store_message_attachments','Team Chat must persist structured object references.');
$need('assets/js/team-chat.js','row.attachments','Team Chat must render structured shared objects.');
$need('app/annotation-ui.php','data-web-annotation-action="team"','Website Annotation cards must hand off to Team Chat.');
$need('app/annotation-ui.php','data-web-annotation-action="agent"','Website Annotation cards must hand off to Agent Chat.');
$need('assets/js/annotation-cards.js','annotated.pendingAgentHandoff','Cross-page Agent handoff must preserve the Annotation reference.');
$need('home.php','agent_context_type','Home Agent Chat must accept direct permission-checked object handoffs.');
$need('extension/sidepanel-feed.js','phase31OpenTeamShare','Chrome Annotation cards must hand off to Team Chat.');
$need('extension/sidepanel-feed.js','phase31OpenAgent','Chrome Annotation cards must hand off to Agent Chat.');
$need('team.php','annotation_ui_card($a,$u)','Team feed must use the unified Annotation component.');
$need('tests/phase31-unified-object-handoff-db.php','Phase 31 Unified Object Handoff & Continuity','Phase 31 must retain an adversarial continuity/privacy suite.');
$need('extension/manifest.json','"version": "0.36.0"','Phase 31 Chrome release must be v0.36.0.');

$need('app/research-workflow.php','research_workflow_state','Phase 29 must derive a unified Research lifecycle.');
$need('app/research-workflow.php','Capture → Investigate → Verify → Synthesize → Review → Publish → Monitor','Phase 29 Agent context must expose the unified lifecycle.');
$need('research-project.php','researchWorkflow','Research project must expose the lifecycle strip.');
$need('research-project.php','NEXT STEP','Research project must expose one clear next step.');
$need('extension/sidepanel.html','openResearchWorkspace','Chrome Research must prioritize the unified workspace.');
$need('extension/manifest.json','"version": "0.36.0"','The current Chrome extension release must be v0.36.0 for Phase 29.');
$need('app/research-evidence-packs.php','research_evidence_pack_create','Phase 28 must create immutable Evidence Packs.');
$need('app/research-evidence-packs.php','research_evidence_pack_compare','Phase 28 must compare frozen packs with current Research.');
$need('app/research-provenance.php','frozen_as','Phase 28 packs must join provenance.');
$need('research-evidence-pack.php','Replay boundary','Phase 28 must expose frozen replay semantics.');
$need('extension/sidepanel.html','openEvidencePacks','Chrome Research must expose Phase 28 Evidence Packs.');
$need('extension/manifest.json','"version": "0.36.0"','The current Chrome extension release must be v0.36.0 for Phase 28.');
$need('app/research-verification.php','research_verification_claim_signal','Phase 27 must derive transparent Claim evidence signals.');
$need('app/research-verification.php','not a truth score','Phase 27 Agent context must preserve the truth-certification boundary.');
$need('app/research-provenance.php','verification_review','Phase 27 human verification events must join provenance.');
$need('research-verification.php','Human review','Phase 27 must expose human review state.');
$need('research-report.php','research_verification_snapshot_claim_signal','Phase 27 public Reports must use immutable snapshot verification signals.');
$need('extension/sidepanel.html','openVerification','Chrome Research must expose Phase 27 Verification.');
$need('extension/manifest.json','"version": "0.36.0"','The current Chrome extension release must be v0.36.0 for Phase 27.');
$need('assets/css/app.css','.settingsSidebar{position:sticky','Account Settings right sidebar must stay sticky on desktop.');
$need('settings.php','annotation-cards.js?v=36.0','Account Settings highlight control must reuse the shared highlight preference runtime.');
$need('app/storage.php','function profile_image_upload','Profile photo uploads must use the validated storage helper.');
$need('app/storage.php',"'image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'",'Profile photo uploads must be restricted to safe raster image types.');
$need('app/feed.php','u.profile_image_url','Annotation feed rows must carry author profile photos.');
$need('extension/sidepanel-feed.js','function phase6AuthorAvatar','Chrome This Page and Following cards must render profile photos with an initial fallback.');
$need('extension/sidepanel-feed.js','data-action="profile"','Chrome annotation identities must open the clean user profile.');
$need('extension/sidepanel-state.js','profileImageAbsolute','Chrome account identity must support website profile photos.');
$need('annotation.php','commentAuthorIdentity','Annotation discussion identities must render profile photos.');
$need('assets/css/app.css','.annotationPost{overflow:visible}','Annotation post menus must not be clipped by the post card.');


$need('assets/js/team-chat.js','annotated:object-add-research','Phase 32 Team object cards must continue into Research.');
$need('assets/js/team-chat.js','annotated:object-ask-agent','Phase 32 Team object cards must continue into Agent Chat.');
$need('assets/js/annotation-cards.js','annotated:object-add-research','Shared web continuity runtime must consume Team-to-Research object actions.');
$need('assets/js/annotation-cards.js','annotated:object-ask-agent','Shared web continuity runtime must consume Team-to-Agent object actions.');
$need('assets/js/agent-chat.js','function attachmentUrl','Agent context chips must provide authoritative object return paths.');
$need('home.php','data-agent-enabled=','Team Agent continuity actions must use server-rendered Agent capability state.');
$need('tests/phase32-unified-continuity-actions.php','Phase 32 Unified Continuity Actions & Object Cards','Phase 32 must retain a dedicated continuity action contract suite.');
$need('extension/manifest.json','"version": "0.36.0"','Phase 32 Chrome release must be v0.36.0.');

$need('app/unified-activity.php','unified_activity_collect','Phase 33 must derive a unified viewer-scoped activity stream.');
$need('api/activity.php','unified_activity_collect','Phase 33 clients must use the same authoritative activity stream.');
$need('activity.php','WORKSPACE ACTIVITY','Phase 33 must expose the full Activity workspace.');
$need('app/cognitive-feed.php','workspace_activity','Home Now must surface bounded workspace activity context.');
$need('extension/sidepanel.html','data-tab="activity"','Chrome must expose the unified Activity tab.');
$need('extension/sidepanel-feed.js','phase33LoadActivity','Chrome Activity must load from the shared Activity API.');
$need('tests/phase33-unified-activity-db.php','Phase 33 Unified Activity & Context Awareness','Phase 33 must retain its privacy/revocation DB suite.');
$need('extension/manifest.json','"version": "0.36.0"','Phase 33 Chrome release must be v0.36.0.');

$need('app/workspace-context.php','workspace_context_resolve','Phase 34 must re-resolve ephemeral workspace refs against current access.');
$need('api/workspace-context.php','workspace_context_resolve','Phase 34 clients must share the same current-access workspace resolver.');
$need('assets/js/workspace-state.js','sessionStorage.setItem(KEY','Website workspace state must be session-scoped.');
$need('assets/js/workspace-state.js','history.replaceState','One-time Browser handoff refs must be scrubbed from the URL after import.');
$need('assets/js/team-chat.js','annotated:workspace-context','Team Chat changes must update workspace context.');
$need('assets/js/agent-chat.js','agent_conversation_public_id','Agent Chat must preserve the active Agent conversation ref.');
$need('assets/js/research-agent.js','research_public_id:project','Research Agent must preserve active Research context.');
$need('extension/sidepanel-workspace.js','chrome.storage.session.set','Chrome workspace state must be session-scoped.');
$need('extension/sidepanel-workspace.js','phase34WorkspaceWebsiteUrl','Chrome must hand opaque workspace refs to the website without copying content.');
$need('extension/sidepanel.html','workspaceContextMini','Chrome must expose contextual workspace navigation.');
$need('tests/phase34-workspace-context-db.php','Phase 34 Contextual Navigation & Workspace State','Phase 34 must retain its current-access revocation DB suite.');
$need('tests/phase34-workspace-state-contract.php','Phase 34 Contextual Navigation & Workspace State','Phase 34 must retain its session-only storage contract suite.');
$need('extension/manifest.json','"version": "0.36.0"','Phase 34 Chrome release must be v0.36.0.');

$need('app/action-center.php','action_center_compose','Phase 35 must derive one unified action queue from current authoritative state.');
$need('app/action-center.php','cognitive_feed_items','Phase 35 must reuse Cognitive Feed observations instead of duplicating intelligence collectors.');
$need('app/action-center.php','research_workflow_state','Phase 35 must include concrete Research lifecycle continuation when not already covered.');
$need('api/action-center.php','action_center_compose','Website and Chrome must share the same Action Center API.');
$need('action-center.php','What needs your attention','Phase 35 must expose the full Action Center workspace.');
$need('assets/js/action-center.js','AnnotatedWorkspaceState','Action Center routes must preserve Phase 34 workspace continuity.');
$need('home.php','/action-center.php','Home must expose the live Action Center count.');
$need('extension/sidepanel.html','actionCenterMiniFeed','Chrome Activity must surface a compact Action Center without adding a seventh tab.');
$need('extension/sidepanel-feed.js','phase35LoadActions','Chrome must load actions from the shared Action Center API.');
$need('tests/phase35-action-center-db.php','Phase 35 Unified Action Center & Attention Routing','Phase 35 must retain authoritative action-resolution coverage.');
$need('tests/phase35-action-center-contract.php','Phase 35 Unified Action Center & Attention Routing','Phase 35 must retain no-shadow-state architectural coverage.');
$need('extension/manifest.json','"version": "0.36.0"','Phase 35 Chrome release must be v0.36.0.');

$need('tests/phase36-end-to-end-workspace-journey-db.php','Browser → Annotation → Feed → Team → Research → Agent → Review → Publish → Monitor → Action Center','Phase 36 must retain the complete workspace journey release gate.');
$need('tests/phase36-release-hardening-contract.php','Phase 36 release hardening contract suite passed.','Phase 36 must retain bounded-scale, accessibility, cache, and session-state hardening.');
$need('app/cognitive-feed.php','function cognitive_feed_compose_from_items','Phase 36 must support one shared Cognitive request snapshot.');
$need('app/action-center.php','?array $cognitiveBase=null','Phase 36 Action Center must reuse the shared Cognitive snapshot.');
$need('home.php','$cognitiveBase=cognitive_feed_items','Home must collect Cognitive state once for Now and Action Center.');
$need('app/annotation-ui.php','annotation-cards.js?v=36.0','Shared Annotation UI must use the Phase 36 release cache tag.');
$need('home.php','workspace-state.js?v=36.0','Home workspace continuity must use the Phase 36 release cache tag.');
$need('home.php','agent-chat.js?v=','Home Agent Chat must use a cache-busted client URL.');
$need('home.php','team-chat.js?v=36.0','Home Team Chat must use the Phase 36 release cache tag.');
$need('activity.php','activity.js?v=36.0','Activity must use the Phase 36 release cache tag.');
$need('action-center.php','action-center.js?v=36.0','Action Center must use the Phase 36 release cache tag.');
$need('research-project.php','research-agent.js?v=36.0','Research Agent must use the Phase 36 release cache tag.');
$need('extension/manifest.json','"version": "0.36.0"','Phase 36 Chrome release candidate must be v0.36.0.');

if($fail){foreach($fail as $f)fwrite(STDERR,"FAIL: $f\n");exit(1);}echo "V1.1 RC1 end-to-end release contract passed.\n";
