<?php
declare(strict_types=1);
$root=dirname(__DIR__);$fail=[];
$need=function(string $file,string $needle,string $message)use(&$fail,$root){$path=$root.'/'.$file;if(!is_file($path)){$fail[]="Missing $file";return;}if(!str_contains((string)file_get_contents($path),$needle))$fail[]=$message;};
$avoid=function(string $file,string $needle,string $message)use(&$fail,$root){$path=$root.'/'.$file;if(is_file($path)&&str_contains((string)file_get_contents($path),$needle))$fail[]=$message;};

$need('register.php','onboarding_ensure($pdo,$uid)','New accounts must initialize the same onboarding state as website accounts.');
$need('register.php','post_auth_destination($pdo,$uid)','Website registration must use the shared post-auth destination flow.');
$need('app/release.php','Publish your first annotation','Onboarding milestones must guide the first annotation.');
$need('app/release.php','Follow a researcher or source','Onboarding milestones must guide social/source following.');
$need('app/release.php','Start or join Research','Onboarding milestones must guide Research setup.');
$need('onboarding.php',"\$status['steps']",'Onboarding page must render the server-derived milestone checklist.');
$need('extension/service-worker.js',"details.reason==='install'",'Extension install must trigger first-run setup.');
$need('extension/sidepanel.html','id="authLoginForm"','Chrome sidebar must expose a normal login form.');
$need('extension/sidepanel.html','id="authRegisterForm"','Chrome sidebar must expose normal account creation.');
$need('extension/sidepanel.html','id="landingPanel"','Chrome sidebar must expose a logged-out landing view.');
$need('extension/sidepanel.html','id="authAccount"','Chrome sidebar must expose a distinct signed-in account view.');
$sidebarHtml=(string)file_get_contents($root.'/extension/sidepanel.html');
$need('extension/sidepanel.html','id="headerCreateNew"','Sidebar header must expose the Create New shortcut.');
$need('extension/sidepanel.html','id="buildVersion"','Sidebar header must visibly expose the loaded extension version.');
$need('extension/sidepanel-init.js',"chrome.runtime.getManifest().version",'Sidebar version marker must come from the manifest actually loaded by Chrome.');
$need('extension/sidepanel-init.js',"[Annotated] Capture mode failed",'Capture mode button errors must be caught instead of surfacing as uncaught anonymous-function dashboard errors.');
$need('extension/sidepanel-capture.js','ensurePageContentScript(tab)','Region capture must ensure the page reader is present before messaging the active tab.');
$avoid('extension/sidepanel.html','id="tab-create"','Create New must not appear as a duplicate sidebar tab.');
$need('extension/sidepanel.html','id="create" class="createPanel"','Create New must remain a standalone composer opened from the header.');
$sidebarPageStart=strpos($sidebarHtml,'<section id="page"');$sidebarCreateStart=strpos($sidebarHtml,'<section id="create"');
if($sidebarPageStart===false||$sidebarCreateStart===false||$sidebarCreateStart<=$sidebarPageStart)$fail[]='Standalone Create New panel must follow the This Page panel.';
else{$pageOnly=substr($sidebarHtml,$sidebarPageStart,$sidebarCreateStart-$sidebarPageStart);if(str_contains($pageOnly,'class="capture"'))$fail[]='This Page must contain annotations only, not the annotation composer.';}
$need('extension/sidepanel.css','repeat(5,minmax(0,1fr))','All five sidebar tabs must fit on one row.');
$need('extension/sidepanel.css','white-space:nowrap','Sidebar tab labels must not wrap onto a second row.');
$need('extension/sidepanel-feed.js','async function phase6OpenCreate','Header Create New must open the standalone composer.');
$need('extension/sidepanel-capture.js',"phase6SwitchTab(pageTab)",'Publishing must return to This Page so the new annotation is visible.');
$need('extension/sidepanel-state.js','await enterWorkspace();','Successful extension authentication must go directly to the workspace.');
$avoid('extension/sidepanel-state.js',"authShow('chooser')",'Normal extension login must not route through an extra chooser page.');
$need('extension/sidepanel-state.js','loadLandingPage','Chrome sidebar must render the website landing page when signed out.');
$need('extension/sidepanel-state.js',"chrome.runtime.getURL('landing.html')",'The logged-out sidebar landing page must not depend on a website fetch.');
$need('extension/sidepanel-init.js',"if(!signedIn&&token)",'A preserved extension session must keep the actual workspace visible when the server check is temporarily unavailable.');
$need('extension/sidepanel-state.js','websiteSessionHandoff','Chrome sidebar must recognize a logged-in Annotated website tab.');
$need('extension/sidepanel-state.js','showAccount','Chrome sidebar must render a dedicated signed-in account view.');
$need('extension/landing.html','Research the web','Chrome sidebar must ship the Annotated public landing experience locally.');
$need('extension/sidepanel-state.js','/api/extension-account.php','Chrome sidebar must authenticate against the shared Annotated account backend.');
$need('extension/sidepanel-feed.js','phase6AnnotationType','Annotation cards must expose a derived annotation type.');
$need('extension/sidepanel-feed.js','Source content','Annotation cards must expose collapsed source content.');
$need('extension/sidepanel-feed.js','phase6HydrateEvidence','Extension annotation media must hydrate through authenticated fetches.');
$need('extension/sidepanel-feed.js',"action==='like'",'Extension annotation posts must expose real Like actions.');
$need('app/annotation-ui.php','annotation_ui_card','Website annotation views must share one post renderer.');
$need('home.php',"feed_annotation_rows(\$pdo,\$u,'following'",'Website Home must use the shared feed that includes the signed-in users own annotations.');
$need('annotation.php','annotationDiscussion','Annotation discussion must be hideable until Comments is opened.');
$need('extension/sidepanel-state.js','client_version:chrome.runtime.getManifest().version','Chrome authentication must identify the client version.');
$avoid('extension/sidepanel-state.js','extension-connect.php','Primary Chrome login must stay inside the sidebar.');
$avoid('extension/sidepanel-state.js','/api/extension-pair.php','Primary Chrome login must not use the legacy pairing flow.');
$need('extension/sidepanel-capture.js','action=publish','Capture must publish through the server API.');
$need('extension/sidepanel-feed.js','action=follow','Feed must support following.');
$need('extension/sidepanel-social.js','live_message','Live messaging must remain wired.');
$need('extension/sidepanel-search.js','action=search','Chrome Search must remain wired.');
$need('api/extension-search.php','search_add_research','Search results must remain addable to Research.');
$need('app/source-integrity.php','source_integrity_notify_event','Source-change intelligence must notify affected users.');
$need('app/notifications.php','notification_rows','Unified notifications must remain access-aware.');
$need('app/moderation.php','rights_claim_create','Rights claims must remain available.');
$need('app/moderation.php','moderation_report_create','Community reports must remain available.');
$need('admin/system-health.php','release_environment_checks','Admin must expose production readiness.');
$need('bin/release-preflight.php','release_environment_checks','CLI must expose the same production readiness service.');
$need('docs/RELEASE-V1.1-RC1.md','Restore the **database backup and private evidence backup as a matched pair**','Release runbook must document matched-data rollback.');
$need('connected-accounts.php','revoke_everywhere','Users must be able to revoke browser and extension sessions.');
$need('oauth/callback.php','$fresh=$issued>0&&$issued>=time()-600','OAuth callback state must expire.');
$need('oauth/callback.php',"unset(\$_SESSION['oauth_state']",'OAuth callback state must be consumed before provider exchange.');
$need('extension/sidepanel.html','role="tablist"','Sidebar must expose tab semantics.');
$need('extension/sidepanel-feed.js',"setAttribute('aria-selected'",'Sidebar tab state must stay accessible.');
$sidebarInit=(string)file_get_contents($root.'/extension/sidepanel-init.js');
preg_match_all("/getElementById\\('([^']+)'\\)/",$sidebarInit,$directIds);
preg_match_all("/sidebarBind(?:Click)?\\('([^']+)'/",$sidebarInit,$boundIds);
$sidebarIds=array_unique(array_merge($directIds[1]??[],$boundIds[1]??[]));
foreach($sidebarIds as $id)if(!str_contains($sidebarHtml,'id="'.$id.'"'))$fail[]='Sidebar initializer references missing element #'.$id;
$need('extension/sidepanel-init.js','function sidebarBind','Sidebar event wiring must tolerate optional/missing elements without aborting all initialization.');
$avoid('extension/sidepanel-init.js',").onclick=",'Sidebar initialization must not use brittle direct onclick chains.');
$init=(string)file_get_contents($root.'/extension/sidepanel-init.js');if(preg_match("/(?<!\\$)\\$\\('nav button'\\)\\.forEach/",$init))$fail[]='Sidebar nav wiring must not call forEach on a single selector.';if(preg_match("/(?<!\\$)\\$\\('\\.modes button'\\)\\.forEach/",$init))$fail[]='Capture mode wiring must not call forEach on a single selector.';

$avoid('home.php','YOUR FEED','Home feed must not render the redundant feed heading block.');
$need('home.php','data-annotation-highlight-picker','Home feed must expose the user highlight color preference.');
$need('home.php','homeAgentDock','Home feed must expose the sticky Agent composer shell.');
$need('app/annotation-ui.php','showSnapshot','Website annotation cards must render screenshots only for image-oriented post types.');
$need('app/annotation-ui.php','View captured evidence','Suppressed screenshots must remain accessible as provenance.');
$need('extension/sidepanel-feed.js',"['image','image_quote'].includes(postType)",'Chrome feed must suppress screenshot duplication for non-image post types.');
$need('app/annotation-ui.php','annotationHeaderMenu','Annotation post actions must live in the post-header overflow menu.');
$need('app/annotation-ui.php','data-annotation-expand','Long annotation notes must expose Read more / Show less behavior.');
$need('app/annotation-ui.php','data-web-annotation-action="research"','Annotation social actions must include Research.');
$need('assets/js/annotation-cards.js','annotated.highlightColor','Annotation highlight color must persist as a viewer display preference.');
$need('assets/css/app.css','--annotation-highlight','Annotation quotes must use the configurable highlight color.');
$need('profile.php','profileActivity','Profile annotations must render in a single-column activity area.');
$avoid('profile.php','profileColumns','Profile page must not restore the old two-column sidebar layout.');
$avoid('profile.php','PUBLISHED RESEARCH','Profile page must not render the old Research sidebar.');

if($fail){foreach($fail as $f)fwrite(STDERR,"FAIL: $f\n");exit(1);}echo "V1.1 RC1 end-to-end release contract passed.\n";
