<?php
declare(strict_types=1);
$root=dirname(__DIR__,2);$dsn=(string)getenv('DB_DSN');$dbUser=(string)getenv('DB_USER');$dbPass=(string)getenv('DB_PASS');if($dsn==='')throw new RuntimeException('DB_DSN is required.');
require_once $root.'/app/installer.php';require_once $root.'/app/migrations.php';
if((string)getenv('ADMIN_V260_RESET_DB')==='1'){
    if(!preg_match('/(?:^|;)dbname=([^;]+)/',$dsn,$m))throw new RuntimeException('Upgrade rehearsal DSN must name a database.');
    $name=installer_validate_db_identifier((string)$m[1]);$adminDsn=(string)preg_replace('/;?dbname=[^;]+/','',$dsn);$a=new PDO($adminDsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_EMULATE_PREPARES=>false]);$tick=chr(96);$q=$tick.str_replace($tick,$tick.$tick,$name).$tick;$a->exec('DROP DATABASE IF EXISTS '.$q);$a->exec('CREATE DATABASE '.$q.' CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');
}
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);$tmp=sys_get_temp_dir().'/annotated-v260-'.bin2hex(random_bytes(5));if(!mkdir($tmp,0700,true))throw new RuntimeException('Could not create migration fixture.');
try{
    foreach(glob($root.'/database/migrations/*.sql')?:[] as $file){$base=basename($file);if(strcmp($base,'20260924_078_admin_security_compliance_audit.sql')<=0)copy($file,$tmp.'/'.$base);}
    installer_run($pdo,$root.'/database/schema.sql',$tmp);if(!installer_table_exists($pdo,'admin_security_cases')||!installer_table_exists($pdo,'admin_security_audit_events'))throw new RuntimeException('078 fixture did not reach Admin V2.50 schema.');if(installer_table_exists($pdo,'admin_platform_features'))throw new RuntimeException('078 fixture unexpectedly contains V2.60 schema.');
    $beforeRoleCaps=[];foreach(['operations_admin','read_only_auditor','trust_ops_admin'] as $roleKey){$q=$pdo->prepare('SELECT capabilities_json FROM admin_roles WHERE role_key=?');$q->execute([$roleKey]);$beforeRoleCaps[$roleKey]=json_decode((string)$q->fetchColumn(),true)?:[];}
    $applied=migration_apply_pending($pdo,$root.'/database/migrations',10);if(!in_array('20260924_079_admin_platform_configuration_governance',$applied,true))throw new RuntimeException('Upgrade did not apply migration 079.');
    foreach(['admin_platform_features','admin_platform_modules','admin_platform_integrations','admin_platform_snapshots','admin_platform_events'] as $table)if(!installer_table_exists($pdo,$table))throw new RuntimeException('079 upgraded schema missing '.$table.'.');
    $q=$pdo->query("SELECT capabilities_json FROM admin_roles WHERE role_key='platform_operations_admin'");$caps=json_decode((string)$q->fetchColumn(),true)?:[];if(!in_array('admin.platform.manage',$caps,true)||!in_array('admin.platform.release',$caps,true)||in_array('admin.billing.manage',$caps,true))throw new RuntimeException('Migration 079 did not seed bounded Platform Operations authority.');
    foreach($beforeRoleCaps as $roleKey=>$beforeCaps){$q=$pdo->prepare('SELECT capabilities_json FROM admin_roles WHERE role_key=?');$q->execute([$roleKey]);$afterCaps=json_decode((string)$q->fetchColumn(),true)?:[];foreach($beforeCaps as $cap)if(!in_array($cap,$afterCaps,true))throw new RuntimeException('Migration 079 removed existing capability '.$cap.' from '.$roleKey.'.');if(!in_array('admin.platform.view',$afterCaps,true))throw new RuntimeException('Migration 079 did not append admin.platform.view to '.$roleKey.'.');if(in_array($roleKey,['operations_admin','trust_ops_admin'],true)&&!in_array('admin.platform.release',$afterCaps,true))throw new RuntimeException('Migration 079 did not append admin.platform.release to '.$roleKey.'.');}
    $q=$pdo->query("SELECT required_approvals,distinct_from_requester,risk_level FROM admin_approval_policies WHERE action_type='change_platform_feature'");$policy=$q->fetch();if(!$policy||(int)$policy['required_approvals']!==1||(int)$policy['distinct_from_requester']!==1||$policy['risk_level']!=='elevated')throw new RuntimeException('Migration 079 did not seed the platform feature approval policy.');
    if(installer_pending_migrations($pdo,$root.'/database/migrations'))throw new RuntimeException('Admin V2.60 upgrade left pending migrations.');if(migration_apply_pending($pdo,$root.'/database/migrations',10))throw new RuntimeException('Admin V2.60 repeat upgrade is not a no-op.');
    echo "PASS: Admin V2.60 upgrade rehearsal advanced migration 078 through 079 and repeat pass was a no-op.\n";
}finally{foreach(glob($tmp.'/*')?:[] as $file)@unlink($file);@rmdir($tmp);}
