<?php
declare(strict_types=1);
$root=dirname(__DIR__,2);$dsn=(string)getenv('DB_DSN');$dbUser=(string)getenv('DB_USER');$dbPass=(string)getenv('DB_PASS');if($dsn==='')throw new RuntimeException('DB_DSN is required.');
require_once $root.'/app/installer.php';require_once $root.'/app/migrations.php';
if((string)getenv('PHASE80_SECTION4_RESET_DB')==='1'){if(!preg_match('/(?:^|;)dbname=([^;]+)/',$dsn,$m))throw new RuntimeException('Upgrade rehearsal DSN must name a database.');$dbName=installer_validate_db_identifier((string)$m[1]);$adminDsn=(string)preg_replace('/;?dbname=[^;]+/','',$dsn);$admin=new PDO($adminDsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_EMULATE_PREPARES=>false]);$q=chr(96).str_replace(chr(96),chr(96).chr(96),$dbName).chr(96);$admin->exec('DROP DATABASE IF EXISTS '.$q);$admin->exec('CREATE DATABASE '.$q.' CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');}
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);$tmp=sys_get_temp_dir().'/annotated-p80s4-upgrade-'.bin2hex(random_bytes(6));if(!mkdir($tmp,0700,true))throw new RuntimeException('Could not create fixture.');
try{$baseline='20261001_118_phase80_sponsored_research_participation.sql';foreach(glob($root.'/database/migrations/*.sql')?:[] as $file){$base=basename($file);if(strcmp($base,$baseline)<=0)copy($file,$tmp.'/'.$base);}installer_run($pdo,$root.'/database/schema.sql',$tmp);
if(installer_table_exists($pdo,'sponsored_research_submissions'))throw new RuntimeException('118 fixture unexpectedly contains Section 4 submissions.');
$applied=migration_apply_pending($pdo,$root.'/database/migrations',20);if(!in_array('20261001_119_phase80_sponsored_research_submissions',$applied,true))throw new RuntimeException('Upgrade did not apply migration 119.');
foreach(['sponsored_research_submissions','sponsored_research_submission_versions','sponsored_research_submission_assets','sponsored_research_submission_events'] as $t)if(!installer_table_exists($pdo,$t))throw new RuntimeException('119 missing '.$t);
$cols=[];$q=$pdo->query("SELECT COLUMN_NAME FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='sponsored_research_submission_assets'");foreach($q->fetchAll(PDO::FETCH_COLUMN) as $column)$cols[(string)$column]=true;foreach(['asset_type','asset_public_id','asset_version','data_contribution_id','snapshot_hash','source_rights_snapshot_hash'] as $column)if(empty($cols[$column]))throw new RuntimeException('119 submission asset missing '.$column);
if(installer_pending_migrations($pdo,$root.'/database/migrations'))throw new RuntimeException('Upgrade left pending migrations.');if(migration_apply_pending($pdo,$root.'/database/migrations',20))throw new RuntimeException('Repeat 119 upgrade is not a no-op.');echo "PASS: migration 118 upgrades through Phase 80 Section 4 migration 119.\n";
}finally{foreach(glob($tmp.'/*')?:[] as $file)@unlink($file);@rmdir($tmp);}
