<?php
declare(strict_types=1);
$root=dirname(__DIR__,2);$dsn=(string)getenv('DB_DSN');$dbUser=(string)getenv('DB_USER');$dbPass=(string)getenv('DB_PASS');if($dsn==='')throw new RuntimeException('DB_DSN is required.');
require_once $root.'/app/installer.php';require_once $root.'/app/migrations.php';
if((string)getenv('PHASE80_SECTION6_RESET_DB')==='1'){if(!preg_match('/(?:^|;)dbname=([^;]+)/',$dsn,$m))throw new RuntimeException('Upgrade rehearsal DSN must name a database.');$dbName=installer_validate_db_identifier((string)$m[1]);$adminDsn=(string)preg_replace('/;?dbname=[^;]+/','',$dsn);$admin=new PDO($adminDsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_EMULATE_PREPARES=>false]);$q=chr(96).str_replace(chr(96),chr(96).chr(96),$dbName).chr(96);$admin->exec('DROP DATABASE IF EXISTS '.$q);$admin->exec('CREATE DATABASE '.$q.' CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');}
$pdo=new PDO($dsn,$dbUser,$dbPass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);$tmp=sys_get_temp_dir().'/annotated-p80s6-upgrade-'.bin2hex(random_bytes(6));if(!mkdir($tmp,0700,true))throw new RuntimeException('Could not create fixture.');
try{$baseline='20261001_120_phase80_sponsored_research_review.sql';foreach(glob($root.'/database/migrations/*.sql')?:[] as $file){$base=basename($file);if(strcmp($base,$baseline)<=0)copy($file,$tmp.'/'.$base);}installer_run($pdo,$root.'/database/schema.sql',$tmp);
if(installer_table_exists($pdo,'sponsored_research_financial_transactions'))throw new RuntimeException('120 fixture unexpectedly contains Section 6 finance.');
$applied=migration_apply_pending($pdo,$root.'/database/migrations',20);if(!in_array('20261001_121_phase80_sponsored_research_financial_ledger',$applied,true))throw new RuntimeException('Upgrade did not apply migration 121.');
foreach(['sponsored_research_finance_settings','sponsored_research_financial_transactions','sponsored_research_financial_entries','sponsored_research_compensation_reservations'] as $t)if(!installer_table_exists($pdo,$t))throw new RuntimeException('121 missing '.$t);
$cols=[];$q=$pdo->query("SELECT COLUMN_NAME FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='sponsored_research_financial_transactions'");foreach($q->fetchAll(PDO::FETCH_COLUMN) as $column)$cols[(string)$column]=true;foreach(['transaction_type','campaign_id','researcher_user_id','currency','idempotency_key','metadata_json'] as $column)if(empty($cols[$column]))throw new RuntimeException('121 financial transaction missing '.$column);
if(installer_pending_migrations($pdo,$root.'/database/migrations'))throw new RuntimeException('Upgrade left pending migrations.');if(migration_apply_pending($pdo,$root.'/database/migrations',20))throw new RuntimeException('Repeat 121 upgrade is not a no-op.');echo "PASS: migration 120 upgrades through Phase 80 Section 6 migration 121.\n";
}finally{foreach(glob($tmp.'/*')?:[] as $file)@unlink($file);@rmdir($tmp);}
