#!/usr/bin/env bash
set -euo pipefail

php tests/release-contracts.php
php tests/security-contracts.php
php tests/app-shell-contracts.php
php tests/home-runtime-hardening-contract.php
php tests/home-render-integrity-contract.php
php tests/home-agent-feed-contract.php
php tests/profile-standalone-ui-contract.php
php tests/profile-phase2-showcase-contract.php
php tests/profile-phase3-research-network-contract.php
php tests/admin-subscriptions-packages-v1-contract.php
php tests/admin-ai-usage-v1-contract.php
php tests/admin-v1-20-information-architecture-contract.php
php tests/admin-v1-30-account-lifecycle-contract.php
php tests/admin-v1-40-stripe-billing-contract.php
php tests/code-audit-hardening-contract.php
php tests/admin-v1-50-account-membership-contract.php
php tests/admin-v1-60-billing-analytics-contract.php
php tests/admin-v1-70-ai-overage-billing-contract.php
php tests/admin-v1-80-coupons-promotions-credits-contract.php
php tests/admin-v1-90-tax-invoices-commercial-billing-contract.php
php tests/admin-v2-0-operations-command-center-contract.php
php tests/admin-v2-10-roles-permissions-approvals-contract.php
php tests/admin-v2-20-support-operations-contract.php
php tests/admin-v2-30-financial-reporting-contract.php
php tests/admin-v2-40-customer-success-contract.php
php tests/admin-v2-50-security-compliance-contract.php
php tests/admin-v2-60-platform-governance-contract.php
php tests/admin-v2-61-final-hardening-contract.php
php tests/admin-v2-70-admin-agent-contract.php
php tests/admin-v2-80-contextual-admin-agent-contract.php
php tests/admin-v2-90-proactive-admin-agent-contract.php
php tests/research-missions-v1-contract.php
php tests/research-missions-v1-section2-contract.php
php tests/research-missions-v1-section3-contract.php
php tests/research-missions-v1-section4-contract.php
php tests/research-missions-v1-section5-contract.php
php tests/research-missions-v1-section6-contract.php
php tests/research-missions-v1-section7-contract.php
php tests/phase71-section1-decision-ledger-contract.php
php tests/phase71-section2-mission-decision-handoff-contract.php
php tests/phase71-section3-decision-evidence-challenge-graph-contract.php
php tests/phase71-section4-outcome-memory-contract.php
php tests/phase71-section5-decision-evolution-reconsideration-contract.php
php tests/phase71-section6-agent-now-report-integration-contract.php
php tests/phase71-section7-decision-command-center-team-review-contract.php
php tests/phase71-section8-end-to-end-release-contract.php
php tests/post-phase71-research-publications-ui-hotfix-contract.php
php tests/phase72-section1-action-plan-ledger-contract.php
php tests/phase72-section2-milestones-tasks-dependencies-contract.php
php tests/phase72-section3-programs-recurring-follow-through-contract.php
php tests/phase72-section4-execution-evidence-variance-contract.php
php tests/phase72-section5-agent-cognition-contract.php
php tests/phase72-section6-team-command-review-contract.php
php tests/phase72-section7-outcome-handoff-contract.php
php tests/phase72-section8-end-to-end-release-contract.php
php tests/phase73-section1-portfolio-native-decision-handoff-contract.php
php tests/phase73-section2-portfolio-decision-execution-rollups-contract.php
php tests/phase73-section3-cross-decision-learning-pattern-memory-contract.php
php tests/phase73-section4-strategic-dependency-conflict-graph-contract.php
php tests/phase73-section5-recurring-strategic-review-contract.php
php tests/phase73-section6-executive-strategic-briefings-team-review-contract.php
php tests/phase73-section7-organizational-agent-cognition-contract.php
php tests/phase73-section8-end-to-end-release-contract.php
php tests/phase74-section1-canonical-ui-compatibility-map-contract.php
php tests/phase74-section2-unified-research-agent-shell-contract.php
php tests/phase74-section3-unified-knowledge-ui-contract.php
php tests/research-folder-canvas-contract.php
php tests/workspace-library-canvas-contract.php
php -n tests/runtime-compat-contract.php
php -n tests/installer-runtime-compat-contract.php
php tests/concurrency-contracts.php
php tests/rate-limit-contracts.php
php tests/v1-rc-e2e-contract.php
php tests/phase32-unified-continuity-actions.php

while IFS= read -r test_file; do
  php "$test_file"
done < <(find tests -maxdepth 1 -type f -name 'phase*-contract.php' -print | sort -V)
