<?php
declare(strict_types=1);

function admin_customer_success_ready(PDO $pdo): bool {
    try{
        foreach(['admin_customer_success_assignments','admin_customer_health_snapshots','admin_customer_success_plans','admin_customer_success_milestones','admin_customer_success_followups','admin_customer_success_events'] as $table)if(!installer_table_exists($pdo,$table))return false;
        return true;
    }catch(Throwable $e){return false;}
}
function admin_customer_success_reason(string $value,string $fallback='Customer Success record updated.'): string {
    $value=trim($value);if($value==='')$value=$fallback;return mb_substr($value,0,1000);
}
function admin_customer_success_security_audit(PDO $pdo,array $admin,string $subjectPublicId,string $eventType,mixed $before,mixed $after,string $reason): void {
    if(function_exists('admin_access_security_audit')&&admin_access_ready($pdo))admin_access_security_audit($pdo,$admin,'action',$subjectPublicId,$eventType,$before,$after,admin_customer_success_reason($reason));
}
function admin_customer_success_event(PDO $pdo,int $accountId,?int $actorUserId,string $eventType,?string $subjectType,?string $subjectPublicId,mixed $before,mixed $after,string $reason): void {
    if(!admin_customer_success_ready($pdo))return;$enc=fn(mixed $v)=>$v===null?null:json_encode($v,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);
    $pdo->prepare("INSERT INTO admin_customer_success_events(public_id,account_id,actor_user_id,event_type,subject_type,subject_public_id,before_json,after_json,reason) VALUES(?,?,?,?,?,?,?,?,?)")->execute([ulid_like(),$accountId,$actorUserId,mb_substr($eventType,0,80),$subjectType!==null?mb_substr($subjectType,0,80):null,$subjectPublicId!==null?mb_substr($subjectPublicId,0,255):null,$enc($before),$enc($after),admin_customer_success_reason($reason)]);
}
function admin_customer_success_events(PDO $pdo,int $accountId,int $limit=200): array {
    if(!admin_customer_success_ready($pdo))return [];$limit=max(1,min(500,$limit));$q=$pdo->prepare("SELECT e.*,u.username actor_username,u.display_name actor_display_name FROM admin_customer_success_events e LEFT JOIN users u ON u.id=e.actor_user_id WHERE e.account_id=? ORDER BY e.created_at DESC,e.id DESC LIMIT ".$limit);$q->execute([$accountId]);return $q->fetchAll()?:[];
}
function admin_customer_success_assignment(PDO $pdo,int $accountId): ?array {
    if(!admin_customer_success_ready($pdo))return null;$q=$pdo->prepare("SELECT a.*,u.username owner_username,u.display_name owner_display_name,u.email owner_email FROM admin_customer_success_assignments a LEFT JOIN users u ON u.id=a.owner_user_id WHERE a.account_id=? LIMIT 1");$q->execute([$accountId]);return $q->fetch()?:null;
}
function admin_customer_success_operator_candidates(PDO $pdo,string $capability='admin.customer_success.manage'): array {
    $rows=$pdo->query("SELECT id,public_id,username,display_name,email,role,status FROM users WHERE role='admin' AND status='active' ORDER BY display_name,username,id")->fetchAll()?:[];$out=[];foreach($rows as $row)if(admin_access_has_capability($pdo,$row,$capability))$out[]=$row;return $out;
}
function admin_customer_success_assign(PDO $pdo,array $admin,int $accountId,?int $ownerUserId,string $reason): ?array {
    admin_access_assert_capability($pdo,$admin,'admin.customer_success.manage');if(!account_admin_get($pdo,$accountId))throw new RuntimeException('Account not found.');$reason=admin_customer_success_reason($reason,'Assign Customer Success owner.');$before=admin_customer_success_assignment($pdo,$accountId);
    if($ownerUserId!==null){$q=$pdo->prepare("SELECT id,public_id,username,display_name,email,role,status FROM users WHERE id=? AND role='admin' AND status='active' LIMIT 1");$q->execute([$ownerUserId]);$owner=$q->fetch();if(!$owner||!admin_access_has_capability($pdo,$owner,'admin.customer_success.manage'))throw new RuntimeException('Selected operator cannot manage Customer Success.');}
    $pdo->prepare("INSERT INTO admin_customer_success_assignments(account_id,owner_user_id,assigned_by_user_id,assigned_at) VALUES(?,?,?,NOW()) ON DUPLICATE KEY UPDATE owner_user_id=VALUES(owner_user_id),assigned_by_user_id=VALUES(assigned_by_user_id),assigned_at=NOW()")->execute([$accountId,$ownerUserId,(int)$admin['id']]);$after=admin_customer_success_assignment($pdo,$accountId);admin_customer_success_event($pdo,$accountId,(int)$admin['id'],'owner_assigned','account',(string)$accountId,$before,$after,$reason);
    if($ownerUserId!==null&&function_exists('notification_create')){$acct=account_admin_get($pdo,$accountId);notification_create($pdo,$ownerUserId,(int)$admin['id'],'customer_success_assigned','customer_success_account',(string)($acct['public_id']??$accountId),'Customer Success account assigned: '.(string)($acct['name']??'Account'),['dedupe_key'=>'customer-success-owner-'.$accountId.'-'.$ownerUserId.'-'.hash('sha256',$reason),'group_key'=>'customer-success-account-'.$accountId]);}
    if(function_exists('admin_access_security_audit')&&admin_access_ready($pdo))admin_access_security_audit($pdo,$admin,'action',(string)$accountId,'customer_success_owner_assigned',$before,$after,$reason);return $after;
}
function admin_customer_success_scalar(PDO $pdo,string $sql,array $params=[]): mixed {$q=$pdo->prepare($sql);$q->execute($params);return $q->fetchColumn();}
function admin_customer_success_latest_source_at(PDO $pdo,int $accountId): ?string {
    $dates=[];$add=function(string $table,string $field='created_at')use($pdo,$accountId,&$dates){if(!installer_table_exists($pdo,$table))return;try{$q=$pdo->prepare("SELECT MAX(".$field.") FROM ".$table." WHERE account_id=?");$q->execute([$accountId]);$v=$q->fetchColumn();if($v)$dates[]=(string)$v;}catch(Throwable $e){}};
    foreach(['account_admin_events','account_membership_events','subscription_package_events','ai_usage_events','admin_support_cases','admin_finance_reconciliation_exceptions','admin_customer_success_events'] as $table)$add($table);
    if(!$dates)return null;rsort($dates,SORT_STRING);return $dates[0]??null;
}
function admin_customer_success_health_inputs(PDO $pdo,int $accountId): array {
    $account=account_admin_get($pdo,$accountId);if(!$account)throw new RuntimeException('Account not found.');$members=account_admin_members($pdo,$accountId);$memberCount=count($members);$memberLimit=max(1,(int)($account['member_limit']??1));if(function_exists('account_admin_effective_member_limit'))try{$memberLimit=max(1,(int)account_admin_effective_member_limit($pdo,$accountId));}catch(Throwable $e){}
    $usage=null;if(function_exists('ai_usage_ready')&&ai_usage_ready($pdo))try{$usage=ai_usage_account_summary($pdo,$accountId);}catch(Throwable $e){}
    $lastAiAt=null;if(installer_table_exists($pdo,'ai_usage_events')){$q=$pdo->prepare("SELECT MAX(created_at) FROM ai_usage_events WHERE account_id=?");$q->execute([$accountId]);$lastAiAt=$q->fetchColumn()?:null;}
    $supportCases=function_exists('admin_support_ready')&&admin_support_ready($pdo)?admin_support_account_cases($pdo,$accountId,200):[];$openSupport=array_values(array_filter($supportCases,fn($c)=>!in_array((string)$c['status'],['resolved','closed'],true)));$urgentSupport=array_values(array_filter($openSupport,fn($c)=>in_array((string)$c['priority'],['urgent','high'],true)));$slaRisk=array_values(array_filter($openSupport,fn($c)=>!empty($c['sla_due_at'])&&strtotime((string)$c['sla_due_at'])<=time()+14400));
    $finance=function_exists('admin_finance_ready')&&admin_finance_ready($pdo)?admin_finance_account_summary($pdo,$accountId):['open_exceptions'=>0,'outstanding_cents'=>0];$criticalFinance=0;if(function_exists('admin_finance_ready')&&admin_finance_ready($pdo)){$q=$pdo->prepare("SELECT COUNT(*) FROM admin_finance_reconciliation_exceptions WHERE account_id=? AND severity='critical' AND status IN ('open','acknowledged')");$q->execute([$accountId]);$criticalFinance=(int)$q->fetchColumn();}
    $researchProjects=0;if(installer_table_exists($pdo,'research_projects')&&!empty($account['owner_user_id'])){$q=$pdo->prepare("SELECT COUNT(*) FROM research_projects WHERE owner_user_id=?");$q->execute([(int)$account['owner_user_id']]);$researchProjects=(int)$q->fetchColumn();}
    $activePlans=0;$openFollowups=0;$overdueFollowups=0;if(admin_customer_success_ready($pdo)){$q=$pdo->prepare("SELECT COUNT(*) FROM admin_customer_success_plans WHERE account_id=? AND status='active'");$q->execute([$accountId]);$activePlans=(int)$q->fetchColumn();$q=$pdo->prepare("SELECT COUNT(*) total,COALESCE(SUM(due_at<UTC_TIMESTAMP()),0) overdue FROM admin_customer_success_followups WHERE account_id=? AND status='open'");$q->execute([$accountId]);$r=$q->fetch()?:[];$openFollowups=(int)($r['total']??0);$overdueFollowups=(int)($r['overdue']??0);}
    return ['account'=>$account,'members'=>$members,'member_count'=>$memberCount,'member_limit'=>$memberLimit,'usage'=>$usage,'last_ai_at'=>$lastAiAt,'support_cases'=>$supportCases,'open_support_count'=>count($openSupport),'urgent_support_count'=>count($urgentSupport),'sla_risk_count'=>count($slaRisk),'finance'=>$finance,'critical_finance_count'=>$criticalFinance,'research_project_count'=>$researchProjects,'active_plan_count'=>$activePlans,'open_followup_count'=>$openFollowups,'overdue_followup_count'=>$overdueFollowups,'source_max_at'=>admin_customer_success_latest_source_at($pdo,$accountId)];
}
function admin_customer_success_calculate_health(PDO $pdo,int $accountId): array {
    $in=admin_customer_success_health_inputs($pdo,$accountId);$a=$in['account'];$score=100;$reasons=[];$opportunities=[];$now=time();$createdTs=strtotime((string)$a['created_at'])?:$now;$ageDays=max(0,(int)floor(($now-$createdTs)/86400));$impact=function(int $points,string $code,string $label,array $evidence=[])use(&$score,&$reasons){$score=max(0,min(100,$score+$points));$reasons[]=['code'=>$code,'impact'=>$points,'label'=>$label,'evidence'=>$evidence];};
    if((string)$a['status']!=='active')$impact(-35,'account_not_active','Account lifecycle is not active.',['status'=>$a['status']]);
    $subscription=(string)($a['subscription_status']??'active');if($subscription==='past_due')$impact(-25,'subscription_past_due','Subscription is past due.',['status'=>$subscription]);elseif($subscription==='paused')$impact(-35,'subscription_paused','Subscription is paused.',['status'=>$subscription]);elseif($subscription==='canceled')$impact(-45,'subscription_canceled','Subscription is canceled.',['status'=>$subscription]);elseif(in_array($subscription,['active','trialing'],true))$reasons[]=['code'=>'subscription_current','impact'=>0,'label'=>'Subscription is current.','evidence'=>['status'=>$subscription]];
    if($in['open_support_count']>0)$impact(-min(16,$in['open_support_count']*4),'open_support','Open support cases require attention.',['open_cases'=>$in['open_support_count']]);
    if($in['urgent_support_count']>0)$impact(-min(20,$in['urgent_support_count']*10),'priority_support','High/urgent support cases increase retention risk.',['high_or_urgent'=>$in['urgent_support_count']]);
    if($in['sla_risk_count']>0)$impact(-12,'support_sla_risk','A support case is at or near SLA risk.',['sla_risk'=>$in['sla_risk_count']]);
    if($in['critical_finance_count']>0)$impact(-min(40,$in['critical_finance_count']*20),'critical_finance','Critical finance reconciliation exceptions are unresolved.',['critical_exceptions'=>$in['critical_finance_count']]);
    $openFinance=(int)($in['finance']['open_exceptions']??0);if($openFinance>0)$impact(-min(15,$openFinance*5),'finance_exceptions','Open finance reconciliation exceptions remain.',['open_exceptions'=>$openFinance]);
    $outstanding=(int)($in['finance']['outstanding_cents']??0);if($outstanding>0)$impact(-10,'outstanding_receivable','Account has an outstanding receivable.',['outstanding_cents'=>$outstanding]);
    $lastAiTs=$in['last_ai_at']?strtotime((string)$in['last_ai_at']):false;$inactiveDays=$lastAiTs?max(0,(int)floor(($now-$lastAiTs)/86400)):null;if($ageDays>30&&$lastAiTs===false)$impact(-15,'no_ai_adoption','No recorded AI usage after the first 30 days.',['account_age_days'=>$ageDays]);elseif($inactiveDays!==null&&$inactiveDays>30)$impact(-12,'ai_activity_decline','No recorded AI usage in more than 30 days.',['inactive_days'=>$inactiveDays]);elseif($inactiveDays!==null&&$inactiveDays<=7)$reasons[]=['code'=>'recent_ai_activity','impact'=>0,'label'=>'AI activity was recorded in the last 7 days.','evidence'=>['inactive_days'=>$inactiveDays]];
    if($ageDays>30&&$in['research_project_count']===0)$impact(-5,'no_research_adoption','No Research Project adoption is recorded after 30 days.',['account_age_days'=>$ageDays]);
    if($ageDays>30&&$in['member_count']<=1&&$in['member_limit']>1)$impact(-5,'single_user_adoption','Team-capable account still has one member after 30 days.',['members'=>$in['member_count'],'member_limit'=>$in['member_limit']]);
    if($in['overdue_followup_count']>0)$impact(-min(10,$in['overdue_followup_count']*5),'overdue_success_followup','Customer Success follow-up is overdue.',['overdue_followups'=>$in['overdue_followup_count']]);
    $memberRatio=$in['member_limit']>0?$in['member_count']/$in['member_limit']:0;$used=(int)($in['usage']['used_tokens']??0);$allowance=$in['usage']['effective_allowance']??null;$usageRatio=is_int($allowance)&&$allowance>0?$used/$allowance:0;
    if($memberRatio>=.8&&$in['member_limit']>1)$opportunities[]=['code'=>'seat_expansion','label'=>'Team is approaching its member limit.','evidence'=>['members'=>$in['member_count'],'member_limit'=>$in['member_limit'],'ratio'=>round($memberRatio,3)]];
    if($usageRatio>=.8)$opportunities[]=['code'=>'ai_capacity_expansion','label'=>'AI usage is approaching the current allowance.','evidence'=>['used_tokens'=>$used,'allowance'=>$allowance,'ratio'=>round($usageRatio,3)]];
    if($in['research_project_count']>0&&$in['member_count']>1)$opportunities[]=['code'=>'multi_user_research_adoption','label'=>'Team and Research Project adoption indicate an established workflow.','evidence'=>['projects'=>$in['research_project_count'],'members'=>$in['member_count']]];
    $score=max(0,min(100,$score));$state=$score>=80?'healthy':($score>=60?'watch':($score>=40?'at_risk':'critical'));
    $recovery=in_array($subscription,['past_due','paused','canceled'],true)||$score<60;$stage=$recovery?'recovery':($ageDays<=14?'onboarding':($ageDays<=45||($used>0&&$in['research_project_count']===0)?'adopting':(($score>=80&&($memberRatio>=.8||$usageRatio>=.8))?'expansion_ready':'established')));
    $signals=['account_status'=>(string)$a['status'],'subscription_status'=>$subscription,'account_age_days'=>$ageDays,'member_count'=>$in['member_count'],'member_limit'=>$in['member_limit'],'member_utilization'=>round($memberRatio,3),'ai_used_tokens'=>$used,'ai_allowance'=>$allowance,'ai_utilization'=>round($usageRatio,3),'last_ai_at'=>$in['last_ai_at'],'research_project_count'=>$in['research_project_count'],'open_support_count'=>$in['open_support_count'],'priority_support_count'=>$in['urgent_support_count'],'support_sla_risk_count'=>$in['sla_risk_count'],'finance_open_exceptions'=>$openFinance,'finance_critical_exceptions'=>$in['critical_finance_count'],'outstanding_cents'=>$outstanding,'active_success_plans'=>$in['active_plan_count'],'open_followups'=>$in['open_followup_count'],'overdue_followups'=>$in['overdue_followup_count']];
    $onboarding=['account_created'=>true,'subscription_current'=>in_array($subscription,['active','trialing'],true),'first_ai_usage'=>$used>0||$in['last_ai_at']!==null,'first_research_project'=>$in['research_project_count']>0,'team_member_added'=>$in['member_count']>1,'success_owner_assigned'=>admin_customer_success_assignment($pdo,$accountId)!==null];
    $payload=['health_score'=>$score,'health_state'=>$state,'lifecycle_stage'=>$stage,'signals'=>$signals,'reasons'=>$reasons,'opportunities'=>$opportunities,'onboarding'=>$onboarding,'source_max_at'=>$in['source_max_at']];$fingerprint=hash('sha256',json_encode([$state,$stage,$signals,$reasons,$opportunities,$onboarding],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));$payload['fingerprint']=$fingerprint;return $payload;
}
function admin_customer_success_latest_snapshot(PDO $pdo,int $accountId): ?array {
    if(!admin_customer_success_ready($pdo))return null;$q=$pdo->prepare("SELECT s.*,u.username created_by_username FROM admin_customer_health_snapshots s JOIN users u ON u.id=s.created_by_user_id WHERE s.account_id=? ORDER BY s.created_at DESC,s.id DESC LIMIT 1");$q->execute([$accountId]);$r=$q->fetch();if(!$r)return null;foreach(['signals_json'=>'signals','reasons_json'=>'reasons','opportunities_json'=>'opportunities'] as $field=>$key){try{$r[$key]=json_decode((string)$r[$field],true,512,JSON_THROW_ON_ERROR)?:[];}catch(Throwable $e){$r[$key]=[];}}return $r;
}
function admin_customer_success_snapshot(PDO $pdo,array $admin,int $accountId,bool $force=false): array {
    admin_access_assert_capability($pdo,$admin,'admin.customer_success.manage');$health=admin_customer_success_calculate_health($pdo,$accountId);$latest=admin_customer_success_latest_snapshot($pdo,$accountId);if(!$force&&$latest&&hash_equals((string)$latest['fingerprint'],(string)$health['fingerprint']))return ['snapshot'=>$latest,'created'=>false,'health'=>$health];
    $pdo->prepare("INSERT INTO admin_customer_health_snapshots(public_id,account_id,health_score,health_state,lifecycle_stage,signals_json,reasons_json,opportunities_json,fingerprint,source_max_at,created_by_user_id) VALUES(?,?,?,?,?,?,?,?,?,?,?)")->execute([ulid_like(),$accountId,(int)$health['health_score'],$health['health_state'],$health['lifecycle_stage'],json_encode($health['signals'],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR),json_encode($health['reasons'],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR),json_encode($health['opportunities'],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR),$health['fingerprint'],$health['source_max_at'],(int)$admin['id']]);$snapshot=admin_customer_success_latest_snapshot($pdo,$accountId)??throw new RuntimeException('Health snapshot could not be reloaded.');$before=$latest?['score'=>$latest['health_score'],'state'=>$latest['health_state'],'stage'=>$latest['lifecycle_stage']]:null;$after=['score'=>$snapshot['health_score'],'state'=>$snapshot['health_state'],'stage'=>$snapshot['lifecycle_stage']];admin_customer_success_event($pdo,$accountId,(int)$admin['id'],'health_snapshot','health_snapshot',(string)$snapshot['public_id'],$before,$after,'Refresh explainable account health snapshot.');admin_customer_success_security_audit($pdo,$admin,(string)$snapshot['public_id'],'customer_success_health_snapshot',$before,$after,'Refresh explainable account health snapshot.');return ['snapshot'=>$snapshot,'created'=>true,'health'=>$health];
}
function admin_customer_success_refresh(PDO $pdo,array $admin,int $limit=500): array {
    admin_access_assert_capability($pdo,$admin,'admin.customer_success.manage');$limit=max(1,min(1000,$limit));$ids=$pdo->query("SELECT id FROM accounts WHERE status<>'closed' ORDER BY updated_at DESC,id DESC LIMIT ".$limit)->fetchAll(PDO::FETCH_COLUMN)?:[];$created=0;$unchanged=0;$states=['healthy'=>0,'watch'=>0,'at_risk'=>0,'critical'=>0];foreach($ids as $id){$r=admin_customer_success_snapshot($pdo,$admin,(int)$id,false);$r['created']?$created++:$unchanged++;$state=(string)$r['health']['health_state'];$states[$state]=($states[$state]??0)+1;}if(function_exists('admin_access_security_audit')&&admin_access_ready($pdo))admin_access_security_audit($pdo,$admin,'action',null,'customer_success_health_refresh',null,['accounts'=>count($ids),'created'=>$created,'unchanged'=>$unchanged,'states'=>$states],'Refresh explainable Customer Success health snapshots.');return ['accounts'=>count($ids),'created'=>$created,'unchanged'=>$unchanged,'states'=>$states];
}
function admin_customer_success_filters(array $input): array {
    $out=[];foreach(['q','state','stage','owner'] as $key){$v=trim((string)($input[$key]??''));if($v!=='')$out[$key]=$v;}if(!empty($input['followup_due']))$out['followup_due']='1';if(!empty($input['unassigned']))$out['unassigned']='1';return $out;
}
function admin_customer_success_portfolio(PDO $pdo,array $viewer,array $filters=[],int $limit=300): array {
    $filters=admin_customer_success_filters($filters);$rows=admin_ui_account_rows($pdo,['q'=>$filters['q']??''],max(1,min(500,$limit)));$out=[];foreach($rows as $row){if((string)($row['status']??'active')==='closed')continue;$assignment=admin_customer_success_assignment($pdo,(int)$row['id']);$snapshot=admin_customer_success_latest_snapshot($pdo,(int)$row['id']);$health=$snapshot?['health_score'=>(int)$snapshot['health_score'],'health_state'=>$snapshot['health_state'],'lifecycle_stage'=>$snapshot['lifecycle_stage'],'signals'=>$snapshot['signals'],'reasons'=>$snapshot['reasons'],'opportunities'=>$snapshot['opportunities'],'source_max_at'=>$snapshot['source_max_at'],'fingerprint'=>$snapshot['fingerprint']]:admin_customer_success_calculate_health($pdo,(int)$row['id']);$q=$pdo->prepare("SELECT COUNT(*) total,COALESCE(SUM(due_at<UTC_TIMESTAMP()),0) overdue,MIN(due_at) next_due FROM admin_customer_success_followups WHERE account_id=? AND status='open'");$q->execute([(int)$row['id']]);$follow=$q->fetch()?:[];$item=$row;$item['success_assignment']=$assignment;$item['health']=$health;$item['open_followups']=(int)($follow['total']??0);$item['overdue_followups']=(int)($follow['overdue']??0);$item['next_followup_at']=$follow['next_due']??null;
        if(isset($filters['state'])&&$health['health_state']!==$filters['state'])continue;if(isset($filters['stage'])&&$health['lifecycle_stage']!==$filters['stage'])continue;if(isset($filters['owner'])){if($filters['owner']==='me'&&(int)($assignment['owner_user_id']??0)!==(int)$viewer['id'])continue;if(ctype_digit($filters['owner'])&&(int)($assignment['owner_user_id']??0)!==(int)$filters['owner'])continue;}if(isset($filters['unassigned'])&&!empty($assignment['owner_user_id']))continue;if(isset($filters['followup_due'])&&(int)$item['overdue_followups']<1)continue;$out[]=$item;}
    usort($out,function($a,$b){$rank=['critical'=>0,'at_risk'=>1,'watch'=>2,'healthy'=>3];$ra=$rank[$a['health']['health_state']]??9;$rb=$rank[$b['health']['health_state']]??9;if($ra!==$rb)return $ra<=>$rb;if((int)$a['overdue_followups']!==(int)$b['overdue_followups'])return (int)$b['overdue_followups']<=>(int)$a['overdue_followups'];return strcmp((string)($b['health']['source_max_at']??$b['updated_at']),(string)($a['health']['source_max_at']??$a['updated_at']));});return $out;
}
function admin_customer_success_metrics(PDO $pdo,array $viewer): array {
    $portfolio=admin_customer_success_portfolio($pdo,$viewer,[],500);$m=['total'=>count($portfolio),'healthy'=>0,'watch'=>0,'at_risk'=>0,'critical'=>0,'onboarding'=>0,'expansion_ready'=>0,'recovery'=>0,'unassigned'=>0,'overdue_followups'=>0];foreach($portfolio as $a){$state=(string)$a['health']['health_state'];$stage=(string)$a['health']['lifecycle_stage'];$m[$state]=($m[$state]??0)+1;$m[$stage]=($m[$stage]??0)+1;if(empty($a['success_assignment']['owner_user_id']))$m['unassigned']++;$m['overdue_followups']+=(int)$a['overdue_followups'];}return $m;
}
function admin_customer_success_workload(PDO $pdo): array {
    if(!admin_customer_success_ready($pdo))return [];$q=$pdo->query("SELECT u.id,u.username,u.display_name,COUNT(a.account_id) account_count FROM users u LEFT JOIN admin_customer_success_assignments a ON a.owner_user_id=u.id WHERE u.role='admin' AND u.status='active' GROUP BY u.id,u.username,u.display_name HAVING account_count>0 ORDER BY account_count DESC,u.display_name,u.username");return $q->fetchAll()?:[];
}
function admin_customer_success_followups(PDO $pdo,?int $accountId=null,?int $assignedUserId=null,string $status='open',int $limit=200): array {
    if(!admin_customer_success_ready($pdo))return [];$limit=max(1,min(500,$limit));$where=[];$params=[];if($accountId!==null){$where[]='f.account_id=?';$params[]=$accountId;}if($assignedUserId!==null){$where[]='f.assigned_user_id=?';$params[]=$assignedUserId;}if($status!==''){$where[]='f.status=?';$params[]=$status;}$sql="SELECT f.*,a.public_id account_public_id,a.name account_name,u.username assigned_username,u.display_name assigned_display_name FROM admin_customer_success_followups f JOIN accounts a ON a.id=f.account_id LEFT JOIN users u ON u.id=f.assigned_user_id".($where?' WHERE '.implode(' AND ',$where):'')." ORDER BY CASE WHEN f.status='open' AND f.due_at<UTC_TIMESTAMP() THEN 0 ELSE 1 END,FIELD(f.priority,'urgent','high','normal','low'),f.due_at,f.id LIMIT ".$limit;$q=$pdo->prepare($sql);$q->execute($params);return $q->fetchAll()?:[];
}
function admin_customer_success_followup_create(PDO $pdo,array $admin,int $accountId,array $input): array {
    admin_access_assert_capability($pdo,$admin,'admin.customer_success.manage');if(!account_admin_get($pdo,$accountId))throw new RuntimeException('Account not found.');$title=mb_substr(trim((string)($input['title']??'')),0,190);if($title==='')throw new InvalidArgumentException('Follow-up title is required.');$due=trim((string)($input['due_at']??''));$ts=strtotime($due);if($ts===false)throw new InvalidArgumentException('A valid follow-up due date/time is required.');$assigned=!empty($input['assigned_user_id'])?(int)$input['assigned_user_id']:null;if($assigned!==null){$valid=array_filter(admin_customer_success_operator_candidates($pdo),fn($u)=>(int)$u['id']===$assigned);if(!$valid)throw new RuntimeException('Assigned operator cannot manage Customer Success.');}$priority=in_array((string)($input['priority']??'normal'),['low','normal','high','urgent'],true)?(string)$input['priority']:'normal';$note=trim((string)($input['note']??''));$public=ulid_like();$pdo->prepare("INSERT INTO admin_customer_success_followups(public_id,account_id,assigned_user_id,title,note,priority,status,due_at,created_by_user_id,updated_by_user_id) VALUES(?,?,?,?,?,?,'open',?,?,?)")->execute([$public,$accountId,$assigned,$title,$note!==''?$note:null,$priority,gmdate('Y-m-d H:i:s',$ts),(int)$admin['id'],(int)$admin['id']]);$q=$pdo->prepare("SELECT * FROM admin_customer_success_followups WHERE public_id=?");$q->execute([$public]);$row=$q->fetch()?:throw new RuntimeException('Follow-up could not be reloaded.');admin_customer_success_event($pdo,$accountId,(int)$admin['id'],'followup_created','followup',$public,null,$row,(string)($input['reason']??'Create Customer Success follow-up.'));admin_customer_success_security_audit($pdo,$admin,$public,'customer_success_followup_created',null,['account_id'=>$accountId,'assigned_user_id'=>$assigned,'priority'=>$priority,'due_at'=>$row['due_at']],(string)($input['reason']??'Create Customer Success follow-up.'));if($assigned!==null&&function_exists('notification_create')){$acct=account_admin_get($pdo,$accountId);notification_create($pdo,$assigned,(int)$admin['id'],'customer_success_followup','customer_success_account',(string)$acct['public_id'],'Customer Success follow-up: '.$title,['dedupe_key'=>'customer-success-followup-'.$public,'group_key'=>'customer-success-account-'.$accountId]);}return $row;
}
function admin_customer_success_followup_update(PDO $pdo,array $admin,string $publicId,string $operation,string $reason): array {
    admin_access_assert_capability($pdo,$admin,'admin.customer_success.manage');$q=$pdo->prepare("SELECT * FROM admin_customer_success_followups WHERE public_id=? LIMIT 1");$q->execute([$publicId]);$row=$q->fetch();if(!$row)throw new RuntimeException('Customer Success follow-up not found.');$reason=admin_customer_success_reason($reason);$before=$row;if($operation==='complete'){if($row['status']!=='open')throw new RuntimeException('Only open follow-ups can be completed.');$pdo->prepare("UPDATE admin_customer_success_followups SET status='completed',completed_at=NOW(),updated_by_user_id=? WHERE id=?")->execute([(int)$admin['id'],(int)$row['id']]);}elseif($operation==='cancel'){if($row['status']!=='open')throw new RuntimeException('Only open follow-ups can be cancelled.');$pdo->prepare("UPDATE admin_customer_success_followups SET status='cancelled',updated_by_user_id=? WHERE id=?")->execute([(int)$admin['id'],(int)$row['id']]);}elseif($operation==='reopen'){if(!in_array($row['status'],['completed','cancelled'],true))throw new RuntimeException('Only completed or cancelled follow-ups can be reopened.');$pdo->prepare("UPDATE admin_customer_success_followups SET status='open',completed_at=NULL,updated_by_user_id=? WHERE id=?")->execute([(int)$admin['id'],(int)$row['id']]);}else throw new RuntimeException('Unknown follow-up operation.');$q->execute([$publicId]);$after=$q->fetch()?:$row;admin_customer_success_event($pdo,(int)$row['account_id'],(int)$admin['id'],'followup_'.$operation,'followup',$publicId,$before,$after,$reason);admin_customer_success_security_audit($pdo,$admin,$publicId,'customer_success_followup_'.$operation,['status'=>$before['status']],['status'=>$after['status']],$reason);return $after;
}
function admin_customer_success_plan_create(PDO $pdo,array $admin,int $accountId,array $input): array {
    admin_access_assert_capability($pdo,$admin,'admin.customer_success.manage');if(!account_admin_get($pdo,$accountId))throw new RuntimeException('Account not found.');$title=mb_substr(trim((string)($input['title']??'')),0,190);$objective=trim((string)($input['objective']??''));if($title===''||$objective==='')throw new InvalidArgumentException('Success plan title and objective are required.');$owner=!empty($input['owner_user_id'])?(int)$input['owner_user_id']:null;if($owner!==null){$valid=array_filter(admin_customer_success_operator_candidates($pdo),fn($u)=>(int)$u['id']===$owner);if(!$valid)throw new RuntimeException('Plan owner cannot manage Customer Success.');}$target=trim((string)($input['target_date']??''));if($target!==''&&!preg_match('/^\d{4}-\d{2}-\d{2}$/',$target))throw new InvalidArgumentException('Success plan target date is invalid.');$public=ulid_like();$pdo->prepare("INSERT INTO admin_customer_success_plans(public_id,account_id,owner_user_id,title,objective,status,target_date,created_by_user_id,updated_by_user_id) VALUES(?,?,?,?,?,'active',?,?,?)")->execute([$public,$accountId,$owner,$title,$objective,$target!==''?$target:null,(int)$admin['id'],(int)$admin['id']]);$q=$pdo->prepare("SELECT * FROM admin_customer_success_plans WHERE public_id=?");$q->execute([$public]);$row=$q->fetch()?:throw new RuntimeException('Success plan could not be reloaded.');admin_customer_success_event($pdo,$accountId,(int)$admin['id'],'plan_created','success_plan',$public,null,$row,(string)($input['reason']??'Create Customer Success plan.'));admin_customer_success_security_audit($pdo,$admin,$public,'customer_success_plan_created',null,['account_id'=>$accountId,'owner_user_id'=>$owner,'status'=>'active'],(string)($input['reason']??'Create Customer Success plan.'));return $row;
}
function admin_customer_success_plans(PDO $pdo,int $accountId): array {
    if(!admin_customer_success_ready($pdo))return [];$q=$pdo->prepare("SELECT p.*,u.username owner_username,u.display_name owner_display_name FROM admin_customer_success_plans p LEFT JOIN users u ON u.id=p.owner_user_id WHERE p.account_id=? ORDER BY FIELD(p.status,'active','paused','completed','cancelled'),p.target_date IS NULL,p.target_date,p.updated_at DESC,p.id DESC");$q->execute([$accountId]);$plans=$q->fetchAll()?:[];foreach($plans as &$p){$q2=$pdo->prepare("SELECT * FROM admin_customer_success_milestones WHERE plan_id=? ORDER BY sort_order,due_at IS NULL,due_at,id");$q2->execute([(int)$p['id']]);$p['milestones']=$q2->fetchAll()?:[];}unset($p);return $plans;
}
function admin_customer_success_plan_update(PDO $pdo,array $admin,string $publicId,string $operation,string $reason): array {
    admin_access_assert_capability($pdo,$admin,'admin.customer_success.manage');$q=$pdo->prepare("SELECT * FROM admin_customer_success_plans WHERE public_id=? LIMIT 1");$q->execute([$publicId]);$row=$q->fetch();if(!$row)throw new RuntimeException('Success plan not found.');$reason=admin_customer_success_reason($reason);$before=$row;$status=match($operation){'pause'=>'paused','resume'=>'active','complete'=>'completed','cancel'=>'cancelled',default=>throw new RuntimeException('Unknown success plan operation.')};$completed=$status==='completed'?gmdate('Y-m-d H:i:s'):null;$pdo->prepare("UPDATE admin_customer_success_plans SET status=?,completed_at=?,updated_by_user_id=? WHERE id=?")->execute([$status,$completed,(int)$admin['id'],(int)$row['id']]);$q->execute([$publicId]);$after=$q->fetch()?:$row;admin_customer_success_event($pdo,(int)$row['account_id'],(int)$admin['id'],'plan_'.$operation,'success_plan',$publicId,$before,$after,$reason);admin_customer_success_security_audit($pdo,$admin,$publicId,'customer_success_plan_'.$operation,['status'=>$before['status']],['status'=>$after['status']],$reason);return $after;
}
function admin_customer_success_milestone_create(PDO $pdo,array $admin,string $planPublicId,array $input): array {
    admin_access_assert_capability($pdo,$admin,'admin.customer_success.manage');$q=$pdo->prepare("SELECT * FROM admin_customer_success_plans WHERE public_id=? LIMIT 1");$q->execute([$planPublicId]);$plan=$q->fetch();if(!$plan)throw new RuntimeException('Success plan not found.');$title=mb_substr(trim((string)($input['title']??'')),0,190);if($title==='')throw new InvalidArgumentException('Milestone title is required.');$due=trim((string)($input['due_at']??''));$dueSql=null;if($due!==''){$ts=strtotime($due);if($ts===false)throw new InvalidArgumentException('Milestone due date is invalid.');$dueSql=gmdate('Y-m-d H:i:s',$ts);}$public=ulid_like();$sort=(int)($input['sort_order']??0);$pdo->prepare("INSERT INTO admin_customer_success_milestones(public_id,plan_id,title,status,due_at,sort_order,created_by_user_id,updated_by_user_id) VALUES(?,? ,?,'pending',?,?,?,?)")->execute([$public,(int)$plan['id'],$title,$dueSql,$sort,(int)$admin['id'],(int)$admin['id']]);$q=$pdo->prepare("SELECT * FROM admin_customer_success_milestones WHERE public_id=?");$q->execute([$public]);$row=$q->fetch()?:throw new RuntimeException('Milestone could not be reloaded.');admin_customer_success_event($pdo,(int)$plan['account_id'],(int)$admin['id'],'milestone_created','milestone',$public,null,$row,(string)($input['reason']??'Add success-plan milestone.'));admin_customer_success_security_audit($pdo,$admin,$public,'customer_success_milestone_created',null,['plan_public_id'=>$planPublicId,'status'=>'pending'],(string)($input['reason']??'Add success-plan milestone.'));return $row;
}
function admin_customer_success_milestone_update(PDO $pdo,array $admin,string $publicId,string $status,string $reason): array {
    admin_access_assert_capability($pdo,$admin,'admin.customer_success.manage');if(!in_array($status,['pending','in_progress','completed','blocked'],true))throw new InvalidArgumentException('Milestone status is invalid.');$q=$pdo->prepare("SELECT m.*,p.account_id FROM admin_customer_success_milestones m JOIN admin_customer_success_plans p ON p.id=m.plan_id WHERE m.public_id=? LIMIT 1");$q->execute([$publicId]);$row=$q->fetch();if(!$row)throw new RuntimeException('Milestone not found.');$before=$row;$pdo->prepare("UPDATE admin_customer_success_milestones SET status=?,completed_at=CASE WHEN ?='completed' THEN NOW() ELSE NULL END,updated_by_user_id=? WHERE id=?")->execute([$status,$status,(int)$admin['id'],(int)$row['id']]);$q->execute([$publicId]);$after=$q->fetch()?:$row;$reason=admin_customer_success_reason($reason);admin_customer_success_event($pdo,(int)$row['account_id'],(int)$admin['id'],'milestone_status','milestone',$publicId,$before,$after,$reason);admin_customer_success_security_audit($pdo,$admin,$publicId,'customer_success_milestone_status',['status'=>$before['status']],['status'=>$after['status']],$reason);return $after;
}
function admin_customer_success_health_history(PDO $pdo,int $accountId,int $limit=100): array {
    if(!admin_customer_success_ready($pdo))return [];$limit=max(1,min(300,$limit));$q=$pdo->prepare("SELECT s.*,u.username created_by_username FROM admin_customer_health_snapshots s JOIN users u ON u.id=s.created_by_user_id WHERE s.account_id=? ORDER BY s.created_at DESC,s.id DESC LIMIT ".$limit);$q->execute([$accountId]);$rows=$q->fetchAll()?:[];foreach($rows as &$r){try{$r['reasons']=json_decode((string)$r['reasons_json'],true,512,JSON_THROW_ON_ERROR)?:[];$r['opportunities']=json_decode((string)$r['opportunities_json'],true,512,JSON_THROW_ON_ERROR)?:[];$r['signals']=json_decode((string)$r['signals_json'],true,512,JSON_THROW_ON_ERROR)?:[];}catch(Throwable $e){$r['reasons']=$r['opportunities']=$r['signals']=[];}}unset($r);return $rows;
}
function admin_customer_success_account(PDO $pdo,array $viewer,int $accountId): array {
    $account=account_admin_get($pdo,$accountId);if(!$account)throw new RuntimeException('Account not found.');$health=admin_customer_success_latest_snapshot($pdo,$accountId);$current=admin_customer_success_calculate_health($pdo,$accountId);$canSupport=admin_access_has_capability($pdo,$viewer,'admin.support.view');$canFinance=admin_access_has_capability($pdo,$viewer,'admin.finance.view');$canUsage=admin_access_has_capability($pdo,$viewer,'admin.ai_usage.view');
    return ['account'=>$account,'current_health'=>$current,'latest_snapshot'=>$health,'assignment'=>admin_customer_success_assignment($pdo,$accountId),'plans'=>admin_customer_success_plans($pdo,$accountId),'followups'=>admin_customer_success_followups($pdo,$accountId,null,'',200),'events'=>admin_customer_success_events($pdo,$accountId,200),'health_history'=>admin_customer_success_health_history($pdo,$accountId,100),'support'=>$canSupport&&function_exists('admin_support_ready')&&admin_support_ready($pdo)?admin_support_account_cases($pdo,$accountId,50):[],'finance'=>$canFinance&&function_exists('admin_finance_ready')&&admin_finance_ready($pdo)?admin_finance_account_summary($pdo,$accountId):null,'members'=>account_admin_members($pdo,$accountId),'usage'=>$canUsage&&function_exists('ai_usage_ready')&&ai_usage_ready($pdo)?ai_usage_account_summary($pdo,$accountId):null,'source_access'=>['support'=>$canSupport,'finance'=>$canFinance,'ai_usage'=>$canUsage]];
}
function admin_customer_success_agent_context(PDO $pdo,array $viewer): string {
    if(($viewer['role']??'')!=='admin'||!admin_customer_success_ready($pdo)||!admin_access_has_capability($pdo,$viewer,'admin.customer_success.view'))return '';$m=admin_customer_success_metrics($pdo,$viewer);return "[ADMIN V2.40 CUSTOMER SUCCESS — READ ONLY]\nAccounts: {$m['total']}; healthy: {$m['healthy']}; watch: {$m['watch']}; at risk: {$m['at_risk']}; critical: {$m['critical']}; onboarding: {$m['onboarding']}; expansion ready: {$m['expansion_ready']}; recovery: {$m['recovery']}; overdue follow-ups: {$m['overdue_followups']}. Health is a deterministic explainable signal index backed by stored reasons and evidence, not an AI prediction. The Agent may summarize changes, risks, opportunities and draft a success plan, but cannot assign owners, change health snapshots, create/complete follow-ups, alter plans/milestones, send customer communications, or execute account/billing actions.";
}
