<?php
declare(strict_types=1);

function commercial_promotions_ready(PDO $pdo): bool {
    try{
        foreach(['commercial_promotions','commercial_promotion_stripe_mappings','commercial_promotion_redemptions','commercial_discount_events','commercial_credit_adjustments','commercial_audit_events'] as $table){
            if(!installer_table_exists($pdo,$table))return false;
        }
        return true;
    }catch(Throwable $e){return false;}
}
function commercial_audit(PDO $pdo,?int $promotionId,?int $accountId,?int $actorUserId,string $eventType,mixed $before,mixed $after,string $reason): void {
    if(!commercial_promotions_ready($pdo))return;
    $pdo->prepare('INSERT INTO commercial_audit_events(public_id,promotion_id,account_id,actor_user_id,event_type,before_json,after_json,reason) VALUES(?,?,?,?,?,?,?,?)')
      ->execute([ulid_like(),$promotionId,$accountId,$actorUserId,mb_substr($eventType,0,100),$before===null?null:json_encode($before,JSON_UNESCAPED_SLASHES),$after===null?null:json_encode($after,JSON_UNESCAPED_SLASHES),mb_substr($reason,0,500)]);
}
function commercial_normalize_code(string $code): string {
    $code=strtoupper(trim($code));
    if($code===''||strlen($code)<3||strlen($code)>40||!preg_match('/^[A-Z0-9-]+$/',$code))throw new InvalidArgumentException('Promotion codes must use 3–40 letters, numbers, or dashes.');
    return $code;
}
function commercial_datetime_or_null(mixed $value): ?string {
    $raw=trim((string)$value);if($raw==='')return null;
    try{$dt=new DateTimeImmutable($raw,new DateTimeZone('UTC'));}catch(Throwable $e){throw new InvalidArgumentException('Promotion date/time is invalid.');}
    return $dt->setTimezone(new DateTimeZone('UTC'))->format('Y-m-d H:i:s');
}
function commercial_promotion(PDO $pdo,string $publicId): ?array {
    if(!commercial_promotions_ready($pdo))return null;$q=$pdo->prepare('SELECT * FROM commercial_promotions WHERE public_id=? LIMIT 1');$q->execute([$publicId]);return $q->fetch()?:null;
}
function commercial_promotion_by_code(PDO $pdo,string $code): ?array {
    if(!commercial_promotions_ready($pdo))return null;$code=commercial_normalize_code($code);$q=$pdo->prepare('SELECT * FROM commercial_promotions WHERE code=? LIMIT 1');$q->execute([$code]);return $q->fetch()?:null;
}
function commercial_promotion_package_ids(PDO $pdo,array $input): array {
    $ids=[];foreach((array)($input['package_ids']??[]) as $public){$p=subscription_package($pdo,(string)$public);if($p)$ids[]=(int)$p['id'];}
    $ids=array_values(array_unique($ids));sort($ids,SORT_NUMERIC);return $ids;
}
function commercial_promotion_values(PDO $pdo,array $input,?array $current=null): array {
    $type=in_array((string)($input['discount_type']??($current['discount_type']??'')),['percent','fixed_amount'],true)?(string)($input['discount_type']??$current['discount_type']):'percent';
    $percent=null;$amount=null;
    if($type==='percent'){$percent=(int)round(((float)($input['percent_off']??(($current['percent_basis_points']??0)/100)))*100);if($percent<1||$percent>10000)throw new InvalidArgumentException('Percent discount must be greater than 0 and no more than 100%.');}
    else{$amount=(int)round(((float)($input['amount_off_dollars']??(($current['amount_off_cents']??0)/100)))*100);if($amount<1)throw new InvalidArgumentException('Fixed discount must be at least $0.01.');}
    $duration=in_array((string)($input['duration']??($current['duration']??'once')),['once','repeating','forever'],true)?(string)($input['duration']??$current['duration']):'once';
    $months=$duration==='repeating'?max(1,min(60,(int)($input['duration_months']??($current['duration_months']??1)))):null;
    $scope=in_array((string)($input['customer_scope']??($current['customer_scope']??'all')),['all','new_customers','existing_customers'],true)?(string)($input['customer_scope']??$current['customer_scope']):'all';
    $status=in_array((string)($input['status']??($current['status']??'draft')),['draft','active','archived'],true)?(string)($input['status']??$current['status']):'draft';
    $maxRaw=trim((string)($input['max_redemptions']??($current['max_redemptions']??'')));$max=$maxRaw===''?null:max(1,(int)$maxRaw);
    $limit=max(1,min(100,(int)($input['per_account_limit']??($current['per_account_limit']??1))));
    $minRaw=trim((string)($input['minimum_package_dollars']??($current['minimum_package_amount_cents']===null?'':((int)$current['minimum_package_amount_cents'])/100)));$minimum=$minRaw===''?null:max(0,(int)round(((float)$minRaw)*100));
    $packages=array_key_exists('package_ids',$input)?commercial_promotion_package_ids($pdo,$input):(json_decode((string)($current['eligible_package_ids_json']??'[]'),true)?:[]);
    return ['status'=>$status,'discount_type'=>$type,'percent_basis_points'=>$percent,'amount_off_cents'=>$amount,'duration'=>$duration,'duration_months'=>$months,'customer_scope'=>$scope,'eligible_package_ids_json'=>json_encode(array_values(array_map('intval',$packages)),JSON_UNESCAPED_SLASHES),'minimum_package_amount_cents'=>$minimum,'starts_at'=>commercial_datetime_or_null($input['starts_at']??($current['starts_at']??null)),'ends_at'=>commercial_datetime_or_null($input['ends_at']??($current['ends_at']??null)),'max_redemptions'=>$max,'per_account_limit'=>$limit];
}
function commercial_promotion_create(PDO $pdo,array $admin,array $input): array {
    if(($admin['role']??'')!=='admin')throw new RuntimeException('Administrator access required.');if(!commercial_promotions_ready($pdo))throw new RuntimeException('Coupons, Promotions & Credits requires migration 071.');
    $name=trim((string)($input['name']??''));if($name==='')throw new InvalidArgumentException('Promotion name is required.');$code=commercial_normalize_code((string)($input['code']??''));$v=commercial_promotion_values($pdo,$input);
    $pdo->prepare('INSERT INTO commercial_promotions(public_id,code,name,description,status,discount_type,percent_basis_points,amount_off_cents,duration,duration_months,customer_scope,eligible_package_ids_json,minimum_package_amount_cents,starts_at,ends_at,max_redemptions,per_account_limit,created_by_user_id,updated_by_user_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')
      ->execute([ulid_like(),$code,mb_substr($name,0,190),trim((string)($input['description']??''))?:null,$v['status'],$v['discount_type'],$v['percent_basis_points'],$v['amount_off_cents'],$v['duration'],$v['duration_months'],$v['customer_scope'],$v['eligible_package_ids_json'],$v['minimum_package_amount_cents'],$v['starts_at'],$v['ends_at'],$v['max_redemptions'],$v['per_account_limit'],(int)$admin['id'],(int)$admin['id']]);
    $id=(int)$pdo->lastInsertId();$q=$pdo->prepare('SELECT * FROM commercial_promotions WHERE id=?');$q->execute([$id]);$row=$q->fetch();commercial_audit($pdo,$id,null,(int)$admin['id'],'promotion_created',null,$row,'Administrator created promotion.');return $row;
}
function commercial_promotion_update(PDO $pdo,array $admin,string $publicId,array $input): array {
    if(($admin['role']??'')!=='admin')throw new RuntimeException('Administrator access required.');$current=commercial_promotion($pdo,$publicId);if(!$current)throw new RuntimeException('Promotion not found.');$v=commercial_promotion_values($pdo,$input,$current);
    $name=trim((string)($input['name']??$current['name']));$code=commercial_normalize_code((string)($input['code']??$current['code']));
    $pdo->prepare('UPDATE commercial_promotions SET code=?,name=?,description=?,status=?,discount_type=?,percent_basis_points=?,amount_off_cents=?,duration=?,duration_months=?,customer_scope=?,eligible_package_ids_json=?,minimum_package_amount_cents=?,starts_at=?,ends_at=?,max_redemptions=?,per_account_limit=?,updated_by_user_id=? WHERE id=?')
      ->execute([$code,mb_substr($name,0,190),trim((string)($input['description']??$current['description']??''))?:null,$v['status'],$v['discount_type'],$v['percent_basis_points'],$v['amount_off_cents'],$v['duration'],$v['duration_months'],$v['customer_scope'],$v['eligible_package_ids_json'],$v['minimum_package_amount_cents'],$v['starts_at'],$v['ends_at'],$v['max_redemptions'],$v['per_account_limit'],(int)$admin['id'],(int)$current['id']]);
    $after=commercial_promotion($pdo,$publicId);commercial_audit($pdo,(int)$current['id'],null,(int)$admin['id'],'promotion_updated',$current,$after,'Administrator updated promotion policy.');return $after;
}
function commercial_promotion_is_new_customer(PDO $pdo,int $accountId,string $mode): bool {
    $q=$pdo->prepare("SELECT COUNT(*) FROM stripe_invoices WHERE account_id=? AND mode=? AND status='paid' AND amount_paid_cents>0");$q->execute([$accountId,$mode]);return (int)$q->fetchColumn()===0;
}
function commercial_promotion_validate_checkout(PDO $pdo,array $promotion,array $account,array $package,string $mode): void {
    if((string)$promotion['status']!=='active')throw new RuntimeException('This promotion is not active.');
    $now=time();if(!empty($promotion['starts_at'])&&strtotime((string)$promotion['starts_at'].' UTC')>$now)throw new RuntimeException('This promotion has not started yet.');if(!empty($promotion['ends_at'])&&strtotime((string)$promotion['ends_at'].' UTC')<$now)throw new RuntimeException('This promotion has expired.');
    $eligible=json_decode((string)($promotion['eligible_package_ids_json']??'[]'),true);if(is_array($eligible)&&$eligible&&!in_array((int)$package['id'],array_map('intval',$eligible),true))throw new RuntimeException('This promotion does not apply to that package.');
    if($promotion['minimum_package_amount_cents']!==null&&(int)$package['monthly_price_cents']<(int)$promotion['minimum_package_amount_cents'])throw new RuntimeException('This package does not meet the promotion minimum.');
    $isNew=commercial_promotion_is_new_customer($pdo,(int)$account['id'],$mode);if($promotion['customer_scope']==='new_customers'&&!$isNew)throw new RuntimeException('This promotion is limited to new customers.');if($promotion['customer_scope']==='existing_customers'&&$isNew)throw new RuntimeException('This promotion is limited to existing customers.');
    $q=$pdo->prepare("SELECT COUNT(*) FROM commercial_promotion_redemptions WHERE promotion_id=? AND stripe_mode=? AND status IN ('pending','applied')");$q->execute([(int)$promotion['id'],$mode]);$used=(int)$q->fetchColumn();if($promotion['max_redemptions']!==null&&$used>=(int)$promotion['max_redemptions'])throw new RuntimeException('This promotion has reached its redemption limit.');
    $q=$pdo->prepare("SELECT COUNT(*) FROM commercial_promotion_redemptions WHERE promotion_id=? AND account_id=? AND stripe_mode=? AND status IN ('pending','applied')");$q->execute([(int)$promotion['id'],(int)$account['id'],$mode]);if((int)$q->fetchColumn()>=(int)$promotion['per_account_limit'])throw new RuntimeException('This account has already used the maximum allowed redemptions for this promotion.');
}
function commercial_promotion_definition_hash(array $p): string {
    return hash('sha256',json_encode(['code'=>$p['code'],'name'=>$p['name'],'type'=>$p['discount_type'],'bps'=>$p['percent_basis_points'],'amount'=>$p['amount_off_cents'],'duration'=>$p['duration'],'months'=>$p['duration_months'],'scope'=>$p['customer_scope'],'end'=>$p['ends_at'],'max'=>$p['max_redemptions']],JSON_UNESCAPED_SLASHES));
}
function commercial_promotion_mapping(PDO $pdo,int $promotionId,string $mode): ?array {$q=$pdo->prepare('SELECT * FROM commercial_promotion_stripe_mappings WHERE promotion_id=? AND stripe_mode=?');$q->execute([$promotionId,$mode]);return $q->fetch()?:null;}
function commercial_promotion_sync_stripe(PDO $pdo,array $config,array $actor,array $promotion): array {
    if(!stripe_billing_configured($pdo,$config))throw new RuntimeException('Stripe billing is not configured.');$settings=stripe_billing_settings($pdo);$mode=(string)$settings['mode'];$hash=commercial_promotion_definition_hash($promotion);
    return app_with_advisory_lock($pdo,'commercial-promotion-sync',(string)$promotion['id'].'-'.$mode,function()use($pdo,$config,$actor,$promotion,$settings,$mode,$hash){
        $current=commercial_promotion_mapping($pdo,(int)$promotion['id'],$mode);if($current&&$current['status']==='synced'&&hash_equals((string)$current['definition_hash'],$hash)&&!empty($current['stripe_promotion_code_id']))return $current;
        try{
            if($current&&!empty($current['stripe_promotion_code_id']))stripe_billing_api_request($config,$settings,'POST','promotion_codes/'.rawurlencode((string)$current['stripe_promotion_code_id']),['active'=>'false']);
            $coupon=['name'=>mb_substr((string)$promotion['name'],0,40),'duration'=>(string)$promotion['duration'],'metadata'=>['annotated_promotion_id'=>(string)$promotion['public_id'],'annotated_code'=>(string)$promotion['code']]];
            if($promotion['discount_type']==='percent')$coupon['percent_off']=number_format(((int)$promotion['percent_basis_points'])/100,2,'.','');else{$coupon['amount_off']=(int)$promotion['amount_off_cents'];$coupon['currency']='usd';}
            if($promotion['duration']==='repeating')$coupon['duration_in_months']=(int)$promotion['duration_months'];if(!empty($promotion['ends_at']))$coupon['redeem_by']=strtotime((string)$promotion['ends_at'].' UTC');
            $c=stripe_billing_api_request($config,$settings,'POST','coupons',$coupon,'annotated-promo-coupon-'.$mode.'-'.$promotion['public_id'].'-'.$hash);$couponId=(string)($c['id']??'');if($couponId==='')throw new RuntimeException('Stripe did not return a coupon ID.');
            $pp=['code'=>(string)$promotion['code'],'active'=>'true','promotion'=>['type'=>'coupon','coupon'=>$couponId],'metadata'=>['annotated_promotion_id'=>(string)$promotion['public_id']]];if($promotion['max_redemptions']!==null)$pp['max_redemptions']=(int)$promotion['max_redemptions'];if(!empty($promotion['ends_at']))$pp['expires_at']=strtotime((string)$promotion['ends_at'].' UTC');if($promotion['customer_scope']==='new_customers')$pp['restrictions']=['first_time_transaction'=>'true'];
            $pc=stripe_billing_api_request($config,$settings,'POST','promotion_codes',$pp,'annotated-promo-code-'.$mode.'-'.$promotion['public_id'].'-'.$hash);$promoId=(string)($pc['id']??'');if($promoId==='')throw new RuntimeException('Stripe did not return a promotion code ID.');
            $pdo->prepare("INSERT INTO commercial_promotion_stripe_mappings(promotion_id,stripe_mode,definition_hash,stripe_coupon_id,stripe_promotion_code_id,status,last_error,synced_at) VALUES(?,?,?,?,?,'synced',NULL,NOW()) ON DUPLICATE KEY UPDATE definition_hash=VALUES(definition_hash),stripe_coupon_id=VALUES(stripe_coupon_id),stripe_promotion_code_id=VALUES(stripe_promotion_code_id),status='synced',last_error=NULL,synced_at=NOW()")
              ->execute([(int)$promotion['id'],$mode,$hash,$couponId,$promoId]);$row=commercial_promotion_mapping($pdo,(int)$promotion['id'],$mode);commercial_audit($pdo,(int)$promotion['id'],null,(int)($actor['id']??0)?:null,'stripe_promotion_synced',$current,$row,'Promotion mirrored to Stripe '.$mode.'.');return $row;
        }catch(Throwable $e){
            $pdo->prepare("INSERT INTO commercial_promotion_stripe_mappings(promotion_id,stripe_mode,definition_hash,status,last_error) VALUES(?,?,?,'failed',?) ON DUPLICATE KEY UPDATE definition_hash=VALUES(definition_hash),status='failed',last_error=VALUES(last_error)")
              ->execute([(int)$promotion['id'],$mode,$hash,mb_substr($e->getMessage(),0,1000)]);throw $e;
        }
    },10);
}
function commercial_promotion_reserve_attempt(PDO $pdo,array $promotion,array $account,array $package,array $user,string $mode,string $attemptPublic,array $mapping): array {
    return app_with_advisory_lock($pdo,'commercial-promotion-redemption',(string)$promotion['id'].'-'.$mode,function()use($pdo,$promotion,$account,$package,$user,$mode,$attemptPublic,$mapping){
        $q=$pdo->prepare('SELECT * FROM commercial_promotion_redemptions WHERE stripe_mode=? AND checkout_attempt_public_id=?');$q->execute([$mode,$attemptPublic]);if($row=$q->fetch())return $row;
        commercial_promotion_validate_checkout($pdo,$promotion,$account,$package,$mode);$snapshot=['promotion_public_id'=>$promotion['public_id'],'code'=>$promotion['code'],'name'=>$promotion['name'],'discount_type'=>$promotion['discount_type'],'percent_basis_points'=>$promotion['percent_basis_points'],'amount_off_cents'=>$promotion['amount_off_cents'],'duration'=>$promotion['duration'],'duration_months'=>$promotion['duration_months'],'stripe_coupon_id'=>$mapping['stripe_coupon_id']??null,'stripe_promotion_code_id'=>$mapping['stripe_promotion_code_id']??null];
        $pdo->prepare("INSERT INTO commercial_promotion_redemptions(public_id,promotion_id,account_id,package_id,user_id,stripe_mode,checkout_attempt_public_id,status,discount_snapshot_json) VALUES(?,?,?,?,?,?,?,'pending',?)")
          ->execute([ulid_like(),(int)$promotion['id'],(int)$account['id'],(int)$package['id'],(int)$user['id'],$mode,$attemptPublic,json_encode($snapshot,JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)]);
        $id=(int)$pdo->lastInsertId();$q=$pdo->prepare('SELECT * FROM commercial_promotion_redemptions WHERE id=?');$q->execute([$id]);return $q->fetch();
    },10);
}
function commercial_promotion_bind_session(PDO $pdo,string $mode,string $attemptPublic,string $sessionId): void {
    if(!commercial_promotions_ready($pdo)||$sessionId==='')return;$pdo->prepare("UPDATE commercial_promotion_redemptions SET stripe_checkout_session_id=? WHERE stripe_mode=? AND checkout_attempt_public_id=? AND status='pending'")->execute([$sessionId,$mode,$attemptPublic]);
}
function commercial_promotion_void_checkout(PDO $pdo,string $mode,?string $attemptPublic=null,?string $sessionId=null): void {
    if(!commercial_promotions_ready($pdo))return;if($sessionId){$pdo->prepare("UPDATE commercial_promotion_redemptions SET status='void',voided_at=COALESCE(voided_at,NOW()) WHERE stripe_mode=? AND stripe_checkout_session_id=? AND status='pending'")->execute([$mode,$sessionId]);}elseif($attemptPublic){$pdo->prepare("UPDATE commercial_promotion_redemptions SET status='void',voided_at=COALESCE(voided_at,NOW()) WHERE stripe_mode=? AND checkout_attempt_public_id=? AND status='pending'")->execute([$mode,$attemptPublic]);}
}
function commercial_promotion_apply_checkout(PDO $pdo,array $session,string $mode): void {
    if(!commercial_promotions_ready($pdo))return;$sid=(string)($session['id']??'');if($sid==='')return;$q=$pdo->prepare('SELECT * FROM commercial_promotion_redemptions WHERE stripe_mode=? AND stripe_checkout_session_id=? LIMIT 1');$q->execute([$mode,$sid]);$r=$q->fetch();
    if(!$r){$promoPublic=(string)($session['metadata']['annotated_promotion_id']??'');$accountPublic=(string)($session['metadata']['annotated_account_id']??$session['client_reference_id']??'');$packagePublic=(string)($session['metadata']['annotated_package_id']??'');if($promoPublic===''||$accountPublic===''||$packagePublic==='')return;$p=commercial_promotion($pdo,$promoPublic);$a=stripe_billing_account_by_public($pdo,$accountPublic);$pkg=subscription_package($pdo,$packagePublic);if(!$p||!$a||!$pkg)return;$attempt=(string)($session['metadata']['annotated_checkout_attempt']??('recovered-'.substr(hash('sha256',$mode.'|'.$sid),0,24)));$snapshot=['promotion_public_id'=>$p['public_id'],'code'=>$p['code'],'name'=>$p['name'],'recovered_from_webhook'=>true];try{$pdo->prepare("INSERT INTO commercial_promotion_redemptions(public_id,promotion_id,account_id,package_id,user_id,stripe_mode,checkout_attempt_public_id,stripe_checkout_session_id,status,discount_snapshot_json,applied_at) VALUES(?,?,?,?,NULL,?,?,?,'applied',?,NOW())")->execute([ulid_like(),(int)$p['id'],(int)$a['id'],(int)$pkg['id'],$mode,$attempt,$sid,json_encode($snapshot,JSON_UNESCAPED_SLASHES)]);}catch(Throwable $e){}$q=$pdo->prepare('SELECT * FROM commercial_promotion_redemptions WHERE stripe_mode=? AND stripe_checkout_session_id=? LIMIT 1');$q->execute([$mode,$sid]);$r=$q->fetch();}
    if(!$r)return;$sub=is_string($session['subscription']??null)?(string)$session['subscription']:null;$pdo->prepare("UPDATE commercial_promotion_redemptions SET status='applied',stripe_subscription_id=COALESCE(?,stripe_subscription_id),applied_at=COALESCE(applied_at,NOW()) WHERE id=? AND status<>'void'")->execute([$sub,(int)$r['id']]);
}
function commercial_invoice_subscription_id(array $invoice): ?string {
    if(is_string($invoice['subscription']??null)&&$invoice['subscription']!=='')return (string)$invoice['subscription'];$v=$invoice['parent']['subscription_details']['subscription']??null;return is_string($v)&&$v!==''?$v:null;
}
function commercial_promotion_handle_invoice(PDO $pdo,array $invoice,string $mode): void {
    if(!commercial_promotions_ready($pdo))return;$invoiceId=(string)($invoice['id']??'');if($invoiceId==='')return;$q=$pdo->prepare('SELECT * FROM stripe_invoices WHERE mode=? AND stripe_invoice_id=? LIMIT 1');$q->execute([$mode,$invoiceId]);$stored=$q->fetch();if(!$stored)return;$accountId=(int)$stored['account_id'];$subId=commercial_invoice_subscription_id($invoice);$discount=0;foreach((array)($invoice['total_discount_amounts']??[]) as $d)$discount+=max(0,(int)($d['amount']??0));$gross=max(0,(int)($invoice['subtotal']??((int)($invoice['total']??$stored['amount_due_cents'])+$discount)));$net=max(0,(int)($invoice['total']??$stored['amount_due_cents']));
    $r=null;if($subId){$rq=$pdo->prepare("SELECT * FROM commercial_promotion_redemptions WHERE account_id=? AND stripe_mode=? AND stripe_subscription_id=? AND status='applied' ORDER BY id DESC LIMIT 1");$rq->execute([$accountId,$mode,$subId]);$r=$rq->fetch()?:null;}if(!$r&&$discount>0){$rq=$pdo->prepare("SELECT * FROM commercial_promotion_redemptions WHERE account_id=? AND stripe_mode=? AND status='applied' ORDER BY applied_at DESC,id DESC LIMIT 1");$rq->execute([$accountId,$mode]);$r=$rq->fetch()?:null;}
    if($discount<=0&&!$r)return;$created=stripe_billing_datetime($invoice['created']??null);$pdo->prepare("INSERT INTO commercial_discount_events(public_id,promotion_id,redemption_id,account_id,stripe_mode,stripe_invoice_id,stripe_subscription_id,gross_subtotal_cents,discount_amount_cents,net_total_cents,event_created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE promotion_id=VALUES(promotion_id),redemption_id=VALUES(redemption_id),stripe_subscription_id=VALUES(stripe_subscription_id),gross_subtotal_cents=VALUES(gross_subtotal_cents),discount_amount_cents=VALUES(discount_amount_cents),net_total_cents=VALUES(net_total_cents),event_created_at=COALESCE(VALUES(event_created_at),event_created_at)")
      ->execute([ulid_like(),$r?(int)$r['promotion_id']:null,$r?(int)$r['id']:null,$accountId,$mode,$invoiceId,$subId,$gross,$discount,$net,$created]);
    if($r){$sum=$pdo->prepare('SELECT COALESCE(SUM(discount_amount_cents),0) FROM commercial_discount_events WHERE redemption_id=?');$sum->execute([(int)$r['id']]);$pdo->prepare('UPDATE commercial_promotion_redemptions SET amount_discounted_cents=?,stripe_invoice_id=? WHERE id=?')->execute([(int)$sum->fetchColumn(),$invoiceId,(int)$r['id']]);}
}
function commercial_credit_row(PDO $pdo,string $publicId): ?array {$q=$pdo->prepare('SELECT * FROM commercial_credit_adjustments WHERE public_id=? LIMIT 1');$q->execute([$publicId]);return $q->fetch()?:null;}
function commercial_credit_retry(PDO $pdo,array $config,array $row): array {
    if($row['status']==='applied')return $row;$settings=stripe_billing_settings($pdo);if((string)$settings['mode']!==(string)$row['stripe_mode'])throw new RuntimeException('Credit adjustment mode does not match current Stripe mode.');
    try{$remote=stripe_billing_api_request($config,$settings,'POST','customers/'.rawurlencode((string)$row['stripe_customer_id']).'/balance_transactions',['amount'=>(int)$row['amount_cents'],'currency'=>(string)$row['currency'],'description'=>(string)$row['reason'],'metadata'=>['annotated_credit_adjustment_id'=>(string)$row['public_id'],'annotated_account_id'=>(string)$row['account_id']],(string)$row['idempotency_key']);$remoteId=(string)($remote['id']??'');if($remoteId==='')throw new RuntimeException('Stripe did not return a customer balance transaction ID.');$pdo->prepare("UPDATE commercial_credit_adjustments SET stripe_balance_transaction_id=?,status='applied',last_error=NULL,applied_at=COALESCE(applied_at,NOW()) WHERE id=?")->execute([$remoteId,(int)$row['id']]);return commercial_credit_row($pdo,(string)$row['public_id'])??$row;}catch(Throwable $e){$pdo->prepare("UPDATE commercial_credit_adjustments SET status='failed',last_error=? WHERE id=?")->execute([mb_substr($e->getMessage(),0,1000),(int)$row['id']]);throw $e;}
}
function commercial_credit_adjust(PDO $pdo,array $config,array $admin,string $accountPublicId,string $direction,int $amountCents,string $reason,?int $relatedId=null): array {
    if(($admin['role']??'')!=='admin')throw new RuntimeException('Administrator access required.');if(!commercial_promotions_ready($pdo))throw new RuntimeException('Coupons, Promotions & Credits requires migration 071.');if(!in_array($direction,['credit','debit','reversal'],true))throw new InvalidArgumentException('Invalid credit adjustment type.');if($amountCents<1||$amountCents>10000000)throw new InvalidArgumentException('Credit adjustment must be between $0.01 and $100,000.00.');$reason=trim($reason);if($reason==='')throw new InvalidArgumentException('A reason is required.');
    $account=stripe_billing_account_by_public($pdo,$accountPublicId);if(!$account)throw new RuntimeException('Account not found.');$settings=stripe_billing_settings($pdo);$mode=(string)$settings['mode'];$customer=stripe_billing_customer_ensure($pdo,$config,$account);$signed=$direction==='credit'?-$amountCents:($direction==='debit'?$amountCents:$amountCents);$public=ulid_like();$idem='annotated-credit-'.hash('sha256',$mode.'|'.$public.'|'.$signed);
    $pdo->prepare("INSERT INTO commercial_credit_adjustments(public_id,account_id,stripe_mode,actor_user_id,adjustment_type,amount_cents,currency,reason,idempotency_key,stripe_customer_id,related_adjustment_id,status) VALUES(?,?,?,?,?,?,'usd',?,?,?,?, 'creating')")
      ->execute([$public,(int)$account['id'],$mode,(int)$admin['id'],$direction,$signed,mb_substr($reason,0,500),$idem,(string)$customer['stripe_customer_id'],$relatedId]);$row=commercial_credit_row($pdo,$public);$after=commercial_credit_retry($pdo,$config,$row);commercial_audit($pdo,null,(int)$account['id'],(int)$admin['id'],'credit_adjustment_created',null,$after,'Administrator created Stripe customer credit balance adjustment.');return $after;
}
function commercial_credit_reverse(PDO $pdo,array $config,array $admin,string $publicId,string $reason): array {
    $original=commercial_credit_row($pdo,$publicId);if(!$original||$original['status']!=='applied')throw new RuntimeException('Only applied credit adjustments can be reversed.');$q=$pdo->prepare("SELECT COUNT(*) FROM commercial_credit_adjustments WHERE related_adjustment_id=? AND status IN ('creating','applied')");$q->execute([(int)$original['id']]);if((int)$q->fetchColumn()>0)throw new RuntimeException('This adjustment already has a reversal.');$accountQ=$pdo->prepare('SELECT public_id FROM accounts WHERE id=?');$accountQ->execute([(int)$original['account_id']]);$accountPublic=(string)$accountQ->fetchColumn();$amount=abs((int)$original['amount_cents']);$direction=(int)$original['amount_cents']<0?'debit':'credit';$r=commercial_credit_adjust($pdo,$config,$admin,$accountPublic,$direction,$amount,$reason,(int)$original['id']);$pdo->prepare("UPDATE commercial_credit_adjustments SET adjustment_type='reversal' WHERE id=?")->execute([(int)$r['id']]);return commercial_credit_row($pdo,(string)$r['public_id'])??$r;
}
function commercial_credit_retry_public(PDO $pdo,array $config,array $admin,string $publicId): array {if(($admin['role']??'')!=='admin')throw new RuntimeException('Administrator access required.');$r=commercial_credit_row($pdo,$publicId);if(!$r)throw new RuntimeException('Credit adjustment not found.');return commercial_credit_retry($pdo,$config,$r);}
function commercial_account_benefits_summary(PDO $pdo,int $accountId): array {
    if(!commercial_promotions_ready($pdo))return ['credit_net_cents'=>0,'discount_total_cents'=>0,'recent_redemptions'=>[]];$mode=(string)(stripe_billing_settings($pdo)['mode']??'test');$q=$pdo->prepare("SELECT COALESCE(SUM(amount_cents),0) FROM commercial_credit_adjustments WHERE account_id=? AND stripe_mode=? AND status='applied'");$q->execute([$accountId,$mode]);$credit=(int)$q->fetchColumn();$q=$pdo->prepare('SELECT COALESCE(SUM(discount_amount_cents),0) FROM commercial_discount_events WHERE account_id=? AND stripe_mode=?');$q->execute([$accountId,$mode]);$discount=(int)$q->fetchColumn();$q=$pdo->prepare("SELECT r.*,p.code,p.name promotion_name FROM commercial_promotion_redemptions r JOIN commercial_promotions p ON p.id=r.promotion_id WHERE r.account_id=? AND r.stripe_mode=? AND r.status='applied' ORDER BY r.applied_at DESC,r.id DESC LIMIT 5");$q->execute([$accountId,$mode]);return ['credit_net_cents'=>$credit,'discount_total_cents'=>$discount,'recent_redemptions'=>$q->fetchAll()?:[]];
}
function commercial_revenue_adjustment_summary(PDO $pdo,int $days=30): array {
    if(!commercial_promotions_ready($pdo))return ['gross_cents'=>0,'discount_cents'=>0,'net_cents'=>0,'credit_issued_cents'=>0,'debit_issued_cents'=>0];$days=max(1,min(3650,$days));$mode=(string)(stripe_billing_settings($pdo)['mode']??'test');$q=$pdo->prepare("SELECT COALESCE(SUM(gross_subtotal_cents),0) gross,COALESCE(SUM(discount_amount_cents),0) discount,COALESCE(SUM(net_total_cents),0) net FROM commercial_discount_events WHERE stripe_mode=? AND created_at>=DATE_SUB(NOW(),INTERVAL ".$days." DAY)");$q->execute([$mode]);$d=$q->fetch()?:[];$q=$pdo->prepare("SELECT COALESCE(SUM(CASE WHEN amount_cents<0 THEN -amount_cents ELSE 0 END),0) credits,COALESCE(SUM(CASE WHEN amount_cents>0 THEN amount_cents ELSE 0 END),0) debits FROM commercial_credit_adjustments WHERE stripe_mode=? AND status='applied' AND created_at>=DATE_SUB(NOW(),INTERVAL ".$days." DAY)");$q->execute([$mode]);$c=$q->fetch()?:[];return ['gross_cents'=>(int)($d['gross']??0),'discount_cents'=>(int)($d['discount']??0),'net_cents'=>(int)($d['net']??0),'credit_issued_cents'=>(int)($c['credits']??0),'debit_issued_cents'=>(int)($c['debits']??0)];
}
function commercial_promotions_list(PDO $pdo): array {return commercial_promotions_ready($pdo)?($pdo->query("SELECT p.*,(SELECT COUNT(*) FROM commercial_promotion_redemptions r WHERE r.promotion_id=p.id AND r.status='applied') applied_redemptions FROM commercial_promotions p ORDER BY FIELD(p.status,'active','draft','archived'),p.updated_at DESC,p.id DESC")->fetchAll()?:[]):[];}
function commercial_recent_redemptions(PDO $pdo,int $limit=100): array {return commercial_promotions_ready($pdo)?($pdo->query("SELECT r.*,p.code,p.name promotion_name,a.public_id account_public_id,a.name account_name,sp.name package_name FROM commercial_promotion_redemptions r JOIN commercial_promotions p ON p.id=r.promotion_id JOIN accounts a ON a.id=r.account_id JOIN subscription_packages sp ON sp.id=r.package_id ORDER BY r.id DESC LIMIT ".max(1,min(500,$limit)))->fetchAll()?:[]):[];}
function commercial_recent_discount_events(PDO $pdo,int $limit=100): array {return commercial_promotions_ready($pdo)?($pdo->query("SELECT d.*,p.code,a.name account_name FROM commercial_discount_events d LEFT JOIN commercial_promotions p ON p.id=d.promotion_id JOIN accounts a ON a.id=d.account_id ORDER BY d.id DESC LIMIT ".max(1,min(500,$limit)))->fetchAll()?:[]):[];}
function commercial_recent_credits(PDO $pdo,int $limit=100): array {return commercial_promotions_ready($pdo)?($pdo->query("SELECT c.*,a.public_id account_public_id,a.name account_name,u.username actor_username FROM commercial_credit_adjustments c JOIN accounts a ON a.id=c.account_id LEFT JOIN users u ON u.id=c.actor_user_id ORDER BY c.id DESC LIMIT ".max(1,min(500,$limit)))->fetchAll()?:[]):[];}
function commercial_promotions_agent_context(PDO $pdo,array $viewer): string {
    if(($viewer['role']??'')!=='admin'||!commercial_promotions_ready($pdo))return '';$mode=(string)(stripe_billing_settings($pdo)['mode']??'test');$q=$pdo->prepare("SELECT COUNT(*) FROM commercial_promotions WHERE status='active' AND (starts_at IS NULL OR starts_at<=NOW()) AND (ends_at IS NULL OR ends_at>=NOW())");$q->execute();$active=(int)$q->fetchColumn();$summary=commercial_revenue_adjustment_summary($pdo,30);$q=$pdo->prepare("SELECT COUNT(*) FROM commercial_promotion_redemptions WHERE stripe_mode=? AND status='applied'");$q->execute([$mode]);$redemptions=(int)$q->fetchColumn();return "Admin promotions and credits context (read-only). Stripe mode: {$mode}. Active promotions: {$active}. Applied redemptions: {$redemptions}. Recorded invoice discounts in the last 30 days: $".number_format($summary['discount_cents']/100,2).". Customer credit adjustments issued in the last 30 days: $".number_format($summary['credit_issued_cents']/100,2).". Annotated commercial policy and audit records are authoritative; Stripe mirrors collection behavior.";
}
