<?php
declare(strict_types=1);

/**
 * Phase 41 — Training Job Registry & Controlled Fine-Tuning
 *
 * Training is allowed only from frozen, currently usable Phase 38 training datasets.
 * Outputs are registered as Phase 40 EXPERIMENTAL versions. Nothing here approves,
 * activates, routes, or silently promotes a resulting model.
 */

function data_training_ready(PDO $pdo): bool {
    try{return data_model_registry_ready($pdo)&&installer_table_exists($pdo,'data_training_jobs')&&installer_table_exists($pdo,'data_training_attempts')&&installer_table_exists($pdo,'data_training_events');}
    catch(Throwable $e){return false;}
}
function data_training_require_admin(array $viewer): void {
    if(($viewer['role']??'')!=='admin')throw new RuntimeException('Administrator access is required for Training Registry operations.');
}
function data_training_executors(): array {
    return [
        'provider_api'=>['label'=>'Provider API','description'=>'Upload a validated JSONL package and manage a provider fine-tuning job.'],
        'manual'=>['label'=>'Manual / self-hosted','description'=>'Freeze and export the exact package, then register the resulting artifact manually.'],
    ];
}
function data_training_statuses(): array {
    return ['draft','queued','preparing','prepared','submitted','running','cancel_requested','succeeded','failed','cancelled','blocked'];
}
function data_training_auto_int(mixed $value,int $min,int $max): string|int {
    if($value===null||$value===''||$value==='auto')return 'auto';$v=(int)$value;if($v<$min||$v>$max)throw new InvalidArgumentException("Training integer parameter must be between $min and $max, or auto.");return $v;
}
function data_training_auto_float(mixed $value,float $min,float $max): string|float {
    if($value===null||$value===''||$value==='auto')return 'auto';$v=(float)$value;if($v<$min||$v>$max)throw new InvalidArgumentException("Training numeric parameter must be between $min and $max, or auto.");return $v;
}
function data_training_config_normalize(array $input): array {
    $executor=(string)($input['executor_type']??'provider_api');if(!isset(data_training_executors()[$executor]))throw new InvalidArgumentException('Invalid training executor.');
    $use=(string)($input['use_class']??'internal_training');if(!in_array($use,['internal_training','commercial_training'],true))throw new InvalidArgumentException('Invalid training use class.');
    $method=(string)($input['method']??'supervised');if($method!=='supervised')throw new InvalidArgumentException('Phase 41 v1 supports supervised fine-tuning only.');
    $format=(string)($input['training_format']??'chat_messages');if($format!=='chat_messages')throw new InvalidArgumentException('Phase 41 v1 supports chat-message training examples only.');
    $seed=($input['seed']??'')!==''?(int)$input['seed']:null;$suffix=mb_substr(trim((string)($input['suffix']??'')),0,64)?:null;$expiry=max(3600,min(2592000,(int)($input['file_expiry_seconds']??604800)));
    $rate=($input['cost_rate_usd_per_million_tokens']??'')!==''?max(0.0,(float)$input['cost_rate_usd_per_million_tokens']):null;$maxAttempts=max(1,min(10,(int)($input['max_attempts']??3)));
    return ['executor_type'=>$executor,'use_class'=>$use,'method'=>$method,'training_format'=>$format,'n_epochs'=>data_training_auto_int($input['n_epochs']??'auto',1,100),'batch_size'=>data_training_auto_int($input['batch_size']??'auto',1,10000),'learning_rate_multiplier'=>data_training_auto_float($input['learning_rate_multiplier']??'auto',0.000001,100.0),'seed'=>$seed,'suffix'=>$suffix,'file_expiry_seconds'=>$expiry,'cost_rate_usd_per_million_tokens'=>$rate,'max_attempts'=>$maxAttempts,'external_provider_acknowledged'=>data_attribution_bool($input['external_provider_acknowledged']??0),'config_version'=>'phase41-v1'];
}
function data_training_event(PDO $pdo,int $jobId,?int $actorUserId,string $type,array $details=[]): void {
    $pdo->prepare('INSERT INTO data_training_events(job_id,actor_user_id,event_type,details_json) VALUES(?,?,?,?)')->execute([$jobId,$actorUserId,$type,$details?data_attribution_encode($details):null]);
}
function data_training_log(PDO $pdo,int $jobId,?int $attemptId,string $source,string $level,string $message,?string $providerEventId=null,?string $eventType=null,array $metadata=[]): void {
    $message=mb_substr(trim($message),0,2000);if($message==='')return;$hash=data_attribution_hash(['job_id'=>$jobId,'attempt_id'=>$attemptId,'source'=>$source,'provider_event_id'=>$providerEventId,'level'=>$level,'event_type'=>$eventType,'message'=>$message,'metadata'=>$metadata]);
    try{$pdo->prepare('INSERT INTO data_training_logs(job_id,attempt_id,source,provider_event_id,level,event_type,message,metadata_json,log_hash) VALUES(?,?,?,?,?,?,?,?,?)')->execute([$jobId,$attemptId,$source,$providerEventId,$level,$eventType,$message,$metadata?data_attribution_encode($metadata):null,$hash]);}catch(PDOException $e){if($providerEventId===null)throw $e;}
}
function data_training_dataset_by_id(PDO $pdo,int $id): ?array {
    $q=$pdo->prepare('SELECT public_id FROM data_datasets WHERE id=? LIMIT 1');$q->execute([$id]);$public=(string)($q->fetchColumn()?:'');return $public!==''?data_dataset_get($pdo,$public):null;
}
function data_training_dataset_assert(PDO $pdo,int $datasetId,string $useClass): array {
    $d=data_training_dataset_by_id($pdo,$datasetId);if(!$d)throw new RuntimeException('Training dataset not found.');if($d['status']!=='frozen')throw new RuntimeException('Training requires a frozen dataset.');
    $required=$useClass==='commercial_training'?'commercial_training':'training';if($d['purpose']!==$required)throw new RuntimeException("Training use class $useClass requires a frozen dataset with purpose $required.");
    $status=data_dataset_current_use_status($pdo,(string)$d['public_id']);if(!$status['usable'])throw new RuntimeException('Training dataset is currently blocked by rights, consent, content, provenance, or manifest integrity.');
    return $d;
}
function data_training_model_version_by_id(PDO $pdo,int $id): ?array {
    $q=$pdo->prepare('SELECT public_id FROM data_model_versions WHERE id=? LIMIT 1');$q->execute([$id]);$public=(string)($q->fetchColumn()?:'');return $public!==''?data_model_version_get($pdo,$public):null;
}
function data_training_base_assert(PDO $pdo,int $versionId,string $executor): array {
    $v=data_training_model_version_by_id($pdo,$versionId);if(!$v)throw new RuntimeException('Base model version not found.');if(!in_array($v['status'],['approved','active'],true))throw new RuntimeException('Training base model must be an approved or active Phase 40 version.');$integrity=data_model_version_integrity($v);if(!$integrity['ok'])throw new RuntimeException('Base model version failed integrity validation.');
    if($executor==='provider_api'){if(!$v['ai_model_id'])throw new RuntimeException('Provider training requires a base version bound to a runtime model.');$m=ai_model_record($pdo,(int)$v['ai_model_id']);if(!in_array($m['provider_type'],['openai','openai_compatible'],true))throw new RuntimeException('Phase 41 provider execution currently supports OpenAI and explicitly configured OpenAI-compatible providers.');if($m['provider_type']==='openai_compatible'&&trim((string)($m['api_base_url']??''))==='')throw new RuntimeException('OpenAI-compatible training requires an explicit API base URL.');}
    return $v;
}
function data_training_registry_by_id(PDO $pdo,int $id): ?array {
    $q=$pdo->prepare('SELECT public_id FROM data_model_registry WHERE id=? LIMIT 1');$q->execute([$id]);$public=(string)($q->fetchColumn()?:'');return $public!==''?data_model_registry_get($pdo,$public):null;
}
function data_training_output_label_assert(PDO $pdo,int $registryId,string $label,?int $ignoreJobId=null): void {
    $q=$pdo->prepare('SELECT COUNT(*) FROM data_model_versions WHERE registry_id=? AND version_label=?');$q->execute([$registryId,$label]);if((int)$q->fetchColumn()>0)throw new RuntimeException('The output model version label already exists in the target Model Registry.');
    $sql="SELECT COUNT(*) FROM data_training_jobs WHERE output_registry_id=? AND output_version_label=? AND status NOT IN ('failed','cancelled','blocked')";$params=[$registryId,$label];if($ignoreJobId){$sql.=' AND id<>?';$params[]=$ignoreJobId;}$q=$pdo->prepare($sql);$q->execute($params);if((int)$q->fetchColumn()>0)throw new RuntimeException('Another active training job already reserves this output version label.');
}
function data_training_job_create(PDO $pdo,array $viewer,array $input): array {
    data_training_require_admin($viewer);if(!data_training_ready($pdo))throw new RuntimeException('Training Registry requires the Phase 41 database upgrade.');$config=data_training_config_normalize($input);
    $datasetId=max(1,(int)($input['dataset_id']??0));$baseId=max(1,(int)($input['base_model_version_id']??0));$registryId=max(1,(int)($input['output_registry_id']??0));$dataset=data_training_dataset_assert($pdo,$datasetId,$config['use_class']);$base=data_training_base_assert($pdo,$baseId,$config['executor_type']);$registry=data_training_registry_by_id($pdo,$registryId);if(!$registry)throw new RuntimeException('Output Model Registry not found.');
    $label=mb_substr(trim((string)($input['output_version_label']??'')),0,120);if($label==='')throw new InvalidArgumentException('Output model version label is required.');data_training_output_label_assert($pdo,$registryId,$label);$description=mb_substr(trim((string)($input['description']??'')),0,5000)?:null;$configJson=data_attribution_encode($config);$configHash=hash('sha256',$configJson);$public=ulid_like();
    $pdo->prepare("INSERT INTO data_training_jobs(public_id,dataset_id,base_model_version_id,output_registry_id,use_class,executor_type,method,training_format,status,output_version_label,description,config_json,config_hash,cost_rate_usd_per_million_tokens,max_attempts,created_by_user_id) VALUES(?,?,?,?,?,?,?,?,'draft',?,?,?,?,?,?,?)")
        ->execute([$public,$datasetId,$baseId,$registryId,$config['use_class'],$config['executor_type'],$config['method'],$config['training_format'],$label,$description,$configJson,$configHash,$config['cost_rate_usd_per_million_tokens'],$config['max_attempts'],$viewer['id']]);$id=(int)$pdo->lastInsertId();data_training_event($pdo,$id,(int)$viewer['id'],'job_created',['dataset_manifest_hash'=>$dataset['manifest_hash'],'base_model_version_hash'=>$base['version_hash'],'config_hash'=>$configHash]);return data_training_job_get($pdo,$public)??[];
}
function data_training_job_get(PDO $pdo,string $publicId): ?array {
    if(!data_training_ready($pdo))return null;$q=$pdo->prepare('SELECT j.*,d.public_id dataset_public_id,d.name dataset_name,d.version_number dataset_version,d.purpose dataset_purpose,b.public_id base_version_public_id,b.version_label base_version_label,b.status base_version_status,r.public_id output_registry_public_id,r.name output_registry_name,p.public_id provider_public_id,p.label provider_label,p.provider_type,ov.public_id output_model_version_public_id,ov.version_label output_model_version_label FROM data_training_jobs j JOIN data_datasets d ON d.id=j.dataset_id JOIN data_model_versions b ON b.id=j.base_model_version_id JOIN data_model_registry r ON r.id=j.output_registry_id LEFT JOIN ai_providers p ON p.id=j.provider_id LEFT JOIN data_model_versions ov ON ov.id=j.output_model_version_id WHERE j.public_id=? LIMIT 1');$q->execute([trim($publicId)]);$j=$q->fetch();if(!$j)return null;$j['config']=json_decode((string)$j['config_json'],true)?:[];$j['rights_snapshot']=$j['rights_snapshot_json']?json_decode((string)$j['rights_snapshot_json'],true):null;$j['provider_snapshot']=$j['provider_snapshot_json']?json_decode((string)$j['provider_snapshot_json'],true):null;$j['result_files']=$j['result_files_json']?json_decode((string)$j['result_files_json'],true):[];return $j;
}
function data_training_job_list(PDO $pdo,int $limit=100): array {
    if(!data_training_ready($pdo))return [];$limit=max(1,min(250,$limit));$q=$pdo->query("SELECT j.*,d.name dataset_name,d.version_number dataset_version,b.version_label base_version_label,r.name output_registry_name,p.label provider_label,ov.public_id output_model_version_public_id FROM data_training_jobs j JOIN data_datasets d ON d.id=j.dataset_id JOIN data_model_versions b ON b.id=j.base_model_version_id JOIN data_model_registry r ON r.id=j.output_registry_id LEFT JOIN ai_providers p ON p.id=j.provider_id LEFT JOIN data_model_versions ov ON ov.id=j.output_model_version_id ORDER BY j.id DESC LIMIT $limit");return $q->fetchAll();
}
function data_training_job_update_draft(PDO $pdo,array $viewer,string $publicId,array $input): array {
    data_training_require_admin($viewer);$j=data_training_job_get($pdo,$publicId);if(!$j)throw new RuntimeException('Training job not found.');if($j['status']!=='draft')throw new RuntimeException('Queued and later training jobs are immutable except for operational lifecycle actions.');$config=data_training_config_normalize(array_merge((array)$j['config'],$input));$datasetId=max(1,(int)($input['dataset_id']??$j['dataset_id']));$baseId=max(1,(int)($input['base_model_version_id']??$j['base_model_version_id']));$registryId=max(1,(int)($input['output_registry_id']??$j['output_registry_id']));data_training_dataset_assert($pdo,$datasetId,$config['use_class']);data_training_base_assert($pdo,$baseId,$config['executor_type']);if(!data_training_registry_by_id($pdo,$registryId))throw new RuntimeException('Output Model Registry not found.');$label=mb_substr(trim((string)($input['output_version_label']??$j['output_version_label'])),0,120);if($label==='')throw new InvalidArgumentException('Output model version label is required.');data_training_output_label_assert($pdo,$registryId,$label,(int)$j['id']);$description=mb_substr(trim((string)($input['description']??$j['description']??'')),0,5000)?:null;$configJson=data_attribution_encode($config);$configHash=hash('sha256',$configJson);
    $pdo->prepare('UPDATE data_training_jobs SET dataset_id=?,base_model_version_id=?,output_registry_id=?,use_class=?,executor_type=?,method=?,training_format=?,output_version_label=?,description=?,config_json=?,config_hash=?,cost_rate_usd_per_million_tokens=?,max_attempts=?,updated_at=NOW() WHERE id=?')->execute([$datasetId,$baseId,$registryId,$config['use_class'],$config['executor_type'],$config['method'],$config['training_format'],$label,$description,$configJson,$configHash,$config['cost_rate_usd_per_million_tokens'],$config['max_attempts'],$j['id']]);data_training_event($pdo,(int)$j['id'],(int)$viewer['id'],'draft_updated',['config_hash'=>$configHash]);return data_training_job_get($pdo,$publicId)??[];
}
function data_training_messages_normalize(array $messages): ?array {
    $out=[];$hasUser=false;$hasAssistant=false;foreach($messages as $m){if(!is_array($m))return null;$role=(string)($m['role']??'');$content=$m['content']??null;if(!in_array($role,['system','developer','user','assistant'],true)||!is_string($content)||trim($content)==='')return null;$content=trim($content);if($role==='user')$hasUser=true;if($role==='assistant')$hasAssistant=true;$out[]=['role'=>$role,'content'=>$content];}if(!$hasUser||!$hasAssistant||($out[count($out)-1]['role']??'')!=='assistant')return null;return $out;
}
function data_training_example_from_metadata(array $metadata): ?array {
    $root=$metadata['training_example']??$metadata;if(!is_array($root))return null;if(isset($root['messages'])&&is_array($root['messages'])){$messages=data_training_messages_normalize($root['messages']);return $messages?['messages'=>$messages]:null;}
    $input=trim((string)($root['input']??$root['training_input']??''));$output=trim((string)($root['output']??$root['training_output']??''));if($input===''||$output==='')return null;$messages=[];$system=trim((string)($root['system']??$root['training_system']??''));if($system!=='')$messages[]=['role'=>'system','content'=>$system];$messages[]=['role'=>'user','content'=>$input];$messages[]=['role'=>'assistant','content'=>$output];return ['messages'=>$messages];
}
function data_training_package_inspect(PDO $pdo,array $job,bool $build=false): array {
    $q=$pdo->prepare('SELECT * FROM data_dataset_items WHERE dataset_id=? ORDER BY position,id');$q->execute([$job['dataset_id']]);$rows=$q->fetchAll();$valid=0;$invalid=0;$attributionBlocked=0;$errors=[];$lines=[];$contributors=[];
    foreach($rows as $row){$metadata=json_decode((string)($row['metadata_snapshot_json']??''),true);if(!is_array($metadata))$metadata=[];$elig=json_decode((string)($row['eligibility_snapshot_json']??''),true);if(!is_array($elig))$elig=[];if((int)($elig['attribution_required']??0)===1)$attributionBlocked++;$example=data_training_example_from_metadata($metadata);if(!$example){$invalid++;if(count($errors)<20)$errors[]=['position'=>(int)$row['position'],'corpus_public_id'=>$row['corpus_public_id'],'reason'=>'missing_or_invalid_training_example'];continue;}$valid++;if($row['contributor_user_id']!==null)$contributors[(int)$row['contributor_user_id']]=true;if($build)$lines[]=data_attribution_encode($example);}
    $package=$build&&$invalid===0&&$attributionBlocked===0?(implode("\n",$lines)."\n"):null;$bytes=$package!==null?strlen($package):0;if($bytes>100*1024*1024)throw new RuntimeException('Training package exceeds the Phase 41 100 MB safety limit.');
    return ['total_items'=>count($rows),'valid_examples'=>$valid,'invalid_examples'=>$invalid,'attribution_blocked_items'=>$attributionBlocked,'contributor_count'=>count($contributors),'errors'=>$errors,'package'=>$package,'package_bytes'=>$bytes,'package_hash'=>$package!==null?hash('sha256',$package):null];
}
function data_training_preflight(PDO $pdo,array $job): array {
    $dataset=data_training_dataset_assert($pdo,(int)$job['dataset_id'],(string)$job['use_class']);$base=data_training_base_assert($pdo,(int)$job['base_model_version_id'],(string)$job['executor_type']);$inspect=data_training_package_inspect($pdo,$job,false);$checks=['dataset_current'=>true,'dataset_purpose'=>true,'base_integrity'=>data_model_version_integrity($base)['ok'],'examples_valid'=>$inspect['invalid_examples']===0&&$inspect['valid_examples']>0,'attribution_compatible'=>$inspect['attribution_blocked_items']===0,'provider_ack'=>(string)$job['executor_type']!=='provider_api'||(int)($job['config']['external_provider_acknowledged']??0)===1,'output_label_available'=>true];try{data_training_output_label_assert($pdo,(int)$job['output_registry_id'],(string)$job['output_version_label'],(int)$job['id']);}catch(Throwable $e){$checks['output_label_available']=false;}
    $pass=!in_array(false,$checks,true);return ['pass'=>$pass,'checks'=>$checks,'dataset'=>$dataset,'base'=>$base,'package'=>$inspect];
}
function data_training_rights_snapshot(PDO $pdo,array $job,array $dataset,array $inspect): array {
    $status=data_dataset_current_use_status($pdo,(string)$dataset['public_id']);return ['dataset_public_id'=>$dataset['public_id'],'dataset_manifest_hash'=>$dataset['manifest_hash'],'purpose'=>$dataset['purpose'],'use_class'=>$job['use_class'],'current_use_status'=>$status,'item_count'=>(int)$dataset['item_count'],'valid_examples'=>$inspect['valid_examples'],'attribution_blocked_items'=>$inspect['attribution_blocked_items'],'contributor_count'=>$inspect['contributor_count'],'captured_at'=>gmdate('c')];
}
function data_training_provider_snapshot(PDO $pdo,array $base): array {
    if(!$base['ai_model_id'])return [];$m=ai_model_record($pdo,(int)$base['ai_model_id']);return ['provider_id'=>(int)$m['provider_id'],'provider_public_id'=>$m['public_id']??null,'provider_label'=>$m['provider_label'],'provider_type'=>$m['provider_type'],'api_base_url'=>(string)($m['api_base_url']??''),'runtime_model_id'=>(int)$m['id'],'runtime_model_public_id'=>$m['public_id'],'model_name'=>$m['model_name'],'base_version_public_id'=>$base['public_id'],'base_version_hash'=>$base['version_hash']];
}
function data_training_job_hash(array $job): string {
    return data_attribution_hash(['public_id'=>$job['public_id'],'dataset_id'=>(int)$job['dataset_id'],'base_model_version_id'=>(int)$job['base_model_version_id'],'output_registry_id'=>(int)$job['output_registry_id'],'use_class'=>$job['use_class'],'executor_type'=>$job['executor_type'],'method'=>$job['method'],'training_format'=>$job['training_format'],'output_version_label'=>$job['output_version_label'],'config_hash'=>$job['config_hash'],'dataset_manifest_hash'=>$job['dataset_manifest_hash'],'base_model_version_hash'=>$job['base_model_version_hash'],'rights_snapshot_hash'=>$job['rights_snapshot_hash'],'provider_snapshot_hash'=>$job['provider_snapshot_hash'],'package_hash'=>$job['package_hash']]);
}
function data_training_job_integrity(PDO $pdo,array $job): array {
    $config=json_decode((string)$job['config_json'],true);if(!is_array($config))$config=[];$configHash=hash('sha256',data_attribution_encode($config));$rights=json_decode((string)($job['rights_snapshot_json']??''),true);if(!is_array($rights))$rights=[];$rightsHash=$rights?hash('sha256',data_attribution_encode($rights)):null;$provider=json_decode((string)($job['provider_snapshot_json']??''),true);if(!is_array($provider))$provider=[];$providerHash=$provider?hash('sha256',data_attribution_encode($provider)):null;$copy=$job;$copy['config_hash']=$configHash;$copy['rights_snapshot_hash']=$rightsHash;$copy['provider_snapshot_hash']=$providerHash;$computed=($job['job_hash']??'')!==''?data_training_job_hash($copy):null;$ok=hash_equals((string)$job['config_hash'],$configHash)&&hash_equals((string)($job['rights_snapshot_hash']??''),(string)($rightsHash??''))&&hash_equals((string)($job['provider_snapshot_hash']??''),(string)($providerHash??''))&&($computed===null||hash_equals((string)$job['job_hash'],$computed));return ['ok'=>$ok,'config_hash_ok'=>hash_equals((string)$job['config_hash'],$configHash),'rights_hash_ok'=>hash_equals((string)($job['rights_snapshot_hash']??''),(string)($rightsHash??'')),'provider_hash_ok'=>hash_equals((string)($job['provider_snapshot_hash']??''),(string)($providerHash??'')),'job_hash_ok'=>$computed===null?true:hash_equals((string)$job['job_hash'],$computed),'computed_job_hash'=>$computed];
}
function data_training_queue(PDO $pdo,array $viewer,string $publicId): array {
    data_training_require_admin($viewer);$job=data_training_job_get($pdo,$publicId);if(!$job)throw new RuntimeException('Training job not found.');if($job['status']!=='draft')throw new RuntimeException('Only draft training jobs can be queued.');$pre=data_training_preflight($pdo,$job);if(!$pre['pass'])throw new RuntimeException('Training preflight is blocked: '.implode(', ',array_keys(array_filter($pre['checks'],fn($v)=>!$v))));
    $built=data_training_package_inspect($pdo,$job,true);if($built['package']===null)throw new RuntimeException('Training package could not be built.');$rights=data_training_rights_snapshot($pdo,$job,$pre['dataset'],$built);$rightsJson=data_attribution_encode($rights);$rightsHash=hash('sha256',$rightsJson);$provider=$job['executor_type']==='provider_api'?data_training_provider_snapshot($pdo,$pre['base']):[];$providerJson=$provider?data_attribution_encode($provider):null;$providerHash=$providerJson?hash('sha256',$providerJson):null;
    $pdo->beginTransaction();try{$q=$pdo->prepare('SELECT status FROM data_training_jobs WHERE id=? FOR UPDATE');$q->execute([$job['id']]);if((string)$q->fetchColumn()!=='draft')throw new RuntimeException('Training job changed before queueing.');$providerId=$provider['provider_id']??null;$pdo->prepare("UPDATE data_training_jobs SET status='queued',dataset_manifest_hash=?,base_model_version_hash=?,rights_snapshot_json=?,rights_snapshot_hash=?,provider_id=?,provider_snapshot_json=?,provider_snapshot_hash=?,package_hash=?,package_bytes=?,example_count=?,invalid_example_count=?,cost_rate_usd_per_million_tokens=?,max_attempts=?,queued_at=NOW(),updated_at=NOW() WHERE id=?")->execute([$pre['dataset']['manifest_hash'],$pre['base']['version_hash'],$rightsJson,$rightsHash,$providerId,$providerJson,$providerHash,$built['package_hash'],$built['package_bytes'],$built['valid_examples'],$built['invalid_examples'],$job['config']['cost_rate_usd_per_million_tokens'],$job['config']['max_attempts'],$job['id']]);$fresh=data_training_job_get($pdo,$publicId);$hash=data_training_job_hash($fresh);$pdo->prepare('UPDATE data_training_jobs SET job_hash=? WHERE id=?')->execute([$hash,$job['id']]);data_training_event($pdo,(int)$job['id'],(int)$viewer['id'],'job_queued',['job_hash'=>$hash,'package_hash'=>$built['package_hash'],'example_count'=>$built['valid_examples']]);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}return data_training_job_get($pdo,$publicId)??[];
}
function data_training_current_use_status(PDO $pdo,array $job): array {
    $integrity=data_training_job_integrity($pdo,$job);$dataset=data_training_dataset_by_id($pdo,(int)$job['dataset_id']);$datasetStatus=$dataset?data_dataset_current_use_status($pdo,(string)$dataset['public_id']):['usable'=>false,'reason'=>'dataset_missing'];$base=data_training_model_version_by_id($pdo,(int)$job['base_model_version_id']);$baseIntegrity=$base?data_model_version_integrity($base):['ok'=>false];$snapshotMatch=$dataset&&hash_equals((string)$job['dataset_manifest_hash'],(string)$dataset['manifest_hash'])&&$base&&hash_equals((string)$job['base_model_version_hash'],(string)$base['version_hash']);return ['usable'=>$integrity['ok']&&($datasetStatus['usable']??false)&&($baseIntegrity['ok']??false)&&$snapshotMatch,'job_integrity'=>$integrity,'dataset_status'=>$datasetStatus,'base_integrity'=>$baseIntegrity,'snapshot_match'=>$snapshotMatch];
}
function data_training_attempt_start(PDO $pdo,array $job): array {
    $next=(int)$job['attempt_count']+1;if($next>(int)$job['max_attempts'])throw new RuntimeException('Training job has exhausted its configured attempts.');$pdo->prepare('UPDATE data_training_jobs SET attempt_count=?,updated_at=NOW() WHERE id=?')->execute([$next,$job['id']]);$pdo->prepare("INSERT INTO data_training_attempts(job_id,attempt_number,status) VALUES(?,?,'preparing')")->execute([$job['id'],$next]);$id=(int)$pdo->lastInsertId();$q=$pdo->prepare('SELECT * FROM data_training_attempts WHERE id=?');$q->execute([$id]);return $q->fetch()?:[];
}
function data_training_attempt_current(PDO $pdo,int $jobId): ?array {
    $q=$pdo->prepare('SELECT * FROM data_training_attempts WHERE job_id=? ORDER BY attempt_number DESC LIMIT 1');$q->execute([$jobId]);return $q->fetch()?:null;
}
function data_training_provider_model(PDO $pdo,array $job): array {
    $base=data_training_model_version_by_id($pdo,(int)$job['base_model_version_id']);if(!$base||!$base['ai_model_id'])throw new RuntimeException('Training base runtime model is unavailable.');return ai_model_record($pdo,(int)$base['ai_model_id']);
}
function data_training_provider_base_url(array $model): string {
    if($model['provider_type']==='openai')return rtrim((string)($model['api_base_url']?:'https://api.openai.com'),'/');$base=rtrim((string)($model['api_base_url']??''),'/');if($base==='')throw new RuntimeException('OpenAI-compatible training provider requires an API base URL.');return $base;
}
function data_training_provider_headers(array $config,array $model): array {
    $key=ai_decrypt_secret($config,$model['api_key_ciphertext']);if($model['provider_type']==='openai'&&$key==='')throw new RuntimeException('OpenAI training API key is not configured.');return $key!==''?['Authorization: Bearer '.$key]:[];
}
function data_training_http_json(string $method,string $url,array $headers,?array $body=null,int $timeout=90): array {
    $ch=curl_init($url);$headers[]='Content-Type: application/json';$opts=[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_HTTPHEADER=>$headers,CURLOPT_TIMEOUT=>$timeout,CURLOPT_CONNECTTIMEOUT=>10,CURLOPT_PROTOCOLS=>CURLPROTO_HTTPS|CURLPROTO_HTTP];if($body!==null)$opts[CURLOPT_POSTFIELDS]=json_encode($body,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);curl_setopt_array($ch,$opts);$raw=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);$err=curl_error($ch);curl_close($ch);if($raw===false)throw new RuntimeException('Training provider connection failed'.($err?': '.$err:''));$json=json_decode($raw,true);if($status<200||$status>=300){$msg=is_array($json)?($json['error']['message']??$json['message']??'Training provider request failed'):'Training provider request failed';throw new RuntimeException((string)$msg);}if(!is_array($json))throw new RuntimeException('Invalid training provider response.');return $json;
}
function data_training_http_upload(string $url,array $headers,string $jsonl,int $expirySeconds): array {
    $tmp=tempnam(sys_get_temp_dir(),'annotated-train-');if($tmp===false)throw new RuntimeException('Unable to create temporary training package.');file_put_contents($tmp,$jsonl);try{$file=new CURLFile($tmp,'application/jsonl','annotated-training.jsonl');$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>['purpose'=>'fine-tune','file'=>$file,'expires_after[anchor]'=>'created_at','expires_after[seconds]'=>(string)$expirySeconds],CURLOPT_HTTPHEADER=>$headers,CURLOPT_TIMEOUT=>120,CURLOPT_CONNECTTIMEOUT=>10,CURLOPT_PROTOCOLS=>CURLPROTO_HTTPS|CURLPROTO_HTTP]);$raw=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);$err=curl_error($ch);curl_close($ch);if($raw===false)throw new RuntimeException('Training file upload failed'.($err?': '.$err:''));$json=json_decode($raw,true);if($status<200||$status>=300){$msg=is_array($json)?($json['error']['message']??$json['message']??'Training file upload failed'):'Training file upload failed';throw new RuntimeException((string)$msg);}if(!is_array($json)||empty($json['id']))throw new RuntimeException('Training provider returned no file ID.');return $json;}finally{@unlink($tmp);}
}
function data_training_provider_submit(PDO $pdo,array $config,array $job,array $attempt,string $package): array {
    $model=data_training_provider_model($pdo,$job);$base=data_training_provider_base_url($model);$headers=data_training_provider_headers($config,$model);$file=data_training_http_upload($base.'/v1/files',$headers,$package,(int)$job['config']['file_expiry_seconds']);$fileId=(string)$file['id'];$method=['type'=>'supervised','supervised'=>['hyperparameters'=>['n_epochs'=>$job['config']['n_epochs'],'batch_size'=>$job['config']['batch_size'],'learning_rate_multiplier'=>$job['config']['learning_rate_multiplier']]]];$body=['model'=>$model['model_name'],'training_file'=>$fileId,'method'=>$method,'metadata'=>['annotated_training_job'=>$job['public_id'],'annotated_job_hash'=>$job['job_hash']]];if($job['config']['seed']!==null)$body['seed']=(int)$job['config']['seed'];if($job['config']['suffix']!==null)$body['suffix']=$job['config']['suffix'];$requestHash=data_attribution_hash($body);$jobResponse=data_training_http_json('POST',$base.'/v1/fine_tuning/jobs',array_merge($headers,['Idempotency-Key: annotated-'.$job['public_id'].'-'.$attempt['attempt_number']]),$body,120);if(empty($jobResponse['id']))throw new RuntimeException('Training provider returned no fine-tuning job ID.');$responseHash=data_attribution_hash($jobResponse);return ['file'=>$file,'file_id'=>$fileId,'job'=>$jobResponse,'job_id'=>(string)$jobResponse['id'],'request_hash'=>$requestHash,'response_hash'=>$responseHash];
}
function data_training_provider_events(PDO $pdo,array $config,array $job,array $attempt): void {
    if(empty($job['provider_job_id']))return;try{$model=data_training_provider_model($pdo,$job);$base=data_training_provider_base_url($model);$headers=data_training_provider_headers($config,$model);$j=data_training_http_json('GET',$base.'/v1/fine_tuning/jobs/'.rawurlencode((string)$job['provider_job_id']).'/events?limit=100',$headers,null,45);foreach(($j['data']??[]) as $e){if(!is_array($e))continue;data_training_log($pdo,(int)$job['id'],(int)($attempt['id']??0)?:null,'provider',(string)($e['level']??'info'),(string)($e['message']??'Provider event'),(string)($e['id']??'')?:null,(string)($e['type']??'message'),['created_at'=>$e['created_at']??null]);}}catch(Throwable $e){data_training_log($pdo,(int)$job['id'],(int)($attempt['id']??0)?:null,'annotated','warning','Unable to sync provider events: '.mb_substr($e->getMessage(),0,500));}
}
function data_training_provider_retrieve(PDO $pdo,array $config,array $job): array {
    $model=data_training_provider_model($pdo,$job);$base=data_training_provider_base_url($model);return data_training_http_json('GET',$base.'/v1/fine_tuning/jobs/'.rawurlencode((string)$job['provider_job_id']),data_training_provider_headers($config,$model),null,60);
}
function data_training_provider_cancel(PDO $pdo,array $config,array $job): array {
    $model=data_training_provider_model($pdo,$job);$base=data_training_provider_base_url($model);return data_training_http_json('POST',$base.'/v1/fine_tuning/jobs/'.rawurlencode((string)$job['provider_job_id']).'/cancel',data_training_provider_headers($config,$model),[],60);
}
function data_training_provider_delete_file(PDO $pdo,array $config,array $job): void {
    if(empty($job['provider_file_id']))return;try{$model=data_training_provider_model($pdo,$job);$base=data_training_provider_base_url($model);data_training_http_json('DELETE',$base.'/v1/files/'.rawurlencode((string)$job['provider_file_id']),data_training_provider_headers($config,$model),null,45);}catch(Throwable $e){data_training_log($pdo,(int)$job['id'],null,'annotated','warning','Unable to delete provider training file: '.mb_substr($e->getMessage(),0,500));}
}
function data_training_register_output(PDO $pdo,array $viewer,array $job,string $artifactRef,string $artifactHash,?string $outputModelName=null,?int $runtimeModelId=null): array {
    if(!preg_match('/^[a-f0-9]{64}$/',$artifactHash))throw new InvalidArgumentException('Output artifact hash must be SHA-256.');$current=data_training_current_use_status($pdo,$job);if(!$current['usable'])throw new RuntimeException('Training output cannot be registered because current rights or integrity no longer validates.');$registry=data_training_registry_by_id($pdo,(int)$job['output_registry_id']);if(!$registry)throw new RuntimeException('Output Model Registry is unavailable.');
    if($runtimeModelId!==null)ai_model_record($pdo,$runtimeModelId);$version=data_model_version_create($pdo,$viewer,(string)$registry['public_id'],['version_label'=>$job['output_version_label'],'origin'=>'annotated_trained','ai_model_id'=>$runtimeModelId?:'','architecture'=>'Fine-tuned derivative of '.$job['base_version_label'],'intended_use'=>'Experimental training output from '.$job['public_id'].'. Requires Phase 39 evaluation and Phase 40 approval before governed activation.','artifact_ref'=>$artifactRef,'artifact_hash'=>$artifactHash,'required_model_runs'=>1,'required_human_reviews'=>1,'minimum_human_pass_rate'=>0.5,'require_integrity'=>1,'require_no_regression'=>0]);return $version;
}
function data_training_finalize_provider_success(PDO $pdo,array $config,array $job,array $provider): array {
    $current=data_training_current_use_status($pdo,$job);if(!$current['usable']){$pdo->prepare("UPDATE data_training_jobs SET status='blocked',provider_status=?,output_model_name=?,blocked_at=NOW(),last_error='Current rights or integrity no longer validates after provider training completed.',completed_at=NOW() WHERE id=?")->execute([(string)($provider['status']??'succeeded'),(string)($provider['fine_tuned_model']??''),$job['id']]);data_training_event($pdo,(int)$job['id'],null,'completion_blocked',['reason'=>'rights_or_integrity_changed_after_training']);return data_training_job_get($pdo,$job['public_id'])??[];}
    $modelName=trim((string)($provider['fine_tuned_model']??''));if($modelName==='')throw new RuntimeException('Training provider reported success without a fine-tuned model name.');$providerId=(int)$job['provider_id'];$q=$pdo->prepare('SELECT id FROM ai_models WHERE provider_id=? AND model_name=? LIMIT 1');$q->execute([$providerId,$modelName]);$runtimeId=(int)($q->fetchColumn()?:0);if(!$runtimeId){$baseModel=data_training_provider_model($pdo,$job);$display=mb_substr($job['output_registry_name'].' · '.$job['output_version_label'],0,190);$pdo->prepare('INSERT INTO ai_models(public_id,provider_id,model_name,display_name,enabled,admin_enabled,pro_enabled,max_output_tokens) VALUES(?,?,?,?,1,1,0,?)')->execute([ulid_like(),$providerId,$modelName,$display,max(256,(int)$baseModel['max_output_tokens'])]);$runtimeId=(int)$pdo->lastInsertId();}
    $descriptor=['provider_job_id'=>$job['provider_job_id'],'fine_tuned_model'=>$modelName,'result_files'=>$provider['result_files']??[],'trained_tokens'=>$provider['trained_tokens']??null,'job_hash'=>$job['job_hash']];$artifactHash=data_attribution_hash($descriptor);$artifactRef='provider-model:'.$modelName;$systemViewer=['id'=>(int)$job['created_by_user_id'],'role'=>'admin'];$version=data_training_register_output($pdo,$systemViewer,$job,$artifactRef,$artifactHash,$modelName,$runtimeId);$tokens=isset($provider['trained_tokens'])?(int)$provider['trained_tokens']:null;$rate=$job['cost_rate_usd_per_million_tokens']!==null?(float)$job['cost_rate_usd_per_million_tokens']:null;$estimated=$tokens!==null&&$rate!==null?($tokens/1000000)*$rate:null;$results=$provider['result_files']??[];$completion=data_attribution_hash(['job_hash'=>$job['job_hash'],'provider_job_id'=>$job['provider_job_id'],'output_model_name'=>$modelName,'artifact_hash'=>$artifactHash,'output_version_public_id'=>$version['public_id'],'trained_tokens'=>$tokens,'result_files'=>$results]);
    $pdo->prepare("UPDATE data_training_jobs SET status='succeeded',provider_status='succeeded',result_files_json=?,trained_tokens=?,estimated_cost_usd=?,output_model_name=?,output_artifact_ref=?,output_artifact_hash=?,output_model_version_id=?,completion_hash=?,completed_at=NOW(),last_error=NULL WHERE id=?")->execute([$results?data_attribution_encode($results):null,$tokens,$estimated,$modelName,$artifactRef,$artifactHash,$version['id'],$completion,$job['id']]);$attempt=data_training_attempt_current($pdo,(int)$job['id']);if($attempt)$pdo->prepare("UPDATE data_training_attempts SET status='succeeded',completed_at=NOW() WHERE id=?")->execute([$attempt['id']]);data_training_event($pdo,(int)$job['id'],null,'training_succeeded',['output_model_version_public_id'=>$version['public_id'],'completion_hash'=>$completion,'trained_tokens'=>$tokens]);data_training_provider_delete_file($pdo,$config,array_merge($job,['provider_file_id'=>$job['provider_file_id']]));return data_training_job_get($pdo,$job['public_id'])??[];
}
function data_training_prepare_or_submit(PDO $pdo,array $config,array $job): array {
    $current=data_training_current_use_status($pdo,$job);if(!$current['usable']){$pdo->prepare("UPDATE data_training_jobs SET status='blocked',blocked_at=NOW(),last_error='Current rights or integrity no longer validates.' WHERE id=?")->execute([$job['id']]);data_training_event($pdo,(int)$job['id'],null,'job_blocked',['reason'=>'current_use_invalid']);return data_training_job_get($pdo,$job['public_id'])??[];}$built=data_training_package_inspect($pdo,$job,true);if($built['package']===null||!hash_equals((string)$job['package_hash'],(string)$built['package_hash']))throw new RuntimeException('Training package no longer matches the queued package hash.');
    if($job['executor_type']==='manual'){$pdo->prepare("UPDATE data_training_jobs SET status='prepared',prepared_at=NOW(),updated_at=NOW() WHERE id=?")->execute([$job['id']]);data_training_event($pdo,(int)$job['id'],null,'package_prepared',['package_hash'=>$job['package_hash'],'package_bytes'=>$built['package_bytes']]);return data_training_job_get($pdo,$job['public_id'])??[];}
    $attempt=data_training_attempt_start($pdo,$job);try{$submitted=data_training_provider_submit($pdo,$config,$job,$attempt,(string)$built['package']);$providerStatus=(string)($submitted['job']['status']??'queued');$pdo->prepare("UPDATE data_training_attempts SET status='submitted',provider_file_id=?,provider_job_id=?,request_hash=?,response_hash=?,submitted_at=NOW() WHERE id=?")->execute([$submitted['file_id'],$submitted['job_id'],$submitted['request_hash'],$submitted['response_hash'],$attempt['id']]);$pdo->prepare("UPDATE data_training_jobs SET status='submitted',provider_file_id=?,provider_job_id=?,provider_status=?,submitted_at=NOW(),last_error=NULL WHERE id=?")->execute([$submitted['file_id'],$submitted['job_id'],$providerStatus,$job['id']]);data_training_log($pdo,(int)$job['id'],(int)$attempt['id'],'annotated','info','Training package uploaded and provider job submitted.',null,'submitted',['provider_job_id'=>$submitted['job_id']]);data_training_event($pdo,(int)$job['id'],null,'provider_submitted',['provider_job_id'=>$submitted['job_id'],'provider_file_id'=>$submitted['file_id'],'attempt'=>(int)$attempt['attempt_number']]);return data_training_job_get($pdo,$job['public_id'])??[];}catch(Throwable $e){$pdo->prepare("UPDATE data_training_attempts SET status='failed',error_text=?,completed_at=NOW() WHERE id=?")->execute([mb_substr($e->getMessage(),0,1500),$attempt['id']]);throw $e;}
}
function data_training_poll(PDO $pdo,array $config,array $job): array {
    if(empty($job['provider_job_id']))throw new RuntimeException('Provider training job ID is missing.');$attempt=data_training_attempt_current($pdo,(int)$job['id']);data_training_provider_events($pdo,$config,$job,$attempt??[]);$provider=data_training_provider_retrieve($pdo,$config,$job);$status=(string)($provider['status']??'unknown');$mapped=in_array($status,['validating_files','queued'],true)?'submitted':($status==='running'?'running':($status==='succeeded'?'succeeded':($status==='failed'?'failed':($status==='cancelled'?'cancelled':$job['status']))));
    if(in_array($mapped,['submitted','running'],true)){$current=data_training_current_use_status($pdo,$job);if(!$current['usable']){try{data_training_provider_cancel($pdo,$config,$job);}catch(Throwable $e){data_training_log($pdo,(int)$job['id'],$attempt['id']??null,'annotated','warning','Automatic cancellation after rights/integrity change failed: '.mb_substr($e->getMessage(),0,500));}$pdo->prepare("UPDATE data_training_jobs SET status='blocked',provider_status=?,blocked_at=NOW(),last_error='Current rights or integrity changed while training was active.' WHERE id=?")->execute([$status,$job['id']]);if($attempt)$pdo->prepare("UPDATE data_training_attempts SET status='blocked',error_text='rights_or_integrity_changed',completed_at=NOW() WHERE id=?")->execute([$attempt['id']]);data_training_event($pdo,(int)$job['id'],null,'active_training_blocked',['provider_status'=>$status]);return data_training_job_get($pdo,$job['public_id'])??[];}$pdo->prepare("UPDATE data_training_jobs SET status=?,provider_status=?,started_at=COALESCE(started_at,IF(?='running',NOW(),NULL)),updated_at=NOW() WHERE id=?")->execute([$mapped,$status,$mapped,$job['id']]);return data_training_job_get($pdo,$job['public_id'])??[];}
    if($mapped==='succeeded')return data_training_finalize_provider_success($pdo,$config,$job,$provider);
    if($mapped==='failed'){$error=(string)($provider['error']['message']??'Provider fine-tuning job failed.');$pdo->prepare("UPDATE data_training_jobs SET status='failed',provider_status=?,last_error=?,completed_at=NOW() WHERE id=?")->execute([$status,mb_substr($error,0,1500),$job['id']]);if($attempt)$pdo->prepare("UPDATE data_training_attempts SET status='failed',error_text=?,completed_at=NOW() WHERE id=?")->execute([mb_substr($error,0,1500),$attempt['id']]);data_training_event($pdo,(int)$job['id'],null,'provider_failed',['error'=>mb_substr($error,0,500)]);data_training_provider_delete_file($pdo,$config,$job);return data_training_job_get($pdo,$job['public_id'])??[];}
    if($mapped==='cancelled'){$pdo->prepare("UPDATE data_training_jobs SET status='cancelled',provider_status=?,cancelled_at=NOW(),completed_at=NOW() WHERE id=?")->execute([$status,$job['id']]);if($attempt)$pdo->prepare("UPDATE data_training_attempts SET status='cancelled',completed_at=NOW() WHERE id=?")->execute([$attempt['id']]);data_training_event($pdo,(int)$job['id'],null,'provider_cancelled',[]);data_training_provider_delete_file($pdo,$config,$job);return data_training_job_get($pdo,$job['public_id'])??[];}
    return data_training_job_get($pdo,$job['public_id'])??[];
}
function data_training_request_cancel(PDO $pdo,array $viewer,string $publicId): array {
    data_training_require_admin($viewer);$job=data_training_job_get($pdo,$publicId);if(!$job)throw new RuntimeException('Training job not found.');if(in_array($job['status'],['succeeded','failed','cancelled','blocked'],true))throw new RuntimeException('Terminal training job cannot be cancelled.');if(in_array($job['status'],['draft','queued','preparing','prepared'],true)){$pdo->prepare("UPDATE data_training_jobs SET status='cancelled',cancelled_at=NOW(),completed_at=NOW() WHERE id=?")->execute([$job['id']]);data_training_event($pdo,(int)$job['id'],(int)$viewer['id'],'cancelled_before_submission',[]);}else{$pdo->prepare("UPDATE data_training_jobs SET status='cancel_requested',cancel_requested_at=NOW() WHERE id=?")->execute([$job['id']]);data_training_event($pdo,(int)$job['id'],(int)$viewer['id'],'cancel_requested',[]);}return data_training_job_get($pdo,$publicId)??[];
}
function data_training_retry(PDO $pdo,array $viewer,string $publicId): array {
    data_training_require_admin($viewer);$job=data_training_job_get($pdo,$publicId);if(!$job)throw new RuntimeException('Training job not found.');if($job['status']!=='failed')throw new RuntimeException('Only failed training jobs can be retried.');if((int)$job['attempt_count']>=(int)$job['max_attempts'])throw new RuntimeException('Training job has exhausted its configured attempts.');$current=data_training_current_use_status($pdo,$job);if(!$current['usable'])throw new RuntimeException('Training job cannot retry because current rights or integrity is blocked.');$pdo->prepare("UPDATE data_training_jobs SET status='queued',provider_file_id=NULL,provider_job_id=NULL,provider_status=NULL,result_files_json=NULL,last_error=NULL,submitted_at=NULL,started_at=NULL,completed_at=NULL,cancel_requested_at=NULL,updated_at=NOW() WHERE id=?")->execute([$job['id']]);data_training_event($pdo,(int)$job['id'],(int)$viewer['id'],'job_retried',['next_attempt'=>(int)$job['attempt_count']+1]);return data_training_job_get($pdo,$publicId)??[];
}
function data_training_manual_complete(PDO $pdo,array $viewer,string $publicId,array $input): array {
    data_training_require_admin($viewer);$job=data_training_job_get($pdo,$publicId);if(!$job)throw new RuntimeException('Training job not found.');if($job['executor_type']!=='manual'||$job['status']!=='prepared')throw new RuntimeException('Only prepared manual training jobs can be completed manually.');$ref=mb_substr(trim((string)($input['artifact_ref']??'')),0,1000);$hash=strtolower(trim((string)($input['artifact_hash']??'')));if($ref===''||!preg_match('/^[a-f0-9]{64}$/',$hash))throw new InvalidArgumentException('Manual completion requires an artifact reference and SHA-256 hash.');$runtimeId=($input['runtime_model_id']??'')!==''?(int)$input['runtime_model_id']:null;$version=data_training_register_output($pdo,$viewer,$job,$ref,$hash,trim((string)($input['output_model_name']??''))?:null,$runtimeId);$completion=data_attribution_hash(['job_hash'=>$job['job_hash'],'artifact_ref'=>$ref,'artifact_hash'=>$hash,'output_version_public_id'=>$version['public_id']]);$cost=($input['actual_cost_usd']??'')!==''?max(0.0,(float)$input['actual_cost_usd']):null;$pdo->prepare("UPDATE data_training_jobs SET status='succeeded',output_model_name=?,output_artifact_ref=?,output_artifact_hash=?,output_model_version_id=?,completion_hash=?,actual_cost_usd=?,completed_at=NOW(),last_error=NULL WHERE id=?")->execute([trim((string)($input['output_model_name']??''))?:null,$ref,$hash,$version['id'],$completion,$cost,$job['id']]);data_training_event($pdo,(int)$job['id'],(int)$viewer['id'],'manual_training_completed',['output_model_version_public_id'=>$version['public_id'],'completion_hash'=>$completion]);return data_training_job_get($pdo,$publicId)??[];
}
function data_training_cost_update(PDO $pdo,array $viewer,string $publicId,?float $actualCost): array {
    data_training_require_admin($viewer);$job=data_training_job_get($pdo,$publicId);if(!$job)throw new RuntimeException('Training job not found.');if(!in_array($job['status'],['succeeded','failed','cancelled','blocked'],true))throw new RuntimeException('Actual training cost can be recorded only after the job reaches a terminal state.');$cost=$actualCost!==null?max(0.0,$actualCost):null;$pdo->prepare('UPDATE data_training_jobs SET actual_cost_usd=? WHERE id=?')->execute([$cost,$job['id']]);data_training_event($pdo,(int)$job['id'],(int)$viewer['id'],'actual_cost_updated',['actual_cost_usd'=>$cost]);return data_training_job_get($pdo,$publicId)??[];
}
function data_training_export_package(PDO $pdo,array $viewer,string $publicId): array {
    data_training_require_admin($viewer);$job=data_training_job_get($pdo,$publicId);if(!$job)throw new RuntimeException('Training job not found.');if($job['status']==='draft')throw new RuntimeException('Queue the job before exporting its frozen training package.');$current=data_training_current_use_status($pdo,$job);if(!$current['usable'])throw new RuntimeException('Training package export is blocked because current rights or integrity no longer validates.');$built=data_training_package_inspect($pdo,$job,true);if($built['package']===null||!hash_equals((string)$job['package_hash'],(string)$built['package_hash']))throw new RuntimeException('Training package hash no longer matches the queued job.');data_training_event($pdo,(int)$job['id'],(int)$viewer['id'],'package_exported',['package_hash'=>$built['package_hash'],'bytes'=>$built['package_bytes']]);return ['content'=>$built['package'],'hash'=>$built['package_hash'],'bytes'=>$built['package_bytes'],'examples'=>$built['valid_examples']];
}
function data_training_process_next(PDO $pdo,array $config): ?array {
    if(!data_training_ready($pdo))throw new RuntimeException('Training Registry is unavailable.');$pdo->beginTransaction();try{$q=$pdo->query("SELECT id,status FROM data_training_jobs WHERE status IN ('cancel_requested','queued','submitted','running') ORDER BY CASE status WHEN 'cancel_requested' THEN 0 WHEN 'submitted' THEN 1 WHEN 'running' THEN 2 ELSE 3 END,updated_at,id LIMIT 1 FOR UPDATE");$row=$q->fetch();if(!$row){$pdo->commit();return null;}$id=(int)$row['id'];$status=(string)$row['status'];if($status==='queued')$pdo->prepare("UPDATE data_training_jobs SET status='preparing',updated_at=NOW() WHERE id=?")->execute([$id]);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
    $q=$pdo->prepare('SELECT public_id FROM data_training_jobs WHERE id=?');$q->execute([$id]);$public=(string)$q->fetchColumn();$job=data_training_job_get($pdo,$public);if(!$job)return null;
    try{if($status==='cancel_requested'){if(!empty($job['provider_job_id']))data_training_provider_cancel($pdo,$config,$job);$pdo->prepare("UPDATE data_training_jobs SET status='cancelled',cancelled_at=NOW(),completed_at=NOW() WHERE id=?")->execute([$job['id']]);data_training_event($pdo,(int)$job['id'],null,'cancelled_by_worker',[]);return data_training_job_get($pdo,$public);}if($status==='queued')return data_training_prepare_or_submit($pdo,$config,$job);return data_training_poll($pdo,$config,$job);}catch(Throwable $e){$fresh=data_training_job_get($pdo,$public);if($fresh&&!in_array($fresh['status'],['succeeded','cancelled','blocked'],true)){$pdo->prepare("UPDATE data_training_jobs SET status='failed',last_error=?,completed_at=NOW() WHERE id=?")->execute([mb_substr($e->getMessage(),0,1500),$fresh['id']]);$attempt=data_training_attempt_current($pdo,(int)$fresh['id']);if($attempt&&!in_array($attempt['status'],['failed','succeeded','cancelled','blocked'],true))$pdo->prepare("UPDATE data_training_attempts SET status='failed',error_text=?,completed_at=NOW() WHERE id=?")->execute([mb_substr($e->getMessage(),0,1500),$attempt['id']]);data_training_log($pdo,(int)$fresh['id'],$attempt['id']??null,'annotated','error',$e->getMessage(),null,'worker_failure');data_training_event($pdo,(int)$fresh['id'],null,'worker_failed',['error'=>mb_substr($e->getMessage(),0,500)]);}throw $e;}
}
function data_training_attempts(PDO $pdo,int $jobId): array {$q=$pdo->prepare('SELECT * FROM data_training_attempts WHERE job_id=? ORDER BY attempt_number DESC');$q->execute([$jobId]);return $q->fetchAll();}
function data_training_logs(PDO $pdo,int $jobId,int $limit=200): array {$limit=max(1,min(500,$limit));$q=$pdo->prepare("SELECT * FROM data_training_logs WHERE job_id=? ORDER BY id DESC LIMIT $limit");$q->execute([$jobId]);return $q->fetchAll();}
function data_training_events(PDO $pdo,int $jobId,int $limit=100): array {$limit=max(1,min(250,$limit));$q=$pdo->prepare("SELECT e.*,u.display_name actor_name FROM data_training_events e LEFT JOIN users u ON u.id=e.actor_user_id WHERE e.job_id=? ORDER BY e.id DESC LIMIT $limit");$q->execute([$jobId]);return $q->fetchAll();}
function data_training_summary(PDO $pdo): array {
    if(!data_training_ready($pdo))return ['ready'=>false];$scalar=fn(string $sql)=>(int)$pdo->query($sql)->fetchColumn();return ['ready'=>true,'jobs'=>$scalar('SELECT COUNT(*) FROM data_training_jobs'),'drafts'=>$scalar("SELECT COUNT(*) FROM data_training_jobs WHERE status='draft'"),'active'=>$scalar("SELECT COUNT(*) FROM data_training_jobs WHERE status IN ('queued','preparing','submitted','running','cancel_requested')"),'prepared'=>$scalar("SELECT COUNT(*) FROM data_training_jobs WHERE status='prepared'"),'succeeded'=>$scalar("SELECT COUNT(*) FROM data_training_jobs WHERE status='succeeded'"),'failed'=>$scalar("SELECT COUNT(*) FROM data_training_jobs WHERE status='failed'"),'blocked'=>$scalar("SELECT COUNT(*) FROM data_training_jobs WHERE status='blocked'")];
}
