<?php
declare(strict_types=1);

/**
 * Phase 42 — Post-Training Evaluation & Promotion Readiness
 *
 * Orchestrates existing Phase 39 evaluation runs for successful Phase 41 outputs.
 * It may link valid evidence into Phase 40, but never changes model lifecycle status.
 */

function data_post_training_ready(PDO $pdo): bool {
    try{return data_training_ready($pdo)&&installer_table_exists($pdo,'data_post_training_plans')&&installer_table_exists($pdo,'data_post_training_suite_links')&&installer_table_exists($pdo,'data_post_training_packets');}
    catch(Throwable $e){return false;}
}
function data_post_training_require_admin(array $viewer): void {
    if(($viewer['role']??'')!=='admin')throw new RuntimeException('Administrator access is required for Post-Training Evaluation operations.');
}
function data_post_training_policy(array $input): array {
    return [
        'required_human_reviews_per_run'=>max(1,min(100,(int)($input['required_human_reviews_per_run']??1))),
        'minimum_human_pass_rate'=>max(0.0,min(1.0,(float)($input['minimum_human_pass_rate']??0.5))),
        'require_no_regression'=>array_key_exists('require_no_regression',$input)?data_attribution_bool($input['require_no_regression']):1,
        'max_regressed_metrics'=>max(0,min(50,(int)($input['max_regressed_metrics']??0))),
        'regression_tolerance'=>max(0.0,min(0.25,(float)($input['regression_tolerance']??0.02))),
        'require_phase40_gate'=>array_key_exists('require_phase40_gate',$input)?data_attribution_bool($input['require_phase40_gate']):1,
        'policy_version'=>'phase42-v1',
    ];
}
function data_post_training_event(PDO $pdo,int $planId,?int $actorUserId,string $type,array $details=[]): void {
    $pdo->prepare('INSERT INTO data_post_training_events(plan_id,actor_user_id,event_type,details_json) VALUES(?,?,?,?)')->execute([$planId,$actorUserId,$type,$details?data_attribution_encode($details):null]);
}
function data_post_training_plan_get(PDO $pdo,string $publicId): ?array {
    if(!data_post_training_ready($pdo))return null;$q=$pdo->prepare('SELECT p.*,j.public_id training_job_public_id,j.output_version_label,j.status training_status,j.completion_hash current_training_completion_hash,ov.public_id output_version_public_id,ov.version_label output_version_label_current,ov.status output_version_status,ov.registry_id output_registry_id,bv.public_id baseline_version_public_id,bv.version_label baseline_version_label,bv.status baseline_version_status,r.public_id registry_public_id,r.name registry_name,u.display_name creator_name FROM data_post_training_plans p JOIN data_training_jobs j ON j.id=p.training_job_id JOIN data_model_versions ov ON ov.id=p.output_model_version_id JOIN data_model_versions bv ON bv.id=p.baseline_model_version_id JOIN data_model_registry r ON r.id=ov.registry_id JOIN users u ON u.id=p.created_by_user_id WHERE p.public_id=? LIMIT 1');$q->execute([trim($publicId)]);$p=$q->fetch();if(!$p)return null;$p['policy']=json_decode((string)$p['policy_json'],true)?:[];return $p;
}
function data_post_training_plans(PDO $pdo,int $limit=100): array {
    if(!data_post_training_ready($pdo))return [];$limit=max(1,min(250,$limit));$q=$pdo->query("SELECT p.*,j.public_id training_job_public_id,j.output_version_label,ov.public_id output_version_public_id,ov.status output_version_status,bv.version_label baseline_version_label,r.name registry_name,(SELECT COUNT(*) FROM data_post_training_suite_links l WHERE l.plan_id=p.id) suite_count,(SELECT COUNT(*) FROM data_post_training_packets pk WHERE pk.plan_id=p.id) packet_count FROM data_post_training_plans p JOIN data_training_jobs j ON j.id=p.training_job_id JOIN data_model_versions ov ON ov.id=p.output_model_version_id JOIN data_model_versions bv ON bv.id=p.baseline_model_version_id JOIN data_model_registry r ON r.id=ov.registry_id ORDER BY p.id DESC LIMIT $limit");return $q->fetchAll();
}
function data_post_training_links(PDO $pdo,int $planId): array {
    $q=$pdo->prepare('SELECT l.*,ts.public_id template_suite_public_id,ts.name template_suite_name,cs.public_id candidate_suite_public_id,cs.name candidate_suite_name,br.public_id baseline_run_public_id,cr.public_id candidate_run_public_id,cr.status candidate_run_status FROM data_post_training_suite_links l JOIN data_evaluation_suites ts ON ts.id=l.template_suite_id LEFT JOIN data_evaluation_suites cs ON cs.id=l.candidate_suite_id JOIN data_evaluation_runs br ON br.id=l.baseline_run_id LEFT JOIN data_evaluation_runs cr ON cr.id=l.candidate_run_id WHERE l.plan_id=? ORDER BY l.id');$q->execute([$planId]);$rows=$q->fetchAll();foreach($rows as &$row)$row['comparison']=$row['comparison_json']?json_decode((string)$row['comparison_json'],true):null;unset($row);return $rows;
}
function data_post_training_packets(PDO $pdo,int $planId): array {
    $q=$pdo->prepare('SELECT p.*,u.display_name creator_name FROM data_post_training_packets p LEFT JOIN users u ON u.id=p.created_by_user_id WHERE p.plan_id=? ORDER BY p.sequence_number DESC');$q->execute([$planId]);$rows=$q->fetchAll();foreach($rows as &$row)$row['packet']=json_decode((string)$row['packet_json'],true)?:[];unset($row);return $rows;
}
function data_post_training_packet_integrity(array $packetRow): array {
    $packet=json_decode((string)$packetRow['packet_json'],true);if(!is_array($packet))$packet=[];$computed=hash('sha256',data_attribution_encode($packet));$ok=hash_equals((string)$packetRow['packet_hash'],$computed);return ['ok'=>$ok,'stored_hash'=>$packetRow['packet_hash'],'computed_hash'=>$computed];
}
function data_post_training_training_job(PDO $pdo,string $publicId): ?array {
    return data_training_job_get($pdo,$publicId);
}
function data_post_training_eligible_jobs(PDO $pdo,int $limit=100): array {
    if(!data_post_training_ready($pdo))return [];$limit=max(1,min(250,$limit));$q=$pdo->query("SELECT j.public_id,j.output_version_label,j.completed_at,j.output_model_version_id,bv.version_label baseline_version_label,r.name registry_name,ov.status output_version_status,ov.ai_model_id FROM data_training_jobs j JOIN data_model_versions bv ON bv.id=j.base_model_version_id JOIN data_model_versions ov ON ov.id=j.output_model_version_id JOIN data_model_registry r ON r.id=ov.registry_id LEFT JOIN data_post_training_plans p ON p.training_job_id=j.id WHERE j.status='succeeded' AND p.id IS NULL ORDER BY j.id DESC LIMIT $limit");return $q->fetchAll();
}
function data_post_training_lineage(PDO $pdo,array $job,?array $plan=null): array {
    $checks=[];$completion=data_training_completion_integrity($pdo,$job);$checks['training_completion_integrity']=$completion['ok'];
    $use=data_training_current_use_status($pdo,$job);$checks['training_current_use']=$use['usable'];
    $output=!empty($job['output_model_version_public_id'])?data_model_version_get($pdo,(string)$job['output_model_version_public_id']):null;$checks['output_exists']=$output!==null;$postDecisionReady=$plan&&$plan['status']==='ready';$allowedOutputStates=$postDecisionReady?['experimental','candidate','approved','active']:['experimental'];$checks['output_lifecycle']=$output&&in_array($output['status'],$allowedOutputStates,true);$checks['output_runtime']=$output&&!empty($output['ai_model_id']);$checks['output_integrity']=$output?data_model_version_integrity($output)['ok']:false;
    $base=data_training_model_version_by_id($pdo,(int)$job['base_model_version_id']);$checks['baseline_exists']=$base!==null;$checks['baseline_status']=$base&&in_array($base['status'],['approved','active','deprecated'],true);$checks['baseline_integrity']=$base?data_model_version_integrity($base)['ok']:false;$approval=$base?data_training_approval_receipt_status($pdo,$job,$base):['ok'=>false];$checks['baseline_approval']=$approval['ok'];
    if($plan){$checks['training_completion_snapshot']=hash_equals((string)$plan['training_completion_hash'],(string)($job['completion_hash']??''));$checks['output_version_snapshot']=$output&&hash_equals((string)$plan['output_version_hash'],(string)$output['version_hash']);$checks['baseline_version_snapshot']=$base&&hash_equals((string)$plan['baseline_version_hash'],(string)$base['version_hash']);$checks['baseline_approval_snapshot']=hash_equals((string)$plan['baseline_approval_receipt_hash'],(string)($job['base_approval_receipt_hash']??''));}
    $pass=!in_array(false,$checks,true);return ['pass'=>$pass,'checks'=>$checks,'training_completion'=>$completion,'training_current_use'=>$use,'output'=>$output,'baseline'=>$base,'baseline_approval'=>$approval];
}
function data_post_training_template_suite(PDO $pdo,array $job,array $base,string $suitePublicId): array {
    $suite=data_evaluation_suite_get($pdo,$suitePublicId);if(!$suite)throw new RuntimeException('Baseline evaluation suite not found.');if($suite['status']!=='active'||$suite['benchmark_type']!=='model')throw new RuntimeException('Post-training templates must be active Phase 39 model benchmark suites.');if(!$base['ai_model_id']||(int)$suite['model_id']!==(int)$base['ai_model_id'])throw new RuntimeException('Baseline evaluation suite model does not match the Phase 41 training base model.');$baselineId=(int)($suite['baseline_run_id']??0);if(!$baselineId)throw new RuntimeException('Baseline evaluation suite requires an integrity-valid regression baseline run.');
    $q=$pdo->prepare('SELECT public_id FROM data_evaluation_runs WHERE id=?');$q->execute([$baselineId]);$runPublic=(string)($q->fetchColumn()?:'');$run=$runPublic!==''?data_evaluation_run_get($pdo,$runPublic):null;if(!$run||$run['status']!=='completed'||!data_evaluation_run_integrity($pdo,$run)['ok'])throw new RuntimeException('Baseline evaluation run is missing or failed integrity.');
    $q=$pdo->prepare('SELECT COUNT(*) FROM data_model_evaluation_links WHERE version_id=? AND evaluation_run_id=?');$q->execute([$base['id'],$run['id']]);if((int)$q->fetchColumn()<1)throw new RuntimeException('Baseline run must already be governed evidence linked to the Phase 40 base model version.');
    $fp=data_model_benchmark_fingerprint($pdo,$run);return ['suite'=>$suite,'run'=>$run,'fingerprint'=>$fp];
}
function data_post_training_eligible_suites(PDO $pdo,string $trainingJobPublicId): array {
    $job=data_training_job_get($pdo,$trainingJobPublicId);if(!$job||$job['status']!=='succeeded')return [];$base=data_training_model_version_by_id($pdo,(int)$job['base_model_version_id']);if(!$base||!$base['ai_model_id'])return [];$q=$pdo->prepare("SELECT public_id FROM data_evaluation_suites WHERE status='active' AND benchmark_type='model' AND model_id=? AND baseline_run_id IS NOT NULL ORDER BY id");$q->execute([$base['ai_model_id']]);$out=[];foreach($q->fetchAll(PDO::FETCH_COLUMN) as $public){try{$t=data_post_training_template_suite($pdo,$job,$base,(string)$public);$out[]=['suite'=>$t['suite'],'run'=>$t['run'],'fingerprint'=>$t['fingerprint']];}catch(Throwable $e){}}return $out;
}
function data_post_training_plan_create(PDO $pdo,array $viewer,string $trainingJobPublicId,array $suitePublicIds,array $input=[]): array {
    data_post_training_require_admin($viewer);if(!data_post_training_ready($pdo))throw new RuntimeException('Post-Training Evaluation requires the Phase 42 database upgrade.');$job=data_training_job_get($pdo,$trainingJobPublicId);if(!$job||$job['status']!=='succeeded')throw new RuntimeException('Post-training evaluation requires a successful Phase 41 training job.');if(empty($job['output_model_version_id']))throw new RuntimeException('Training job has no registered output model version.');$lineage=data_post_training_lineage($pdo,$job);if(!$lineage['pass'])throw new RuntimeException('Training lineage is not currently eligible for post-training evaluation.');
    $suitePublicIds=array_values(array_unique(array_filter(array_map('trim',$suitePublicIds))));if(!$suitePublicIds)throw new InvalidArgumentException('Select at least one governed baseline benchmark suite.');$policy=data_post_training_policy($input);$policyJson=data_attribution_encode($policy);$policyHash=hash('sha256',$policyJson);$public=ulid_like();$approvalHash=(string)$job['base_approval_receipt_hash'];
    $pdo->beginTransaction();try{$pdo->prepare("INSERT INTO data_post_training_plans(public_id,training_job_id,output_model_version_id,baseline_model_version_id,status,policy_json,policy_hash,training_completion_hash,output_version_hash,baseline_version_hash,baseline_approval_receipt_hash,created_by_user_id) VALUES(?,?,?,?,'draft',?,?,?,?,?,?,?)")->execute([$public,$job['id'],$job['output_model_version_id'],$job['base_model_version_id'],$policyJson,$policyHash,$job['completion_hash'],$lineage['output']['version_hash'],$lineage['baseline']['version_hash'],$approvalHash,$viewer['id']]);$id=(int)$pdo->lastInsertId();foreach($suitePublicIds as $suitePublic){$t=data_post_training_template_suite($pdo,$job,$lineage['baseline'],$suitePublic);$pdo->prepare("INSERT INTO data_post_training_suite_links(plan_id,template_suite_id,baseline_run_id,benchmark_fingerprint,status) VALUES(?,?,?,?,'selected')")->execute([$id,$t['suite']['id'],$t['run']['id'],$t['fingerprint']['hash']]);}data_post_training_event($pdo,$id,(int)$viewer['id'],'plan_created',['training_job_public_id'=>$job['public_id'],'suite_count'=>count($suitePublicIds),'policy_hash'=>$policyHash]);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}return data_post_training_plan_get($pdo,$public)??[];
}
function data_post_training_plan_hash_material(PDO $pdo,array $plan): array {
    $links=data_post_training_links($pdo,(int)$plan['id']);$mapped=[];foreach($links as $l)$mapped[]=['template_suite_public_id'=>$l['template_suite_public_id'],'candidate_suite_public_id'=>$l['candidate_suite_public_id'],'baseline_run_public_id'=>$l['baseline_run_public_id'],'candidate_run_public_id'=>$l['candidate_run_public_id'],'benchmark_fingerprint'=>$l['benchmark_fingerprint']];return ['public_id'=>$plan['public_id'],'training_job_public_id'=>$plan['training_job_public_id'],'training_completion_hash'=>$plan['training_completion_hash'],'output_version_public_id'=>$plan['output_version_public_id'],'output_version_hash'=>$plan['output_version_hash'],'baseline_version_public_id'=>$plan['baseline_version_public_id'],'baseline_version_hash'=>$plan['baseline_version_hash'],'baseline_approval_receipt_hash'=>$plan['baseline_approval_receipt_hash'],'policy_hash'=>$plan['policy_hash'],'suite_links'=>$mapped];
}
function data_post_training_plan_integrity(PDO $pdo,array $plan): array {
    if(empty($plan['plan_hash']))return ['ok'=>$plan['status']==='draft','reason'=>$plan['status']==='draft'?'draft_unfrozen':'plan_hash_missing'];$computed=data_attribution_hash(data_post_training_plan_hash_material($pdo,$plan));$ok=hash_equals((string)$plan['plan_hash'],$computed);return ['ok'=>$ok,'reason'=>$ok?'current':'plan_integrity_failure','stored_hash'=>$plan['plan_hash'],'computed_hash'=>$computed];
}
function data_post_training_clone_suite(PDO $pdo,array $viewer,array $template,array $output,array $plan): array {
    $suite=data_evaluation_suite_create($pdo,$viewer,['dataset_id'=>$template['dataset_id'],'name'=>'Post-training · '.$output['version_label'].' · '.$template['name'],'description'=>'Phase 42 equivalent benchmark cloned from '.$template['public_id'].' for plan '.$plan['public_id'].'.','benchmark_type'=>'model','top_k'=>$template['top_k'],'model_id'=>$output['ai_model_id'],'prompt_template'=>$template['prompt_template']]);foreach(data_evaluation_cases($pdo,(int)$template['id']) as $case){$tags=json_decode((string)($case['tags_json']??''),true);if(!is_array($tags))$tags=[];data_evaluation_case_add($pdo,$viewer,$suite['public_id'],['label'=>$case['label'],'query_text'=>$case['query_text'],'expected_dataset_item_id'=>$case['expected_dataset_item_id'],'reference_answer'=>$case['reference_answer'],'weight'=>$case['weight'],'tags'=>$tags]);}$suite=data_evaluation_suite_activate($pdo,$viewer,$suite['public_id']);return $suite;
}
function data_post_training_prepare(PDO $pdo,array $viewer,string $planPublicId): array {
    data_post_training_require_admin($viewer);$plan=data_post_training_plan_get($pdo,$planPublicId);if(!$plan)throw new RuntimeException('Post-training evaluation plan not found.');if($plan['status']!=='draft')throw new RuntimeException('Only draft post-training plans can be prepared.');$job=data_training_job_get($pdo,$plan['training_job_public_id']);$lineage=$job?data_post_training_lineage($pdo,$job,$plan):['pass'=>false];if(!$job||!$lineage['pass'])throw new RuntimeException('Post-training lineage changed before evaluation preparation.');$links=data_post_training_links($pdo,(int)$plan['id']);if(!$links)throw new RuntimeException('Evaluation plan has no governed benchmark suites.');
    $pdo->beginTransaction();try{foreach($links as $link){$t=data_post_training_template_suite($pdo,$job,$lineage['baseline'],$link['template_suite_public_id']);if(!hash_equals((string)$link['benchmark_fingerprint'],(string)$t['fingerprint']['hash']))throw new RuntimeException('Baseline benchmark fingerprint changed before preparation.');$candidateSuite=data_post_training_clone_suite($pdo,$viewer,$t['suite'],$lineage['output'],$plan);$candidateRun=data_evaluation_run_queue($pdo,$viewer,$candidateSuite['public_id']);$candidateFp=data_model_benchmark_fingerprint($pdo,$candidateRun);if(!hash_equals((string)$link['benchmark_fingerprint'],(string)$candidateFp['hash']))throw new RuntimeException('Cloned candidate benchmark is not fingerprint-equivalent to its governed baseline.');$pdo->prepare("UPDATE data_post_training_suite_links SET candidate_suite_id=?,candidate_run_id=?,status='queued',updated_at=NOW() WHERE id=?")->execute([$candidateSuite['id'],$candidateRun['id'],$link['id']]);}
        $fresh=data_post_training_plan_get($pdo,$planPublicId);$hash=data_attribution_hash(data_post_training_plan_hash_material($pdo,$fresh));$pdo->prepare("UPDATE data_post_training_plans SET status='evaluating',plan_hash=?,prepared_at=NOW(),last_error=NULL,blocked_at=NULL,updated_at=NOW() WHERE id=?")->execute([$hash,$plan['id']]);data_post_training_event($pdo,(int)$plan['id'],(int)$viewer['id'],'evaluation_prepared',['plan_hash'=>$hash,'suite_count'=>count($links)]);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}return data_post_training_plan_get($pdo,$planPublicId)??[];
}
function data_post_training_compare_runs(PDO $pdo,array $baseline,array $candidate,float $tolerance=0.02): array {
    if($baseline['status']!=='completed'||$candidate['status']!=='completed')throw new RuntimeException('Comparison requires completed evaluation runs.');$bi=data_evaluation_run_integrity($pdo,$baseline);$ci=data_evaluation_run_integrity($pdo,$candidate);if(!$bi['ok']||!$ci['ok'])throw new RuntimeException('Comparison requires integrity-valid evaluation runs.');$bf=data_model_benchmark_fingerprint($pdo,$baseline);$cf=data_model_benchmark_fingerprint($pdo,$candidate);if(!hash_equals((string)$bf['hash'],(string)$cf['hash']))throw new RuntimeException('Candidate benchmark is not equivalent to the governed baseline.');
    $base=$baseline['summary']??[];$cur=$candidate['summary']??[];$keys=['automated_pass_rate','expected_citation','grounded_token_ratio','reference_token_f1'];$deltas=[];$regressed=0;foreach($keys as $key){$bv=$key==='automated_pass_rate'?(float)($base[$key]??0):(float)($base['metrics'][$key]??0);$cv=$key==='automated_pass_rate'?(float)($cur[$key]??0):(float)($cur['metrics'][$key]??0);$delta=$cv-$bv;$isRegression=$delta<-$tolerance;if($isRegression)$regressed++;$deltas[$key]=['baseline'=>$bv,'candidate'=>$cv,'delta'=>$delta,'regressed'=>$isRegression];}$baseLatency=(float)($base['metrics']['latency_ms']??0);$candidateLatency=(float)($cur['metrics']['latency_ms']??0);
    return ['benchmark_fingerprint'=>$bf['hash'],'baseline_run_public_id'=>$baseline['public_id'],'candidate_run_public_id'=>$candidate['public_id'],'baseline_run_hash'=>$baseline['run_hash'],'candidate_run_hash'=>$candidate['run_hash'],'regression_tolerance'=>$tolerance,'regressed_metrics'=>$regressed,'deltas'=>$deltas,'latency_ms'=>['baseline'=>$baseLatency,'candidate'=>$candidateLatency,'delta'=>$candidateLatency-$baseLatency],'baseline_human'=>data_evaluation_human_summary($pdo,(int)$baseline['id']),'candidate_human'=>data_evaluation_human_summary($pdo,(int)$candidate['id'])];
}
function data_post_training_link_candidate_evidence(PDO $pdo,array $plan,array $output,array $run): void {
    $q=$pdo->prepare('SELECT COUNT(*) FROM data_model_evaluation_links WHERE version_id=? AND evaluation_run_id=?');$q->execute([$output['id'],$run['id']]);if((int)$q->fetchColumn()>0)return;$viewer=['id'=>(int)$plan['created_by_user_id'],'role'=>'admin'];data_model_link_evaluation($pdo,$viewer,$output['public_id'],$run['public_id'],'Phase 42 post-training readiness plan '.$plan['public_id']);
}
function data_post_training_packet_basis(array $plan,array $job,array $lineage,array $links,array $gate,array $checks): array {
    $suitePackets=[];foreach($links as $l)$suitePackets[]=['template_suite_public_id'=>$l['template_suite_public_id'],'candidate_suite_public_id'=>$l['candidate_suite_public_id'],'baseline_run_public_id'=>$l['baseline_run_public_id'],'candidate_run_public_id'=>$l['candidate_run_public_id'],'benchmark_fingerprint'=>$l['benchmark_fingerprint'],'comparison'=>$l['comparison']];
    return ['schema'=>'annotated.post-training-readiness.v1','plan_public_id'=>$plan['public_id'],'plan_hash'=>$plan['plan_hash'],'training_job_public_id'=>$job['public_id'],'training_completion_hash'=>$job['completion_hash'],'output_model'=>['public_id'=>$lineage['output']['public_id'],'version_label'=>$lineage['output']['version_label'],'version_hash'=>$lineage['output']['version_hash'],'status'=>$lineage['output']['status'],'runtime_model_public_id'=>$lineage['output']['ai_model_public_id']],'baseline_model'=>['public_id'=>$lineage['baseline']['public_id'],'version_label'=>$lineage['baseline']['version_label'],'version_hash'=>$lineage['baseline']['version_hash'],'status'=>$lineage['baseline']['status'],'approval_receipt_hash'=>$plan['baseline_approval_receipt_hash']],'policy'=>$plan['policy'],'policy_hash'=>$plan['policy_hash'],'checks'=>$checks,'phase40_gate'=>['pass'=>$gate['pass'],'policy_hash'=>$gate['policy_hash'],'checks'=>$gate['checks'],'evidence'=>$gate['evidence']],'benchmarks'=>$suitePackets,'readiness_state'=>'ready_for_human_consideration','boundary'=>'This packet does not approve, promote, activate, or route the model.'];
}
function data_post_training_packet_create(PDO $pdo,array $plan,array $packet,?int $actorUserId): array {
    $json=data_attribution_encode($packet);$hash=hash('sha256',$json);$q=$pdo->prepare('SELECT * FROM data_post_training_packets WHERE plan_id=? ORDER BY sequence_number DESC LIMIT 1');$q->execute([$plan['id']]);$latest=$q->fetch();if($latest&&hash_equals((string)$latest['packet_hash'],$hash))return $latest;$q=$pdo->prepare('SELECT COALESCE(MAX(sequence_number),0)+1 FROM data_post_training_packets WHERE plan_id=?');$q->execute([$plan['id']]);$seq=(int)$q->fetchColumn();$public=ulid_like();$pdo->prepare("INSERT INTO data_post_training_packets(public_id,plan_id,sequence_number,readiness_state,packet_json,packet_hash,created_by_user_id) VALUES(?,?,?,'ready_for_human_consideration',?,?,?)")->execute([$public,$plan['id'],$seq,$json,$hash,$actorUserId]);data_post_training_event($pdo,(int)$plan['id'],$actorUserId,'readiness_packet_created',['packet_public_id'=>$public,'packet_hash'=>$hash,'sequence_number'=>$seq]);$q=$pdo->prepare('SELECT * FROM data_post_training_packets WHERE public_id=?');$q->execute([$public]);return $q->fetch()?:[];
}
function data_post_training_set_status(PDO $pdo,array $plan,string $status,?string $error=null,?int $actorUserId=null): array {
    $errorValue=$error?mb_substr($error,0,1500):null;$currentError=$plan['last_error']!==null?(string)$plan['last_error']:null;if((string)$plan['status']===$status&&$currentError===$errorValue)return $plan;
    $blocked=$status==='blocked'?',blocked_at=NOW()':',blocked_at=NULL';$ready=$status==='ready'?',ready_at=COALESCE(ready_at,NOW())':'';$pdo->prepare("UPDATE data_post_training_plans SET status=?,last_error=?,updated_at=NOW()$blocked$ready WHERE id=?")->execute([$status,$errorValue,$plan['id']]);data_post_training_event($pdo,(int)$plan['id'],$actorUserId,'status_changed',['from'=>$plan['status'],'status'=>$status,'error'=>$errorValue]);return data_post_training_plan_get($pdo,$plan['public_id'])??[];
}
function data_post_training_refresh(PDO $pdo,array $viewer,string $planPublicId): array {
    data_post_training_require_admin($viewer);$plan=data_post_training_plan_get($pdo,$planPublicId);if(!$plan)throw new RuntimeException('Post-training evaluation plan not found.');if(in_array($plan['status'],['draft','archived'],true))return $plan;$integrity=data_post_training_plan_integrity($pdo,$plan);if(!$integrity['ok'])return data_post_training_set_status($pdo,$plan,'blocked','Post-training plan integrity failed.',(int)$viewer['id']);$job=data_training_job_get($pdo,$plan['training_job_public_id']);$lineage=$job?data_post_training_lineage($pdo,$job,$plan):['pass'=>false];if(!$job||!$lineage['pass'])return data_post_training_set_status($pdo,$plan,'blocked','Training/model lineage no longer satisfies current governance.',(int)$viewer['id']);if($plan['status']==='ready'&&($lineage['output']['status']??'')!=='experimental')return $plan;
    $links=data_post_training_links($pdo,(int)$plan['id']);$allComplete=true;$hardError=null;$reviewReady=true;$regressionReady=true;$policy=(array)$plan['policy'];$updatedLinks=[];
    foreach($links as $link){$candidate=$link['candidate_run_public_id']?data_evaluation_run_get($pdo,$link['candidate_run_public_id']):null;$baseline=data_evaluation_run_get($pdo,$link['baseline_run_public_id']);if(!$candidate||!$baseline){$hardError='A planned evaluation run is missing.';break;}if(in_array($candidate['status'],['queued','processing'],true)){$allComplete=false;$pdo->prepare("UPDATE data_post_training_suite_links SET status='evaluating',updated_at=NOW() WHERE id=?")->execute([$link['id']]);$updatedLinks[]=$link;continue;}if($candidate['status']==='failed'){$hardError='A candidate evaluation run failed. Requeue it in the Phase 39 Evaluation Harness, then refresh this plan.';break;}if($candidate['status']!=='completed'||!data_evaluation_run_integrity($pdo,$candidate)['ok']){$hardError='A candidate evaluation run is incomplete or failed integrity.';break;}
        try{$comparison=data_post_training_compare_runs($pdo,$baseline,$candidate,(float)$policy['regression_tolerance']);}catch(Throwable $e){$hardError=$e->getMessage();break;}$json=data_attribution_encode($comparison);$hash=hash('sha256',$json);$pdo->prepare("UPDATE data_post_training_suite_links SET status='completed',comparison_json=?,comparison_hash=?,updated_at=NOW() WHERE id=?")->execute([$json,$hash,$link['id']]);data_post_training_link_candidate_evidence($pdo,$plan,$lineage['output'],$candidate);$human=$comparison['candidate_human'];$decided=(int)$human['pass']+(int)$human['fail'];$passRate=$decided>0?(int)$human['pass']/$decided:0.0;if((int)$human['reviews']<(int)$policy['required_human_reviews_per_run']||$passRate<(float)$policy['minimum_human_pass_rate'])$reviewReady=false;if((int)$policy['require_no_regression']&&$comparison['regressed_metrics']>(int)$policy['max_regressed_metrics'])$regressionReady=false;$link['comparison']=$comparison;$updatedLinks[]=$link;
    }
    if($hardError!==null)return data_post_training_set_status($pdo,$plan,'blocked',$hardError,(int)$viewer['id']);if(!$allComplete)return data_post_training_set_status($pdo,$plan,'evaluating',null,(int)$viewer['id']);if(!$reviewReady)return data_post_training_set_status($pdo,$plan,'awaiting_review','Required human review is incomplete or below the configured pass-rate threshold.',(int)$viewer['id']);if(!$regressionReady)return data_post_training_set_status($pdo,$plan,'blocked','One or more equivalent benchmarks exceed the configured regression allowance.',(int)$viewer['id']);
    $gate=data_model_gate_evaluate($pdo,$lineage['output']);if((int)$policy['require_phase40_gate']&&!$gate['pass'])return data_post_training_set_status($pdo,$plan,'blocked','Phase 40 release gates are not yet satisfied by the linked evaluation evidence.',(int)$viewer['id']);$checks=['plan_integrity'=>true,'training_lineage'=>true,'all_runs_completed'=>true,'run_integrity'=>true,'human_review'=>true,'regression_policy'=>true,'phase40_gate'=>!(int)$policy['require_phase40_gate']||$gate['pass']];$links=data_post_training_links($pdo,(int)$plan['id']);$packet=data_post_training_packet_basis($plan,$job,$lineage,$links,$gate,$checks);data_post_training_packet_create($pdo,$plan,$packet,(int)$viewer['id']);return data_post_training_set_status($pdo,$plan,'ready',null,(int)$viewer['id']);
}
function data_post_training_archive(PDO $pdo,array $viewer,string $planPublicId): array {
    data_post_training_require_admin($viewer);$plan=data_post_training_plan_get($pdo,$planPublicId);if(!$plan)throw new RuntimeException('Post-training evaluation plan not found.');if($plan['status']==='archived')return $plan;$pdo->prepare("UPDATE data_post_training_plans SET status='archived',archived_at=NOW(),updated_at=NOW() WHERE id=?")->execute([$plan['id']]);data_post_training_event($pdo,(int)$plan['id'],(int)$viewer['id'],'plan_archived',[]);return data_post_training_plan_get($pdo,$planPublicId)??[];
}
function data_post_training_events(PDO $pdo,int $planId,int $limit=100): array {
    $limit=max(1,min(250,$limit));$q=$pdo->prepare("SELECT e.*,u.display_name actor_name FROM data_post_training_events e LEFT JOIN users u ON u.id=e.actor_user_id WHERE e.plan_id=? ORDER BY e.id DESC LIMIT $limit");$q->execute([$planId]);return $q->fetchAll();
}
function data_post_training_summary(PDO $pdo): array {
    if(!data_post_training_ready($pdo))return ['ready'=>false];$scalar=fn(string $sql)=>(int)$pdo->query($sql)->fetchColumn();return ['ready'=>true,'plans'=>$scalar('SELECT COUNT(*) FROM data_post_training_plans'),'draft'=>$scalar("SELECT COUNT(*) FROM data_post_training_plans WHERE status='draft'"),'evaluating'=>$scalar("SELECT COUNT(*) FROM data_post_training_plans WHERE status='evaluating'"),'awaiting_review'=>$scalar("SELECT COUNT(*) FROM data_post_training_plans WHERE status='awaiting_review'"),'ready_count'=>$scalar("SELECT COUNT(*) FROM data_post_training_plans WHERE status='ready'"),'blocked'=>$scalar("SELECT COUNT(*) FROM data_post_training_plans WHERE status='blocked'"),'packets'=>$scalar('SELECT COUNT(*) FROM data_post_training_packets')];
}
function data_post_training_process_batch(PDO $pdo,int $limit=10): array {
    if(!data_post_training_ready($pdo))throw new RuntimeException('Post-Training Evaluation is unavailable.');$limit=max(1,min(50,$limit));$q=$pdo->query("SELECT public_id,created_by_user_id FROM data_post_training_plans WHERE status IN ('evaluating','awaiting_review') ORDER BY updated_at,id LIMIT $limit");$rows=$q->fetchAll();$out=[];foreach($rows as $row){$viewer=['id'=>(int)$row['created_by_user_id'],'role'=>'admin'];$out[]=data_post_training_refresh($pdo,$viewer,(string)$row['public_id']);}return $out;
}
function data_post_training_process_next(PDO $pdo): ?array {
    if(!data_post_training_ready($pdo))throw new RuntimeException('Post-Training Evaluation is unavailable.');$q=$pdo->query("SELECT public_id,created_by_user_id FROM data_post_training_plans WHERE status IN ('evaluating','awaiting_review') ORDER BY updated_at,id LIMIT 1");$row=$q->fetch();if(!$row)return null;$viewer=['id'=>(int)$row['created_by_user_id'],'role'=>'admin'];return data_post_training_refresh($pdo,$viewer,(string)$row['public_id']);
}
