<?php
declare(strict_types=1);

const ANNOTATED_VP3_CONNECTOR_V100='annotated-vp3-connector-v100-20260923';

function vp3_connector_config(array $config): array {
    $cfg=is_array($config['vp3']??null)?$config['vp3']:[];
    $base=rtrim(trim((string)($cfg['base_url']??getenv('ANNOTATED_VP3_BASE_URL')?:'')),'/');
    $client=(string)($cfg['client_id']??'annotated');$secret=trim((string)($cfg['client_secret']??getenv('ANNOTATED_VP3_CLIENT_SECRET')?:''));
    $callback=trim((string)($cfg['redirect_uri']??''));if($callback==='')$callback=rtrim((string)($config['app']['base_url']??''),'/').'/vp3/callback.php';
    $scheme=strtolower((string)(parse_url($base,PHP_URL_SCHEME)?:''));$host=strtolower((string)(parse_url($base,PHP_URL_HOST)?:''));$secure=$scheme==='https'||($scheme==='http'&&in_array($host,['localhost','127.0.0.1','::1'],true));
    return ['base_url'=>$base,'client_id'=>$client,'client_secret'=>$secret,'redirect_uri'=>$callback,'configured'=>$base!==''&&$secure&&strlen($secret)>=32,'scopes'=>['account.identity.read','meetings.transcripts.read','meetings.intelligence.read']];
}
function vp3_connector_ready(PDO $pdo): bool {try{return installer_table_exists($pdo,'vp3_connections')&&installer_table_exists($pdo,'vp3_imports');}catch(Throwable $e){return false;}}
function vp3_connector_key(array $config): string {$key=(string)($config['app']['encryption_key']??'');if(strlen($key)<32)throw new RuntimeException('Annotated encryption key must be configured before connecting VP3.');return hash('sha256','vp3-connector|'.$key,true);}
function vp3_connector_encrypt(array $config,string $plain): string {
    if($plain==='')return '';$iv=random_bytes(12);$tag='';$cipher=openssl_encrypt($plain,'aes-256-gcm',vp3_connector_key($config),OPENSSL_RAW_DATA,$iv,$tag,'annotated-vp3-v1');if($cipher===false)throw new RuntimeException('Could not encrypt VP3 connection credentials.');
    return 'v1.'.rtrim(strtr(base64_encode($iv),'+/','-_'),'=').'.'.rtrim(strtr(base64_encode($tag),'+/','-_'),'=').'.'.rtrim(strtr(base64_encode($cipher),'+/','-_'),'=');
}
function vp3_connector_b64d(string $v): string {$pad=(4-strlen($v)%4)%4;$raw=base64_decode(strtr($v,'-_','+/').str_repeat('=',$pad),true);if($raw===false)throw new RuntimeException('Stored VP3 credential is invalid.');return $raw;}
function vp3_connector_decrypt(array $config,string $value): string {
    if($value==='')return '';$p=explode('.',$value);if(count($p)!==4||$p[0]!=='v1')throw new RuntimeException('Stored VP3 credential format is invalid.');$plain=openssl_decrypt(vp3_connector_b64d($p[3]),'aes-256-gcm',vp3_connector_key($config),OPENSSL_RAW_DATA,vp3_connector_b64d($p[1]),vp3_connector_b64d($p[2]),'annotated-vp3-v1');if($plain===false)throw new RuntimeException('Stored VP3 credential could not be decrypted.');return $plain;
}
function vp3_connector_connection(PDO $pdo,int $userId,bool $includeDisconnected=false): ?array {
    if($userId<1||!vp3_connector_ready($pdo))return null;$sql='SELECT * FROM vp3_connections WHERE user_id=?'.($includeDisconnected?'':" AND status='active'").' LIMIT 1';$q=$pdo->prepare($sql);$q->execute([$userId]);$row=$q->fetch();if(!$row)return null;$row['scopes']=json_decode((string)$row['scopes_json'],true)?:[];return $row;
}
function vp3_connector_http(array $config,string $method,string $url,array $headers=[],array $form=[]): array {
    $cfg=vp3_connector_config($config);if(empty($cfg['configured']))throw new RuntimeException('VP3 connection is not configured on this Annotated server.');
    if(!str_starts_with($url,$cfg['base_url'].'/'))throw new RuntimeException('VP3 connector refused an unexpected destination.');
    $ch=curl_init($url);if($ch===false)throw new RuntimeException('VP3 connection could not start.');$baseHeaders=['Accept: application/json'];
    $options=[CURLOPT_RETURNTRANSFER=>true,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_CONNECTTIMEOUT=>5,CURLOPT_TIMEOUT=>20,CURLOPT_SSL_VERIFYPEER=>true,CURLOPT_SSL_VERIFYHOST=>2,CURLOPT_HTTPHEADER=>array_merge($baseHeaders,$headers)];
    if(strtoupper($method)==='POST'){$options[CURLOPT_POST]=true;$options[CURLOPT_POSTFIELDS]=http_build_query($form);$options[CURLOPT_HTTPHEADER][]= 'Content-Type: application/x-www-form-urlencoded';}
    curl_setopt_array($ch,$options);$raw=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);$err=curl_error($ch);curl_close($ch);if(!is_string($raw))throw new RuntimeException('VP3 connection failed'.($err!==''?': '.$err:'.'));
    try{$json=json_decode($raw,true,64,JSON_THROW_ON_ERROR);}catch(Throwable $e){throw new RuntimeException('VP3 returned an invalid response.');}return ['status'=>$status,'data'=>$json];
}
function vp3_connector_token_exchange(array $config,array $form): array {
    $cfg=vp3_connector_config($config);$form=['client_id'=>$cfg['client_id'],'client_secret'=>$cfg['client_secret']]+$form;$r=vp3_connector_http($config,'POST',$cfg['base_url'].'/api/connected-site-token.php',[],$form);if($r['status']!==200||empty($r['data']['access_token']))throw new RuntimeException((string)($r['data']['error_description']??'VP3 authorization could not be completed.'));return $r['data'];
}
function vp3_connector_begin(array $config,string $mode,int $userId=0): string {
    $cfg=vp3_connector_config($config);if(empty($cfg['configured']))throw new RuntimeException('VP3 connection has not been configured by the Annotated administrator.');$mode=$mode==='login'?'login':'connect';if($mode==='connect'&&$userId<1)throw new RuntimeException('Sign in to Annotated before connecting VP3.');
    $state=bin2hex(random_bytes(24));$_SESSION['vp3_oauth_state']=['state'=>$state,'mode'=>$mode,'user_id'=>$userId,'created_at'=>time()];$q=['client_id'=>$cfg['client_id'],'redirect_uri'=>$cfg['redirect_uri'],'state'=>$state,'scope'=>implode(' ',$cfg['scopes']),'mode'=>$mode];return $cfg['base_url'].'/connected-site-authorize.php?'.http_build_query($q);
}
function vp3_connector_unique_username(PDO $pdo,string $remoteId,string $display): string {
    $base=strtolower(trim($display));$base=preg_replace('/[^a-z0-9._-]+/','-',$base)??'';$base=trim($base,'-._');if($base==='')$base='vp3-'.$remoteId;$base=substr($base,0,42);$q=$pdo->prepare('SELECT 1 FROM users WHERE username=? LIMIT 1');$candidate=$base;$n=1;while(true){$q->execute([$candidate]);if(!$q->fetchColumn())return $candidate;$n++;$candidate=substr($base,0,max(4,46-strlen((string)$n))).'-'.$n;}}
function vp3_connector_attach(PDO $pdo,array $config,int $userId,array $identity,array $tokens): array {
    if(!vp3_connector_ready($pdo))throw new RuntimeException('VP3 connections require the latest database upgrade.');$remote=(string)($identity['id']??'');if($remote==='')throw new RuntimeException('VP3 did not return an account identity.');
    $q=$pdo->prepare('SELECT user_id FROM vp3_connections WHERE vp3_user_id=? LIMIT 1');$q->execute([$remote]);$other=(int)($q->fetchColumn()?:0);if($other&&$other!==$userId)throw new RuntimeException('This VP3 account is already connected to another Annotated account.');
    $scopes=preg_split('/s+/',trim((string)($tokens['scope']??'')))?:[];$accessExp=gmdate('Y-m-d H:i:s',time()+max(60,(int)($tokens['expires_in']??3600)));$refreshExp=gmdate('Y-m-d H:i:s',time()+max(3600,(int)($tokens['refresh_expires_in']??7776000)));
    $pdo->prepare("INSERT INTO vp3_connections(user_id,vp3_user_id,vp3_display_name,vp3_email,status,scopes_json,access_token_cipher,refresh_token_cipher,access_expires_at,refresh_expires_at,connected_at,last_checked_at) VALUES(?,?,?,?, 'active',?,?,?,?,?,NOW(),NOW()) ON DUPLICATE KEY UPDATE vp3_user_id=VALUES(vp3_user_id),vp3_display_name=VALUES(vp3_display_name),vp3_email=VALUES(vp3_email),status='active',scopes_json=VALUES(scopes_json),access_token_cipher=VALUES(access_token_cipher),refresh_token_cipher=VALUES(refresh_token_cipher),access_expires_at=VALUES(access_expires_at),refresh_expires_at=VALUES(refresh_expires_at),disconnected_at=NULL,last_checked_at=NOW(),updated_at=NOW()")
      ->execute([$userId,$remote,mb_substr((string)($identity['display_name']??''),0,190),filter_var((string)($identity['email']??''),FILTER_VALIDATE_EMAIL)?strtolower((string)$identity['email']):null,json_encode($scopes),vp3_connector_encrypt($config,(string)$tokens['access_token']),vp3_connector_encrypt($config,(string)$tokens['refresh_token']),$accessExp,$refreshExp]);
    return vp3_connector_connection($pdo,$userId,true)??[];
}
function vp3_connector_identity_from_token(array $config,string $access): array {
    $cfg=vp3_connector_config($config);$r=vp3_connector_http($config,'GET',$cfg['base_url'].'/api/connected-site-me.php',['Authorization: Bearer '.$access]);if($r['status']!==200||empty($r['data']['ok']))throw new RuntimeException('VP3 account identity could not be read.');return $r['data']['data'];
}
function vp3_connector_callback(PDO $pdo,array $config,string $code,string $state,?array $viewer): array {
    $stored=is_array($_SESSION['vp3_oauth_state']??null)?$_SESSION['vp3_oauth_state']:[];unset($_SESSION['vp3_oauth_state']);if(empty($stored)||!hash_equals((string)($stored['state']??''),$state)||(int)($stored['created_at']??0)<time()-600)throw new RuntimeException('VP3 connection state expired. Start the connection again.');
    $cfg=vp3_connector_config($config);$tokens=vp3_connector_token_exchange($config,['grant_type'=>'authorization_code','code'=>$code,'redirect_uri'=>$cfg['redirect_uri']]);$identity=vp3_connector_identity_from_token($config,(string)$tokens['access_token']);$mode=(string)$stored['mode'];
    if($mode==='connect'){$uid=(int)($viewer['id']??0);if($uid<1||$uid!==(int)$stored['user_id'])throw new RuntimeException('Sign in to the same Annotated account that started this VP3 connection.');vp3_connector_attach($pdo,$config,$uid,$identity,$tokens);return ['user_id'=>$uid,'mode'=>'connect'];}
    $remote=(string)$identity['id'];$q=$pdo->prepare("SELECT u.id FROM vp3_connections c JOIN users u ON u.id=c.user_id WHERE c.vp3_user_id=? AND c.status='active' AND u.status='active' LIMIT 1");$q->execute([$remote]);$uid=(int)($q->fetchColumn()?:0);
    if(!$uid){$email=filter_var((string)($identity['email']??''),FILTER_VALIDATE_EMAIL)?strtolower((string)$identity['email']):null;if($email!==null){$q=$pdo->prepare('SELECT id FROM users WHERE email=? AND status="active" LIMIT 1');$q->execute([$email]);if($q->fetchColumn())throw new RuntimeException('An Annotated account already uses this email. Sign in to Annotated first, then choose Connect VP3 Account in Settings.');}
        $display=mb_substr(trim((string)($identity['display_name']??'VP3 User')),0,100);$username=vp3_connector_unique_username($pdo,$remote,$display);$pdo->prepare("INSERT INTO users(public_id,username,display_name,email,password_hash,role,status,live_presence_mode) VALUES(?,?,?,?,NULL,'user','active','cloaked')")->execute([ulid_like(),$username,$display,$email]);$uid=(int)$pdo->lastInsertId();$pdo->prepare('INSERT IGNORE INTO user_preferences(user_id) VALUES(?)')->execute([$uid]);}
    vp3_connector_attach($pdo,$config,$uid,$identity,$tokens);return ['user_id'=>$uid,'mode'=>'login'];
}
function vp3_connector_refresh(PDO $pdo,array $config,array $connection): array {
    $refresh=vp3_connector_decrypt($config,(string)$connection['refresh_token_cipher']);if($refresh==='')throw new RuntimeException('VP3 refresh credential is unavailable.');$tokens=vp3_connector_token_exchange($config,['grant_type'=>'refresh_token','refresh_token'=>$refresh]);$identity=['id'=>$connection['vp3_user_id'],'display_name'=>$connection['vp3_display_name'],'email'=>$connection['vp3_email']];return vp3_connector_attach($pdo,$config,(int)$connection['user_id'],$identity,$tokens);
}
function vp3_connector_access_token(PDO $pdo,array $config,int $userId): string {
    $c=vp3_connector_connection($pdo,$userId);if(!$c)throw new RuntimeException('Connect your VP3 account first.');$exp=strtotime((string)$c['access_expires_at'])?:0;if($exp<=time()+60)$c=vp3_connector_refresh($pdo,$config,$c);$token=vp3_connector_decrypt($config,(string)$c['access_token_cipher']);if($token==='')throw new RuntimeException('VP3 access credential is unavailable.');return $token;
}
function vp3_connector_api(PDO $pdo,array $config,int $userId,string $path): array {
    $cfg=vp3_connector_config($config);$token=vp3_connector_access_token($pdo,$config,$userId);$r=vp3_connector_http($config,'GET',$cfg['base_url'].$path,['Authorization: Bearer '.$token]);if($r['status']===401){$c=vp3_connector_connection($pdo,$userId);if($c){$c=vp3_connector_refresh($pdo,$config,$c);$token=vp3_connector_decrypt($config,(string)$c['access_token_cipher']);$r=vp3_connector_http($config,'GET',$cfg['base_url'].$path,['Authorization: Bearer '.$token]);}}
    if($r['status']!==200||empty($r['data']['ok']))throw new RuntimeException((string)($r['data']['error']??'VP3 data is currently unavailable.'));$pdo->prepare('UPDATE vp3_connections SET last_used_at=NOW(),last_checked_at=NOW() WHERE user_id=?')->execute([$userId]);return $r['data']['data'];
}
function vp3_connector_disconnect(PDO $pdo,array $config,int $userId): void {
    $c=vp3_connector_connection($pdo,$userId,true);if(!$c)return;if($c['status']==='active')try{$cfg=vp3_connector_config($config);$token=vp3_connector_decrypt($config,(string)$c['access_token_cipher']);if($token!=='')vp3_connector_http($config,'POST',$cfg['base_url'].'/api/connected-site-revoke.php',['Authorization: Bearer '.$token],[]);}catch(Throwable $e){}
    $pdo->prepare("UPDATE vp3_connections SET status='disconnected',access_token_cipher=NULL,refresh_token_cipher=NULL,access_expires_at=NULL,refresh_expires_at=NULL,disconnected_at=NOW(),updated_at=NOW() WHERE user_id=?")->execute([$userId]);
}
function vp3_connector_artifacts(PDO $pdo,array $config,array $viewer): array {return (array)(vp3_connector_api($pdo,$config,(int)$viewer['id'],'/api/connected-site-artifacts.php')['artifacts']??[]);}
function vp3_connector_artifact(PDO $pdo,array $config,array $viewer,string $remoteId): array {return vp3_connector_api($pdo,$config,(int)$viewer['id'],'/api/connected-site-artifacts.php?id='.rawurlencode($remoteId));}
function vp3_connector_absolute_source_url(array $config,string $url): string {$url=trim($url);if($url!==''&&str_starts_with($url,'/'))return rtrim((string)vp3_connector_config($config)['base_url'],'/').$url;return $url;}
function vp3_connector_summary_html(array $s): string {
    $h=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');$html='<h1>VP3 AI Summary</h1><p>'.$h($s['summary']??'').'</p>';$sections=['key_points'=>'Key points','decisions'=>'Decisions','actions'=>'Actions','questions'=>'Open questions','risks'=>'Risks & blockers','topics'=>'Topics'];foreach($sections as $key=>$label){$rows=(array)($s[$key]??[]);if(!$rows)continue;$html.='<h2>'.$h($label).'</h2><ul>';foreach(array_slice($rows,0,30) as $row){$text=is_array($row)?($row['summary']??$row['text']??$row['title']??$row['decision']??$row['action']??json_encode($row,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)):$row;$html.='<li>'.$h($text).'</li>';}$html.='</ul>';}return $html;
}
function vp3_connector_object_public(PDO $pdo,?int $id): string {if(!$id)return '';$q=$pdo->prepare('SELECT public_id FROM research_workspace_objects WHERE id=? LIMIT 1');$q->execute([$id]);return (string)($q->fetchColumn()?:'');}
function vp3_connector_import_row(PDO $pdo,int $projectId,string $remoteId): ?array {$q=$pdo->prepare("SELECT * FROM vp3_imports WHERE project_id=? AND remote_artifact_type='meeting' AND remote_artifact_id=? LIMIT 1");$q->execute([$projectId,$remoteId]);return $q->fetch()?:null;}
function vp3_connector_import(PDO $pdo,array $config,array $viewer,string $agentPublic,string $remoteId,array $parts): array {
    $agent=research_agent_access($pdo,$viewer,$agentPublic);if(!$agent)throw new RuntimeException('Research Agent is unavailable.');$project=research_agent_workspace_project($pdo,$viewer,$agentPublic);if(!$project)throw new RuntimeException('Research Agent workspace is unavailable.');research_agent_workspace_require_write($project);
    $parts=array_values(array_intersect(['transcript','summary'],$parts));if(!$parts)throw new InvalidArgumentException('Choose the transcript, AI summary, or both.');
    $remote=vp3_connector_artifact($pdo,$config,$viewer,$remoteId);$artifact=(array)($remote['artifact']??[]);if(($artifact['id']??'')!==$remoteId)throw new RuntimeException('VP3 artifact identity did not match the requested item.');$version=(string)($artifact['version_hash']??'');if(!preg_match('/^[a-f0-9]{64}$/',$version))throw new RuntimeException('VP3 artifact version is invalid.');
    $url=vp3_connector_absolute_source_url($config,(string)($artifact['original_url']??''));if(!filter_var($url,FILTER_VALIDATE_URL))throw new RuntimeException('VP3 artifact source URL is invalid.');$title=mb_substr((string)($artifact['title']??'VP3 Meeting'),0,500);$transcript=(array)($remote['transcript']??[]);$summary=is_array($remote['ai_summary']??null)?$remote['ai_summary']:null;
    if(in_array('transcript',$parts,true)&&trim((string)($transcript['text']??''))==='')throw new RuntimeException('This VP3 meeting does not have a transcript yet.');if(in_array('summary',$parts,true)&&!$summary)throw new RuntimeException('This VP3 meeting does not have an AI summary available to your account.');
    $source=ensure_source($pdo,$url,$title);$q=$pdo->prepare('SELECT id,version_number,content_hash FROM source_versions WHERE source_id=? ORDER BY version_number DESC LIMIT 1');$q->execute([(int)$source['id']]);$latest=$q->fetch();$sourceVersionId=0;
    if($latest&&hash_equals((string)($latest['content_hash']??''),$version))$sourceVersionId=(int)$latest['id'];else{$next=(int)($latest['version_number']??0)+1;$extracted=trim((string)($transcript['text']??'')).($summary?"\n\nVP3 AI Summary\n".(string)($summary['summary']??''):'');$metadata=['origin'=>'vp3','remote_artifact_type'=>'meeting','remote_artifact_id'=>$remoteId,'remote_version_hash'=>$version,'remote_updated_at'=>$artifact['updated_at']??null,'summary_source_hash'=>$summary['source_hash']??null];$pdo->prepare('INSERT INTO source_versions(source_id,version_number,final_url,title,extracted_text,content_hash,metadata_json) VALUES(?,?,?,?,?,?,?)')->execute([(int)$source['id'],$next,$url,$title,$extracted!==''?$extracted:null,$version,json_encode($metadata,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)]);$sourceVersionId=(int)$pdo->lastInsertId();$pdo->prepare("UPDATE sources SET current_version_id=?,title=?,status='current',last_checked_at=NOW() WHERE id=?")->execute([$sourceVersionId,$title,(int)$source['id']]);}
    $pdo->prepare('INSERT IGNORE INTO project_sources(project_id,source_id,added_by_user_id) VALUES(?,?,?)')->execute([(int)$project['id'],(int)$source['id'],(int)$viewer['id']]);$existing=vp3_connector_import_row($pdo,(int)$project['id'],$remoteId);
    $transcriptObjectId=(int)($existing['transcript_document_object_id']??0);$summaryObjectId=(int)($existing['summary_document_object_id']??0);
    if(in_array('transcript',$parts,true)){$body=(string)$transcript['text'];$public=vp3_connector_object_public($pdo,$transcriptObjectId);if($public!==''){$obj=research_agent_workspace_object($pdo,$viewer,$public,false);research_agent_workspace_save_document($pdo,$viewer,$public,['title'=>$title.' — VP3 Transcript','body'=>$body,'summary'=>'Imported VP3 transcript · source version '.$version,'base_revision'=>(int)($obj['revision_number']??0)]);}else{$doc=research_agent_workspace_create_document($pdo,$viewer,$project,['title'=>$title.' — VP3 Transcript','body'=>$body,'summary'=>'Imported from VP3 with immutable source provenance.','document_type'=>'document'],false);$transcriptObjectId=(int)$doc['id'];}
        $pdo->prepare("UPDATE research_workspace_objects SET metadata_json=? WHERE id=?")->execute([json_encode(['origin'=>'vp3','artifact_type'=>'meeting_transcript','remote_artifact_id'=>$remoteId,'remote_version_hash'=>$version,'source_public_id'=>$source['public_id'],'source_version_id'=>$sourceVersionId,'original_url'=>$url],JSON_UNESCAPED_SLASHES),$transcriptObjectId]);}
    if(in_array('summary',$parts,true)){$html=vp3_connector_summary_html($summary);$public=vp3_connector_object_public($pdo,$summaryObjectId);if($public!==''){$obj=research_agent_workspace_object($pdo,$viewer,$public,false);research_agent_workspace_save_document($pdo,$viewer,$public,['title'=>$title.' — VP3 AI Summary','content_html'=>$html,'summary'=>mb_substr((string)($summary['summary']??''),0,5000),'base_revision'=>(int)($obj['revision_number']??0)]);}else{$doc=research_agent_workspace_create_document($pdo,$viewer,$project,['title'=>$title.' — VP3 AI Summary','content_html'=>$html,'summary'=>mb_substr((string)($summary['summary']??''),0,5000),'document_type'=>'source_summary'],false);$summaryObjectId=(int)$doc['id'];}
        $pdo->prepare("UPDATE research_workspace_objects SET metadata_json=? WHERE id=?")->execute([json_encode(['origin'=>'vp3','artifact_type'=>'meeting_ai_summary','remote_artifact_id'=>$remoteId,'remote_version_hash'=>$version,'source_public_id'=>$source['public_id'],'source_version_id'=>$sourceVersionId,'original_url'=>$url,'ai_generated'=>true],JSON_UNESCAPED_SLASHES),$summaryObjectId]);}
    $partsJson=json_encode($parts);$remoteUpdated=trim((string)($artifact['updated_at']??''))?:null;
    $pdo->prepare("INSERT INTO vp3_imports(public_id,user_id,project_id,remote_artifact_type,remote_artifact_id,remote_version_hash,remote_updated_at,original_url,title,source_id,source_version_id,transcript_document_object_id,summary_document_object_id,imported_parts_json,status,imported_at,last_checked_at) VALUES(?,?,?,'meeting',?,?,?,?,?,?,?,?,?,?,'current',NOW(),NOW()) ON DUPLICATE KEY UPDATE user_id=VALUES(user_id),remote_version_hash=VALUES(remote_version_hash),remote_updated_at=VALUES(remote_updated_at),original_url=VALUES(original_url),title=VALUES(title),source_id=VALUES(source_id),source_version_id=VALUES(source_version_id),transcript_document_object_id=COALESCE(VALUES(transcript_document_object_id),transcript_document_object_id),summary_document_object_id=COALESCE(VALUES(summary_document_object_id),summary_document_object_id),imported_parts_json=VALUES(imported_parts_json),status='current',imported_at=NOW(),last_checked_at=NOW(),updated_at=NOW()")
      ->execute([ulid_like(),(int)$viewer['id'],(int)$project['id'],$remoteId,$version,$remoteUpdated,$url,$title,(int)$source['id'],$sourceVersionId,$transcriptObjectId?:null,$summaryObjectId?:null,$partsJson]);
    return vp3_connector_import_row($pdo,(int)$project['id'],$remoteId)??[];
}
function vp3_connector_imports_for_user(PDO $pdo,array $viewer): array {
    if(!vp3_connector_ready($pdo))return [];$q=$pdo->prepare("SELECT i.*,rp.public_id project_public_id,rp.title project_title,ra.public_id agent_public_id,ra.name agent_name,s.public_id source_public_id FROM vp3_imports i JOIN research_projects rp ON rp.id=i.project_id LEFT JOIN research_agents ra ON ra.project_id=rp.id LEFT JOIN sources s ON s.id=i.source_id LEFT JOIN team_members tm ON tm.team_id=rp.team_id AND tm.user_id=? WHERE i.user_id=? AND (rp.owner_user_id=? OR tm.user_id=?) ORDER BY i.updated_at DESC LIMIT 200");$q->execute([(int)$viewer['id'],(int)$viewer['id'],(int)$viewer['id'],(int)$viewer['id']]);$rows=$q->fetchAll()?:[];foreach($rows as &$row)$row['parts']=json_decode((string)$row['imported_parts_json'],true)?:[];unset($row);return $rows;
}
