-- Annotated Phase 41 — Training Job Registry & Controlled Fine-Tuning
-- Controlled training over frozen Phase 38 training datasets and governed Phase 40 base models.
-- Training outputs return to Phase 40 as EXPERIMENTAL versions; no automatic approval or activation.

CREATE TABLE IF NOT EXISTS data_training_jobs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(40) NOT NULL UNIQUE,
  dataset_id BIGINT UNSIGNED NOT NULL,
  base_model_version_id BIGINT UNSIGNED NOT NULL,
  output_registry_id BIGINT UNSIGNED NOT NULL,
  executor_type VARCHAR(32) NOT NULL DEFAULT 'provider_api',
  method VARCHAR(32) NOT NULL DEFAULT 'supervised',
  training_format VARCHAR(32) NOT NULL DEFAULT 'chat_messages',
  status VARCHAR(32) NOT NULL DEFAULT 'draft',
  output_version_label VARCHAR(120) NOT NULL,
  description TEXT NULL,
  config_json JSON NOT NULL,
  config_hash CHAR(64) NOT NULL,
  dataset_manifest_hash CHAR(64) NULL,
  base_model_version_hash CHAR(64) NULL,
  rights_snapshot_json JSON NULL,
  rights_snapshot_hash CHAR(64) NULL,
  provider_id BIGINT UNSIGNED NULL,
  provider_snapshot_json JSON NULL,
  provider_snapshot_hash CHAR(64) NULL,
  package_hash CHAR(64) NULL,
  package_bytes BIGINT UNSIGNED NULL,
  example_count INT UNSIGNED NULL,
  invalid_example_count INT UNSIGNED NULL,
  job_hash CHAR(64) NULL,
  provider_file_id VARCHAR(255) NULL,
  provider_job_id VARCHAR(255) NULL,
  provider_status VARCHAR(64) NULL,
  result_files_json JSON NULL,
  trained_tokens BIGINT UNSIGNED NULL,
  cost_rate_usd_per_million_tokens DECIMAL(14,6) NULL,
  estimated_cost_usd DECIMAL(14,6) NULL,
  actual_cost_usd DECIMAL(14,6) NULL,
  output_model_name VARCHAR(255) NULL,
  output_artifact_ref VARCHAR(1000) NULL,
  output_artifact_hash CHAR(64) NULL,
  output_model_version_id BIGINT UNSIGNED NULL,
  completion_hash CHAR(64) NULL,
  attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
  max_attempts INT UNSIGNED NOT NULL DEFAULT 3,
  last_error VARCHAR(1500) NULL,
  created_by_user_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  queued_at DATETIME NULL,
  prepared_at DATETIME NULL,
  submitted_at DATETIME NULL,
  started_at DATETIME NULL,
  completed_at DATETIME NULL,
  cancelled_at DATETIME NULL,
  blocked_at DATETIME NULL,
  cancel_requested_at DATETIME NULL,
  INDEX idx_data_training_job_status(status,created_at),
  INDEX idx_data_training_job_dataset(dataset_id,status),
  INDEX idx_data_training_job_base(base_model_version_id,status),
  INDEX idx_data_training_job_provider(provider_id,provider_job_id),
  CONSTRAINT fk_data_training_job_dataset FOREIGN KEY(dataset_id) REFERENCES data_datasets(id) ON DELETE RESTRICT,
  CONSTRAINT fk_data_training_job_base FOREIGN KEY(base_model_version_id) REFERENCES data_model_versions(id) ON DELETE RESTRICT,
  CONSTRAINT fk_data_training_job_registry FOREIGN KEY(output_registry_id) REFERENCES data_model_registry(id) ON DELETE RESTRICT,
  CONSTRAINT fk_data_training_job_provider FOREIGN KEY(provider_id) REFERENCES ai_providers(id) ON DELETE SET NULL,
  CONSTRAINT fk_data_training_job_output FOREIGN KEY(output_model_version_id) REFERENCES data_model_versions(id) ON DELETE SET NULL,
  CONSTRAINT fk_data_training_job_creator FOREIGN KEY(created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS data_training_attempts (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  job_id BIGINT UNSIGNED NOT NULL,
  attempt_number INT UNSIGNED NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'preparing',
  provider_file_id VARCHAR(255) NULL,
  provider_job_id VARCHAR(255) NULL,
  request_hash CHAR(64) NULL,
  response_hash CHAR(64) NULL,
  error_text VARCHAR(1500) NULL,
  started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  submitted_at DATETIME NULL,
  completed_at DATETIME NULL,
  UNIQUE KEY uq_data_training_attempt(job_id,attempt_number),
  INDEX idx_data_training_attempt_status(status,started_at),
  CONSTRAINT fk_data_training_attempt_job FOREIGN KEY(job_id) REFERENCES data_training_jobs(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS data_training_logs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  job_id BIGINT UNSIGNED NOT NULL,
  attempt_id BIGINT UNSIGNED NULL,
  source VARCHAR(32) NOT NULL DEFAULT 'annotated',
  provider_event_id VARCHAR(255) NULL,
  level VARCHAR(24) NOT NULL DEFAULT 'info',
  event_type VARCHAR(64) NULL,
  message VARCHAR(2000) NOT NULL,
  metadata_json JSON NULL,
  log_hash CHAR(64) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_data_training_provider_event(job_id,provider_event_id),
  INDEX idx_data_training_log_job(job_id,created_at),
  CONSTRAINT fk_data_training_log_job FOREIGN KEY(job_id) REFERENCES data_training_jobs(id) ON DELETE CASCADE,
  CONSTRAINT fk_data_training_log_attempt FOREIGN KEY(attempt_id) REFERENCES data_training_attempts(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS data_training_events (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  job_id BIGINT UNSIGNED NOT NULL,
  actor_user_id BIGINT UNSIGNED NULL,
  event_type VARCHAR(48) NOT NULL,
  details_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_data_training_event_job(job_id,created_at),
  CONSTRAINT fk_data_training_event_job FOREIGN KEY(job_id) REFERENCES data_training_jobs(id) ON DELETE CASCADE,
  CONSTRAINT fk_data_training_event_actor FOREIGN KEY(actor_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
