-- Expand the existing source-history lifecycle so a previously unavailable source can be recorded as restored.
ALTER TABLE source_change_events
  MODIFY COLUMN change_type ENUM('updated','edited','moved','unavailable','restored') NOT NULL;

-- Annotated Phase 56 — Continuous Research Monitoring & External Research Intelligence

CREATE TABLE IF NOT EXISTS research_monitor_watches (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(40) NOT NULL UNIQUE,
  research_agent_id BIGINT UNSIGNED NOT NULL,
  project_id BIGINT UNSIGNED NOT NULL,
  created_by_user_id BIGINT UNSIGNED NOT NULL,
  watch_type ENUM('url','domain','topic','entity','claim','query') NOT NULL,
  target VARCHAR(1000) NOT NULL,
  canonical_url VARCHAR(1000) NULL,
  query_text VARCHAR(1000) NULL,
  watch_key CHAR(64) NOT NULL,
  cadence ENUM('hourly','daily','weekly','manual') NOT NULL DEFAULT 'daily',
  alert_level ENUM('all','important') NOT NULL DEFAULT 'important',
  auto_promote TINYINT(1) NOT NULL DEFAULT 0,
  status ENUM('active','paused','archived') NOT NULL DEFAULT 'active',
  last_checked_at DATETIME NULL,
  last_source_change_event_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  next_check_at DATETIME NULL,
  last_result_hash CHAR(64) NULL,
  last_error VARCHAR(1000) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_research_monitor_watch_agent_key(research_agent_id,watch_key),
  INDEX idx_research_monitor_watch_due(status,next_check_at),
  INDEX idx_research_monitor_watch_project(project_id,status,updated_at),
  CONSTRAINT fk_research_monitor_watch_agent FOREIGN KEY(research_agent_id) REFERENCES research_agents(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_monitor_watch_project FOREIGN KEY(project_id) REFERENCES research_projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_monitor_watch_user FOREIGN KEY(created_by_user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS research_monitor_jobs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  watch_id BIGINT UNSIGNED NOT NULL UNIQUE,
  research_agent_id BIGINT UNSIGNED NOT NULL,
  project_id BIGINT UNSIGNED NOT NULL,
  requested_by_user_id BIGINT UNSIGNED NULL,
  trigger_type ENUM('schedule','manual','source_change','recovery') NOT NULL DEFAULT 'schedule',
  status ENUM('queued','processing','done','failed') NOT NULL DEFAULT 'queued',
  attempts INT UNSIGNED NOT NULL DEFAULT 0,
  claim_token CHAR(32) NULL,
  lease_expires_at DATETIME NULL,
  available_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_error VARCHAR(1000) NULL,
  rerun_requested TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  started_at DATETIME NULL,
  completed_at DATETIME NULL,
  INDEX idx_research_monitor_job_claim(status,available_at,lease_expires_at,created_at),
  INDEX idx_research_monitor_job_project(project_id,status),
  CONSTRAINT fk_research_monitor_job_watch FOREIGN KEY(watch_id) REFERENCES research_monitor_watches(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_monitor_job_agent FOREIGN KEY(research_agent_id) REFERENCES research_agents(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_monitor_job_project FOREIGN KEY(project_id) REFERENCES research_projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_monitor_job_user FOREIGN KEY(requested_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS research_monitor_runs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(40) NOT NULL UNIQUE,
  watch_id BIGINT UNSIGNED NOT NULL,
  research_agent_id BIGINT UNSIGNED NOT NULL,
  project_id BIGINT UNSIGNED NOT NULL,
  trigger_type ENUM('schedule','manual','source_change','recovery') NOT NULL,
  status ENUM('processing','completed','failed','skipped') NOT NULL DEFAULT 'processing',
  discovered_count INT UNSIGNED NOT NULL DEFAULT 0,
  promoted_count INT UNSIGNED NOT NULL DEFAULT 0,
  event_count INT UNSIGNED NOT NULL DEFAULT 0,
  input_hash CHAR(64) NULL,
  output_hash CHAR(64) NULL,
  summary TEXT NULL,
  started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at DATETIME NULL,
  last_error VARCHAR(1000) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_research_monitor_run_watch(watch_id,created_at),
  INDEX idx_research_monitor_run_project(project_id,created_at),
  CONSTRAINT fk_research_monitor_run_watch FOREIGN KEY(watch_id) REFERENCES research_monitor_watches(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_monitor_run_agent FOREIGN KEY(research_agent_id) REFERENCES research_agents(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_monitor_run_project FOREIGN KEY(project_id) REFERENCES research_projects(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS research_monitor_candidates (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(40) NOT NULL UNIQUE,
  watch_id BIGINT UNSIGNED NOT NULL,
  project_id BIGINT UNSIGNED NOT NULL,
  canonical_url VARCHAR(1000) NOT NULL,
  canonical_url_hash CHAR(64) NOT NULL,
  title VARCHAR(500) NULL,
  domain VARCHAR(255) NULL,
  excerpt TEXT NULL,
  published_at DATETIME NULL,
  relevance_score DECIMAL(5,2) NOT NULL DEFAULT 0,
  relevance_reason VARCHAR(500) NULL,
  payload_hash CHAR(64) NOT NULL,
  status ENUM('candidate','promoted','ignored') NOT NULL DEFAULT 'candidate',
  source_id BIGINT UNSIGNED NULL,
  discovered_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  promoted_at DATETIME NULL,
  UNIQUE KEY uq_research_monitor_candidate_watch_url(watch_id,canonical_url_hash),
  INDEX idx_research_monitor_candidate_project(project_id,status,last_seen_at),
  INDEX idx_research_monitor_candidate_source(source_id),
  CONSTRAINT fk_research_monitor_candidate_watch FOREIGN KEY(watch_id) REFERENCES research_monitor_watches(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_monitor_candidate_project FOREIGN KEY(project_id) REFERENCES research_projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_monitor_candidate_source FOREIGN KEY(source_id) REFERENCES sources(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS research_monitor_events (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(40) NOT NULL UNIQUE,
  watch_id BIGINT UNSIGNED NOT NULL,
  project_id BIGINT UNSIGNED NOT NULL,
  event_key CHAR(64) NOT NULL,
  event_type ENUM('candidate_discovered','new_source','source_changed','source_unavailable','source_restored','claim_supported','claim_weakened','claim_contradicted','claim_resolved','monitor_error') NOT NULL,
  source_id BIGINT UNSIGNED NULL,
  source_change_event_id BIGINT UNSIGNED NULL,
  claim_id BIGINT UNSIGNED NULL,
  importance ENUM('info','important','high') NOT NULL DEFAULT 'important',
  summary TEXT NOT NULL,
  payload_json JSON NULL,
  occurred_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  notified_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_research_monitor_event_key(watch_id,event_key),
  INDEX idx_research_monitor_event_project(project_id,occurred_at),
  INDEX idx_research_monitor_event_watch(watch_id,occurred_at),
  CONSTRAINT fk_research_monitor_event_watch FOREIGN KEY(watch_id) REFERENCES research_monitor_watches(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_monitor_event_project FOREIGN KEY(project_id) REFERENCES research_projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_monitor_event_source FOREIGN KEY(source_id) REFERENCES sources(id) ON DELETE SET NULL,
  CONSTRAINT fk_research_monitor_event_source_change FOREIGN KEY(source_change_event_id) REFERENCES source_change_events(id) ON DELETE SET NULL,
  CONSTRAINT fk_research_monitor_event_claim FOREIGN KEY(claim_id) REFERENCES research_claims(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS research_monitor_claim_states (
  watch_id BIGINT UNSIGNED NOT NULL,
  claim_id BIGINT UNSIGNED NOT NULL,
  assessment ENUM('unresolved','supported','weakened','contradicted','resolved') NOT NULL DEFAULT 'unresolved',
  supports_count INT UNSIGNED NOT NULL DEFAULT 0,
  contradicts_count INT UNSIGNED NOT NULL DEFAULT 0,
  evidence_hash CHAR(64) NOT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(watch_id,claim_id),
  INDEX idx_research_monitor_claim_state(claim_id,assessment),
  CONSTRAINT fk_research_monitor_claim_watch FOREIGN KEY(watch_id) REFERENCES research_monitor_watches(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_monitor_claim_claim FOREIGN KEY(claim_id) REFERENCES research_claims(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS research_monitor_claim_assessments (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(40) NOT NULL UNIQUE,
  watch_id BIGINT UNSIGNED NOT NULL,
  project_id BIGINT UNSIGNED NOT NULL,
  claim_id BIGINT UNSIGNED NOT NULL,
  source_version_id BIGINT UNSIGNED NOT NULL,
  status ENUM('queued','processing','completed','failed') NOT NULL DEFAULT 'queued',
  assessment ENUM('supports','weakens','contradicts','unrelated') NULL,
  confidence DECIMAL(6,5) NULL,
  rationale TEXT NULL,
  ai_run_public_id VARCHAR(40) NULL,
  last_error VARCHAR(1000) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at DATETIME NULL,
  UNIQUE KEY uq_research_monitor_claim_assessment(watch_id,claim_id,source_version_id),
  INDEX idx_research_monitor_claim_assessment_status(status,created_at),
  INDEX idx_research_monitor_claim_assessment_project(project_id,created_at),
  CONSTRAINT fk_research_monitor_claim_assessment_watch FOREIGN KEY(watch_id) REFERENCES research_monitor_watches(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_monitor_claim_assessment_project FOREIGN KEY(project_id) REFERENCES research_projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_monitor_claim_assessment_claim FOREIGN KEY(claim_id) REFERENCES research_claims(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_monitor_claim_assessment_source_version FOREIGN KEY(source_version_id) REFERENCES source_versions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
