-- Annotated Phase 58 — Research Programs & Recurring Intelligence

CREATE TABLE IF NOT EXISTS research_programs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(40) NOT NULL UNIQUE,
  research_agent_id BIGINT UNSIGNED NOT NULL,
  project_id BIGINT UNSIGNED NOT NULL,
  created_by_user_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(255) NOT NULL,
  objective TEXT NOT NULL,
  status ENUM('active','paused','archived') NOT NULL DEFAULT 'active',
  priority ENUM('low','medium','high','urgent') NOT NULL DEFAULT 'medium',
  cadence ENUM('hourly','daily','weekly','monthly','manual') NOT NULL DEFAULT 'weekly',
  timezone_name VARCHAR(64) NOT NULL DEFAULT 'UTC',
  run_time_local TIME NOT NULL DEFAULT '09:00:00',
  weekday TINYINT UNSIGNED NULL,
  day_of_month TINYINT UNSIGNED NULL,
  quiet_mode ENUM('material_only','always') NOT NULL DEFAULT 'material_only',
  materiality_threshold ENUM('any','important','high') NOT NULL DEFAULT 'important',
  catch_up_mode ENUM('skip','latest') NOT NULL DEFAULT 'latest',
  max_concurrent_runs TINYINT UNSIGNED NOT NULL DEFAULT 1,
  monthly_run_limit SMALLINT UNSIGNED NOT NULL DEFAULT 31,
  token_budget_per_run INT UNSIGNED NOT NULL DEFAULT 60000,
  max_tasks_per_run TINYINT UNSIGNED NOT NULL DEFAULT 12,
  plan_due_offset_hours SMALLINT UNSIGNED NOT NULL DEFAULT 72,
  deliverable_type ENUM('research_brief','competitive_analysis','due_diligence','source_digest','timeline','comparison','weekly_report','report','analysis','document') NOT NULL DEFAULT 'weekly_report',
  plan_title_template VARCHAR(255) NOT NULL DEFAULT '{program} · {date}',
  deliverable_title_template VARCHAR(255) NOT NULL DEFAULT '{program} · {date}',
  task_template_json JSON NULL,
  scope_json JSON NULL,
  current_revision INT UNSIGNED NOT NULL DEFAULT 1,
  config_hash CHAR(64) NOT NULL,
  next_run_at DATETIME NULL,
  last_run_at DATETIME NULL,
  last_input_hash CHAR(64) NULL,
  last_material_hash CHAR(64) NULL,
  run_count INT UNSIGNED NOT NULL DEFAULT 0,
  quiet_run_count INT UNSIGNED NOT NULL DEFAULT 0,
  failure_count INT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_research_program_agent(research_agent_id,status,updated_at),
  INDEX idx_research_program_project(project_id,status,updated_at),
  INDEX idx_research_program_due(status,next_run_at),
  CONSTRAINT fk_research_program_agent FOREIGN KEY(research_agent_id) REFERENCES research_agents(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_program_project FOREIGN KEY(project_id) REFERENCES research_projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_program_user FOREIGN KEY(created_by_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT chk_research_program_weekday CHECK (weekday IS NULL OR weekday<=6),
  CONSTRAINT chk_research_program_monthday CHECK (day_of_month IS NULL OR (day_of_month>=1 AND day_of_month<=28)),
  CONSTRAINT chk_research_program_concurrency CHECK (max_concurrent_runs>=1 AND max_concurrent_runs<=3),
  CONSTRAINT chk_research_program_tasks CHECK (max_tasks_per_run>=1 AND max_tasks_per_run<=30)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS research_program_versions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(40) NOT NULL UNIQUE,
  program_id BIGINT UNSIGNED NOT NULL,
  revision_number INT UNSIGNED NOT NULL,
  config_json JSON NOT NULL,
  change_reason VARCHAR(1000) NULL,
  edited_by_user_id BIGINT UNSIGNED NULL,
  edited_by_agent TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_research_program_revision(program_id,revision_number),
  INDEX idx_research_program_version(program_id,created_at),
  CONSTRAINT fk_research_program_version_program FOREIGN KEY(program_id) REFERENCES research_programs(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_program_version_user FOREIGN KEY(edited_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS research_program_runs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(40) NOT NULL UNIQUE,
  program_id BIGINT UNSIGNED NOT NULL,
  research_agent_id BIGINT UNSIGNED NOT NULL,
  project_id BIGINT UNSIGNED NOT NULL,
  requested_by_user_id BIGINT UNSIGNED NULL,
  previous_run_id BIGINT UNSIGNED NULL,
  trigger_type ENUM('schedule','manual','catch_up','recovery') NOT NULL DEFAULT 'schedule',
  trigger_key CHAR(64) NOT NULL UNIQUE,
  scheduled_for DATETIME NULL,
  available_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status ENUM('queued','processing','active','completed','failed','skipped') NOT NULL DEFAULT 'queued',
  attempts INT UNSIGNED NOT NULL DEFAULT 0,
  claim_token CHAR(32) NULL,
  lease_expires_at DATETIME NULL,
  started_at DATETIME NULL,
  completed_at DATETIME NULL,
  input_hash CHAR(64) NULL,
  material_hash CHAR(64) NULL,
  input_snapshot_json JSON NULL,
  delta_summary_json JSON NULL,
  material_change_count INT UNSIGNED NOT NULL DEFAULT 0,
  quiet_suppressed TINYINT(1) NOT NULL DEFAULT 0,
  tokens_used INT UNSIGNED NOT NULL DEFAULT 0,
  summary TEXT NULL,
  last_error VARCHAR(1000) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_research_program_run_queue(status,available_at,id),
  INDEX idx_research_program_run_program(program_id,created_at),
  INDEX idx_research_program_run_project(project_id,created_at),
  CONSTRAINT fk_research_program_run_program FOREIGN KEY(program_id) REFERENCES research_programs(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_program_run_agent FOREIGN KEY(research_agent_id) REFERENCES research_agents(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_program_run_project FOREIGN KEY(project_id) REFERENCES research_projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_program_run_user FOREIGN KEY(requested_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_research_program_run_previous FOREIGN KEY(previous_run_id) REFERENCES research_program_runs(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE research_task_plans
  ADD COLUMN program_run_id BIGINT UNSIGNED NULL AFTER project_id,
  ADD UNIQUE KEY uq_research_task_plan_program_run(program_run_id),
  ADD CONSTRAINT fk_research_task_plan_program_run FOREIGN KEY(program_run_id) REFERENCES research_program_runs(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS research_program_deltas (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(40) NOT NULL UNIQUE,
  run_id BIGINT UNSIGNED NOT NULL,
  program_id BIGINT UNSIGNED NOT NULL,
  project_id BIGINT UNSIGNED NOT NULL,
  delta_type ENUM('baseline','source_added','source_changed','source_unavailable','source_restored','claim_added','claim_status_changed','claim_strengthened','claim_weakened','claim_contradicted','claim_resolved','contradiction_opened','contradiction_resolved','entity_added','monitor_event','annotation_added','workspace_changed') NOT NULL,
  importance ENUM('info','important','high') NOT NULL DEFAULT 'important',
  ref_type VARCHAR(32) NULL,
  ref_public_id VARCHAR(64) NULL,
  fingerprint CHAR(64) NOT NULL,
  summary TEXT NOT NULL,
  before_json JSON NULL,
  after_json JSON NULL,
  occurred_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_research_program_delta(run_id,fingerprint),
  INDEX idx_research_program_delta_program(program_id,created_at),
  INDEX idx_research_program_delta_project(project_id,importance,created_at),
  INDEX idx_research_program_delta_ref(ref_type,ref_public_id),
  CONSTRAINT fk_research_program_delta_run FOREIGN KEY(run_id) REFERENCES research_program_runs(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_program_delta_program FOREIGN KEY(program_id) REFERENCES research_programs(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_program_delta_project FOREIGN KEY(project_id) REFERENCES research_projects(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS research_program_events (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(40) NOT NULL UNIQUE,
  program_id BIGINT UNSIGNED NOT NULL,
  run_id BIGINT UNSIGNED NULL,
  project_id BIGINT UNSIGNED NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  actor_type ENUM('user','agent','system') NOT NULL DEFAULT 'system',
  actor_user_id BIGINT UNSIGNED NULL,
  payload_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_research_program_event_program(program_id,created_at),
  INDEX idx_research_program_event_project(project_id,created_at),
  CONSTRAINT fk_research_program_event_program FOREIGN KEY(program_id) REFERENCES research_programs(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_program_event_run FOREIGN KEY(run_id) REFERENCES research_program_runs(id) ON DELETE SET NULL,
  CONSTRAINT fk_research_program_event_project FOREIGN KEY(project_id) REFERENCES research_projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_program_event_user FOREIGN KEY(actor_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
