-- Annotated Phase 55 — Autonomous Research Workspace

CREATE TABLE IF NOT EXISTS research_autonomy_runs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(40) NOT NULL UNIQUE,
  research_agent_id BIGINT UNSIGNED NOT NULL,
  project_id BIGINT UNSIGNED NOT NULL,
  requested_by_user_id BIGINT UNSIGNED NULL,
  trigger_type ENUM('manual','workspace_change','schedule','research_change','recovery') NOT NULL DEFAULT 'workspace_change',
  reason VARCHAR(500) NULL,
  status ENUM('processing','completed','failed','skipped') NOT NULL DEFAULT 'processing',
  input_state_hash CHAR(64) NULL,
  output_state_hash CHAR(64) NULL,
  summary TEXT NULL,
  metrics_json JSON NULL,
  started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at DATETIME NULL,
  last_error VARCHAR(1000) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_research_autonomy_run_agent(research_agent_id,created_at),
  INDEX idx_research_autonomy_run_project(project_id,created_at),
  INDEX idx_research_autonomy_run_status(status,created_at),
  CONSTRAINT fk_research_autonomy_run_agent FOREIGN KEY(research_agent_id) REFERENCES research_agents(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_autonomy_run_project FOREIGN KEY(project_id) REFERENCES research_projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_autonomy_run_user FOREIGN KEY(requested_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS research_autonomy_jobs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  research_agent_id BIGINT UNSIGNED NOT NULL UNIQUE,
  project_id BIGINT UNSIGNED NOT NULL,
  requested_by_user_id BIGINT UNSIGNED NULL,
  trigger_type ENUM('manual','workspace_change','schedule','research_change','recovery') NOT NULL DEFAULT 'workspace_change',
  reason VARCHAR(500) NULL,
  status ENUM('queued','processing','done','failed') NOT NULL DEFAULT 'queued',
  attempts INT UNSIGNED NOT NULL DEFAULT 0,
  claim_token CHAR(32) NULL,
  lease_expires_at DATETIME NULL,
  available_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_error VARCHAR(1000) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  started_at DATETIME NULL,
  completed_at DATETIME NULL,
  rerun_requested TINYINT(1) NOT NULL DEFAULT 0,
  INDEX idx_research_autonomy_job_claim(status,available_at,lease_expires_at,created_at),
  INDEX idx_research_autonomy_job_project(project_id,status),
  CONSTRAINT fk_research_autonomy_job_agent FOREIGN KEY(research_agent_id) REFERENCES research_agents(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_autonomy_job_project FOREIGN KEY(project_id) REFERENCES research_projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_autonomy_job_user FOREIGN KEY(requested_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS research_autonomy_artifacts (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  research_agent_id BIGINT UNSIGNED NOT NULL,
  project_id BIGINT UNSIGNED NOT NULL,
  object_id BIGINT UNSIGNED NOT NULL,
  management_key VARCHAR(190) NOT NULL,
  managed_kind ENUM('folder','document','sticky','report') NOT NULL,
  purpose VARCHAR(500) NULL,
  created_by_run_id BIGINT UNSIGNED NULL,
  last_managed_run_id BIGINT UNSIGNED NULL,
  status ENUM('active','retired') NOT NULL DEFAULT 'active',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_research_autonomy_artifact_object(object_id),
  UNIQUE KEY uq_research_autonomy_artifact_key(research_agent_id,management_key),
  INDEX idx_research_autonomy_artifact_project(project_id,status,updated_at),
  CONSTRAINT fk_research_autonomy_artifact_agent FOREIGN KEY(research_agent_id) REFERENCES research_agents(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_autonomy_artifact_project FOREIGN KEY(project_id) REFERENCES research_projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_autonomy_artifact_object FOREIGN KEY(object_id) REFERENCES research_workspace_objects(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_autonomy_artifact_created_run FOREIGN KEY(created_by_run_id) REFERENCES research_autonomy_runs(id) ON DELETE SET NULL,
  CONSTRAINT fk_research_autonomy_artifact_managed_run FOREIGN KEY(last_managed_run_id) REFERENCES research_autonomy_runs(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS research_autonomy_observations (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(40) NOT NULL UNIQUE,
  research_agent_id BIGINT UNSIGNED NOT NULL,
  project_id BIGINT UNSIGNED NOT NULL,
  last_run_id BIGINT UNSIGNED NULL,
  observation_type ENUM('evidence_gap','contradiction','stale_evidence','change','next_step') NOT NULL,
  subject_type VARCHAR(32) NOT NULL,
  subject_public_id VARCHAR(64) NULL,
  fingerprint CHAR(64) NOT NULL,
  title VARCHAR(255) NOT NULL,
  detail TEXT NULL,
  severity ENUM('info','low','medium','high') NOT NULL DEFAULT 'medium',
  status ENUM('open','resolved','dismissed') NOT NULL DEFAULT 'open',
  evidence_refs_json JSON NULL,
  first_detected_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resolved_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_research_autonomy_observation(research_agent_id,fingerprint),
  INDEX idx_research_autonomy_observation_project(project_id,status,observation_type,updated_at),
  CONSTRAINT fk_research_autonomy_observation_agent FOREIGN KEY(research_agent_id) REFERENCES research_agents(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_autonomy_observation_project FOREIGN KEY(project_id) REFERENCES research_projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_autonomy_observation_run FOREIGN KEY(last_run_id) REFERENCES research_autonomy_runs(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS research_autonomy_reports (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  research_agent_id BIGINT UNSIGNED NOT NULL UNIQUE,
  project_id BIGINT UNSIGNED NOT NULL,
  object_id BIGINT UNSIGNED NOT NULL UNIQUE,
  report_key VARCHAR(64) NOT NULL DEFAULT 'living-report',
  evidence_state_hash CHAR(64) NULL,
  last_run_id BIGINT UNSIGNED NULL,
  last_posted_state_hash CHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_research_autonomy_report_agent FOREIGN KEY(research_agent_id) REFERENCES research_agents(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_autonomy_report_project FOREIGN KEY(project_id) REFERENCES research_projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_autonomy_report_object FOREIGN KEY(object_id) REFERENCES research_workspace_objects(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_autonomy_report_run FOREIGN KEY(last_run_id) REFERENCES research_autonomy_runs(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
