CREATE TABLE IF NOT EXISTS research_action_plan_execution_baselines (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(40) NOT NULL UNIQUE,
  action_plan_id BIGINT UNSIGNED NOT NULL,
  action_plan_revision INT UNSIGNED NOT NULL,
  action_plan_config_hash CHAR(64) NOT NULL,
  config_json JSON NOT NULL,
  milestone_snapshot_json JSON NOT NULL,
  task_snapshot_json JSON NOT NULL,
  captured_by_user_id BIGINT UNSIGNED NULL,
  captured_by_agent TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_rap_exec_baseline_revision(action_plan_id,action_plan_revision,action_plan_config_hash),
  INDEX idx_rap_exec_baseline_plan(action_plan_id,id),
  CONSTRAINT fk_rap_exec_baseline_plan FOREIGN KEY(action_plan_id) REFERENCES research_action_plans(id) ON DELETE CASCADE,
  CONSTRAINT fk_rap_exec_baseline_user FOREIGN KEY(captured_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS research_action_plan_execution_observations (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(40) NOT NULL UNIQUE,
  action_plan_id BIGINT UNSIGNED NOT NULL,
  baseline_id BIGINT UNSIGNED NOT NULL,
  milestone_id BIGINT UNSIGNED NULL,
  task_id BIGINT UNSIGNED NULL,
  observation_type ENUM('progress','success_measure','milestone','assumption','risk','new_evidence','outcome_signal') NOT NULL,
  subject_type ENUM('action_plan','milestone','task','success_measure','assumption','risk') NOT NULL DEFAULT 'action_plan',
  subject_key VARCHAR(255) NULL,
  summary TEXT NOT NULL,
  expected_json JSON NULL,
  actual_json JSON NULL,
  assessment ENUM('unknown','on_track','at_risk','met','missed','changed') NOT NULL DEFAULT 'unknown',
  source_type VARCHAR(64) NULL,
  source_public_id VARCHAR(80) NULL,
  source_snapshot_json JSON NULL,
  observed_on DATE NOT NULL,
  material TINYINT(1) NOT NULL DEFAULT 0,
  idempotency_key CHAR(64) NOT NULL,
  recorded_by_user_id BIGINT UNSIGNED NULL,
  recorded_by_agent TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_rap_exec_observation_request(action_plan_id,idempotency_key),
  INDEX idx_rap_exec_observation_plan(action_plan_id,observed_on,id),
  INDEX idx_rap_exec_observation_milestone(milestone_id,id),
  INDEX idx_rap_exec_observation_task(task_id,id),
  CONSTRAINT fk_rap_exec_observation_plan FOREIGN KEY(action_plan_id) REFERENCES research_action_plans(id) ON DELETE CASCADE,
  CONSTRAINT fk_rap_exec_observation_baseline FOREIGN KEY(baseline_id) REFERENCES research_action_plan_execution_baselines(id) ON DELETE CASCADE,
  CONSTRAINT fk_rap_exec_observation_milestone FOREIGN KEY(milestone_id) REFERENCES research_action_plan_milestones(id) ON DELETE SET NULL,
  CONSTRAINT fk_rap_exec_observation_task FOREIGN KEY(task_id) REFERENCES research_tasks(id) ON DELETE SET NULL,
  CONSTRAINT fk_rap_exec_observation_user FOREIGN KEY(recorded_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS research_action_plan_variances (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(40) NOT NULL UNIQUE,
  action_plan_id BIGINT UNSIGNED NOT NULL,
  baseline_id BIGINT UNSIGNED NOT NULL,
  observation_id BIGINT UNSIGNED NULL,
  milestone_id BIGINT UNSIGNED NULL,
  task_id BIGINT UNSIGNED NULL,
  variance_type ENUM('schedule_delay','target_miss','assumption_changed','new_evidence','risk_realized','scope_change','execution_deviation') NOT NULL,
  subject_type ENUM('action_plan','milestone','task','success_measure','assumption','risk') NOT NULL DEFAULT 'action_plan',
  subject_key VARCHAR(255) NULL,
  severity ENUM('low','medium','high','critical') NOT NULL DEFAULT 'medium',
  material TINYINT(1) NOT NULL DEFAULT 1,
  summary TEXT NOT NULL,
  expected_json JSON NULL,
  actual_json JSON NULL,
  impact TEXT NULL,
  response TEXT NULL,
  status ENUM('open','resolved') NOT NULL DEFAULT 'open',
  fingerprint CHAR(64) NOT NULL,
  created_by_user_id BIGINT UNSIGNED NULL,
  created_by_agent TINYINT(1) NOT NULL DEFAULT 0,
  resolved_by_user_id BIGINT UNSIGNED NULL,
  resolved_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_rap_variance_fingerprint(action_plan_id,fingerprint),
  INDEX idx_rap_variance_plan(action_plan_id,status,severity,id),
  INDEX idx_rap_variance_milestone(milestone_id,status,id),
  INDEX idx_rap_variance_task(task_id,status,id),
  CONSTRAINT fk_rap_variance_plan FOREIGN KEY(action_plan_id) REFERENCES research_action_plans(id) ON DELETE CASCADE,
  CONSTRAINT fk_rap_variance_baseline FOREIGN KEY(baseline_id) REFERENCES research_action_plan_execution_baselines(id) ON DELETE CASCADE,
  CONSTRAINT fk_rap_variance_observation FOREIGN KEY(observation_id) REFERENCES research_action_plan_execution_observations(id) ON DELETE SET NULL,
  CONSTRAINT fk_rap_variance_milestone FOREIGN KEY(milestone_id) REFERENCES research_action_plan_milestones(id) ON DELETE SET NULL,
  CONSTRAINT fk_rap_variance_task FOREIGN KEY(task_id) REFERENCES research_tasks(id) ON DELETE SET NULL,
  CONSTRAINT fk_rap_variance_creator FOREIGN KEY(created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_rap_variance_resolver FOREIGN KEY(resolved_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;