-- Admin V1.80 — Coupons, Promotions & Credits
-- Annotated owns commercial policy, eligibility, redemption and credit audit. Stripe mirrors collection behavior.

CREATE TABLE IF NOT EXISTS commercial_promotions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(40) NOT NULL UNIQUE,
  code VARCHAR(80) NOT NULL UNIQUE,
  name VARCHAR(190) NOT NULL,
  description TEXT NULL,
  status ENUM('draft','active','archived') NOT NULL DEFAULT 'draft',
  discount_type ENUM('percent','fixed_amount') NOT NULL,
  percent_basis_points INT UNSIGNED NULL,
  amount_off_cents INT UNSIGNED NULL,
  duration ENUM('once','repeating','forever') NOT NULL DEFAULT 'once',
  duration_months SMALLINT UNSIGNED NULL,
  customer_scope ENUM('all','new_customers','existing_customers') NOT NULL DEFAULT 'all',
  eligible_package_ids_json JSON NULL,
  minimum_package_amount_cents INT UNSIGNED NULL,
  starts_at DATETIME NULL,
  ends_at DATETIME NULL,
  max_redemptions INT UNSIGNED NULL,
  per_account_limit INT UNSIGNED NOT NULL DEFAULT 1,
  created_by_user_id BIGINT UNSIGNED NULL,
  updated_by_user_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_commercial_promotions_status(status,starts_at,ends_at,id),
  CONSTRAINT fk_commercial_promotion_creator FOREIGN KEY(created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_commercial_promotion_updater FOREIGN KEY(updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS commercial_promotion_stripe_mappings (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  promotion_id BIGINT UNSIGNED NOT NULL,
  stripe_mode ENUM('test','live') NOT NULL,
  definition_hash CHAR(64) NOT NULL,
  stripe_coupon_id VARCHAR(255) NULL,
  stripe_promotion_code_id VARCHAR(255) NULL,
  status ENUM('synced','failed') NOT NULL DEFAULT 'synced',
  last_error VARCHAR(1000) NULL,
  synced_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_commercial_promotion_mapping(promotion_id,stripe_mode),
  INDEX idx_commercial_promotion_mapping_code(stripe_mode,stripe_promotion_code_id),
  CONSTRAINT fk_commercial_promotion_mapping FOREIGN KEY(promotion_id) REFERENCES commercial_promotions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS commercial_promotion_redemptions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(40) NOT NULL UNIQUE,
  promotion_id BIGINT UNSIGNED NOT NULL,
  account_id BIGINT UNSIGNED NOT NULL,
  package_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NULL,
  stripe_mode ENUM('test','live') NOT NULL,
  checkout_attempt_public_id VARCHAR(40) NOT NULL,
  stripe_checkout_session_id VARCHAR(255) NULL,
  stripe_subscription_id VARCHAR(255) NULL,
  stripe_invoice_id VARCHAR(255) NULL,
  status ENUM('pending','applied','void') NOT NULL DEFAULT 'pending',
  amount_discounted_cents BIGINT UNSIGNED NOT NULL DEFAULT 0,
  discount_snapshot_json JSON NOT NULL,
  reserved_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  applied_at DATETIME NULL,
  voided_at DATETIME NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_commercial_redemption_attempt(stripe_mode,checkout_attempt_public_id),
  UNIQUE KEY uq_commercial_redemption_session(stripe_mode,stripe_checkout_session_id),
  INDEX idx_commercial_redemption_promotion(promotion_id,stripe_mode,status,id),
  INDEX idx_commercial_redemption_account(account_id,stripe_mode,status,id),
  INDEX idx_commercial_redemption_subscription(stripe_mode,stripe_subscription_id,id),
  CONSTRAINT fk_commercial_redemption_promotion FOREIGN KEY(promotion_id) REFERENCES commercial_promotions(id) ON DELETE RESTRICT,
  CONSTRAINT fk_commercial_redemption_account FOREIGN KEY(account_id) REFERENCES accounts(id) ON DELETE CASCADE,
  CONSTRAINT fk_commercial_redemption_package FOREIGN KEY(package_id) REFERENCES subscription_packages(id) ON DELETE RESTRICT,
  CONSTRAINT fk_commercial_redemption_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS commercial_discount_events (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(40) NOT NULL UNIQUE,
  promotion_id BIGINT UNSIGNED NULL,
  redemption_id BIGINT UNSIGNED NULL,
  account_id BIGINT UNSIGNED NOT NULL,
  stripe_mode ENUM('test','live') NOT NULL,
  stripe_invoice_id VARCHAR(255) NOT NULL,
  stripe_subscription_id VARCHAR(255) NULL,
  gross_subtotal_cents BIGINT UNSIGNED NOT NULL DEFAULT 0,
  discount_amount_cents BIGINT UNSIGNED NOT NULL DEFAULT 0,
  net_total_cents BIGINT UNSIGNED NOT NULL DEFAULT 0,
  event_created_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_commercial_discount_invoice(stripe_mode,stripe_invoice_id),
  INDEX idx_commercial_discount_account(account_id,stripe_mode,created_at,id),
  INDEX idx_commercial_discount_promotion(promotion_id,created_at,id),
  CONSTRAINT fk_commercial_discount_promotion FOREIGN KEY(promotion_id) REFERENCES commercial_promotions(id) ON DELETE SET NULL,
  CONSTRAINT fk_commercial_discount_redemption FOREIGN KEY(redemption_id) REFERENCES commercial_promotion_redemptions(id) ON DELETE SET NULL,
  CONSTRAINT fk_commercial_discount_account FOREIGN KEY(account_id) REFERENCES accounts(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS commercial_credit_adjustments (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(40) NOT NULL UNIQUE,
  account_id BIGINT UNSIGNED NOT NULL,
  stripe_mode ENUM('test','live') NOT NULL,
  actor_user_id BIGINT UNSIGNED NULL,
  adjustment_type ENUM('credit','debit','reversal') NOT NULL,
  amount_cents BIGINT NOT NULL,
  currency VARCHAR(12) NOT NULL DEFAULT 'usd',
  reason VARCHAR(500) NOT NULL,
  idempotency_key VARCHAR(191) NOT NULL,
  stripe_customer_id VARCHAR(255) NOT NULL,
  stripe_balance_transaction_id VARCHAR(255) NULL,
  related_adjustment_id BIGINT UNSIGNED NULL,
  status ENUM('creating','applied','failed') NOT NULL DEFAULT 'creating',
  last_error VARCHAR(1000) NULL,
  applied_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_commercial_credit_idempotency(idempotency_key),
  UNIQUE KEY uq_commercial_credit_stripe(stripe_mode,stripe_balance_transaction_id),
  INDEX idx_commercial_credit_account(account_id,stripe_mode,created_at,id),
  CONSTRAINT fk_commercial_credit_account FOREIGN KEY(account_id) REFERENCES accounts(id) ON DELETE CASCADE,
  CONSTRAINT fk_commercial_credit_actor FOREIGN KEY(actor_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_commercial_credit_related FOREIGN KEY(related_adjustment_id) REFERENCES commercial_credit_adjustments(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS commercial_audit_events (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(40) NOT NULL UNIQUE,
  promotion_id BIGINT UNSIGNED NULL,
  account_id BIGINT UNSIGNED NULL,
  actor_user_id BIGINT UNSIGNED NULL,
  event_type VARCHAR(100) NOT NULL,
  before_json JSON NULL,
  after_json JSON NULL,
  reason VARCHAR(500) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_commercial_audit_promotion(promotion_id,created_at,id),
  INDEX idx_commercial_audit_account(account_id,created_at,id),
  CONSTRAINT fk_commercial_audit_promotion FOREIGN KEY(promotion_id) REFERENCES commercial_promotions(id) ON DELETE SET NULL,
  CONSTRAINT fk_commercial_audit_account FOREIGN KEY(account_id) REFERENCES accounts(id) ON DELETE CASCADE,
  CONSTRAINT fk_commercial_audit_actor FOREIGN KEY(actor_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
