CREATE TABLE IF NOT EXISTS research_agents (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(40) NOT NULL UNIQUE,
  owner_user_id BIGINT UNSIGNED NOT NULL,
  team_id BIGINT UNSIGNED NULL,
  project_id BIGINT UNSIGNED NOT NULL,
  conversation_id BIGINT UNSIGNED NOT NULL,
  automation_id BIGINT UNSIGNED NULL,
  name VARCHAR(190) NOT NULL,
  description TEXT NULL,
  status ENUM('active','paused','archived') NOT NULL DEFAULT 'active',
  monitoring_cadence ENUM('hourly','daily','weekly','manual') NOT NULL DEFAULT 'daily',
  is_default TINYINT UNSIGNED NULL DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_research_agent_project(project_id),
  UNIQUE KEY uq_research_agent_conversation(conversation_id),
  UNIQUE KEY uq_research_agent_default(owner_user_id,is_default),
  INDEX idx_research_agent_owner(owner_user_id,status,updated_at),
  INDEX idx_research_agent_team(team_id,status,updated_at),
  CONSTRAINT fk_research_agent_owner FOREIGN KEY(owner_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_agent_team FOREIGN KEY(team_id) REFERENCES teams(id) ON DELETE SET NULL,
  CONSTRAINT fk_research_agent_project FOREIGN KEY(project_id) REFERENCES research_projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_agent_conversation FOREIGN KEY(conversation_id) REFERENCES conversations(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_agent_automation FOREIGN KEY(automation_id) REFERENCES research_automations(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
