-- Phase 69 — Research Intelligence Delivery & Subscriptions
-- Uses existing Research Program scheduling. No second scheduler or worker is introduced.

CREATE TABLE IF NOT EXISTS research_intelligence_subscriptions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(40) NOT NULL UNIQUE,
  research_agent_id BIGINT UNSIGNED NOT NULL,
  project_id BIGINT UNSIGNED NOT NULL,
  subscriber_user_id BIGINT UNSIGNED NULL,
  preset_id BIGINT UNSIGNED NULL,
  program_id BIGINT UNSIGNED NULL,
  name VARCHAR(190) NOT NULL,
  status ENUM('active','paused','archived') NOT NULL DEFAULT 'active',
  delivery_policy ENUM('every_run','if_changed','material_change_only','if_stale') NOT NULL DEFAULT 'material_change_only',
  stale_after_hours SMALLINT UNSIGNED NOT NULL DEFAULT 168,
  notify_in_app TINYINT(1) NOT NULL DEFAULT 1,
  notify_agent_chat TINYINT(1) NOT NULL DEFAULT 1,
  include_summary TINYINT(1) NOT NULL DEFAULT 1,
  include_comparison TINYINT(1) NOT NULL DEFAULT 1,
  last_report_id BIGINT UNSIGNED NULL,
  last_state_hash CHAR(64) NULL,
  last_change_signature CHAR(64) NULL,
  last_delivered_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_report_subscription_user_preset_program(subscriber_user_id,preset_id,program_id),
  INDEX idx_report_subscription_agent(research_agent_id,status,updated_at),
  INDEX idx_report_subscription_program(program_id,status,updated_at),
  INDEX idx_report_subscription_user(subscriber_user_id,status,updated_at),
  CONSTRAINT fk_p69_intel_sub_agent FOREIGN KEY(research_agent_id) REFERENCES research_agents(id) ON DELETE CASCADE,
  CONSTRAINT fk_p69_intel_sub_project FOREIGN KEY(project_id) REFERENCES research_projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_p69_intel_sub_user FOREIGN KEY(subscriber_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_p69_intel_sub_preset FOREIGN KEY(preset_id) REFERENCES research_report_presets(id) ON DELETE SET NULL,
  CONSTRAINT fk_p69_intel_sub_program FOREIGN KEY(program_id) REFERENCES research_programs(id) ON DELETE SET NULL,
  CONSTRAINT fk_p69_intel_sub_last_report FOREIGN KEY(last_report_id) REFERENCES research_system_reports(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS research_report_deliveries (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(40) NOT NULL UNIQUE,
  subscription_id BIGINT UNSIGNED NULL,
  subscription_public_id VARCHAR(40) NULL,
  research_agent_id BIGINT UNSIGNED NOT NULL,
  project_id BIGINT UNSIGNED NOT NULL,
  subscriber_user_id BIGINT UNSIGNED NULL,
  preset_id BIGINT UNSIGNED NULL,
  program_id BIGINT UNSIGNED NULL,
  program_run_id BIGINT UNSIGNED NULL,
  report_id BIGINT UNSIGNED NULL,
  previous_report_id BIGINT UNSIGNED NULL,
  trigger_type ENUM('program_completed','program_quiet','manual') NOT NULL DEFAULT 'program_completed',
  status ENUM('pending','delivered','suppressed','failed','viewed') NOT NULL DEFAULT 'pending',
  reason_code VARCHAR(64) NULL,
  dedupe_key CHAR(64) NOT NULL UNIQUE,
  change_signature CHAR(64) NULL,
  material_change_count INT UNSIGNED NOT NULL DEFAULT 0,
  summary TEXT NULL,
  comparison_json JSON NULL,
  channels_json JSON NULL,
  delivered_at DATETIME NULL,
  viewed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_report_delivery_subscription(subscription_id,created_at),
  INDEX idx_report_delivery_subscription_public(subscription_public_id,created_at),
  INDEX idx_report_delivery_agent(research_agent_id,status,created_at),
  INDEX idx_report_delivery_user(subscriber_user_id,status,created_at),
  INDEX idx_report_delivery_program(program_id,created_at),
  INDEX idx_report_delivery_run(program_run_id,created_at),
  CONSTRAINT fk_p69_delivery_agent FOREIGN KEY(research_agent_id) REFERENCES research_agents(id) ON DELETE CASCADE,
  CONSTRAINT fk_p69_delivery_project FOREIGN KEY(project_id) REFERENCES research_projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_p69_delivery_user FOREIGN KEY(subscriber_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_p69_delivery_preset FOREIGN KEY(preset_id) REFERENCES research_report_presets(id) ON DELETE SET NULL,
  CONSTRAINT fk_p69_delivery_program FOREIGN KEY(program_id) REFERENCES research_programs(id) ON DELETE SET NULL,
  CONSTRAINT fk_p69_delivery_program_run FOREIGN KEY(program_run_id) REFERENCES research_program_runs(id) ON DELETE SET NULL,
  CONSTRAINT fk_p69_delivery_report FOREIGN KEY(report_id) REFERENCES research_system_reports(id) ON DELETE SET NULL,
  CONSTRAINT fk_p69_delivery_previous_report FOREIGN KEY(previous_report_id) REFERENCES research_system_reports(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS research_report_delivery_events (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(40) NOT NULL UNIQUE,
  delivery_id BIGINT UNSIGNED NULL,
  subscription_id BIGINT UNSIGNED NULL,
  event_type VARCHAR(64) NOT NULL,
  actor_type ENUM('user','agent','system') NOT NULL DEFAULT 'system',
  actor_user_id BIGINT UNSIGNED NULL,
  payload_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_report_delivery_event_delivery(delivery_id,created_at),
  INDEX idx_report_delivery_event_subscription(subscription_id,created_at),
  CONSTRAINT fk_p69_delivery_event_delivery FOREIGN KEY(delivery_id) REFERENCES research_report_deliveries(id) ON DELETE SET NULL,
  CONSTRAINT fk_p69_delivery_event_user FOREIGN KEY(actor_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
