-- Phase 80 Section 7 — Knowledge Base Versioning & Promotion

CREATE TABLE IF NOT EXISTS sponsored_research_knowledge_bases (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(40) NOT NULL UNIQUE,
  campaign_id BIGINT UNSIGNED NOT NULL,
  account_id BIGINT UNSIGNED NOT NULL,
  research_agent_id BIGINT UNSIGNED NULL,
  name VARCHAR(255) NOT NULL,
  description MEDIUMTEXT NULL,
  status ENUM('draft','active','archived') NOT NULL DEFAULT 'draft',
  current_release_number INT UNSIGNED NOT NULL DEFAULT 0,
  created_by_user_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_sponsored_kb_campaign_name(campaign_id,name),
  INDEX idx_sponsored_kb_account(account_id,status,updated_at),
  CONSTRAINT fk_sponsored_kb_campaign FOREIGN KEY(campaign_id) REFERENCES sponsored_research_campaigns(id) ON DELETE RESTRICT,
  CONSTRAINT fk_sponsored_kb_account FOREIGN KEY(account_id) REFERENCES accounts(id) ON DELETE RESTRICT,
  CONSTRAINT fk_sponsored_kb_agent FOREIGN KEY(research_agent_id) REFERENCES research_agents(id) ON DELETE SET NULL,
  CONSTRAINT fk_sponsored_kb_creator FOREIGN KEY(created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sponsored_research_knowledge_items (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(40) NOT NULL UNIQUE,
  knowledge_base_id BIGINT UNSIGNED NOT NULL,
  source_submission_version_id BIGINT UNSIGNED NOT NULL,
  source_submission_asset_id BIGINT UNSIGNED NOT NULL,
  source_object_type VARCHAR(64) NOT NULL,
  source_object_public_id VARCHAR(64) NOT NULL,
  source_object_version VARCHAR(64) NULL,
  contributor_user_id BIGINT UNSIGNED NULL,
  title VARCHAR(255) NOT NULL,
  body MEDIUMTEXT NOT NULL,
  state ENUM('active','corrected','withdrawn','rights_revoked') NOT NULL DEFAULT 'active',
  future_use_allowed TINYINT(1) NOT NULL DEFAULT 1,
  snapshot_json JSON NOT NULL,
  snapshot_hash CHAR(64) NOT NULL,
  source_rights_snapshot_json JSON NULL,
  source_rights_snapshot_hash CHAR(64) NULL,
  supersedes_item_id BIGINT UNSIGNED NULL,
  promoted_by_user_id BIGINT UNSIGNED NOT NULL,
  promoted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  corrected_at DATETIME NULL,
  rights_revoked_at DATETIME NULL,
  withdrawn_at DATETIME NULL,
  UNIQUE KEY uq_sponsored_kb_asset(knowledge_base_id,source_submission_asset_id),
  INDEX idx_sponsored_kb_item_state(knowledge_base_id,state,future_use_allowed,id),
  INDEX idx_sponsored_kb_item_source(source_object_type,source_object_public_id,source_object_version),
  INDEX idx_sponsored_kb_item_contributor(contributor_user_id,promoted_at),
  CONSTRAINT fk_sponsored_kb_item_kb FOREIGN KEY(knowledge_base_id) REFERENCES sponsored_research_knowledge_bases(id) ON DELETE CASCADE,
  CONSTRAINT fk_sponsored_kb_item_version FOREIGN KEY(source_submission_version_id) REFERENCES sponsored_research_submission_versions(id) ON DELETE RESTRICT,
  CONSTRAINT fk_sponsored_kb_item_asset FOREIGN KEY(source_submission_asset_id) REFERENCES sponsored_research_submission_assets(id) ON DELETE RESTRICT,
  CONSTRAINT fk_sponsored_kb_item_contributor FOREIGN KEY(contributor_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_sponsored_kb_item_supersedes FOREIGN KEY(supersedes_item_id) REFERENCES sponsored_research_knowledge_items(id) ON DELETE SET NULL,
  CONSTRAINT fk_sponsored_kb_item_promoter FOREIGN KEY(promoted_by_user_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sponsored_research_knowledge_releases (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(40) NOT NULL UNIQUE,
  knowledge_base_id BIGINT UNSIGNED NOT NULL,
  release_number INT UNSIGNED NOT NULL,
  manifest_json JSON NOT NULL,
  manifest_hash CHAR(64) NOT NULL,
  item_count INT UNSIGNED NOT NULL DEFAULT 0,
  release_note VARCHAR(1000) NULL,
  released_by_user_id BIGINT UNSIGNED NOT NULL,
  released_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_sponsored_kb_release(knowledge_base_id,release_number),
  INDEX idx_sponsored_kb_release_hash(manifest_hash),
  CONSTRAINT fk_sponsored_kb_release_kb FOREIGN KEY(knowledge_base_id) REFERENCES sponsored_research_knowledge_bases(id) ON DELETE CASCADE,
  CONSTRAINT fk_sponsored_kb_release_user FOREIGN KEY(released_by_user_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sponsored_research_knowledge_release_items (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  release_id BIGINT UNSIGNED NOT NULL,
  knowledge_item_id BIGINT UNSIGNED NOT NULL,
  position INT UNSIGNED NOT NULL,
  item_public_id VARCHAR(40) NOT NULL,
  source_object_type VARCHAR(64) NOT NULL,
  source_object_public_id VARCHAR(64) NOT NULL,
  source_object_version VARCHAR(64) NULL,
  contributor_user_id BIGINT UNSIGNED NULL,
  snapshot_hash CHAR(64) NOT NULL,
  source_rights_snapshot_hash CHAR(64) NULL,
  item_state VARCHAR(32) NOT NULL,
  future_use_allowed TINYINT(1) NOT NULL,
  UNIQUE KEY uq_sponsored_kb_release_position(release_id,position),
  UNIQUE KEY uq_sponsored_kb_release_item(release_id,knowledge_item_id),
  INDEX idx_sponsored_kb_release_source(source_object_type,source_object_public_id,source_object_version),
  CONSTRAINT fk_sponsored_kb_release_item_release FOREIGN KEY(release_id) REFERENCES sponsored_research_knowledge_releases(id) ON DELETE CASCADE,
  CONSTRAINT fk_sponsored_kb_release_item_item FOREIGN KEY(knowledge_item_id) REFERENCES sponsored_research_knowledge_items(id) ON DELETE RESTRICT,
  CONSTRAINT fk_sponsored_kb_release_item_contributor FOREIGN KEY(contributor_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sponsored_research_knowledge_events (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(40) NOT NULL UNIQUE,
  knowledge_base_id BIGINT UNSIGNED NOT NULL,
  knowledge_item_id BIGINT UNSIGNED NULL,
  release_id BIGINT UNSIGNED NULL,
  actor_user_id BIGINT UNSIGNED NULL,
  event_type VARCHAR(80) NOT NULL,
  payload_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_sponsored_kb_event(knowledge_base_id,created_at,id),
  CONSTRAINT fk_sponsored_kb_event_kb FOREIGN KEY(knowledge_base_id) REFERENCES sponsored_research_knowledge_bases(id) ON DELETE CASCADE,
  CONSTRAINT fk_sponsored_kb_event_item FOREIGN KEY(knowledge_item_id) REFERENCES sponsored_research_knowledge_items(id) ON DELETE SET NULL,
  CONSTRAINT fk_sponsored_kb_event_release FOREIGN KEY(release_id) REFERENCES sponsored_research_knowledge_releases(id) ON DELETE SET NULL,
  CONSTRAINT fk_sponsored_kb_event_actor FOREIGN KEY(actor_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
