-- Annotated Phase 18 — Research Automation / Recurring Agent Workflows
-- Automations run under the creating user's current permissions.
-- Review workflows may only create normal Stage 15 proposals; execution still requires explicit confirmation.

CREATE TABLE IF NOT EXISTS research_automations (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(40) NOT NULL UNIQUE,
  user_id BIGINT UNSIGNED NOT NULL,
  project_id BIGINT UNSIGNED NOT NULL,
  conversation_id BIGINT UNSIGNED NULL,
  watch_id BIGINT UNSIGNED NULL,
  title VARCHAR(190) NOT NULL,
  workflow_type ENUM('briefing','review','source_refresh') NOT NULL,
  trigger_type ENUM('schedule','watch_alert') NOT NULL DEFAULT 'schedule',
  cadence ENUM('hourly','daily','weekly','manual') NOT NULL DEFAULT 'daily',
  timezone_name VARCHAR(64) NOT NULL DEFAULT 'UTC',
  run_time_local TIME NULL,
  weekday TINYINT UNSIGNED NULL,
  prompt TEXT NULL,
  status ENUM('active','paused','archived') NOT NULL DEFAULT 'active',
  next_run_at DATETIME NULL,
  last_trigger_notification_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  last_triggered_at DATETIME NULL,
  last_run_at DATETIME NULL,
  run_count INT UNSIGNED NOT NULL DEFAULT 0,
  failure_count INT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_research_automation_due(status,trigger_type,next_run_at),
  INDEX idx_research_automation_user(user_id,status,updated_at),
  INDEX idx_research_automation_project(project_id,status),
  INDEX idx_research_automation_watch(watch_id,status),
  CONSTRAINT fk_research_automation_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_automation_project FOREIGN KEY(project_id) REFERENCES research_projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_automation_conversation FOREIGN KEY(conversation_id) REFERENCES conversations(id) ON DELETE SET NULL,
  CONSTRAINT fk_research_automation_watch FOREIGN KEY(watch_id) REFERENCES cognitive_watches(id) ON DELETE SET NULL,
  CONSTRAINT chk_research_automation_weekday CHECK (weekday IS NULL OR weekday<=6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS research_automation_runs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(40) NOT NULL UNIQUE,
  automation_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  project_id BIGINT UNSIGNED NOT NULL,
  trigger_type ENUM('schedule','watch_alert','manual') NOT NULL,
  trigger_key CHAR(64) NOT NULL UNIQUE,
  trigger_notification_public_id VARCHAR(40) NULL,
  scheduled_for DATETIME NULL,
  available_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status ENUM('queued','processing','completed','failed','skipped') NOT NULL DEFAULT 'queued',
  attempts INT UNSIGNED NOT NULL DEFAULT 0,
  claim_token CHAR(32) NULL,
  lease_expires_at DATETIME NULL,
  started_at DATETIME NULL,
  completed_at DATETIME NULL,
  input_hash CHAR(64) NULL,
  output_text MEDIUMTEXT NULL,
  ai_run_public_id VARCHAR(40) NULL,
  conversation_public_id VARCHAR(40) NULL,
  proposal_count INT UNSIGNED NOT NULL DEFAULT 0,
  notification_public_id VARCHAR(40) NULL,
  last_error VARCHAR(1000) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_research_automation_run_queue(status,available_at,id),
  INDEX idx_research_automation_run_automation(automation_id,created_at),
  INDEX idx_research_automation_run_user(user_id,created_at),
  CONSTRAINT fk_research_automation_run_automation FOREIGN KEY(automation_id) REFERENCES research_automations(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_automation_run_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_research_automation_run_project FOREIGN KEY(project_id) REFERENCES research_projects(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
