<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
$admin=require_admin($pdo);
if(!subscriptions_ready($pdo)){http_response_code(503);exit('Accounts require the latest database upgrade.');}
$filters=['q'=>trim((string)($_GET['q']??'')),'status'=>(string)($_GET['status']??''),'subscription_status'=>(string)($_GET['subscription_status']??''),'package'=>(string)($_GET['package']??'')];
$accounts=admin_ui_account_rows($pdo,$filters,300);$packages=subscription_packages($pdo,false);
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Accounts · Annotated Admin</title><link rel="stylesheet" href="/assets/css/app.css"></head><body><?=admin_ui_sidebar('accounts')?>
<main class="panel adminAccountsPage"><div class="pageTitle"><span class="eyebrow">ACCOUNTS & BILLING</span><h1>Commercial accounts</h1><p>Inspect account ownership, subscription state, package entitlement, members, period dates, and current AI allowance consumption. Research Teams remain a separate collaboration model.</p></div>
<form method="get" class="card adminAccountFilters"><label>Search<input name="q" value="<?=h($filters['q'])?>" placeholder="Account, user, email or ID"></label><label>Account status<select name="status"><option value="">All</option><?php foreach(['active','suspended','closed'] as $v):?><option value="<?=h($v)?>" <?=$filters['status']===$v?'selected':''?>><?=h(ucfirst($v))?></option><?php endforeach?></select></label><label>Subscription<select name="subscription_status"><option value="">All</option><?php foreach(['trialing','active','paused','canceled'] as $v):?><option value="<?=h($v)?>" <?=$filters['subscription_status']===$v?'selected':''?>><?=h(ucfirst($v))?></option><?php endforeach?></select></label><label>Package<select name="package"><option value="">All</option><?php foreach($packages as $p):?><option value="<?=h((string)$p['public_id'])?>" <?=$filters['package']===$p['public_id']?'selected':''?>><?=h((string)$p['name'])?></option><?php endforeach?></select></label><div class="inlineActions"><button>Filter</button><a class="button secondary" href="/admin/accounts.php">Reset</a></div></form>
<div class="sectionHeadWeb"><div><span class="eyebrow">RESULTS</span><h2><?=h(number_format(count($accounts)))?> accounts</h2></div><div class="inlineActions"><a class="button secondary" href="/admin/users.php">Manage users</a><a class="button secondary" href="/admin/packages.php">Manage packages</a><a class="button secondary" href="/admin/usage.php">AI usage</a></div></div>
<div class="tableWrap"><table><thead><tr><th>Account</th><th>Owner</th><th>Package</th><th>Subscription</th><th>Members</th><th>AI allowance</th><th>Period</th></tr></thead><tbody>
<?php foreach($accounts as $a):$s=$a['usage']??null;?><tr><td><strong><?=h((string)$a['name'])?></strong><div class="meta"><?=h((string)$a['public_id'])?> · <?=h((string)$a['account_type'])?></div><div class="meta">Account <?=h((string)$a['status'])?></div></td><td><?=h((string)($a['display_name']?:'—'))?><?php if($a['username']):?><div class="meta">@<?=h((string)$a['username'])?></div><?php endif?><?php if($a['email']):?><div class="meta"><?=h((string)$a['email'])?></div><?php endif?></td><td><strong><?=h((string)$a['package_name'])?></strong><div class="meta"><?=h((string)$a['package_slug'])?></div></td><td><?=h((string)$a['subscription_status'])?><?php if($a['trial_ends_at']):?><div class="meta">Trial ends <?=h((string)$a['trial_ends_at'])?></div><?php endif?></td><td><?=h((string)$a['member_count'])?> / <?=h((string)$a['member_limit'])?></td><td><?php if($s):?><?=h(number_format((int)$s['used_tokens']))?> used<div class="meta"><?=$s['remaining_tokens']===null?'Uncapped / not configured':h(number_format((int)$s['remaining_tokens'])).' remaining'?></div><?php else:?>—<?php endif?></td><td><?=h((string)$a['period_start'])?> → <?=h((string)$a['period_end'])?></td></tr><?php endforeach?>
<?php if(!$accounts):?><tr><td colspan="7" class="empty">No accounts match these filters.</td></tr><?php endif?>
</tbody></table></div></main></body></html>
