<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
$admin=require_admin($pdo);$success='';$error='';$accountAdminReady=account_admin_ready($pdo);
if(!subscriptions_ready($pdo)){http_response_code(503);exit('Accounts require the latest database upgrade.');}
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();try{
    if(!$accountAdminReady)throw new RuntimeException('Run the latest database upgrade before creating managed accounts.');
    if((string)($_POST['action']??'')!=='create_account')throw new RuntimeException('Unknown account action.');
    $created=account_admin_create($pdo,$admin,$_POST);header('Location:/admin/account.php?id='.rawurlencode((string)$created['public_id']));exit;
}catch(Throwable $e){$error=$e->getMessage();}}
$filters=['q'=>trim((string)($_GET['q']??'')),'status'=>(string)($_GET['status']??''),'subscription_status'=>(string)($_GET['subscription_status']??''),'package'=>(string)($_GET['package']??'')];
$accounts=admin_ui_account_rows($pdo,$filters,300);$packages=subscription_packages($pdo,false);
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Accounts · Annotated Admin</title><link rel="stylesheet" href="/assets/css/app.css"></head><body><?=admin_ui_sidebar('accounts')?>
<main class="panel adminAccountsPage"><div class="pageTitle"><span class="eyebrow">ACCOUNTS & BILLING</span><h1>Commercial accounts</h1><p>Manage account ownership, lifecycle, subscription state, package entitlements, members, and account-specific overrides. Research Teams remain a separate collaboration model with independent research permissions.</p></div>
<?php if($error):?><div class="error"><?=h($error)?></div><?php endif?><?php if(!$accountAdminReady):?><div class="error">Account lifecycle administration requires the latest database upgrade.</div><?php endif?>
<?php if($accountAdminReady):?><details class="card adminAccountCreate"><summary><strong>+ Create organization account</strong></summary><form method="post" class="adminAccountCreateForm"><?=csrf_field()?><input type="hidden" name="action" value="create_account"><label>Name<input name="name" required maxlength="190" placeholder="Acme Research"></label><label>Type<select name="account_type"><option value="organization">Organization</option><option value="internal">Internal</option></select></label><label>Owner<input name="owner" required placeholder="username, email or user ID"></label><label>Package<select name="package_id" required><?php foreach($packages as $p):if($p['status']!=='active')continue;?><option value="<?=h((string)$p['public_id'])?>"><?=h((string)$p['name'])?></option><?php endforeach?></select></label><label>Reason<input name="reason" required maxlength="500" placeholder="Why this account is being created"></label><button>Create account</button></form></details><?php endif?>
<form method="get" class="card adminAccountFilters"><label>Search<input name="q" value="<?=h($filters['q'])?>" placeholder="Account, user, email or ID"></label><label>Account status<select name="status"><option value="">All</option><?php foreach(['active','suspended','closed'] as $v):?><option value="<?=h($v)?>" <?=$filters['status']===$v?'selected':''?>><?=h(ucfirst($v))?></option><?php endforeach?></select></label><label>Subscription<select name="subscription_status"><option value="">All</option><?php foreach(['trialing','active','past_due','paused','canceled'] as $v):?><option value="<?=h($v)?>" <?=$filters['subscription_status']===$v?'selected':''?>><?=h(ucfirst($v))?></option><?php endforeach?></select></label><label>Package<select name="package"><option value="">All</option><?php foreach($packages as $p):?><option value="<?=h((string)$p['public_id'])?>" <?=$filters['package']===$p['public_id']?'selected':''?>><?=h((string)$p['name'])?></option><?php endforeach?></select></label><div class="inlineActions"><button>Filter</button><a class="button secondary" href="/admin/accounts.php">Reset</a></div></form>
<div class="sectionHeadWeb"><div><span class="eyebrow">RESULTS</span><h2><?=h(number_format(count($accounts)))?> accounts</h2></div><div class="inlineActions"><a class="button secondary" href="/admin/users.php">Manage users</a><a class="button secondary" href="/admin/packages.php">Manage packages</a><a class="button secondary" href="/admin/usage.php">AI usage</a></div></div>
<div class="tableWrap"><table><thead><tr><th>Account</th><th>Owner</th><th>Package</th><th>Subscription</th><th>Members</th><th>AI allowance</th><th>Period</th><th></th></tr></thead><tbody>
<?php foreach($accounts as $a):$s=$a['usage']??null;?><tr><td><strong><?=h((string)$a['name'])?></strong><div class="meta"><?=h((string)$a['public_id'])?> · <?=h((string)$a['account_type'])?></div><div class="meta">Account <?=h((string)$a['status'])?><?=$a['override_count']??0?' · '.h((string)$a['override_count']).' active override(s)':''?><?=!empty($a['over_capacity'])?' · OVER MEMBER LIMIT':''?></div></td><td><?=h((string)($a['owner_display_name']?:$a['display_name']?:'—'))?><?php if($a['owner_username']??$a['username']):?><div class="meta">@<?=h((string)($a['owner_username']??$a['username']))?></div><?php endif?></td><td><strong><?=h((string)$a['package_name'])?></strong><div class="meta"><?=h((string)$a['package_slug'])?></div></td><td><?=h((string)$a['subscription_status'])?><?php if($a['trial_ends_at']):?><div class="meta">Trial ends <?=h((string)$a['trial_ends_at'])?></div><?php endif?></td><td><?=h((string)$a['member_count'])?> / <?=h((string)($a['effective_member_limit']??$a['member_limit']))?></td><td><?php if($s):?><?=h(number_format((int)$s['used_tokens']))?> used<div class="meta"><?=$s['remaining_tokens']===null?'Uncapped / not configured':h(number_format((int)$s['remaining_tokens'])).' remaining'?><?php if(($s['entitlement_source']??'package')==='override'):?> · override<?php endif?></div><?php else:?>—<?php endif?></td><td><?=h((string)$a['period_start'])?> → <?=h((string)$a['period_end'])?></td><td><?php if($accountAdminReady):?><a class="button secondary" href="/admin/account.php?id=<?=h(rawurlencode((string)$a['public_id']))?>">Manage</a><?php endif?></td></tr><?php endforeach?>
<?php if(!$accounts):?><tr><td colspan="8" class="empty">No accounts match these filters.</td></tr><?php endif?>
</tbody></table></div></main></body></html>
