<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
$admin=require_admin($pdo);if(!account_admin_ready($pdo)){http_response_code(503);exit('Account lifecycle administration requires the latest database upgrade.');}
$id=trim((string)($_GET['id']??$_POST['id']??''));$account=$id!==''?account_admin_get($pdo,$id):null;if(!$account){http_response_code(404);exit('Account not found.');}
$success='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();try{
    $action=(string)($_POST['action']??'');$reason=(string)($_POST['reason']??'');
    if($action==='lifecycle'){$account=account_admin_update_lifecycle($pdo,$admin,(string)$account['public_id'],$_POST);$success='Account lifecycle updated.';}
    elseif($action==='package'){$account=account_admin_change_package($pdo,$admin,(string)$account['public_id'],(string)($_POST['package_id']??''),$reason);$success='Account package updated.';}
    elseif($action==='add_member'){account_admin_add_member($pdo,$admin,(string)$account['public_id'],(string)($_POST['user_identifier']??''),(string)($_POST['account_role']??'member'),$reason);$success='Account member added.';}
    elseif($action==='member_role'){account_admin_update_member_role($pdo,$admin,(string)$account['public_id'],(int)($_POST['user_id']??0),(string)($_POST['account_role']??'member'),$reason);$success='Member role updated.';}
    elseif($action==='remove_member'){account_admin_remove_member($pdo,$admin,(string)$account['public_id'],(int)($_POST['user_id']??0),$reason);$success='Member removed.';}
    elseif($action==='transfer_owner'){$account=account_admin_transfer_owner($pdo,$admin,(string)$account['public_id'],(int)($_POST['user_id']??0),$reason);$success='Account ownership transferred.';}
    elseif($action==='set_token_override'){$mode=(string)($_POST['token_mode']??'set');$value=$mode==='unlimited'?null:max(0,(int)($_POST['token_value']??0));account_admin_set_override($pdo,$admin,(string)$account['public_id'],'monthly_ai_token_allowance',$value,trim((string)($_POST['expires_at']??''))?:null,$reason);$success='AI token entitlement override saved.';}
    elseif($action==='set_member_override'){account_admin_set_override($pdo,$admin,(string)$account['public_id'],'member_limit',max(1,(int)($_POST['member_limit']??1)),trim((string)($_POST['expires_at']??''))?:null,$reason);$success='Member-limit entitlement override saved.';}
    elseif($action==='set_feature_override'){
        $feature=preg_replace('/[^a-z0-9_.-]+/','',strtolower(trim((string)($_POST['feature_key']??''))))?:'';if($feature==='')throw new InvalidArgumentException('Feature key is required.');
        $type=(string)($_POST['value_type']??'boolean');$raw=trim((string)($_POST['feature_value']??''));if($type==='boolean')$value=in_array(strtolower($raw),['1','true','yes','on'],true);elseif($type==='integer')$value=(int)$raw;elseif($type==='json'){$value=json_decode($raw,true,512,JSON_THROW_ON_ERROR);}else $value=$raw;
        account_admin_set_override($pdo,$admin,(string)$account['public_id'],'feature.'.$feature,$value,trim((string)($_POST['expires_at']??''))?:null,$reason);$success='Feature entitlement override saved.';
    }elseif($action==='revoke_override'){account_admin_revoke_override($pdo,$admin,(string)$account['public_id'],(string)($_POST['entitlement_key']??''),$reason);$success='Entitlement override revoked.';}
    else throw new RuntimeException('Unknown account action.');
}catch(Throwable $e){$error=$e->getMessage();}$account=account_admin_get($pdo,(int)$account['id'])??$account;}
$members=account_admin_members($pdo,(int)$account['id']);$ent=account_admin_effective_entitlements($pdo,(int)$account['id']);$overrides=account_admin_overrides($pdo,(int)$account['id'],false);$events=account_admin_events($pdo,(int)$account['id'],100);$packages=subscription_packages($pdo,true);$usage=ai_usage_ready($pdo)?ai_usage_account_summary($pdo,(int)$account['id']):null;
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=h((string)$account['name'])?> · Annotated Admin</title><link rel="stylesheet" href="/assets/css/app.css"></head><body><?=admin_ui_sidebar('accounts')?>
<main class="panel adminAccountDetailPage"><div class="pageTitle"><span class="eyebrow">ACCOUNT LIFECYCLE</span><h1><?=h((string)$account['name'])?></h1><p><?=h((string)$account['public_id'])?> · <?=h((string)$account['account_type'])?> account. Commercial membership and entitlements remain separate from Research Teams and research permissions.</p></div>
<?php if($success):?><div class="success"><?=h($success)?></div><?php endif?><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?>
<div class="inlineActions"><a class="button secondary" href="/admin/accounts.php">← Accounts</a><a class="button secondary" href="/admin/billing.php">Billing & Stripe</a><a class="button secondary" href="/admin/usage.php">AI Usage</a></div>
<section class="adminAccountSummaryGrid"><article class="card"><span class="meta">Account status</span><strong><?=h((string)$account['status'])?></strong></article><article class="card"><span class="meta">Subscription</span><strong><?=h((string)$account['subscription_status'])?></strong></article><article class="card"><span class="meta">Package</span><strong><?=h((string)$account['package_name'])?></strong><small><?=h((string)($account['billing_source']??'manual'))?> billing</small></article><article class="card"><span class="meta">Members</span><strong><?=h((string)count($members))?> / <?=h((string)$ent['values']['member_limit'])?></strong></article><article class="card"><span class="meta">AI tokens used</span><strong><?=$usage?h(number_format((int)$usage['used_tokens'])):'—'?></strong></article><article class="card"><span class="meta">AI tokens remaining</span><strong><?=$usage?($usage['remaining_tokens']===null?'Uncapped':h(number_format((int)$usage['remaining_tokens']))):'—'?></strong></article></section>
<section class="adminAccountTwoCol"><article class="card"><span class="eyebrow">LIFECYCLE</span><h2>Account state</h2><form method="post" class="stack"><?=csrf_field()?><input type="hidden" name="id" value="<?=h((string)$account['public_id'])?>"><input type="hidden" name="action" value="lifecycle"><label>Account name<input name="name" required maxlength="190" value="<?=h((string)$account['name'])?>"></label><label>Account status<select name="status"><?php foreach(['active','suspended','closed'] as $v):?><option value="<?=h($v)?>" <?=$account['status']===$v?'selected':''?>><?=h(ucfirst($v))?></option><?php endforeach?></select></label><label>Subscription status<select name="subscription_status"><?php foreach(['trialing','active','past_due','paused','canceled'] as $v):?><option value="<?=h($v)?>" <?=$account['subscription_status']===$v?'selected':''?>><?=h(ucfirst($v))?></option><?php endforeach?></select></label><label>Reason<textarea name="reason" rows="2" required></textarea></label><button>Save lifecycle</button></form></article>
<article class="card"><span class="eyebrow">PACKAGE</span><h2>Commercial package</h2><p><strong><?=h((string)$account['package_name'])?></strong><br><span class="meta">Period <?=h((string)$account['period_start'])?> → <?=h((string)$account['period_end'])?></span></p><form method="post" class="stack"><?=csrf_field()?><input type="hidden" name="id" value="<?=h((string)$account['public_id'])?>"><input type="hidden" name="action" value="package"><label>Package<select name="package_id"><?php foreach($packages as $p):?><option value="<?=h((string)$p['public_id'])?>" <?=$p['public_id']===$account['package_public_id']?'selected':''?>><?=h((string)$p['name'])?></option><?php endforeach?></select></label><label>Reason<textarea name="reason" rows="2" required></textarea></label><button>Change package</button></form></article></section>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">MEMBERSHIP</span><h2>Account members</h2></div><span class="badge">Effective limit <?=h((string)$ent['values']['member_limit'])?></span></div><form method="post" class="adminMemberAddForm"><?=csrf_field()?><input type="hidden" name="id" value="<?=h((string)$account['public_id'])?>"><input type="hidden" name="action" value="add_member"><label>User<input name="user_identifier" required placeholder="username, email or user ID"></label><label>Role<select name="account_role"><option value="member">Member</option><option value="admin">Account admin</option></select></label><label>Reason<input name="reason" required maxlength="500"></label><button>Add member</button></form>
<div class="tableWrap"><table><thead><tr><th>User</th><th>Role</th><th>Joined</th><th>Administration</th></tr></thead><tbody><?php foreach($members as $m):?><tr><td><strong><?=h((string)$m['display_name'])?></strong><div class="meta">@<?=h((string)$m['username'])?> · <?=h((string)$m['email'])?></div></td><td><?=h((string)$m['account_role'])?></td><td><?=h((string)$m['joined_at'])?></td><td><?php if($m['account_role']!=='owner'):?><form method="post" class="adminMemberActionForm"><?=csrf_field()?><input type="hidden" name="id" value="<?=h((string)$account['public_id'])?>"><input type="hidden" name="action" value="member_role"><input type="hidden" name="user_id" value="<?=h((string)$m['user_id'])?>"><select name="account_role"><option value="member" <?=$m['account_role']==='member'?'selected':''?>>Member</option><option value="admin" <?=$m['account_role']==='admin'?'selected':''?>>Account admin</option></select><input name="reason" required placeholder="Reason"><button>Update role</button></form><form method="post" class="adminMemberActionForm"><?=csrf_field()?><input type="hidden" name="id" value="<?=h((string)$account['public_id'])?>"><input type="hidden" name="action" value="remove_member"><input type="hidden" name="user_id" value="<?=h((string)$m['user_id'])?>"><input name="reason" required placeholder="Removal reason"><button class="button secondary">Remove</button></form><?php if($account['account_type']!=='personal'):?><form method="post" class="adminMemberActionForm"><?=csrf_field()?><input type="hidden" name="id" value="<?=h((string)$account['public_id'])?>"><input type="hidden" name="action" value="transfer_owner"><input type="hidden" name="user_id" value="<?=h((string)$m['user_id'])?>"><input name="reason" required placeholder="Transfer reason"><button class="button secondary">Make owner</button></form><?php endif?><?php else:?><span class="meta">Owner is protected. Transfer ownership first for organization accounts.</span><?php endif?></td></tr><?php endforeach?></tbody></table></div></section>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">ENTITLEMENTS</span><h2>Package baseline + account overrides</h2></div></div><div class="adminEntitlementSummary"><div><span>Monthly AI tokens</span><strong><?=$ent['values']['monthly_ai_token_allowance']===null?'Uncapped':h(number_format((int)$ent['values']['monthly_ai_token_allowance']))?></strong><small><?=h((string)$ent['sources']['monthly_ai_token_allowance'])?></small></div><div><span>Member limit</span><strong><?=h((string)$ent['values']['member_limit'])?></strong><small><?=h((string)$ent['sources']['member_limit'])?></small></div></div>
<div class="adminAccountTwoCol"><form method="post" class="stack"><?=csrf_field()?><input type="hidden" name="id" value="<?=h((string)$account['public_id'])?>"><input type="hidden" name="action" value="set_token_override"><h3>AI token override</h3><label>Mode<select name="token_mode"><option value="set">Set monthly allowance</option><option value="unlimited">Uncapped</option></select></label><label>Tokens<input type="number" min="0" name="token_value" value="<?=h((string)($ent['values']['monthly_ai_token_allowance']??0))?>"></label><label>Expires at<input type="datetime-local" name="expires_at"></label><label>Reason<textarea name="reason" rows="2" required></textarea></label><button>Save token override</button></form>
<form method="post" class="stack"><?=csrf_field()?><input type="hidden" name="id" value="<?=h((string)$account['public_id'])?>"><input type="hidden" name="action" value="set_member_override"><h3>Member-limit override</h3><label>Member limit<input type="number" min="<?=h((string)count($members))?>" name="member_limit" value="<?=h((string)$ent['values']['member_limit'])?>" required></label><label>Expires at<input type="datetime-local" name="expires_at"></label><label>Reason<textarea name="reason" rows="2" required></textarea></label><button>Save member override</button></form></div>
<details><summary>+ Feature entitlement override</summary><form method="post" class="adminFeatureOverrideForm"><?=csrf_field()?><input type="hidden" name="id" value="<?=h((string)$account['public_id'])?>"><input type="hidden" name="action" value="set_feature_override"><label>Feature key<input name="feature_key" required placeholder="advanced_exports"></label><label>Type<select name="value_type"><option value="boolean">Boolean</option><option value="integer">Integer</option><option value="string">String</option><option value="json">JSON</option></select></label><label>Value<input name="feature_value" required placeholder="true"></label><label>Expires at<input type="datetime-local" name="expires_at"></label><label>Reason<input name="reason" required maxlength="500"></label><button>Save feature override</button></form></details>
<h3>Override registry</h3><div class="tableWrap"><table><thead><tr><th>Key</th><th>Status</th><th>Value</th><th>Expiry</th><th>Reason</th><th></th></tr></thead><tbody><?php foreach($overrides as $o):?><tr><td><code><?=h((string)$o['entitlement_key'])?></code></td><td><?=h((string)$o['status'])?></td><td><code><?=h((string)($o['value_json']??'null'))?></code></td><td><?=h((string)($o['expires_at']?:'—'))?></td><td><?=h((string)$o['reason'])?></td><td><?php if($o['status']==='active'):?><form method="post"><?=csrf_field()?><input type="hidden" name="id" value="<?=h((string)$account['public_id'])?>"><input type="hidden" name="action" value="revoke_override"><input type="hidden" name="entitlement_key" value="<?=h((string)$o['entitlement_key'])?>"><input name="reason" required placeholder="Revocation reason"><button class="button secondary">Revoke</button></form><?php endif?></td></tr><?php endforeach?><?php if(!$overrides):?><tr><td colspan="6" class="empty">No account-level overrides. Package entitlements are authoritative.</td></tr><?php endif?></tbody></table></div></section>
<section class="card"><span class="eyebrow">AUDIT</span><h2>Account administration history</h2><?php foreach($events as $e):?><div class="historyItem"><strong><?=h(ucwords(str_replace('_',' ',(string)$e['event_type'])))?></strong><div class="meta"><?=h((string)$e['created_at'])?> · <?=h((string)($e['actor_username']?:'System'))?><?php if($e['subject_username']):?> · @<?=h((string)$e['subject_username'])?><?php endif?></div><p><?=h((string)$e['reason'])?></p></div><?php endforeach?><?php if(!$events):?><p class="empty">No V1.30 account administration events yet.</p><?php endif?></section>
</main></body></html>
