<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
$admin=require_admin($pdo);if(!admin_ops_ready($pdo)){http_response_code(503);exit('Admin V2.0 Operations requires migration 073.');}
$success='';$error='';$preview=null;$selected=null;$catalog=admin_ops_action_catalog();$accountPublic=trim((string)($_GET['account']??$_POST['account']??''));
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();try{
    $op=(string)($_POST['op']??'');
    if($op==='preview'){admin_access_assert_capability($pdo,$admin,'admin.actions.request');$preview=admin_ops_action_preview($pdo,$admin,(string)($_POST['action_type']??''),(string)($_POST['account']??''),(string)($_POST['reason']??''));$selected=$preview['record'];$accountPublic=(string)($preview['preview']['account_public_id']??$accountPublic);$success='Governed action preview created. Review the exact action and approval requirement below.';}
    elseif($op==='request_approval'){$selected=admin_access_action_request_approval($pdo,$admin,(string)($_POST['record_id']??''));$success='Approval request submitted. A permitted reviewer must approve it before execution.';}
    elseif($op==='approve'){$selected=admin_access_action_decide($pdo,$admin,(string)($_POST['record_id']??''),'approved',(string)($_POST['reason']??''));$success=$selected['status']==='approved'?'Required approvals are satisfied. The requester may execute the action.':'Approval recorded; additional approval is still required.';}
    elseif($op==='reject'){$selected=admin_access_action_decide($pdo,$admin,(string)($_POST['record_id']??''),'rejected',(string)($_POST['reason']??''));$success='Approval request rejected. The action cannot execute.';}
    elseif($op==='execute'){admin_access_assert_capability($pdo,$admin,'admin.actions.execute');$selected=admin_ops_action_execute($pdo,$config,$admin,(string)($_POST['record_id']??''));$success='Governed action executed and recorded.';}
    else throw new RuntimeException('Unknown action-center operation.');
}catch(Throwable $e){$error=$e->getMessage();}}
if(!$selected&&!empty($_GET['record']))$selected=admin_ops_action_record($pdo,(string)$_GET['record']);
$accounts=admin_ui_account_rows($pdo,[],300);$actions=admin_ops_recent_actions($pdo,150);$profile=admin_ops_operator_profile($pdo,$admin);$pending=admin_access_ready($pdo)?admin_access_pending_approvals($pdo,$admin,100):[];$selectedSummary=$selected&&admin_access_ready($pdo)?admin_access_action_approval_summary($pdo,$selected):['required'=>(int)($selected['required_approvals']??0),'approved'=>0,'rejected'=>0,'rows'=>[],'satisfied'=>(int)($selected['required_approvals']??0)===0];
$canRequest=admin_access_has_capability($pdo,$admin,'admin.actions.request');$canApprove=admin_access_has_capability($pdo,$admin,'admin.actions.approve');$canExecute=admin_access_has_capability($pdo,$admin,'admin.actions.execute');
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Action Center · Annotated Admin</title><link rel="stylesheet" href="/assets/css/app.css"></head><body><?=admin_ui_sidebar('action_center')?>
<main class="panel adminActionCenterPage"><div class="pageTitle"><span class="eyebrow">ADMIN V2.10 · GOVERNED OPERATIONS</span><h1>Governed action center</h1><p>Preview operational actions before execution. Approval policies can require a distinct authorized reviewer, and every request, decision, execution result, actor, reason and correlation ID is durable.</p></div>
<?php if($success):?><div class="success"><?=h($success)?></div><?php endif?><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?>
<section class="adminAccountSummaryGrid"><article class="card"><span class="meta">Operator role</span><strong><?=h((string)($profile['role_name']??$profile['role_key']))?></strong></article><article class="card"><span class="meta">Execution model</span><strong>Preview → Approve → Execute</strong><small>Policy-driven separation of duties</small></article><article class="card"><span class="meta">Pending approvals</span><strong><?=h((string)count($pending))?></strong></article><article class="card"><span class="meta">Governed actions</span><strong><?=h((string)count($catalog))?></strong></article></section>
<section class="adminAccountTwoCol"><article class="card"><span class="eyebrow">NEW ACTION</span><h2>Create preview</h2><?php if($canRequest):?><form method="post" class="stack"><?=csrf_field()?><input type="hidden" name="op" value="preview"><label>Account<select name="account" required><option value="">Select account</option><?php foreach($accounts as $a):?><option value="<?=h((string)$a['public_id'])?>" <?=$accountPublic===$a['public_id']?'selected':''?>><?=h((string)$a['name'])?> · <?=h((string)$a['package_name'])?></option><?php endforeach?></select></label><label>Action<select name="action_type" required><?php foreach($catalog as $key=>$meta):if(($meta['surface']??'account')!=='account'||!admin_access_has_capability($pdo,$admin,(string)$meta['capability']))continue;?><option value="<?=h($key)?>"><?=h((string)$meta['label'])?> · <?=h((string)$meta['risk'])?></option><?php endforeach?></select></label><label>Reason<textarea name="reason" rows="3" maxlength="500" required placeholder="Why is this action necessary?"></textarea></label><button>Preview governed action</button></form><?php else:?><p class="empty">Your operator role can view governed actions but cannot request new ones.</p><?php endif?></article>
<article class="card"><span class="eyebrow">BOUNDARIES</span><h2>What V2.10 can execute</h2><?php foreach($catalog as $meta):?><div class="historyItem"><strong><?=h((string)$meta['label'])?></strong><div class="meta"><?=h(strtoupper((string)$meta['risk']))?> RISK · <?=h((string)$meta['capability'])?></div><p><?=h((string)$meta['description'])?></p></div><?php endforeach?><p class="meta">Credits, refunds, lifecycle changes, membership changes, package changes and other mutations remain on their existing explicit Admin surfaces. Delegated route permissions now govern access to those surfaces as well.</p></article></section>
<?php if($selected):$request=json_decode((string)$selected['request_json'],true)?:[];$p=$request['preview']??[];$required=(int)($selected['required_approvals']??0);?><section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">ACTION REVIEW</span><h2><?=h((string)($catalog[$selected['action_type']]['label']??ucwords(str_replace('_',' ',(string)$selected['action_type']))))?></h2></div><span class="badge"><?=h(strtoupper((string)$selected['risk_level']))?> · <?=h(strtoupper((string)$selected['status']))?></span></div><div class="billingSubscriptionFacts"><div><span>Account</span><strong><?=h((string)($selected['account_name']??$p['account_name']??'—'))?></strong></div><div><span>Requester</span><strong>@<?=h((string)$selected['actor_username'])?></strong></div><div><span>Required approvals</span><strong><?=h((string)$required)?></strong></div><div><span>Recorded approvals</span><strong><?=h((string)$selectedSummary['approved'])?></strong></div><div><span>Correlation</span><strong><code><?=h(substr((string)$selected['correlation_id'],0,20))?>…</code></strong></div></div><p><?=h((string)$selected['reason'])?></p><?php if($selected['action_type']==='change_platform_feature'):?><details open><summary>Platform feature change</summary><pre><?=h((string)json_encode(['feature_key'=>$request['feature_key']??null,'before'=>$request['before']??null,'after'=>$request['after']??null],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES))?></pre></details><?php endif?>
<?php if(in_array((string)$selected['action_type'],['change_account_package','set_account_lifecycle'],true)):?><details open><summary>Admin Agent requested change</summary><pre><?=h((string)json_encode($p,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES))?></pre></details><?php endif?>
<?php foreach($selectedSummary['rows'] as $decision):?><div class="historyItem"><strong><?=h(ucfirst((string)$decision['decision']))?> · <?=h((string)($decision['display_name']?:$decision['username']))?></strong><div class="meta"><?=h((string)$decision['created_at'])?></div><p><?=h((string)$decision['reason'])?></p></div><?php endforeach?>
<div class="inlineActions">
<?php if($selected['status']==='previewed'&&$required>0&&(int)$selected['actor_user_id']===(int)$admin['id']&&$canRequest):?><form method="post"><?=csrf_field()?><input type="hidden" name="op" value="request_approval"><input type="hidden" name="record_id" value="<?=h((string)$selected['public_id'])?>"><button>Request approval</button></form><?php endif?>
<?php if($selected['status']==='pending_approval'&&$canApprove&&(int)$selected['actor_user_id']!==(int)$admin['id']):?><form method="post" class="stack"><?=csrf_field()?><input type="hidden" name="op" value="approve"><input type="hidden" name="record_id" value="<?=h((string)$selected['public_id'])?>"><input name="reason" required maxlength="500" placeholder="Approval rationale"><button>Approve</button></form><form method="post" class="stack"><?=csrf_field()?><input type="hidden" name="op" value="reject"><input type="hidden" name="record_id" value="<?=h((string)$selected['public_id'])?>"><input name="reason" required maxlength="500" placeholder="Rejection rationale"><button class="button secondary">Reject</button></form><?php endif?>
<?php if(($selected['status']==='previewed'&&$required===0)||$selected['status']==='approved'):?><?php if((int)$selected['actor_user_id']===(int)$admin['id']&&$canExecute):?><form method="post"><?=csrf_field()?><input type="hidden" name="op" value="execute"><input type="hidden" name="record_id" value="<?=h((string)$selected['public_id'])?>"><button>Execute reviewed action</button></form><?php endif?><?php endif?>
</div></section><?php endif?>
<?php if($pending):?><section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">APPROVAL INBOX</span><h2>Awaiting your review</h2></div><span class="badge"><?=h((string)count($pending))?></span></div><div class="tableWrap"><table><thead><tr><th>Requested</th><th>Action</th><th>Account</th><th>Requester</th><th>Approvals</th><th></th></tr></thead><tbody><?php foreach($pending as $a):?><tr><td><?=h((string)$a['approval_requested_at'])?></td><td><strong><?=h((string)($catalog[$a['action_type']]['label']??$a['action_type']))?></strong><div class="meta"><?=h((string)$a['risk_level'])?></div></td><td><?=h((string)($a['account_name']??'—'))?></td><td>@<?=h((string)$a['actor_username'])?></td><td><?=h((string)$a['approval_summary']['approved'])?> / <?=h((string)$a['approval_summary']['required'])?></td><td><?php if(empty($a['distinct_from_requester'])||(int)$a['actor_user_id']!==(int)$admin['id']):?><a class="button secondary" href="/admin/action-center.php?record=<?=h(rawurlencode((string)$a['public_id']))?>">Review</a><?php else:?><span class="meta">Requester cannot self-approve.</span><?php endif?></td></tr><?php endforeach?></tbody></table></div></section><?php endif?>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">ACTION LEDGER</span><h2>Recent governed Admin actions</h2></div></div><div class="tableWrap"><table><thead><tr><th>Time</th><th>Action</th><th>Account</th><th>Actor</th><th>Risk</th><th>Status</th><th>Approvals</th><th>Reason</th><th>Correlation</th></tr></thead><tbody><?php foreach($actions as $a):$summary=admin_access_ready($pdo)?admin_access_action_approval_summary($pdo,$a):['approved'=>0,'required'=>0];?><tr><td><?=h((string)$a['created_at'])?></td><td><a href="/admin/action-center.php?record=<?=h(rawurlencode((string)$a['public_id']))?>"><?=h(ucwords(str_replace('_',' ',(string)$a['action_type'])))?></a></td><td><?php if($a['account_public_id']):?><a href="/admin/account.php?id=<?=h(rawurlencode((string)$a['account_public_id']))?>"><?=h((string)$a['account_name'])?></a><?php else:?>—<?php endif?></td><td><?=h((string)$a['actor_username'])?></td><td><?=h((string)$a['risk_level'])?></td><td><?=h((string)$a['status'])?></td><td><?=h((string)$summary['approved'])?> / <?=h((string)$summary['required'])?></td><td><?=h((string)$a['reason'])?></td><td><code><?=h(substr((string)$a['correlation_id'],0,16))?>…</code></td></tr><?php endforeach?><?php if(!$actions):?><tr><td colspan="9" class="empty">No V2.0 governed actions yet.</td></tr><?php endif?></tbody></table></div></section>
</main></body></html>
