<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
if(PHP_SAPI!=='cli')header('Cache-Control: no-store, private');
$admin=require_admin($pdo);if(!billing_operations_ready($pdo)){http_response_code(503);exit('Billing Analytics requires the latest database upgrade.');}
$success='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();try{
    $op=(string)($_POST['op']??'');$reason=trim((string)($_POST['reason']??''));
    if($op==='settings'){$settings=billing_operations_save_settings($pdo,$admin,$_POST);$success='Billing operations settings updated.';}
    elseif($op==='snapshot'){$snap=billing_operations_snapshot_day($pdo);$success='Billing snapshot rebuilt for '.(string)$snap['snapshot_date'].'.';}
    elseif($op==='run_dunning'){$r=billing_operations_process_due_dunning($pdo,$admin);billing_operations_snapshot_day($pdo);$success='Dunning review complete: '.$r['reviewed'].' reviewed, '.$r['suspended'].' suspended, '.$r['grace'].' retained in grace.';}
    elseif($op==='grant_grace'){billing_operations_grant_grace($pdo,$admin,(string)($_POST['case_id']??''),(int)($_POST['days']??7),$reason?:'Administrator granted temporary billing grace.');$success='Dunning grace updated.';}
    elseif($op==='note'){billing_operations_add_note($pdo,$admin,(string)($_POST['account_id']??''),(string)($_POST['note_type']??'general'),(string)($_POST['body']??''));$success='Billing note added.';}
    elseif($op==='extend_trial'){billing_operations_extend_trial($pdo,$config,$admin,(string)($_POST['account_id']??''),(int)($_POST['days']??7),$reason?:'Administrator extended the Stripe trial.');$success='Stripe trial extended and resynchronized.';}
    elseif($op==='resync'){billing_operations_resync_account($pdo,$config,$admin,(string)($_POST['account_id']??''));billing_operations_snapshot_day($pdo);$success='Account resynchronized from Stripe.';}
    elseif($op==='feedback'){billing_operations_record_cancellation_feedback($pdo,$admin,(string)($_POST['account_id']??''),'admin',(string)($_POST['reason_code']??'other'),(string)($_POST['feedback_text']??''),!empty($_POST['win_back_eligible']));$success='Cancellation feedback recorded.';}
    else throw new RuntimeException('Unknown billing operations action.');
}catch(Throwable $e){$error=$e->getMessage();}}
$settings=billing_operations_settings($pdo);$metrics=billing_operations_current_metrics($pdo);$snapshots=billing_operations_daily_snapshots($pdo,45);$latest=$snapshots[0]??null;$packages=billing_operations_revenue_by_package($pdo);$dunning=billing_operations_dunning_cases($pdo,200);$trials=billing_operations_trial_accounts($pdo);$alerts=billing_operations_alerts($pdo,100);$feedback=billing_operations_feedback($pdo,null,100);$commercial=commercial_promotions_ready($pdo)?commercial_revenue_adjustment_summary($pdo,30):['gross_cents'=>0,'discount_cents'=>0,'net_cents'=>0,'credit_issued_cents'=>0,'debit_issued_cents'=>0];$taxMetrics=commercial_billing_ready($pdo)?commercial_billing_tax_summary($pdo,30):['tax_cents'=>0,'invoice_count'=>0,'automatic_tax_count'=>0,'tax_id_accounts'=>0,'drift_count'=>0];
$money=fn(int $c)=>'$'.number_format($c/100,2);
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Billing Analytics · Annotated Admin</title><link rel="stylesheet" href="/assets/css/app.css"></head><body><?=admin_ui_sidebar('billing_analytics')?>
<main class="panel adminBillingAnalyticsPage"><div class="pageTitle"><span class="eyebrow">ADMIN V1.60</span><h1>Billing analytics, revenue operations & dunning</h1><p>Stripe remains payment truth. Annotated derives revenue operations, dunning state, snapshots, alerts and auditable Admin decisions.</p></div>
<?php if($success):?><div class="success"><?=h($success)?></div><?php endif?><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?>
<section class="billingKpiGrid">
<article class="card"><span class="meta">MRR</span><strong><?=h($money((int)$metrics['mrr_cents']))?></strong><small>active + past due paid accounts</small></article>
<article class="card"><span class="meta">ARR run-rate</span><strong><?=h($money((int)$metrics['arr_cents']))?></strong><small>12 × current MRR</small></article>
<article class="card"><span class="meta">Collected · 30d</span><strong><?=h($money((int)$metrics['collected_30d_cents']))?></strong><small>paid Stripe invoices</small></article>
<article class="card"><span class="meta">Active</span><strong><?=h((string)$metrics['active_subscriptions'])?></strong><small><?=h((string)$metrics['trialing_subscriptions'])?> trialing</small></article>
<article class="card"><span class="meta">Past due</span><strong><?=h((string)$metrics['past_due_subscriptions'])?></strong><small><?=h((string)$metrics['open_dunning_cases'])?> open dunning</small></article>
<?php if($latest):?><article class="card"><span class="meta">Latest snapshot</span><strong><?=h((string)$latest['snapshot_date'])?></strong><small><?=h((string)$latest['stripe_mode'])?> mode</small></article><?php endif?>
</section>
<?php if(commercial_billing_ready($pdo)):?><section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">TAX & INVOICE EVIDENCE · 30D</span><h2>Tax collection and invoice integrity</h2></div><a class="button secondary" href="/admin/tax-invoices.php">Tax & invoices</a></div><div class="billingMovementGrid"><div><span>Tax recorded</span><strong><?=h($money((int)$taxMetrics['tax_cents']))?></strong></div><div><span>Invoices</span><strong><?=h((string)$taxMetrics['invoice_count'])?></strong></div><div><span>Automatic-tax invoices</span><strong><?=h((string)$taxMetrics['automatic_tax_count'])?></strong></div><div><span>Tax-ID accounts</span><strong><?=h((string)$taxMetrics['tax_id_accounts'])?></strong></div><div><span>Evidence drift</span><strong><?=h((string)$taxMetrics['drift_count'])?></strong></div></div></section><?php endif?>
<?php if(commercial_promotions_ready($pdo)):?><section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">COMMERCIAL ADJUSTMENTS · 30D</span><h2>Gross, discounts, credits & net</h2></div><a class="button secondary" href="/admin/promotions.php">Promotions & credits</a></div><div class="billingMovementGrid"><div><span>Gross subtotal</span><strong><?=h($money((int)$commercial['gross_cents']))?></strong></div><div><span>Promotion discounts</span><strong><?=h($money((int)$commercial['discount_cents']))?></strong></div><div><span>Net invoice total</span><strong><?=h($money((int)$commercial['net_cents']))?></strong></div><div><span>Credits issued</span><strong><?=h($money((int)$commercial['credit_issued_cents']))?></strong></div><div><span>Debits issued</span><strong><?=h($money((int)$commercial['debit_issued_cents']))?></strong></div></div><p class="meta">These are Stripe-invoice discount events and customer-balance adjustments recorded by V1.80. They remain separate from list-price MRR so discounts and credits are never hidden inside the recurring-revenue baseline.</p></section><?php endif?>
<section class="adminBillingGrid"><article class="card"><span class="eyebrow">OPERATIONS POLICY</span><h2>Dunning & trial settings</h2><form method="post" class="stack"><?=csrf_field()?><input type="hidden" name="op" value="settings"><label>Grace period days<input type="number" min="0" max="60" name="dunning_grace_days" value="<?=h((string)$settings['dunning_grace_days'])?>"></label><label>Trial reminder window<input type="number" min="1" max="30" name="trial_reminder_days" value="<?=h((string)$settings['trial_reminder_days'])?>"></label><label><input type="checkbox" name="suspend_after_grace" value="1" <?=!empty($settings['suspend_after_grace'])?'checked':''?>> Suspend account access after grace expires</label><label><input type="checkbox" name="restore_after_payment" value="1" <?=!empty($settings['restore_after_payment'])?'checked':''?>> Restore V1.60-owned suspension after payment recovery</label><button>Save policy</button></form><p class="meta">Automatic suspension is off by default. Manual lifecycle changes always take precedence over dunning restoration.</p></article>
<article class="card"><span class="eyebrow">RUN OPERATIONS</span><h2>Snapshot & dunning worker</h2><div class="inlineActions"><form method="post"><?=csrf_field()?><input type="hidden" name="op" value="snapshot"><button>Snapshot now</button></form><form method="post"><?=csrf_field()?><input type="hidden" name="op" value="run_dunning"><button class="button secondary">Review due dunning</button></form></div><p class="meta">Production scheduling: run <code>php bin/billing-operations.php</code> daily. Re-running a day updates the same mode/date snapshot instead of duplicating it.</p></article></section>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">REVENUE BY PACKAGE</span><h2>Current recurring revenue</h2></div></div><div class="tableWrap"><table><thead><tr><th>Package</th><th>List price</th><th>Billable accounts</th><th>MRR</th><th>Trials</th><th>Past due</th></tr></thead><tbody><?php foreach($packages as $p):?><tr><td><strong><?=h((string)$p['package_name'])?></strong></td><td><?=h($money((int)$p['monthly_price_cents']))?></td><td><?=h((string)$p['billable_accounts'])?></td><td><?=h($money((int)$p['mrr_cents']))?></td><td><?=h((string)$p['trialing_accounts'])?></td><td><?=h((string)$p['past_due_accounts'])?></td></tr><?php endforeach?></tbody></table></div></section>
<?php if($latest):?><section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">LATEST DAILY MOVEMENT</span><h2><?=h((string)$latest['snapshot_date'])?></h2></div></div><div class="billingMovementGrid"><div><span>New MRR</span><strong><?=h($money((int)$latest['new_mrr_cents']))?></strong></div><div><span>Expansion</span><strong><?=h($money((int)$latest['expansion_mrr_cents']))?></strong></div><div><span>Contraction</span><strong><?=h($money((int)$latest['contraction_mrr_cents']))?></strong></div><div><span>Churn</span><strong><?=h($money((int)$latest['churned_mrr_cents']))?></strong></div><div><span>Recovered</span><strong><?=h($money((int)$latest['recovered_mrr_cents']))?></strong></div><div><span>Collected</span><strong><?=h($money((int)$latest['gross_collected_cents']))?></strong></div><div><span>Failed</span><strong><?=h($money((int)$latest['failed_amount_cents']))?></strong></div><div><span>Refunded</span><strong><?=h($money((int)$latest['refunded_amount_cents']))?></strong></div><div><span>Disputed</span><strong><?=h($money((int)$latest['disputed_amount_cents']))?></strong></div></div></section><?php endif?>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">ATTENTION</span><h2>Billing alerts</h2></div><span class="badge"><?=h((string)count($alerts))?></span></div><?php foreach($alerts as $a):?><div class="historyItem billingAlert <?=h((string)$a['severity'])?>"><strong><?=h((string)$a['label'])?></strong><div class="meta"><?=h((string)$a['type'])?> · <?=h((string)$a['detail'])?><?php if($a['account_public_id']):?> · <a href="/admin/account.php?id=<?=h(rawurlencode((string)$a['account_public_id']))?>">Account</a><?php endif?></div></div><?php endforeach?><?php if(!$alerts):?><p class="empty">No current billing alerts.</p><?php endif?></section>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">DUNNING</span><h2>Payment recovery cases</h2></div></div><div class="tableWrap"><table><thead><tr><th>Account</th><th>Status</th><th>Invoice</th><th>Amount</th><th>Failures</th><th>Grace</th><th>Operations</th></tr></thead><tbody><?php foreach($dunning as $d):?><tr><td><a href="/admin/account.php?id=<?=h(rawurlencode((string)$d['account_public_id']))?>"><?=h((string)$d['account_name'])?></a><div class="meta"><?=h((string)$d['package_name'])?></div></td><td><?=h((string)$d['status'])?></td><td><code><?=h((string)$d['stripe_invoice_id'])?></code></td><td><?=h($money((int)$d['amount_due_cents']))?></td><td><?=h((string)$d['failure_count'])?></td><td><?=h((string)($d['grace_until']?:'—'))?></td><td><?php if(!in_array($d['status'],['recovered','uncollectible','closed'],true)):?><form method="post" class="inlineActions"><?=csrf_field()?><input type="hidden" name="op" value="grant_grace"><input type="hidden" name="case_id" value="<?=h((string)$d['public_id'])?>"><input type="number" name="days" min="1" max="60" value="7" aria-label="Grace days"><input name="reason" value="Administrator granted temporary billing grace." required><button class="button secondary">Grant grace</button></form><?php endif?><form method="post" class="inlineActions"><?=csrf_field()?><input type="hidden" name="op" value="resync"><input type="hidden" name="account_id" value="<?=h((string)$d['account_public_id'])?>"><button class="button secondary">Resync Stripe</button></form></td></tr><?php endforeach?><?php if(!$dunning):?><tr><td colspan="7" class="empty">No dunning cases yet.</td></tr><?php endif?></tbody></table></div></section>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">TRIALS</span><h2>Trials ending within <?=h((string)$settings['trial_reminder_days'])?> days</h2></div></div><div class="tableWrap"><table><thead><tr><th>Account</th><th>Package</th><th>Trial end</th><th>Extend</th></tr></thead><tbody><?php foreach($trials as $t):?><tr><td><a href="/admin/account.php?id=<?=h(rawurlencode((string)$t['account_public_id']))?>"><?=h((string)$t['account_name'])?></a></td><td><?=h((string)$t['package_name'])?></td><td><?=h((string)$t['trial_end'])?></td><td><form method="post" class="inlineActions"><?=csrf_field()?><input type="hidden" name="op" value="extend_trial"><input type="hidden" name="account_id" value="<?=h((string)$t['account_public_id'])?>"><input type="number" name="days" min="1" max="90" value="7"><input name="reason" value="Administrator extended the Stripe trial." required><button class="button secondary">Extend</button></form></td></tr><?php endforeach?><?php if(!$trials):?><tr><td colspan="4" class="empty">No trials in the reminder window.</td></tr><?php endif?></tbody></table></div></section>
<section class="adminBillingGrid"><article class="card"><span class="eyebrow">BILLING NOTE</span><h2>Add internal note</h2><form method="post" class="stack"><?=csrf_field()?><input type="hidden" name="op" value="note"><label>Account public ID<input name="account_id" required placeholder="acct-…"></label><label>Type<select name="note_type"><option>general</option><option>dunning</option><option>trial</option><option>cancellation</option><option>dispute</option></select></label><label>Note<textarea name="body" required rows="4"></textarea></label><button>Add note</button></form></article>
<article class="card"><span class="eyebrow">CANCELLATION INTELLIGENCE</span><h2>Record cancellation feedback</h2><form method="post" class="stack"><?=csrf_field()?><input type="hidden" name="op" value="feedback"><label>Account public ID<input name="account_id" required placeholder="acct-…"></label><label>Reason<select name="reason_code"><option value="price">Price</option><option value="missing_features">Missing features</option><option value="not_using">Not using</option><option value="temporary">Temporary</option><option value="support">Support</option><option value="competitor">Competitor</option><option value="business_closed">Business closed</option><option value="other">Other</option></select></label><label>Feedback<textarea name="feedback_text" rows="4"></textarea></label><label><input type="checkbox" name="win_back_eligible" value="1" checked> Win-back eligible</label><button>Record feedback</button></form></article></section>
<section class="card"><span class="eyebrow">RECENT CANCELLATION FEEDBACK</span><h2>Customer & Admin reasons</h2><?php foreach($feedback as $f):?><div class="historyItem"><strong><?=h((string)$f['account_name'])?> · <?=h((string)$f['reason_code'])?></strong><div class="meta"><?=h((string)$f['source'])?> · <?=h((string)$f['created_at'])?> · win-back <?=((int)$f['win_back_eligible'])?'yes':'no'?></div><?php if($f['feedback_text']):?><p><?=h((string)$f['feedback_text'])?></p><?php endif?></div><?php endforeach?><?php if(!$feedback):?><p class="empty">No cancellation feedback recorded yet.</p><?php endif?></section>
<section class="card"><span class="eyebrow">DAILY HISTORY</span><h2>Recent billing snapshots</h2><div class="tableWrap"><table><thead><tr><th>Date</th><th>MRR</th><th>ARR</th><th>Active</th><th>Trial</th><th>Past due</th><th>Open dunning</th><th>Collected</th></tr></thead><tbody><?php foreach($snapshots as $s):?><tr><td><?=h((string)$s['snapshot_date'])?></td><td><?=h($money((int)$s['mrr_cents']))?></td><td><?=h($money((int)$s['arr_cents']))?></td><td><?=h((string)$s['active_subscriptions'])?></td><td><?=h((string)$s['trialing_subscriptions'])?></td><td><?=h((string)$s['past_due_subscriptions'])?></td><td><?=h((string)$s['open_dunning_cases'])?></td><td><?=h($money((int)$s['gross_collected_cents']))?></td></tr><?php endforeach?><?php if(!$snapshots):?><tr><td colspan="8" class="empty">Run the first billing snapshot to begin historical reporting.</td></tr><?php endif?></tbody></table></div></section>
</main></body></html>