<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
$admin=require_admin($pdo);$success='';$error='';$testResult='';
if(!stripe_billing_ready($pdo)){http_response_code(503);exit('Stripe Billing requires the latest database upgrade.');}
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();try{
    $op=(string)($_POST['op']??'');
    if($op==='settings'){stripe_billing_save_settings($pdo,$config,$admin,$_POST);$success='Stripe billing settings saved.';}
    elseif($op==='test'){$acct=stripe_billing_test_connection($pdo,$config);$testResult=(string)($acct['business_profile']['name']??$acct['settings']['dashboard']['display_name']??$acct['id']??'Connected');$success='Stripe connection verified.';}
    elseif($op==='sync_price'){$row=stripe_billing_sync_package_price($pdo,$config,$admin,(string)($_POST['package_id']??''));$success='Stripe Product/Price synchronized: '.(string)$row['stripe_price_id'];}
    elseif($op==='map_price'){$row=stripe_billing_map_existing_price($pdo,$config,$admin,(string)($_POST['package_id']??''),(string)($_POST['stripe_price_id']??''));$success='Existing Stripe Price mapped: '.(string)$row['stripe_price_id'];}
    else throw new RuntimeException('Unknown billing action.');
}catch(Throwable $e){$error=$e->getMessage();}}
$settings=stripe_billing_settings($pdo);$packages=stripe_billing_package_rows($pdo);$webhooks=stripe_billing_recent_webhooks($pdo,100);$events=stripe_billing_recent_events($pdo,100);
$secretConfigured=!empty($settings['secret_key_ciphertext']);$webhookConfigured=!empty($settings['webhook_secret_ciphertext']);$base=rtrim((string)($config['app']['base_url']??''),'/');$webhookUrl=$base.'/stripe/webhook.php';
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Billing & Stripe · Annotated Admin</title><link rel="stylesheet" href="/assets/css/app.css"></head><body><?=admin_ui_sidebar('billing')?>
<main class="panel adminBillingPage"><div class="pageTitle"><span class="eyebrow">STRIPE BILLING</span><h1>Payments, subscriptions & billing sync</h1><p>Stripe executes payments. Annotated remains authoritative for commercial accounts, package entitlements, membership, AI allowances, and access state.</p></div>
<?php if($success):?><div class="success"><?=h($success)?></div><?php endif?><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?>
<section class="adminBillingGrid"><article class="card"><span class="eyebrow">CONNECTION</span><h2>Stripe settings</h2><form method="post" class="stack"><?=csrf_field()?><input type="hidden" name="op" value="settings"><label>Mode<select name="mode"><option value="test" <?=$settings['mode']==='test'?'selected':''?>>Test</option><option value="live" <?=$settings['mode']==='live'?'selected':''?>>Live</option></select></label><label>Publishable key<input name="publishable_key" value="<?=h((string)($settings['publishable_key']??''))?>" placeholder="pk_test_…"></label><label>Secret key<input type="password" name="secret_key" autocomplete="new-password" placeholder="<?=$secretConfigured?'Configured — enter only to replace':'sk_test_…'?>"></label><label>Webhook signing secret<input type="password" name="webhook_secret" autocomplete="new-password" placeholder="<?=$webhookConfigured?'Configured — enter only to replace':'whsec_…'?>"></label><label>Checkout success path<input name="checkout_success_path" value="<?=h((string)$settings['checkout_success_path'])?>"></label><label>Checkout cancel path<input name="checkout_cancel_path" value="<?=h((string)$settings['checkout_cancel_path'])?>"></label><label>Portal return path<input name="portal_return_path" value="<?=h((string)$settings['portal_return_path'])?>"></label><button>Save Stripe settings</button></form><form method="post" class="inlineActions adminStripeTestForm"><?=csrf_field()?><input type="hidden" name="op" value="test"><button class="button secondary">Test Stripe connection</button><?php if($testResult):?><span class="meta"><?=h($testResult)?></span><?php endif?></form></article>
<article class="card"><span class="eyebrow">WEBHOOK</span><h2>Endpoint</h2><p>Configure this endpoint in the matching Stripe mode. Annotated verifies Stripe signatures and stores each Stripe event ID once before applying account changes.</p><code class="adminWebhookUrl"><?=h($webhookUrl)?></code><div class="adminBillingStatus"><div><span>Mode</span><strong><?=h(strtoupper((string)$settings['mode']))?></strong></div><div><span>Secret key</span><strong><?=$secretConfigured?'Configured':'Missing'?></strong></div><div><span>Webhook secret</span><strong><?=$webhookConfigured?'Configured':'Missing'?></strong></div></div><h3>Recommended events</h3><p class="meta">checkout.session.completed · customer.subscription.created/updated/deleted/paused/resumed · invoice.finalized/paid/payment_failed/voided/marked_uncollectible · charge.refunded · charge.dispute.created/closed</p></article></section>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">PACKAGE MAPPING</span><h2>Annotated packages → Stripe recurring Prices</h2></div></div><div class="tableWrap"><table><thead><tr><th>Package</th><th>Annotated price</th><th>Stripe mapping</th><th>Sync/create</th><th>Map existing</th></tr></thead><tbody>
<?php foreach($packages as $p):$map=$p['stripe_price']??null;?><tr><td><strong><?=h((string)$p['name'])?></strong><div class="meta"><?=h((string)$p['slug'])?> · <?=h((string)$p['status'])?></div></td><td>$<?=h(number_format(((int)$p['monthly_price_cents'])/100,2))?> / month</td><td><?php if($map):?><code><?=h((string)$map['stripe_price_id'])?></code><div class="meta"><?=h(strtoupper((string)$map['currency']))?> <?=h(number_format(((int)$map['unit_amount_cents'])/100,2))?> · <?=h((string)$map['mode'])?></div><?php else:?><span class="meta">Not mapped in <?=h((string)$settings['mode'])?> mode</span><?php endif?></td><td><?php if((int)$p['monthly_price_cents']>0&&$p['status']==='active'):?><form method="post"><?=csrf_field()?><input type="hidden" name="op" value="sync_price"><input type="hidden" name="package_id" value="<?=h((string)$p['public_id'])?>"><button class="button secondary"><?=$map?'Resync Stripe Price':'Create Stripe Product + Price'?></button></form><?php else:?><span class="meta">Free/archived package</span><?php endif?></td><td><?php if((int)$p['monthly_price_cents']>0):?><form method="post" class="adminMapPriceForm"><?=csrf_field()?><input type="hidden" name="op" value="map_price"><input type="hidden" name="package_id" value="<?=h((string)$p['public_id'])?>"><input name="stripe_price_id" required placeholder="price_…"><button class="button secondary">Map</button></form><?php endif?></td></tr><?php endforeach?>
</tbody></table></div></section>
<section class="adminBillingGrid"><article class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">WEBHOOK HEALTH</span><h2>Recent Stripe events</h2></div></div><?php foreach(array_slice($webhooks,0,20) as $w):?><div class="historyItem"><strong><?=h((string)$w['event_type'])?></strong><div class="meta"><?=h((string)$w['stripe_event_id'])?> · <?=h((string)$w['status'])?> · attempts <?=h((string)$w['attempt_count'])?> · <?=h((string)$w['received_at'])?></div><?php if($w['error_text']):?><p><?=h((string)$w['error_text'])?></p><?php endif?></div><?php endforeach?><?php if(!$webhooks):?><p class="empty">No Stripe webhook events received yet.</p><?php endif?></article>
<article class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">BILLING AUDIT</span><h2>Recent account billing events</h2></div></div><?php foreach(array_slice($events,0,20) as $e):?><div class="historyItem"><strong><?=h((string)$e['event_type'])?></strong><div class="meta"><?=h((string)$e['account_name'])?> · <?=h((string)$e['source'])?> · <?=h((string)$e['created_at'])?></div><p><?=h((string)$e['reason'])?></p></div><?php endforeach?><?php if(!$events):?><p class="empty">No billing events yet.</p><?php endif?></article></section>
</main></body></html>