<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
if(PHP_SAPI!=='cli')header('Cache-Control: no-store, private');
$admin=require_admin($pdo);if(!admin_customer_success_ready($pdo)){http_response_code(503);exit('Admin V2.40 Customer Success requires migration 077.');}
admin_access_assert_capability($pdo,$admin,'admin.customer_success.view');$canManage=admin_access_has_capability($pdo,$admin,'admin.customer_success.manage');$id=trim((string)($_GET['id']??$_POST['id']??''));$account=$id!==''?account_admin_get($pdo,$id):null;if(!$account){http_response_code(404);exit('Account not found.');}$success='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();try{if(!$canManage)throw new RuntimeException('Your operator role cannot manage Customer Success.');$op=(string)($_POST['op']??'');
    if($op==='snapshot'){admin_customer_success_snapshot($pdo,$admin,(int)$account['id'],true);$success='Explainable health snapshot refreshed.';}
    elseif($op==='assign'){admin_customer_success_assign($pdo,$admin,(int)$account['id'],($_POST['owner_user_id']??'')!==''?(int)$_POST['owner_user_id']:null,(string)($_POST['reason']??''));$success='Customer Success owner updated.';}
    elseif($op==='followup_create'){admin_customer_success_followup_create($pdo,$admin,(int)$account['id'],$_POST);$success='Follow-up created.';}
    elseif(in_array($op,['followup_complete','followup_cancel','followup_reopen'],true)){admin_customer_success_followup_update($pdo,$admin,(string)($_POST['followup_id']??''),substr($op,9),(string)($_POST['reason']??''));$success='Follow-up updated.';}
    elseif($op==='plan_create'){admin_customer_success_plan_create($pdo,$admin,(int)$account['id'],$_POST);$success='Success plan created.';}
    elseif(in_array($op,['plan_pause','plan_resume','plan_complete','plan_cancel'],true)){admin_customer_success_plan_update($pdo,$admin,(string)($_POST['plan_id']??''),substr($op,5),(string)($_POST['reason']??''));$success='Success plan updated.';}
    elseif($op==='milestone_create'){admin_customer_success_milestone_create($pdo,$admin,(string)($_POST['plan_id']??''),$_POST);$success='Milestone added.';}
    elseif($op==='milestone_status'){admin_customer_success_milestone_update($pdo,$admin,(string)($_POST['milestone_id']??''),(string)($_POST['status']??''),(string)($_POST['reason']??''));$success='Milestone updated.';}
    else throw new RuntimeException('Unknown Customer Success action.');
}catch(Throwable $e){$error=$e->getMessage();}}
$data=admin_customer_success_account($pdo,$admin,(int)$account['id']);$health=$data['current_health'];$snapshot=$data['latest_snapshot'];$assignment=$data['assignment'];$plans=$data['plans'];$followups=$data['followups'];$events=$data['events'];$history=$data['health_history'];$support=$data['support'];$finance=$data['finance'];$members=$data['members'];$usage=$data['usage'];$operators=admin_customer_success_operator_candidates($pdo);$stateLabel=fn(string $s)=>ucwords(str_replace('_',' ',$s));$stale=$snapshot===null||!hash_equals((string)$snapshot['fingerprint'],(string)$health['fingerprint']);
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=h((string)$account['name'])?> · Customer Success · Annotated Admin</title><link rel="stylesheet" href="/assets/css/app.css"></head><body><?=admin_ui_sidebar('customer_success_account')?>
<main class="panel adminCustomerSuccessAccountPage"><div class="pageTitle"><span class="eyebrow">ADMIN V2.40 · ACCOUNT SUCCESS 360</span><h1><?=h((string)$account['name'])?></h1><p><?=h((string)$account['public_id'])?> · <?=h((string)$account['package_name'])?> · <?=h((string)$account['subscription_status'])?> · Explainable Customer Success evidence</p></div>
<?php if($success):?><div class="success"><?=h($success)?></div><?php endif?><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?>
<div class="adminPageActions"><a class="button secondary" href="/admin/customer-success.php">← Customer Success</a><?php if(admin_access_has_capability($pdo,$admin,'admin.accounts.view')):?><a class="button secondary" href="/admin/account.php?id=<?=h(rawurlencode((string)$account['public_id']))?>">Account 360</a><?php endif?><?php if(admin_access_has_capability($pdo,$admin,'admin.support.view')):?><a class="button secondary" href="/admin/support.php?q=<?=h(rawurlencode((string)$account['public_id']))?>">Support</a><?php endif?><?php if(admin_access_has_capability($pdo,$admin,'admin.finance.view')):?><a class="button secondary" href="/admin/financial-reporting.php?account=<?=h(rawurlencode((string)$account['public_id']))?>">Finance</a><?php endif?></div>
<section class="customerSuccessHero"><article class="card"><span class="meta">Health index</span><strong><?=h((string)$health['health_score'])?></strong><small><?=h($stateLabel((string)$health['health_state']))?></small></article><article class="card"><span class="meta">Lifecycle</span><strong><?=h($stateLabel((string)$health['lifecycle_stage']))?></strong><small>deterministic stage</small></article><article class="card"><span class="meta">Success owner</span><strong><?=h((string)($assignment['owner_display_name']??$assignment['owner_username']??'Unassigned'))?></strong><small><?=h((string)($assignment['assigned_at']??'Needs assignment'))?></small></article><article class="card"><span class="meta">Open follow-ups</span><strong><?=h((string)($health['signals']['open_followups']??0))?></strong><small><?=h((string)($health['signals']['overdue_followups']??0))?> overdue</small></article><article class="card"><span class="meta">Open support</span><strong><?=h((string)($health['signals']['open_support_count']??0))?></strong><small><?=h((string)($health['signals']['priority_support_count']??0))?> high/urgent</small></article><article class="card"><span class="meta">Finance exceptions</span><strong><?=h((string)($health['signals']['finance_open_exceptions']??0))?></strong><small><?=h((string)($health['signals']['finance_critical_exceptions']??0))?> critical</small></article></section>
<?php if($stale):?><div class="warn customerSuccessNotice">Current source evidence differs from the latest stored health snapshot.<?php if($canManage):?> Refresh the snapshot after reviewing the changes.<?php endif?></div><?php endif?>
<section class="adminContentSplit"><article class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">WHY THIS HEALTH STATE</span><h2>Explainable signals</h2></div><?php if($canManage):?><form method="post"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($id)?>"><input type="hidden" name="op" value="snapshot"><button>Refresh snapshot</button></form><?php endif?></div><?php foreach($health['reasons'] as $reason):?><div class="healthReason"><span class="healthImpact <?=$reason['impact']<0?'healthImpactNegative':'healthImpactNeutral'?>"><?=h(($reason['impact']>0?'+':'').(string)$reason['impact'])?></span><div><strong><?=h((string)$reason['label'])?></strong><div class="meta"><?=h((string)$reason['code'])?><?php if(!empty($reason['evidence'])):?> · <?=h(json_encode($reason['evidence'],JSON_UNESCAPED_SLASHES))?><?php endif?></div></div></div><?php endforeach?></article>
<aside class="card"><span class="eyebrow">OPPORTUNITIES</span><h2>Expansion & adoption signals</h2><?php foreach($health['opportunities'] as $o):?><div class="historyItem"><strong><?=h((string)$o['label'])?></strong><div class="meta"><?=h((string)$o['code'])?> · <?=h(json_encode($o['evidence']??[],JSON_UNESCAPED_SLASHES))?></div></div><?php endforeach?><?php if(!$health['opportunities']):?><p class="empty">No expansion signal currently meets the deterministic threshold.</p><?php endif?></aside></section>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">ONBOARDING & ADOPTION</span><h2>Milestone evidence</h2></div><span class="badge"><?=h($stateLabel((string)$health['lifecycle_stage']))?></span></div><div class="customerOnboardingGrid"><?php foreach($health['onboarding'] as $key=>$done):?><div class="<?=$done?'complete':'pending'?>"><span><?=h(ucwords(str_replace('_',' ',$key)))?></span><strong><?=$done?'Complete':'Pending'?></strong></div><?php endforeach?></div></section>
<?php if($canManage):?><section class="adminContentSplit"><article class="card"><span class="eyebrow">OWNERSHIP</span><h2>Assign Success owner</h2><form method="post" class="stack"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($id)?>"><input type="hidden" name="op" value="assign"><label>Owner<select name="owner_user_id"><option value="">Unassigned</option><?php foreach($operators as $op):?><option value="<?=h((string)$op['id'])?>" <?=((int)($assignment['owner_user_id']??0)===(int)$op['id'])?'selected':''?>><?=h((string)($op['display_name']?:$op['username']))?></option><?php endforeach?></select></label><label>Reason<input name="reason" required maxlength="1000" placeholder="Portfolio ownership or reassignment reason"></label><button>Update owner</button></form></article>
<article class="card"><span class="eyebrow">FOLLOW-UP</span><h2>Schedule next action</h2><form method="post" class="stack"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($id)?>"><input type="hidden" name="op" value="followup_create"><label>Title<input name="title" required maxlength="190" placeholder="Review onboarding progress"></label><label>Assigned to<select name="assigned_user_id"><option value="">Unassigned</option><?php foreach($operators as $op):?><option value="<?=h((string)$op['id'])?>"><?=h((string)($op['display_name']?:$op['username']))?></option><?php endforeach?></select></label><div class="adminFormGrid"><label>Priority<select name="priority"><?php foreach(['normal','high','urgent','low'] as $v):?><option value="<?=h($v)?>"><?=h(ucfirst($v))?></option><?php endforeach?></select></label><label>Due<input type="datetime-local" name="due_at" required></label></div><label>Note<textarea name="note" rows="3"></textarea></label><label>Reason<input name="reason" required placeholder="Why this follow-up is needed"></label><button>Create follow-up</button></form></article></section><?php endif?>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">FOLLOW-THROUGH</span><h2>Follow-ups</h2></div><span class="badge"><?=h((string)count($followups))?></span></div><?php foreach($followups as $f):?><div class="historyItem"><div class="sectionHeadWeb"><div><strong><?=h((string)$f['title'])?></strong><div class="meta"><?=h(strtoupper((string)$f['priority']))?> · <?=h((string)$f['status'])?> · due <?=h((string)$f['due_at'])?><?php if($f['assigned_username']):?> · @<?=h((string)$f['assigned_username'])?><?php endif?></div><?php if($f['note']):?><p><?=h((string)$f['note'])?></p><?php endif?></div><?php if($canManage):?><div class="inlineActions"><?php if($f['status']==='open'):?><?php foreach(['complete'=>'Complete','cancel'=>'Cancel'] as $op=>$label):?><form method="post"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($id)?>"><input type="hidden" name="op" value="followup_<?=h($op)?>"><input type="hidden" name="followup_id" value="<?=h((string)$f['public_id'])?>"><input name="reason" required placeholder="<?=h($label)?> reason"><button class="<?=$op==='cancel'?'button secondary':''?>"><?=h($label)?></button></form><?php endforeach?><?php else:?><form method="post"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($id)?>"><input type="hidden" name="op" value="followup_reopen"><input type="hidden" name="followup_id" value="<?=h((string)$f['public_id'])?>"><input name="reason" required placeholder="Reopen reason"><button class="button secondary">Reopen</button></form><?php endif?></div><?php endif?></div></div><?php endforeach?><?php if(!$followups):?><p class="empty">No Customer Success follow-ups yet.</p><?php endif?></section>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">SUCCESS PLANS</span><h2>Goals & milestones</h2></div></div><?php if($canManage):?><details><summary>Create success plan</summary><form method="post" class="stack adminInsetForm"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($id)?>"><input type="hidden" name="op" value="plan_create"><label>Plan title<input name="title" required maxlength="190" placeholder="Complete team onboarding"></label><label>Objective<textarea name="objective" required rows="3"></textarea></label><div class="adminFormGrid"><label>Owner<select name="owner_user_id"><option value="">Unassigned</option><?php foreach($operators as $op):?><option value="<?=h((string)$op['id'])?>"><?=h((string)($op['display_name']?:$op['username']))?></option><?php endforeach?></select></label><label>Target date<input type="date" name="target_date"></label></div><label>Reason<input name="reason" required placeholder="Why this plan is being created"></label><button>Create plan</button></form></details><?php endif?>
<?php foreach($plans as $plan):?><article class="customerPlan"><div class="sectionHeadWeb"><div><strong><?=h((string)$plan['title'])?></strong><div class="meta"><?=h((string)$plan['status'])?> · target <?=h((string)($plan['target_date']?:'—'))?><?php if($plan['owner_username']):?> · @<?=h((string)$plan['owner_username'])?><?php endif?></div><p><?=h((string)$plan['objective'])?></p></div><?php if($canManage):?><div class="inlineActions"><?php $ops=$plan['status']==='active'?['pause'=>'Pause','complete'=>'Complete','cancel'=>'Cancel']:($plan['status']==='paused'?['resume'=>'Resume','cancel'=>'Cancel']:[]);foreach($ops as $op=>$label):?><form method="post"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($id)?>"><input type="hidden" name="op" value="plan_<?=h($op)?>"><input type="hidden" name="plan_id" value="<?=h((string)$plan['public_id'])?>"><input name="reason" required placeholder="<?=h($label)?> reason"><button class="button secondary"><?=h($label)?></button></form><?php endforeach?></div><?php endif?></div>
<div class="customerMilestones"><?php foreach($plan['milestones'] as $m):?><div><strong><?=h((string)$m['title'])?></strong><div class="meta"><?=h($stateLabel((string)$m['status']))?> · due <?=h((string)($m['due_at']?:'—'))?></div><?php if($canManage):?><form method="post" class="inlineActions"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($id)?>"><input type="hidden" name="op" value="milestone_status"><input type="hidden" name="milestone_id" value="<?=h((string)$m['public_id'])?>"><select name="status"><?php foreach(['pending','in_progress','completed','blocked'] as $v):?><option value="<?=h($v)?>" <?=$m['status']===$v?'selected':''?>><?=h($stateLabel($v))?></option><?php endforeach?></select><input name="reason" required placeholder="Status reason"><button class="button secondary">Update</button></form><?php endif?></div><?php endforeach?></div>
<?php if($canManage&&$plan['status']==='active'):?><form method="post" class="adminInlineForm"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($id)?>"><input type="hidden" name="op" value="milestone_create"><input type="hidden" name="plan_id" value="<?=h((string)$plan['public_id'])?>"><input name="title" required maxlength="190" placeholder="Add milestone"><input type="datetime-local" name="due_at"><input name="reason" required placeholder="Milestone reason"><button>Add milestone</button></form><?php endif?></article><?php endforeach?><?php if(!$plans):?><p class="empty">No success plans have been created.</p><?php endif?></section>
<section class="adminContentSplit"><article class="card"><span class="eyebrow">COMMERCIAL & SUPPORT CONTEXT</span><h2>Connected evidence</h2><div class="customerContextGrid"><div><span>Members</span><strong><?=h((string)count($members))?></strong></div><div><span>AI used</span><strong><?=h(number_format((int)($usage['used_tokens']??0)))?></strong></div><div><span>Outstanding</span><strong>$<?=h(number_format(((int)($finance['outstanding_cents']??0))/100,2))?></strong></div><div><span>Finance exceptions</span><strong><?=h((string)($finance['open_exceptions']??0))?></strong></div><div><span>Support cases</span><strong><?=h((string)count($support))?></strong></div><div><span>Research projects</span><strong><?=h((string)($health['signals']['research_project_count']??0))?></strong></div></div></article>
<aside class="card"><span class="eyebrow">HEALTH HISTORY</span><h2>Snapshot changes</h2><?php foreach(array_slice($history,0,12) as $s):?><div class="historyItem"><strong><?=h((string)$s['health_score'])?> · <?=h($stateLabel((string)$s['health_state']))?></strong><div class="meta"><?=h($stateLabel((string)$s['lifecycle_stage']))?> · <?=h((string)$s['created_at'])?> · @<?=h((string)$s['created_by_username'])?></div></div><?php endforeach?><?php if(!$history):?><p class="empty">No stored health snapshot yet.</p><?php endif?></aside></section>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">CUSTOMER SUCCESS AUDIT</span><h2>Success timeline</h2></div><span class="badge"><?=h((string)count($events))?> events</span></div><?php foreach($events as $e):?><div class="historyItem"><strong><?=h($stateLabel((string)$e['event_type']))?></strong><div class="meta"><?=h((string)$e['created_at'])?><?php if($e['actor_username']):?> · @<?=h((string)$e['actor_username'])?><?php endif?><?php if($e['subject_type']):?> · <?=h((string)$e['subject_type'])?><?php endif?></div><p><?=h((string)$e['reason'])?></p></div><?php endforeach?><?php if(!$events):?><p class="empty">No Customer Success activity has been recorded.</p><?php endif?></section>
</main></body></html>
