<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
if(PHP_SAPI!=='cli')header('Cache-Control: no-store, private');
$admin=require_admin($pdo);if(!admin_customer_success_ready($pdo)){http_response_code(503);exit('Admin V2.40 Customer Success requires migration 077.');}
admin_access_assert_capability($pdo,$admin,'admin.customer_success.view');$canManage=admin_access_has_capability($pdo,$admin,'admin.customer_success.manage');$success='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();try{
    if(!$canManage)throw new RuntimeException('Your operator role cannot manage Customer Success.');
    $op=(string)($_POST['op']??'');
    if($op==='refresh'){$r=admin_customer_success_refresh($pdo,$admin,500);$success='Health refresh complete: '.$r['accounts'].' accounts checked, '.$r['created'].' new snapshots, '.$r['unchanged'].' unchanged.';}
    else throw new RuntimeException('Unknown Customer Success action.');
}catch(Throwable $e){$error=$e->getMessage();}}
$filters=admin_customer_success_filters($_GET);$portfolio=admin_customer_success_portfolio($pdo,$admin,$filters,500);$metrics=admin_customer_success_metrics($pdo,$admin);$operators=admin_customer_success_operator_candidates($pdo);$workload=admin_customer_success_workload($pdo);$due=admin_customer_success_followups($pdo,null,null,'open',100);
$stateLabel=fn(string $s)=>ucwords(str_replace('_',' ',$s));$scoreClass=fn(string $s)=>'customerHealth customerHealth'.str_replace(' ','',ucwords(str_replace('_',' ',$s)));
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Customer Success · Annotated Admin</title><link rel="stylesheet" href="/assets/css/app.css"></head><body><?=admin_ui_sidebar('customer_success')?>
<main class="panel adminCustomerSuccessPage"><div class="pageTitle"><span class="eyebrow">ADMIN V2.40 · CUSTOMER SUCCESS, ACCOUNT HEALTH & RETENTION</span><h1>Customer Success</h1><p>Explainable account health, onboarding, retention risks, expansion signals, success ownership and follow-through across Account, Support, Finance and product-usage evidence.</p></div>
<?php if($success):?><div class="success"><?=h($success)?></div><?php endif?><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?>
<section class="customerSuccessMetrics">
<a class="card" href="/admin/customer-success.php"><span class="meta">Portfolio</span><strong><?=h((string)$metrics['total'])?></strong><small>active / non-closed accounts</small></a>
<a class="card" href="/admin/customer-success.php?state=healthy"><span class="meta">Healthy</span><strong><?=h((string)$metrics['healthy'])?></strong><small>80–100 explainable index</small></a>
<a class="card" href="/admin/customer-success.php?state=watch"><span class="meta">Watch</span><strong><?=h((string)$metrics['watch'])?></strong><small>60–79 explainable index</small></a>
<a class="card" href="/admin/customer-success.php?state=at_risk"><span class="meta">At risk</span><strong><?=h((string)$metrics['at_risk'])?></strong><small>40–59 explainable index</small></a>
<a class="card" href="/admin/customer-success.php?state=critical"><span class="meta">Critical</span><strong><?=h((string)$metrics['critical'])?></strong><small>below 40</small></a>
<a class="card" href="/admin/customer-success.php?stage=onboarding"><span class="meta">Onboarding</span><strong><?=h((string)$metrics['onboarding'])?></strong><small>new-account adoption</small></a>
<a class="card" href="/admin/customer-success.php?stage=expansion_ready"><span class="meta">Expansion ready</span><strong><?=h((string)$metrics['expansion_ready'])?></strong><small>capacity/adoption signals</small></a>
<a class="card" href="/admin/customer-success.php?unassigned=1"><span class="meta">Unassigned</span><strong><?=h((string)$metrics['unassigned'])?></strong><small>needs Success owner</small></a>
</section>
<section class="card adminToolbarCard"><div class="sectionHeadWeb"><div><span class="eyebrow">PORTFOLIO CONTROL</span><h2>Account health portfolio</h2></div><?php if($canManage):?><form method="post"><?=csrf_field()?><input type="hidden" name="op" value="refresh"><button>Refresh health evidence</button></form><?php endif?></div><p class="meta">The health index is deterministic. Every deduction and opportunity is visible on the account record; the Agent does not decide the score.</p>
<form method="get" class="adminAccountFilters"><label>Search<input name="q" value="<?=h((string)($filters['q']??''))?>" placeholder="Account, user, email"></label><label>Health<select name="state"><option value="">All states</option><?php foreach(['healthy','watch','at_risk','critical'] as $v):?><option value="<?=h($v)?>" <?=($filters['state']??'')===$v?'selected':''?>><?=h($stateLabel($v))?></option><?php endforeach?></select></label><label>Lifecycle<select name="stage"><option value="">All stages</option><?php foreach(['onboarding','adopting','established','expansion_ready','recovery'] as $v):?><option value="<?=h($v)?>" <?=($filters['stage']??'')===$v?'selected':''?>><?=h($stateLabel($v))?></option><?php endforeach?></select></label><label>Owner<select name="owner"><option value="">Any owner</option><option value="me" <?=($filters['owner']??'')==='me'?'selected':''?>>My accounts</option><?php foreach($operators as $op):?><option value="<?=h((string)$op['id'])?>" <?=($filters['owner']??'')===(string)$op['id']?'selected':''?>><?=h((string)($op['display_name']?:$op['username']))?></option><?php endforeach?></select></label><label class="adminCheckLabel"><input type="checkbox" name="unassigned" value="1" <?=!empty($filters['unassigned'])?'checked':''?>> Unassigned</label><label class="adminCheckLabel"><input type="checkbox" name="followup_due" value="1" <?=!empty($filters['followup_due'])?'checked':''?>> Overdue follow-up</label><button>Filter</button><a class="button secondary" href="/admin/customer-success.php">Clear</a></form></section>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">ACCOUNT HEALTH</span><h2>Portfolio</h2></div><span class="badge"><?=h((string)count($portfolio))?> shown</span></div><div class="tableWrap"><table><thead><tr><th>Account</th><th>Health</th><th>Lifecycle</th><th>Signals</th><th>Success owner</th><th>Follow-up</th><th>Source activity</th></tr></thead><tbody><?php foreach($portfolio as $row):$h=$row['health'];$owner=$row['success_assignment'];$sig=$h['signals'];?><tr><td><a href="/admin/customer-success-account.php?id=<?=h(rawurlencode((string)$row['public_id']))?>"><strong><?=h((string)$row['name'])?></strong></a><div class="meta"><?=h((string)$row['package_name'])?> · <?=h((string)$row['subscription_status'])?> · <?=h((string)$row['member_count'])?> member(s)</div></td><td><span class="<?=h($scoreClass((string)$h['health_state']))?>"><strong><?=h((string)$h['health_score'])?></strong> <?=h($stateLabel((string)$h['health_state']))?></span></td><td><?=h($stateLabel((string)$h['lifecycle_stage']))?><?php if(!empty($h['opportunities'])):?><div class="meta"><?=h((string)count($h['opportunities']))?> opportunity signal(s)</div><?php endif?></td><td><div class="meta"><?=h((string)($sig['open_support_count']??0))?> support · <?=h((string)($sig['finance_open_exceptions']??0))?> finance · <?=h((string)($sig['research_project_count']??0))?> research</div><div class="meta">AI <?=h(number_format(((float)($sig['ai_utilization']??0))*100,0))?>% · Seats <?=h(number_format(((float)($sig['member_utilization']??0))*100,0))?>%</div></td><td><?=h((string)($owner['owner_display_name']??$owner['owner_username']??'Unassigned'))?></td><td><?php if((int)$row['overdue_followups']>0:?><strong><?=h((string)$row['overdue_followups'])?> overdue</strong><?php elseif($row['next_followup_at']):?><?=h((string)$row['next_followup_at'])?><?php else:?><span class="meta">None open</span><?php endif?></td><td><?=h((string)($h['source_max_at']??$row['updated_at']))?></td></tr><?php endforeach?><?php if(!$portfolio):?><tr><td colspan="7" class="empty">No accounts match this Customer Success view.</td></tr><?php endif?></tbody></table></div></section>
<section class="adminContentSplit"><article class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">FOLLOW-THROUGH</span><h2>Open follow-ups</h2></div><a class="button secondary" href="/admin/customer-success.php?followup_due=1">Overdue accounts</a></div><?php foreach(array_slice($due,0,20) as $f):$overdue=$f['status']==='open'&&strtotime((string)$f['due_at'])<time();?><div class="historyItem"><a href="/admin/customer-success-account.php?id=<?=h(rawurlencode((string)$f['account_public_id']))?>"><strong><?=h((string)$f['title'])?></strong></a><div class="meta"><?=h((string)$f['account_name'])?> · <?=h(strtoupper((string)$f['priority']))?> · due <?=h((string)$f['due_at'])?><?=$overdue?' · OVERDUE':''?><?php if($f['assigned_username']):?> · @<?=h((string)$f['assigned_username'])?><?php endif?></div></div><?php endforeach?><?php if(!$due):?><p class="empty">No open Customer Success follow-ups.</p><?php endif?></article>
<aside class="card"><span class="eyebrow">PORTFOLIO OWNERSHIP</span><h2>Success owner workload</h2><?php foreach($workload as $w):?><div class="historyItem"><strong><?=h((string)($w['display_name']?:$w['username']))?></strong><div class="meta"><?=h((string)$w['account_count'])?> assigned account(s)</div></div><?php endforeach?><?php if(!$workload):?><p class="empty">No Customer Success accounts have been assigned.</p><?php endif?></aside></section>
</main></body></html>
