<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
if(PHP_SAPI!=='cli')header('Cache-Control: no-store, private');
$admin=require_admin($pdo);if(!admin_finance_ready($pdo)){http_response_code(503);exit('Admin V2.30 Financial Reporting requires migration 076.');}
admin_access_assert_capability($pdo,$admin,'admin.finance.view');$canManage=admin_access_has_capability($pdo,$admin,'admin.finance.manage');$canExport=admin_access_has_capability($pdo,$admin,'admin.finance.export');$success='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();try{
    if(!$canManage)throw new RuntimeException('Your operator role cannot manage finance reconciliation.');
    $op=(string)($_POST['op']??'');
    if($op==='scan'){$r=admin_finance_scan($pdo,$admin);$success='Reconciliation scan complete: '.$r['active_count'].' active exceptions, '.$r['auto_resolved'].' auto-resolved.';}
    elseif(in_array($op,['assign','acknowledge','resolve','ignore','reopen'],true)){admin_finance_exception_update($pdo,$admin,(string)($_POST['exception_id']??''),$op,$_POST);$success='Finance exception updated.';}
    elseif($op==='close_period'){$close=admin_finance_period_close($pdo,$admin,(string)($_POST['from']??''),(string)($_POST['to']??''),(string)($_POST['reason']??''));$success='Finance period closed: '.(string)$close['period_start'].' → '.(string)$close['period_end'].' · '.substr((string)$close['metrics_sha256'],0,12).'…';}
    else throw new RuntimeException('Unknown finance action.');
}catch(Throwable $e){$error=$e->getMessage();}}
$filters=admin_finance_exception_filters($_GET);$filters['from']=(string)($_GET['from']??'');$filters['to']=(string)($_GET['to']??'');$dashboard=admin_finance_dashboard($pdo,$admin,$filters);$range=$dashboard['range'];$metrics=$dashboard['metrics'];$aging=$dashboard['aging'];$receivables=$dashboard['receivables'];$exceptions=$dashboard['exceptions'];$types=$dashboard['exception_types'];$operators=$dashboard['operators'];$closes=$dashboard['closes'];$packages=$dashboard['packages'];$recentExports=$canExport?admin_finance_recent_exports($pdo,20):[];
$money=fn(int $c)=>'$'.number_format($c/100,2);$micro=fn(int $m)=>'$'.number_format($m/1000000,6);
$account=null;$ledger=[];$accountFinance=null;if(!empty($_GET['account'])){$account=account_admin_get($pdo,(string)$_GET['account']);if($account){$ledger=admin_finance_account_ledger($pdo,(int)$account['id'],300);$accountFinance=admin_finance_account_summary($pdo,(int)$account['id']);}}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Financial Reporting · Annotated Admin</title><link rel="stylesheet" href="/assets/css/app.css"></head><body><?=admin_ui_sidebar('financial_reporting')?>
<main class="panel adminFinancePage"><div class="pageTitle"><span class="eyebrow">ADMIN V2.30 · FINANCIAL REPORTING & RECONCILIATION</span><h1>Finance workspace</h1><p>One finance view across Stripe-synchronized invoices, collections, receivables, tax, discounts, credits, AI overage and reconciliation evidence. Source billing ledgers remain authoritative.</p></div>
<?php if($success):?><div class="success"><?=h($success)?></div><?php endif?><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?>
<section class="card"><form method="get" class="adminAccountFilters"><label>From<input type="date" name="from" value="<?=h((string)$range['from'])?>"></label><label>To<input type="date" name="to" value="<?=h((string)$range['to'])?>"></label><label>Exception status<select name="status"><option value="">Open + acknowledged</option><?php foreach(['open','acknowledged','resolved','ignored'] as $v):?><option value="<?=h($v)?>" <?=($filters['status']??'')===$v?'selected':''?>><?=h(ucfirst($v))?></option><?php endforeach?></select></label><label>Severity<select name="severity"><option value="">All</option><?php foreach(['critical','warning','info'] as $v):?><option value="<?=h($v)?>" <?=($filters['severity']??'')===$v?'selected':''?>><?=h(ucfirst($v))?></option><?php endforeach?></select></label><button>Apply period</button></form></section>
<section class="financeKpiGrid">
<article class="card"><span class="meta">Collected</span><strong><?=h($money((int)$metrics['collected_cents']))?></strong><small><?=h((string)$metrics['paid_invoice_count'])?> paid invoices</small></article>
<article class="card"><span class="meta">Net collection position</span><strong><?=h($money((int)$metrics['net_collection_position_cents']))?></strong><small>collected − refunds − credits + debits</small></article>
<article class="card"><span class="meta">Invoiced</span><strong><?=h($money((int)$metrics['invoiced_cents']))?></strong><small><?=h((string)$metrics['invoice_count'])?> invoices</small></article>
<article class="card"><span class="meta">Outstanding · current</span><strong><?=h($money((int)$metrics['outstanding_cents']))?></strong><small><?=h((string)$metrics['open_dunning_cases'])?> open dunning cases</small></article>
<article class="card"><span class="meta">MRR</span><strong><?=h($money((int)$metrics['mrr_cents']))?></strong><small><?=h($money((int)$metrics['arr_cents']))?> ARR run-rate</small></article>
<article class="card"><span class="meta">Discounts</span><strong><?=h($money((int)$metrics['discount_cents']))?></strong><small>invoice discount evidence</small></article>
<article class="card"><span class="meta">Tax</span><strong><?=h($money((int)$metrics['tax_cents']))?></strong><small>recorded invoice tax</small></article>
<article class="card"><span class="meta">AI overage reported</span><strong><?=h($money((int)$metrics['overage_reported_cents']))?></strong><small><?=h($micro((int)$metrics['overage_accrued_micros']))?> accrued in period</small></article>
</section>
<section class="financeSplit"><article class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">RECONCILIATION</span><h2>Exception queue</h2></div><div class="inlineActions"><?php if($canManage):?><form method="post"><?=csrf_field()?><input type="hidden" name="op" value="scan"><button>Run reconciliation scan</button></form><?php endif?><?php if($canExport):?><a class="button secondary" href="/admin/financial-export.php?type=exceptions&status=<?=h(rawurlencode((string)($filters['status']??'open')))?>">Export exceptions</a><?php endif?></div></div>
<form method="get" class="adminAccountFilters"><input type="hidden" name="from" value="<?=h((string)$range['from'])?>"><input type="hidden" name="to" value="<?=h((string)$range['to'])?>"><label>Search<input name="q" value="<?=h((string)($filters['q']??''))?>" placeholder="Exception, source ID, account"></label><label>Type<select name="type"><option value="">All types</option><?php foreach($types as $t):?><option value="<?=h((string)$t['exception_type'])?>" <?=($filters['type']??'')===$t['exception_type']?'selected':''?>><?=h(ucwords(str_replace('_',' ',(string)$t['exception_type'])))?> (<?=h((string)$t['total'])?>)</option><?php endforeach?></select></label><label>Owner<select name="assigned"><option value="">Anyone</option><option value="me" <?=($filters['assigned']??'')==='me'?'selected':''?>>Mine</option><option value="unassigned" <?=($filters['assigned']??'')==='unassigned'?'selected':''?>>Unassigned</option><?php foreach($operators as $op):?><option value="<?=h((string)$op['id'])?>" <?=($filters['assigned']??'')===(string)$op['id']?'selected':''?>><?=h((string)($op['display_name']?:$op['username']))?></option><?php endforeach?></select></label><button>Filter</button></form>
<?php foreach($exceptions as $e):?><div class="historyItem <?=$e['severity']==='critical'?'financeExceptionCritical':'financeExceptionWarning'?>"><div class="sectionHeadWeb"><div><strong><?=h((string)$e['title'])?></strong><div class="meta"><?=h(strtoupper((string)$e['severity']))?> · <?=h(ucwords(str_replace('_',' ',(string)$e['exception_type'])))?> · <?=h((string)$e['status'])?> · <?=h((string)$e['last_seen_at'])?></div></div><span class="badge"><?=h($money(abs((int)$e['delta_cents'])))?></span></div><p><?=h((string)($e['detail']??''))?></p><div class="meta"><code><?=h((string)$e['public_id'])?></code> · Source <code><?=h((string)($e['source_public_id']?:'—'))?></code><?php if($e['account_name']):?> · <?=h((string)$e['account_name'])?><?php endif?><?php if($e['assigned_username']):?> · @<?=h((string)$e['assigned_username'])?><?php endif?></div><div class="inlineActions"><?php if($e['account_public_id']):?><a class="button secondary" href="/admin/financial-reporting.php?account=<?=h(rawurlencode((string)$e['account_public_id']))?>&from=<?=h(rawurlencode((string)$range['from']))?>&to=<?=h(rawurlencode((string)$range['to']))?>">Account ledger</a><?php endif?><?php if($e['source_type']==='stripe_invoice'&&admin_access_has_capability($pdo,$admin,'admin.billing.view')):?><a class="button secondary" href="/admin/tax-invoices.php">Invoice evidence</a><?php endif?><?php if($e['account_public_id']&&admin_access_has_capability($pdo,$admin,'admin.support.view')):?><a class="button secondary" href="/admin/support.php?account=<?=h(rawurlencode((string)$e['account_public_id']))?>&new_title=<?=h(rawurlencode('Finance reconciliation: '.(string)$e['title']))?>&category=billing">Open in Support</a><?php endif?><?php if($e['account_public_id']&&admin_access_has_capability($pdo,$admin,'admin.customer_success.view')):?><a class="button secondary" href="/admin/customer-success-account.php?id=<?=h(rawurlencode((string)$e['account_public_id']))?>&new_followup_title=<?=h(rawurlencode('Finance follow-up: '.(string)$e['title']))?>&new_followup_note=<?=h(rawurlencode('Linked finance exception '.(string)$e['public_id']))?>">Customer Success</a><?php endif?></div>
<?php if($canManage):?><div class="inlineActions"><form method="post"><?=csrf_field()?><input type="hidden" name="exception_id" value="<?=h((string)$e['public_id'])?>"><input type="hidden" name="op" value="assign"><select name="user_id" required><option value="">Assign operator</option><?php foreach($operators as $op):?><option value="<?=h((string)$op['id'])?>" <?=((int)($e['assigned_user_id']??0)===(int)$op['id'])?'selected':''?>><?=h((string)($op['display_name']?:$op['username']))?></option><?php endforeach?></select><input name="reason" required placeholder="Assignment reason"><button class="button secondary">Assign</button></form><?php if($e['status']==='open'):?><form method="post"><?=csrf_field()?><input type="hidden" name="exception_id" value="<?=h((string)$e['public_id'])?>"><input type="hidden" name="op" value="acknowledge"><input name="reason" required placeholder="Acknowledgement reason"><button class="button secondary">Acknowledge</button></form><?php endif?><?php if(in_array($e['status'],['open','acknowledged'],true)):?><form method="post"><?=csrf_field()?><input type="hidden" name="exception_id" value="<?=h((string)$e['public_id'])?>"><input type="hidden" name="op" value="resolve"><input name="reason" required placeholder="Resolution evidence"><button>Resolve</button></form><form method="post"><?=csrf_field()?><input type="hidden" name="exception_id" value="<?=h((string)$e['public_id'])?>"><input type="hidden" name="op" value="ignore"><input name="reason" required placeholder="Why is this expected?"><button class="button secondary">Ignore</button></form><?php else:?><form method="post"><?=csrf_field()?><input type="hidden" name="exception_id" value="<?=h((string)$e['public_id'])?>"><input type="hidden" name="op" value="reopen"><input name="reason" required placeholder="Reopen reason"><button class="button secondary">Reopen</button></form><?php endif?></div><?php endif?></div><?php endforeach?><?php if(!$exceptions):?><p class="empty">No reconciliation exceptions match this view. Run a reconciliation scan to refresh source conditions.</p><?php endif?></article>
<aside class="card"><span class="eyebrow">RECEIVABLE AGING</span><h2>Outstanding balance</h2><div class="financeLedgerGrid"><div><span>Current</span><strong><?=h($money((int)$aging['current']))?></strong></div><div><span>1–30 days</span><strong><?=h($money((int)$aging['1_30']))?></strong></div><div><span>31–60 days</span><strong><?=h($money((int)$aging['31_60']))?></strong></div><div><span>61–90 days</span><strong><?=h($money((int)$aging['61_90']))?></strong></div><div><span>90+ days</span><strong><?=h($money((int)$aging['90_plus']))?></strong></div><div><span>Total</span><strong><?=h($money((int)$aging['total']))?></strong></div></div><?php if($canExport):?><a class="button secondary" href="/admin/financial-export.php?type=receivables">Export receivables</a><?php endif?></aside></section>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">RECEIVABLES</span><h2>Outstanding invoices</h2></div><span class="badge"><?=h((string)count($receivables))?> shown</span></div><div class="tableWrap"><table><thead><tr><th>Account</th><th>Invoice</th><th>Status</th><th>Due</th><th>Age</th><th>Remaining</th></tr></thead><tbody><?php foreach($receivables as $r):?><tr><td><a href="/admin/financial-reporting.php?account=<?=h(rawurlencode((string)$r['account_public_id']))?>"><?=h((string)$r['account_name'])?></a><div class="meta"><?=h((string)$r['package_name'])?></div></td><td><code><?=h((string)($r['invoice_number']?:$r['stripe_invoice_id']))?></code></td><td><?=h((string)$r['status'])?></td><td><?=h((string)($r['due_at']?:'—'))?></td><td><?=$r['age_days']===null?'—':h((string)$r['age_days']).'d'?></td><td><?=h($money((int)$r['amount_remaining_cents']))?></td></tr><?php endforeach?><?php if(!$receivables):?><tr><td colspan="6" class="empty">No outstanding Stripe receivables.</td></tr><?php endif?></tbody></table></div></section>
<section class="financeSplit"><article class="card"><span class="eyebrow">REVENUE BY PACKAGE</span><h2>Recurring revenue mix</h2><div class="tableWrap"><table><thead><tr><th>Package</th><th>Billable accounts</th><th>MRR</th><th>Trialing</th><th>Past due</th></tr></thead><tbody><?php foreach($packages as $p):?><tr><td><?=h((string)$p['package_name'])?></td><td><?=h((string)$p['billable_accounts'])?></td><td><?=h($money((int)$p['mrr_cents']))?></td><td><?=h((string)$p['trialing_accounts'])?></td><td><?=h((string)$p['past_due_accounts'])?></td></tr><?php endforeach?></tbody></table></div></article><article class="card"><span class="eyebrow">PERIOD CLOSE</span><h2>Immutable close snapshot</h2><p>Period close stores the current finance metrics, receivable aging and reconciliation summary as an immutable JSON snapshot with a SHA-256 fingerprint.</p><?php if($canManage):?><form method="post" class="stack"><?=csrf_field()?><input type="hidden" name="op" value="close_period"><label>From<input type="date" name="from" value="<?=h((string)$range['from'])?>" required></label><label>To<input type="date" name="to" value="<?=h((string)$range['to'])?>" required></label><label>Close reason<textarea name="reason" rows="3" required placeholder="Month-end finance close after reconciliation review."></textarea></label><button>Close reporting period</button></form><?php endif?></article></section>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">CLOSE LEDGER</span><h2>Closed reporting periods</h2></div><?php if($canExport):?><a class="button secondary" href="/admin/financial-export.php?type=period_closes">Export close ledger</a><?php endif?></div><div class="tableWrap"><table><thead><tr><th>Period</th><th>Mode</th><th>Closed by</th><th>Closed at</th><th>Fingerprint</th><th>Reason</th></tr></thead><tbody><?php foreach($closes as $c):?><tr><td><?=h((string)$c['period_start'])?> → <?=h((string)$c['period_end'])?></td><td><?=h((string)$c['stripe_mode'])?></td><td>@<?=h((string)$c['closed_by_username'])?></td><td><?=h((string)$c['closed_at'])?></td><td><code><?=h(substr((string)$c['metrics_sha256'],0,20))?>…</code></td><td><?=h((string)$c['close_reason'])?></td></tr><?php endforeach?><?php if(!$closes):?><tr><td colspan="6" class="empty">No finance periods have been closed yet.</td></tr><?php endif?></tbody></table></div></section>
<?php if($account&&$accountFinance):?><section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">ACCOUNT FINANCIAL LEDGER</span><h2><?=h((string)$account['name'])?></h2></div><div class="inlineActions"><a class="button secondary" href="/admin/account.php?id=<?=h(rawurlencode((string)$account['public_id']))?>">Account 360</a><?php if($canExport):?><a class="button secondary" href="/admin/financial-export.php?type=ledger&account=<?=h(rawurlencode((string)$account['public_id']))?>&from=<?=h(rawurlencode((string)$range['from']))?>&to=<?=h(rawurlencode((string)$range['to']))?>">Export period ledger</a><?php endif?></div></div><div class="financeLedgerGrid"><div><span>Invoices</span><strong><?=h((string)$accountFinance['invoice_count'])?></strong></div><div><span>Paid</span><strong><?=h($money((int)$accountFinance['paid_cents']))?></strong></div><div><span>Outstanding</span><strong><?=h($money((int)$accountFinance['outstanding_cents']))?></strong></div><div><span>Tax</span><strong><?=h($money((int)$accountFinance['tax_cents']))?></strong></div><div><span>Discounts</span><strong><?=h($money((int)$accountFinance['discount_cents']))?></strong></div><div><span>Open exceptions</span><strong><?=h((string)$accountFinance['open_exceptions'])?></strong></div></div><div class="tableWrap"><table><thead><tr><th>Date</th><th>Type</th><th>Record</th><th>Status</th><th>Amount</th><th>Detail</th></tr></thead><tbody><?php foreach($ledger as $l):?><tr><td><?=h((string)$l['created_at'])?></td><td><?=h(ucwords(str_replace('_',' ',(string)$l['type'])))?></td><td><?=h((string)$l['label'])?><div class="meta"><code><?=h((string)$l['identifier'])?></code></div></td><td><?=h((string)$l['status'])?></td><td><?=h($money((int)$l['amount_cents']))?></td><td><?=h((string)$l['detail'])?></td></tr><?php endforeach?></tbody></table></div></section><?php endif?>
<?php if($canExport):?><section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">AUDITED EXPORTS</span><h2>Finance export history</h2></div><a class="button secondary" href="/admin/financial-export.php?type=ledger&from=<?=h(rawurlencode((string)$range['from']))?>&to=<?=h(rawurlencode((string)$range['to']))?>">Export current ledger period</a></div><div class="tableWrap"><table><thead><tr><th>Export</th><th>Type</th><th>Rows</th><th>SHA-256</th><th>Operator</th><th>Created</th></tr></thead><tbody><?php foreach($recentExports as $e):?><tr><td><code><?=h((string)$e['public_id'])?></code></td><td><?=h((string)$e['export_type'])?></td><td><?=h((string)$e['row_count'])?></td><td><code><?=h(substr((string)$e['content_sha256'],0,18))?>…</code></td><td>@<?=h((string)$e['requested_by_username'])?></td><td><?=h((string)$e['created_at'])?></td></tr><?php endforeach?><?php if(!$recentExports):?><tr><td colspan="6" class="empty">No finance exports have been created.</td></tr><?php endif?></tbody></table></div></section><?php endif?>
</main></body></html>
