<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
$admin=require_admin($pdo);$snapshot=admin_ui_dashboard_snapshot($pdo);$counts=$snapshot['counts'];$usage=$snapshot['usage'];
$recentPackages=subscriptions_ready($pdo)?subscription_recent_events($pdo,8):[];$recentUsage=ai_usage_ready($pdo)?ai_usage_recent_events($pdo,8):[];
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin · Annotated</title><link rel="stylesheet" href="/assets/css/app.css"></head><body><?=admin_ui_sidebar('dashboard')?>
<main class="panel adminDashboardPage"><div class="pageTitle"><span class="eyebrow">ADMIN CONTROL CENTER</span><h1>Admin control center</h1><p>Accounts, AI, research infrastructure, trust operations, release health, and audit tools now share one categorized admin workspace.</p></div>
<section class="adminDashboardMetrics"><a class="card adminMetric" href="/admin/users.php"><span>Users</span><strong><?=h(number_format($counts['users']))?></strong></a><a class="card adminMetric" href="/admin/accounts.php"><span>Accounts</span><strong><?=h(number_format($counts['accounts']))?></strong></a><a class="card adminMetric" href="/admin/packages.php"><span>Active packages</span><strong><?=h(number_format($counts['packages']))?></strong></a><a class="card adminMetric" href="/admin/usage.php"><span>Account AI tokens used</span><strong><?=h(number_format($usage['used_tokens']))?></strong></a><a class="card adminMetric" href="/admin/moderation.php"><span>Open trust cases</span><strong><?=h(number_format($counts['open_claims']+$counts['open_reports']))?></strong></a><a class="card adminMetric" href="/admin/source-monitor.php"><span>Sources</span><strong><?=h(number_format($counts['sources']))?></strong></a><a class="card adminMetric" href="/home.php"><span>Published annotations</span><strong><?=h(number_format($counts['annotations']))?></strong></a><a class="card adminMetric" href="/admin/system-health.php"><span>Worker problems</span><strong><?=h(number_format($snapshot['worker_problems']))?></strong></a></section>
<section class="adminDashboardGrid"><article class="card adminAttention"><div class="sectionHeadWeb"><div><span class="eyebrow">NEEDS ATTENTION</span><h2>Operational alerts</h2></div><a href="/admin/system-health.php">System health</a></div><?php if(!$snapshot['attention']):?><div class="adminAllClear"><strong>No active dashboard alerts.</strong><span>Usage, queues, moderation, migrations, and worker health have no flagged conditions.</span></div><?php else:?><div class="adminAttentionList"><?php foreach($snapshot['attention'] as $item):?><a class="adminAttentionItem <?=h((string)$item['severity'])?>" href="<?=h((string)$item['url'])?>"><strong><?=h(number_format((int)$item['count']))?></strong><span><?=h((string)$item['label'])?></span></a><?php endforeach?></div><?php endif?></article>
<article class="card"><span class="eyebrow">AI ACCOUNTING</span><h2>Current-period usage</h2><div class="adminUsageSummary"><div><strong><?=h(number_format($usage['used_tokens']))?></strong><span>customer tokens</span></div><div><strong><?=h(number_format($usage['system_tokens']))?></strong><span>system tokens</span></div><div><strong><?=h(number_format($usage['admin_tokens']))?></strong><span>admin tokens</span></div><div><strong><?=h((string)$usage['exhausted_accounts'])?></strong><span>exhausted accounts</span></div></div><div class="inlineActions"><a class="button secondary" href="/admin/usage.php">Open AI Usage</a><a class="button secondary" href="/admin/ai.php">Providers & Routing</a></div></article></section>
<section><div class="sectionHeadWeb"><div><span class="eyebrow">ADMIN WORKSPACES</span><h2>Organized by responsibility</h2></div></div><div class="adminWorkspaceGrid">
<a class="card adminWorkspaceCard" href="/admin/accounts.php"><span class="eyebrow">ACCOUNTS & BILLING</span><h3>Accounts, users, packages & usage</h3><p>Commercial ownership, subscription periods, package assignments, member limits, and AI allowance accounting.</p></a>
<a class="card adminWorkspaceCard" href="/admin/ai.php"><span class="eyebrow">AI & MODELS</span><h3>Providers, models & release lifecycle</h3><p>Routing, evaluation, training, post-training readiness, deployment, observability, and improvement campaigns.</p></a>
<a class="card adminWorkspaceCard" href="/admin/data-attribution.php"><span class="eyebrow">RESEARCH & DATA</span><h3>Governed research infrastructure</h3><p>Source monitoring, attribution, dataset governance, and public discovery entity maintenance.</p></a>
<a class="card adminWorkspaceCard" href="/admin/system-health.php"><span class="eyebrow">TRUST & OPERATIONS</span><h3>Moderation, health & audit</h3><p>Human review, worker and queue health, production readiness, and end-to-end release auditing.</p></a>
</div></section>
<section><div class="sectionHeadWeb"><div><span class="eyebrow">QUICK DESTINATIONS</span><h2>Admin directory</h2></div></div><div class="adminDirectoryGrid">
<div class="card adminDirectoryGroup"><h3>Accounts & Billing</h3><a href="/admin/users.php">User accounts</a><a href="/admin/packages.php">Subscription Packages</a><a href="/admin/billing.php">Billing & Stripe</a><a href="/admin/usage.php">AI Usage & Tokens</a><a href="/admin/accounts.php">Commercial Accounts</a></div>
<div class="card adminDirectoryGroup"><h3>AI & Models</h3><a href="/admin/ai.php">AI & LLM models</a><a href="/admin/evaluations.php">Evaluation Harness</a><a href="/admin/model-registry.php">Model Registry</a><a href="/admin/training.php">Training Registry</a><a href="/admin/post-training.php">Post-Training Readiness</a><a href="/admin/model-release.php">Model Release Decisions</a><a href="/admin/model-deployment.php">Model Deployments</a><a href="/admin/model-observability.php">Model Health & Outcomes</a><a href="/admin/model-improvements.php">Model Improvement Loop</a><a href="/admin/model-campaigns.php">Improvement Campaigns</a></div>
<div class="card adminDirectoryGroup"><h3>Research & Data</h3><a href="/admin/source-monitor.php">Source monitor</a><a href="/admin/data-attribution.php">Data Governance</a><a href="/admin/datasets.php">Dataset Registry</a><a href="/admin/discovery-entities.php">Discovery Entities</a></div>
<div class="card adminDirectoryGroup"><h3>Trust & Operations</h3><a href="/admin/moderation.php">Moderation & rights</a><a href="/admin/system-health.php">System Health & Release</a><a href="/admin/intelligence-release-audit.php">Intelligence Release Audit</a><a href="/admin/assistant.php">Admin Assistant</a></div>
</div></section>
<section class="adminDashboardGrid"><article class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">RECENT</span><h2>Account & package changes</h2></div><a href="/admin/packages.php">Packages</a></div><?php foreach($recentPackages as $e):?><div class="historyItem"><strong><?=h((string)($e['display_name']?:$e['account_name']))?></strong><div class="meta"><?=h((string)($e['old_package_name']?:'—'))?> → <?=h((string)($e['new_package_name']?:'—'))?> · <?=h((string)$e['created_at'])?></div></div><?php endforeach?><?php if(!$recentPackages):?><p class="empty">No package changes yet.</p><?php endif?></article>
<article class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">RECENT</span><h2>Metered AI runs</h2></div><a href="/admin/usage.php">AI Usage</a></div><?php foreach($recentUsage as $e):?><div class="historyItem"><strong><?=h((string)$e['task_type'])?></strong><div class="meta"><?=h(number_format((int)$e['total_tokens']))?> tokens · <?=h((string)$e['usage_class'])?> · <?=h((string)$e['created_at'])?></div></div><?php endforeach?><?php if(!$recentUsage):?><p class="empty">No metered AI runs yet.</p><?php endif?></article></section>
</main></body></html>
