<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
$u=require_admin($pdo);
if(!data_model_campaign_ready($pdo)){http_response_code(503);exit('Improvement Campaigns requires the Phase 47 database upgrade.');}
$error='';$success='';$campaignPublic=trim((string)($_GET['campaign']??$_POST['campaign']??''));
if($_SERVER['REQUEST_METHOD']==='POST'){
    require_csrf();$op=(string)($_POST['op']??'');
    try{
        if($op==='create'){$c=data_model_campaign_create($pdo,$u,$_POST);header('Location:/admin/model-campaigns.php?campaign='.rawurlencode((string)$c['public_id']));exit;}
        elseif($op==='add_case'){data_model_campaign_add_case($pdo,$u,$campaignPublic,(string)($_POST['case_public_id']??''));$success='Improvement case added to campaign.';}
        elseif($op==='remove_case'){data_model_campaign_remove_case($pdo,$u,$campaignPublic,(string)($_POST['case_public_id']??''));$success='Improvement case removed.';}
        elseif($op==='add_proposal'){data_model_campaign_add_proposal($pdo,$u,$campaignPublic,(string)($_POST['proposal_public_id']??''));$success='Approved proposal added to campaign.';}
        elseif($op==='remove_proposal'){data_model_campaign_remove_proposal($pdo,$u,$campaignPublic,(string)($_POST['proposal_public_id']??''));$success='Proposal removed.';}
        elseif($op==='datasets'){data_model_campaign_create_dataset_drafts($pdo,$u,$campaignPublic);$success='Campaign-specific Dataset Registry drafts created. Freeze remains a separate Dataset Registry action.';}
        elseif($op==='lock'){data_model_campaign_lock($pdo,$u,$campaignPublic);$success='Campaign plan locked. Scope and selected evidence are now immutable.';}
        elseif($op==='evaluation_suite'){$s=data_model_campaign_prepare_evaluation_suite($pdo,$u,$campaignPublic);$success='Baseline regression suite draft created. Activate and run it explicitly in Evaluation Harness.';}
        elseif($op==='training_draft'){$j=data_model_campaign_prepare_training_draft($pdo,$u,$campaignPublic,$_POST);$success='Phase 41 training draft created. Queue/submission remains an explicit Training Registry action.';}
        elseif($op==='post_training'){$p=data_model_campaign_prepare_post_training_plan($pdo,$u,$campaignPublic,$_POST);$success='Phase 42 post-training readiness draft created. Preparation/evaluation remains explicit.';}
        elseif($op==='close'){data_model_campaign_close($pdo,$u,$campaignPublic,(string)($_POST['close_status']??''),(string)($_POST['close_note']??''));$success='Campaign status updated.';}
        elseif($op==='sync'){$c=data_model_campaign_get($pdo,$campaignPublic);if($c)data_model_campaign_sync_status($pdo,$c);$success='Campaign lifecycle synchronized from governed downstream records.';}
    }catch(Throwable $e){$error=$e->getMessage();}
}
$stats=data_model_campaign_summary($pdo);$campaigns=data_model_campaign_list($pdo,150);$campaign=$campaignPublic!==''?data_model_campaign_get($pdo,$campaignPublic,true):null;
$cases=$campaign?data_model_campaign_cases($pdo,(int)$campaign['id']):[];$proposals=$campaign?data_model_campaign_proposals($pdo,(int)$campaign['id']):[];$events=$campaign?data_model_campaign_events($pdo,(int)$campaign['id'],150):[];$integrity=$campaign&&$campaign['plan_hash']?data_model_campaign_plan_integrity($pdo,$campaign):null;$current=$campaign&&$campaign['plan_hash']?data_model_campaign_current_use($pdo,$campaign):null;$outcome=$campaign?data_model_campaign_outcome($pdo,$campaign):null;
$baseVersions=$pdo->query("SELECT v.id,v.public_id,v.version_label,v.status,r.name registry_name,m.display_name runtime_name FROM data_model_versions v JOIN data_model_registry r ON r.id=v.registry_id LEFT JOIN ai_models m ON m.id=v.ai_model_id WHERE v.status IN ('approved','active') ORDER BY r.name,v.id DESC")->fetchAll();
$availableCases=[];$availableProposals=[];
if($campaign&&!$campaign['plan_hash']){
    $q=$pdo->prepare("SELECT c.public_id,c.title,c.classification,c.status,c.severity,c.route_key,mv.version_label model_version_label FROM data_model_improvement_cases c LEFT JOIN data_model_versions mv ON mv.id=c.model_version_id WHERE c.classification NOT IN ('untriaged','expected_behavior','no_action') AND (c.model_version_id IS NULL OR mv.registry_id=?) ORDER BY FIELD(c.severity,'critical','warning'),c.updated_at DESC LIMIT 200");$q->execute([$campaign['registry_id']]);$availableCases=$q->fetchAll();
    $q=$pdo->prepare("SELECT p.public_id,p.title,p.proposal_type,p.status,c.public_id case_public_id,c.title case_title FROM data_model_improvement_proposals p JOIN data_model_improvement_cases c ON c.id=p.case_id JOIN data_model_improvement_campaign_cases l ON l.improvement_case_id=c.id AND l.campaign_id=? WHERE p.status='published' ORDER BY p.proposal_type,p.id DESC");$q->execute([$campaign['id']]);$availableProposals=$q->fetchAll();
}
$strategies=data_model_campaign_strategies();$statuses=data_model_campaign_statuses();
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Improvement Campaigns · Annotated Admin</title><link rel="stylesheet" href="/assets/css/app.css"></head><body><?=admin_ui_sidebar('model_campaigns')?>
<main class="panel article">
  <div class="pageTitle"><span class="eyebrow">PHASE 47 · MODEL IMPROVEMENT CAMPAIGNS</span><h1>Controlled retraining & remediation handoff</h1><p>Group validated production failures into an immutable campaign plan, prepare campaign-specific governed datasets, and hand them into the existing Evaluation, Training, and Post-Training systems. This workspace never freezes datasets, queues evaluation runs, queues/submits training, promotes, deploys, rolls back, or changes routing.</p></div>
  <div class="inlineActions"><a class="button secondary" href="/admin/model-improvements.php">Phase 46 Improvements</a><a class="button secondary" href="/admin/datasets.php">Dataset Registry</a><a class="button secondary" href="/admin/evaluations.php">Evaluation Harness</a><a class="button secondary" href="/admin/training.php">Training Registry</a><a class="button secondary" href="/admin/post-training.php">Post-Training</a></div>
  <?php if($error):?><div class="notice error"><?=h($error)?></div><?php endif?><?php if($success):?><div class="notice success"><?=h($success)?></div><?php endif?>
  <section class="healthGrid"><article class="card"><strong><?=h((string)$stats['campaigns'])?></strong><p class="meta">Campaigns</p></article><article class="card"><strong><?=h((string)$stats['open'])?></strong><p class="meta">Open</p></article><article class="card"><strong><?=h((string)$stats['ready_for_training'])?></strong><p class="meta">Ready for training</p></article><article class="card"><strong><?=h((string)$stats['evaluation'])?></strong><p class="meta">Evaluation</p></article><article class="card"><strong><?=h((string)$stats['release_review'])?></strong><p class="meta">Release review</p></article></section>

  <?php if(!$campaign):?>
  <section class="card"><span class="eyebrow">NEW CAMPAIGN</span><h2>Create governed remediation plan</h2><form method="post" class="settingsForm"><?=csrf_field()?><input type="hidden" name="op" value="create"><label>Title<input name="title" maxlength="255" required placeholder="Research grounding improvement · Sep 2026"></label><label>Strategy<select name="strategy"><?php foreach($strategies as $k=>$v):?><option value="<?=h($k)?>"><?=h($v)?></option><?php endforeach?></select></label><label>Governed base model<select name="base_model_version_id" required><option value="">Select base model</option><?php foreach($baseVersions as $b):?><option value="<?=h((string)$b['id'])?>"><?=h($b['registry_name'].' · '.$b['version_label'].' · '.$b['status'].($b['runtime_name']?' · '.$b['runtime_name']:''))?></option><?php endforeach?></select></label><label>Target model version label<input name="target_version_label" maxlength="120" placeholder="v1.4-grounding-improvement"></label><label>Objective<textarea name="objective" rows="4" required></textarea></label><label>Success criteria<textarea name="success_criteria" rows="4" required></textarea></label><button class="button">Create campaign</button></form><p class="meta">Target version label is required for Controlled model training and optional for non-training campaigns.</p></section>
  <section class="card"><span class="eyebrow">CAMPAIGNS</span><h2>Improvement portfolio</h2><?php if(!$campaigns):?><p class="empty">No campaigns yet.</p><?php else:?><div class="unifiedActivityList"><?php foreach($campaigns as $c):?><article class="unifiedActivityItem"><div class="unifiedActivityMain"><div class="unifiedActivityHead"><div><span class="badge"><?=h($c['status'])?></span> <strong><a href="/admin/model-campaigns.php?campaign=<?=rawurlencode((string)$c['public_id'])?>"><?=h($c['title'])?></a></strong></div><span class="meta"><?=h($c['updated_at'])?></span></div><p class="meta"><?=h($strategies[$c['strategy']]??$c['strategy'])?> · <?=h($c['registry_name'])?> · base <?=h($c['base_version_label'])?><?=!empty($c['training_job_status'])?' · training '.$c['training_job_status']:''?><?=!empty($c['post_training_plan_status'])?' · readiness '.$c['post_training_plan_status']:''?></p></div></article><?php endforeach?></div><?php endif?></section>
  <?php else:?>
  <section class="card"><span class="eyebrow">CAMPAIGN</span><h2><?=h($campaign['title'])?></h2><p><span class="badge"><?=h($statuses[$campaign['status']]??$campaign['status'])?></span> <span class="badge"><?=h($strategies[$campaign['strategy']]??$campaign['strategy'])?></span></p><p><?=h($campaign['objective'])?></p><div class="cognitiveCardMeta"><span><small>Registry</small><?=h($campaign['registry_name'])?></span><span><small>Base</small><?=h($campaign['base_version_label'])?></span><span><small>Target</small><?=h((string)($campaign['target_version_label']??'—'))?></span><span><small>Cases</small><?=h((string)count($cases))?></span><span><small>Evidence proposals</small><?=h((string)count($proposals))?></span></div><p><strong>Success criteria:</strong> <?=h($campaign['success_criteria'])?></p>
    <div class="inlineActions"><form method="post"><?=csrf_field()?><input type="hidden" name="op" value="sync"><input type="hidden" name="campaign" value="<?=h($campaign['public_id'])?>"><button class="button secondary">Sync lifecycle</button></form><form method="post" action="/admin/model-campaigns-export.php"><?=csrf_field()?><input type="hidden" name="campaign" value="<?=h($campaign['public_id'])?>"><button class="button secondary">Export campaign JSON</button></form></div>
    <?php if($integrity):?><p class="meta">Plan integrity: <strong><?=h($integrity['ok']?'PASS':'FAIL')?></strong> · <?=h((string)$campaign['plan_hash'])?></p><?php endif?>
  </section>

  <?php if(!$campaign['plan_hash']):?>
  <section class="card"><span class="eyebrow">1 · SCOPE</span><h2>Production improvement cases</h2><p class="meta">Only actionable, human-triaged Phase 46 cases from this logical model family can be selected.</p><form method="post" class="inlineActions"><?=csrf_field()?><input type="hidden" name="op" value="add_case"><input type="hidden" name="campaign" value="<?=h($campaign['public_id'])?>"><select name="case_public_id" required><option value="">Select case</option><?php foreach($availableCases as $c):?><option value="<?=h($c['public_id'])?>"><?=h($c['severity'].' · '.$c['title'].' · '.$c['route_key'].' · '.$c['classification'])?></option><?php endforeach?></select><button class="button secondary">Add case</button></form><?php if($cases):?><div class="unifiedActivityList"><?php foreach($cases as $c):?><article class="unifiedActivityItem"><div class="unifiedActivityMain"><strong><?=h($c['case_title'])?></strong><p class="meta"><?=h($c['severity'])?> · <?=h($c['route_key'])?> · <?=h($c['classification'])?> · recurrence <?=h((string)$c['recurrence_count'])?></p><form method="post"><?=csrf_field()?><input type="hidden" name="op" value="remove_case"><input type="hidden" name="campaign" value="<?=h($campaign['public_id'])?>"><input type="hidden" name="case_public_id" value="<?=h($c['case_public_id'])?>"><button class="button secondary">Remove</button></form></div></article><?php endforeach?></div><?php endif?></section>

  <section class="card"><span class="eyebrow">2 · APPROVED EVIDENCE</span><h2>Select published Phase 46 examples</h2><form method="post" class="inlineActions"><?=csrf_field()?><input type="hidden" name="op" value="add_proposal"><input type="hidden" name="campaign" value="<?=h($campaign['public_id'])?>"><select name="proposal_public_id" required><option value="">Select proposal</option><?php foreach($availableProposals as $p):?><option value="<?=h($p['public_id'])?>"><?=h($p['proposal_type'].' · '.$p['title'].' · '.$p['case_title'])?></option><?php endforeach?></select><button class="button secondary">Add proposal</button></form><?php if($proposals):?><div class="unifiedActivityList"><?php foreach($proposals as $p):?><article class="unifiedActivityItem"><div class="unifiedActivityMain"><span class="badge"><?=h($p['proposal_type'])?></span> <strong><?=h($p['proposal_title'])?></strong><p class="meta">content <?=h(substr((string)$p['content_hash'],0,16))?>… · approval <?=h(substr((string)$p['approval_hash'],0,16))?>…</p><form method="post"><?=csrf_field()?><input type="hidden" name="op" value="remove_proposal"><input type="hidden" name="campaign" value="<?=h($campaign['public_id'])?>"><input type="hidden" name="proposal_public_id" value="<?=h($p['proposal_public_id'])?>"><button class="button secondary">Remove</button></form></div></article><?php endforeach?></div><?php endif?></section>

  <section class="card"><span class="eyebrow">3 · DATASET DRAFTS</span><h2>Prepare campaign-specific selection policies</h2><p class="meta">This creates drafts selecting exactly the chosen proposal IDs. It does not freeze a dataset.</p><form method="post"><?=csrf_field()?><input type="hidden" name="op" value="datasets"><input type="hidden" name="campaign" value="<?=h($campaign['public_id'])?>"><button class="button secondary">Create campaign dataset drafts</button></form>
    <?php if($campaign['evaluation_dataset_public_id']):?><p><a href="/admin/datasets.php?id=<?=rawurlencode((string)$campaign['evaluation_dataset_public_id'])?>">Evaluation dataset <?=h($campaign['evaluation_dataset_public_id'])?></a> · <?=h($campaign['evaluation_dataset_status'])?></p><?php endif?>
    <?php if($campaign['training_dataset_public_id']):?><p><a href="/admin/datasets.php?id=<?=rawurlencode((string)$campaign['training_dataset_public_id'])?>">Training dataset <?=h($campaign['training_dataset_public_id'])?></a> · <?=h($campaign['training_dataset_status'])?></p><?php endif?>
  </section>

  <section class="card"><span class="eyebrow">4 · LOCK PLAN</span><h2>Freeze campaign intent, not datasets</h2><p class="meta">Locking hashes the base approval receipt, selected cases/evidence, approved proposals, campaign rationale, target label, and dataset selection policies. Dataset freezing remains a separate human action in Dataset Registry.</p><form method="post" onsubmit="return confirm('Lock this campaign plan? Case/proposal scope will become immutable.');"><?=csrf_field()?><input type="hidden" name="op" value="lock"><input type="hidden" name="campaign" value="<?=h($campaign['public_id'])?>"><button class="button">Lock campaign plan</button></form></section>
  <?php else:?>

  <section class="card"><span class="eyebrow">LOCKED PLAN</span><h2>Current-use validation</h2><?php if($current):?><div class="unifiedActivityList"><?php foreach($current['checks'] as $name=>$check):?><article class="unifiedActivityItem"><div class="unifiedActivityMain"><strong><?=h(str_replace('_',' ',$name))?></strong> <span class="badge"><?=h(($check['pass']??$check['ok']??false)?'PASS':'BLOCKED')?></span><?php if(isset($check['status'])):?><p class="meta">status <?=h((string)$check['status'])?></p><?php endif?></div></article><?php endforeach?></div><?php endif?></section>

  <section class="card"><span class="eyebrow">5 · HUMAN DATASET FREEZE</span><h2>Dataset Registry checkpoints</h2><p class="meta">Freeze these datasets manually after reviewing their exact preview. Phase 47 cannot freeze them.</p><?php if($campaign['evaluation_dataset_public_id']):?><p><a class="button secondary" href="/admin/datasets.php?id=<?=rawurlencode((string)$campaign['evaluation_dataset_public_id'])?>">Review evaluation dataset · <?=h($campaign['evaluation_dataset_status'])?></a></p><?php endif?><?php if($campaign['training_dataset_public_id']):?><p><a class="button secondary" href="/admin/datasets.php?id=<?=rawurlencode((string)$campaign['training_dataset_public_id'])?>">Review training dataset · <?=h($campaign['training_dataset_status'])?></a></p><?php endif?></section>

  <section class="card"><span class="eyebrow">6 · REGRESSION BASELINE</span><h2>Prepare Phase 39 suite draft</h2><p class="meta">Requires the campaign evaluation dataset to be frozen. Phase 47 creates the suite and cases only; a human must activate it and queue the baseline run in Evaluation Harness.</p><?php if(!$campaign['baseline_suite_public_id']):?><form method="post"><?=csrf_field()?><input type="hidden" name="op" value="evaluation_suite"><input type="hidden" name="campaign" value="<?=h($campaign['public_id'])?>"><button class="button secondary">Create baseline regression suite draft</button></form><?php else:?><a class="button secondary" href="/admin/evaluations.php?suite=<?=rawurlencode((string)$campaign['baseline_suite_public_id'])?>">Open baseline suite · <?=h($campaign['baseline_suite_status'])?></a><?php endif?></section>

  <?php if($campaign['strategy']==='model_training'):?>
  <section class="card"><span class="eyebrow">7 · TRAINING HANDOFF</span><h2>Create Phase 41 draft only</h2><?php if(!$campaign['training_job_public_id']):?><p class="meta">Requires frozen training data and a prepared regression suite. Phase 47 validates the supervised package but does not queue or submit training.</p><form method="post" class="settingsForm"><?=csrf_field()?><input type="hidden" name="op" value="training_draft"><input type="hidden" name="campaign" value="<?=h($campaign['public_id'])?>"><label>Executor<select name="executor_type"><option value="manual">Manual / self-hosted</option><option value="provider_api">Configured provider API</option></select></label><label>Epochs<input name="n_epochs" value="auto"></label><label>Batch size<input name="batch_size" value="auto"></label><label>Learning-rate multiplier<input name="learning_rate_multiplier" value="auto"></label><label>Seed<input name="seed"></label><label>Provider suffix<input name="suffix" maxlength="64"></label><label>Configured cost $/1M trained tokens<input type="number" min="0" step="0.000001" name="cost_rate_usd_per_million_tokens"></label><label>Max attempts<input type="number" min="1" max="10" name="max_attempts" value="3"></label><label><input type="checkbox" name="external_provider_acknowledged" value="1"> I acknowledge selected training data may be transferred to the configured external provider if Provider API is later queued.</label><button class="button">Create Training Registry draft</button></form><?php else:?><p><a class="button secondary" href="/admin/training.php?job=<?=rawurlencode((string)$campaign['training_job_public_id'])?>">Open Phase 41 training job · <?=h((string)$campaign['training_job_status'])?></a></p><?php endif?></section>

  <section class="card"><span class="eyebrow">8 · POST-TRAINING HANDOFF</span><h2>Create Phase 42 readiness draft</h2><p class="meta">Available only after the Training Registry job succeeds and the baseline regression suite has a governed completed baseline run. This action creates a Phase 42 draft; it does not prepare or queue candidate evaluation.</p><?php if(!$campaign['post_training_plan_public_id']):?><form method="post"><?=csrf_field()?><input type="hidden" name="op" value="post_training"><input type="hidden" name="campaign" value="<?=h($campaign['public_id'])?>"><button class="button secondary">Create Post-Training Readiness draft</button></form><?php else:?><a class="button secondary" href="/admin/post-training.php?plan=<?=rawurlencode((string)$campaign['post_training_plan_public_id'])?>">Open Phase 42 readiness · <?=h((string)$campaign['post_training_plan_status'])?></a><?php endif?></section>
  <?php endif?>

  <section class="card"><span class="eyebrow">CLOSED-LOOP OUTCOME</span><h2>Original production failures vs output model</h2><p class="meta">Outcome comparison begins only after a trained output is governed through deployment and Phase 45 has production observations. “Not reproduced” means no matching failure has been observed yet; it is not a claim that the problem can never recur.</p><p><strong>State:</strong> <?=h((string)$outcome['state'])?> · observations <?=h((string)$outcome['observations'])?></p><?php if($outcome['output_model_version_public_id']):?><p class="meta">Output model <?=h($outcome['output_model_version_public_id'])?><?=!empty($outcome['deployment_public_id'])?' · deployment '.h($outcome['deployment_public_id']):''?></p><?php endif?><?php if($outcome['cases']):?><div class="unifiedActivityList"><?php foreach($outcome['cases'] as $o):?><article class="unifiedActivityItem"><div class="unifiedActivityMain"><span class="badge"><?=h($o['state'])?></span> <strong><?=h($o['title'])?></strong><p class="meta">route <?=h($o['route_key'])?><?php if($o['detail']):?> · <?=h($o['detail']['metric'])?> baseline <?=h((string)$o['detail']['baseline'])?> → current <?=h((string)$o['detail']['current'])?><?php endif?></p></div></article><?php endforeach?></div><?php endif?></section>

  <section class="card"><span class="eyebrow">CLOSE CAMPAIGN</span><h2>Human completion / abandonment</h2><form method="post" class="settingsForm"><?=csrf_field()?><input type="hidden" name="op" value="close"><input type="hidden" name="campaign" value="<?=h($campaign['public_id'])?>"><label>Status<select name="close_status"><option value="completed">Completed</option><option value="abandoned">Abandoned</option></select></label><label>Close note<textarea name="close_note" rows="3"></textarea></label><button class="button secondary">Record campaign close</button></form></section>
  <?php endif?>

  <section class="card"><span class="eyebrow">AUDIT EVENTS</span><h2>Campaign history</h2><?php if(!$events):?><p class="empty">No events.</p><?php else:?><div class="unifiedActivityList"><?php foreach($events as $e):?><article class="unifiedActivityItem"><div class="unifiedActivityMain"><div class="unifiedActivityHead"><strong><?=h(str_replace('_',' ',$e['event_type']))?></strong><span class="meta"><?=h($e['created_at'])?></span></div><p class="meta"><?=h((string)($e['actor_name']??'System'))?> · <?=h(substr((string)$e['event_hash'],0,16))?>…</p></div></article><?php endforeach?></div><?php endif?></section>
  <?php endif?>
</main></body></html>