<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
$u=require_admin($pdo);
if(!data_model_improvement_ready($pdo)){http_response_code(503);exit('Model Improvements requires the Phase 46 database upgrade.');}
$error='';$success='';$casePublic=trim((string)($_GET['case']??$_POST['case']??''));$proposalPublic=trim((string)($_GET['proposal']??$_POST['proposal']??''));
if($_SERVER['REQUEST_METHOD']==='POST'){
    require_csrf();$op=(string)($_POST['op']??'');
    try{
        if($op==='backfill'){$r=data_model_improvement_backfill($pdo,$u,(int)($_POST['limit']??500));$success='Production feedback backfill touched '.$r['cases_touched'].' improvement case(s).';}
        elseif($op==='triage'){data_model_improvement_triage($pdo,$u,$casePublic,$_POST);$success='Improvement case triage updated.';}
        elseif($op==='create_proposal'){$p=data_model_improvement_proposal_create($pdo,$u,$casePublic,$_POST);header('Location:/admin/model-improvements.php?case='.rawurlencode($casePublic).'&proposal='.rawurlencode((string)$p['public_id']));exit;}
        elseif($op==='update_proposal'){data_model_improvement_proposal_update($pdo,$u,$proposalPublic,$_POST);$success='Sanitized proposal updated.';}
        elseif($op==='approve_proposal'){data_model_improvement_proposal_approve($pdo,$u,$proposalPublic);$success='Sanitized proposal approved for governed reuse.';}
        elseif($op==='publish_proposal'){data_model_improvement_proposal_publish($pdo,$u,$proposalPublic);$success='Approved example published into the governed corpus.';}
        elseif($op==='dataset_draft'){$d=data_model_improvement_create_dataset_draft($pdo,$u,(string)($_POST['purpose']??''));header('Location:/admin/datasets.php?id='.rawurlencode((string)$d['public_id']));exit;}
    }catch(Throwable $e){$error=$e->getMessage();}
}
$stats=data_model_improvement_summary($pdo);$cases=data_model_improvement_cases($pdo,150);$case=$casePublic!==''?data_model_improvement_case_get($pdo,$casePublic):null;
$evidence=$case?data_model_improvement_evidence($pdo,(int)$case['id']):[];$events=$case?data_model_improvement_events($pdo,(int)$case['id'],100):[];$proposals=$case?data_model_improvement_proposals($pdo,(int)$case['id']):[];$proposal=$proposalPublic!==''?data_model_improvement_proposal_get($pdo,$proposalPublic):null;if($proposal&&$case&&(int)$proposal['case_id']!==(int)$case['id'])$proposal=null;
$regressions=data_model_improvement_regression_cases($pdo,null,100);$admins=$pdo->query("SELECT id,display_name FROM users WHERE role='admin' AND status='active' ORDER BY display_name,id")->fetchAll();$classes=data_model_improvement_classifications();$statuses=data_model_improvement_statuses();
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Model Improvements · Annotated Admin</title><link rel="stylesheet" href="/assets/css/app.css"></head><body><?=admin_ui_sidebar('model_improvements')?>
<main class="panel article">
  <div class="pageTitle"><span class="eyebrow">PHASE 46 · PRODUCTION FEEDBACK & MODEL IMPROVEMENT</span><h1>Human-governed improvement loop</h1><p>Turn production incidents and negative outcomes into structured improvement work. Production prompts and model output are never copied automatically. Reusable examples must be rewritten, redacted, attested, approved, and explicitly published by a human.</p></div>
  <div class="inlineActions"><a class="button secondary" href="/admin/model-observability.php">Model Health</a><a class="button secondary" href="/admin/model-campaigns.php">Improvement Campaigns</a><a class="button secondary" href="/admin/datasets.php">Dataset Registry</a><a class="button secondary" href="/admin/evaluations.php">Evaluation Harness</a><a class="button secondary" href="/admin/training.php">Training Registry</a></div>
  <?php if($error):?><div class="notice error"><?=h($error)?></div><?php endif?><?php if($success):?><div class="notice success"><?=h($success)?></div><?php endif?>
  <section class="healthGrid">
    <article class="card"><strong><?=h((string)$stats['cases'])?></strong><p class="meta">Improvement cases</p></article>
    <article class="card"><strong><?=h((string)$stats['needs_triage'])?></strong><p class="meta">Needs triage</p></article>
    <article class="card"><strong><?=h((string)$stats['eval_ready'])?></strong><p class="meta">Evaluation ready</p></article>
    <article class="card"><strong><?=h((string)$stats['training_ready'])?></strong><p class="meta">Training ready</p></article>
    <article class="card"><strong><?=h((string)$stats['regression_cases'])?></strong><p class="meta">Regression library</p></article>
  </section>
  <section class="card"><span class="eyebrow">FEEDBACK MAINTENANCE</span><h2>Import existing Phase 45 evidence</h2><p class="meta">Backfill clusters existing incidents and negative outcome signals by governed model/route/failure signature. Existing evidence links are deduplicated.</p><form method="post" class="inlineActions"><?=csrf_field()?><input type="hidden" name="op" value="backfill"><input type="number" name="limit" min="1" max="5000" value="500"><button class="button secondary">Backfill production feedback</button></form></section>
  <section class="card"><span class="eyebrow">DATASET HANDOFF</span><h2>Create governed dataset drafts</h2><p class="meta">These actions create empty Dataset Registry drafts whose policy selects approved Phase 46 corpus examples. Freezing the dataset and running evaluation/training remain separate human actions.</p><div class="inlineActions"><form method="post"><?=csrf_field()?><input type="hidden" name="op" value="dataset_draft"><input type="hidden" name="purpose" value="evaluation"><button class="button secondary">Create evaluation dataset draft</button></form><form method="post"><?=csrf_field()?><input type="hidden" name="op" value="dataset_draft"><input type="hidden" name="purpose" value="training"><button class="button secondary">Create training dataset draft</button></form></div></section>

  <?php if(!$case):?>
  <section class="card"><span class="eyebrow">IMPROVEMENT BACKLOG</span><h2>Clustered production feedback</h2><?php if(!$cases):?><p class="empty">No production improvement cases yet.</p><?php else:?><div class="unifiedActivityList"><?php foreach($cases as $c):?><article class="unifiedActivityItem"><div class="unifiedActivityMain"><div class="unifiedActivityHead"><div><span class="badge"><?=h($c['severity'])?></span> <span class="badge"><?=h($c['status'])?></span> <strong><a href="/admin/model-improvements.php?case=<?=rawurlencode((string)$c['public_id'])?>"><?=h($c['title'])?></a></strong></div><span class="meta"><?=h($c['updated_at'])?></span></div><p><?=h((string)$c['summary'])?></p><p class="meta"><?=h($c['model_version_label']??'Unbound model')?> · route <?=h($c['route_key'])?> · <?=h($classes[$c['classification']]??$c['classification'])?> · recurrences <?=h((string)$c['recurrence_count'])?> · evidence <?=h((string)$c['evidence_count'])?></p></div></article><?php endforeach?></div><?php endif?></section>
  <?php else:?>
  <section class="card"><span class="eyebrow">IMPROVEMENT CASE</span><h2><?=h($case['title'])?></h2><p><span class="badge"><?=h($case['severity'])?></span> <span class="badge"><?=h($case['status'])?></span></p><p><?=h((string)$case['summary'])?></p><div class="cognitiveCardMeta"><span><small>Model</small><?=h((string)($case['model_version_label']??'—'))?></span><span><small>Route</small><?=h($case['route_key'])?></span><span><small>Classification</small><?=h($classes[$case['classification']]??$case['classification'])?></span><span><small>Recurrences</small><?=h((string)$case['recurrence_count'])?></span><span><small>Evidence</small><?=h((string)$case['evidence_count'])?></span></div>
    <form method="post" class="settingsForm"><?=csrf_field()?><input type="hidden" name="op" value="triage"><input type="hidden" name="case" value="<?=h($case['public_id'])?>"><label>Classification<select name="classification"><?php foreach($classes as $k=>$v):?><option value="<?=h($k)?>" <?=$case['classification']===$k?'selected':''?>><?=h($v)?></option><?php endforeach?></select></label><label>Status<select name="status"><?php foreach($statuses as $k=>$v):?><option value="<?=h($k)?>" <?=$case['status']===$k?'selected':''?>><?=h($v)?></option><?php endforeach?></select></label><label>Owner<select name="owner_user_id"><option value="">Unassigned</option><?php foreach($admins as $a):?><option value="<?=h((string)$a['id'])?>" <?=((string)$case['owner_user_id']===(string)$a['id'])?'selected':''?>><?=h($a['display_name'])?></option><?php endforeach?></select></label><label>Human triage note<textarea name="triage_note" rows="4"><?=h((string)$case['triage_note'])?></textarea></label><button class="button">Save triage</button></form>
    <div class="inlineActions"><?php if(!empty($case['incident_public_id'])):?><a class="button secondary" href="/admin/model-observability.php?incident=<?=rawurlencode((string)$case['incident_public_id'])?>">Open source incident</a><?php endif?><form method="post" action="/admin/model-improvements-export.php"><?=csrf_field()?><input type="hidden" name="case" value="<?=h($case['public_id'])?>"><button class="button secondary">Export case JSON</button></form></div>
  </section>

  <section class="card"><span class="eyebrow">EVIDENCE BUNDLE</span><h2>Production references & hashes</h2><p class="meta">Evidence stores identifiers, metric/signal hashes, and governed links—not raw production prompts or model output.</p><?php if(!$evidence):?><p class="empty">No evidence linked.</p><?php else:?><div class="unifiedActivityList"><?php foreach($evidence as $e):?><article class="unifiedActivityItem"><div class="unifiedActivityMain"><div class="unifiedActivityHead"><strong><?=h(str_replace('_',' ',$e['evidence_type']))?></strong><span class="meta"><?=h($e['created_at'])?></span></div><p class="meta">ref <?=h($e['evidence_ref_public_id'])?> · hash <?=h(substr((string)$e['evidence_hash'],0,18))?>…</p></div></article><?php endforeach?></div><?php endif?></section>

  <section class="card"><span class="eyebrow">SANITIZED IMPROVEMENT PROPOSAL</span><h2>Create evaluation or training evidence</h2><div class="notice">Do not paste raw production prompts, private user content, secrets, or model output. Rewrite the scenario into the minimum sanitized example needed to test or teach the intended behavior.</div>
    <form method="post" class="settingsForm"><?=csrf_field()?><input type="hidden" name="op" value="create_proposal"><input type="hidden" name="case" value="<?=h($case['public_id'])?>"><label>Type<select name="proposal_type"><option value="evaluation_case">Evaluation / regression case</option><option value="training_example">Training example</option></select></label><label>Title<input name="title" maxlength="255" required></label><label>Sanitized input / scenario<textarea name="sanitized_input" rows="5" required></textarea></label><label>Expected behavior / answer<textarea name="sanitized_expected_output" rows="5" required></textarea></label><label>Optional sanitized context<textarea name="sanitized_context" rows="4"></textarea></label><label>Why this reusable example is needed<textarea name="purpose_justification" rows="3"></textarea></label><label><input type="checkbox" name="redaction_attested" value="1"> I confirm raw production/private content has been removed or rewritten.</label><label><input type="checkbox" name="rights_attested" value="1"> I confirm this sanitized example is approved for the selected evaluation/training reuse.</label><button class="button">Create draft proposal</button></form>
  </section>

  <section class="card"><span class="eyebrow">PROPOSALS</span><h2>Human-sanitized reusable evidence</h2><?php if(!$proposals):?><p class="empty">No proposals yet.</p><?php else:?><div class="unifiedActivityList"><?php foreach($proposals as $p):?><article class="unifiedActivityItem"><div class="unifiedActivityMain"><div class="unifiedActivityHead"><div><span class="badge"><?=h($p['proposal_type'])?></span> <span class="badge"><?=h($p['status'])?></span> <strong><a href="/admin/model-improvements.php?case=<?=rawurlencode((string)$case['public_id'])?>&proposal=<?=rawurlencode((string)$p['public_id'])?>"><?=h($p['title'])?></a></strong></div><span class="meta"><?=h($p['updated_at'])?></span></div><p class="meta">content <?=h(substr((string)$p['content_hash'],0,16))?>…<?=!empty($p['corpus_item_public_id'])?' · corpus '.h($p['corpus_item_public_id']):''?></p></div></article><?php endforeach?></div><?php endif?></section>

  <?php if($proposal):?>
  <section class="card"><span class="eyebrow">PROPOSAL DETAIL</span><h2><?=h($proposal['title'])?></h2><p><span class="badge"><?=h($proposal['proposal_type'])?></span> <span class="badge"><?=h($proposal['status'])?></span></p>
    <?php if($proposal['status']==='draft'):?><form method="post" class="settingsForm"><?=csrf_field()?><input type="hidden" name="op" value="update_proposal"><input type="hidden" name="case" value="<?=h($case['public_id'])?>"><input type="hidden" name="proposal" value="<?=h($proposal['public_id'])?>"><label>Title<input name="title" value="<?=h($proposal['title'])?>" required></label><label>Sanitized input / scenario<textarea name="sanitized_input" rows="5" required><?=h($proposal['sanitized_input'])?></textarea></label><label>Expected behavior / answer<textarea name="sanitized_expected_output" rows="5" required><?=h($proposal['sanitized_expected_output'])?></textarea></label><label>Sanitized context<textarea name="sanitized_context" rows="4"><?=h((string)$proposal['sanitized_context'])?></textarea></label><label>Purpose justification<textarea name="purpose_justification" rows="3"><?=h((string)$proposal['purpose_justification'])?></textarea></label><label><input type="checkbox" name="redaction_attested" value="1" <?=$proposal['redaction_attested']?'checked':''?>> Redaction / rewrite attested</label><label><input type="checkbox" name="rights_attested" value="1" <?=$proposal['rights_attested']?'checked':''?>> Evaluation/training reuse approved</label><button class="button secondary">Update draft</button></form><form method="post"><?=csrf_field()?><input type="hidden" name="op" value="approve_proposal"><input type="hidden" name="case" value="<?=h($case['public_id'])?>"><input type="hidden" name="proposal" value="<?=h($proposal['public_id'])?>"><button class="button" <?=$proposal['redaction_attested']&&$proposal['rights_attested']?'':'disabled'?>>Approve sanitized proposal</button></form><?php endif?>
    <?php if($proposal['status']==='approved'):?><div class="notice success"><strong>APPROVED FOR GOVERNED REUSE</strong><br>Publishing admits only this sanitized text into the governed Phase 37 corpus. It does not create/freeze a dataset or run evaluation/training.</div><form method="post" onsubmit="return confirm('Publish this approved sanitized example into the governed corpus?');"><?=csrf_field()?><input type="hidden" name="op" value="publish_proposal"><input type="hidden" name="case" value="<?=h($case['public_id'])?>"><input type="hidden" name="proposal" value="<?=h($proposal['public_id'])?>"><button class="button">Publish to governed corpus</button></form><?php endif?>
    <?php if($proposal['status']==='published'):?><div class="notice success"><strong>PUBLISHED</strong><br>Governed corpus item <?=h((string)$proposal['corpus_item_public_id'])?>. <?=h($proposal['proposal_type']==='evaluation_case'?'Evaluation eligible only; not training eligible.':'Training eligible only; not evaluation or commercial-training eligible.')?></div><?php endif?>
    <p class="meta">Content hash <?=h($proposal['content_hash'])?><?=!empty($proposal['approval_hash'])?' · approval '.h($proposal['approval_hash']):''?></p>
  </section><?php endif?>

  <section class="card"><span class="eyebrow">AUDIT EVENTS</span><h2>Improvement case history</h2><?php if(!$events):?><p class="empty">No events.</p><?php else:?><div class="unifiedActivityList"><?php foreach($events as $e):?><article class="unifiedActivityItem"><div class="unifiedActivityMain"><div class="unifiedActivityHead"><strong><?=h(str_replace('_',' ',$e['event_type']))?></strong><span class="meta"><?=h($e['created_at'])?></span></div><p class="meta"><?=h((string)($e['actor_name']??'System'))?> · evidence <?=h(substr((string)$e['evidence_hash'],0,16))?>…</p></div></article><?php endforeach?></div><?php endif?></section>
  <?php endif?>

  <section class="card"><span class="eyebrow">REGRESSION LIBRARY</span><h2>Permanent approved production failures</h2><?php if(!$regressions):?><p class="empty">No published evaluation regression cases.</p><?php else:?><div class="unifiedActivityList"><?php foreach($regressions as $r):?><article class="unifiedActivityItem"><div class="unifiedActivityMain"><div class="unifiedActivityHead"><strong><a href="/admin/model-improvements.php?case=<?=rawurlencode((string)$r['case_public_id'])?>"><?=h($r['label'])?></a></strong><span class="meta"><?=h($r['created_at'])?></span></div><p class="meta"><?=h((string)($r['model_version_label']??'Any model'))?> · route <?=h($r['route_key'])?> · case <?=h(substr((string)$r['case_hash'],0,16))?>…</p></div></article><?php endforeach?></div><?php endif?></section>
</main></body></html>