<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';require_once dirname(__DIR__).'/app/ai.php';
$admin=require_admin($pdo);header('Cache-Control: private, no-store');header('Vary: Cookie');$success='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    require_csrf();$op=(string)($_POST['op']??'');
    try{
        if($op==='claim_status'){
            $id=(int)($_POST['id']??0);$status=(string)($_POST['status']??'under_review');$note=trim((string)($_POST['note']??''));$decision=trim((string)($_POST['decision']??''));
            rights_claim_update($pdo,$admin,$id,$status,$note,$decision);$success='Rights claim updated and logged.';
        }
        if($op==='report_status'){
            $id=(int)($_POST['id']??0);$status=(string)($_POST['status']??'under_review');$action=(string)($_POST['resolution_action']??'none');$note=trim((string)($_POST['note']??''));
            moderation_report_update($pdo,$admin,$id,$status,$action,$note);$success='Report updated and moderation action logged.';
        }
        if($op==='ai_claim'){
            $id=(int)($_POST['id']??0);$q=$pdo->prepare('SELECT public_id FROM rights_claims WHERE id=?');$q->execute([$id]);$public=(string)$q->fetchColumn();$model=ai_setting_model_id($pdo,'moderation');if(!$public||!$model)throw new RuntimeException('Configure a moderation model first.');ai_queue_job($pdo,(int)$admin['id'],'moderation_rights_triage',$model,'rights_claim',$public,[],2);$success='AI rights triage queued.';
        }
        if($op==='ai_report'){
            $id=(int)($_POST['id']??0);$q=$pdo->prepare('SELECT public_id FROM moderation_reports WHERE id=?');$q->execute([$id]);$public=(string)$q->fetchColumn();$model=ai_setting_model_id($pdo,'moderation');if(!$public||!$model)throw new RuntimeException('Configure a moderation model first.');ai_queue_job($pdo,(int)$admin['id'],'moderation_report_triage',$model,'moderation_report',$public,[],2);$success='AI moderation triage queued.';
        }
    }catch(Throwable $e){$error=$e->getMessage();}
}
$claims=$pdo->query("SELECT rc.*,a.public_id annotation_public_id,s.canonical_url,TIMESTAMPDIFF(HOUR,rc.created_at,NOW()) age_hours FROM rights_claims rc JOIN annotations a ON a.id=rc.annotation_id JOIN sources s ON s.id=a.source_id ORDER BY FIELD(rc.status,'submitted','appealed','reopened','under_review','restricted','resolved','rejected'),rc.updated_at DESC LIMIT 150")->fetchAll();
$reports=$pdo->query("SELECT mr.*,TIMESTAMPDIFF(HOUR,mr.created_at,NOW()) age_hours,(SELECT COUNT(*) FROM moderation_reports x WHERE x.object_type=mr.object_type AND x.object_public_id=mr.object_public_id) object_report_count FROM moderation_reports mr ORDER BY FIELD(mr.status,'open','under_review','actioned','dismissed'),mr.updated_at DESC LIMIT 150")->fetchAll();
$actions=$pdo->query("SELECT ma.*,u.display_name FROM moderation_actions ma JOIN users u ON u.id=ma.moderator_user_id ORDER BY ma.id DESC LIMIT 50")->fetchAll();
$runs=$pdo->query("SELECT task_type,scope_type,scope_public_id,output_text,status,created_at FROM ai_runs WHERE task_type LIKE 'moderation_%' ORDER BY created_at DESC LIMIT 20")->fetchAll();
$openClaims=count(array_filter($claims,fn($c)=>in_array($c['status'],['submitted','appealed','reopened','under_review'],true)));$openReports=count(array_filter($reports,fn($r)=>in_array($r['status'],['open','under_review'],true)));$aged=count(array_filter(array_merge($claims,$reports),fn($x)=>(int)$x['age_hours']>=72&&!in_array($x['status'],['resolved','rejected','actioned','dismissed'],true)));
function admin_moderation_target_url(PDO $pdo,array $r): ?string {
    return match($r['object_type']){
        'annotation'=>'/annotation.php?id='.rawurlencode($r['object_public_id']),
        'source'=>'/source.php?id='.rawurlencode($r['object_public_id']),
        'live_message'=>null,
        'comment'=>null,
        'user'=>(function()use($pdo,$r){$q=$pdo->prepare('SELECT username FROM users WHERE public_id=?');$q->execute([$r['object_public_id']]);$u=$q->fetchColumn();return $u?'/profile.php?u='.rawurlencode((string)$u):null;})(),
        default=>null
    };
}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Moderation · Annotated Admin</title><meta name="robots" content="noindex,nofollow"><link rel="stylesheet" href="/assets/css/app.css"></head><body>
<header class="topbar"><a class="brand" href="/admin/">Annotated Admin</a><nav><a href="/admin/ai.php">AI</a><a href="/admin/source-monitor.php">Sources</a><a href="/admin/users.php">Users</a></nav></header>
<main class="panel moderationConsole"><div class="pageTitle"><span class="eyebrow">HUMAN REVIEW REQUIRED</span><h1>Moderation & rights</h1><p>AI triage is advisory only. Final restrictions, removals, restorations, and claim decisions require an admin action and are written to the moderation audit trail.</p></div>
<?php if($success):?><div class="success"><?=h($success)?></div><?php endif?><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?>
<div class="trustStats"><div class="card"><strong><?=h((string)$openClaims)?></strong><span>open claims</span></div><div class="card"><strong><?=h((string)$openReports)?></strong><span>open reports</span></div><div class="card"><strong><?=h((string)$aged)?></strong><span>cases 72h+</span></div></div>
<h2>Rights claims</h2><?php if(!$claims):?><div class="card empty">No rights claims.</div><?php endif?><?php foreach($claims as $c):?><article class="card trustCase"><div class="caseHeader"><div><span class="badge"><?=h($c['status'])?></span> <span class="badge"><?=h($c['claim_type'])?></span><?php if((int)$c['age_hours']>=72&&!in_array($c['status'],['resolved','rejected'],true)):?><span class="badge warn"><?=h((string)$c['age_hours'])?>h open</span><?php endif?></div><span class="meta"><?=h($c['created_at'])?></span></div><h3>Claim <?=h($c['public_id'])?></h3><p><?=nl2br(h($c['description']))?></p><p><a href="/annotation.php?id=<?=h($c['annotation_public_id'])?>">Annotation</a> · <a href="<?=h($c['canonical_url'])?>" target="_blank" rel="noopener">Original source ↗</a> · <a href="/claim-status.php?id=<?=h($c['public_id'])?>">Admin status view</a></p>
<form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="op" value="claim_status"><input type="hidden" name="id" value="<?=h((string)$c['id'])?>"><label>Status<select name="status"><?php foreach(['submitted','under_review','restricted','resolved','rejected','appealed','reopened'] as $st):?><option value="<?=h($st)?>" <?=$c['status']===$st?'selected':''?>><?=h(str_replace('_',' ',$st))?></option><?php endforeach?></select></label><label>Internal moderator note<textarea name="note" rows="2"><?=h((string)$c['moderator_note'])?></textarea></label><label>Decision summary visible to claimant<textarea name="decision" rows="2"><?=h((string)$c['decision_summary'])?></textarea></label><button>Save decision</button></form><form method="post" class="inlineActions"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="op" value="ai_claim"><input type="hidden" name="id" value="<?=h((string)$c['id'])?>"><button class="button secondary">AI triage</button></form></article><?php endforeach?>
<h2>Community reports</h2><?php if(!$reports):?><div class="card empty">No community reports.</div><?php endif?><?php foreach($reports as $r):$targetUrl=admin_moderation_target_url($pdo,$r);?><article class="card trustCase"><div class="caseHeader"><div><span class="badge"><?=h($r['status'])?></span> <span class="badge"><?=h($r['object_type'])?></span><?php if((int)$r['object_report_count']>1):?><span class="badge warn"><?=h((string)$r['object_report_count'])?> reports on this object</span><?php endif?><?php if((int)$r['age_hours']>=72&&!in_array($r['status'],['actioned','dismissed'],true)):?><span class="badge warn"><?=h((string)$r['age_hours'])?>h open</span><?php endif?></div><span class="meta"><?=h($r['created_at'])?></span></div><h3><?=h(ucwords(str_replace('_',' ',(string)$r['reason'])))?></h3><p><?=nl2br(h((string)$r['description']))?></p><p class="meta">Object <?=h($r['object_public_id'])?><?php if($targetUrl):?> · <a href="<?=h($targetUrl)?>">Open object</a><?php endif?></p>
<form method="post" class="stack"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="op" value="report_status"><input type="hidden" name="id" value="<?=h((string)$r['id'])?>"><label>Status<select name="status"><?php foreach(['open','under_review','actioned','dismissed'] as $st):?><option value="<?=h($st)?>" <?=$r['status']===$st?'selected':''?>><?=h(str_replace('_',' ',$st))?></option><?php endforeach?></select></label><label>Object action<select name="resolution_action"><?php foreach(['none','warn','restrict','remove','restore'] as $act):?><option value="<?=h($act)?>" <?=$r['resolution_action']===$act?'selected':''?>><?=h($act)?></option><?php endforeach?></select></label><label>Moderator note<textarea name="note" rows="2"><?=h((string)$r['moderator_note'])?></textarea></label><button>Apply</button></form><form method="post" class="inlineActions"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="op" value="ai_report"><input type="hidden" name="id" value="<?=h((string)$r['id'])?>"><button class="button secondary">AI triage</button></form></article><?php endforeach?>
<h2>Recent moderation audit</h2><?php foreach($actions as $a):?><div class="historyItem"><strong><?=h(ucwords(str_replace('_',' ',(string)$a['action_type'])))?></strong> · <?=h($a['display_name'])?><div class="meta"><?=h($a['created_at'])?> · action <?=h($a['public_id'])?></div><?php if($a['reason']):?><p><?=nl2br(h((string)$a['reason']))?></p><?php endif?></div><?php endforeach?>
<h2>Recent AI triage</h2><?php foreach($runs as $r):?><div class="card"><div class="meta"><?=h($r['task_type'])?> · <?=h($r['scope_public_id'])?> · <?=h($r['status'])?></div><p><?=nl2br(h(mb_substr((string)$r['output_text'],0,4000)))?></p></div><?php endforeach?></main></body></html>