<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
$u=require_admin($pdo);
if(!data_model_observability_ready($pdo)){http_response_code(503);exit('Model Observability requires the Phase 45 database upgrade.');}
$error='';$success='';$deploymentPublic=trim((string)($_GET['deployment']??$_POST['deployment']??''));$incidentPublic=trim((string)($_GET['incident']??$_POST['incident']??''));
$deployment=null;$deploymentId=null;
if($deploymentPublic!==''){$q=$pdo->prepare('SELECT id FROM data_model_deployments WHERE public_id=? LIMIT 1');$q->execute([$deploymentPublic]);$deploymentId=(int)($q->fetchColumn()?:0)?:null;if($deploymentId)$deployment=data_model_observability_deployment_row($pdo,$deploymentId);}
if($_SERVER['REQUEST_METHOD']==='POST'){
    require_csrf();$op=(string)($_POST['op']??'');
    try{
        if($op==='backfill'){$count=data_model_observability_backfill($pdo,$u,(int)($_POST['limit']??500));$success='Captured '.$count.' historical AI run observation(s).';}
        if($op==='evaluate'&&$deploymentId){$snapshots=data_model_observability_evaluate_deployment($pdo,$deploymentId,true);$success='Created '.count($snapshots).' fresh health snapshot(s).';}
        if($op==='policy'&&$deploymentId){data_model_observability_policy_update($pdo,$u,$deploymentId,$_POST);$success='Monitoring policy updated. No routing or deployment state changed.';}
        if($op==='incident'&&$incidentPublic!==''){$i=data_model_observability_incident_update($pdo,$u,$incidentPublic,(string)($_POST['status']??''),(string)($_POST['note']??''));$success='Incident review updated to '.$i['status'].'.';}
    }catch(Throwable $e){$error=$e->getMessage();}
}
$stats=data_model_observability_summary($pdo);$incident=$incidentPublic!==''?data_model_observability_incident_get($pdo,$incidentPublic):null;$incidents=data_model_observability_incidents($pdo,100);
$deployments=$pdo->query("SELECT d.id,d.public_id,d.status,d.current_traffic_percent,d.created_at,d.full_at,cv.version_label candidate_version_label,r.name registry_name,(SELECT health_status FROM data_model_health_snapshots hs WHERE hs.deployment_id=d.id ORDER BY hs.id DESC LIMIT 1) latest_health,(SELECT created_at FROM data_model_health_snapshots hs WHERE hs.deployment_id=d.id ORDER BY hs.id DESC LIMIT 1) latest_health_at,(SELECT COUNT(*) FROM data_model_incidents i WHERE i.deployment_id=d.id AND i.status IN ('open','investigating')) open_incidents FROM data_model_deployments d JOIN data_model_versions cv ON cv.id=d.model_version_id JOIN data_model_registry r ON r.id=d.registry_id ORDER BY d.id DESC LIMIT 100")->fetchAll();
$policy=$deploymentId?data_model_observability_policy_get($pdo,$deploymentId,true):null;$snapshots=$deploymentId?data_model_observability_snapshots($pdo,$deploymentId,60):[];$observations=$deploymentId?data_model_observability_observations($pdo,$deploymentId,100):[];
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Model Observability · Annotated Admin</title><link rel="stylesheet" href="/assets/css/app.css"></head><body>
<main class="panel article">
  <div class="pageTitle"><span class="eyebrow">PHASE 45 · PRODUCTION MODEL OBSERVABILITY</span><h1>Model health & outcomes</h1><p>Measure production behavior, surface threshold breaches, and collect outcome evidence. This workspace can alert humans but cannot change model lifecycle, deployment stage, rollout traffic, training, or AI routing.</p></div>
  <div class="inlineActions"><a class="button secondary" href="/admin/model-deployment.php">Model Deployments</a><a class="button secondary" href="/admin/model-registry.php">Model Registry</a><a class="button secondary" href="/admin/ai.php">AI & LLM</a></div>
  <?php if($error):?><div class="notice error"><?=h($error)?></div><?php endif?><?php if($success):?><div class="notice success"><?=h($success)?></div><?php endif?>
  <section class="healthGrid">
    <article class="card"><strong><?=h((string)$stats['observations'])?></strong><p class="meta">Observed AI runs</p></article>
    <article class="card"><strong><?=h((string)$stats['last_24h'])?></strong><p class="meta">Last 24 hours</p></article>
    <article class="card"><strong><?=h((string)$stats['open_incidents'])?></strong><p class="meta">Open incidents</p></article>
    <article class="card"><strong><?=h((string)$stats['investigating'])?></strong><p class="meta">Investigating</p></article>
    <article class="card"><strong><?=h((string)$stats['critical'])?></strong><p class="meta">Critical attention</p></article>
  </section>
  <section class="card"><span class="eyebrow">TELEMETRY MAINTENANCE</span><h2>Capture earlier completed runs</h2><p class="meta">New AI runs are observed automatically. Backfill adds telemetry records only; it does not replay inference.</p><form method="post" class="inlineActions"><?=csrf_field()?><input type="hidden" name="op" value="backfill"><input type="number" name="limit" min="1" max="5000" value="500"><button class="button secondary">Backfill recent AI runs</button></form></section>

  <?php if($incident):?>
  <section class="card"><span class="eyebrow">INCIDENT REVIEW</span><h2><?=h($incident['title'])?></h2><p><span class="badge"><?=h($incident['severity'])?></span> <span class="badge"><?=h($incident['status'])?></span></p><p><?=h((string)$incident['summary'])?></p><div class="cognitiveCardMeta"><span><small>Route</small><?=h($incident['route_key'])?></span><span><small>Metric</small><?=h($incident['metric_name'])?></span><span><small>Observed</small><?=h((string)$incident['current_value'])?></span><span><small>Threshold</small><?=h((string)$incident['threshold_value'])?></span><span><small>Model</small><?=h((string)($incident['model_version_label']??'—'))?></span></div>
    <form method="post" class="settingsForm"><?=csrf_field()?><input type="hidden" name="op" value="incident"><input type="hidden" name="incident" value="<?=h($incident['public_id'])?>"><label>Status<select name="status"><?php foreach(['open','investigating','accepted','resolved'] as $s):?><option value="<?=h($s)?>" <?=$incident['status']===$s?'selected':''?>><?=h(ucfirst($s))?></option><?php endforeach?></select></label><label>Human review note<textarea name="note" rows="4"><?=h((string)$incident['review_note'])?></textarea></label><button class="button">Record human review</button></form><p class="meta">Reviewing an incident records evidence and status only. Rollback remains an explicit Phase 44 action.</p>
  </section><?php endif?>

  <section class="card"><span class="eyebrow">NEEDS ATTENTION</span><h2>Production health incidents</h2><?php if(!$incidents):?><p class="empty">No model-health incidents.</p><?php else:?><div class="unifiedActivityList"><?php foreach($incidents as $i):?><article class="unifiedActivityItem"><div class="unifiedActivityMain"><div class="unifiedActivityHead"><div><span class="badge"><?=h($i['severity'])?></span> <span class="badge"><?=h($i['status'])?></span> <strong><a href="/admin/model-observability.php?incident=<?=rawurlencode((string)$i['public_id'])?>"><?=h($i['title'])?></a></strong></div><span class="meta"><?=h($i['last_seen_at'])?></span></div><p><?=h((string)$i['summary'])?></p><p class="meta"><?=h($i['model_version_label']??'Model')?> · route <?=h($i['route_key'])?> · observed <?=h((string)$i['current_value'])?> / threshold <?=h((string)$i['threshold_value'])?></p></div></article><?php endforeach?></div><?php endif?></section>

  <section class="card"><span class="eyebrow">DEPLOYMENT HEALTH</span><h2>Governed production deployments</h2><?php if(!$deployments):?><p class="empty">No Phase 44 deployments yet.</p><?php else:?><div class="unifiedActivityList"><?php foreach($deployments as $d):?><article class="unifiedActivityItem"><div class="unifiedActivityMain"><div class="unifiedActivityHead"><div><span class="badge"><?=h($d['status'])?></span> <strong><a href="/admin/model-observability.php?deployment=<?=rawurlencode((string)$d['public_id'])?>"><?=h($d['candidate_version_label'])?></a></strong></div><span class="meta"><?=h((string)($d['latest_health']?:'not sampled'))?></span></div><p class="meta"><?=h($d['registry_name'])?> · <?=h((string)$d['current_traffic_percent'])?>% candidate traffic · <?=h((string)$d['open_incidents'])?> active incident(s)<?=!empty($d['latest_health_at'])?' · last snapshot '.h($d['latest_health_at']):''?></p></div></article><?php endforeach?></div><?php endif?></section>

  <?php if($deployment&&$policy):?>
  <section class="card"><span class="eyebrow">MONITORING POLICY</span><h2><?=h($deployment['public_id'])?> · <?=h($deployment['status'])?></h2><p class="meta">Routes: <?=h(implode(', ',(array)$deployment['route_keys']))?>. Thresholds produce evidence and alerts only.</p>
    <form method="post" class="settingsForm"><?=csrf_field()?><input type="hidden" name="op" value="policy"><input type="hidden" name="deployment" value="<?=h($deployment['public_id'])?>"><label><input type="checkbox" name="enabled" value="1" <?=$policy['enabled']?'checked':''?>> Monitoring enabled</label><label>Rolling window minutes<input type="number" name="window_minutes" min="15" max="10080" value="<?=h((string)$policy['window_minutes'])?>"></label><label>Minimum samples<input type="number" name="min_samples" min="1" max="10000" value="<?=h((string)$policy['min_samples'])?>"></label><label>Maximum failure rate (0–1)<input type="number" name="max_failure_rate" min="0" max="1" step="0.001" value="<?=h((string)$policy['max_failure_rate'])?>"></label><label>Maximum p95 latency ms<input type="number" name="max_p95_latency_ms" min="1" value="<?=h((string)$policy['max_p95_latency_ms'])?>"></label><label>Maximum candidate failure-rate delta vs baseline<input type="number" name="max_failure_rate_delta" min="0" max="1" step="0.001" value="<?=h((string)$policy['max_failure_rate_delta'])?>"></label><label>Maximum candidate p95 latency delta vs baseline (ms)<input type="number" name="max_p95_latency_delta_ms" min="0" value="<?=h((string)$policy['max_p95_latency_delta_ms'])?>"></label><label>Maximum average input tokens<input type="number" name="max_avg_input_tokens" min="0" value="<?=h((string)$policy['max_avg_input_tokens'])?>"></label><label>Maximum average output tokens<input type="number" name="max_avg_output_tokens" min="0" value="<?=h((string)$policy['max_avg_output_tokens'])?>"></label><label>Maximum average cost (micro-USD)<input type="number" name="max_avg_cost_micros" min="0" value="<?=h((string)$policy['max_avg_cost_micros'])?>"></label><label>Minimum average outcome score (-1 to 1)<input type="number" name="min_avg_outcome_score" min="-1" max="1" step="0.01" value="<?=h((string)$policy['min_avg_outcome_score'])?>"></label><button class="button">Save monitoring policy</button></form>
    <div class="inlineActions"><form method="post"><?=csrf_field()?><input type="hidden" name="op" value="evaluate"><input type="hidden" name="deployment" value="<?=h($deployment['public_id'])?>"><button class="button secondary">Refresh health now</button></form><form method="post" action="/admin/model-observability-export.php"><?=csrf_field()?><input type="hidden" name="deployment" value="<?=h($deployment['public_id'])?>"><button class="button secondary">Export health JSON</button></form><a class="button secondary" href="/admin/model-deployment.php?deployment=<?=rawurlencode((string)$deployment['public_id'])?>">Open Phase 44 deployment</a></div>
  </section>
  <section class="card"><span class="eyebrow">HEALTH SNAPSHOTS</span><h2>Rolling route metrics</h2><?php if(!$snapshots):?><p class="empty">No health snapshots yet.</p><?php else:?><div class="unifiedActivityList"><?php foreach($snapshots as $s):$m=$s['metrics'];?><article class="unifiedActivityItem"><div class="unifiedActivityMain"><div class="unifiedActivityHead"><div><span class="badge"><?=h($s['health_status'])?></span> <strong><?=h($s['route_key'])?></strong></div><span class="meta"><?=h($s['created_at'])?></span></div><p class="meta">samples <?=h((string)$m['sample_count'])?> · failures <?=h(number_format((float)$m['failure_rate']*100,1))?>% · avg latency <?=h($m['avg_latency_ms']!==null?number_format((float)$m['avg_latency_ms'],1):'—')?> ms · p95 <?=h($m['p95_latency_ms']!==null?number_format((float)$m['p95_latency_ms'],1):'—')?> ms · input <?=h($m['avg_input_tokens']!==null?number_format((float)$m['avg_input_tokens'],1):'—')?> · output <?=h($m['avg_output_tokens']!==null?number_format((float)$m['avg_output_tokens'],1):'—')?> · outcome <?=h($m['avg_outcome_score']!==null?number_format((float)$m['avg_outcome_score'],2):'—')?> · failure drift <?=h(($m['candidate_vs_baseline']['failure_rate_delta']??null)!==null?number_format((float)$m['candidate_vs_baseline']['failure_rate_delta']*100,1).'%':'—')?> · p95 drift <?=h(($m['candidate_vs_baseline']['p95_latency_delta_ms']??null)!==null?number_format((float)$m['candidate_vs_baseline']['p95_latency_delta_ms'],1).' ms':'—')?> · shadow <?=h((string)$m['shadow_candidate_count'])?></p><p class="meta">metrics hash <?=h(substr((string)$s['metrics_hash'],0,16))?>…</p></div></article><?php endforeach?></div><?php endif?></section>
  <section class="card"><span class="eyebrow">RUN TELEMETRY</span><h2>Recent observed inference</h2><?php if(!$observations):?><p class="empty">No observations for this deployment.</p><?php else:?><div class="unifiedActivityList"><?php foreach($observations as $o):?><article class="unifiedActivityItem"><div class="unifiedActivityMain"><div class="unifiedActivityHead"><div><span class="badge"><?=h($o['run_status'])?></span> <strong><?=h($o['route_key'])?> · <?=h($o['source_task_type'])?></strong></div><span class="meta"><?=h($o['observed_at'])?></span></div><p class="meta"><?=h((string)($o['model_version_label']?:$o['ai_model_name']?:'runtime'))?><?=((int)$o['is_shadow'])?' · SHADOW':''?> · latency <?=h($o['latency_ms']!==null?(string)$o['latency_ms'].' ms':'—')?> · tokens <?=h((string)($o['input_tokens']??'—'))?>/<?=h((string)($o['output_tokens']??'—'))?> · cost <?=h($o['estimated_cost_micros']!==null?(string)$o['estimated_cost_micros'].' μUSD':'—')?><?=!empty($o['error_class'])?' · '.h($o['error_class']):''?></p></div></article><?php endforeach?></div><?php endif?></section>
  <?php endif?>
</main></body></html>
