<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
$admin=require_admin($pdo);$success='';$error='';
if(!ai_overage_ready($pdo)){http_response_code(503);exit('AI Overage Billing requires migration 070.');}
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();try{
    $op=(string)($_POST['op']??'');
    if($op==='settings'){ai_overage_save_settings($pdo,$admin,$_POST);$success='AI overage billing settings saved.';}
    elseif($op==='reconcile'){ai_overage_reconcile_account($pdo,$config,$admin,(string)($_POST['account_id']??''));$success='AI overage billing reconciled with Stripe.';}
    elseif($op==='report'){ $r=ai_overage_report_pending($pdo,$config,null,250);$success='Overage reporting run complete: '.(int)$r['reported'].' reported, '.(int)$r['failed'].' failed, '.(int)$r['skipped'].' skipped.'; }
    else throw new RuntimeException('Unknown AI overage billing action.');
}catch(Throwable $e){$error=$e->getMessage();}}
$settings=ai_overage_settings($pdo);$accounts=ai_overage_admin_accounts($pdo,250);$ledger=ai_overage_recent_ledger($pdo,100);$batches=ai_overage_recent_batches($pdo,100);$thresholds=ai_overage_recent_thresholds($pdo,100);
$totalAccrued=0;$totalReported=0;$enabled=0;$atCap=0;foreach($accounts as $a){$o=$a['overage'];$totalAccrued+=(int)$o['accrued_micros'];$totalReported+=(int)$o['reported_micros'];if($o['policy']['enabled'])$enabled++;if($o['remaining_cap_micros']!==null&&(int)$o['remaining_cap_micros']<=0)$atCap++;}
$moneyMicros=fn(int $m)=>'$'.number_format($m/1000000,6);
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AI Overage Billing · Annotated Admin</title><link rel="stylesheet" href="/assets/css/app.css"></head><body><?=admin_ui_sidebar('overage_billing')?>
<main class="panel adminOverageBillingPage"><div class="pageTitle"><span class="eyebrow">ADMIN V1.70</span><h1>AI overage billing & usage plans</h1><p>The local usage ledger is authoritative. Overage is opt-in, capped, Test/Live isolated, accumulated at micro-dollar precision, and reported to the account's Stripe subscription.</p></div>
<?php if($success):?><div class="success"><?=h($success)?></div><?php endif?><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?>
<section class="billingKpiGrid"><article class="card"><span class="meta">Opted-in accounts</span><strong><?=h((string)$enabled)?></strong></article><article class="card"><span class="meta">Accounts at cap</span><strong><?=h((string)$atCap)?></strong></article><article class="card"><span class="meta">Accrued overage</span><strong><?=h($moneyMicros($totalAccrued))?></strong></article><article class="card"><span class="meta">Reported to Stripe</span><strong><?=h($moneyMicros($totalReported))?></strong></article></section>
<section class="adminBillingGrid"><article class="card"><span class="eyebrow">POLICY</span><h2>Reporting & threshold settings</h2><form method="post" class="stack"><?=csrf_field()?><input type="hidden" name="op" value="settings"><label><input type="checkbox" name="stripe_reporting_enabled" value="1" <?=!empty($settings['stripe_reporting_enabled'])?'checked':''?>> Report accumulated overage to Stripe</label><label>Allowance thresholds<input name="usage_thresholds" value="<?=h(implode(',',ai_overage_threshold_list($settings['usage_thresholds_json'],[50,75,90,100])))?>" placeholder="50,75,90,100"></label><label>Cap thresholds<input name="cap_thresholds" value="<?=h(implode(',',ai_overage_threshold_list($settings['cap_thresholds_json'],[75,90,100])))?>" placeholder="75,90,100"></label><button>Save settings</button></form><p class="meta">Customer overage remains off until explicitly enabled per account.</p></article>
<article class="card"><span class="eyebrow">OPERATIONS</span><h2>Stripe reporting</h2><form method="post"><?=csrf_field()?><input type="hidden" name="op" value="report"><button>Report pending overage</button></form><p class="meta">The daily <code>php bin/billing-operations.php</code> runner also performs this operation. Replays are protected by a durable idempotency key.</p></article></section>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">ACCOUNTS</span><h2>Current AI overage state</h2></div></div><div class="tableWrap"><table><thead><tr><th>Account</th><th>Package</th><th>Policy</th><th>Opt-in</th><th>Overage</th><th>Accrued</th><th>Reported</th><th>Cap remaining</th><th>Reconcile</th></tr></thead><tbody><?php foreach($accounts as $a):$o=$a['overage'];$p=$o['policy'];?><tr><td><a href="/admin/account.php?id=<?=h(rawurlencode((string)$a['public_id']))?>"><?=h((string)$a['name'])?></a><div class="meta"><?=h((string)$a['public_id'])?></div></td><td><?=h((string)$a['package_name'])?></td><td><?=h((string)$p['package_policy'])?><div class="meta">In $<?=h(number_format(((int)$p['input_rate_micros_per_million'])/1000000,6))?> / Out $<?=h(number_format(((int)$p['output_rate_micros_per_million'])/1000000,6))?> per 1M</div></td><td><?=$p['enabled']?'Enabled':'Off'?></td><td><?=h(number_format((int)$o['overage_tokens']))?> tokens</td><td><?=h($moneyMicros((int)$o['accrued_micros']))?></td><td><?=h($moneyMicros((int)$o['reported_micros']))?></td><td><?=$o['remaining_cap_micros']===null?'No cap':h($moneyMicros((int)$o['remaining_cap_micros']))?></td><td><form method="post"><?=csrf_field()?><input type="hidden" name="op" value="reconcile"><input type="hidden" name="account_id" value="<?=h((string)$a['public_id'])?>"><button class="button secondary">Reconcile</button></form></td></tr><?php endforeach?><?php if(!$accounts):?><tr><td colspan="9" class="empty">No commercial accounts.</td></tr><?php endif?></tbody></table></div></section>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">IMMUTABLE OVERAGE LEDGER</span><h2>Recent billable usage attribution</h2></div></div><div class="tableWrap"><table><thead><tr><th>When</th><th>Account</th><th>Model</th><th>Included</th><th>Overage</th><th>Amount</th><th>Mode</th></tr></thead><tbody><?php foreach($ledger as $l):?><tr><td><?=h((string)$l['created_at'])?></td><td><?=h((string)$l['account_name'])?></td><td><?=h((string)($l['model_name']?:'Unknown'))?></td><td><?=h(number_format((int)$l['included_input_tokens']+(int)$l['included_output_tokens']))?></td><td><?=h(number_format((int)$l['overage_tokens']))?></td><td><?=h($moneyMicros((int)$l['amount_micros']))?><?=$l['cap_limited']?' · capped':''?></td><td><?=h((string)$l['stripe_mode'])?></td></tr><?php endforeach?><?php if(!$ledger):?><tr><td colspan="7" class="empty">No overage ledger entries yet.</td></tr><?php endif?></tbody></table></div></section>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">STRIPE REPORTING LEDGER</span><h2>Invoice-item batches</h2></div></div><div class="tableWrap"><table><thead><tr><th>When</th><th>Account</th><th>Period</th><th>Amount</th><th>Status</th><th>Invoice item</th><th>Invoice</th><th>Error</th></tr></thead><tbody><?php foreach($batches as $b):?><tr><td><?=h((string)$b['created_at'])?></td><td><?=h((string)$b['account_name'])?></td><td><?=h((string)$b['period_start'])?> → <?=h((string)$b['period_end'])?></td><td>$<?=h(number_format(((int)$b['amount_cents'])/100,2))?></td><td><?=h((string)$b['status'])?></td><td><code><?=h((string)($b['stripe_invoice_item_id']?:'—'))?></code></td><td><code><?=h((string)($b['stripe_invoice_id']?:'—'))?></code></td><td><?=h((string)($b['last_error']?:'—'))?></td></tr><?php endforeach?><?php if(!$batches):?><tr><td colspan="8" class="empty">No Stripe overage batches yet.</td></tr><?php endif?></tbody></table></div></section>
<section class="card"><span class="eyebrow">THRESHOLDS</span><h2>Recent allowance & cap milestones</h2><?php foreach($thresholds as $t):?><div class="historyItem"><strong><?=h((string)$t['account_name'])?> · <?=h((string)$t['threshold_type'])?> <?=h((string)$t['threshold_percent'])?>%</strong><div class="meta"><?=h((string)$t['period_start'])?> → <?=h((string)$t['period_end'])?> · <?=h((string)$t['created_at'])?></div></div><?php endforeach?><?php if(!$thresholds):?><p class="empty">No threshold milestones recorded yet.</p><?php endif?></section>
</main></body></html>
