<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
if(PHP_SAPI!=='cli')header('Cache-Control: no-store, private');
$admin=require_admin($pdo);if(!admin_platform_ready($pdo)){http_response_code(503);exit('Admin V2.60 Platform Governance requires migration 079.');}
admin_access_assert_capability($pdo,$admin,'admin.platform.view');
$canManage=admin_access_has_capability($pdo,$admin,'admin.platform.manage');$canRelease=admin_access_has_capability($pdo,$admin,'admin.platform.release');$canRequest=admin_access_has_capability($pdo,$admin,'admin.actions.request');$canExecute=admin_access_has_capability($pdo,$admin,'admin.actions.execute');$success='';$error='';$preview=null;$selected=null;
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();try{$op=(string)($_POST['op']??'');
    if($op==='feature_preview'){if(!$canManage||!$canRequest)throw new RuntimeException('Your operator role cannot request platform feature changes.');$preview=admin_platform_feature_action_preview($pdo,$admin,(string)($_POST['feature_id']??''),$_POST);$selected=$preview['record'];$success='Feature change preview created. Review it before requesting approval.';}
    elseif($op==='request_approval'){$selected=admin_access_action_request_approval($pdo,$admin,(string)($_POST['record_id']??''));$success='Feature rollout approval requested.';}
    elseif($op==='execute'){if(!$canExecute)throw new RuntimeException('Your operator role cannot execute governed actions.');$selected=admin_ops_action_execute($pdo,$config,$admin,(string)($_POST['record_id']??''));$success='Approved platform feature change executed.';}
    elseif($op==='module_update'){if(!$canManage)throw new RuntimeException('Your operator role cannot manage module governance.');admin_platform_module_update($pdo,$admin,(string)($_POST['module_id']??''),$_POST);$success='Module governance metadata updated.';}
    elseif($op==='integration_update'){if(!$canManage)throw new RuntimeException('Your operator role cannot manage integration governance.');admin_platform_integration_update($pdo,$admin,(string)($_POST['integration_id']??''),$_POST);$success='Integration governance metadata updated.';}
    elseif($op==='snapshot'){if(!$canRelease)throw new RuntimeException('Your operator role cannot capture release snapshots.');$type=(string)($_POST['snapshot_type']??'release_readiness');admin_platform_capture_snapshot($pdo,$config,$admin,$type,(string)($_POST['reason']??''));$success=$type==='drift_baseline'?'New drift baseline captured.':'Platform readiness snapshot captured.';}
    else throw new RuntimeException('Unknown Platform Governance operation.');
}catch(Throwable $e){$error=$e->getMessage();}}
if(!$selected&&!empty($_GET['record']))$selected=admin_ops_action_record($pdo,(string)$_GET['record']);
$metrics=admin_platform_metrics($pdo,$config);$features=admin_platform_features($pdo);$modules=admin_platform_modules($pdo);$integrations=admin_platform_integrations($pdo,$config);$safe=admin_platform_safe_config_summary($pdo,$config,dirname(__DIR__));$drift=admin_platform_drift($pdo,$config);$events=admin_platform_events($pdo,120);$baseline=admin_platform_latest_snapshot($pdo,'drift_baseline');$readiness=admin_platform_latest_snapshot($pdo,'release_readiness');$selectedSummary=$selected&&admin_access_ready($pdo)?admin_access_action_approval_summary($pdo,$selected):null;
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Platform Governance · Annotated Admin</title><link rel="stylesheet" href="/assets/css/app.css"></head><body><?=admin_ui_sidebar('platform_governance')?>
<main class="panel"><div class="pageTitle"><span class="eyebrow">ADMIN V2.60 · PLATFORM CONFIGURATION, FEATURE GOVERNANCE & RELEASE OPERATIONS</span><h1>Platform Governance</h1><p>Govern feature rollout, inspect module and integration state, verify deployment readiness, and detect configuration drift without creating a second deployment or secret-management system.</p></div>
<?php if($success):?><div class="success"><?=h($success)?></div><?php endif?><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?>
<section class="adminAccountSummaryGrid">
<article class="card"><span class="meta">Release readiness</span><strong><?=$metrics['release_ready']?'READY':'BLOCKED'?></strong></article>
<article class="card"><span class="meta">Schema</span><strong><?=$metrics['schema_ready']?'CURRENT':'ATTENTION'?></strong></article>
<article class="card"><span class="meta">Governed features</span><strong><?=h((string)$metrics['features'])?></strong><small><?=h((string)$metrics['enforced_features'])?> enforce mode</small></article>
<article class="card"><span class="meta">Integration health</span><strong><?=h((string)$metrics['degraded_integrations'])?> degraded</strong></article>
<article class="card"><span class="meta">Module mismatches</span><strong><?=h((string)$metrics['module_mismatches'])?></strong></article>
<article class="card"><span class="meta">Configuration drift</span><strong><?=h(strtoupper((string)$metrics['drift_status']))?></strong></article>
</section>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">RELEASE & ENVIRONMENT</span><h2>Authoritative deployment state</h2></div><div class="inlineActions"><a class="button secondary" href="/admin/system-health.php">System Health</a><a class="button secondary" href="/admin/security-compliance.php?domain=platform">Security audit</a></div></div>
<div class="billingSubscriptionFacts"><div><span>Release</span><strong><?=h((string)($safe['release']['release']??'—'))?> · <?=h((string)($safe['release']['version']??'—'))?></strong></div><div><span>Build SHA</span><strong><code><?=h((string)($safe['release']['build_sha']??'—'))?></code></strong></div><div><span>Latest migration</span><strong><code><?=h((string)($safe['release']['latest_migration']??'—'))?></code></strong></div><div><span>Package fingerprint</span><strong><code><?=h(substr((string)($safe['release']['package_fingerprint']??'—'),0,24))?>…</code></strong></div><div><span>Base URL</span><strong><?=h((string)$safe['app']['base_url'])?></strong></div><div><span>Private storage</span><strong><?=$safe['storage']['configured']&&$safe['storage']['exists']&&$safe['storage']['writable']?'READY':'ATTENTION'?></strong></div></div>
<p class="meta">Secrets are never displayed here. Package fingerprint, migration state, runtime requirements, workers, backups and environment checks continue to come from the existing release operations stack.</p>
<?php if($canRelease):?><form method="post" class="inlineActions"><?=csrf_field()?><input type="hidden" name="op" value="snapshot"><select name="snapshot_type"><option value="release_readiness">Release readiness snapshot</option><option value="configuration">Configuration snapshot</option><option value="drift_baseline">Set drift baseline</option></select><input name="reason" required value="Capture V2.60 platform readiness evidence."><button>Capture snapshot</button></form><?php endif?>
<div class="historyItem"><strong>Drift status: <?=h(strtoupper((string)$drift['status']))?></strong><div class="meta">Current fingerprint <code><?=h(substr((string)$drift['current_fingerprint'],0,24))?>…</code><?php if($baseline):?> · baseline <?=h((string)$baseline['created_at'])?><?php endif?></div><?php if($drift['changed_sections']):?><p>Changed sections: <?=h(implode(', ',$drift['changed_sections']))?></p><?php elseif(!$baseline):?><p>No drift baseline exists yet.</p><?php else:?><p>Current governed configuration matches the latest baseline.</p><?php endif?></div></section>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">FEATURE GOVERNANCE</span><h2>Rollout controls</h2></div><span class="badge">Preview → Approve → Execute</span></div><p class="meta">Existing features are seeded in observation mode so V2.60 does not silently change current product behavior. Enforced gates become authoritative where product code explicitly consults the V2.60 feature API.</p>
<div class="tableWrap"><table><thead><tr><th>Feature</th><th>Lifecycle</th><th>Mode</th><th>Rollout</th><th>Eligibility</th><th>Dependencies</th><th>Governance</th></tr></thead><tbody><?php foreach($features as $f):?><tr><td><strong><?=h((string)$f['name'])?></strong><div class="meta"><code><?=h((string)$f['feature_key'])?></code> · <?=h((string)$f['category'])?></div></td><td><?=h((string)$f['lifecycle_status'])?></td><td><?=h((string)$f['enforcement_mode'])?> · <?=((int)$f['default_enabled'])?'enabled':'disabled'?></td><td><?=h((string)$f['rollout_percent'])?>%</td><td><span class="meta"><?=count($f['packages'])?> packages · <?=count($f['accounts'])?> accounts</span></td><td><?=h($f['dependencies']?implode(', ',$f['dependencies']):'—')?></td><td><?php if($canManage&&$canRequest):?><details><summary>Request change</summary><form method="post" class="stack"><?=csrf_field()?><input type="hidden" name="op" value="feature_preview"><input type="hidden" name="feature_id" value="<?=h((string)$f['public_id'])?>"><label>Lifecycle<select name="lifecycle_status"><?php foreach(['draft','pilot','active','paused','retired'] as $v):?><option value="<?=h($v)?>" <?=$f['lifecycle_status']===$v?'selected':''?>><?=h(ucfirst($v))?></option><?php endforeach?></select></label><label>Enforcement<select name="enforcement_mode"><option value="observe" <?=$f['enforcement_mode']==='observe'?'selected':''?>>Observe</option><option value="enforce" <?=$f['enforcement_mode']==='enforce'?'selected':''?>>Enforce</option></select></label><label><input type="checkbox" name="default_enabled" value="1" <?=((int)$f['default_enabled'])?'checked':''?>> Default enabled</label><label>Rollout %<input type="number" min="0" max="100" name="rollout_percent" value="<?=h((string)$f['rollout_percent'])?>"></label><label>Package public IDs<input name="packages" value="<?=h(implode(', ',$f['packages']))?>" placeholder="blank = any package"></label><label>Account public IDs<input name="accounts" value="<?=h(implode(', ',$f['accounts']))?>" placeholder="blank = any account"></label><label>Dependencies<input name="dependencies" value="<?=h(implode(', ',$f['dependencies']))?>" placeholder="feature keys"></label><label>Reason<textarea name="reason" required rows="2">Govern platform feature rollout.</textarea></label><button>Create governed preview</button></form></details><?php else:?><span class="meta">Read only</span><?php endif?></td></tr><?php endforeach?></tbody></table></div></section>
<?php if($selected&&$selected['action_type']==='change_platform_feature'):$req=json_decode((string)$selected['request_json'],true)?:[];$required=(int)($selected['required_approvals']??0);?><section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">FEATURE CHANGE REVIEW</span><h2><?=h((string)($req['feature_key']??'Platform feature'))?></h2></div><span class="badge"><?=h(strtoupper((string)$selected['status']))?></span></div><pre><?=h((string)json_encode(['before'=>$req['before']??null,'after'=>$req['after']??null],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES))?></pre><p><?=h((string)$selected['reason'])?></p><div class="inlineActions"><?php if($selected['status']==='previewed'&&$required>0&&(int)$selected['actor_user_id']===(int)$admin['id']&&$canRequest):?><form method="post"><?=csrf_field()?><input type="hidden" name="op" value="request_approval"><input type="hidden" name="record_id" value="<?=h((string)$selected['public_id'])?>"><button>Request approval</button></form><?php endif?><?php if($selected['status']==='approved'&&(int)$selected['actor_user_id']===(int)$admin['id']&&$canExecute):?><form method="post"><?=csrf_field()?><input type="hidden" name="op" value="execute"><input type="hidden" name="record_id" value="<?=h((string)$selected['public_id'])?>"><button>Execute approved change</button></form><?php endif?><a class="button secondary" href="/admin/action-center.php?record=<?=h(rawurlencode((string)$selected['public_id']))?>">Open in Action Center</a></div><div class="meta">Approvals <?=h((string)($selectedSummary['approved']??0))?> / <?=h((string)($selectedSummary['required']??$required))?> · correlation <code><?=h((string)$selected['correlation_id'])?></code></div></section><?php endif?>
<section class="adminContentSplit"><article class="card"><span class="eyebrow">MODULE REGISTRY</span><h2>Desired vs observed state</h2><p class="meta">Desired state is governance metadata; runtime availability is observed from the authoritative application and schema.</p><?php foreach($modules as $m):$obs=admin_platform_module_observed($pdo,$m);?><div class="historyItem"><strong><?=h((string)$m['name'])?></strong><div class="meta"><?=h((string)$m['version_label'])?> · desired <?=h((string)$m['desired_state'])?> · observed <?=h((string)$obs['state'])?></div><?php if(!$obs['matches_desired']):?><span class="badge">Mismatch</span><?php endif?><?php if($canManage):?><form method="post" class="adminInlineForm"><?=csrf_field()?><input type="hidden" name="op" value="module_update"><input type="hidden" name="module_id" value="<?=h((string)$m['public_id'])?>"><select name="desired_state"><?php foreach(['enabled','maintenance','disabled'] as $v):?><option value="<?=h($v)?>" <?=$m['desired_state']===$v?'selected':''?>><?=h(ucfirst($v))?></option><?php endforeach?></select><input name="owner_note" value="<?=h((string)($m['owner_note']??''))?>" placeholder="Owner / note"><input name="reason" required placeholder="Reason"><button class="button secondary">Save</button></form><?php endif?></div><?php endforeach?></article>
<article class="card"><span class="eyebrow">INTEGRATION REGISTRY</span><h2>Configuration health without secrets</h2><p class="meta">Health is derived from existing provider/configuration authorities. V2.60 stores desired state and ownership notes only.</p><?php foreach($integrations as $i):?><div class="historyItem"><strong><?=h((string)$i['name'])?></strong><div class="meta"><?=h((string)$i['provider'])?> · <?=h((string)$i['category'])?> · <?=h((string)$i['health_state'])?></div><p><?=h((string)$i['health_detail'])?></p><?php if($canManage):?><form method="post" class="adminInlineForm"><?=csrf_field()?><input type="hidden" name="op" value="integration_update"><input type="hidden" name="integration_id" value="<?=h((string)$i['public_id'])?>"><select name="desired_state"><option value="enabled" <?=$i['desired_state']==='enabled'?'selected':''?>>Enabled</option><option value="disabled" <?=$i['desired_state']==='disabled'?'selected':''?>>Disabled</option></select><input name="owner_note" value="<?=h((string)($i['owner_note']??''))?>" placeholder="Owner / note"><input name="reason" required placeholder="Reason"><button class="button secondary">Save</button></form><?php endif?></div><?php endforeach?></article></section>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">PLATFORM CHANGE LEDGER</span><h2>Recent governance evidence</h2></div><a class="button secondary" href="/admin/security-compliance.php?domain=platform">Full security timeline</a></div><?php foreach($events as $e):?><div class="historyItem"><strong><?=h(ucwords(str_replace('_',' ',(string)$e['event_type'])))?></strong><div class="meta"><?=h((string)$e['created_at'])?> · <?=h((string)($e['actor_display_name']?:$e['actor_username']))?> · <?=h((string)$e['subject_type'])?><?php if($e['correlation_id']):?> · <code><?=h((string)$e['correlation_id'])?></code><?php endif?></div><p><?=h((string)$e['reason'])?></p></div><?php endforeach?><?php if(!$events):?><p class="empty">No V2.60 platform governance events yet.</p><?php endif?></section>
</main></body></html>