<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
$admin=require_admin($pdo);if(!admin_access_ready($pdo)){http_response_code(503);exit('Admin V2.10 roles and approval policies require migration 074.');}
admin_access_assert_capability($pdo,$admin,'admin.roles.view');$canManage=admin_access_is_super_admin($pdo,$admin);$success='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();try{
    if(!$canManage)throw new RuntimeException('Super Admin authority is required.');
    $op=(string)($_POST['op']??'');
    if($op==='assign_operator'){admin_access_assign_operator($pdo,$admin,(int)($_POST['user_id']??0),(string)($_POST['role_public_id']??''),(string)($_POST['operator_status']??'active'),(string)($_POST['reason']??''));$success='Admin operator role updated.';}
    elseif($op==='save_role'){admin_access_role_save($pdo,$admin,$_POST);$success='Custom Admin role saved.';}
    elseif($op==='save_policy'){admin_access_approval_policy_save($pdo,$admin,(string)($_POST['policy_public_id']??''),$_POST);$success='Approval policy updated.';}
    else throw new RuntimeException('Unknown roles and permissions operation.');
}catch(Throwable $e){$error=$e->getMessage();}}
$roles=admin_access_roles($pdo,false);$activeRoles=array_values(array_filter($roles,fn($r)=>$r['status']==='active'));$operators=admin_access_admin_operators($pdo);$policies=admin_access_approval_policies($pdo);$events=admin_access_security_events($pdo,120);$registry=admin_access_capability_registry();$groups=[];foreach($registry as $cap=>$meta)$groups[(string)$meta['group']][$cap]=$meta;
$editRole=null;if(!empty($_GET['edit_role'])){$candidate=admin_access_role($pdo,(string)$_GET['edit_role']);if($candidate&&!$candidate['is_system'])$editRole=$candidate;}$editCaps=$editRole?admin_access_role_caps($editRole):[];
$profile=admin_access_profile($pdo,$admin);
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Roles & Permissions · Annotated Admin</title><link rel="stylesheet" href="/assets/css/app.css"></head><body><?=admin_ui_sidebar('roles_permissions')?>
<main class="panel adminRolesPermissionsPage"><div class="pageTitle"><span class="eyebrow">ADMIN V2.10</span><h1>Roles, delegated permissions & approval policies</h1><p>Site-admin authentication remains the outer boundary. Operator roles now determine which Admin surfaces can be viewed or mutated, while elevated governed actions can require approval from a different authorized administrator.</p></div>
<?php if($success):?><div class="success"><?=h($success)?></div><?php endif?><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?>
<section class="adminAccountSummaryGrid"><article class="card"><span class="meta">Your operator role</span><strong><?=h((string)$profile['role_name'])?></strong></article><article class="card"><span class="meta">Role registry</span><strong><?=h((string)count($roles))?></strong></article><article class="card"><span class="meta">Admin operators</span><strong><?=h((string)count($operators))?></strong></article><article class="card"><span class="meta">Approval policies</span><strong><?=h((string)count($policies))?></strong></article></section>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">OPERATORS</span><h2>Delegated Admin assignments</h2></div><?php if(!$canManage):?><span class="badge">VIEW ONLY</span><?php endif?></div><p class="meta">Only existing <code>users.role='admin'</code> accounts can receive an operator role. The last active Super Admin cannot be demoted or disabled.</p><div class="tableWrap"><table><thead><tr><th>Administrator</th><th>Operator role</th><th>Status</th><th>Assigned</th><th>Administration</th></tr></thead><tbody><?php foreach($operators as $op):?><tr><td><strong><?=h((string)($op['display_name']?:$op['username']))?></strong><div class="meta">@<?=h((string)$op['username'])?> · <?=h((string)$op['email'])?></div></td><td><strong><?=h((string)$op['role_name'])?></strong><div class="meta"><code><?=h((string)$op['role_key'])?></code></div></td><td><?=h((string)($op['operator_status']?:'active'))?></td><td><?=h((string)($op['assigned_at']?:'Legacy / implicit'))?><?php if($op['assigned_by_username']):?><div class="meta">by @<?=h((string)$op['assigned_by_username'])?></div><?php endif?></td><td><?php if($canManage):?><form method="post" class="stack"><?=csrf_field()?><input type="hidden" name="op" value="assign_operator"><input type="hidden" name="user_id" value="<?=h((string)$op['id'])?>"><label>Role<select name="role_public_id"><?php foreach($activeRoles as $role):?><option value="<?=h((string)$role['public_id'])?>" <?=$op['role_key']===$role['role_key']?'selected':''?>><?=h((string)$role['name'])?></option><?php endforeach?></select></label><label>Status<select name="operator_status"><option value="active" <?=($op['operator_status']?:'active')==='active'?'selected':''?>>Active</option><option value="disabled" <?=$op['operator_status']==='disabled'?'selected':''?>>Disabled</option></select></label><label>Reason<input name="reason" required maxlength="500" placeholder="Reason for access change"></label><button>Update operator</button></form><?php else:?><span class="meta">Super Admin required.</span><?php endif?></td></tr><?php endforeach?></tbody></table></div></section>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">ROLE REGISTRY</span><h2>System and custom roles</h2></div></div><div class="tableWrap"><table><thead><tr><th>Role</th><th>Type</th><th>Status</th><th>Operators</th><th>Capabilities</th><th></th></tr></thead><tbody><?php foreach($roles as $role):$caps=admin_access_role_caps($role);?><tr><td><strong><?=h((string)$role['name'])?></strong><div class="meta"><code><?=h((string)$role['role_key'])?></code></div><div class="meta"><?=h((string)($role['description']??''))?></div></td><td><?=$role['is_system']?'System':'Custom'?></td><td><?=h((string)$role['status'])?></td><td><?=h((string)$role['assigned_count'])?></td><td><?php foreach($caps as $cap):?><code><?=h($cap)?></code> <?php endforeach?></td><td><?php if($canManage&&!$role['is_system']):?><a class="button secondary" href="/admin/roles-permissions.php?edit_role=<?=h(rawurlencode((string)$role['public_id']))?>">Edit</a><?php endif?></td></tr><?php endforeach?></tbody></table></div></section>
<?php if($canManage):?><section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">CUSTOM ROLE</span><h2><?=$editRole?'Edit custom role':'Create custom role'?></h2></div><?php if($editRole):?><a class="button secondary" href="/admin/roles-permissions.php">New role</a><?php endif?></div><form method="post" class="stack"><?=csrf_field()?><input type="hidden" name="op" value="save_role"><?php if($editRole):?><input type="hidden" name="public_id" value="<?=h((string)$editRole['public_id'])?>"><?php endif?><div class="adminAccountTwoCol"><label>Role name<input name="name" required maxlength="120" value="<?=h((string)($editRole['name']??''))?>" placeholder="Customer Success Admin"></label><label>Role key<input name="role_key" required maxlength="64" value="<?=h((string)($editRole['role_key']??''))?>" placeholder="customer_success_admin"></label></div><label>Description<textarea name="description" rows="2" maxlength="500"><?=h((string)($editRole['description']??''))?></textarea></label><label>Status<select name="status"><option value="active" <?=(!$editRole||$editRole['status']==='active')?'selected':''?>>Active</option><option value="archived" <?=($editRole&&$editRole['status']==='archived')?'selected':''?>>Archived</option></select></label><div class="adminWorkspaceGrid"><?php foreach($groups as $group=>$caps):?><article class="card"><h3><?=h($group)?></h3><?php foreach($caps as $cap=>$meta):<?php if($cap==='admin.roles.manage')continue;?><label><input type="checkbox" name="capabilities[]" value="<?=h($cap)?>" <?=in_array($cap,$editCaps,true)?'checked':''?>> <strong><?=h((string)$meta['label'])?></strong><span class="meta"><?=h((string)$meta['description'])?></span></label><?php endforeach?></article><?php endforeach?></div><label>Reason<textarea name="reason" required rows="2" maxlength="500" placeholder="Why is this role being created or changed?"></textarea></label><button><?=$editRole?'Save custom role':'Create custom role'?></button></form></section><?php endif?>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">SEPARATION OF DUTIES</span><h2>Governed-action approval policies</h2></div><?php if(!$canManage):?><span class="badge">VIEW ONLY</span><?php endif?></div><p>Approval counts are snapshotted onto each new action preview. Existing pending actions keep the policy that governed them when they were requested.</p><div class="tableWrap"><table><thead><tr><th>Action</th><th>Risk</th><th>Approvals</th><th>Distinct reviewer</th><th>Status</th><th>Policy</th></tr></thead><tbody><?php foreach($policies as $policy):?><tr><td><strong><?=h((string)$policy['name'])?></strong><div class="meta"><code><?=h((string)$policy['action_type'])?></code></div></td><td><?=h((string)$policy['risk_level'])?></td><td><?=h((string)$policy['required_approvals'])?></td><td><?=$policy['distinct_from_requester']?'Required':'Not required'?></td><td><?=h((string)$policy['status'])?></td><td><?php if($canManage):?><form method="post" class="stack"><?=csrf_field()?><input type="hidden" name="op" value="save_policy"><input type="hidden" name="policy_public_id" value="<?=h((string)$policy['public_id'])?>"><label>Risk<select name="risk_level"><?php foreach(['routine','elevated','high'] as $v):?><option value="<?=h($v)?>" <?=$policy['risk_level']===$v?'selected':''?>><?=h(ucfirst($v))?></option><?php endforeach?></select></label><label>Required approvals<input type="number" name="required_approvals" min="0" max="3" value="<?=h((string)$policy['required_approvals'])?>"></label><label><input type="checkbox" name="distinct_from_requester" value="1" <?=$policy['distinct_from_requester']?'checked':''?>> Reviewer must differ from requester</label><label>Status<select name="status"><option value="active" <?=$policy['status']==='active'?'selected':''?>>Active</option><option value="disabled" <?=$policy['status']==='disabled'?'selected':''?>>Disabled</option></select></label><label>Reason<input name="reason" required maxlength="500" placeholder="Policy-change reason"></label><button class="button secondary">Save policy</button></form><?php else:?>—<?php endif?></td></tr><?php endforeach?></tbody></table></div></section>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">SECURITY AUDIT</span><h2>Role, policy & approval history</h2></div></div><?php foreach($events as $event):?><div class="historyItem"><strong><?=h(ucwords(str_replace('_',' ',(string)$event['event_type'])))?></strong><div class="meta"><?=h((string)$event['created_at'])?> · <?=h((string)($event['actor_display_name']?:$event['actor_username']))?> · <?=h((string)$event['subject_type'])?><?=!empty($event['subject_public_id'])?' · '.h((string)$event['subject_public_id']):''?></div><p><?=h((string)$event['reason'])?></p></div><?php endforeach?><?php if(!$events):?><p class="empty">No V2.10 security audit events yet.</p><?php endif?></section>
</main></body></html>
