<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
if(PHP_SAPI!=='cli')header('Cache-Control: no-store, private');
$admin=require_admin($pdo);if(!admin_security_ready($pdo)){http_response_code(503);exit('Admin V2.50 Security & Compliance requires migration 078.');}
admin_access_assert_capability($pdo,$admin,'admin.security.view');
$canManage=admin_access_has_capability($pdo,$admin,'admin.security.manage');$canPrivacyView=admin_access_has_capability($pdo,$admin,'admin.privacy.view');$canPrivacyManage=admin_access_has_capability($pdo,$admin,'admin.privacy.manage');$canExport=admin_access_has_capability($pdo,$admin,'admin.security.export');$success='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();try{$op=(string)($_POST['op']??'');
    if($op==='case_create'){if(!$canManage)throw new RuntimeException('Your operator role cannot manage security cases.');admin_security_case_create($pdo,$admin,$_POST);$success='Security case opened.';}
    elseif($op==='case_update'){if(!$canManage)throw new RuntimeException('Your operator role cannot manage security cases.');admin_security_case_update($pdo,$admin,(string)($_POST['case_id']??''),$_POST);$success='Security case updated.';}
    elseif($op==='privacy_create'){if(!$canPrivacyManage)throw new RuntimeException('Your operator role cannot manage privacy requests.');admin_privacy_create($pdo,$admin,$_POST);$success='Privacy request created.';}
    elseif($op==='privacy_update'){if(!$canPrivacyManage)throw new RuntimeException('Your operator role cannot manage privacy requests.');admin_privacy_update($pdo,$admin,(string)($_POST['privacy_id']??''),$_POST);$success='Privacy request updated.';}
    else throw new RuntimeException('Unknown Security & Compliance operation.');
}catch(Throwable $e){$error=$e->getMessage();}}
$filters=admin_security_filters($_GET);$events=admin_security_events($pdo,$admin,$filters,300);$metrics=admin_security_metrics($pdo);$cases=admin_security_cases($pdo,'',150);$privacy=$canPrivacyView?admin_privacy_requests($pdo,'',150):[];$review=admin_security_permission_review($pdo);$operators=admin_access_admin_operators($pdo);$accounts=admin_ui_account_rows($pdo,[],150);$users=$pdo->query("SELECT id,public_id,username,display_name,email FROM users WHERE status<>'deleted' ORDER BY display_name,username,id LIMIT 300")->fetchAll()?:[];
$domains=[];$types=[];foreach($events as $e){$domains[(string)$e['source_domain']]=true;$types[(string)$e['event_type']]=true;}$domains=array_keys($domains);sort($domains);$types=array_keys($types);sort($types);
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Security & Compliance · Annotated Admin</title><link rel="stylesheet" href="/assets/css/app.css"></head><body><?=admin_ui_sidebar('security_compliance')?>
<main class="panel"><div class="pageTitle"><span class="eyebrow">ADMIN V2.50 · SECURITY, COMPLIANCE & ADMINISTRATIVE AUDIT CENTER</span><h1>Security & Compliance</h1><p>One permission-aware view across administrative audit evidence, security cases, privacy workflows and delegated access. Source ledgers remain authoritative.</p></div>
<?php if($success):?><div class="success"><?=h($success)?></div><?php endif?><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?>
<section class="adminAccountSummaryGrid">
<article class="card"><span class="meta">Audit events · 24h</span><strong><?=h((string)$metrics['events_24h'])?></strong></article>
<article class="card"><span class="meta">High sensitivity · 24h</span><strong><?=h((string)$metrics['high_events_24h'])?></strong></article>
<article class="card"><span class="meta">Open security cases</span><strong><?=h((string)$metrics['open_cases'])?></strong><small><?=h((string)$metrics['critical_cases'])?> critical</small></article>
<article class="card"><span class="meta">Open privacy requests</span><strong><?=h((string)$metrics['open_privacy'])?></strong><small><?=h((string)$metrics['overdue_privacy'])?> overdue</small></article>
<article class="card"><span class="meta">Audit exports · 30d</span><strong><?=h((string)$metrics['exports_30d'])?></strong></article>
<article class="card"><span class="meta">Permission-review flags</span><strong><?=h((string)$metrics['permission_issues'])?></strong></article>
</section>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">ADMINISTRATIVE AUDIT LEDGER</span><h2>Permission-aware event timeline</h2></div><?php if($canExport):?><div class="inlineActions"><a class="button secondary" href="/admin/security-export.php?<?=h(http_build_query(array_merge($filters,['format'=>'csv'])))?>">Export CSV</a><a class="button secondary" href="/admin/security-export.php?<?=h(http_build_query(array_merge($filters,['format'=>'json'])))?>">Export JSON</a></div><?php endif?></div>
<p class="meta">V2.50 extends the V2.10 append-only security audit. Restricted source-domain details are redacted unless this operator also has that domain’s view permission.</p>
<form method="get" class="adminFormGrid"><label>Search<input name="q" value="<?=h((string)($filters['q']??''))?>" placeholder="event, actor, account, correlation"></label><label>Domain<input name="domain" value="<?=h((string)($filters['domain']??''))?>" placeholder="security, support, finance..."></label><label>Event type<input name="event_type" value="<?=h((string)($filters['event_type']??''))?>"></label><label>Actor<input name="actor" value="<?=h((string)($filters['actor']??''))?>" placeholder="username or public id"></label><label>Account<input name="account" value="<?=h((string)($filters['account']??''))?>" placeholder="account id or name"></label><label>Sensitivity<select name="sensitivity"><option value="">All</option><?php foreach(['standard','restricted','high'] as $v):?><option value="<?=h($v)?>" <?=($filters['sensitivity']??'')===$v?'selected':''?>><?=h(ucfirst($v))?></option><?php endforeach?></select></label><label>From<input type="date" name="from" value="<?=h((string)($filters['from']??''))?>"></label><label>To<input type="date" name="to" value="<?=h((string)($filters['to']??''))?>"></label><div class="inlineActions"><button>Filter</button><a class="button secondary" href="/admin/security-compliance.php">Reset</a></div></form>
<div class="tableWrap"><table><thead><tr><th>Time</th><th>Actor</th><th>Domain</th><th>Event</th><th>Subject / account</th><th>Sensitivity</th><th>Evidence</th></tr></thead><tbody><?php foreach($events as $e):?><tr><td><?=h((string)$e['created_at'])?></td><td><strong><?=h((string)($e['actor_display_name']?:$e['actor_username']))?></strong><div class="meta">@<?=h((string)$e['actor_username'])?></div></td><td><?=h((string)$e['source_domain'])?></td><td><strong><?=h(ucwords(str_replace('_',' ',(string)$e['event_type'])))?></strong><div class="meta"><?=h((string)$e['subject_type'])?><?php if(!empty($e['correlation_id'])):?> · <code><?=h((string)$e['correlation_id'])?></code><?php endif?></div></td><td><?=h((string)($e['subject_public_id']?:'—'))?><?php if(!empty($e['account_public_id'])):?><div class="meta"><?=h((string)$e['account_name'])?> · <?=h((string)$e['account_public_id'])?></div><?php endif?></td><td><?=h((string)$e['sensitivity'])?></td><td><p><?=h((string)$e['reason'])?></p><?php if(!$e['source_allowed']):?><span class="badge">Source details redacted</span><?php elseif(!empty($e['before_json'])||!empty($e['after_json'])):?><details><summary>Before / after</summary><pre><?=h((string)json_encode(['before'=>$e['before_json_decoded']??null,'after'=>$e['after_json_decoded']??null],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES))?></pre></details><?php endif?></td></tr><?php endforeach?><?php if(!$events):?><tr><td colspan="7" class="empty">No audit events match these filters.</td></tr><?php endif?></tbody></table></div></section>
<section class="adminContentSplit"><article class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">SECURITY CASES</span><h2>Investigation workflow</h2></div></div>
<?php if($canManage):?><details><summary>+ Open security case</summary><form method="post" class="adminFormGrid"><?=csrf_field()?><input type="hidden" name="op" value="case_create"><label>Title<input name="title" maxlength="190" required></label><label>Severity<select name="severity"><?php foreach(['info','low','medium','high','critical'] as $v):?><option value="<?=h($v)?>" <?=$v==='medium'?'selected':''?>><?=h(ucfirst($v))?></option><?php endforeach?></select></label><label>Account<select name="account_id"><option value="">None</option><?php foreach($accounts as $a):?><option value="<?=h((string)$a['id'])?>"><?=h((string)$a['name'])?> · <?=h((string)$a['public_id'])?></option><?php endforeach?></select></label><label>Assignee<select name="assigned_user_id"><option value="">Unassigned</option><?php foreach($operators as $o):?><option value="<?=h((string)$o['id'])?>"><?=h((string)($o['display_name']?:$o['username']))?> · <?=h((string)($o['role_name']??$o['role_key']))?></option><?php endforeach?></select></label><label class="adminFormSpan">Description<textarea name="description" rows="3"></textarea></label><label class="adminFormSpan">Reason<input name="reason" required value="Open security investigation."></label><button>Open case</button></form></details><?php endif?>
<?php foreach($cases as $c):?><div class="historyItem"><strong><?=h((string)$c['title'])?></strong><div class="meta"><?=h(strtoupper((string)$c['severity']))?> · <?=h((string)$c['status'])?> · <?=h((string)$c['updated_at'])?><?=!empty($c['account_name'])?' · '.h((string)$c['account_name']):''?></div><?php if(!empty($c['description'])):?><p><?=h((string)$c['description'])?></p><?php endif?><?php if($canManage):?><form method="post" class="adminInlineForm"><?=csrf_field()?><input type="hidden" name="op" value="case_update"><input type="hidden" name="case_id" value="<?=h((string)$c['public_id'])?>"><select name="status"><?php foreach(['open','investigating','monitoring','resolved','dismissed'] as $v):?><option value="<?=h($v)?>" <?=$c['status']===$v?'selected':''?>><?=h(ucwords(str_replace('_',' ',$v)))?></option><?php endforeach?></select><select name="severity"><?php foreach(['info','low','medium','high','critical'] as $v):?><option value="<?=h($v)?>" <?=$c['severity']===$v?'selected':''?>><?=h(ucfirst($v))?></option><?php endforeach?></select><input name="reason" required placeholder="Update reason"><button class="button secondary">Update</button></form><?php endif?></div><?php endforeach?><?php if(!$cases):?><p class="empty">No security cases yet.</p><?php endif?></article>
<article class="card"><span class="eyebrow">PERMISSION REVIEW</span><h2>Delegated-access signals</h2><p class="meta">Flags are deterministic review prompts, not automatic findings. Roles and effective capabilities remain authoritative in Roles & Permissions.</p><?php foreach($review['issues'] as $i):?><div class="historyItem"><strong><?=h((string)($i['display_name']?:$i['username']))?></strong><div class="meta"><?=h((string)$i['role_name'])?> · <?=h(implode(', ',$i['risks']))?></div></div><?php endforeach?><?php if(!$review['issues']):?><p class="empty">No deterministic permission-review flags.</p><?php endif?><a class="button secondary" href="/admin/roles-permissions.php">Open Roles & Permissions</a></article></section>
<?php if($canPrivacyView):?><section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">PRIVACY & COMPLIANCE</span><h2>Data-rights and retention workflow</h2></div><span class="badge"><?=h((string)$metrics['overdue_privacy'])?> overdue</span></div>
<p class="meta">This workflow records requests and evidence. It does not silently delete, export, or mutate user data; underlying domain actions remain explicit and permission-bound.</p>
<?php if($canPrivacyManage):?><details><summary>+ Create privacy request</summary><form method="post" class="adminFormGrid"><?=csrf_field()?><input type="hidden" name="op" value="privacy_create"><label>Request type<select name="request_type"><?php foreach(['access','export','deletion','restriction','rectification','consent_review','retention_review'] as $v):?><option value="<?=h($v)?>"><?=h(ucwords(str_replace('_',' ',$v)))?></option><?php endforeach?></select></label><label>User<select name="subject_user_id"><option value="">None</option><?php foreach($users as $u):?><option value="<?=h((string)$u['id'])?>"><?=h((string)($u['display_name']?:$u['username']))?> · @<?=h((string)$u['username'])?></option><?php endforeach?></select></label><label>Account<select name="account_id"><option value="">None</option><?php foreach($accounts as $a):?><option value="<?=h((string)$a['id'])?>"><?=h((string)$a['name'])?> · <?=h((string)$a['public_id'])?></option><?php endforeach?></select></label><label>Assignee<select name="assigned_user_id"><option value="">Unassigned</option><?php foreach($operators as $o):?><option value="<?=h((string)$o['id'])?>"><?=h((string)($o['display_name']?:$o['username']))?></option><?php endforeach?></select></label><label>Reference<input name="request_reference" maxlength="190"></label><label>Due<input type="datetime-local" name="due_at"></label><label class="adminFormSpan">Request note<textarea name="request_note" rows="3"></textarea></label><label class="adminFormSpan">Reason<input name="reason" required value="Create governed privacy request."></label><button>Create request</button></form></details><?php endif?>
<div class="tableWrap"><table><thead><tr><th>Request</th><th>Subject</th><th>Status</th><th>Due</th><th>Assignee</th><th>Administration</th></tr></thead><tbody><?php foreach($privacy as $p):?><tr><td><strong><?=h(ucwords(str_replace('_',' ',(string)$p['request_type'])))?></strong><div class="meta"><?=h((string)$p['public_id'])?><?php if(!empty($p['request_reference'])):?> · <?=h((string)$p['request_reference'])?><?php endif?></div></td><td><?=h((string)($p['subject_display_name']?:$p['subject_username']?:$p['account_name']?:'—'))?></td><td><?=h((string)$p['status'])?></td><td><?=h((string)($p['due_at']?:'—'))?></td><td><?=h((string)($p['assigned_username']?:'Unassigned'))?></td><td><?php if($canPrivacyManage):?><form method="post" class="adminInlineForm"><?=csrf_field()?><input type="hidden" name="op" value="privacy_update"><input type="hidden" name="privacy_id" value="<?=h((string)$p['public_id'])?>"><select name="status"><?php foreach(['open','verifying','in_progress','blocked','completed','denied','cancelled'] as $v):?><option value="<?=h($v)?>" <?=$p['status']===$v?'selected':''?>><?=h(ucwords(str_replace('_',' ',$v)))?></option><?php endforeach?></select><input name="reason" required placeholder="Update reason"><button class="button secondary">Update</button></form><?php else:?><span class="meta">Read only</span><?php endif?></td></tr><?php endforeach?><?php if(!$privacy):?><tr><td colspan="6" class="empty">No privacy requests yet.</td></tr><?php endif?></tbody></table></div></section><?php endif?>
</main></body></html>