<?php
declare(strict_types=1);require dirname(__DIR__).'/app/bootstrap.php';$admin=require_admin($pdo);$success='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();$op=(string)($_POST['op']??'');try{
 if($op==='queue'){$source=(int)($_POST['source_id']??0);if(!$source)throw new RuntimeException('Source missing.');$pdo->prepare("INSERT INTO source_monitor_jobs(source_id,priority,status) SELECT ?,2,'queued' WHERE NOT EXISTS(SELECT 1 FROM source_monitor_jobs WHERE source_id=? AND status IN ('queued','processing'))")->execute([$source,$source]);$success='Source check queued.';}
 if($op==='queue_all'){$pdo->exec("INSERT INTO source_monitor_jobs(source_id,priority,status) SELECT s.id,4,'queued' FROM sources s WHERE s.monitoring_enabled=1 AND (s.next_check_at IS NULL OR s.next_check_at<=NOW()) AND NOT EXISTS(SELECT 1 FROM source_monitor_jobs j WHERE j.source_id=s.id AND j.status IN ('queued','processing'))");$success='Due sources queued.';}
 if($op==='toggle'){$id=(int)($_POST['source_id']??0);$pdo->prepare('UPDATE sources SET monitoring_enabled=1-monitoring_enabled WHERE id=?')->execute([$id]);$success='Monitoring preference updated.';}
}catch(Throwable $e){$error=$e->getMessage();}}
$sources=$pdo->query("SELECT s.id,s.public_id,s.title,s.domain,s.status,s.monitoring_enabled,s.last_checked_at,s.next_check_at,(SELECT COUNT(*) FROM source_watches sw WHERE sw.source_id=s.id) watch_count,(SELECT COUNT(*) FROM project_sources ps WHERE ps.source_id=s.id) project_count FROM sources s WHERE EXISTS(SELECT 1 FROM source_watches sw WHERE sw.source_id=s.id) OR EXISTS(SELECT 1 FROM project_sources ps WHERE ps.source_id=s.id) ORDER BY COALESCE(s.next_check_at,'2000-01-01') ASC LIMIT 200")->fetchAll();$jobs=$pdo->query("SELECT j.*,s.title,s.domain FROM source_monitor_jobs j JOIN sources s ON s.id=j.source_id ORDER BY FIELD(j.status,'processing','queued','failed','done'),j.created_at DESC LIMIT 60")->fetchAll();
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Source Monitor · Annotated Admin</title><link rel="stylesheet" href="/assets/css/app.css"></head><body><header class="topbar"><a class="brand" href="/admin/">Annotated Admin</a><nav><a href="/admin/ai.php">AI</a><a href="/admin/moderation.php">Moderation</a><a href="/admin/users.php">Users</a></nav></header><main class="layout"><section><div class="pageTitle"><span class="eyebrow">SOURCE INTEGRITY</span><h1>Source monitoring</h1><p>Checks public source URLs, creates immutable new Source Versions when content changes, and alerts people whose research depends on them.</p></div><?php if($success):?><div class="success"><?=h($success)?></div><?php endif?><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?><form method="post" class="inlineActions"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="op" value="queue_all"><button>Queue due sources</button></form><?php foreach($sources as $s):?><article class="card"><div class="meta"><?=h($s['domain'])?> · <?=h($s['status'])?> · <?=h((string)$s['watch_count'])?> watches · <?=h((string)$s['project_count'])?> projects</div><h3><a href="/source.php?id=<?=h($s['public_id'])?>"><?=h($s['title']?:$s['public_id'])?></a></h3><div class="meta">Last checked <?=h($s['last_checked_at']?:'never')?> · next <?=h($s['next_check_at']?:'not scheduled')?></div><div class="inlineActions"><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="op" value="queue"><input type="hidden" name="source_id" value="<?=h((string)$s['id'])?>"><button>Check now</button></form><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="op" value="toggle"><input type="hidden" name="source_id" value="<?=h((string)$s['id'])?>"><button class="button secondary"><?= $s['monitoring_enabled']?'Disable':'Enable'?> monitoring</button></form></div></article><?php endforeach?></section><aside><div class="card"><h3>Worker queue</h3><?php foreach($jobs as $j):?><div class="historyItem"><strong><?=h($j['title']?:$j['domain'])?></strong><div class="meta"><?=h($j['status'])?> · attempts <?=h((string)$j['attempts'])?></div><?php if($j['last_error']):?><div class="error"><?=h($j['last_error'])?></div><?php endif?></div><?php endforeach?><p class="meta">Run <code>php worker/source-monitor-worker.php</code> under cron or Supervisor.</p></div></aside></main></body></html>
