<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
$admin=require_admin($pdo);if(!admin_support_ready($pdo)){http_response_code(503);exit('Admin V2.20 Support Operations requires migration 075.');}
admin_access_assert_capability($pdo,$admin,'admin.support.view');$canManage=admin_access_has_capability($pdo,$admin,'admin.support.manage');$id=trim((string)($_GET['id']??$_POST['id']??''));if($id===''){http_response_code(400);exit('Support case ID is required.');}
$success='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();try{if(!$canManage)throw new RuntimeException('Your operator role cannot manage support cases.');$op=(string)($_POST['op']??'');admin_support_update($pdo,$admin,$id,$op,$_POST);$success='Support case updated.';}catch(Throwable $e){$error=$e->getMessage();}}
$case=admin_support_case($pdo,$id);if(!$case){http_response_code(404);exit('Support case not found.');}$cx=admin_support_customer_360($pdo,$case,$admin);$events=admin_support_events($pdo,(int)$case['id'],250);$links=$cx['links'];$timeline=$cx['timeline'];$ops=$cx['operations'];$user=$cx['user'];$members=$cx['members'];$operators=admin_support_admin_candidates($pdo);$duplicates=admin_support_duplicate_candidates($pdo,$case['account_id']!==null?(int)$case['account_id']:null,$case['user_id']!==null?(int)$case['user_id']:null,(string)$case['category'],(string)$case['title'],8);$duplicates=array_values(array_filter($duplicates,fn($x)=>$x['public_id']!==$case['public_id']));
$customerComms=array_values(array_filter($events,fn($e)=>$e['visibility']==='customer'));
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=h((string)$case['title'])?> · Support · Annotated Admin</title><link rel="stylesheet" href="/assets/css/app.css"></head><body><?=admin_ui_sidebar('support_case')?>
<main class="panel adminSupportCasePage"><div class="pageTitle"><span class="eyebrow">ADMIN V2.20 · SUPPORT CASE</span><h1><?=h((string)$case['title'])?></h1><p><code><?=h((string)$case['public_id'])?></code> · <?=h(ucwords(str_replace('_',' ',(string)$case['category'])))?> · Created <?=h((string)$case['created_at'])?> by @<?=h((string)$case['creator_username'])?></p></div>
<?php if($success):?><div class="success"><?=h($success)?></div><?php endif?><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?>
<div class="inlineActions"><a class="button secondary" href="/admin/support.php">← Support inbox</a><?php if($case['account_public_id']&&admin_access_has_capability($pdo,$admin,'admin.accounts.view')):?><a class="button secondary" href="/admin/account.php?id=<?=h(rawurlencode((string)$case['account_public_id']))?>">Account 360</a><?php endif?><?php if($case['account_public_id']&&admin_access_has_capability($pdo,$admin,'admin.actions.view')):?><a class="button secondary" href="/admin/action-center.php?account=<?=h(rawurlencode((string)$case['account_public_id']))?>">Governed actions</a><?php endif?></div>
<section class="adminAccountSummaryGrid"><article class="card"><span class="meta">Status</span><strong><?=h(ucwords(str_replace('_',' ',(string)$case['status'])))?></strong></article><article class="card"><span class="meta">Priority</span><strong><?=h(strtoupper((string)$case['priority']))?></strong></article><article class="card"><span class="meta">Owner</span><strong><?=h((string)($case['assigned_display_name']?:($case['assigned_username']?:'Unassigned')))?></strong></article><article class="card"><span class="meta">SLA due</span><strong><?=h((string)($case['sla_due_at']?:'—'))?></strong></article><article class="card"><span class="meta">Customer</span><strong><?=h((string)($case['customer_display_name']?:($case['customer_username']?:'—')))?></strong></article><article class="card"><span class="meta">Account</span><strong><?=h((string)($case['account_name']?:'—'))?></strong></article></section>
<?php if($canManage):?><section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">CASE CONTROL</span><h2>Ownership, state & escalation</h2></div></div><div class="adminWorkspaceGrid">
<form method="post" class="card stack"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($id)?>"><input type="hidden" name="op" value="assign"><h3>Assign</h3><select name="user_id" required><option value="">Select operator</option><?php foreach($operators as $op):?><option value="<?=h((string)$op['id'])?>" <?=((int)($case['assigned_user_id']??0)===(int)$op['id'])?'selected':''?>><?=h((string)($op['display_name']?:$op['username']))?></option><?php endforeach?></select><input name="reason" required maxlength="500" placeholder="Assignment reason"><button>Assign case</button></form>
<form method="post" class="card stack"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($id)?>"><input type="hidden" name="op" value="priority"><h3>Priority / SLA</h3><select name="priority"><?php foreach(['urgent','high','normal','low'] as $v):?><option value="<?=h($v)?>" <?=$case['priority']===$v?'selected':''?>><?=h(ucfirst($v))?></option><?php endforeach?></select><input name="reason" required maxlength="500" placeholder="Priority reason"><button>Update priority</button></form>
<form method="post" class="card stack"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($id)?>"><input type="hidden" name="op" value="status"><h3>Workflow state</h3><select name="status"><?php foreach(['open','assigned','waiting_customer','waiting_internal','escalated'] as $v):?><option value="<?=h($v)?>" <?=$case['status']===$v?'selected':''?>><?=h(ucwords(str_replace('_',' ',$v)))?></option><?php endforeach?></select><input name="reason" required maxlength="500" placeholder="Status reason"><button>Update status</button></form>
<form method="post" class="card stack"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($id)?>"><input type="hidden" name="op" value="escalate"><h3>Escalate</h3><select name="team"><option value="billing">Billing / Finance</option><option value="operations">Operations</option><option value="ai_models">AI & Models</option><option value="research_data">Research & Data</option><option value="trust">Trust & Moderation</option><option value="security">Security / Super Admin</option></select><input name="reason" required maxlength="500" placeholder="Escalation reason"><button>Escalate case</button></form>
</div></section>
<section class="adminAccountTwoCol"><article class="card"><span class="eyebrow">INTERNAL COLLABORATION</span><h2>Add internal note</h2><form method="post" class="stack"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($id)?>"><input type="hidden" name="op" value="note"><textarea name="body" required rows="4" maxlength="1000" placeholder="Investigation notes. @mention another operator if useful."></textarea><button>Add internal note</button></form></article><article class="card"><span class="eyebrow">CUSTOMER COMMUNICATION LOG</span><h2>Record customer-facing update</h2><form method="post" class="stack"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($id)?>"><input type="hidden" name="op" value="communication"><textarea name="body" required rows="4" maxlength="1000" placeholder="What was communicated to the customer?"></textarea><button>Record communication</button></form><p class="meta">This records communication evidence only; it does not send email or messages.</p></article></section>
<section class="adminAccountTwoCol"><article class="card"><span class="eyebrow">RESOLUTION</span><h2>Resolve or reopen</h2><?php if(!in_array($case['status'],['resolved','closed'],true)):?><form method="post" class="stack"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($id)?>"><input type="hidden" name="op" value="resolve"><textarea name="resolution_summary" required rows="3" maxlength="1000" placeholder="What resolved the customer issue?"></textarea><input name="reason" required maxlength="500" placeholder="Resolution reason / evidence"><button>Resolve case</button></form><?php else:?><p><?=h((string)($case['resolution_summary']?:'Resolved without summary.'))?></p><form method="post" class="inlineActions"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($id)?>"><input type="hidden" name="op" value="reopen"><input name="reason" required maxlength="500" placeholder="Why is this case reopening?"><button>Reopen case</button></form><?php endif?></article><article class="card"><span class="eyebrow">DUPLICATE DETECTION</span><h2>Similar active cases</h2><?php foreach($duplicates as $dup):?><div class="historyItem"><a href="/admin/support-case.php?id=<?=h(rawurlencode((string)$dup['public_id']))?>"><strong><?=h((string)$dup['title'])?></strong></a><div class="meta"><?=h((string)$dup['public_id'])?> · <?=h((string)$dup['status'])?> · <?=h((string)$dup['updated_at'])?></div><form method="post" class="inlineActions"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($id)?>"><input type="hidden" name="op" value="duplicate"><input type="hidden" name="duplicate_of" value="<?=h((string)$dup['public_id'])?>"><input name="reason" required maxlength="500" placeholder="Duplicate rationale"><button class="button secondary">Mark this case duplicate</button></form></div><?php endforeach?><?php if(!$duplicates):?><p class="empty">No exact active duplicate detected for this customer/category/title.</p><?php endif?></article></section>
<section class="card"><span class="eyebrow">RELATED RECORDS</span><h2>Case links</h2><form method="post" class="inlineActions"><?=csrf_field()?><input type="hidden" name="id" value="<?=h($id)?>"><input type="hidden" name="op" value="link"><select name="link_type"><option value="invoice">Invoice</option><option value="subscription">Subscription</option><option value="admin_action">Admin action</option><option value="alert">Operations alert</option><option value="promotion">Promotion</option><option value="research">Research object</option><option value="other">Other</option></select><input name="linked_public_id" required placeholder="Record identifier"><input name="label" maxlength="255" placeholder="Label"><input name="target_url" maxlength="500" placeholder="/admin/..."><input name="reason" required maxlength="500" placeholder="Why is this related?"><button>Link record</button></form><?php foreach($links as $link):?><div class="historyItem"><strong><?=h(ucwords(str_replace('_',' ',(string)$link['link_type'])))?> · <?=h((string)($link['label']?:$link['linked_public_id']))?></strong><div class="meta"><code><?=h((string)$link['linked_public_id'])?></code><?php if($link['target_url']):?> · <a href="<?=h((string)$link['target_url'])?>">Open</a><?php endif?></div></div><?php endforeach?></section><?php endif?>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">CUSTOMER 360</span><h2>Customer & commercial context</h2></div></div><?php if($user):?><div class="billingSubscriptionFacts"><div><span>User</span><strong><?=h((string)($user['display_name']?:$user['username']))?></strong><small>@<?=h((string)$user['username'])?></small></div><div><span>Email</span><strong><?=h((string)$user['email'])?></strong></div><div><span>User status</span><strong><?=h((string)$user['status'])?></strong></div><div><span>Joined</span><strong><?=h((string)$user['created_at'])?></strong></div></div><?php endif?>
<?php if($ops):$acct=$ops['account'];$stripe=$ops['stripe'];$benefits=$ops['benefits'];$overage=$ops['overage'];?><div class="billingSubscriptionFacts"><div><span>Account</span><strong><?=h((string)$acct['name'])?></strong><small><?=h((string)$acct['public_id'])?></small></div><div><span>Package</span><strong><?=h((string)$acct['package_name'])?></strong></div><div><span>Account status</span><strong><?=h((string)$acct['status'])?> · <?=h((string)$acct['subscription_status'])?></strong></div><div><span>Stripe customer</span><strong><?=h((string)($stripe['customer']['stripe_customer_id']??'—'))?></strong></div><div><span>Open ops alerts</span><strong><?=h((string)count($ops['alerts']??[]))?></strong></div><div><span>Governed actions</span><strong><?=h((string)count($ops['actions']??[]))?></strong></div><div><span>AI overage</span><strong><?=$overage?h(number_format(((int)($overage['unreported_micros']??0))/1000000,6)):'—'?></strong></div><div><span>Account benefits</span><strong><?=$benefits?h((string)count((array)($benefits['benefits']??[]))):'—'?></strong></div></div><?php endif?>
<?php if($members):?><h3>Account members</h3><div class="tableWrap"><table><thead><tr><th>User</th><th>Account role</th><th>Joined</th></tr></thead><tbody><?php foreach($members as $m):?><tr><td><?=h((string)$m['display_name'])?><div class="meta">@<?=h((string)$m['username'])?> · <?=h((string)$m['email'])?></div></td><td><?=h((string)$m['account_role'])?></td><td><?=h((string)$m['joined_at'])?></td></tr><?php endforeach?></tbody></table></div><?php endif?></section>
<section class="adminAccountTwoCol"><article class="card"><span class="eyebrow">CUSTOMER COMMUNICATIONS</span><h2>Communication history</h2><?php foreach($customerComms as $e):?><div class="historyItem"><strong><?=h((string)($e['actor_display_name']?:($e['actor_username']?:'System')))?></strong><div class="meta"><?=h((string)$e['created_at'])?></div><p><?=h((string)$e['body'])?></p></div><?php endforeach?><?php if(!$customerComms):?><p class="empty">No customer-facing communications have been logged.</p><?php endif?></article><article class="card"><span class="eyebrow">ESCALATION</span><h2>Current escalation</h2><?php if($case['escalation_team']):?><p><strong><?=h(ucwords(str_replace('_',' ',(string)$case['escalation_team'])))?></strong></p><p><?=h((string)$case['escalation_reason'])?></p><?php else:?><p class="empty">This case has not been escalated.</p><?php endif?></article></section>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">CASE + ACCOUNT TIMELINE</span><h2>Unified support history</h2></div><span class="badge"><?=h((string)count($timeline))?> events</span></div><p class="meta">Support events are merged chronologically with Account 360 source ledgers. The underlying billing, membership, AI, promotion, tax/invoice and Admin-action ledgers remain authoritative.</p><?php foreach($timeline as $e):?><div class="historyItem"><strong><?=h(ucwords(str_replace('_',' ',(string)$e['title'])))?></strong><div class="meta"><?=h((string)$e['created_at'])?> · <?=h((string)$e['source'])?><?=!empty($e['actor'])?' · @'.h((string)$e['actor']):''?><?=isset($e['visibility'])?' · '.h((string)$e['visibility']):''?></div><?php if(!empty($e['detail'])):?><p><?=h((string)$e['detail'])?></p><?php endif?></div><?php endforeach?></section>
</main></body></html>
