<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
$admin=require_admin($pdo);if(!admin_support_ready($pdo)){http_response_code(503);exit('Admin V2.20 Support Operations requires migration 075.');}
admin_access_assert_capability($pdo,$admin,'admin.support.view');$canManage=admin_access_has_capability($pdo,$admin,'admin.support.manage');$success='';$error='';$created=null;
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();try{
    if(!$canManage)throw new RuntimeException('Your operator role cannot manage support cases.');
    $op=(string)($_POST['op']??'');
    if($op==='create'){$created=admin_support_create($pdo,$admin,$_POST);$success='Support case created.';}
    elseif($op==='save_view'){admin_support_saved_view_save($pdo,$admin,(string)($_POST['view_name']??''),$_POST,!empty($_POST['is_default']));$success='Support view saved.';}
    elseif($op==='delete_view'){admin_support_saved_view_delete($pdo,$admin,(string)($_POST['view_id']??''));$success='Saved support view deleted.';}
    else throw new RuntimeException('Unknown Support Operations action.');
}catch(Throwable $e){$error=$e->getMessage();}}
$filters=admin_support_filters($_GET);$dashboard=admin_support_dashboard($pdo,$admin,$filters);$cases=$dashboard['cases'];$metrics=$dashboard['metrics'];$operators=$dashboard['operators'];$views=$dashboard['views'];$categories=$dashboard['categories'];$workload=$dashboard['workload'];$effective=$dashboard['filters'];
$accounts=admin_ui_account_rows($pdo,[],300);
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Support Operations · Annotated Admin</title><link rel="stylesheet" href="/assets/css/app.css"></head><body><?=admin_ui_sidebar('support')?>
<main class="panel adminSupportPage"><div class="pageTitle"><span class="eyebrow">ADMIN V2.20 · SUPPORT OPERATIONS</span><h1>Support inbox & customer service workspace</h1><p>Work customer cases from one queue with account context, SLA risk, ownership, communications, escalation and resolution history. Commercial and security source systems remain authoritative.</p></div>
<?php if($success):?><div class="success"><?=h($success)?><?php if($created):?> <a href="/admin/support-case.php?id=<?=h(rawurlencode((string)$created['public_id']))?>">Open <?=h((string)$created['public_id'])?></a><?php endif?></div><?php endif?><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?>
<section class="adminDashboardMetrics">
<a class="card adminMetric" href="/admin/support.php"><span>Open cases</span><strong><?=h(number_format((int)($metrics['open']??0)))?></strong></a>
<a class="card adminMetric" href="/admin/support.php?assigned=me"><span>My cases</span><strong><?=h(number_format((int)($metrics['mine']??0)))?></strong></a>
<a class="card adminMetric" href="/admin/support.php?assigned=unassigned"><span>Unassigned</span><strong><?=h(number_format((int)($metrics['unassigned']??0)))?></strong></a>
<a class="card adminMetric" href="/admin/support.php?sla_risk=1"><span>SLA risk</span><strong><?=h(number_format((int)($metrics['sla_risk']??0)))?></strong></a>
<a class="card adminMetric" href="/admin/support.php?status=escalated"><span>Escalated</span><strong><?=h(number_format((int)($metrics['escalated']??0)))?></strong></a>
<article class="card adminMetric"><span>Resolved · 7d</span><strong><?=h(number_format((int)($metrics['resolved_7d']??0)))?></strong></article>
<article class="card adminMetric"><span>Reopened · 7d</span><strong><?=h(number_format((int)($metrics['reopened_7d']??0)))?></strong></article>
<article class="card adminMetric"><span>Avg resolution · 30d</span><strong><?=$metrics['avg_resolution_minutes']===null?'—':h(number_format((int)$metrics['avg_resolution_minutes']).'m')?></strong></article>
</section>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">SUPPORT INBOX</span><h2>Case queue</h2></div><span class="badge"><?=h((string)count($cases))?> shown</span></div>
<form method="get" class="adminAccountFilters"><label>Search<input name="q" value="<?=h((string)($effective['q']??''))?>" placeholder="Case ID, title, account, username, email"></label><label>Status<select name="status"><option value="">All open + history</option><?php foreach(['open','assigned','waiting_customer','waiting_internal','escalated','resolved','closed'] as $v):?><option value="<?=h($v)?>" <?=($effective['status']??'')===$v?'selected':''?>><?=h(ucwords(str_replace('_',' ',$v)))?></option><?php endforeach?></select></label><label>Priority<select name="priority"><option value="">All</option><?php foreach(['urgent','high','normal','low'] as $v):?><option value="<?=h($v)?>" <?=($effective['priority']??'')===$v?'selected':''?>><?=h(ucfirst($v))?></option><?php endforeach?></select></label><label>Owner<select name="assigned"><option value="">Anyone</option><option value="me" <?=($effective['assigned']??'')==='me'?'selected':''?>>My cases</option><option value="unassigned" <?=($effective['assigned']??'')==='unassigned'?'selected':''?>>Unassigned</option><?php foreach($operators as $op):?><option value="<?=h((string)$op['id'])?>" <?=($effective['assigned']??'')===(string)$op['id']?'selected':''?>><?=h((string)($op['display_name']?:$op['username']))?></option><?php endforeach?></select></label><label>Category<input name="category" value="<?=h((string)($effective['category']??''))?>" placeholder="billing"></label><label>Escalation<select name="team"><option value="">Any team</option><?php foreach(['billing'=>'Billing / Finance','operations'=>'Operations','ai_models'=>'AI & Models','research_data'=>'Research & Data','trust'=>'Trust & Moderation','security'=>'Security / Super Admin'] as $k=>$label):?><option value="<?=h($k)?>" <?=($effective['team']??'')===$k?'selected':''?>><?=h($label)?></option><?php endforeach?></select></label><label><input type="checkbox" name="sla_risk" value="1" <?=!empty($effective['sla_risk'])?'checked':''?>> SLA risk ≤4h</label><button>Filter</button><a class="button secondary" href="/admin/support.php">Clear</a></form>
<?php if($canManage):?><details><summary>Save current view</summary><form method="post" class="inlineActions"><?=csrf_field()?><input type="hidden" name="op" value="save_view"><?php foreach($effective as $k=>$v):?><input type="hidden" name="<?=h((string)$k)?>" value="<?=h((string)$v)?>"><?php endforeach?><input name="view_name" required maxlength="120" placeholder="Billing escalations"><label><input type="checkbox" name="is_default" value="1"> Default</label><button>Save view</button></form></details><?php endif?>
<?php if($views):?><div class="inlineActions"><?php foreach($views as $view):$vf=[];try{$vf=json_decode((string)$view['filters_json'],true,512,JSON_THROW_ON_ERROR)?:[];}catch(Throwable $e){}?><a class="button secondary" href="/admin/support.php?<?=h(http_build_query($vf))?>"><?=h((string)$view['name'])?><?=$view['is_default']?' ★':''?></a><?php if($canManage):?><form method="post"><?=csrf_field()?><input type="hidden" name="op" value="delete_view"><input type="hidden" name="view_id" value="<?=h((string)$view['public_id'])?>"><button class="button secondary" aria-label="Delete saved view">×</button></form><?php endif?><?php endforeach?></div><?php endif?>
<div class="tableWrap"><table><thead><tr><th>Case</th><th>Customer</th><th>Priority</th><th>Status</th><th>Owner</th><th>SLA</th><th>Updated</th></tr></thead><tbody><?php foreach($cases as $case):$slaRisk=!in_array($case['status'],['resolved','closed'],true)&&!empty($case['sla_due_at'])&&strtotime((string)$case['sla_due_at'])<=time()+14400;?><tr><td><a href="/admin/support-case.php?id=<?=h(rawurlencode((string)$case['public_id']))?>"><strong><?=h((string)$case['title'])?></strong></a><div class="meta"><?=h((string)$case['public_id'])?> · <?=h((string)$case['category'])?></div></td><td><?=h((string)($case['account_name']?:($case['customer_display_name']?:($case['customer_username']?:'Unlinked'))))?><?php if($case['customer_email']):?><div class="meta"><?=h((string)$case['customer_email'])?></div><?php endif?></td><td><span class="badge"><?=h(strtoupper((string)$case['priority']))?></span></td><td><?=h(ucwords(str_replace('_',' ',(string)$case['status'])))?><?php if($case['duplicate_of_case_id']):?><div class="meta">Duplicate</div><?php endif?></td><td><?=h((string)($case['assigned_display_name']?:($case['assigned_username']?:'Unassigned')))?></td><td class="<?=$slaRisk?'dangerText':''?>"><?=h((string)($case['sla_due_at']?:'—'))?><?=$slaRisk?' · RISK':''?></td><td><?=h((string)$case['updated_at'])?></td></tr><?php endforeach?><?php if(!$cases):?><tr><td colspan="7" class="empty">No support cases match this view.</td></tr><?php endif?></tbody></table></div></section>
<?php if($canManage):?><section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">NEW CASE</span><h2>Create support case</h2></div></div><form method="post" class="stack"><?=csrf_field()?><input type="hidden" name="op" value="create"><div class="adminAccountTwoCol"><label>Account<select name="account_public_id"><option value="">Optional / resolve from user</option><?php foreach($accounts as $a):?><option value="<?=h((string)$a['public_id'])?>" <?=((string)($_GET['account']??'')===(string)$a['public_id'])?'selected':''?>><?=h((string)$a['name'])?> · <?=h((string)$a['public_id'])?></option><?php endforeach?></select></label><label>User<input name="user_identifier" placeholder="username, email or user ID"></label></div><label>Title<input name="title" required maxlength="255" value="<?=h((string)($_GET['new_title']??''))?>" placeholder="Customer cannot access billing portal"></label><div class="adminAccountTwoCol"><label>Category<input name="category" maxlength="80" value="<?=h((string)($_GET['category']??'general'))?>" placeholder="billing, access, ai_usage"></label><label>Priority<select name="priority"><option value="normal">Normal · 24h SLA</option><option value="high">High · 8h SLA</option><option value="urgent">Urgent · 4h SLA</option><option value="low">Low · 72h SLA</option></select></label></div><label>Assign to<select name="assigned_user_id"><option value="">Leave unassigned</option><?php foreach($operators as $op):?><option value="<?=h((string)$op['id'])?>"><?=h((string)($op['display_name']?:$op['username']))?></option><?php endforeach?></select></label><label>Internal description<textarea name="description" required rows="4" maxlength="1000" placeholder="What is the customer reporting, and what evidence do we have?"></textarea></label><button>Create support case</button></form></section><?php endif?>
<section class="adminAccountTwoCol"><article class="card"><span class="eyebrow">CATEGORY VOLUME</span><h2>Support mix</h2><?php foreach($categories as $row):?><div class="historyItem"><strong><?=h(ucwords(str_replace('_',' ',(string)$row['category'])))?></strong><div class="meta"><?=h((string)$row['open_total'])?> open · <?=h((string)$row['total'])?> total</div></div><?php endforeach?><?php if(!$categories):?><p class="empty">No case categories yet.</p><?php endif?></article><article class="card"><span class="eyebrow">WORKLOAD</span><h2>Operator load</h2><?php foreach($workload as $row):?><div class="historyItem"><strong><?=h((string)($row['display_name']?:$row['username']))?></strong><div class="meta"><?=h((string)$row['open_cases'])?> open · <?=h((string)$row['urgent_cases'])?> urgent</div></div><?php endforeach?><?php if(!$workload):?><p class="empty">No assigned open cases.</p><?php endif?></article></section>
</main></body></html>
