<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';$admin=require_admin($pdo);header('Cache-Control: private, no-store');header('Vary: Cookie');$health=release_environment_checks($pdo,$config);
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>System Health · Annotated Admin</title><meta name="robots" content="noindex,nofollow"><link rel="stylesheet" href="/assets/css/app.css"></head><body>
<header class="topbar"><a class="brand" href="/admin/">Annotated Admin</a><nav><a href="/admin/source-monitor.php">Sources</a><a href="/admin/moderation.php">Moderation</a><a href="/admin/users.php">Users</a></nav></header>
<main class="panel releaseHealth"><div class="pageTitle"><span class="eyebrow"><?=h($health['release'])?></span><h1>Production readiness</h1><p><?= $health['ready']?'Critical release checks pass.':'One or more critical release checks require attention.'?> <?=h((string)$health['warnings'])?> warning(s).</p></div>
<div class="releaseVerdict <?=$health['ready']?'ready':'blocked'?>"><strong><?=$health['ready']?'READY FOR V1 RC1 VALIDATION':'RELEASE BLOCKED'?></strong><span>App <?=h($health['version'])?> · Chrome <?=h((string)$health['extension_version'])?></span></div>
<h2>Environment & security</h2><div class="healthGrid"><?php foreach($health['checks'] as $c):?><article class="card healthCheck <?=$c['status']?>"><div class="caseHeader"><strong><?=h($c['label'])?></strong><span class="badge"><?=h(strtoupper($c['status']))?></span></div><p><?=h($c['detail'])?></p></article><?php endforeach?></div>
<h2>Worker health</h2><div class="healthGrid"><?php foreach($health['workers'] as $w):?><article class="card healthCheck <?=$w['status']==='success'?'pass':($w['status']==='failure'||$w['status']==='stale'?'warn':'')?>"><div class="caseHeader"><strong><?=h(ucwords(str_replace('_',' ',$w['name'])))?></strong><span class="badge"><?=h(strtoupper($w['status']))?></span></div><p class="meta">Last seen <?=h($w['last_seen_at']?:'never')?> · processed <?=h((string)$w['processed_total'])?> · failures <?=h((string)$w['failed_total'])?></p><?php if($w['last_message']):?><p><?=h($w['last_message'])?></p><?php endif?></article><?php endforeach?></div>
<h2>Queues</h2><div class="healthGrid"><?php foreach($health['queues'] as $name=>$q):?><article class="card"><strong><?=h(ucwords(str_replace('_',' ',$name)))?></strong><?php if(isset($q['error'])):?><p class="error">Queue unavailable.</p><?php else:?><p class="meta">Queued <?=h((string)$q['queued'])?> · processing <?=h((string)$q['processing'])?> · failed <?=h((string)$q['failed'])?> · blocked <?=h((string)$q['blocked'])?> · done <?=h((string)$q['done'])?></p><?php endif?></article><?php endforeach?></div>
<div class="card"><h2>Release procedure</h2><ol><li>Apply all migrations and refresh this page until critical checks pass.</li><li>Run every worker under cron/Supervisor and confirm heartbeats.</li><li>Run the complete PHP 8.1/8.3 CI matrix, MySQL 8 fresh-install gate, Phase 36 integrated journey, and V1 RC1 production-readiness contracts.</li><li>Back up database and private evidence storage before deployment.</li><li>Deploy the exact-main package; run <code>upgrade.php</code>; verify health again.</li></ol></div></main></body></html>