<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
$admin=require_admin($pdo);$success='';$error='';
if(!commercial_billing_ready($pdo)){http_response_code(503);exit('Tax & Invoice hardening requires migration 072.');}
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();try{
    $op=(string)($_POST['op']??'');
    if($op==='settings'){commercial_billing_save_settings($pdo,$admin,$_POST);$success='Tax and invoice policy saved for the current Stripe mode.';}
    elseif($op==='sync_subscription'){commercial_billing_sync_subscription_policy($pdo,$config,$admin,(string)($_POST['account_id']??''));$success='Billing profile and tax policy synchronized to the Stripe subscription.';}
    elseif($op==='reconcile_invoice'){commercial_billing_reconcile_invoice($pdo,$config,$admin,(string)($_POST['stripe_invoice_id']??''));$success='Invoice reconciled from Stripe.';}
    else throw new RuntimeException('Unknown tax and invoice action.');
}catch(Throwable $e){$error=$e->getMessage();}}
$mode=commercial_billing_mode($pdo);$settings=commercial_billing_settings($pdo,$mode);$metrics=commercial_billing_tax_summary($pdo,30);$evidence=commercial_billing_recent_evidence($pdo,100);$taxIds=commercial_billing_recent_tax_ids($pdo,100);
$accounts=$pdo->query("SELECT a.public_id,a.name,a.subscription_status,p.name package_name,bp.legal_name,bp.billing_email,bp.address_country,bp.tax_exempt,bp.last_stripe_sync_at,ss.stripe_subscription_id FROM accounts a JOIN subscription_packages p ON p.id=a.package_id LEFT JOIN account_billing_profiles bp ON bp.account_id=a.id LEFT JOIN stripe_subscriptions ss ON ss.id=(SELECT sx.id FROM stripe_subscriptions sx WHERE sx.account_id=a.id AND sx.mode=". $pdo->quote($mode) ." AND sx.status NOT IN ('canceled','incomplete_expired') ORDER BY sx.updated_at DESC,sx.id DESC LIMIT 1) WHERE a.status<>'closed' ORDER BY a.name,a.id")->fetchAll()?:[];
$money=fn(int $c)=>'$'.number_format($c/100,2);
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Tax & Invoices · Annotated Admin</title><link rel="stylesheet" href="/assets/css/app.css"></head><body><?=admin_ui_sidebar('tax_invoices')?>
<main class="panel adminTaxInvoicesPage"><div class="pageTitle"><span class="eyebrow">ADMIN V1.90</span><h1>Tax, invoices & commercial billing hardening</h1><p>Stripe calculates tax and executes invoice/payment state. Annotated controls billing policy, account billing profiles, invoice evidence, reconciliation, and audit for the active <?=h(strtoupper($mode))?> environment.</p></div>
<?php if($success):?><div class="success"><?=h($success)?></div><?php endif?><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?>
<section class="billingKpiGrid"><article class="card"><span class="meta">Tax recorded · 30d</span><strong><?=h($money((int)$metrics['tax_cents']))?></strong></article><article class="card"><span class="meta">Invoices · 30d</span><strong><?=h((string)$metrics['invoice_count'])?></strong></article><article class="card"><span class="meta">Automatic-tax invoices</span><strong><?=h((string)$metrics['automatic_tax_count'])?></strong></article><article class="card"><span class="meta">Accounts with observed tax IDs</span><strong><?=h((string)$metrics['tax_id_accounts'])?></strong></article><article class="card"><span class="meta">Finalized evidence drift</span><strong><?=h((string)$metrics['drift_count'])?></strong></article></section>
<section class="adminBillingGrid"><article class="card"><span class="eyebrow">POLICY</span><h2>Checkout & invoice defaults</h2><form method="post" class="stack"><?=csrf_field()?><input type="hidden" name="op" value="settings"><label><input type="checkbox" name="automatic_tax_enabled" value="1" <?=!empty($settings['automatic_tax_enabled'])?'checked':''?>> Enable Stripe automatic tax for new Checkout subscriptions</label><label><input type="checkbox" name="collect_billing_address" value="1" <?=!empty($settings['collect_billing_address'])?'checked':''?>> Require billing address in Checkout</label><label><input type="checkbox" name="collect_tax_ids" value="1" <?=!empty($settings['collect_tax_ids'])?'checked':''?>> Allow Stripe Checkout to collect customer tax IDs</label><label><input type="checkbox" name="sync_billing_profile_to_stripe" value="1" <?=!empty($settings['sync_billing_profile_to_stripe'])?'checked':''?>> Sync Annotated billing profiles to Stripe customers</label><label>Default invoice memo<textarea name="invoice_memo" rows="2" maxlength="500"><?=h((string)($settings['invoice_memo']??''))?></textarea></label><label>Default invoice footer<textarea name="invoice_footer" rows="3" maxlength="1000"><?=h((string)($settings['invoice_footer']??''))?></textarea></label><button>Save tax & invoice policy</button></form><p class="meta">Automatic tax is opt-in and mode-specific. Existing subscriptions are changed only through the explicit per-account sync below.</p></article>
<article class="card"><span class="eyebrow">INVOICE RECONCILIATION</span><h2>Refresh one Stripe invoice</h2><form method="post" class="stack"><?=csrf_field()?><input type="hidden" name="op" value="reconcile_invoice"><label>Stripe invoice ID<input name="stripe_invoice_id" required placeholder="in_…"></label><button class="button secondary">Reconcile invoice</button></form><p class="meta">Reconciliation refreshes Annotated's invoice row and evidence snapshot from Stripe. It does not modify a finalized Stripe invoice.</p></article></section>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">ACCOUNTS</span><h2>Billing profile & subscription tax policy</h2></div></div><div class="tableWrap"><table><thead><tr><th>Account</th><th>Package</th><th>Billing profile</th><th>Tax</th><th>Stripe subscription</th><th>Policy sync</th></tr></thead><tbody><?php foreach($accounts as $a):?><tr><td><a href="/admin/account.php?id=<?=h(rawurlencode((string)$a['public_id']))?>"><?=h((string)$a['name'])?></a><div class="meta"><?=h((string)$a['subscription_status'])?></div></td><td><?=h((string)$a['package_name'])?></td><td><?=h((string)($a['legal_name']?:'Not configured'))?><div class="meta"><?=h((string)($a['billing_email']?:'No billing email'))?><?=$a['address_country']?' · '.h((string)$a['address_country']):''?></div></td><td><?=h((string)($a['tax_exempt']?:'none'))?></td><td><code><?=h((string)($a['stripe_subscription_id']?:'—'))?></code></td><td><?php if($a['stripe_subscription_id']):?><form method="post"><?=csrf_field()?><input type="hidden" name="op" value="sync_subscription"><input type="hidden" name="account_id" value="<?=h((string)$a['public_id'])?>"><button class="button secondary">Sync current policy</button></form><?php else:?><span class="meta">No active Stripe subscription</span><?php endif?></td></tr><?php endforeach?></tbody></table></div></section>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">FINALIZED INVOICE EVIDENCE</span><h2>Financial snapshot integrity</h2></div><span class="badge"><?=h((string)count($evidence))?> recent</span></div><div class="tableWrap"><table><thead><tr><th>Invoice</th><th>Account</th><th>Finalized</th><th>Evidence SHA</th><th>Last event</th><th>Integrity</th></tr></thead><tbody><?php foreach($evidence as $e):?><tr><td><code><?=h((string)($e['invoice_number']?:$e['stripe_invoice_id']))?></code></td><td><?=h((string)$e['account_name'])?></td><td><?=h((string)($e['finalized_at']?:'Not finalized'))?></td><td><code><?=h(substr((string)$e['financial_snapshot_sha256'],0,16))?>…</code></td><td><?=h((string)($e['last_seen_event_type']?:'—'))?></td><td><?=$e['drift_detected']?'<strong>Review drift</strong>':'Verified'?></td></tr><?php endforeach?><?php if(!$evidence):?><tr><td colspan="6" class="empty">No invoice evidence captured yet.</td></tr><?php endif?></tbody></table></div></section>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">TAX IDs</span><h2>Observed customer tax-ID snapshots</h2></div></div><p class="meta">Annotated stores Stripe tax-ID object IDs, type, verification status, and only the final four characters of the value. Full tax-ID values are not copied into Annotated.</p><div class="tableWrap"><table><thead><tr><th>Account</th><th>Type</th><th>Last 4</th><th>Verification</th><th>Source invoice</th><th>Last seen</th></tr></thead><tbody><?php foreach($taxIds as $t):?><tr><td><?=h((string)$t['account_name'])?></td><td><?=h((string)($t['tax_id_type']?:'—'))?></td><td><?=h((string)($t['value_last4']?:'—'))?></td><td><?=h((string)($t['verification_status']?:'—'))?></td><td><code><?=h((string)($t['source_invoice_id']?:'—'))?></code></td><td><?=h((string)$t['last_seen_at'])?></td></tr><?php endforeach?><?php if(!$taxIds):?><tr><td colspan="6" class="empty">No customer tax IDs observed yet.</td></tr><?php endif?></tbody></table></div></section>
</main></body></html>
