<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
$admin=require_admin($pdo);$success='';$error='';
if(!ai_usage_ready($pdo)){http_response_code(503);exit('AI Usage Metering requires the latest database upgrade.');}
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();try{
    if((string)($_POST['action']??'')!=='adjust_tokens')throw new RuntimeException('Unknown usage action.');
    $account=(string)($_POST['account_id']??'');$delta=(int)($_POST['token_delta']??0);$reason=(string)($_POST['reason']??'');
    $updated=ai_usage_admin_adjust($pdo,$admin,$account,$delta,$reason);$success='Token adjustment recorded. Current remaining balance: '.($updated['remaining_tokens']===null?'uncapped':number_format((int)$updated['remaining_tokens'])).'.';
}catch(Throwable $e){$error=$e->getMessage();}}
$accounts=ai_usage_admin_accounts($pdo,250);$events=ai_usage_recent_events($pdo,100);$adjustments=ai_usage_recent_adjustments($pdo,100);
$totalUsed=0;$totalSystem=0;$totalAdmin=0;$capped=0;$exhausted=0;foreach($accounts as $a){$s=$a['usage'];$totalUsed+=(int)$s['used_tokens'];$totalSystem+=(int)$s['system_tokens'];$totalAdmin+=(int)$s['admin_tokens'];if($s['effective_allowance']!==null){$capped++;if((int)$s['remaining_tokens']<=0)$exhausted++;}}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AI Usage · Annotated Admin</title><link rel="stylesheet" href="/assets/css/app.css"></head><body>
<header class="topbar"><a class="brand" href="/admin/">Annotated Admin</a><nav><a href="/admin/users.php">Users</a><a href="/admin/packages.php">Packages</a><a class="active" href="/admin/usage.php">AI Usage</a><a href="/admin/ai.php">AI</a><a href="/home.php">Site</a></nav></header>
<main class="panel"><div class="pageTitle"><span class="eyebrow">USAGE & ENTITLEMENTS</span><h1>AI usage & token management</h1><p>Canonical provider usage is metered to commercial accounts. User-requested Pro runs consume the account allowance; administrator and internal-system runs remain visible but do not consume customer tokens.</p></div>
<?php if($success):?><div class="success"><?=h($success)?></div><?php endif?><?php if($error):?><div class="error"><?=h($error)?></div><?php endif?>
<div class="adminGrid"><div class="card"><div class="meta">Account tokens used</div><div class="bigNumber"><?=h(number_format($totalUsed))?></div></div><div class="card"><div class="meta">System tokens observed</div><div class="bigNumber"><?=h(number_format($totalSystem))?></div></div><div class="card"><div class="meta">Admin tokens observed</div><div class="bigNumber"><?=h(number_format($totalAdmin))?></div></div><div class="card"><div class="meta">Capped / exhausted</div><div class="bigNumber"><?=h((string)$capped)?> / <?=h((string)$exhausted)?></div></div></div>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">CURRENT PERIOD</span><h2>Account balances</h2></div></div><div class="tableWrap"><table><thead><tr><th>Account</th><th>Package</th><th>Period</th><th>Allowance</th><th>Used</th><th>Remaining</th><th>Adjustment</th></tr></thead><tbody>
<?php foreach($accounts as $a):$s=$a['usage'];?><tr><td><strong><?=h((string)($a['display_name']?:$a['name']))?></strong><?php if($a['username']):?><div class="meta">@<?=h((string)$a['username'])?></div><?php endif?><div class="meta"><?=h((string)$a['public_id'])?></div></td><td><?=h((string)$a['package_name'])?></td><td><?=h((string)$s['account']['period_start'])?> → <?=h((string)$s['account']['period_end'])?></td><td><?=$s['effective_allowance']===null?'Uncapped / not configured':h(number_format((int)$s['effective_allowance']))?><?php if((int)$s['adjustment_tokens']!==0):?><div class="meta">Base <?=h(number_format((int)($s['base_allowance']??0)))?> · adjustments <?=h(number_format((int)$s['adjustment_tokens']))?></div><?php endif?></td><td><?=h(number_format((int)$s['used_tokens']))?><?php if((int)$s['overage_tokens']>0):?><div class="meta"><?=h(number_format((int)$s['overage_tokens']))?> over allowance</div><?php endif?></td><td><?=$s['remaining_tokens']===null?'—':h(number_format((int)$s['remaining_tokens']))?></td><td><form method="post" class="adminPackageAssignForm"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="adjust_tokens"><input type="hidden" name="account_id" value="<?=h((string)$a['public_id'])?>"><input name="token_delta" type="number" step="1" required placeholder="+50000 or -50000"><input name="reason" maxlength="500" required placeholder="Reason"><button>Record</button></form></td></tr><?php endforeach?>
</tbody></table></div></section>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">IMMUTABLE LEDGER</span><h2>Recent metered runs</h2></div></div><div class="tableWrap"><table><thead><tr><th>When</th><th>Account / user</th><th>Task</th><th>Model</th><th>Class</th><th>Tokens</th><th>Cost estimate</th></tr></thead><tbody><?php foreach($events as $e):?><tr><td><?=h((string)$e['created_at'])?></td><td><?=h((string)($e['display_name']?:$e['account_name']?:'System'))?><?php if($e['username']):?><div class="meta">@<?=h((string)$e['username'])?></div><?php endif?></td><td><?=h((string)$e['task_type'])?></td><td><?=h((string)($e['model_name']?:'Unknown'))?><div class="meta"><?=h((string)($e['provider_label']?:''))?></div></td><td><?=h((string)$e['usage_class'])?><?=((int)$e['chargeable'])?' · charged':' · observed'?><div class="meta"><?=h((string)$e['token_source'])?></div></td><td><?=h(number_format((int)$e['total_tokens']))?><div class="meta"><?=h(number_format((int)$e['input_tokens']))?> in · <?=h(number_format((int)$e['output_tokens']))?> out</div></td><td><?=$e['estimated_cost_micros']===null?'—':h('$'.number_format(((int)$e['estimated_cost_micros'])/1000000,6))?></td></tr><?php endforeach?></tbody></table></div></section>
<section class="card"><div class="sectionHeadWeb"><div><span class="eyebrow">AUDIT</span><h2>Token adjustments</h2></div></div><div class="tableWrap"><table><thead><tr><th>When</th><th>Account</th><th>Delta</th><th>Admin</th><th>Reason</th><th>Period</th></tr></thead><tbody><?php foreach($adjustments as $x):?><tr><td><?=h((string)$x['created_at'])?></td><td><?=h((string)$x['account_name'])?></td><td><?=h(number_format((int)$x['token_delta']))?></td><td><?=h((string)($x['actor_username']?:'System'))?></td><td><?=h((string)$x['reason'])?></td><td><?=h((string)$x['period_start'])?> → <?=h((string)$x['period_end'])?></td></tr><?php endforeach?></tbody></table></div></section>
</main></body></html>
