<?php
declare(strict_types=1);require dirname(__DIR__).'/app/bootstrap.php';require_once dirname(__DIR__).'/app/oauth.php';
$state=(string)($_GET['state']??'');$code=(string)($_GET['code']??'');$provider=(string)($_SESSION['oauth_provider']??'');$intent=(string)($_SESSION['oauth_intent']??'login');$linkUserId=$intent==='link'?(int)($_SESSION['oauth_link_user_id']??0):0;
if($limit=rate_limit_page_message($pdo,'oauth-callback-ip',rate_limit_ip_subject(),60,600)){http_response_code(429);exit(h($limit));}
if(!$provider||!hash_equals((string)($_SESSION['oauth_state']??''),$state)||$code===''){http_response_code(400);exit('Invalid OAuth callback.');}
try{
 $p=oauth_config($config,$provider);
 if($intent==='link'){if(!$linkUserId||empty($_SESSION['user_id'])||(int)$_SESSION['user_id']!==$linkUserId)throw new RuntimeException('Account-linking session changed. Sign in again and retry.');}
 if($provider==='google'){$token=oauth_http('https://oauth2.googleapis.com/token',['post'=>['code'=>$code,'client_id'=>$p['client_id'],'client_secret'=>$p['client_secret'],'redirect_uri'=>$p['redirect_uri'],'grant_type'=>'authorization_code']]);$info=oauth_http('https://openidconnect.googleapis.com/v1/userinfo',['headers'=>['Authorization: Bearer '.$token['access_token']]]);$userId=oauth_finish_login($pdo,'google',(string)$info['sub'],$info['email']??null,$info['name']??'Google User',isset($info['email'])?strstr($info['email'],'@',true):'google_user',(bool)($info['email_verified']??false),$linkUserId?:null);}
 elseif($provider==='x'){$verifier=(string)($_SESSION['oauth_verifier']??'');if($verifier==='')throw new RuntimeException('Missing PKCE verifier.');$auth=base64_encode($p['client_id'].':'.$p['client_secret']);$token=oauth_http('https://api.x.com/2/oauth2/token',['headers'=>['Authorization: Basic '.$auth],'post'=>['code'=>$code,'grant_type'=>'authorization_code','redirect_uri'=>$p['redirect_uri'],'code_verifier'=>$verifier]]);$me=oauth_http('https://api.x.com/2/users/me?user.fields=profile_image_url,name,username',['headers'=>['Authorization: Bearer '.$token['access_token']]]);$info=$me['data']??[];$userId=oauth_finish_login($pdo,'x',(string)($info['id']??''),null,$info['name']??'X User',$info['username']??'x_user',false,$linkUserId?:null);}
 else throw new RuntimeException('Unsupported OAuth provider.');
 session_regenerate_id(true);$_SESSION['user_id']=$userId;$_SESSION['rotated_at']=time();$_SESSION['last_activity']=time();$dest=post_login_destination();unset($_SESSION['oauth_state'],$_SESSION['oauth_provider'],$_SESSION['oauth_verifier'],$_SESSION['oauth_intent'],$_SESSION['oauth_link_user_id']);header('Location:'.$dest);exit;
}catch(Throwable $e){error_log('Annotated OAuth failure: '.$e->getMessage());unset($_SESSION['oauth_state'],$_SESSION['oauth_provider'],$_SESSION['oauth_verifier'],$_SESSION['oauth_intent'],$_SESSION['oauth_link_user_id']);http_response_code(502);echo 'OAuth sign-in failed. Please retry from Annotated.';}
