<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';require_once dirname(__DIR__).'/app/oauth.php';
$state=(string)($_GET['state']??'');$code=(string)($_GET['code']??'');$provider=(string)($_SESSION['oauth_provider']??'');$intent=(string)($_SESSION['oauth_intent']??'login');$linkUserId=$intent==='link'?(int)($_SESSION['oauth_link_user_id']??0):0;$issued=(int)($_SESSION['oauth_issued_at']??0);$verifier=(string)($_SESSION['oauth_verifier']??'');
if($limit=rate_limit_page_message($pdo,'oauth-callback-ip',rate_limit_ip_subject(),60,600)){http_response_code(429);exit(h($limit));}
$validProvider=in_array($provider,['google','x'],true);$fresh=$issued>0&&$issued>=time()-600;
if(!$validProvider||!$fresh||$state===''||strlen($state)>200||!hash_equals((string)($_SESSION['oauth_state']??''),$state)||$code===''){http_response_code(400);exit('Invalid or expired OAuth callback. Start sign-in again from Annotated.');}
if($intent==='link'&&(!$linkUserId||empty($_SESSION['user_id'])||(int)$_SESSION['user_id']!==$linkUserId)){http_response_code(400);exit('Account-linking session changed. Sign in again and retry.');}
unset($_SESSION['oauth_state'],$_SESSION['oauth_provider'],$_SESSION['oauth_verifier'],$_SESSION['oauth_intent'],$_SESSION['oauth_link_user_id'],$_SESSION['oauth_issued_at']);
try{
 $p=oauth_config($config,$provider);
 if($provider==='google'){$token=oauth_http('https://oauth2.googleapis.com/token',['post'=>['code'=>$code,'client_id'=>$p['client_id'],'client_secret'=>$p['client_secret'],'redirect_uri'=>$p['redirect_uri'],'grant_type'=>'authorization_code']]);$info=oauth_http('https://openidconnect.googleapis.com/v1/userinfo',['headers'=>['Authorization: Bearer '.$token['access_token']]]);$userId=oauth_finish_login($pdo,'google',(string)$info['sub'],$info['email']??null,$info['name']??'Google User',isset($info['email'])?strstr($info['email'],'@',true):'google_user',(bool)($info['email_verified']??false),$linkUserId?:null);}
 elseif($provider==='x'){if($verifier==='')throw new RuntimeException('Missing PKCE verifier.');$auth=base64_encode($p['client_id'].':'.$p['client_secret']);$token=oauth_http('https://api.x.com/2/oauth2/token',['headers'=>['Authorization: Basic '.$auth],'post'=>['code'=>$code,'grant_type'=>'authorization_code','redirect_uri'=>$p['redirect_uri'],'code_verifier'=>$verifier]]);$me=oauth_http('https://api.x.com/2/users/me?user.fields=profile_image_url,name,username',['headers'=>['Authorization: Bearer '.$token['access_token']]]);$info=$me['data']??[];$userId=oauth_finish_login($pdo,'x',(string)($info['id']??''),null,$info['name']??'X User',$info['username']??'x_user',false,$linkUserId?:null);}
 else throw new RuntimeException('Unsupported OAuth provider.');
 session_regenerate_id(true);$_SESSION['user_id']=$userId;$_SESSION['rotated_at']=time();$_SESSION['last_activity']=time();$_SESSION['auth_time']=time();$dest=$intent==='link'?post_login_destination():onboarding_post_login_destination($pdo,$userId);header('Location:'.$dest);exit;
}catch(Throwable $e){error_log('Annotated OAuth failure: '.$e->getMessage());http_response_code(502);?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sign-in problem · Annotated</title><link rel="stylesheet" href="/assets/css/app.css"></head><body><main class="panel narrow"><span class="eyebrow">SIGN-IN RECOVERY</span><h1>That sign-in did not finish</h1><p>Annotated did not connect the provider account. No provider access token was stored.</p><div class="inlineActions"><a class="button" href="/login.php">Try sign-in again</a><?php if($intent==='link'):?><a class="button secondary" href="/connected-accounts.php">Connected accounts</a><?php endif?></div></main></body></html><?php }