<?php
declare(strict_types=1);if(PHP_SAPI!=='cli'){http_response_code(404);exit;}require dirname(__DIR__).'/app/bootstrap.php';require_once dirname(__DIR__).'/app/ai.php';release_worker_heartbeat($pdo,'ai','starting','Worker invocation started.');$releaseProcessed=0;$releaseFailed=0;$limit=max(1,min(20,(int)($argv[1]??5)));
for($n=0;$n<$limit;$n++){
 $run=null;$job=job_claim($pdo,'ai_jobs',"SELECT * FROM ai_jobs WHERE status='queued' AND available_at<=NOW() ORDER BY priority ASC,available_at ASC,created_at ASC LIMIT 1",[],1800);if(!$job)break;$id=(int)$job['id'];$token=(string)$job['claim_token'];
 try{$model=(int)($job['model_id']?:0);if(!$model)$model=ai_setting_model_id($pdo,task_route((string)$job['task_type']));if(!$model)throw new RuntimeException('No AI model configured for task.');$user=null;if($job['requested_by_user_id']){$q=$pdo->prepare('SELECT id,public_id,username,display_name,email,role FROM users WHERE id=?');$q->execute([$job['requested_by_user_id']]);$user=$q->fetch()?:null;}[$system,$prompt,$refs,$scopeType,$scopePublic]=build_task($pdo,$job);$initiated=$user?(($user['role']??'')==='admin'?'admin':'pro'):'system';job_claim_renew($pdo,'ai_jobs',$id,$token,1800);$run=ai_run($pdo,$config,$user,$initiated,(string)$job['task_type'],$model,$system,$prompt,$refs,$scopeType,$scopePublic);job_claim_complete($pdo,'ai_jobs',$id,$token);$releaseProcessed++;echo "ai job {$job['id']} done\n";}catch(LostJobClaim $e){if($run&&isset($run['public_id'])){$q=$pdo->prepare("UPDATE ai_runs SET status='failed',error_text='Discarded because worker lease expired before commit.',completed_at=NOW() WHERE public_id=?");$q->execute([$run['public_id']]);}$releaseFailed++;fwrite(STDERR,"ai job {$job['id']}: lease lost; stale result discarded\n");}catch(Throwable $e){try{job_claim_retry_or_fail($pdo,'ai_jobs',$id,$token,substr($e->getMessage(),0,1000),(int)$job['attempts'],3,120);}catch(LostJobClaim $lost){}$releaseFailed++;fwrite(STDERR,"ai job {$job['id']}: {$e->getMessage()}\n");}
}
release_worker_heartbeat($pdo,'ai',$releaseFailed?'failure':'success',$releaseFailed?("$releaseFailed AI job(s) failed; $releaseProcessed completed."):("$releaseProcessed AI job(s) completed."),$releaseProcessed);
function task_route(string $t): string {return match(true){str_starts_with($t,'moderation_')=>'moderation',$t==='source_change_summary'=>'source_monitor',str_starts_with($t,'research_')=>'research',$t==='transcript_cleanup'=>'transcript_cleanup',default=>'admin'};}
function build_task(PDO $pdo,array $job): array {
 $type=(string)$job['task_type'];$obj=(string)$job['object_public_id'];
 if($type==='source_change_summary'){$id=(int)$obj;$q=$pdo->prepare('SELECT e.*,s.public_id source_public_id,s.title,s.canonical_url,p.extracted_text old_text,n.extracted_text new_text FROM source_change_events e JOIN sources s ON s.id=e.source_id LEFT JOIN source_versions p ON p.id=e.previous_version_id JOIN source_versions n ON n.id=e.new_version_id WHERE e.id=?');$q->execute([$id]);$r=$q->fetch();if(!$r)throw new RuntimeException('Source change event missing.');$system='You are Annotated source-integrity intelligence. Summarize only observable changes. Do not infer motives or truth. Flag whether research evidence may need human review.';$prompt="Source: {$r['title']}\nURL: {$r['canonical_url']}\nDeterministic change type: {$r['change_type']}\nTarget changed: {$r['target_changed']}\nExisting diff summary: {$r['diff_summary']}\n\nPREVIOUS VERSION:\n".mb_substr((string)$r['old_text'],0,14000)."\n\nCURRENT VERSION:\n".mb_substr((string)$r['new_text'],0,14000)."\n\nReturn: concise change summary; likely affected evidence; recommended human review steps.";return [$system,$prompt,[['type'=>'source','id'=>$r['source_public_id']],['type'=>'source_change_event','id'=>$obj]],'source',$r['source_public_id']];}
 if($type==='moderation_rights_triage'){$q=$pdo->prepare('SELECT rc.public_id,rc.claim_type,rc.description,a.public_id annotation_public_id,a.text_commentary,c.selected_text,s.canonical_url FROM rights_claims rc JOIN annotations a ON a.id=rc.annotation_id JOIN captures c ON c.id=a.capture_id JOIN sources s ON s.id=a.source_id WHERE rc.public_id=?');$q->execute([$obj]);$r=$q->fetch();if(!$r)throw new RuntimeException('Rights claim missing.');$system='You assist a human moderation team with triage. Do not make legal conclusions. Do not decide fair use, copyright ownership, privacy liability, or whether content must be removed. Summarize the concern, identify missing facts, and suggest neutral review steps.';$prompt="Claim type: {$r['claim_type']}\nClaim description (claimant identity removed): {$r['description']}\nAnnotation commentary: {$r['text_commentary']}\nCaptured material: ".mb_substr((string)$r['selected_text'],0,6000)."\nOriginal source: {$r['canonical_url']}\n\nProduce a neutral triage memo for a human administrator.";return [$system,$prompt,[['type'=>'rights_claim','id'=>$obj],['type'=>'annotation','id'=>$r['annotation_public_id']]],'rights_claim',$obj];}
 if($type==='moderation_report_triage'){$q=$pdo->prepare('SELECT * FROM moderation_reports WHERE public_id=?');$q->execute([$obj]);$r=$q->fetch();if(!$r)throw new RuntimeException('Moderation report missing.');$system='You assist a human content moderation team. Your output is advisory. Do not take action or make final policy determinations. Summarize the report and suggest what evidence a moderator should inspect.';$prompt="Object type: {$r['object_type']}\nObject id: {$r['object_public_id']}\nReason: {$r['reason']}\nDescription: {$r['description']}\n\nReturn a short triage memo.";return [$system,$prompt,[['type'=>'moderation_report','id'=>$obj]],'moderation_report',$obj];}
 if($type==='research_project_summary'){$q=$pdo->prepare('SELECT * FROM research_projects WHERE public_id=?');$q->execute([$obj]);$p=$q->fetch();if(!$p)throw new RuntimeException('Research project missing.');$ctx=ai_research_context($pdo,(int)$p['id']);$system='You are Annotated research intelligence. Work only from the provided provenance-backed context. Distinguish evidence from inference. Cite source and annotation IDs exactly in square brackets. State when evidence is insufficient.';$prompt="Project: {$p['title']}\nQuestion: Summarize the project, key evidence, disagreements, stale/changed source risks, and next research actions.\n\nCONTEXT:\n".$ctx['text'];return [$system,$prompt,$ctx['refs'],'research_project',$obj];}
 throw new RuntimeException('Unsupported AI job type: '.$type);
}
