<?php
declare(strict_types=1);if(PHP_SAPI!=='cli'){http_response_code(404);exit;}require dirname(__DIR__).'/app/bootstrap.php';require_once dirname(__DIR__).'/app/ai.php';
$limit=max(1,min(25,(int)($argv[1]??5)));
// Seed due watched/project sources without duplicating active jobs.
$pdo->exec("INSERT INTO source_monitor_jobs(source_id,priority,status) SELECT s.id,4,'queued' FROM sources s WHERE s.monitoring_enabled=1 AND (s.next_check_at IS NULL OR s.next_check_at<=NOW()) AND (EXISTS(SELECT 1 FROM source_watches sw WHERE sw.source_id=s.id) OR EXISTS(SELECT 1 FROM project_sources ps WHERE ps.source_id=s.id)) AND NOT EXISTS(SELECT 1 FROM source_monitor_jobs j WHERE j.source_id=s.id AND j.status IN ('queued','processing'))");
for($n=0;$n<$limit;$n++){
    $pdo->beginTransaction();$q=$pdo->query("SELECT j.*,s.public_id source_public_id,s.canonical_url,s.current_version_id,s.title source_title FROM source_monitor_jobs j JOIN sources s ON s.id=j.source_id WHERE j.status='queued' AND j.scheduled_at<=NOW() ORDER BY j.priority ASC,j.created_at ASC LIMIT 1 FOR UPDATE");$job=$q->fetch();if(!$job){$pdo->commit();break;}$pdo->prepare("UPDATE source_monitor_jobs SET status='processing',attempts=attempts+1,started_at=NOW() WHERE id=?")->execute([$job['id']]);$pdo->commit();
    try{
        $fetch=fetch_public_url((string)$job['canonical_url']);$status=(int)$fetch['status'];$currentId=(int)($job['current_version_id']??0);$current=null;if($currentId){$q=$pdo->prepare('SELECT * FROM source_versions WHERE id=?');$q->execute([$currentId]);$current=$q->fetch();}
        if($status<200||$status>=400){
            $q=$pdo->prepare('SELECT COALESCE(MAX(version_number),0)+1 FROM source_versions WHERE source_id=?');$q->execute([$job['source_id']]);$versionNo=(int)$q->fetchColumn();
            $q=$pdo->prepare('INSERT INTO source_versions(source_id,version_number,final_url,title,extracted_text,content_hash,target_content_hash,metadata_json) VALUES(?,?,?,?,NULL,NULL,NULL,?)');$q->execute([$job['source_id'],$versionNo,$fetch['url'],$job['source_title'],json_encode(['http_status'=>$status],JSON_UNESCAPED_SLASHES)]);$newId=(int)$pdo->lastInsertId();
            $pdo->prepare("UPDATE sources SET current_version_id=?,status='unavailable',last_checked_at=NOW(),next_check_at=DATE_ADD(NOW(),INTERVAL 12 HOUR) WHERE id=?")->execute([$newId,$job['source_id']]);$pdo->prepare("INSERT INTO source_change_events(source_id,previous_version_id,new_version_id,change_type,target_changed,diff_summary) VALUES(?,?,?,'unavailable',0,?)")->execute([$job['source_id'],$currentId?:null,$newId,'Source returned HTTP '.$status.'.']);notify_source_dependents($pdo,(int)$job['source_id'],'Source is currently unavailable.');
        }else{
            $parsed=html_to_research_text((string)$fetch['body']);$text=(string)$parsed['text'];$title=$parsed['title']?:$job['source_title'];$hash=hash('sha256',normalize_match_text($text));
            if($current && hash_equals((string)($current['content_hash']??''),$hash)){$pdo->prepare("UPDATE sources SET status='current',last_checked_at=NOW(),next_check_at=DATE_ADD(NOW(),INTERVAL 24 HOUR) WHERE id=?")->execute([$job['source_id']]);}
            else{
                $q=$pdo->prepare('SELECT COALESCE(MAX(version_number),0)+1 FROM source_versions WHERE source_id=?');$q->execute([$job['source_id']]);$versionNo=(int)$q->fetchColumn();$pdo->prepare('INSERT INTO source_versions(source_id,version_number,final_url,title,extracted_text,content_hash,target_content_hash,metadata_json) VALUES(?,?,?,?,?,?,?,?)')->execute([$job['source_id'],$versionNo,$fetch['url'],$title,$text,$hash,null,json_encode(['http_status'=>$status,'content_type'=>$fetch['content_type']],JSON_UNESCAPED_SLASHES)]);$newId=(int)$pdo->lastInsertId();
                $targetChanged=0;$q=$pdo->prepare("SELECT DISTINCT c.selected_text FROM captures c JOIN annotations a ON a.capture_id=c.id WHERE c.source_id=? AND a.status IN ('published','restricted') AND c.selected_text IS NOT NULL AND c.selected_text<>'' LIMIT 100");$q->execute([$job['source_id']]);$newNorm=normalize_match_text($text);foreach($q->fetchAll() as $r){$needle=normalize_match_text((string)$r['selected_text']);if($needle!==''&&!str_contains($newNorm,$needle)){$targetChanged=1;break;}}
                $type=$targetChanged?'edited':'updated';$oldText=(string)($current['extracted_text']??'');$diff=simple_text_diff($oldText,$text,120);$added=0;$removed=0;$sample=[];foreach($diff as $d){if($d['type']==='added')$added++;elseif($d['type']==='removed')$removed++;if($d['type']!=='same'&&count($sample)<4&&trim($d['text'])!=='')$sample[]=($d['type']==='added'?'+ ':'- ').mb_substr(trim($d['text']),0,180);}$summary="Detected $added added and $removed removed lines.".($sample?' '.implode(' | ',$sample):'');
                $pdo->prepare('UPDATE sources SET title=?,current_version_id=?,status=?,last_checked_at=NOW(),next_check_at=DATE_ADD(NOW(),INTERVAL 24 HOUR) WHERE id=?')->execute([$title,$newId,$type,$job['source_id']]);$pdo->prepare('INSERT INTO source_change_events(source_id,previous_version_id,new_version_id,change_type,target_changed,diff_summary) VALUES(?,?,?,?,?,?)')->execute([$job['source_id'],$currentId?:null,$newId,$type,$targetChanged,$summary]);$eventId=(int)$pdo->lastInsertId();$q=$pdo->prepare('SELECT id FROM source_change_events WHERE id=?');$q->execute([$eventId]);notify_source_dependents($pdo,(int)$job['source_id'],$targetChanged?'Source edited after an annotation was captured.':'A monitored source changed.');
                try{$model=ai_setting_model_id($pdo,'source_monitor');if($model)ai_queue_job($pdo,null,'source_change_summary',$model,'source_change_event',(string)$eventId,[],3);}catch(Throwable $e){}
            }
        }
        $pdo->prepare("UPDATE source_monitor_jobs SET status='done',completed_at=NOW(),last_error=NULL WHERE id=?")->execute([$job['id']]);echo "source job {$job['id']} done\n";
    }catch(Throwable $e){$pdo->prepare("UPDATE source_monitor_jobs SET status=IF(attempts>=3,'failed','queued'),scheduled_at=DATE_ADD(NOW(),INTERVAL 30 MINUTE),last_error=?,completed_at=IF(attempts>=3,NOW(),NULL) WHERE id=?")->execute([substr($e->getMessage(),0,1000),$job['id']]);fwrite(STDERR,"source job {$job['id']}: {$e->getMessage()}\n");}
}
function notify_source_dependents(PDO $pdo,int $sourceId,string $body): void {
    $q=$pdo->prepare('SELECT DISTINCT user_id FROM source_watches WHERE source_id=? UNION SELECT DISTINCT rp.owner_user_id FROM project_sources ps JOIN research_projects rp ON rp.id=ps.project_id WHERE ps.source_id=?');$q->execute([$sourceId,$sourceId]);$sourcePublic=(string)$pdo->query('SELECT public_id FROM sources WHERE id='.(int)$sourceId)->fetchColumn();foreach($q->fetchAll(PDO::FETCH_COLUMN) as $uid)notify_user($pdo,(int)$uid,null,'source_changed','source',$sourcePublic,$body);
}
