<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
require_once dirname(__DIR__).'/app/admin-agent.php';
require_once dirname(__DIR__).'/app/admin-agent-v290.php';
api_headers();$action=(string)($_GET['action']??'state');$input=$_SERVER['REQUEST_METHOD']==='POST'?(json_decode(file_get_contents('php://input'),true)?:[]):$_GET;
try{
    if($action==='state'){$admin=require_api_user($pdo);admin_agent_assert_admin($pdo,$admin);$context=null;if(!empty($input['current_url']))$context=admin_agent_page_context_from_url($pdo,$admin,(string)$input['current_url']);json_response(['ok'=>true,'data'=>['ready'=>admin_agent_ready($pdo),'threads'=>admin_agent_threads($pdo,$admin,50),'page_context'=>$context]]);}
    if($action==='messages'){$admin=require_api_user($pdo);admin_agent_assert_admin($pdo,$admin);$thread=trim((string)($input['thread']??''));$data=admin_agent_messages($pdo,$admin,$thread,!empty($input['before'])?(int)$input['before']:null,(int)($input['limit']??80));if(!$data)json_response(['ok'=>false,'error'=>['code'=>'NOT_FOUND','message'=>'Admin Agent thread not found.']],404);$meta=admin_agent_v290_message_meta($pdo,$admin,$thread,array_map(fn($m)=>(int)($m['id']??0),(array)($data['messages']??[])));foreach($data['messages'] as &$message){$mid=(int)($message['id']??0);$message['admin_evidence']=$meta[$mid]['admin_evidence']??[];$message['admin_plans']=$meta[$mid]['admin_plans']??[];}unset($message);json_response(['ok'=>true,'data'=>$data]);}
    if($action==='brief'){$admin=require_api_user($pdo);admin_agent_assert_admin($pdo,$admin);json_response(['ok'=>true,'data'=>['signals'=>admin_agent_v290_proactive_brief($pdo,$admin)]]);}
    if($action==='plan-step'){$admin=require_api_mutation_auth($pdo);admin_agent_assert_admin($pdo,$admin);rate_limit_api_or_429($pdo,'admin-agent-plan-step','user:'.$admin['id'],240,3600);$plan=admin_agent_v290_plan_step($pdo,$admin,trim((string)($input['thread']??'')),trim((string)($input['plan_public_id']??'')),trim((string)($input['step_id']??'')),trim((string)($input['status']??'')));json_response(['ok'=>true,'data'=>['plan'=>$plan]]);}
    if($action==='new'){$admin=require_api_mutation_auth($pdo);admin_agent_assert_admin($pdo,$admin);rate_limit_api_or_429($pdo,'admin-agent-new','user:'.$admin['id'],60,3600);$thread=admin_agent_thread_create($pdo,$admin);json_response(['ok'=>true,'data'=>['thread'=>$thread]],201);}
    if($action==='send'){$admin=require_api_mutation_auth($pdo);admin_agent_assert_admin($pdo,$admin);$pageContext=is_array($input['page_context']??null)?$input['page_context']:[];$thread=trim((string)($input['thread']??''));$prompt=(string)($input['prompt']??'');$data=admin_agent_send($pdo,$config,$admin,$thread,$prompt,isset($input['client_message_id'])?trim((string)$input['client_message_id']):null,$pageContext);if(empty($data['deduplicated'])&&!empty($data['assistant_message']['id'])){$extra=admin_agent_v290_enrich($pdo,$admin,$thread,(int)$data['assistant_message']['id'],$prompt,$pageContext);$data['assistant_message']['admin_evidence']=$extra['admin_evidence'];$data['assistant_message']['admin_plans']=$extra['admin_plans'];$data['proactive_brief']=$extra['proactive_brief'];}json_response(['ok'=>true,'data'=>$data],201);}
    json_response(['ok'=>false,'error'=>['code'=>'UNKNOWN_ACTION']],404);
}catch(InvalidArgumentException $e){json_response(['ok'=>false,'error'=>['code'=>'INVALID_INPUT','message'=>$e->getMessage()]],422);}
catch(RuntimeException $e){json_response(['ok'=>false,'error'=>['code'=>'ADMIN_AGENT_ERROR','message'=>$e->getMessage()]],403);}
catch(Throwable $e){$reference=substr(hash('sha256','admin-agent|'.$e->getMessage().'|'.microtime(true).'|'.random_bytes(8)),0,12);error_log('[Annotated admin-agent '.$reference.'] '.$e->getMessage());json_response(['ok'=>false,'error'=>['code'=>'ADMIN_AGENT_INTERNAL','message'=>'Admin Agent could not complete this request. Reference: '.$reference]],500);}
