<?php
require_once dirname(__DIR__).'/app/research-workspace.php';
if($action==='publish'){
    $u=require_api_mutation_auth($pdo);$pageUrl=trim((string)($input['url']??''));$url=source_identity_url($pageUrl,(string)($input['canonical_url']??''));$selected=trim((string)($input['selected_text']??''));$comment=trim((string)($input['commentary']??''));$type=(string)($input['capture_type']??'text');$start=isset($input['start_seconds'])?(float)$input['start_seconds']:null;$end=isset($input['end_seconds'])?(float)$input['end_seconds']:null;
    if(!filter_var($url,FILTER_VALIDATE_URL))json_response(['ok'=>false,'error'=>['code'=>'INVALID_URL']],422);
    if(!in_array($type,['text','video_clip','audio_clip','image_region','page_region'],true))json_response(['ok'=>false,'error'=>['code'=>'INVALID_CAPTURE_TYPE']],422);
    $isMedia=in_array($type,['video_clip','audio_clip'],true);$mediaKind=$type==='video_clip'?'video':($type==='audio_clip'?'audio':null);
    if($isMedia&&($start===null||$end===null||$start<0||$end<=$start||($end-$start)>90))json_response(['ok'=>false,'error'=>['code'=>'CLIP_TOO_LONG','message'=>'Clips must be more than 0 and no more than 90 seconds.']],422);
    if($isMedia&&trim((string)($input['media_upload_id']??''))==='')json_response(['ok'=>false,'error'=>['code'=>'MEDIA_UPLOAD_REQUIRED','message'=>'Record the selected tab clip before publishing.']],422);
    if($selected===''&&$comment===''&&empty($input['audio_commentary'])&&!$isMedia&&!in_array($type,['image_region','page_region'],true))json_response(['ok'=>false,'error'=>['code'=>'EMPTY_ANNOTATION']],422);
    $visibility=(string)($input['visibility']??'public');$teamId=null;if($visibility==='team'){$teamId=ext_team_id($pdo,(string)($input['team_id']??''),(int)$u['id']);if(!$teamId)json_response(['ok'=>false,'error'=>['code'=>'TEAM_FORBIDDEN','message'=>'Choose a team you belong to.']],403);}elseif(!in_array($visibility,['public','private'],true))$visibility='public';
    $provider=mb_substr(trim((string)($input['media_provider']??'')),0,64)?:null;$providerMediaId=mb_substr(trim((string)($input['provider_media_id']??'')),0,190)?:null;$mediaTitle=mb_substr(trim((string)($input['media_title']??'')),0,500)?:null;$mediaAuthor=mb_substr(trim((string)($input['media_author']??'')),0,500)?:null;$sourceMediaDuration=isset($input['source_media_duration_seconds'])?(float)$input['source_media_duration_seconds']:null;if($sourceMediaDuration!==null&&(!is_finite($sourceMediaDuration)||$sourceMediaDuration<0))$sourceMediaDuration=null;
    $mediaMeta=['provider'=>$provider,'provider_media_id'=>$providerMediaId,'title'=>$mediaTitle,'author'=>$mediaAuthor,'duration_seconds'=>$sourceMediaDuration];$mediaMeta=array_filter($mediaMeta,fn($v)=>$v!==null&&$v!=='');
    $contextPath=$targetPath=$audioPath=null;try{$contextPath=save_data_url_image((string)($input['screenshot_context']??''),'context',$config);$targetPath=save_data_url_image((string)($input['screenshot_target']??''),'target',$config);$audioPath=save_data_url_audio((string)($input['audio_commentary']??''),$config);}catch(Throwable $e){json_response(['ok'=>false,'error'=>['code'=>'CAPTURE_INVALID','message'=>$e->getMessage()]],422);}
    $canonical=canonicalize_url($url);$pageText=(string)($input['page_text']??'');$pageHash=hash('sha256',$pageText);$targetHash=hash('sha256',$selected);$upload=null;
    $pdo->beginTransaction();
    try{
        $source=ensure_source($pdo,$canonical,$input['title']??null,$input['media_type']??null);$sourceId=(int)$source['id'];$source=lock_source_row($pdo,$sourceId);$previousVersionId=(int)($source['current_version_id']??0);$versionId=$previousVersionId;$current=source_current_version($pdo,$source);$currentHash=$current['content_hash']??null;$wasUnavailable=((string)($source['status']??'')==='unavailable');$sourceChangeEventId=0;
        if(!$versionId||($pageText!==''&&$currentHash!==$pageHash)){
            $next=next_source_version_number($pdo,$sourceId);$versionMeta=['media_type'=>$input['media_type']??null,'capture_media'=>$mediaMeta,'page_url'=>$pageUrl,'identity_url'=>$canonical];
            $q=$pdo->prepare('INSERT INTO source_versions(source_id,version_number,final_url,title,extracted_text,content_hash,target_content_hash,screenshot_path,metadata_json) VALUES(?,?,?,?,?,?,?,?,?)');$q->execute([$sourceId,$next,$canonical,$input['title']??null,$pageText?:null,$pageHash,$targetHash,$contextPath,json_encode($versionMeta,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)]);$versionId=(int)$pdo->lastInsertId();
            $targetChanged=false;
            if($previousVersionId&&$pageText!==''){$q=$pdo->prepare('SELECT DISTINCT c.selected_text FROM annotations a JOIN captures c ON c.id=a.capture_id WHERE a.source_id=? AND a.source_version_id=? AND c.selected_text IS NOT NULL AND c.selected_text<>"" LIMIT 100');$q->execute([$sourceId,$previousVersionId]);foreach($q->fetchAll(PDO::FETCH_COLUMN) as $priorText){if(!str_contains(normalize_match_text($pageText),normalize_match_text((string)$priorText))){$targetChanged=true;break;}}}
            $status=$previousVersionId?($wasUnavailable?'current':($targetChanged?'edited':'updated')):'current';$pdo->prepare('UPDATE sources SET current_version_id=?,title=COALESCE(?,title),status=? WHERE id=?')->execute([$versionId,$input['title']??null,$status,$sourceId]);
            if($previousVersionId){$changeType=$wasUnavailable?'restored':($targetChanged?'edited':'updated');$pdo->prepare('INSERT INTO source_change_events(source_id,previous_version_id,new_version_id,change_type,target_changed,diff_summary) VALUES(?,?,?,?,?,?)')->execute([$sourceId,$previousVersionId,$versionId,$changeType,$targetChanged?1:0,$wasUnavailable?'Source became available again.':($targetChanged?'One or more previously annotated passages no longer match the current source.':'Source content changed; existing annotated passages were still found.')]);$sourceChangeEventId=(int)$pdo->lastInsertId();source_integrity_analyze_event($pdo,$sourceChangeEventId);source_integrity_notify_event($pdo,$sourceChangeEventId);live_event_emit_source_change($pdo,$sourceId,$sourceChangeEventId);}
        }
        if($isMedia)$upload=rich_capture_upload_for_publish($pdo,$config,(int)$u['id'],(string)$input['media_upload_id'],(string)$mediaKind);
        $q=$pdo->prepare('INSERT INTO captures(public_id,source_id,source_version_id,user_id,capture_type,selected_text,start_seconds,end_seconds,media_provider,provider_media_id,media_title,media_author,source_media_duration_seconds,media_metadata_json,screenshot_target_path,screenshot_context_path,selector_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$q->execute([ulid_like(),$sourceId,$versionId,$u['id'],$type,$selected?:null,$start,$end,$provider,$providerMediaId,$mediaTitle,$mediaAuthor,$sourceMediaDuration,$mediaMeta?json_encode($mediaMeta,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE):null,$targetPath,$contextPath,json_encode($input['selector']??null)]);$captureId=(int)$pdo->lastInsertId();
        $project=rich_capture_project_for_publish($pdo,(int)$u['id'],(string)($input['project_id']??''),$visibility,$teamId);
        $publicId=ulid_like();$pdo->prepare('INSERT INTO annotations(public_id,user_id,source_id,source_version_id,capture_id,text_commentary,audio_commentary_path,visibility,team_id,status) VALUES(?,?,?,?,?,?,?,?,?,"published")')->execute([$publicId,$u['id'],$sourceId,$versionId,$captureId,$comment?:null,$audioPath,$visibility,$teamId]);$annotationId=(int)$pdo->lastInsertId();
        if($visibility==='team'&&$teamId){$mq=$pdo->prepare('SELECT user_id FROM team_members WHERE team_id=? AND user_id<>?');$mq->execute([$teamId,$u['id']]);foreach($mq->fetchAll(PDO::FETCH_COLUMN) as $memberId)notification_create($pdo,(int)$memberId,(int)$u['id'],'team_annotation','annotation',$publicId,'A new annotation was published to your Team.',['category'=>'team','dedupe_key'=>'team-annotation:'.$annotationId.':'.$memberId,'group_key'=>'team:'.$teamId,'context'=>['source_public_id'=>$source['public_id'],'annotation_public_id'=>$publicId]]);}

        $transcriptionQueued=false;if($audioPath){$pdo->prepare('INSERT INTO annotation_transcripts(annotation_id,status) VALUES(?,"queued")')->execute([$annotationId]);$transcriptId=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO transcription_jobs(transcript_id,input_path) VALUES(?,?)')->execute([$transcriptId,$audioPath]);$transcriptionQueued=true;}
        if($isMedia&&$upload){$duration=$end-$start;$pdo->prepare('INSERT INTO media_derivatives(capture_id,media_type,duration_seconds,resolution_label,processing_status) VALUES(?,?,?,?,"queued")')->execute([$captureId,$mediaKind,$duration,$mediaKind==='video'?'240p':null]);$derivative=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO media_jobs(derivative_id,source_url,input_path,input_is_clip,start_seconds,end_seconds) VALUES(?,?,?,1,?,?)')->execute([$derivative,$canonical,$upload['storage_path'],$start,$end]);rich_capture_mark_consumed($pdo,(int)$upload['id'],(string)$upload['checksum']);}
        if($project){$pdo->prepare('INSERT IGNORE INTO project_annotations(project_id,annotation_id,added_by_user_id) VALUES(?,?,?)')->execute([$project['id'],$annotationId,$u['id']]);$pdo->prepare('INSERT IGNORE INTO project_sources(project_id,source_id,added_by_user_id) VALUES(?,?,?)')->execute([$project['id'],$sourceId,$u['id']]);}
        live_event_emit_for_annotation($pdo,$annotationId,'annotation');if($project)live_event_emit_research_add($pdo,(int)$project['id'],$annotationId,(int)$u['id']);
        $intelligenceQueued=annotation_intelligence_queue($pdo,$annotationId,(int)$u['id'],4);$workspaceQueued=$project&&research_workspace_ready($pdo)?research_workspace_queue($pdo,(int)$project['id'],4):false;
        if(function_exists('data_attribution_capture_object'))data_attribution_try_capture_object($pdo,(int)$u['id'],'annotation',$publicId);
        $pdo->commit();json_response(['ok'=>true,'data'=>['annotation_id'=>$publicId,'url'=>'/annotation.php?id='.$publicId,'media_queued'=>$isMedia,'transcription_queued'=>$transcriptionQueued,'research_added'=>(bool)$project,'intelligence_queued'=>$intelligenceQueued,'workspace_intelligence_queued'=>$workspaceQueued]],201);
    }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();foreach([$contextPath,$targetPath,$audioPath] as $stored){$abs=$stored?storage_path_to_absolute($config,(string)$stored):null;if($abs&&is_file($abs))@unlink($abs);}json_response(['ok'=>false,'error'=>['code'=>'PUBLISH_FAILED','message'=>$e->getMessage()?:'Unable to publish annotation.']],500);}
}

if($action==='transcript_edit'){
    $u=require_api_mutation_auth($pdo);$a=ext_annotation($pdo,(string)($input['annotation_id']??''),$u);if(!$a||((int)$a['user_id']!==(int)$u['id']&&$u['role']!=='admin'))json_response(['ok'=>false,'error'=>['code'=>'FORBIDDEN']],403);
    $text=trim((string)($input['text']??''));if(mb_strlen($text)>50000)json_response(['ok'=>false,'error'=>['code'=>'TRANSCRIPT_TOO_LONG']],422);
    $q=$pdo->prepare('UPDATE annotation_transcripts SET edited_text=?,updated_at=NOW() WHERE annotation_id=?');$q->execute([$text?:null,$a['id']]);$queued=annotation_intelligence_queue($pdo,(int)$a['id'],(int)$u['id'],3);json_response(['ok'=>true,'data'=>['updated'=>true,'intelligence_queued'=>$queued]]);
}
